### ISSUE TITLE
Error underline is being rendered over files not related to the error

### ISSUE THREAD

**Issue by maciekmm** [Microsoft/vscode-go#100]
Let's say you have unused import on line 6 in file `example.go`,
if you go to `main.go` and save it it will display you have unused import on that line in the main.go file.

image:
![](http://i.maciekmm.net/Screenshot_2015-11-25_21-48-21)

**Comment by lukehoban** [comment]
@maciekmm Are you running the latest version of the Go plugin?  This issue should have been fixed with https://github.com/Microsoft/vscode-go/issues/29.  If you are running latest, could you reopen with any additional details?
