### ISSUE TITLE
go install and go test on save without creating tasks

### ISSUE THREAD

**Issue by citizenrich** [Microsoft/vscode-go#1000]
Heyo,

I love the tool. I wonder if it's possible to do both go install and go test together on save, but without having to create a new task in each code dir. I'm mimicking the behavior of go-plus for Atom.

FWIW, in a teaching environment, I'd rather not impose task writing out of the box.

Rich

**Comment by ramya-rao-a** [comment]
Test on Save is already a feature, just set `go.testOnSave` to `true`

Install on save is a good feature as well. PRs are welcome :)

**Comment by ramya-rao-a** [comment]
The `Go: Install Current Package` command will be available in the next update
