### ISSUE TITLE
File links in output channel (detection seems occasionally broken)

### ISSUE THREAD

**Issue by coreds** [Microsoft/vscode-go#1002]
Filenames in output channels used to be clickable and one could open the target files and jump to line/column but doesn't work anymore in latest release 1.12.2 on Mac. 

E.g.
 
```javascript
let out = vscode.window.createOutputChannel('whatever')
out.appendLine ('ERROR: ... '+e+'\n')
```
Would have rendered to a clickable link like in:

```
ERROR: ... at /some/filenames/catalog.cds:47:11
```

Actually, this used to work in some past release. Stopped working in some later update. Worked again for a short time in 1.12.0 and gone again in 1.12.1 or .2. Looks like a pattern meanwhile.

**Comment by ramya-rao-a** [comment]
@coreds This doesn't look like it is specific to the Go extension.

Can you open an issue in the VS Code repo instead?

**Comment by coreds** [comment]
Yes this was a mistake, sorry. 
(was in vacation)
