### ISSUE TITLE
run test | debug test

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode-go#1003]
![image](https://cloud.githubusercontent.com/assets/863731/26193264/06c3d40a-3bb5-11e7-9174-7abfcaec7364.png)

The run `test | debug test` appearing when writing test is really annoying for me and can't figure out how to disable it?

Things like this distracts you too much from writing code

**Comment by goenning** [comment]
That is called CodeLens inside VSCode and it can be disabled with following settings.

```
go.enableCodeLens": {
  "references": false, //this is already false by default, but keep it if you want to make sure it's disabled
  "runtest": false
}
```

**Comment by gertcuykens** [comment]
A yes, thx! Much better :D Ps this feature should be off by default I think, this is more like a toggle feature you only use when you want to examine a other repo quickly.

**Comment by goenning** [comment]
I understand your point, by at least for me, this is a huge gain of productivity. I usually split screen between the test and the function under test and use these shortcuts to verify if it's working, i don't need to switch to terminal and neither run all the tests. Debug is insanely useful when I have no idea why it's not working and it's just a click away. But yeah, this is just my point of view, I believe it's more useful than annoying 😀

**Comment by gertcuykens** [comment]
Agree thats why maybe i think a toggle would be a good idea to turn it on or off in the view menu
![image](https://cloud.githubusercontent.com/assets/863731/26283736/e09deb64-3e2d-11e7-9e8a-6dd5addc7aa8.png)

**Comment by ramya-rao-a** [comment]
@gertcuykens

You can also turn codelens off for all languages by setting `editor.codeLens` to `false`

For granular control on codelens by the Go extension, you can use `go.enableCodeLens` like @goenning has suggested.

By default, we keep codelens on. Same goes for VS Code in general.
If there are codelens that may have perf impact (for eg: the references one), we keep them off by default.
