### ISSUE TITLE
Incorrect highlighting in import blocks

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode-go#1007]
![image](https://cloud.githubusercontent.com/assets/159209/26329002/1aee1e20-3efa-11e7-9089-1ba803812893.png)

Note the commented-out lines are not properly painted as gray.

vscode-go: 0.6.61
vscode: 1.12.2-mac

**Comment by ramya-rao-a** [comment]
Duplicate of #119

The latest Insiders has the fix. Can you give that a try?
