### ISSUE TITLE
No local variables are shown in debugging

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#101]
Not sure if bug or not implemented yet but I don't see any local variables in the debugging area. What I add to watches don't get picked up either.

**Comment by lukehoban** [comment]
@ahmetalpbalkan Do you still see this consistently?  Can you share what project you are working in and what you see when you follow the steps in https://github.com/Microsoft/vscode-go/issues/51#issuecomment-158703417 and https://github.com/Microsoft/vscode-go/issues/51#issuecomment-158854899.

**Comment by ahmetalpbalkan** [comment]
Hmm this started to work mysteriously now.
