### ISSUE TITLE
Debugger does not display values in array of struct on VARIABLES pane and debug: Evaluate command.

### ISSUE THREAD

**Issue by YoskeOkamoto2** [Microsoft/vscode-go#1010]
I would like to inspect variables in array of struct.
I know 'Add to Watch' works fine for this request. but this is not a convenient way.

Here is the sample I wrote.
```go
package main

import (
	"fmt"
)

// ItemStruct is item
type ItemStruct struct {
	Num1 int
	Num2 int
}

// OwnerStruct holds item list and pointer list
type OwnerStruct struct {
	ItemList        []ItemStruct
	ItemPointerList []*ItemStruct
}

func main() {
	// initialize part
	list := make([]ItemStruct, 0, 2)
	plist := make([]*ItemStruct, 0, 2)
	for i := 0; i < 2; i++ {
		item := ItemStruct{Num1: i, Num2: i + 1}
		list = append(list, item)
		plist = append(plist, &item)
	}
	owner := OwnerStruct{
		ItemList:        list,
		ItemPointerList: plist}

	// watch variable here on debugger
	fmt.Println(owner)
}
```

and the screenshot.
![image](https://cloud.githubusercontent.com/assets/7908644/26517870/181180ca-42dd-11e7-9201-2706595c8efc.png)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @yoskeoka 
And thanks for the sample code as well, I can repro this.

@roblourens Can this be done?

**Comment by roblourens** [comment]
Looking at the code, it's not obvious whether we can do it without evaluating all the variables like the watches window does. I'm not sure what other info we can get out of Delve.

**Comment by Yussak** [comment]
Hi, I am bumping this up because being able to see the content of the variables we are debugging is actually important :)

Thanks for taking the time to look into this!

**Comment by christian-boks** [comment]
Getting this fixed would be really nice. It is one of the small things that would make Go debugging support feel as complete as the Javascript debugging support. Which is just incredible.

**Comment by ramya-rao-a** [comment]
If anyone wants to take a stab at this, the place to get started is the `variablesRequest` method in the `goDebug.ts` file. For setup, please see the simple instructions in the [README for debugging](https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter)

**Comment by ramya-rao-a** [comment]
Nested content is now shown in the latest update (0.9.0) to the Go extension.
Huge thanks to @jhendrixMSFT who made this happen!
