### ISSUE TITLE
incorrect work with .editorconfig

### ISSUE THREAD

**Issue by vahpetr** [Microsoft/vscode-go#1011]
.editorconfig
```
root = true

[*]
indent_style = space
indent_size = 4
```

After saving, the spaces are converted to tabs

**Comment by daenney** [comment]
Do you happen to run `gofmt` as part of save? That would change it to tabs since that's how Go code is expected to be indented.

Your editorconfig should probably look like this instead, for Go:

```
root = true

[*]
indent_style = space
indent_size = 4

[*.go]
indent_style = tab
```

**Comment by vahpetr** [comment]
> Do you happen to run gofmt as part of save?
I use default configuration

I don't want to use tab indent style.
vscode-go must using global .editorconfig settings (4 space)

**Comment by daenney** [comment]
What are the settings you have enabled for vscode-go?
