### ISSUE TITLE
How does gofmt work?

### ISSUE THREAD

**Issue by xDShot** [Microsoft/vscode-go#1016]
I added _"go.formatTool": "gofmt"_ line into my settings. Then, in my project folder in my opened document I run _Format Document_ command in VS Code (didn't find separate command to run _gofmt_ on current file), but my document is still unchanged and unformatted.

What am I doing wrong?

**Comment by ramya-rao-a** [comment]
Can you also try setting `go.useDiffForFormatting` to `false` and try again ?
We use the `-d` diff flag while running the formatting tool to get the diff output and then apply the diff on the editor. The `-d` option doesn't work for some set ups. We aren't sure why.

**Comment by xDShot** [comment]
Still doesn't work.

**Comment by ramya-rao-a** [comment]
How about setting `go.formatTool` to `goreturns` or `goimports`?

**Comment by xDShot** [comment]
Closing. Turns out it was because of wrong golang installation.
