### ISSUE TITLE
nested maps in go

### ISSUE THREAD

**Issue by liberalakrep** [Microsoft/vscode-go#1019]
```
func main() {
    var data = map[string]map[string]string{}
    data["a"]["w"] = "x"
    data["b"]["w"] = "x"
    data["c"]["w"] = "x"
    fmt.Println(data)
}
```
In the VSCode-Go, there is no warning, But it must gives "panic: assignment to entry in nil map" (https://play.golang.org/p/QgCjdmTeoP)

Right way of running code :
```
func main() {
var data = map[string]map[string]string{
    "a": map[string]string{},
    "b": map[string]string{},
    "c": map[string]string{},
}

data["a"]["w"] = "x"
data["b"]["w"] = "x"
data["c"]["w"] = "x"
fmt.Println(data)
}
```

**Comment by ramya-rao-a** [comment]
The Go extension runs build, lint and vet and none of these give the error you are expecting.

@rakyll In the linked playground above, do you know what process needs to be run to get the expected error?

**Comment by liberalakrep** [comment]
I use vscode in osx. Please follow the steps on vscode-go.
- Run vscode
- Create main.go file in a new workspace
- Copy & Paste the following code
```
func main() {
    var data = map[string]map[string]string{}
    data["a"]["w"] = "x"
    data["b"]["w"] = "x"
    data["c"]["w"] = "x"
    fmt.Println(data)
}
```
- Finally save file.

When you saved file, vscode auto-indents the code, you know..
Then if there is an error, it will be red underlined, right ?
But there is an issue in vscode-go because it did not underline the text with red color.
When you try "go run main.go" in integrated terminal, it gives you an error like that "panic: assignment to entry in nil map" for the above code. Or you can try this link (https://play.golang.org/p/QgCjdmTeoP)

**Comment by ramya-rao-a** [comment]
@liberalakrep Thanks for the clarification 

In the first case, you get the error only when doing a `go run` and not a `go build` where as in the second case you get the error when doing a `go build` itself

I believe this is a case of run time vs compile time error.

The VS Code Go extension uses `go build`, `go vet` and linters to provide users with errors and warnings. It doesn't try to run the code on save. Therefore, unless there is a Go tool out there that can give the "panic: assignment to entry in nil map" error, the Go extension cannot do much here.

I suggest you open an issue for Go itself for surfacing this error while running `go build`.

@rakyll @campoy Correct me if I am wrong above.

**Comment by liberalakrep** [comment]
Okey, i got it.
As you say attempting to index it like data["a"]["w"] is a runtime panic, not a compiling time error.
So i have to initialize a map first before indexing it.
Thank you su much for your clarification.

**Comment by ramya-rao-a** [comment]
No problem, thanks for logging the issue though, I learn more with each such scenario :)
