### ISSUE TITLE
Offer install option in warnings about missing Go tools

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#102]
![image](https://cloud.githubusercontent.com/assets/159209/11412669/74a85a42-9394-11e5-95db-4f3e25892024.png)
![image](https://cloud.githubusercontent.com/assets/159209/11412673/805969c6-9394-11e5-9170-bacf9802c74a.png)

Perhaps we can offer an "Install" button for such missing tools?

**Comment by LiterallyElvis** [comment]
Alternatively, just opening a document with the list of commands to run would be helpful so I don't have to pull up the README every time.
