### ISSUE TITLE
"run test" and "debug test" links appear in random order

### ISSUE THREAD

**Issue by olivierperes** [Microsoft/vscode-go#1021]
In a Go source file containing tests, VS Code inserts two links before each test : "run test" and "debug test". As illustrated in the captures below, they do not always appear in the same order, which is rather confusing (I have already clicked several times on the wrong link because of that). It is not terribly bad, just annoying.

Version of VS Code: 1.12.2
Extensions installed: Go, Git Lens, Docker
Reproducible steps: unfortunately this seems to happen randomly. Open a file containing tests, see in which order the links are, modify and save the file, look again: it might have changed, or not.
Errors in the Dev Tools console: several instances of _[IPC Library: Watcher] Error: watch /home/[X]/Projects/src/[Y]/.git/modules/vendor/golang.org/x/net/index.lock ENOSPC_ but it seems unrelated.

![capture test debug run](https://cloud.githubusercontent.com/assets/5556642/26829145/a2bac83c-4ac4-11e7-8ce9-3e2ec6afe855.png)
![capture test run debug](https://cloud.githubusercontent.com/assets/5556642/26829144/a2b49bc4-4ac4-11e7-9302-473d2ee8e6ec.png)

**Comment by ramya-rao-a** [comment]
@olivierperes Thanks for reporting.

There is already a bug for this: #999

The fix is in the main VS Code product and not the Go extension
The fix is available in the Insiders build and will be shipped in the next update of VS Code (1.13)
