### ISSUE TITLE
Autocomplete doesn't autocomplete the parameters

### ISSUE THREAD

**Issue by dbcc** [Microsoft/vscode-go#1022]
i don't know if i'm supposed to open the issue here or at vscode github, so i'm just gonna do it here since i noticed it when i code in Go. 
In the insiders vscode it doesn't autocomplete the parameters and i don't know why.
![image](https://user-images.githubusercontent.com/5368488/26862855-b98c51c2-4b4e-11e7-9813-ab7c45c93f6d.png)
and this is on the release version of vscode
![image](https://user-images.githubusercontent.com/5368488/26862951-8881cf98-4b4f-11e7-9263-f131c29d5b52.png)

**Comment by ramya-rao-a** [comment]
Nice catch @dbcc 

We use snippets with placeholders of the format `${placeholder}`, but looks like in the insiders, the expected syntax for placeholders is `${tabstop:placeholder}`

@jrieken Can you confirm that `${placeholder}` is no longer valid and that we need to use `${tabstop:placeholder}` instead?

**Comment by RobGraham** [comment]
I've noticed this since I started working with Go in vs code about a week ago and always questioned whether or not the auto complete was meant to complete with the parameters but it's not. Glad I'm not the only one.
![autocomplete1](https://user-images.githubusercontent.com/1311204/26909623-ca891c4a-4bb6-11e7-893a-4a14adb38836.png)
After using tab or enter:
![autocomplete2](https://user-images.githubusercontent.com/1311204/26909639-dde66392-4bb6-11e7-97f9-dfba4e18b5d9.png)

**Comment by ramya-rao-a** [comment]
@RobGraham Welcome to Go in VS Code :)
 Setting `go.useCodeSnippetsOnFunctionSuggest` to `true` will insert the expected snippet on auto-complete. This is set to `false` by default.

What @dbcc is saying above is that this feature is broken in Insiders and so will be broken in next update to VS Code as well which will be out some time this week or early next week.

The fix is simple, am just waiting for a confirmation from @jrieken

**Comment by jrieken** [comment]
> @jrieken Can you confirm that ${placeholder} is no longer valid and that we need to use ${tabstop:placeholder} instead?

Yes, ${foo} references a variable, not a placeholder. The adoption in #709 wan't adding the right syntax? I guess we were to quick on https://github.com/Microsoft/vscode/issues/15573, outsiders got more detail, e.g, https://github.com/twxs/vs.language.cmake/issues/21

**Comment by RobGraham** [comment]
@ramya-rao-a thanks so much! Sorry for intruding in an unrelated topic

**Comment by ramya-rao-a** [comment]
@jrieken As part of #709 we did move away from the internal syntax of `{{...}}`, but I guess I missed the tabstop, will fix it. thanks!

@RobGraham no problem at all, happy to help

**Comment by ramya-rao-a** [comment]
The fix is now available in the latest update (0.6.62)

**Comment by highskillzz** [comment]
for some reason for me even though it shows the it is a function when enter or tab is pressed not even brackets are placed and I HAVE TURNED THE go.useCodeSnippetsOnFunctionSuggest to true. Am I missing something??

**Comment by ramya-rao-a** [comment]
@highskillzz Can you include a gif/video/screenshot of the issue?

**Comment by highskillzz** [comment]
![issue-2](https://user-images.githubusercontent.com/20688709/30469285-14cf98b6-9a0d-11e7-9994-bdc3553d8ed2.PNG)
![issue1](https://user-images.githubusercontent.com/20688709/30469287-19691afa-9a0d-11e7-932a-870f1905fd69.PNG)

**Comment by highskillzz** [comment]
![issue1](https://user-images.githubusercontent.com/20688709/30469318-3c922774-9a0d-11e7-83b7-3f4756a9b947.PNG)
![issue-2](https://user-images.githubusercontent.com/20688709/30469320-3e7b4ce6-9a0d-11e7-95fd-4c37251716e9.PNG)

**Comment by highskillzz** [comment]
brackets are not appearing when I press enter

**Comment by ramya-rao-a** [comment]
@highskillzz Silly question.... Is that Go?

**Comment by highskillzz** [comment]
Yes, and sorry if the question is irrelevant but regardless can anybody provide the solution

**Comment by ramya-rao-a** [comment]
@highskillzz In your example, `require` is not a function. If it is a function then the docs would say `func ...`, in your case it is a variable and so you see `var require: NodeRequire`.

**Comment by highskillzz** [comment]
then this..

![issue-1](https://user-images.githubusercontent.com/20688709/30501304-945d004c-9a7f-11e7-96a7-0f9fdd05ab8a.PNG)
![issue2](https://user-images.githubusercontent.com/20688709/30501305-945e128e-9a7f-11e7-8dd4-0a0435de503f.PNG)

**Comment by ramya-rao-a** [comment]
What does it show next to the suggestion in the docs? Does it indicate "func" like this:

<img width="488" alt="screen shot 2017-09-15 at 4 41 41 pm" src="https://user-images.githubusercontent.com/16890566/30506934-c9b228b2-9a34-11e7-8a82-6e1daf540091.png">

**Comment by highskillzz** [comment]
It shows like this
![image](https://user-images.githubusercontent.com/20688709/30513760-67166824-9b26-11e7-94cd-96a6bb686e99.png)

**Comment by ramya-rao-a** [comment]
@highskillzz The code you are sharing is definitely not Go. Its typescript. Try setting `typescript.useCodeSnippetsOnMethodSuggest` to `true`

**Comment by highskillzz** [comment]
Yes its working now. Thank you and sorry for my misunderstanding
