### ISSUE TITLE
Build tags breaks go to definition and other features

### ISSUE THREAD

**Issue by inancgumus** [Microsoft/vscode-go#1024]
When I add a build tag on top of a file, vscode-go _go to definition_ and _mouse over peak_ functionality breaks.

When I remove it, it works again.

```
// +build integration
```

# See this:

![vscodegobug](https://user-images.githubusercontent.com/621232/26931076-00f89a24-4c68-11e7-8f87-8fbe01e2fe9e.gif)

**Comment by ramya-rao-a** [comment]
@inancgumus Do you have the language server turned on?

**Comment by inancgumus** [comment]
Do you mean [this](https://github.com/sourcegraph/go-langserver)? If so, I'll try it.

What do you think about why this happens when I add a build tag? Even because of the lang-server. Because, it works w/out it.

**Comment by ramya-rao-a** [comment]
We have 3 different ways of providing the definition information

- `go.docsTool` is set to `godoc` (default)
- `go.docsTool` is set to `gogetdoc`
- go.useLanguageServer` is set to `true`

I was trying to see which one of the above categories does your scenario fall into.

I can repro this issue in the second and third case but not the first.

cc @zmb3 for `gogetdoc` and @slimsag for the language server

**Comment by zmb3** [comment]
This makes a lot of sense.  Feel free to file an issue at github.com/zmb3/gogetdoc for build tag support and I will look to add a way to provide build tags to the tool.

> I can repro this issue in the second and third case but not the first.

In the first case, how are you actually getting definition information?  I wasn't aware that `godoc` spits that out.

**Comment by ramya-rao-a** [comment]
@zmb3 its `godef` that gives the definition info

When I added the setting to choose between default implementation (godef + godoc) and gogetdoc, I couldnt come up with a better name than `go.docsTool` and since it says "**docs**tool", the options were `godoc` and `gogetdoc` :)

**Comment by ramya-rao-a** [comment]
Logged an issue for gogetdoc and the language server and closing this issue

**Comment by ramya-rao-a** [comment]
Re-opening to absorb the changes done in gogetdoc

**Comment by inancgumus** [comment]
@ramya-rao-a I couldn't see the absorbed changes from gogetdoc?

**Comment by ramya-rao-a** [comment]
I am yet to release an update (should be out in the next few days).
You will see the changes then.

**Comment by ramya-rao-a** [comment]
`go.buildTags` will now be honored when using the `Go to definition` feature in the latest update (0.6.63) to the Go extension

**Comment by inancgumus** [comment]
@ramya-rao-a That's perfect, thanks!
