### ISSUE TITLE
Explore setting gogetdoc as the default doc tool on new installations

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#1025]
We added support for `gogetdoc` last November and it solved a number of issues in the Go extension

![screen shot 2017-06-08 at 11 15 50 am](https://user-images.githubusercontent.com/16890566/26943860-e3412acc-4c3b-11e7-9edd-73dcdee1061b.png)

`gogetdoc` is not yet the default option.

Once there is a resolution on #667, we can look into making `gogetdoc` the default option.

**Comment by tayhalla** [comment]
Fwiw - I had the GoToDef and click to def fail for me randomly. I followed all these other issues and nothing resolved it. 

Finally, I realized homebrew updated my go version doing a large update. The tools VSCode installed during the initial use of `vscode-go` were out of date. Going to the VSCode commands and running `Go: Install Tools` fixed everything for me.

**Comment by labregowski** [comment]
Hi. 
@tayhalla, sorry for my ignorance. I just installed VSC yesterday. How do I go to VSCode commands :D?
Thanks in advance

**Comment by otterley** [comment]
I support making this change as the default.  My out-of-the-box setup on a new Mac did not work with the latest versions (VS Code 1.29.0, Go extension 0.7, Golang 1.11.1) did not work until I switched to gogetdoc.

**Comment by ramya-rao-a** [comment]
Now that there is active development on an official language server for Go via [gopls](https://github.com/golang/go/wiki/gopls), we will soon be suggesting to use it for most language features including `Go to definition`, signature help and info on hover.

Therefore, there will be no further work in investigating whether `gogetdoc` should be the default or not for the `go.docsTool` setting.

For more on language server integration with this extension, please see [Go language server](https://github.com/microsoft/vscode-go#go-language-server)

To go a feature request for gopls, use the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)
