### ISSUE TITLE
Could not launch process: stub exited while attempting to connect: signal: segmentation fault

### ISSUE THREAD

**Issue by alanpadillachua** [Microsoft/vscode-go#1027]
I had trouble earlier installing delve but finally moved on from that. When I go to debug I get 
`launching process with args: [/Users/alan.chua/Projects/GoWorkspace/src/github.com/alan-chua/strservice/main/debug]
could not launch process: stub exited while attempting to connect: signal: segmentation fault`

```
Delve Debugger
Version: 1.0.0-rc.1
Build: 
```

**Comment by ramya-rao-a** [comment]
Are you able to use delve from the command line?

**Comment by alanpadillachua** [comment]
when I run the command `dlv debug main.go`
I get `could not launch process: stub exited while attempting to connect: signal: segmentation fault`

**Comment by ramya-rao-a** [comment]
Ok, then its a problem with delve itself. Or some combination of your environment and delve.
Please open an issue in https://github.com/derekparker/delve

They should be able to help you better
