### ISSUE TITLE
command line arguments do not seem to be passed when debugging

### ISSUE THREAD

**Issue by xoviat** [Microsoft/vscode-go#1028]

**Comment by ramya-rao-a** [comment]
@xoviat Have you tried the `args` field in the debug configuration?

**Comment by xoviat** [comment]
Yes. Here is my configuration:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch file",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${file}",
            "args": [
                "-arga",
                "-argb"
            ]
        },
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${fileDirname}",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}
```

`os.Args` was empty in the debugger

**Comment by ramya-rao-a** [comment]
Can you share sample code as well so that I can try and repro?

**Comment by xoviat** [comment]
```go
package main

import "os"

func main() {
	a := os.Args

	_ = a
}

```

**Comment by ramya-rao-a** [comment]
I used your code + a print statement and your debug config
As you can see the args get printed in the debug console.

<img width="964" alt="screen shot 2017-06-10 at 6 41 36 pm" src="https://user-images.githubusercontent.com/16890566/27007585-881750ae-4e0c-11e7-82e5-4d22f5dc3b2d.png">

**Comment by xoviat** [comment]
![image](https://user-images.githubusercontent.com/15351036/27007632-1fabed50-4e1f-11e7-8fb3-1dbf1872d5e4.png)

**Comment by ramya-rao-a** [comment]
You are passing the args to the "Launch file" config, but looking at your screenshot you seem to be using the "Launch" config.

Can you either try adding the args to the "Launch" config or choose "Launch file" in the drop down?

**Comment by xoviat** [comment]
That was it. I am so sorry for wasting your time.

**Comment by ramya-rao-a** [comment]
No problem at all 😊 Happy Coding!
