### ISSUE TITLE
Code completion in comments sections

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#103]
(Not sure if Go Plugin or VSCode in general)

I'm trying to write 80-line word-wrap comments and auto-completion keeps working in the comments. Naturally when I hit return, it automatically takes the first suggestion. This probably shouldn't be the case.

![image](https://cloud.githubusercontent.com/assets/159209/11412923/096c4956-9398-11e5-94d6-04d2d279df17.png)

**Comment by nictuku** [comment]
+1. This is an annoying bug. Simple repro:

![vscode](https://cloud.githubusercontent.com/assets/202998/11462913/9b3abd6a-96cf-11e5-8df4-69ca57d5a2a6.png)

Keep up the great work!

**Comment by egamma** [comment]
These are actually 2 different scenarios. 

VS Code supports multiple completion providers and for Go there is the Go aware completion provider and a buffer based textual completion provider. The providers are prioritized first specific if no suggestions from the specific provider then show completions of a less specific provider. 

In the scenario from @ahmetalpbalkan the Go completion provider has no suggestions and the buffer based provider shows textual completions. We have found this very useful when writing documentation. I agree that the auto accept on return is annoying and we need to tune this.

In the scenario of @nictuku the Go completion provider suggests semantic completions inside a comment and this is what is shown. This can be considered as a bug of the underlying gocode tool, it should not make semantic suggestions inside comments. As @lukehoban suggested above this could be worked around in the Go completion provider by not making suggestions inside comment tokens.

**Comment by lukehoban** [comment]
My current plan is to:

1. In the short term, do a targeted fix to turn off Go suggestions inside `//` comments.
2. In the medium term, use whatever mechanism Code provides to suppress suggestions inside certain tokens/scopes once https://github.com/Microsoft/vscode/issues/719 is addressed.

Neither of these will suppress the "textual completions" that @egamma mentions.  I don't think there's anything we can do about those and it's just part of how Code behaves today.  Perhaps in the future there will be a user visible option to turn this off.

**Comment by shurcooL** [comment]
I was going to report this issue too, because I found completions appearing when editing comments were surprising (no other editor I've used in the past did this), unhelpful and distracting. Since this is new behavior for me, there's a chance I would get used to it over time and start to like it.

Anyway, I see the issue was already reported, discussed, and closed, so there's no need for me to open a new one.

**Comment by Ziflin** [comment]
Has this issue been addressed yet? It is still **extremely** annoying to write comments in PHP files with it auto-completing on "Return".  Is there a way to disable that behavior currently?  It's to the point where I'll be switching to Atom/Brackets if there isn't a way to disable it...

**Comment by lukehoban** [comment]
Per my previous comment - the Go specific piece of this is indeed fixed (at least for comments).

But textual completions cannot currently be disabled in vscode, and I expect this is what you are seeing.

I believe this is being tracked by https://github.com/Microsoft/vscode/issues/2496 and https://github.com/Microsoft/vscode/issues/719, it would be worth providing feedback there on the concern with this design/default.  

If there is support for disabling this, I expect to turn it off by default as part of the `vscode-go` extension.

**Comment by Ziflin** [comment]
Yeah, I'm referring to PHP comments actually.  Trying to add a new-line in a comment always seems to auto-complete something making it super annoying.  If there was just a way to disable/unbind 'Return' performing autocompletes I think that would be fine.

**Comment by egamma** [comment]
>Yeah, I'm referring to PHP comments actually. Trying to add a new-line in a comment always seems to auto-complete something making it super annoying.

Can you please file an issue against VS Code with an example the reproduces the annoying behaviour.

**Comment by Ziflin** [comment]
I was actually able to just disable Enter auto-completing which was enough for me with the following override in File/Preferences/Keyboard Shortcuts:

```
{
		"key": "enter",
		"when" : "editorTextFocus && suggestWidgetVisible"
}
```

**Comment by gillez** [comment]
Is there an open issue for this that I can add info to, or should I open a  new bug?

**Comment by ramya-rao-a** [comment]
@gillez The latest discussion on code completion in comments is tracked in #10819 You can also read through #11704
