### ISSUE TITLE
Go lang server eats up cpu

### ISSUE THREAD

**Issue by mhindery** [Microsoft/vscode-go#1030]
Working on a Go project with the golangserver enabled, the process eats up my cpu. This is even without doing actual coding (so no hovering and lookups necessary)
<img width="769" alt="screen shot 2017-06-12 at 09 33 14" src="https://user-images.githubusercontent.com/8758073/27023532-355e76ce-4f53-11e7-885d-75f0d7637467.png">

This is on a Macbook Pro with i7 QC

**Comment by ramya-rao-a** [comment]
This issue is being tracked here: https://github.com/sourcegraph/go-langserver/issues/178

Please add your input there.

Until the issue gets fixed, the workaround is to disable the language server
