### ISSUE TITLE
Can't debug integration tests

### ISSUE THREAD

**Issue by RoarkeRandall** [Microsoft/vscode-go#1031]
I'm able to debug go tests in vscode by pressing the debug test link above the test function. 

However, if I add `// +build Integration` to the top of the test file to indicate it is an integration test, one of two things will occur... 

1. In the case of there being test binary had been built before adding the integration tag, then the old test binary will be run. If you modify your code enough, you won't hit breakpoints.
2. In this case that the test hasn't been run before adding the integration tag line, you will receive the following error:

```
could not launch process: stub exited while waiting for connection: exit status 0
Process exiting with code: 1
```

I'm running this on:
vscode 10.13.0
vscode-go 0.6.62
go 1.8.3 darwin/amd64

**Comment by ramya-rao-a** [comment]
In both the cases, the issue is with delve.
Am sure if you run delve from command line for both cases, you will see similar results.

If so, please log this issue in repo for delve: http://github.com/derekparker/delve

If delve from command line works, then please re-open this issue
