### ISSUE TITLE
Go file icon is scary in VSCode 1.13

### ISSUE THREAD

**Issue by AlekSi** [Microsoft/vscode-go#1033]
Seriously, look into those hollow eyes: ![2017-06-15_11-46-04](https://user-images.githubusercontent.com/11512/27173138-4a75af7c-51c0-11e7-8a61-00d564644873.png) My guess they are transparent, and transparency wasn't supported until 1.13. Or maybe icon just changed.

macOS 10.12.5, VSCode 1.13.1.

**Comment by ramya-rao-a** [comment]
Alright people, although this is a very serious (cough cough) issue, am going to close this one.

If anyone can come up with a better (read friendly) icon, feel free to update the icon in https://github.com/jesseweed/seti-ui

**Comment by AlekSi** [comment]
Any reason https://github.com/jesseweed/seti-ui/blob/master/icons/go2.svg is used instead of https://github.com/jesseweed/seti-ui/blob/master/icons/go.svg?

**Comment by ramya-rao-a** [comment]
@AlekSi No idea

AFAIK We use the icons from https://github.com/jesseweed/seti-ui.
See 
https://github.com/Microsoft/vscode/blob/2f76c44632b0d47ba97f66fbc158c763628e30b3/extensions/theme-seti/OSSREADME.json

cc @bpasero

**Comment by AlekSi** [comment]
They use both: https://github.com/jesseweed/seti-ui/blob/master/styles/components/icons/mapping.less#L97. I wonder if it looks scary in Atom too, or differences between Atom and VSCode make it look good in Atom and scary in VSCode.

**Comment by bpasero** [comment]
@ramya-rao-a it is @aeschli who does our icon themes
