### ISSUE TITLE
High CPU perf issue since 1.13, auto-complete barely supportable

### ISSUE THREAD

**Issue by dstpierre** [Microsoft/vscode-go#1035]
```
Version 1.13.1
Commit 379d2efb5539b09112c793d3d9a413017d736f89
Date 2017-06-14T18:18:03.540Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
go version go1.8.3 linux/amd64
vscode-go 0.6.62
```

I already tried the `gocode close` and `go get -u github.com/nsf/gocode` which worked for me in the past. But it does not this time.

Looking at top vscode and gocode are both eating all my 8 CPU cycles. I have a 4 core i7 3.5ghz so this should be plenty for a text editor ;).

This starts to occurs since 1.13, I thought that 1.13.1 would have helped, but nope, same issue.

I'd say normally the auto-complete suggestion display almost instantly so I have lots of mechanical things like `func handler(w http.Respo` normally I was tabbing there, and now it takes up to 1.5 seconds to show, so I mechanically tab in "empty suggestion" making this muscle memory questionable I must admit, but that debate is out of scope of this issue hah.

Anything I can supply, is this a know issue at the moment?
Thanks

**Comment by andreis** [comment]
Same here, same CPU, and it's driving me crazy. E.g. when saving (Cmd-S) it's often typing a few to a lot of `s`es.

**Comment by dstpierre** [comment]
This is now at a point where I'm editing my Go code in vim, since vscode-go and vim-go seems to be using ~similar tools, I can't think of anything else than maybe my project is now too big for vscode?

Using it for Typescript and the CPU usage is ~normal. But as soon as I'm editing a Go code file the CPU jump in the 325 % usage. Using the <kbd>SHIFT</kbd>+<kbd>F12</kbd> to see all references for example simply takes forever compare to vim-go `:GoReferrers` which does nothing to CPU and respond in 1-2 seconds and I'd say 35-45 seconds to vscode-go.

Up until very recently there were no issue, but this is now un-usable for me.

**Comment by andreis** [comment]
I feel your pain. I've worked on Go projects with under 100 loc and it's the same deal. Something's fishy. My workaround is to just change the linter from `gometalinter` to `golint` until this gets fixed.

**Comment by dstpierre** [comment]
@andreis my linter was already golint.

If that can help also, I've noticed that this bad performance occurs on project that I have multiple packages, i.e.

root
|- package1
|- package2
|- package3

When editing a project with only one package, the performance is much better, as in similar to pre 1.13.

**Comment by ramya-rao-a** [comment]
@dstpierre @andreis Sorry didn't get to this earlier, it somehow got lost in the sea of notifications and I was on vacation all last week.

Here are a few thoughts

- On using `gometalinter`, try using the lint flags to disable all linters and then enable the ones that most interest you. Eg: `['--disable-all', '--enable=varcheck', '--enable=errcheck']` Or use the `-fast` flag that will run only the fast linters
- On the multi-package note: In the last update to Go extension, we started supporting build/lint/vet on workspace as well. This is done by the settings `buildOnSave`, `vetOnSave` and `lintOnSave` now accepting values `package`, `workspace` and `off`. Can you try setting these to `package` and see if you still see perf issues when working on multi packages?

On the perf side

- Upgrading to 1.13 shouldn't have had any affect on the auto complete perf for Go
- Can you disable all other extensions and see if you still have the issue? We have seem sometimes that some other extensions interfere and cause perf issues
- Have you recently upgraded Go version or recently upgraded to Sierra. We have seen perf issues in both cases. Updating and rebuilding the Go tools have helped users in this case. Can you update all the Go tools regardless by running `Go: Install/Update tools` to ensure you have the latest tools rebuilt

If the issue still persists, the next thing I'd like to try is to use an older version of the Go extension. This is to see if something we shipped last time is causing trouble.

- download the vsix file for Go 0.6.61 from https://github.com/Microsoft/vscode-go/releases/tag/0.6.61
- Close all VS Code instances
- run `code --install-extension` and pass the path to the downloaded vsix file.
- open VS Code and see if you still see issues.

**Comment by ramya-rao-a** [comment]
@dstpierre @andreis Any updates? Do you still have perf issues?

**Comment by andreis** [comment]
@ramya-rao-a none here, thank you – I'm on a different machine now so I'm not exactly a reliable data point

This is the config I use though https://github.com/andreis/cfg/tree/master/vscode

**Comment by ramya-rao-a** [comment]
Thanks @andreis 

@dstpierre ?

**Comment by alexbrand** [comment]
I am running into this as well. I see a bunch of `guru` processes that seem to be eating up my CPU on a mac os machine.

<img width="1406" alt="screen shot 2017-07-30 at 10 33 11 am" src="https://user-images.githubusercontent.com/545723/28754405-a42c1d6a-7512-11e7-9aab-f65e06747aa5.png">

Go plugin v0.6.63
VS Code v1.14.2

**Comment by ramya-rao-a** [comment]
@alexbrand Do you have the references codelens enabled? It uses `guru` and gets updated for every file change. And so gets expensive on bigger code bases

**Comment by alexbrand** [comment]
Yes,  I do have codelens enabled, although I wouldn't consider it a large code base.

**Comment by xpqz** [comment]
This is still an issue. I need to kill all `gocode` processes every 5 minutes or so.

**Comment by ramya-rao-a** [comment]
@xpqz Can you try setting `go.gocodeAutoBuild` to `false` and see if that helps?

Is it only the `gocode` processes or do you see a lot of other go tools taking up CPU?

**Comment by ramya-rao-a** [comment]
In the [November release of 0.6.69](https://github.com/Microsoft/vscode-go/wiki/Release-Notes#0669---27th-november-2017) we pushed some perf improvements that should help.

Locking and closing this issue for now as there hasn't been any activity here.

If anybody does see any perf issue, please log a new issue
