### ISSUE TITLE
vscode golang plugin dosn't show documentation for some functions on mouse hover

### ISSUE THREAD

**Issue by jcbritobr** [Microsoft/vscode-go#1038]
Some functions comments are not appearing in info when the mouse pointer is over a function:

Operation System info:
==================
linux x86_64 fedora 25

Visual Studio Code Info:
==================
Version 1.13.0
Commit 376c52b955428d205459bea6619fc161fc8faacf
Date 2017-06-08T16:41:25.571Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

vscode-go plugin info:
=================
version:0.6.62 - 9th June, 2017

![small-clip](https://user-images.githubusercontent.com/6579862/27228840-99c09b7c-527f-11e7-92ac-0fa74b1e4167.gif)

**Comment by ramya-rao-a** [comment]
Can you try setting `go.docsTool` to `gogetdoc`? The default tool for docs doesnt work well with structs

**Comment by jcbritobr** [comment]
Hi @ramya-rao-a . It worked with gogetdoc. Thank you. Maybe vscode whould support this tool officialy.

**Comment by ramya-rao-a** [comment]
We do support gogetdoc officially, just not by default.

#1025 is tracking the task to make it the default tool
