### ISSUE TITLE
`func` and `type` is specified via the scope `keyword`

### ISSUE THREAD

**Issue by kyoh86** [Microsoft/vscode-go#1040]
In other languages, (JavaScript, Python, etc.) they are specified via a scope `storage.type`.
Only in golang, they're colored with another color in some color theme.

https://www.sublimetext.com/docs/3/scope_naming.html#storage

**Comment by ramya-rao-a** [comment]
@kyoh86 We use the grammar for Go from https://github.com/atom/language-go
Please log an issue in that repo for your issue with scope names
