### ISSUE TITLE
Calling lint and vet tool by hotkey or from interface

### ISSUE THREAD

**Issue by DevNulPavel** [Microsoft/vscode-go#1041]
Great plugin, but calling lint and vet tools manualy sometimes needed to avoid freezings on save with autolint/autovet enabled.

**Comment by ramya-rao-a** [comment]
Agreed. We can have commands to run lint/vet/build. One thing to think about is whether these will act on current file/ current package or the whole workspace. Do we have 3 separate lint commands for the 3 scenarios? Or 1 lint command and a setting to control the scope? Or re-use the scope from buildOnSave/lintOnSave settings.

Other than that this is a very simple feature to implement. PRs welcome

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.69)
The commands `Go: Lint Current Package` and `Go: Lint Workspace` are now available.
Thanks @ndrewnee!

**Comment by DevNulPavel** [comment]
Good news everyone! Thanks!
