### ISSUE TITLE
Slice type is inferred wrongly as array

### ISSUE THREAD

**Issue by manikawnth-tcs** [Microsoft/vscode-go#1042]
The definition popover of a slice type is wrongly depicted as an array.
Let me know if this is not an issue to be posted here.

![error](https://user-images.githubusercontent.com/28628364/27339711-852ef094-55a6-11e7-9f70-442e693bc3e8.png)

**Comment by ramya-rao-a** [comment]
That's how `godef` returns the information. So I'd suggest to log the issue in the repo for the `godef` tool.

However, we have 2 other options for showing the hover info
- Set `go.docsTool` to `gogetdoc`. 
OR
- Set `go.useLanguageServer` to `true`

Both options gives the right hover info
