### ISSUE TITLE
Auto Indent Support

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-go#1043]
To embrace the new auto indent feature in Code, languages need to define its indentation rules. You can either do that in JavaScript or simply put that into `language-configuration.json` https://github.com/Microsoft/vscode/blob/master/extensions/ruby/language-configuration.json#L25 .

A good start can be https://github.com/atom/language-go/blob/master/settings/language-go.cson but we need to do some validation against https://github.com/atom/language-go/issues?q=is%3Aissue+is%3Aopen+label%3Aauto-indent

**Comment by ramya-rao-a** [comment]
Indentation rules are updated in the core VS Code with https://github.com/Microsoft/vscode/commit/e6c60418fd865c65b114211f4148c1268277b217

and in the Go extension with https://github.com/Microsoft/vscode-go/commit/bd9556143bcf214db8c10a19d5cec5e9882286af

The fix in the core will help users that don't use the Go extension.
The fix in the Go extension will help users that are on the next update (0.6.63) but not necessarily on the next VS Code update (1.15)
