### ISSUE TITLE
Go to Definition and Codelens fails for anonymous struct members

### ISSUE THREAD

**Issue by hhrutter** [Microsoft/vscode-go#1044]
I am on MacOS, VSCode Release May 2017 (version 1.13); Go 0.6.62

When using anonymous types like so jumping to the struct definition eg `Configuration` does not work neither do I get a codelens.

<img width="316" alt="struct" src="https://user-images.githubusercontent.com/11322155/27380263-bd5aa7a0-567e-11e7-941d-699a56ca73da.png">

**Comment by ramya-rao-a** [comment]
For jumping to definition can you try setting `go.docsTool` to `gogetdoc`?

What do you get when you do a "Find All References" on this type?

**Comment by hhrutter** [comment]
Hi,

I am already on gogetdoc.

When I do a "Find All References" I get a code lens
showing me the same containing struct with the type highlighted 
to which definition I would like to be taken.

**Comment by ramya-rao-a** [comment]
Can you share a complete sample code where I can try this?

**Comment by hhrutter** [comment]
Sure.
Jumping to the definition works in this example for f1 and f2 but not
for the anonymous members of type foo and *foo. 

```
package main

type foo struct {
	i int
}

type bar1 struct {
	foo
	f1 foo
}

type bar2 struct {
	*foo
	f2 *foo
}

func main() {}
```

**Comment by ramya-rao-a** [comment]
Using your example, I am able to go to the definition of both `foo` and `f1` in `bar1`

![anoyn](https://user-images.githubusercontent.com/16890566/27512778-be423ad6-5901-11e7-8d62-81157e6b1528.gif)

**Comment by hhrutter** [comment]
I know this works. I think there has been some misunderstanding
I want to inspect the members of a struct and be taken to each members definition.
That's why I left out the implementation of `main`,  because it's irrelevant here.

Like when I hover over the bar1 struct I 'd like to inspect the definitions for f1 or the anonymous member foo especially in my case when they reside in different source files.
For f1 it works but not for the anonymous member  of type foo one line above.

How did you make this animated gif?
I love it. I'd like to post what I mean by sending you one.

**Comment by ramya-rao-a** [comment]
I used LICEcap for the gif. Its pretty easy

Yes, please share gif/video.

**Comment by hhrutter** [comment]
There you go..
![vs](https://user-images.githubusercontent.com/11322155/27519311-05f823c8-59f1-11e7-8cd2-ddbd503babd5.gif)

**Comment by ramya-rao-a** [comment]
I can repro when using `gogetdoc` but not when I set `go.docsTool` to `godoc` (which uses `godef` to find the definition)

cc @zmb3

**Comment by ramya-rao-a** [comment]
@hhrutter you also mentioned that the codelens doesn't work. Can you elaborate on that as well? I see the references codelens on the structs

<img width="263" alt="screen shot 2017-06-27 at 10 31 05 pm" src="https://user-images.githubusercontent.com/16890566/27621837-61c313e6-5b88-11e7-9050-497e004c0caa.png">

**Comment by zmb3** [comment]
I'll take a look at the go to definition issue in gogetdoc. Thanks for the report!

**Comment by zmb3** [comment]
I can't seem to reproduce this. Docs tool is set to `gogetdoc` and here's what I get:

![embed](https://user-images.githubusercontent.com/7527103/27648837-defc9b50-5bfd-11e7-992a-de5cf4ab8f53.gif)

**Comment by ramya-rao-a** [comment]
@zmb3 Make sure `go.useLanguageServer` is set to `false`. That overrides the `go.docsTool` setting

**Comment by zmb3** [comment]
Got it. Thanks Ramya. I have a fix coded up, just need to clean up a few things and I'll have it out tomorrow.

**Comment by ramya-rao-a** [comment]
Awesome, thanks @zmb3!

**Comment by hhrutter** [comment]
Excellent. So the codelens issue I mentioned is tied into all this.
The codelens is showing the doc for the embedded field but not for its type which makes
more sense as @zmb3 already figured.
I am going to check out @zmb3 's fix once its merged in and report back.
Thanks!

**Comment by zmb3** [comment]
@hhrutter the fix is committed. Just update with 'go get -u github.com/zmb3/gogetdoc'

**Comment by hhrutter** [comment]
💯 working. Thx @zmbr & @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@hhrutter just confirming.. When you say codelens so you mean the text you see when you hover on the field?

**Comment by hhrutter** [comment]
Exactly.
The codelens used to show field doc for embedded fields and now it correctly shows the type doc which makes much more sense.
![vs](https://user-images.githubusercontent.com/11322155/27820338-78390570-609e-11e7-99c4-f39a4926211d.gif)

**Comment by ramya-rao-a** [comment]
Ah! That got me confused. Codelens is the term used for something else entirely 😊 

See https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup

**Comment by hhrutter** [comment]
I see. So how do you call this little popup displaying the type info?

**Comment by ramya-rao-a** [comment]
Hover info or tooltip

**Comment by hhrutter** [comment]
Like in the browser. ok

**Comment by ramya-rao-a** [comment]
Correct
