### ISSUE TITLE
debug test - How to configure?

### ISSUE THREAD

**Issue by mathieupythian** [Microsoft/vscode-go#1045]
I like the fact that I can easily run a single test with the link ('run test') that appears right above the test function, and that works great.  However, I cannot figure out how to use the 'debug test' link next to it.  I assume I need a launch.json configuration based on the instructions for dlv, but I did not have any luck actually running an individual test in debug and hitting a breakpoint.

I also find it strange that according to what I read, I would need to hardcode the test name in the launch config... seems like a workaround people found, but that's not very practical.  Any reason why that's the case?  Especially when the 'run test' works so nicely.

In the debug console, I get:
```
could not launch process: dial tcp :58180: getsockopt: connection refused
Process exiting with code: 1
```

Here is my the part of my launch.json that has the 'test' mode:

```
         {
            "name": "Launch Test",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "remotePath": "",
            "port": 2346,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {},
            "args": [
                "-test.v",
                "-test.run",
                "^TestName$"
            ],
            "showLog": true
        }
```

**Comment by ramya-rao-a** [comment]
The `getsocopt` error you are seeing is tracked in #986. I am guessing you are on Mac OS?

Please follow the workaround here: https://github.com/Microsoft/vscode-go/issues/986#issuecomment-304347853

The "debug test" link doesnt need any launch.config to run. It creates a debug configuration based on test function name and starts the debug session.

You need the launch.config if you intend to start debugging using `F5` or via the debug pane
