### ISSUE TITLE
Feature Request: Kill Running Test

### ISSUE THREAD

**Issue by tylerstillwater** [Microsoft/vscode-go#1047]
It is not uncommon for a misbehaving test to run for a long time, or indefinitely. It would be fantastic if there was a command/button/shortcut/some way to kill the currently running test.

**Comment by ramya-rao-a** [comment]
I am little busy at work, and may not be able to get to this any time soon, but this is a very useful feature to have.

PRs are welcome.

I can help out pointing people in the right direction if needed

**Comment by tylerb** [comment]
Happy to take a peek. No idea where to start 😃

I'm sure I could figure it out if you get me pointed in the right direction. Thanks!!

**Comment by ramya-rao-a** [comment]
There are 2 ways that I can think of to do this

- Have a status bar item that shows the status "Cancel Running Tests" that shows up when tests take say more than 5 seconds. Clicking on the status bar item should cancel the test. 
- Another way is to use the integrated terminal to run the tests, maybe via tasks. That way the user can just hit `Ctrl+C` to cancel the process as everything in the terminal is interactive

**Comment by tylerb** [comment]
Excellent. I love the status bar idea. Would you be able to point me in the right direction as to how to get started with putting something in the status bar?

**Comment by ramya-rao-a** [comment]
There already is a status bar that appears when the tests are run on save. Clicking on it shows the test output.

Look at the goCheck.ts file.

**Comment by tylerb** [comment]
Perfect. I'll dig in. Thanks!

**Comment by ramya-rao-a** [comment]
This feature is out in the latest update to the Go extension (0.6.82) thanks to @tylerb!

**Comment by tylerb** [comment]
Hooray! 🎉 Thanks @ramya-rao-a!
