### ISSUE TITLE
Go extension does not recognize other packages interfaces

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1048]
_From @rmescandon on June 21, 2017 16:51_

Steps to Reproduce:
1. I create a go project
2. That project has a package pkg1 with several types defined there, amongst them I declare an interface
```
package pkg1
...
type MyInterface interface {
...
```
3. In same project, I have another package pkg2
4. In a file from pkg2, I declare a var of MyInterface
```
var i pkg1.MyInterface
```
Expected:
The var declaration is not marked as error

Result:
That declaration line is underlined in red and tip when I set mouse cursor over it says "undefined: pkg1.MyInterface". However project compiles and works properly.

This is not happening if MyInterface is declared in same package

_Copied from original issue: Microsoft/vscode#29200_

**Comment by ramya-rao-a** [comment]
Here is my example, and I don't see any build errors. Can you share some code where you can repro this? 

<img width="934" alt="screen shot 2017-06-27 at 9 27 17 pm" src="https://user-images.githubusercontent.com/16890566/27620596-6eaa73fa-5b7f-11e7-8312-94dbe925bf3a.png">

**Comment by rmescandon** [comment]
Oh, so sorry.
Seems that a go build executed from command line solved the problem. Not sure what happened, but for the first time the interface was not recognized. Now everything looks fine. Sorry for the inconvenience of taking your time.
You can close it.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
