### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by pschuegr** [Microsoft/vscode-go#1052]
I'm having the same issue as this one from last year: https://github.com/Microsoft/vscode-go/issues/564.  Unable to launch the debugger from within vscode go or I get "Debug adapter process has terminated unexpectedly" (twice).

```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("hello world")
}
```

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/main.go",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}
```

- OSX 10.12.5
- vscode 1.13.1
- vscode-go 0.6.62
- dlv works fine from the command line
- same issue with remote debugging
- no output in debug console

**Comment by ramya-rao-a** [comment]
Can you set `"trace": "verbose"` in the debug config and see if you get any logs in the debug console?

**Comment by pschuegr** [comment]
Sorry, nothing else in the debug console with `trace: "verbose"`

**Comment by ramya-rao-a** [comment]
Not even the initial lines about writing to a file?

<img width="742" alt="screen shot 2017-06-28 at 8 24 17 pm" src="https://user-images.githubusercontent.com/16890566/27670138-d492580c-5c3f-11e7-8b8f-ff47664f45bf.png">

Have you been able to debug successfully before? Or never got it to work in your current environment? What I am trying to get at is if this is a regression due to a recent update or an environment issue.

cc @roblourens

**Comment by pschuegr** [comment]
@ramya-rao-a Nothing, unfortunately.  I tested this on another machine and it seems to work fine, so it's definitely an environment thing.  I'll dig into it more - do you have any suggestions?

**Comment by pschuegr** [comment]
Reinstall and the `debugAdapter` directory showed up fine.  Thanks for your help.

**Comment by ramya-rao-a** [comment]
>  go extension points to ./out/src/debugAdapter/goDebug.js, which afaict doesn't exist

That's a new one :)
No wonder the debug adapter couldn't start coz it didn't exist 😆 

Glad you are unblocked now. Happy Coding!
