### ISSUE TITLE
Trigger visibility of argument hints?

### ISSUE THREAD

**Issue by AndersenTobias** [Microsoft/vscode-go#1053]
I wonder if it is possible to trigger the visibility of the "argument hint" widget?
Specifically, I'm talking about this:
![skarmavbild 2017-06-23 kl 18 54 33](https://user-images.githubusercontent.com/4043059/27494401-9d9fe66e-5845-11e7-9dbd-e2459f6baf96.png)

It disappears as soon as I start typing the first parentheses.
It is kind of annoying to not know how to make it visible again since I cannot remember all arguments a lot of times.

**Comment by ramya-rao-a** [comment]
What you have in your screenshot is the suggestion widget/ autocompletion widget

We have another widget for parameter hints which will start showing up as you start typing inside the parentheses. Or if you click `Ctrl+Shift+Space` inside the parentheses. 

Can you try that?

**Comment by AndersenTobias** [comment]
@ramya-rao-a 
Unfortunately, nothing shows when I begin typing. Also `Ctrl+Shift+Space` does nothing for me.
(I'm on a Mac and also tried `Cmd+Shift+Space`.)

**Comment by ramya-rao-a** [comment]
I get the below

![sighelp](https://user-images.githubusercontent.com/16890566/27512667-bed61340-58fd-11e7-8f03-0002408e8a5d.gif)

**Comment by AndersenTobias** [comment]
Hmm, why don't I get that? Have you activated this somewhere in a settings file?

**Comment by ramya-rao-a** [comment]
Not at all, this should work out of the box.

If `Go to Definition` and quick info on hover works, the Signature/Parameter help should also work
They all share the same code.

Can you try on a simple piece of code?

**Comment by ramya-rao-a** [comment]
@AndersenTobias Haven't heard back from you in a while. Closing this issue for now.
If you still have issues with the parameter hints, feel free to re-open this issue
