### ISSUE TITLE
I've set my gopath, but when I try to download gocode and other packages it says $GOPATH not set and fails to download

### ISSUE THREAD

**Issue by ALynch11** [Microsoft/vscode-go#1054]

**Comment by ramya-rao-a** [comment]
Please read [GOPATH-in-the-VS-Code-Go-extension](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension). That should help.

If that still doesn't help, What do you see when you do the below?

- Run the command `Go: Current GOPATH`
- Open the integrated terminal (Ctrl+`) and type `echo $GOPATH`
