### ISSUE TITLE
PANIC on Intellisense

### ISSUE THREAD

**Issue by ardan-bkennedy** [Microsoft/vscode-go#1058]
Operating System
maxOS Sierra  v 10.12.5 (16F73)

Go
go1.9beta1 darwin/amd64

I downloaded a new version of gocode
go get -u github.com/nsf/gocode

When I use intellisense all I see is  "PANIC"

Not sure if there something else I need to update?

**Comment by ramya-rao-a** [comment]
`gocode` needs a rebuild after updating Go version.

Just to be on the safe side, you can run `Go: Install/Update Tools` which will update all the Go tools that the Go extension depends on 

We have #797 to track automatic updating of the said tools.

I have a plan in mind for this. Will look into it for the next update of the Go extension.

Now that Go 1.9 beta is out, I am guessing many more people would see this issue.

**Comment by atilkan** [comment]
I have the exact same issue. And this did not solve my problem.
maxOS Sierra
go version go1.8 darwin/amd64

**Comment by ramya-rao-a** [comment]
thanks for the update @atilkan and Happy Coding!

**Comment by atilkan** [comment]
Thanks to you @ramya-rao-a . You rock.

**Comment by mattwilson1024** [comment]
Just had the same problem. The following steps fixed it for me (the third step seemed necessary for me in addition to the above suggestions):
- Run Go: Install/Update Tools in VSCode
- `cd ~/go/bin`
- `./gocode close`

**Comment by jaysonesmith** [comment]
I just ran through @mattwilson1024 's steps and I'm all set, also! Thanks!
