### ISSUE TITLE
Build Workspace except vendor folder

### ISSUE THREAD

**Issue by RoarkeRandall** [Microsoft/vscode-go#1060]
Hello, currently the setting `"go.buildOnSave"` only allows the 3 options: `workspace`, `package`, and `off`. If you are using glide or the vendoring directory & you use the `workspace` option, then it will build the entire vendoring folder. The directories to build are not a flag so I'm not sure how to handle this scenario. 

For glide you would run `go build $(glide novendor)`, is there a way to replicate this behavior on save?

**Comment by ramya-rao-a** [comment]
Fixed with #1074

**Comment by ramya-rao-a** [comment]
The fix is out in the latest update (0.6.63) to the Go extension
