### ISSUE TITLE
`goreturns` use two much CPU time

### ISSUE THREAD

**Issue by xiaohui** [Microsoft/vscode-go#1061]
I run vscode Version 1.13.1 (1.13.1) 379d2efb5539b09112c793d3d9a413017d736f89 on my macOS 
Sierra， it always run about 60% CPU, and may be some time run 4 processes.
![image](https://user-images.githubusercontent.com/76129/27719565-e2321758-5d85-11e7-9bf7-3c1d6c90b216.png)

**Comment by ramya-rao-a** [comment]
Do you have autosave as well as formatOnSave on?

Do you see this happening on all your Go projects regardless of size?

**Comment by xiaohui** [comment]
1. yeah, I had set go.formatOnSave on but I still make file.autosave off. 
2. yeah, it happened no matter what size of projects.

**Comment by ramya-rao-a** [comment]
Did you recently upgrade to Sierra?
We have seen perf issues when users upgraded to Sierra. They had to update/rebuild all the dependent Go tools.

Can you run `Go: Install/Update tools` to update your Go tools and try again?

**Comment by AlekSi** [comment]
Removing $GOPATH/pkg and $GOPATH/bin, and reinstalling all tools is a good advice in general when updating OS or Go version.

**Comment by chaseadamsio** [comment]
I have had this issue too and I've noticed it happening when there's an error in my code. the goreturns has to be manually killed even after exiting code.

**Comment by orcaman** [comment]
Happens to me as well. Makes vscode unusable for go

**Comment by ramya-rao-a** [comment]
@orcaman Do you see any errors in the console? From the `Help` menu select `Toggle Devleoper Tools` and  then click on `Console`

**Comment by orcaman** [comment]
@ramya-rao-a I have updated my go version from 1.8x to 1.9x, re-installed all the tools (e.g. goimports etc.) and this seem to have solved the problem

**Comment by ramya-rao-a** [comment]
Closing this issue as most of the folks here have gotten the issue resolved. If anyone else sees formatting taking too much CPU, please log a new issue
