### ISSUE TITLE
No code completion for fmt

### ISSUE THREAD

**Issue by JeanMertz** [Microsoft/vscode-go#1062]
<img width="656" alt="screen shot 2017-07-01 at 14 49 19" src="https://user-images.githubusercontent.com/383250/27762167-c5985084-5e6c-11e7-9bfb-70af2f8b77b8.png">

I'm using the default configuration, but somehow the completion isn't working as expected.

I am seeing some other completions though (but no documentation, not sure if that 's intended):

<img width="746" alt="screen shot 2017-07-01 at 14 55 41" src="https://user-images.githubusercontent.com/383250/27762189-6c56009c-5e6d-11e7-96ad-00c40c7a72ab.png">

**Comment by JeanMertz** [comment]
I _do_ see the function interface inside the function parameters.

<img width="627" alt="screen shot 2017-07-01 at 15 11 17" src="https://user-images.githubusercontent.com/383250/27762323-21a0688c-5e70-11e7-9fcc-15b936014d02.png">

**Comment by JeanMertz** [comment]
The same happens for the `os` package (any package that is outside of my current project, it seems):

<img width="476" alt="screen shot 2017-07-03 at 16 06 38" src="https://user-images.githubusercontent.com/383250/27796262-b2106ae4-6009-11e7-84f1-0cc28797f552.png">

I disabled all plugins except for the Go plugin.

Here's my config with the above screenshot (I played around with different settings, but nothing seems to work):

```json
{
  "go.testOnSave": true,
  "go.coverOnSave": true,
  "go.coverageOptions": "showUncoveredCodeOnly",
  "go.useCodeSnippetsOnFunctionSuggest": true,
  "go.useLanguageServer": true,
  "go.languageServerFlags": [
    "-trace",
    "-logfile",
    "/tmp/lang.log"
  ],
  "go.formatTool": "goimports",
  "go.autocompleteUnimportedPackages": true,
  "go.gotoSymbol.includeImports": true
}
```

**Comment by JeanMertz** [comment]
Alright, I found some other (unrelated) issue which mentioned running `go get -u github.com/nsf/gocode`, that indeed solved the problem for me. Not sure why, since I haven't updated Go on this machine (it's a new machine, and has had the latest version of Go from the start).

**Comment by ramya-rao-a** [comment]
Hey @JeanMertz

Sorry, didn't get to this earlier. Am on vacation at the moment.

Not sure why gocode would start acting up like that. The readme in its repo should help.

Sometimes even closing gocode and reloading VSCode helps

**Comment by ramya-rao-a** [comment]
Closing this issue as autocomplete works for you now
