### ISSUE TITLE
http.Server.Shutdown() missing in code completion

### ISSUE THREAD

**Issue by embano1** [Microsoft/vscode-go#1066]
Not sure whether it´s just an issue on my local device, but the http://godoc.org/net/http#Server.Shutdown function is missing in auto-completion (see screenshot).

Is there a cache that needs rebuilding?
<img width="482" alt="shutdown" src="https://user-images.githubusercontent.com/15986659/27770696-9c929c62-5f43-11e7-931b-769987fb7307.png">

**Comment by zmb3** [comment]
I believe that func is new in Go 1.8. Are you running an old version of Go by chance?

**Comment by embano1** [comment]
Thx. Yeah, that was the first I checked :) (running v1.8.3). The code compiles fine, and VS Code accepts the function. It´s just that auto-complete does not work for this specific func...

**Comment by ramya-rao-a** [comment]
Try "gocode close" and then update gocode using "go get -u github.com/nsf/gocode"

**Comment by embano1** [comment]
Thx, this (almost) fixes it. The func is now recognised, however documentation and thus hinting is not.

![image](https://user-images.githubusercontent.com/15986659/27843395-612a18ae-6113-11e7-9a63-44452f03ef15.png)

**Comment by ramya-rao-a** [comment]
Can you try setting "go.docsTool" to "gogetdoc"?

**Comment by embano1** [comment]
Thank you. I did change the setting, without any difference.
What it´s really strange:

VSCode (with go version go1.8.3 darwin/amd64) recognises the Shutdown() function, even that the ctx argument is missing. However, if I right-click "Go to definition" it still says "No definition found...". Even more strange: if I open the source code for the Server struct (right-click-> go to def) and then search for Shutdown() or close(), there is no method? That´s why it can´t find it. However, I don´t get why is that? VSCode uses my go version (and thus stdblib), and recognises the Shutdown() function - but won´t find a definition? Like it´s pointing to an old source code for definitions, but during compile time it actually takes the right stdlib...super weird.

![image](https://user-images.githubusercontent.com/15986659/27853248-4b34f6f0-6162-11e7-8fb0-4f0b52de6dea.png)

**Comment by embano1** [comment]
OK, searching the issues for entries about "godef" and "stdlib" helped me fixing the issue.

Steps I took (not sure if all were necessary):

- close VSCode and gocode close
- go get -u github.com/rogpeppe/godef
- go get -u github.com/nsf/gocode (again, just to make sure)
- revert back to "go.docsTool": "godoc" (gogetdoc still doesn´t work)

Thx @ramya-rao-a for your help!

**Comment by ramya-rao-a** [comment]
The Go extension uses different set of tools for different features. 

The autocomplete is backed by the gocode tool.
The missing argument must be coming from running "go build"
The Go to Definition, hover info and signature/parameter help features are backed by the godef and godoc tools unless you have set go.docsTool to gogetdoc.

Am glad you are unblocked now. But am curious why gogetdoc didn't work for you for the Go to Definition feature.

**Comment by ramya-rao-a** [comment]
I am on vacation right now so don't have access to my mac.

@zmb3 can you take a look at why gogetdoc wouldn't have worked in the above scenario?

**Comment by zmb3** [comment]
There's not enough info here to say for sure. Sounds like some sort of
misconfiguration?

Do you have multiple versions of Go installed?  What's the output of 'go
env'?

**Comment by embano1** [comment]
Sorry, was travelling.

↳ go env
GOARCH="amd64"
GOBIN="/Users/mgasch/GO/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mgasch/GO"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/15/5y30b63d1vb0nk7r6pv_xn400000gp/T/go-build206403948=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

↳ ls -al `which go`
lrwxr-xr-x  1 mgasch  admin  25 14 Jun 11:15 /usr/local/bin/go -> ../Cellar/go/1.8.3/bin/go

**Comment by zmb3** [comment]
Nothing out of the ordinary there.  What's the absolute path of the file you're editing in that screenshot?

**Comment by ramya-rao-a** [comment]
@embano1 Another thing to try is to run both `godef` and `gogetdoc` from the command line for the same file and offset and see if they give different results

**Comment by ramya-rao-a** [comment]
I think the reason is that `Shutdown` needs pointer

![shutdown](https://user-images.githubusercontent.com/16890566/27991905-4d47f160-643a-11e7-99c9-1767f33751d3.gif)

**Comment by ramya-rao-a** [comment]
Closing this issue

- the autocomplete issue got fixed with updating the gocode tool
- the Go To Definition not working when using `gogetdoc` according to me is valid as the `ShutDown` method is defined on the pointer. When using the pointer, this works as shown in https://github.com/Microsoft/vscode-go/issues/1066#issuecomment-313903326

**Comment by embano1** [comment]
Thank you for your quick help.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
