### ISSUE TITLE
How do I pass arguments when I use vscode to debug a go program

### ISSUE THREAD

**Issue by Jamesxql** [Microsoft/vscode-go#1067]
My go program needs to receive the arguments passed from the command line. How do I pass these   args when I debug in vscode?

Like this: goapp -k1=v1 -k2=v2

**Comment by ramya-rao-a** [comment]
Have you created debug configuration in the launch.json file?

One of the fields in the debug configuration is "args" which you can use to pass the arguments

**Comment by Jamesxql** [comment]
I found answer in [this issue](https://github.com/Microsoft/vscode/issues/2167)

Anyway, thank you.
