### ISSUE TITLE
go.coverOnSave breaks problems view

### ISSUE THREAD

**Issue by christoph-k** [Microsoft/vscode-go#1068]
vscode-version: 1.13.1
vscode-go-version: 0.6.62
tools: updated today
os: ubuntu 16.04.2 lts
go-version: 1.8.3

If i set go.coverOnSave to true coverage is not shown.
What's really weird is the fact that it seems to break the problems view. New problems are shown but in case i fix them they don't disappear until there is a new problem. Same behaviour with the red line under the invalid statements.
I already updated all tools and ran "gocode close" but it does not seem to make a difference.

**Comment by ramya-rao-a** [comment]
I am able to get coverage and the problems go away after fixing as well

![cover](https://user-images.githubusercontent.com/16890566/27991825-453b9bcc-6438-11e7-8b2c-c50e6ca0ab9d.gif)

Can you share your settings?

**Comment by christoph-k** [comment]
I don't know why but after another Ubuntu and Go-Tools Update it works again.
