### ISSUE TITLE
GoReturns/Goimports/Gofmt doesn't seem to run and I get an "unknown" error

### ISSUE THREAD

**Issue by levigross** [Microsoft/vscode-go#107]
Hello,

First of all, thank you for taking the time to write this plugin. I really enjoy using it!

When I write code, `GoReturns/Goimports/Gofmt` doesn't run at all on save (it used to but now it doesn't). Additionally, I am getting an error (but I cannot find the log file to figure out what type of error it is) that may or may not be related to this. 

This may be related to the fact that my project doesn't build (it is a library) but I don't know

![screen shot 2015-11-26 at 16 02 34](https://cloud.githubusercontent.com/assets/80920/11430595/257cd538-9457-11e5-9f9e-e37e5c6847d6.png)

**Comment by lukehoban** [comment]
The plugin doesn't yet have any support for format-on-save (see #14).  So unless you are doing an explicit `Format Document`, I expect that is not what's causing the problem.

If you fully quit out of Code, then reopen, can you pinpoint exactly when you see this error?  Do you see it if you haven't yet opened any `.go` files?  Do you see it only when you hover over a Go identifier?  Do you see it when you hit save?

**Comment by lukehoban** [comment]
One more note - did you intentionally change the font in the editor?  That font (non-fixed width) is often an indication that Code is not initializing correctly.

**Comment by lukehoban** [comment]
Closing this out for now, as there's no current action we can take.  Please reopen if more details are available to help pin this down.
