### ISSUE TITLE
Spawns cc1 and hogs up CPU

### ISSUE THREAD

**Issue by abs-zero** [Microsoft/vscode-go#1070]
When I import [gotk3](https://github.com/gotk3/gotk3), which depends on gcc to compile, every time I save a file (reformat occurs), it spawns `cc1` process. Eventually, I end up with this mess:
![2017-07-06-141411_208x91_scrot](https://user-images.githubusercontent.com/16974688/27902599-09fad854-6256-11e7-8a6a-7381ad728a49.png)

Also even after I close vscode, those processes won't be terminated.

OS: Manjaro Linux 17.0.1 Gellivara

**Comment by ramya-rao-a** [comment]
Does it happen when you have `go.formatOnSave` set to `false`?

**Comment by abs-zero** [comment]
It is weird that I can't reproduce this error in any way anymore. I guess it was a problem with my machine. A reboot might have fixed it.

**Comment by ramya-rao-a** [comment]
No worries, I'll close it.
