### ISSUE TITLE
Variable block declaration syntax highlighting broken by call assignment

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1071]
Can be seen with this syntax:

```go
var (
	AAA = foo() // AAA is correctly light blue
	BBB string  // BBB is incorrectly white; it should be light blue like AAA
)
```

*Note: GitHub syntax highlighting for the above doesn't show the problem.*

See the screenshot:

![screen shot 2017-07-07 at 5 04 33 pm](https://user-images.githubusercontent.com/63830/27980711-8c6333c8-6336-11e7-85b4-f5cd2fdf0e7f.png)

VS Code: Version 1.13.1 (1.13.1), 379d2efb5539b09112c793d3d9a413017d736f89
OS: macOS Sierra 10.12.5 (16F73)

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#130
