### ISSUE TITLE
Go related suggestions should not show up in multi line comments

### ISSUE THREAD

**Issue by diegobernardes** [Microsoft/vscode-go#1072]
Single and multi line comments have different behaviours when we type a dot. Single line is better and make more sense. Multi line annoy me everytime i need to write a big comment because of the dot at the end of the lines.

![gif](https://user-images.githubusercontent.com/14483/27981266-289c64d4-6360-11e7-99a6-655eef813fcf.gif)

**Comment by ramya-rao-a** [comment]
Suggestions in single line comments are not shown due to this https://github.com/Microsoft/vscode-go/blob/cf6a40d3b929f1d1fa4b247f044349f25c45aeec/src/goSuggest.ts#L59

We could use regex to figure out if the cursor is inside a multi line comment and skip calling `gocode` for suggestions as well. 

PRs are welcome

**Comment by thomasdarimont** [comment]
I gave this a spin and I think I got something working now (also my first contribution to vscode-go) :)

**Comment by thomasdarimont** [comment]
PR is #1116

**Comment by tohjustin** [comment]
Hi @ramya-rao-a , is this issue still available? 

I can start working on making changes to https://github.com/ramya-rao-a/go-outline based on your most recent feedback in https://github.com/Microsoft/vscode-go/pull/1116#discussion_r133992917.

**Comment by ramya-rao-a** [comment]
@tohjustin Yes, it is still available, but I am concerned about the idea of using `go-outline` everytime we need a completion.

We have seen the Outline view feature in the explorer call `go-outline` for every change in the file and it affects the performance in some code bases.

@stamblerre Is `gocode` aware of whether or not the given position is inside comments or not? If it is aware, then I'd rather pass another flag to `gocode` to exclude completions inside comments

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre!

I have logged https://github.com/mdempsky/gocode/issues/87 for tracking purposes.

@tohjustin I'll be closing this issue as it would certainly be better to get this feature from gocode.
Feel free to pick up any other issue here.

**Comment by ramya-rao-a** [comment]
To get this fix, please run `Go: Install/Update Tools`, select `gocode` and press `Ok` to update `gocode`

Thanks @tohjustin!
