### ISSUE TITLE
GOPATH environment variable seems to be ignored

### ISSUE THREAD

**Issue by NobbZ** [Microsoft/vscode-go#1075]
When I tried to open VSCODE using `GOPATH=$(pwd)/go code .` vscode didn't seem to pick that up. according to my observations it still searched in my regular GOPATH for packages.

**Comment by ramya-rao-a** [comment]
This works for me...

When you are trying this, is there any other instance of VS Code open?
If yes, then the process running new VS Code window will have env vars from the already opened window

**Comment by NobbZ** [comment]
I will check later this day if there are other instances open or phantom processes.

**Comment by NobbZ** [comment]
I chechked it, there are no other instances running. I did reboot to make sure.

Version info:

```
Version 1.13.1
Commit 379d2efb5539b09112c793d3d9a413017d736f89
Date 2017-06-14T18:18:03.540Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

Go plugin 0.6.62.

go itself: go version go1.8.3 linux/amd64

To make sure it wasn't something in my shell I also tried to export the new GOPATH and I tried bash and and zsh.

**Comment by ramya-rao-a** [comment]
Can you open the console (Run `Developer: Toggle Developer Tools`) and check the value of `process['env']['GOPATH']` ?

Also, do you have any of `go.toolsGopath` or `go.gopath` set?

**Comment by NobbZ** [comment]
Its the wrong, old GOPATH as I set it in my `.zshrc` instead of the current one. `go.gopath` was unset for the experiments, `go.toolsPath` is set to my regular GOPATH, to avoid cluttering this minified workspace. But removing it wont change anything, I have tried that too.

Also I did some further testing:

I added `export GOFAST=test` to my `.zshrc`, saved it and did not restart my terminal but opened VS-Code from a terminal which hadn't sourced the altered `.zshrc`. Still, VS-Code knew that variable and the “correct” value, so it seems, that vscode sources my `.zshrc` for some reason…

**Comment by ramya-rao-a** [comment]
@Tyriar would you know why the env vars from `.zshrc` gets used instead of the one that is set in the terminal from where code is bing launched?

**Comment by Tyriar** [comment]
I think @joaomoreno knows the most about us fetching the environment on launch.

**Comment by joaomoreno** [comment]
@NobbZ What does `which code` return?

**Comment by NobbZ** [comment]
Actually nothing ;)

My package manager installed `code` as `visual-studio-code`, I just substituted above for beeing conform to the rest of the world ;)

```plain
$ which visual-studio-code
/usr/bin/visual-studio-code
```

**Comment by joaomoreno** [comment]
Interesting. So what are the contents of `/usr/bin/visual-studio-code`?

Is this from our official Debian/RPM packages?

**Comment by NobbZ** [comment]
Its a community ebuild for gentoo. There are no official builds available.

It does only contain a single line `exec /opt/visual-studio-code/code`.

The started executable is ELF 64-bit LSB executable according to `file`.

Since I'm only connected via SSH to my home-PC right now, I will check in about 8 to 12 hours if the problem persists when I do start that executable directly.

**Comment by joaomoreno** [comment]
Yep, that's the real problem. It should point to `/opt/visual-studio-code/bin/code`. You might want to file that as an issue to the gentoo peoples.

**Comment by NobbZ** [comment]
Thank you for your help, I'll file an issue there.

**Comment by NobbZ** [comment]
FYI: `GOPATH=$(pwd)/go /opt/visual-studio-code/bin/code` works fine.
