### ISSUE TITLE
Documentation for go.gopath wrong?

### ISSUE THREAD

**Issue by NobbZ** [Microsoft/vscode-go#1076]
In the wiki about GOPATH the following is written:

> Setting `go.gopath` in User settings overrides the GOPATH that was derived from the [environment variable]. Setting `go.gopath` in Workspace settings overrides the one from User settings.

While documentation of the setting `"go.gopath"` as available in VSCode states:

> Specifies the GOPATH to use when no environment variable is set.

Which one is correct and describes actual behaviour?

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode-go/commit/1ec6d7cfd4c4846e77739ce83eae5ed0482a7425

The first one is the right one
