### ISSUE TITLE
Running vsce package with vsce > 1.25.1 fails; requires https img src

### ISSUE THREAD

**Issue by myitcv** [Microsoft/vscode-go#1077]
Using 9c59b60 of `vscode-go`:

```
npm install
npm install vsce@1.29.0 --save-dev

./node_modules/.bin/vsce package
```

gives the output (eliding the `npm` output):

```
Executing prepublish script 'npm run vscode:prepublish'...

> Go@0.6.62 vscode:prepublish /home/myitcv/dev/vscode-go
> tsc -p ./

Error: Images in README.md must come from an HTTPS source: http://i.giphy.com/xTiTndDHV3GeIy6aNa.gif
```

Is `vscode-go` supposed to work with the latest version of `vsce` or is it effectively pinned against a version?

**Comment by ramya-rao-a** [comment]
Fixed.

I love it that you are trying to side load the vsix from master

Do you mind helping me out with testing a few features?
Am planning to release an update tomorrow and would really appreciate an extra set of eyes :)

**Comment by myitcv** [comment]
Sure thing 👍

**Comment by myitcv** [comment]
Might also be worth testing the `./node_modules/.bin/vsce package` step in the CI with "known" versions of `vsce`?

**Comment by ramya-rao-a** [comment]
What step are you referring to?

**Comment by myitcv** [comment]
@ramya-rao-a - my apologies. I accidentally muted the email thread in Gmail 👎 

I've actually realised my suggestion is not something that belongs within `vscode-go` - more an issue for builders of the package. So nothing to do here :)

**Comment by ramya-rao-a** [comment]
got it. Happy coding!
