### ISSUE TITLE
helpers for porting code from C/C++?

### ISSUE THREAD

**Issue by am21** [Microsoft/vscode-go#1079]
In the process of porting code from C/C++, I often have to rename constants or `#define` from `SOME_NAME` to `SomeName`, i.e. use camelcase to make golint happy.  I ended up going back to my favorite Emacs with `string-inflection` package so I can do the conversion in one keystroke.

Would be very cool to have the same kind of symbol renaming directly from a popup menu.

Or maybe there is already a way to do that and I missed it?

**Comment by ramya-rao-a** [comment]
Try https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case
