### ISSUE TITLE
can't debug

### ISSUE THREAD

**Issue by henjue** [Microsoft/vscode-go#108]
waring "vscode property mode is not allowed"

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch web.go",
			"type": "go",
			"request": "launch",
			"program": "web.go",
			"mode": "debug",
			"stopOnEntry": false,
			"env": {},
			"args": [],
			"cwd": "."
		}
	]
}
```

**Comment by lukehoban** [comment]
Do you have the latest version of the Go extension installed?

**Comment by timeloveboy** [comment]
same with @henjue 

{
	"version": "0.1.0",
    "configurations": [
        {
            "name": "Launch main.go",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": ".",
            "env": {},
            "args": []
        }
    ]
}

Configured debug type 'go' is not supported.

in mac os x 10.11 ei caption

dlv-cert  install OK

**Comment by lukehoban** [comment]
@timeloveboy Could you confirm that you have updated the `vscode-go` plugin to the latest version?  `Extensions: Install Extension` and make sure that if there is a cloud+arrow icon there to download it you have clicked that?  If you are up to date you should see an X icon instead of the cloud.  The current version if `0.6.15`.

**Comment by timeloveboy** [comment]
thanks，the resaen is i download a old vscode-go estexsion.now it works~

**Comment by lukehoban** [comment]
Good to hear. Closing this out now as I expect that was the same for @henjue.

**Comment by asaf** [comment]
Hey,

I'm having the same error, `Configured debug type 'go' is not supported.`, Using version _0.6.43_,

Any clue?

Thanks

**Comment by thessem** [comment]
@asaf I'm having the same issue as you, I've created a new issue over at https://github.com/Microsoft/vscode-go/issues/445
