### ISSUE TITLE
Autoindent inserts extra undo item, requires double undo after paste

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode-go#1083]
Here's an example of pasting something, then hitting cmd-Z to undo. As you can see, it first undoes one indentation, then undoes the paste. That's not right, since my paste was a single command, so a single undo should undo it.

![vsc](https://user-images.githubusercontent.com/50314/28082497-eee3dfe0-6672-11e7-998a-8715249ec60b.gif)

Steps:

1. Copy something.
2. Go into a block that has a deeper indentation level.
3. Hit cmd-V.
4. Hit cmd-Z.
5. The paste remains, but one indent level is subtracted.

**Comment by OneOfOne** [comment]
Wrong repo, this belongs on https://github.com/Microsoft/vscode/issues

**Comment by atombender** [comment]
Apologies, Safari autocompleted the URL and I didn't notice where I landed.
