### ISSUE TITLE
Configuring intellisense 'Run Test' behavior

### ISSUE THREAD

**Issue by amkoehler** [Microsoft/vscode-go#1086]
I recently made a change that affected the build tags needed to run unit tests. This broke the `run test | debug test` buttons that are above each of my unit test functions, because those aren't configured to use the appropriate build tags. Is there a way to configure this? For example, if I click 'Run Test' for a function this is the command that executes:

```bash
/usr/local/bin/go test -timeout 30s -tags  -run ^Test_Login_ShouldSucceed$
```

Is there a way for me to configure what is set after `-tags`? Since it's empty by default it would appear that I can do this somewhere.

**Comment by ramya-rao-a** [comment]
Yes, you can set the build tags in the setting `go.buildTags` which then gets used by the extension to when building and testing the files

**Comment by amkoehler** [comment]
Thank you!

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
