### ISSUE TITLE
Remote debug

### ISSUE THREAD

**Issue by ssadok** [Microsoft/vscode-go#1089]
Hi,
I user vagrant and i start on vagrant
$ dlv debug --headless --listen=:2345 --log
and my launch my json :
![image](https://user-images.githubusercontent.com/1891667/28200994-e269993a-6866-11e7-9c2e-867e3c0d4860.png)
like : https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#remote-debugging

but vscode start on local he is not connected to the port in vagrant : 
config.vm.network :forwarded_port, guest: 2345, host: 2345, id: "debuggolang", host_ip: "localhost", auto_correct: true

when i try to put him in convention format : 

![image](https://user-images.githubusercontent.com/1891667/28201062-31e3b450-6867-11e7-9ea4-c55ae1a391b2.png)

break point doesn't stop

![image](https://user-images.githubusercontent.com/1891667/28201104-5fe86b84-6867-11e7-98aa-e77ef730da5d.png)

Regards

**Comment by rpfister51** [comment]
This seems similar to a problem I reported in issue 1138.  @ramya-rao-a shared a link to an update there which solved the problem for me.  @ssadok , you might want to try it.

**Comment by ramya-rao-a** [comment]
@ssadok There is no difference between the 2 screenshots for the launch.json

Can you try using delve from the command line and see if you are able to hit the breakpoint?

**Comment by ramya-rao-a** [comment]
@ssadok  Closing this issue as we havent heard back you with answers for the questions in https://github.com/Microsoft/vscode-go/issues/1089#issuecomment-326439708
