### ISSUE TITLE
Issues with debugging goroutine when main routine is blocked

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-go#1091]
_From @firelizzard18 on July 15, 2017 8:4_

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.3.4|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-theme-onelight|akamud|2.0.2|
|vscode-npm-script|eg2|0.2.0|
|task-master|ianhoney|0.1.39|
|quicktask|lkytal|2.8.1|
|Go|lukehoban|0.6.62|
|debugger-for-chrome|msjsdiag|3.1.6|
|Material-theme|zhuangtongfa|2.9.3|;

---

Steps to Reproduce:

1. Have a go program
2. Run a goroutine
3. Block the main routine
4. Break in the goroutine
5. Try to step through the goroutine

---

When the main routine is blocked and I try to step through a 'worker' goroutine, on **EVERY SINGLE BLEEPING STEP** VSCode switches the currently viewed frame to the main routine. So on *every step* I have to reselect the worker goroutine in the 'call stack' panel. It's quite painful.

Maybe this is an issue with delve? Not sure.

_Copied from original issue: Microsoft/vscode#30752_

**Comment by weinand** [comment]
_From @firelizzard18 on July 15, 2017 8:6_

Update: since the main thread is blocked, I can step twice and it goes back properly to the goroutine. So at least there's that.

Update: nevermind, that doesn't really work. At least not in a useful and reliable way.

**Comment by ramya-rao-a** [comment]
@firelizzard18 

- Can you provide a simple program where I can try and repro this?
- Can you also try the same from the command line using delve so that we can eliminate the case that this is a delve problem?

**Comment by firelizzard18** [comment]
I'm having trouble reproducing this, even with my original scenario. I guess close it for now. I'll reopen or open a new issue if I'm able to reproduce it.

**Comment by ramya-rao-a** [comment]
Thanks @firelizzard18 
Like you said, lets close it for now

Happy Coding!
