### ISSUE TITLE
Autoformating (ext v. 0.6.62) broken in Visual Studio Code (v. 1.14.1)

### ISSUE THREAD

**Issue by jakobhviid** [Microsoft/vscode-go#1093]
Autoformating seems to be broken for this extension (v. 0.6.62) in Visual Studio Code (v. 1.14.1)

**Comment by ramya-rao-a** [comment]
Do you mean formatting on save?
It works fine for me.

- Does explicit formatting work? i.e Right-click inside the document and choose "Format Document"
- Any errors in the console? Run `Developer: Toggle Developer Tools` to open the console
- Is this a regression? i.e. did it work fine before and stopped with a recent update? If yes, then was the update to the extension or vs code or your OS or Go?
- Does building and linting work as expected on save?

**Comment by jakobhviid** [comment]
Hello. 

I mean formatting on save, but also explicit formatting.
Yes it is a regression that happened after the Visual Studio Code Update.

In the meantime though, i have imported the settings to another computer using the CodeSync Extension, and everything works as expected. I am closing this issue as i only have the problem on 2 of 3 computers. The problem must be localized.

Thank you for your time.

**Comment by ramya-rao-a** [comment]
No problem @jakobhviid, thanks for looping back and updating the issue.
And Happy Coding!

**Comment by jakobhviid** [comment]
Thank you. Unfortunatly i still seem to have this problem. 

I: 
1. removed VS code, and all settings files from the file system. Removed all configuration and everything left.
2. reinstalled VS code from scratch.
3. verified all settings were gone.
4. updated golang (just to make sure)
5. installed the vscode-go extension
6. restarted VS code.
7. Changed a go file and saved (nothing happened)
8. tried to force format using alt + shift +f (nothing happened)
9. repeated 7 and 8 with the developer console open and nothing happened.
10. after a while of doing nothing though i got this error: 

[Extension Host] (node:12592) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
h.logExtensionHostMessage @ extensionHost.ts:320
(anonymous) @ extensionHost.ts:176
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

11. I verified formatting shortcuts really are alt + shift + f (verified)
12. Checked the go log and got this:

Finished running tool: C:\Users\jakob\Dropbox\Projects\Go\bin\golint.exe

Finished running tool: C:\Program Files\Go\bin\go.exe vet

Finished running tool: C:\Program Files\Go\bin\go.exe build -i -o C:\Users\jakob\AppData\Local\Temp\go-code-check -tags ""

13. lost!

It is almost as if nothing ever runs when saving.

**Comment by ramya-rao-a** [comment]
> It is almost as if nothing ever runs when saving.

The fact that you get the "Finished running tool..." in your output is proof that the save is triggering build, lint and vet successfully.
To confirm that, can you introduce an error in your go file, save and see if you get the red squiggles. If yes, then the save has triggered the build and you are seeing the results

>  DeprecationWarning: os.tmpDir() is deprecated

That is unrelated

Can you try setting `go.useDiffForFormatting` to `false`?
We have seen some cases where running the formatting tools using the `-d` flag doesn't work well for some users

**Comment by jakobhviid** [comment]
Hello again.

yes the red squiggles are there.

I tried putting in the setting "go.useDiffForFormatting": false, and the formatting seems to work now! 

Do you what what the cause is for this?

From my perspective the issue is solved. Feel free to close the issue if you feel it isn't something that needs to be changed in the code.

Thank you so much for your help!

**Comment by ramya-rao-a** [comment]
> Do you what what the cause is for this?

That indeed is a mystery.

We logged an upstream issue https://github.com/sqs/goreturns/issues/28 but it got closed as environment issue.

Try running `goreturns` with and without the `-d` flag on an unformatted file.
You will see that you get expected output in the former, but you won't get the diff in the latter.

What OS are you on? `goreturns` tries to use the `diff` tool available on the PATH.
So maybe its an incompatibility issue between the diff tool and `goreturns`

There is nothing more we can do from the extension side though.
So closing this issue.

**Comment by jakobhviid** [comment]
I am not really sure what the output of goreturns should be, but i get this: 
> goreturns -d main.go
diff main.go gofmt/main.go

The goreturns was NOT in the path. I have added it but with same results. (after a reboot of course)

Regarding OS i am running windows 10 on version 1703, build 15063.413

With the setting you provided everything works fine, so i am leaving the issue at this point. 

Thanks for your help!
