### ISSUE TITLE
Go to definition does not work on functions

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode-go#1094]
In current version Ctrl + click or rightclick+"go to definition" does not work anymore.
"No definition found for xyz".

**Comment by ramya-rao-a** [comment]
@DasJott More details would help in looking into the problem. Please provide

- A sample code or video or gif
- Does it not work at all or only for functions from std library or third party code? Have you tried on structs or variables?
- Values for settings `go.docsTool` and `go.useLanguageServer`
- Version of VS Code, the Go extension, and Go itself
- OS

The `Go to definition` works as expected for me.

**Comment by DasJott** [comment]
I made a video where I am pressing the Ctrl Button while hovering with the mouse above the code.
The functions within the same file seems to be recognized. A function within an other file is not working, but its package. A click on that jumps to the import of that package. Not helpful ;)
[definition_issue.mp4.zip](https://github.com/Microsoft/vscode-go/files/1158303/definition_issue.mp4.zip)

"go.docsTool": "godoc" (and it is installed)
"go.useLanguageServer": false

other custom settings:
```
	"go.buildOnSave": true,
	"go.lintOnSave": true,
	"go.vetOnSave": true,
	"go.buildFlags": [],
	"go.lintFlags": [],
	"go.vetFlags": [],
	"go.coverOnSave": false,
	"go.useCodeSnippetsOnFunctionSuggest": false,
	"go.formatOnSave": true,
	"go.formatTool": "goreturns",

```

go version: go1.8.3 linux/amd64

VSCode:

Version 1.14.1
Commit 2648980a697a4c8fb5777dcfb2ab110cec8a2f58
Date 2017-07-13T19:12:01.887Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

Extension: 0.6.62

OS:
Arch Anywhere with DDE

**Comment by ramya-rao-a** [comment]
I cant play either of your videos (the one you linked here and the one in your other issue on gocode)
Can you upload a gif instead?

Can you also try to set `go.docsTool` to `gogetdoc` and see if that makes a difference?

**Comment by DasJott** [comment]
![definition_issue](https://user-images.githubusercontent.com/6298761/28404435-901f91f8-6d29-11e7-943c-fd4ffaf1583a.gif)

This was using godoc.

Surprisingly gogetdoc works fine, except it seems a little slower recognizing a clickable item while pressing ctrl.

**Comment by DasJott** [comment]
This is shown in the dev console using godoc while hovering on a function when pressing ctrl (which is not working)
![definition_issue](https://user-images.githubusercontent.com/6298761/28404836-2d29ccd8-6d2b-11e7-9c37-cd5ad891776c.png)

**Comment by ramya-rao-a** [comment]
And when using `godoc`, Go to Definition works for say the `fmt.Println`?

**Comment by DasJott** [comment]
When using `godoc` while typing `fmt.` it only suggests `PANIC`.

**Comment by DasJott** [comment]
![deepin-screen-recorder_select area_20170721082819](https://user-images.githubusercontent.com/6298761/28451634-ab814fb6-6dee-11e7-92a5-d1517ace1fe0.gif)
Using godoc.

**Comment by ramya-rao-a** [comment]
Wow,

ok last thing I have to say is change `go.docsTool` to `godoc`, run `Go: Install/Update tools` so that all your tools are updated and rebuilt and try again.

If it still doesn't work then my suggestion is to use gogetdoc or you can also try out the new language server by setting `go.useLanguageServer` to `true`

**Comment by ramya-rao-a** [comment]
@DasJott Do you still have this issue?

**Comment by DasJott** [comment]
Seems to work now. Can not reproduce anymore. Will close it for now.

**Comment by ramya-rao-a** [comment]
Thanks @DasJott
