### ISSUE TITLE
Intellisense for functions of packages does not work

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode-go#1095]
In current version if I use e.g. `log "github.com/Sirupsen/logrus"` and type log. there is only one function suggested, not all. Not even those, I used before.

That worked once and was nice. Now I have to guess function names of packages again...

**Comment by ramya-rao-a** [comment]
Basically you are saying that when you provide an alias for an imported package, you don't get suggestions for the functions in the package?

I tried this and it works just fine for me.

Suggestions are provided by the `gocode` tool.

Can you close all VS Code windows, run `gocode close`, open VS Code and try again?

**Comment by DasJott** [comment]
Yup, If I type the package or an alias for a package (does not matter), there are no suggestions on typing a dot. On trying Ctrl+Space it says "No suggestions available".
Here is a video of just typing.
[gocode_issue.mp4.zip](https://github.com/Microsoft/vscode-go/files/1158269/gocode_issue.mp4.zip)

Maybe I need to start a service myself on Arch?

go version: go1.8.3 linux/amd64

VSCode:

Version 1.14.1
Commit 2648980a697a4c8fb5777dcfb2ab110cec8a2f58
Date 2017-07-13T19:12:01.887Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

OS:
Arch Anywhere with DDE

**Comment by ramya-rao-a** [comment]
Do you get suggestions in other cases? Say for a local variable?

With VS Code open and you typing Go code, can you check if there is an process called "gocode" active in your machine?

We use https://github.com/nsf/gocode for giving completions in the Go extension.

Did you try closing all VS Code windows, run gocode close, open VS Code and try again?

**Comment by DasJott** [comment]
This gif pretty much explains it.
![suggest_godoc_issue](https://user-images.githubusercontent.com/6298761/28405285-efac13fa-6d2c-11e7-8169-d7e4dda55f94.gif)

The dev console stays empty meanwhile.

Yes, I already tried that and it did not change anything. :-/

**Comment by ramya-rao-a** [comment]
That clearly shows gocode is not working at all for you.

Can you run `gocode close` and then `go get -u github.com/nsf/gocode` to update and rebuild the `gocode` instance you have?

**Comment by DasJott** [comment]
Did do all the steps. Didn't solve anything. Strange thing...

Is there any service I need to start manually on arch?

**Comment by DasJott** [comment]
> That clearly shows gocode is not working at all for you.

True, but it is there:
![gocode_help](https://user-images.githubusercontent.com/6298761/28451888-3fa67e18-6df0-11e7-9ad4-3157d0e26bb9.png)

**Comment by ramya-rao-a** [comment]
I don't know much about arch to say if it needs anything special

Is there any way to see currently running processes?
If there is, the open VS Code, start typing some gocode, you should see a gocode process running

**Comment by ramya-rao-a** [comment]
@DasJott Do you still have this issue?

**Comment by DasJott** [comment]
I am sorry, I was on vacation a few weeks. 
Was testing it a minute ago and it seems to work now. Whatever happened.

Thank you!

**Comment by ramya-rao-a** [comment]
Thanks @DasJott
