### ISSUE TITLE
IntelliSense issue with func keyword/snippet

### ISSUE THREAD

**Issue by fishnux** [Microsoft/vscode-go#1097]
Whenever I type "func", IntelliSense gives me two options:
 - A keyword
 - A snippet prefix

![Screenshot](http://i.imgur.com/LflQGFd.png)
[Screen recording](https://i.imgur.com/dHYqgPp.gifv)

How do I get rid of the "func" keyword?

With the Go extension disabled:
![Screenshot](http://i.imgur.com/554ClMl.png)

Links that might be useful:
https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions

**Comment by ramya-rao-a** [comment]
There is no option to get rid of the keyword
But there is an option to make the snippet come first

Set `editor.snippetSuggestions` to `top`

**Comment by fishnux** [comment]
That works, thanks!
