### ISSUE TITLE
Use/document  gocode "autobuild" to fix missing code completion.

### ISSUE THREAD

**Issue by klauspost** [Microsoft/vscode-go#110]
It seems like gocode uses binaries of **installed** packages `go install <package>`, which makes code completion unable to locate the package if only the source of the package is installed.

To remedy this gocode has the [`autobuild=true` option](https://github.com/nsf/gocode#options), which will automatically build any "missing" packages.

vscode-go should either mention this setting in the documentation, ie. execute `gocode set autobuild true`, or enable it automatically. The only downside from enabling it automatically is that a console window shows up briefly when a package is used the first time.

**Comment by lukehoban** [comment]
@klauspost Could you give a pointer to a codebase I could try to repro the problem?

**Comment by klauspost** [comment]
If you rename the `$GOPATH\pkg` folder it should happen.

**Comment by lukehoban** [comment]
I just tried turning this on, and when I work in the `Delve` codebase, completion lists start taking several seconds to show up.  I think that makes this a non-starter as the default setting.

I could add a note in the README, but given the slowdown not sure it makes sense to encourage folks to turn this on.

Also, won't the user still see errors from compile-on-save if they haven't built the dependencies?  I'm still a bit unclear on what the real-world setup looks like where this is a problem that just adding 'autobuild true' fixes in a meaningful way.

**Comment by klauspost** [comment]
>I just tried turning this on, and when I work in the Delve codebase, completion lists start taking several seconds to show up.

It should only be a once-per-package. The standard `go get <package>` will not compile the .a files for the autocomplete.

> Also, won't the user still see errors from compile-on-save if they haven't built the dependencies? 

All the go tools just compiles what isn't installed on the fly, so ordinarily you don't notice it, compilation just takes a fraction of a second longer.

But you can test it out. It works ok for me, except for the very annoying console window that pops up and grabs focus. That is why I left the final decision to you :)

**Comment by klauspost** [comment]
It also seems to behave "stupid" when you edit a test file in the same folder, but with a different package name than the package.

This will make it "rebuild" on almost every keystroke. It seems like adding a FAQ entry is the safest way to go for now. Maybe this will be better after the [potential rewrite](https://github.com/nsf/gocode/issues/307) gocode seems to need.

**Comment by ironcladlou** [comment]
The current vscode-go actually uses autobuild=true by default, and the setting is now configurable (https://github.com/Microsoft/vscode-go/pull/283). Can this issue be closed?

**Comment by ironcladlou** [comment]
Although I still question whether using the default of true is a good idea- perhaps some docs would be warranted.

**Comment by alienth** [comment]
The autobuild=true option is considered experimental by the gocode author. Doesn't seem like there will be any improvement on that feature. The author desires to rebuild gocode for several reasons, and one of them is to read source files for completion reasons. Seems like he doesn't have the time to address this at the moment: nsf/cocode#307
