### ISSUE TITLE
Put Code Lens test links in the context menu instead of the editor buffer

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1101]
The test Code Lens links (debug/run test) disrupt the visual flow of the numbered lines. Why not put those commands in the context menu instead? If the concern is discoverability, maybe highlight the line or something else that doesn't affect the actual layout to indicate there's something for Code Lens for a particular line?

**Comment by Ianwww** [comment]
I also notice that when I go from a test file to a non test file and then back i'm not returned to where I left of in the test file.  This has something to do with those test code links. Do you experience this?

**Comment by willfaught** [comment]
@Ianwww I haven't seen that myself.

**Comment by didenko** [comment]
1. IMHO the extra visual separation between tests is nice.
2. I prefer a single-click interface with less fiddling, especially when collaborating on a computer with a poor pointing device (like some trackpads, which require finger gymnastics for right click)
3. Is this a #1088 duplicate?

**Comment by willfaught** [comment]
@didenko #1088 turned into a workaround for having the run/debug test commands in the context menu instead. This issue is about making that what Code Lens does out of the box.

**Comment by didenko** [comment]
@willfaught So this is indeed a duplicate entry of the #1088 issue. Seems that you do not like which way the resolution went hence opened the same issue second time. Otherwise the conversation could have been continued in #1088.

Although it may be OK to move the run/debug links to a submenu **as a configurable property**, I definitely vote for leaving the default setting ass it is now. That is both for being newcomer friendly and diverse-interface-friendly.

**Comment by willfaught** [comment]
@didenko The resolution required disabling Code Lens entirely, which I think is unreasonable.

**Comment by willfaught** [comment]
A configurable property to present Code Lens commands in the context menu instead of the buffer would be great.

**Comment by ramya-rao-a** [comment]
Sorry, am late to this party

So this issue is about the changing the UI behavior of code lens in general so that they do don't take up a whole line and so don't disrupt the flow of numbered lines. Did I sum it up right?

**Comment by willfaught** [comment]
Basically. This ticket doesn't prescribe general changes to Code Lens as the solution, but that might be what's required to accomplish it.

**Comment by ramya-rao-a** [comment]
In that case, it is beyond the capabilities of this extension.

VS Code extensions in general cannot make any UI changes to the product. It can work inside the confines of what the core provides.

**Comment by willfaught** [comment]
Since the other ticket is tracking work on putting those things in the context menu, I'll close this then.
