### ISSUE TITLE
How to get the coverage ui to update when running test on the package

### ISSUE THREAD

**Issue by iarief** [Microsoft/vscode-go#1104]
Hi, could someone explain to me what is the correct workflow if i want the coverage ui to update everytime i executed test package? It seems that there used to be an option to test with coverage, now there's just a toggle to test coverage in current package, and when i want to visually see the coverage change, i need to toggle it on and off again.

Executing test the package doesn't use coverage after the toggle coverage has been executed.

steps to reproduce
1. create a new .go file containing functions with branching conditional
2. create a test to test that file
3. toggle coverage and you can see which line is covered or not
4. fix the test file to cover more of it
5. test the package again (won't show coverage, need to toggle the coverage on and off again for it to update)

**Comment by ramya-rao-a** [comment]
That's a good catch @iarief 

I have added feature to run and show the test coverage after running the Test Package command.
That should help.

The feature will be out in the next update to the Go extension which should be sometime this week

**Comment by iarief** [comment]
@ramya-rao-a thanks!

**Comment by ramya-rao-a** [comment]
@iarief Can you help in testing it out?

All you have to do is
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.visx` from the location where you downloaded the above file
- Restart vs code and you should be good to go

**Comment by iarief** [comment]
@ramya-rao-a sure, please wait a bit

**Comment by iarief** [comment]
@ramya-rao-a 
Yeah, it seems that this issue is resolved as per the following expected behaviour

1. Create go file
2. Create test file
3. Run `Go:Toggle Test Coverage In Current Package` (this would result in highlighting for coverage)
4. Modify the code in the go file or the unit test file
5. Run `Go: Test Package` again 
6. Check that the coverage highlighting has been updated for the package

The steps above works, without throwing any error, so I think it is save to say that the issue is fully resolved.

**Comment by iarief** [comment]
@ramya-rao-a 
I'm sorry, it seems that i missed something.

right now, the toggle test coverage function does not disable test coverage when i run it for the second time

**Comment by iarief** [comment]
@ramya-rao-a 
I'm terribly sorry, but I think that there is still something wrong with the toggle test coverage command.

I think it should work like this

1. toggle test coverage
2. coverage highlighting shows up
3. edit unit test files and test package
4. coverage highlighting is updated
5. toggle the coverage testing again (to turn off coverage test)
6. test the package again

expected behaviour : the vs code should not show coverage highlighting and should not test the coverage of the packaage

current behaviour : the vs code hides the highlighting after the coverage toggle, but as soon as i run test package, the coverage result pops up in the output, and the coverage highlighting is updated.

I think the coverage should be able to be turned off and on via the toggle test coverage in current package.

**Comment by ramya-rao-a** [comment]
- Coverage highlighting is removed the minute there is a change to any file. This is because we can't guarantee that the change hasn't changed the test results
- Toggle Test Coverage removes coverage highlighting if it exists, else it runs tests and applies the coverage highlighting. It doesn't maintain any state that can be re-used by the test package command

In your steps if you add a step 7 to toggle coverage, the coverage highlighting will be removed.

I was going for a feature of apply test coverage every time the package is tested. 

So the flow is

- Run `Go: Test Package`. This will run tests and show test coverage
- Any change to any file removes highlighting of test coverage
- Toggle Test Coverage shows the test coverage if it is currently not shown, removes it if it is currently shown

**Comment by iarief** [comment]
I see, so the toggle coverage is purely for visual purpose.
Then I believe everything works as supposed to.

**Comment by ramya-rao-a** [comment]
Great then, Happy Coding!
