### ISSUE TITLE
go.toolsEnvVars ignores workspaceRoot variable

### ISSUE THREAD

**Issue by osechet** [Microsoft/vscode-go#1111]
I want to set an environment variable for the Go tools using the `go.toolsEnvVars` settings but it does not recognize the `workspaceRoot` variable:
```
"go.toolsEnvVars": {
    "FOO": "${workspaceRoot}"
}
```
If I replace the variable by the absolute path to my workspace, it works.

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of #736

**Comment by ramya-rao-a** [comment]
In the latest update to the Go extension, `${workspaceRoot}` will be resolved when it is passed to `go.testEnvVars` setting
