### ISSUE TITLE
gox support. (A dead simple, no frills Go cross compile tool)

### ISSUE THREAD

**Issue by necrose99** [microsoft/vscode-go#1112]
https://github.com/mitchellh/gox

A dead simple, no frills Go cross compile tool 

on linux has been very easy , to make windows , BSD , Linux etc binaries in one "go" as far as a sysadmin..

**Comment by ramya-rao-a** [comment]
Sounds like a cool feature to add.

PRs are welcome. I can guide anyone who wants to give this a try.

**Comment by necrose99** [comment]
gox isnt perfect , however insted of go-build , you can substitute gox which wrapps go build with cross-ers.. 
a PULL on this is just not within my reach...  however simple apps like hugo one can add use gox.. 
[gox.zip](https://github.com/Microsoft/vscode-go/files/1180342/gox.zip)  anyhow exe's are built 
go get go build , can move gox.exe or x86/x64 to gox.exe under c:\go\bin\gox if you so like ... 

filter targets : gox -osarch="linux/amd64"  or  gox -osarch="linux/arm64"
else by default it will build a default run... of majority ...  windows/Linux/BSD/ x86/x64/arm 
(no arm64 and not yet windows arm64.)

https://github.com/fragmenta & fragmenta-cms will compile with gox very easily ..
go get , and gox insted of go-build .. or just run the x64 exe etc.. 

unfortunately , as well build commands would be a plus to add... as for settings..  ie were go/gox are installed. as far as the menu , I'm more of an Admin /Security Ops Engineer / some but crude coding skills at best..

**Comment by ramya-rao-a** [comment]
Closing this issue as there hasnt been much of a community interest in this feature.
