### ISSUE TITLE
the debugging tool is ignoring the `go.buildTags` parameter

### ISSUE THREAD

**Issue by ijlopez02** [Microsoft/vscode-go#1117]
The **debugging** tool seems to be ignoring the value of the parameter `go.buildTags`. Running test functions does consider it, though. Using the file `launch.json` I can solve this problem by setting the `buildFlags` parameter, but I'd like to use codelens, which are quicker. Is this a bug?

**Comment by ramya-rao-a** [comment]
We can add the values of  `go.buildFlags` and `go.testFlags` settings (which combined get used when running tests) to the `buildFlags` parameter of the debug config that gets used by the codelens.

Thats pretty easy to do.
Use https://github.com/Microsoft/vscode-go/blob/master/src/goTest.ts#L309 to get the flags and pass it to the debug config being formed here: https://github.com/Microsoft/vscode-go/blob/master/src/goRunTestCodelens.ts#L78

PRs are welcome if anyone wants to give this a try.

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension 0.6.64

The debug code lens will now honor the `go.buildFlags`, `go.buildTags` and `go.testFlags` settings.

**Comment by ijlopez02** [comment]
I'm using the extension 0.6.65 and I'm still having problems. Specifically, I need to use the "fts5" module of SQLite. To this end, in the workspace settings file, I'm including "`go.testFlags`" as follows:

    "go.testFlags": ["-tags", "fts5"]

I'm also including the line:

    "go.buildTags": "fts5"

However, when I run tests using **codelens** the "fts5" module fails to load.

**Comment by ramya-rao-a** [comment]
@ijlopez02 Do you need to use the `fts5` tag only when testing? Then use
`"go.testFlags": ["-tags fts5"]`

Do you need to use it both for testing and normal building, then don't include it in test flags, just use
`"go.buildTags": "fts5"`

**Comment by ijlopez02** [comment]
Sorry, running tests using codelens works. What is still failing me is debugging through codelens.

**Comment by ramya-rao-a** [comment]
So are you using `go.testFlags` or `go.buildTags` ?

**Comment by ijlopez02** [comment]
I'm using `"go.buildTags"`. I've defined the option within both the user-serttings and the workspace-settings files (just to be sure). I've also tried other options and combinations, but debugging using codelens seems to be ignoring them:

     no such module: fts5

Running tests using codelens is generating the correct command, though.

     go test -timeout 30s -tags fts5 -run ^Test...$

**Comment by ramya-rao-a** [comment]
@ijlopez02 In the latest update to the Go extension, the buildTags will be used by the debug code lens correctly
Thanks @ka2n for the fix

**Comment by ijlopez02** [comment]
Great! Thank you both very much @ramya-rao-a and @ka2n
