### ISSUE TITLE
Go lint started to pick up vendor folder.

### ISSUE THREAD

**Issue by nvma** [Microsoft/vscode-go#1119]
I can't pinpoint what is the reason for this because I didn't update vscode or gotools since the last time I've worked (this morning). And now my `PROBLEMS` tab is filled with thousands upon thousands of warnings from vendor folder.
Would you be so kind to direct me how I could go about solving this issue? Thanks.

```
Finished running tool: /home/nvma/.gvm/pkgsets/go1.7.3/nvma/bin/golint ./...
/home/nvma/work/go/src/github.com/nvma/project/vendor/github.com/corpix/uarand/uarand.go:1: package comment should be of the form "Package uarand ..."
/home/nvma/work/go/src/github.com/nvma/project/vendor/github.com/corpix/uarand/uarand.go:60: exported function New should have comment or be unexported
```

**Comment by hyacinthus** [comment]
same issues +1
can't find option to ignore this

**Comment by ramya-rao-a** [comment]
@nvma @hyacinthus 

Based on the logs it looks like you have `go.lintOnSave` set to `workspace` which is why it runs `go lint ./...` which picks up vendor folder.

As a workaround, you can set `go.lintOnSave` to `package`

I will look into skipping vendor folders when linting workspace

**Comment by nvma** [comment]
@ramya-rao-a What's puzzling is that it's been working like this ever since I've switched to vscode and discovered this wonderful plugin. I've been using glide to handle dependencies and vscode-go been working fine with `go lint ./...`  and vendor folder since the first day I started to use it. 
So I naturally assumed that something had to happen before things stopped working.

**Comment by ramya-rao-a** [comment]
@nvma That's puzzling to me too. Because this change to use `./...` was in the previous update that was early June and not in the latest update that was released a few days ago :)

**Comment by nvma** [comment]
@ramya-rao-a is it possible that I didn't update the gotools and vscode-go extension since early June while sticking to the latest versions of vscode every time it was released?

**Comment by ramya-rao-a** [comment]
that can be the case

**Comment by nvma** [comment]
I see, thanks for your time, @ramya-rao-a I will have to stick to a half-measure of scoping linter to a package level keeping the hope that optional ignoreDirectory could be introduced to linting options in the near future. Cheers and thank your for your work on this stellar extension, I didn't realise I relied on it so much :)

**Comment by ramya-rao-a** [comment]
When you say `ignoreDirectory` do you mean that's flag on the linter or you are just referring to the fix I would be making?

**Comment by ramya-rao-a** [comment]
I have pushed the fix to master.

Until I release an update, here is what you can do

- Download this vsix file: https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Go to extensions pane in VS Code and in the menu choose "Install from vsix", and select the downloaded vsix file when the finder/file explorer opens

<img width="643" alt="screen shot 2017-07-28 at 2 24 48 pm" src="https://user-images.githubusercontent.com/16890566/28736832-9c066492-73a0-11e7-8d15-8bdd4182f449.png">

**Comment by atomi** [comment]
Just a heads up. It looks like you added a PR to prevent workspace symbols from picking up vendor/ https://github.com/Microsoft/vscode-go/issues/700  but the version from Go-latest.vsix is including all symbols, including those in vendor/.

**Comment by ramya-rao-a** [comment]
@atomi You need to set `"go.gotoSymbol.ignoreFolders": ["vendor"]` to exclude vendor folder from the symbol search

**Comment by ramya-rao-a** [comment]
The fix for linting picking up vendor folder is now out in the latest update to the Go extension (0.6.64)

**Comment by douglarek** [comment]
This issue will occur again when debugging `vendor` codes.

**Comment by ramya-rao-a** [comment]
@douglarek Please log a new issue with clear repro steps.
