### ISSUE TITLE
Testing tool doesn't show log output

### ISSUE THREAD

**Issue by mileusna** [Microsoft/vscode-go#1120]
I love "run test" option in test files.

However, after VS Code update on 1.14.2 on MacOS executing tests inside Code doesn't show up any log output. So if I have ```log.Println(err)``` it won't be printed, however, ```fmt.Println(err)``` will be printed.

**Comment by ramya-rao-a** [comment]
I am able to see the log.Println output

<img width="591" alt="screen shot 2017-07-28 at 2 31 33 pm" src="https://user-images.githubusercontent.com/16890566/28737012-769bb256-73a1-11e7-83ab-99b7c3db381f.png">

Can you share sample code?

**Comment by mileusna** [comment]
Sure, anything. Same testing works OK in terminal window.

It just started to happen after the VS Code upgrade.
![screen shot 2017-07-29 at 01 16 13](https://user-images.githubusercontent.com/4697935/28739494-a62eede4-73fb-11e7-8631-cf9f5f613a69.png)

**Comment by ramya-rao-a** [comment]
Ah! Looks like the `log` part is going to stderr and the `fmt` one goes to stdout

<img width="616" alt="screen shot 2017-07-28 at 4 34 09 pm" src="https://user-images.githubusercontent.com/16890566/28739766-b2e338a4-73b2-11e7-8640-de522ef83336.png">

And in a recent commit stderr is not shown unless there is a test failure https://github.com/Microsoft/vscode-go/commit/94dadaa42af7e59cee6f97eb660de1a14ad45409

@uudashr Can you take a look at this?

**Comment by mileusna** [comment]
Sorry, but I don't see log.* output, failure or no failure. It has nothing to do with the test's outcome.
![screen shot 2017-07-29 at 05 37 28](https://user-images.githubusercontent.com/4697935/28741828-18ebd756-7420-11e7-8ec5-bd6a8b7e69c9.png)

**Comment by ramya-rao-a** [comment]
@mileusna Its right there.... look at the line which has the file path... In the end it says "Failed, but no Hello"

**Comment by ramya-rao-a** [comment]
I have pushed a fix. But even with the fix the `log` will appear after the rest of the output. This is because like I said earlier, log is going to stderr. And while running the `go test` the extension can only fetch stdout and stderr separately.

**Comment by uudashr** [comment]
@ramya-rao-a your changes on the master?

**Comment by mileusna** [comment]
@ramya-rao-a Yes, the ```t.Error``` is there but not the ```log.Println```. That is why I wrote `no Hello`, there is no Hello on the screen from ```log.Println("Hello")```

**Comment by uudashr** [comment]
Fixed on #1124 cc @ramya-rao-a

**Comment by ramya-rao-a** [comment]
This fix is now out in the latest update to the Go extension 0.6.64

**Comment by mileusna** [comment]
Latest update, with VS Code 1.17.0 and vscode-go 0.6.66 neither stderr nor stdout is printed with testing tool. Only if there is `t.Error("x")`, then I see the output of `fmt.Println()` and `log.Println()`

**Comment by uudashr** [comment]
To print to stderr or stdout, you need to add`-v` to the `go test` command. Add test flag to the settings
```json
{
"go.testFlags": ["-v"]
}
```

**Comment by mileusna** [comment]
OK. It is not the same behavior as `go test` which gives output even without -v, but verbose will do the trick. Thanks.

**Comment by ramya-rao-a** [comment]
@mileusna You are right, previously, we were running a simple `go test` which gives the output even without `-v` 

We moved to using `go test package` which does not give such output unless `-v` is passed.

The move was made to support running tests in symlinked folders. See https://github.com/Microsoft/vscode-go/pull/1164

I'll look into documenting this better

**Comment by martinlindhe** [comment]
> The move was made to support running tests in symlinked folders. See #1164

symlinks are not mentioned in #1164 and this change seem to have degraded the experience of vscode, what gives? (See also #1381)

**Comment by ramya-rao-a** [comment]
@martinlindhe #1164 is a PR which is linked to https://github.com/Microsoft/vscode-go/issues/846#issuecomment-323589274 which in turn talks about the symlinks
