### ISSUE TITLE
Coverage highlighting does not work when files are outside of $GOPATH

### ISSUE THREAD

**Issue by arbourd** [Microsoft/vscode-go#1122]
[applyCoverage()](https://github.com/Microsoft/vscode-go/blob/4f33a078a8fd65dd9be763b213554501972641bb/src/goCover.ts#L117)  does not work with files outside the $GOPATH.

`coverageFiles` paths come from `go test`, which returns non-$GOPATH paths like `_/main.go`

**Comment by andreis** [comment]
This confused me a bit until I realised I was out of `$GOPATH`

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to the Go extension 0.6.64

**Comment by andreis** [comment]
@ramya-rao-a just taking the chance to say you're doing an amazing job, I see you everywhere! 😄

**Comment by ramya-rao-a** [comment]
:) thanks @andreis!
