### ISSUE TITLE
command 'go.debug.startSession' not found

### ISSUE THREAD

**Issue by rambhavaraju** [Microsoft/vscode-go#1125]
Hi,

After updating my VSCode last week i started getting the following error when trying to debug the go code.
command 'go.debug.startSession' not found
**my vscode version is 1.14.2**
**Go extension versions is 0.6.63**

I was able to run fine until last week when i updated the vscode on my windows 10 machine. I have GOPATH and GOROOT variables set in the environmental variables too which isn't helping me to debug the code.
My GOPATH env variable is set to the base folder of the project where my GO Code is there where as GO ROOT is pointed to C:\Go where the Go is installed.

I have had added PATH and GOPATH to launch.json but still in vain. Here PATH folder is pointed to the bin folder where dlv is there and the GOPATH is to the base folder where my src is there.

Any help in troubleshooting this issue would be greatly appreciated.

Regards,
Ram

**Comment by rambhavaraju** [comment]
Could someone help me in this regards its very important for me to troubleshoot this issue.

**Comment by ramya-rao-a** [comment]
This looks like that the extension has ended up in some kind of corrupted state.

- Are other features from the Go extension working as expected? Try some of the the "Go: .." commands from the command pallet
- Can you uninstall the Go extension and install it again?
- The `go.debug.startSession` command is called when you try to debug without configuring the launch.json file. Can you create one and see if that helps?

**Comment by rambhavaraju** [comment]
Thanks Ramya for response. 

I think the Go extensions are working fine from command pallete. Ill try uninstalling the GO extensions and re install. I have had configured my launch.json file too. Below is the launch.json configuration
 {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "E:/Projects/OrderManagementSystem/patra-GoService/src/PatraService.go",
            "env": {"PATH": "C:/Go/",
                    "GOPATH":"E:/Projects/OrderManagementSystem/GoService/"},
            "args": [],
            "showLog": true
        }

**Comment by ramya-rao-a** [comment]
If you have the launch.json file then `go.debug.StartSession` should not be called at all.
It gets called when there is no debug configuration in the `launch.json` file 

When you open the debug pane, do you see your configuration selected or does it say "No configurations" ?

<img width="354" alt="screen shot 2017-07-31 at 11 09 46 pm" src="https://user-images.githubusercontent.com/16890566/28811624-5692ebcc-7645-11e7-8e46-485e5fb32d96.png">

If you have set GOPATH as environment variable, then you don't need to set it in the `env` in the debug config.

**Comment by rambhavaraju** [comment]
![image](https://user-images.githubusercontent.com/6705212/28811796-004f534e-76af-11e7-9896-1f1971b00e75.png)
This is how my debug looks like, it shows that i have configured the debug settings

**Comment by rambhavaraju** [comment]
@ramya-rao-a uninstalling and installing the Go extension did the trick. Thank you so much for your help.

**Comment by ramya-rao-a** [comment]
#1126 is tracking something similar.

Somehow, upgrading to VS Code 1.14.2 is corrupting the existing extension.

I cannot get a repro though.

Hopefully this is an isolated case ..

**Comment by eZioPan** [comment]
Hi, I update Go extension to 0.6.66, and every extension function won't work, no matter how I reinstall extension or vscode. The vscode version is 1.16.1, x64.
I also try vscode 1.17.0-insider, x64, extension won't work.
Then I rollback to Go extension 0.6.65, extension function works again.
Only Go extension installed.
Thanks~

**Comment by ramya-rao-a** [comment]
@eZioPan That's unfortunate. Are you still on 0.6.65 or 0.6.66? Did you happen to install the Go extension using the `vsix` file before?

**Comment by eZioPan** [comment]
@ramya-rao-a After I found 0.6.66 won't work, I use `vsix` rollback to 0.6.65.
I didn't use `vsix` to install extension before.

**Comment by ramya-rao-a** [comment]
@eZioPan Did you try uninstalling the Go extension and installing it again?

**Comment by eZioPan** [comment]
@ramya-rao-a yes, i have already try uninstall extension by vscode gui and by manually remove extension folder, but none of them work.
BTW, i use vscode on windows10, i will test it on macos later.

**Comment by ramya-rao-a** [comment]
I am on Windows 10, just installed 0.6.66 and it works fine.

So in your Windows machine, do you see any errors shown in the UI or in the console? Run `Developer: Toggle Developer Tools` to see the console?

**Comment by eZioPan** [comment]
@ramya-rao-a Hi, when I load Go extension, the `Developer Tools` Tells me

extensionHost.ts:384 [Extension Host] Activating extension `lukehoban.Go` failed: Cannot read property 'substr' of undefined.
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

extensionHost.ts:384 [Extension Host] Activating extension `lukehoban.Go` failed:  Cannot read property 'substr' of undefined
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

extensionHost.ts:384 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'substr' of undefined
	at Object.getCurrentGoPath (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:301:34)
	at new GoRunTestCodeLensProvider (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goRunTestCodelens.js:23:34)
	at activate (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goMain.js:101:32)
	at Function.e._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:423087)
	at Function.e._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422832)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422185
	at Object.m [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:41309)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:44874)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46702)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46143)

extensionService.ts:405 Activating extension `lukehoban.Go` failed: Cannot read property 'substr' of undefined.
e._logMessageInConsole @ extensionService.ts:405
e._logOrShowMessage @ extensionService.ts:419
e.$localShowMessage @ mainThreadExtensionService.ts:31
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

extensionHost.ts:384 [Extension Host] rejected promise not handled within 1 second
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
shell.ts:419 [lukehoban.Go] Cannot read property 'substr' of undefined: TypeError: Cannot read property 'substr' of undefined
	at getCurrentGoPath (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:301:34)
	at Object.isGoPathSet (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:217:10)
	at goInstallTools_1.updateGoPathGoRootFromConfig.then (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goMain.js:96:54)
	at <anonymous>
e.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

extensionHost.ts:384 [Extension Host] rejected promise not handled within 1 second
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
shell.ts:419 [lukehoban.Go] Cannot read property 'substr' of undefined: TypeError: Cannot read property 'substr' of undefined
	at getCurrentGoPath (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:301:34)
	at Object.getBinPath (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:274:75)
	at Promise (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goInstallTools.js:294:31)
	at Promise (<anonymous>)
	at Promise.all.keys.map.tool (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goInstallTools.js:293:41)
	at Array.map (native)
	at getMissingTools (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goInstallTools.js:293:29)
	at util_1.getGoVersion.then.goVersion (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goInstallTools.js:266:9)
	at <anonymous>
e.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

**Comment by eZioPan** [comment]
@ramya-rao-a i use chinese(zh-cn) as my primary language, so when i change vscode language to zh-cn, and load Go extension, `Developer Tools` reports something different

> sorry for the chinese in logs.
>
> 激活扩展“lukehoban.Go”失败
> means
> Activating extension lukehoban.Go failed

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] 激活扩展“lukehoban.Go”失败: Cannot read property 'substr' of undefined。
t._logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 激活扩展“lukehoban.Go”失败: Cannot read property 'substr' of undefined。
e._logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] Activating extension `lukehoban.Go` failed:  Cannot read property 'substr' of undefined
t._logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'substr' of undefined
	at Object.getCurrentGoPath (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:301:34)
	at new GoRunTestCodeLensProvider (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goRunTestCodelens.js:23:34)
	at activate (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goMain.js:101:32)
	at Function.e._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:423087)
	at Function.e._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422832)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422185
	at Object.m [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:41309)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:44874)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46702)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:46143)

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] rejected promise not handled within 1 second
t._logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [lukehoban.Go] Cannot read property 'substr' of undefined: TypeError: Cannot read property 'substr' of undefined
	at getCurrentGoPath (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:301:34)
	at Object.isGoPathSet (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:217:10)
	at goInstallTools_1.updateGoPathGoRootFromConfig.then (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goMain.js:96:54)
	at <anonymous>
e.onUnexpectedError @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] rejected promise not handled within 1 second
t._logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [lukehoban.Go] Cannot read property 'substr' of undefined: TypeError: Cannot read property 'substr' of undefined
	at getCurrentGoPath (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:301:34)
	at Object.getBinPath (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:274:75)
	at Promise (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goInstallTools.js:294:31)
	at Promise (<anonymous>)
	at Promise.all.keys.map.tool (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goInstallTools.js:293:41)
	at Array.map (native)
	at getMissingTools (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goInstallTools.js:293:29)
	at util_1.getGoVersion.then.goVersion (C:\Users\eZioPan\.vscode\extensions\lukehoban.go-0.6.66\out\src\goInstallTools.js:266:9)
	at <anonymous>
e.onUnexpectedError @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29

extensionHost.ts:384 [Extension Host] (node:14188) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

**Comment by ramya-rao-a** [comment]
@eZioPan Thanks for the call stack! That helps a lot.

This is the line that is causing the failure in detecting GOPATH and so failing the extension activation: https://github.com/Microsoft/vscode-go/blob/0.6.66/src/util.ts#L334

Since it is a Windows specific code path, you were seeing it only in Windows.

Did you have any folder open in VSCode when you see this issues?

**Comment by eZioPan** [comment]
@ramya-rao-a Yes! new extension solve my problem! THANKS A LOT!
You are right, I often open Go file without open a folder, and I think I should learn more about vscode to improve my usage~
Thank you again!

**Comment by ramya-rao-a** [comment]
no problem, Happy Coding!

**Comment by vbocan** [comment]
I am seeing the same problem with VS Code v1.17 when the .go file is the only one opened in the editor. If I open the folder instead, it works flawlessly.

**Comment by ramya-rao-a** [comment]
@vbocan I am guessing you must be on Windows. 
The issue you are seeing got introduced in the last update to the Go extension.
The fix for this is in the master branch.
Will be releasing an update this week.
See https://github.com/Microsoft/vscode-go/issues/1271#issuecomment-336198657 to get the fix before the release
