### ISSUE TITLE
Wrapping for comments

### ISSUE THREAD

**Issue by nictuku** [Microsoft/vscode-go#113]
Something me and others[1] miss is the ability to wrap a comment paragraph at, say, 80 columns. 

I'm aware of the wrappingColumn feature, but it doesn't help in this case. We want to wrap comments only, not code.

In SublimeText you can type Alt-Cmd-Q to wrap the current line into a paragraph, independently of the auto-wrapping feature.

Two possible choices would make me happy:
1) vscode-go could add automatic wrapping for comment blocks.
2) vscode could add a keybinding for wrapping the current line manually (not auto-wrapping).

[1] https://forum.golangbridge.org/t/visual-studio-now-with-go-support/1531/13 by @calmh

**Comment by lukehoban** [comment]
Inexpert automatic wrapping for comments would be unexpected as a default, and feels a bit orthogonal to Go language support. 

A wrap text command could make sense as an extension at least, and perhaps worth suggesting as a built-in for Code. 

Do you see a reason to think about this as a Go-specific thing?

**Comment by nictuku** [comment]
I don't think it's Go-specific. I'd take inspiration from ST and enable the binding for everyone. 

But I only use vscode for Go and Markdown, so I can't make any serious suggestions about what to do for other languages.

**Comment by calmh** [comment]
Indeed! Note that ST in this case actually rewraps the current *paragraph*. When in a code syntax mode, a paragraph matches a set of lines beginning with the comment character. So given the code:

```
1: foo := "bar"
2: // a comment here
3: // more comment string
4: if foo == "bar" {
5:   print("hello")
6: }
```

pressing the wrap-paragraph shortcut when on lines 2 or 3 would wrap the comment paragraph nicely. (Pressing it while on line 4 would paragraph wrap the code on lines 4 and following, resulting in garbage which is fine by me. No need to try to be smart when the user asks for something stupid.)

**Comment by lukehoban** [comment]
Closing this, as I don't expect we'll add anything Go specific for this.  You could reopen a request in http://github.com/Microsoft/vscode for adding it to VS Code itself (or just implement as an extension!).  

Totally agreed that this would be nice to have.
