### ISSUE TITLE
Will not install on Windows 7 i386

### ISSUE THREAD

**Issue by k5nwa** [Microsoft/vscode-go#1130]
Gets errors while installing on a Windows 7 i386 PC. Below is a sample of one error, a similar error occurs on multiple modules.

D:\Projects\Go\src\github.com\derekparker\delve\pkg\proc\disasm.go:9: undefined: ArchInst

On several modules, it mentions that "undefined: ArchInst"

I need it to work on i386 Windows 7 environment as I'm replacing an application that requires that environment and would like to look at the old application and the replacement on the same PC.

Thanks

**Comment by ramya-rao-a** [comment]
@k5nwa Closing this issue as we haven't heard back you in a while
