### ISSUE TITLE
Browse packages does not list packages

### ISSUE THREAD

**Issue by delicb** [Microsoft/vscode-go#1132]
"Browse packages" feature, which is recently introduced, never manages to list packages.

All I get is bar saying "Finding packages... Try after sometime.". But it does not work after "sometime"

I am using vscode-go in version 0.6.63 and vscode in version 1.14.2 os macOS Siera (10.12.6).

Manually running `go list all` does take some time on my machine (probably due to number of installed packages in GOPATH). I am not sure what is intended time for running this, but here is timed output:

First run:
```bash
$ time go list all
...
go list all  9.35s user 9.19s system 11% cpu 2:46.14 total
```

Next run:
```bach
$ time go list all
...
go list all  7.31s user 5.28s system 25% cpu 49.378 total
```

A thing to note is that I do get some errors when executing `go list all` for packages that expect to be imported via vanity path and are in wrong place in my `$GOPATH`. Could this be the cause? Or is it timeout? Is it possible to increase timeout?

**Comment by delicb** [comment]
I managed to make it work. 

I have cleaned up my `GOPATH` so that I do not have any more errors reported by `go list all`. Errors that I had were with packages that were in `$GOPATH/src/github/<username>/<package>` and had import comment that required them to be on some vanity import path (like `gopkg.in/<package>.v1` or something. I had couple of those, from times that I tried to `go get` them from github just to figure out they are meant to be fetched from somewhere else. Go leaves such packages, but fails to build them, and I never deleted them manually (until now).

So I guess this is related to how vscode-go expects output from `go list all` to look like and does not expect errors (or at least this specific error).

**Comment by ramya-rao-a** [comment]
So doing a `go get` on any `gopkg.in/<package>.v1` should be able to let me repro this issue?

**Comment by delicb** [comment]
Not just `go get gopkg.in/...`. For example, https://github.com/uber-go/zap should be installed by using `go get -u go.uber.org/zap`. If someone would do `go get github.com/uber-go/zap` that would result in error:
```bash
package github.com/uber-go/zap: code in directory /Users/del-boy/go/src/github.com/uber-go/zap expects import "go.uber.org/zap"
```
But folder `$GOPATH/github.com/uber-go/zap` would be created and because of that when `go list all` is executed, first few lines are:
```
(3.6.1) ~/go/src  ᐅ go list all
can't load package: package github.com/uber-go/zap: code in directory /Users/del-boy/go/src/github.com/uber-go/zap expects import "go.uber.org/zap"
can't load package: package github.com/uber-go/zap/zapcore: code in directory /Users/del-boy/go/src/github.com/uber-go/zap/zapcore expects import "go.uber.org/zap/zapcore"
can't load package: package github.com/uber-go/zap/zapgrpc: code in directory /Users/del-boy/go/src/github.com/uber-go/zap/zapgrpc expects import "go.uber.org/zap/zapgrpc"
can't load package: package github.com/uber-go/zap/zaptest: code in directory /Users/del-boy/go/src/github.com/uber-go/zap/zaptest expects import "go.uber.org/zap/zaptest"
can't load package: package github.com/uber-go/zap/zaptest/observer: code in directory /Users/del-boy/go/src/github.com/uber-go/zap/zaptest/observer expects import "go.uber.org/zap/zaptest/observer"
# rest of the packages
```

At least that is what I believe could cause problems, but not I can not reproduce this consistently. I did what I wrote above, but now I do get list of packages in vscode. Earlier I had over 100 packages like this, now I cleaned them all, so number might be relevant (it could take longer for `go list all` to finish if there are a lot of packages like this or something similar).

**Comment by ramya-rao-a** [comment]
I tried your steps, but like you said can't repro the issue.

I have removed https://github.com/Microsoft/vscode-go/blob/0.6.63/src/goPackages.ts#L42-L47 so that we continue to use the output of `go list all` even in case of failures to atleast get the info on the pkgs that appeared in stdout.

Also, added a error message that is shown to the user if no pkgs were found instead of saying "Fetching packages... try again later"

**Comment by marwan-at-work** [comment]
@ramya-rao-a since listing the packages takes a long time, what do you think of starting to show results before the command `go list all` has finished fetching the list?

it might make the code a bit more complex, but i'd be happy to submit a pr if that idea makes sense :)

**Comment by ramya-rao-a** [comment]
@marwan-at-work Yes definitely, give it a try.
