### ISSUE TITLE
Difficulty setting environment variables for the debugger

### ISSUE THREAD

**Issue by peteryates** [Microsoft/vscode-go#1134]
My go program requires either a `-config` argument *or* the `CONFIG` environment variable to be set, so `go test -config=../config/test.yml` or `CONFIG=../config/test.yml go test` both work fine; if neither are present the default config location is `/etc/my-program.yml`.

Now, when I attempt to run the debugger it's *always* looking for the config in `/etc/my-program.yml`, despite trying the following things in my `launch.json` file:

```json
"env": {
    "CONFIG": "../config/test.yml"
},
```

and

```json
"args": ["-config=config/test.yml"],
```

I'm using the standard [`flag`](https://golang.org/pkg/flag/) package and have set the config flag up as follows:

```
configPath = flag.String("config", "/etc/my-program.yml", "the config file")
```

If I change the default value it works as expected, but I'd rather leave that pointing at where the file is likely to be on a live deployment. Am I misunderstanding the `README` or is something just not right with my setup? It's as if the `args` and `env` settings do nothing.

**Edit** I'm launching the debugger by clicking "debug test" above the test functions, and have tried changing `mode` to `debug` and `test` to no avail.

**Comment by peteryates** [comment]
OK, so it appears that this is just a problem with my setup and me not really knowing what VSCode is doing under the hood.

Rather than running the debugger from the "debug test" link, if I do it from the test window it works as I'd expect:

![screen shot 2017-08-06 at 16 36 19](https://user-images.githubusercontent.com/128088/29004782-7746d8e0-7ac5-11e7-96cf-01b05641e005.png)

So I guess now my question is, when I'm clicking "debug test", which configuration is it using and how do I substitute the hardcoded arg with the test name?

```json
{
	"name": "Launch test",
	"type": "go",
	"request": "launch",
	"mode": "test",
	"program": "${workspaceRoot}/backend",
	"args": [
		"-test.run",
		"Test_MakeSureXYZ"
	],
	"env": {
		"CONFIG": "../config/test.yml"
	}
}
```

[As far as I can see](https://code.visualstudio.com/docs/editor/debugging#_variable-substitution), the closest I can get is the `${lineNumber}`.

**Comment by peteryates** [comment]
So it would appear that [this feature of CodeLens isn't supported yet](https://github.com/Microsoft/vscode-go/issues/879).

**Comment by ramya-rao-a** [comment]
@peteryates Have you tried using the `go.testEnvVars` setting? Any env vars set there will be used by
- All the Test commands from the command palet
- The Run test and Debug test codelens

**Comment by peteryates** [comment]
Thank you, this worked as you suggested it might. 

```json
"go.testEnvVars": {
    "CONFIG": "../config/test.yml"
}
```

I appeared to only be able to make it work by adding the above section to my 'User Settings' file, so this will apply to *all* of my Go projects. Can I not specify this option somehow in `launch.json`?

But, it's working for the moment, thank you for your help @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@peteryates Set it in your Workspace settings file instead of the User Settings file. This way it will apply only to the current project

**Comment by peteryates** [comment]
Ah, excellent, thank you very much!

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!

**Comment by jamietre** [comment]
@ramya-rao-a it looks like variables like `${workspaceRoot}` are not honored in `go.TestEnvVars`, which I need to set some environment variables relative to project root. Any chance this could be added?

**Comment by ramya-rao-a** [comment]
@jamietre That's covered in https://github.com/Microsoft/vscode-go/issues/736 for which I just pushed a fix. You can find the feature in the next update

**Comment by jamietre** [comment]
Awesome, thanks! Sorry I missed the more closely related issue in my search.

**Comment by ramya-rao-a** [comment]
@jamietre In the latest update to the Go extension, `${workspaceRoot}` will be resolved when it is passed to `go.testEnvVars` setting
