### ISSUE TITLE
vscode should not try to contact the internet when computer is disconnected

### ISSUE THREAD

**Issue by aybabtme** [Microsoft/vscode-go#1137]
When I go offline, on planes or whatever, I want to be able to use my editor without issues. Currently, parts of VS Code appear to be trying to check for upgrades or things like that, and does so even when my wifi is completely off. When those upgrades fail, it shows pops up that are distracting.

VS Code should detect that there's no connectivity and avoid spamming user with connection error messages.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#32196

**Comment by aybabtme** [comment]
Woups I totally opened this against the wrong repo!
