### ISSUE TITLE
inferGopath doesn't work as expected

### ISSUE THREAD

**Issue by ttimasdf** [Microsoft/vscode-go#1139]
Environment:
VSCode 1.14.2
macOS 10.12.6

Step to reproduce:
- GOPATH was set in my .zshrc.
- `process.env['GOPATH']` in developer tool can get it.
- add option `go.gopath` in settings.json could overwrite it correctly.
- add option `go.inferGopath` in settings.json could not detect a custom gopath. My open directory is `/Users/user/Projects/proj/src/github.com/ttimasdf/proj/main.go`, and I want `/Users/user/Projects/proj` as my GOPATH, which is also the expected behavior.

**Comment by ramya-rao-a** [comment]
When you set `go.inferGopath` to `true`, what GOPATH did you get?

**Comment by charmfocus** [comment]
me too!
```
"go.inferGopath":true
```

**Comment by ttimasdf** [comment]
@ramya-rao-a The same as I got when it was set to `false`

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ttimasdf** [comment]
Err, here comes another question. After upgraded VSCode to 1.15.1, even `go.gopath` option stopped working as well. I'm not familiar with Extension Development host, how could I provide you more information?

**Comment by ramya-rao-a** [comment]
@ttimasdf The master branch has quite a few changes since the last released version (0.6.63)

So there might be differences in behavior.

Can you try installing the Go extension using the latest vsix that was built from master branch and see if your issue still occurs?
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Close all VS Code windows
- Run `code --install-extension Go-latest.vsix` from the location where the above file was downloaded
- Open VS Code

**Comment by ttimasdf** [comment]
From [here](https://github.com/Microsoft/vscode-go/blob/89feaa7fa54d0d5782f8a305ad8e205a7ac32ea2/src/goInstallTools.ts#L239), the GOPATH env was set to value of `go env GOPATH`, and [debug server](https://github.com/Microsoft/vscode-go/blob/89feaa7fa54d0d5782f8a305ad8e205a7ac32ea2/src/debugAdapter/goDebug.ts#L230) run with this value as well. should there be anywhere setting `process.env['GOPATH']` to the value of `getCurrentGoPath()` so that `go run` could be invoked successfully?

**Comment by ttimasdf** [comment]
@ramya-rao-a Oh, thanks. I'll try it. With my last comment I was using the code cloned from master branch. In conclusion, linter is good(code completion detected my module), debugger is not(wrong GOPATH env).

**Comment by ramya-rao-a** [comment]
@ttimasdf The debugger not using the gopath like the rest of the extension features is a known issue. See #840

**Comment by ttimasdf** [comment]
2017年8月20日 14:42，"Ramya Rao" <notifications@github.com>写道：

**Comment by ramya-rao-a** [comment]
@ttimasdf Sorry, I didn't understand your previous comment

**Comment by ttimasdf** [comment]
@ramya-rao-a Errr, I don't know either..maybe replied by a bug of my phone. Sorry for disturbance. 😢

**Comment by ramya-rao-a** [comment]
So what's your current state?
Does inferGopath work everywhere except for debugger?

**Comment by ttimasdf** [comment]
Latest commit(94e6acd2a0c68bb4269dbf13fe9b134ce188614d) fixed it and everything works like a charm. Many thanks 👍  @ramya-rao-a
