### ISSUE TITLE
No receiver functions with go-langserver turned on

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode-go#1140]
When I set `"go.useLanguageServer": true`, I no longer see receiver functions (aka methods) when I type "@" in the command palette (though I see all other symbols).  This is in contrast to the behavior when I use go.docsTool set to either godoc or gogetdoc.  Nonetheless, I wish that I had these symbols because they're useful!

**Comment by josh-tepper** [comment]
@ramya-rao-a have you seen this?  Should I file this with the sourcegraph folks or is this an artifact of the way vscode-go invokes or uses go-langserver?

I just updated my langserver with go get, and I have this version:
```
$ go-langserver -version
v2-dev
```

**Comment by ramya-rao-a** [comment]
Hey @josh-tepper 

Sorry my notifications are all in a mess, don't know how I missed this issue.

Yes, this should be logged in the repo for the language server.

No worries I'll move it.

**Comment by ramya-rao-a** [comment]
This issue was moved to sourcegraph/go-langserver#199
