### ISSUE TITLE
Option to disable "run test | debug test" links

### ISSUE THREAD

**Issue by VojtechVitek** [Microsoft/vscode-go#1141]
Hi,

just a minor nit -- is there any way to disable these two links?

![screen shot 2017-08-11 at 4 32 00 pm](https://user-images.githubusercontent.com/139342/29230824-ae3b7626-7eb2-11e7-91a2-fc8a71c7aa06.png)

When writing tests, these lines show up when the code is OK, but they disappear every time there's a syntax error - effectively every time I save a `_test.go` file that doesn't compile.

The showing up / hiding causes the code to jump up and down and it gets too much of my attention and slows me down.

Thanks for the coolest extension for Go out there! I'm very happy user otherwise.

Best,
\- Vojtech

**Comment by ramya-rao-a** [comment]
@VojtechVitek 

To disable all codelens in VS Code, set `editor.codeLens` to `false`
To disable Go related codelens, set the below
```
"go.enableCodeLens": {
    "references": false,
    "runtest": false
  }
```

**Comment by VojtechVitek** [comment]
Works like charm. Thanks a lot! 👍

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
