### ISSUE TITLE
Map keys with braces cause lines moved below to be indented

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode-go#1143]
Put the cursor in the first key-value line, press and hold Option, then press down to move the line down below the one with the curly brace as the key. The moved line will become indented one tab.

```go
var _ = map[string]string{
	"": "",
	"{": "",
}
```

**Comment by ramya-rao-a** [comment]
I believe this is due to the indentation rules we have.

Only happens when there is an un-closed `{` in the line before the final position of the move.

**Comment by ramya-rao-a** [comment]
The [indentation rules for Go](https://github.com/microsoft/vscode/blob/1.37.1/extensions/go/language-configuration.json#L27-L30) are in the VS Code project, and so the fix should be there as well.

**Comment by ramya-rao-a** [comment]
@rebornix Can you please transfer this issue to the VS Code repo?

**Comment by ramya-rao-a** [comment]
Closing this issue as there the fix should be done upstream.
@willfaught, Please log this issue in the [VS Code](https://github.com/Microsoft/vscode) repo

**Comment by willfaught** [comment]
The issue seems fixed in the latest release. Will skip copying this to vscode.
