### ISSUE TITLE
5 GB of RAM usage by go-langserver, leak?

### ISSUE THREAD

**Issue by Shadowfaxenator** [Microsoft/vscode-go#1144]
While saving (cmd+S) several times Hello World app written in golang on MacOS VSCode, I get 5+ GB of RAM consumed by go-langserver process, CPU fans start working and no memory is freed

**Comment by ramya-rao-a** [comment]
@Shadowfaxenator 

I don't believe the language server does anything on save. 

cc @slimsag

**Comment by slimsag** [comment]
Hi @Shadowfaxenator can you tell me which version this command shows for you?

```bash
$ $GOPATH/bin/go-langserver -version
v2-dev
```

Additionally, when the process uses a large amount of memory, could you capture a heap profile via the steps described in https://github.com/sourcegraph/go-langserver#profiling ?

**Comment by Shadowfaxenator** [comment]
Yes, I have v2-dev
When I try
```
go tool pprof -svg $GOPATH/bin/go-langserver http://localhost:6060/debug/pprof/heap > heap.svg
```

I get 

``` 
Fetching profile from http://localhost:8060/debug/pprof/heap
http fetch http://localhost:8060/debug/pprof/heap: Get http://localhost:8060/debug/pprof/heap: dial tcp [::1]:8060: getsockopt: connection refused
```

**Comment by ramya-rao-a** [comment]
@Shadowfaxenator Do you still have issues with the go-langserver process taking a lot of CPU and memory?
