### ISSUE TITLE
Vscode-go doesn't recognise new package installed by dep ensure

### ISSUE THREAD

**Issue by airlanggacahya** [Microsoft/vscode-go#1146]
After running dep ensure on the command line to install new package, the new package is not recognized by vscode-go directly. Vscode restart is required to get the new package recognized by autocomplete and linter.

**Comment by ramya-rao-a** [comment]
linters are triggered on file save. They do not react to file changes and so that is expected behavior.

For auto-complete, are you trying it with or without the import statement to the new package in the file?

**Comment by airlanggacahya** [comment]
Yes, I already put the import statement. In fact, "dep ensure" is working directly by scanning the go source file for import path, and combined with file on root project to create final list of package to be downloaded. And then pull the source and put into vendor folder. Golang dep: https://github.com/golang/dep

So the problem is, run vs-code, put import statement, run terminal, run dep ensure on terminal, dep download and populated the vendor directory, vscode autocomplete and linter fail to recognize the vendor directory and report the import path error and all references is to the import path is error.

**Comment by ramya-rao-a** [comment]
Does `dep` download only the source or also build the package? 

For auto-complete we use [gocode](https://github.com/nsf/gocode) which uses pkgs from GOPATH/pkgs and not source code

**Comment by airlanggacahya** [comment]
Hmm.. that understandable. Thank you for your time, I'll mark this as closed.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
