### ISSUE TITLE
can't autoimport packages in vendor directories

### ISSUE THREAD

**Issue by Hawken94** [Microsoft/vscode-go#1147]
I use glide and find that vscode can't autoimport packages in vendor directories . But it can autoimport packages in $GOPATH/src . I don't know the reason . Sorry for my bad english.

**Comment by airlanggacahya** [comment]
Try to restart vs-code after running glide. Maybe related to #1146

**Comment by Hawken94** [comment]
@airlanggacahya  I try it but it doesn't work ( in my windows10) . I remember I can auto-import packages in vendor directories in my ubuntu 16 . I will try it on my ubuntu after I get back home at night .May it isn't a big problem . PS , it can auto-import packages in vendor directories when I use Gogland .

**Comment by Hawken94** [comment]
@airlanggacahya I tried . It can work on ubuntu 16.

**Comment by ramya-rao-a** [comment]
@Hawken94 Do you still see this issue in Windows?

When you say auto-import, are you referring to adding the missing import statements when you format the file or save the file?

**Comment by Hawken94** [comment]
@ramya-rao-a No, when I use the package(method) at the first time, vs code can't auto-import it's package in win10. Normally, when I write "println", it will import fmt package automatically. Sorry for my bad english again. But it can work in ubuntu 16. I don't know the reason.

**Comment by ramya-rao-a** [comment]
@Hawken94 We have made some changes around completions for unimported packages. Can you try out the latest Go extension from source and see if that helps?
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` from the terminal
- Reload VS Code

**Comment by Hawken94** [comment]
@ramya-rao-a OK,I will try it now. Thank vs code! Thank  Microsoft! Thank you for solving my problem.

**Comment by Hawken94** [comment]
@ramya-rao-a Sorry, I took some time to try, but it still dosen't work. It is OK, I almost work on ubuntu16, so it's not a trouble. Thank you again! (windows 10 1703, vs code 1.16.1, go 1.9 ) This issue can be closed. 

- I describe my problem again. When I glide init and glide get github.com/skip2/go-qrcode (e.g.) , I write "qrcode", the vscode didn't prompt and import the package. This is my problem. But in ubuntu, it has a nice prompt and will auto-import the package just like the built-in package. 
- Thank you again! I can write `import "github.com/skip2/go-qrcode"` manually, so it's not a big problem. 
sorry for my bad english. I can say Chinese if necessary.
This is my glide.yaml: (just for testing)

package: littlezz
import:
- package: github.com/skip2/go-qrcode
- package: github.com/gorilla/mux
  version: ^1.5.0

**Comment by ramya-rao-a** [comment]
@Hawken94 Your English is fine, dont worry about it :)

> But in ubuntu, it has a nice prompt and will auto-import the package just like the built-in package.

What prompt are you talking about here? Can you share a screenshot? Do you mean auto-completion?

Can you check your settings? Do you have `go.autocompleteUnimportedPackages` enabled in either ubuntu or windows?

**Comment by Hawken94** [comment]
@ramya-rao-a Thank you for your praise! 

### This is in Ubuntu 16. Firstly,
![default](https://user-images.githubusercontent.com/12959892/31155941-63b7c74c-a8e4-11e7-8c8a-272324b148dc.png)
Secondly, when I write "qrcode", vscode has a nice prompt. And then I press the Enter key, it auto-import the 'qrcode' package.
![default](https://user-images.githubusercontent.com/12959892/31155999-c4b92bb2-a8e4-11e7-87c0-4e1f5806af57.png)
![default](https://user-images.githubusercontent.com/12959892/31156010-cc585f32-a8e4-11e7-9650-5047040bc77b.png)
### This is in Windows 10. The version of vscode-go is 0.6.66. I just upgrade it.
The setting is OK.
![win_1](https://user-images.githubusercontent.com/12959892/31156840-2ee62810-a8e9-11e7-907f-cb5ecee3da6c.png)
It doesn't work in windows 10.
![win_2](https://user-images.githubusercontent.com/12959892/31156841-2eeb835a-a8e9-11e7-94b7-5da914470f9c.png)
As usual, it can auto-import the built-in packages and packages in GOPATH.  
![win_3](https://user-images.githubusercontent.com/12959892/31156842-2ef2357e-a8e9-11e7-968d-bfbf1367df84.png)

- This is my test. I don't know what will happen in your windows 10. If you can recurrent my issues, it can't be better.
- My gmail account is xionghekuan@gmail.com. If you have other problem to ask, please contact with me. 
- Happy mid-Autumn Festival!

**Comment by ramya-rao-a** [comment]
Can you run `Go: Browse Packages` or `Go: Add Import` command and see if `qrcode` appears in the list?

**Comment by Hawken94** [comment]
@ramya-rao-a When I run Go: Browse Packages command, 'qrcode' appears in the list. But Go: Add Import doesn't.

**Comment by ramya-rao-a** [comment]
Alright, I have a fix in.

Can you try the below to see if my fix works for you?
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix`
- Reload VS Code

**Comment by Hawken94** [comment]
@ramya-rao-a I had a try just now. It has a nice prompt. It works. Thank you very much!!!

**Comment by ramya-rao-a** [comment]
No problem, thanks for reporting the issue and Happy Coding!

**Comment by Hawken94** [comment]
@ramya-rao-a I find another problem today. The functions or interfaces can't go to definition if they are in vendor directory .
![tim 20171012104425](https://user-images.githubusercontent.com/12959892/31476692-5c3d8658-af3a-11e7-8118-56340fc74f5f.png)
![tim 20171012104508](https://user-images.githubusercontent.com/12959892/31476761-b8a65cb2-af3a-11e7-9403-bf0dfe559c08.png)

**Comment by ramya-rao-a** [comment]
@Hawken94 that would be a separate issue. Try setting `go.docsTool` to `gogetdoc` in your settings

**Comment by Hawken94** [comment]
@ramya-rao-a When I set **go.docsTool** to **gogetdoc**, it can go to definition.But there is another question. When my mouse on the function, it can't show the definition.
Packages in GOPATH can show :）：
![image](https://user-images.githubusercontent.com/12959892/31526285-6c6758ba-aff8-11e7-9130-597ad3b30975.png)

It doesn't work.
![image](https://user-images.githubusercontent.com/12959892/31526307-8b81dfae-aff8-11e7-9aed-8108627268b4.png)

Thanks all the way. I think it is not a big problem ^_^

**Comment by ramya-rao-a** [comment]
@Hawken94 Try running `gogetdoc` from the command line/terminal. If you don't get the docs as expected, then log an issue at https://github.com/zmb3/gogetdoc
