### ISSUE TITLE
Debugging does not honor go.buildTags

### ISSUE THREAD

**Issue by mbanzon** [Microsoft/vscode-go#1148]
I'm trying to debug a project that rely on build tags (actually it is the `github.com/mattn/go-sqlite3` used in a way that require `-tags trace` for the feature to be included). Debugging this package does not work - the compiler output errors that functions behind build tag are not defined.

To reproduce these two files:

(main.go)
```Go
package main

func main() {
	myFunc()
}
```

(func.go)
```Go
// +build mytag

package main

import "fmt"

func myFunc() {
	fmt.Println("Hello from myFunc")
}
```

and adding the `"go.buildTags": "mytag"` to user settings.

The background compilation works fine - along with completion, vet, gofmt etc. - but starting the program from the debugger gives the error:

```
./main.go:4: undefined: myFunc
exit status 2
Process exiting with code: 1
```

**Comment by ramya-rao-a** [comment]
Unfortunately, debugger cant read the settings at the moment. Try using "buildFlags" property in your debug config. Pass ["-tags", "urtag"]

**Comment by mbanzon** [comment]
Too bad.

Just to clarify (will post in the twitter thread as well for anyone following there): `buildFlags` takes a string argument. It is working with: `"buildFlags": "-tags mytag"`.

**Comment by ramya-rao-a** [comment]
Thanks @mbanzon
