### ISSUE TITLE
handle gorename errors better

### ISSUE THREAD

**Issue by jmhodges** [Microsoft/vscode-go#1149]
In order to figure out why a rename call happened, I have to open up the developer tools window and poke through the console to get the full error text. Example case: renaming a type `Apple` to `apple` would cause the variable name `apple` that's used in the project to be shadowed and so gorename exits early.

It'd be really nice if I could click on something and go to the spot with the error, but maybe there's a better way of getting the error text than the console?

This is on Mac OS 10.12.6 and VSCode 1.15.1.

**Comment by ramya-rao-a** [comment]
Dont you get the notification pop up?

![image](https://user-images.githubusercontent.com/16890566/30885365-d2523214-a2c7-11e7-8d22-acd175778bb7.png)

**Comment by ramya-rao-a** [comment]
The Warning that has the required message disappears after a while though. I have logged an upstream issue for that in the vscode repo: https://github.com/Microsoft/vscode/issues/35177

**Comment by ramya-rao-a** [comment]
The upstream issue has been fixed.
Now the error shows up and doesnt go away until user hits escape or the close button
