### ISSUE TITLE
Highlight TODO and BUG in comments

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1153]
It calls attention to them.

**Comment by ramya-rao-a** [comment]
That would be a cool feature indeed, but is not specific to the Go extension.
It applies to all languages actually.

Quite a few feature requests have been logged in the VS Code repo for this. Go through both the open and closed issues here: https://github.com/Microsoft/vscode/issues?q=is%3Aissue+TODO+in%3Atitle+is%3Aopen

Some of them have links to extensions that do this.

**Comment by willfaught** [comment]
Good point, as long as it highlights both TODO and BUG.
