### ISSUE TITLE
"Test Package" ignores buildFlags and testFlags when coverOnTestPackage is true

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#1155]
title

**Comment by OneOfOne** [comment]
Not sure if I need to sign something for the PR, but I'd be happy to.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @OneOfOne! And for the PR as well.
I am going ahead with a separate solution and have pointed that out in your PR.

**Comment by OneOfOne** [comment]
Thanks!

**Comment by ramya-rao-a** [comment]
@OneOfOne I am curious though.. How did you come across this error?

Have you been working on the extension or testing it using the `Go-latest.vsix` ?

**Comment by OneOfOne** [comment]
Yep! I needed `gometalinter and dlv will honor the go.toolsGopath setting.` and `Support for the Go To Implementation command on interfaces.` so I grabbed `Go-latest.vsix` as soon as it was available with them.

Great work on the extension btw!

**Comment by ramya-rao-a** [comment]
Thanks! That's great to hear.

Would you be interested in beta testing the extension for every release?
I am not a Go developer myself and I always fear that I am missing out certain scenarios that a everyday Go develeper could catch.

You wouldnt need to test all features. Just install using  `Go-latest.vsix`and use the VS Code just like you would any other day.

**Comment by OneOfOne** [comment]
Yes of course, I'd like to help.

**Comment by ramya-rao-a** [comment]
Great! Can you please join the group https://groups.google.com/forum/#!forum/go-with-vs-code-beta-testers?

Whenever I update the `Go-latest.vsix` for the upcoming release, I announce in that group, so that people can download it and install.
