### ISSUE TITLE
Debug adapter crashes when connecting to a target that's stopped on a breakpoint

### ISSUE THREAD

**Issue by ilevine** [Microsoft/vscode-go#1157]
To reproduce:
The initial state as an application that's already debugged using a dlv server with multi client enabled, that's stopped in a breakpoint. 
After the breakpoint hit, the first client remains inactive. and vscode-go comes into play.

We use the "stopOnEntry: true" in the launch config, so that vscode will remain on the breakpoint and allow us to debug it.

When vscode connects, it eventually issues a `threadsRequest` command, which fails on this check `if (this.debugState.exited) {` as `this.debugState` is null.

I'm assuming the solution is to initialize the debugState in this case, using a `State` command to dlv. I tried to do that, but it wasn't working well when I tested it.

Pointers on how to solve this correctly are appreciated and I'd be glad to submit a PR once I get a fix working.

**Comment by ramya-rao-a** [comment]
@ilevine I am not familiar with the multi-client feature of delve. Can you share information on your setup that we can try and replicate to check the issue?

cc @roblourens On initializing debugstate

**Comment by roblourens** [comment]
The multiclient feature is interesting. Even without that, I remember an issue that `stopOnEntry` doesn't really work, for the same reason - debugState is never initialized. I'm not sure whether dlv gives us a way to initialize it in this case.

**Comment by ramya-rao-a** [comment]
Looks like it does in v2: https://godoc.org/github.com/derekparker/delve/service/rpc2#RPCServer.State

**Comment by giulianob** [comment]
@ramya-rao-a Has there been an attempt to switch to v2? I was looking through the API and it doesn't seem like it has changed much. I'm wondering if anyone has tried and if there is a list of known issues anywhere.

**Comment by ramya-rao-a** [comment]
@giulianob As far as I know, no one has tried to switch to v2 yet. You are welcome to try and I can help if you have any questions

**Comment by ramya-rao-a** [comment]
@giulianob  Sometime in the last year, we made the move to using v2 apis of delve by default. So, we should be able to initialize the debug state.

cc @vladbarosan As you were planning to look into the multi client feature of delve

cc @jhendrixMSFT, @lggomez, @quoctruong91, @iantalarico and @pongad as well for your thoughts

Also linking https://github.com/Microsoft/vscode-go/issues/763 here as it was meant to track the `stopOnEntry` feature

**Comment by jhendrixMSFT** [comment]
Hmm I can't repro this with the latest version.

**Comment by jhendrixMSFT** [comment]
Closing as I can't repro this.  If you have a repro with recent bits please re-open and I'll take a look.
