### ISSUE TITLE
Display comment in suggest.

### ISSUE THREAD

**Issue by edDimensi** [Microsoft/vscode-go#1158]
Suggests not show comments for fields in struct when i typing.
```
// DiscordMessage - message for discord webhook
type DiscordMessage struct {
	Username string `json:"username,omitempty"`
	// AvatarURL for bot
	AvatarURL string  `json:"avatar_url,omitempty"`
	Content   string  `json:"content,omitempty"`
	Embeds    []Embed `json:"embeds,omitempty"`
}
```

![image](https://user-images.githubusercontent.com/11390039/29591469-6fe5b366-87a7-11e7-8a7e-22b4437ccc95.png)
![image](https://user-images.githubusercontent.com/11390039/29591478-783fe8ce-87a7-11e7-8919-c953ecb7bcc4.png)

**Comment by ramya-rao-a** [comment]
This is being tracked in #194 Please follow that issue
