### ISSUE TITLE
Feature request: Support for goderive

### ISSUE THREAD

**Issue by dahankzter** [microsoft/vscode-go#1160]
A cool tool was just released by @awalterschulze https://github.com/awalterschulze/goderive and it would be really cool with editor support.

**Comment by awalterschulze** [comment]
Wow yes, this would be really nice :)

**Comment by ramya-rao-a** [comment]
Maybe I am missing something, but from what I read from https://github.com/awalterschulze/goderive, the way to use this tool is to run `goderive ./...` which can be done easily from the terminal.

What kind of editor support will help here?

**Comment by awalterschulze** [comment]
My usecase would be that `goderive <filename>` is run on a file whenever I save it.  Just like gofmt.

It could also be nice if the command line flags were configurable.

Would that be possible?

**Comment by ramya-rao-a** [comment]
Yes, configuring the flags is possible. For example, we do this for the formatting feature.

I wouldnt want to run this on every save, instead implementing this via a command and using the command when required makes sense.

PRs are welcome.

**Comment by ramya-rao-a** [comment]
I do believe this is a cool feature to have, although I am afraid I don't believe this extension is the right place for it. 

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features. 

Therefore, one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.
