### ISSUE TITLE
Feature request: support expanderr

### ISSUE THREAD

**Issue by AlekSi** [microsoft/vscode-go#1161]
https://github.com/stapelberg/expanderr

**Comment by ramya-rao-a** [comment]
Looks cool, PRs welcome.
I can help out if anyone is interested

**Comment by mrkaspa** [comment]
I can help too

**Comment by hanleym** [comment]
@ramya-rao-a I created a PR (#1335) that should fully implement it. Let me know if there is anything I missed. P.S. Thanks for being awesome; your episode of gotime was great.

**Comment by ramya-rao-a** [comment]
@hanleym Thanks!
I'll take a look at the PR sometime this week.

**Comment by dastergon** [comment]
Any updates on this PR? `expanderr` support is a quite useful addition

**Comment by ramya-rao-a** [comment]
The corresponding PR #1335 has been closed as it hasnt seen any activity in over a year.
The general approach there is right, so if anyone wants to pick it up, they are most welcome

**Comment by ramya-rao-a** [comment]
While I do see the merits of this feature, although I am afraid I don't believe this extension is the right place for it anymore.

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features.

Therefore, one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so. Closing this issue in favor of having it implemented as a separate extension.

Thanks for your patience.
