### ISSUE TITLE
Debug is very slow in Go 1.9

### ISSUE THREAD

**Issue by zaaksam** [Microsoft/vscode-go#1166]
macOS Sierra 10.12.6
Go 1.9
VS Code 1.15.1
Go extension 0.6.63
delve 1.0.0-rc.1 (Build Id: b6077a6a35c48a31716aad2ad3fdf77bbdf70abd)

launch.json
```
{
            "name": "goproject",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/goproject",
            "env": {},
            "args": [],
            "showLog": true,
            "trace": "verbose"
        }
```

User Settings is default, none breakpoint, just press Fn+F5, and it spend about 1 minute to start.

vscode-go-debug.txt
```
Verbose logs are written to:
/var/folders/_f/7fjzkvdn6fgd4mhr2fnglpfw0000gn/T/vscode-go-debug.txt
11:19:52 AM, 8/28/2017
InitializeRequest
InitializeResponse
Using dlv at: /gocode/bin/dlv
2017/08/28 11:20:38 server.go:73: Using API v1
2017/08/28 11:20:38 debugger.go:97: launching process with args: [/gocode/src/goproject/debug]
API server listening at: 127.0.0.1:2345
InitializeEvent
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
ThreadsRequest
2017/08/28 11:20:39 debugger.go:505: continuing
...
```

In terminal: `bash -c "date && go build && date"`
```
Mon Aug 28 11:19:37 CST 2017
Mon Aug 28 11:19:40 CST 2017
```

**Comment by thanhps42** [comment]
Me too

**Comment by zeallag** [comment]
me to

**Comment by xxxtonixxx** [comment]
Me too 👍

**Comment by xxxtonixxx** [comment]
I have reached a workaround using the `exec` mode and launching a prebuild task.

Here is my launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "exec",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/debug",
            "preLaunchTask": "build-debug",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}
```

And here my tasks.json
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build-debug",
            "type": "shell",
            "command": "go",
            "group": "build",
            "presentation": {
                "echo": true,
                "reveal": "never",
                "focus": false,
                "panel": "shared"
            },
            "args": [
                "build",
                "-i",
                "-gcflags",
                "'-N -l'"
            ],
            "linux": {
                "args": [
                    "-o",
                    "debug",
                    "${workspaceRoot}/main.go"
                ]
            },
            "osx": {
                "args": [
                    "-o",
                    "debug",
                    "${workspaceRoot}/main.go"
                ]
            },
            "windows": {
                "args": [
                    "-o",
                    "debug.exe",
                    "\"${workspaceRoot}\\main.go\""
                ]
            },
            "problemMatcher": [
                "$go"
            ]
        }
    ]
}
```

These files are into my .vscode folder 👍

**Comment by Zaaksam** [comment]
@xxxtonixxx Thanks! It's very helpful for me.

**Comment by goofle** [comment]
Any news about fixing this? It should be easier than creating a tasks.json.
And be aware, it compiles EVERYTHING, even the packages you haven't used in your project.

**Comment by xxxtonixxx** [comment]
I think it is problem of dlv. I tested using shell and dlv command...

**Comment by goofle** [comment]
Yeah, I did search around a little and it seems the issue's roots go back to `go 1.9`. It probably doesn't make sense for `dlv` developers to make a "workaround" solution either. And meanwhile your suggestion seems the right way to proceed, so I'm going with the tasks.json file.

**Comment by ITSecMedia** [comment]
I thought I'm the only one with this problem that suddenly came up...

**Comment by SteelPhase** [comment]
I think this is going to be related to derekparker/delve#970 and golang/go#19340

**Comment by goofle** [comment]
Forgive me, but what is optimized code exactly? Can anyone elaborate?

**Comment by SteelPhase** [comment]
I think this goes into more detail than i can about [compiler optimizations](https://github.com/golang/go/wiki/CompilerOptimizations) in Go.

**Comment by leesjensen** [comment]
I used the task workaround to speed up debugging of the application, but I still get a slow down on debugging tests. Does anyone have a work around for that? Very painful.

**Comment by delaneyj** [comment]
On win10x64 with go1.9 I'm getting `Warning: the task 'build-debug' is a shell command and either the command name or one of its arguments has unescaped spaces. To ensure correct command line quoting please merge args into the command.`.  Not sure what part its complaining about.

**Comment by stevebriley** [comment]
Running Windows 10. Visual Studio Code, and vscode-go 0.6.67.

Running the following code: main.go
```
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("Welc\nome to the playground!")
	tar := "poof"
	var ssd string

	fmt.Println("The time is", time.Now())
	fmt.Println("Just when you think you can't " + tar + "you go and BIGly... " + ssd)

}
```

Here are the timing results until I could see output from entering debug mode with 0 breakpoints...
- VSCode-Go with Go 1.9.2 takes 22 seconds
- VSCode-Go with Go 1.8.5 takes 6 seconds
- JetBrains GoLand EAP with Go 1.9.2, takes 3 seconds

**Clearly, there's some serious performance issues that need to be resolved. =(**

Also, for some reason, there's no actual difference between "Start Debugging", and "Start Without Debugging" in VSCode. They both stop at breakpoints.

**Comment by stevebriley** [comment]
What data do I have to collect to help diagnose and resolve this?

**Comment by SteelPhase** [comment]
As i understand it, the changes for golang/go#19340 are supposed to make it into go 1.10, and delve   will be able to resolve derekparker/delve#970 by reverting the change to recompile all dependencies to ensure optimizations are disabled. This should all go away around the release of 1.10

**Comment by tms320** [comment]
I have the same problem - debugging starts in 20-25 seconds after I push "Start Debugging" button.
My OS is Windows 10, Go v.1.9.2, delve [1.0.0-rc.2] 2017-10-16.

**Comment by SteelPhase** [comment]
@tms320 Go 1.10 is planned for February, once that is released this problem should be able to be resolved.

**Comment by pd93** [comment]
This issue popped up for me today. After reading the comments above, I got curious and temporarily installed the [Go 1.10 beta1](https://golang.org/dl/#go1.10beta1) (on Windows 10) to see if it's any better. From what I can tell, this is indeed fixed in the next version. Bring on Feb.

**Comment by SteelPhase** [comment]
So go 1.10 is out, and delve 1.0.0 is also available. I've tested using both of those and the latest version of vscode. Start Debugging is noticeably faster now. Technically this issue can be closed now. Though there is not full solution for anyone stuck on 1.9.

**Comment by rrrezende** [comment]
Starting is fast for me with go 1.10 and delve 1.0, but stopping/restarting the debugger is still very slow.

**Comment by SteelPhase** [comment]
@rrrezende I actually have run into any issues with stopping and restarting. Maybe that is related to another issue.

**Comment by napalm684** [comment]
Running on Ubuntu 16.04 way faster almost immediate stop/start time with go 1.10

**Comment by zaaksam** [comment]
Back to normal on Go 1.10
