### ISSUE TITLE
Not displaying global variables and objects data in a array in debug panel

### ISSUE THREAD

**Issue by jayantnd** [Microsoft/vscode-go#1168]
value of address object data is not displaying in myUser array. but displaying if the object is not in array. [Mark-1, 2]

x is a global variable but not displaying in "VARIABLES" section. to check, we need to add a watch. [Mark-3]. 

please check the image attached.

![screen shot 2017-08-28 at 12 48 02 pm](https://user-images.githubusercontent.com/2960473/29786952-09906d10-8bfb-11e7-8564-c1b543b1060d.png)

**Comment by ramya-rao-a** [comment]
This is a limitation on v1 apis of delve that only looks 1 level deep when resolving variables.
A few updates ago in the Go extension, we have added a way to use v2 apis which lets us configure delve more deeply. Add the below in your settings to be able to see the nested variables:

```
"go.delveConfig": {
    "useApiV1": false,
    "dlvLoadConfig": {
        "followPointers": true,
        "maxVariableRecurse": 2,
        "maxStringLen": 64,
        "maxArrayValues": 64,
        "maxStructFields": -1
    }
}
```

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode-go/blob/0.6.85/package.json#L431-L468 to learn more
