### ISSUE TITLE
How can i transmit ${workspaceRoot} to Go environment?

### ISSUE THREAD

**Issue by free1139** [Microsoft/vscode-go#1169]
I do it like below, but go.testEnvVars it's not work.

// user define
{
    "go.gopath": "C:\\Users\\SHU\\ws\\golibs;${workspaceRoot}", // ${workspaceRoot} has worked.
    "go.testEnvVars": {
        "PJROOT":"${workspaceRoot}" // it not work,  os.Env("PJROOT") has printed out "${workspaceRoot}".
    },
    "go.toolsEnvVars": {
        "PJROOT":"${workspaceRoot}"
    }
}

**Comment by ramya-rao-a** [comment]
this is being tracked in #736

**Comment by ramya-rao-a** [comment]
In the latest update to the Go extension, `${workspaceRoot}` will be resolved when it is passed to `go.testEnvVars` setting
