### ISSUE TITLE
GO binary check configured go.gopath

### ISSUE THREAD

**Issue by variab1e** [Microsoft/vscode-go#117]
Currently it only checks the environment variable, but I set this per-console. so when I launch from the gui, it doesn't get set via the env.

Would be an easy fix, if I am not mistaken, in `/src/goCheck.ts` changing:

_line:14_

	//TODO: Less hacky?
	var go: string;
	if (process.env.GOROOT) {
		go = path.join(process.env["GOROOT"], "bin", "go");
	} else if (process.env.PATH) {
		var pathparts = (<string>process.env.PATH).split((<any>path).delimiter);
		go = pathparts.map(dir => path.join(dir, 'go' + (os.platform() == "win32" ? ".exe" : ""))).filter(candidate => fs.existsSync(candidate))[0];
	}
	if (!go) {
		vscode.window.showInformationMessage("No 'go' binary could be found on PATH or in GOROOT.");
	}

to:

_line:14_

	//TODO: Less hacky?
	var go: string;
	if (process.env.GOROOT) {
		go = path.join(process.env["GOROOT"], "bin", "go");
	} else if (process.env.PATH) {
		var pathparts = (<string>process.env.PATH).split((<any>path).delimiter);
		go = pathparts.map(dir => path.join(dir, 'go' + (os.platform() == "win32" ? ".exe" : ""))).filter(candidate => fs.existsSync(candidate))[0];
	} else {
		go = getBinPath(go) {
	}
	if (!go) {
		vscode.window.showInformationMessage("No 'go' binary could be found on PATH or in GOROOT.");
	}

Thus using the configured gopath as a last resort.

**Comment by lukehoban** [comment]
Do you have an environment where `go` is installed in your `GOPATH`?  I didn't know that was possible.  My understanding was that `go` had to live in `GOROOT/bin`.

Do you not have the `go` binary in your shared PATH?

**Comment by variab1e** [comment]
@lukehoban  I am on windows and use [ConEmu](https://github.com/Maximus5/ConEmu) which wraps my terminals, both powershell, cmd, and msys2. Each time ConEmu loads I set GOROOT and GOPATH. For example, for cmd; I have an init.bat that runs before the console loads:

	@if exist "%USERPROFILE%\dev\lib\go" (
		set "GOROOT=%USERPROFILE%\dev\lib\go"
		
	)
	:: add GOROOT to PATH ; GOROOT can only be added to PATH if checked if defined
	@if defined GOROOT (
		set "PATH=%USERPROFILE%;%GOROOT%\bin;%PATH%"
		set "GOPATH=%USERPROFILE%\dev"
	)

Thus, the PATH, GOPATH, and GOROOT are not set at the system level, but the console level/program level.

**Comment by variab1e** [comment]
So if I am in ConEmu and I run code blah.go everything loads fine. It is just that is not nearly as easy as double clicking an icon in the gui...

**Comment by lukehoban** [comment]
Got it.

How does the fix you suggested earlier help with this then?

Or even more basically - if Code is running without any environment variables indicating where to find `go`, how are thinking of locating it?

**Comment by variab1e** [comment]
Yes, to the first bit, and secondly, it is not at GOPATH/bin. But the way I read through the code for `getBinPath` is that it recursively searches the subdirectories until it finds the relevant file, correct?

`go.goroot`, as the old error used to say would work, but as I understand it, the error was a misnomer correct? And not actually a configurable item?

**Comment by lukehoban** [comment]
The current `getBinPath` doesn't do a recursive search, but even if it did I don't think it would typically find the `go` binary inside `GOPATH`. 

I think we should go ahead and add a new configuration option to override the `GOROOT`.

**Comment by variab1e** [comment]
Cool, that would definitely do the job!

**Comment by variab1e** [comment]
I got a chance to test this today, the new release 0.6.17 and it is still a no go. Was it working on your side? 


    "go.gopath":  "C:/Users/ehiller/dev",
    "go.goroot": "C:/Users/ehiller/dev/lib/go"

The go binary is under `C:/Users/ehiller/dev/lib/go/bin/go.exe`

From what I can tell it should be reading go.goroot from 

src/goInstallTools.ts

	var goroot = vscode.workspace.getConfiguration('go')['goroot'];
	if (goroot) {
		process.env["GOROOT"] = goroot;
	}

and then processing it in  src/goPath.ts --> hitting the `if (process.env["GOROOT"]) {` correct?

	export function getGoRuntimePath(): string {
		if (runtimePathCache) return runtimePathCache;
		if (process.env["GOROOT"]) {
			runtimePathCache = path.join(process.env["GOROOT"], "bin", "go");
		} else if (process.env.PATH) {
			var pathparts = (<string>process.env.PATH).split((<any>path).delimiter);
			runtimePathCache = pathparts.map(dir => path.join(dir, 'go' + (os.platform() == "win32" ? ".exe" : ""))).filter(candidate => fs.existsSync(candidate))[0];
		}
		return runtimePathCache;
	}

Am I missing anything?
