### ISSUE TITLE
Build complete workspace when buildOnSave is set to workspace

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-go#1170]
Testing https://github.com/Microsoft/vscode/issues/33297

When the setting `go.buildOnSave` is set to `workspace`, in a multi-root workspace it is expected to build the complete workspace instead of just the `workspace folder`.  I see it was mentioned expected but this can be changed.

Here is the use case: In the sample MR set up I have two root folders `hello` and `stringutil`. I wanted to configure settings in `stringutil` folder that on changes in this folder, I would like to build all other workspace folders too.

**Comment by ramya-rao-a** [comment]
Closing this as "as-designed"
For now, in multi-root set-up, in the Go extension `workspace` in build/lint/vet on save settings will not mean the entire workspace. Build/Lint/Vetting the entire workspace will get expensive and there are no great benefits for the same.

We will re-visit if and when there is user feedback in this direction
