### ISSUE TITLE
Toggling test coverage is not removing all coverage decorations

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-go#1171]
Testing https://github.com/Microsoft/vscode/issues/33297

- Set coverage decorator for folder StringUtil to `highlight`
- Open `reverse.go` file and Run command `toggle test coverage in current package` 
- Code coverage is shown by highlight
- Change the setting to `gutter`
- Run the command again

Expected to remove all coverage decorations. But not.

**Comment by ramya-rao-a** [comment]
@sandy081 I can only repro this if the settings editor and the Go file are in 2 separate editor groups.
Do you recall if thats what you saw as well?

**Comment by sandy081** [comment]
I do not remember if I have those files in two groups, but definitely those two are opened. Anyway good thing is that you can reproduce it and fixed it. 👍
