### ISSUE TITLE
Refactoring would be nice

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode-go#1173]
Hello, first of all, let me say that GoCode is a really cool package and I especially appreciate the support for Delve that it gives me. What would be really nice would be some form of refactoring. Maybe just "Extract Method" to start with as this is probably the most likely refactoring feature to be needed. Alternatively, do you or anyone else know of any Golang refactoring extensions for VS Code?

**Comment by ramya-rao-a** [comment]
The extract method feature is tracked in #588
Other refactoring are tracked in #649 

Yes refactoring would be a cool feature to add. PRs are welcome and I can help out anyone who wants to give it a try.

Closing this issue in favor of the 2 linked issues

**Comment by ramya-rao-a** [comment]
The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension has this feature. Please see [Refactoring in VS Code](https://code.visualstudio.com/docs/editor/refactoring) on how you can use the refactor feature.
