### ISSUE TITLE
I set go.docsTool to gogetdoc before, and my mac become very very slow and even crashed

### ISSUE THREAD

**Issue by zz-bmj** [Microsoft/vscode-go#1174]
@ramya-rao-a I set go.docsTool to gogetdoc before, and my mac become very very slow and even crashed. Maybe it needs some fix?

**Comment by zz-bmj** [comment]
the previous issue is https://github.com/Microsoft/vscode/issues/32935#issuecomment-325889252

**Comment by ramya-rao-a** [comment]
@zz-bmj Are you sure that gogetdoc was the reason?

Did you see it taking up a lot of CPU? Can you repro the issue by enabling it again?

cc @zmb3

**Comment by ramya-rao-a** [comment]
@zz-bmj Closing this issue as we havent heard back from you in a while.
If you still see perf issues with `gogetdoc` please drop in a comment here with details
