### ISSUE TITLE
Debugging on Windows doesn't build exe

### ISSUE THREAD

**Issue by cdhunt** [Microsoft/vscode-go#1177]
I'm trying to debug an issue with Packer on Windows and when I try to launch debugging in VSCode, it appears to produce a binary with no extension and then cannot launch said binary.

launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {"GOPATH": "C:\\go",
                "GOROOT": "C:\\Go"},
            "args": ["build"],
            "showLog": true
        }
    ]
}
```

Output

```2017/08/30 09:51:04 server.go:73: Using API v1
2017/08/30 09:51:04 debugger.go:97: launching process with args: [c:\go\src\github.com\hashicorp\packer\debug build]
API server listening at: 127.0.0.1:2345
2017/08/30 09:51:08 debugger.go:505: continuing
Couldn't start Packer: exec: "c:\\go\\src\\github.com\\hashicorp\\packer\\debug": file does not exist```

**Comment by ramya-rao-a** [comment]
@cdhunt Can you try running delve from the command line and see if you are able to get it debugging successfully?

Just run `dlv debug` in the from whatever is the folder you have opened in vs code.

I noticed that you have GOPATH and GOROOT set to the same location. I have a feeling we aren't suppose to do that

**Comment by ramya-rao-a** [comment]
Also you seem to be passing the args `build`. Is that for the program you are trying to debug?

**Comment by cdhunt** [comment]
@ramya-rao-a I see vscode installed delve `Installing github.com/derekparker/delve/cmd/dlv SUCCEEDED` but I can't find an executable and `dlv debug` fails.

My GOPATH and GOROOT are actually different, I just anonymized them for the issue.

`build` is indeed the command argument for the program I'm attempting to debug.

**Comment by ramya-rao-a** [comment]
> but I can't find an executable

You mean the `dlv` executable? That would be in %GOPATH%/bin

> dlv debug fails.

You mean when you run from the command line? What is the error?

I tried debugging https://github.com/hashicorp/packer as well and I get the same error. It is coming from https://github.com/hashicorp/packer/blob/v1.0.4/main.go#L91

I get the same error when running delve from the command line as well.

This is not an issue with the Go extension. Please check with the owner/author/maintainer/contributors of https://github.com/hashicorp/packer about the best way to debug it using delve.

**Comment by andrewsav-datacom** [comment]
Just for the sake of any future visitors who try to debug packer. Packer spawns child processes to do all subtasks it needs to do, so even if you get this particular issue solved, you are still not there - you'll be debugging just the initial parent that is not doing match. I personally not sure how and if hashicorp debugs this product, so I personally had to resort to debugging by logging, without breakpoints.

**Comment by ramya-rao-a** [comment]
Thanks for the information @andrewsav-datacom!
