### ISSUE TITLE
Function definition popping up every time when opening bracket

### ISSUE THREAD

**Issue by isavcic** [Microsoft/vscode-go#1181]
Hello,

Function definition is popping up every time when opening bracket like this:

<img width="579" alt="vscode-always-showing-definition" src="https://user-images.githubusercontent.com/3032922/29949397-c2f5d770-8eb4-11e7-8553-46a327797e55.png">

Notice that this is a different popup than a regular mouseover definition popup (which I want to happen):

<img width="552" alt="vscode-mouseover" src="https://user-images.githubusercontent.com/3032922/29949411-d5970c0a-8eb4-11e7-82bb-b9806f8647e6.png">

Is this a bug, and if not, is there any advice how to get rid of it?

Thanks

**Comment by ramya-rao-a** [comment]
Thats called "Signature Help" or "Parameter Hints"
Its helpful when the function in question has multiple parameters.
As you type the parameter, the underline moves to the current parameter.

You can disable this by setting `"editor.parameterHints": false`

**Comment by isavcic** [comment]
Thank you for the explanation! Any way to change font size of it?

**Comment by ramya-rao-a** [comment]
Not at the moment. There is an open issue in vscode tracking that. You can add your upvotes/comments there https://github.com/Microsoft/vscode/issues/13480
