### ISSUE TITLE
Struct hover has extra indent

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-go#1187]
![image](https://user-images.githubusercontent.com/323878/29991494-cc43d006-8f3c-11e7-807a-dd2e2aa411df.png)

The second and third lines of the hover is double indented

**Comment by uudashr** [comment]
Should be fixed on godef side https://github.com/rogpeppe/godef/pull/70

**Comment by ramya-rao-a** [comment]
Thanks @uudashr!
