### ISSUE TITLE
vagrant integration

### ISSUE THREAD

**Issue by alioygur** [microsoft/vscode-go#1188]
hello, I am usign vagrant on MacOS, I haven't install any go and its packages on my . host machine (MacOS)

So this extension requires go packages like goreturn, go vet etc. How can i say to vscode that run these commands on remote host (vagrant)

thank you.

**Comment by ironcladlou** [comment]
I'm interested in a generalization of this concept for remotely editing code in a VM or container.

A possible way forward here might be additional language server client configuration options. The language server could be anywhere (e.g. the host, a VM, a container), colocated with the source, and the plugin could easily support that use case.

However, to actually be useful I suspect we'll need a *comprehensive* language server to which nearly all useful analysis operations can be delegated (including those in the Go toolchain itself, e.g. `vet` and even `list`).

If any of that makes sense, maybe https://github.com/dominikh/go-tools/issues/136 is the first focus area?

/cc @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@ironcladlou With [Remote Development with VS Code](https://code.visualstudio.com/blogs/2019/05/02/remote-development), we now have a good story around the remote code editing that you have referred to.

@alioygur If the above does not support vagrant scenarios, then https://github.com/Microsoft/vscode would be the right place to log an issue.

Thanks for your patience and Happy Coding!
