### ISSUE TITLE
Command to "go get" a package that is not available

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1189]
Say there is an import statement for a package that is not yet in "imported" or downloaded.
A new command to run to get this package can be useful.

**Comment by ramya-rao-a** [comment]
Its pretty easy to implement, if anyone wants to take a stab at it, I can help

**Comment by juicemia** [comment]
Isn't this already a built-in feature of dependency managers like Glide?

I'm willing to work on it, just want to know if it's something worth doing.

Maybe it would be useful to just download the dependencies to `$GOPATH/src`.

**Comment by juicemia** [comment]
Also, I imagine you have some idea of how this should be implemented?

**Comment by ramya-rao-a** [comment]
I am not aware of Glide, but I believe we can have this feature regardless.

- You can have a command `Go: Get Package`. When this command is run if the line under the cursor is an import statement, we can spawn a process to run `go get -u` on it. 
- Taking this a step further, we can have code actions. I refer to those light bulb like images that can appear on the import statement clicking on which results in running the `go get` for the package
- To show the code action, we need to first check if the package in question exists or not. One way to do this would be to run a `go list` on the import path, but there might be better ways to do the same

**Comment by ramya-rao-a** [comment]
To begin with, you can take the implementation of the `Go: Browse Packages` https://github.com/Microsoft/vscode-go/blob/0.6.65/src/goBrowsePackage.ts as a reference

The logic to fetch the import path from the import statement is already present in that file.
You can re-use that

**Comment by juicemia** [comment]
Awesome! Thanks for all the info :)

**Comment by ramya-rao-a** [comment]
Closing this issue as the feature has been implemented
