### ISSUE TITLE
Go standard library src should be read-only by default

### ISSUE THREAD

**Issue by yhuang0** [Microsoft/vscode-go#1190]
When navigating outside of my project code to go's standard library, those files should be marked as readonly in my editor so I don't accidentally change something and not know about it. This should be a config like: "go.readOnlyStdLib" and should be set to true by default.

**Comment by ramya-rao-a** [comment]
We can use [TextDocumentContentProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametextdocumentcontentprovideraspan-classcodeitem-id458textdocumentcontentproviderspan) to provide read only documents in the editor. This can technically be done as a separate command.
You could then map the current keyboard shortcut for the `Go to Definition` command to this new command.

But changing the behavior of the `Go to Definition` command itself is not in the hands of the extension. That would be changing core behavior.

The [DefinitionProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namedefinitionprovideraspan-classcodeitem-id522definitionproviderspan) would have to return the info of whether the Definition Location is to be read-only or not
The core code in VS Code would have to react to this and show the file at location at read-only.

**Comment by ramya-rao-a** [comment]
@yhuang0 Have you tried setting the folder with sub libraries as read-only? VS Code will then honor that setting when opening the files.

**Comment by yhuang0** [comment]
Yes that works but it's not a good solution.

**Comment by ramya-rao-a** [comment]
why not?

**Comment by ramya-rao-a** [comment]
@yhuang0 Closing this issue as we havent heard back from you in a while
