### ISSUE TITLE
dlv not work on MacOS

### ISSUE THREAD

**Issue by hero0926** [Microsoft/vscode-go#1192]
My MacOs still occurs Failed to continue, "Error : spawn users/ksh/go/bin/dlv ENOENT".
My launch.json looks like

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${fileDirname}",
            "env": { 
                "GOPATH" : "Users/ksh/go",
                "PATH" : "Users/ksh/workspace/go/bin;Users/ksh/go/bin;" },
            "args": [],
            "showLog": true
        }
    ]
}
```
from  #466 and #332.... They suggested not to use ${}, So I used absolute path but it also won't worked.
Maybe because of brew install problem? Anybody help?

**Comment by ramya-rao-a** [comment]
Your GOPATH is `users/ksh/go`, and as per the error message, that is where dlv is being run from
You said you installed using brew, but brew wouldnt install delve in your GOPATH

Run `which dlv` in your terminal outside VS Code. Does the output match with "users/ksh/go/bin" ?

Most probably you have 2 dlvs
One in your GOPATH/bin
The other in your PATH

If so delete the one in the GOPATH and try again

**Comment by hero0926** [comment]
@ramya-rao-a outside of vs code, iterm couldn't find dlv command... i think brew confused with my path. should reset things... and i found 3 more dlvs in every path. thanks for your help

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
