### ISSUE TITLE
None of the go editor features are working

### ISSUE THREAD

**Issue by Nais777** [Microsoft/vscode-go#1195]
Yesterday when working on a project import statements would give suggestions or automatically populate, a slew of tools would run on save, syntax highlighting would occur, links would appear to run tests directly in test files, etc. Today, none of this is happening. I have restarted vscode, disabled and re-enabled the extension, and rebooted my computer. It seems to coincide with your latest release. Any ideas?

OS: OSX 10.12.6
VSCode: 1.15.1
Go Extension: 0.6.64

EDIT:
Thinking about it, this was working this morning. I was demoing an app, doing code on the screen and relying on code complete to find the methods I wanted since I wasn't familiar with the package.

I just manually installed version 0.6.63 and everything is working again.

**Comment by ramya-rao-a** [comment]
@Nais777 Can you run the command `Go: Current GOPATH` and see if the output matches your GOPATH?
Also please share your Go related settings

The latest update was out around noon PST. So that can explain why everything was fine this morning for you.

**Comment by Nais777** [comment]
It is my current GOPATH: /Users/CLHQ3496JacobLambert/Code/go

go version go1.9 darwin/amd64

What other Go related settings to you need? I haven't set any in vscode, I have just installed the extension.

**Comment by Nais777** [comment]
It seems that the issue was with the package auto updating. After dropping the version to 0.0.63, then manually updating to 0.6.64 to get you the output of `Go: Current GOPATH`, everything is working again on the newer version.

**Comment by ramya-rao-a** [comment]
That is super weird. I'll keep an eye out for anybody else facing similar issues.

Thanks for getting back on this and Happy Coding!

**Comment by wwkeyboard** [comment]
I had a similar problem. After an update `goimport` and `golint` stopped running on save. After running `Go:Install/Update Tools` everything seems to be working again. IDK what the root cause was but this fix has me rolling again.
