### ISSUE TITLE
Can`t debug a Go program with mutil GOPATH which is set in configurations.env

### ISSUE THREAD

**Issue by ansencumt** [Microsoft/vscode-go#1196]
It works fine for the past 2 weeks. But today I update the go extensions to 0.6.64, it can`t run any more.
The launch.json:
![image](https://user-images.githubusercontent.com/5181385/30091919-b77ee9f2-92ee-11e7-81d2-7fd3fdaaca5a.png)

Then the error:
![image](https://user-images.githubusercontent.com/5181385/30091965-cbdd2058-92ee-11e7-8c03-768566e40387.png)

In fact, I have the package "bitbucket.org/ansenwork/ilog" in my GOPATH "E:\\golang\\golibs;".
From the error message, It seems that the debugger doesn`t scan the GOPATH which I set in the configurations.env.

**Comment by ramya-rao-a** [comment]
In this case what is your `${workspaceRoot}` ?

**Comment by ansencumt** [comment]
Yes, that`s right.
but even if I replace ${workspaceRoot} to e:\Work\yunkai\robot, it also can`t debug.

**Comment by ramya-rao-a** [comment]
I have a fix in master, can you try it out?

You will need to download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix and then run `code --install-extension Go-latest.vsix` from the location where you downloaded that file.
Then reload VS Code window

**Comment by ramya-rao-a** [comment]
@ansencumt Does the fix in https://github.com/Microsoft/vscode-go/issues/1196#issuecomment-327544415 work for you?

**Comment by ramya-rao-a** [comment]
The fix for this issue has been released with the latest update to the Go extension (0.6.65)

**Comment by ansencumt** [comment]
The Go extension(0.6.65) work fine. Thx
