### ISSUE TITLE
"Run VS Code with admin privileges so the changes can be applied"

### ISSUE THREAD

**Issue by dannolan** [Microsoft/vscode-go#1199]
I'm on macOS Sierra 10.12.6, have just installed the latest update to the Go plugin and now see this every time I save (and go imports and govet run) in VS Code. Any idea what I can do to fix it as it's... extraordinarily frustrating and cluttering. I've confirmed it's the go plugin as I uninstalled it and the error went away, then reinstalled it.

**Comment by ramya-rao-a** [comment]
> now see this every time I save

What is it that you are seeing?

**Comment by dannolan** [comment]
@ramya-rao-a Hey sorry, I see a banner at the top of VSCode that said "Run VS Code with admin privileges so the changes can be applied", but I restarted my computer and it's gone so I assume it's my fault. THANK YOU SO MUCH FOR YOUR AMAZING WORK ON THIS PLUGIN I LOVE VSCODE AND GO! Also your fantastic GoTime interview was amazing! You rule!

**Comment by ramya-rao-a** [comment]
Thanks for your kind words @dannolan :) and Happy Coding!

**Comment by BrahimS** [comment]
Hi Ramaya, thanks for the good work with VSCODE, i am getting the same notification* each time hit save. 
*: Run VS Code with admin privileges so the changes can be applied.

**Comment by ramya-rao-a** [comment]
@BrahimS can you share a screenshot?

**Comment by BrahimS** [comment]
![screen shot 2017-12-27 at 19 44 01](https://user-images.githubusercontent.com/7687826/34390200-7a7deff0-eb3e-11e7-94c0-5a70e29c120a.png)

**Comment by BrahimS** [comment]
@ramya-rao-a 
Thanks for your replay:
![](https://user-images.githubusercontent.com/7687826/34390200-7a7deff0-eb3e-11e7-94c0-5a70e29c120a.png)

**Comment by ramya-rao-a** [comment]
That message is neither coming from VS Code or the Go extension. It must be coming from one of the extensions you have installed. Can you disable all extensions other than the Go extension and see if you still repro the issue?

**Comment by BrahimS** [comment]
I think that was related to some of the parcel.js dependencies, because since i've disabled it, the notification stop appearing.

Thanks so much for your help.
