### ISSUE TITLE
Should Find References show implementations of interfaces

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode-go#12]
I have an interface with a method on it.

That method is called in another file.

I have several files that implement or conform to that interface which have the method in them.

Should Find References show those implementations or only those where its called and defined like it does currently?

**Comment by lukehoban** [comment]
@jchannon - Was your expectation that you'd see all of these locations returned from find-references?

**Comment by jchannon** [comment]
Yup :smile:

**Comment by ironcladlou** [comment]
If vscode-go's design goal is to delegate Find References to a single community tool (oracle/guru), I'm not sure this feature request should be directed at vscode-go. The results of Find References is going to be entirely dependent upon the capabilities/decisions of the external tool.

**Comment by lukehoban** [comment]
I tend to agree with @ironcladlou.  

I looked at this again as part of moving Find References from a custom tool (my fork of `go-find-references`) to a standard community tool (`oracle`/`guru`). 

I think it is for better or worse not the standard interpretation of "References" to include implementations of interfaces.

But tools like `guru` do offer separate `implements` command which may be helpful.  It might be nice to expose those commands some how - though there's no especially nice way to do that in VS Code (on par with the Find References user experience).

Going to close this for now though.  If there's a concrete proposal for something additional to do we can open separately.
