### ISSUE TITLE
go vet (on save) does not appear to work.

### ISSUE THREAD

**Issue by shurcooL** [Microsoft/vscode-go#120]
I'm using latest stable versions of everything, including VSC (0.10.2) on OS X (10.11.1) with Go extension (0.6.16) and Go (1.5.1), with this config:

```JSON
{
	"go.buildOnSave": true,
	"go.lintOnSave": true,
	"go.vetOnSave": true,
	"go.formatTool": "goimports",
	"go.formatOnSave": true
}
```

### Problem

With this sample file:

```Go
package main

import "fmt"

func main() {
	fmt.Printf("Hello %d.\n", "string not number")
}
```

I'd expect to see what `go vet` displays in a terminal:

```
try-vet $ go vet
main.go:6: arg "string not number" for printf verb %d of wrong type: string
exit status 1
```

But it doesn't show up. Go lint issues do show up, however (as do build errors):

![image](https://cloud.githubusercontent.com/assets/1924134/11454571/373b43ec-95e5-11e5-977f-123e7bd6a204.png)

Am I doing something wrong, or is `go.vetOnSave` not implemented yet?

**Comment by lukehoban** [comment]
Thanks for catching this!

**Comment by shurcooL** [comment]
Confirmed fixed. Thanks!

![image](https://cloud.githubusercontent.com/assets/1924134/11616929/10872b6e-9c3c-11e5-80c3-5c0045eae3c8.png)
