### ISSUE TITLE
Show "Problem" when analysis tools fail, e.g. due to syntax errors

### ISSUE THREAD

**Issue by philipithomas** [Microsoft/vscode-go#1200]
I just spent a long time trying to figure out why my code wasn't auto-formatting or linting. When I opened the developer tools, I found that the gofmt and golint were failing due to syntax errors. 

I expected to see these warnings under the "Problems" field. However, no problems were reported. 

Can lint/formatting errors be reported as problems?

**Comment by ramya-rao-a** [comment]
If there were syntax errors build should have caught them. Have you turned off `go.buildOnSave` setting?

**Comment by ramya-rao-a** [comment]
@philipithomas I just tried formatting and linting on a Go file which has syntax errors. Both work as expected. 

Can you share a sample code where you dont see formatting and linting working?

**Comment by philipithomas** [comment]
@ramya-rao-a This is from awhile ago, so I don't have any handy. Perhaps try removing the package statement at the top? 

Please feel free to close if you cannot duplicate. I think the problem was that an unhandled error was missing.

**Comment by ramya-rao-a** [comment]
In that case, I'll close this issue.
Thanks!
