### ISSUE TITLE
Go: Add Import can't search package contains "_" like "mission_service" properly

### ISSUE THREAD

**Issue by szyhf** [Microsoft/vscode-go#1202]
Hey, I may find a bug ~

While using "Go: Add Import" to search packages.

For example:

I has a package path like `member/hello-service`, I can type "ms" as "m" at "member" and "s" at "server" to find package properly.

But if I has a package path like `member/hello_service`, I can use "mb" in "member" to find, but I can not use "ms" to find "member/hello_service", looks like the char '_' will interrupt the filter search of packages list.

The go-ext version: 
0.6.65
OS Version:
macOS Sierra 10.12.6

**Comment by ramya-rao-a** [comment]
This is due to the filtering behavior of the quick pick control in general

**Comment by ramya-rao-a** [comment]
Logged upstream issue: https://github.com/Microsoft/vscode/issues/34088
