### ISSUE TITLE
Do not create "type args struct" for autogenerated tests if function is a single-argument one

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode-go#1205]
e.g.

```go
func Test_clonePod(t *testing.T) {
	type args struct {
		pod *corev1.Pod
	}
	tests := []struct {
		name    string
		args    args
		want    *corev1.Pod
		wantErr bool
	}{
	// TODO: Add test cases.
	}
	...
}
```

In the code above, instead of generating `type args struct { ...}`, it's sufficient to just specify args field in anonymous struct as `*corev1.Pod` and not generate an additional type. This should help create simpler and more readable tests.

**Comment by ramya-rao-a** [comment]
We use https://github.com/cweill/gotests to generate these tests.
Please log an issue in the repo for gotests
