### ISSUE TITLE
Why it can not show the val when debug galang?

### ISSUE THREAD

**Issue by friends110110** [Microsoft/vscode-go#1206]
Why it can not show the val when debug galang?

**Comment by ramya-rao-a** [comment]
@friends110110 You need to provide more information that just a question :)

Please provide sample code with repro steps and screenshots

**Comment by paulviks** [comment]
@ramya-rao-a Hello,
It is probably about show in the editor the value of a variable in a given line when we debug source code.
Preview screen: 
![proposal](https://user-images.githubusercontent.com/12736118/30274760-2193c218-96ff-11e7-8f92-33edaf660443.png)

**Comment by ramya-rao-a** [comment]
@paulviks you are referring to inline values.

@friends110110 Is that what you meant?

**Comment by friends110110** [comment]
I have fixed the problem. I  use `go build -i  -tags "nopkcs11" -o explorer main.go` instead of go build, then it woks, and could show the val.
