### ISSUE TITLE
Cannot read property 'GOPATH' of undefined

### ISSUE THREAD

**Issue by rpeshkov** [Microsoft/vscode-go#1207]
After upgrade to vscode 1.16 default launch.json configuration doesn't work properly.

I had this in launch.json:

    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Launch app",
                "type": "go",
                "request": "launch",
                "mode": "debug",
                "program": "${workspaceRoot}"
            }
        ]
    }

That's the default "Go: Launch package" configuration.

When I try to launch debug, I get an error "Failed to continue: "TypeError: Cannot read property 'GOPATH' of undefined"". However, if I explicitly set environment variable GOPATH in launch.json, it works fine:

    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Launch app",
                "type": "go",
                "request": "launch",
                "env": {
                    "GOPATH": "/Users/rpeshkov"
                },
                "mode": "debug",
                "program": "${workspaceRoot}"
            }
        ]
    }

**Comment by ramya-rao-a** [comment]
@rpeshkov What version of the Go extension are you using? Can you ensure it is the latest i.e 0.6.65 ?

**Comment by rpeshkov** [comment]
@ramya-rao-a Yes, I have the latest version: 0.6.65

**Comment by ijlopez02** [comment]
I'm having the same issue.

**Comment by ramya-rao-a** [comment]
Ah! looks like an undefined `env` is causing this.
I have pushed a fix in which will be out in the next update which will be some time at the end of next week.

Until then the workaround is to set `env` to `{}` in the debug configuration

**Comment by sepisoad** [comment]
`Until then the workaround is to set env to {} in the debug configuration`
I just got a little bit confused, can you explain more?

**Comment by wusendong** [comment]
@sepisoad 

it work for me by add "env": {}
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch file",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${file}",
            "env": {} // <-----add this
        }
}
```

**Comment by sepisoad** [comment]
thanks @wusendong

**Comment by AlekSi** [comment]
Thank you so much!

**Comment by skovtunenko** [comment]
Thank you, temp fix works fine!
