### ISSUE TITLE
Too many goreturns processes

### ISSUE THREAD

**Issue by pilwon** [Microsoft/vscode-go#121]
The latest version (v0.6.16) has a CPU usage issue causing sluggishness on OSX Yosemite, due to a lot of `goreturns` processes being spawned and run at the same time in the background.

**Comment by lukehoban** [comment]
@pilwon. Just checking:

1. Do you have AutoSave turned on?
2. Do you have "go.formatOnSave" turned on?

**Comment by pilwon** [comment]
@lukehoban `AutoSave` is disabled but `forrmatOnSave` option is on. Let me know how I could help with debugging this issue. Is it normal that multiple processes of `goreturns` are created in the background?

**Comment by lukehoban** [comment]
I spent some time trying to reproduce this, but haven't been able to yet.

Can you give any more details on what file you were working in when you saw this?  `goreturns` should never take more than 100s of milliseconds, and should only be spawned on `save` with a dirty buffer.  I'm not sure what could cause a lot of them to get spawned.

It could be that something about your file is causing `goreturns` to take an extremely long time - that would likely be a bug in `goreturns` but would be interesting to try to pinpoint it.

**Comment by lukehoban** [comment]
Closing for now - please reopen if you have any additional details you can share.
