### ISSUE TITLE
Find all references only lists results in the current file

### ISSUE THREAD

**Issue by KyleMoser** [Microsoft/vscode-go#1210]
Windows 10
VSCODE 1.16.0
Go 1.9
GOPATH is d:\users\me\documents\vscode\projects
GOROOT is c:\Go
Project is in d:\users\me\documents\vscode\projects\src\root\portal

Right clicking a struct and clicking "Find all references" only shows references in the same file. 
Right clicking a function and clicking "Find all references" only shows reference in the same file.
Looks like ctrl+clicking a function call works fine and jumps to the function definition. 
I have tried running gocode close, it doesn't change anything.
If I uninstall and reinstall vscode, the extension still shows up as installed, so I'm not sure that does anything. 

I've been at it for hours, I have no idea why this doesn't work. I did notice once (after a reinstall, and deleting the roaming\code folder) that ctrl+shift+p then go:install tools installed the tools, but then prompted me again with an analysis message that tools were missing... even though they were right there in the bin folder.

**Comment by ramya-rao-a** [comment]
Are you using the language server?
If not then `guru` is the tool being used to find the references.
Can you use `guru referrers` command from the command line and see if you are able to get references from other file as well?

**Comment by KyleMoser** [comment]
@ramya-rao-a I was trying to do that before, but I couldn't figure out the offset. Let's say I know the name of a struct in a particular file, how do I find out it's offset to use it in the guru command?

**Comment by ramya-rao-a** [comment]
For finding offset, I have this extension: https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset

It will show the offset for current position in the status bar.

Yes, this is a guru issue. 
Sorry couldnt help you much here
