### ISSUE TITLE
Add support for The Go Playground

### ISSUE THREAD

**Issue by dastergon** [Microsoft/vscode-go#1211]
Hi,

It would be really handy to either share code in [The Go Playground](https://play.golang.org/) or compile and run code within it, through VS Code. There is already an implemented [tool](https://github.com/haya14busa/goplay) that interacts with the playground, so, that tool could be easily integrated with this extension, or some of its functionalities could be implemented within the extension to reduce external dependencies.

Thanks in advance,
Pavlos

**Comment by xmattstrongx** [comment]
👍  agreed with @dastergon. This could def be useful.

**Comment by m90** [comment]
I'd be happy to add this (as I wished for it too already a few times). Will open a PR once done.

**Comment by ramya-rao-a** [comment]
The PR for this has been merged and the feature will be out in the next release

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.69)
