### ISSUE TITLE
Set cwd for formatting tools

### ISSUE THREAD

**Issue by otto-md** [Microsoft/vscode-go#1212]
Im using goimports as a formatting tool and have code that is vendored. So if I remove the validation line below and run formatting I will not get the validation imports line back.

```go
import (
	"fmt"
	"time"

	validation "github.com/go-ozzo/ozzo-validation"
)
.
.
code that uses validation.Foo
```

To solve this you need to send the current working directory `cwd` to [execFile()](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) called [here](https://github.com/Microsoft/vscode-go/blob/45be8dad5daa948f06cb8325212d586263a1236e/src/goFormat.ts#L34).

I dont know enough typescript to do a PR but I found and fixed the same issue in another tool:  https://github.com/spamwax/goimports-sublime-text-3/pull/4

**Comment by ramya-rao-a** [comment]
Is the validation pkg in your case a vendor pkg?

**Comment by ottob** [comment]
> Is the validation pkg in your case a vendor pkg?

Yes it is.

**Comment by ramya-rao-a** [comment]
Ok, I'll try it get this in next week

**Comment by otto-md** [comment]
I reinstalled the extension and it seems to work as expected now. Sorry for the noise.

**Comment by ramya-rao-a** [comment]
No problem @otto-md, thanks for getting back. Happy Coding!
