### ISSUE TITLE
Vscode adds extra 'import' identifier 

### ISSUE THREAD

**Issue by MintyOwl** [Microsoft/vscode-go#1214]
Everytime a new package is added, vscode also adds an extra 'import' alongside.

See 'bufio' example

![vscode-bad-import](https://user-images.githubusercontent.com/7389244/30465325-18aafae8-99f4-11e7-8b18-76dbc58c15a3.jpg)

Doesnt matter whether its goreturns or goimports

Platform: Windows 10
Vscode Release version: 1.16.1

**Comment by ramya-rao-a** [comment]
Can you share exact steps? Do you have `go.autocompleteUnimportedPackages` enabled?

**Comment by MintyOwl** [comment]
Actually this was not  VSCode error, since this happened when I used an aliased import with same name as the package itself. Like so

```
import (
     "bytes"
      myPkg "path/to/myPkg"
     "os"
)
```

If you import another package from here point on, using autocomplete features, then an extra 'import' is added. Ofcourse using same alias as package name is the problem. I donnot know/remember how that manifested as an oversight on my part.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
