### ISSUE TITLE
go to breakpoint

### ISSUE THREAD

**Issue by alioygur** [Microsoft/vscode-go#1216]
is there any way to go to breakpoint shortcut like go to line or go to file?

**Comment by xmattstrongx** [comment]
Hi @alioygur. I am not sure if this will help you or not but I have found this section of the debug tab to be useful. Perhaps you already know of it but if not then maybe this will help you out.  

At he bottom of the debug tab there is a section titled `BREAKPOINTS`. It will list out all of your breakpoints in your code and you can click on each to go to them. I have also found the Deactivate Breakpoints feature to be very useful.

![image](https://user-images.githubusercontent.com/10662489/30513218-4a377b50-9ac5-11e7-89f7-2506228aa49e.png)

Hopefully that helps. Happy bug hunting :smile:

**Comment by alioygur** [comment]
I already know this :) I am looking for a shortcut

16 Eyl 2017 Cmt, saat 17:57 tarihinde Matt Strong <notifications@github.com>
şunu yazdı:

**Comment by ramya-rao-a** [comment]
I am not aware of any such shortcuts.
Even if they were present, it would be a general VS Code feature than related to the Go extension.

For future reference, run the command `Preferences: Open Keyboard Shortcuts` to see all available shortcuts as well as commands to which you can add your own shortcuts
