### ISSUE TITLE
Command D case sensitive option

### ISSUE THREAD

**Issue by xmattstrongx** [Microsoft/vscode-go#1217]
`Command D - Add Next Occurrence`

I have found this shortcut to be a nice substitute for a refactor command that you may find in other IDEs. Unfortunately there does not seem to be an option to do this in a case sensitive manner. 

![image](https://user-images.githubusercontent.com/10662489/30513174-34b122aa-9ac4-11e7-8c38-8ea0cd06e3b5.png)

It would be nice if this option could either be configurable to be case sensitive or perhaps to have another shortcut that could function the same as Command D but in a case sensitive manner.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#34548
