### ISSUE TITLE
Debugging with parameters/flags doesn't properly pass on args.

### ISSUE THREAD

**Issue by mitom** [Microsoft/vscode-go#1224]
To reproduce run the following code:
```go
package main

import "os"
import "fmt"

func main() {
	fmt.Print(os.Args)
}
```
With the following `launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}/main.go",
            "env": {},
            "args": ["switch", "--profile prod", "--account", "foo", "--role", "bar"],
            "showLog": true
        }
    ]
}
```
Used different pattern (putting the parameter flag and value in 1 string and separate strings) to test if it affects it.

```
2017/09/18 10:32:27 server.go:73: Using API v1
2017/09/18 10:32:27 debugger.go:97: launching process with args: [.../Projects/go/src/test/debug switch --profile prod --account foo --role bar]
API server listening at: 127.0.0.1:2345
2017/09/18 10:32:28 debugger.go:505: continuing
[.../Projects/go/src/test/debug switch foo bar]
```
It seems to ignore everything with a `-` in front of it, short parameters (`-p foo`) will just cause it to hang. Tested that if I run the command it says it tries to run in a terminal myself, that works as expected.

```
go version
go version go1.9 darwin/amd64
```
```
code -v
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959
```
go plugin version `0.6.65`

**Comment by ramya-rao-a** [comment]
Works as expected for me.. I tried on Mac and Windows.
What version of delve are you using?
Can you try running delve from the command line and see if it works as expected?

<img width="1097" alt="screen shot 2017-09-18 at 5 01 57 pm" src="https://user-images.githubusercontent.com/16890566/30570011-32894194-9c93-11e7-9281-5e7f693faca7.png">

**Comment by dolmen** [comment]
I think you probably meant this:
```
"args": ["switch", "--profile", "prod", "--account", "foo", "--role", "bar"]
```
instead of:
```
"args": ["switch", "--profile prod", "--account", "foo", "--role", "bar"]
```

**Comment by ramya-rao-a** [comment]
@dolmen both work for me. All args get printed

@mitom Closing this issue as we havent heard back from you in a while
