### ISSUE TITLE
Can clicking "run tests" automatically save the file?

### ISSUE THREAD

**Issue by skybrian** [Microsoft/vscode-go#1225]
If I edit a test and click "run test", there is a dialog:

    File has unsaved changes. Save and try again.

It seems like it would be better to automatically save the file?

**Comment by skybrian** [comment]
In case it matters, I have file.autoSave on. Here are my preferences:

```
{
    "[plaintext]": {
        "editor.quickSuggestions": false,
        "editor.wordWrap": "bounded"
    },

    "editor.stablePeek": true,
    "files.autoSave": "onFocusChange",
    "go.coverageDecorator": "gutter",
    "go.coverageOptions": "showUncoveredCodeOnly",
    "go.inferGopath": true,
    "go.lintOnSave": "off",
    "go.toolsGopath": "/Users/skybrian/go/tools",
    "go.useCodeSnippetsOnFunctionSuggest": true
}
```

**Comment by ramya-rao-a** [comment]
Sure that is doable and is pretty simple.
PRs are welcome.

The change should be done here: https://github.com/Microsoft/vscode-go/blob/0.6.65/src/goTest.ts#L34

You can use `editor.document.save()` to save the document

**Comment by chaseadamsio** [comment]
would it make sense to have this disabled by default and have a flag to enable? something like `go.saveTestFileOnRun`?

**Comment by ramya-rao-a** [comment]
@chaseadamsio Why so? When you explicitly click on the `Run test` code lens or use one of the test commands from the command palet, you are making a conscious decision to run the test and so saving the file makes sense. Am I missing something?

**Comment by chaseadamsio** [comment]
If the expected behavior is always save the file when you run the tests I think it makes sense. Personally I like having flags for anything I might want to disable, so that was the only reason I suggested it. I'll pick this up and submit a PR.

**Comment by ramya-rao-a** [comment]
Since `go test` can only work on files on disk, I believe this is the right call

**Comment by ramya-rao-a** [comment]
In the latest update to the Go extension, the files get saved when test is triggered.
Thanks @chaseadamsio for the fix!
