### ISSUE TITLE
Multiple GOPATH directories not working

### ISSUE THREAD

**Issue by Erik-Blucher** [Microsoft/vscode-go#1226]
Due to how I have my git repositories set up my GOPATH contains two directories. One for my source code and another for development tools that I don't want to check into my repository.

Since VS Code 1.14 was released this is not working anymore. I get the following error in all files that have references to the development tools
```
can't load package: package github.com/onsi/ginkgo: cannot find package "github.com/onsi/ginkgo" in any of:
    /usr/local/go/src/github.com/onsi/ginkgo (from $GOROOT)
    /home/erik/git/ES/ES/src/github.com/onsi/ginkgo (from $GOPATH)
can't load package: package github.com/onsi/ginkgo/reporters: cannot find package "github.com/onsi/ginkgo/reporters" in any of:
    /usr/local/go/src/github.com/onsi/ginkgo/reporters (from $GOROOT)
    /home/erik/git/ES/ES/src/github.com/onsi/ginkgo/reporters (from $GOPATH)
can't load package: package github.com/onsi/gomega: cannot find package "github.com/onsi/gomega" in any of:
    /usr/local/go/src/github.com/onsi/gomega (from $GOROOT)
    /home/erik/git/ES/ES/src/github.com/onsi/gomega (from $GOPATH)
can't load package: package github.com/onsi/gomega/ghttp: cannot find package "github.com/onsi/gomega/ghttp" in any of:
    /usr/local/go/src/github.com/onsi/gomega/ghttp (from $GOROOT)
    /home/erik/git/ES/ES/src/github.com/onsi/gomega/ghttp (from $GOPATH)
```
My GOPATH is: `/home/erik/workgo:/home/erik/git/ES/ES`
Both gomega and ginkgo are available under `/home/erik/workgo/src/github.com/onsi`

**Comment by ramya-rao-a** [comment]
What do you get when you run `Go: Current GOPATH` command?

Where have you set your GOPATH to `/home/erik/workgo:/home/erik/git/ES/ES`?

**Comment by Erik-Blucher** [comment]
Running `Go: Current GOPATH` yields `Current GOPATH: /home/erik/git/ES/ES`

My GOPATH is set in `.profile` in my home directory.

**Comment by ramya-rao-a** [comment]
So you have set GOPATH to `/home/erik/workgo:/home/erik/git/ES/ES` in your `.profile` and to `/home/erik/git/ES/ES` in VS Code settings?

**Comment by Erik-Blucher** [comment]
No, my VS Code setting is the default `"go.gopath": null,` but this made me curious as to how it fails on reading my environment variables. So I switched to a different directory and started code as I usually do with `code .` and ran `Go: Current GOPATH` and got `Current GOPATH: /home/erik/git/ES/ES:/home/erik/workgo`

It seems like it only fails in reading my env variable in the `/home/erik/git/ES/ES` directory. Could it be that there are some workspace/repository setting that I'm missing?

**Comment by Erik-Blucher** [comment]
I found the problem!
A co-worker had checked in a `settings.json` file in the `.vscode` directory that had `"go.gopath": "${workspaceRoot}",` set.

I'll close this issue now as it was a mistake on my end.
Sorry for bothering you.

BR, Erik

**Comment by ramya-rao-a** [comment]
No problem @Erik-Blucher, glad you found what the issue was. Happy Coding!
