### ISSUE TITLE
Feature request: add fillstruct support

### ISSUE THREAD

**Issue by tylerb** [Microsoft/vscode-go#1227]
Recently added to vim-go, this seems pretty awesome:

https://github.com/davidrjenni/reftools/tree/master/cmd/fillstruct

I will probably take a stab at adding it as a command myself, but wanted to note it here as an issue first.

**Comment by ramya-rao-a** [comment]
cool!

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.77)
Thanks @buyology!

**Comment by tylerb** [comment]
Hooray! Thanks so much @buyology @ramya-rao-a
