### ISSUE TITLE
Field name "string" colored same as type name "string"

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1230]
As in:

```go
type foo struct {
    name, packageName, packagePath, string string
}
```

Screenshot:

<img width="347" alt="screen shot 2017-09-18 at 7 04 25 pm" src="https://user-images.githubusercontent.com/63830/30629141-1beaac32-9d8f-11e7-9073-76a04bc6f119.png">

Is there a way to color the token "string" based on the parsing context?

---

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.17
php-formatter|Sop|0.2.4
sort-lines|Tyr|1.3.0
githistory|don|0.2.3
javadebugger|don|0.1.3
python|don|0.7.0
phpunit|ema|2.1.1
git-project-manager|fel|1.4.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
code-runner|for|0.7.1
vscode-javac|geo|0.0.46
phpcs|ika|0.7.0
Go|luk|0.6.65
prettify-json|moh|0.0.3
mssql|ms-|1.1.0
cpptools|ms-|0.12.4
Ruby|reb|0.15.0
rewrap|stk|1.5.0
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

**Comment by ramya-rao-a** [comment]
Am curious, why would you want to name a struct field the same as a keyword?

**Comment by willfaught** [comment]
The fields matched exported method names in another type. In this case, `String() string`.

Another common one is “len”. Also “cap”.

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#136
