### ISSUE TITLE
No quick suggestion inside back-quoted strings

### ISSUE THREAD

**Issue by reusee** [microsoft/vscode-go#1231]
It works inside double-quoted strings, but not in strings like ``` `foobarbaz foo` ```

**Comment by ramya-rao-a** [comment]
Quick suggestions are not suppose to work inside double quoted strings either...
Can you give me an example?

**Comment by reusee** [comment]
I'm writing long SQL queries in backquoted strings, it would be really helpful to auto-complete table or column names.

Suggestions inside backquoted strings is working when vscode-go is disabled. Is the default behavior overwritten by any configuration of this extension?

**Comment by ramya-rao-a** [comment]
You are writing SQL queries in backquoted strings in Go files?
Are the table/column names Go variables? If not, then how would they appear in the completion lists?

Can you give me a sample code that I can try this on?

**Comment by reusee** [comment]
```go
func (a *API) AvgleVideos(
	arg struct {
		ash.Argument
		Keyword    *string
		Page       int
		Max        int
		Sort       *string
		IsFavorite *bool
	},
) (
	ret struct {
		ash.Return
		Videos json.RawMessage
		Total  int
	},
	err error,
) {

	if arg.Max == 0 {
		arg.Max = 30
	}

	err = db.Get(&ret, `
		SELECT
			COALESCE(json_agg(raw), '[]') AS videos,
			COALESCE(MAX(total), 0) AS total
		FROM (
			SELECT
				raw,
				COUNT(*) OVER () AS total
			FROM site_avgle_videos
			WHERE true

			-- keyword
			AND CASE WHEN $1::text IS NOT NULL THEN
				raw->>'title' ~* $1
			ELSE true END

			-- favorite
			AND CASE WHEN $5::bool IS NOT NULL THEN
				is_favorite = $5
			ELSE true END

			-- sort
			ORDER BY
			CASE $4
			WHEN 'id-desc' THEN (raw->>'vid')::int
			WHEN 'id-asc' THEN -(raw->>'vid')::int
			WHEN 'likes-desc' THEN (raw->>'likes')::int
			WHEN 'random' THEN random()
			ELSE (raw->>'vid')::int
			END DESC

			OFFSET $2
			LIMIT $3
		) t
		`,
		arg.Keyword,
		arg.Max*arg.Page,
		arg.Max,
		arg.Sort,
		arg.IsFavorite,
	)
	if err != nil {
		return
	}

	return
}

```

When vscode-go is disabled, suggestions pop up:

https://imgur.com/SWtPJCD

**Comment by reusee** [comment]
settings
```
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
```

**Comment by ramya-rao-a** [comment]
what you are seeing are textual suggestions. You can identify them from the icon in the suggestion list. The icon says "abc"

Textual suggestions are agnostic of the language. They are based on words already used in the document.

Textual suggestions appear when there are no other language based suggestions to show.

Language based suggestions should be disabled inside strings. In the Go extension, we have disabled it inside double quoted strings, but not inside `` which is actually a bug.

And so you end up getting the textual suggestions inside the double quoted strings, but not inside the ``.

I don't have a quick solution for this yet, but I'll keep it in mind.

**Comment by ramya-rao-a** [comment]
One workaround is that when you are working inside the `` on your SQL strings, set the language mode to plain text (Click on the "Go" status bar item on the bottom right corner of the window -> In the pop up choose "Plain Text")

This will remove all Go related features from the Go extension to the current file.
And when you are back to writing Go code, change the language mode back to Go.

I know this is not ideal, but it is the only work-around I can think of as of now.

**Comment by ramya-rao-a** [comment]
Now that there is active development on an official language server for Go via [gopls](https://github.com/golang/go/wiki/gopls) which will provide the auto-completion feature as well, there is no further planned work in the auto-completion feature that is coming directly out of the extension.

This issue is being closed in favor of having the auto-completion feature from the language server which will not have the same problem.

For more on language server integration with this extension, please see [Go language server](https://github.com/microsoft/vscode-go#go-language-server)

To go a feature request for gopls, use the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)
