### ISSUE TITLE
<-chan field name is colored differently than other field names

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1233]
Try with:

```go
var (
    X chan bool
    Y <-chan bool // Y is a different color than X and Z
    Z chan<- bool
)
```

Screenshot:

<img width="258" alt="screen shot 2017-09-20 at 10 55 39 am" src="https://user-images.githubusercontent.com/63830/30660798-ebd72260-9df6-11e7-8df7-d30c924e01a8.png">

**Comment by ramya-rao-a** [comment]
We use the grammar for Go from http://github.com/atom/language-go

The scope for `X` in the above example is `variable.other.declaration.go` where as for `Y` the scope turns out to be just `source.go`. Thus the change in color.

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#134
