### ISSUE TITLE
auto-indent results in wrong auto-completion

### ISSUE THREAD

**Issue by skybrian** [Microsoft/vscode-go#1234]
To reproduce, you need to type two switch statements:

```
func foo(x string) {
    switch x {
    default: 
    }
}

func bar(x string) {
    switch x {
    default:
    }
}
```

While typing "default" in the second switch statement, wait for the autocomplete to come up, showing a dropdown with "default" as one of the choices. (But don't trigger it.) Then, type the colon. (It will auto-indent, but the autocomplete pulldown is still up.) Then, type return.

The autocomplete will trigger, messing up the results:

```
switch x {
ddefault
}
```

It seems like this would be fixed if the autocomplete pulldown disappeared after typing the colon? At that point it's no longer useful.

**Comment by ramya-rao-a** [comment]
If you disable auto-indenting (by setting `editor.autoIndent` to `false`), then typing `:` makes the suggestion list disappear as it should.

Somehow the adding of the indent is messing up the sequence of events.

Nice catch!

By the way, we don't need 2 switch statements for this. I am able to repro even with a single one.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#34897
