### ISSUE TITLE
buildOnSave passes go.buildFlags to go test

### ISSUE THREAD

**Issue by gregmarr** [Microsoft/vscode-go#1235]
I have go.buildFlags set to `[ "-gcflags='-N -l'" ]`.  This is being passed to `go test` when I save, but `go test` doesn't know how to deal with these flags, so it throws a usage message.  I've tried setting `go.testFlags` to `null`, and `[]`, but no change.

Is there any way to make buildOnSave only use testFlags when running tests, and not buildFlags, which should just be for building?

**Comment by ramya-rao-a** [comment]
I resorted using `go test -c -i` to get build errors as I noticed that `go build` was ignoring the test files in the package

You bring up a good point where this approach fails.

**Comment by ramya-rao-a** [comment]
Made a change such that

- Build errors in test files will show up if any test file in the package is being edited
- Build errors in non-test files will show up if a non test file in the package/workspace (based on whether go.buildOnSave was set to package or workspace) is being edited

Can you help testing this out? All you have to do is
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- Reload VS Code window

**Comment by ramya-rao-a** [comment]
BuildFlags are used by `go test` by default.
If you don't want to do so set `go.testFlags` to `[]` or a non null value
