### ISSUE TITLE
full package docs in a separate view

### ISSUE THREAD

**Issue by apiarian** [Microsoft/vscode-go#1237]
It would be great to have access to the output of `godoc` for a package (and possibly a specific identifier) within the editor without having to open up a browser to godoc.org or similar.

Should be possible using https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocumentContentProvider . Some care will need to be taken to handle vendored code correctly. `godoc` seems to default to looking in the `$GOPATH` or `$GOROOT` so we'll probably have to explicitly check `$PROJECTROOT/vendor` first.

I'd like to take this issue on myself, but it'll be my first foray into vscode extensions out of my backend-development cave, so if somebody is keen to see this quicker, please let me know. I'd certainly be willing to hand the branch over or collaborate on the work.

**Comment by apiarian** [comment]
Looks like this is probably related to https://github.com/Microsoft/vscode-go/issues/789

**Comment by apiarian** [comment]
created https://github.com/apiarian/vscode-go-test-docs-main to help with documentation experiments.

**Comment by ramya-rao-a** [comment]
@apiarian Let's use #789 to track this.
