### ISSUE TITLE
Live error reporting says can't find import: xxx/vendor/xxx 

### ISSUE THREAD

**Issue by DarthPestilane** [Microsoft/vscode-go#1239]
![image](https://user-images.githubusercontent.com/15375753/30746920-0afc13a6-9fde-11e7-8ce4-a32716f366ef.png)

It keeps telling me that cannot find package, but the package I import is just under vendor directory.

**Comment by ramya-rao-a** [comment]
What's your GOPATH?
Is your `BNB` folder under `GOPATH/src`?

**Comment by DarthPestilane** [comment]
@ramya-rao-a Yes `BNB` is under `GOPATH/src` but I can't run `go build` since there is not a `main.go` file.

**Comment by ramya-rao-a** [comment]
you don't need a main.go file to run `go build`
Just run `go build .` in the `BNB` directory

**Comment by DarthPestilane** [comment]
@ramya-rao-a `go build .` comes out with no error
![image](https://user-images.githubusercontent.com/15375753/30839404-3e8fc226-a2a4-11e7-8826-3e036f3d33b8.png)

**Comment by ramya-rao-a** [comment]
The error is showing up in the test file.
Do you see the error in non test files as well?

Also, open the output pane, choose the "Go" channel from the dropdown. You can see the output of build/lint/vet there. Can you share what you see there?

**Comment by DarthPestilane** [comment]
Error is showing up even if in a non-test file:
![image](https://user-images.githubusercontent.com/15375753/30891939-716116c2-a368-11e7-8d3f-9b0be613419c.png)
![image](https://user-images.githubusercontent.com/15375753/30891994-bca1b9d4-a368-11e7-94e8-32746bfa556c.png)

And output panel shows nothing when I chose the "Go" channel:
![image](https://user-images.githubusercontent.com/15375753/30891964-901c064e-a368-11e7-815c-f72abd2f985a.png)
maybe it's because I turn `go.vetOnSave` to `off`?

And I also tried turn  `go.vetOnSave` to `package`, and output shows only `Finished running tool: /usr/local/bin/go tool vet .`

Here's my golang config:
```
    "go.buildOnSave": "off",
    "go.lintOnSave": "off",
    "go.vetOnSave": "off",
    "go.formatOnSave": false,
    "go.formatTool": "gofmt",
    "go.useDiffForFormatting": false,
    "go.coverOnTestPackage": false,
    "go.gocodeAutoBuild": false,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.autocompleteUnimportedPackages": true,
    "go.gotoSymbol.includeImports": true,
    "go.liveErrors": {
        "enabled": true,
        "delay": 500
    },
```

**Comment by ramya-rao-a** [comment]
Ah! You have turned build,vet,lint on save features off. That's why there is nothing showing in the output pane.

The errors you are seeing is coming from the live errors which is coming from the tool `gotype-live`.
Can you run `gotype-live` from the terminal for your package and see if you are getting the same error?

cc @tylerb who integrated `gotype-live` in the Go extension

**Comment by DarthPestilane** [comment]
@ramya-rao-a It's all `gotype-live`
I ran `gotype-live -a ./`, it showed the exact errors
Thank you!

**Comment by ramya-rao-a** [comment]
That's good to know @DarthPestilane 

@tylerb Any idea why `gotype-live` was not able to find the vendor projects?

**Comment by ramya-rao-a** [comment]
@DarthPestilane Until we know why `gotype-live` behaves the way it does, as a workaround I'd suggest to turn off the live errors and enable the build on save feature instead

**Comment by DarthPestilane** [comment]
@ramya-rao-a Sounds reasonable. Thank you ! Hope to figure out of this.

**Comment by tylerb** [comment]
@ramya-rao-a @DarthPestilane I'm not sure why it would be complaining here, other than some kind of odd directory structure that it isn't expecting. `gotype-live` is really just a fork of `gotype` that adds the ability to work on a file that is currently being edited.

@DarthPestilane can you install+run the normal `gotype` and see if the error still happens?

**Comment by DarthPestilane** [comment]
@tylerb It shows `could not import xxx`, same errors as above, after I run `gotype-live -a ./`. And I don't think it's the problem of directory structure, since I moved the whole project folder to `$GOPATH/src`, errors also showed up

**Comment by tylerb** [comment]
Honestly not sure what this could be. Have you tried it with the original gotype tool? Mine may be out of date or something like that.

**Comment by ramya-rao-a** [comment]
Closing this as this is an upstream issue with `gotype` and we there is nothing much we can do from the extension's perspective.
