### ISSUE TITLE
Improve comment for turning string arguments off 

### ISSUE THREAD

**Issue by btracey** [Microsoft/vscode-go#1240]
The current documentation (for instance, on `go.lintOnSave`) says 
```
// On save, runs the configured Lint tool on current workspace, current package or nothing at all.
```

With the default value of "package", this would lead me to believe that the possible settings are "package", "workspace" and "nothing". I would suggest to rephrase the comment as

```
// On save, runs the configured Lint tool on current workspace, current package or turn it off.
```
to make it clear that the option is "off".

**Comment by ramya-rao-a** [comment]
@btracey How about this?
https://github.com/Microsoft/vscode-go/commit/632083c48e15ecda7e1b9ab593a64b50e528af27#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
