### ISSUE TITLE
Add option for autocomplete to not add the types on function/method calls

### ISSUE THREAD

**Issue by btracey** [Microsoft/vscode-go#1241]
Currently, when autocompleting a function or method the entire method signature, including types, is used. For example, in `strings.Split`, it currently autocompletes as `strings.Split(s string, sep string)` rather than `strings.Split(s, sep)`. In a lot of my code, I have variable names that are the same as argument names (i.e. my string is named `s`), and it would be convenient to only have to change the ones that are different.

**Comment by alexkohler** [comment]
I'd like to take a stab at this.

**Comment by ramya-rao-a** [comment]
This feature is out in the latest update to the Go extension via the new setting `go.useCodeSnippetsOnFunctionSuggestWithoutType`

Thanks @alexkohler!
