### ISSUE TITLE
Can Not Step Into External Package When Remote Debug

### ISSUE THREAD

**Issue by lshunter** [Microsoft/vscode-go#1243]
local machine: windows
remote machine: linux
When I remote debug a go file, vscode show an error:`Unable to open 'redisWrite.go': File not found (`c:\Go\src\telcomapp.cn\redis\redisWrite.g`o).` The file(`redisWrite.go`) is in my local machine GOPATH(`C:\Users\lisi-\go`, as `C:\Users\lisi-\go\src\telcomapp.cn\redis\redisWrite.go`), it seems llike vscode made a mistake and tried  to find the file `redisWrite.go` in the local GOROOT(`c:\Go`).
Here are the top lines in vscode-go-debug.txt:
`18:50:09, 2017-9-24
InitializeRequest
InitializeResponse
Using GOPATH: C:\Users\lisi-\go\
InitializeEvent
SetBreakPointsRequest
All cleared
Creating on: C:\Go\src\telcomapp.cn\redis\redisWrite.go (C:/Go/src/telcomapp.cn/redis/redisWrite.go) :123
SetBreakPointsRequest
All cleared
Creating on: D:\git\anascripts\app\apkana.go (/data/code/golangApp/app/apkana.go) :16
Error on CreateBreakpoint: unknown file: C:/Go/src/telcomapp.cn/redis/redisWrite.go`

**Comment by ramya-rao-a** [comment]
Can you share your debug configuration from the launch.json file?

**Comment by lshunter** [comment]
@ramya-rao-a Thanks for answering! Here is my launch.json file, I use the `Remote` :
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Remote",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "remotePath": "/data/code/golangApp/app",
            "port": 12345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "trace": "verbose",
            "env": {},
            "args": [],
            "showLog": true
        },
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${fileDirname}",
            "env":{},
            "args": [],
            "showLog": true
        }
    ]
}`
And my setting.json file:
`{
    "files.autoSave": "off",
    "python.formatting.formatOnSave": true,
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "deploy": {
        "packages": [
            {
                "name": "apps",
                "description": "App",
                "files": [
                    "**/*.go",
                    "*.go"
                ],
                "deployOnSave": ["APP"]
            }
        ],
        "targets": [
            {
                "type": "sftp",
                "name": "APP",
                "description": "to app path",

                "mappings": [
                    {
                        "source": "",
                        "target": "app"
                    }
                ],

                "dir": "/data/code/golangApp",
                "host": "localhost", "port": 16022,
                "user": "****", "password": "****",
                "checkBeforeDeploy": true
            }

        ]
    }
}`

**Comment by ramya-rao-a** [comment]
And what is the value for ${workspaceRoot} ?

**Comment by lshunter** [comment]
Yes, you are right. `redisWrite.go` is in a external package, its path is `$GOPATH(C:\Users\lisi-\go\src\telcomapp.cn\redis)`. And `apkana.go` is in the package I have opened in VS Code, the ${workspaceRoot} is where `apkana.go`  in, as `D:\git\anascripts\app`.
When I remove the breakpoint in  `redisWrite.go`  the remote debug works right, but when I am trying to step into `redisWrite.go`, the error `Unable to open 'redisWrite.go': File not found c:\Go\src\telcomapp.cn\redis\redisWrite.go).` comes up.

**Comment by ramya-rao-a** [comment]
In the remote machine what is the location of the `redisWrite.go` file?

**Comment by lshunter** [comment]
`apkana.go` not in GOPATH, neither the local or remote machine. After I put `apkana.go` into GOPATH, step into works fine, problem solved. I am new to Go, so this problem due to the wrong organization of Go project. I will post the project organization of my project and changes has been made to correct it.
But I still wonder why the local debug can step into the external package, but the remote one can't.
### WRONG ORGANIZATION !!!
    remote machine:
        1. env:
            $GOPATH = /data/app/gopath
        2. packages
            2.1 external package
                %GOPATH/
                    bin/
                    pkg/
                    src/
                        telcomapp.cn/
                            redis/
                                redisWrite.go	# package redis
            2.2 package main
                /data/
                    code/
                        golangApp/
                            app/
                                apkana.go
        3. debug
            cd /data/code/golangApp/app
            dlv debug --headless --listen :2345
---
	local machine:
    1. env:
		$GOPATH = C:\Users\lisi-\go
	2. packages
        2.1 external package
            %GOPATH/
                bin/
                pkg/
                src/
                    telcomapp.cn/
                        redis/
                            -redisWrite.go	# package redis
        2.2 package main
            (${workspaceRoot} = D:\git\anascripts\app)
            ${workspaceRoot}/
                .vscode/
                    launch.json
                    settings.json
                apkana.go	# package main
    3. debug
        run Rmote in VS Code 

### AFTER CHANGED
    remote machine:
        1. env:
            $GOPATH = /data/app/gopath
        2. packages
            2.1 external package
                %GOPATH/
                    bin/
                    pkg/
                    src/
                        telcomapp.cn/
                            redis/
                                redisWrite.go	# package redis
            2.2 package main
                %GOPATH/
                    bin/
                    pkg/
                    src/
                        telcomapp.cn/
                            apkana/
                                apkana.go	# package main
        3. debug
            cd $GOPATH/src/telcomapp.cn/apkana
            dlv debug --headless --listen :2345
---
	local machine:
    1. env:
		$GOPATH = C:\Users\lisi-\go
	2. packages
        2.1 external package
            %GOPATH/
                bin/
                pkg/
                src/
                    telcomapp.cn/
                        redis/
                            -redisWrite.go	# package redis
        2.2 package main
            (${workspaceRoot} = C:\Users\lisi-\go)
            %GOPATH/
                bin/
                pkg/
                src/
                    telcomapp.cn/
                        apkana/
                            apkana.go	# package main
    3. debug
        run Rmote in VS Code

**Comment by ramya-rao-a** [comment]
> But I still wonder why the local debug can step into the external package, but the remote one can't

when debugging remotely, we need to map the remote filepath to local paths
We use GOPATH to make the mapping or fallback to GOROOT which failed

When debugging locally no mapping is needed, so things worked.

Anyway, am glad things got resolved for you.
Happy Coding!
