### ISSUE TITLE
update tools failed

### ISSUE THREAD

**Issue by windzhu0514** [Microsoft/vscode-go#1245]
i upgrade go to 1.9,so vscode remind me to update tools ,ctrl+shif+P , then click Go:Install/Update Tools, but some failed
```
Installing github.com/nsf/gocode SUCCEEDED
Installing github.com/tpng/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/josharian/impl FAILED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing golang.org/x/tools/cmd/godoc FAILED
Installing sourcegraph.com/sqs/goreturns FAILED
Installing github.com/golang/lint/golint FAILED
Installing github.com/cweill/gotests/... FAILED
Installing github.com/derekparker/delve/cmd/dlv SUCCEEDED

9 tools failed to install.

go-outline:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/ramya-rao-a/go-outline
github.com/ramya-rao-a/go-outline (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
golang.org/x/tools (download)
# cd D:\goprojects\MyGoLibrary\src\golang.org\x\tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Timed out
package golang.org/x/tools/go/buildutil: exit status 1
github.com/ramya-rao-a/go-outline (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
golang.org/x/tools (download)
# cd D:\goprojects\MyGoLibrary\src\golang.org\x\tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Timed out
package golang.org/x/tools/go/buildutil: exit status 1
```

github.com/ramya-rao-a/go-outline package use the "golang.org/x/tools/go/buildutil" ,why not use the package "github.com/golang//tools/go/buildutil"  

so i how to update tools???

**Comment by lshunter** [comment]
It seems like a network problem, make sure you can access[https://golang.org/x/tools/go/buildutil]( https://golang.org/x/tools/go/buildutil) and [https://go.googlesource.com/tools/](https://go.googlesource.com/tools/).
why use golang.org but not github, that's because of  `golang.org/x/tools/go/buildutil` was imported in `github.com/ramya-rao-a/go-outline/main.go` but not `github.com/golang//tools/go/buildutil` . `github.com/golang//tools/go/buildutil`  is a mirror of  `golang.org/x/tools/go/buildutil`.
if you cannot access the site above, try to replace `golang.org/x/tools/go/buildutil` in  file `$GOPATH/src/github.com/ramya-rao-a/go-outline/main.go` into `github.com/golang/tools/go/buildutil`, then run `go get -u -v github.com/ramya-rao-a/go-outline`. (NOT TESTED！！！CAREFUL)

**Comment by windzhu0514** [comment]
So why not modify github.com/ramya-rao-a/go-outline/main.go , import  github.com/golang//tools/go/buildutil not golang.org/x/tools/go/buildutil, I think this is Convenience for people can’t access google or golang.org

发送自 Windows 10 版邮件应用

发件人: lshunter
发送时间: 2017年9月26日 22:57
收件人: Microsoft/vscode-go
抄送: windzhu0514; Author
主题: Re: [Microsoft/vscode-go] update tools failed (#1245)

It seems like a network problem, make sure you can accesshttps://golang.org/x/tools/go/buildutil and https://go.googlesource.com/tools/.
why use golang.org but not github, that's because of golang.org/x/tools/go/buildutil was imported in github.com/ramya-rao-a/go-outline/main.go but not github.com/golang//tools/go/buildutil . github.com/golang//tools/go/buildutil is a mirror of golang.org/x/tools/go/buildutil.
if you cannot access the site above, try to replace golang.org/x/tools/go/buildutil in file $GOPATH/src/github.com/ramya-rao-a/go-outline/main.go into github.com/golang/tools/go/buildutil, then run go get -u -v github.com/ramya-rao-a/go-outline. (NOT TESTED！！！CAREFUL)

**Comment by ramya-rao-a** [comment]
If I make the change as @windzhu0514 suggested, then I get an error saying that buildutil expects "golang.org/x/tools/go/buildutil" 

![image](https://user-images.githubusercontent.com/16890566/30890827-25889b8c-a2e4-11e7-9d6f-eaf113aa1254.png)

So I dont see how making that change will help

Note that its not just go-outline, a bunch of other tools are also failing
I dont own the other tools, so changing the import is not the solution here.

This is indeed a network problem
