### ISSUE TITLE
Run `..onSave` functions even when there is nothing to save?

### ISSUE THREAD

**Issue by ByteFlinger** [Microsoft/vscode-go#1246]
Is it possible to trigger things like buildOnSave or lintOnSave when pressing ctrl+s (or any other saving shortcut) even though the underlying file has not changed at all?

I often find myself changing a file and then opening up another file which has not changed but is affected by the first file so I want to trigger linting. I will then introduce a meaningless change like line break somewhere and immediately save just to trigger linting.

I know I am not alone on this but could not find anything on the matter. Is this just something not implemented or maybe a limitation on VS Code itself?

**Comment by ramya-rao-a** [comment]
You can use tasks for triggering build/lint on demand

Run `Tasks: Configure Task Runner` to create a tasks,json file in your workspace (Choose "others" in the dropdown) and then edit it to create tasks for build/lint etc

For example see: 
https://github.com/Microsoft/vscode-go/issues/1015#issuecomment-331250277

**Comment by ByteFlinger** [comment]
Right. It would be a lot simpler with a simple config to allow all the onSave to trigger when saving even if there is nothing to save as I now have to figure out what are all the commands and tasks VS Code is doing plus ant disabling of linting and/or building on save requires me to remember to do the same on the tasks but it looks like this could be a solution for now, thank you.
