### ISSUE TITLE
setting -ldflags="-X ..." in go.testFlags fails

### ISSUE THREAD

**Issue by AlexRouSg** [Microsoft/vscode-go#1247]
Whenever I try to use the linker flag -X, it fails to build with the error
```
# testmain
flag provided but not defined: -X ...
```

However copy pasting the exact command into the terminal works as intended.
`go test -ldflags='-X ...' -timeout 30s -run ^TestDriver$`

**Comment by ramya-rao-a** [comment]
what is the value that you have set for `go.testFlags` ?
Are you seeing this error when building or running tests?

**Comment by AlexRouSg** [comment]
Only

```
"go.testFlags": [
        "-ldflags='-X mypackage.myvalue=./'"        
]
```

The error happens when I use any run test button (function/file/package) and is a build error.

**Comment by ramya-rao-a** [comment]
Try
"go.testFlags": [
        "-ldflags", "-X mypackage.myvalue=./"    
]

**Comment by AlexRouSg** [comment]
Well that works ... *face palm*

**Comment by ramya-rao-a** [comment]
😄 Happy Coding!
