### ISSUE TITLE
Generate a lot of processes (godef, vet, conhost, golint ....)

### ISSUE THREAD

**Issue by www2t** [Microsoft/vscode-go#1249]
vscode 1.15.1 x64
golang 1.8.3
Go for Visual Studio Code 0.6.64
When writing code will produce a lot of the process (300-400), vscode becomes very slow, write the code will disappear for a while

**Comment by ramya-rao-a** [comment]
Have you set `go.lintOnSave` and `go.vetOnSave`  to `workspace`? If yes can you  try setting it to `package`

**Comment by www2t** [comment]
@ramya-rao-a  
Using the default setting，all setting to package

**Comment by ramya-rao-a** [comment]
Are you working on a large project? 
Do you see this happening even when working on smaller projects?
Do you have multiple windows open?
Do you have auto save enabled?

**Comment by roadrunner** [comment]
a small project here, but this is happening when `vet-on-save` enabled. it feels so laggy even if it's set package or workspace level.

**Comment by ramya-rao-a** [comment]
@roadrunner Do you have auto save enabled?

**Comment by roadrunner** [comment]
No, it's not enabled @ramya-rao-a

**Comment by ramya-rao-a** [comment]
We spawn new process each time we want to vet/lint/build code.
#1265 tracks closing of existing processes before starting new ones.
That should help here
