### ISSUE TITLE
Autocompletion return vendored dependency

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode-go#1251]
I got two `spew` the other one is vendored package from testify.

<img width="517" alt="screen shot 2017-09-30 at 5 38 34 am" src="https://user-images.githubusercontent.com/166053/31038578-df34e4d6-a5a1-11e7-96bd-ad834af23406.png">

**Comment by ramya-rao-a** [comment]
The fix for this is out in the latest update to the Go extension
