### ISSUE TITLE
Support auto discovering GOPATH by source file path.

### ISSUE THREAD

**Issue by hackwaly** [Microsoft/vscode-go#126]
It's a feature of GoSublime
https://github.com/DisposaBoy/GoSublime/blob/master/USAGE.md#per-project-settings--project-based-gopath
It's useful if you want to put your projects outside of system $GOPATH.

**Comment by lukehoban** [comment]
This should be possible already by using a `.vscode/settings.json` file in your workspace (the root folder that you will open in Code) and setting ` "go.gopath": "/Users/lukeh/go"`.

That seems to handle the same cases as the GoSublime feature you linked.

See https://github.com/Microsoft/vscode-go#options.
