### ISSUE TITLE
Package name autocomplete appending _test in test files is not ideal

### ISSUE THREAD

**Issue by m90** [Microsoft/vscode-go#1260]
Reading the changelog of 0.6.66 I know this is expected behavior due to https://github.com/Microsoft/vscode-go/pull/1220 but I think it is not necessarily the best idea:

When I now use autocomplete to spell out the package name in a test file it will forcefully append `_test` to the package name.

This is not really the Go default as it changes quite a few things: when in a `_test` package the invisible members of the package (i.e. everything that start with a lowercase letter) are not accessible to the test. This is good for writing integration and acceptance tests, but is rarely useful when writing unit tests. Until now I have rarely seen a larger Go project that defaults to `_test` packages.

I know this is an opinionated request, but I would much love to see this change being undone and having the autocomplete default to the standard package name with `name_test` being the second option (or the other way round). Right now I will have to delete the trailing `_test` for 99% of the cases or skip using the autocompletion.

**Comment by uudashr** [comment]
Can you mention the projects?

**Comment by m90** [comment]
I'll just name a few of the "big" ones from the top of my head, apparently none of them use `_test` packages as default behavior:

- https://github.com/camlistore/camlistore/tree/master/pkg
- https://github.com/gin-gonic/gin/tree/master/render
- https://github.com/patrickmn/go-cache
- https://github.com/gohugoio/hugo/tree/master/helpers
- https://github.com/ha/doozerd/tree/master/server
- https://github.com/go-chi/chi

The only one that seems to use `_test` as a default is pongo:

- https://github.com/flosch/pongo2

Again, `_test` packages surely are a nice tool and have their place (which is why I would like to see them as an addition to the autocompletions), but I think it's just an odd default.

**Comment by ramya-rao-a** [comment]
Thanks for bringing this up @m90, I appreciate it.

@uudashr has put in a fix to show both "yourpkg" and "yourpkg_test" in the completion list.

I'll release an update in a few days. Until then to make use of the fix you can
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` and reload VS Code

**Comment by m90** [comment]
This is great! Thanks to the two of you for dealing with this so quickly. I think the update is a really nice addition to the Extension. Thanks for that @uudashr !
