### ISSUE TITLE
go-to-definition doesn't work in go 1.9 with type aliasing.

### ISSUE THREAD

**Issue by ssoroka** [Microsoft/vscode-go#1261]
Steps to reproduce:
1. define a package that uses type aliasing. eg: 
```go
package typealiasing
type Broken = string
```
2. import "typealiasing" and reference `Broken`. eg:
```go
package main

import "fmt"
import "typealias"

func main() {
	fmt.Println(typealias.Broken("hi"))
}
```

3. Try to jump to definition. Error tells you `no definition found for "Broken"`. Note that this doesn't just affect the aliased type, it affects all definitions in the same package as the aliased type.

**Comment by ramya-rao-a** [comment]
We use `godef` by default for the `Go to Definition` feature which seems to have issues when dealing with type aliasing.

`gogetdoc` on the other hand works just fine with type aliases

You can change the setting `go.docsTool` to `gogetdoc` until we get an upstream fix for `godef`

**Comment by ssoroka** [comment]
I'm not sure if I'm doing something wrong, but this doesn't resolve it for me.

**Comment by ramya-rao-a** [comment]
@ssoroka Are you using the language server feature?

**Comment by ssoroka** [comment]
No. I have an odd project layout and I think that might be complicating the problem. Is there any way I can see the debug output that vscode is getting from the `gogetdoc` command?

**Comment by ramya-rao-a** [comment]
Try running the `gogetdoc` tool from the terminal directly
It takes file name and offset

You can use this extension https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset to get the offset under the cursor
