### ISSUE TITLE
import formatting and linting different MAC vs Windows

### ISSUE THREAD

**Issue by lmtyler** [Microsoft/vscode-go#1264]
When coding GoLang on MAC import statements are added on separate lines and linter gives syntax error if using  a single import with an array of strings, which works on Windows.

[Go import formatting](https://golang.org/doc/code.html)

**Comment by ramya-rao-a** [comment]
@lmtyler Can you share some screenshots for Mac vs Windows?

Import statements get added by the Go extension in the below scenarios. Do you see this issue in all the below cases or only a few?
- Those that get added when the file is formatted either manually or on save
- Those that get added when the `Go: Add Import` command is used
- Those that get added when auto-completing the unimported packages or symbols from unimported packages

**Comment by lmtyler** [comment]
Seems to be an issue will goreturns and not vccode-go.  Changed default to goimports and now formatting correctly.

**Comment by ramya-rao-a** [comment]
good to know, Happy Coding!
