### ISSUE TITLE
Syntax highlighting is wrong

### ISSUE THREAD

**Issue by jhaynie** [Microsoft/vscode-go#1267]
This may not be a golang specific issue but something in the core package.  But it doesn't seem to happen in other non-go files.

Some files, often, when I open them (or select them if already opened), will highlight certain blocks of code that don't seem to have any discernable reason to be highlighted. For example:

![screen shot 2017-10-06 at 9 24 04 am](https://user-images.githubusercontent.com/6027/31288084-602f32d2-aa78-11e7-8bd2-6ee6278a40f6.png)

If I simply select somewhere in the file and make a change (for example, click space and then delete to remove it), the bad highlights go away and the file is rendered correctly:

![screen shot 2017-10-06 at 9 27 08 am](https://user-images.githubusercontent.com/6027/31288134-877daac6-aa78-11e7-944b-f6e0c6a3d4fa.png)

This is pretty difficult to work with. I've tried various different themes and all exhibit this behavior so it doesn't seem to be related to that.

I can't figure this out and it's driving me nuts!! :)

VSCode: Version 1.17.0 (1.17.0) be377c0faf7574a59f84940f593a6849f12e4de7
Golang Plugin: Version 0.6.66

Any help would be much appreciated.

**Comment by ramya-rao-a** [comment]
@jhaynie Sorry for the delay in responding to this issue.

Thats the code coverage showing up.

You might have `go.coverOnSave` enabled.
Disable that, and those highlights should go away.

Let me know if that doesn't work

**Comment by jhaynie** [comment]
@ramya-rao-a thanks so much.  i never would have figured that out !!!

**Comment by ramya-rao-a** [comment]
How did you end up enabling the code coverage any way :) ?

**Comment by jhaynie** [comment]
well, i guess it was turned on but didn't realize the highlighting would only show when i saved it. that wasn't intuitive until you explained it. it might have been better to indicate something in a hover etc.

**Comment by ramya-rao-a** [comment]
The default value for `go.coverOnSave` setting is `false`.

The below is the description of the setting that shows up on hover.
![image](https://user-images.githubusercontent.com/16890566/31519635-d9de6e02-af57-11e7-9461-2a7d8bba72d0.png)

Regardless, am glad that is resolved now. Happy Coding!

**Comment by esemplastic** [comment]
Dear @ramya-rao-a could you please take a quick look and confirm the https://github.com/Microsoft/vscode-go/issues/1277 ?
