### ISSUE TITLE
Does format on save work?

### ISSUE THREAD

**Issue by polds** [Microsoft/vscode-go#127]
I have been able to get formatting working by hitting `Alt + Shift + F` which works, wondering if format on save works or if I just have my setup incorrect.

**Comment by lukehoban** [comment]
Format-on-save is currently off by default while we get more usage experience.  You can turn it on by setting `"go.formatOnSave:: true` in your settings.  

See https://github.com/Microsoft/vscode-go#options and https://github.com/Microsoft/vscode-go/issues/14#issuecomment-160328819.

**Comment by kylebrandt** [comment]
@lukehoban Not sure where to put this, but maybe if https://github.com/Microsoft/vscode/issues/353 gets done that will interact well with format on save (instead of autosave). That way it won't format while typing in a window - this is how I worked in sublime.
