### ISSUE TITLE
Hints for defined types

### ISSUE THREAD

**Issue by alexmironof** [Microsoft/vscode-go#1273]
Is there a way to show hint for user defined types, like expected arguments for `WalkFunc` function in screenshot below?

![1](https://user-images.githubusercontent.com/6573628/31453069-6f925660-aeb9-11e7-999c-03842dbec6d2.PNG)

![1](https://user-images.githubusercontent.com/6573628/31453236-1f8c5fd4-aeba-11e7-8dbe-3091a10bd279.PNG)

**Comment by ramya-rao-a** [comment]
Argument hints are currently provided when an already defined function is called.

In this case, you are defining a function of a particular type.

If we were to use a language server then this may be possible, but in the current way the Go extension is designed (where we shell out process to run Go tools), I don't believe this is possible. 

If you have any ideas how to go about this I would be interested to hear your thoughts

**Comment by ramya-rao-a** [comment]
Closing this issue as there is nothing we can do in the Go extension for this at the moment
