### ISSUE TITLE
Go intellisense stop working

### ISSUE THREAD

**Issue by charlires** [Microsoft/vscode-go#1275]
Since a few days, go extension just stop working.

I dont get auto completion, and I can install/Update tools.

I get `command 'go.tools.install' not found`, I disable Language Server but no luck.

Im setting gopath per project but also tried directly in my global gopath but nothing. 

There is no output at all, how can I start digging? this is the only extension that I can tell its not working.

**Comment by charlires** [comment]
Looks like uninstalling and reinstalling the extension did the trick

**Comment by ramya-rao-a** [comment]
Hey @charlires 

The `command 'go.tools.install' not found` tells us that the Go extension failed to get activated.

Did you recently install the Go extension directly from a vsix file?

**Comment by charlires** [comment]
@ramya-rao-a No, Installed it from vs code
