### ISSUE TITLE
quick suggestion show very slow

### ISSUE THREAD

**Issue by drinktee** [Microsoft/vscode-go#1276]
When I type some words, the quick suggestion show very slow about 15 seconds.
When I open a small project , it shows fast.
But when I open a bit project such as kubernetes , it shows suggestions after 10-20 seconds.
VSCODE  1.17.1

**Comment by ramya-rao-a** [comment]
Can you try the below?
- Close VS Code
- Run `gocode close`
- Start VS Code and start typing in the bigger project.

If this still doesn't help, try disabling the setting `go.gocodeAutoBuild`

**Comment by drinktee** [comment]
I disabled go.gocodeAutoBuild and result is same. I have close any other extensions. This is my config. Is anything wrong?
```
{
     "editor.fontFamily":"Consolas, Monaco, 'Courier New', monospace",
    "editor.rulers": [95],
    "editor.fontSize": 20,
    "editor.wordWrapColumn": 70,  
    "editor.wordWrap": "bounded",
    "go.gopath": "/Users/chenguoyan01/work/gocode",
       "terminal.integrated.shell.osx": "/bin/zsh",
    "editor.quickSuggestionsDelay": 1,    
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "editor.renderIndentGuides": true,
     "editor.mouseWheelZoom": true,
    "go.vetOnSave": "off",
    "go.autocompleteUnimportedPackages": false,
    "files.autoSave": "off",
    "files.autoSaveDelay": 600,
    "editor.tabCompletion": false,
  
    "window.zoomLevel": 0,
    "terminal.integrated.fontSize": 16,
    "workbench.activityBar.visible": true,
 
    "workbench.iconTheme": "vs-minimal",
    "editor.minimap.enabled": false,
    "workbench.colorCustomizations": {
        "editorCursor.foreground": "#00FFFF",
        "activityBar.background": "#110000",
        "editor.selectionBackground": "#0022FF"
    },
    "workbench.colorTheme": "Solarized Dark cgy",
    "go.testFlags": [
        "-v"
    ],
    "window.openFilesInNewWindow": "on",
    "editor.acceptSuggestionOnEnter": "smart",
    "go.formatTool": "gofmt",
    "go.gocodeAutoBuild": false,
    "go.toolsGopath": "/Users/chenguoyan01/work/gocode/bin"
}
```

**Comment by ramya-rao-a** [comment]
Did you run `gocode close`?

Your settings look fine. One comment though..
You have set `go.toolsGopath` to the your GOPATH/bin. 
That doesnt make sense. If you want to use the Go tools from your GOPATH, then there is no need to set the `go.toolsGopath` setting

**Comment by drinktee** [comment]
It seems good when I have upgraded to macOS 10.13 ......

**Comment by ramya-rao-a** [comment]
That must have reset something ...

Am glad that its better now, Happy Coding!
