### ISSUE TITLE
Completion doesn't work in go 1.9 for type aliases 

### ISSUE THREAD

**Issue by esemplastic** [Microsoft/vscode-go#1277]
`iris.C` 's origin type is `mvc.C`: https://github.com/kataras/iris/blob/master/mvc/controller.go#L39
`iris.C` type alias definition: https://github.com/kataras/iris/blob/master/go19.go#L148

The mvc.C looks like the following:

```go
type C struct {
	Name string
	Ctx context.Context
}

func (c *C) BeginRequest(ctx context.Context) { c.Ctx = ctx }
```

But when embedding the type in other type, auto completion doesn't work:

![problem1](https://user-images.githubusercontent.com/26099364/31510866-7e0e83c8-af8e-11e7-8aaa-15717fba7728.png)

Same for non-embedding, i.e return a struct that derives from a type alias:

![problem2](https://user-images.githubusercontent.com/26099364/31510867-7e6ec274-af8e-11e7-941a-0855cdf5f029.png)

Is this a bug, is it a feature request? I don't know but please try to look on this and fix that as soon as possible!

----

This issue is also posted at nsf/gocode repository: https://github.com/nsf/gocode/issues/479

**Comment by ramya-rao-a** [comment]
@esemplastic Can you provide a smaller code sample that I can try to repro this on?

**Comment by esemplastic** [comment]
Sure!

**file: mypackage/original/embedded_struct.go**
```go
package original

type C struct {
	Field  string
	Field2 int
}

func (c *C) BeginRequest() {

}
```

**file: mypackage/original/return_type.go**
```go
package original

type Result interface {
	DoSomething()
}

type Response struct {
	Text string
}

func (r Response) DoSomething() {

}
```

**file: mypackage/mypackage.go**
```go
package mypackage

import (
	"esemplastic/mypackage/original"
)

type (
	C        = original.C
	Result   = original.Result
	Response = original.Response
)
```

**file: main.go**
```go
package main

import (
	"esemplastic/mypackage"
)

type ExampleController struct {
	mypackage.C
}

func (ex *ExampleController) Get() {
	// `ex.` doesn't give completion for the mypackage.C's:
	//	     Field  string
	//       Field2 int
	// neither the function `BeginRequest()`,
	// it only shows the field `C` and its own function `Get`.
	// but `ex.Field` or `ex.BeginRequest` is compiled and ran without errors.
	// The `ex.C.` gives completion help.
}

func (ex *ExampleController) ReturnSomething() mypackage.Result {
	return mypackage.Response{
	// field: Text string is not shown to completion help,
	// nothing except the built go functions like `append`...
	}
}

func main() {

}
```

**Comment by ramya-rao-a** [comment]
Thanks @esemplastic, I can repro

The issue lies with gocode and I see that the corresponding issue there is being looked at.

Will close this issue as you have the upstream one to track the problem.

When gocode is fixed for working with type alias, please drop a comment here so that others who might encounter the same issue will know to update gocode
