### ISSUE TITLE
Code completion for method calls can fill out parameters

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#128]
![image](https://cloud.githubusercontent.com/assets/159209/11481176/a5be36fa-9750-11e5-9004-944f90187b70.png)

hitting `return` here in the code completion context gives me:

    azure.NewServicePrincipalToken

it could give:

    azure.NewServicePrincipalToken(id, secret, tenantID, resource)

GoSublime does it and it is very successful.

**Comment by lukehoban** [comment]
The current way we plan on addressing this is https://github.com/Microsoft/vscode-go/issues/9.  

This is a different UX, but I think satisfies the same need (and arguably with more context.

I'm inclined to focus on getting that added before considering also doing something like the UX proposed here.

**Comment by ahmetalpbalkan** [comment]
Agreed, can be better. If you try  GoSublime, it actually just prints the method signature and then allows you to circle on the parameters with Tab key.

Ideally, I'd expect this completion to complete the left side of the call as well by adding `,err` if missing (and just add an `if err != nil` check to the next line if that's the case).
