### ISSUE TITLE
debugging single unit test no longer works in october insiders

### ISSUE THREAD

**Issue by natefinch** [Microsoft/vscode-go#1280]
Clicking the "debug test" link above a test function now pops up the message 

"command 'vscode.startDebug' not found"

Probably related to this: https://github.com/Microsoft/vscode/issues/33795

**Comment by ramya-rao-a** [comment]
Thanks for reporting Nate

I have pushed in a fix and will be releasing an update soon

**Comment by natefinch** [comment]
Unfortunately, I uninstalled insiders after this bug and went back to the release version.  And I actually don't particularly want to go back to insiders because for some reason it loses all my settings?  Not exactly sure if that's expected or not, but it's kind of a PITA.

**Comment by ramya-rao-a** [comment]
> for some reason it loses all my settings

That shouldn't be happening. If you are able to get a repro, please do log an issue in the vscode repo

As for testing the fix, the API changes work on the stable build as well. So you can follow the same instructions in https://github.com/Microsoft/vscode-go/issues/1280#issuecomment-337769920 replacing `code-insiders` with `code`
