### ISSUE TITLE
Pasting a func with a blank line for a body indents the closing brace

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1285]
Paste this (note that there's no indentation in the blank line in the function body):

```go
func Qualifiers() {

}
```

What you get is:

```go
func Qualifiers() {
	
	}
```

where the blank line in the function body and the closing brace are indented by one tab.

The closing brace shouldn't be indented.

---

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-docker|Pet|0.0.18
sort-lines|Tyr|1.3.0
githistory|don|0.2.3
vs-code-xml-format|fab|0.1.5
markdown-table-formatter|jos|0.2.3
Go|luk|0.6.66
prettify-json|moh|0.0.3
rewrap|stk|1.5.1
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

**Comment by ramya-rao-a** [comment]
@willfaught Do you still see this? I am not able to get a repro.

**Comment by willfaught** [comment]
Nope! Looks good. Thanks.
