### ISSUE TITLE
Reinstall tools when a GOROOT change is detected

### ISSUE THREAD

**Issue by FiloSottile** [Microsoft/vscode-go#1286]
When the GOROOT changes (for example when Go is updated on macOS with Homebrew) the old GOROOT stays embedded in the binaries built with the old toolchain. This causes all kinds of things to break: list packages, autocomplete, `autocompleteUnimportedPackages` all break for stdlib packages.

This is the scenario explained here: https://blog.filippo.io/stale-goroot-and-gorebuild/

Ideally, the extension should detect this and rebuild the tools, also because the Go version changed, so it's probably time to rebuild code analysis tools. Otherwise, it should explicitly set the `GOROOT` env var to the output of `go env GOROOT`.

Similar to fatih/vim-go#901

**Comment by ramya-rao-a** [comment]
We do this currently if we see a change in the version of Go being used.
Doesnt that help?

**Comment by FiloSottile** [comment]
That's an approximation, since the tools will break on a GOROOT change even if the version stays the same, but it would have helped in my case. However, it did not rebuild the tools automatically. How/when is it supposed to happen?

**Comment by ramya-rao-a** [comment]
The first time you open a VS Code window after changing the Go version, VS Code would give you a prompt saying "Your Go version is different than before, few Go tools may need re-compiling" and an option to update all the dependent tools.

Behind the scenes, we store the Go version being used in local storage. Whenever you open a new window or Go project, the Go version is checked

**Comment by arbourd** [comment]
I personally don't get the "Your Go version is different than before, few Go tools may need re-compiling" message.

**Comment by FiloSottile** [comment]
I never saw it either. It might be that some people, me included,
restart the editor so rarely that the check is not effective if only
done at startup.

**Comment by FiloSottile** [comment]
FWIW, I just updated Go changing the GOROOT, and even restarting the editor no message popped up. I had to delete the tools and reinstall them to get back functional autocomplete for the stdlib. (A change of version without a change of GOROOT would cause more subtle problems I suspect.)

**Comment by arbourd** [comment]
Thanks so much for this @ramya-rao-a 🎉

**Comment by ramya-rao-a** [comment]
The feature will be out in the next update to the Go extension

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update of the Go extension (0.6.70)
