### ISSUE TITLE
Function complete doesn't support inline functions

### ISSUE THREAD

**Issue by FiloSottile** [Microsoft/vscode-go#1287]
If a local variable like this is defined

```
ensureKeyword := func (k string) {}
```

then `ensureKeyword` autocompletes to `ensureKeyword` without arguments even if `useCodeSnippetsOnFunctionSuggestWithoutType` is true.

**Comment by alexkohler** [comment]
It looks like we are checking if the suggest.class is `func`, whereas we should 
 be checking if the `suggest.type` contains 'func': https://github.com/Microsoft/vscode-go/blob/0.6.66/src/goSuggest.ts#L168

I.e. before:
`...&& suggest.class === 'func'`

My proposed solution:
`...&& suggest.type.includes('func')`

@ramya-rao-a thoughts?

**Comment by ramya-rao-a** [comment]
In this case what does `suggest.type` have?

**Comment by alexkohler** [comment]
@ramya-rao-a in this case, I believe a locally defined function would have a type of ‘var’.

**Comment by alexkohler** [comment]
@ramya-rao-a sorry, thought I read `suggest.class`. The `suggest.type` would be `func (k string)` I think - I’ll double check this when I have access to my PC.

**Comment by alexkohler** [comment]
@ramya-rao-a Yes, to confirm the `suggest.type` is `func(k string)`. The `suggest.type` of the same function declared non-locally is also `func(k string)`. Looking at all the potential edge cases, using `includes` does seem a little heavy handed.

**Comment by ramya-rao-a** [comment]
by non-locally, you mean in another file in the same package?

**Comment by alexkohler** [comment]
Not necessarily in another file, just declared in package scope rather than local scope.

I.e.:
```
package main

// package scoped function p
func p (k string) {}

func main() {
// locally scoped function l
l := func (k string) {}
}
```

**Comment by ramya-rao-a** [comment]
> The suggest.type of the same function declared non-locally is also func(k string)

Wouldn't the non-locally declared function have the class as `func`?

So `&& suggest.class === 'func'` could be replaced with `&& (suggest.class === 'func' || (suggest.class === 'var' && suggest.type.startswith('func')))

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.80)
