### ISSUE TITLE
No suggestions/completion in import paths

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#129]
If I create an

```
import ( )
```

block and start typing

```
import (
    "github.com/...
)
```

it should suggest me the packages in GOPATH. GoSublime does that well.

**Comment by lukehoban** [comment]
This would be nice - but is something that would really have to be supported in `gocode` to make sense.  Looks like there's a feature request for this here: https://github.com/nsf/gocode/issues/257.

For now though, I've added a couple new features to support this per https://github.com/Microsoft/vscode-go/issues/53#issuecomment-163713326.  I think that should be sufficient for now.
