### ISSUE TITLE
Problem with installing tools on Windows

### ISSUE THREAD

**Issue by GrumpyMetalGuy** [Microsoft/vscode-go#1292]
Hi,

I've done my best to see if I can track down the issue I'm facing, but had no luck. Go easy on the noob :)

I've installed golang 1.9 on Windows, set a GOROOT and GOPATH env variable (since I've installed Go under my user directory), but when I try and install the go tools using the Go: Install/Update Tools command in VS Code, it doesn't seem to install to the place I thought. My env vars are:

    GOPATH=C:\Users\username\Apps\Go\bin
    GOROOT=C:\Users\username\Apps\Go

And when I show the GOPATH in VS Code, I get:

    Current GOPATH: C:\Users\username\Apps\Go\bin

So far, so good. However, when I try and install the tools, I get the following:

    Installing 14 tools at C:\Users\username\Apps\Go\bin\bin

Which doesn't seem right. As such, I'm unable to run any go code from within VS Code.

The only settings I have for go in my user settings are:

    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.autocompleteUnimportedPackages": true

If anyone can suggest what I might be doing wrong, it would be much appreciated.

Cheers,

P.

**Comment by ramya-rao-a** [comment]
Your GOPATH is under the GOROOT
It is not advised for GOPATH and GOROOT to be the same or under each other

Try setting GOPATH to another location, reload VS Code and run the command to install tools again.

Pro Tip: To keep the Go tools that the Go extension for VS Code depends on separate from your Go projects, it is advised to have a separate location for the tools. You can do this by providing a different path for the tools via the `go.toolsGopath` setting

**Comment by GrumpyMetalGuy** [comment]
Sorry for the late response - yep, that worked well, plus I did some more reading on paths in Go, which provided some additional background. Thanks for the advice, onwards to more Go coding!
