### ISSUE TITLE
Missing configuration allowing auteSave only for Go

### ISSUE THREAD

**Issue by keeema** [Microsoft/vscode-go#1293]
Editor doesn't correctly show errors until I save the file with changes, so I would appreciate to have possibility to switch autoSave on - but only for GO files.

It works the same way in other Go editors.

**Comment by ramya-rao-a** [comment]
To enable autosave based on file type, please log an issue in the repo for vscode: https://github.com/Microsoft/vscode

If you are looking for error feedback as you type, then try enabling the live error feature by add the below in your setting
```
"go.liveErrors": {
    "enabled": false,
    "delay": 500
  }
```

This will use `gotype` on the file currently being edited and report any semantic or syntactic errors found after configured delay
