### ISSUE TITLE
Using more than one format tool

### ISSUE THREAD

**Issue by stanleynguyen** [Microsoft/vscode-go#1294]
Is it possible to use more than one format tool in __vscode-go__? Because I want to run all __goimports__, __gofmt__, and __goreturns__ on save but there seems to be only a single-tool option for __go.formatTool__

**Comment by stanleynguyen** [comment]
My suggestion would be using array of strings data type instead of string for __go.formatTool__

**Comment by dolmen** [comment]
`goimports` is a superset of `gofmt`. No reason to use both.
`goreturns` has a [`-i` option](https://github.com/sqs/goreturns/blob/master/goreturns.go#L32) that allows to ask it to run `goimports` before.
So I don't see a use case for this change request.
