### ISSUE TITLE
Open generated Go files in readonly mode

### ISSUE THREAD

**Issue by dolmen** [Microsoft/vscode-go#1295]
The Go community has a standard for files marked as machine-generated: https://golang.org/s/generatedcode
It is expected that the generator may ran again and that any changes made by a human would be overwritten. So those files should not be modified by humans. It would be helpful if VSCode could help to enforce this.

So I propose that when a .go file is opened and it contains the `^// Code generated .* DO NOT EDIT\.$`pattern the readonly mode would be enabled.

**Comment by roederw** [comment]
I don't think it's a good idea to force read only. What do you think about a notification like feature that notifies the user that this is a generated file? That way they understand that their changes will, probably, be overwritten with future generations.

**Comment by dolmen** [comment]
A notification at file open is too intrusive.
As a developer I may want to be able to open the generated file to read the code or because I want to trace it with the debugger. A notification every time I enter the file with the debugger would be too intrusive.
This is generated code, so if I want to modify it I should either use the generator again, or if I want just to make a discardable change (for example for debugging), disable the readonly mode to make my change. Requiring to disable the readonly mode makes the action painful, and this is the point of this feature request.

However once I have the file open, it would be helpful to have a notification of why the file is in readonly mode (and how to disable that) when I try to modify the content.

**Comment by ramya-rao-a** [comment]
If a file is being opened programatically say via a command registered by an extension, then the extension can use custom uri and register a content provider for the same which will result in the file being opened in a read only mode.

But we are talking about files that are opened normally, from the file explorer or quick open etc. There are no apis that the extension can use to let the core know that the file needs to be opened in read only mode.

One thing we (the Go extension) could do is to listen to the change event on the document. When this event occurs, check the first line for `^// Code generated .* DO NOT EDIT\.$` and provide a notification.

This is pretty easy to do and PRs are welcome.
I can help if anyone wants to give this a try.

Hint: https://github.com/Microsoft/vscode-go/blob/0.6.67/src/goMain.ts#L135  removes test coverage when there is a file change

**Comment by ramya-rao-a** [comment]
This is now out in the latest update to the Go extension (0.6.71)

**Comment by gregmarr** [comment]
@ramya-rao-a Is there any way to make this notification go away when I close the file, or automatically time out?  Right now I have to explicitly dismiss it, which is a bit of a pain.  I've also seen this appear when I haven't tried to edit the file, but I have been unable to track down a reproduction scenario so far.

**Comment by ramya-rao-a** [comment]
@gregmarr 

> Is there any way to make this notification go away when I close the file, or automatically time out?

You can always press the ESC key to make any notification in VS Code go away. There is no clear way to set timeouts on notification, but there is a feature request for the same in VS Code. See https://github.com/Microsoft/vscode/issues/23684

> I've also seen this appear when I haven't tried to edit the file

That's worrisome, its only supposed to show up on any change to the document. Please report an issue if you are able to get a repro consistently

**Comment by gregmarr** [comment]
@ramya-rao-a It happens if the file is regenerated (deleted and recreated) while it is open in VSCode.  I guess in some fashion that results in a "file edited" trigger.

**Comment by ramya-rao-a** [comment]
@gregmarr Does that happen often?

**Comment by gregmarr** [comment]
In main my project, I'm working with a Swagger library that generates 4 different sets of code based on 3 different swagger files.  I'm currently working on the services, so it's fairly often, but I don't expect it to be something that lots of people run into often.  I also suspect that it would be difficult to differentiate between "delete, and create new" from "edit".
