### ISSUE TITLE
Can't run "Go: Current GOPATH" on Windows

### ISSUE THREAD

**Issue by Blazero** [Microsoft/vscode-go#1296]
#![image](https://user-images.githubusercontent.com/14362209/31849605-6866b92e-b677-11e7-880a-c01f220c6268.png)

I've set GOPATH in the Environment Variables, and even in settings of VSCode ("go.gopath": "D:\\Documents\\Go"). It just didn't work. 
Consequently, it's not possible to install go tools.

**Comment by Blazero** [comment]
This is solved after I open the GOPATH **floder** in VSCode. Only opening a GO file is not enough. No one mentioned this while I googled it.

![image](https://user-images.githubusercontent.com/14362209/31850372-50733192-b683-11e7-9ef3-31402d093d57.png)

**Comment by ramya-rao-a** [comment]
The extension not getting activated in Windows until you open a folder was a bug.
The latest update (0.6.67) has the fix for this.
Sorry for the inconvenience
