### ISSUE TITLE
Go plugin not functioning at all on Windows

### ISSUE THREAD

**Issue by jmmcatee** [Microsoft/vscode-go#1299]
After upgrading to Go 1.9.1 and the latest release of VS Code, I cannot get any of the Go plugin functions to work. They all present me with various "command '####' not found. All my Go variables are set and I have tried a variety of settings changes. Anyone have any idea?

**Comment by jmmcatee** [comment]
This appears to only happen if I am opening arbitrary Go files without have a folder open. If this is a requirement to load the function, I missed this in the instructions.

**Comment by 474420502** [comment]
My situation is just like yours @jmmcatee

**Comment by ramya-rao-a** [comment]
@jmmcatee Please see https://github.com/Microsoft/vscode-go/issues/1271#issuecomment-336198657
