### ISSUE TITLE
Plugin should manage its own copy of go helper tools globally

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#130]
I find it tedious and difficult to install godef/goimports/goreturns/go-vet etc to each GOPATH I have. When I switch to another project, these tools are missing again.

I also don't want to keep them under my GOPATH at all. They're just some tools that helps me to write code. They do not have anything to do with my project either. I know GOPATH actually keeps things tidy but a shared global copy for these tools makes sense to me.

I think vscode-go should install and keep a copy of these tools mentioned in the README itself and perhaps update them regularly.

**Comment by newhook** [comment]
Dup of https://github.com/Microsoft/vscode-go/issues/5

**Comment by ahmetalpbalkan** [comment]
ah yeah I was that offline feedback in the issue. thanks @newhook
