### ISSUE TITLE
cannot work on some packages in the vendor directory

### ISSUE THREAD

**Issue by dxvgef** [Microsoft/vscode-go#1300]
I store the Echo framework in the vendor directory, but vscode does not have the completion lists for the Echo package in vendor
There are other packages in the vendor directory, some will have completion lists, some will not, and I'll use IDEA to be all right.

**Comment by dxvgef** [comment]
It's work.

**Comment by ramya-rao-a** [comment]
@dxvgef I am guessing from your latest comment that completion is working as expected.

We use `gocode` for getting completions which work only if the packages are installed.
Check if the package for which you want completion exists in your GOPATH/pkg folder
