### ISSUE TITLE
Change the path to the debug binary file

### ISSUE THREAD

**Issue by dxvgef** [Microsoft/vscode-go#1301]
I set up `"buildFlags"` in `launch.json`: 
`"-gcflags='-o ${workspaceRoot}/bin/debug ${workspaceRoot}/src/main/main.go'"`
and I have a vendor directory, it will tip cannot find the custom packages for my project.

**Comment by Daylien** [comment]
Hey, i have a little work around for this problem.

First configure an task for the build process. Like this: 

```json  
  "version": "2.0.0",
    "tasks": [
        {
            "taskName": "Build",
            "type": "shell",
            "command": "go",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "args": [
                "build", "-o", "${workspaceRoot}/bin/output", "${workspaceRoot}/main.go"
            ]       
        }
    ]
} 
```
After that edit the debugger settings. Like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "exec",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "preLaunchTask": "Build",
            "program": "${workspaceRoot}/bin/output",       
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}
```

Make sure that ` "preLaunchTask": "Build", ` is set to the correct task name !

If you hit the debugger key (for me `F5`), the task is running after that you can debug your code. Works like a charm for me.

Hope this helps. Have fun

**Comment by ramya-rao-a** [comment]
@dxvgef Add `"trace": "verbose"` to your debug configuration and start debugging.
In the debug console you will see a like `Running:` followed by path to the `dlv` binary and all the arguments being passed to it.
Check if reflects what you expect

**Comment by ramya-rao-a** [comment]
@dxvgef Closing this issue as we havent heard back you in a while
