### ISSUE TITLE
Windows: Open single file crashes plugin 

### ISSUE THREAD

**Issue by avoidik** [Microsoft/vscode-go#1306]
Hello,

Attempt to open single go-file finished with plugin failure.
```
Activating extension `lukehoban.Go` failed:  Cannot read property 'substr' of undefined
Here is the error stack:  TypeError: Cannot read property 'substr' of undefined
	at Object.getCurrentGoPath (C:\Users\vja\.vscode\extensions\lukehoban.go-0.6.66\out\src\util.js:301:34)
```

Full error log:
https://pastebin.com/8Vyti4kK

Environment variables
```
echo %GOROOT%
C:\tools\go\
echo %GOPATH%
C:\Users\vja\go\
echo %PATH%
...;c:\Users\vja\go\bin
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @avoidik 

The fix for this is in the master branch.
Will be releasing an update this week.
See https://github.com/Microsoft/vscode-go/issues/1271#issuecomment-336198657 to get the fix before the release
