### ISSUE TITLE
Hovering a variable does not show the full package path

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#131]
![image](https://cloud.githubusercontent.com/assets/159209/11481886/b201c2ac-9754-11e5-837c-10e330aab7cb.png)

cuts at `/com...`. Maybe it can be line-wrapped somehow?

**Comment by lukehoban** [comment]
This is blocked on https://github.com/Microsoft/vscode/issues/842.

**Comment by lukehoban** [comment]
This should be fixed by https://github.com/Microsoft/vscode/issues/842.
