### ISSUE TITLE
All Commands that are mentioned on Go for Visual Studio Code,not one of them works

### ISSUE THREAD

**Issue by Jetlum** [Microsoft/vscode-go#1310]
command 'go.add.tags' not found;
Error command 'go.import.add' not found; 
Error command 'go.get.package' not found;
Error command 'go.gopath' not found; 
Error command 'go.test.previous' not found etc...

![untitled](https://user-images.githubusercontent.com/13225839/32227968-1b9a2ef4-be4d-11e7-865a-bf0e67756e12.png)

**Comment by belltanellc** [comment]
I had the same issue on Windows. I had to override go.gopath in settings.json and use \\ instead of \ in the path.    "go.gopath": "C:\\Files\\Development\\Go1.8.1\\Workspace". The first backslash is the escape character so that the second is read literally.

**Comment by ramya-rao-a** [comment]
Sorry about that @Jetlum 

The latest update to the Go extension (0.6.67) has the fix for this.
