### ISSUE TITLE
Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode-go#1311]
- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.0.3
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
xml|Dot|1.9.2
gitlens|eam|5.7.1
tslint|eg2|1.0.14
vscode-abap|lar|0.1.0
Go|luk|0.6.66
postscript|max|1.0.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.4.0
vscode-docker|Pet|0.0.20
vscode-icons|rob|7.17.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
html-preview-vscode|tht|0.1.1

(1 theme extensions excluded)

---

Steps to Reproduce:

No idea sorry, just found it in the logs after a programming a while.

```
shell.ts:459 Cannot read property 'forEach' of null: TypeError: Cannot read property 'forEach' of null
	at GoDocumentSymbolProvider.convertToCodeSymbols (C:\Users\mxs\.vscode-insiders\extensions\lukehoban.go-0.6.66\out\src\goOutline.js:68:14)
	at documentSymbols.then.decls (C:\Users\mxs\.vscode-insiders\extensions\lukehoban.go-0.6.66\out\src\goOutline.js:89:18)
	at <anonymous>
```

**Comment by ramya-rao-a** [comment]
I've added a fix to take care of the null scenario, but am curious as to in which case it would happen.

If you see this again, can you please add more details here?

**Comment by maxibanki** [comment]
Yes, I try my best to give you more further details about this issue. But it's very hard for me to give you that, because I don't know exactly when and how this error occurred.

**Comment by ramya-rao-a** [comment]
no problem, thanks for reporting though, Happy Coding!

**Comment by maxibanki** [comment]
Now the error occurred during the installation of the Go dependencies:

```javascript
Cannot read property 'forEach' of undefined: TypeError: Cannot read property 'forEach' of undefined
	at Promise.all.then (C:\Users\maxsc\.vscode-insiders\extensions\lukehoban.go-0.6.67\out\src\goPackages.js:121:13)
	at <anonymous>
e.onUnexpectedError @ shell.ts:459

```

**Comment by ramya-rao-a** [comment]
That line of code is only hit when typing or when running the `Go: Add Import` command.
