### ISSUE TITLE
Cmd+Click (Go to Definition) not working on JS/Go in multiple files/packages

### ISSUE THREAD

**Issue by benguild** [Microsoft/vscode-go#1315]
I've considered switching from IntelliJ to VS Code but one of the things that IntelliJ does really nicely out of the box is indexed "Go to Definition" across multiple packages/files in the case of web projects or Go projects, etc.

I tested it in VS Code and it *sort of* works. For example, in a JavaScript file, I can Cmd+Click (or F12) to certain methods or definitions... as long as they're not in another file. If they are, it just says "no definition found".

With Golang, I'm seeing methods in different packages not working. Usually methods within that folder/package do indeed work with this.

I'm running version 1.17.2 for Mac right now.

----

**Also, two bits of UX feedback:**
- For some reason the cursor isn't always a hand when hovering over clickable stuff with the Command key held down, it like flickers to the text cursor default (the thin-line with T's at the top and bottom) ...? Doesn't inspire much confidence :(
- When opening a new tab for this, it seems much slower... taking almost a second and fading in awkwardly vs. IntelliJ which loads files basically instantly. Over the course of the day, I feel like this would be tremendously frustrating. Is there a fix or optimization?

**Comment by ramya-rao-a** [comment]
Any issues you see with javscript in VS Code as well as UX feedback, please log an issue at https://github.com/Microsoft/vscode. 
This is the repo for the Go extension and so my comments below are with respect to Golang.

I am able to see the `Go to Definition` feature is working as expected across Go packages.
As long as all the packages in question are under the same GOPATH, I dont see why this wouldnt work.

Did you happen to try to navigate to a package outside GOPATH?

**Comment by benguild** [comment]
Yes, I only tried to Cmd+Click stuff inside the `GOPATH` ... works fine in IntelliJ but not here. If we can fix this, I can basically officially adopt this as my editor for at least that part.

**Comment by ramya-rao-a** [comment]
- Can you run the command `Go: Current GOPATH` and check if the result is indeed your expected GOPATH?
- When you hover on symbols, do you get information on the method?
- Are you using the language server (do you have `go.useLanguageServer` turned on in your settings?)

**Comment by benguild** [comment]
To answer your questions (sorry for the delay) ...
1. Yes, and I have my GOPATH open in VS Code as well.
2. If I hover over packages I get information, but not methods. Variables in the local file also work but again... not methods.
3. I haven't setup a language server.

**Comment by ramya-rao-a** [comment]
- From the menu select Help -> Toggle Developer Tools.
- Click on "Console" when the dev tools open.
- Clear all the errors if there are any
- Cmd-Click on the method for which you want to get the definition

Do you see any errors in the console related to running a command called "godef"?

**Comment by benguild** [comment]
There weren't any errors initially. Just one info line. Here's what I see after clicking:
```
workbench.main.js:sourcemap:9 [Extension Host] Cannot find golint
workbench.main.js:sourcemap:9 [Extension Host] Error: Command failed: /Go/bin/godef -t -i -f file.go -o 849
godef: no declaration found for test.Method

	at ChildProcess.exithandler (child_process.js:217:12)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
workbench.main.js:sourcemap:9 [Extension Host] Error: Command failed: /Go/bin/godef -t -i -f file.go -o 851
godef: no declaration found for test.Method

	at ChildProcess.exithandler (child_process.js:217:12)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

... That's when trying the same line quickly a couple of times. Same code line works fine in IntelliJ.

**Comment by ramya-rao-a** [comment]
The Go extension uses reputed Go tools from the Go open source community to provide most of the features. How IntelliJ works is beyond me. So lets not compare the two.

The Go to Definition feature is provided by the `godef` tool which as you can see is from the errors in the console is not able to find the definition for the symbol in question. 

Can you run that command from the terminal with the same arguments that you see in the console and see if it still returns the same error? If so, then I would suggest to log an issue in the repo for the `godef` tool. The fact that this (go to definition across packages) works for a lot of folks, but doesnt in your case alludes to something in your env setup or the code itself having issues with the `godef` tool.

Also, you can change the tool being used for finding definitions by adding the setting `"go.docsTool": "gogetdoc"`. Let's see if the tool `gogetdoc` fares any better.

**Comment by ramya-rao-a** [comment]
@benguild Any updates?

**Comment by benguild** [comment]
It's the same with `godef`. Not sure what IntelliJ uses but IntelliJ works perfectly?

**Comment by ramya-rao-a** [comment]
> It's the same with godef

Can you elaborate? You get the same issue when you add `"go.docsTool": "gogetdoc"` to your settings? Did you try running `godef` from the command line as described in https://github.com/Microsoft/vscode-go/issues/1315#issuecomment-345335868?

**Comment by benguild** [comment]
@ramya-rao-a yes the behavior is the same when using `godef` from the command line as mentioned in my comment above. I haven't had the chance to try your settings tweak though.

**Comment by ramya-rao-a** [comment]
Since you are getting the same issue when using `godef` from the command line, I'd say that the problem is with the `godef` tool itself.
Try adding `"go.docsTool": "gogetdoc"` to you settings to see if that makes a difference.

**Comment by benguild** [comment]
That seems to work, but it's a little slow. Is there any way to pre-index stuff?

**Comment by ramya-rao-a** [comment]
Not really

If you are not on Windows, then another option is to use the language server. Add `"go.useLanguageServer": true` to your settings and read [Language Server for Go](https://github.com/Microsoft/vscode-go#go-language-server-experimental)

**Comment by benguild** [comment]
Is that instead of the other setting or in addition to it? — I think IntelliJ does its own indexing somehow. It might be worth looking into, but I know you've said in the past that you're not familiar with their product. It does work correctly though.

**Comment by ramya-rao-a** [comment]
When you enable the use of language server, the other setting is ignored.

Indexing and caching and re-using ASTs etc are all features that a centralized service can provide.
By default the Go extension to VS Code does not use a centralized approach, instead it relies on a variety of Go tools instead.

The language server by sourcegraph is the right step forward.

**Comment by benguild** [comment]
OK— is there a reason why that's not turned on or included by default?

**Comment by benguild** [comment]
Also, it says:
> Reload VS Code window after installing the Go language server

... Every time I open a file now. But the plug-in is installed already and I didn't hear of a way to install this on its own from you?

**Comment by ramya-rao-a** [comment]
> is there a reason why that's not turned on or included by default

Initially, there were some perf issues that had to be hashed out. Right now (its about a year since we introduced the language server support), it is quite stable but has limited features. We still don't have Windows support though.

Are you sure the language server got installed in the right place? It should either be in your `PATH` or in your `GOPATH/bin`. If it is the latter, then make sure that its the same GOPATH as what you see when you run the command `Go: Current GOPATH`

**Comment by benguild** [comment]
Got it, it wasn't installed. That is quite fast. I'll give it a try, thanks!
