### ISSUE TITLE
Renaming a symbol also scan other golang projects for syntactic correctness

### ISSUE THREAD

**Issue by atedja** [Microsoft/vscode-go#1316]
When renaming a symbol on a particular golang project, VSCode seems to also be checking other golang projects in the GOPATH that includes that project for syntactic correctness.  If there is a golang project that fails this check, the rename also fails.

Steps to reproduce:
1. Create two projects on GOPATH. Example: `~/go/src/github.com/yourusername/project1` and `~/go/src/github.com/yourusername/project2`
2. Purposely create a syntax error on project1
3. Create a symbol on project2
4. Import project2 on project1 `import "github.com/yourusername/project2"`, and use that particular symbol on project1.
5. Rename that symbol on project2, notice it also looks for errors on project1 and fails if there is an error.

Renaming a symbol should not be done across projects.

Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by ramya-rao-a** [comment]
We use the [`gorename`](https://godoc.org/golang.org/x/tools/cmd/gorename) tool.

It does have a `-force` flag which lets the rename operation proceed even if conflicts are reported.

Can you try the `gorename` command from the terminal and see if using the `-force`  lets you rename in the presence of the errors?

**Comment by atedja** [comment]
You are right. I ran `gorename` and it produced the same errors, with and without `-force`. This looks like an intentional `gorename` feature.
```
gorename automatically computes the set of packages that might be
affected.  For a local renaming, this is just the package specified by
-from or -offset, but for a potentially exported name, gorename scans
the workspace ($GOROOT and $GOPATH).
```
It's quite annoying that you can't rename a package unless all of your packages are in proper/compilable form.
