### ISSUE TITLE
go.testOnSave with verbose output

### ISSUE THREAD

**Issue by cxww107** [Microsoft/vscode-go#1317]
Would you consider to run go.testOnSave with -v flag?

It is useful sometimes to log in unit tests (using t.Log). These messages are not displayed in output after saving. Still it can be achieved with a new task but it would be nicer to have verbose output in "on save" feature.

Thank you.

**Comment by ramya-rao-a** [comment]
Have you tried setting the `go.testFlags` to `["-v"]` ?
Note if you are using any buildflags via the `go.buildFlags` setting, then you will need to repeat it here.

**Comment by cxww107** [comment]
I missed this parameter. Thank you!

**Comment by ramya-rao-a** [comment]
Happy Coding!
