### ISSUE TITLE
Having `json:"omitempty"` twice shouldn't raise a warning

### ISSUE THREAD

**Issue by ls42** [Microsoft/vscode-go#1318]
Hi,

having the aforementioned tag twice in a struct is marked in the editor as a warning, stating that that tag shouldn't appear twice in a struct.

<img width="526" alt="screen shot 2017-11-05 at 22 17 40" src="https://user-images.githubusercontent.com/498359/32419258-7d1c3180-c277-11e7-9a3b-21d34a62a0ad.png">

Have a nice day and thanks for this awesome plugin!

**Comment by ramya-rao-a** [comment]
@ls42 Thanks for reporting this.

The warnings are coming either from the linting or vetting.
The inner workings of either are out of scope for the Go extension.

Try turning off linting and vetting one by one via the settings (`go.lintOnSave` and `go.vetOnSave`) to figure out which of the 2 is giving the warning.

If its the linter then log an issue at https://github.com/golang/lint if you are using the default linter. If you have changed the `go.lintTool` setting, then log the issue in the corresponding repo.

For vetting, we use the command `go tool vet`, so I am guessing you will have to log an issue in the go repo.

**Comment by ls42** [comment]
@ramya-rao-a Thanks for your suggestions. I tried tuning the settings and with `go.vetOnSave="off"` its better. I'll ask over at the go repo for a change.

Thanks again, have a nice day.
