### ISSUE TITLE
Formatting on Refactor

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode-go#1319]
Hi! Thanks a lot for the great extension.

We wanted to use our own coding style within Go and so we hand to disable your formatting system, which for now only has the option: `go.formatOnSave` to be false. But when you refactor your code it also formats it. Like this:

![go-bug](https://user-images.githubusercontent.com/2157285/32419794-3281db20-c295-11e7-8952-6b108bad19dc.gif)

I don't know if the formatting is done by the external tool or if it's done by you, but if in any ways it is done by you can you add an option to turn it off? 

Thanks a lot and
Keep up the great job 👍

**Comment by ramya-rao-a** [comment]
@pmkary Your linked image/gif is not getting loaded, can you add it again?

**Comment by pmkary** [comment]
I uploaded the gif in an [outside source in mp4 format](https://thumbs.gfycat.com/WearyPeskyAustralianfreshwatercrocodile-mobile.mp4). Hope you can see it right and clear

**Comment by ramya-rao-a** [comment]
Check both User and Workspace settings. If you have disabled formatting in User settings and enabled it in Workspace settings, then the latter overrides the former.

If that's not the case,
- Do you see this formatting done only after rename or even when saving after doing a manual change?
- Do you have any other extensions that might be doing this? Try disabling all extensions (`code --disable-extensions`), enable just the Go extensions and try.

**Comment by pmkary** [comment]
> ### Check both User and Workspace settings. If you have disabled formatting in User settings and enabled it in Workspace settings, then the latter overrides the former.

No I have the formatting disabled everywhere. The only workspace setting is this:

```json
{
    "cSpell.words": [
        "Optimus"
    ]
}
``` 

And my main settings is:

```
{
    "go.gopath":"/Users/pmk/Codes/Go",
    "go.formatOnSave":false,
    "[go]":{
        "editor.formatOnSave":false,
        "editor.formatOnType":false,
        "editor.formatOnPaste":false
    },
    "[karyscript]":{
        "editor.wordSeparators":"`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?"
    },
    "[css]":{
        "editor.formatOnSave":true,
        "editor.renderWhitespace":"none"
    },
    "javascript.format.enable":false,
    "editor.autoIndent":false,
    "editor.detectIndentation":false,
    "[markdown]":{
        "editor.fontSize":14,
        "editor.lineHeight":30
    },
    "editor.cursorBlinking":"expand",
    "editor.trimAutoWhitespace":true,
    "files.trimTrailingWhitespace":true,
    "window.openFilesInNewWindow":"off",
    "editor.fontSize":13,
    "terminal.integrated.fontSize":14,
    "editor.lineHeight":26,
    "editor.wordWrapColumn":90,
    "html.format.wrapLineLength":300,
    "editor.fontFamily":"Hasklig-Medium",
    "editor.tabSize":4,
    "editor.wordWrap":"wordWrapColumn",
    "editor.minimap.enabled":false,
    "editor.minimap.renderCharacters":false,
    "editor.renderIndentGuides":false,
    "editor.wrappingIndent":"same",
    "editor.quickSuggestionsDelay":0,
    "window.zoomLevel":0,
    "editor.renderWhitespace":"none",
    "editor.insertSpaces":true,
    "editor.formatOnType":false,
    "workbench.statusBar.visible":true,
    "window.titleBarStyle":"custom",
    "cSpell.showStatus":false,
    "editor.mouseWheelZoom":false,
    "git.confirmSync":false,
    "workbench.activityBar.visible":true,
    "workbench.sideBar.location":"left",
    "typescript.referencesCodeLens.enabled":false,
    "terminal.integrated.shell.osx":"/usr/local/bin/fish",
    "terminal.integrated.lineHeight":1.42,
    "editor.fontLigatures":true,
    "workbench.iconTheme":null,
    "typescript.check.npmIsInstalled":false,
    "rust.mode":null,
    "workbench.colorTheme":"Kary － Light"
}
```

> ### Do you see this formatting done only after rename or even when saving after doing a manual change?

I only see this formatting done after I done rename. on saving there is no formatting

> ### Do you have any other extensions that might be doing this? Try disabling all extensions (code --disable-extensions), enable just the Go extensions and try.

I have no other extension for Go and no extension that does formatting.

**Comment by ramya-rao-a** [comment]
We use the `gorename` tool for the rename operation.
It returns the diff that needs to be applied on the file, and Go extension applies the diff.

Can you try running `gorename` from the terminal on your file to see if this is so? Pass the `-d` flag to get the diff as output

**Comment by pmkary** [comment]
Yes the formatting was caused by the `grename` tools.
I guess I should create an issue in Go.

Thanks a lot for helping me here and putting your time.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
