### ISSUE TITLE
Indentation/new lines in compiler errors are lost

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#132]
I get a somewhat neat error msg from `go build`:

![image](https://cloud.githubusercontent.com/assets/159209/11482100/c577bbce-9755-11e5-9c27-4aefe0ed0f8e.png)

in vscode-go hovering to error does this:

![image](https://cloud.githubusercontent.com/assets/159209/11482112/d2462cd2-9755-11e5-8661-ef250b080f49.png)

all new lines/tabs are lost.

**Comment by lukehoban** [comment]
This is blocked on https://github.com/Microsoft/vscode/issues/843.
