### ISSUE TITLE
How do I find implement in vscode-go？

### ISSUE THREAD

**Issue by malc0lm** [Microsoft/vscode-go#1320]
I saw that vscode-go have already supported this feature "Find implementations (using guru)
", but there is no way to do this in vscode-go ui. So what should I do?
(My vscode-go verison is 0.6.67)

**Comment by ramya-rao-a** [comment]
There is a command `Go to Implementation`. You can run it from the command pallet or assign a keyboard shortcut for it.

Good point though, I'll look into adding more details in the README file
