### ISSUE TITLE
Can't goto definition if is imported like   . "gopkg.in/check.v1"

### ISSUE THREAD

**Issue by DeathPoem** [Microsoft/vscode-go#1321]
As stated in title.  Can't goto definition for 'Suite' in code like this : 

```
package tests

import (
	"somecustom/suites"
	"testing"

	. "gopkg.in/check.v1"  // would omit package name 
)

var context *suites.SharedContext = suites.NewSharedContext()

// gocheck execute suites sequentially
var _ = Suite(&suites.CreateASuite{Ctx: context})
```

**Comment by ramya-rao-a** [comment]
The default tool we use for finding definitions is `godef` which doesn't support dot imports.
See https://github.com/rogpeppe/godef/issues/19

As a workaround, you can change the setting `go.docsTool` to `gogetdoc` which should help
