### ISSUE TITLE
Feature: explorer tree view color scheme for _test.go file

### ISSUE THREAD

**Issue by bsr203** [Microsoft/vscode-go#1322]
Hi.

It would be great to have normal visibility for the source files on explorer window, and the test files (_test.go) are somewhat less dominant color (grayish in my dark color). It helps a lot in easily finding the files as the number of files in a package grows. I could do that through some customization in Atom, and wonder something similar possible.

thanks.

**Comment by ramya-rao-a** [comment]
Sorry, that level of customization is not supported in VS Code.
