### ISSUE TITLE
vscode-go shows warning every time I start debugging node

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-go#1324]
Since vscode-go is activated with `"onDebug"`, and it checks for out of date packages on activate, I get an out of date package warning when I start debugging a node app. Ideally I would only get that when a .go file is present.

I don't know if it's easily possible to improve this with our extension model. vscode-go would have to have a file watcher for .go files so it can detect this on its own.

**Comment by ramya-rao-a** [comment]
can you share a screenshot of the warning?

**Comment by roblourens** [comment]
It's just the prompt to update one of my outdated go tools

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/32583083-a426c714-c4a6-11e7-9bf4-d101c3ce41e4.png)

**Comment by roblourens** [comment]
Will it still prompt later if it gets activated when not on a go file?

**Comment by ramya-rao-a** [comment]
it will prompt only when activated on a go file
