### ISSUE TITLE
Extension only works if VSCode run from terminal...

### ISSUE THREAD

**Issue by fruser** [Microsoft/vscode-go#1325]
Having issues with running GO files from within Code. I've configured GOPATH but it didn't help:
`Current GOPATH: /Users/username/Projects/GO`

This is the error message I'm getting when I try to run the code:
```
[Running] go run "/Users/username/Projects/GO/src/hello/hello.go"
/bin/sh: go: command not found
```
Extension does work if I run it from within the terminal. Are there any other env variables I can configure in Settings file to make it work outside the terminal?

**Comment by ramya-rao-a** [comment]
When you say you are trying to run the code, I am guessing you mean you ran the `go run` command from the integrated terminal

When you run VS Code from the terminal, it inherits all the env variables from the terminal.
When you run VS Code from a shortcut, the same doesnt happen.

See #708

**Comment by fruser** [comment]
@ramya-rao-a I'm sorry, I didn't provide enough information in my issue. 
I'm using OSX; Go was installed using Brew, therefore, `which go` results in `/usr/local/bin/go`
It looks like even when I specify GOPATH in the settings and run Code from the shortcut Code is unable to find GO. Is there a way to specify `go` binary in the settings somehow?

**Comment by ramya-rao-a** [comment]
GOPATH has nothing to do with finding the `go` binary.

Can you run `go env GOROOT` in the below 3 ways and compare the results
- Run it in an external teriminal
- Close all VS Code instances. Run `go env GOROOT` in the integrated terminal in VS Code after running VS Code from shortcut
- Close all VS Code instances. Run `go env GOROOT` in the integrated terminal in VS Code after running VS Code from the external terminal

**Comment by fruser** [comment]
@ramya-rao-a please see the output below:
- external terminal: `/usr/local/opt/go/libexec`
- VS Code instance started from shortcut: `/usr/local/opt/go/libexec`
- VS Code instance started from external terminal: `/usr/local/opt/go/libexec`

**Comment by ramya-rao-a** [comment]
> Is there a way to specify go binary in the settings somehow?

Yes, you can provide it via the `go.goroot` settings. This setting is specific to the Go extension and will not affect the integrated terminal. So this will not help you.

What does running `which go` give when you run it inside the integrated terminal when VS COde is opened using shortcut? Also check the value of the PATH variable. Run `echo $PATH`. Does it have `/usr/local/bin/` ?

**Comment by fruser** [comment]
Hm, interesting...
This is the output of `which go` when I opened Code via the shortcut:
`/usr/local/bin/go`, thus running `go run hello.go` from within integrated terminal works as expected.

Here is the output of the $PATH env variable:
`/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/user/.swiftenv/shims:/Users/user/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/qt@5.5/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/user/Applications/miniconda3/bin:/usr/local/opt/go/libexec/bin:/Users/user/Projects/GO/bin`

**Comment by ramya-rao-a** [comment]
> This is the output of which go when I opened Code via the shortcut:
/usr/local/bin/go, thus running go run hello.go from within integrated terminal works as expected.

That solves your issue right?

**Comment by fruser** [comment]
Well, if I use internal terminal, then yes. But if I use `Run Code` feature, then I get `/bin/sh: go: command not found` error message...

**Comment by ramya-rao-a** [comment]
What is this `Run Code` feature you are talking about??
There is no such feature from the Go extension.

**Comment by fruser** [comment]
Wow, you are absolutely right! This feature was part of the extension (Code Runner) I've installed and forgot about. I'm sorry for the confusion! Thank you so much for all your help!

**Comment by ramya-rao-a** [comment]
Ok then, Happy Coding!
