### ISSUE TITLE
Editor not looking at vendor folder it is `ln -s` from other path

### ISSUE THREAD

**Issue by kkpoon** [microsoft/vscode-go#1327]
```
VSCODE=Version 1.18.0 (1.18.0)
GOPATH=/Users/admin/Development/go
GO Extension = 0.6.67
go version go1.9.2 darwin/amd64
```
Project path at `$GOPATH/src/github.com/kkpoon/myproject`

in the editor, the import statement is red underlined

mouseover one of it, for example `"github.com/rs/cors"`, shows
```
cannot find package "github.com/rs/cors" in any of:
    /usr/local/Cellar/go/1.9.2/libexec/src/github.com/rs/cors (from $GOROOT)
    /Users/admin/Development/go/src/github.com/rs/cors (from $GOPATH)
```
in terminal, vscode integrated or outside vscode, `go build` success

`"github.com/rs/cors"` exists in `vendor` folder
```
cd $GOPATH/src/github.com/kkpoon/myproject
ls vendor/github.com/rs/cors
LICENSE   README.md cors.go   utils.go
```

**after investigation, found**

if project path is locate at `/some/path/outside/go/path/myproject`
and `ln -s /some/path/outside/go/path/myproject` to `$GOPATH/src/github.com/kkpoon/myproject`
then go import statement is red underlined

if project code is really stored in `$GOPATH/src/github.com/kkpoon/myproject`
vscode works as expected.

**Comment by ramya-rao-a** [comment]
What is the folder that you have opened in VS Code?

Can you try to open the folder to which you have symlinked?

**Comment by kkpoon** [comment]
I start vscode by 

```
cd $GOPATH/src/github.com/kkpoon/myproject
code .
```

**Comment by ramya-rao-a** [comment]
And is `$GOPATH/src/github.com/kkpoon/myproject` symlinked to the actual place where the other code lives or is the symlink created higher up in the path?

For example, I symlinked `$GOPATH/src/folder` to another location where the code actually lives.
If I open `$GOPATH/src/folder`, then everything is fine
If I open `$GOPATH/src/folder/some/other/folder/under/this`, then I get the same errors like you with vendor folders not being identified

**Comment by kkpoon** [comment]
for example:
```
# actual code location
/Users/admin/Development/github.com/project1

# GOPATH location by ln -s
GOPATH=/Users/admin/Development/go
$GOPATH/src/github.com/kkpoon/project1

ls /Users/admin/Development/github.com/project1
# and 
ls $GOPATH/src/github.com/kkpoon/project1
# show the same result
```

**Comment by ramya-rao-a** [comment]
That still doesn't tell me if you symlinked the folders at the `github.com` level or `kkpoon` level or `project1` level

**Comment by kkpoon** [comment]
project1 level

I did mkdir -p src/github.com/kkpoon
cd into that level and symlink project1 to its actual location. 

This worked well when vscode icon was orange. But not after I update vscode to blue icon version.

**Comment by ramya-rao-a** [comment]
When you hover over the tab after opening a file, you will get see the path of the file. Does this path correspond to the actual place where the code is or the location under GOPATH?

**Comment by kkpoon** [comment]
It shows the actual path, which is not under `GOPATH`

**Comment by ramya-rao-a** [comment]
that's the issue..

The Go extension depends on the file path (the one you see on the file tab) to determine the import path of the current package to use in the `go build` command.
Since the value is the actual path, the import path cannot be determined and the extension falls back to using `go build .` which in turn is obviously not able to find the vendor folders.

Can you try opening VS Code at `$GOPATH/src/github.com/kkpoon` level, and see if the file path in the tab now shows the actual path or the GOPATH?

**Comment by kkpoon** [comment]
I open vscode at $GOPATH/src/github.com/kkpoon. it shows the path under GOPATH and it works fine.

Yet, it worked fine even I start vscode in symlink folder.

Now, I have no idea whether this issue belongs to OS level (macos) or vscode or go extension.
:(

**Comment by ramya-rao-a** [comment]
Ok, so to summarize
- opening vscode at $GOPATH/src/github.com/kkpoon works
- opening vscode at /Users/admin/Development/github.com/project1 works
- opening vscode at $GOPATH/src/github.com/kkpoon.project1 doesn't work

Is that right?

**Comment by kkpoon** [comment]
opening vscode at `$GOPATH/src/github.com/kkpoon` works
opening vscode at `/Users/admin/Development/github.com/project1` doesn't works (it is not under GOPATH)
opening vscode at `$GOPATH/src/github.com/kkpoon/project1` doesn't work

**Comment by shuntksh** [comment]
I am having the exact same issue as @kkpoon that I have to open one code from level up ($GOPATH/src/github.com/kkpoon in this case to work on project1)  in order for go-plugin to read vendor directory.

**Comment by quicksnap** [comment]
Also seem to be affected. When I open it one level above the symlink, the red underline changes to a green underline with the same error message.

**Comment by quicksnap** [comment]
Looks like the green underline is coming from `"go.vetOnSave": "package"` setting

**Comment by ewoutp** [comment]
Same problem here.

**Comment by ramya-rao-a** [comment]
I've logged an upstream issue in vscode for this. https://github.com/Microsoft/vscode/issues/49315

**Comment by stlaz** [comment]
It seems that https://github.com/Microsoft/vscode/issues/34627 is the current upstream issue that needs to be resolved in order for the debugging in symlinked directory to work. I suspect the Go community will be bumping into this the most.

**Comment by stamblerre** [comment]
I've filed a general tracking issue for VS Code feature requests, so I'm going to close this in favor of that issue: https://github.com/golang/vscode-go/issues/48.
