### ISSUE TITLE
When will Refactoring be made available?

### ISSUE THREAD

**Issue by alwindoss** [Microsoft/vscode-go#1328]
Now that with code 1.18 there is refactoring made available for typescript and JavaScript was wondering when it would be available for Go extension.

**Comment by ramya-rao-a** [comment]
As soon as someone in the open source community can spend some time on it and contribute :)
#588 is tracking the "Extract Method" feature request.
PRs are very welcome.

Closing this issue in favor of #588

**Comment by ramya-rao-a** [comment]
The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension has this feature. Please see [Refactoring in VS Code](https://code.visualstudio.com/docs/editor/refactoring) on how you can use the refactor feature.
