### ISSUE TITLE
Find References not working

### ISSUE THREAD

**Issue by jlozano** [Microsoft/vscode-go#1329]
Hi folks, I upgraded to macOS version 10.13.1 and find references stopped working.

I am running VSCode version 1.18.0 and go version go1.9.2.

Any suggestions on how I can help debug this? I do not see any error messages in the VSCode console.

**Comment by ramya-rao-a** [comment]
Can you run `Go: Install/Update Tools` command to ensure all the dependent tools are the latest and are compiled?

**Comment by jlozano** [comment]
@ramya-rao-a Thanks! that seems to have fixed it!

**Comment by ramya-rao-a** [comment]
An upgrade to Mac OS or go itself needs the tools to be re-compiled to work again.

Happy Coding!
