### ISSUE TITLE
Autocomplete does not work for builtins

### ISSUE THREAD

**Issue by deathly809** [Microsoft/vscode-go#133]
Autocomplete does not work (for me) as related to builtin functions and types.  

Expected:

```
1. Type f
2. Box pops up with 2 or more options with float32 and float64 included
```

What happens

```
1. Type f
2. Box pops up with 0 or more options with neither float32 or float64 not included
```

**Comment by lukehoban** [comment]
Yep - we need to run `gocode set propose-builtins true` once on launch to tell gocode to include builtins.

**Comment by rythmkraze** [comment]
@lukehoban Is there a way to set `propose-builtins` to false?

**Comment by ramya-rao-a** [comment]
@rythmkraze There is no way to set it to false today.

What is your scenario where you want the this off?
