### ISSUE TITLE
How can I disable gocode completely  when I use go LanguageServer ?

### ISSUE THREAD

**Issue by douglarek** [Microsoft/vscode-go#1331]
When I set  `"go.useLanguageServer": true`, vscode will open a gocode process; how can I disable it?

**Comment by ramya-rao-a** [comment]
`gocode` is used for the auto-completion feature. It has nothing to do with the language server. Do you want to disable the auto-completion feature itself?

**Comment by douglarek** [comment]
@ramya-rao-a do you mean the language server can not be used for the auto-completion feature,
 so we need `gocode` ? If so, maybe it is my misunderstanding.

**Comment by ramya-rao-a** [comment]
Yes thats right.
The language server provides only a subset of features which are Hover, Definition, Find All References, Signature Help, Go to Symbol in File and Workspace.
