### ISSUE TITLE
Will support std library search when go to symbols in workspace ?

### ISSUE THREAD

**Issue by douglarek** [Microsoft/vscode-go#1332]
Now vscode-go just supports **vendors** search in the `Go to Symbols in Workspace` action; will it support std library search ?

**Comment by ramya-rao-a** [comment]
`Go to symbols in Workspace` by definition is a feature that lets you search for symbols in the current workspace i.e. the folder that you opened VS Code with.

Try the `Go: Browse Packages` command to browse the standard packages and find your symbol or use the `Go To Definition` feature on the symblol
