### ISSUE TITLE
Go to definition not working (since Mac High Sierra update?)

### ISSUE THREAD

**Issue by pierznj** [Microsoft/vscode-go#1338]
I "upgraded" to MacOS High Sierra yesterday (\<gripe\> they always manage to break core stuff in the course of providing more luxury features in the photo app or something \</gripe\>) and since then, 'Go to definition' no longer works in Go files. It might be coincidence, but I got my colleague who is also on High Sierra to try on his machine, and he has the same problem. Always says 'definition not found'.

**Comment by ramya-rao-a** [comment]
Run `Go: Install/Update Tools` to recompile all the dependent Go tools and try again.
An upgrade either to Mac OS or Go itself requires recompiling of the tools.

**Comment by pierznj** [comment]
Thank you - that makes sense when I think about it! I actually found this suggestion in another thread yesterday and it did the trick. I am noticing that the validation of Go code is much slower now than before - used to get error indicators almost right away, now there's a pause of several seconds. Closing this issue, but wonder if you have a suggestion for that?

**Comment by ramya-rao-a** [comment]
There are some perf improvements I am pusing for the next update. You can try it out and let me know if it helps. I havent released an update yet, but you can try out the improvements by doing the below:

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` and reload VS Code

**Comment by pierznj** [comment]
I did as you suggest, but it was still very slow. However I noticed on the output that my linter (gometalinter) was not found in my PATH. I changed to standard linter and it's quick again. Thanks so much for your help!

**Comment by diogogmt** [comment]
I'm having a similar problem, after upgrading to High Sierra I can't go to the definition of libs in the vendor/ dir of my project.

I've tried the settings:
```
 "go.docsTool": "gogetdoc",
 "go.useLanguageServer": true
```

But also didn't work.

**Comment by ramya-rao-a** [comment]
@diogogmt Please see https://github.com/Microsoft/vscode-go/issues/1338#issuecomment-345108242
