### ISSUE TITLE
Can't debug test: "could not launch process: stub exited while waiting for connection: exit status 0"

### ISSUE THREAD

**Issue by jpap** [Microsoft/vscode-go#1339]
I'm on macOS and have [followed the instructions](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code) for setting up my `launch.json` to debug my tests.

My launch configuration is:
```'
...
    {
      "name": "Launch Tests",
      "type": "go",
      "request": "launch",
      "mode": "test",
      "remotePath": "",
      "port": 2346,
      "host": "127.0.0.1",
      "program": "${workspaceRoot}",
      "cwd": "${workspaceRoot}",
      "env": {
        "GOPATH": "${workspaceRoot}/.gopath~:${workspaceRoot}/vendor",
        "LOGGO": "<root>=DEBUG"
      },
      "args": [
        "-test.run", "MyTest"
      ],
      "showLog": true,
      "trace": "verbose"
    },
...
```

When I run this, I see the following in the debug console:
```
Verbose logs are written to:
/var/folders/wc/jkc42h512cv0n1tdp51yjp7w0000gq/T/vscode-go-debug.txt
21:50:30, 2017-11-14
InitializeRequest
InitializeResponse
Using GOPATH: /Users/jpap/PROJECT/.gopath~:/Users/jpap/PROJECT/vendor
Running: /usr/local/bin/dlv test --headless=true --listen=127.0.0.1:2346 --log=true --wd=/Users/jpap/PROJECT -- -test.run MyTest
2017/11/14 21:50:31 server.go:73: Using API v1
2017/11/14 21:50:31 debugger.go:96: launching process with args: [./debug.test -test.run MyTest]
could not launch process: stub exited while waiting for connection: exit status 0
Process exiting with code: 1
Delve is closed
DisconnectRequest
```

And in the verbose log:
```
Verbose logs are written to:
/var/folders/wc/jkc42h512cv0n1tdp51yjp7w0000gq/T/vscode-go-debug.txt
21:50:30, 2017-11-14
InitializeRequest
InitializeResponse
Using GOPATH: /Users/jpap/PROJECT/.gopath~:/Users/jpap/PROJECT/vendor
Running: /usr/local/bin/dlv test --headless=true --listen=127.0.0.1:2346 --log=true --wd=/Users/jpap/PROJECT -- -test.run MyTest
[Error] Process exiting with code: 1
Delve is closed
DisconnectRequest
DisconnectResponse
```

In the system log, I see:
```
default	21:50:31.729793 -0800	debugserver	debugserver will use os_log for internal logging.
default	21:50:31.730064 -0800	debugserver	debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-900.0.57
 for x86_64.
default	21:50:31.730606 -0800	debugserver	1 +0.000000 sec [1384a/0307]: RNBRunLoopLaunchInferior DNBProcessLaunch() returned error: 'No such file or directory (./debug.test)'
default	21:50:31.730649 -0800	debugserver	error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: No such file or directory (./debug.test)
default	21:50:31.730668 -0800	debugserver	Exiting.
```

When I try and run delve manually on the command line, I can run and debug the test OK.  I'd much prefer to be doing this graphically in the VSC debugger though! :-)

I've read through #318, but still can't get it to work... any help appreciated.

**Comment by jpap** [comment]
Further observations:

* I can remove the GOPATH `env` item from `launch.json` and the GOPATH environment appears to be the same (taken from the workspace GOPATH?)  Why is this? Is this a bug?
* When I remove the `cwd` item from `launch.json` and set the `program` to point into the folder where the test is, then the debugger launches and runs the test.  Unfortunately all of my breakpoints are marked as "unverified" (greyed out) and do not trigger.

The new config is:

```
...
    {
      "name": "Launch Tests",
      "type": "go",
      "request": "launch",
      "mode": "test",
      "remotePath": "",
      "port": 2346,
      "host": "127.0.0.1",
      "program": "${workspaceRoot}/lib/package",
      "cwd": "${workspaceRoot}",
      "env": {
        "LOGGO": "<root>=DEBUG"
      },
      "args": [
        "-test.run", "MyTest"
      ],
      "showLog": true,
      "trace": "verbose"
    },
...
```
where I am wanting to debug tests in the package `$PROJ/lib/package`.

**Comment by jpap** [comment]
I have hit "remove all breakpoints" in the debug pane, reset the breakpoint by clicking it in a source editor, and now the breakpoint is hit!

Is this a bug in the VSC debugger? (Not the debug adapter?)

**Comment by jpap** [comment]
My final configuration is:
```
...
    {
      "name": "Launch Tests",
      "type": "go",
      "request": "launch",
      "mode": "test",
      "remotePath": "",
      "port": 2346,
      "host": "127.0.0.1",
      "program": "${fileDirname}",
      "env": {
        "LOGGO": "<root>=DEBUG"
      },
      "args": [
        "-test.v"
      ]
    },
...
```

So now I can just hit F5 with any test file open and it runs all the tests in that folder; breakpoints included.  The `LOGGO` environment variable is there for my logging package; it doesn't need to be there in general.

**Comment by jpap** [comment]
@ramya-rao-a, before closing this thread, I'd love your view on some of the problems encountered above:
* It appears setting the `cwd` breaks the debugger.
* I had to clear the breakpoints and resetting them before they started working.

Separately, it would be nice to document in the README:
*  the `-test.v` argument
* The use of `${fileDirname}` for running all tests in the opened file's directory
* The GOPATH is inherited from the VSC environment, so there's no need to set it again in the launch configuration

**Comment by jpap** [comment]
Hmm -- this is weird: I am now trying to debug a test in a different package using the latest configuration above; but the breakpoints won't trigger.  I have tried reloading the VSC window, as well as clearing all breakpoints and setting them up again, but they remain "unverified".  Any ideas?

**Comment by ramya-rao-a** [comment]
Hey @jpap,

First off, thanks for your patience. Was a little busy at work past 2 days and so didnt get to respond sooner.

Secondly, congrats! That's some great investigation and am glad you got yourself unblocked.

Now coming to your points:

**About cwd**
- `cwd` from the debug config is passed directly to dlv in the `--wd` argument. We do nothing else with it.
- The path provided in the `program` from the debug config is used as cwd to run dlv
- In your case, I believe the issue was that the `program` attribute in the debug config was not pointing to the location of the package being debugged and not cwd.

**About the need to reset breakpoints**
Can you provide clear repro steps for this with simple sample code so that I can get a repro? Then I can look into where the issue is.

**About GOPATH**
- From version 1.17 onwards, VS Code now provides a way for the extensions to talk to the debug adapters. I was able to use this feature to pass along the GOPATH used by the Go extension to the debug adapter. This was not possible previously and so the README talks about the need to pass GOPATH in the `env` of the debug config. 
- This happened in the last update to the Go extension that I released last week, but I missed updating the docs, my bad. 

**Documentation**
- The GOPATH related note has been updated
- The note on use of `${fileDirname}` is also added
- Can you elaborate on the `-test.v` argument?

**Comment by jpap** [comment]
> Can you provide clear repro steps for this with simple sample code so that I can get a repro? Then I can look into where the issue is.

I've not seen this issue since; it happened when I was using a HEAD build of delve but have since moved to the latest release candidate `1.0.0-rc.2`.  I think we can assume it was delve, and not your extension. :)

> Can you elaborate on the -test.v argument?

Using the `-test.v` argument tells the Golang testing framework to output verbose reports, which is helpful during debugging of a test.  It might be helpful to mention this in the README?

Separately I guess the same could be said of the "run package tests" clickable link in a test source file; how can we selectively enable that? (It's the same as passing `-v` to `go test`.)

**Comment by ramya-rao-a** [comment]
You can use `go.testFlags` setting to pass the flags you want to use when running the tests. This will be used by all the test commands from the command pallet as well as the codelens "run package tests" and "run test"

I have added the note on `-test.v` in the wiki.

Thanks and Happy Coding!
