### ISSUE TITLE
Run go tools from docker

### ISSUE THREAD

**Issue by diegobernardes** [microsoft/vscode-go#1342]
Go tools rocks, we all know about it, but there is a problem that is happening very often with me. The linters running at the CI and the ones running on my machine are different because they were installed in different moments.

To solve the CI problem, did a docker image with the linter already installed, so, i never get surprises about the linter rules changing. But, the problem on development machine remains, sometimes the linter warn but the CI don't and the opposite too, 
which is very frustrating.

Would be great if we could add any kind of command on the configuration. The vscode-go, could recognize the default ones (gometalinter, golint and megacheck), but if the user put another one, it could respect.

```json
{
  "go.lintTool": "docker start --name linter -v ${workspaceRoot}/project"
}
```

Or something like this:
```json
{
  "go.lintPlatform": "docker",
  "go.lintTool": "gometalinter",
}
```

With `go.lintPlatform` the vscode-go could call the docker passing the gometalinter as a param.

**Comment by ramya-rao-a** [comment]
If we did provide a solution to run tools from a container, then a general solution is needed. Not just for linter. This is a major undertaking.

I'd love to help put if anyone wants to take this up.

**Comment by asasmoyo** [comment]
Hello, I would like to take this :)
Do you have idea how the configurations should look like if we want to use Docker?

**Comment by ramya-rao-a** [comment]
@asasmoyo 
Last year, we gave this a try and you can see our work at https://github.com/Microsoft/vscode-go/compare/master...ramya-rao-a:docker

You can start by looking at that code and see what approach was taken and if you are thinking along the same lines or something different.

**Comment by asasmoyo** [comment]
Great! Thanks @ramya-rao-a, I'll take a look at it

**Comment by MOZGIII** [comment]
I would love to run my tools off on a remote server via ssh. For my use case I'll share the file system via sshfs or nfs (either from the "workstation" to the "tools runner", or the other way - from the "tools runner" to the "workstation").
My end goal is to only have the editor and other relatively lightweight stuff runing off of my laptop (that runs from battarey, aka "workstation") and do all the heavy lifting on the power cord connected server ("tools runner"). Turns out linters heavily load CPU, who would knew.

**Comment by ramya-rao-a** [comment]
@diegobernardes, @asasmoyo The original problem here is related to not able to lock down on the version of the go tools being used by the extension. My hope is that as the Go ecosystem moves to using modules, we should be able to target particular versions.

@MOZGIII Have you tried any of the vscde-remote solutions? See https://code.visualstudio.com/docs/remote/remote-overview

I will be using #1412 to track the work required to target the tools such that the version can be locked.
Closing this issue as I don't have the resources to support running of Go tools from docker which comes with its own set of big complexities not only to implement, but also maintain.

Thanks for reporting and Happy Coding!
