### ISSUE TITLE
Toggle test coverage working incorrectly with split editor

### ISSUE THREAD

**Issue by lggomez** [Microsoft/vscode-go#1343]
Hi, and thanks for this great extension beforehand. I come here to report the following issue:

- VSCode Version: 1.18.0
- Extension Version: 0.6.67

**Steps to Reproduce:**

1. Open a go file and its test file in a single editor window
2. Click the "run package test" option in the active editor. Alternatively, run the "Go: Toggle Test Coverage In Current Package" command. Either of these will highlight the test coverage for the source file in the current editor
3. Split the editor with the highlighted source
4. Run again the "Go: Toggle Test Coverage In Current Package" command

**Expected result:** The code coverage highlighting should be toggled for both editors
**Actual result:** The code coverage highlighting only toggles in the first (leftmost) editor

Reloading the window will remove the highlighting for all editors

**Comment by ramya-rao-a** [comment]
You are welcome @leaxoy and thanks for reporting this issue.
The fix will be out in the next update

**Comment by ramya-rao-a** [comment]
The fix is out in the latest update to the Go extension (0.6.69)
