### ISSUE TITLE
Delve: Allow custom config file

### ISSUE THREAD

**Issue by Eun** [Microsoft/vscode-go#1347]
Delve allows us to use custom settings using the `--config` argument.

It would be great to specify the file using the `User Settings` in vscode.

---

An additonal / enhanced task would be to autogenerate the file and pass it to delve, or pass the config values in some other way.

**Comment by ramya-rao-a** [comment]
Can you provide any references or docs for the `--config` argument?

**Comment by Eun** [comment]
After digging into Delves source code I found out that the docs are outdated and delve is (currenlty) ignoring the `--config` flag. However there is a config file that will be loaded.

It is in the `.dlv` folder in your home folder.

**Comment by ramya-rao-a** [comment]
Thanks for figuring that out and getting back. Happy Coding!
