### ISSUE TITLE
VSCode going into not responding mode after the latest update

### ISSUE THREAD

**Issue by rambhavaraju** [Microsoft/vscode-go#1348]
Hi,

I have updated my vscode to 1.18 today and after the update my GO project is getting frozen up. I have had opened other language projects and there it seems to be running alrite.
When i looked at command palette and looked for the error i found this.
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 Cannot read property 'forEach' of undefined: TypeError: Cannot read property 'forEach' of undefined
	at Promise.all.then (C:\Users\ram.bhavaraju\.vscode\extensions\lukehoban.go-0.6.67\out\src\goPackages.js:121:13)
	at <anonymous>

I tried to uninstall and reinstall the extension but no luck.

Could you @ramya-rao-a help me out in this regards

**Comment by rambhavaraju** [comment]
![image](https://user-images.githubusercontent.com/6705212/32893839-ee4d99ca-cb00-11e7-9715-de5b6be4eedd.png)
Here is the windows not responding message.
I'm running windows 10 pro x64 version.

**Comment by ramya-rao-a** [comment]
The fix is in master, but I havent released an update yet. Until I do, you do the following:

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` and reload VS Code
