### ISSUE TITLE
The cursor keeps jumping to the bottom

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1349]
_From @matthewfcarlson on November 16, 2017 6:27_

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.67
csharp|ms-|1.13.1
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.22
java|red|0.14.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. Edit a go document
2. Stop typing for a second
3. Cursor focus goes to the end of the document

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#38479_

**Comment by ramya-rao-a** [comment]
_From @matthewfcarlson on November 16, 2017 7:36_

Looks like it's a result of go-code-check running.

**Comment by ramya-rao-a** [comment]
_From @Ripper1992 on November 16, 2017 12:48_

Same thing is happening with me.

Steps to reproduce the error:

1 - Type some code.
2 - Hit "ctrl +s" to save the file.
3 - Hit arrow up or down.
4 - Cursor focus at the bottom of the file.

**Comment by ramya-rao-a** [comment]
@matthewfcarlson I believe this is due to the formatting that runs on save. The edits that get applied end up moving the cursor. Let's track this in #1346

@matthewfcarlson , @Ripper1992, I can repro the case when the cursor moves to the next line, but not the case when the cursor moving to the bottom of the file.

Can either of you provide a small sample code with repro steps for when you see the cursor going to the end of the file?

Please provide the details in #1346

**Comment by ramya-rao-a** [comment]
I have pushed the fix for the issue that I see i.e cursor jumping to the next line.

Can either of you test it and see if it solves your case as well? All you have to do is
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` and reload VS Code

**Comment by matthewfcarlson** [comment]
I can confirm that turning off the go extension fixes the issue. Let me try this newest package.

**Comment by ramya-rao-a** [comment]
Scratch that.

I can repro the case when the cursor jumps to the last line.
It is when the changes due to formatting spans multiple lines till the end of the document.

The root cause is due to changes in the core api. I'll dig around a little more and get back here.

**Comment by Ripper1992** [comment]
I have the following extensions installed.

- Debugger for Chrome
- Git Histpry (git log)
- Git Merger
- IntelliSense for CSS class names
- JS-CSS-HTML Formatter
- Material Theme
- npm
- Path Intellisense
- Project Manager
- Settings Sync

After disabling all extensions, I verified that this resolved the issue. I'll try one by one to see which one might be causing the problem.

**Comment by leonardoResendeLima** [comment]
Yeah, foundIt. It was the "JS-CSS-HTML Formatter", last change (0.2.3) of this project was on 31 Mar 2017

**Comment by ramya-rao-a** [comment]
The formatting feature of the Go extension also does the same. I am working on a fix

**Comment by ramya-rao-a** [comment]
All,

You can follow the steps in https://github.com/Microsoft/vscode-go/issues/1346#issuecomment-349893523 to get the fix for this issue before the next udpate

**Comment by ramya-rao-a** [comment]
The latest update to the Go extension (0.6.70) has the fix for this issue.
