### ISSUE TITLE
Support for Type Aliases

### ISSUE THREAD

**Issue by dc0d** [Microsoft/vscode-go#1350]
Currently VSCode for Go, does not support type aliases. It would be nice to support type info and docs for them. And the mouse over shows an empty square.

**Comment by ramya-rao-a** [comment]
Can you provide sample code that I can use to repro?

**Comment by dc0d** [comment]
For example this [repo](https://github.com/dc0d/gsamples) contains Go code that uses type aliases.

**Comment by ramya-rao-a** [comment]
Setting `"go.docsTool": "gogetdoc"` seems to work.
The default tool we use to find definitions is `godef` which is supposed to return the location and the signature of the definition which it fails to do in case of type alias. But `gogetdoc` works.

Try running `godef` on a type alias and compare it with a normal function or type, you will see the difference in the output. Can you log an issue in the repo for `godef` for this please?
