### ISSUE TITLE
Codefolding of a function with a label in it fold from `func` to label

### ISSUE THREAD

**Issue by NobbZ** [Microsoft/vscode-go#1351]
When I try to fold the following function:

```go
func foo() {
  var a
labelLoop:
  for {
    break labelLoop
  }
}
```

It is folded to:

```go
func foo() {
labelLoop:
  for {
    break labelLoop
  }
}
```

I can then fold again at the label resulting in

```go
func foo() {
labelLoop:
}
```

But I'd expect to have the following when folding at the `func` initially:

```go
func foo() {
}
```

**Comment by ramya-rao-a** [comment]
@NobbZ Sorry for the delay in response.

The folding in VS Code is language agnostic and depends on indentation only
In your example, since the line with `labelLoop:` is outdented with respect to the previous line, it didn't get folded

**Comment by NobbZ** [comment]
Do you know about an upstream issue that addresses this? If so I'd like to track it.

**Comment by ramya-rao-a** [comment]
You can follow https://github.com/Microsoft/vscode/issues/3422

**Comment by ramya-rao-a** [comment]
This no longer is a problem in the latest version of VS Code
