### ISSUE TITLE
Cannot start delve debugging when files in $GOPATH/src*

### ISSUE THREAD

**Issue by finallybye** [Microsoft/vscode-go#1352]
- OS: win7 x64
- vscode: 1.18.1 win32-x64
- vscode-go: 0.6.67
- delve: 1.0.0-rc.1
- golang: 1.9.2 windows/amd64
- GOPATH: D:\WorkSpace\Develop\gopath_x64
- file location: D:\WorkSpace\Develop\gopath_x64\src01\github.com\foo\bar\main.go (attention: src01, not 'src\01')

The error information shown on debug console when I start debugging(F5):
```
can't load package: package 01/github.com/foo/bar: cannot find package "01/github.com/foo/bar" in any of:
	D:\Program\go\src\01\github.com\foo\bar (from $GOROOT)
	D:\WorkSpace\Develop\gopath_x64\src\01\github.com\foo\bar (from $GOPATH)
exit status 1
Process exiting with code: 1
```

After some tests, I find error will occur when the name of a directory is like 'src*' rather than 'src', and its parent directory is $GOPATH.

In addition, using `dlv debug main.go` is going well.

**Comment by ramya-rao-a** [comment]
- Run the command `Go: Current GOPATH`. Does this match with what's expected?
- Add `"trace": "verbose"` to your debug configuration and then start debugging. This will add some logs to the debug console. There should be a line there saying `Using GOPATH:`. Does this match with the expected GOPATH?

**Comment by ramya-rao-a** [comment]
@finallybye Closing this issue as we havent heard back from you with any answers for https://github.com/Microsoft/vscode-go/issues/1352#issuecomment-345493623
