### ISSUE TITLE
go.buildTags only works properly with a single tag

### ISSUE THREAD

**Issue by mfpierre** [Microsoft/vscode-go#1355]
## Issue

I've been experiencing issues with the `go.buildTags` setting. It seems to work fine only when you have a single tag.

When using multiple tags (space-separated) the tools are not working properly anymore on tagged files (as if no tags were applied).

## How to reproduce
```go
// +build randomtag

package main

import (
	"fmt"
)

func main() {
	fmt.Println("hello")
	foobar
}
```
with `"go.buildTags": "randomtag"` reporting the error correctly `undefined: foobar` 

with `"go.buildTags": "randomtag othertag"` -> `build constraints exclude all Go files`

**Comment by ramya-rao-a** [comment]
@mfpierre I have pushed a fix for this, can you help in testing it out? All you have to do is
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` and reload vs code

Do try out features like rename, find references etc and see if all the language features work with multiple build tags

And thanks for reporting this.

**Comment by mfpierre** [comment]
@ramya-rao-a thanks for the fix, however I'm not able to install the provided extension

```code --install-extension Go-latest.vsix
Error: end of central directory record signature not found
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/yauzl/index.js:183:14
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/yauzl/index.js:618:5
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)
```

**Comment by ramya-rao-a** [comment]
You must be on ubuntu, for some reason direct download doesnt work.
Can you clone this repo and then use the vsix file from the repo?

**Comment by mfpierre** [comment]
@ramya-rao-a I'm on OSX but the install from the cloned repo worked, from what I've tested so fare seems to be fixed 👍

**Comment by ramya-rao-a** [comment]
great, did you try other features like rename, find all references etc? The Go tools that back these features also take the build tags. Also give the new commands `Go: Build Current Package`, `Go: Install Current Package` a try. These are not released yet, but since you are using the code from master you can use them

**Comment by ramya-rao-a** [comment]
The fix is out in the latest update to the Go extension (0.6.69)
