### ISSUE TITLE
Cannot assert types in debug console

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1357]
When I try to assert a type in the debug console, for example `f.users.(client)`, I get this message:

```
Unable to eval expression: "no type entry found, use 'types' for a list of valid types"
Failed to eval expression:  {
 "symbol": "f.users.(client)",
 "scope": {
  "goroutineID": 19,
  "frame": 0
 }
}
```

Entering `types` also gives an error:

```
Unable to eval expression: "could not find symbol value for types"
Failed to eval expression:  {
 "symbol": "types",
 "scope": {
  "goroutineID": 19,
  "frame": 0
 }
}
```

---

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
sort-lines|Tyr|1.3.0
githistory|don|0.2.3
markdown-table-formatter|jos|0.2.3
Go|luk|0.6.67
prettify-json|moh|0.0.3
azure-account|ms-|0.2.2
rewrap|stk|1.5.3
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

**Comment by ramya-rao-a** [comment]
`"no type entry found, use 'types' for a list of valid types` That's coming from delve.
Can you run delve from the command line, and try doing the same there?

**Comment by willfaught** [comment]
It worked there.

**Comment by ramya-rao-a** [comment]
Can you share the steps? I need to know the commands used

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
