### ISSUE TITLE
Debug info in variable and debug console panes is different

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1358]
See the screenshot:

![screen shot 2017-11-21 at 3 13 36 pm](https://user-images.githubusercontent.com/63830/33101841-e5586314-cece-11e7-97af-5015e382d676.png)

In the variables pane, c.client.ctx only shows one field, and it's not even a real field, I'm not sure what that is. In the debug console pane, I can drill down into c.client.ctx.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
sort-lines|Tyr|1.3.0
githistory|don|0.2.3
markdown-table-formatter|jos|0.2.3
Go|luk|0.6.67
prettify-json|moh|0.0.3
azure-account|ms-|0.2.2
rewrap|stk|1.5.3
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

**Comment by ramya-rao-a** [comment]
The data shown in the variables pane is the data returned by delve.

I dont have the code to repro this issue, but I can help you debug the Go extension to figure out what's happening.

If you are up for it, follow the steps at [Building and Debugging Go extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension). This will set up the dev env for the Go extension.

Then debug the debugger for the Go extension by following the [Debug Adapter README](https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter)

In the third instance of VS Code (the one where you opened `vscode-go/src/debugAdapter`), add a breakpoint at https://github.com/Microsoft/vscode-go/blob/0.6.69/src/debugAdapter/goDebug.ts#L716. That's where the variables are fetched from the response from delve.

That can explain why you see the extra things.

**Comment by ramya-rao-a** [comment]
@willfaught Since we didnt hear back from you and we don't have a sample code that we can use to replicate this problem, I am closing this issue.

If you do see this again, please log a new issue with a small code sample that we can use.

Happy Coding!

**Comment by willfaught** [comment]
@ramya-rao-a It looks like this is fixed now. Thanks!

**Comment by ramya-rao-a** [comment]
Thanks for getting back to us with the confirmation @willfaught, and Happy Coding!
