### ISSUE TITLE
GoDocumentSymbolProvider provide more context?

### ISSUE THREAD

**Issue by newhook** [Microsoft/vscode-go#136]
Perhaps we should provide more context for the symbols?

For example;
```
func (t* type1) foo () {
}

func (t* type2) foo () {
}
```
These both present foo in the list of symbols. Perhaps it should be test1.foo, test2.foo?

**Comment by lukehoban** [comment]
I think this is the same as https://github.com/Microsoft/vscode-go/issues/18?
