### ISSUE TITLE
Import statement is disappearing

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode-go#1361]
macOS 10.13.1 High Sierra
VSCode 1.19.0 Insider

Hello, I'm trying to add an import statement to the start of a .go file. The import statement is:
`"github.com/carlca/bigdata/company"` In the corresponding folder I have 1 file named `company.go` which contains a larger version of this code:

```
package company

// Company struct
type Company struct {
	// Details
	CompanyName   string `bson:"companyname,omitempty"`   // 160
	CompanyNumber string `bson:"companynumber,omitempty"` // 8
	Careof        string `bson:"careof,omitempty"`        // 100
	POBox         string `bson:"pobox,omitempty"`         // 10
	AddressLine1  string `bson:"addressline1,omitempty"`  // (HouseNumber and Street) 300
	AddressLine2  string `bson:"addressline2,omitempty"`  // (area) 300
	PostTown      string `bson:"posttown,omitempty"`      // 50
	County        string `bson:"county,omitempty"`        // (region) 50
	Country       string `bson:"country,omitempty"`       // 50
	PostCode      string `bson:"postcode,omitempty"`      // 10
}

```
The problem is that every time I save the file, Go Import is kicking in and is deleting the `"github.com/carlca/bigdata/company"` line. It's very frustrating! I am prepared to accept that I am doing something daft, but I cannot figure out what. Can anyone help? Thanks!

**Comment by carlca** [comment]
I found the problem. Once I set the import line to `c "github.com/carlca/bigdata/company"` and used that prefix in the code, all was well.

**Comment by ramya-rao-a** [comment]
@carlca `goimports` will remove unused imports and that's what you see.
