### ISSUE TITLE
Ideas to add struct tag for json/xml?

### ISSUE THREAD

**Issue by OuSatoru** [Microsoft/vscode-go#1362]
Like Intellij go plugin, when type `j tab, it adds json tag for the variable with CamelCase to underscore

**Comment by ramya-rao-a** [comment]
We have the commands `Go: Add Tags to Struct Fields` that does something similar. It uses the setting `go.addTags`.
See https://github.com/Microsoft/vscode-go/wiki/Release-Notes#editing-improvements
