### ISSUE TITLE
"Test fucntion at cursor" Runs all tests in the package

### ISSUE THREAD

**Issue by silentred** [Microsoft/vscode-go#1363]
plugin version: 0.6.67
vscode version: 1.18.1

It seems all "Go: Test ..." commands run all the tests in package

**Comment by ramya-rao-a** [comment]
There are multiple `Go: Test` commands. Which ones are running all the tests in the package for you?

**Comment by ramya-rao-a** [comment]
@silentred  Closing this issue as we havent heard back from you in a while with details on the issue
