### ISSUE TITLE
Code hint error when using string format in backquote

### ISSUE THREAD

**Issue by tannineo** [Microsoft/vscode-go#1364]
I have a string in `` for `fmt.Sprintf`, like this:  
```go
UGLY_UI = `
* * * * * * * * * * * * * * * * * * * * * * * *
    Score = %d
    Turns = %d
* * * * * * * * * * * * * * * * * * * * * * * *
    + - - - - + - - - - + - - - - + - - - - +
    |         |         |         |         |
    | %7d | %7d | %7d | %7d |
    |         |         |         |         |
    + - - - - + - - - - + - - - - + - - - - +
    |         |         |         |         |
    | %7d | %7d | %7d | %7d |
    |         |         |         |         |
    + - - - - + - - - - + - - - - + - - - - +
    |         |         |         |         |
    | %7d | %7d | %7d | %7d |
    |         |         |         |         |
    + - - - - + - - - - + - - - - + - - - - +
    |         |         |         |         |
    | %7d | %7d | %7d | %7d |
    |         |         |         |         |
    + - - - - + - - - - + - - - - + - - - - +
`
```
There're **18** items in total, and the print code like this:  
```
func (g *Grid44) Print() string {
	return fmt.Sprintf(UGLY_UI, g.Score(), g.TurnNumber,
		g.Data[0][0], g.Data[0][1], g.Data[0][2], g.Data[0][3],
		g.Data[1][0], g.Data[1][1], g.Data[1][2], g.Data[1][3],
		g.Data[2][0], g.Data[2][1], g.Data[2][2], g.Data[2][3],
		g.Data[3][0], g.Data[3][1], g.Data[3][2], g.Data[3][3])
}
```

When I miss some items in `fmt.Sprintf()`, the hint shows:
![image](https://user-images.githubusercontent.com/33346345/33200801-16a5927a-d131-11e7-80e2-02c311a248e0.png)
If we add or remove one, the count changes:  
![image](https://user-images.githubusercontent.com/33346345/33200853-464d220e-d131-11e7-9cbd-978da77f8e32.png)

It seems like only the first flag missing item can be detected?

**Comment by ramya-rao-a** [comment]
I am not able to repro this.
Can you open the output pane and select "Go" from the drop down on the top right corner of the pane?
The results of build/lint/vet are shown there.
This is either the result of linting or the vet process.

Either way, the Go plugin has no control over the errors/warnings coming from he build/lint/vet process. It just runs these tools and displays the results in the editor.

Look at the output pane to see if lint or vet caused the issue and then log an issue in the appropriate repo.

**Comment by tannineo** [comment]
The output pane has the same info like the screenshot:
```
Finished running tool: /usr/local/bin/go tool vet .
/Users/carychan/Code/go/src/github.com/tannineo/2048-cli/gameplate/grid44.go:192: missing argument for Sprintf("%7d"): format reads arg 10, have only 9 args
```
So it's something wrong with vet...
Anyway thank you!

**Comment by tannineo** [comment]
```shell
$ go version
go version go1.9.2 darwin/amd64
```
