### ISSUE TITLE
Struct and bson tags alignment issues

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode-go#1366]
When I save my go code, my structs are being aligned like this:
![screen shot 2017-11-24 at 15 18 20](https://user-images.githubusercontent.com/260612/33216230-e24b034e-d12a-11e7-9fec-f6d960a262f7.png)

I would prefer the automatic alignment of the `string bson` info to carry on over the comments, like so:
![screen shot 2017-11-24 at 15 23 04](https://user-images.githubusercontent.com/260612/33216365-75d4cba4-d12b-11e7-92a0-98084a49e600.png)

I'm not certain which VSCode extension is controlling this. Any ideas, anyone? Thanks!

**Comment by ramya-rao-a** [comment]
That's done by the formatting tool we use. You can choose to use `goreturns`, `goimports` or `gofmt` by changing the `go.formatTool` setting. You can also pass flags to these tools via the `go.formatFlags` setting.

Other than these customizations, rest of the details of formatting is out of scope of VS Code. You can log an issue in the repos of any of the above 3 tools.

**Comment by carlca** [comment]
Thanks, Ramya. Here's a controversial question: what's the difference between `goreturns`, `goimports` and `gofmt', and, perhaps even more controversial: which one is better? You don't have to answer the second question, but if there was a summarised guide that answers the first question, that would be great!

**Comment by carlca** [comment]
I found the http://dominik.honnef.co/posts/2014/12/go-tools/ page that you referenced in #418. It looks like `goreturns` is the superset of the others.

**Comment by ramya-rao-a** [comment]
That's correct
