### ISSUE TITLE
Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode-go#1367]
- VSCode Version: Code - Insiders 1.19.0-insider (0c60476e5167d4bdcf01cc48558b2e1faf0edae1, 2017-11-23T05:14:03.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
gotemplate|cas|0.1.1
vscode-markdownlint|Dav|0.11.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.23
markdown-table-formatter|jos|0.2.3
Lua|key|0.0.9
Go|luk|0.6.67
debugger-for-chrome|msj|3.5.0
tmlanguage|Tog|0.8.4
vscode-import-cost|wix|2.5.1

---

Steps to Reproduce:

Sorry, just as always it appears in DevTools while doing other programming stuff.

Full Error:

`
shell.ts:467 Cannot read property 'concat' of undefined: TypeError: Cannot read property 'concat' of undefined
	at Promise.all.then.res (C:\Users\maxsc\.vscode-insiders\extensions\lukehoban.go-0.6.67\out\src\goRunTestCodelens.js:41:26)
	at <anonymous>
`

I think it's this promise:

https://github.com/Microsoft/vscode-go/blob/ef53221368e77f43cb7512c1d2f14f784c25892a/src/goRunTestCodelens.ts#L38-L43

**Comment by ramya-rao-a** [comment]
Thanks for reporting @maxibanki, that promise was indeed the issue.
I have pushed in a fix. 
Next time, feel free to send a PR :)

Happy Coding!
