### ISSUE TITLE
Problem activating Signature Help

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode-go#1371]
macOS 10.13.1 High Sierra
VSCode Insiders 1.19.0

Hello, I've just tried to install the `Signature Help` feature, so I've added:
```
  "go.useLanguageServer": true,
  "go.docsTool": "gogetdoc",

```
and I've run `go get -v github.com/sourcegraph/go-langserver` from the command line, and restarted VSCode. What do I have to do to activate `Signature Help`? I thought that just typing the `func` name followed by brackets would be sufficient.

**Comment by carlca** [comment]
The full list of relevant settings is now:
```
  "go.formatTool": "goreturns",
  "go.useLanguageServer": true,
  "go.docsTool": "gogetdoc",

```
Still no `Signature Help`! TBH, I hadn't realised that I was missing the feature, then I saw it described and saw the lovely screenshots. Now I'm missing it like crazy!!

**Comment by carlca** [comment]
`⇧⌘Space` does not work, either.

**Comment by ramya-rao-a** [comment]
When you hover on the function name are you able to see the details including the function signature?
Can you provide a code sample where I can repro this?
Also do try on a simple program, say `fmt.Println(`. Does that work?

**Comment by carlca** [comment]
Thanks for the speedy reply Ramya! What hours do you work? I thought you were based in the US...
> When you hover on the function name are you able to see the details including the function signature?
No I am not.

> Can you provide a code sample where I can repro this?
Yeah! Do a `go get github.com/carlca/bigdata` (Don't worry - there's metadata but NO actual bigdata!) , then go into the file I'm currently working on `cd carlca/bigdata/sqlorm` and open `sqlorm.go`. That file is displaying all the symptoms described.

> Also do try on a simple program, say fmt.Println(. Does that work?
Nothing. Nada. Zilch. You get the idea!

Thanks in advance,
Car

**Comment by carlca** [comment]
Oops, tell a lie! I do get the hover help when I hover over `fmt.Println` but I'm not getting the individual parameter help, and, as I mentioned, `⇧⌘Space` does not work, either. 

When I hover over `schema.addColumn` I don't see any help displayed at all.

I know there was an issue between built-in functions as opposed to external functions, but I thought this had been fixed.

**Comment by carlca** [comment]
I've just tried the standard version of VSCode and there the Signature Help works perfectly. I'll investigate the config files...

**Comment by carlca** [comment]
Weird. It turns out that it was the line `"go.useLanguageServer": true,` that was causing the problem. It raises the question, what possible benefit could ever be gained from including that line?

**Comment by carlca** [comment]
Now that I have my Signature Help working, of course now I want to tweak it! How do I a) Change the background color of the Signature Help hover block, and b) Get VSCode  to pick up any doc comments I may have written for the func in question? Thanks!

**Comment by ramya-rao-a** [comment]
The language server feature is an experimental one. If you want to checkout why that wasn't working, log an issue at http://github.com/sourcegraph/go-langserver

I am able to see the signature help for `fmt.Println` in both stable and insiders build of vscode
Try setting `go.docsTool` to `gogetdoc` and try the "Go to definition", hover and signature help features.

VS Code doesn't allow tweaking the UI elements. You can change the theme and that will apply color changes to all elements

**Comment by carlca** [comment]
I spoke too soon. I have the Signature Help working in as much as hovering over the func call gives me access to the full parameter list, but the Trigger Parameter Hints keystroke [⇧⌘Space] still does not work in Insiders but it does work in Stable. The Preferences -> Keyboard Shortcuts config entry appears to be identical in each version of VSCode.

**Comment by ramya-rao-a** [comment]
What version of VS Code (stable) are you using?
Do you see the parameter hints the first time you type `(` after the function name?

**Comment by carlca** [comment]
I'm using version 1.18.1 of VSCode (stable) and 1.19.0 of VSCode (insiders)
Signature Help is working in VSCode (stable) but the Trigger Parameter Hints keystroke [⇧⌘Space] does not work in VSCode (insiders).

No strike that - I've just tested it again and Insiders and Stable both appear to be working correctly now. I don't understand what was happening before but I'll take it!

**Comment by ramya-rao-a** [comment]
:) Alright, then I'll close this issue.
