### ISSUE TITLE
using golinter making my system memory go nuts

### ISSUE THREAD

**Issue by jeyanthimuthuram** [Microsoft/vscode-go#1373]
**My Vscode config** 
```
{
    "go.gopath": "/home/jeyanthinath/.gvm/pkgsets/go1.9.2/global",
    "go.goroot": "/home/jeyanthinath/.gvm/gos/go1.9.2",
    "go.formatTool": "goreturns",
    "go.lintTool": "gometalinter"
}
```

**For a while I tried using golang , and initally no issues , starting from yesterday my memory is raising to whooping `100% from 30%` and my cpu usage also shoots up to `100% instantly from 60%` whenever I hit save** 

> This make my laptop unusable with golang 

I used dsat to log the issue

`dstat -ta --top-cpu --noheader --output systemstats.cs`

**output:**

```
27-11 12:08:14| 54  21   1  23   0   0|9092k    0 | 222B  435B|  16k    0 |  19k   54k|megacheck     33
27-11 12:08:15| 21  10   0  68   0   1|  12M    0 | 731B  536B|   0     0 |8402    23k|megacheck    9.0
27-11 12:08:16| 33   9   0  58   0   0|  14M  208k| 578B  164B|   0     0 |  10k 9405 |unconvert     27
27-11 12:08:17| 75  12   0  12   0   1|6068k    0 | 168B    0 |   0     0 |  24k   15k|megacheck     41
27-11 12:08:18| 72  12   0  15   0   0|8208k    0 |  60B    0 |  28k    0 |  79k   16k|unconvert     38
.
.
27-11 12:08:38| 42  13   0  45   0   0|2824k   21M|  11k 3643B|  36k   21M|  59k   16k|errcheck      72
.
.
7-11 12:08:38| 42  13   0  45   0   0|2824k   21M|  11k 3643B|  36k   21M|  59k   16k|errcheck      72
27-11 12:08:45| 50   8   0  42   0   0|3824k   56k| 531B  536B|  96k    0 |  17k 6030 |varcheck      30
27-11 12:08:46| 79  20   1   1   0   0|4028k    0 | 354B  246B| 112k    0 |  24k   14k|varcheck      38
27-11 12:08:47| 81  18   0   1   0   0|4756k 3460k|1028B    0 | 436k 3436k|  16k 9607 |maligned      40
27-11 12:08:48| 52  20   0  27   0   0|2480k   29M|   0     0 | 704k   78M|  32k 5308 |varcheck      22
27-11 12:08:49|  5   5   0  90   0   0|  89M  313M|5559B 1560B|1168k  262M|  87k   38k|maligned      38
```

please do help me solve this issue

**Comment by altairlu** [comment]
the same to me !  
i cant work well

**Comment by ramya-rao-a** [comment]
@jeyanthimuthuram @altairlu Can you update to the latest Go version (0.6.69) and see if you still have issues?

**Comment by altairlu** [comment]
@ramya-rao-a 
i updated to 0.6.69, but the issue stll existed. 
 i changed lintTool to gometalinter, not work.

**Comment by jeyanthimuthuram** [comment]
Initially it too thought it was something to do with golang.

But after I disabled this extension everything is going super smooth.

But as there are no good alternatives to golang extension. I am completely
stuck and I can't code in vscode with golang

**Comment by ramya-rao-a** [comment]
Can you try on a smaller project? If a project is too large, the linting on save might get expensive.

Here are a few things to try:
- Set `go.lintTool` to `golint`. The other 2 options may get expensive on larger projects
- Set `go.lintOnSave` to `false`. This will disable the running of the linter on every save. Instead use the command `Go: Lint Current Package` whenever you want to lint your code
