### ISSUE TITLE
Broken selection choice "Open Workspace settings"

### ISSUE THREAD

**Issue by JanKoehnlein** [Microsoft/vscode-go#1374]
In `goInstallTools.ts` the selection result "Open Workspace settings" is not handled properly.

**Comment by ramya-rao-a** [comment]
Fixed with #1375

**Comment by ramya-rao-a** [comment]
The fix is out in the latest update to the Go extension (0.6.69)

**Comment by JanKoehnlein** [comment]
Cool, thanks.
