### ISSUE TITLE
Run tests with verbose output

### ISSUE THREAD

**Issue by rakyll** [Microsoft/vscode-go#1377]
The inline "run test" runs the tests without -v flag. I often end up copy pasting what "Running tool" is outputting to my terminal and modify it to have the -v flag.

```
Running tool: /Users/jbd/go/bin/go test -timeout 30s go.opencensus.io/exporter/stats/stackdriver -run ^TestEqualAggWindowTagKeys$
```

**Comment by ramya-rao-a** [comment]
Add the below in your settings

 `"go.testFlags": ["-v"]`
