### ISSUE TITLE
many launch.go files ?

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/vscode-go#138]
my use case:
i need to be able to kick off many processes.
It this case 3.
so i made 3 launch files.
launch.json
launch-agent.json
launch-master.json

but the tool only allows me to choose "launch.json", even though the other two are there.

my intension was too lanch 3 editors, and then kick off each launch.json in each
```
code .
```

I wonder about where you are going on your roadmap with this.
it occurs to me that because the debugger is communicating over http (i think ?) with the IDE; then its possible it could launch many debug processes from a single code IDE session ?

**Comment by lukehoban** [comment]
For your original issue, you can list multiple debug configurations in a single `launch.json` file, and then choose the specific target you want to debug differently in each window.  You may though run into the issue that you can't have multiple Code windows open on the same folder - so you'd have to do something where you open different subfolders in different Code instances (and perhaps put each ones launch.json local to that folder).

On the questions about attaching multiple debuggers in a single Code debugging session...

This may be theoretically possible, but I expect it's not simple.  Delve doesn't provide this ability itself, so we'd have to coordinate multiple attached Delve instances from the single UI.  But that UI doesn't provide a way of knowing how to map actions to the various debuggees (breakpoints in particular).

But it doesn't seem impossible, so I'll leave this active in case we're able to do it.

**Comment by joeblew99** [comment]
Thanks I get it. Really thorough answer.

Can you copy into this issue example json that models 2 for me ?

On the issue of launching more than one vscode windows that map to the same folder on the hard-disk. Yeah I hit that one.
Not sure how I can work around it easily.
I could restructure my code so each client is its own namespace and hence cmd path. 

Am liking vscode BTW. Keep going please

**Comment by lukehoban** [comment]
Here's an example that uses multiple launch targets in a single `launch.json` - this example is for a Node project, but same general thing will work for Go.

```json
{
	"version": "0.1.0",
	"configurations": [
		{
			"name": "Launch Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [ "--extensionDevelopmentPath=${workspaceRoot}" ],
			"stopOnEntry": false,
			"sourceMaps": true,
			"outDir": "out",
			"preLaunchTask": "npm"
		},
		{
			"name": "Launch Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": ["--extensionDevelopmentPath=${workspaceRoot}", "--extensionTestsPath=${workspaceRoot}/out/test", "env.GOPATH" ],
			"stopOnEntry": false,
			"sourceMaps": true,
			"outDir": "out",
			"preLaunchTask": "npm"
		}
	]
}
```
