### ISSUE TITLE
Extra whitespace in running test output

### ISSUE THREAD

**Issue by martinlindhe** [Microsoft/vscode-go#1381]
When I click "run test" on a single test function in vscode, the output looks like this:

<img width="277" alt="in_vscode" src="https://user-images.githubusercontent.com/181531/33374697-7678dea8-d507-11e7-8f71-69c9c50360b7.png">

If I instead copy the command line that vscode claims to have used and run it in the terminal,

    $ /usr/local/bin/go test -timeout 30s github.com/martinlindhe/XXXX-tests -run ^TestXXXXXXX$

 I get the following output:

<img width="197" alt="in_terminal" src="https://user-images.githubusercontent.com/181531/33374747-a7028934-d507-11e7-9341-afb0795cb677.png">

First, there are a bunch of whitespace taking up space in my output window.

Secondly, the line "assertions.go:239" is confusing, since it is not present when running from terminal.

**Comment by ramya-rao-a** [comment]
When you run the test command separately, you only see the stdout
When running test in VS Code, it shows both stdout and stderr
Please follow the discussion in https://github.com/Microsoft/vscode-go/issues/1120 where we talk about this.

Can you run the same test command and see what you get in stderr?

**Comment by martinlindhe** [comment]
> When you run the test command separately, you only see the stdout

This is not right. I am quite sure my terminal is showing both stderr and stdout.

Will look at the odiscussion in #1120

**Comment by martinlindhe** [comment]
@ramya-rao-a   #1120 is unrelated to this issue.

**Comment by martinlindhe** [comment]
So, according to #1120 you no longer actually run "go test", so the command line you are showing is indeed not correct.

I am referrring to https://github.com/Microsoft/vscode-go/issues/1120#issuecomment-334788240

**Comment by ramya-rao-a** [comment]
We dont literally run `go test package`, we run `go test <import-path-to your-package`
What is being printed in the output channel is exactly what is being run.

If you are up for it, I can help you debug this by running the extension code from source

**Comment by martinlindhe** [comment]
I made another observation

When using go/testing, the internal testing system, vscode test output looks as expected.

I only get these extra whitespace as in screenshot when using testify/assert, a very popular third-party testing framework for go.


Mini reproducable tiny_test.go:

```go
package tiny

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestInternal(t *testing.T) {
	if 1 != 2 {
		t.Error("TestInternal marked failed")
	}
}

func TestTestify(t *testing.T) {
	assert.Equal(t, 1, 2, "TestTestify marked failed")
}
```


Output from running file tests in vscode:
<img width="726" alt="screen shot 2017-12-01 at 11 31 27" src="https://user-images.githubusercontent.com/181531/33478931-56181ce8-d68b-11e7-9bd9-a1bf325f699c.png">

Output from running the same command in zsh:

<img width="756" alt="screen shot 2017-12-01 at 11 32 05" src="https://user-images.githubusercontent.com/181531/33478946-5f2abf48-d68b-11e7-9ab7-16e506e0f1ca.png">

**Comment by ramya-rao-a** [comment]
Append `2>&1 | tee output` to the end of the test command when you run from zsh and then open the "output" file.

stdout and stderr both are redirected to the "output" file

You will see the blank lines

**Comment by martinlindhe** [comment]
@ramya-rao-a Thanks once more.
You are fully right.

It appears my configuration is broken, and stderr is not showing on my terminal. I must have broken the setup some time ago and didn't notice.

with `2>&1 | tee output` i can confirm the extra stuff is there, but that is another issue

Thanks again

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
