### ISSUE TITLE
Show which analysis tools are missing

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode-go#1382]
My vscode shows "Analysis Tools Missing" in the bottom right, and when I click on it I get this message:

![image](https://user-images.githubusercontent.com/159209/33392757-c82e93a2-d4f1-11e7-8049-a36b76a07e88.png)

I can't click on Install, because I use an external path and a [download script](https://github.com/ahmetb/dotfiles/blob/cfbc3d8e36403d6c5f067ade03559da2e67d180d/install_gotools.sh#L16-L29) to maintain those. 

I'm curious if the message can be more specific if some things are installed, but not all.

**Comment by anchepiece** [comment]
The logic to collect the right tools for the running platform and go version is found here:
https://github.com/Microsoft/vscode-go/blob/3c895791b1e35098c395259140e5925c961d652a/src/goInstallTools.ts#L44

The complete array of available tools and their source locations are placed above that. Note that some may not be applicable to your environment.  I like how the prompt simplifies the install process, especially with new go installs that may not have any tools installed yet. However, the `missing` tools could be logged somewhere for review to aid users handling things differently.

**Comment by ahmetb** [comment]
I guess I should just copy from there, thanks.

**Comment by ramya-rao-a** [comment]
Nice timing. See #1394
I just pushed a change that will give you the option of "showing" the missing tools.
Also, updated the logic to include only the explicitly used tools in this list.
This way, you wont get the missing tools message for tools like `gotests`, `goplay` etc.

When you do however try to run `Generate Tests` or `Run in Playground` commands, a prompt for exactly that tool will show up

**Comment by ahmetb** [comment]
@ramya-rao-a great, thanks@

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.70), the `Analysis Missing Tools` message will now appear only if the Go tools for the basic features are missing.
When clicked, the resulting prompt will also have an option to show the said missing tools
