### ISSUE TITLE
Extension failed to activate

### ISSUE THREAD

**Issue by meling** [Microsoft/vscode-go#1386]
After a reboot yesterday, `vscode-go` does not work properly anymore. I noticed because `formatOnSave` wouldn't reformat my code, and I depend heavily on this feature! I haven't been able to figure out what is the cause of this problem. Still trying different things, but wanted to get some input on what to try. Here is at least one clue:

Go commands that I could access through the command palette returns an error message like this:
```
command 'go.gopath' not found
command 'go.get.package' not found
```
This seems to apply for all Go related palette commands. Other extensions like markdown etc does is not impacted.

One thing that seems to still work though is the syntax highlighting.

I hope someone could please tell me where to start looking in order to fix this problem. Thanks!

Versions etc: 
- macOS High Sierra 10.13.1
- VSCode 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9) 2017-11-16T18:19:05.981Z
- vscode-go version 0.6.69 - 27th November, 2017
- go version go1.9.2 darwin/amd64
- GOPATH includes my bin, which should contain the tools used by vscode-go.

**Comment by meling** [comment]
Restarted VSCode yet another time, and now it suddenly works again!!  (I've restarted several times before to no avail... so I'm still curious what could be the problem, but it is solved for me.) Feel free to close the issue.

**Comment by ramya-rao-a** [comment]
Next time this happens, open the console (Help -> Developer Tools -> Console) and share any error messages found there.

**Comment by qoops-1** [comment]
@ramya-rao-a, I have the same error, here is the error from console: 
    
> command 'go.get.package' not found 
> e.doShow @ messageService.ts:126

go get from command line works fine.

info:
* macOS Sierra
* go 1.9.2
* VSCode 1.18.1

**Comment by ramya-rao-a** [comment]
@qoops-1 Looks like the extension did not get activated. Do you get the error when there is a Go file open?

**Comment by qoops-1** [comment]
@ramya-rao-a No, there was no Go file open. If I open a file, I get:

> No import path to get

**Comment by ramya-rao-a** [comment]
Where do you see the "No import path to get" ? Please share a screenshot

**Comment by meling** [comment]
This problem resurfaced, but this time on my laptop. Here is a screenshot:
<img width="551" alt="screenshot 2017-12-03 20 54 19" src="https://user-images.githubusercontent.com/810999/33536823-5ac4fdbe-d86c-11e7-97b2-731429c307fd.png">

(will try to figure out what the problem is from the debug messages, but thought I'd share it here anyway... since this is the second time it has occurred, and others may run into this as well... maybe consider reopening this issue.)

**Comment by ramya-rao-a** [comment]
The error is about failing to find the `diffUtils` module when loading the formatter as needed in https://github.com/Microsoft/vscode-go/blob/0.6.69/src/goFormat.ts#L10

This fails the extension activation. Since the extension didn't get activated, running any of the commands from the extension fails as well.

This is weird. I cannot repro in Windows or in Mac OS X El Capitan.

Can you navigate to `~/.vscode/extensions/lukehoban.go-0.6.69/out/src` and see if there is a file there named `diffUtils.js` ?

@qoops-1 Can you confirm that you see similar call stacks?

**Comment by meling** [comment]
I seem to have problems on both my computers. My office machine does have `diffUtils.js` and it was working fine for a while today. (I will check my laptop later, if the `diffUtils.js` is missing there still (where the screenshot was taken)).

Anyway, earlier today, I ran into a similar problem, in that I couldn't get the compiler to identify problems in a specific file, which I knew wouldn't compile. For this problem, it didn't help to try to edit the file and save it to trigger the compiler/format on save thing. Here is a screenshot of this issue:
<img width="995" alt="screenshot 2017-12-04 17 03 48" src="https://user-images.githubusercontent.com/810999/33589413-2809165a-d92d-11e7-9f59-8ddf5816c05c.png">

I was able work around the issue by restarting vscode, but the above error messages seem to indicate some problems in the vscode or the vscode-go extension that should be fixed anyway.

But then just a few minutes ago, I ran into another (likely) unrelated issue, where I could not use the arrow keys to navigate the Editor part, but instead when pressing arrow keys, things were happening in the Explorer part (expanding/collapsing folders). I tried to "reactivate" the editor with mouse clicking, to no avail. I was able to use the mouse to position the cursor and write text into the editor, but then the space bar didn't work. Very weird behavior!! I forgot to check if the developer tools/console were showing any issues. However, this also resolved itself after restarting vscode. This could be totally unrelated to the go plugin I presume. Just thought I let you know anyway. If it happens again, I'll report it elsewhere properly.

**Comment by ramya-rao-a** [comment]
If you find the `diffUtils.js` file missing, then it means somehow you ended up with a corrupted set of files for the Go extension. I would suggest to uninstall the extension -> reload vscode -> install the Go extension.

The errors related to `godef` are cases when definition for given symbol is not found. This gets triggered for the Go to definition feature, hover feature and the signature help feature.

The other issue on arrow keys is independent of the Go extension. If you get a good repro, then please log the issue in the vscode repo.

**Comment by qoops-1** [comment]
@ramya-rao-a 
<img width="1440" alt="2017-12-13 12 08 30" src="https://user-images.githubusercontent.com/10588791/33930600-8c3c196a-dffe-11e7-9ad1-d434c9c43404.png">

**Comment by ramya-rao-a** [comment]
@qoops-1 Please dont just paste a screenshot of an error. Add details around what you did to get to that state.
In this particular case, you must have run the `Go: Get Package` command which only works when your cursor is on an import statement. 
And so this is unrelated to the current issue at hand

**Comment by qoops-1** [comment]
@ramya-rao-a yep, you're right, sorry for confusion. Now I see how go get works

**Comment by ramya-rao-a** [comment]
@meling Are you still seeing issues? Did an uninstall and a clean install of the extension help?

**Comment by meling** [comment]
@ramya-rao-a It was fine before the holidays; haven't been working on code the last few weeks. Can't recall the exact steps I took, but I think the uninstall and reinstall did the trick.

**Comment by ramya-rao-a** [comment]
I'll close the issue then. Happy Coding!
