### ISSUE TITLE
VSCode hogs cpu and constantly churns on go code

### ISSUE THREAD

**Issue by joelpresence** [Microsoft/vscode-go#1387]
Hi,

I'm using VSCode for go 1.9.2 development.  Thanks for your hard work on this editor!

The editor has gotten MUCH slower on go 1.9.  Is there anything else we can do to speed it up?  It's a really issue for me.  For example, I have been sitting here for about 5 minutes now, have not edited any code in the 4 go tabs that are open, and the little blue "cursor" underneath Explorer has been moving left to right left to right the whole time while pegging my cpu at 60-100%.  This does NOT happen in VSCode with the same extensions installed when used on JS or other languages.  Only go.  This does NOT happen when using my go code in other editors.

So the issue is not my go code or VSCode, but rather VSCode + go.

Is there any way to to debug/log what is causing this blue line to keep cycling across?  It's obviously some kind of activity indicator, but how do I find out what that activity is and how to stop it or make it more efficient?

I just don't see how VSCode could still be recompiling stuff 5 minutes after I last edited and saved a file.  There have been no changes in the last 5 minutes and yet still it pegs my cpu at 60%.

Any ideas how to debug this?  I can't just turn extensions off.

Thanks!  :-)

![image](https://user-images.githubusercontent.com/12057689/33457269-d4536c26-d5d6-11e7-9c92-59b6423af9cf.png)

**Comment by joelpresence** [comment]
I'm on the latest version of VSCode, using the latest vscode-go and go 1.9.2 on macos Sierra latest version.

**Comment by ramya-rao-a** [comment]
- What version of the Go extension are you using?
- Have you recently upgraded the Go version or the OS? If yes, then run `Go: Install/Update Tools` to ensure that the dependent Go tools have been recompiled
- What action was taken just before the progress indicator appeared? Renaming, Go to definition, file save or just typing? Try to get a repro to answer this question.
- Can you share your Go related settings?
- Do you still see this with all other extensions disabled?

**Comment by joelpresence** [comment]
@ramya-rao-a 

What version of the Go extension are you using?
- the latest, 0.6.69

Have you recently upgraded the Go version or the OS? If yes, then run Go: Install/Update Tools to ensure that the dependent Go tools have been recompiled
- No I have NOT recently updated.  But my go tools are all up to date.

What action was taken just before the progress indicator appeared? Renaming, Go to definition, file save or just typing? Try to get a repro to answer this question.
- Any action causes this.  All actions cause this.  Edit a file.  Run tests separately in terminal (bash) using `go test` causes this.  Typically it's worst when I edit a file, save it and then go to the shell to run tests.  I don't like the test output in VSCode so that's why I run them in the shell.

Can you share your Go related settings?
```
{
  "go.testEnvVars": {
    "REDIS_URL": "redis://localhost:6379"
   },
  "editor.formatOnSave": true,
  "files.autoSave": "off",
  "files.autoSaveDelay": 5000,
  "go.formatOnSave": true,
  "go.gocodeAutoBuild": false,
  "go.lintOnSave": "off",
  "go.vetOnSave": "off",
  "go.buildOnSave": "off"
}
```

Do you still see this with all other extensions disabled?
- I do not see it with any other language, like JS, so why would turning off all other extensions have an impact?  All other extensions are unrelated to go.  I only have one go extension.  How would I do this?

Any errors in the console when this happens? Help -> Developer Tools -> Console
- Nothing that I can see, no


Any ideas?  I really love VSCode, but it's SO slow now that I'm thinking of abandoning it for go because it really slows down my productivity.

Any help would be hugely appreciated.  :-)

**Comment by joelpresence** [comment]
I'm also seeing tons of warnings like this in the VSCode dev console:
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
```
these seem to involve 'raw.marked.js`.

Then a number of errors about broken pipes.

**Comment by ramya-rao-a** [comment]
- Try turning off `editor.formatOnSave`. That might be interrupting with the format on save feature of the Go extension. You can turn this off just for Go files by adding this in your settings
```
"[go]": {
      "editor.formatOnSave": false
    }
```

- There are some extensions that run some actions on file save that might have undesirable effects. That's why I asked to disable all other extensions and try to eliminate that scenario. You can do this by running `code --disable-extensions` and then enabling just the Go extension in the extensions viewlet 

- Do you see any Go related processing running a lot in the Activity Monitor. If so which ones?

**Comment by joelpresence** [comment]
Hi @ramya-rao-a ,

I've followed your suggestions and I guess they help a bit, but not much.  VSCode is still horribly slow on go 1.9.2.

For example, I see "Code Helper" in activity monitor using 54% of my cpu, with parent process Code.  Any ideas how to dig deeper and see what is causing this within VSCode?

**Comment by ramya-rao-a** [comment]
Yes, run `ps aux`, use grep to narrow down the processes for `Code Helper`. For the ones that are using high cpu, look at the args being passed to the process and share here.

To ensure that other extensions are not interfering, please disable all the other extensions, reload VS Code and look at the processes

**Comment by joelpresence** [comment]
Hi @ramya-rao-a , it seems like there's a lot of `go list -json` that are using some cpu.  But still, the VSCode "CodeHelper" is the principal culprit ... Any further tips?  Thanks!

**Comment by ramya-rao-a** [comment]
`go list -json` is used by the `Go to Implementation` feature. Have you used that lately? There should just be 1 process spawned for a `go list -json` each time you use this feature. That would still not explain why there would be a lot of these, unless go itself spawns parallel processes.

What are the args for the Code Helper process that you see?

**Comment by ramya-rao-a** [comment]
Are you working on large projects?
Do you also see such high cpu usage when working on smaller simpler projects?

**Comment by joelpresence** [comment]
Well, I just upgraded to the November release, 1.19.0 and all of sudden VSCode is really fast again and all the slowdowns disappeared.  Nice work by your team!  Thanks so much for all of your help and all the hard work you do on our behalf.  Things are fast again!  :-)

This feels resolved, so I'm going to close this.

Thanks again @ramya-rao-a .

**Comment by ramya-rao-a** [comment]
Thanks @joelpresence :)
