### ISSUE TITLE
cursor jumping to top of file

### ISSUE THREAD

**Issue by tsraza** [Microsoft/vscode-go#1389]
On save, the cursor jumps to Ln 1, Col 1 of the file.

Version 0.6.69 - 27th November, 2017

**Comment by hajhatten** [comment]
Getting the same on Windows. I'm guessing it's go fmt that's messing things up on save.

Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Date 2017-11-16T18:32:36.023Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by ramya-rao-a** [comment]
This is being tracked in #1346

Workaround until we find a fix for this is to disable the format on save feature. Add the below in your settings
`"go.formatOnSave": false"`

**Comment by ramya-rao-a** [comment]
@tsraza @hajhatten You can follow the steps in https://github.com/Microsoft/vscode-go/issues/1346#issuecomment-349893523 to get the fix for this issue before the next udpate

**Comment by ramya-rao-a** [comment]
The latest update to the Go extension (0.6.70) has this fix.
