### ISSUE TITLE
Debugging a single file

### ISSUE THREAD

**Issue by opjlmi** [Microsoft/vscode-go#1390]
Hi, these is my launch.json file.

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "go",
      "request": "launch",
      "name": "Launch Single file",
      "mode": "debug",
      "program": "${file}",
    },
  ]
}
```

In my project folder, every file are independent file......
I thought VSCode should debug a single file, not project.
(because the `program` setting)

If I run `Start Debugging`, it will failed.
VSCode always show `could not success debug the codes`. 😰
```
# myproject
./hello.go:5:6: main redeclared in this block
	previous declaration at ./go-basic.go:8:6
./method.go:32:6: main redeclared in this block
	previous declaration at ./hello.go:5:6
./type.go:34:6: main redeclared in this block
	previous declaration at ./method.go:32:6
```

But run `Start Without Debugging`, it will work........

**Comment by ramya-rao-a** [comment]
`Start Without Debugging` uses `go run`. `program` points to `$file` and current file path is passed to `go run`

`Start Debugging` uses `dlv debug`. program` points to `$file` , the debug adapter assumes you want to debug the package to which the current file belongs to and so runs `go debug` in the file's directory.

What you want is for the debug adapter to run `dlv debug filepath` which is being tracked in #1229
