### ISSUE TITLE
go debuging failed  tips "could not find symbol value for vscode"

### ISSUE THREAD

**Issue by sunnyingit** [Microsoft/vscode-go#1392]
vscode: 1.18.1 (1.18.1)
go version: go1.9.2 darwin/amd64

dlv version:  1.0.0-rc.2

![image](https://user-images.githubusercontent.com/7732824/33612680-54650098-da0d-11e7-96f2-624cbc11a494.png)

**Comment by ramya-rao-a** [comment]
What's the `print debug` there? Is that what you typed in the debug console?
Is `debug` a variable and you wanted to check its value?

If so, then you need to just type `debug` not `print debug` in the debug console

**Comment by sunnyingit** [comment]
Sorry for not describing the problem clearly

The issue is when i start debuggering and typed some commands provided by dlv such as 'print' 'break' in the debug console, but  console responses to me with message: "Failed to eval expression"

![image](https://user-images.githubusercontent.com/7732824/34197204-61e0b980-e5a0-11e7-9156-2bcfc938afd1.png)

**Comment by idevz** [comment]
hi @sunnyingit did you resloved this issue? I have the same problem, how to fix this ? and thanks.

**Comment by ramya-rao-a** [comment]
You cannot use dlv commands in the debug console.

**Comment by idevz** [comment]
hi @ramya-rao-a thanks a lot, I just can print some vars value like just type the names  in the debug console, but, can I type other dlv command like `step `, `next ` and how? I can't find the relevant wiki.
<img width="588" alt="screen shot 2018-01-09 at 5 49 57 am" src="https://user-images.githubusercontent.com/2113827/34694292-824c7f4a-f501-11e7-95f2-f1095d1394c7.png">

**Comment by ramya-rao-a** [comment]
You can use the debug bar on top for stepping in/out/over

<img width="701" alt="screen shot 2018-01-08 at 3 22 07 pm" src="https://user-images.githubusercontent.com/16890566/34697388-b7d7fb78-f487-11e7-88a6-cb9433f32ead.png">

You can also use the keyboard short cuts for the same.

**Comment by idevz** [comment]
@ramya-rao-a got it, thanks a lot :)
