### ISSUE TITLE
Show missing analysis tool only for explicitly used features

### ISSUE THREAD

**Issue by bsr203** [Microsoft/vscode-go#1394]
Hi.
Is there a way to disable missing analysis tool message. recent changes add dependency on `goplay`, and there was no way to know which tool was missing until looking through the code. The warning doesn't say which tool is missing. Also, [this page](https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on) is not updated. To avoid this 
1. is it possible to only warn when the feature is explicitly used. 
2. list all the missing plugins in the warning.
or opt out some of the plugins through configuration

thanks
bsr

**Comment by ramya-rao-a** [comment]
Updated the wiki.

> is it possible to only warn when the feature is explicitly used.

Yes, that's a good point. 

> list all the missing plugins in the warning.

Along with "Install" option, we can show a "Show missing tools" option that will print out the missing tools in the output pane

PRs are welcome if anyone wants to give this a try.

I can help out with pointers to where to get started

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.70), the `Analysis Missing Tools` message will now appear only if the Go tools for the basic features are missing.
When clicked, the resulting prompt will also have an option to show the said missing tools
