### ISSUE TITLE
command key vs hover

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode-go#1396]
vscode 1.18.1 OSX
plugin 0.6.69 
go 1.9.2

Hovering over a function will give you the definition of the function but when still hovering and keep pressing the command key at the same time will open the definition twice stacked. It should detect if the definition popup is already open.

Also there is no way to scroll a large definition popup when holding command button

ref: https://github.com/Microsoft/vscode/issues/39739

**Comment by ramya-rao-a** [comment]
Sorry for the churn @gertcuykens, I have re-opened the original issue in vscode with my comments
