### ISSUE TITLE
augment vet's "not enough arguments in call to …" with the definition

### ISSUE THREAD

**Issue by buyology** [Microsoft/vscode-go#1397]
When there are missing arguments to a call and `vet` complains about it — it's currently difficult to know what the arguments are as the raw `vet` error only shows the types. 

I find myself hovering the definition (which can be somewhat flaky when you also have that `vet` error there) or jumping into the definition.

It would increase ergonomics if we could also display the definition alongside the error.

(Sorry for the look of this mockup — this is not gonna win any design awards — but gives you an idea of what I mean.)

<img width="388" alt="screen shot 2017-12-07 at 11 48 50" src="https://user-images.githubusercontent.com/5368302/33711533-a8a28026-db44-11e7-9e00-837c30803672.png">

**Comment by ramya-rao-a** [comment]
This feature request would require us to 
- parse the vet output
- look for certain types of messages
- extract the function name along with package name
- Run godef on it to find the signature

That's assuming the text for such warnings does not change.
If it does, then have different text for different Go versions.

Ideally, if we were to use a language server, then it would be simpler to do the above.

But in the current state of things (where we spawn new processes each time we use any Go tool), this seems like an overkill.

A more simpler solution would be to log this feature request against the vet tool itself.

Or create a new Go tool that wraps around the vet tool and provides the additional information.

Sorry, closing this issue as the request is out of scope for the Go extension

**Comment by buyology** [comment]
Hm. Maybe I wasn't clear enough about this being more of an experience report that `vet`s complaint often shadows the already existing func def helper. 

If you are lucky, it shows the func def — or it just shows the `vet` output — which is not very helpful for said reasons.

The suggestion is to reach a middle ground and show both. The more information, the merrier, esp in the case of an error.
