### ISSUE TITLE
Hover is showing wrong function documentation

### ISSUE THREAD

**Issue by webRat** [Microsoft/vscode-go#1398]
Given the following:
![image](https://user-images.githubusercontent.com/59866/33725660-d2f8e38c-db40-11e7-82ce-6218f982bbf2.png)

You can see that the hover is showing the package documentation for `Eval` and not for the method function `func (*SomeStruct) Eval`

Godoc is showing both of these `Eval` statements correctly.

**Comment by zmb3** [comment]
`"go.docsTool": "gogetdoc"`  should handle this correctly.

**Comment by webRat** [comment]
Thanks @zmb3, your suggestion is working. I'll relay internally.
