### ISSUE TITLE
Incorrect display of map structure in debugger

### ISSUE THREAD

**Issue by vanhumbeecka** [Microsoft/vscode-go#1399]
See this issue here: https://github.com/derekparker/delve/issues/1039#issuecomment-350533067

The vscode debugger incorrectly displays a map-datastructure with wrong formatting.
This needs to be mapped by this plugin according how ```delve``` returns this to vscode.

**Comment by ramya-rao-a** [comment]
This is being tracked in #1384

Can you share a small sample code in #1384 that I can use to see what's going on?

**Comment by ramya-rao-a** [comment]
The fix for this issue is now out in the latest update to the Go extension (0.6.77)
