### ISSUE TITLE
support for `$workspaceFolder` in go.gopath

### ISSUE THREAD

**Issue by sandipb** [Microsoft/vscode-go#1400]
With multiple go projects in different folders sharing the same workspace, we need a way to specify a per folder `$GOPATH`, for example using the variable `$workspaceFolder`. Please add support for this in the Go extension.

**Comment by ramya-rao-a** [comment]
Support for `${workspaceFolder}` along with the previous `${workspaceRoot}` is now available in the  latest update of the Go extension (0.6.70) for the below settings
`go.gopath`
`go.toolsGopath`
`go.testEnvVars`
`go.testEnvFile`
