### ISSUE TITLE
Debugging: F11 keystroke makes macOS windows go crazy

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode-go#1401]
macOS 10.13.2
VSCode (Stable 1.18.1 and Insiders 1.19.0)

Hello, I don't know if this problem is peculiar to the Golang extension, or whether it applies to VSCode as a whole, but when I press the function key F11 in order to step into a func after stopping at a breakpoint, the entire desktop goes crazy. Note the very top and very bottom of the screenshot.

![screen shot 2017-12-12 at 11 48 23](https://user-images.githubusercontent.com/260612/33883140-917de7e0-df32-11e7-8c72-3ed8349433c2.png)

Pressing F11 again restores VSCode to normal. I can get the `step into` behaviour by clicking the button on the debug toolbar. I am trying to educate myself into using the keyboard more so it's a bit of an annoyance.

![screen shot 2017-12-12 at 11 51 50](https://user-images.githubusercontent.com/260612/33883198-e6529ec8-df32-11e7-8eaf-4ad785aa8e07.png)

**Comment by ramya-rao-a** [comment]
This is not Golang specific. Something happens when debugging in typescript as well.
F11 is the keyboard shortcut to show the desktop in Mac.

See https://github.com/Microsoft/vscode/issues/5102
