### ISSUE TITLE
Spelling: Litning in progress...

### ISSUE THREAD

**Issue by akurani** [Microsoft/vscode-go#1402]
Spelling error for version 0.6.69:

Run:
`Go: Lint Workspace`

Output:
`Litning in progress...`

Thanks.

**Comment by ramya-rao-a** [comment]
That got fixed via https://github.com/Microsoft/vscode-go/commit/0276792ee5271d5112a23a2bbcfd2a328885e502

Should be out in the next update to the Go extension.

Thanks for reporting
