### ISSUE TITLE
Feature request: Run linting first time file is opened

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode-go#1405]
It's a little weird that a file has to be saved in order to be linted.

Example use case: Since Gometalinter is so slow, I run a limited set of linters (`gometalinter --fast` minus a few annoying ones), and we have extensive linting included as a Make target, which is run part of the CI testing pipeline. When I run `make lint` manually, or a build comes back from CI with linter errors, I can open the offending file and fix it. But in order to mark all the lint error instances, I have to first make a dummy change and save the file.

There's a command *Go: Lint current package*, but it's a manual command, and it opens up an annoying panel in addition to create markers.

**Comment by atombender** [comment]
@ramya-rao-a Any opinion?

**Comment by ramya-rao-a** [comment]
Running diagnostics on file open was discussed once before in #118

The problem of the output panel popping up every time the manual command is run can be fixed easily. Instead we can show an item in the status bar ("Linting...")

**Comment by ramya-rao-a** [comment]
@atombender The problem of the output panel popping up every time the manual command is run is fixed in the latest release (0.6.74)

**Comment by atombender** [comment]
Super, thanks.

**Comment by ramya-rao-a** [comment]
Closing in favor of #654
