### ISSUE TITLE
debug broken: debug session is crashed/stoped without any information

### ISSUE THREAD

**Issue by Grisson** [Microsoft/vscode-go#1406]
Hi exports, 

When I hit the debug button, following is what I get in the debug console.

2017/12/12 23:56:35 server.go:73: Using API v1
2017/12/12 23:56:35 debugger.go:96: launching process with args: [/Users/<xxxx>/go/src/github.com/<project>/debug]
API server listening at: 127.0.0.1:2345
2017/12/12 23:56:37 debugger.go:492: continuing

Then, the debug is crashed or stoped here without any further information or error message.

I tried to start debug session manually in terminal.
e.g. dlv debug ${fileDirName}
It worked fine.

May I know how to fix this issue? 

I'm using Mac High Sierra 10.13.2. 
My VSC is Version 1.18.1 (1.18.1). 
Delve Debugger version is  1.0.0-rc.2.

**Comment by ramya-rao-a** [comment]
Add `"trace": "verbose"` to the debug config in the `launch.json` file and try again.
The debug console will now have verbose logging. That might shed some light on what's going on

Also,
Are you able to repro this consistently?
Is this specific to any particular project or does it repro even with simple code?
If you can repro with simple code, then can you share the code so that I can try?

**Comment by Grisson** [comment]
Hi Ramya-rao-a,

Thanks for your response. I add trace to debug configuration.
Here is the new information I got.

**InitializeEvent
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
ThreadsRequest
2017/12/14 22:37:54 debugger.go:492: continuing
continue state {"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":-1,"When":""}
TerminatedEvent
DisconnectRequest**


I cannot repro it with simple code. 
But, I can consistently repro it with one particular project. And, I can debug this project on my other machines.

**Comment by ramya-rao-a** [comment]
Are you other machines on other platform or are they Mac Sierra too? Also is the VS Code version, Go extension version and dlv version the same in the other machines?

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
