### ISSUE TITLE
Code coverage highlighting doesn't work when using multi-root workspace

### ISSUE THREAD

**Issue by alhails** [Microsoft/vscode-go#1408]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
vscode-extjs|Sen|1.0.1
jshint|dba|0.10.15
createuniqueid|don|0.0.3
githistory|don|0.2.3
php-debug|fel|1.12.1
php-intellisense|fel|2.1.0
Go|luk|0.6.69
mssql|ms-|1.3.0
azure-account|ms-|0.2.2
sublime-keybindings|ms-|3.0.3

Highlighting works fine when individual folder is open, but not when folder is opened as part of a multi-root workspace

**Comment by ramya-rao-a** [comment]
Are you referring to the `Go: Toggle Test Coverage in Current Package` command or the cover on save feature?

I ran the command in a file from each folder in the multi root mode and it works as expected.
cover on save feature works at package level. i.e saving a file in 1 package doesn't add coverage to another package.

**Comment by alhails** [comment]
@ramya-rao-a 
Hi, thanks for the reply.  
It was the `Go: Toggle Test Coverage in Current Package` command, but I've now tried with cover on save and this has the same issue.

Both commands successfully run...

 `/usr/local/go/bin/go test -coverprofile=/tmp/go-code-cover -timeout 30s`

It returns Test Pass and coverage %, But then I don't get any highlighting.

As mentioned previously if I close the workspace and just open a specific folder and retry then it works ok.  In this case I noticed the command run is slightly different...

`/usr/local/go/bin/go test -coverprofile=/tmp/go-code-cover -timeout 30s gitlab.com/datasoft-computing/starsapi/cmd/starsapi/services/qcc`

**Comment by ramya-rao-a** [comment]
Can you share the output of those commands from the output pane?
Most likely there is an issue in parsing the output

**Comment by alhails** [comment]
For the workspace scenario i get...

```
Running tool: /usr/local/go/bin/go test -coverprofile=/tmp/go-code-cover -timeout 30s

PASS
coverage: 79.5% of statements
ok  	gitlab.com/my/project/path	0.028s
Success: Tests passed.
```

For the single folder i get...

```
Running tool: /usr/local/go/bin/go test -coverprofile=/tmp/go-code-cover -timeout 30s gitlab.com/datasoft-computing/starsapi/internal/access

ok  	gitlab.com/my/project/path	0.010s	coverage: 79.5% of statements
Success: Tests passed.
```

**Comment by ramya-rao-a** [comment]
I can't repro the issue though.

If you don't mind, can you run the Go extension from source and see why coverage doesn't get applied? Its fairly easy to do so
- Follow the steps in [Building and Debugging the extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) to a local dev env set up
- Add a breakpoint at https://github.com/Microsoft/vscode-go/blob/0.6.69/src/goCover.ts#L169 and step through

**Comment by alhails** [comment]
:man_facepalming: I figured out it was caused by my workspace folder being setup to point to a symlink of the actual folder in GOPATH.  

And then when I was opening as a single folder I was opening the folder in GOPATH itself.

I've repointed the workspace folder and now it works great.

Sorry for the trouble and thanks very much for the help :+1:

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
