### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by jsturtevant** [Microsoft/vscode-go#1409]
VS Code Version: 1.18.1
Go  Extension Version: 0.6.69
OS: Windows 10 1709

I am not sure if this is a Go extension issue or VS code but I was not able to reproduce the error with other extensions like `c#` files and the `c#` extension.  If I add `"git.enabled": false` in `User Settings` the extension works.

Repo steps:
1. Open `go` file
2.  Get error: `Extension host terminated unexpectedly.`

Console output from developer tools:

`
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 Extension host terminated unexpectedly.
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
e._onExtensionHostCrashed @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 Extension host terminated unexpectedly.
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
e._onExtensionHostCrashed @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 Extension host terminated unexpectedly.
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
`

**Comment by ramya-rao-a** [comment]
VS Code 1.19 was released today.
Do you still see the issue after updating to 1.19?
