### ISSUE TITLE
gofmt -s not working

### ISSUE THREAD

**Issue by hhrutter** [microsoft/vscode-go#1411]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
githistory|don|0.2.3
gitlens|eam|6.4.0
Go|luk|0.6.69
vscode-icons|rob|7.19.0
vim|vsc|0.10.6

Steps to Reproduce:

Settings: "go.formatFlags": ["-s"],

The weird thing in the comment (see line below) the suggested usage is '-s' but this results in a settings error.

// Flags to pass to format tool (e.g. ['-s'])

**Comment by ramya-rao-a** [comment]
Can you provide a small sample code with before and expected after states when you run `gofmt -s` ?

**Comment by hhrutter** [comment]
There you go Ramya...

before:
`package main

import "fmt"

type foo struct {
	bar string
}

func main() {

	f := []foo{
		foo{bar: "abc"},
		foo{bar: "def"},
	}

	fmt.Print(f)

}`
after:
`package main

import "fmt"

type foo struct {
	bar string
}

func main() {

	f := []foo{
		{bar: "abc"},
		{bar: "def"},
	}

	fmt.Print(f)

}`

**Comment by ramya-rao-a** [comment]
Works for me.
Did you add the setting `"go.formatTool": "gofmt"`? The default formatting tool used is `goreturns` which does not support the -s flag

**Comment by hhrutter** [comment]
👍 you're right - sorry me :(

but then the comment for go.formatFlags in user settings needs to be fixed to:
`// Flags to pass to format tool (e.g. ["-s"])`

I just don't understand why in the world would anybody choose anything other than gofmt as the default go formatting tool in an IDE? `gofmt` is the definitive standard for formatting go source code and goreportcard.com which many Go projects integrate into their CI chain also requires projects to be formatted with `gofmt -s` for QA reasons.

I vote for making `gofmt` the default.

**Comment by hhrutter** [comment]
I've been looking more into this.
goimports is another option for formatting.

This is not good for 2 reasons:

1) goimports main job is to fix the import declaration in source files.
This is smth we always want to have irregardless of the choice for formatting.

2) goimports also takes care of formatting in gofmt style. Good - but it neither comes with the -s cmd line option as far I can see, nor does the built in formatting take care of anything gofmt -s takes care of.

My conclusion here:

This extension needs to have the import statement fixing added as
a separate flag in settings, maybe like: `"go.fixImportsOnSave": true`
That way we still can choose gofmt with corresponding flags like -s
as long as the formatting tool gets executed **after** goimports.

**Comment by ramya-rao-a** [comment]
I'd much rather prefer the `goimports` tool to support the `-s` flag instead.

There was a discussion on this from 2014. See https://groups.google.com/forum/#!topic/golang-nuts/RyWfs9ddn8c
Though the then author of goimports wasn't too keen on supporting the `-s` flag, I am sure they wouldn't mind if a PR was submitted to support the same.

Including @erikjohnston in this discussion as he brought up the same point in https://github.com/Microsoft/vscode-go/issues/435#issuecomment-346626619

**Comment by hhrutter** [comment]
I disagree.

There are 2 different actions here: formatting and fixing (also missing)
import declarations.
One should be able to enable each individually and independently.

Without having looked into how goimports executes the formatting part,
gofmt is part of the google go tools and it makes a lot of sense to keep it
separated and not mixed into some other tool.

**Comment by ramya-rao-a** [comment]
When not using `goimports` or `goreturns` as a formatting tool, we do have another way to add missing imports which is via the code actions (the light bulb that appears next to an error if there is a possible fix)

![codeaction](https://user-images.githubusercontent.com/16890566/34083089-72eb3300-e31f-11e7-94d3-f72eac6b45ba.gif)

We can add another code action for removing unused imports as well.

But running multiple tools when formatting a file is something that I want to avoid.

**Comment by hhrutter** [comment]
Maybe we have too many options..
I want to run whatever sequence of actions I want when saving my source
file and I think I am not the only one.
Both goimports and gofmt are defacto standards in the go community and this
should be baked into vscode's go extension either explicitly or under the
hood.
I don't see any reason why somebone would not want to rely on this.

I am against mixing together 3 tools as formatters when not all of them are
real formatters - It is confusing.
Maybe this is smth worth reconsidering.

**Comment by JeanMertz** [comment]
I came here looking for the same functionality, Or, that is, looking for ways to have both `gofmt -s` _and_ `goimports` run on save.

I really don't like having to add imports manually (through typing, or the code actions), but when _not_ using `gofmt -s`, I frequently run into CI errors that expect pushed code to be compliant with whatever gofmt makes of it (which makes sense).

**Comment by ramya-rao-a** [comment]
In the next month, I'll look into the new [Organize Imports](https://code.visualstudio.com/updates/v1_23#_run-code-actions-on-save) feature supported by VS Code. Best case scenario would be
- You use `gofmt` as your formatting tool
- The Go extension will implement the code action for organizing imports by using `goimports`

**Comment by JeanMertz** [comment]
That sounds awesome. Thanks.

**Comment by ramya-rao-a** [comment]
Apologies, there has been no update here, but PRs are most welcome :)

If anyone wants to look into the Organize Imports feature, I am here to help. Below are some code pointers

- See [Building & Debugging the Go extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) to have a local set up of this extension running.
- Update the `engine` property in the `package.json` file to `^1.23.0`. This is the property that defines the minimum version of VS Code that this extension supports. Since the APIs for the Organize Imports feature was introduced in 1.23, we have to change this property
- Run `npm run postinstall` to get the newer apis corresponding to VS Code version `1.23`
- From here on, you should be able to register a CodeActionProvider that runs `goimports` to return edits to VS Code.
- For running `goimports`, please re-use the code in `goFormat.ts`

Useful links:
- [Organize Imports feature](
https://code.visualstudio.com/updates/v1_23#_run-code-actions-on-save)
- [Source Code Action Kinds](https://code.visualstudio.com/updates/v1_23#_source-code-action-kinds)
- [Organize imports Code Actions](https://code.visualstudio.com/updates/v1_23#_organize-imports-code-actions)

Feel free to ask any further clarifications

**Comment by Helcaraxan** [comment]
No problem @ramya-rao-a can't guarantee anything but if I have any time available I'll definitely have a look. 👍

**Comment by ramya-rao-a** [comment]
The "Organize Imports" feature is now available when using `gopls` as the language server in this extension. The code formatting feature is independent of the import organizing feature when using the language server.

For more on language server, please see https://github.com/microsoft/vscode-go#go-language-server

Closing this issue as there are no plans to add this feature separately to the extension outside of the language server
