### ISSUE TITLE
Debug with long strings. Again

### ISSUE THREAD

**Issue by heretic13** [Microsoft/vscode-go#1413]
Hello.

At this point in the delve itself, you can set the maximum length of the string to display. But when debugging from vscode-go, "... 55 more" is still displayed.

It is impossible (or I do not know how) to interact directly with delve from vscode.

I do not see a parameter in the configuration file vs-code or vscode-go, which would determine the maximum length of the output string for delve.

**Comment by ramya-rao-a** [comment]
How do you set the max length in delve?

**Comment by heretic13** [comment]
Under delve:

config -list
config max-string-len 10000
config -save

**Comment by ramya-rao-a** [comment]
Closing the issue in favor of #868 which has a hack to get around the issue.
Looks like we have to use v2 of dlv apis to be able to configure the max string length.
