### ISSUE TITLE
I can not jump to definition.

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-go#1414]
_From @TXZdream on December 19, 2017 8:7_

- VSCode Version: 1.19.0
- OS Version: win 10 latest update

Steps to Reproduce:

1. `go get -u https://github.com/golang/tour`
2. Choose a function and press F12

Reproduces without extensions: No

_Copied from original issue: Microsoft/vscode#40496_

**Comment by ramya-rao-a** [comment]
@TXZdream

- Can you repro this using simple code and standard libraries?
- Can you try setting `go.docsTool` to `gogetdoc` and try again?
- Are there any errors in the console? Help -> Toggle Developer Tools -> Console
- Can you share your settings?
- Are other features of the extension working as expected? Like auto-completion and build/lint/vet?

**Comment by ramya-rao-a** [comment]
@TXZdream Closing this issue as we haven't heard back from you in a while
