### ISSUE TITLE
Find all references doesn't return references if used on the definition of the method

### ISSUE THREAD

**Issue by jltjohanlindqvist** [Microsoft/vscode-go#1415]
VS Code doesn't seem to return any references if I use "Find all references" from the actual implementation of the function. I've attached an example project where if I go to `config.go` and try to use "Find all references" on the function `GetConfig`, I get zero results. But if I go to either `main.go` or `config1.go` and use "Find all references" on the function `GetConfig` in those files, I get all the expected references, even the actual implementation in `config.go`. 

**Steps to reproduce:**
1. Open the attached project in vs code.
2. Go to the file `config.go`
3. Use "Find all references" on the function  `GetConfig`. Get zero results.

**Expected result:**
All the references to the function `GetConfig`, in this case 2.

**Actual result:**
Zero references are returned, when it should actually return 2.

The strange thing is that a colleague doesn't have this issue, and the only difference is that he's running VS Code on Mac, and I'm running it on Windows.

[config.zip](https://github.com/Microsoft/vscode-go/files/1571639/config.zip)

**Comment by ramya-rao-a** [comment]
I am not able to repro either

When you get zero results, are there any errors in the console? Help -> Toggle Developer Tools -> Console.
If there are no errors there, then can you try running the `guru` tool from the command line and see if you get non zero results there? You can use the [show offset](https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset) extension to get the offset you need to run `gocode`

**Comment by jltjohanlindqvist** [comment]
I tried using `guru` directly from the command line and I get the same result as when using VS Code, no references are found.

**Comment by ramya-rao-a** [comment]
I was not able to repro this (but am using Mac), so am guessing its specific to your environment.
Maybe your GOPATH set up is different from that of your colleagues who aren't seeing the issue?
I'll try in Windows tomorrow for a repro.

**Comment by jltjohanlindqvist** [comment]
Most of us at the office are using Windows and the two others I've asked have the same issue. The only one that doesn't have the issue is the guy using a Mac.

**Comment by ramya-rao-a** [comment]
The only thing I can think of (without actually trying on a Windows machine which I can only tomorrow in my office) is a casing issue in either the GOPATH or the file path that is passed to `guru`. See https://github.com/Microsoft/vscode-go/issues/290#issuecomment-249323841

- Have you set either `go.gopath` or `go.inferGopath` in your settings?
- What do you see when running the command `Go: Current GOPATH`?
- Again, any errors in the console when you get the 0 results? Help -> Toggle Developer Tools -> Console?
- Do you get the right references when running `Find All references` anywhere not on the definition?

**Comment by jltjohanlindqvist** [comment]
1. No.
2. c:\code\go
3. There's no error.
4. Yes. When I run `Find All References` on the actual usage of the function (config.GetConfig()) I get the two classes using the function and I get the actual implementation.

**Comment by ramya-rao-a** [comment]
I tried on my Windows machine and I couldn't get a repro.

Since you mentioned that you get 0 results when running guru from the command line as well, I would say that the next step should be to log an issue against guru itself. Maybe they will be able to tell what's going on.

Also, just to ensure you have the latest version of the tool, can you run `Go: Install/Update Tools` and try one more time?

**Comment by jltjohanlindqvist** [comment]
Tried running the command, the problem still exists after updating all the tool.

I'll try with the guru project instead, thanks.

**Comment by ramya-rao-a** [comment]
@jltjohanlindqvist It would do good if you share the results of what you found when running guru in the command line in the upstream issue you created.
Share the call you made (with all the input params) and the result. Do this for when getting references for the definition and also for the place where the symbol is used.

**Comment by jltjohanlindqvist** [comment]
Will do!

**Comment by ramya-rao-a** [comment]
Closing this issue as there is an upstream issue tracking the same.
