### ISSUE TITLE
0.6.7 Auto-include broken

### ISSUE THREAD

**Issue by kilmore** [Microsoft/vscode-go#1417]
Example: 

we have davecgh's spew in our vendor directory (e.g. app_root\vendor\github.com\davecgh). Prior to 0.6.7 it would automatically find the spew.Dump() function. After updating to 0.6.7 it cannot find the package.

**Comment by ramya-rao-a** [comment]
What do you mean by "cannot find the package"?
Any build errors?
Can you share screenshots?

What do you mean by "auto-include"?
Do you mean adding missing imports?

Can you share your settings?

**Comment by ramya-rao-a** [comment]
@kilmore Closing this issue as we haven't heard back from you in a while.
