### ISSUE TITLE
go generate button

### ISSUE THREAD

**Issue by marwan-at-work** [Microsoft/vscode-go#1418]
It would be super handy if we had a button on top of `//go:generate` to run the command that generates code without having to leave your editor or type `go generate` in your terminal. Quite similar to how Run Tests work on top of test functions. 

Other options
1. `//go:generate` could turn into hyper text, so you can just click it.
2. Have the `go generate` command in the command palette. 

I'm happy to submit a PR for it with some guidance :)

**Comment by ramya-rao-a** [comment]
We are tracking something similar in #263. Can you add your thoughts there?

Codelens (the button you refer to) and having a command is do-able
Changing the //go:generate to a link is not.
