### ISSUE TITLE
Format variables

### ISSUE THREAD

**Issue by pjebs** [Microsoft/vscode-go#1420]
The debugger doesn't format variables such as: `time.Time` and `time.Duration` in a human-readable form. Is this a bug? If not, it should be changed.

**Comment by pjebs** [comment]
https://github.com/derekparker/delve/issues/999

**Comment by ramya-rao-a** [comment]
Thanks for logging the upstream issue @pjebs 
Will close the current issue here as there is nothing to do in the Go extension for this.

**Comment by pjebs** [comment]
If upstream don't fix it, then why can't Go plugin do so instead? For `time.Duration` objects, it's trivial. For `time.Time` objects it's not trivial but still easy to do. Many people are trying out VSCode only because of Go Debugger support and many people deal with `time` objects. I'm sure it'd be worthwhile. I did a google search, and many people have this issue because for debugging purposes, it's simply not tenable to look an nanoseconds for `time.Duration` and some nonsense for `time.Time`

**Comment by pjebs** [comment]
@ramya-rao-a I looks like the guy who is creating a update to delve is resisting a fix for `time.Duration`. I've stated my reasoning there on the benefits of showing it and if he's not going to do it, it would be awesome if VSCode did: https://github.com/derekparker/delve/issues/999#issuecomment-354590454

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode-go/blob/0.6.70/src/debugAdapter/goDebug.ts#L664 is where we convert what we get from dlv (what you see as the output of the `print` cmd when using dlv directly)

As you can see, dlv can communicate the type of the variable and uses the [reflect#Kind](https://golang.org/pkg/reflect/#Kind) for it. The Go extension can make use of this information to display the variable value.

In case of the `time.Duration` object, the information on type would be some kind of int (I assume). There is no way I know of to differentiate it from other ints. This is why the Go plugin cannot fix the issue at hand. The fix needs to come from upstream.

If you have any ideas, I am open to hear them

**Comment by pjebs** [comment]
`reflect.Kind` will probably return `int64` for a `time.Duration`.
Maybe you consider the solution to be unacceptably messy but would it be possible for us to signify that a variable is actually a particular type (i.e. int64) and then VSCode can format it based on what we specify.

**Comment by ramya-rao-a** [comment]
> would it be possible for us to signify that a variable is actually a particular type (i.e. time.Duration instead of int64)

Who would be the `us`? People writing the code being debugged or dlv?

The Go plugin would depend on what dlv would return the type info as.

**Comment by pjebs** [comment]
`us` is user of VSCode. After the use signifies that a variable is of type `time.Duration`, then VSCode formats it instead of delve.

**Comment by ramya-rao-a** [comment]
But how would VS Code know that the variable is of type `time.Duration`?

**Comment by pjebs** [comment]
We tell it.

**Comment by ramya-rao-a** [comment]
Can you share a sample code that does that?

**Comment by pjebs** [comment]
There is no sample code. My suggestion is built into the VSCode UI.

**Comment by ramya-rao-a** [comment]
> The user tells it to pretend the int64 is actually a time.Duration

How do you propose this be done?

> My suggestion is built into the VSCode UI.

Am sorry, I don't understand what changes to the VS Code UI are you suggesting. Can you elaborate?
