### ISSUE TITLE
Latest Version does not start 

### ISSUE THREAD

**Issue by Mistobaan** [Microsoft/vscode-go#1424]
Macos Sierra 10.12.6
Visual Studio Code 1.19.1
Go Extension: lukehoban.go-0.6.70

Is not working. Always shows "reload and uninstall" buttons even after reloading multiple times.
Any `>Go: command` fails with `command not found`.

Can't find any log or any error message. 

It just auto-updated and now is unusable. 

Suggestions?

**Comment by halfpastfive** [comment]
I have the same issue on Ubuntu 17.10. I opened the vscode developer console and got the following message: 

```
Echec de l'activation de l'extension 'lukehoban.Go' : Cannot find module 'vscode-extension-telemetry'.
t._logMessageInConsole @ extensionService.ts:652
console.ts:123 [Extension Host] Échec de l'activation de l'extension 'lukehoban.Go' : Cannot find module 'vscode-extension-telemetry'.
t.log @ console.ts:123
```

Just updated vscode and the extension to the latest version (auto update).

**Comment by Mistobaan** [comment]
Installing back vscode 1.18.1 works back as expected

**Comment by ramya-rao-a** [comment]
Looks like the extension got into a corrupted state.
Uninstall and Install the extension again, and it should work

**Comment by Mistobaan** [comment]
Why close the issue before verifying is resolved? add a tag #waiting-response and have a bot that triages 14days long issues with that tag.

**Comment by ramya-rao-a** [comment]
@Mistobaan My apologies, I looked at the second comment on this issue and didn't read through your original issue description properly.

Can you share what your current status is?

> Always shows "reload and uninstall" buttons even after reloading multiple times

This seems to be an issue with core VS Code extension management and not the Go extension itself.
