### ISSUE TITLE
new pkg: go get..., no Completion Lists

### ISSUE THREAD

**Issue by imkos** [Microsoft/vscode-go#1429]
1.go get new pkg: go get (pkg url)
2.import (new pkg url)
3.to use:  (pkgname).     <-no Completion Lists

**Comment by ramya-rao-a** [comment]
- Does this happen only with new pkgs? 
- Are you able to get completions for other packages? 
- What about packages from std lib?

**Comment by imkos** [comment]
Does this happen only with new pkgs?
A: new pkg or no std lib and no used pkg.

Are you able to get completions for other packages?
A: OK.

What about packages from std lib?
A: OK.

Tried a few times,  After `go build -i .` .  The Completion Lists appears.

**Comment by ramya-rao-a** [comment]
We use `gocode` for completions which depend on the installed pkgs and not the source code i.e the pkgs in GOPATH/pkg and not GOPATH/src

Running `go build -i` would install all the dependent pkgs.
