### ISSUE TITLE
support multiple paths in GOPATH

### ISSUE THREAD

**Issue by dalu** [Microsoft/vscode-go#1430]
You can have multiple paths in GOPATH. This is good for separating "go get space" from own files.
For instance, my GOPATH looks like this
`GOPATH=$HOME/3go:$HOME/go`

So when I `go get github.com/abc/xyz` this would be placed in `~/3go`
while my own work would reside in `~/go`

However vscode-go doesn't support multiple paths in GOPATH, or maybe I missed something?

**Comment by ramya-rao-a** [comment]
vscode-go does support multiple paths in GOPATH. Are you seeing something that tells you otherwise?

Read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension. That might clear some of the doubts

**Comment by dalu** [comment]
Well this document states that, for all except "GOPATH from the environment variable" multiple paths are supported. That might be an oversight in the document.

Assuming it's an oversight, when I have 3 paths in the GOPATH env var, and one package was and is downloaded to the 2nd path in this var (because this GOPATH was extended later and the process of copying from 2nd to 1st path is underway) vscode-go prints, in imports, that this package is unavailable.

reproduce:
```
mkdir -p ~/go/src
export GOPATH=$HOME/go
go get github.com/gomango/sux
export GOPATH=$HOME/3go:$HOME/go
cat <<EOF
package main

import (
	"github.com/gomango/sux"
	"io"
	"net/http"
)

func main() {
	r := sux.New()
	r.GET("/", Hello)
	http.ListenAndServe(":8080", r)
}

func Hello(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, "hello")
}
EOF
code .
```
You'll see the `"github.com/gomango/sux"` with a red underline.
But if you mv the package from ~/go to  ~/3go the red underline disappears.

**Comment by ramya-rao-a** [comment]
When you open VS Code this way and run the command `Go: Current GOPATH`, what do you see?

> Well this document states that, for all except "GOPATH from the environment variable" multiple paths are supported. That might be an oversight in the document

Yes, thats an oversight

**Comment by dalu** [comment]
```Current GOPATH is inferred from current folder: /home/darko/3go```

```
env|grep GOPATH
GOPATH=/home/darko/3go:/home/darko/go
```

**Comment by ramya-rao-a** [comment]
Looks like you have set `go.inferGopath` set to `true` in which case GOPATH is inferred from the folder that is opened in VS Code instead of using the GOPATH from the env var.

Set it to `false` and try again

**Comment by dalu** [comment]
Hmm I don't know where that snuck in.
Sorry for taking up your time.
Happy new year Ramya

**Comment by ramya-rao-a** [comment]
No problem @dalu
Happy New Year to you too and Happy Coding!
