### ISSUE TITLE
debug test not working anymore after using "Debug > Start Debugging"

### ISSUE THREAD

**Issue by abenz1267** [Microsoft/vscode-go#1433]
Hello,

since using "Debug > Start Debugging" once i can't use the "debug test" link in test files anymore. I always get this error:

```
# runtime/cgo
exec: "gcc": executable file not found in $PATH
Process exiting with code: 1
```

How can i fix this?

Ubuntu 17.10
VSCode 1.19.1

Regards

**Comment by ramya-rao-a** [comment]
Using `Debug > Start Debugging` and the debug test links have nothing do with each other. Using one does not affect the other.

Are you able to debug tests using a debug configuration in the launch.json file?

**Comment by abenz1267** [comment]
Hi,

thanks for your reply. Weirdly enough a simple system restart fixed it. I tried to reproduce it but couldn't so far.

Regards
