### ISSUE TITLE
Open the documentation popup via keybind

### ISSUE THREAD

**Issue by elaurendeau** [Microsoft/vscode-go#1435]
I'm looking for a way to open the documentation popup (gogetdoc) by using a
keyboard shortcut.
When using vim to navigate your editor, you never move the actual mouse over the different methods to look at the documentation.

Is there a command that we can call to open the following popup?
![image](https://user-images.githubusercontent.com/4604501/34474174-65d6d9c2-ef49-11e7-8e34-cab98fb8ff34.png)

**Comment by elaurendeau** [comment]
Looking at VSCode keybinds, i just found peek definition which is a fine alternative for now!

![image](https://i.imgur.com/IhYqS7R.png)

**Comment by ramya-rao-a** [comment]
There is a keyboard shortcut to trigger the info that is shown on hover. Run the command `Preferences: Open Keyboard Shortcuts` and search for "hover"

<img width="1151" alt="screen shot 2018-01-01 at 10 40 04 pm" src="https://user-images.githubusercontent.com/16890566/34476343-c6338ee6-ef44-11e7-96d8-19a08bdfce89.png">

**Comment by elaurendeau** [comment]
This is working great, thanks!
