### ISSUE TITLE
[FeatureRequest] Allow 'hint' (gohint) as linter alternative 

### ISSUE THREAD

**Issue by wlbr** [microsoft/vscode-go#1436]
Hi,

would it be possible to allow an additional tool option to the linter choice? The required changes would be minimal, as there is the nice tool called gohint (or hint on the cmd line), which ist completely compatible to golint, but which is configurable by a small file within the project workspace.
See https://github.com/elgris/hint

Currently the config setting "go.lintTool" only support "golint", "gometalinter", "megacheck". An new option "gohint" would enable the use of the command line tool "hint", that is simply used on the path (therefore probably $GOBIN).

Thanks in advance!

**Comment by ramya-rao-a** [comment]
Have you tried using the `go.alternateTools` setting to do this?
- Install the `gohint` tool using `go get`
- Add the below in your settings
```
"go.alternateTools": {
    "golint": "gohint"
}
```

This will make the extension use `gohint` instead of `golint` for linting.
