### ISSUE TITLE
"go.buildOnSave" yeilds "cannot find package" errors for vendored packages

### ISSUE THREAD

**Issue by MikeMangialardi** [Microsoft/vscode-go#1437]
Setup:
here is what my $GOPATH looks like:
```
src/
    - vendor/
    |    - github.com/
    |    |    - various vendored dependencies...
    - test/
    |    - main.go
```

Contents of main.go:
```
package main

import (
	"fmt"
	"github.com/twinj/uuid"
)

func main() {
	foo := uuid.NewV4()
	fmt.Println(foo.String())
}

```
Steps to reproduce:
1. make a small, non-breaking change to main.go (add a comment, add a carriage return somewhere, etc.)
2. save main.go

Expected result:
No build errors appear in the "problems" viewer in Visual Studio Code

Actual Result:
One build error appears with text: "<$GOPATH redacted for privacy>/src/test/main.go:5: cannot find package "github.com/twinj/uuid" in any of the following: ..."

Note that if i run the command `/usr/local/bin/go build -i -o /var/folders/s0/pcmdx65n5jnfm7pqb11p8l740000gn/T/go-code-check .` (this is the verbatim command being run by the go extension copied from the output window) manually in my terminal after navigating to the text/ directory, the build succeeds without issue. 

EDIT:
I will include some system information
OS: MacOS High Sierra v 10.13.2 (17C88)
VSC: Version 1.19.1
Go: go1.9.2 darwin/amd64
Go Extension: 0.6.70 - 19th December, 2017

**Comment by MikeMangialardi** [comment]
I did a little more investigating, and it seems that this only occurs when I run VSCode from a zsh shell; when I open VSCode from a bash shell, it works as expected.

**Comment by ramya-rao-a** [comment]
There is some existing issue with zsh which we haven't been able to resolve yet. See https://github.com/Microsoft/vscode-go/issues/1133#issuecomment-349174335. Looks like the GOPATH doesn't get passed from .zshenv to VS Code extensions.

To confirm that, can you check if the GOPATH you see from the below ways match?
- `echo $GOPATH` in your zsh shell
- `echo $GOPATH` in the integrated terminal of VS Code when VS Code has been opened from the zsh shell
- Run the command `Go: Current GOPATH` from the command pallet

I am assuming that you haven't set the `go.gopath` or `go.inferGopath` settings
