### ISSUE TITLE
Keywords and Storage.types have the same color in Dark theme for Go

### ISSUE THREAD

**Issue by sullyme** [Microsoft/vscode-go#1439]
These are the colors in **X IDE:**

![image](https://user-images.githubusercontent.com/18464442/34537646-7ec7246a-f0c9-11e7-880b-bd76964317b7.png)

This instead in my **VSCode**:

![image](https://user-images.githubusercontent.com/18464442/34537686-9caa0c4a-f0c9-11e7-91f7-08a72d5dfb5d.png)

How can I format colors of my code better?

Eg: `chan` and `int` have the same color!

**Comment by smt923** [comment]
This isn't really an issue for this project, some vscode syntax themes have more or less color stuff, here is my vscode + vscode-go + [the brilliant Dracula theme](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula) (plus I have ligatures in the font but that's unrelated)

![syntax](https://i.imgur.com/TuOFl9G.png)

You'll have to find another color theme that has more colors I think there's a vscode dark plus, or if you want one more like your old theme there's plenty of monokai and monokai variant themes on the marketplace for vscode

**Comment by sullyme** [comment]
Thanks a lot. That screenshot (https://user-images.githubusercontent.com/18464442/34537686-9caa0c4a-f0c9-11e7-91f7-08a72d5dfb5d.png) is from Visual Studio Code Dark+ theme which I love. Monokai is more grey... and Dracula I don't like it: too many lines.

Now I will go with Monokai. But I'm unhappy.

**Comment by ramya-rao-a** [comment]
Thanks @smt93 for chiming in!

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#41822
