### ISSUE TITLE
Shorthand variable declaration is reformatted to label instead

### ISSUE THREAD

**Issue by Kyslik** [Microsoft/vscode-go#1440]
Given following code:

```go
func main() {
    s := "My string"
}
```

after saving it is reformatted to the following:

```go
func main() {
    s: = "My string"
}
```

with following syntax error:

> syntax error: missing statement after label

---

I am using:
- OSX 10.10 (Yosemite)
- VCS Version 1.19.1 (1.19.1) 
  - Go ext: 0.6.70
- Go go1.9.2 darwin/amd64

settings related to go:

```
"go.useDiffForFormatting": false,
"go.autocompleteUnimportedPackages": true,
"go.formatTool": "goreturns"
```

**Comment by ramya-rao-a** [comment]
I can't repro this...

Can you run the `goreturns` tool from the command line on your file and see if does the same?

**Comment by Kyslik** [comment]
Hmm using `$ goreturns main.go` works as expected.

My whole config is following:

```
{
    "editor.fontSize": 15,
    "extensions.autoUpdate": false,
    "files.autoSave": "off",
    "go.useDiffForFormatting": false,
    "go.autocompleteUnimportedPackages": true,
    "go.formatTool": "goreturns"
}
```

I am really confused what is going on here, any ideas? Any logs I can provide?

**Comment by Kyslik** [comment]
@ramya-rao-a Well it was another extension that caused this... 

I went and disabled extensions one by one.

Thank you for caring.

**Comment by ramya-rao-a** [comment]
Glad you found the root cause, Happy Coding!
