### ISSUE TITLE
Browse packages error incorrectly suggests running "go list all" when "gopkgs" is used

### ISSUE THREAD

**Issue by mastercactapus** [Microsoft/vscode-go#1441]
While digging into why unimported packages were no longer auto-completing on my machine, I came across an error message that seems out-of-date and could have saved some debugging time.

The error is displayed when package listing fails. (e.g. from the `Go: Browse Packages` command)

The current message reads:
```Could not find packages. Ensure `go list all` runs successfully.```

It should read (assuming we're not using the `--format` option):
```Could not find packages. Ensure `gopkgs` runs successfully.```

`go list all` worked fine, but my issue actually seemed to be caused by `gopkgs` failing to run.

As for the auto-complete issue, I'll link it here for reference in case anyone else runs into it in the meantime.
uudashr/gopkgs#3

To reproduce **this** error, follow the steps in the above `gopkgs` issue, then run `Go: Browse Packages` in vscode (with the go extension & tools installed).

I haven't had a chance to make sure `gopkgs` is always the command that's run (i.e. if gopkgs is missing), and/or if the `--format` option is used (since the error should probably reflect what is actually executed). If someone knows the answer to that offhand it may be a really quick fix, otherwise I may be able to dig in this weekend.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @mastercactapus!

I've update the error message with https://github.com/Microsoft/vscode-go/commit/300510e74aceb881817336f1f39f7b160af3042e

> I haven't had a chance to make sure gopkgs is always the command that's run (i.e. if gopkgs is missing), and/or if the --format option is used 

If the `gopkgs` is missing or doesn't support the `-format` flag then an appropriate prompt will be shown. See https://github.com/Microsoft/vscode-go/blob/0.6.70/src/goPackages.ts#L27 and https://github.com/Microsoft/vscode-go/blob/0.6.70/src/goPackages.ts#L35

So the only pending thing to do is to fix the upstream issue that you have logged.

cc @uudashr

**Comment by uudashr** [comment]
Solved. Please update the gopkgs.

**Comment by ramya-rao-a** [comment]
@mastercactapus You can run `Go: Install/Update Tools` command to update the dependent Go tools.
You can also update just gopkgs by using `go get -u https://github.com/uudashr/gopkgs`.

Let us know if this solves the issue and you get the autocompletion working as expected for unimported packages

**Comment by mastercactapus** [comment]
@ramya-rao-a looks like the gopkgs update fixed the autocomplete issue!

**Comment by ramya-rao-a** [comment]
Great! Happy Coding!
