### ISSUE TITLE
No Symbols Found

### ISSUE THREAD

**Issue by arashbina** [Microsoft/vscode-go#1442]
I am using version 1.19.1 with latest Golang plugin on macOS High Sierra.
When I try to get the list of symbols it says "No Symbols Found".

**Comment by arashbina** [comment]
Things I have tried:

- Completely remove vscode and all cached, associated files and reinstall
- enable/disable/reload plugin
- Starting vscode from terminal

Nothing has helped so far.
Version of go I'm using is 1.9.

**Comment by ramya-rao-a** [comment]
- Can you share a sample code where you can consistently repro this?
- How are you trying to get the list of symbols?
- Any errors from Help -> Toggle Developer Tools -> Console?

**Comment by arashbina** [comment]
The issue for me is not specific to a particular project. I have included a small piece of code below. It doesn't show any of the functions for me when I trigger the "Go to symbol in file" using `shift-command-o`. I don't see any errors in the console.

```
package main
   
import "fmt"

func main() {
	HelloWorld("hello")
}

func HelloWorld(message string) {
	fmt.Println(message)
}

**Comment by ramya-rao-a** [comment]
Am not able to repro...

Do you have the `go-outline` tool installed? Look for it in your $GOPATH/bin or if you have set the `go.toolsGopath` setting, then look for it under that path

**Comment by ramya-rao-a** [comment]
Are other features of the Go extension working? Like Go to definition, code completion?

Are you using the language server? i.e have you set `go.useLanguageServer`?

**Comment by arashbina** [comment]
I had the `go-outline` installed and I was not using the language server.
However I updated all the go tools that the vscode uses that are provided [here](https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on) and that fixed the issue. Thanks for pointing me to the right direction. I will close the issue.

**Comment by ramya-rao-a** [comment]
Another alternative to updating the dependent Go tools is to run the command `Go: Install/Update Tools`

Glad to know that things are working for you now, Happy Coding!
