### ISSUE TITLE
The setting of "go.toolsGopath" is not working in version: 0.6.71.

### ISSUE THREAD

**Issue by cylof22** [Microsoft/vscode-go#1443]
The VS code always search the default folder /user/../go.

**Comment by ramya-rao-a** [comment]
Works as expected for me..

> The VS code always search the default folder /user/../go.

Can you share a screenshot of what made you come to this conclusion?

Are you talking about `go build` looking for packages in the default folder?

**Comment by cylof22** [comment]
The go.tools.Gopath is ok when the folder is added to a workspace. However, it fails when opening the code folder separately.

**Comment by ramya-rao-a** [comment]
> it fails when opening the code folder separately.

Sorry, I don't understand. Can you elaborate with examples?

**Comment by cylof22** [comment]
The problem is reproduced again. The setting file is {
"[go]": {
    "editor.insertSpaces": false
},
"go.buildOnSave": "workspace",
"go.lintOnSave": "workspace",
"go.vetOnSave": "workspace",
"go.buildTags": "",
"go.buildFlags": [],
"go.lintTool": "golint",
"go.lintFlags": [],
"go.vetFlags": [],
"go.coverOnSave": false,
"go.useCodeSnippetsOnFunctionSuggest": false, 
"go.formatTool": "goreturns",
"go.formatFlags": [],
"go.gopath": "/Users/caoyuanle/Documents/neural-style/neural-style-server",
"go.gocodeAutoBuild": false,
"go.toolsGopath": "/Users/caoyuanle/Documents/gotools",
"go.goroot": "/usr/local/go",
"go.autocompleteUnimportedPackages": true
}.

However, the plugin always search the gotools under the /Users/caoyuanle/Documents/neural-style/neural-style-server/bin, not the /Users/caoyuanle/Documents/gotools.

**Comment by cylof22** [comment]
@ramya-rao-a The error can be reproduced by opening a parent folder of the code folder. For example, When opening the neural-style-server directly, no problem happens. If you open the neural-style, then the warning about the 'Analysis Tools warning' can be seen at the low-right corner.

**Comment by cylof22** [comment]
Is there any special setting for the work space when a go code folder is added to the work space for the 'go.toolsGopath'?

**Comment by ramya-rao-a** [comment]
The usage of `go.toolsGopath` in the Go extension does not depend on what folder is opened in VS Code.

Are you sure the below binaries exists under `/Users/caoyuanle/Documents/gotools/bin`?
```
       'gocode',
	'gopkgs',
	'go-outline',
	'go-symbols',
	'guru',
	'gorename',
	'godef',
	'godoc',
	'goreturns',
	'golint',
	'dlv'
```

**Comment by heila** [comment]
I have exactly the same issue. I am using version 1.19.2 of vs code. Only the GOROOT and GOPATH are searched for the tools and not the  "go.toolsGopath" I explicitly set.

**Comment by ramya-rao-a** [comment]
@heila Can you check if the tools listed in https://github.com/Microsoft/vscode-go/issues/1443#issuecomment-357475980 are under `<the-go-tools-goapht>/bin`?
