### ISSUE TITLE
Completion selection jump to the bottom

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode-go#1444]
Completion selection jump to the bottom
![completion-selection-jump-to-bottom](https://user-images.githubusercontent.com/166053/34658812-cfe120fa-f464-11e7-9e63-20b7bcc38c35.gif)

The selection supposed to be on the position 1, but it jump to position 3.

OS: macOS high Sierra 10.13.2
Version: Version 1.19.1 (1.19.1)

**Comment by ramya-rao-a** [comment]
Does the latest changes to [Intellisense](https://code.visualstudio.com/updates/v1_19#_smarter-intellisense) help explain what might be happening here?

**Comment by uudashr** [comment]
I see... unexpected. Sorting fine, but pre-selected... when I press enter I expect the first one, need to be more careful then.

It explain a lot.  @ramya-rao-a is there a way to disable this behavior?

**Comment by ramya-rao-a** [comment]
>  is there a way to disable this behavior?
I dont think so.

You can log a request in the vscode repo

Closing this issue as this is out of scope of the Go extension
