### ISSUE TITLE
Can not set breakpoint after start debug

### ISSUE THREAD

**Issue by eagyne** [Microsoft/vscode-go#1446]
Situation1 (works fine)
1. Set a breakpoint in a function.
2. Start debug the code.
3. When the function is invoked, then hit the breakpoint.

Situation2 (go wrong)
1. Start debug the code
2. Set a breakpoint in the line the same with situation1, and the breakpoint is unverified
3. Nothing happened when the function is invoked.

my env:
windows 10
go version: go1.9.2 windows/amd64
VSCode: 1.19.1
dlv version: 1.0.0-rc.2
dlv Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c $
logs:
[s1-vscode-go-debug-set-bp-before-start.txt](https://github.com/Microsoft/vscode-go/files/1611154/s1-vscode-go-debug-set-bp-before-start.txt)
[s2-vscode-go-debug-set-bp-after-start.txt](https://github.com/Microsoft/vscode-go/files/1611155/s2-vscode-go-debug-set-bp-after-start.txt)

**Comment by ramya-rao-a** [comment]
the issue about not able to set breakpoints when the program is running is discussed in https://github.com/Microsoft/vscode-go/issues/473#issuecomment-334901004 and is an issue with delve itself. See https://github.com/derekparker/delve/issues/982

**Comment by eagyne** [comment]
Thank you @ramya-rao-a
