### ISSUE TITLE
Google App Engine and Delve

### ISSUE THREAD

**Issue by pjebs** [Microsoft/vscode-go#1448]
I want to use vscode-go + delve debugger with Google App Engine.
There is an old article that shows how to do it: https://medium.com/@dbenque/debugging-golang-appengine-module-with-visual-studio-code-85b3aa59e0f

This article is essentially a crude "work-around".

Since Nov 15 2017, a "work-around" is no longer needed: https://cloud.google.com/appengine/docs/standard/go/release-notes

The `--debug` flag can be used with `goapp serve` (the command to run GAE Go programs locally).

The steps are:

- run `goapp serve --debug`
- run `ps aux | grep _go_app` (to find the pid)
- run `sudo gdlv attach <pid>`
- Add breakpoint: `b <file location>:<line num>` (in gdlv)  (gdlv is a graphical version of the basic dlv)

How can I get it to work with VSCode. I require VSCode to not attempt to run the app. I need VSCode to attach to delve instead.

Alternatively, if VSCode must run the app, then it should execute `goapp serve --debug` with the working directory set to the project location.

**Comment by pjebs** [comment]
NB: In GAE, `goapp` serves the purpose of `go` program.

**Comment by ramya-rao-a** [comment]
@pjebs 

We can attach to an already running headless dlv instance using the [remote debugging feature](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#remote-debugging)

Does that help?

**Comment by pjebs** [comment]
I suspect it will work but currently I'm not using GAE. When I use it again in a few months, I will test it out. based on the article you linked, I suspect it will work.

**Comment by ramya-rao-a** [comment]
In that case, I'll close this issue. If you find any issues getting the remote debugging setup to work, pease log a new issue.

Thanks and Happy Coding!
