### ISSUE TITLE
[suggestion/ask for help] Pop up before prepare data for `go.import`

### ISSUE THREAD

**Issue by szyhf** [Microsoft/vscode-go#1450]
If there lots packages in `GOPATH/src`, while using `go.import`, the `dialog` for search always pop up after seconds delay. Then while waiting the `dialog` pop up, I always type the keyword I want to search in current editor, then the `dialog` show up.

That case lots of mistake type while focus on working.

I think its preparing data for search, but how about pop up as soon as press the hotkey of `go.import`, and user can type the keyword for search  immediately while the background prepare the data for search.

I tried to fix it by myself but failed unless delete some of go packages.

Thanks a lot for helping 0.0

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.81)

**Comment by szyhf** [comment]
Really happy to see that and thanks a lot ~
