### ISSUE TITLE
when I update the 0.6.72(#1447),formatting doesn't work until goreturns is updated

### ISSUE THREAD

**Issue by wangjieyanda** [Microsoft/vscode-go#1452]
Hi,
 em,when I update the 0.6.72,the vscode formatting never work,I cannnot write code with the ide.How can I solve  the problem? thanks!

**Comment by jsmouret** [comment]
Running the command "Go: Install/Update Tools" fixed it for me.

**Comment by ramya-rao-a** [comment]
Is there any error that shows up? Any notification?

**Comment by natefinch** [comment]
Try reinstalling the plugin.  Mine had a missing file somehow... uninstalling and reinstalling the plugin fixed it.

**Comment by braneof** [comment]
Uninstalling and reinstalling didn't work for me. I just updated VS Code also today to 1.19.2. On Ubuntu.

**Comment by charles-d-burton** [comment]
I'm experiencing the same problem.
VSCode: 1.19.2
OS: Ubuntu
Go Plugin: 0.6.72

My settings look like this:
`{
    "git.confirmSync": false,
    "git.enableSmartCommit": true,
    "files.autoSave": "off",
    "editor.formatOnSave": true
}`
 
The behavior I'm getting is no formatting on save, imports don't update, the code doesn't format.

**Comment by ramya-rao-a** [comment]
The uninstall and install only helps if you see an error around failure to activate the extension in your console (Help -> Toggle Developer Tools -> Console)

I can repro this issue and am looking into it.

Until then the workaround is to either update the `goreturns` tool (You can do this by running `Go: Install/Update Tools) or by changing your formatting tool to "gofmt"

**Comment by ramya-rao-a** [comment]
The fix is out in version 0.6.73

**Comment by wangjieyanda** [comment]
thanks,it is ok now
