### ISSUE TITLE
Return of the "Unverified Breakpoint"

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode-go#1453]
VSCode Insiders 1.20.0
Go 1.9.2
macOS 10.13.2 High Sierra

As per the msg from Ramya in #360, I am opening this fresh issue.

I am having problems setting breakpoints in some non-main Golang code. In particular, though I don't know if it is significant, the breakpoints I am setting in String() methods (implementing the Stringer interface) are showing "Unverified Breakpoint". I am now in a position where I don't know if my String() implementations are failing because of my error of because the breakpoints are failing.

**Comment by ramya-rao-a** [comment]
Can you share sample code that I can use to get a repro?
Also set `"trace": "verbose"` in your debug configuration and try again. Can you share the logs that then get printed to the debug console?

**Comment by carlca** [comment]
The problem seems to be variable in that after I closed down and restarted VSCode just a couple of seconds ago, the breakpoints came back to life. I haven't seen the failure since. If It does reoccur, I will carry out the trace as you suggested.

**Comment by ramya-rao-a** [comment]
In that case, you can re-open this issue when you see the problem again and share the logs
