### ISSUE TITLE
`No definition found for "someName"` after 0.6.72

### ISSUE THREAD

**Issue by Skinass** [Microsoft/vscode-go#1454]
Hello!
I found my "jump to definition" stops working after 0.6.72
It does work for definitions in the same file, but it does not search for definitions made in other packages.
I didn't change any settings after last update. 
Here some of them:
"go.gopath": "${workspaceRoot}:${workspaceRoot}/vendor",
"go.docsTool": "godoc",  
Tried to use gogetdoc and guru as go.docsTool and it works better, but does not solve the problem in some cases.
However i'm wondering why godoc doesn't work correctly.
Project has the following structure:
── project (is the $workspaceRoot)
   ├── src
   └── vendor

**Comment by ramya-rao-a** [comment]
@Skinass Nothing around the definition feature was changed in the last 3 releases or so.

Open the console (Help -> Toggle Developer Tools -> Console) and see if you have any errors there from the `godef` tool after retrying the "jump to definition".

Then use the exact same call to `godef` from the command line.
