### ISSUE TITLE
Why I have no error in my VS-Code if I write a main.go like this?

### ISSUE THREAD

**Issue by johnunclesam** [Microsoft/vscode-go#1455]
Why I have no error in my VS-Code if I have a `main.go` like this:

https://github.com/jinzhu/gorm/issues/1720

My VS-Code doesn't complain at all.

Isn't this strange?

**Comment by tw1nk** [comment]
No, in the init function you declare a new local variable `db` that shadows the global `db` variable in the function scope, the normal linter does not give you any information of this. 

However if you configure vs-code to use gometalinter it will give you the warning "'declaration of "db" shadows declaration at main.go:17 (vetshadow)"

**Comment by ramya-rao-a** [comment]
Thanks @tw1nk!

@johnunclesam I hope that answers your question.
