### ISSUE TITLE
Latest release is showing as 0.6.73, which may not exist

### ISSUE THREAD

**Issue by JoeUX** [Microsoft/vscode-go#1457]
The changelog is showing 0.6.72 as the latest release, dated 2018-01-09.

The installed extension is showing as 0.6.73. Notably it was also showing this *before* I reloaded for the update (presumably to 0.6.72), so maybe it's been showing it for a while.

Windows 10 Pro 1709, 64-bit, Build 16299.192
VS Code 1.19.2

**Comment by ramya-rao-a** [comment]
The latest release is 0.6.73
It had a single bug fix around formatting and I didn't get around to updating the Changelog for just a single bug fix.
