### ISSUE TITLE
When gocode doesn't return any results, notify user that the problem may be solved by an update to the tool

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1459]
Quite a few times users have seen no auto-completion showing up. The problem is usually solved by updating `gocode`.

This issue is to to track a feature request to notify users that `gocode` is having problems which may be solved by an update to the tool.

This can be shown when say 10 consecutive requests to the completion providers results in no completions. The notification should be shown not more than once in a VS Code session.

PRs are welcome.

**Comment by santos22** [comment]
Hi @ramya-rao-a! I would like to take a look into this issue seeing as I too faced this problem 😅

**Comment by ramya-rao-a** [comment]
@santos22 You are most welcome to give it a try. If this is the first time working on this extension, then do read https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension

You can check the suggestion output returned from this [promise](https://github.com/Microsoft/vscode-go/blob/0.6.72/src/goSuggest.ts#L78) to see if consecutive requests are getting 0 suggestions

**Comment by knrt10** [comment]
@santos22 are you still working on this issue? If not, I would like to give it a try.

**Comment by ramya-rao-a** [comment]
Everyone, Thanks for your patience, this issue got lost in a sea of notifications and so I couldnt respond sooner :(

I created this issue in January when it made good sense to have this feature.

Since June, the original `gocode` is no longer suggested to be used. Instead we use its [fork](https://github.com/mdempsky/gocode) which has its own issues with external packages.  Plus, now with module support, things are still not stabilized.

And so, suggesting an update when `gocode` doesnt give results will not always work.

Therefore, I am closing this issue.

@knrt10, feel free to look at other issues marked as `help-wanted` and/or `good-first-issue`. 
[Building & Debugging the Go extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) is the place to start to have a local setup of this extension up and running.
