### ISSUE TITLE
Tools does't work on if there are opened files outside the current project

### ISSUE THREAD

**Issue by alxzh** [Microsoft/vscode-go#146]
I've noticed today that if I have project opened "Format code" works OK inside the project. But if I create a file outside the project and try to write some test code and format it - formatting stops working outside and inside project.

VSC version 0.10.3
go plugin 0.6.17 (latest as on today)

**Comment by newhook** [comment]
I cannot reproduce this.

**Comment by lukehoban** [comment]
Yeah - I can't repro this either.  

@alxzh - Could you reopen if you are still seeing this with any additional details?
