### ISSUE TITLE
VSCode intellisense text wrap not correct for godoc

### ISSUE THREAD

**Issue by YipingRuan** [Microsoft/vscode-go#1461]
Using VSCode 1.19.1 and extention GO 0.6.70

Not sure this is due to godoc itself or VSCode.
![image](https://user-images.githubusercontent.com/5492274/34925319-a0497ffc-f9e3-11e7-984a-bf1579140d69.png)

**Comment by ramya-rao-a** [comment]
I don't see this on my Mac or Windows

<img width="750" alt="screen shot 2018-06-01 at 2 04 09 pm" src="https://user-images.githubusercontent.com/16890566/40863444-b0ba82f0-65a4-11e8-9a38-fee0de05b79b.png">

Am using Go 1.9.2

Do you still see this?

**Comment by YipingRuan** [comment]
I am using go 1.10.3 and VS code 1.23.1 after update.
![image](https://user-images.githubusercontent.com/5492274/41214922-53b21dc8-6d80-11e8-8a08-7861054c1d7d.png)

**Comment by ramya-rao-a** [comment]
None of the settings touch how the hover text is rendered as far as I know...

Are you zoomed in?
