### ISSUE TITLE
please append gopath after inferredGopath

### ISSUE THREAD

**Issue by di3663** [Microsoft/vscode-go#1462]
Normally `GOPATH` is not the same with `GOROOT`, vscode can always find GOROOT libs, of curse. But vscode should alse find GOPATH and project libs.

I found that if "go.inferGopath" is true, then vscode can only find project libs, and ignore GOPATH, it dose not make sense.

I changed 

.vscode\extensions\lukehoban.go-0.6.73\out\src\util.js     line 353

from 

```
    return inferredGopath ? inferredGopath : (configGopath || process.env['GOPATH']);
```
to

```
    return inferredGopath ? (inferredGopath + ';' + process.env['GOPATH']) : (configGopath || process.env['GOPATH']);
```

seems works on windows.

**Comment by ramya-rao-a** [comment]
If you want to use the GOPATH as is, then why not use the `go.gopath` setting instead of `go.inferGopath`?

**Comment by di3663** [comment]
@ramya-rao-a 

then with new project open, need to modify GOPATH ?

**Comment by di3663** [comment]
then do i need restart vscode to reload GOPATH ?

besides, GOPATH should be one path for installation of cmd packages.

**Comment by ramya-rao-a** [comment]
So from what I could understand, you have
- one GOPATH where you install some common cmd packages
- different GOPATH for each of your projects

Is that right?
