### ISSUE TITLE
Package test flags

### ISSUE THREAD

**Issue by SimonRichardson** [Microsoft/vscode-go#1467]
The ability to have different `go.testFlags` if running "run package tests" vs "run tests". It would be nice if we could have `go.testPackageFlags` so that it maybe possible to run things like benchmarking, but not run them for simple run testing.

If this is possible currently, it would be nice to know how and so we can document that setup. Alternatively if I get time I hope to make PR for this myself.

**Comment by ramya-rao-a** [comment]
#1522 is tracking the feature request to be able to run all benchmarks in current file/package using a separate set of codelens.

We will close this issue in favor of #1522 for which we will accept PRs.

Please subscribe to #1522 and Happy Coding!
