### ISSUE TITLE
Go extension not working

### ISSUE THREAD

**Issue by adamfill28** [Microsoft/vscode-go#1468]
i installed the go extension, but when i try to write code, i get the following messages:

"The "gopkgs" command is not available. Use "go get -v github.com/uudashr/gopkgs/cmd/gopkgs" to install."

"Cannot find "go" binary. Update PATH or GOROOT appropriately"

"The "gocode" command is not available. Use "go get -v github.com/nsf/gocode" to install."

Other extensions are working, so I am not sure why the Go extension is giving these errors.

**Comment by ramya-rao-a** [comment]
> "Cannot find "go" binary. Update PATH or GOROOT appropriately"

You are getting this error because the extension cannot find the Go binary. Do you have Go installed? Run `go env` in the integrated terminal in VS Code. What do you get?

The rest of the errors are about not finding Go tools that the extension depends on.
Please run the command `Go: Install/Update Tools` to install the required tools.

**Comment by adamfill28** [comment]
Thank you, I now have Go installed and I have updated the PATH and GOROOT and I was able to install most of the tools. but now i have a new issue:

when I am typing code, I am not getting any of the features i am supposed to be getting (no autofill, suggestions etc). 

go env returns this:
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Adam\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

I am not receiving and popups telling me to install tools or anything, so I am unsure as to why I am not getting any functionality. Thanks

**Comment by ramya-rao-a** [comment]
Does the output of the command `Go: Current GOPATH` match your GOPATH?

**Comment by smithaitufe** [comment]
@ramya-rao-a Hello, I have been experiencing similar issue for about 6 months now. It is discouraging though.

Following the thread, this is what I have

Running `go env` gave me this

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/smith/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build768730231=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

and running `Go: Current GOPATH` gave me a different thing
`/home/smith/Documents//projects/go`

I decided to set GOPATH in vscode to `/home/smith/go` which corresponds to the one returned by `go env`

Am I correct with this approach?

**Comment by ramya-rao-a** [comment]
@smithaitufe So in your case, VS Code figures out the expected GOPATH ($HOME/Documents/projects/go), but `go env` doesn't ?

**Comment by smithaitufe** [comment]
@ramya-rao-a Yea.

**Comment by ramya-rao-a** [comment]
When you run `go env` in the integrated terminal in VS Code, do you get expected GOPATH?

**Comment by smithaitufe** [comment]
@ramya-rao-a 
I got this response when I ran it in vscode
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/smith/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build678750223=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
However, in my `~/.profile`, I actually have this

```
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/Documents/projects/go
export GOBIN=$GOPATH/bin
```

**Comment by ramya-rao-a** [comment]
Have you changed the setting for either `go.gopath` or `go.inferGopath`?

> I decided to set GOPATH in vscode to /home/smith/go

Why would you want to do this if the GOPATH you want to use is `$HOME/Documents/projects/go`?

When you run `go env GOPATH` in an external terminal, do you get `/home/smith/go` or `/home/smith/Documents/projects/go`?

**Comment by smithaitufe** [comment]
@ramya-rao-a 
When I run `go env GOPATH` in an external terminal, I get this 
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/smith/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build684290367=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

```
The response pasted above corresponds to the one I get when I run the same command in vscode. 
And today, when I opened my golang project in vscode, after setting the `go.gopath` in vscode to the value of GOPATH when I run `go env`, vscode started installing some packages as you can find below
```
Installing 8 tools at /home/smith/go/bin
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  godef
  goreturns
  golint

Finished running tool: /usr/bin/go build -i -o /tmp/go-code-check .

Finished running tool: /usr/bin/go vet ./...

Installing github.com/uudashr/gopkgs/cmd/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing sourcegraph.com/sqs/goreturns SUCCEEDED
Installing github.com/golang/lint/golint SUCCEEDED

All tools successfully installed. You're ready to Go :).
```

It is possible that the system is not seeing the one in my `~/.profile` hence it defaults to `/home/smith/go`. 
What do you think?

**Comment by smithaitufe** [comment]
@ramya-rao-a  I think I was wrong. 

After installing those tools, it was still popping up some errors. I decided to change the `go.gopath` value in vscode to  `/home/smith/Documents/projects/go`. All is well now.

Thanks so much
