### ISSUE TITLE
Gopath in Extension Development Host

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-go#147]
_From @MattiasPernhult on December 7, 2015 9:8_

Sometimes when opening the Extension Development Host to debug custom extensions and the active file is a golang file it will give the following error:  **"Path must be a string. Received ..."**

The call stack looks like this:
![skarmavbild 2015-12-07 kl 10 07 35](https://cloud.githubusercontent.com/assets/7289303/11623039/601d84be-9cca-11e5-8281-97b8f3d27643.png)

As I mentioned this doesn't happens all the time.

_Copied from original issue: Microsoft/vscode#1061_

**Comment by egamma** [comment]
From the call stack it looks like this is vscode-go initiated.

**Comment by lukehoban** [comment]
I'm fairly certain this was fixed with f7a60c4adce567f96f60d3df8fd10568a6103b3a and/or 315722bdf4eb205b77a350e33ab5aac5f3b61125.  Could you upgrade to the latest `vscode-go` and verify?

**Comment by MattiasPernhult** [comment]
I have upgraded to 0.6.17 and it seems to work, thanks!
