### ISSUE TITLE
Working with code in a repo subdir?

### ISSUE THREAD

**Issue by adam-p** [Microsoft/vscode-go#1470]
I have an app (not distributable package) project that lives in a subdirectory. Like: `${workspaceFolder}/server`, and under that is `main.go` and various package directories.

The Go extension doesn't seem to like this arrangement. In the "Problems" pane there's a persistent "can't load package: package github.com/adam-p/example: no Go files in [path here]". That message is certainly true -- the Go files start in the "server" subdirectory, not top-level. 

When I run "Go: Build Workspace" I get the same error, followed by successes as the subdirectories build (with no executable being produced).

I've looked through the vscode-go settings and I don't see a way to tell it where to look for the code.  I've looked through the Go build flags and don't see anything that seems likely to help. I've created a VSCode build task that specifies `main.go` and works, but it doesn't make the extension build errors go away (of course).

Any pointers would be appreciated.

**Comment by ramya-rao-a** [comment]
If you can replicate the issue in a small code sample and share the code and the folder structure, I can attempt to figure out what is going on

**Comment by adam-p** [comment]
This should do it: https://github.com/adam-p/vscode-go-subdir

Build the workspace and check the Problems tab in the lower pane.

**Comment by ramya-rao-a** [comment]
That was simple enough :)
I have pushed a fix which should be out in the next update to the Go extension which should be in a week or so

**Comment by ramya-rao-a** [comment]
Just released an update (0.6.74) that has the fix for this issue. Thanks for your patience @adam-p!
