### ISSUE TITLE
When `gopkgs` fails to get packages, there is no user notification

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1471]
`gopkgs` is used to get packages that are used bu the auto-completion feature to provide the completions for unimported packages. When `gopkgs` fails, we log a message to the console (See https://github.com/Microsoft/vscode-go/blob/0.6.72/src/goPackages.ts#L103).

This is not enough, there should be a user notification about the same.

`gopkgs` gets called for every auto-completion request, but this error should not be notified for every request. Once for a VS Code session will do.

PRs are welcome

**Comment by mkorejo** [comment]
Hi @ramya-rao-a,

I made some changes for this issue but before a PR, I am trying to test/debug locally. Can you suggest a way to get `gopkgs` to fail such that the [console message](https://github.com/Microsoft/vscode-go/blob/0.6.72/src/goPackages.ts#L103) is generated? I can't seem to get that part of the code to run, or get that message to show in the Developer Tools Console.

I tried renaming the `gopkgs` binary on my machine so VS Code couldn't find it.  I got [this message](https://github.com/Microsoft/vscode-go/blob/a48be65e1e0b4eedf1e21595946085de7185b332/src/goInstallTools.ts#L150) to appear:
![image](https://user-images.githubusercontent.com/14164612/35606949-79fedfd2-0617-11e8-8063-7c509eab41fc.png)

Then tried ^Space, and actually it looks like I'm still able to get import suggestions somehow, but no console message:
![image](https://user-images.githubusercontent.com/14164612/35607088-2449ee46-0618-11e8-9b45-098593893bfb.png)
![image](https://user-images.githubusercontent.com/14164612/35607201-9931a7a8-0618-11e8-804c-d767696354fc.png)

Also played with GOPATH a bit but not sure how to simulate this issue.

Thanks very much for your work on this plugin!

**Comment by ramya-rao-a** [comment]
@mkorejo One simple way to make `gopkgs` fail would be to change `gopkgs` itself :) You can find the code for it in `GOPATH/src/github.com/uudashr/gopkgs/cmd/gopkgs`, make a change and run `go install` to make sure the binary updates. @uudashr might have better ideas though :)

**Comment by uudashr** [comment]
@mkorejo @ramya-rao-a 

Not sure how to make it fail. The empty result will happen only when there is no packages on the GOPATH or GOROOT, which kind a weird. This is more like a panic mode, things that impossible. It is possible but the go extension will also fail.

But if really want to make it fail
1. just modify the `GOPATH/src/github.com/uudashr/gopkgs/cmd/gopkgs` to return empty
2. or do it here https://github.com/Microsoft/vscode-go/blob/0.6.72/src/goPackages.ts#L16 to return empty

**Comment by ramya-rao-a** [comment]
Or maybe modify `gopkgs` to return empty array?

**Comment by mkorejo** [comment]
Two commits more than it should've taken but I think I got it. Thanks for the tips @ramya-rao-a and @uudashr! Hacking `gopkgs` was a simple and fun exercise. See PR #1528.
