### ISSUE TITLE
Produce zombies process when use "debug test" feature.

### ISSUE THREAD

**Issue by wudi** [Microsoft/vscode-go#1472]
Issue:
Use `debug test` feature will produce zombies process one by one. And can't kill it.

VScode: 1.19.2
OSVersion: macOS 10.13.2

Repetition steps:
1. Create test file like `lex_test.go` in any package, code below.
```go
package main

import "testing"

func TestBug(t *testing.T) {
	t.Log("Hello")  // Important! set breakpoint here.
}
```
2. Click `debug test` feature in the `TestZombies` above.

![wx20180119-135019](https://user-images.githubusercontent.com/3753615/35136652-b994f718-fd1f-11e7-8729-716ccfe4dac7.png)

3.Click the `stop` button when debug running and stop in the breakpoint.

![99b5fef4-4a29-4122-8ebf-3a5767bf7d84](https://user-images.githubusercontent.com/3753615/35136701-09087aa4-fd20-11e7-9b79-c250b8095b72.png)

4. And now produce and zombies process and can't kill it.
```sh
🍺 eagle [~] → ps -ef |grep debug
  501  3297     1   0  1:51PM ??         0:00.00 (debug.test)

🍺 eagle [~] → kill 3297

🍺 eagle [~] → ps -ef |grep debug
  501  3297     1   0  1:51PM ??         0:00.00 (debug.test)
  501  5512 57627   0  1:56PM ttys003    0:00.00 grep --color debug

🍺 eagle [~] → kill -9 3297

🍺 eagle [~] → ps -ef |grep debug
  501  3297     1   0  1:51PM ??         0:00.00 (debug.test)
  501  5600 57627   0  1:56PM ttys003    0:00.00 grep --color debug

🍺 eagle [~] → sudo kill -9 3297
Password:

🍺 eagle [~] → ps -ef |grep debug
  501  3297     1   0  1:51PM ??         0:00.00 (debug.test)
  501  5690 57627   0  1:57PM ttys003    0:00.00 grep --color debug
```

**Comment by eaglewu** [comment]
🍺 eagle [~] → ps -ef |grep 'debug.test' | wc -l
      39

🍺 eagle [~] → ps -ef |grep 'debug.test'
  501   591     1   0 Fri05PM ??         0:00.00 (debug.test)
  501  3297     1   0 Fri01PM ??         0:00.00 (debug.test)
  501  7928     1   0 Fri05PM ??         0:00.00 (debug.test)
...

**Comment by ramya-rao-a** [comment]
@wudi We've made changes in the past 2 months to gracefully detach the dlv debugging session which takes care of the killing the debug processes as well. 

If you still see this, please re-open this issue.
