### ISSUE TITLE
Find All References not working with golang

### ISSUE THREAD

**Issue by Macilias** [Microsoft/vscode-go#1473]
Hi, I´m used to IntelliJ Goland "Find Usage" feature, and found its counterpart to be "Find All Features" in VS Code. Sadly I found it not to be working, because the usage are not listed and you are faced with: "No results" while the usages are obviously there and get found by Goland.
I´m using: 
VS Code Version 1.19.2 on
MacOS: 10.13.2 (17C88) with the
Go 0.6.73 Extension and
go1.9.2 darwin/amd64

**Comment by Macilias** [comment]
I found the solution:
beside the go extension now also the language server is needed, which can be found here: https://github.com/sourcegraph/go-langserver
Its also worth mentioning that the description of the extension is wrong and tells you to set:
go.useLanguageServer = true, which leads to not working function call.
The solution is to remove the entry.

**Comment by ramya-rao-a** [comment]
By default, the Go extension uses the `guru` tool to find references. If you dont have `guru` installed and you run `Find All References`, you will be prompted to install the tool.
You can also see a `Analysis Tools Missing` warning on the bottom right corner which you can click and install the necessary tools. See https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on

Using the language server is another way of getting few features. See https://github.com/Microsoft/vscode-go#go-language-server-experimental
