### ISSUE TITLE
Not prompt for other package existing variables or functions

### ISSUE THREAD

**Issue by unix2dos** [Microsoft/vscode-go#1474]
```
import "goWebStudy/test1"

func main() {
	test1.TestA()
	test1.TestB()

	test1.   //this not prompt 
}
```

**Comment by ramya-rao-a** [comment]
Is the `test1` package installed? We use `gocode` for completions that looks at the packages under `GOPATH/pkgs` to give completions.

Run `go install goWebStudy/test1` to ensure that its installed and try again
