### ISSUE TITLE
Refactor does not work properly

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode-go#1475]
It is a pity. Refactoring a simple struct name does not work, if not the whole go/src folder is error free.
Currently it does not refactor and instead gives an error in a tool tip (3 sec to read a bunch of text!!!) because somewhere in an other project - not related to the current - there is an error. I find that rediculous.

Refactoring should work on the current project, no matter what!

**Comment by ramya-rao-a** [comment]
I am assuming you mean "renaming" when you say "refactoring".

The Go extension uses the `gorename` tool to give the renaming feature. Its the `gorename` tool that expects code to be error free. You can try running `gorename` from the command line and am sure it takes that much time and returns with the same error.

https://github.com/sourcegraph/go-langserver/issues/220 is the issue thats tracking a feature request for the Go language server to implement rename. If that get's through and is faster and better, then we can integrate the same here in the Go extension to VS Code
