### ISSUE TITLE
Tools not Installed problem

### ISSUE THREAD

**Issue by ukaric** [Microsoft/vscode-go#1476]
Really mind bending problem that I have with Windows 10.

This is the output of `go env`

My project is located at `E:\Code\Go\src\github.com\ukaric`

I have run `Install All` multiple times.

Each time the plugin complains that tools are not present when they are clearly installed.

I have tired running VS Code with from `cmd` in the directory that my code is located with `code . ` and by opening code manually then navigating to the directory with no success.

I have not set `go.gopath` in `settings.json`.

```
set GOARCH=amd64
set GOBIN=C:\Gocode\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Code\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

**Comment by ramya-rao-a** [comment]
- When you run the `Install All`, the output pane opens up with logs for each tools being installed as well as the location they are being installed to. Does that location match with your expected GOPATH?
- Run the command `Go: Current GOPATH`. Does that give you the expected GOPATH?

**Comment by ramya-rao-a** [comment]
Why are you removing the `go.toolsGopath`?
The Go extension doesn't keep track of where tools are installed. It looks for them in `go.toolsGopath` and then in the GOPATH and then in the PATH.

**Comment by ukaric** [comment]
I tried both with `go.toolsGopath` and without it the default settings same thing. It does not detect that the tools are installed whatsoever.

**Comment by ramya-rao-a** [comment]
That's weird. If you have set `go.toolsGopath`, then the extension should look for the tools first there.
Can you paste a screenshot of the Go extension complaining that it cant find the tools?

**Comment by ukaric** [comment]
Here are bunch of SS
![2018-01-23 1](https://user-images.githubusercontent.com/9012882/35275432-066c7354-0040-11e8-9707-84025c9a5517.png)
![2018-01-23 2](https://user-images.githubusercontent.com/9012882/35275433-068c2690-0040-11e8-97fe-c98ca61d235c.png)
![2018-01-23 3](https://user-images.githubusercontent.com/9012882/35275434-06a7b284-0040-11e8-8621-d917c08427c5.png)
![2018-01-23 4](https://user-images.githubusercontent.com/9012882/35275435-06c5f4ce-0040-11e8-8869-5c25fc4c317e.png)
![2018-01-23](https://user-images.githubusercontent.com/9012882/35275436-06e7004c-0040-11e8-8074-71e34bb856a0.png)

**Comment by ramya-rao-a** [comment]
In the last but one screenshot you show that `E:/Code/src/github.com` has the repos of the tools. Can you instead look at `E:/Code/bin` and check if you have the actual tools?

**Comment by ukaric** [comment]
Strangely enough `E:/Code/bin` is empty even after manually running `go get`

**Comment by ramya-rao-a** [comment]
That's why the Go extension keeps asking you to install the tools, because it cant find them in the `bin` folder!

Try deleting the repos corresponding to these tools (See this [list](https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on)) and try again

**Comment by ukaric** [comment]
@ramya-rao-a Thanks for the nudge in right direction after inspecting both user and system env vars i found that I had `GOBIN` explicitly set to other folder after deleting that and clearing `src` folder everything works. Once again thanks.

**Comment by ramya-rao-a** [comment]
glad to hear you figured that out :)
Happy Coding!
