### ISSUE TITLE
After a while I just see "Loading..." and no go features work anymore

### ISSUE THREAD

**Issue by Globegitter** [Microsoft/vscode-go#1478]
Running on 
```
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:57:21.071Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

with extension version `0.6.73`
OS: elementary OS 0.4.1 (based on Ubuntu 16.04)

At the beginning when I write some go code everything works fine, vs code formats my stuff, shows me errors on the fly, autocompletion as well as docs of functions etc. But then after a certain period of time (anything from 5-30min, most of the time closer to 5 though) all features just stop working and if I e.g. ask for autocompletion (via ctrl+space) I just see `Loading...`, same if I hove over a function to see its docs I just see `Loading...`

I tried to activate the languageserver and see if it would change things but it does not seem to have any impact.

Edit: One thing I do notice is that my vscode also starts to use a lot of CPU (80-90% on all my cores) impacting my system overall.

**Comment by ramya-rao-a** [comment]
Can you disable all extensions other than Go and see if you still have the issue? This is to eliminate the case that some other extension is interfering and causing the CPU load.

**Comment by Globegitter** [comment]
Disabling all other extensions seems to do the trick and now the go extension seems to work without any problems (at least has now for an hour or so).

So what is the best approach here? Enable extensions one-by-one and see when the issue starts appearing? Is this most likely just related to the CPU spikes?

**Comment by ramya-rao-a** [comment]
> Is this most likely just related to the CPU spikes

Yes, I believe so.

> So what is the best approach here?

- Run the command `Developer: Show Running Extensions`
- Click the Start Extension Host Profile button at the top right, it's the circle
- Reproduce the issue
- Stop profile
- You should be able see snapshots of CPU usage for each extension
