### ISSUE TITLE
Wrong syntaxhilighting when german umlaut in comment

### ISSUE THREAD

**Issue by ulrichSchreiner** [Microsoft/vscode-go#148]
hi,

when i use a german umlaut in a comment, the comment become's a new color:

![image](https://cloud.githubusercontent.com/assets/1642951/11625363/c23ab4e0-9cda-11e5-9085-ec312f237271.png)

**Comment by lukehoban** [comment]
Huh - I've tried this in a few contexts - and I can't reproduce this.  Do you have a file you can point me at where you see this?  Does it happen 100% of the time for you?   

Please re-open if you have any more details you can share.

**Comment by ulrichSchreiner** [comment]
You're right. It was a misconfiguration on my side. My atom-in-a-docker-container had the same behaviour, so i digged into the whole thing and the solution is to do a `locale-gen $LANG` inside my docker-container before starting `vscode` (or atom).
