### ISSUE TITLE
Is it possible to run all tools on a remote machine?

### ISSUE THREAD

**Issue by acroca** [Microsoft/vscode-go#1480]
I'd like to use vscode on one machine (local) but all tools and even source code on a remote headless machine.

The setup is basically to have two lightweight laptops for pure editing and a remote computer with everything else. I'd use one laptop at a time, if that matters.

So, all tools (linter, etc) and even the `go` binary should be executed on the remote server somehow, ssh I guess would be the best way.

So, is this something that can be done currently by configuration or using another extension?

**Comment by ramya-rao-a** [comment]
This is not possible in VS Code at the moment. But work is under way.
It is part of the Roadmap: https://github.com/Microsoft/vscode/wiki/Roadmap#for-extension-authors

Once we have good support from the core, we will be seeing how we can get Go support.

Closing this issue for now as there is no immediate work planned around this.
