### ISSUE TITLE
No go files in Microsoft VS Code issue

### ISSUE THREAD

**Issue by burzum0727** [Microsoft/vscode-go#1481]
Hello y'all
I recently downloaded golang and vs code. It's my first attempt to work on this language anyways. I have set the GOPATH and GOROOT correctly. Go extension installed as well and I can see them in my bin file however on problems part I'm receiving this error.
file: 'file:///Untitled-1'
severity: 'Error'
message: 'can't load package: package .: no Go files in C:\Program Files\Microsoft VS Code
'
at: '1,1'
source: ''
code: 'undefined'
What supposes to I do? I have no clue what should I put in vs code section.

**Comment by ramya-rao-a** [comment]
Can you run `go env` in a terminal and share the results?
What folder have you opened in VS Code when you got this error?

**Comment by burzum0727** [comment]
These are the results in terminal.

C:\Users\varg>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Users\varg\GoWorks
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

C:\Users\varg>
C:\Users\varg>file: 'file:///Untitled-1'severity: 'Error'message: 'can't load package: package .: no Go files in C:\Program Files\Microsoft VS Code'at: '1,1'source: ''code: 'undefined'
I tried without folder just created with a new file, in documents a new workplace and the path root. None of them worked.

**Comment by ramya-rao-a** [comment]
Can you share what's in your Output pane under the Go channel?
Press `Ctrl+Shift+u` to open the output pane
Select "Go" from the drop down thats on the top right corner of the output pane

**Comment by burzum0727** [comment]
there aren't written anything actually. I suppose that I didn't do some setting related to VS Code or my go workspace.

**Comment by ramya-rao-a** [comment]
Do you see the same when opening any of the Go projects under your GOPATH?

**Comment by burzum0727** [comment]
Unfortunately, I do not have any project yet. This one supposed to be mine first project but due to problems, I couldn't start yet.

**Comment by ramya-rao-a** [comment]
You will still have the code for all the Go tools you installed as part of the Go extension.
For example, you can open `E:Users\varg\GoWorks\src\github.com\ramya-rao-a\go-outline`

**Comment by burzum0727** [comment]
Finished running tool: E:\Users\varg\GoWorks\bin\golint.exe
e:\Users\varg\GoWorks\src\github.com\ramya-rao-a\go-outline\main.go:17: exported type Declaration should have comment or be unexported

Finished running tool: C:\Go\bin\go.exe vet ./...
e:\Users\varg\GoWorks\src\github.com\ramya-rao-a\go-outline\main.go:116: no formatting directive in Errorf call

Finished running tool: C:\Go\bin\go.exe build -i -o C:\Users\varg\AppData\Local\Temp\go-code-check github.com\ramya-rao-a\go-outline

**Comment by ramya-rao-a** [comment]
@okandas Please elaborate on whats not working for you in a separate issue. This current issue is about the error `can't load package: package .: no Go files in C:\Program Files\Microsoft VS Code` showing up on build.

@burzum0727 Thanks for reporting this issue, I can repro it by opening a new untitled file when no folder is open. I have pushed a fix which should be out in the next update to this extension next week. Until then, please avoid working with untitled files.

**Comment by burzum0727** [comment]
So you mean I can work now with the titled files? Because I do not understand the result from the output that I receive from your github file is an issue or a regular start up.

**Comment by ramya-rao-a** [comment]
> So you mean I can work now with the titled files

Working on titled files was never a problem. The output you shared in https://github.com/Microsoft/vscode-go/issues/1481#issuecomment-360434169 is the output of the processes that ran build, lint and vet on the file that was opened.

Go uses the concept of packages (the folder that contains the Go files). When you work on an untitled file, there is valid package that can be used for building which caused the issue.

**Comment by burzum0727** [comment]
Thank you for the help Mrs. Rao!

**Comment by ramya-rao-a** [comment]
Just released an update (0.6.74) that has the fix for this issue.
