### ISSUE TITLE
Adopt VSCode 1.20's new CodeAction type 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-go#1484]
VS Code 1.20 adds a new [`CodeAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1897) type that attaches additional metadata to code actions. This additional information is already being used in a few places:

* `CodeAction.kind` describes the kind of a code action (extract refactoring, quickfix, ...) Kinds are used for VS Code's new `refactor` command, and they are used to [setup keybindings for specific code actions](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_20.md#keybindings-for-quick-fixes-and-code-actions)

* `CodeAction.diagnostics` tells which errors a quickfix addresses. This is used to order quickfixes by severity

I suggest that you migrate this extension to use the new `CodeAction` type in order to enable support for these features.

Please let me know if you have any questions about the new API

**Comment by ramya-rao-a** [comment]
We now have refactor code actions which follow this model.

There is only one diagnostic for which we provide code action (the missing import), am adding some telemetry around this to check the usage as I have a hunch this is not used much because formatting in Go adds the missing imports.

**Comment by BertoMejia** [comment]
Are there any plans on adding other code actions? I use this all the time in other languages. It is extremely useful! It was a bit disappointing to see that it is non included in this Go extension.

Is there a UserVoice or similar feature request system that we can vote this up on?

**Comment by ramya-rao-a** [comment]
Any further work on the Code Actions will be taken up via the language server work that is going on.
No new work on this front is planned for the extension itself.

cc @stamblerre
