### ISSUE TITLE
Plugin makes code changes on "save"

### ISSUE THREAD

**Issue by trondhindenes** [Microsoft/vscode-go#1485]
If I create a new file ("main.go") and add the following:
```
package main
import (
	"github.com/gin-gonic/gin"
)
```
When hitting "save" the imports are actually removed. It might be because I haven't installed the dependencies or something, but still. No editor should just automatically make destructive changes upon save.

```
go version: go version go1.9.3 linux/amd64
ubuntu 17.10
vscode Version 1.19.2
Plugin version 0.6.73
```

**Comment by atjeff** [comment]
Hey @trondhindenes,

The import was removed because you aren't using it. This behavior happens because of the editor.formatOnSave in vscode. If you search your default settings you will see:

```
"[go]":  {
    "editor.insertSpaces": false,
    "editor.formatOnSave": true
  },
```

You can change formatOnSave to false to stop this behavior

**Comment by ramya-rao-a** [comment]
Or you can change the formatting tool that is being used to `gofmt` which doesnt remove unused imports
```
"go.formatTool": "gofmt"
```
The default tool that is used is `goreturns` that removes unused imports and adds missing imports
