### ISSUE TITLE
Asterisk seems to be treated specially in documentation preview

### ISSUE THREAD

**Issue by jawnsy** [microsoft/vscode-go#1486]
**Description**

Documentation preview requires an asterisk to be escaped, while `godoc` does not require the escaping. This is a pretty minor issue but I'd expect vscode-go to behave as close to `godoc` as possible.

**Actual behavior**

This comment:

```go
// ValidFileName returns nil if the string is a valid file name, or an
// error otherwise. If pattern is true, file glob patterns are permitted
// ("*" and "?", e.g. "abc*")
```

is rendered like so:

![actual](https://user-images.githubusercontent.com/52710/35525071-4f20a43e-04d8-11e8-9619-a8f2d8e060da.png)

Notice that the * is missing between "".

**Expected behavior**

`godoc -http` renders it like so:

![godoc](https://user-images.githubusercontent.com/52710/35525064-4aa133a6-04d8-11e8-9a5b-51b306bb1611.PNG)

I'd expect this to be correct, though I haven't read godoc spec.

**Workaround**

You can escape the * in the comment (`\*`), like so:

```go
// ValidFileName returns nil if the string is a valid file name, or an
// error otherwise. If pattern is true, file glob patterns are permitted
// ("\*" and "?", e.g. "abc*")
```

Then it appears to be rendered as expected:

![workaround](https://user-images.githubusercontent.com/52710/35525157-8de95508-04d8-11e8-88f4-4e74d273875d.png)

**Version info**

vscode-go 0.6.73

VSCode version info (OS: Windows 10):

```
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by ramya-rao-a** [comment]
Seems to be an issue with VS Code and not the Go extension.
I get similar issues on hover text when using typescript

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#42353

**Comment by ramya-rao-a** [comment]
Reopening as the upstream issue was closed

**Comment by ramya-rao-a** [comment]
I no longer see this issue with the latest VS Code

<img width="842" alt="Screen Shot 2020-01-27 at 4 56 01 PM" src="https://user-images.githubusercontent.com/16890566/73226742-fb10d080-4125-11ea-9960-4d9da1215e8d.png">
