### ISSUE TITLE
Debugging support on Windows

### ISSUE THREAD

**Issue by andrewrgoss** [Microsoft/vscode-go#149]
Is there any kind of timeline around when Go debugging support will be available through VSCode on Windows?

**Comment by lukehoban** [comment]
Not necessarily a timeline - but this is being tracked in https://github.com/derekparker/delve/issues/198 and https://github.com/derekparker/delve/pull/276. 

Technically, if you build Delve from that PR branch you should be able to use it with VS Code on Windows today.  But there is work still to complete and improve the Windows support for an experience that is on-par with the Linux and Mac support.
