### ISSUE TITLE
Option to use go-find-references for Find all All References 

### ISSUE THREAD

**Issue by jonbonazza** [Microsoft/vscode-go#1491]
I found this past issue #340 and I understand the problem, but in the current state, Find All References is completely unusable for large projects. The way I see it, we have a couple options here:
1. Take a page from JetBrains' book and index all the files in memory and update the index asynchronously when they change. This way, when you do a Find All References, you don't need to rerun guru and can just consult the index. This is the ideal solution in terms of performance, but also comes with an increase in memory usage, as well as being more rather to implement.
2. Add the option to use the old Find All References method. While not as accurate as Guru, at least it's usable. Some people (myself included) would much rather a slightly less accurate find all references feature that is fast than one that is more accurate but unbearably slow.

I'm not sure what everyone's thoughts are here, but I think option 2 should be easy enough to implement and expose as a configuration item until a better solution is discovered.

**Comment by ramya-rao-a** [comment]
Option 1 is what a language server ought to do, and we have a step forward in that direction. If you are not on Windows, you can try our support for the  [language server from Sourcegraph](https://github.com/Microsoft/vscode-go/blob/master/README.md#go-language-server-experimental). The issue with Windows support is tracked in https://github.com/sourcegraph/go-langserver/issues/113

Option 2 is definitely doable and am open to consider any PRs and help if anyone has questions.

**Comment by jonbonazza** [comment]
I actually implemented this already. I can submit a PR tomorrow.

**Comment by ramya-rao-a** [comment]
Great

**Comment by ijesonchen** [comment]
I tried Go Language Server but it seems has some problem, and Find All References still cost a few seconds (about half of gore?). 
BUT it seem can not find references when projects not in GOPATH. I don't know why. 
It cost half of a day. Any suggest?
Thank you.

**Comment by jonbonazza** [comment]
So I actually realized recently that if you don't have any vendored code, Find All References is actually really fast. It's when you have a lot of vendored code that its speed becomes an issue.

Is there a way to ignore the vendor directory when running Guru?

**Comment by ramya-rao-a** [comment]
@ijesonchen 

> Go Language Server is not a suitable solution, since it does not support multiple GOPATH.

The language server should support multiple GOPATH as far as I know. 
cc @slimsag and @keegancsimth to confirm.

Do you see the multiple gopath when running the command `Go: Current GOPATH`? That should be the same value passed to the language server

@jonbonazza That's a great find. I don't know if guru has a way to ignore the vendor code. Ask in the Gophers slack. Someone there must know.

**Comment by ramya-rao-a** [comment]
Given that the new language server work from Google will support the find all references feature, we are not inclined to support any new tool for the same feature.

Closing this issue.
