### ISSUE TITLE
Go: Generate Unit Tests doesn't respect the go build file ignore rule

### ISSUE THREAD

**Issue by gcoka** [Microsoft/vscode-go#1492]
Steps to Reproduce:

1. add a file which starts with "_" and don't write any code (omit package xxx line) 
2. Run "Go: Generate Unit Tests For Function" on another go file.
3. This message below will appear
`Parser.Parse source file: other file parser.ParseFile: /Users/bamboo/src/github.com/gemcook/xxxxx/service/_charge.go:64:6: expected 'package', found 'EOF'`

`_charge.go` has only commented lines.

**Comment by ramya-rao-a** [comment]
@gcoka What do you mean by "go build file ignore rule"?

**Comment by gcoka** [comment]
@ramya-rao-a 
I did mean this comment. 
<https://github.com/golang/go/blob/master/src/cmd/go/internal/test/test.go#L69>

In cmd/go doc, [this part](https://golang.org/cmd/go/#hdr-Test_packages)  shows `Files whose names begin with "_" (including "_test.go") or "." are ignored.`

**Comment by ramya-rao-a** [comment]
@gcoka Do you get the same error when running `gotests` from the command line?
