### ISSUE TITLE
Jump to declaration is too slow

### ISSUE THREAD

**Issue by JFixby** [Microsoft/vscode-go#1493]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.73

---

Steps to Reproduce:

1. Click on a variable or a function usage with Ctrl+<mouse click>
2. Takes 3+ seconds to jump to the variable declaration

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please share your settings related to the go extension (the ones starting with `go.`)
Does this happen with even with the simplest of code or only in large projects?

**Comment by chandradeepak** [comment]
I also face this. It happens in large projects.  In those cases some times disabling   "go.gocodeAutoBuild": false helps and makes it faster. But the problem with disabling this is , as we modify code and write new lines  "go to definition" no longer works or points to wrong variables.

**Comment by ramya-rao-a** [comment]
@chandradeepak  The `gocodeAutoBuild` setting is related to the auto-completion feature and has nothing to do with the `Go to Definition` feature. Are you having issues with auto-completion or `Go to Definition`?

**Comment by chandradeepak** [comment]
@ramya-rao-a , mostly go to definition . I often see so many process with code helper running as go binaries which makes the whole mac slow. They die after some time but they take while to die. I know this issue is been discussed in other issues but i think none of them are helping and this keeps happening. 

this is definitely an improvement which we can bring in vscode .

**Comment by ramya-rao-a** [comment]
@chandradeepak If you are not on Windows, then do give the [language server](https://github.com/Microsoft/vscode-go#go-language-server-experimental) a try. 

Which go binaries do you see the most that take up too much CPU cycles?
