### ISSUE TITLE
eval+copy on text selection

### ISSUE THREAD

**Issue by dolmen** [Microsoft/vscode-go#1498]
## Use Case
In Go code that interacts with an SQL database I often have code formatted this way:

```go
	const query = `` +
		`SELECT id, name` +
		` FROM products` +
		` WHERE active = 1` +
		` ORDER BY name`
	rows, err := db.QueryContext(ctx, query)
```

I often want to copy the SQL query to paste it elsewhere to run it. However, this requires as an intermediate step to remove the Go formatting.

## Request

So I request a feature that I would apply to the text selection the string expression of the query: it would evaluate the selection as a Go expression and copy the result value (`fmt.Sprint()` applied to the expression) to the clipboard. I call this feature "eval+copy".
If I select this:
```go
		`SELECT id, name` +
		` FROM products` +
		` WHERE active = 1` +
		` ORDER BY name`
```
I want this in the clipboard:
```sql
SELECT id, name  FROM products WHERE active = 1 ORDER BY name
```

**Comment by ramya-rao-a** [comment]
Though this would be a good feature to have for your scenario, this need not be under the scope of the Go extension. The same feature can be useful for other languages as well. I would suggest to have an independent extension for this feature.
