### ISSUE TITLE
Unnecessary warning when editing generated files

### ISSUE THREAD

**Issue by tilinna** [Microsoft/vscode-go#1499]
Steps to Reproduce:

1. Use a Protobuf's protoc to generate a .go -file
2. Try to edit the generated file

Got:
A warning popup "This file seems to be generated. DO NOT EDIT."

Expected:
No constant warnings about the dangers of editing a generated file -- I can see the fact on the file myself, thank you. At least I would've expected a configuration option to turn the warning off (if there is one I couldn't find it).

**Comment by dolmen** [comment]
See #1295 for the original design of this feature.

**Comment by ramya-rao-a** [comment]
It's easy enough to add a "Don't show again" option to the prompt which should help your case.
PRs are welcome. I can help if anyone wants to take this up

**Comment by tilinna** [comment]
I think the whole feature should be made compatible with the [No Code](https://github.com/kelseyhightower/nocode).
