### ISSUE TITLE
where is console output (stdout)

### ISSUE THREAD

**Issue by jeromelaurens** [Microsoft/vscode-go#15]
Hi here, 
not sure it is an issue, probably more a question.
Where is the stdout console ? where we can see all the log.Print...
The logs are not in the terminal that launched VSCode
I'm on MacOSX.

Thanks
Jerome

**Comment by mattetti** [comment]
Same question here, I'm having issues with the debugger and wish I could see the output, I'm sure it's somewhere obvious that I just can't find :(

**Comment by jchannon** [comment]
View -> Toggle Output?

**Comment by mattetti** [comment]
@jchannon when I do that, it only shows the git output

**Comment by shurcooL** [comment]
After seeing [`console.log`](https://github.com/Microsoft/vscode-go/blob/eca07a3a3355f0038460830a6a876111271c141d/src/goPath.ts#L26), I was wondering the same thing.

I found it in the help menu, under "Toggle Developer Tools", on OS X.

![image](https://cloud.githubusercontent.com/assets/1924134/11257166/e14f38d6-8e04-11e5-8e2d-f195cd478f52.png)

**Comment by mattetti** [comment]
thanks @shurcooL but it looks like the debugger isn't logging anything when launching, I was having issues with the debugger because I didn't properly install dlv on OS X: https://github.com/Microsoft/vscode-go/issues/20

I did wish there was a way to see stdout output somewhere but it might be up to the extension you use.

**Comment by rudygt** [comment]
Same here,

the "Debug Console" is always empty after the execution of a simple hello world, if I put a breakpoint in the printf it stops there but the output is not show anywhere.

**Comment by jeromelaurens** [comment]
Thanks @shurcooL but we are talking here about the go program output when debugging. I tried to open the console from developer tools : the output is not showing.
Same behaviour as @rudygt  : the debug console always empty, but breakpoint works with variables.
I have other strange behaviour when debugging, but before posting them, I'd like to see the output.
About Delve, I have installed the latest version with the certificate, everything seems fine (I'm using it with intellig idea go plugin)

**Comment by lukehoban** [comment]
Agreed - this is a bug.  Redirecting the debugees output to the debug console is not yet implemented.

**Comment by jeromelaurens** [comment]
@lukehoban ok , some bugs of course but you've done a great job so far !

**Comment by rudygt** [comment]
@lukehoban I would like to help but, I'm starting with vs code, typescript and go, I see in this class https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts (line 127) a handler for the standard output of the debugProcess that just send the information to console.log, can you point me in the right direction to make it send the information to the debug console? or I'm lost.

Thanks!, nice work with this plugin.

**Comment by yuntan** [comment]
This change fixed the issue for me.
https://github.com/yuntan/vscode-go/commit/e3ec828ef9310800f59b214aba6f5a90dab7bd01

**Comment by rudygt** [comment]
Thanks @yuntan I was looking over the node debug adapter, https://github.com/Microsoft/vscode-node-debug/blob/master/node/nodeDebug.ts, the "_captureOutput" method does exactly that. 

:+1:

**Comment by lukehoban** [comment]
Great - thanks @yuntun.  Feel free to open up a PR for this work as well so we can work on getting these changes merged in.

**Comment by yuntan** [comment]
seems #41 is more clean solution for this problem.

**Comment by rudygt** [comment]
Thanks for your help @yuntan :+1:

**Comment by Stabledog** [comment]
It's August of 2017 -- almost 2 years later.  I just discovered and installed VScode for Mac, installed the C++ support, and I'm having this same problem in v1.14.2:  when my program writes to stdout, that does not show up anywhere in the debugger's output window.

This seems like a really basic behavioral deficiency that makes me wonder... "is anybody using this tool on the Mac?"  Am I missing some secret sauce to be able to see the output of my program while debugging?

**Comment by dcsan** [comment]
@Stabledog what's the correct incant for launch.json?

```
file: 'file:///Users/dc/dev/rikai/nlp-rnd/nlp-debug/.vscode/launch.json'
severity: 'Warning'
message: 'Attribute 'externalConsole' is deprecated, use 'console' instead.'
at: '13,7'
source: ''
```

![image](https://user-images.githubusercontent.com/514002/29999193-97fef038-9071-11e7-9568-b1bf133eca71.png)

using
```json
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [

    {
      "type": "node",
      "request": "launch",
      "name": "debug server",
      "program": "${workspaceRoot}/server.js",
      "externalConsole": false,
      "console": false
    }
  ]
}
```

**Comment by dcsan** [comment]
oh UPDATE:
works with the above with standard `console.log` but for some reason TJs' `debug` module doesn't output here. must be something to do with how the console.log is being hijacked fighting between these two.
