### ISSUE TITLE
Intellisense does not work

### ISSUE THREAD

**Issue by zerkms** [Microsoft/vscode-go#1500]
I understand it was reported million times already. And I spent enough time to give up to find the problem myself.

What I have:
vscode v1.20.0
go v1.9.4
vscode-go v0.6.73

```
➜ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/srv/work/go"
GORACE=""
GOROOT="/home/ivan/.local/share/umake/go/go-lang"
GOTOOLDIR="/home/ivan/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build769322194=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

The tools (like `gocode`) are installed, and are in the `$PATH`:

```
➜ which gocode
/srv/work/go/bin/gocode
```

In the preferences I have no parameters set for `go.`

yet, for this file

```
package main

import "fmt"

func main() {
	fmt.Println("qqq")

	fmt.
}
```
if I put a cursor after the `fmt.` and press `ctrl+space` it only shows the symbols from the current file, not the identifiers exported from the `fmt`.

`Go: Current GOPATH` command shows the same `GOPATH` value like the `go env` above.

How do I debug this problem?

**Comment by zerkms** [comment]
Solved.

I had to set the

```
"go.goroot": "/home/ivan/.local/share/umake/go/go-lang"
```

parameter in the preferences explicitly

**Comment by virtualdreams** [comment]
Thx, helped me alot.
