### ISSUE TITLE
test output in vscode 1.20 syntax highlighting

### ISSUE THREAD

**Issue by bryanl** [Microsoft/vscode-go#1501]
With 1.20 syntax highlighting in test output makes viewing unpleasant

![2018-02-08_10-11-38](https://user-images.githubusercontent.com/240/35980338-75b5f986-0cb8-11e8-89df-7317b52b7b8c.png)

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#43271
