### ISSUE TITLE
go build causes output window to take focus

### ISSUE THREAD

**Issue by ceriath** [Microsoft/vscode-go#1502]
When you build a package or the whole workspace, the output window of vscode is always taking the focus. This can be annoying sometimes.

According to https://github.com/Microsoft/vscode/issues/31474#issuecomment-319032829 it's the extension causing this and i would really like to see this fixed for vscode-go

**Comment by cheesedosa** [comment]
Check #1456. The fix should be out in the next release of the extension.

**Comment by ceriath** [comment]
woops, seems like i missed this when searching for an open issue regarding this.

**Comment by ramya-rao-a** [comment]
Just released an update (0.6.74) that has the fix for this
