### ISSUE TITLE
0.6.74 breaks all go-commands

### ISSUE THREAD

**Issue by btm6084** [Microsoft/vscode-go#1503]
0.6.74 (release today) seems to have broken all commands.

OS: Ubuntu 17.10

VS Code Info:
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:10:15.949Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Install latest version from extension menu (0.6.74) (08 Feb 18)
2. Run any "Go: " command from the command pallet. Observe "command 'go.gopath' not found", "command 'go.import.add' not found", "command 'go.benchmark.cursor' not found" ETC.

Downgrading to 0.6.72 tag by disabling auto-updates, downloading directly from github, and installing from VSIX returns it to a working state.

**Comment by ramya-rao-a** [comment]
@btm6084 Looks like the extension is not getting activated. Can you share the errors from the console? You can open the console by Help -> Toggle Developer Tools -> Console

**Comment by btm6084** [comment]
I re-upgraded and it seems to be working at the latest version. I replicated this 4 times in a row before I opened this issue, yet now I can't replicate it again.

I will close this ticket, and reopen if I can reproduce again in the future.

**Comment by ramya-rao-a** [comment]
Chances are that the original update resulted in a bad state.

**Comment by ahelal** [comment]
I am running `0.6.76` and experiencing the same issue. 
Thats what i get in Console

```
command 'go.gopath' not found
e.doShow @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2925
```

All the go commands fails.

**Comment by ramya-rao-a** [comment]
@ahelal Do you see any callstack for the error?
Try uninstalling the extension and installing it back

**Comment by ahelal** [comment]
@ramya-rao-a I uninstalled all my extensions and installed one by one and it worked.

Note sure what was the issue
