### ISSUE TITLE
go-langserver: `invalid root path "file://": must be file:/// URI`

### ISSUE THREAD

**Issue by Dominik-K** [Microsoft/vscode-go#1504]
In a new VSCode (`1.21.0-insider`, d28f0960) window, I opened a simple Go file `/tmp/vscode-test.go` and get the following error message popup:

<img width="896" alt="screen shot 2018-02-09 at 13 24 19" src="https://user-images.githubusercontent.com/5795847/36027700-a0078850-0d9c-11e8-9e88-e4408d686d2b.png">

(BTW: Would be good that the "output" channel will be shown in the message popup.)

It's from the activated `go-langserver` (current `master` version https://github.com/sourcegraph/go-langserver/commit/c0ef041f)

```
[Error - 1:19:09 PM] Server initialization failed.
  Message: invalid root path "file://": must be file:/// URI
  Code: 0 
langserver-go: reading on stdin, writing on stdout
--> request #0: initialize: {"processId":40939,"capabilities":{},"trace":"off"}
<-- error #0: initialize: {"code":0,"message":"invalid root path \"file://\": must be file:/// URI","data":null}
--> request #1: shutdown: null
<-- error #1: shutdown: {"code":0,"message":"server must be initialized","data":null}
```

**Comment by ramya-rao-a** [comment]
I can see this happening when opening a stand alone go file, but not when opening a folder. @Dominik-K, can you confirm?

**Comment by keegancsmith** [comment]
Yeah right now go-langserver doesn't support not having a rootPath or rootURI. I'll see how easy it is to add, but we have in quite a lot of places baked in the assumption of a rootPath.

**Comment by keegancsmith** [comment]
I'm unsure how well this would work, but we could just pretend that `rootPath = "/"`. For operations that inspect the `workspace` (like references), this would end up being very very costly. So it doesn't seem like the correct solution.

@ramya-rao-a what functionality is expected to work when there is no workspace? If we can rule out `references` and `workspace/symbols` that seems fine to me. If references are expected to work, in what scope? Just the current file / current directory / more (GOPATH?)

**Comment by ramya-rao-a** [comment]
We could start with just current directory and log the fact that we are doing so since going beyond is expensive.

**Comment by ramya-rao-a** [comment]
This issue was moved to sourcegraph/go-langserver#286
