### ISSUE TITLE
Folding breaks with brace-containing multiline strings

### ISSUE THREAD

**Issue by mrwonko** [Microsoft/vscode-go#1516]
Strings containing unindented braces break folding, which assumes the containing block ends at the opening brace inside the string. Take for example this code:

```Go
func foldMe() {
	_ = `if the braces inside the string are indented,
	{
		that's not an issue
	}`
	_ = `but multiline strings like this
{
	break folding
}`
	// there's no way to fold this code away
}
```

Trying to hide the implementation of `foldMe()` only hides everything up to and including the line containing `but multiline strings like this`.

**Comment by ramya-rao-a** [comment]
Code folding in VS Code is done based on indentation and spaces. It does not depend on any language or language syntax.

All contiguous lines that have the same number of spaces or tabs in the starting of the lines can be collapsed together

https://github.com/Microsoft/vscode/issues/3422 is tracking the work on making folding language aware
