### ISSUE TITLE
Support for `gotests` and `fillstruct` toolling

### ISSUE THREAD

**Issue by msoedov** [Microsoft/vscode-go#1519]
Hi guys do you have any plans to add https://github.com/davidrjenni/reftools/tree/master/cmd/fillstruct and https://github.com/cweill/gotests to the plugin? :grinning:

**Comment by ramya-rao-a** [comment]
gotests is already integrated. The commands `Go: Generate Unit Tests...` use it. 

For fillstruct we have a PR open #1506
