### ISSUE TITLE
Unable to run (without debugging) from VS Code

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode-go#152]
I am using Visual Studio Code on Windows, and as you mentioned `delve` isn't currently available for Windows.

I'm getting the following error when trying to run my Go project:

> Failed to continue: 'Cannot find Delve debugger. Ensure it is in your `GOPATH/bin` or `PATH`.'

I can't seem to find a way to just **compile and run the Go program from Visual Studio Code _without_ debugging**.  Is this currently possible?  Or, on Windows, can a Go program only be run from the command line currently?

**Comment by lukehoban** [comment]
Yes - there is no notion of "running" without "debugging" in VS Code today.  

In principle, we could have an option on the Go debugger which launches using the launch.json configuration (args, env vars, etc.) but does not attach a debugger.  

But I'd be interested in what the general VS Code model for this should/could be.

**Comment by tstringer** [comment]
Perfect, Luke!  I'm glad I wasn't missing something.  I guess the next best thing to do would be to just wait for `delve` support for Windows, and until then I'll just compile and run my Go programs through CLI.

**Comment by tapir** [comment]
Can't we have this feature? A simple 'go run' would be highly appreciated.
