### ISSUE TITLE
No local variables after upgrading to Go 1.10

### ISSUE THREAD

**Issue by torre76** [Microsoft/vscode-go#1520]
After upgrading to Go 1.10 on OSX, when I debug a project the *local variable* panel is always empty.

If I downgrade to 1.9, it works as usual.

**Comment by torre76** [comment]
![schermata 2018-02-17 alle 10 37 45](https://user-images.githubusercontent.com/3954720/36339850-9da5ea56-13ce-11e8-94b9-14c04b3524f4.png)

**Comment by torre76** [comment]
For completion, the trace log.

[vscode-go-debug.txt](https://github.com/Microsoft/vscode-go/files/1733831/vscode-go-debug.txt)

**Comment by ramya-rao-a** [comment]
@torre76 Can you run delve from the terminal and check if you are able to hit breakpoints and get the local variables when running the `locals` command?

**Comment by torre76** [comment]
![schermata 2018-02-18 alle 09 09 50](https://user-images.githubusercontent.com/3954720/36349661-912f650a-148b-11e8-9973-b9a110f8c210.png)

It seems that local variables is missing, maybe I open a cross bug to `dlv` project.

**Comment by torre76** [comment]
The problem has been solved by manually upgrade `dlv`.

Soon there will be a new official release that will be downloadable via package managers.

**Comment by ramya-rao-a** [comment]
Thanks for the follow up @torre76
