### ISSUE TITLE
feature request: go generate support

### ISSUE THREAD

**Issue by awreece** [Microsoft/vscode-go#1521]
It would be really nice to have proper support for go-generate: https://blog.golang.org/generate

Things that would be nice to have:
 - `go.generateOnSave`: Supported in the https://code.visualstudio.com/docs/languages/go#_build-lint-and-vet "buildOnSave" toolchain. Note that we'd probably want to generate code before formatting it, so that packages will build/import correctly.
 - `Go: Generate Workspace`: Command in the command pallette

This is a workaround:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "go:generate",
            "type": "shell",
            "command": "go generate ./...",
            "group": "build",
            "presentation": {
                "echo": true,
                "reveal": "silent",
                "focus": false,
                "panel": "shared"
            },
            "problemMatcher": "$go"
        }
    ]
}
```

It might be possible to add this to a default build target:

```
            "group": {
                "kind": "build",
                "isDefault": true
            }
```

But this isn't quite as good as filetype aware support in this plugin.

**Comment by lkarlslund** [comment]
Yes, I agree, it would be very nice to have this integrated. I'm using this:

https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave

With this config:

"emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.go$",
                "isAsync": false,
                "cmd": "cd ${fileDirname} && go generate ${file}"
            }
        ]
    },

You get no feedback of a go generate call fails :(

**Comment by ramya-rao-a** [comment]
This is being tracked in #263
Please add your comments there.
