### ISSUE TITLE
Ability to run all Benchmarks in a test file

### ISSUE THREAD

**Issue by lkarlslund** [Microsoft/vscode-go#1522]
Go testing support in this package is awesome. But it would be really cool if you had the abililty to:

run package benchmarks (if any *_test.go file had Benckmark* functions)
run file benchmarks (if current *_test.go file contains Benchmark* functions)

![image](https://user-images.githubusercontent.com/8929787/36369416-6d9aaee4-155b-11e8-9287-55a0f82f9711.png)

Also not show "run file tests" (if current *_test.go does not contain Test* functions.

**Comment by ramya-rao-a** [comment]
Showing all the 4 below by default would get noisy
- run package tests
- run file tests
- run package benchmarks
- run file benchmarks

So I propose the below
- Allow the `go.enableCodeLens` to take another property `runbenchmarks` with default value `false`
- Show the `run package benchmarks` and `run file benchmarks` only if the above is `true` and if there are benchmarks present in current file 

> Also not show "run file tests" (if current _test.go does not contain Test functions.

Sure we can do this, but is this a common scenario that a _test.go file which is essentially a test file will not have any tests?

PRs are welcome

**Comment by ramya-rao-a** [comment]
This should now be available in the latest update to this extension (0.6.90). Thanks to @biancarosa!
