### ISSUE TITLE
update `go.Vet` for 1.10 recommendations

### ISSUE THREAD

**Issue by lusis** [Microsoft/vscode-go#1526]
With release 1.10 it's recommended to run `go vet` instead of `go tool vet`:

https://golang.org/doc/go1.10#vet

**Comment by ramya-rao-a** [comment]
Thats good to know. PRs are welcome. The code to change would be in this file: https://github.com/Microsoft/vscode-go/blob/0.6.76/src/goVet.ts

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update (0.6.78) to the Go extension
