### ISSUE TITLE
Code Completion fails for getgb.io / slide based projects

### ISSUE THREAD

**Issue by conikeec** [Microsoft/vscode-go#153]
Hey

I have been attempting to migrate majority of my projects to getgb.io based vendoring/build system.
For any such projects, I use direnv to add the vendor folder (for the specific project) to $GOPATH  environment variable.

Where is $GOOT and $GOPATH being set.

My current alias to initiate Visual studio from the command line is 
# !/bin/bash

export GOPATH=$(PWD)/vendor:$GOPATH
VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*

Yet my $GOPATH is not being reset in visual studio to include the vendor directory

Am I missing anything here?

**Comment by sevein** [comment]
I've been experiencing this same issue with OSX and the fish shell. I've found that it only works when your launcher script exports a new environment variable that has not been defined before but it will fail with variables like `GOPATH` that were probably defined already. It could be related to @lukehoban's comment: https://github.com/Microsoft/vscode-go/issues/220#issuecomment-192095289.

Alternatively, I'm looking at defining `go.gopath` in my workspace settings, it works now but I think it'd be best when variables like `workspaceRoot` are expanded in settings so I don't have to use absolute paths. Related issues: https://github.com/Microsoft/vscode/issues/3759 and https://github.com/Microsoft/vscode/issues/2809.

**Comment by ramya-rao-a** [comment]
@conikeec @sevein 
There have been quite a few changes in both VS Code and the Go extension since last March.
Do you still have issues with GOPATH?

**Comment by ramya-rao-a** [comment]
Closing this issue as it is very old and we havent heard back from the OP.

@conikeec @sevein if you do have any updates, please comment here and I can re-open the issue
