### ISSUE TITLE
Generate Unit Tests for File not working with go1.10

### ISSUE THREAD

**Issue by alimac** [Microsoft/vscode-go#1530]
Steps to Reproduce on OS X:

1. cmd/Ctrl + shift + P, type "go test", select Generate Unit Tests for File

Error is "Generate unit tests feature is not supported as gotests tool needs go version 1.6 or higher."

After switching back to go1.9.4 feature works fine.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @alimac 
@uudashr's fix in https://github.com/Microsoft/vscode-go/pull/1523 should have fixed this.
Please check again after updating to the latest version of this extension (0.6.77)
