### ISSUE TITLE
extension become unavailable after upgrade the vscode

### ISSUE THREAD

**Issue by forthe2008** [Microsoft/vscode-go#1533]
os:win7

$ code -v
1.20.1
f88bbf9137d24d36d968ea6b2911786bfe103002
ia32

$ code --list-extensions
felixfbecker.php-intellisense
georgewfraser.vscode-javac
liximomo.sftp
lukasz-wronski.ftp-sync
lukehoban.Go
ms-mssql.mssql
ms-python.python
ms-vscode.azure-account
PeterJausovec.vscode-docker
rebornix.Ruby
redhat.java
trixnz.vscode-lua
vscjava.vscode-java-debug
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
xxxg0001.lua-for-vscode

![image](https://user-images.githubusercontent.com/24647448/36517990-9283412e-17bf-11e8-8765-c24cd9db86f2.png)

console.ts:123 [Extension Host] Here is the error stack:  Error: Cannot find module 'vscode-extension-telemetry'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (d:\Program\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Administrator\.vscode\extensions\lukehoban.go-0.6.77\out\src\util.js:11:38)
	at Object.<anonymous> (C:\Users\Administrator\.vscode\extensions\lukehoban.go-0.6.77\out\src\util.js:707:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)

I have try install and uninstall the extension, but failed.

**Comment by forthe2008** [comment]
I have fixed it by download these modules and put them into Microsoft VS\Code\resources\app\node_modules .

**Comment by caarlos0** [comment]
version 1.20.0 stopped working as well

**Comment by caarlos0** [comment]
I removed ~/.vscode and all folders related to vscode I found, reinstalled everything and it seems to work now.

**Comment by lzelevinsky** [comment]
I had the same problem, reinstalled extension, didn't help, 
uninstalled the extension, reloaded vscode,
rm -rf ~/.vscode/extensions/lukehoban.go-0.6.77/
reinstalled the extension
now it works.

**Comment by Southclaws** [comment]
I'm running into this currently on Windows, a couple of weeks ago everything worked perfectly but trying to work today and the extension just refuses to do *anything*. I'm not getting any linter output or static analysis. Going to attempt a backdate for now.

**Comment by franciscocpg** [comment]
https://github.com/Microsoft/vscode-go/issues/1533#issuecomment-368915785 worked for me.
Thanks @lzelevinsky.

**Comment by ramya-rao-a** [comment]
We are tracking this upstream in the VS Code repo.
There has been fixes made to the upcoming version of VS Code.
So the next time you update VS Code, you shouldn't be seeing this issue
