### ISSUE TITLE
extension does not handle command-line args that need to be passed to tests

### ISSUE THREAD

**Issue by dvelitchkov** [Microsoft/vscode-go#1534]
the `go test` supports passing command-line arguments to the test binary. To quote `go test -help`:

     In addition to the build flags, the flags handled by 'go test' itself are:
     -args
            Pass the remainder of the command line (everything after -args)
            to the test binary, uninterpreted and unchanged.
            Because this flag consumes the remainder of the command line,
            the package list (if present) must appear before this flag.

Sadly, the extension isn't aware of this rule, and adding any "-args" to the "go.testFlags" setting does not work, as the extension does not put such arguments last in the arguments list. 

Steps to Reproduce:

1. Write a test file:
```go

import (
    "flag"
    "os"
    "testing"
)

var dbCnn string

func TestMain(m *testing.M) {
    flag.StringVar(&dbCnn, "dbcnn", "", "database connection")
    flag.Parse()
    os.Exit(m.Run())
}

func TestReports(t *testing.T) {
    if dbCnn == "" {
	t.Fatal("db connection not set")
    }
}


```
2. Change Go settings:
```json
"go.testFlags": [
        "-args",
        "-dbcnn",
        "postgres://foo:bar@baz/abc"
    ]
```
3. Run test

Result:
```sh
Running tool: /usr/local/Cellar/go/1.9.3/libexec/bin/go test -args -dbcnn postgres://foo:bar@baz/abc -timeout 30s ***/server/db -run ^TestReports$

flag provided but not defined: -timeout
```
The error is because "-args" is not placed after all other args to `go test`. 

I think the correct solution would be to define a new setting - perhaps "go.testArgs" - an array of arguments to the test binary. 

I would love to work on this myself and submit a PR

**Comment by ramya-rao-a** [comment]
So instead of 

`go test -args -dbcnn postgres://foo:bar@baz/abc -timeout 30s ***/server/db -run ^TestReports$`

we should actually be running

`go test -timeout 30s ***/server/db -run ^TestReports$ -args -dbcnn postgres://foo:bar@baz/abc` ?

**Comment by dvelitchkov** [comment]
Sounds good, I'll try to get this in ASAP!

**Comment by rschmied** [comment]
Hey... I do face the exact same issue when clicking on the "run test" link next to a function in the editor... I want to pass extra args for the test but those have to be appended to the values that are being passed as defaults...

my go.testflags look like this:

```json
"go.testFlags": ["-args", "-logtostderr", "-stderrthreshold", "info", "-v", "4"],
```


e.g. this is what happens now:

```
Running tool: /usr/local/go/bin/go test -args -logtostderr -stderrthreshold info -v 4 -timeout 30s -run ^Test_getServerID$
```

and it *should* be like this:

```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^Test_getServerID$ -args -logtostderr -stderrthreshold info -v 4 
```

I think I could experiment with the code you pointed to above (testUtils.ts#L127) but I have absolutely no idea how I would even start to test those changes.

**Comment by ramya-rao-a** [comment]
@rschmied See [Building and Debugging the extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) to get the local set up and to debug the extension.

Also, wait a few days till October starts to send your PR to win a t-shirt! For more details, see https://open.microsoft.com/2018/09/18/hacktoberfest-2018-microsoft/?WT.mc_id=hacktoberfest-twitter-beverst

**Comment by ramya-rao-a** [comment]
The fix for this issue is now out in the latest update to the Go extension (0.6.92). Thanks @rschmied!
