### ISSUE TITLE
compile a list of useful tips

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#154]
I started to track things I need to research as I ramp up with VSCode: https://github.com/Microsoft/vscode-go/wiki/Usage-FAQ  Hopefully this will be useful to others and more will contribute.

Please let me know if you think a README PR would be more appropriate.

**Comment by lukehoban** [comment]
This is great - thanks for starting it!  I'll start adding things here when questions come up that are useful to record but don't necessarily make sense directly in the README.

If you wan to open a PR to add a link to the wiki page into the README in an appropriate place - feel free to do that.  We can probably close this issue once we've done that?
