### ISSUE TITLE
Create a lot of zombie processes on windows

### ISSUE THREAD

**Issue by Adirelle** [Microsoft/vscode-go#1541]
OS: Windows 7.1 64-bits
GO version: >=1.9.2
VSCode version: >=1.19
vscode-go version: 0.6.77
Settings:
```json
{
  "go.autocompleteUnimportedPackages": true,
  "go.toolsGopath": "E:\\Projets\\gopath",
}
```

Steps to Reproduce:

1. Starts VSCode.
2. Edit files, save, several times.
3. Open Windows Task Manager,
4. See that there is a lot of vet.exe processes.
5. Close VSCode.
6. vet.exe processes are still there. They have to be killed one by one or using `taskkill /f /fi "IMAGENAME eq vet.exe"`.

It goes worse if using gometalinter and/or live lint.

**Comment by ramya-rao-a** [comment]
Does this happen only on large projects? Can you try on a simple single file package?

**Comment by lggomez** [comment]
Could it be related to #1472, on how code handles the processes?

**Comment by Adirelle** [comment]
The project is ~5000 lines of code in less than 50 files.

I could not reproduce this bug with "golint" as go.lintTool (the default) as of Code 1.20.1, but it does happen with gometalinter, which does not work properly by the way, so maybe this is a gometalinter bug.

**Comment by ramya-rao-a** [comment]
@lggomez The Go extension spawns a single process that runs `gometalinter`. If there has been another save, then the previous process is killed. See https://github.com/Microsoft/vscode-go/blob/0.6.77/src/util.ts#L570

I am guessing `gometalinter` in turn spawns new processes to run the individual linters which are not getting killed, when the main process for the `gometalinter` is killed.

**Comment by ramya-rao-a** [comment]
@Adirelle We've made some progress on handling the multiple process being spawned for lint and vet features which should help.

Please feel free to re-open this issue if you still see the problem

**Comment by lggomez** [comment]
@ramya-rao-a coincidentally, I had this problem today with guru (10-15 processes eating 250-300MB each), I had to set go.enableCodeLens.references to false... altough it can be a separate issue

**Comment by ramya-rao-a** [comment]
@lggomez  Yes, please log a separate issue for that.
We know that guru is slow. So cant do much there.
But if VS Code sends a cancellation token and we (the extension) dont cancel the process, then that is something we can look into
