### ISSUE TITLE
command 'go.tools.install' not found

### ISSUE THREAD

**Issue by ansencumt** [Microsoft/vscode-go#1542]
![image](https://user-images.githubusercontent.com/5181385/36667068-a4a1dd32-1b27-11e8-8a91-d47b498ae7c2.png)

The vscode-go version is 0.6.77
The vscode version is 1.20.1
The golang version is 1.10

**Comment by ansencumt** [comment]
the extension output:
![image](https://user-images.githubusercontent.com/5181385/36667491-f8df1166-1b28-11e8-9536-92a6e7621c2d.png)

**Comment by ramya-rao-a** [comment]
Any errors in the console? Help -> Toggle Developer Tools -> Console

If there are any errors there saying something line `activation of Go extension failed` or that some modules are missing in the Go extension, then uninstall the extension and re-install it.

**Comment by carney520** [comment]
![image](https://user-images.githubusercontent.com/6149975/36707530-a1ac350a-1ba9-11e8-8433-be5f90938ec2.png)

**Comment by ramya-rao-a** [comment]
@carney520 Please try uninstalling and installing the extension again

**Comment by ansencumt** [comment]
I had to uninstall the extension, then go to the folder that vscode extension created and delete the extension folder. After finishing these steps, install the extension again.
It works!

**Comment by ramya-rao-a** [comment]
@ansencumt Did you recently upgrade VS Code? Are you on Windows?

**Comment by ansencumt** [comment]
@ramya-rao-a Yes.

I`m on Windows 10.

**Comment by ramya-rao-a** [comment]
@ansencumt And you recently upgraded VS Code? Just before upgrading VS Code, the Go extension was working fine?

**Comment by ansencumt** [comment]
@ramya-rao-a Yes, I upgraded my VS Code recently. It work fine before.

**Comment by ramya-rao-a** [comment]
This is an upstream issue with VS Code. See https://github.com/Microsoft/vscode/issues/43813

Current workaround has already been discussed i.e uninstall or manually delete the extension from the extensions folder and then re-install the extension.

Let's see if the next update to VS Code reduces the number of such issues
