### ISSUE TITLE
Support shortcut to handle errors

### ISSUE THREAD

**Issue by alwindoss** [Microsoft/vscode-go#1549]
This is a feature request:
A short cut to insert a piece of code that does the following

if err != nil {
    fmt.Printf("err") // an alternative to print too
}

**Comment by buyology** [comment]
https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by ramya-rao-a** [comment]
Thanks for the link @buyology!

@alwindoss You can use the snippet @buyology shared above or create your own snippets using the link he shared

**Comment by alwindoss** [comment]
Thank you for your comments.
I know of this snippet generator in code. What I am referring to is a shortcut like we have for `for range` loop. The shortcut is `forr`
The request is very specific to golang and it is something used very often when developing with golang too.
I suggest we keep this issue open.

**Comment by alwindoss** [comment]
Thank you Ramya for pointing it out. This is exactly what I was looking for. But if we need a handler for a snippet with print statement I will be happy to make the change and raise a PR
