### ISSUE TITLE
Intellisense filters comments from structure definitions; should be optional

### ISSUE THREAD

**Issue by dmick** [Microsoft/vscode-go#1550]
I see that https://github.com/Microsoft/vscode-go/blob/master/src/goExtraInfo.ts#L32 intentionally filters lines starting with "\t//", which means comments in structure definitions don't show up on rollover.  I think this behavior is undesirable and would like to petition for it to be made optional; the comments are what define the behavior and use of the fields, which is important info, especially in unfamiliar code where Intellisense does the most good.

**Comment by ramya-rao-a** [comment]
I tried commenting that line, but turns out both `godef` and `gogetdoc` skips the line that has only comments when returning the information that we need to show the text that you see on hover. I would suggest to log an issue with either or both of these tools.

On the other hand, if you are not on Windows, you can use the language server from source graph which doesn't seem to be skipping such lines. See https://github.com/Microsoft/vscode-go#go-language-server-experimental

**Comment by ramya-rao-a** [comment]
Fair enough. Feel free to send a PR.
By default we use a combination of `godef`+`godoc` tools to get the information that is shown on hover. Users can change this by either setting `go.docsTool` to `gogetdoc` or by setting `go.languageServer` to `true`

`godef` does not return the lines that have only comments. So even if you make change removing https://github.com/Microsoft/vscode-go/blob/master/src/goExtraInfo.ts#L32, there won't be any difference. But, if you choose to use `gogetdoc`, your change will result in the comments showing up on hover. If you choose to use the language server, it already shows the comments on hover

**Comment by dmick** [comment]
Yes, I noticed the behavior after trying to circumvent it with go.docsTool == gogetdoc, although, the comment filtering seems to be independent of tool?...  I don't know anything about the language server so will look.

**Comment by ramya-rao-a** [comment]
The comment filtering done in this extension is independent of the tool, so you can just remove it.
The language server doesnt need any changes, it already shows the line with comments

**Comment by dmick** [comment]
OK, concur, removing the filtering will only affect 'gogetdoc'.

**Comment by dmick** [comment]
I can't seem to run the tests, even on the unmodified master, and I'm not sure what I'm doing wrong.  Either launching from within 'code .' as documented or running 'npm test', I get "TypeError: Path must be a string. Received undefined"

I'm sure it's something to do with my environment, but, how to tell what?

**Comment by dmick** [comment]
(and is there an appropriate chat forum for such difficulties?)

**Comment by ramya-rao-a** [comment]
> TypeError: Path must be a string. Received undefined

Do you have GOPATH set as an env var? The tests dont run if there is no GOPATH set as env var.

> (and is there an appropriate chat forum for such difficulties?)

You can either ask the question here or on [gitter](gitter.im/Microsoft/vscode-go) or on the vscode channel in Gophers Slack

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update (0.6.78) to the Go extension
