### ISSUE TITLE
gometalinter with config using $workspaceRoot

### ISSUE THREAD

**Issue by giniedp** [Microsoft/vscode-go#1551]
i am trying to configure gometalinter using a configuration file that is located at $workspaceRoot

my first attempt was to use the following vscode settings

```json
  "go.lintTool": "gometalinter",
  "go.lintOnSave": "package",
  "go.lintFlags": ["--config", "${workspaceRoot}/.gometalinter.json"],
```

this does not work, since lintFlags are not evaluated for "${workspaceRoot}" substring.

Second attempt was to use toolsEnvVars like this

```json
  "go.toolsEnvVars": {
    "GOMETALINTER_CONFIG": "${workspaceRoot}/.gometalinter.json",
  },
  "go.lintTool": "gometalinter",
  "go.lintOnSave": "package",
  "go.lintFlags": [],
```

This runs the tool, but the tool ignores the configuration file. Unfortunately i can not verify the value of GOMETALINTER_CONFIG, so i am not sure whether this is an issue with vscode-go or the gometalinter itself. Am i doing something wrong?

besides that, we have the options `go.testEnvFile` and `go.testEnvVars` but we only have `go.toolsEnvVars` and no `go.toolsEnvFile`. Can we also get a `go.toolsEnvFile` option?

**Comment by giniedp** [comment]
i see that i grabbed an older version of gometalinter which does not make use of the GOMETALINTER_CONFIG env variable. The new version does work perfectly using the env variable.

**Comment by ramya-rao-a** [comment]
The right way to use the config is to set the lintFlag setting to `["--config=${workspaceRoot}/.gometalinter.json"]`

From `gometalinter -h`

> Flags:
  -h, --help                   Show context-sensitive help.
      --version                Show application version.
      --config=CONFIG          Load JSON configuration from file.
