### ISSUE TITLE
showLog does not show anything when delve runs in 'attach' mode

### ISSUE THREAD

**Issue by KingRikkie** [Microsoft/vscode-go#1552]
I was trying to work around the issue that VScode does not allow you to interact with your app via debugging-console (fmt.Scanln()...). I created a task that compiles and then starts my app in a new console window and afterwards attaches delve headlessly onto its PID (new window too). The task is specified under `preLaunchTask` in launch.json, everything else equals the default remote debug settings.

This works fine, however even with `--log` and `"showLog": true` set there will be absolutely no log-output.

Steps to Reproduce:

1. Build and run your app
2. Attach delve to the running process : `dlv attach XXX --headless --listen=:2345 --log`
3. Add a default "Go: Connect to server" launch configuration
4. Append `"showLog": true` to configuration
5. Start remote debugging in VScode
6. **No log-output is shown** despite a working remote debugging session

**Comment by ramya-rao-a** [comment]
`showLog` is used by the Go extension to start `dlv` with the `--log` flag
When attaching to an already running dlv process, there is no way I know of to pipe the output of the dlv process to VS Code.
You do get to see the logs in the terminal where you ran the `dlv attach` command though

**Comment by KingRikkie** [comment]
I though `--log` command would work the same way as it certainly is listed in the official documentation: https://github.com/derekparker/delve/blob/master/Documentation/usage/dlv_attach.md
