### ISSUE TITLE
Feature Request: Expand func types to func snippets

### ISSUE THREAD

**Issue by joncalhoun** [Microsoft/vscode-go#1553]
Given the code:

```go
type HandlerFunc func(ResponseWriter, *Request)
```

I would like to see an expansion setting in vscode-go for expanding `http.HandlerFunc` into one of the following (I'm impartial on which is used):

```go
http.HandlerFunc(func(arg1 http.ResponseWriter, arg2 *http.Request) {
	
})
```

or without the http.HandlerFunc prefix...

```go
func(arg1 http.ResponseWriter, arg2 *http.Request) {
	
}
```

Ideally the cursors would be at each arg, and then inside the function like so:

```go
func(${1:"arg1 http.ResponseWriter"}, ${2:"arg2 *http.Request"}) {
	$3
}
```

`gocode` returns enough information to do this, and it was done in Atom's Go package here: https://github.com/joefitzgerald/go-plus/pull/719

I'm willing to help with this, but have no experience working on extensions for vscode so I'll have to find some time and figure the basics out. I suspect the actual PR will be fairly small once I learn how to get going. 

Any suggestions on how to start developing the vscode-go extension are appreciated.

**Comment by ramya-rao-a** [comment]
@joncalhoun Basic set up steps are described here: [Building and Debugging the Go extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)

It assumes you have node installed.

Once you are set up, add a breakpoint at https://github.com/Microsoft/vscode-go/blob/0.6.77/src/goSuggest.ts#L154

For your case above, you will see that the `suggest` variable would have

<img width="424" alt="screen shot 2018-03-03 at 9 11 59 pm" src="https://user-images.githubusercontent.com/16890566/36942476-9a05a97c-1f27-11e8-8bc3-8cdf2c97ab03.png">

So when `suggest.class == 'type' && suggest.type.startsWith('func(')` (or do a regex check), you can then build your snippet. 

Checkout https://github.com/Microsoft/vscode-go/blob/0.6.77/src/goSuggest.ts#L169-L186 to see how we build snippets for functions

Let's re-use the settings `useCodeSnippetsOnFunctionSuggest` and add these snippets only if that setting is enabled.

Good luck! Let me know if you have any issues. You can also ping me on the gophers slack

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.80)
