### ISSUE TITLE
Error underlining

### ISSUE THREAD

**Issue by JustTestingGo** [Microsoft/vscode-go#1556]
I have a strange behaviour with the location of my folders an vscode-go showing/not showing error underlining (red) my source code (same with green underlining).
I have my wokspace set to \~/Documents/go (Documents is actually a soft-link to /shared/Documents/). If I put a folder with source code under \~/Documents/go, everything works fine. The errors are underlined in red and the problem is also reported in the PROBLEMS tab and in the OUTPUT (Go) tab.

![image](https://user-images.githubusercontent.com/36553625/36941612-c2670dd0-1f35-11e8-9e17-55439816c367.png)

But as soon as I put the folder (or even the main.go file alone) under the folder src (\~/Dosuments/go/src) or any of its sub-folders, the errors still appears in both PROBLEMS and OUTPUT (Go) tabs, but they aren't underlined in red.

![image](https://user-images.githubusercontent.com/36553625/36941638-4cb16cb0-1f36-11e8-84f8-e63978941d88.png)

I've checked the folders permissions, and both go folder and src folder seem to have equal owner, group and permissions (I'm running Pearl Linux, derived from Ubuntu). Also I've got golint as my linter.

Am I missing anything?

Thanks in advance for your help!

Best regards.

**Comment by ramya-rao-a** [comment]
So when the `test` folder is directly under `~/Documents/go` you see the red underlines but not when the same folder is directly under `~/Documents/go/src` ?

Can you click on the `Output` pane next to the `Problems` view and share  what you see?

**Comment by JustTestingGo** [comment]
> So when the test folder is directly under ~/Documents/go you see the red underlines but not when the same folder is directly under ~/Documents/go/src

Sure, that's it.

> Can you click on the Output pane next to the Problems view and share what you see in both cases?

Here's my Output pane when the source folder is under ~/Documents/go

![image](https://user-images.githubusercontent.com/36553625/36946327-cd765670-1f91-11e8-8a4c-6f494c7f8a7f.png)

And here's my Output pane when the source folder is under ~Documents/go/src

![image](https://user-images.githubusercontent.com/36553625/36946394-bb91920c-1f92-11e8-9dd1-283f75008988.png)

> Also run the command Go: Current GOPATH in both cases, and share the results

With the source folder under ~Documents/go

![image](https://user-images.githubusercontent.com/36553625/36946294-3c119a46-1f91-11e8-8b86-b7b4ad329dff.png)

With the source folder under ~Documents/go/src

![image](https://user-images.githubusercontent.com/36553625/36946279-d0b60976-1f90-11e8-84b2-06dc12e5fbdd.png)

So, the difference seems to be in 
"Finished running tool: /usr/local/go/bin/go build -i -o /tmp/go-code-check ."
When the error is underlined, this command reports the error in the actual folder (/shared/Documents/go/test/test.go:8: undefined: testVariable), while when the error isn't underlined the command reports the error in the soft-link (~/Documents/go/src/test/test.go:8: undefined: testVariable).

Best regards.

**Comment by JustTestingGo** [comment]
Problem solved!

It seems that go tools aren't very fond of GOPATH using links (at least soft-links). I've changed my GOPATH from $HOME/Documents/go to /shared/Documents/go and now everything is working like a charm.

Thank you for heading me in the right way Ramya and sorry for the inconveniences.

Best regards.

**Comment by ramya-rao-a** [comment]
Glad that you got things working, Happy Coding!
