### ISSUE TITLE
Include the standard library in 'Go to Symbol in Workspace...' searching

### ISSUE THREAD

**Issue by seen** [Microsoft/vscode-go#1567]
It would be nice if symbols from the stdlib were included when using 'Go to Symbol in Workspace...'.

It appears that `go-symbols` only accepts one root and making multiple invocations might bet messy, so an alternative approach of having a 'Go to Symbol in Standard Library...' could be sufficient

**Comment by ramya-rao-a** [comment]
We would definitely not be overloading the existing `Go to Symbol in Workspace` command as it is meant for the current workspace. 

Can you elaborate on your scenario here? Do you search for a symbol that you know for sure is part of the std lib? When doing so, do you also know which package it belongs to? If so, then have you tried the `Go: Browse Packages` command?

**Comment by ramya-rao-a** [comment]
Also, if you are looking at searching for all symbols in given package, https://github.com/Microsoft/vscode-go/issues/671 is tracking that feature request

**Comment by seen** [comment]
The desired result is having the same functionality (namely a type-ahead) search that `Go to Symbol in Workspace` has, but targeted at the standard library.

The main use case is for those times when I'm fairly sure of the naming of a symbol, but less certain of it's package location. The current solution is to either start typing in code and hope code sense picks up what I'm after, or heading to google. Neither of which are as effective as the behavior `Go to Symbol in Workspace` presents

**Comment by ramya-rao-a** [comment]
> The main use case is for those times when I'm fairly sure of the naming of a symbol, but less certain of it's package location

Would you know the package name at this point?

**Comment by seen** [comment]
`...package location` should have really been `package name`. In this scenario I wouldn't know the package in which the symbol lives, otherwise I'd be able to use the `Browse Packages` command

**Comment by ramya-rao-a** [comment]
Doesnt this scenario also extend to when using symbols from non std lib?

**Comment by seen** [comment]
It does, but with projects utilizing `dep` or other dependency management techniques that have a `vendor` directory, those symbols are in the workspaces, so `Go to Symbol in Workspace` is sufficient

**Comment by ramya-rao-a** [comment]
Ok, in that case we can have setting which when enabled can include the results from the std lib when the `Go to Symbol in Workspace` command is run. We can run `go-symbols` twice once on the current workspace and the second time on the goroot and return the combined results.

PRs are welcome.

**Comment by ramya-rao-a** [comment]
Add `"gotoSymbol.includeGoroot": true` to your settings to get this feature is the latest update to the Go extension (0.6.79)
