### ISSUE TITLE
Feature Request: List Methods and Types

### ISSUE THREAD

**Issue by joncalhoun** [Microsoft/vscode-go#1569]
https://github.com/natdm/go-types-atom is a pretty cool atom extension that I'd love to see in vscode. I'm not certain if inside the `vscode-go` extension is the right place - what are your thoughts on that?

I'm not sure how plausible this is in vscode (I have no idea if you can create a side panel like the one used in the atom plugin), but if there are examples of extensions that do things similar to this I'd love to see one.

**Comment by ramya-rao-a** [comment]
Try the [Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) extension. You will get a panel in the explorer view that will show you all the symbols in the current file.
