### ISSUE TITLE
Could support Visual Studio 2015?

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode-go#157]
I know this plugin for vscode,But, no plan to support VS2015?

**Comment by axelgenus** [comment]
Those are two totally different programs and also the API for add-ons is different. There is another project on-going for supporting Golang on Visual Studio: https://github.com/tunnelvisionlabs/LangSvcV2.

**Comment by egamma** [comment]
>Those are two totally different programs and also the API for add-ons is different. 
yes, but the textMate grammar, snippets can be shared between VS and VS Code. I understand that this is a small subset of the full extension/plugin, but i wanted to mention it anyways.

**Comment by lukehoban** [comment]
I'm going to close this out, as there isn't any work we'll do specifically in this extension to support this.

The textmate grammar and snippets for Go are in fact already being shared with VS in VS2015 Update 1, details are here: http://blogs.msdn.com/b/visualstudio/archive/2015/11/30/visual-studio-update-1-rtm.aspx.

But we will also continue to look at whether we can bring similar functionality as is available in the `vscode-go` extension to VS as well.
