### ISSUE TITLE
view information about extended class and jump to that class on click vs code ! problem 

### ISSUE THREAD

**Issue by shrijan00003** [Microsoft/vscode-go#1570]
I would like to view the information about the extended library or class and jump to definition in php just like in sublime text. I have tried installing go extension for it , unfortunately can't find solution for it. 
![one](https://user-images.githubusercontent.com/18306760/37198827-bb84da3a-23a7-11e8-8387-d62bf242e539.PNG)
![two](https://user-images.githubusercontent.com/18306760/37198848-c7ab45a6-23a7-11e8-9096-00cd68882348.PNG)

**Comment by ramya-rao-a** [comment]
@shrijan00003 The Go extension adds language support to the [Golang](https://golang.org). Am guessing you assumed it had something to do with code navigation in general.
