### ISSUE TITLE
go-outline hight cpu

### ISSUE THREAD

**Issue by mars79668** [Microsoft/vscode-go#1571]
1. when i create test code, i modify the generated test code,  vscode run many go-ouline proccess with parament  -modified, like  "go-outline.exe c:\prj\src\aa_test.go -modified", then cpu run 100%
2.

**Comment by ramya-rao-a** [comment]
@mars79668 Do you still have this issue?
Do you see this only when editing test files?
Is there a sample code where you can consistently repro this?
