### ISSUE TITLE
Feature request: use line number + byte offset to highlight errors

### ISSUE THREAD

**Issue by dhowden** [Microsoft/vscode-go#1572]
It would be great if the error highlighting would begin at the byte offset reported by the compiler (since go 1.9:https://github.com/golang/go/issues/10324).

**Comment by dhowden** [comment]
So it looks like the correct information is making it in, but just not being passed to the renderer correctly: https://github.com/Microsoft/vscode-go/blob/master/src/goLiveErrors.ts#L87

**Comment by dhowden** [comment]
Closing as this has been merged.

Note: go1.10 is known to report some counter-intuitive column locations for certain errors (for instance https://github.com/golang/go/issues/24339, which has been fixed and will be released in go1.11).

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update (0.6.78) to the Go extension.
