### ISSUE TITLE
Extra new tab when debugging

### ISSUE THREAD

**Issue by demothorg** [Microsoft/vscode-go#1574]
Hi,

Sorry if my issue is duplicate or well known, but I really tried to find it.

When I start debugging, it opens a new tab for the same file.
Pathes of the files differ only by case: `C:\Users\...\myfile.go` and `C:\users\...\myfile.go`
I fixed this by editing GOPATH, but I think it's an issue.

OS: Windows 10 x64
VSCode: 1.20.1 and 1.21.0 (tried both)
Go extension: 0.6.77

Steps to Reproduce:

1. Change the GOPATH so that it differs from the "normal" path only by case.
2. Open project from the workspace and start debugging.
3. Look at the new tab.

**Comment by ramya-rao-a** [comment]
This is due to upstream issues with VS Code itself. Trying to fix this in the Go extension is expensive and a fix from VS Code itself is preferable.

See https://github.com/Microsoft/vscode/issues/19014 and https://github.com/Microsoft/vscode/issues/12448
