### ISSUE TITLE
Go extension can't do code complete any more

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode-go#1575]
--This issue has been moved from [Microsoft/vscode](https://github.com/Microsoft/vscode/issues/45559)--
Author is @yuwgle.
Issue Type: <b>Bug</b>

Go extention can't do code complete any more

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.4.0-111-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3783)|
|Load (avg)|0, 0, 0|
|Memory (System)|7.75GB (3.21GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.28
Go|luk|0.6.77
python|ms-|2018.2.1
cpptools|ms-|0.15.0
vscode-icons|rob|7.21.0

</details>
Reproduces only with extensions

**Comment by ramya-rao-a** [comment]
Are other features of the extension like Go to definition, build, lint etc working?
Any errors in the console? Help -> Toggle Developer Tools -> Console

**Comment by SommerEngineering** [comment]
I had the same issue. But in my case, it was just for `vendor` packages, maintained by `dep`. Completion for Go's own packages still works. I'm not sure: Should it work with `vendor` packages?

**Comment by ramya-rao-a** [comment]
Completion should work for vendor packages as well.
Run `gocode -debug -s` in a terminal and try for completions in VS Code.
You will see the output for each completion attempt in the terminal. 
That should tell you if `gocode` is not able to return completions

**Comment by LaughingCabbage** [comment]
same issue here. 


extensionService.ts:782 Activating extension 'lukehoban.Go' failed: Cannot find module 'vscode-extension-telemetry'.
O._logMessageInConsole @ extensionService.ts:782
console.ts:136 [Extension Host] Activating extension `lukehoban.Go` failed:  Cannot find module 'vscode-extension-telemetry'
t.log @ console.ts:136
console.ts:136 [Extension Host] Here is the error stack:  Error: Cannot find module 'vscode-extension-telemetry'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:784)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Genti\.vscode\extensions\lukehoban.go-0.6.77\out\src\util.js:11:38)
	at Object.<anonymous> (C:\Users\Genti\.vscode\extensions\lukehoban.go-0.6.77\out\src\util.js:707:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)

**Comment by ramya-rao-a** [comment]
@LaughingCabbage In your case, there is a problem in activating the extension itself. Please try uninstalling and then re-installing the extension.

**Comment by LaughingCabbage** [comment]
@ramya-rao-a thanks for the tip. Both done already with no change in results

**Comment by ramya-rao-a** [comment]
@LaughingCabbage Delete the folder `lukehoban.go-0.6.77` under `C:\Users\Genti\.vscode\extensions` and try again

**Comment by LaughingCabbage** [comment]
Thank you! This seems to have worked. I do a

**Comment by ramya-rao-a** [comment]
@LaughingCabbage See upstream issue https://github.com/Microsoft/vscode/issues/43813. This shouldn't happen after updating to the latest VS Code

**Comment by yuwgle** [comment]
Dude,sorry about the go extention bug report.
My problem is gocode didn't work properly, reinstall gocode can fix my problem.

Go extention is ok here.

**Comment by ramya-rao-a** [comment]
Thanks for getting back @yuwgle 
Closing this issue
