### ISSUE TITLE
Feature Request: Option to view definition and doc in output panel

### ISSUE THREAD

**Issue by leninhasda** [Microsoft/vscode-go#1579]
Options to view definition and/or doc of any symbol (type, interface, method etc) in output panel like this (example from atom):

<img width="685" alt="screen shot 2018-03-14 at 19 09 24" src="https://user-images.githubusercontent.com/3797647/37404182-53fdd32c-27bb-11e8-91dd-a1610a97eea7.png">

There exists a quick pop up view for similar purpose but it requires hovering mouse pointer over the symbol and disappears when not focused. However I think its more helpful to have a reference in output panel just down below while coding.

**Comment by ramya-rao-a** [comment]
This is a generic feature request and is language agnostic. Please log this issue in the main VS Code repo at https://github.com/Microsoft/vscode/issues
