### ISSUE TITLE
langserver invocation is not using GOPATH from folder settings

### ISSUE THREAD

**Issue by sandipb** [Microsoft/vscode-go#1580]
My gopath settings is like this:

- User setting: `"go.gopath": "${workspaceFolder}"` 
- Workspace setting: [NOT SET]
- Folder setting: `"go.gopath": "${workspaceFolder}/xx/yy"`

I was debugging why the langserver would work for all features but not for "references".

I set up trace by setting `go.languageServerFlags`, and I found out that this was throwing an error:

```
--> request #10: textDocument/references: {"textDocument":{"uri":"file:///SOME_PATH_INSIDE_WORKSPACE_FOLDER/file.go"},"position":{"line":16,"character":12},"context":{"includeDeclaration":true}}
<-- error #10: textDocument/references: {"code":0,"message":"import \"/SOME_IMPORT_PATH\": cannot import absolute path","data":null}
```

I looked at https://github.com/sourcegraph/go-langserver/issues/185 which mentioned that this should only happen for files outside GOPATH. Which is odd because every other Go tool inside vscode works with the folder gopath setting.

So i looked up the pid of the langserver process and tried to find the environment variables being passed to it.

```
$ ps eww 70965
  PID   TT  STAT      TIME COMMAND
70965   ??  R      0:05.11 /Users/snbhatta/go/bin/go-langserver -mode=stdio -trace -logfile /Users/snbhatta/langserver.log ... GOPATH=/WORKSPACE_FOLDER
```

This tells me that the GOPATH used to invoke the langserver was the one from User setting.

I would have expected it to be:  `${workspaceFolder}/xx/yy`

I understand how the current architecture uses a single instance of the langserver per workspace, and how having different langserver instances per folder might be a significant change.

But if the langserver feature doesn't support per folder GOPATH setting, it might be a good idea to add this warning in the langserver section in https://github.com/Microsoft/vscode-go/blob/master/README.md

**Comment by sandipb** [comment]
Additionally, it doesn't seem that the PATH variable being passed on to the langserver process includes `$GOROOT/bin`

**Comment by sandipb** [comment]
I see this in the code: 😄 

```typescript
     if (!allFoldersHaveSameGopath()) {
         vscode.window.showInformationMessage('The Go language server is not supported in a multi root set up with different GOPATHs.');
         return false;
     }
```
So most probably this is known, and just not documented, or perhaps documented in a place where I have not spotted it.

**Comment by sandipb** [comment]
Seems it is just setting `GOPATH` right now during langserver invocation.

```typescript
        if (langServerAvailable) {
            let langServerFlags: string[] = vscode.workspace.getConfiguration('go')['languageServerFlags'] || [];
            // Language Server needs GOPATH to be in process.env
            process.env['GOPATH'] = getCurrentGoPath();
```

Other Go tools seem to be using `getToolsEnvVars()` which includes the PATH setting needed to find the go executable.

**Comment by ramya-rao-a** [comment]
> So most probably this is known, and just not documented, or perhaps documented in a place where I have not spotted it.

Was there no notification that popped up saying "The Go language server is not supported in a multi root set up with different GOPATHs." ? I was hoping that would suffice to inform users of the multi-root issue with language servers. Feel free to send a PR updating the [README](https://github.com/Microsoft/vscode-go/blob/master/README.md#go-language-server-experimental)

> Other Go tools seem to be using getToolsEnvVars() which includes the PATH setting needed to find the go executable.

Feel free to submit a PR to use `getToolsEnvVars()` replacing the line that just sets the GOPATH before starting the language server.

**Comment by ramya-rao-a** [comment]
btw, great job investigating the issue and the root cause!

**Comment by sandipb** [comment]
> Was there no notification that popped up saying "The Go language server is not supported in a multi root set up with different GOPATHs."

No. AFAIK, I didn't get any such notifications.

And sure! Let me send PRs for both these changes! :-)

**Comment by ramya-rao-a** [comment]
The readme has been updated with https://github.com/Microsoft/vscode-go/commit/db1273d35939ff7b51b02035cb9379549b7c0dbc#diff-04c6e90faac2675aa89e2176d2eec7d8

The env vars from `getToolsEnvVars()` are passed to the language server with https://github.com/Microsoft/vscode-go/commit/819f10767cdd64db4f63a95dd529c75ad0eedd71
