### ISSUE TITLE
for x := range []string {} shows 'x' as type "bool"

### ISSUE THREAD

**Issue by rracb** [Microsoft/vscode-go#1581]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

Using stock Go 1.10 and latest vscode-go with latest MS VSCode install.

1.  for x := range []string {stuff here}
2.  Hovering the mouse pointer over the 'x' shows type "bool" and not type "int" as it should.
3.  Language spec shows line 1 is a valid statement and 'x' should be index (type "int").
4.  Change line 1 to:  for x, _ := range []string {stuff here}
5.  Hovering mouse pointer over the 'x' shows type "int" but the IDE complains that the ', _' isn't necessary.
6.  Remove the ', _' and x shows as type "bool" again.
7.  Lang spec shows 'x, _ : range...' is a legitimate statement form.
8.  Placing 'var x int' ahead of the 'for x := range... statement forces the 'x' to be seen as type "int" by vscode-go.
8.  Code compiles either way without complaint.

**Comment by m90** [comment]
This is an upstream bug in `godef`: https://github.com/rogpeppe/godef/issues/72 - using `gogetdoc` instead fixed the issue for me.

Also see: https://github.com/Microsoft/vscode-go/issues/1242

**Comment by ramya-rao-a** [comment]
Thanks for the links @m90 

I can confirm that the hover works as expected when choosing `gogetdoc`

> but the IDE complains that the ', _' isn't necessary. .... Lang spec shows 'x, _ : range...' is a legitimate statement form

@rracb Thats the linter talking

Closing this as we have a workaround as well as an upstream issue
