### ISSUE TITLE
Errors not being reported

### ISSUE THREAD

**Issue by janhancic** [Microsoft/vscode-go#1582]
We have a bit of a non standard go structure in that we don't have a src folder. So we have go files in `common/go/somepkg/code.go` and then some other code in `project/foo/bar/code.go`. Note that I've also created a more go-like folder structure by symlinking things together, and I still see the same issue as I'm about to describe.

The problem I'm seeing is that, depending on which files I'm editing, I get or don't get error reporting, even for basic stuff like syntax errors. Bellow is a screenshot from the same project, where I made the same mistake in two different files.

![image](https://user-images.githubusercontent.com/356488/37456365-103ebd28-2837-11e8-8e3b-c47b917231f4.png)

As you can see on the left, I get errors reported back, and on the right I don't. You can also see the output in the developer tools, where it's clear that the error is actually found in both cases. It just doesn't get reported.
There is nothing relevant in the output window.

I can see this in both vscode latest and insiders.

I realise this is not a lot to go on, so I would appreciate if you can advise me in how to provide more relevant information that would help us find the cause of the problem, and hopefully fix it.

**Comment by ramya-rao-a** [comment]
The errors in the console is coming from the `goFormat` file which means they are formatting errors. Formatting errors are not the source of the red squiggly lines that you see in the editor.

Can you share the logs in the output pane for both cases? In the output pane choose "Go" in the dropdown that appears on the top right corner of the output pane. This is where the output of the `go build` process gets printed out and then later piped to the Problems view which gets translated to the red lines in the editor.

Note: The build only gets triggered when you make an edit and save the file

**Comment by janhancic** [comment]
Output from the first file (where I get the squiggly line):

```
Finished running tool: /usr/bin/golint

Finished running tool: /usr/bin/go build -i -o /tmp/go-code-check .
/home/jan/dev/core/common/go/validate/validate.go:32: syntax error: unexpected aaa, expecting {

Finished running tool: /usr/bin/go vet ./...
```

and from the second, non working one:

```
Finished running tool: /usr/bin/golint

Finished running tool: /usr/bin/go build -i -o /tmp/go-code-check .
/home/jan/dev/core/plz-out/go/src/common/go/db/db.go:13: cannot find package "common/go/db/config/dbconfig" in any of:
/home/jan/dev/core/REDACTED/REDACTED2/productbuilder/service.go:12: found packages validate (validate.go) and main (validate_test_main.go) in /home/jan/dev/core/plz-out/go/src/common/go/validate
/home/jan/dev/core/REDACTED/REDACTED2/productbuilder/service.go:14: no Go files in /home/jan/dev/core/plz-out/go/src/REDACTED/REDACTED2/proto/productbuilder

Finished running tool: /usr/bin/go vet ./...
```

**Comment by ramya-rao-a** [comment]
The logs don't tell what is the `cwd` when the commands are run. If you don't mind, can you install the beta version of the Go extension that does output the cwd as well? All you have to do is
- Download the latest [vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix) file
- Run `code --install-extension Go-latest.vsix`
- Reload VS Code and try again

**Comment by janhancic** [comment]
Ok, here are the new outputs.

The working one:

```
/home/jan/dev/core/common/go/validate>Finished running tool: /usr/bin/golint

/home/jan/dev/core/common/go/validate>Finished running tool: /usr/bin/go build -i -o /tmp/go-code-check .
/home/jan/dev/core/common/go/validate/validate.go:17: syntax error: unexpected aaa, expecting {

/home/jan/dev/core/common/go/validate>Finished running tool: /usr/bin/go vet ./...
```

the non working one (file name is `/home/jan/dev/core/REDACTED/REDACTED2/productbuilder/db.go`):

```
/home/jan/dev/core/REDACTED/REDACTED2/productbuilder>Finished running tool: /usr/bin/golint

/home/jan/dev/core/REDACTED/REDACTED2/productbuilder>Finished running tool: /usr/bin/go build -i -o /tmp/go-code-check .
/home/jan/dev/core/plz-out/go/src/common/go/db/db.go:13: cannot find package "common/go/db/config/dbconfig" in any of:
/home/jan/dev/core/REDACTED/REDACTED2/productbuilder/service.go:12: found packages validate (validate.go) and main (validate_test_main.go) in /home/jan/dev/core/plz-out/go/src/common/go/validate
/home/jan/dev/core/REDACTED/REDACTED2/productbuilder/service.go:14: no Go files in /home/jan/dev/core/plz-out/go/src/REDACTED/REDACTED2/proto/productbuilder

/home/jan/dev/core/REDACTED/REDACTED2/productbuilder>Finished running tool: /usr/bin/go vet ./...
```

I've noticed that I get the same output regardless if I have the syntax error or not in the second (non working) file. That seems strange, but I don't know if it's significant.

**Comment by ramya-rao-a** [comment]
In the second case, the file that is open is `/home/jan/dev/core/REDACTED/REDACTED2/productbuilder/db.go` and errors are being reported against `/home/jan/dev/core/plz-out/go/src/common/go/db/db.go:13` and `/home/jan/dev/core/REDACTED/REDACTED2/productbuilder/service.go`. 

There are no errors being reported against the file that was open so you dont see any red lines in it.

Do these 3 errors appear in the "Problems" panel?

**Comment by janhancic** [comment]
They do show up in the problems panel. But why doesn't the one from db.go? Note that it also doesn't pick up any errors of the type "unused variable", "cannot use int as string" etc. So I get no go support effectively.

**Comment by ramya-rao-a** [comment]
> They do show up in the problems panel. But why doesn't the one from db.go?

Which of the 3 errors dont show up in the problems panel? When you click on the errors in the Problems panel, the file should show up with red lines

> Note that it also doesn't pick up any errors of the type "unused variable", "cannot use int as string" etc

And these dont appear in the output channel either correct? The Problems panel can only show errors that show up in the logs in the output channel. If they dont show up in the output channel, then copy the command being used from the logs and run it in a separate terminal (using the the same cwd) and see if you get expected errors there

**Comment by janhancic** [comment]
So I tried running the commands manually in the same folder they get run according to the output panel and I do get the expected errors:

```
$ /home/jan/dev/core/bin/golint
db.go:17:2: expected '{', found 'IDENT' aaa
```
that error doesn't show up in the problems or output panel

**Comment by ramya-rao-a** [comment]
And you ran that from `/home/jan/dev/core/REDACTED/REDACTED2/productbuilder`?

**Comment by janhancic** [comment]
Yes, that's correct.

>

**Comment by ramya-rao-a** [comment]
In https://github.com/Microsoft/vscode-go/issues/1582#issuecomment-375597384, you have run the linter which only gives warnings. Since you were expecting errors, can you run the `go build` command from the output pane?

**Comment by janhancic** [comment]
Sorry for the late reply, was on my easter break ...

I've ran the command @ramya-rao-a and I get a bunch of "cannot find package" errors. I suppose go can't go past that? But it's weird that syntax errors aren't considered first. I'm a bit new to go, so I don't know if this is an issue with vscode or Go.

**Comment by janhancic** [comment]
I've now additionally have a case where a syntax error is reported in the Output panel but isn't highlighted in the editor itself:

```
/home/jan/dev/core-golang/src/common/go/calc>Finished running tool: /usr/bin/go build -i -o /tmp/go-code-check common/go/calc
/home/jan/dev/core-golang/core-golang/src/common/go/calc/calc.go:16: syntax error: unexpected newline, expecting comma or )
```
