### ISSUE TITLE
Debugger: Failed to get threads.

### ISSUE THREAD

**Issue by msingleton** [Microsoft/vscode-go#1584]
I'm having trouble getting VS Code to stop on a breakpoint using Delve remotely in a docker container. After receiving a ContinueResponse, it attempts a ThreadsRequest which appears to fail.

launch.json
```{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Go - Docker",
      "type": "go",
      "request": "launch",
      "mode": "remote",
      "remotePath": "/go/src/github.com/msingleton/betamax/",
      "port": 5432,
      "host": "127.0.0.1",
      "program": "${workspaceRoot}",
      "env": {},
      "showLog": true,
      "trace": "verbose"
    }
  ]
}
```

Delve logs:
```iterate-debug         | 2018/03/17 20:55:48 server.go:73: Using API v1
iterate-debug         | 2018/03/17 20:55:48 debugger.go:98: launching process with args: [/go/src/github.com/msingleton/betamax/debug]
iterate-debug         | API server listening at: [::]:5432
iterate-debug         | 2018/03/17 20:57:12 debugger.go:340: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x401032, File:"/go/src/github.com/msingleton/betamax/app.go", Line:26, FunctionName:"main.main", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
iterate-debug         | 2018/03/17 20:57:12 debugger.go:497: continuing
```

Debugger Logs:
```Verbose logs are written to:
/var/folders/rj/tqsmvbg57sxfykw84769r9j40000gn/T/vscode-go-debug.txt
4:57:12 PM, 3/17/2018
InitializeRequest
InitializeResponse
Using GOPATH: /Users/mike/Iterate
InitializeEvent
SetBreakPointsRequest
All cleared
Creating on: /Users/mike/Iterate/src/github.com/msingleton/betamax/app.go (/go/src/github.com/msingleton/betamax/app.go) :26
All set:[{"id":1,"name":"","addr":4198450,"file":"/go/src/github.com/msingleton/betamax/app.go","line":26,"functionName":"main.main","Cond":"","continue":false,"goroutine":false,"stacktrace":0,"LoadArgs":null,"LoadLocals":null,"hitCount":{},"totalHitCount":0}]
SetBreakPointsResponse
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
ThreadsRequest
continue state {"currentThread":{"id":58,"pc":4198450,"file":"/go/src/github.com/msingleton/betamax/app.go","line":26,"function":{"name":"main.main","value":4198400,"type":0,"goType":0,"optimized":false},"goroutineID":1,"breakPoint":{"id":1,"name":"","addr":4198450,"file":"/go/src/github.com/msingleton/betamax/app.go","line":26,"functionName":"main.main","Cond":"","continue":false,"goroutine":false,"stacktrace":0,"LoadArgs":null,"LoadLocals":null,"hitCount":{"1":1},"totalHitCount":1},"breakPointInfo":{}},"currentGoroutine":{"id":1,"currentLoc":{"pc":4198450,"file":"/go/src/github.com/msingleton/betamax/app.go","line":26,"function":{"name":"main.main","value":4198400,"type":0,"goType":0,"optimized":false}},"userCurrentLoc":{"pc":4198450,"file":"/go/src/github.com/msingleton/betamax/app.go","line":26,"function":{"name":"main.main","value":4198400,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4572878,"file":"/usr/local/go/src/runtime/asm_amd64.s","line":151,"function":{"name":"runtime.rt0_go","value":4572528,"type":0,"goType":0,"optimized":false}},"threadID":58},"Threads":[{"id":58,"pc":4198450,"file":"/go/src/github.com/msingleton/betamax/app.go","line":26,"function":{"name":"main.main","value":4198400,"type":0,"goType":0,"optimized":false},"goroutineID":1,"breakPoint":{"id":1,"name":"","addr":4198450,"file":"/go/src/github.com/msingleton/betamax/app.go","line":26,"functionName":"main.main","Cond":"","continue":false,"goroutine":false,"stacktrace":0,"LoadArgs":[...]
Failed to get threads.
```

In a Delve console I was able to successfully get the list of threads, which makes me think it may be an issue on the VSCode side.
```
(dlv) threads
* Thread 57 at 0x40101b /go/src/github.com/msingleton/betamax/app.go:25 main.main
  Thread 62 at 0x460417 /usr/local/go/src/runtime/sys_linux_amd64.s:95 runtime.usleep
  Thread 63 at 0x460833 /usr/local/go/src/runtime/sys_linux_amd64.s:388 runtime.futex
  Thread 64 at 0x460833 /usr/local/go/src/runtime/sys_linux_amd64.s:388 runtime.futex
  Thread 65 at 0x460833 /usr/local/go/src/runtime/sys_linux_amd64.s:388 runtime.futex
```

Any ideas? Thanks!

**Comment by ramya-rao-a** [comment]
No ideas looking at the logs. I would suggest debugging the Go extension directly. Its pretty straight-forward.
- First clone this repo and run `npm install`
- Then follow the steps in the [debugger README](https://github.com/Microsoft/vscode-go/tree/0.6.77/src/debugAdapter)
- Add breakpoint at https://github.com/Microsoft/vscode-go/blob/0.6.77/src/debugAdapter/goDebug.ts#L577 where thread request is being made

**Comment by mocampo5** [comment]
I was having similar problem, i follow @ramya-rao-a steps and got this error
`Unable to display threads: "Internal debugger error: runtime error: invalid memory address or nil pointer dereference`
Since that was coming from go, i tried updating to go 1.10 and that fixed it

**Comment by krasoffski** [comment]
Had the same issue but on xubuntu 16.04 but no issues using dlv from cli.

**Comment by dsyer** [comment]
In my case I found that VSCode ignores my "go.goroot" setting from global config, so it was picking up the wrong version from somewhere. If I manually set `GOROOT` in the `launch.json` it works.

**Comment by krasoffski** [comment]
It seem like the issue related to old version of go compiler. After updating from 1.8.5 to the latest 1.9 release issue disappeared.

**Comment by greggwardnz** [comment]
I am having the same problem on Ubuntu 17.10/18.04, running Go v1.8.3, with Go extension v0.6.78. I had been successfully debugging with VSCode and Go v1.8.3, for months, up until just a couple of weeks ago and then every project that I try to debug I get the "Failed to get threads" error. 

It seems it doesn't matter where I put the breakpoint, as soon as the breakpoint gets hit, it outputs this error.

I got the same error as @mocampo5 when debugging the Go extension.

**Comment by greggwardnz** [comment]
I have tried completely rebuilding the project that I am having the problem with, which does not fix the problem. If I use GoLand to debug the same project, on the same platform, I do not have a problem. I would much prefer to stay with VS Code.

I have tried manually setting GOROOT, as suggested by @dsyer, but that did not work either.

I am happy to try any suggestions, to help resolve this issue, except for the fact that I must stay with the current version of Go that I am using i.e. Go v1.8.3.

**Comment by greggwardnz** [comment]
I have been using Delve v1.0, pulled down via the VSCode Install/Update tools functionality. This will throw the "Failed to get threads" error, every time I try to stop on a breakpoint, debugging a particular project. I changed the dlv executable with the one that comes with GoLand  (v0.12.1) and I no longer get the error and can stop on breakpoints successfully.

Is there some incompatibility with the latest version of Delve?

**Comment by greggwardnz** [comment]
Have decided to move project to Go v1.10.2, rebuilt all tools and no longer have a problem debugging.

**Comment by ramya-rao-a** [comment]
Looks like everyone in this issue was able to get the problem resolved. Most of them by rebuilding the tools after updating to newer versions of Go.

Thanks to each of you for getting back here with your solutions.

Closing this issue as there are nothing more to do here.

Happy Coding!
