### ISSUE TITLE
No logs when running tests?

### ISSUE THREAD

**Issue by nasht00** [Microsoft/vscode-go#1586]
My tests file includes all kinds of `fmt.Println`.

When I run `go test`, I see those logs. However when I use any of the `run tests`, `run package tests`, etc, then I don't see my logs (only "Tests passed").

Now the tricky part is, my co-worker working on the same package DOES see the logs I wrote.

I noticed a difference, when he runs the tests the first line says:

`Running tool: /usr/local/bin/go test -coverprofile=/var/folders/3p/brp58kw16kz6fnf0ld_nn84wfsg2rn/T/go-code-cover -timeout 30s`

While mine says:

`Running tool: /usr/local/go/bin/go test -coverprofile=/var/folders/31/kdcrrtn12bs0h7vjjhsc_vrmc69nl3/T/go-code-cover -timeout 30s github.ibm.com/NATHANH/json-logic-go`

Notice the extra path at the end? And indeed, if I manually enter those commands in the terminal I see the same behavior.

1. Why does my version includes the package name?
1. Why does it affect logs?

**Comment by ramya-rao-a** [comment]
> Why does my version includes the package name?

We try to deduce the import path to the package from the current GOPATH and then add it to enable running tests in symlinked directories. See https://github.com/Microsoft/vscode-go/blob/0.6.77/src/testUtils.ts#L150.

The difference between your and your co-worker's set up must be the GOPATH. Run `Go: Current GOPATH` to see the GOPATH being used.

> Why does it affect logs?

That I don't know. You will have to ask this question in the repo for the go tool itself.

Hope this answers your question and sorry for the delay.

Happy Coding!
