### ISSUE TITLE
Not detecting syntax errors in vscode

### ISSUE THREAD

**Issue by okabbas** [Microsoft/vscode-go#1588]
vscode version : 1.21.1
extension version : 0.6.77

Hello . Unfortunately, I'm going to go with a problem. In vscode, look at the code below for a few syntax errors, but vscode does not detect these errors.

<img src="http://uupload.ir/files/q11y_vscode.png">

settings : 
> "go.autocompleteUnimportedPackages": true

**Comment by ramya-rao-a** [comment]
Open the Output pane and select "Go" from the dropdown that appears in the top right corner of the Output pane. Here you can find logs of the `go build` command that runs on each file save. Are there any errors there?

**Comment by okabbas** [comment]
This problem was solved by installing all the necessary tools for the go plugin.
