### ISSUE TITLE
"Add Import" index times are really slow

### ISSUE THREAD

**Issue by polds** [Microsoft/vscode-go#159]
I apologize for opening so many issues lately... this is 1 of 2 for this morning :cry: 

The "Add Import" is very slow to list all available packages. I'm wondering if there is a way to improve the index times:

![import_times](https://cloud.githubusercontent.com/assets/2372558/11847146/403db220-a3d9-11e5-89ae-e9e22e59aa63.gif)

What's really bad is you can't click away from Code while it's trying to pop open the menu or it stops. So I just kind of have to sit there.

**Comment by lukehoban** [comment]
The `Add Imports` feature relies on running `go list all` with your active `GOPATH` to get the list of available packages.  Unfortunately, I'm not aware of any alternative option for this that would be faster.

If anyone has a suggestion on a faster technique for gathering the available packages though, please do reopen this.

**Comment by tpng** [comment]
@lukehoban I have created a utility [gopkgs](https://github.com/tpng/gopkgs) for listing available packages, it is based on the similar function of the SublimeText plugin GoSublime and should run much faster than `go list all`.

**Comment by lukehoban** [comment]
@tpng Awesome.  Reopening this issue - let's try out incorporating `gopkgs` here.

**Comment by lukehoban** [comment]
This should be fixed by #178.  Thanks @zippoxer!

I did notice that on my machine, `gopkgs` returns about half as many results as `go list all`.  A decent number of these appear to be cases where `go list all` includes a program (which can't be imported anyway), so that reduction seems positive.  But it looks like there are other cases where perhaps libraries are being left out that should be included?

**Comment by tpng** [comment]
The difference of `go list all` and `gopkgs` is that `go list all` looks for go packages in your `$GOPATH/src` while `gopkgs` looks in your `$GOPATH/pkg`.
As a result of this, only importable packages that have been installed (either by `go get` or `go install`) are listed by `gopkgs`.

**Comment by lukehoban** [comment]
Thanks @tpng.  That makes sense.  Seems reasonable to limit to those, and definitely the performance of `gopkgs` is significantly better.
