### ISSUE TITLE
go vet is not passed go.buildTags

### ISSUE THREAD

**Issue by FiloSottile** [Microsoft/vscode-go#1591]
I have a file with a build tag of `json1`, and workspace settings of

```
{
    "go.buildTags": "json1"
}
```

cause vet to report issues everywhere the symbols from that file are not found, while

```
{
    "go.buildTags": "json1",
    "go.vetFlags": ["-tags", "json1"]
}
```

works fine. The same issue seems not to be there with `lintFlags`.

**Comment by ramya-rao-a** [comment]
Looks like we miss passing the build tags to when vetting, this should be an easy fix.
PRs are welcome.

Place where `go vet` is called: https://github.com/Microsoft/vscode-go/blob/0.6.78/src/goVet.ts#L57
Reference to how build tags are passed to `go build`: https://github.com/Microsoft/vscode-go/blob/0.6.78/src/goBuild.ts#L71

**Comment by ramya-rao-a** [comment]
Thanks to @novak, this bug is now fixed in the latest update to the Go extension (0.6.79)
