### ISSUE TITLE
issue in Go: Install/Update tools

### ISSUE THREAD

**Issue by jayantnd** [Microsoft/vscode-go#1592]
I Have GOPATH at $HOME/Workspace/Go
but when I check for  "Go: Install/Update tools" it does not check for GOPATH and creates another folder in $HOME/Go

**Comment by jayantnd** [comment]
It seems not working with .profile. but working if Env variables are in .bash_profile

**Comment by ramya-rao-a** [comment]
Glad you could find a work around.
Closing this issue
