### ISSUE TITLE
use completion feature comes from go-langserver

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode-go#1593]
I notice that go-langserver has provider an experimental completion feature, so if we use go-langserver in vscode, should we use completion feature provided by go-langserver?

**Comment by ramya-rao-a** [comment]
Yes, definitely. We should integrate the completion feature from the language server.
PRs are welcome.

**Comment by e-nikolov** [comment]
They seem to have added support for querying interface implementations as well.

https://github.com/sourcegraph/go-langserver/commit/7e016370b5dcb7c929e563a2eea65b1c42ba01e3

**Comment by leaxoy** [comment]
This will meet some error when add new lines to file while using completion feature comes from go-langserver. So I suggest don't harry to integrate it.

**Comment by leaxoy** [comment]
https://github.com/sourcegraph/go-langserver/issues/257

**Comment by ramya-rao-a** [comment]
The changes for this are merged in and will be available in the next week.
The below settings are needed to get this feature
```
"go.useLanguageServer": true,
  "go.languageServerExperimentalFeatures": {
    "autoComplete": true
  }
```

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.81)
