### ISSUE TITLE
General comment between var keyword and name colored differently

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1594]
![screen shot 2018-03-27 at 11 13 17 am](https://user-images.githubusercontent.com/63830/37986334-0ba2a626-31b0-11e8-9398-5a796ee3ed62.png)

(This code was formatted with goimports.)

Also, the first name is white, unlike the second name, which is blue.

**Comment by ramya-rao-a** [comment]
I don't see the `y` in blue though. Which theme are you using?

<img width="322" alt="screen shot 2018-03-28 at 4 32 45 pm" src="https://user-images.githubusercontent.com/16890566/38061798-a91fffde-32a5-11e8-9ae6-12ba586ff428.png">

**Comment by willfaught** [comment]
It’s because you have the y commented.

**Comment by ramya-rao-a** [comment]
Moved to https://github.com/atom/language-go/issues/149
