### ISSUE TITLE
Windows 10 fails activating extension due missing dependency?

### ISSUE THREAD

**Issue by shivas** [Microsoft/vscode-go#1595]
Steps to Reproduce:

1. Latest VSCODE + Latest GO extension
 getting following output in Developer Tools:

`C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Activating extension 'lukehoban.Go' failed: Cannot find module 'vscode-extension-telemetry'.
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:257
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2842 Activating extension 'lukehoban.Go' failed: Cannot find module 'vscode-extension-telemetry'.
O._logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2842
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Activating extension `lukehoban.Go` failed:  Cannot find module 'vscode-extension-telemetry'`

**Comment by shivas** [comment]
Running following commands in extension folder:

`npm install vscode-extension-telemetry` 
AND
`npm install vscode-languageclient` 

resolved issues. 

Looks like some hidden dependencies are not included?

**Comment by ramya-rao-a** [comment]
@sandy081 Here is a case of extension update post VS Code update causing corrupted state as disucssed in https://github.com/Microsoft/vscode/issues/43813

@shivas Can you provide the logs as described in https://github.com/Microsoft/vscode/issues/43813#issuecomment-366951225?

**Comment by shivas** [comment]
@ramya-rao-a I would, problem is i don't have issue anymore as i fixed it myself, (don't want to break it again), and logs folder looks like doesn't have logs from that time anymore :(

**Comment by ramya-rao-a** [comment]
Thats ok @shivas, thanks for getting back
