### ISSUE TITLE
request: ability to load custom coverprofile

### ISSUE THREAD

**Issue by AlexRouSg** [microsoft/vscode-go#1596]
With go 1.10 supporting coverage tests on multiple packages, it would be nice if the plugin lets you load a custom coverage profile and have a more complete profile than only being able to see profiles for a single package tests.

**Comment by ramya-rao-a** [comment]
That would be a cool feature. There can be a command say `Go: Apply Test Coverage from Custom Profile` which opens an input box where you can provide the path to the coverprofile file.

PRs are welcome.

Code Pointers:

- [getCoverage() in goCover.ts](https://github.com/Microsoft/vscode-go/blob/0.6.78/src/goCover.ts#L163) takes path to coverage profile and applies the result on the editor.
- Use the [Go: Generate Interface Stubs](https://github.com/Microsoft/vscode-go/blob/0.6.78/src/goMain.ts#L186-L188) command as reference to create the new command. This makes use of  `vscode.window.showInputBox` to show the input box

**Comment by AlekSi** [comment]
Related to #816.

**Comment by ramya-rao-a** [comment]
A new command `Go: Apply Cover Profile` is now available in the latest version (0.13.0) of this extension.

Thanks for the PR @Eun and Thanks for reporting @AlexRouSg !

Happy Coding!
