### ISSUE TITLE
gogetdoc freezes UI, utilizes 100% CPU

### ISSUE THREAD

**Issue by dmke** [Microsoft/vscode-go#1598]
Using this sample code and `"go.docsTool": "gogetdoc"` in my `settings.json`, the UI freezes and VSCode utilizes 100% CPU, when I hover the `Done`:

```go
package main

import "context"

func main() {
	ctx, cancel := context.WithCancel(context.Background())

	go func() {
		<-ctx.Done()
	}()

	cancel()
}
```

![vscode-freeze](https://user-images.githubusercontent.com/327411/38025566-21087836-3289-11e8-86c4-aabb4434070a.gif)

which leads to

![image](https://user-images.githubusercontent.com/327411/38025626-4970790e-3289-11e8-9684-ac84d33cd6bc.png)

---

I currently am using

- VSCode 1.21.1 (79b44aa704)
- on Debian Stretch 9.4 (Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 GNU/Linux)
- with lukehoban.go 0.6.77
- current [master of zmb3/gogetdoc](https://github.com/zmb3/gogetdoc/tree/b4c1dcb095da28d1d54e10184a3eddd9b0122f89)

Other settings are:

```json
{
  "go.gopath": "/home/dm/code/go",
  "go.goroot": "/home/dm/.local/go",
  "go.lintTool": "gometalinter",
  "go.lintFlags": [
    "--fast",
    "--disable=errcheck",
    "--disable=gotype",
    "--disable=gas",
    "--disable=gocyclo"
  ],
}
```

Neither `guru` nor `godoc` as `go.docsTool` seem to have this problem.

**Comment by ramya-rao-a** [comment]
I cannot repro, `gogetdoc` works just fine with this code sample.

Can you update `gogetdoc`, just to ensure you have the latest version? 

Also, can you share the arguments passed to the `/usr/share/code/code --type=renderer` in your screenshot?

**Comment by dmke** [comment]
```
$ go get -f -u -v github.com/zmb3/gogetdoc
github.com/zmb3/gogetdoc (download)
golang.org/x/tools (download)
github.com/zmb3/gogetdoc
```

and

```
$ ps ww 10700 
  PID TTY      STAT   TIME COMMAND
10700 tty2     Rl+    0:15 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=16004A775203BA2A370E042427651A7C --lang=en-US --app-path=/usr/share/code/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#ffffff --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --disable-gpu-compositing
```

I believe, the proc line is truncated, through. Neither `htop` no `ps` print more than 1248 bytes (there should be space for a full page, shouldn't it?):

```
$ wc -c /proc/10700/cmdline
1248
```

Is there a way to get information out of `code --type=zygote` or `code --unity-launch`, any hidden sockets I could query?

**Comment by dmke** [comment]
Using the Insiders build (1.22.0-insider, 952b2a641), this does not happen.

**Comment by ramya-rao-a** [comment]
Since things look good in the Insiders and that we will be releasing the next update to stable next week, I wouldnt prefer to spend much time here.
Feel free to re-open this issue or create a new one if you see this in Insiders or in Stable (after the next release)

**Comment by dmke** [comment]
Sure, no problem!
