### ISSUE TITLE
Format on save is converting 'foo :=' to 'foo: ='

### ISSUE THREAD

**Issue by peragwin** [Microsoft/vscode-go#1600]
Hi,

I am using the following environment:
```
go version go1.10 linux/amd64
```

VS Code:
```
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:30.761Z
```
When I save a file such as:

```go
package main

func foo() {
	test := "string"
}
```

it gets formatted as:

```go
package main

func foo() {
	test: = "string"
}
```

However, the output of `gofmt` on my terminal is the former (correct) format.

Any ideas?

**Comment by ramya-rao-a** [comment]
This is due to some other extension that is also doing some formatting.
A few other users saw the same thing. See #1487

Try disabling other extensions you have installed to see which of them is causing this.
