### ISSUE TITLE
vscode reports "//+build ignore" as error

### ISSUE THREAD

**Issue by hex2010** [Microsoft/vscode-go#1601]
Steps to Reproduce:

1. create a new main package
2. add`//+build ignore` 
3. vscode reports "can't load package: package ...  build constraints exclude all Go files in ...."

code:
```
//+build ignore

package main

func main() {}
```

**Comment by ramya-rao-a** [comment]
You need to update the `go.buildTags` setting so that the Go extension will know which build tags to use when building your code. Add the below in your settings file:
```
"go.buildTags": "ignore"
```

**Comment by hex2010** [comment]
added `"go.buildTags": "ignore"` to workspace settings,  error raise other place:

```
//+build ignore

package main

import (
	"crypto/x509"  // <- error here
...
``` 

`found packages tls (alert.go) and main (generate_cert.go) in /go/src/crypto/tls`

**Comment by hex2010** [comment]
ok. I found the solution:   rename the tag to "ignore1" and add it to go.buildTags,  errors gone

**Comment by ramya-rao-a** [comment]
What is the purpose of the `ignore` build tag here?
You want to ignore the current package and not build it?

**Comment by hex2010** [comment]
this directory is not a "package"  but a c++ project,  golang  files in it are all tool scripts,  should run with `go run xxxx.go`,  not for `go build`.

**Comment by ramya-rao-a** [comment]
Ok, in that case we shouldnt add "ignore" to the `go.buildTags" setting.

I am not sure how to move forward here.

The error "can't load package: package ... build constraints exclude all Go files in ...." is indeed correct, as you dont want the current file to be built. You are using the "ignore" build constraint to exclude the Go files in the current folder. Since there is no way to exclude files from being built by the Go extension, I am not sure how to proceed other than ignoring the error.

Do you have any suggestions?

**Comment by defjosiah** [comment]
Running into a similar issue here, I have a folder called:
# $GOPATH/github.com/user/myproject/
integration_test/
--integration_test_suite.go
--integration_test.go

And I'm getting the error:
```
go build github.com/user/myproject/integration_test: no non-test Go files in /home/go/src/github.com/user/myproject/integration_test
```

Maybe add a folder ignore option to the go extension? And then check it here (https://github.com/Microsoft/vscode-go/blob/master/src/goBuild.ts#L51)?

**Comment by ramya-rao-a** [comment]
The [April Iteration Plan](https://github.com/Microsoft/vscode/issues/47369) for VS Code has an item for "Problems view support to exclude errors for some files/folders". Getting the ignore support from the core is better than the Go extension implementing its own. 

Closing this issue in favor of the upstream feature.
