### ISSUE TITLE
Find All References is not showing references from GOPATH in windows

### ISSUE THREAD

**Issue by Vigneshr6** [Microsoft/vscode-go#1602]
Find All References only showing the references from the same package in windows. But in linux  vscode shows references from entire GOPATH.

**Comment by Vigneshr6** [comment]
guru command's result itself does not include references from GOPATH. in windows.
I raised an issue for the same in golang repo [https://github.com/golang/go/issues/24699](golang issue id)

**Comment by ramya-rao-a** [comment]
great, I'll close this issue as you have logged an upstream issue to track the same
