### ISSUE TITLE
gorename now requires -scope

### ISSUE THREAD

**Issue by bimargulies** [Microsoft/vscode-go#1605]
If I try to rename a symbol, it fails, because gorename now insists on -scope for global renames. It seems as if you need to construct a list of scopes and add them to the command line.

**Comment by ramya-rao-a** [comment]
rename is working as expected for me and I don't see the `scope` flag when running `gorename -h`. Can you provide more details? I am using Go 1.9.2 on a Mac

**Comment by bimargulies** [comment]
➜  ~ go version
go version go1.10 linux/amd64

https://github.com/golang/tools/blob/f1a397bba50dee815e8c73f3ec94ffc0e8df1a09/cmd/guru/main.go#L32

**Comment by ramya-rao-a** [comment]
@bimargulies The link you have shared is for guru. Is there a similar link for gorename?
