### ISSUE TITLE
auto import doesn't work when () imports has a comment in the end

### ISSUE THREAD

**Issue by gflarity** [Microsoft/vscode-go#1606]
I have one import statement for many imports:

import (
  	"k8s.io/kubernetes/pkg/kubectl"
	"crypto/x509/pkix"
	"errors"
	"time"
)

If I use the auto import feature (where I type package name then select it from list in IDE), I get this:

import (
import "fmt"
	"k8s.io/kubernetes/pkg/kubectl"
	"crypto/x509/pkix"
	"errors"
	"time"
)

So I have to go to the top and remove the import in front of the string. As far as I recall I haven't changed any settings... Any ideas?

**Comment by ramya-rao-a** [comment]
@gflarity I can't repro this. Can you share your settings?

![import](https://user-images.githubusercontent.com/16890566/38472170-a2a0a1f2-3b30-11e8-944c-972a4ecdb535.gif)

**Comment by gflarity** [comment]
Absolutely. Please let me know if there's anything else I can do to help debug. 

`{
    "workbench.colorTheme": "Visual Studio Dark",
    "window.zoomLevel": 1,
    "go.autocompleteUnimportedPackages": true,
    "editor.multiCursorModifier": "alt",
    "editor.minimap.enabled": false,
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": true,
        "suppressShowKeyBindingsNotice": true
    }
}`

**Comment by ramya-rao-a** [comment]
@gflarity You only have 1 go related setting changed and I have the same and I still can't repro. Can you provide a complete code sample?

**Comment by gflarity** [comment]
Ok, I found a very small repo case (for me): 
```
package main

import (
	"log"
	/* comment */)

func main() {
	l := log.Logger{}
}
```
^ auto import fmt  in main after that first line.  I don't actually use comments in my imports, but as I was using trial and error to come up with an example I noticed this and ran with it. 

Env:
OS X, go 1.10, vscode Version 1.22.1 (1.22.1), vscode-go 0.6.78

**Comment by gflarity** [comment]
I should note, if I move the comment above it works again.

**Comment by ramya-rao-a** [comment]
Thanks for the example! Looks like it only happens when there is a comment like that before the closing `)`

**Comment by gflarity** [comment]
It happens workout a comment on certain cases but this is the smallest
example I could make.

**Comment by ramya-rao-a** [comment]
I have pushed a fix for the case when the comment exists before the closing `)`

If you see any other case, please create a new issue with the code sample. 
Thanks!

**Comment by ramya-rao-a** [comment]
This bug fix is now out in the latest update to the Go extension (0.6.79)
Thanks for reporting @gflarity!
