### ISSUE TITLE
Setting environment variables for tests causes output to cease

### ISSUE THREAD

**Issue by mattgen88** [Microsoft/vscode-go#1608]
Steps to Reproduce:

1. Open a test file for a go program
2. Open configuration
3. set `go.testEnvVars` to have an environment variable, e.g. `{"TEST": 1}`
4. Switch to a test and click run test
5. Observe that **no output** was produced in the output window
6. Set g`o.testEnvVars` back to `{}`
7. Switch to a test and click run test
8. Observe output was produced in the output window

Expected result:
The clicked test should execute, with the environment variables output before the test execution, so that the programmer knows that the test was executed and done so with the specified environment.

Reason:
I use an environment variable to trigger an integration suite of tests. I wish to execute the test suite the same as any other test by setting the environment variable within my configuration.

**Comment by ramya-rao-a** [comment]
Looks like this is a problem when the value of the env var is not a string. I have pushed a fix. Until I ship an update, you can try the below:
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by mattgen88** [comment]
Many thanks! I'll give it a shot tomorrow. Thanks for the quick response!

**Comment by ramya-rao-a** [comment]
PS: you will have to be on VS Code 1.22 to get the fix

**Comment by mattgen88** [comment]
Confirmed working in vscode 1.22.1

Thank you once again!

**Comment by ramya-rao-a** [comment]
This bug fix is now out in the latest update to the Go extension (0.6.79)
Thanks for reporting @mattgen88!
