### ISSUE TITLE
Find Implementation doesn't show up in menu (with go.useLanguageServer: true)

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-go#1611]
The Go langserver recently added support for `textDocument/implementation`: https://github.com/sourcegraph/go-langserver/pull/252
I wanted to use it (with `go.useLanguageServer: true`), but the menu item doesn't show for me when I right click on symbols.

**Comment by felixfbecker** [comment]
Thanks! 🤗

**Comment by ramya-rao-a** [comment]
The language client had to be updated. Try the below
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

Note, this will only work from VS Code 1.22 onwards
