### ISSUE TITLE
Increase default timeout for format on save

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#1613]
From VS Code 1.22 onwards, we can now change the default timeout of 750ms for the format on save feature. This issue is to see if Golang needs a higher timeout. We collect numbers on how long formatting takes. Will share the details here soon

**Comment by OneOfOne** [comment]
Format on save is not working for me at all anymore, even with `	"editor.formatOnSaveTimeout": 10000`.

**Comment by ramya-rao-a** [comment]
Closing this issue as we are moving towards using the language server for language feature needs including formatting
