### ISSUE TITLE
cursor focus goes to the end of the document in the other view.

### ISSUE THREAD

**Issue by zhliner** [Microsoft/vscode-go#1615]
like #1349, but same file in two or more view,
save on first view, "cursor jump to the end of document" happened on the second view.

It happens in format alignment. Such as structure members, parameters, etc. But the code needs to have hundreds of lines. 
My two test files: happened when it over 530 lines, and the other happened when it over 550 lines... :(

Steps to Reproduce:

1. Open C:\Go\src\net\dial.go.
2. Alt+Shift+2 to open a new view.
3. Edit in one of the views, such as adding some space before a parameter.
4. Save.
5. Look another view, the cursor rolls to the bottom.

-------------------------------------------
VSCode Version: 1.22.1 (Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd)
OS Version: Windows 10 Professional Edition (1709)
go version: go1.10.1 windows/amd64
Extensions:
- Go v0.6.78
- Auto Comment Blocks v1.0.1
- markdownlint v0.14.1
- Sublime Text Keymap v3.0.3

Note: when I upgraded VSCode to v1.22.1, It happened.

**Comment by rusenask** [comment]
Same on Mac with this version.

* Version 1.22.1 (1.22.1)

**Comment by ramya-rao-a** [comment]
This is due to an [upstream issue](https://github.com/Microsoft/vscode/issues/47382) with VS Code.
The fix is available in the latest [Insiders](https://code.visualstudio.com/insiders) and will also be out in the stable build 1.22.2 which will be released in a few days.
