### ISSUE TITLE
Add option to set GOOS and GOARCH

### ISSUE THREAD

**Issue by raggi** [Microsoft/vscode-go#1616]
I work on Fuchsia and when I am writing programs for the target, I want to set GOOS=fuchsia and often want to set GOARCH=arm64.

Currently I end up with various autocomplete and other tooling problems because the GOOS target is incorrect.

I looked in the settings tree and couldn't currently see any option for these.

Thank you!

**Comment by AlexRouSg** [comment]
You can set it in the `go.toolsEnvVars` or `go.testEnvVars`

**Comment by ramya-rao-a** [comment]
Use `go.toolsEnvVars` to set any environment variables you want the Go tools (that are used by this extension) to use.
