### ISSUE TITLE
No function hover while debugging

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode-go#1617]
While not debugging, mouse hovers work find with and without Ctrl being pressed, both with godoc and gogetdoc. While debugging, hovering over a function call does nothing, neither with nor without Ctrl being pressed.

**Comment by mbenkmann** [comment]
The behaviour is really weird. It seems like during debugging function hovers work in all files EXCEPT for the one currently selected in the CALL STACK. I guess it's the debug hover that shows me a variable's current value that's the issue. It's only active for the current stack frame and seems to disable all the other hovers. The desired behaviour would be to show the debug hover only over variables and only when the Ctrl-key is not pressed. If either the mouse cursor is over something that's not a variable or if the Ctrl-key is pressed, the default editor hover should be shown.

**Comment by ramya-rao-a** [comment]
This behavior occurs for all languages and is not specific to Go. So moving it to the main repo.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#48971
