### ISSUE TITLE
auto import doesn't work with () imports

### ISSUE THREAD

**Issue by gflarity** [Microsoft/vscode-go#1618]
```
package main

import (
	"log"
	"time"

	apicorev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	typedcorev1 "k8s.io/client-go/kubernetes/typed/core/v1"
)

func main() {

	lo := apicorev1.ListOptions
	
}
```

Type 'fmt' and try to auto import it.  You'll get:

```
package main

import (
import "fmt"
	"log"
	"time"

	apicorev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	typedcorev1 "k8s.io/client-go/kubernetes/typed/core/v1"
)

func main() {

	lo := apicorev1.ListOptions
	fmt
}
```

**Comment by ramya-rao-a** [comment]
We stop parsing the lines when we find a `func` or `const` or `type` or `var` declaration. The regular expression used for this was missing to look for a space after these keywords and so mistook `typedcorev1` for `type` declaration :)

I have pushed a fix. Until I release an update, you can do the following to get the fix:
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by gflarity** [comment]
So far so good. Thanks for fixing this so quickly. Big fan of vscode+go.

**Comment by ramya-rao-a** [comment]
Thanks :)

**Comment by ramya-rao-a** [comment]
This bug fix is now out in the latest update to the Go extension (0.6.79)
Thanks for reporting @gflarity!
