### ISSUE TITLE
Stop debugging in VSCode macOS 10.13.4+ does not kill the process

### ISSUE THREAD

**Issue by rymcol** [Microsoft/vscode-go#1619]
As the title says, stopping the debugger in VSCode on macOS >= 10.13.4 will not terminate the process, and produces errors like the following when restarted:

`PANI[0000] Could not start the service. Failed with error: listen tcp :8000: bind: address already in use `

Steps to Reproduce:

1. Make sure you are running macOS 10.13.4+
2. Install the current master branch of https://github.com/derekparker/delve (recent fixes make it work on macOS again)
3. Open a go project in VSCode, preferably one that binds to a port or takes another action that prevents it from starting if another instance is already running
4. Configure the debugger in VSCode for your project
5. Start Debugging
6. Stop Debugging (at this step feel free to `ps aux | grep debug` to verify it doesn't stop)
7. Start Debugging, observe behavior

**Comment by aaahrens** [comment]
I have this issue as well.

**Comment by MarlonFan** [comment]
+1

**Comment by hielfx** [comment]
Also happening to me on Ubuntu 16.04 and Ubuntu 18.04

**Comment by maxtuzz** [comment]
As of the latest release I'm having the problem. Having to kill manually using:
```sh
$ sudo lsof -i tcp:8080
debug   76261 maxtuzzolino    4u  IPv6      0t0  TCP *:http-alt (LISTEN)
$ kill -9 76261
```

**Comment by ramya-rao-a** [comment]
Hello all,

There have been quite some changes to the debug adapter in the past month. The one that is of importance here is graceful detaching of delve at the end of the debugging session which should solve this issue.

Please feel free to re-open this or log a new bug if the latest version (0.6.86) has not solved this for you.

Thanks for your patience and Happy Coding!
