### ISSUE TITLE
is it support vendor?

### ISSUE THREAD

**Issue by johnnyluo586** [Microsoft/vscode-go#162]
when i use vendor dir save the 3th package, cann't use "go to definition".

**Comment by lukehoban** [comment]
Generally speaking, vendoring is up to each of the tools that `vscode-go` depends on to handle correctly.  For example `go build` does handle vendoring correctly, so error squiggles should handle environments that depend upon vendoring  (as long as you launch `code` from an environment with `GO15VENDOREXPERIMENT=1` or running   Go 1.6).  

However, it appears that `godef` does not support vendoring yet.  See https://github.com/rogpeppe/godef/pull/14 and https://github.com/rogpeppe/godef/issues/13.

I don't think there is anything we can/should do in `vscode-go` right now for this though, so I'll go ahead and close this issue.

**Comment by ctaggart** [comment]
There is now https://github.com/rogpeppe/godef/pull/25 which I installed with:
```
cd $GOPATH/src/github.com/rogpeppe
rm -rf godef
git clone https://github.com/grncdr/godef.git --branch vendor-support --single-branch
cd godef
go install
```

However, it didn't appear to fix it so this: 
![image](https://cloud.githubusercontent.com/assets/80104/14898433/884c1e82-0d3b-11e6-9cb0-3892c7cf8327.png)

Is it `godef` are another app that is needed for imports?

**Comment by zoumo** [comment]
This one is fixed in https://github.com/rogpeppe/godef/pull/33
