### ISSUE TITLE
Make preview the same as the original code on hover ?

### ISSUE THREAD

**Issue by di3663** [Microsoft/vscode-go#1629]
![1](https://user-images.githubusercontent.com/36250009/38765375-b599628c-3ff2-11e8-9b5c-8248ca46c364.png)

As you can see. the preview is ugly.

**Comment by m90** [comment]
This is the formatting that (the default) `godoc` will return, so there isn't much that the extension can do here. You can use a different `docsTool` like `gogetdoc` in your settings, which will format these previews correctly.

**Comment by di3663** [comment]
@m90 

gogetdoc do work although it's much slower than guru.

**Comment by m90** [comment]
In case you are not on Windows you could also try using the `go-languageserver`, which - at least in my setup - seems reasonably fast and has nicely formatted output: https://github.com/Microsoft/vscode-go#go-language-server-experimental
