### ISSUE TITLE
go-langserver not working with separate go.toolsGopath

### ISSUE THREAD

**Issue by sudo-suhas** [Microsoft/vscode-go#1631]
I use a separate folder for installing the Go tools and this is the relevant section of my editor settings:

```json
{
	"go.useLanguageServer": true,
    "go.toolsGopath": "~/installs/go-tools",
    "go.gopath": "~/dev/go"
}
``` 

When I open a project inside my `GOPATH`(`$HOME/dev/go/myprj`), pretty much all intellisense fails and I can see the following logs from `go-langserver`
```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///home/suhaskaranth/dev/go/src/gorank") is deprecated. Use rootUri instead.
parseLocalPackage error: no more package files found
[Error - 15:02:52] Request textDocument/hover failed.
  Message: no declaration found for hotelsdb.NewClient
  Code: 0 
...
[Error - 15:05:32] Request textDocument/hover failed.
  Message: failed to find doc object for /home/suhaskaranth/dev/go/src/gorank/cmd/gorank/main.go:29:2
  Code: 0 
```
The `GOPATH` passed to the language server was `/home/suhaskaranth/dev/go`. I saw some related issues - #185, #1580 but I am opening a new one because the scenario seems different to me. The project is inside my `GOPATH` but the language server is not.

**Comment by ramya-rao-a** [comment]
@sudo-suhas The project you are opening is `$HOME/dev/go/myprj` or `$HOME/dev/go/src/myprj` ?
Where does the folder `gorank` fit into all this?

According to the logs, looks like the folder opened in VS Code is `$HOME/dev/go/src/gorank`

I have the same set up as yours i.e the path in `go.toolsGopath` is different from ` go.gopath` and the language server works as expected for me.

**Comment by sudo-suhas** [comment]
I ran `Go: Install/Update tools` and after that it is working correctly. Closing the issue, will re-open if the problem reappears.
