### ISSUE TITLE
Brackets in strings causes incorrect indentation in Go files

### ISSUE THREAD

**Issue by Zariel** [Microsoft/vscode-go#1632]
Steps to Reproduce:

1.
If a string ends with a { then it causes the next line to indent as if it is a new block which is incorrect.
![image](https://user-images.githubusercontent.com/2213/38924776-b9de3c40-42f5-11e8-9e45-a39454322663.png)

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#50959
