### ISSUE TITLE
can't load manually created package because no go file in GOROOT

### ISSUE THREAD

**Issue by pontakornth** [Microsoft/vscode-go#1633]
This is my code
```

package database
import "database/sql"
import _ "github.com/go-sql-driver/mysql"
```

This is absolutely simple basic Go first lines of code. But it just said

can't load packages no go files in C:\Go\src

but it should be perfectly fine. Do I need to repeat workspace src folder?

I use go.inferGopath and no one gonna code in goroot!!

**Comment by ramya-rao-a** [comment]
The only error I see is about imported package not being used

![image](https://user-images.githubusercontent.com/16890566/39453063-56f9d1f0-4c89-11e8-95e1-0c462b30027d.png)

What do you get when you run `go build` on the folder that has this file?
