### ISSUE TITLE
"Add Import" and "Go to definition" do not work with builtin packages

### ISSUE THREAD

**Issue by conradoplg** [Microsoft/vscode-go#1636]
"Go: Add Import" does not work with builtin Go packages, and "Go to definition" also doesn't work for builtin packages.

go version go1.10.1 linux/amd64

VS Code 1.22.2
Go plugin 0.6.78

**Comment by yuansushow** [comment]
same problem

**Comment by conradoplg** [comment]
Setting GOROOT fixes the "Go to definition" issue, but not the "Add import" issue.

Furthermore, IMO the plugin shouldn't require GOROOT to bet set, it seems better to obtain it with `go env GOROOT` as described in https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really

**Comment by ramya-rao-a** [comment]
Where did you set the GOROOT?
Before you set the GOROOT, what did you see when you ran `echo $GOROOT` or `go env GOROOT` in the terminal in VS Code?

**Comment by ramya-rao-a** [comment]
And where did you set the GOROOT?
Outside or inside VS Code?

**Comment by conradoplg** [comment]
Outside; I opened VS Code with

```
GOROOT=/usr/lib/go-1.10 code
```

**Comment by uudashr** [comment]
@ramya-rao-a 
Somehow the go builder doesn't respect the `GOROOT `
https://github.com/golang/go/blob/master/src/go/build/build.go#L283-L287

@conradoplg 
Base on https://golang.org/doc/install section "_Installing to a custom location_" you need to set the PATH also
```
export GOROOT=$HOME/go1.X
export PATH=$PATH:$GOROOT/bin
```

Now the question is "_can vscode use non-standard go installation?_" If it can, then probably that we should do.

I think go compiler automatically use the `GOROOT` as context of the "_go_" command, so no need to set it on env for `GOROOT`

**Comment by uudashr** [comment]
@conradoplg @yuansushow 
can you run `gopkgs| head -n 10`

**Comment by uudashr** [comment]
I try to install golang on non-standard location
```
$ docker run -it --rm ubuntu
```

inside the docker container run
```
cd $HOME && apt-get update && \
    apt-get install -y --no-install-recommends curl git ca-certificates && \
    curl -C - -O -k https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz && \
    tar xzvf go1.10.2.linux-amd64.tar.gz && \
    export GOROOT=$HOME/go; export PATH=$PATH:$GOROOT/bin && \
    mkdir gopath; export GOPATH=$HOME/gopath; export PATH=$PATH; export PATH=$PATH:$GOPATH/bin && \
    go get -u github.com/uudashr/gopkgs/cmd/gopkgs && \
    echo "=== Executing gopkgs... ===" && \
    gopkgs| head -n 10
```

Output:
```
=== Executing gopkgs... ===
log
internal/testenv
mime/quotedprintable
encoding/json
net/rpc/jsonrpc
cmd/link/internal/ppc64
vendor/golang_org/x/net/nettest
cmd/vendor/github.com/google/pprof/internal/symbolizer
internal/syscall/unix
internal/syscall/windows
```
Make sure
1.  To set the `GOROOT` and expose `$GOROOT/bin` to the `PATH`
2. You have `GOPATH` and expose the `$GOPATH/bin` to the `PATH`

**Comment by jlucktay** [comment]
My builtin packages have been behaving strangely as well, recently.

It can see the builtin packages in the autocomplete list, like so:

![image](https://user-images.githubusercontent.com/460028/39820093-e93657ea-539c-11e8-90f6-7e56c974c267.png)

However, when I select one of the builtins to use, it says it can't find it:

![image](https://user-images.githubusercontent.com/460028/39820077-e121596a-539c-11e8-84f8-de0c3c71f473.png)

I have followed [this wiki article](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension) and tried setting `go.inferGopath` to true but the behaviour is still odd.

I don't want to have to hardcode the path to my Go install, because I'm using Homebrew on MacOS and that path will shift unpredictably with future versions.

Versions:
- Go: `go version go1.10.2 darwin/amd64`
- VSCode: `1.23.0`
- Extension: `0.6.79`

**Comment by ramya-rao-a** [comment]
@jlucktay 

- That's a build error, can you share the complete error from the Output pane? View -> Output -> Select Go from the drop down on the top right corner of the Output pane.
- What do you get when you run `go env GOROOT` in the integrated terminal? Does that match with the hombrwe location?
- Are the built-in packages appearing in the list when you run the command `Go: Add Import`?

**Comment by jlucktay** [comment]
Hi, @ramya-rao-a and thanks for investigating further!

I removed all of my `go.*` specific settings from VSCode preferences, and it settled down a little bit, but still seems a little off.

- The output from `View -> Output -> Go` looks like this after I open a `.go` file and edit and (re)save it:
```
/Users/jameslucktaylor/go/src/github.com/jlucktay/golang-workbench/codewars/playing-with-digits>Finished running tool: /Users/jameslucktaylor/go/bin/golint

/Users/jameslucktaylor/go/src/github.com/jlucktay/golang-workbench/codewars/playing-with-digits>Finished running tool: /usr/local/bin/go test -c -i -o /var/folders/92/8y_s2pz52wj_5byc2cvgv3w00000gp/T/go-code-check github.com/jlucktay/golang-workbench/codewars/playing-with-digits

/Users/jameslucktaylor/go/src/github.com/jlucktay/golang-workbench/codewars/playing-with-digits>Finished running tool: /usr/local/bin/go vet ./...
```

- `go env GOROOT` in the terminal gives this:
```
/usr/local/Cellar/go/1.10.2/libexec
```
This path lines up with Homebrew. 👌

- When I do `Go: Add Import` the built-in packages _**do not**_ show up, yet the packages themselves no longer have the red underline, and autocomplete gives all of the methods etc when typing, e.g. `math.` or `big.`:
![image](https://user-images.githubusercontent.com/460028/39854716-d0f60408-5420-11e8-9667-cc0d431a4988.png)

**Comment by conradoplg** [comment]
I've just noticed that this is not limited to golang-backports. All Go packages in Ubuntu are like that, including default packages from LTS versions. So maybe that's an argument for changing gopkgs.

**Comment by ramya-rao-a** [comment]
@jlucktay Can you follow the steps in https://github.com/Microsoft/vscode-go/issues/1636#issuecomment-386960076 and see if that fixes the issue of the built in packages not appearing when running the command `Go: Add Import`. Also, is your setup anyway similar to what @conradoplg describes in https://github.com/Microsoft/vscode-go/issues/1636#issuecomment-388037685?

**Comment by jlucktay** [comment]
@ramya-rao-a on Windows, installing the `Go-latest.vsix` file (which reports its version as `0.6.80-beta.3` within VSCode) has straightened out the `Go: Add Import` problem:
![image](https://user-images.githubusercontent.com/460028/39955340-25d48760-55c5-11e8-99c6-45162b2b604b.png)
On MacOS however, it's still off:
![image](https://user-images.githubusercontent.com/460028/39955620-cc6ae822-55c9-11e8-84bb-d6339af36552.png)

**Comment by uudashr** [comment]
@conradoplg try to re-install the Go tools
```
go get -u github.com/uudashr/gopkgs/cmd/gopkgs
```

I've made some changes.. hopefully that fix the Ubuntu issues.

**Comment by conradoplg** [comment]
@uudashr It works now!

Thank you and @ramya-rao-a for the excellent work :+1:

**Comment by uudashr** [comment]
Cool
