### ISSUE TITLE
[feature] add the coverage for single test run

### ISSUE THREAD

**Issue by primalmotion** [Microsoft/vscode-go#1637]
Code coverage highlighting only works when we run the package tests.

Would it be possible to have the coverage when we run individual test function? This would be very helpful to see what a test function is actually testing, without having other tests interfering when we run all of them.

Thanks,

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.79)
Add the setting `"go.coverOnSingleTest": true` to get code coverage when running individual tests either via the command or the code lens
