### ISSUE TITLE
issue with go and vim

### ISSUE THREAD

**Issue by x4m3** [Microsoft/vscode-go#1639]
Issue Type: <b>Bug</b>

i get an issue where i edit a blank go file (or any file actually) with the go package and vim package to reproduce the vim keybindings.

i start to edit my file with the `i` key (to go in insert mode) and start typing. after a couple of letters, i get an error on the down right side with `Extension host terminated unexpectedly.`, and when i try to go out of insert mode with the `esc` key, i get `command 'extension.vim_escape' not found`, same thing for the backspace key, and almost any key other than the letter keys.

BUT when i disable the go package, everything is back to normal.

i recently switched to vscode from vim and i want to learn go... i would love to do that on vscode and not vim...

anyone has got this issue?  
thank you

here's a screencast of me enabling/disabling the go package to reproduce the issue: <https://youtu.be/LOJTN-OTXnE>

a screenshot with the errors i get : ![screenshot from 2018-04-22 14-54-40](https://user-images.githubusercontent.com/8809909/39095218-2c91530e-463d-11e8-9a59-31b18dbfc4aa.png)

Extension version: 0.6.78
VS Code version: Code - Insiders 1.23.0-insider (c1cd4378c5e5dc434ed959e13556d05240a8ca18, 2018-04-20T05:12:24.983Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2451)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.12GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ramya-rao-a** [comment]
I dont see how the Go extension can interfere with the vim extension. Have you customized any keybindings?

The `command .. not found` means that the extension could not be loaded correctly.
@rebornix , any ideas?
