### ISSUE TITLE
Go build doesn't work with symlinks

### ISSUE THREAD

**Issue by Green7** [microsoft/vscode-go#1643]
VS Code 1.22.2
Go for Visual Studio Code: 0.6.78

Go build comand doesn't work with symlinks directories.

Steps to Reproduce:

1. create directory for project. For example: symlinktest. (in my case i created p:\symlinktest)
2. in gopath/src directory create symlink to symlinktest. Symlink has also name symlinktest 
3. create example main.go
4. open folder and build workspace from vscode, and you see:
  
```
"can't load package: package _/p_/symlinktest: cannot find package \"_/p_/symlinktest\" in any 
   of:
   C:\\Go\\src\\_\\p_\\symlinktest (from $GOROOT)
   C:\\Users\\username\\go\\src\\_\\p_\\symlinktest (from $GOPATH)",
```
Of course go build from command line works ok. Also you can debug this code under VsCode

**Comment by nebiros** [comment]
+1

Version 1.22.2 (1.22.2)

```
12:45 $ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nebiros/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nebiros/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bg/q5lvd51j5qz4jhrrfbfs3ycr0000gn/T/go-build062933725=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
The actual error:

```
/Users/nebiros/OneDrive/Projects/my-api>Finished running tool: /usr/local/opt/go/libexec/bin/go build -i -o /var/folders/bg/q5lvd51j5qz4jhrrfbfs3ycr0000gn/T/go-code-check _/Users/nebiros/OneDrive/Projects/my-api/router
can't load package: package _/Users/nebiros/OneDrive/Projects/my-api/router: cannot find package "_/Users/nebiros/OneDrive/Projects/my-api/router" in any of:
	/usr/local/opt/go/libexec/src/_/Users/nebiros/OneDrive/Projects/my-api/router (from $GOROOT)
	/Users/nebiros/go/src/_/Users/nebiros/OneDrive/Projects/my-api/router (from $GOPATH)
```

And this is the symlink:

```
~/go/src/github.com/MyCompany/my-api -> /Users/nebiros/OneDrive/Projects/my-api
```
```
14:32 $ pwd
/Users/nebiros/go/src/github.com/MyCompany/my-api
```

**Comment by ramya-rao-a** [comment]
@Green7 Can you open the parent of the symlinked folder and see what you get?

**Comment by Green7** [comment]
@ramya-rao-a I tried - and also have "can't load package" error.

**Comment by ramya-rao-a** [comment]
@Green7 Can you paste the complete text from the output pane? Include the cwd as well as the text that says "Finished running tool..."

**Comment by Green7** [comment]
As I wrote, there is no difference. If I open gopath/src/myfolder the error is the same. Also if I hover on tab in editor I have this same - physical file path.

**Comment by ramya-rao-a** [comment]
Hey @Green7 and @nebiros 

The last I left this issue I was not able to replicate the problem.
My best bet is that this is a set up issue or a combination of which folder was opened in VS Code due to upstream issues like https://github.com/microsoft/vscode/issues/18837 and https://github.com/microsoft/vscode/issues/49315

The upstream issues are closed, so my hope is that the issue here is resolved as well. Therefore, I will be closing this issue.

If the problem still persists, please log a new issue and I can walk you through debugging the problem with a local set up of the extension.

Happy Coding!
