### ISSUE TITLE
Modal popup on compile-time error.

### ISSUE THREAD

**Issue by jeffhoye** [microsoft/vscode-go#1644]
Since this change, https://github.com/Microsoft/vscode/commit/b987d5b0b58b773513b717d1ffd86fc22e456732, to vscode in February, any trivial syntax error causes this modal popup when starting the debugger:

```Failed to continue: Check the debug console for details.```

![image](https://user-images.githubusercontent.com/1181397/39250020-00948fa4-486e-11e8-83a4-f5ddd2ab1ee8.png)

The root cause of the error is usually a syntax error in my code, and the debug console properly explains the issue.  However, the popup adds a very common and annoying step of having to close it before proceeding to fix the issue.  

I'm not yet familiar with the details of how the language plugin should report these kind of issues to the debug subsystem, but it works differently in other language plugins.  For example, the same kind of issue in Python, or Node.js doesn't result in a modal popup.  

If there's no better way to report this issue to the vscode debug subsystem, my recommendation is to add a configuration option in the plugin to disable the error, or perhaps change them to warnings which show up in the new notification system rather than a modal popup.  

I made such a patch in vscode "core" but they rejected it saying that maybe vscode-go should report the error differently.  

Here's that discussion:
https://github.com/Microsoft/vscode/issues/48606

Here's some more info:
https://github.com/Microsoft/vscode/issues/45998
https://github.com/Microsoft/vscode/issues/44720

I'm happy to build a patch to this in vscode-go but want to make sure there's not a better or existing workaround already.

**Comment by ramya-rao-a** [comment]
@weinand Following up on your comment in https://github.com/Microsoft/vscode/issues/48606#issuecomment-384265967

Any error response sent by the debug adapter is shown as the modal popup. Same goes for errors from pre-launch tasks. How do you suggest debug adapters deal with compile errors?

Other examples:

Debugging a simple javascript file prints errors in the debug console.
Debugging an extension with errors with pre-launch tasks set up results in the modal popup.
![image](https://user-images.githubusercontent.com/16890566/39552377-d3f18c62-4e1d-11e8-8ee5-2c5bddf2d15f.png)

**Comment by jeffhoye** [comment]
Here's a potential issue:  
Some projects are too big to be continuously compiled in a timely manner.  Therefore all un-saved files are saved, and the build starts when the user hits "run (debug)."  

It would be handy to be able to return to launchService.ts whether the error was in "attaching" to the debug host (which should result in the modal popup) or whether there was a pre-launch failure and the error has already been reported to the user in a different way.  Perhaps this is already possible by returning an error in a pre-launch task?  Forgive me because I'm not very familiar with the debug pipeline.

**Comment by ramya-rao-a** [comment]
@isidorn Any thoughts on what @weinand has mentioned above in https://github.com/microsoft/vscode-go/issues/1644#issuecomment-386194054?

**Comment by isidorn** [comment]
@ramya-rao-a  I agree with his statement.

**Comment by ramya-rao-a** [comment]
@isidorn So, is the suggestion to use a modal like https://github.com/microsoft/vscode-go/issues/1644#issuecomment-386141660?

**Comment by isidorn** [comment]
@ramya-rao-a  Well if the debug extension can still launch the debugee I would expect it launches.
If it can not I would expect a modal popup with the error information.
Though this is just my point of view, you can check what other debug extensinos are doing, this does not sound like something specific only to Go.

**Comment by ramya-rao-a** [comment]
Thanks @isidorn 

I am going to stick with the modal approach.
