### ISSUE TITLE
gocode is broken on current go git master

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#1645]
Steps to Reproduce:

1. use current go git master.
2. get PANIC when you try to auto complete.

Possible fixes:

- https://github.com/mdempsky/gocode, slightly slower than nsf/gocode but NOT that slow, not noticeable really.
- https://github.com/OneOfOne/gocode my fork based on mdempsky's +  myitcv's vgo PR.

Just installing either of those will override nsf's gocode and you just can run `killall -9 gocode` without restarting vscode.

**Comment by OneOfOne** [comment]
With https://github.com/Microsoft/vscode-go/pull/1607, go-langserver will handle that.

- https://github.com/sourcegraph/go-langserver/issues/268

@slimsag @keegancsmith

**Comment by FiloSottile** [comment]
From https://github.com/nsf/gocode/blob/9d1e0378d/README.md:

> IMPORTANT: consider switching to https://github.com/mdempsky/gocode if you have problems starting with Go version 1.10, due to changes in binary packages architecture (introduction of package cache) I'm not going to adjust gocode for it for quite some time. There is a higher chance that fork under the given link will have some solution to the problem sooner or later.

**Comment by mccolljr** [comment]
Out of curiousity, has this been addressed? Is this package going to move to `github.com/mdempsky/gocode`? Manually installing and switching to that fork of `gocode` stops the `PANIC` messages and gets me completion again. Even `gocode`'s original author recommends switching to the fork, so I think this would be the right move. Or, at least provide a setting for which fork to use?

**Comment by localvar** [comment]
just FYI: To improve the performance of [https://github.com/mdempsky/gocode](https://github.com/mdempsky/gocode), I create another temporary folk at: [https://github.com/localvar/gocode](https://github.com/localvar/gocode)

**Comment by ramya-rao-a** [comment]
Well, I did give this a try, but the completion tests for all versions of Go started failing in travis.
See https://github.com/Microsoft/vscode-go/commits/new-gocode

If anyone can figure that out, then yes, we can move to `github.com/mdempsky/gocode`

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode-go/pull/1710 thanks to @m90
The fix is out in today's update to the Go extension (0.6.82)
