### ISSUE TITLE
"Go to Definition" Doesn't Find Function Definitions in Interface Implementations

### ISSUE THREAD

**Issue by tagatac** [Microsoft/vscode-go#1650]
Issue Type: <b>Bug</b>

1. Right-click a function call on an interface.
2. Click "Go to Definition".

Expected: The definitions of that function for each implementation of the interface are found and listed.
Actual: Overlay message: "No definition found for \<function\>".

This is problematic because idiomatic Go code uses interfaces extensively.

Extension version: 0.6.78
VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.61GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ramya-rao-a** [comment]
Can you provide a small code sample I can try this on?
Also, do you see the same after 
- adding the setting `"go.docsTool": "gogetdoc"`
- reloading VS Code
- Click Go to Definition, it may prompt you to install `gogetdoc`. Do so and try again.

**Comment by tagatac** [comment]
This is reproducible on the Go repository. Try, for example, to "Go to Definition" for `Done` on line 46 of context_test.go: https://github.com/golang/go/blob/eec8fb5ef3a60fae575f18ec05e7c21f5589f05f/src/context/context_test.go#L46.

I see the same behavior after setting `go.docsTool` to `gogetdoc` and installing `gogetdoc`.

**Comment by ramya-rao-a** [comment]
When you run `godef` and/or `gogetdoc` from the terminal, can you get to the definition or do you seen any error?

**Comment by tagatac** [comment]
I'm not sure if I'm invoking it properly:
```
~/go ❯❯❯ godef -f src/context/context_test.go XTestBackground
src/context/context_test.go:40:6
~/go ❯❯❯ godef -f src/context/context_test.go Done
parseLocalPackage error: no more package files found
godef: no declaration found for Done
```

**Comment by ramya-rao-a** [comment]
Install the [show-offset](https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset) extension. You will get the offset for the location under your cursor in the status bar.

Then run `godef -f your-file-path -o offset-for-the-symbol-you-are-getting-definition-for`

**Comment by tagatac** [comment]
```
❯❯❯ godef -f src/context/context_test.go -o 980
parseLocalPackage error: no more package files found
src/context/context.go:97:2
```
That gives me the location of the function signature in the interface definition, but there is an implementation of the interface with a definition for `Done` further down in context.go on line 175.

**Comment by ramya-rao-a** [comment]
The Go extension relies on the Go tools to give definition location. If you find that the results of `godef` and `gogetdoc` are not as expected, please log an issue in the repository for those tools.

You can also give our experimental integration with the Go language server from Sourcegraph a try. Add `"go.useLanguageServer": true` to your settings. this will prompt you to install the language server and the reload VS Code. The language server powers the definition and symbol search.

**Comment by tagatac** [comment]
Okay, but what about the fact that VS Code doesn't even show me the signature in the interface definition?

**Comment by tagatac** [comment]
@ramya-rao-a, it looks like this is a known limitation of `godef`: rogpeppe/godef#8. Is there a way to use `guru` for "Go to Definition"?

**Comment by ramya-rao-a** [comment]
Not at the moment.
For your specific case of interface and implementation, have you tried using the command `Go to Implementation` and `Peek Implementation`?

**Comment by tagatac** [comment]
Thanks for pointing out those commands, but `Go to Implementation` also reports "No implementation found for `Done`".

**Comment by tagatac** [comment]
`guru` returns the expected result:
```
~/go ❯❯❯ guru implements src/context/context.go:#3737
/Users/tag/go/src/context/context.go:97.2-97.5: abstract method func (Context).Done() <-chan struct{}
/Users/tag/go/src/context/context.go:325.21-325.24: 	is implemented by method (*cancelCtx).Done
/Users/tag/go/src/context/context.go:175.18-175.21: 	is implemented by method (*emptyCtx).Done
/Users/tag/go/src/context/context.go:325.21-325.24: 	is implemented by method (*timerCtx).Done
/Users/tag/go/src/context/context.go:97.2-97.5: 	is implemented by method (*valueCtx).Done
```

**Comment by tagatac** [comment]
It works with `"go.inferGopath": true`, thanks!
