### ISSUE TITLE
Request: Generating Documentation Stub for Exported Objects

### ISSUE THREAD

**Issue by shreyu86** [Microsoft/vscode-go#1653]
This is a feature request and could save some time during development and encourage adding relevant documentation via doc comments.

Per [Effective Go](https://golang.org/doc/effective_go.html):
> All top-level, exported names should have doc comments, as should non-trivial unexported type or function declarations. See https://golang.org/doc/effective_go.html#commentary for more information about commentary conventions.

During the course of development I often come across this situation where some the linter (`golint`) complains about `should have comment or be unexported` and I often go and fix this issue by going through each of these warnings thanks to the built in highlighter in vs-code which highlights the linter issues. Having done this a couple of times this process seemed repetitive and was searching for tools to aid in creating a stub for doc comments similar to the utility provided by `Go: Add Tags To Struct Fields`. 

Currently, I have a utility written in Go which does the following: 

Identify exported items in the current project and adds a stub comment with a TODO to fill in the rest. 
Before:
![image](https://user-images.githubusercontent.com/311217/39592546-ed3523c0-4ebb-11e8-8131-c2659091da8c.png)
![image](https://user-images.githubusercontent.com/311217/39592536-e51c1b8a-4ebb-11e8-8283-af5ceade8f97.png)

After: 
![image](https://user-images.githubusercontent.com/311217/39592567-feb43140-4ebb-11e8-9634-df93c499ff49.png)

I use the TODO Highlighter from vs-code to keep track of this to-do item in and complete the documentation. Currently the utility that I have works for all exported items. I am currently working on integrating it with vs-code to make it more useful, following existing examples. 

I wanted to open this Feature Request to gauge interest on this topic so as to open a PR for this feature if this type of functionality could be handy to other users.

**Comment by m90** [comment]
That's a very personal opinion, but I feel this is kind of defeating the purpose of using golint. golint wants you to write a comment, not a TODO for doing that. If you are fine with not having comments yet, you can still build the code.

**Comment by ramya-rao-a** [comment]
Including that stub (just the member name not a TODO following it) in the auto-completion list when user types `//` above an exported member is a good feature addition. 
This way we don't circumvent the linting warning, user still has to type text after the member name.

#1005 is the feature request that is tracking exactly the same thing.
So closing this in favor of that.

**Comment by ramya-rao-a** [comment]
I have provided some pointers in https://github.com/Microsoft/vscode-go/issues/1005#issuecomment-387878292 if you want to get started with this

**Comment by shreyu86** [comment]
Thanks for the feedback, I will check out #1005 and the pointers and start working towards a prototype.
