### ISSUE TITLE
Debug: Environment Variables are Not Retrieved (Ubuntu)

### ISSUE THREAD

**Issue by napalm684** [Microsoft/vscode-go#1654]
Versions:
Go 1.10.1 linux/amd64
Delve Debugger 1.0.0
Vs Code Version: 1.22.2
Ubuntu 16.04.4 LTS

Related: 
https://github.com/Microsoft/vscode-go/issues/947

Steps to Reproduce:

1. Code
```
package main

import (
     "fmt"
     "os"
)

func main() {
     t  := os.Getenv("ENV_VAR")
     fmt.Println(t)
}
```

2. Set environment variable EXPORT ENV_VAR="value"

3. Start program in debug

4. Verify t is empty string

I set the environment variable, verified go run main.go was fine.  I tried the backend values in launch.json with no change in the behavior.  I can confirm delve on the command-line works as expected.

**Comment by ramya-rao-a** [comment]
Did you set the environment variable in the integrated terminal inside VS Code? And then run `go run main.go` from the same terminal?

All extensions are run in a separate process and so when you set a new environment variable in the terminal, the extensions do not get the same.

Try this:
- set the environment variable in an external terminal
- run `code` from the same terminal
- now debug

**Comment by napalm684** [comment]
@ramya-rao-a Thank you that indeed corrected the problem.  Unless I missed it somewhere that should be part of the docs?

**Comment by ramya-rao-a** [comment]
Good point, I've created a [page](https://github.com/Microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting) in the wiki in this repo that covers it and other FAQs
