### ISSUE TITLE
Avoid adding snippet for function suggest when cursor is followed by ()

### ISSUE THREAD

**Issue by klaidliadon** [Microsoft/vscode-go#1655]
Right now `go.useCodeSnippetsOnFunctionSuggestWithoutType: true` always appends the snippet. 

It would be really useful if it wouldn't when the first non-space character after the cursor is a `(`.

**Comment by ramya-rao-a** [comment]
Can you give an example?

**Comment by klaidliadon** [comment]
Suppose that `|` is the cursor and I have `r.Lo|()`
Since the round parenthesis are already there, when I choose `Lock` from the suggestions the line becomes  `r.Lock()()` instead of `r.Lock()`

https://giphy.com/gifs/2yzHKEmXsaNQkyqrLv

**Comment by ramya-rao-a** [comment]
Good point
PRs are welcome to fix this.
The place to add the fix would be https://github.com/Microsoft/vscode-go/blob/0.6.79/src/goSuggest.ts#L171

**Comment by ramya-rao-a** [comment]
This bug fix is now out in the latest update to the Go extension (0.6.81)
