### ISSUE TITLE
Add "goformat" to the allowed values for go.formatTool

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode-go#1656]
Please add "goformat" to the allowed values for go.formatTool.
goformat is an extended version of gofmt with more options:

https://github.com/mbenkmann/goformat

This tool would also allow you to revisit issue #1011 but all I care about is having VSCode accept "goformat" as a value for go.formatTool. Usage is exactly as gofmt, so the backend can call it exactly the same way.

**Comment by ramya-rao-a** [comment]
I believe you should be able to use `goformat` without any support from the Go extension if it works similar to the other tools we support.

- Add `"go.formatTool": "goformat"` to your settings. (There will be a warning that it is not valid, but ignore that)
- Install the `goformat` tool so that it is available in the $PATH

The extension should just pick it up and run it.

**Comment by mbenkmann** [comment]
It runs it, but I get a perpetual entry in my Problems tab, so that it always has the blue bubble, which makes harder to notice when I have an actual problem.

**Comment by ramya-rao-a** [comment]
That makes sense. PRs are welcome to this option to `go.formatTool`

Just add an entry at https://github.com/Microsoft/vscode-go/blob/0.6.79/package.json#L507. That should fix the warning in the settings.
Also add an entry in https://github.com/Microsoft/vscode-go/blob/0.6.79/src/goInstallTools.ts#L20 which will ensure you get the right prompt when you have chosen `goformat`, but its not installed

**Comment by mbenkmann** [comment]
Thanks for the code pointers. I managed to implement it.
Since goformat allows style options I think it would make sense to implement the following behavior:

If go.formatFlags == [] and go.formatTool == "goformat", then use a default set of flags that corresponds to

* editor.insertSpaces
* editor.tabSize.

I would assume that this automatically fixes issue #1011 if the user is willing/able to set go.formatTool="goformat".

What do you think? Should I add this at
https://github.com/Microsoft/vscode-go/blob/0.6.79/src/goFormat.ts#L31

**Comment by ramya-rao-a** [comment]
Let's not have hidden defaults that way. Sometimes, a user might indeed want to pass no flags. Also, it wouldn't be right for the Go extension to have formatting opinions :). That's purely a personal decision.

**Comment by mbenkmann** [comment]
But that's exactly the point. We should honor the user's setting of editor.insertSpaces. VSCode contains this default:

"[go]": {
    "editor.insertSpaces": false,
    "editor.formatOnSave": true
  },

If the user deliberately changes insertSpaces to true, he clearly does not want tabs. If he also deliberately changes go.formatTool to goformat, he clearly does not want standard gofmt formatting.
I'm not suggesting any hidden defaults. I'm suggesting to use the user's settings.

**Comment by ramya-rao-a** [comment]
I am sorry, I misunderstood.

Yes, translating the user's settings for `editor.insertSpaces` and `editor.tabSize` to corresponding flags for `goformat` makes sense.

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.80)
