### ISSUE TITLE
Go Function Signature in the statusbar

### ISSUE THREAD

**Issue by petermbenjamin** [Microsoft/vscode-go#1657]
Hi,

I was curious if vscode-go or other VSCode Go-related plugins can display Go function signatures in the VSCode statusbar, similar to [this in Atom](https://atom.io/packages/go-signature-statusbar)

Coming from Vim, I am accustomed to using the keyboard for much of the navigation and interactions with the editor.

It also seems possible since other VSCode extensions seem to utilize the statusbar to implement various functionality.

Thank you.

**Comment by ramya-rao-a** [comment]
> Coming from Vim, I am accustomed to using the keyboard for much of the navigation and interactions with the editor.

You can already see the function signature when you are typing inside the () of the function call.
The same can be invoked by Ctrl+Shift+Space or Cmd+Shift+Space when the cursor is inside the () of the function call. 

![image](https://user-images.githubusercontent.com/16890566/39730654-c081a6d2-5217-11e8-908c-7691ce52dcea.png)

Is there still a benefit to see this in the status bar instead of inline in the editor?

**Comment by petermbenjamin** [comment]
Hi @ramya-rao-a,

Thank you for your response. 

The in-editor suggestion works great when I’m writing a new function. But, When reading code, it would be a lot more convenient to display the signature of the function under the cursor in the status bar without having to press key combinations. 

Another minor issue with in-editor function signature is that long signatures are truncated and I would have to invoke the same key combinations again to pop the signatures out to a separate little widget.

**Comment by petermbenjamin** [comment]
Thanks @ramya-rao-a. I wasn't aware that the `Show Hover` (default <kbd>⌘K</kbd>+<kbd>⌘I</kbd>) was an exposed API that can be bound to keyboard shortcuts. This certainly helps a little. 

I was doing something similar with <kbd>CTRL</kbd> + <kbd>SPACE</kbd> (intellisense), which leads me to...

> Another minor issue with in-editor function signature is that long signatures are truncated

What I meant was the intellisense autocompletion truncates long function signatures:

<img width="493" alt="screen shot 2018-05-08 at 2 16 46 pm" src="https://user-images.githubusercontent.com/6811830/39783894-7413ec6a-52cb-11e8-8080-191c189aa6df.png">

which forces me to press <kbd>CTRL</kbd> + <kbd>SPACE</kbd> again to expand it:
<img width="685" alt="screen shot 2018-05-08 at 2 26 38 pm" src="https://user-images.githubusercontent.com/6811830/39784045-edd873c2-52cb-11e8-9a85-6cbc40cbd178.png">

I will give the `Show Hover` feature a try, although I slightly dislike that the modal covers text behind it:
<img width="557" alt="screen shot 2018-05-08 at 2 31 37 pm" src="https://user-images.githubusercontent.com/6811830/39784246-97266dc6-52cc-11e8-8236-0c9b1b5d427d.png">

Thank you for the help.

**Comment by ramya-rao-a** [comment]
Alright then, Happy Coding!
