### ISSUE TITLE
The "." (dot) inside comment open the suggestion/completion list

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode-go#1659]
Steps to Reproduce:

1.  Create comment on the right side of the code
2. Type "." (dot) and the completion list will opened

<img width="636" alt="screen shot 2018-05-06 at 01 40 54" src="https://user-images.githubusercontent.com/166053/39666538-71010380-50cf-11e8-82ef-60d357d704c1.png">

Expect: The completion should not appear since it's inside the comment

**Comment by ramya-rao-a** [comment]
Nice catch.
PRs are welcome.
The fix would go in the place where we have a check to avoid calling suggestions when the complete line is a comment. https://github.com/Microsoft/vscode-go/blob/0.6.79/src/goSuggest.ts#L55

**Comment by ramya-rao-a** [comment]
This bug fix is now out in the latest update to the Go extension (0.6.80)
