### ISSUE TITLE
go.goroot setting ignored

### ISSUE THREAD

**Issue by variab1e** [Microsoft/vscode-go#166]
go.goroot setting igorned despite being set, I am still receiving `No 'go' binary could be found on PATH or in GOROOT.`

go.exe is at `~/dev/lib/go/bin`
go.goroot is set to `~/dev/lib/go`
go.gopath is set to`~/dev/`

**Comment by lukehoban** [comment]
@variab1e Do you have the latest version of the extension installed?  There was an issue with this that I believe was fixed a few weeks ago.  I don't see any obvious problem with the handling of `go.goroot` in the current code.  Please reopen if you are still seeing this after updating though.
