### ISSUE TITLE
Optimize breakpoint changes during debug

### ISSUE THREAD

**Issue by lggomez** [microsoft/vscode-go#1660]
https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L531-L573

The current approach does the following, upon setting/unsetting a breakpoint during debug:
1. Traverse all breakpoints and clear them via ClearBreakpoint apicalls
2. Restore existing (active) breakpoints from DebugProtocol args and re-create them via CreateBreakpoint apicalls
3. Send the debug protocol response

We might be able to optimize this so we only update modified breakpoints via [AmendBreakpoint](https://godoc.org/github.com/derekparker/delve/service/rpc2#RPCServer.AmendBreakpoint) apicalls (and use ClearBreakpoint/CreateBreakpoint for the rest accordingly)

The downside is that DebugProtocol.SetBreakpointsArguments only contains the breakpoints that have been set, and not which ones were unset until the request

I can work on this but I have the following questions
- Do breakpoint editions also trigger a setBreakPointsRequest?
- Can setBreakPointsRequest calls be concurrent? I think we can use a breakpoint cache to compare the breakpoints state from the last setBreakPointsRequest call, and then process the modified breakpoints only

**Comment by ramya-rao-a** [comment]
@roblourens Can you answer the above questions?

**Comment by ramya-rao-a** [comment]
@lggomez 

> Do breakpoint editions also trigger a setBreakPointsRequest?

What kind of edits are we talking about here?

> Can setBreakPointsRequest calls be concurrent? I think we can use a breakpoint cache to compare the breakpoints state from the last setBreakPointsRequest call, and then process the modified breakpoints only

Are you asking about this because if the calls were indeed concurrent, then the cache wouldnt work?

**Comment by stamblerre** [comment]
Filed https://github.com/golang/vscode-go/issues/163 in our new repository, as we are migrating: #3247. Let's continue the discussion there.
