### ISSUE TITLE
go-langserver output pane re-opens after being manually closed

### ISSUE THREAD

**Issue by antismap** [Microsoft/vscode-go#1661]
When editing a go file with the langserver option enabled, the go language server output window opens often and displays various error, for example when saving a file containing compiling errors. When closing the pane, it reopens shortly after.

Example of the errors in the output pane:
```
[Error - 10:46:43 AM] Request textDocument/signatureHelp failed.
  Message: import "/home/michael/workspace/go/micmail": cannot import absolute path
  Code: 0 
jsonrpc2 handler: notification "textDocument/didOpen" handling error: Open git:/home/michael/workspace/go/micmail/imapHandler.go?%7B%22path%22%3A%22%2Fhome%2Fmichael%2Fworkspace%2Fgo%2Fmicmail%2FimapHandler.go%22%2C%22ref%22%3A%22~%22%7D: unable to read out-of-workspace resource from virtual file system
jsonrpc2 handler: notification "textDocument/didChange" handling error: Open git:/home/michael/workspace/go/micmail/imapHandler.go?%7B%22path%22%3A%22%2Fhome%2Fmichael%2Fworkspace%2Fgo%2Fmicmail%2FimapHandler.go%22%2C%22ref%22%3A%22~%22%7D: unable to read out-of-workspace resource from virtual file system
jsonrpc2 handler: notification "textDocument/didClose" handling error: Open git:/home/michael/workspace/go/micmail/imapHandler.go?%7B%22path%22%3A%22%2Fhome%2Fmichael%2Fworkspace%2Fgo%2Fmicmail%2FimapHandler.go%22%2C%22ref%22%3A%22~%22%7D: unable to read out-of-workspace resource from virtual file system
[Error - 10:55:11 AM] Request textDocument/signatureHelp failed.
  Message: import "/home/michael/workspace/go/micmail": cannot import absolute path
  Code: 0 
```
This seems to be similar to this: https://github.com/felixfbecker/vscode-php-intellisense/issues/65

I'm running : 

Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T15:23:19.356Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Fedora 28

Steps to Reproduce:

1. Enable language server in settings and restart vscode
2. Start editing some code and write some code causing compilation errors :)
3. Save the file

**Comment by ramya-rao-a** [comment]
Thanks for reporting!
This is being tracked in #1662
