### ISSUE TITLE
Rename error disappear so fast that I can not see them clearly

### ISSUE THREAD

**Issue by davyzhang** [Microsoft/vscode-go#1663]
I didn't press any key during the showing of the message, just waited
![untitled 1](https://user-images.githubusercontent.com/576863/39680999-4bf9ccba-51d9-11e8-8bf2-46f5dbed5421.gif)

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#49411

**Comment by ramya-rao-a** [comment]
In the latest update to the Go extension (0.6.80), the rename errors will now show up in the output pane.
