### ISSUE TITLE
Regression in the setting of toolsEnvVars

### ISSUE THREAD

**Issue by tanguylebarzic** [Microsoft/vscode-go#1664]
https://github.com/Microsoft/vscode-go/commit/be30dfc597d94194b96ae5a03ca7731a90795e8a introduced a regression: For environment variables that are not set in process.env, the value taken from toolsEnvVars is not set. I'll send a PR shortly.

**Comment by ramya-rao-a** [comment]
Fixed with #1665
Thanks for reporting and providing the fix @tanguylebarzic !
