### ISSUE TITLE
formatOnSave extremely slow at piping

### ISSUE THREAD

**Issue by FiloSottile** [Microsoft/vscode-go#1668]
`formatOnSave` is being extremely slow, and failing if `editor.formatOnSaveTimeout` is not set to north of 5000ms on moderately large (8000 lines) files.

```
[Extension Host] Formatting took too long(5647ms). Format On Save feature could be aborted.
```

**The issue is not in the formatting tool, but in how the input is sent to it.**

I replaced `goimports` (my `go.formatTool`) with this script to compare invocations from VS Code:

```
#! /bin/bash

echo "$@"
echo "$PWD"
date
wc
date
```

When run within VS Code:

```
Mon May  7 20:13:27 EDT 2018
    2879   12052   90302
Mon May  7 20:13:31 EDT 2018
```

When run with the exact same input, invocation and environment from a shell with `pbpaste`:

```
Mon May  7 20:14:04 EDT 2018
    2879   12052   90302
Mon May  7 20:14:04 EDT 2018
```

You can see that it's taking 4 seconds just to pipe the input to `wc`, between the two `date` calls.

Reporting it here instead of to VS Code because in https://github.com/Microsoft/vscode-go/issues/1419#issuecomment-355654879 it says this extension implemented its own version of `formatOnSave`.

I have the global `editor.formatOnSave` on, in case it matters. Running on macOS.

**Comment by OneOfOne** [comment]
I've been having weird formatting issues recently (I *think* they got fixed with current git version of the extension, time will tell).

Any way, I've been using (unintended self-plug) https://marketplace.visualstudio.com/items?itemName=oneofone.save-runner with this:

```
"save-runner.enabled": true,
	"save-runner.commands": [
		{
			"enabled": true,
			"include": "\\.go$",
			"useTempFile": false,
			"pre": "goimports",
		}
	]
```

**Comment by SuburbanFilth** [comment]
I am having the same issue and it started out of nowhere today.

**OS :** elementaryOS
**VSCode :** 
- Version 1.23.1
- Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
- Date 2018-05-10T16:04:33.747Z
- Shell 1.7.12
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64
**VSCode-Go :** 0.6.80

**Comment by FiloSottile** [comment]
I am now noticing flakey `formatOnSave` with the default timeout of 750ms with files of just 1000 lines on a MacBook Pro (13-inch, 2017) with macOS 10.13.4.

**Comment by ramya-rao-a** [comment]
@OneOfOne's issue here was due to the language server which has been addressed in https://github.com/Microsoft/vscode-go/issues/1667

@SuburbanFilth Have you been using the language server as well?

@FiloSottile Thanks for the detailed investigation. I haven't had time to look into why the piping is so slow. We will definitely get back to this, this month.

**Comment by ramya-rao-a** [comment]
#1766 will definitely help for VS Code 1.25 and above as the outline view in the explorer now opens up by default. Not sure if  it helps #1668 when the outline view in the explorer is disabled.

**Comment by FiloSottile** [comment]
formatOnSave was timing out after 30s while developing golang.org/x/crypto/chacha20poly1305. The issue impacted any file in the package, but the cause is probably a giant source file with test vectors. goimports from the command line takes 0.04s. 

No idea why, but a restart of the editor fixed it. There were no pending updates.

**Comment by atombender** [comment]
I'm using modules, yes. My formatter is `goimports`.

**Comment by ramya-rao-a** [comment]
@atombender Let's use #1532 to track issues that show up when using modules

**Comment by ramya-rao-a** [comment]
@FiloSottile Since you haven't seen any issues here in the past month, I'll close this issue.
