### ISSUE TITLE
Documentation on mouse hover

### ISSUE THREAD

**Issue by SuburbanFilth** [Microsoft/vscode-go#1669]
Hey,

I checked to see if the issue has been reported, but did not see anything. If the issue has already been reported, then please close this :)

**Problem :** If you hover with the mouse over one of built-in keywords you do not get any documentation.

Steps to Reproduce:

1. create a go file
2. type **append**
3. Hover over it

**Comment by ramya-rao-a** [comment]
By default, we use the godef tool to provide the definition of the symbol and then use `godoc` to get the information from the location. `godef` doesn't provide any location for the builtin symbols like `append`

On the other hand, you can use `gogetdoc` instead by adding the setting `"go.docsTool": "gogetdoc"`. This will give you the hover information, but running a `Go to definition` command on `append` would still not give you the definition.

The reasons are covered in https://github.com/Microsoft/vscode-go/issues/674
