### ISSUE TITLE
Adopt new APIs from VS Code

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#1676]
Go over the "Extension Authoring" section of the Release Notes of the past year to see what can be adopted in the Go extension. Below are a few examples to begin with 

June 2018
- [ ] Support the new `Organize Imports` code action if possible. This might help the case where users want to use the `-s` flag for formatting (which isn't supported by goimports/goreturns) as well as have the ability to manage the imports
- [ ] Provide all the refactoring commands via the new Refactor context menu if possible
- [ ] Explore if the new notification with cancel option for long running operations can be used for the "Cancel Tests" feature
- [x] Update code to use the `affectsConfiguration` method on `ConfigurationChangeEvent`
- [ ] Language aware code folding

July 2018 and future
- [ ] Debug Adapter Protocol updates
- [ ] Investigate if the `process` event in the Debug Adapter Protocol can help in killing the ghost debug processes that remain after debugging is over
- [ ] Explore what it takes to adopt the Logpoints feature if at all possible
- [ ] Explore what needs to be done to get a good Live Share experience for Go

**Comment by mattetti** [comment]
I'm definitely interested in https://code.visualstudio.com/docs/editor/refactoring being able to extract variables, constants or even functions would be really awesome. 
What's your plan of attack, what can we do to help?

**Comment by lggomez** [comment]
Do you have a list of the updates on the debug adapter?

For starters, we can use args.breakpoints instead of args.lines in the setBreakPointsRequest method, which I may do for #1720 (and possibly #1660, if aplicable)

**Comment by ramya-rao-a** [comment]
@mattetti 

For starters wrt to refactoring, I was looking at exposing the generic "Refactor" option in the context menu which could then be used for things that we already support like filling structs, interface stubs etc.

To add new features like extracting variables/constants/functions, we need to implement them first.

I can revive the [old PR](https://github.com/Microsoft/vscode-go/pull/404) that use `godoctor` for the extract feature. I could use help in testing it. Last time we took a shot at it, it didn't work for a lot of common cases

@lggomez You seem to be on fire :) I didn't realize the conditional breakpoint feature was so straightforward to implement.

I don't have the list of updates on the debug adapter on hand. I was planning to just go over the "Extension Authoring" section of the [release notes](https://code.visualstudio.com/updates) for every month in the past year and see which ones can be applied to Go.

**Comment by ramya-rao-a** [comment]
Closing this issue as all new APIs will be taken up by the language server and no new work is planned for the extension on the above fronts.

cc @stamblerre

**Comment by ramya-rao-a** [comment]
And there is an independent effort going on to explore the Debug Adapter Protocol 

cc @quoctruong
