### ISSUE TITLE
Sometimes i can't save files when language server is enabled

### ISSUE THREAD

**Issue by faceair** [Microsoft/vscode-go#1677]
![qq20180515-193457-hd](https://user-images.githubusercontent.com/3659110/40054578-e33f767a-5877-11e8-8ab8-bf368005a784.gif)

This is the error message in `go-langserver` output:
```jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for out of range position &{{'\x00' '\x00'} {';' '\x00'}} on "file:///Users/faceair/Developer/scooter/src/scooter/broker/message/message.go"
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'\x1b' '\x1f'} on "file:///Users/faceair/Developer/scooter/src/scooter/broker/message/message.go": character 31 is beyond line 27 boundary
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for out of range position &{{'\x00' '\x00'} {':' '\x00'}} on "file:///Users/faceair/Developer/scooter/src/scooter/broker/message/message.go"
[Error - 19:35:54] Request textDocument/hover failed.
  Message: invalid position: /Users/faceair/Developer/scooter/src/scooter/broker/message/message.go:27:30 (character 30 is beyond line 27 boundary)
  Code: 0 
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'\x1b' '\x1f'} on "file:///Users/faceair/Developer/scooter/src/scooter/broker/message/message.go": character 31 is beyond line 27 boundary
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for out of range position &{{'\x00' '\x00'} {':' '\x00'}} on "file:///Users/faceair/Developer/scooter/src/scooter/broker/message/message.go"```

**Comment by faceair** [comment]
1. This error will continue if I don't reload window or close this file, and now I still keep the issue scene. I can't consistently reproduce, but this issue occurs several times a day.
2. I'll try disabled language-server today.
3. No.

I have been using `go language server` for a long time, this error is only occurred after upgrading VSCode to 1.23, maybe is the new version break something.

**Comment by faceair** [comment]
[QQ20180516-110825-HD.mp4.zip](https://github.com/Microsoft/vscode-go/files/2007401/QQ20180516-110825-HD.mp4.zip)
I made a video display the output. It seems that it has nothing to do with `go language server`, and now I doubt whether it is the problem of format tool.
The following is my settings.json
```
{
    "editor.dragAndDrop": false,
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.fontSize": 12.4,
    "editor.minimap.renderCharacters": false,
    "editor.scrollBeyondLastLine": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "explorer.openEditors.visible": 0,
    "extensions.ignoreRecommendations": true,
    "files.autoSave": "onFocusChange",
    "files.exclude": {
        "**/*.py[co]": true
    },
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "git.autofetch": true,
    "git.confirmSync": false,
    "go.autocompleteUnimportedPackages": true,
    "go.gopath": "~/Developer/Go",
    "go.lintTool": "golint-free",
    "go.toolsGopath": "~/Developer/Go",
    "go.useLanguageServer": true,
    "python.linting.flake8Args": [
        "--ignore=E501,E702"
    ],
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "search.exclude": {
        "**/.git": true,
        "**/node_modules": true,
        "**/vendor": true
    },
    "search.smartCase": true,
    "terminal.integrated.fontFamily": "Monaco",
    "vsicons.dontShowNewVersionMessage": true,
    "window.openFoldersInNewWindow": "on",
    "window.restoreWindows": "all",
    "window.zoomLevel": 0,
    "workbench.activityBar.visible": false,
    "workbench.colorTheme": "Ayu One Dark",
    "workbench.iconTheme": "vscode-icons",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.statusBar.feedback.visible": false
}
```
The `go.lintTool` is [golint-free](https://github.com/faceair/), maybe it's not related.

**Comment by faceair** [comment]
And in developer console, I found this message. 
```
[Extension Host] Could not find packages. Ensure `gopkgs -format {{.Name}};{{.ImportPath}}` runs successfully.
log.ts:171   ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (/Users/faceair/.vscode/extensions/ms-vscode.go-0.6.80/node_modules/vscode-languageclient/lib/protocolConverter.js:98:26)
	at asHover (/Users/faceair/.vscode/extensions/ms-vscode.go-0.6.80/node_modules/vscode-languageclient/lib/protocolConverter.js:131:31)
	at <anonymous>
```
[full console.log](https://github.com/Microsoft/vscode-go/files/2007426/console.log)

**Comment by ramya-rao-a** [comment]
> I have been using go language server for a long time, this error is only occurred after upgrading VSCode to 1.23, maybe is the new version break something.

In the recent versions, the Go language server provides formatting abilities which can change file contents. This might be the reason why you didnt see this before. 

> The go.lintTool is golint-free, maybe it's not related.

Yes, thats not related

The error on `gopkgs` is unrelated too.


I have disabled the format feature coming from language server in the master branch. Can you follow the below to get that change and then see if you still have the issue?

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by faceair** [comment]
Thank you. I'll give you feedback tomorrow or the day after tomorrow.

**Comment by faceair** [comment]
And I noticed that the previous version of the extension flashes the file syntax when saving the file, and the latest version doesn't have this issue.

**Comment by faceair** [comment]
> @faceair By "latest version", do you mean the version after following the steps in #1677 (comment)?

Yes, and I mean the previous version is 0.6.80.

**Comment by faceair** [comment]
In the [latest version](https://github.com/Microsoft/vscode-go/issues/1677#issuecomment-389388519), this issue can't reproduce. 
According to [this](https://github.com/Microsoft/vscode-go/issues/1677#issuecomment-389447685) I guess it is the language server covered the file content when saving it, and editor re rendering the file syntax highlighting.

0.6.80
![0 6 80](https://user-images.githubusercontent.com/3659110/40175354-68c151ae-5a0a-11e8-84c4-dada29435d0e.gif)

0.6.81.beta2
![0 6 81 beta2](https://user-images.githubusercontent.com/3659110/40175377-766c99a8-5a0a-11e8-9f0c-99be7e1151d3.gif)

**Comment by ramya-rao-a** [comment]
Great, thanks for verifying and Happy Coding!
