### ISSUE TITLE
Method Suggestion

### ISSUE THREAD

**Issue by klaidliadon** [Microsoft/vscode-go#168]
When you write func in a package the suggestion list show also a method constructor for each type in the package that produces the following output:

``` go
func (p *PkgType) Method(){

}
```

Pressing tab should focus in order:
1. the `*` to remove the pointer sign
2. the `Method` to change the name
3. In the parenthesis to change the argument
4. After the parenthesis to change the return type
5. In the method body

**Comment by lukehoban** [comment]
I like the idea of this.  I noticed that GoSublime has a similar feature.  

It should be possible to add this on top of the same "smart snippets" infrastructure that was added in f8508b40f80a3ce812201ba5eadc268225684b61.

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update of the Go extension (0.6.70)
