### ISSUE TITLE
Method signature highlighting incorrect parameter when commas inside string

### ISSUE THREAD

**Issue by cassiobock** [Microsoft/vscode-go#1682]
When I type commas inside a string parameter, the current highlighted parameter changes. I tested using a JS file and it didn't happened. Disabling all extensions except this one didn't fixed the issue as well.

**Sample code**
``` go
strings.Replace(",,,")
```
**Image**
![image](https://user-images.githubusercontent.com/3936166/40253921-f97a9d4c-5ab7-11e8-93bd-48ca892a8091.png)

**Comment by ramya-rao-a** [comment]
Nice catch. 

We use commas to determine how many of the parameters are already typed in. Looks like we end up counting commas even when they are inside a string.

PRs are welcome to fix this bug.
The fix should go here: https://github.com/Microsoft/vscode-go/blob/0.6.80/src/goSignature.ts#L92

**Comment by cassiobock** [comment]
Hi @ramya-rao-a,

Thanks for the heads up. I will definitely take a look later today.

**Comment by lggomez** [comment]
@cassiobock are you still working on this or I am free to take a look at it?

**Comment by cassiobock** [comment]
Hey @lggomez, feel free to take a look.

**Comment by ramya-rao-a** [comment]
The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension has the fix for this issue

**Comment by ramya-rao-a** [comment]
This bug fix  is out in the latest release(0.10.0) of the Go extension
