### ISSUE TITLE
Coverage display is misinterpreting the coverprofile file

### ISSUE THREAD

**Issue by kentquirk** [Microsoft/vscode-go#1683]
I toggled the code coverage view for a package I was working on, and I quickly saw that some of my heavily-tested code was marked as untested.

I used `go tool cover -html=/name/of/the/cover/profile` to show the "official" html version of the same coverage file used by the vscode-go plugin and it showed the correct result.

Looking at the code [here](https://github.com/Microsoft/vscode-go/blob/cded61c853da3e4a9cfa06dbfca818da6d79ee80/src/goCover.ts#L193) the test for whether code was covered is checking to see if fileRange[7] is exactly 1.

The comment in the code says:

    // go test coverageprofile generates output:
    //    filename:StartLine.StartColumn,EndLine.EndColumn Hits IsCovered

But in the comments in the Go profiler source, it says:

    the fields are: name.go:line.column,line.column numberOfStatements count

In other words, the "count" value (the 8th value at index 7) is not a boolean, it is the number of times that code has been executed.

Consequently, code that has been executed many times is instead being marked as not covered.

I believe that the code should be changed from:

				// If is Covered
				if (parseInt(fileRange[7]) === 1) {
					coverage.coveredRange.push({ range });
				}
				// Not Covered
				else {
					coverage.uncoveredRange.push({ range });
				}

to:

				// If is Covered
				if (parseInt(fileRange[7]) > 0) {
					coverage.coveredRange.push({ range });
				}
				// Not Covered
				else {
					coverage.uncoveredRange.push({ range });
				}

I don't have time at the moment to figure out how to build and test a modification to turn this into a PR but hopefully this is enough that someone internal can easily take it on.

**Comment by kentquirk** [comment]
FWIW, I was able to modify `~/.vscode/extensions/ms-vscode.go-0.6.80/out/src/goCover.js` to make the corresponding change, and it works correctly now on my machine.

**Comment by ramya-rao-a** [comment]
What version of Go are you using?
I wonder if this is a change in the way the coverage file is created in the latest version of Go.

I am using Go 1.9.2 on my Mac. I have tests for code that gets run multiple times too. But the the last number is always 1.

**Comment by kentquirk** [comment]
On my mac, I'm using `go version go1.10.1 darwin/amd64`. I thought I had linked to the golang source, but apparently I failed to paste that link. Here it is:

https://github.com/golang/go/blob/master/src/cmd/cover/profile.go

It doesn't appear to have changed lately. Note these lines:

https://github.com/golang/go/blob/master/src/cmd/cover/profile.go#L29
https://github.com/golang/go/blob/master/src/cmd/cover/profile.go#L56

Also, please note that my proposed change is equivalent to the current behavior if the value is only a boolean (either 1 or 0), but it continues to work if the value (as documented in the source) is actually a count.

**Comment by ramya-rao-a** [comment]
Thanks for the links! I'll make the necessary changes which should be out in the next update which should be in the next few days.

**Comment by ramya-rao-a** [comment]
> I don't have time at the moment to figure out how to build and test a modification to turn this into a PR but hopefully this is enough that someone internal can easily take it on.

Unfortunately the test coverage feature doesnt have much test coverage itself :(
So, you can just send a PR online on Github for the one line change if you are up for it.

I would prefer if you get the credit for this fix as you found the issue, root cause and the fix it self :)

**Comment by kentquirk** [comment]
Thank you! I'll try to do that in the next couple of days.

Thank you so much for your work on this tool. It is really appreciated.

**Comment by ramya-rao-a** [comment]
This bug fix is now out in the latest update to the Go extension (0.6.81)
