### ISSUE TITLE
Problems with gopkg.in/ukautz/clif.v1 package naming

### ISSUE THREAD

**Issue by xander27** [Microsoft/vscode-go#1684]
Steps to Reproduce:

1. Install package 'go get gopkg.in/ukautz/clif.v1'
2. Create sample program with import like in examples https://github.com/ukautz/clif/blob/v1/examples/simple.go

```
package main

import "gopkg.in/ukautz/clif.v1"

func main() {
	c := clif.New("My App", "1.0.0", "An example application").
		New("hello", "The obligatory hello world", func(out clif.Output) {
		out.Printf("Hello World\n")
	})
	c.Run()
}

```

try to save it. It will remove import line and say that clif is undefined. But if you disable go plugin, save file and run it from terminal it will be compiled ok.

**Comment by ramya-rao-a** [comment]
I followed the steps above and was able to save the file without any issues.
Are you sure that the imported package and your sample code are under the same GOPATH?

Add the setting `"go.formatTool": "gofmt"` and try again. The `gofmt` tool will not remove unused imports. When doing so, do you get any build errors?
