### ISSUE TITLE
Add support for Govendor

### ISSUE THREAD

**Issue by chuacw** [Microsoft/vscode-go#1685]
Add support for Govendor

**Comment by chuacw** [comment]
When working on a project, if you use a package (A) that uses version 1 of an external dependency (B), but the latest for B is version 3, and B declares a function that requires v1 of a struct in B, then project won't compile, until you use Govendor to flatten the external dependency into a namespace that A can use.

Please see https://stackoverflow.com/questions/35999046/vendoring-in-go-1-6 and https://github.com/kardianos/govendor .

**Comment by ramya-rao-a** [comment]
Thanks for the details @chuacw 

I'll have to say this is out of scope for this Go extension which does only the very basic in the area of package management. It lets you

- Import package when auto-completing a symbol from unimported package
- Remove unused packages, add missing packages, order packages all of which comes via the use of either `goreturns` or `goimports` as the formatting tool.
- Browse packages
- Import a package

We dont intend to go beyond this and handle package/version management in general as we neither have the expertise for it nor do we feel this is the right place for it.

You are more than welcome to create a separate extension that can help with package/version management. I can point you to the resources to getting started and help if you find any issues along the way.

**Comment by chuacw** [comment]
Thanks, Ramya. Please point me to the resources, I can investigate if I can do this.

**Comment by ramya-rao-a** [comment]
Great! [Extending VS Code](https://code.visualstudio.com/docs/extensions/overview) is a good place to start.
