### ISSUE TITLE
gopath import problem with release 0.6.80

### ISSUE THREAD

**Issue by m3talsmith** [Microsoft/vscode-go#1688]
I'm running into an issue where imports that worked before are completely marked as bad paths now. This refers to any package attached to my GOPATH. I did find a workaround and dug into what I think is the relevant commit below in the Workaround  section.

Additionally, vscode started flickering badly until I did my workaround. It may be because it keeps repainting on state change, caused by my GOROOT not explicitly set yet being attempted to be found via `go env` (which might be failing itself because of the GOPATH issue). After my workaround it stopped flickering.

Let me know if there is any other info you need from me.

## System setup

1. Fedora 28
1. vscode 1.23.1
1. vscode-go 0.6.80
1. Go code using [go-dep](https://github.com/golang/dep) to manage vendoring
1. $GOPATH = $HOME
1. $GOROOT = /usr/local/go

## Steps to Reproduce:

1. Upgrade extension to 0.6.80
1. Set preference `go.gopath` to your $GOPATH
1. Make sure `go.inferGopath` is default (`false`) or is not in preferences
1. Open code that had valid paths previously
1. Add a comment and save the file
1. See red underline under project localized all packages in imports
1. Look at output for `go` in Panel (ctrl + j) and see import path errors

## Workaround

The only work around for me was to explicitly set my `go.gopath` and set `go.inferGopath` to true. I've never had those set before and everything worked fine. I noticed a change by [Ramnya Rao](https://github.com/Microsoft/vscode-go/releases/tag/0.6.80) that might account for this; specifically these two lines in the [check GOROOT commit](https://github.com/Microsoft/vscode-go/commit/5a76fc502272f41f0e8e6016510f007aa0f92d10) may be the culprits:

1. https://github.com/Microsoft/vscode-go/commit/5a76fc502272f41f0e8e6016510f007aa0f92d10#diff-3f57b095642b0ee445d6cdbc4f60d751R289
1. https://github.com/Microsoft/vscode-go/commit/5a76fc502272f41f0e8e6016510f007aa0f92d10#diff-3f57b095642b0ee445d6cdbc4f60d751R299

## Final thoughts

I left a comment on one line of code regarding the check for valid values on gopath and goroot, but I feel shaky about the checks as whole. There are assumptions made that I'm not 100% sure exists, but I'm not sure they are a problem either. Is there any testing done around the logic? It really feels like something subtle is happening in connection to the `go.inferGopath` which is not handling an error correctly (maybe even through the child_process call?). Best of luck on the dive!

**Comment by ramya-rao-a** [comment]
@m3talsmith 

To confirm that the latest update is indeed causing the issue, can you install the previous version and check that everything is fine? Below are the steps to get the previous version
- Uninstall the Go extension 
- Add the setting `"extensions.autoUpdate": false`
- Download the `Go-0.6.79.vsix` file from https://github.com/Microsoft/vscode-go/releases/tag/0.6.79
- Close all instances of VS Code
- Run `code --install-extension Go-0.6.79.vsix`

If the previous version indeed works fine, then while still being in the previous version run the command `Go: Current GOPATH`. Then update the extension to the latest version and run the same command. Compare the 2 results. Is there any difference?

In your system setup, it looks like you have set the GOROOT env variable. Can you run `echo $GOROOT` in the integrated terminal in VS Code, and check that its the expected value?
