### ISSUE TITLE
Debugging: could not launch process: stub exited while waiting for connection: exit status 0

### ISSUE THREAD

**Issue by bojand** [Microsoft/vscode-go#1689]
As far as I can tell I am following instructions as [documented in the wiki](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension). delve installed using the go get method described in [installation instructions](https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md).

The only part that I did not do as I am not sure what it means is:

> On OS X it requires creating a self-signed cert to sign the dlv binary.

OS: MacOS High Sierra 10.13.4

```sh
$ echo $GOPATH
/Users/bojand/dev/go
$ go version
go version go1.10.1 darwin/amd64
$ which dlv
/Users/bojand/dev/go/bin/dlv
$ dlv version
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533
$ code --version
1.23.1
d0182c3417d225529c6d5ad24b7572815d0de9ac
x64
```

Sample program:

```go
package main

import (
  "fmt"
)

func greet(greeting string) {
  fmt.Println(greeting)
}

func createGreeting(greeting, name string) string {
  ret := fmt.Sprintf("%s %s!", greeting, name)
  return ret
}

func main() {
  greeting := createGreeting("Hello", "Bob")
  greet(greeting)
}
```

It seems to work fine for me using command line:

```
~/dev/go/src/github.com/bojand/godbg dlv debug github.com/bojand/godbg --listen=127.0.0.1:2782 --log=true
2018/05/22 16:57:28 server.go:73: Using API v1
2018/05/22 16:57:28 debugger.go:101: launching process with args: [/Users/bojand/dev/go/src/github.com/bojand/godbg/debug]
Type 'help' for list of commands.
(dlv) c
2018/05/22 16:57:29 debugger.go:513: continuing
Hello Bob!
Process 57044 has exited with status 0
(dlv) exit
Process 57044 has exited with status 0
~/dev/go/src/github.com/bojand/godbg
```

But fails in vscode...

```
Verbose logs are written to:
/var/folders/_2/6lm0xv15389_67pyc3hm4n180000gp/T/vscode-go-debug.txt
16:56:15, 2018-5-22
InitializeRequest
InitializeResponse
Using GOPATH: /Users/bojand/dev/go
Running: /Users/bojand/dev/go/bin/dlv debug github.com/bojand/godbg --headless=true --listen=127.0.0.1:7085 --log=true
2018/05/22 16:56:16 server.go:73: Using API v1
2018/05/22 16:56:16 debugger.go:101: launching process with args: [/Users/bojand/dev/go/src/github.com/bojand/godbg/debug]
could not launch process: stub exited while waiting for connection: exit status 0
Process exiting with code: 1
Delve is closed
DisconnectRequest
```

the specific configuration in `launch.json` :

```
{
  "name": "Launch file",
  "type": "go",
  "request": "launch",
  "mode": "debug",
  "program": "${file}",
  "showLog": true,
  "trace":"verbose"
}
```
The default config also fails with same issue
```
{
  "name": "Launch",
  "type": "go",
  "request": "launch",
  "mode": "debug",
  "remotePath": "",
  "port": 2345,
  "host": "127.0.0.1",
  "program": "${fileDirname}",
  "env": {},
  "args": [],
  "showLog": true,
  "trace": "verbose"
}
```

**Comment by ramya-rao-a** [comment]
Can you run `which dlv` in the terminal and make sure the resulting path is the same as what VS Code is using i.e `/Users/bojand/dev/go/bin/dlv`?

**Comment by ramya-rao-a** [comment]
Also https://github.com/derekparker/delve/issues/1215 is talking the exact same issue. Can you get the latest delve and try again?

**Comment by bojand** [comment]
The upgrade fixed it. I looked into delve issues a few days ago when I originally encountered the issue, but i do not think it was created at that time. Thanks for your assistance.

**Comment by ramya-rao-a** [comment]
Glad that it all worked out. And thanks for pointing out about the `On OS X it requires creating a self-signed cert to sign the dlv binary.`

That was related to the old way of getting delve on Mac which was by using the Homebrew formula. The maintainers of delve have now removed that has one of the options and I was not aware of that move.

I have updated our wiki to reflect the same.

Happy Coding!
