### ISSUE TITLE
goto definition, find references etc, not working on Mac

### ISSUE THREAD

**Issue by nutmix** [Microsoft/vscode-go#1690]
When I was using vscode on windows, with the go plugin, I could right click on a function call and it would allow me to go to the definition, and if I was on a definition, it would allow me to find the references.

I just switched to Mac (company requirement, not choice), and cant seem to get the same features. Should they work on a mac?

Basically, I downloaded visual studio code last week (1.23.1)  on Mac OS 10.13.4, then installed the go plugin (0.6.80).I have rebooted the laptop several times since.

I have go 1.10.2 installed.
GOPATH is set to /home/me/go as usual.
project which doesnt work is in /home/me/go/src/github.com/me/myproject/...

When I select a function all and right click, I only see:

1. change all occurences
1. cut
1. copy
1. paste 
1. command palette

I cant see anything under the menus either.

Any suggestions?

**Comment by dearplain** [comment]
Press F1, type `install tools`, you can see `Go: install/update tools`, that's it.

**Comment by nutmix** [comment]
That worked, thanks.  I had installed go from the marketplace.
