### ISSUE TITLE
Request: Support linting with golangci-lint

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode-go#1694]
[golangci-lint](https://github.com/golangci/golangci-lint) is a new linter that refactors a bunch of gometalinter's supported linters into a single tool and codebase:

> GolangCI-Lint is a linters aggregator. It's fast: on average 5 times faster than gometalinter. It's easy to integrate and use, has nice output and has minimum number of false positives.

Considering that many of gometalinter's linters are unusable within VSCode because they're too slow, and thus have to be run separately as part of CI, I think this would be an important feature.

**Comment by kentquirk** [comment]
Linking to PR #1693

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.81)
Change the `go.lintTool` to start using `golangci-lint`
