### ISSUE TITLE
Test Plan for May 2018 update (0.6.81)

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1698]
If you got a notification from this issue, then you are part of the next update to the Go extension.
Thanks and Welcome!

As most of you know already, I am the sole maintainer of this project at the moment. I wanted to try something different for this next update. 

Here I will be listing the features and the bug fixes that will go in the next update along with the the folks who logged the bugs/feature requests, those who upvoted it, and those who fixed it by sending PRs.

The idea is to get the folks behind this update to give the update a trial run before I release it.
I always do basic testing before every update. But because I dont work with Go in my day job, I always feel that someone who does Go more than me can help in testing tremendously.

And when I say "test", you can do a minimum pass of just installing the update and then do nothing special other than going about using VS Code like you do everyday. Or you can test the feature you requested/implemented or the bug you logged/fixed. Or you can test all of the below. Every bit helps.

Drop in a comment in this issue after 2 or 3 days of installing the update with your findings.
Also, let me know in the comments what you think of this model of me asking your help in testing an update before releasing it.

Feature Requests:

- #1005 Include stub with exported member name on the comment above it in completions. Use Ctrl+Space to trigger completions inside comments. cc @shreyu86, @atombender, @shurcooL, @ruedap
- #1593 Use code-completion feature from language server. Ensure to use both `go.useLanguageServer` and `go.languageServerExperimentalFeatures` to test this. cc @m90, @leaxoy, @OneOfOne, @primalmotion, @Contextualist
- #1555 Use version 2 apis of delve that enables watching strings and arrays whose size is > 64. First set `useApiV1` to `false` in the debug config to test this. Then configure `dlvLoadConfig` in the same place to control the array size to display. cc @lggomez, @Sirikon, @michaelmello, @jgfet, @Arman92, @carusyte
- #1693 Support to use `golangci-lint` as a linter. cc @golangci, @atombender, @caarlos0, @lafin, @nikitabokovoy
- #1697 Support to use `revive` as a linter. cc @Southclaws, @mgechev, @wolfeidau
- #1302 Make the test coverage colors/styles more colorblind friendly. cc @kentquirk, @dcormier, @sigwinch28, @Mistobaan

Bugs:

- #1667 Issue with formatting when using the language server. cc @OneOfOne 
- #1490 Perf issue with using `gopkgs`. cc @codingconcepts, @uudashr
- #1683 Fix code coverage when code is covered by multiple tests. cc @kentquirk

**Comment by ramya-rao-a** [comment]
To install the update, 
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by primalmotion** [comment]
Hi,

I tried to use `golangci-lint` seems to work, but when I save, the cursor goes straight to the end of the file.

**Comment by caarlos0** [comment]
Hi,

tried golangci-lint, seems to work ok for me. Didn't had this problems related to going to end of the file as @primalmotion reported (or at least I didn't notice them)

**Comment by primalmotion** [comment]
Actually it is not golangci-lint, but it is when I enable the formatting by language-server

**Comment by ramya-rao-a** [comment]
@primalmotion The formatter from the language server is not yet stable. Did you enable it explicitly using the `go.languageServerExperimentalFeatures` setting?

**Comment by primalmotion** [comment]
yeah I did. let me disable it. Is `autoComplete` from `go.languageServerExperimentalFeatures` more or less stable?

**Comment by ramya-rao-a** [comment]
autoComplete is stable. It doesn't have features like automatic importing of unimported packages when completing symbols from the unimported packages though. That's why I didn't make it a default and kept it as an opt-in for the moment

**Comment by primalmotion** [comment]
Oh I see. No autoimport is game over for me :) I’ll wait before activating it.

Other than that (and the debugger that never really worked for me), everything seems to work well

**Comment by OneOfOne** [comment]
It seems to work fine for me but I don't think we should set it as the default just yet, maybe in 1-2 more releases or at least until after automatic imports works.

**Comment by leaxoy** [comment]
AutoComplete feature come from `go-langserver` works for me, this looks great, thanks for your work.

**Comment by wolfeidau** [comment]
@ramya-rao-a Tested out revive and made a PR just for some README updates #1703

Integration worked great once it was correctly configured.

**Comment by ramya-rao-a** [comment]
Thanks @wolfeidau! Do try out the -config flag with file paths having ~ for homer or the ${workspaceRoot} variable

**Comment by Southclaws** [comment]
Revive is working great! Tested on osx and windows. `~` and `${workspaceRoot}` work fine on both platforms.

**Comment by m90** [comment]
I've used the "pre-release" version for the last 1 1/2 days and it seems to work mostly fine.

The only feature that is giving me issues is the `go-langserver` based formatting, which sometimes creates the "jump-to-bottom" behavior described by @primalmotion as well as gives me a slightly annoying flashing on save (syntax highlighting is removed, all code is displayed in white, syntax highlighting is reapplied):

![ezgif-4-7ec6822722](https://user-images.githubusercontent.com/1662740/40835256-2b26e450-6593-11e8-873f-346af3a81a16.gif)

From having a quick glance at the code it looks to me as if these are upstream issues though, either in the language server or the language server interface of VSCode, so I doubt this is to be fixed here.

I'll probably not turn on the language server formatting, but other than that, the update is more than welcome. Thanks to everyone involved.

---

> Also, let me know in the comments what you think of this model of me asking your help in testing an update before releasing it.

I think this is a really great format for cutting releases. The thread above also looks like it's working, so :+1:

**Comment by Southclaws** [comment]
^I've noticed the syntax flashing on a few other file types too, it definitely seems like a general issue rather than Go-specific.

**Comment by kentquirk** [comment]
The change to go-cover works fine for me. I'm bummed that the PR for code coverage appearance prefs didn't make it in, but so it goes.

I think it's a fine idea to ask for help testing.

**Comment by shreyu86** [comment]
I have been using the extension for the past day without any issues and have tested the following:

- `golangci-lint`
- completion in comments for exported variables

**Comment by ramya-rao-a** [comment]
Great, thanks everyone!
I'll release the update first thing on Monday morning.

**Comment by ramya-rao-a** [comment]
Thanks to each and everyone here, the update has been released!
