### ISSUE TITLE
add interfacer support

### ISSUE THREAD

**Issue by sijad** [Microsoft/vscode-go#170]
[interfacer](https://github.com/mvdan/interfacer) A linter that suggests interface types

**Comment by LiterallyElvis** [comment]
I'd like to add my support to this suggestion

**Comment by mafredri** [comment]
gometalinter supports interfacer, so I'd say efforts are better placed into integrating with it, there's an issue open for it #17.

**Comment by gyf19** [comment]
+1

**Comment by lukehoban** [comment]
I agree with @mafredi that it probably makes sense to focus on adding `gometalinter` support as a path to getting `interfacer` linting.  So closing this issue out for now.
