### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [Microsoft/vscode-go#1705]
Hi @microsoft ,

My name is Ulises or TJ if you like,
i'm a graphic designer and I contribute to cool projects (open source) like this one!
if this is something that you're looking forward to, I'll gladly upload some logo proposals

I'll look forward for your reply, cheers!

TJ.

**Comment by ramya-rao-a** [comment]
Thanks for your offer @tjulises. We are not looking to change the logo of this project/plugin at the moment.
