### ISSUE TITLE
go.goroot setting ignored

### ISSUE THREAD

**Issue by variab1e** [Microsoft/vscode-go#171]
@lukehoban Referencing #166 

Yes, this is with the newest 0.6.22 and 0.10.6 vscode. The same exact settings,
go.goroot setting igorned despite being set, I am still receiving `No 'go' binary could be found on PATH or in GOROOT.` I actually get the full set of:
```
Some Go analysis tools are missing from your GOPATH. Would you like to install them?
The 'godef' command is not available. Use 'go get -u github.com/rogpeppe/godef' to install.
The 'golint' command is not available. Use 'go get -u github.com/golang/lint/golint' to install.
No 'go' binary could be found on PATH or in GOROOT.
```
But of course clicking yes install errors because the binary isn't known.  
I tried going another level further and appending `bin/` to the goroot but that didn't do it either.  
**only difference being vscode's requirement that the windows \ be / and I do have the ~ fully expanded when being set **
go.exe is at `~/dev/lib/go/bin`
go.goroot is set to `~/dev/lib/go`
go.gopath is set to`~/dev/`

**Comment by lukehoban** [comment]
Thanks @variab1e.

Could you provide any additional details on your environment.  OS? How are you launching Code?  What does your `go env` look like?

> *only difference being vscode's requirement that the windows \ be / and I do have the ~ fully expanded when being set *

What did you mean by this part?

**Comment by variab1e** [comment]
Oh I was just shortening, I'll just write it out:

go.exe is at `C:/Users/ehiller/dev/lib/go/bin`  
go.goroot is set to `C:/Users/ehiller/dev/lib/go`  
go.gopath is set to `C:/Users/ehiller/dev/`  

I was just saying that in vscode I actually did fully specific the paths, and not use ~. 

I launch vscode from the gui/just double click.

**Comment by variab1e** [comment]
Gopath definitely works, just seems that goroot doesn't. I can install the tools manually, and then they work (gopath setting is fine, but the go.exe is not found due to the goroot not being found). Automatic installation doesn't work because obviously go get won't work. Hope that clarifies some.

**Comment by variab1e** [comment]
Somehow I am still have the same result - I even ensured that the extension was fully being reinstalled by deleting it and reinstalling from scratch. Still ->

I checked the binaries, made sure they were unblocked and permissions were good. I posted all my settings and directories for a sanity check. I am doing something horribly off?

`No 'go' binary could be found on PATH or in GOROOT.`

```user -> settings.json
	// Specifies the GOPATH to use when no environment variable is set.
	"go.gopath": "C:/Users/ehiller/dev/",

	// Specifies the GOROOT to use when no environment variable is set.
	"go.goroot": "C:/Users/ehiller/dev/lib/go/"

	// Specifies the GOROOT to use when no environment variable is set.
	"go.goroot": "C:/Users/ehiller/dev/lib/go/",
```

```
C:\Users\ehiller\dev\lib\go
λ pwd

Path
----
C:\Users\ehiller\dev\lib\go


C:\Users\ehiller\dev\lib\go
λ ls
total 178
-rw-r--r-- 1 ehiller ehiller 21146 Jan 13 19:09 AUTHORS
-rw-r--r-- 1 ehiller ehiller  1107 Jan 13 19:09 CONTRIBUTING.md
-rw-r--r-- 1 ehiller ehiller 28953 Jan 13 19:09 CONTRIBUTORS
-rw-r--r-- 1 ehiller ehiller  1479 Jan 13 19:09 LICENSE
-rw-r--r-- 1 ehiller ehiller  1303 Jan 13 19:09 PATENTS
-rw-r--r-- 1 ehiller ehiller  1519 Jan 13 19:09 README.md
-rw-r--r-- 1 ehiller ehiller     7 Jan 13 19:09 VERSION
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:09 api
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:09 bin
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:09 blog
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:09 doc
-rw-r--r-- 1 ehiller ehiller  1150 Jan 13 19:09 favicon.ico
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:09 lib
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:09 misc
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:09 pkg
-rw-r--r-- 1 ehiller ehiller    26 Jan 13 19:09 robots.txt
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:09 src
drwxr-xr-x 1 ehiller ehiller     0 Jan 13 19:10 test
C:\Users\ehiller\dev\lib\go
λ ls bin
total 31728
-rwxr-xr-x 1 ehiller ehiller 11258368 Jan 29 14:01 go.exe
-rwxr-xr-x 1 ehiller ehiller 17121280 Jan 29 14:01 godoc.exe
-rwxr-xr-x 1 ehiller ehiller  4105216 Jan 29 14:01 gofmt.exe
```

**Comment by lukehoban** [comment]
Sorry - the fix for this is in master, but I haven't pushed out an update of the extension yet to catch up with what's in master.  Coming soon...

**Comment by lukehoban** [comment]
`0.6.25` is published now which should have the fix for this.  Could you try that?

**Comment by variab1e** [comment]
Sure thing! No more error message.

Nice thanks! That was my bad, I misread, I thought the tag was on .24 -- sorry about that. I was in the midst of debugging it myself. Saved me some time. Thanks heaps.

Is there anything specific I can/should test to ensure the functionality is present as well?

**Comment by lukehoban** [comment]
> Is there anything specific I can/should test to ensure the functionality is present as well?

If you introduce an error in your code and save the file, that should trigger a `go build` which will only work if your `goroot` is set correctly.   

Generally, you'll likely see a lot of failures in the tool if you have an illegal/incorrect `go.goroot`.

**Comment by variab1e** [comment]
Put an error in the code, a few actually - and it did not generate any output. Without errors it didn't generate an exe either. I tried it with both auto save on and off, but neither generated an error. If I manually ran `go build .` it behaved as expected. To ensure I looking in the proper place, I go to `Toggle Output` > `Go` correct?
