### ISSUE TITLE
ENV_VARs during Debugging

### ISSUE THREAD

**Issue by mikeholmesuk** [Microsoft/vscode-go#1712]
I'm having trouble using environment variables when running the debugger. I've read the thread at https://github.com/Microsoft/vscode-go/issues/1134 and https://github.com/Microsoft/vscode-go/issues/1114 indeed that helped me with getting these working last time I tried this. I've set `go.testEnvVars` under my workspace.settings but they always appear to be empty when reading them in while debugging. I've tried setting `go.gopath` under `User Settings` and I've tried adding `GOPATH` as an entry under `env` in `launch.json`. None of these make a difference to the output. 

I did run an update for the plugin recently. This has worked for me previously so I'm not sure if this issue has been introduced in a recent update? Or whether I'm missing something else (which I concur is entirely possible)?  

Minimal steps to recreate:
1. I have the following file in `main.go` in the project root:
```
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println(fmt.Sprintf("ENV VAR[FOO]: %s", os.Getenv("FOO")))
	fmt.Println(fmt.Sprintf("ENV VAR[GOPATH]: %s", os.Getenv("GOPATH")))
}
```
2. I have the following in `Workspace Settings`:
```
{
    "go.testEnvVars": {
        "FOO": "Bar"
    }
}
```
3. The output from the above:
```
ENV VAR[FOO]: 
ENV VAR[GOPATH]: /Users/mike/Development/GO:/Users/mike/Development/xxxxxxxx
```
(I'm running this from under the second of those `GOPATH` entries)
4. The `launch.json` file looks like this:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${file}",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}
```

Env vars are correctly loaded if I added them under the `env` stanza in `launch.json`, but my understanding was that I didn't have to?

**Comment by ramya-rao-a** [comment]
The `go.testEnvVars` is used by when running/debugging tests.
The code you shared is not a test.
If you want the debug process to have access to a environment variable, then it should either be already available as an environment variable or can be set via the `env` property in the debug configuration or you can provide a file path using the `envFile` property in the debug configuration

**Comment by mikeholmesuk** [comment]
Hi @ramya-rao-a - thanks for getting back. You're quite right in that I'm running the program with the debugger rather than tests so what you say makes sense. What I was looking for was a way to define env vars in workspace settings and have them available for the debugger wherever that was running so for tests, or just running the program using a debugger or whatever.  Irrespective, if I can load values via the `env` stanza then that will work. Closing this issue.
