### ISSUE TITLE
Code coverage does not update properly using "gutter"

### ISSUE THREAD

**Issue by FryDay** [Microsoft/vscode-go#1716]
Using these settings:
```
    "go.coverOnSave": true,
    "go.coverageDecorator": {
        "type": "gutter",
        "coveredHighlightColor": "rgba(64,128,128,0.5)",
        "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
        "coveredGutterStyle": "blockgreen",
        "uncoveredGutterStyle": "slashred"
    },
```

Code coverage does not properly update on save. I have to restart vscode to update the coverage. Changing the type to highlight restores functionality.

**Comment by ramya-rao-a** [comment]
Thank for reporting! This bug got introduced in the last release.
Fixed with https://github.com/Microsoft/vscode-go/commit/abe97240e573e9d2c11cea00bfd8c1e77c41398e

I just released an update (0.6.82) that has the fix
