### ISSUE TITLE
New code coverage highlighting is additive 

### ISSUE THREAD

**Issue by FryDay** [Microsoft/vscode-go#1717]
Using these settings:
```
    "go.coverOnSave": true,
    "go.coverageDecorator": {
        "type": "highlight",
        "coveredHighlightColor": "rgba(64,128,128,0.25)",
        "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
        "coveredGutterStyle": "blockgreen",
        "uncoveredGutterStyle": "slashred"
    },
```

Every time I save, the highlight gets added until eventually it's so bright that you cannot properly see the code underneath.

Edit: This also causes issues if a block of code is uncovered and then becomes covered. The covered color gets put on top of the uncovered color causing odd issues.

**Comment by ramya-rao-a** [comment]
Thank for reporting! This bug got introduced in the last release.
Fixed with https://github.com/Microsoft/vscode-go/commit/abe97240e573e9d2c11cea00bfd8c1e77c41398e

I just released an update (0.6.82) that has the fix
