### ISSUE TITLE
Local runtime/stdlib files not links in error output

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode-go#1719]
![screen shot 2018-06-06 at 3 14 40 pm](https://user-images.githubusercontent.com/63830/41068018-93acc23a-699c-11e8-9d01-53ba6900a238.png)

Redacted example output:

```
Running tool: /usr/local/bin/go test -timeout 30s github.com/foo/bar -run ^TestBar$

--- FAIL: TestBar (0.00s)
panic: reflect: call of reflect.Value.FieldByName on ptr Value [recovered]
	panic: reflect: call of reflect.Value.FieldByName on ptr Value

goroutine 7 [running]:
testing.tRunner.func1(0xc4201a80f0)
	/usr/local/Cellar/go/1.10.2/libexec/src/testing/testing.go:742 +0x29d
panic(0x15062a0, 0xc420181380)
	/usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
reflect.flag.mustBe(0x16, 0x19)
	/usr/local/Cellar/go/1.10.2/libexec/src/reflect/value.go:207 +0xb5
reflect.Value.FieldByName(0x14bb840, 0xc4201aa640, 0x16, 0x15ca8ad, 0x7, 0xc42002e1b0, 0x90, 0x4)
	/usr/local/Cellar/go/1.10.2/libexec/src/reflect/value.go:835 +0x4c
github.com/foo/bar.(*baz).Get(0xc4201aa600, 0x14bb840, 0xc4201aa640, 0x0, 0x0)
	/Users/will/Developer/go/src/github.com/foo/bar/baz.go:54 +0x4d8
github.com/foo/bar.TestBar(0xc4201a80f0)
	/Users/will/Developer/go/src/github.com/foo/bar/baz_test.go:56 +0xb24
testing.tRunner(0xc4201a80f0, 0x15eec68)
	/usr/local/Cellar/go/1.10.2/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10.2/libexec/src/testing/testing.go:824 +0x2e0
FAIL	github.com/foo/bar	0.025s
Error: Tests failed.
```

where these aren't clickable links, but should be:

- /usr/local/Cellar/go/1.10.2/libexec/src/testing/testing.go:742
- /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502
- /usr/local/Cellar/go/1.10.2/libexec/src/reflect/value.go:207
- /usr/local/Cellar/go/1.10.2/libexec/src/reflect/value.go:835
- /usr/local/Cellar/go/1.10.2/libexec/src/testing/testing.go:777
- /usr/local/Cellar/go/1.10.2/libexec/src/testing/testing.go:824

**Comment by ramya-rao-a** [comment]
@isidorn Any idea why some of the links get detected and others dont in the Output channel?

**Comment by isidorn** [comment]
@ramya-rao-a our link detection approach is not very good and uses various heuristics
PR to improve this are welcome
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputLinkComputer.ts#L24

**Comment by ramya-rao-a** [comment]
Closing this issue as there is no next steps for the extension at the moment.
