### ISSUE TITLE
Conditional Debugging

### ISSUE THREAD

**Issue by freman** [Microsoft/vscode-go#1720]
Hello, I have a feature request.

It would appear that the API for dlv supports conditional debugging, and it turns out you never know how much you need a feature until you don't have it.

Could we please get conditional debugging support?

https://godoc.org/github.com/derekparker/delve/service/api#Breakpoint

**Comment by lggomez** [comment]
As you said @freman, this one was easy to implement, it was an oversight due to limitations of the legacy debug adapter API, the new one supports this scenario

You may try the feature on a build from the attached PR

**Comment by ramya-rao-a** [comment]
@freman and others (@l33t0, @houmam, @skycube, @zenyuk, @mattevans, and @shousper) who have upvoted this feature:

 Please give this feature a try by following the below steps and share any feedback you have.

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by freman** [comment]
Thanks @ramya-rao-a, I'll try to find something I need to interactively debug and test it out 😀

**Comment by l33t0** [comment]
Thanks @ramya-rao-a works a treat!

**Comment by ramya-rao-a** [comment]
@freman 

> You have brought us so much joy! Thank you!

All credits go to @lggomez :)

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update to the Go extension (0.6.83)
