### ISSUE TITLE
Go Tools are not updating properly

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-go#1726]
On my Windows machine running VSCode 1.24.0, running "Go Install/Update Tools" fails. It updates some tools, but doesn't update others. It seems like the git-related operations fail and leave the go tools' directory dirty:

```
Installing github.com/mdempsky/gocode SUCCEEDED
Installing github.com/uudashr/gopkgs/cmd/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
Installing github.com/josharian/impl SUCCEEDED
Installing github.com/davidrjenni/reftools/cmd/fillstruct SUCCEEDED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing golang.org/x/tools/cmd/godoc SUCCEEDED
Installing golang.org/x/tools/cmd/goimports SUCCEEDED
Installing github.com/golang/lint/golint FAILED
Installing github.com/cweill/gotests/... SUCCEEDED
Installing github.com/derekparker/delve/cmd/dlv SUCCEEDED

# cd D:\Workspace\golang\src\github.com\golang\lint; git pull --ff-only
From https://github.com/golang/lint
   e14d9b0..470b6b0  master     -> origin/master
Updating e14d9b0..470b6b0
error: Your local changes to the following files would be overwritten by merge:
	CONTRIBUTING.md
	README.md
	golint/golint.go
	golint/import.go
	lint.go
	misc/emacs/golint.el
	testdata/else-multi.go
	testdata/error-return.go
	testdata/iferr.go
	testdata/range.go
Please commit your changes or stash them before you merge.
Aborting
package github.com/golang/lint/golint: exit status 1
```

I haven't modified any files in any of these tools' folders. My guess would be that maybe  Windows Defender might be interfering with file copy operations.

**Comment by ramya-rao-a** [comment]
Must have been an unfortunate series of events that lead to that state.
There is not much we can do in this case. The expectation is that the user cleans up the said repos and try updating again if needed.

Do you have any other suggestions?

**Comment by kumarharsh** [comment]
No, I guess I will have to keep cleaning it manually. The slightly painful part is that the extension tries to update *all* go tools again - so it kind-of becomes a loop where I just keep fixing one repo, just for something else to break again next time.

**Comment by ramya-rao-a** [comment]
You can log a feature request to make the `Go: Install/Update Tools` show a quick pick (drop down) which has all the tools + an "all" option.
