### ISSUE TITLE
Adding wrong imports on save for a linked directory

### ISSUE THREAD

**Issue by inancgumus** [Microsoft/vscode-go#1727]
**Steps to Reproduce:**

1. ln -s ~/Desktop/folder $GOPATH/src/github.com/inancgumus/folder
2. folder contains `main.go` and `foo/file.go`
3. When I save `main.go` without using an `import` it adds import directory relative to the `main.go` on my `~/Desktop` instead of `$GOPATH/src/github.com/inancgumus/folder`.

**folder/main.go**

```go
    package main

    // wrong
    import "foo"

    // should be:
    // import "github.com/inancgumus/folder"

    func main() {
      foo.X()
    }
```

**folder/foo/file.go**

```go
    package foo
    func X(){}
```

```bash
>  go env
GOPATH="/Users/inanc/dev/go"
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
```

**vscode user settings**
```json
    "go.inferGopath": false,
    "go.gopath": "/Users/inanc/dev/go",
    "go.toolsGopath": "/Users/inanc/dev/go",
    "go.goroot": "/usr/local/opt/go/libexec",
    "go.formatTool": "goimports",
```

_I also have tried without these (vscode) customizations, the behavior is the same._

---

**When I type the following from bash console:**

```bash
goimports -w main.go
```

It adds the correct import (_github.com/..._).

**Comment by ramya-rao-a** [comment]
@inancgumus I tried the exact same setup as you described above, but I get the right import

The below shows how my `~/Desktop/folder` and `$GOPATH/src/github.com/ramya-rao-a/folder` are linked. 

<img width="608" alt="screen shot 2018-07-16 at 5 01 02 pm" src="https://user-images.githubusercontent.com/16890566/42789354-c02e34aa-8919-11e8-98ff-b4892671f70c.png">

And below I save the file which triggers formatting and the right import is added.

![import](https://user-images.githubusercontent.com/16890566/42789448-38ad3750-891a-11e8-9830-7f00eea3b93e.gif)

Are you doing anything differently than what I did?
