### ISSUE TITLE
Weird code highlighting from time to time

### ISSUE THREAD

**Issue by huttarichard** [Microsoft/vscode-go#1728]
No sure if this is about this extension or not. But this happens to me lately a lot:

![screen shot 2018-06-12 at 23 00 10](https://user-images.githubusercontent.com/1809268/41317144-a4ad88e2-6e94-11e8-8e87-59cf25b4df43.png)

have latest extension

**Comment by huttarichard** [comment]
I spot this only with golang.

**Comment by kentquirk** [comment]
This is the code coverage system accidentally being turned on.

Use Cmd-shift-P and select the "Toggle Test Coverage in Current Package"  command and it will go away.

**Comment by huttarichard** [comment]
Alright so this is a feature. Didn't know. Thanks!
