### ISSUE TITLE
Code completion does not work

### ISSUE THREAD

**Issue by luca-moser** [Microsoft/vscode-go#173]
vscode-go does not provide completion/suggestions under certain circumstances.

I've got a project, structured like this:
1. %GOPATH%/src/lucamoser.io/karbon/karbon.go
2. %GOPATH%/src/lucamoser.io/karbon/models/customer.go

When importing the second package into the first one (inside `karbon.go`), no suggestions/code-completion are given for the code inside `customer.go`:

![try_1](https://cloud.githubusercontent.com/assets/1385611/12119192/84a635ee-b3ca-11e5-8fa6-8d7de51d58ff.gif)

For the record: the problem is, that when I hit `ctrl + space` there are not suggestions. The issue is not the unused package import/variable error.

**Comment by abiosoft** [comment]
I'll try to reproduce this. 

The initial error for the import path is most likely for `unused import` error. Probably autocomplete is attached to the import not showing error.

**Comment by luca-moser** [comment]
I've resolved the issue. By default `gocode` does not autorebuild packages. So setting `gobuild set autobuild true` via console with fix this issue and immediately show suggestion/code-completion.

It might be worth to share this information in the readme somewhere?

**Comment by rogierlommers** [comment]
I had the same problem. `gocode set autobuild true` indeed solved it. Where does it save the setting?

**Comment by lukehoban** [comment]
Seems like this is something that quite a few folks have been running into.  So I think we'll go ahead and force `gocode set autobuild true` when vscode-go initializes.

The `gocode` docs mention that this is experimental still, but I haven't seen or heard of cases where it causes problems.
