### ISSUE TITLE
Cannot get the value of the monitor variables when debugging

### ISSUE THREAD

**Issue by nengc** [Microsoft/vscode-go#1730]
After i update the vscode to the latest version, I found i cannot get the monitor value when debugging, And cannot add variables to the monitor dynamically. And the snapshots are as below:

![image](https://user-images.githubusercontent.com/19792047/41389686-b6a716a4-6fc4-11e8-854e-f72abe669866.png)

![image](https://user-images.githubusercontent.com/19792047/41389699-d1eb8832-6fc4-11e8-98f4-3c9caeddbd2b.png)

![image](https://user-images.githubusercontent.com/19792047/41389734-06d117b0-6fc5-11e8-9de1-6ce09a95003e.png)

**Comment by ramya-rao-a** [comment]
This is most likely the same issue as #1714
I've released an update to fix #1714.
Can you update to 0..6.83 version of the Go extension and try again?

**Comment by nengc** [comment]
@ramya-rao-a  As you say，it is the same issue as #1714 . 
And after i updated to  0.6.83, the problem is gone. 
Thanks!

**Comment by ramya-rao-a** [comment]
Good to know.
Happy Coding!
