### ISSUE TITLE
go.toolsGopath doesn't expand ${env:GOPATH}

### ISSUE THREAD

**Issue by sphawk** [Microsoft/vscode-go#1732]
go.toolsGopath doesn't expand ${env:GOPATH}
I'm using ms-vscode.go v0.6.82

reproduce step

1. create .vscode/setting.json

{
    "go.gopath": "${env:GOPATH};${workspaceFolder}",
    "go.toolsGopath": "${env:GOPATH}"
}

2. press ctrl + shift + p, select Go: Install/Update Tools

**Comment by ramya-rao-a** [comment]
PRs are welcome to enable both `go.gopath` and `go.toolsGopath` settings to honor the env var

- [resolveToolsGopath](https://github.com/Microsoft/vscode-go/blob/0.6.82/src/util.ts#L309) is where we resolve toolsgopath
- [getCurrentGopath](https://github.com/Microsoft/vscode-go/blob/0.6.82/src/util.ts#L371) is where we resolve the gopath

The env var should be available in `process.env['GOPATH']`.

**Comment by sphawk** [comment]
ok, I'll do it within a few days.

**Comment by sphawk** [comment]
@ramya-rao-a I created pull request #1743, could you check it please?

**Comment by ramya-rao-a** [comment]
Hey @sphawk,

Am a little busy with work at the moment, will definitely get to this by the end of the week.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update to the Go extension (0.7.0)
Thanks to @sphawk!
