### ISSUE TITLE
Feature request: Add import folder to workspace

### ISSUE THREAD

**Issue by freman** [Microsoft/vscode-go#1733]
I'm not sure how feasible this one is but it's something I'm constantly doing.

It'd be super cool if you could select an import, right click it, and add folder to workspace.

**Comment by ramya-rao-a** [comment]
PRs are welcome for this feature

References:
- The `Go: Get Package` is an example of a command that acts on the import statement.
-  `vscode.workspace.updateWorkspaceFolders` can help in adding folder to workspace

**Comment by freman** [comment]
So, I'll be the first to admin, I've never used typescript before and my abuse of it is probably a reflection but I have a patch https://github.com/Microsoft/vscode-go/pull/1745 that is a start in a direction. It's not vendor aware but realistically your vendors are already in your workspace.

Happy for tips to further develop it?

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update (0.6.85) to the Go extension.
