### ISSUE TITLE
Linting Underline - Unused variable underline placement

### ISSUE THREAD

**Issue by itsjamie** [Microsoft/vscode-go#1734]
Given: `sCtx := httpstat.WithHTTPStat(ctx, r)`

If `sCtx` is unused in the program, and the linting error is shown, the portion which is outlined is the `r)`.

![Example](https://www.dropbox.com/s/34m30zg4yk7hjn0/Screenshot%202018-06-15%2011.30.34.png?dl=1)

It would be ideal if the sCtx was the portion which was underlined.

**Comment by ramya-rao-a** [comment]
Errors are shown in red, warnings in green.
Errors from linters are shown as warnings by the Go extension.
So what you are seeing must be from the build output.

Open the output pane (View -> Output), select "Go" from the dropdown on the top right corner of the output pane. This will have the output from build/lint/vet. Check the line number and column number in the build error output there. We use that to show the red lines.

**Comment by itsjamie** [comment]
I see! Thanks for the tip on the coloring, never really noticed it! I'll see about filing an issue on this upstream then :)
