### ISSUE TITLE
Install/Update Tools fails

### ISSUE THREAD

**Issue by kroppt** [Microsoft/vscode-go#1736]
Setup
- Windows go installation
- User GOPATH set to C:\Users\kropp\go
- No go-related settings in VSCode
- Already have the extension working

Steps to Reproduce:
1. Ctrl-Shift-P
2. Go: Install/Update Tools

"Go" OUTPUT:
```
Installing 16 tools at C:\Users\kropp\go\bin
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gomodifytags
  goplay
  impl
  fillstruct
  godef
  godoc
  goreturns
  golint
  gotests
  dlv

Installing gocode aborted as existing process cannot be closed. Please kill the running process for gocode and try again.
Installing github.com/mdempsky/gocode SUCCEEDED
Installing github.com/uudashr/gopkgs/cmd/gopkgs SUCCEEDED
```

After the last line of the above log prints, VSCode developer tools console errors:
```
  ERR Cannot read property 'Symbol(Symbol.iterator)' of undefined: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
	at callback (C:\Users\kropp\.vscode\extensions\ms-vscode.go-0.6.83\out\src\goInstallTools.js:260:37)
	at cp.execFile (C:\Users\kropp\.vscode\extensions\ms-vscode.go-0.6.83\out\src\goInstallTools.js:286:25)
	at ChildProcess.exithandler (child_process.js:209:7)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Notes:
- Restarting VSCode does not work
- I only noticed this when I was changing to `revive` linter, but it may have been happening before that
- I had issues installing one of the tools through this at one point, which I resolved by deleting the local folder for golang.org/x/lint
- Got it to update fine a couple times, not sure how
- No gocode process is running

**Comment by ramya-rao-a** [comment]
We show the `Installing gocode aborted as existing process cannot be closed....` message when running `gocode close` fails with something like `rpc: can\t find service Server` because of an existing process.

At this point, we shouldn't continue to update `gocode`, but according to the logs you shared, we do continue. I'll fix that.

**Comment by mikegleasonjr** [comment]
Since it prevents further tools from installing, one can start `gocode` manually first, then re-issue the Go: Install/Update Tools command.

All the tools wil be installed/updated.

**Comment by kroppt** [comment]
@mikegleasonjr Yes, that workaround seems to work.
