### ISSUE TITLE
Code completion doesn't work for packages outside of gopath

### ISSUE THREAD

**Issue by Jon-Murray** [Microsoft/vscode-go#1737]
Hi,

   So i'm writing this issue as i have read all previous issues on here to no avail and i'm hoping that getting an answer here will help me and others in future. Basically, i have a project set up like so:

       main.go
       projectname/utils/utils.go (function DoUtils())
       projectname/secondutils/secondutils.go  (function DoSecondUtils())
       src
       pkg
       bin

now if i import utils.go, or secondutils.go from within main.go, i get full completion. However, if i navigate into secondutils.go and try and reference something from utils.go, the packages gets found - set with   "go.autocompleteUnimportedPackages": true - but i get no autocompletion whatsoever.

I've read from previous issues that the autocomplete works based off of having the .a files within the pkg directory. Running 'go get ./...' or 'go install ./...' will correctly place both utils.a and secondutils.a within my pkg directory, but i still cannot get autocomplete when actually being inside the utils.go or secondutils.go code. I'd expect to be able to type "utils.D..." and have it present "DoUtils" regardless of which package I am in. It works fine in Jetbrains' gogland but not vscode. 

I've tried the various normal recommendations of updating gocode, killing it, rebooting vscode, etc. with no luck. I've also tried setting both gopath globally as an environmental variable, as a workspace variable, and removing both and using infergopath = true. All give the same results.

I'm using the latest vscode, gocode, and go 1.10.3 windows/amd64.

Thanks

**Comment by ramya-rao-a** [comment]
Run the below to start gocode in server mode
- `gocode close`
- `gocode -s -debug`

Now start typing in VS Code. The completions will start appearing in the terminal with all details. If you don't see the expected completions there, then such completions (from packages out of GOPATH) are not supported by `gocode` itself.

Also, I believe such code organization isn't suggested either.
Cant you put your `main.go` file and the `projectname` folder in a separate location under a "src" folder and include that in your GOPATH?

For example: In the below case your GOPATH would be `path-to-folder1;path-tofolder2` 

- folder1
    - src
        - main.go
        - projectName
    -pkg
    -bin
- folder2
     - src
     - pkg
     - bin

**Comment by Jon-Murray** [comment]
Thanks for getting back to me so quickly, but that's effectively how the project is laid out at the moment. Even having the above structure, when i've navigated into folder1 -> projectname -> utils -> utils.go, and then trying to reference something from secondutils, i wouldn't get autocompletion.

Is this expected behaviour? I mean, are you able to autocomplete from one subdirectory to another? I mean, as a practical example.. i'd expect to have "networkUtils" and "stringUtils" underneath one "utils" folder/namespace, referenced from the main project. Within networkUtils, i'd expect to call stringUtils for common functions/helpers i've made; i'd expect autocompletion here. Even laying out the project as you've recommended above i still get no completion, which is working fine in other IDEs.

Thanks

**Comment by ramya-rao-a** [comment]
> when i've navigated into folder1 -> projectname -> utils -> utils.go, and then trying to reference something from secondutils, i wouldn't get autocompletion.

- Is there a `src` folder after `folder1` and before `projectname`,  otherwise folder1 cannot be a valid GOPATH can it?
- Did you add both `folder1` and `folder2` to your GOPATH?
- Did you try running `gocode` in server mode and see what results are being returned?

**Comment by Jon-Murray** [comment]
So i've managed to fix it. I've no idea how i did it, but for those reading i did the following:

```
uninstalled/reinstalled go
reset all environmental variables
uninstalled vscode completely
cleared my global settings 
deleted all files under %localappdata%/temp/1
re-set/installed all of the above
rebooted
```

This seemed to fix the issue. My apologies for raising it, but thanks for the help.
