### ISSUE TITLE
Autocomplete not suggest type variable

### ISSUE THREAD

**Issue by paulviks** [Microsoft/vscode-go#1739]
Hello,
I install fresh vsc with vscode-go extension. 
Go version command return:
go version go1.10.3 linux/amd64
When i create new variable autocomplete doesn't show suggest of string, int... e.i.
![screenshot_20180618_214741](https://user-images.githubusercontent.com/32170749/41558813-5b44bff6-7342-11e8-9d07-6730ea597c9f.png)

**Comment by paulviks** [comment]
I replace mdempsky/gocode of nsf/gocode and completion works. Weird.

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode-go/commit/0f40521affce86b2cf75f52c5da47b0c51deb67e
Please see instructions at https://github.com/mdempsky/gocode/issues/34#issuecomment-405129087 to get the fix before I release an update later this week

**Comment by ramya-rao-a** [comment]
The fix for this issue is now out in the latest update (0.6.85) to the Go extension.
