### ISSUE TITLE
 If i am using Go-Lang extension it won't save changes but remove all changes and save it

### ISSUE THREAD

**Issue by Kabariya** [Microsoft/vscode-go#1740]
after opening file of Go-lang, if I made changes and then try to save, it won't save and it removes all changes that I have made within a file. And **Important Thing is that it happens only and only if I use "import" in file if remove all import it works normally** It happens only with Go-Lang extension. I tried with C and C++ language it works perfectly with that.

VSCode Version:1.24.1
OS Version: Ubuntu 18.04
Steps to Reproduce:

Open Go-Lang File. Make some changes
Try to save. It won't save and remove all changes
if I disable an extension it works and saves perfectly but then I don't get advantages of extension

Does this issue occur when all extensions are disabled?: No

**Comment by OneOfOne** [comment]
Does it still happen if you set `"editor.formatOnSaveTimeout": 10000` in your vscode config (`ctrl+,`)?

**Comment by Kabariya** [comment]
yes

**Comment by Kabariya** [comment]
before cntl + s

**Comment by Kabariya** [comment]
yes

**Comment by Kabariya** [comment]
I m sorry. I misunderstood go extension. Everything is okay :)
