### ISSUE TITLE
Feature Request: Better interface stubbing

### ISSUE THREAD

**Issue by matthewmueller** [microsoft/vscode-go#1741]
It can be hard to get the input right with the current implementation of `Generate Interface Stubs`. 

For example, if your path is `github.com/matthewmueller/graphql` and you have a `Query` interface and you want your `query` struct to implement it:

```go
package graphql

// interface to implement
type Query interface {
  CreateTeam(ctx context.Context, teamInput TeamInput) (Team, error)
  // ... many more
}

// this struct needs to implement the Query interface
type query struct {}

// interface enforcement
var _ Query = (*query)(nil)
```

With the `Generate Interface Stubs`, you'd need to write in the following:

```
q *query github.com/matthewmueller/graphql.Query
```

This is quite hard to get right. I think it'd be a lot more useful if it did the following:

1. Highlight over the interface enforcement with your cursor: `var _ Query = (*query)(nil)`
2. Right click, and click on `Generate Interface Stubs`
3. It calls `impl` under the hood with the correct paths. The receiver variable could just be the first letter of the struct (lowercased)
4. The output is written below your cursor selection

---

**Update:** Even better would be how typescript does it with the little lightbulb next to any interface enforcement that is currently erroring out.

**Comment by qzyse2017** [comment]
@matthewmueller could you describe your demand more specific with your directory structure and the path of your project? I would like to take this issue but it seems you just need to type in `graphql.Query` instead of `github.com/matthewmueller/graphql.Query` , the current implemantation in vscode -go extension which make use of `impl` seems to perform the same with `github.com/matthewmueller/graphql.Query` and  `graphql.Query`

**Comment by qzyse2017** [comment]
If you put your project under `$GOPATH` directory, `impl` will automatically search it and you just need to type in the package name without its previous path if it is not ambiguous with another package

**Comment by matthewmueller** [comment]
@qzyse2017 awesome! I'm not able to reproduce needing the full path, maybe I was typing in the command wrong. That's definitely easier

Either way, I think it would be awesome if it could auto implement: `var _ Query = (*query)(nil)`

**Comment by qzyse2017** [comment]
@matthewmueller I am doing it in a similar way to what you need.
It  just needs to 
1. select the reciever type name and use right click to choose the command `Generate interface stub `, the inputbox will have the `t *typeReciever`(something like it) auto completed 
2. type in the last arg: `packageName.interfaceName`(packageName here do not need its previous path) 

3. relocate your cursor to find the correct place to insert and type in `Enter` in the inputBox to confirm the command,

I think steps above can be used in more general conditions.
can you give me some more suggestions on making it more easier to use?

**Comment by zhulingbiezhi** [comment]
Nice,  looking forward to this issuer.

**Comment by BitPhinix** [comment]
It would also be nice if vscode would provide interface stubbing as a quick fix.

```
func NewRepository(db orm.DB) goal.Repository {
	return &Repository{
		db: db,
	}
}
```

Should provide a quick fix like "generate interface stubs" if Repository doesn't implement goal.Repository

**Comment by stamblerre** [comment]
Feature work in this area will be done in `gopls` rather than in this extension. I'm going to close this in favor of the upstream issue, https://github.com/golang/go/issues/37537.
