### ISSUE TITLE
ability to copy type

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode-go#1742]
```
package dropbox

import (
	"testing"

	"github.com/dropbox/dropbox-sdk-go-unofficial/dropbox"
	"github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/users"
)

const token = ""
const accountId = ""

func TestDropbox(t *testing.T) {
	config := dropbox.Config{
		Token:    token,
		LogLevel: dropbox.LogInfo,
	}
	dbx := users.New(config)
	arg := users.NewGetAccountArg(accountId)
	if resp, err := dbx.GetAccount(arg); err != nil {
		t.Fatal(err)
	} else {
		t.Logf("Name: %v", resp.Name)
	}
}
```
You can hover over `resp` to see the type, but you can't copy the type `*users.BasicAccount` into the clip board so you can use it to paste in for example a function argument declaration.
![image](https://user-images.githubusercontent.com/863731/41596063-5b6f5478-73c9-11e8-891c-901e2a006852.png)

**Comment by ramya-rao-a** [comment]
I am able to copy text from what is shown on hover as shown below.

![hover](https://user-images.githubusercontent.com/16890566/42074807-d904ff04-7b22-11e8-9e47-6809b6a0625f.gif)

Is this what you are trying to do or am I missing something?

**Comment by gertcuykens** [comment]
Yes but you have to admit it's like doing heart surgery to be ably to accomplish what you just dit :P I think it should be in the right click menu

**Comment by ramya-rao-a** [comment]
Wow... thats demeaning to all the heart surgeons who have spent years learning their craft and where people die if they make a mistake!!

Kidding.

Providing an option copy the hover text to the clipboard is a language agnostic feature request. As such, please log it in the repo for [VS Code](https://github.com/Microsoft/vscode).
