### ISSUE TITLE
Support ability to run individual subtests

### ISSUE THREAD

**Issue by Robinnnnn** [Microsoft/vscode-go#1748]
One of my favorite VSCode features is the ability to run a specific Go test with the click of a button via **run test**, which is auto-generated based on [certain factors](https://twitter.com/ramyanexus/status/1009659005038292992). It would be great if this button could also show up under [subtests and sub-benchmarks](https://blog.golang.org/subtests), a feature introduced in Go 1.7 for increased flexibility + modularization.

Below is a screenshot of some tests I'm working on for card registration. Notice the **run test** option appearing over `func TestCard`, but *not* over the subtests within (declared via `t.Run`):

![screen shot 2018-06-21 at 11 22 11 am](https://user-images.githubusercontent.com/12162433/41728902-f03f5e54-7545-11e8-9480-94374f4c38d6.png)

Running subtests in the above example using the command line is easy if you're trying to group them:
```
go test -run Card           // runs `TestCard` and all underlying subtests
go test -run Card/valid     // runs all subtests under `TestCard` that match `valid` (first and fourth ones)
```

Where the CLI gets cumbersome is when I want to run a _specific_ subtest and have to type out the entire name:
```
go test -run Card/Card__invalid_creation__invalid_token
```

This is a first-world problem but it would be amazing to just do this through the click of a button.

I guess the challenge is that subtests are declared _within_ a function declaration and never at the outer level. It is also common to use `t.Run` inside a loop, which would make the purpose of a button more ambiguous:

```
func TestGroupedParallel(t *testing.T) {
    for _, tc := range tests {
        tc := tc // capture range variable

        /////// what would a button do if it appeared here?
        t.Run(tc.Name, func(t *testing.T) {
            t.Parallel()
            ...
        })
    }
}
```

It definitely wouldn't be the end of the world if this is not worth implementing but I just wanted to put it on your radar! Thank you in advance.

**Comment by ramya-rao-a** [comment]
> I guess the challenge is that subtests are declared within a function declaration and never at the outer level. 

Yes, thats indeed the challenge.
The Go plugin gets the outline of the file (what you see when you do a Ctrl/Cmd+Shift+O), get all functions whose name starts with either "Test", "Benchmark" or "Example" and then provides the code lens to run the tests.

In case of sub tests, we need to parse the inner contents of the function which the Go plugin isn't capable of doing as it doesn't really understand Go code. For all other rich language features, we use the Go tools like godef, gocode etc.

If there was a tool that understands Go code and would return positions of each sub tests, then we could use that to provide the codelens.

Thanks for logging the feature request, but unfortunately, in the current state of things, we cannot implement this feature.

I did get to learn about sub tests though, so thanks for that!
