### ISSUE TITLE
Run Stop has wrong number of ins

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode-go#175]
The following works without error in mac os console

./debug -port=8080
dlv debug -- -port=8080

Using vscode I get errors in server.go when doing `go http.ListenAndServe...`

```json
{
	"version": "0.6.22",
	"configurations": [
		{
			"name": "Launch main.go",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "${workspaceRoot}/.",
			"env": {},
			"args": ["-port=8080"]
		}
	]
}
```

```log
debugger.go:56: launching process with args: [./debug -port=8080]
server.go:301: method Run has wrong number of ins: 1
server.go:301: method Stop has wrong number of ins: 2
debugger.go:227: continuing
```

Also note that the breakpoint only works once in a http handler, after continue the next same http request does nothing.

**Comment by lukehoban** [comment]
The `method Run has wrong number of ins: 1` actually just comes from passing `--log` to `dlv`.  I always see that being printed - it shouldn't be a blocking error.  (Of course, we should look into why).

As for the actual problem you are seeing - could you provide a code sample and details of whats going wrong?

> Also note that the breakpoint only works once in a http handler, after continue the next same http request does nothing.

I've certainly debugged examples of HTTP servers in Go where this is not the case - so I expect it's something specific to your particular code.

Can you reopen with more details?

**Comment by gertcuykens** [comment]
Ok I will create a new issue about the breakpoint because it has no correlation with the error message. You are correct after testing some more it always prints the error. Ps can you keep this issue open please until it's confirmed what causes the problem? Maybe mark it help needed or something.

**Comment by gertcuykens** [comment]
Going to open a ticket at dlv, I get the same error just using dlv
```log
dlv --log debug -- -port=8080
2016/01/27 20:51:59 debugger.go:56: launching process with args: [./debug -port=8080]
2016/01/27 20:51:59 server.go:301: method Run has wrong number of ins: 1
2016/01/27 20:51:59 server.go:301: method Stop has wrong number of ins: 2
Type 'help' for list of commands.
(dlv) exit
```
