### ISSUE TITLE
buildOnSave automatically puts -o flag, but breaks in 1.10

### ISSUE THREAD

**Issue by aerialcombat** [Microsoft/vscode-go#1757]
`go build -i -o `

produces

```
flag needs an argument: -o
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
```

'-o' needs to be removed.

**Comment by ramya-rao-a** [comment]
I am guessing you tried to run `go build -i -o` separately and got the above error.
You need to provide a path for the output binary if you are using `-o`

The Go extension provides a temp path when building on save.
I just tried on 1.10 and everything is working as expected in the Go extension.
