### ISSUE TITLE
All test functions are broken (possibly due to vscode API change)

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode-go#176]
Running any of the test commands throws a console error:

```
Running the contributed command:'vscode.executeDocumentSymbolProvider' failed.
```

Looks like https://github.com/Microsoft/vscode/issues/769 finally caught up with us somehow. I haven't debugged the vscode API to determine the underlying source of the error since I think it's time to just reuse the vscode-go DocumentSymbolProvider in the test subsystem. I'm working on a PR for it (but am wrestling with TypeScript union return types so it's slow going).

Using Code 0.10.6 and vscode-go e14219882dc284b0a83b0ecb36d3251efe22632f

**Comment by lukehoban** [comment]
@ironcladlou Sorry for the delay on this.  I've pushed a fix which avoids invoking `vscode.executeDocumentSymbolProvider` at all, and just directly calls the GoDocumentSymbolProvider API.  Per @jrieken's comments in https://github.com/Microsoft/vscode/issues/769, I think this is the more correct behaviour anyway.
