### ISSUE TITLE
go binary in $GOROOT should be prioritized

### ISSUE THREAD

**Issue by FiloSottile** [Microsoft/vscode-go#1760]
Since e882fb2f971a07d205dd61ee126065e9799c13f2, the `go` binary in `$PATH` is prioritized even if `go.goroot` is explicitly set. It can be overridden with `go.alternateTools`, but it is pretty unexpected.

**Comment by FiloSottile** [comment]
Also, `go.alternateTools` does not expand `~`, so it doesn't fully work as a replacement.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @FiloSottile 

Is it a common scenario to have different go binaries in $PATH vs the goroot?

**Comment by FiloSottile** [comment]
Myself I use it to develop on the standard library, and I would expect most people doing that to have different binaries in PATH. I think it's closely correlated to setting GOROOT explicitly, as that often implies using a separate toolchain.

The priority I would expect it alternateTools > GOROOT > PATH.

**Comment by ramya-rao-a** [comment]
How about 3rd party go tool binaries?

alternateTools > GOROOT > PATH > GOPATH 
or
alternateTools > GOPATH > GOROOT > PATH ?

**Comment by FiloSottile** [comment]
No real reason for anything else than `gofmt` and go to be in `GOROOT/bin`, so it's almost irrelevant, but I guess "alternateTools > GOROOT > GOPATH > PATH" for consistency across all tools?

**Comment by ramya-rao-a** [comment]
I have pushed the fix to master. Can you give it a try by following the below steps and share any feedback you have.

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by RinaFave01** [comment]
Cc creative commons

**Comment by ramya-rao-a** [comment]
The fix for this issue is now out in the latest update (0.6.85) to the Go extension.
