### ISSUE TITLE
lint on save is causing my laptop to die

### ISSUE THREAD

**Issue by primalmotion** [Microsoft/vscode-go#1761]
When doing some big search & replace in a fairly big projec, it starts the linter processes (once per package).
This ends up basically killing my laptop for dozens of minutes.

Maybe a solution would be to :
- run only a few lint processes at the same time and have a queue
- add a way to kill the running linting processes

**Comment by primalmotion** [comment]
I'm not sure if this issue can be solved here, or if I should open in on vscode main repo

**Comment by ramya-rao-a** [comment]
This is similar to save all triggering a lot of linter processes which is covered in https://github.com/Microsoft/vscode-go/issues/1015
