### ISSUE TITLE
IntelliSense is completely broken on Windows

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode-go#1762]
Probably a duplicate of #1723

![image](https://user-images.githubusercontent.com/9491603/42128688-93de677c-7cb1-11e8-90f9-85807b9dabb2.png)

This code compiles fine. I already updated all Go tools used by the extension.
I'm using Go 1.10, VS Code 1.24.1 and vscode-go 0.6.84

More examples:

![image](https://user-images.githubusercontent.com/9491603/42128700-e6e170fe-7cb1-11e8-9467-641f9d2ad15d.png)
IntelliSense doesn't show at all. Doesn't help to show it manually.

![image](https://user-images.githubusercontent.com/9491603/42128973-aa4e7154-7cb7-11e8-861e-22938026ad71.png)
Again, it compiles so this type cannot be invalid.

Additionally, just some general feedback: To be honest I'm kinda disappointed by this extension. I never got it working well (at least on Windows, didn't try it on macOS or Linux) and always switched back to GoLand which just works fine out-of-the-box but I would like to stop paying for it because it's a bit expensive for private fun side-projects. VS Code itself is so high-quality so it confused me a bit why this extension isn't. I will try to compile a list of general issues and file separate issues if they don't exist yet and also look into contributing but I'm not sure if I have the time and expertise. I really want this extension to be as great as the rest of VS Code but at the moment it was just an awful experience for me.

**Comment by bidhan-a** [comment]
Same here. I had to format my machine for some reason. After doing a fresh installation of the latest versions of Go, VS Code, and VS Code extensions, Intellisense has stopped working altogether. No matter what I type, it says `*invalid type` instead of showing suggestions.

**Comment by ansencumt** [comment]
![image](https://user-images.githubusercontent.com/5181385/42197804-2518030e-7eb7-11e8-983a-7799c3581307.png)

The same to me. But it seems to only appear in the same workspace with different references between packages.

VSCode: 1.24.1

**Comment by ramya-rao-a** [comment]
The issue with auto-completions is due to `nsf/gocode` and the alternative `mdempsky/gocode` having their own issues with Go 1.10 Otherwise, completions using this extension never had any issues before.

Please try https://github.com/Microsoft/vscode-go/issues/1723#issuecomment-403673078 and let me know if that helps at all.

**Comment by bidhan-a** [comment]
I followed the solution described [here](https://github.com/Microsoft/vscode-go/issues/1758#issuecomment-402851808) and Intellisense is now working for me.

**Comment by levrik** [comment]
@ramya-rao-a 0.6.85 fixed this issue for me!
