### ISSUE TITLE
we need to stop adding new features and make sure the current features are working 100%

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#1763]
Right now the extension grew to be a massive beast, however a lot of the tooling are falling apart (mainly gocode and/or go-langserver).

We need to figure something out, maybe an active fork or something.

This is more of a thinking-out-loud thing than an actual bug/request, feel free to close it.

**Comment by ramya-rao-a** [comment]
The `go-langserver` has always been an opt-in and marked as an experimental feature. It was mainly a stepping stone to an eventual scenario where we would use the language server for all the language features.

The gocode case is definitely an unfortunate one where the one we relied on for many years (nsf/gocode) doesn't work well with Go 1.10 and above. And the replacement (mdempsky/gocode) is not working well for many either.

None of the new features added in the past 6 months are creating any issues as far as I can see. Its existing features (language server and gocode like you said) that are having issues. 

I myself have stopped adding new features and have taken more of a maintainer role with essential bug and perf fixes. At the same time, if there are PRs for new features from the community, I am all for it, and will not take the stance of "no new features".

I also agree that its about time that we took a step back and take a look at whats not working. Especially the issue with gocode and debugging with symlinks.

A big refactoring is also in order.

I am on vacation for a week, once am back, my first task is to tackle the gocode issue.

Thanks for your concerns though and if you have any ideas on what to do with the gocode issue, please do share.
