### ISSUE TITLE
workspace bashrc environment variables

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode-go#1764]
osx
vscode 1.24
extention 0.6.84

When you launch a debugger on one of the directories in a workspace vscode, the bashrc environment variables are not picked up as they are when you launch debugger in a non workspace vscode. In vscode workspace mode it seems debugger get started in it's own shell instead of the normal shell that includes the bashrc environment variables

```
func main() {
	fmt.Println("Hello ", os.Getenv("ENVIRONMENT"))
}
```

Define a export in bashrc named ENVIRONMENT and debug the above code in vscode normal mode and vscode workspace mode

**Comment by ramya-rao-a** [comment]
Hey @gertcuykens 

I followed your instructions on the latest VS Code and Go extension versions on a Mac. I am able to see the value of the env variable set in .bashrc file in both modes. Below are my steps

- Create .bashrc file with `export ENVIRONMENT=hello-env`
- Run `source .bashrc` to apply it on current terminal
- Run `code-insiders` from the terminal
- Added your code above
- Debug to find expected output
- Run command `Save workspace as` to convert current set up to workspace mode
- Debug to find expected output

**Comment by ramya-rao-a** [comment]
Can you try with latest VS Code and Go extension?

**Comment by gertcuykens** [comment]
Both are working :) Seems Ramya has a bit of a backlog at the moment :P Thanks for cleaning things up <3
