### ISSUE TITLE
Linting  Highlights Persist Even when Fixed

### ISSUE THREAD

**Issue by husainaloos** [Microsoft/vscode-go#1767]
I am running into this linting problem. When VSCode detects a compiler error, it puts a red line under where the error is. This line remains even after I fix the error.

![image](https://user-images.githubusercontent.com/4754802/42218192-6471bdee-7e8d-11e8-8e0e-c2fc2f21c03a.png)

This has been happening quite often, and  my fold structure is almost all red.

I it still not clear to me how to reproduce it. All I do is this:
1. create a compile error, vscode highlights it
2. build
3. build fails. I go and fix it
4. build
5. it is fixed, but vscode does not remove the highlight.
6. reloading the window fixes the issue

Here is my setting:

```json
{
  "html.format.enable": true,
  "workbench.iconTheme": "material-icon-theme",
  "workbench.statusBar.visible": true,
  "workbench.activityBar.visible": true,
  "workbench.colorTheme": "Material Theme Darker High Contrast",
  "editor.fontSize": 14,
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.minimap.enabled": false,
  "editor.wordWrap": "on",
  "editor.renderIndentGuides": true,
  "editor.formatOnSave": true,
  "editor.multiCursorModifier": "alt",
  "editor.tabSize": 8,
  "prettier.disableLanguages": [
    "vue",
    "markdown",
    "typescript"
  ],
  "git.autofetch": true,
  "git.confirmSync": false,
  "material-icon-theme.showUpdateMessage": false,
  "emmet.triggerExpansionOnTab": true,
  "gitlens.advanced.messages": {
    "suppressCommitHasNoPreviousCommitWarning": false,
    "suppressCommitNotFoundWarning": false,
    "suppressFileNotUnderSourceControlWarning": false,
    "suppressGitVersionWarning": false,
    "suppressLineUncommittedWarning": false,
    "suppressNoRepositoryWarning": false,
    "suppressResultsExplorerNotice": false,
    "suppressShowKeyBindingsNotice": true
  },
  "todohighlight.isEnable": true,
  "gitlens.historyExplorer.enabled": true,
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
  "terminal.integrated.shellArgs.windows": [
    "/k C:\\PROGRA~1\\cmder\\vscode.bat"
  ],
  "gitlens.gitExplorer.files.layout": "list",
  "team.showWelcomeMessage": false,
  "window.zoomLevel": 0,
  "materialTheme.fixIconsRunning": false,
  "terminal.integrated.rendererType": "dom",
  "vsicons.projectDetection.autoReload": true
}
```

**Comment by ramya-rao-a** [comment]
In your step 4 you say "build". How exactly are you building it?

**Comment by husainaloos** [comment]
@ramya-rao-a I meant building the go project (go build).

After the last vscode update, I don't seem to be able to replicate the problem. It could have been fixed, though I didn't see anything in the release note that mentioned that.

**Comment by ramya-rao-a** [comment]
Running `go build` manually in a terminal will not remove the errors.
You either need to save the file which will trigger a build or running build manually via a command in VS Code.

I will close this issue for now. Let us know if you see it again.
