### ISSUE TITLE
Debugging unit tests does not honor "go.gopath" setting

### ISSUE THREAD

**Issue by olostan** [Microsoft/vscode-go#1768]
I have followed all instructions and I can run/debug and run unit tests of my application. 

However, when I try to debug unit tests, it looks like "go.gopath" setting is ignored (it uses GOPATH from environment). 

Steps to Reproduce:

1. Change "go.gopath" setting
2. Verify that program can be run/debugged and unit tests are run
3. Try to debug unit test
4. See error "cannot find package..."

**Comment by lggomez** [comment]
Static debug configuration for unit tests is a known issue. #1749 solved it in regards to delve support, I´ll take a look at this

Preferably, "go.gopath" will override the environment gopath, which is the one vscode is using for default on the test debug codelns

**Comment by olostan** [comment]
@lggomez for me the most strange that go.gopath was respected in normal debug mode and when running test. The only case where gopath was taken from env - debugging unittest...

**Comment by ramya-rao-a** [comment]
@olostan 
- Are you on the latest version of the Go extension (0.6.84)?
- Are you trying to debug the unit tests using the codelens or a debug configuration?
- If you are using a debug configuration, then can you share that config?
