### ISSUE TITLE
Code Complication in PHP

### ISSUE THREAD

**Issue by cra0kalo** [Microsoft/vscode-go#177]
![ss 2016-01-26 at 02 39 14](https://cloud.githubusercontent.com/assets/6405860/12571982/9f46bf60-c43a-11e5-9e50-43937e26a2ed.png)

This is really annoying any way to disable this for comments?

**Comment by lukehoban** [comment]
I think this is feedback on the PHP language support - not the Go support in this repo.  Did you intend to open this in http://github.com/Microsoft/vscode?
