### ISSUE TITLE
bug - not able to find reference for a particular project

### ISSUE THREAD

**Issue by flockonus** [Microsoft/vscode-go#1770]
### bug report

It seems that for the specific repo of [go-libp2p](https://github.com/libp2p/go-libp2p), the GO TO DEFINITION (F12 / cmd+click) is not working, but it does work for other projects.

I'm suspecting it might have to do with the way the directory are structured? I really can't figure out why it's impossible to go to definition just for this particular project, even tho from the example folder source code it can navigate to other dependencies.

Steps to Reproduce:

1. clone https://github.com/libp2p/go-libp2p
2. follow dependencies install instruction in the README
3. open vscode, examples/echo/main.go try to go to definition for any function of `libp2p` - it fails. Anything else, works.

Some system info:

Process Argv | /Applications/Visual Studio Code.app/Contents/MacOS/Electron .
-- | --

Extension | Author (truncated) | Version
-- | -- | --
vscode-docker | Pet | 0.0.27
Bookmarks | ale | 0.19.1
jupyter | don | 1.1.4
pgsql | dou | 0.1.3
solidity | Jua | 0.0.45
python | ms- | 2018.6.0
csharp | ms- | 1.15.2
Go | ms- | 0.6.84
proto | pet | 0.0.2

**Comment by flockonus** [comment]
I believe the default config was to blame.

With the params: `"go.docsTool": "guru"` or `"go.docsTool": "gogetdoc"` then it works.

**Comment by ramya-rao-a** [comment]
Glad you found a workaround. The default tool being used is godef. Please log an issue https://github.com/rogpeppe/godef if you are not able to find the definition even after using `godef` from the terminal

**Comment by flockonus** [comment]
If godef is the default, and it has some cases where it doesn't work, while other do, then IMO it means vscode should have another default

**Comment by ramya-rao-a** [comment]
#1025 tracks just that. I havent had the time to resolve it yet though.
