### ISSUE TITLE
go.addTags should supports multi tags

### ISSUE THREAD

**Issue by IIInsomnia** [Microsoft/vscode-go#1771]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Please provide examples and sample code. Also check if [gomodifytags](https://github.com/fatih/gomodifytags) supports your case

**Comment by IIInsomnia** [comment]
custom multi tags, then can select add `json` tag or `db` tag, etc.

**Comment by ramya-rao-a** [comment]
I believe this is already supported. Please see https://github.com/Microsoft/vscode-go/wiki/Release-Notes#0656---29th-march-2017

**Comment by IIInsomnia** [comment]
thanks a lot !
