### ISSUE TITLE
debug  bug  in coroutine

### ISSUE THREAD

**Issue by WithLin** [Microsoft/vscode-go#1773]
If this is a bug report, please share 
- i am debug  go  project  mutil  Coroutine  vscode  will  Failed to next.

Steps to Reproduce:

2018/07/06 15:29:45 debugger.go:510: continuing
2018/07/06 15:29:47 debugger.go:510: continuing
2018/07/06 15:29:55 debugger.go:522: nexting
2018/07/06 15:29:55 debugger.go:522: nexting
2018/07/06 15:30:01 debugger.go:510: continuing
2018/07/06 15:30:05 debugger.go:522: nexting
2018/07/06 15:30:08 debugger.go:522: nexting
Failed to next.

vscode debug is die.

![image](https://user-images.githubusercontent.com/22409551/42365941-7429ea20-8132-11e8-93ae-a1fff981ba3e.png)

so what should i do?

**Comment by lggomez** [comment]
Can you add `"trace": "verbose"` to the debug config in the launch.json and share the logs?

**Comment by lggomez** [comment]
@WithLin can you share the logs again but using the latest version? I didn´t dive into the logs yet but the latest beta contains changes that should help diagnosing the cause

To install the update,

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run code --install-extension Go-latest.vsix
- f the above fails with Error: end of central directory record signature not found, then clone this repo and use the Go-latest.vsix file from the cloned repo
- Reload VS Code

**Comment by WithLin** [comment]
Thank you for your answer。
 you answered it too long, I have finished writing the project.
