### ISSUE TITLE
Parse test output and present it in a nice way

### ISSUE THREAD

**Issue by recht** [Microsoft/vscode-go#1774]
When running tests from vscode I often have to look at the output for a while before I can figure out which tests actually failed. This is particularly bad if the tests produce a lot of debug output.

It would be awesome if the test output was nicely formatted and presented somehow. I don't know what's actually possible in vscode, but a listing of the failed tests with an option to expand the output would be great.

**Comment by ramya-rao-a** [comment]
We show the exact same output which `go test` gives us with the exception that we expand the relative file paths to absolute paths. 

Would you say the normal output of the `go test` command itself is not intuitive enough or that us expanding the file paths is creating noise?

**Comment by recht** [comment]
`go test` output is also pretty bad, it's just as hard to figure out what failed (and how many tests failed) when you have a lot of output. It gets even worse if you enable parallel execution while you have output. In that case the output will be interleaved, making it more or less impossible to figure out what happened.
I would suggest using a treeview of some sort with each test at the root with a color indicator, somewhat like intellij/eclipse: https://www.jetbrains.com/help/idea/viewing-and-exploring-test-results.html

**Comment by ramya-rao-a** [comment]
We as an extension will not be investing in a UI feature that is better implemented from the core VS Code. See https://github.com/Microsoft/vscode/issues/9505 which is the upstream feature request in VS Code to have a test runner viewlet/tree. When that is implemented, we can onboard this extension to use the same.

In the absence of an upstream solution, extensions can still do this using the tree view approach like you suggested. I do believe this is a useful feature to have, although it would be out of scope for this extension.

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features. Therefore,one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request is definitely one such request.
