### ISSUE TITLE
Excessive cpu usage

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode-go#1776]
Issue Type: <b>Bug</b>

Excessive cpu usage,as shown in the screenshot below .But when i disable the Go plugin,the problem disappears.

![10](https://user-images.githubusercontent.com/13393959/42415766-306c614e-828d-11e8-8f53-14311a9d2bdd.png)

![11](https://user-images.githubusercontent.com/13393959/42415767-413b8108-828d-11e8-8ed3-f8eb18f5ae48.png)

Extension version: 0.6.84
VS Code version: Code - Insiders 1.26.0-insider (bd953248ad6a8e2f8896bfb78b3ae40e0fd47426, 2018-07-06T05:17:37.386Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.48GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by MrTravisB** [comment]
I believe this is more about the gotools that are run. Everytime I save a file I see the various tools show up in the top of CPU usage.

**Comment by ramya-rao-a** [comment]
Do you have the references codelens enabled? That might explain all the `guru` instances.

**Comment by czfadmin** [comment]
@ramya-rao-a 
It seems that only <code>guru</code> does this.
And I have the references codelens enabled

**Comment by ramya-rao-a** [comment]
Then that's the culprit.
`guru` is inherently slow. We use it to find references.
Having codelens for references enabled would mean a lot of guru processes around. Especially on larger files.
I would suggest to disable the references codelens until we have a good alternative to guru
