### ISSUE TITLE
how to show full struct tip info? 

### ISSUE THREAD

**Issue by wjx0912** [Microsoft/vscode-go#1783]
vscode-1.25, go version go1.10.2 windows/amd64

when mouse over the struct, a popup window show, it give the struct member, but no funciton.
a screenshot: http://45.63.95.173:9527/vscode-go.png

how to fix it?

**Comment by ramya-rao-a** [comment]
We use `godef` and `gogetdoc` tools to provide the hover info. Please log issues in the repos for these tools.
