### ISSUE TITLE
bind: can't assign requested address

### ISSUE THREAD

**Issue by wustzhy** [Microsoft/vscode-go#1785]
##### launch.json configuration below:
```
{
    "version": "0.2.0",
    "configurations": [
		{
			"name": "Launch",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"remotePath": "",
			"port": 2345,
			"host": "127.0.0.1",
			"program": "${fileDirname}",
			"env": {},
			"args": [],
			"showLog": true
		}
	]
}
```
***press F5, then failed***

##### debug console show below:
```
API server listening at: 127.0.0.1:2345
time="2018-07-12T14:50:14+08:00" level=info msg="launching process with args: [/Users/erice/Desktop/tool_test/Go/src/test1/debug]" layer=debugger
could not launch process: listen tcp 185.199.110.153:0: bind: can't assign requested address
Process exiting with code: 1
```

**Comment by ramya-rao-a** [comment]
Are you able to debug using delve from the command line?

**Comment by wustzhy** [comment]
@ramya-rao-a , Thanks for your attension
I used Visual Studio Code(VSCode) to debug, above is error log in the DEBUG CONSOLE of VSCode.

Then I use delve debug in the terminal, failed, log as below:
yestin-iMac:test1 erice$ dlv debug math_1.go
couldn't start listener: listen tcp 185.199.109.153:0: bind: can't assign requested address

**Comment by ramya-rao-a** [comment]
Thanks for sharing that you get similar error when using delve directly.
VS Code uses delve to provide the debugging features.
Please log an issue at https://github.com/derekparker/delve
