### ISSUE TITLE
Go: Toggle Test Coverage In Current Package, No color highlight

### ISSUE THREAD

**Issue by finalcreator** [Microsoft/vscode-go#1786]
I use windows vscode 1.25.1 ,  and  try "go test in package" and  "" , please see my plugin below:
![image](https://user-images.githubusercontent.com/2627422/42721623-6c114394-8770-11e8-9114-7d187a2d2ad9.png)

and settings:
![image](https://user-images.githubusercontent.com/2627422/42721652-ea87d7a6-8770-11e8-84f1-42f749fa278d.png)

There is a coverage statistics in console, but **no color highlight**!
Is there any thing I have to enable?

**Comment by ramya-rao-a** [comment]
The coverage result in the terminal shows the file path as starting with `_` which happens when GOPATH is not set. Do you get the expected GOPATH when you run the command `Go: Current GOPATH`?

**Comment by finalcreator** [comment]
Thanks for your replay, it works after I double check the GOPATH variable settings and point to the workspace folder.
