### ISSUE TITLE
How to disable green tips?

### ISSUE THREAD

**Issue by zhanswift** [Microsoft/vscode-go#1787]
How to disable green tips?

![2018-07-14 18 53 58](https://user-images.githubusercontent.com/16617536/42724619-4f6070d6-8797-11e8-8fde-40afbd13ae00.png)

**Comment by ramya-rao-a** [comment]
Those are either linter warnings or warnings from running `go vet`.
Hover on them to read the warning. Or press F8 to go over all the warnings.

To get rid of them, fix the problem that is being called out in the warning.
If you don't want to see the warnings at all, then add the below to your settings
```
"go.lintOnSave": "off",
"go.vetOnSave": "off"
```

In the future, if you have questions on the usage of this extension, please feel free to ask in the vscode channel on [Gophers slack](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwit5fuPmKDcAhVxHjQIHXMABtkQFggpMAA&url=https%3A%2F%2Finvite.slack.golangbridge.org%2F&usg=AOvVaw08_uXSna-aeaVk9bTsuJhN) or the [gitter](https://gitter.im/Microsoft/vscode-go). The Go community there would be happy to help
