### ISSUE TITLE
Extract to const/var feature

### ISSUE THREAD

**Issue by marco-jantke** [Microsoft/vscode-go#1796]
It would be nice if expressions or literals could be extracted to a variable or constant. Consider the following example:

```golang
myArtificalSample := fn("argument")
```

By moving the cursor to the "argument" literal you could extract it to a constant, requiring the user to input the name of the constant and transforming the code to the following:

```golang
const myArgument = "argument"
myArtificalSample := fn(myArgument)
```

The same would be nice for variables.

**Comment by ramya-rao-a** [comment]
The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension has this feature. Please see [Refactoring in VS Code](https://code.visualstudio.com/docs/editor/refactoring) on how you can use the refactor feature.
