### ISSUE TITLE
Show Method Type in Symbol Browser

### ISSUE THREAD

**Issue by kylebrandt** [Microsoft/vscode-go#18]
When using the symbol browser, I have methods that are bound to different types of the same name:

![image](https://cloud.githubusercontent.com/assets/1692624/11250408/6e55bed6-8dfa-11e5-8510-0f268552c192.png)

It would be nice to see which type each of those methods are for in that view.

**Comment by prashantv** [comment]
I agree with 2 as well, the receiver type is mostly useful to uniquely identify it.

**Comment by lukehoban** [comment]
Thanks to @prashantv for the contribution of https://github.com/lukehoban/go-outline/pull/3 which this is now implemented on.  

As noted in the commit - this additional information will only show up for users who update their `go-outline` - and we unfortunately don't have any good way to force/suggest users do that yet.
