### ISSUE TITLE
Using delve debugging in Windows  os console, can not stop at the breakpoint.

### ISSUE THREAD

**Issue by ljia310** [Microsoft/vscode-go#180]
Delve now has support for Windows  os console,
but using delve debugging in Windows  os console, can not stop at the breakpoint.

**launch.json**
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "st",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "${workspaceRoot}/.",
			"env": {},
			"args": []
		}
	]
}
```

**debug console**
2016/01/27 16:56:50 debugger.go:55: launching process with args: [./debug]
2016/01/27 16:56:51 server.go:301: method Run has wrong number of ins: 1
2016/01/27 16:56:51 server.go:301: method Stop has wrong number of ins: 2
2016/01/27 16:56:51 debugger.go:239: continuing

**Comment by zanven42** [comment]
also recieving the same problem

i have also tried adding 
`"stopOnEntry": true`
to the launch.json

**Comment by jonmurrayncc** [comment]
+1

**Comment by lukehoban** [comment]
Could someone provide a code sample and complete repro steps for this?

I tried on Windows on a few projects, and haven't seen this problem.

Note that the info shown in the debug console is not actually a problem, this is just the info returned by the `--log` flag on Delve to make diagnostics easier.  We'll turn that off soon to avoid making the output ugly, but the results you see above are expected if everything is operating normally.

**Comment by jonmurrayncc** [comment]
Heya,

    So i've tried this now in two different environments. Both of which were a clean install (with a prior install of VS Code, no Go). Same result both times. My environment:

GOPATH=C:\Go\SrcThirdParty
GOROOT=C:\Go\

Most recent version of delve, compiled with Mingw32 as detailed on their site with the GO15VENDOREXPERIMENT set to 1 (SHA-256 hash of dlv.exe in C:\Go\SrcThirdParty\bin\ ends with 090F65D)

Using the sample projects hello world:

package main

import "fmt"
func main() {
    fmt.Println("hello world")
}


with a break at the first print statement, no luck. Output is:

2016/02/02 16:21:14 debugger.go:55: launching process with args: [./debug]
2016/02/02 16:21:14 debugger.go:246: continuing
hello world


My User settings file looks like the below:

// Place your settings in this file to overwrite the default settings
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": false,
    "go.formatTool": "goreturns",
    "go.goroot": "C:\\Go",
    "go.gopath": "C:\\Go\\SrcThirdParty"
}

My Launch.json looks like:

{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "${workspaceRoot}",
			"env": {},
			"args": []
		}
	]
}

Let me know if there is anything further i can do, or if there is a way i can step through delve with your addon. Nb. i've tested delve with gdb-esque commands (ie. i've manually set and stepped through breakpoints on the command line) and that worked fine.

Cheers again for the addon, other than this it is perfect.

**Comment by joegrasse** [comment]
I am running into this issue as well. delve stops at breakpoints on the command line, but vscode-go doesn't. 

If I can provide any additional information to help out let me know.

**Comment by lukehoban** [comment]
Thanks all.  

My guess is that folks who are seeing problems here are hitting the issue in https://github.com/derekparker/delve/pull/386.  If you build Delve from that PR branch, you could validate whether this is indeed the problem.

**Comment by joegrasse** [comment]
That pull request fixed my issue.

**Comment by zanven42** [comment]
i just checked and that pull request also fixed the issue for me, thanks again :+1:

**Comment by lukehoban** [comment]
Great.  https://github.com/derekparker/delve/pull/386 has also now been merged into Delve master.  Closing this issue.
