### ISSUE TITLE
Invalid syntax highlighting for rune and error types

### ISSUE THREAD

**Issue by AlekSi** [Microsoft/vscode-go#1805]
![2018-07-23_22-44-08](https://user-images.githubusercontent.com/11512/43099207-16758b28-8eca-11e8-943f-922fab4839f0.png)

Both `rune` and `error` are basic types.

**Comment by ramya-rao-a** [comment]
How are you not getting errors with that code?
I tried the below:

```
package main

import "fmt"

var (
	_ bool
	_ byte
	_error
	_ rune
	_ string
	_uint
)

func main() {
	fmt.Println("Hello")
}
```

And I get the below errors from `go build`
```
..\hello.go:8: syntax error: unexpected newline, expecting type
..\hello.go:9: syntax error: unexpected _, expecting semicolon, newline, or )
```

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#56515
