### ISSUE TITLE
No highlight from key work like main func。。

### ISSUE THREAD

**Issue by Crazyang** [Microsoft/vscode-go#1807]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1.  after installed， open 。go file
2. no hight light display

<img width="320" alt="screen shot 2018-07-25 at 20 19 13" src="https://user-images.githubusercontent.com/11581027/43200404-0abd7d02-9048-11e8-9418-bc2d3c5fe920.png">
<img width="1131" alt="screen shot 2018-07-25 at 20 19 02" src="https://user-images.githubusercontent.com/11581027/43200406-0b1bf12a-9048-11e8-97de-d9874e06b5c2.png">

**Comment by ramya-rao-a** [comment]
Can you share a small sample code which I can use to get a repro of this issue?
