### ISSUE TITLE
[Feature Request] - Ability to hide/shorten path prefix in debugger

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode-go#1813]
Currently when debugging a project many variables are prefixed with the absolute path of the project. This makes it very difficult to quickly glean information. The only way to actually fit everything in the screen right now is to make the debugger panel take up 70% of my screen which is uncomfortable. I suggest that there should be a workspace setting that will disable this behavior.

**Comment by ramya-rao-a** [comment]
Can you share a screenshot and sample code that I can use to see this issue?

**Comment by nealot** [comment]
After thinking it through I realize that this behavior is how the debugger was designed. As such, I'm going to close this issue.

**Comment by nealot** [comment]
I'm reopening this because it's still frustrating me. Here's a screenshot of what I'm referring to:

![screenshot_20180802_144323](https://user-images.githubusercontent.com/36805289/43604192-28568ff4-9663-11e8-82b9-a7f6bc96f668.png) 

You can reproduce this by running the debugger on this project: https://github.com/magiconair/properties. 

Would it be possible to disable the project path prefix being displayed above? In other words, I would like to hide the "github.com/magiconair/" section of the value.

**Comment by nealot** [comment]
Would the solution described only work for projects under GOPATH? I've been using Exercism and they keep their go files under ~/exercism/go.

**Comment by ramya-rao-a** [comment]
@nealot, @lggomez Does this happen only for variables from external packages or even from the current package?

**Comment by nealot** [comment]
In retrospect, I don't think this is a valid issue as it stems from my lack of understanding of package management. Having gained more experience with Go, I think the current behavior is optimal. As such, I'm going to close this issue.

**Comment by ramya-rao-a** [comment]
Thanks for getting back @nealot and Happy Coding!
