### ISSUE TITLE
Auto Complete showing only Go keywords and standard library stuff

### ISSUE THREAD

**Issue by Southclaws** [Microsoft/vscode-go#1816]
I've recently set up a new macbook and the Go tools are being really problematic:

![image](https://user-images.githubusercontent.com/1636971/43388976-777d1572-93e2-11e8-8a3f-d8089badbb92.png)

![image](https://user-images.githubusercontent.com/1636971/43389266-3545d012-93e3-11e8-840f-3d5f7180bcbd.png)

I'm not really sure what else to do in order to debug this. I'm using all the latest stable stuff as of last week, it's all freshly installed on a new machine.

Code: 1.25.1
Go: go1.10.3 darwin/amd64
vscode-go: 0.6.85

**Comment by ramya-rao-a** [comment]
This looks like https://github.com/mdempsky/gocode/issues/39

Can you run `Go: Install/Update Tools`, select `gocode` to update it and try again?

**Comment by Southclaws** [comment]
That fixed it, thanks!
