### ISSUE TITLE
run/debug test via buttons and states in the "OUTLINE"-window

### ISSUE THREAD

**Issue by rand99** [Microsoft/vscode-go#1820]
It would be great if the Outline-window could get buttons next to the tests (run/debug).
The states (FAIL/PASS) of the tests would also be fantastic!

![screen shot 2018-07-31 at 14 31 31](https://user-images.githubusercontent.com/460223/43460360-ae02f1c2-94d0-11e8-99ec-0f20e1e54ed6.png)

**Comment by ramya-rao-a** [comment]
Though it does sound like a cool idea, this is very much out of the scope of this extension.

The outline view is a UI construct from VS Code. Extensions contribute data to it, but all the functionality is coming from VS Code itself. So if we want actionable buttons next to the items, then that part of the outline view should be made contributable. 

Please go over the [feature requests in VS Code for outline](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+in%3Atitle+outline). One of them might be talking about exactly what you want or close to what you want. You can add your input in one of those issues. If you find none, then you can log a new feature request there.
