### ISSUE TITLE
Add Go to implementation cmd to the Go: Show all Commands for better discoverability

### ISSUE THREAD

**Issue by covrom** [Microsoft/vscode-go#1822]
Proposal. Please, implement a function that shows which interfaces from the current scope are satisfied by the selected function.

**Comment by ramya-rao-a** [comment]
Are you aware of any Go tools that can do this? The Go extension itself is not smart enough to figure out Go ASTs. It relies on a set of [Go Tools](https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on) to give rich language features.

**Comment by ChrisHines** [comment]
The guru implements subcommand can do this.

https://docs.google.com/document/d/1_Y9xCEMj5S-7rv2ooHpZNH15JgRT5iM742gJkw5LtmQ/edit#heading=h.f6hyappclfor

**Comment by ramya-rao-a** [comment]
Thanks for sharing that @ChrisHines!
We have the `Go to implementation` and `Peek Implementation` commands that uses the `guru implements` command. 
@covrom Can you try these commands?

**Comment by vimalk78** [comment]
@ramya-rao-a is it possible to add this command(`Go: Implements`) to `Go : Show All Commands...` right-click sub menu?

i was trying to look for the same, how does vscode invoke `guru implements`.  i could not find it in the list of go commands. I found it in [extension source](https://github.com/Microsoft/vscode-go/blob/78854238a1f2745c6576f734ad1ff3d05c2141ab/src/goImplementations.ts#L61), but had to search in issues to lead to this [issue](https://github.com/Microsoft/vscode-go/issues/1822#issuecomment-412393695) to know how it is to be used.  

if this is not a bad idea, i can try sending a PR

**Comment by vimalk78** [comment]
i tried the following

file : package.json
add a new command
```
    "commands": [
      {
        "command": "go.go.toimpl",
        "title": "Go: Test Go To Implementation",
        "description": "Test Command for testing go.go.toimpl."
      },
```

file : goMain.ts
invoke the `'vscode.executeImplementationProvider'` command in this command handler
```
	ctx.subscriptions.push(vscode.commands.registerCommand('go.go.toimpl', () => {
		let textdoc = vscode.window.activeTextEditor.document;
		let pos = vscode.window.activeTextEditor.selection.active;
		vscode.commands.executeCommand('vscode.executeImplementationProvider',textdoc, pos);
	}));	
```


i am getting the below error in the Debug Console :
```
Object
command:"go.go.toimpl"
title:"Go: Test Go To Implementation"
description:"Test Command for testing go.go.toimpl."
rejected promise not handled within 1 second
```
invoking with `async/await` also results in same error

debugging:
a breakpoint in `goImplementations.ts:44` is not hit when invoked via the above command. but breakpoint is hit if invoked via ` Go -> Go to Implementation` from the vscode menu.

perhaps there is a better way. #needhelp

**Comment by ramya-rao-a** [comment]
Try passing `editor.action.goToImplementation` as command for `vscode.commands.executeCommand`, that should work.

But, we shouldnt add new commands that behind the scenes just calls another command. I was thinking of passing the existing commands for `Go to Implementation`, `Go to symbol in file`  etc to the quick pick control in https://github.com/Microsoft/vscode-go/blob/0.6.89/src/goMain.ts#L357

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.92). Thanks @vimalk78!
