### ISSUE TITLE
Enhance the Generate Interface Stubs command to include user interface to browse packages and select the interface

### ISSUE THREAD

**Issue by covrom** [microsoft/vscode-go#1823]
Proposal. Please, add function "Implement interface" by right click on type name and select interface from current package, current project, current scope, core golang packages, package by name. This function inserts empty functions definitions for implement selected interface.

**Comment by ramya-rao-a** [comment]
We use the [impl](https://github.com/josharian/impl) tool to provide this feature via the command `Go: Generate Interface Stubs`. What is missing is the user interface to select the interface from packages which should be straight forward to implement. PRs are welcome.

Code pointers:
- User interface for browsing packages: https://github.com/Microsoft/vscode-go/blob/master/src/goBrowsePackage.ts
- Once the package is selected, you can use the `go list` command on it to get all the files
- Once a file is selected you can use the `go-outline` tool to get the interfaces

**Comment by stamblerre** [comment]
Future work in this space will be done in `gopls`, rather than in this extension itself. I'm going to close this issue in favor of the upstream one: https://github.com/golang/go/issues/37537.
