### ISSUE TITLE
cant find definition

### ISSUE THREAD

**Issue by Kurt-Shiwz** [Microsoft/vscode-go#1824]
if import some lib like ". github.com/a/b", can't goto definition which define in b.
function is also undefined.
```
// b.go
type GlobalConfig struct {
	Localaddr string
}
func InitGlobalVars(globalconfig *GlobalConfig) error {
}

// main.go
import (
. github.com/a/b
)
// can't goto definition
// InitGlobalVars is undefined
globalconfig := &GlobalConfig{}
InitGlobalVars(globalconfig)
```

**Comment by ramya-rao-a** [comment]
We use [godef](https://github.com/rogpeppe/godef) for getting the definition location. Please try the `godef` tool from the command line and see if you get the desired result. If not, then log a bug at https://github.com/rogpeppe/godef

Another alternative is to add a setting `"go.docsTool": "gogetdoc"`. This will use [gogetdoc](https://github.com/zmb3/gogetdoc) instead.
