### ISSUE TITLE
Problem reporting in editor doesn't work if GOPATH is in a directory called "Workspace"

### ISSUE THREAD

**Issue by Fornax96** [Microsoft/vscode-go#1825]
I store all my code in `~/Documents/Workspace/go`, for months I was wondering why errors were not showing up in my editor. In the "Problems" list it always shows errors in `~/Documents/go`, leaving out the "Workspace" directory. I dug through all the settings to see if I had missed something, but everything checked out.

Today I decided to rename the "Workspace" directory to "workspace", and lo and behold, error reporting started working. Now I have a symbolic link with the upper case W in the same directory pointing to the lower case directory and it seems to have fixed it, but it's a pretty dirty hack.

Steps to Reproduce:

1. Install your GOPATH in a directory called `~/Documents/Workspace/go`
2. Edit some code and make a mistake
3. Notice how it doesn't show a squiggly line under the error and the paths in the Problems window are incorrect
4. Rename `~/Documents/Workspace` to `~/Documents/workspace`
5. Notice how all your problems vanish under the sun

I hope this gets fixed before someone else falls victim to this incredibly frustrating and unproductive issue.

**Comment by ramya-rao-a** [comment]
I did this and I was able to see the errors. I am on a Mac.

<img width="1039" alt="screen shot 2018-08-15 at 6 17 20 pm" src="https://user-images.githubusercontent.com/16890566/44181635-91c70a00-a0b7-11e8-8f0e-c9384a12d07b.png">

What do you see the output channel?
