### ISSUE TITLE
Autocompletion does not work in comments

### ISSUE THREAD

**Issue by dastergon** [Microsoft/vscode-go#1827]
When I write code into the editor, the autocompletion works as expected:
![screen shot 2018-08-06 at 16 53 40](https://user-images.githubusercontent.com/1192342/43724042-64c2016a-9999-11e8-97aa-2bcbf6fed52b.png)

However, when I want to write a comment, let's say for an exported function, the autocompletion does not work in comments. 
![screen shot 2018-08-06 at 16 51 30](https://user-images.githubusercontent.com/1192342/43724046-66cdb184-9999-11e8-9603-5d3c1c516efb.png)

vscode-go version: 0.6.85
VSCode version: 1.25.1
OS: macOS High Sierra 10.13.4

**Comment by ramya-rao-a** [comment]
Completions as you type is disabled in comments by default. You can do one of 2 things
- Hit Ctrl+Space manually to trigger the completion
- Update the `editor.quickSuggestions` to allow the completions in comments.
