### ISSUE TITLE
Install package shows me 'permission denied'

### ISSUE THREAD

**Issue by zongUMR** [Microsoft/vscode-go#1834]
When open a go file, vscode-go notify me to install the packages, but the result is
```
package github.com/mdempsky/gocode: mkdir /User/xxxx/go/src/github.com: permission denied
```
All packages are same result, but if I copy the command and run it in the terminal of the vscode, all is ok. The packages installed successfully.

Is it a issue of the vscode-go?  And how I can resolve it?

Thanks a lot

**Comment by zongUMR** [comment]
`go env`:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zongmeng/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zongmeng/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/HEAD-f2131f6/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/HEAD-f2131f6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/66/h198vsq94gjbzhkj2vbg1rqr0000gn/T/go-build203400249=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
-----
 `go version devel +f2131f6e0c Wed Aug 8 21:37:36 2018 +0000 darwin/amd64`
---
I installed go with brew: `brew install go --HEAD`

**Comment by ramya-rao-a** [comment]
I am not sure why there would be a permissions issue.
Can you try adding the setting `go.toolsGopath` and provide a different path there and then run `Go: Install/Update tools` again? This will install the tools in the path you have provided for `go.toolsGopath` setting
