### ISSUE TITLE
Debugging Auto-completion  feature

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1838]
Creating this issue to continue the investigations with @LiPengfei19820619  from https://github.com/Microsoft/vscode-go/issues/1723#issuecomment-410721126 to reduce noise in the main issue.

**Comment by ramya-rao-a** [comment]
From _@LiPengfei19820619_

@ramya-rao-a I tried your instructions, This is what I got. Could you please give me some advice? thx.

- I Closed all gocode processes with `gocode close`:
![image](https://user-images.githubusercontent.com/14314478/43721109-7ecccbc8-99c4-11e8-89d5-361cd5c57bea.png)

- Run `gocode -s -debug`
![image](https://user-images.githubusercontent.com/14314478/43721227-d3a0c1a4-99c4-11e8-946a-be683d52c881.png)

- use vscode and try for completions
  the gocode output:
`C:\Users\lpf>gocode -s -debug
2018/08/06 22:06:11 Got autocompletion request for 'd:\golang\code\src\chykj\collect-webapi\infrastructure\persistence\path_plan_repo_pg.go'
2018/08/06 22:06:11 Cursor at: 2658
2018/08/06 22:06:11 -------------------------------------------------------
package persistence

import (
        "chykj/collect-webapi/domain/path_plan"
        "database/sql"
        "errors"
        "log"
        "strconv"
)

// PathPlanRepositoryPG 路径规划repository的postgresql实现
type PathPlanRepositoryPG struct {
        db *sql.DB
}

// NewPathPlanRepositoryPG 创建路径规划repository的pg实现
func NewPathPlanRepositoryPG(db *sql.DB) *PathPlanRepositoryPG {
        return &PathPlanRepositoryPG{db: db}
}

// GetAllPoints 加载所有的路径规划点
func (r *PathPlanRepositoryPG) GetAllPoints() []*path_plan.Point {
        points := make([]*path_plan.Point, 0)

        rows, err := r.db.Query("SELECT id,type,stationid,position_x,position_y FROM r_path_plan_point")
        if err != nil {
                return points
        }
        defer rows.Close()

        for rows.Next() {
                var point path_plan.Point
                var id int

                err = rows.Scan(&id, &point.Type, &point.StationID, &point.PositionX, &point.PositionY)
                if err != nil {
                        return points
                }
                point.ID = strconv.Itoa(id)

                points = append(points, &point)
        }

        return points
}

// GetPointByID 根据ID加载人员信息
func (r *PathPlanRepositoryPG) GetPointByID(id string) (*path_plan.Point, error) {
        var point path_plan.Point

        rows, err := r.db.Query("SELECT id,type,stationid,position_x,position_y FROM r_path_plan_point WHERE id=$1", id)
        if err != nil {
                return nil, err
        }
        defer rows.Close()

        for rows.Next() {
                err = rows.Scan(&point.ID, &point.Type, &point.StationID, &point.PositionX, &point.PositionY)
                if err != nil {
                        return nil, err
                }

                return &point, nil
        }

        return nil, errors.New("Path Plan Point Not Found By ID")
}

// AddPoint 增加路径规划点
func (r *PathPlanRepositoryPG) AddPoint(point *path_plan.Point) error {
        if point.StationID != "" {
                return r.db.QueryRow(`INSERT INTO r_path_plan_point(type,stationid,position_x,position_y) VALUES($1,$2,$3,$4) RETURNING id`,
                        point.Type, point.StationID, point.PositionX, point.PositionY).Scan(&point.ID)
        } else {
                return r.db.QueryRow(`INSERT INTO r_path_plan_point(type,stationid,position_x,position_y) VALUES($1,$2,$3,$4) RETURNING id`,
                        point.Type, point.StationID, point.PositionX, point.PositionY).Scan(&point.ID)
        }
}

// UpdatePoint 更新路径规划点
func (r *PathPlanRepositoryPG) UpdatePoint(point *path_plan.Point) error {
        _, err := r.db.Exec(`UPDATE r_path_plan_point SET type=$2,stationid=$3,position_x=$4,position_y=$5 WHERE id=$1`,
                point.ID, point.Type, point.StationID, point.PositionX, point.PositionY)

        return err
}

// DeletePoint 删除路径规划点
func (r *PathPlanRepositoryPG) DeletePoint(id string) error {
        log.Println("delete point, id: ", id)
        _, err := r.db.Exec(`DELETE FROM r_path_plan_point WHERE id=$1`, id)
l#
        return err
}
2018/08/06 22:06:11 -------------------------------------------------------
2018/08/06 22:06:11 Elapsed duration: 39.0022ms
2018/08/06 22:06:11 Offset: 0
2018/08/06 22:06:11 Number of candidates found: 2
2018/08/06 22:06:11 Candidates are:
2018/08/06 22:06:11   func len(v Type) int
2018/08/06 22:06:11   package log
2018/08/06 22:06:11 =======================================================
2018/08/06 22:06:15 Got autocompletion request for 'd:\golang\code\src\chykj\collect-webapi\infrastructure\persistence\path_plan_repo_pg.go'
2018/08/06 22:06:15 Cursor at: 2661
2018/08/06 22:06:15 -------------------------------------------------------
package persistence

import (
        "chykj/collect-webapi/domain/path_plan"
        "database/sql"
        "errors"
        "log"
        "strconv"
)

// PathPlanRepositoryPG 路径规划repository的postgresql实现
type PathPlanRepositoryPG struct {
        db *sql.DB
}

// NewPathPlanRepositoryPG 创建路径规划repository的pg实现
func NewPathPlanRepositoryPG(db *sql.DB) *PathPlanRepositoryPG {
        return &PathPlanRepositoryPG{db: db}
}

// GetAllPoints 加载所有的路径规划点
func (r *PathPlanRepositoryPG) GetAllPoints() []*path_plan.Point {
        points := make([]*path_plan.Point, 0)

        rows, err := r.db.Query("SELECT id,type,stationid,position_x,position_y FROM r_path_plan_point")
        if err != nil {
                return points
        }
        defer rows.Close()

        for rows.Next() {
                var point path_plan.Point
                var id int

                err = rows.Scan(&id, &point.Type, &point.StationID, &point.PositionX, &point.PositionY)
                if err != nil {
                        return points
                }
                point.ID = strconv.Itoa(id)

                points = append(points, &point)
        }

        return points
}

// GetPointByID 根据ID加载人员信息
func (r *PathPlanRepositoryPG) GetPointByID(id string) (*path_plan.Point, error) {
        var point path_plan.Point

        rows, err := r.db.Query("SELECT id,type,stationid,position_x,position_y FROM r_path_plan_point WHERE id=$1", id)
        if err != nil {
                return nil, err
        }
        defer rows.Close()

        for rows.Next() {
                err = rows.Scan(&point.ID, &point.Type, &point.StationID, &point.PositionX, &point.PositionY)
                if err != nil {
                        return nil, err
                }

                return &point, nil
        }

        return nil, errors.New("Path Plan Point Not Found By ID")
}

// AddPoint 增加路径规划点
func (r *PathPlanRepositoryPG) AddPoint(point *path_plan.Point) error {
        if point.StationID != "" {
                return r.db.QueryRow(`INSERT INTO r_path_plan_point(type,stationid,position_x,position_y) VALUES($1,$2,$3,$4) RETURNING id`,
                        point.Type, point.StationID, point.PositionX, point.PositionY).Scan(&point.ID)
        } else {
                return r.db.QueryRow(`INSERT INTO r_path_plan_point(type,stationid,position_x,position_y) VALUES($1,$2,$3,$4) RETURNING id`,
                        point.Type, point.StationID, point.PositionX, point.PositionY).Scan(&point.ID)
        }
}

// UpdatePoint 更新路径规划点
func (r *PathPlanRepositoryPG) UpdatePoint(point *path_plan.Point) error {
        _, err := r.db.Exec(`UPDATE r_path_plan_point SET type=$2,stationid=$3,position_x=$4,position_y=$5 WHERE id=$1`,
                point.ID, point.Type, point.StationID, point.PositionX, point.PositionY)

        return err
}

// DeletePoint 删除路径规划点
func (r *PathPlanRepositoryPG) DeletePoint(id string) error {
        log.Println("delete point, id: ", id)
        _, err := r.db.Exec(`DELETE FROM r_path_plan_point WHERE id=$1`, id)
log.#
        return err
}
2018/08/06 22:06:15 -------------------------------------------------------
2018/08/06 22:06:15 Error parsing input file (outer block):
2018/08/06 22:06:15  d:\golang\code\src\chykj\collect-webapi\infrastructure\persistence\path_plan_repo_pg.go:92:5: expected selector or type assertio
, found ';'
2018/08/06 22:06:15  d:\golang\code\src\chykj\collect-webapi\infrastructure\persistence\path_plan_repo_pg.go:93:2: expected ';', found 'return'
2018/08/06 22:06:15 Elapsed duration: 38.0022ms
2018/08/06 22:06:15 Offset: 0
2018/08/06 22:06:15 Number of candidates found: 24
2018/08/06 22:06:15 Candidates are:
2018/08/06 22:06:15   const LUTC untyped int
2018/08/06 22:06:15   const Ldate untyped int
2018/08/06 22:06:15   const Llongfile untyped int
2018/08/06 22:06:15   const Lmicroseconds untyped int
2018/08/06 22:06:15   const Lshortfile untyped int
2018/08/06 22:06:15   const LstdFlags untyped int
2018/08/06 22:06:15   const Ltime untyped int
2018/08/06 22:06:15   func Fatal(v ...interface{})
2018/08/06 22:06:15   func Fatalf(format string, v ...interface{})
2018/08/06 22:06:15   func Fatalln(v ...interface{})
2018/08/06 22:06:15   func Flags() int
2018/08/06 22:06:15   func New(out io.Writer, prefix string, flag int) *log.Logger
2018/08/06 22:06:15   func Output(calldepth int, s string) error
2018/08/06 22:06:15   func Panic(v ...interface{})
2018/08/06 22:06:15   func Panicf(format string, v ...interface{})
2018/08/06 22:06:15   func Panicln(v ...interface{})
2018/08/06 22:06:15   func Prefix() string
2018/08/06 22:06:15   func Print(v ...interface{})
2018/08/06 22:06:15   func Printf(format string, v ...interface{})
2018/08/06 22:06:15   func Println(v ...interface{})
2018/08/06 22:06:15   func SetFlags(flag int)
2018/08/06 22:06:15   func SetOutput(w io.Writer)
2018/08/06 22:06:15   func SetPrefix(prefix string)
2018/08/06 22:06:15   type Logger struct
2018/08/06 22:06:15 =======================================================
`

**Comment by ramya-rao-a** [comment]
@LiPengfei19820619 As per the output you have shared `gocode` is acting as expected. Looks like when VS Code calls it, it never returns anything and the process never closes. Please follow the steps in [Building and Debugging the extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) to have a local set up of the extension running. Add breakpoints at https://github.com/Microsoft/vscode-go/blob/0.6.85/src/goSuggest.ts#L163, https://github.com/Microsoft/vscode-go/blob/0.6.85/src/goSuggest.ts#L167 and https://github.com/Microsoft/vscode-go/blob/0.6.85/src/goSuggest.ts#L175 and see if the process that is spawned of gocode ever returns any data.

**Comment by ramya-rao-a** [comment]
From _@LiPengfei19820619_ 

@ramya-rao-a  This is my debugging process, Would you please give me a hand, thanks.
![image](https://user-images.githubusercontent.com/14314478/43966300-150d02ba-9cf4-11e8-936c-b35cff09bb04.png)
![debug2](https://user-images.githubusercontent.com/14314478/43966332-32851166-9cf4-11e8-8e28-aadb223468e5.png)
![debug3](https://user-images.githubusercontent.com/14314478/43966333-32fca6ea-9cf4-11e8-8fda-9891bcd45daa.PNG)
![debug4](https://user-images.githubusercontent.com/14314478/43966334-332ed5d4-9cf4-11e8-912b-a887f79b9018.PNG)
![debug5](https://user-images.githubusercontent.com/14314478/43966335-33a6b540-9cf4-11e8-9f7b-12a39e89f072.PNG)
![debug6](https://user-images.githubusercontent.com/14314478/43966336-340d5822-9cf4-11e8-8125-a22f443c0dd0.PNG)
![debug7](https://user-images.githubusercontent.com/14314478/43966337-3440e00c-9cf4-11e8-9b72-415bf74394c0.PNG)
![debug8](https://user-images.githubusercontent.com/14314478/43966338-348715cc-9cf4-11e8-82b0-6b25104e6d9b.PNG)
![debug9](https://user-images.githubusercontent.com/14314478/43966339-34c4af72-9cf4-11e8-9589-3574e2e1495f.PNG)

**Comment by ramya-rao-a** [comment]
@LiPengfei19820619 Your breakpoints are off by 1 at almost all places.
Please add them in the line AFTER `p.on('close'` and `p.on('error'`

**Comment by LiPengfei19820619** [comment]
@ramya-rao-a HI, I added breakpoints in the line after p.on('error', err => {  and p.on('close', code => {.

But they are not triggered while debugging.

Breakpoints in the line before p.on('error', err => { can be triggered.

Thanks.

**Comment by ramya-rao-a** [comment]
@LiPengfei19820619 Can you kill any currently running `gocode` process and try again?

**Comment by ramya-rao-a** [comment]
Closing this issue as we haven't heard back from @LiPengfei19820619 in a while
