### ISSUE TITLE
Need to make debugging aware of env settings

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode-go#1839]
macOS 10.13.6
Golang 1.11 beta 3
VSCode Insider 1.26

Hello, I tweeted that I would like to be able to set the environment variable to values such as:
GOARCH=386 GOOS=darwin CGO_ENABLED=1 
and have VSCode use them for debugging purposes. 

@ramya-rao-a pointed out that I could use the "go.toolsEnvVars" setting to pass the vars through, but that debugging doesn't use them and to post an issue here.

**Comment by ramya-rao-a** [comment]
This is now available in the latest update (0.6.86) to the Go extension.

**Comment by carlca** [comment]
Thanks, Ramya! Excellent work as always!
