### ISSUE TITLE
Error displayed when debug process isn't running: "There is already a debug configuration "launch" running."

### ISSUE THREAD

**Issue by dgiridharan** [Microsoft/vscode-go#1840]
Steps to reporduce:

1) Create a main function with compile error:
```
package main

import (
	"fmt"
)

func main() {
	// compile error
	oisjdflsdfkj

	fmt.Printf("Hello World")
}
```
2) Create a new Configuration to launch this file:
```
    {
      "name": "Launch file",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "program": "path to the go main function file"
    },
```
3) Launch the debug configuration give you an error:
          "Failed to continue: Check the debug console for deatils."
4) Click cancel on the error dialog
5) Remove the compile error:
```
package main

import (
	"fmt"
)

func main() {
	// Compile error removed

	fmt.Printf("Hello World")
}
```
6) Save and launch the same debug configuration gives you an error:
There is already a debug configuration "Launch file" running.

NOTE:
If I change the launch file configuration name and run the new configuration then I can run it. After it's run, there is a new entry in the call stack with an orphaned process running. I can't stop it or remove it from stopping.

**Comment by dgiridharan** [comment]
This is really really bad user experience.

Is it possible to fix this issue soon? This happens any time I have an error for launching a debug configuration and I attempt to relaunch after fixing the issue.

It would be fine if there's a work around for this as well (for the time being).

Thanks again, I really appreciate it!

**Comment by tianyouhui** [comment]
Also, when I updated vscode to 1.25.1 (or even lower 1.25?), the vscode and vscode-go becomes very stutter, and cpu runs heavily ... 100%

**Comment by ramya-rao-a** [comment]
Please see https://github.com/Microsoft/vscode-go/issues/1814#issuecomment-411920595

I'll be releasing an update in a day or two.

Thanks for your patience.

**Comment by dgiridharan** [comment]
@ramya-rao-a - Thanks lot! That was really fast.
