### ISSUE TITLE
Separate build-tags and test-tags

### ISSUE THREAD

**Issue by johan-lejdung** [Microsoft/vscode-go#1842]
Hi!

I have come across a use-case that is not covered by this extension, a use-case that I cannot imagine being alone with.

For many of my Go projects I have integration tests, these are tests that spin up docker containers and take longer to run. I also like to test my code on save.. To let me have the best of two worlds, fast running tests on save and longer integration tests on demand, I tag my integration tests with:
```
// +build integration
```

This stops the file from building unless I supply the tag with the build or test command.

Unfortunately this also disables the linting and syntax checks on the file, making it really hard to verify the code is working.

**Atom** solves this by having an option for build tags for build/install commands and a command for build tags for tests. I am not finding it possible to do a similar configuration with Visual Studio Code. All i find is `go.buildTags` which affects both build and save.

Are there any plans to fix that?

**Comment by ramya-rao-a** [comment]
When you say you'd like to test your code on save, are you referring to the linter and syntax checks or actual tests that are run?

**Comment by johan-lejdung** [comment]
Well both of it, but I am referring to actual tests being run.

As long as the tests are simple unit tests they run fast enough, but of course they only run if the linter and syntax checks pass :)

**Comment by ramya-rao-a** [comment]
I would suggest the below:
- Add the tag `!fastRunning` on the files that have the integration tests
- Add `"go.testFlags": ["-tags", "fastRunning"]` to your settings
At this point, linter and syntax checks will run on all files, test on save will not run on the integration tests.

Set up a test task to run just all tests. Tasks have no knowledge of the go extension and so no knowldge of its settings.
- Run command `Tasks: Configure Task` -> `Create tasks.json file from template` -> Choose "Others" from the template options
- Update the command to `go test <your package name>`. 
- Run command `Tasks: Run Task` and then choose your task to run all the tests on demand.

See https://code.visualstudio.com/Docs/editor/tasks to learn more about tasks

**Comment by ramya-rao-a** [comment]
Oh wait, my bad. The `go.testFlags` get used when compiling so you wont get the syntax checks. This is because `go test` is used to compile test files and `go build` is used to compile non test files.

You can use a small variation of the above.

- Add the `integration` tag like you first described
- Have the task run the build and/or run tests using the tag

You can now run the task on demand every once in a while to get feedback on errors or to run the tests themselves

**Comment by johan-lejdung** [comment]
But then we are back full-circle. I still wont have linting and syntax checks on my test files unless I run it manually, which I already do today - task or not -.

I feel like adding proper support for this would be great, especially considering that both Atom and GoLand covers this use-case.

**Comment by ramya-rao-a** [comment]
Adding proper support is definitely not off the table, I was just brainstorming ideas before we get there. We can definitely add a new setting called `go.testTags` to be used for when we run the tests and not for when compile them. Would that serve this scenario?

**Comment by johan-lejdung** [comment]
Much appreciated, for trying to help out and find alternative solutions!

Yeah that would be super, if you are stretched for time I could look into it this weekend.

**Comment by johan-lejdung** [comment]
Thanks! If I havent submitted anything by the end of the weekend you can
consider me MIA hehe

**Comment by ramya-rao-a** [comment]
No worries, take your time.

**Comment by johan-lejdung** [comment]
@ramya-rao-a is this considered closed already or is it only after a release?

**Comment by ramya-rao-a** [comment]
Yes, this can be considered as closed. 

For people who want to try this, you can use the [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension until we release an update.

**Comment by ramya-rao-a** [comment]
The new `go.testTags` setting is now available for use in the latest update to this extension (0.6.90)
