### ISSUE TITLE
Adding a new breakpoint in different Go Routine after starting of the run fails

### ISSUE THREAD

**Issue by viggyprabhu** [Microsoft/vscode-go#1843]
Steps to Reproduce:

1. Run a program with multiple GoRoutines, putting a debug breakpoint in one of the GoRoutines
2. While the program is running, add a new breakpoint in different go routine which should run after the current breakpoint.
3. When you reach the Breakpoint, if you want to go to next app, please F10.
4. I get an error saying "Failed to next" and execution stops.

**Comment by ramya-rao-a** [comment]
I havent worked with goroutines before. Can you provide a code sample and repro steps?
@lggomez Have you seen something like this?

**Comment by lggomez** [comment]
No, I will try to reproduce it

@viggyprabhu if you can share a reduced repro code it will be very helpful. Additionally, if you installed the latest version of the extension the "Failed to next" message should include the delve error, making diagnostics faster

**Comment by ramya-rao-a** [comment]
@viggyprabhu We havent heard back from you on the possibly reduced repro code. Also, we have had a lot improvements to the debugging side of things in the extension in the past 6 months. 

Closing this issue. If you still see this problem, please log a new issue with a sample code
