### ISSUE TITLE
Autocompletion for symbols from non imported packages without typing package name

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-go#1846]
hi guys, pycharm have a very interesting feature:

![go 1](https://user-images.githubusercontent.com/7406597/44109144-f4b48bbe-a004-11e8-8530-b298d09348ce.png)

Very helpful in developing, there is any plans for this feature?

**Comment by ramya-rao-a** [comment]
We do show completions for symbols from unimported packages, but we need you to type the package name first.

We show completes for unimported pacakges names themselves if you add `"go.autocompleteUnimportedPackages": true` to your settings.

But typing a symbol name and then showing all matches with packages is not something we can do given the constraints of the Go tools we use.

But an alternative is the Workspace symbol search. Run the command `Go to Symbol in Workspace` or Ctr+# or Cmd+# you should be able to type just the symbol name (without package name) and the search will give you the same results as you've shown above.

If you want to include std lib in such searches, add ` "go.gotoSymbol.includeGoroot": true` to your setting

**Comment by RokkerRuslan** [comment]
**"go.autocompleteUnimportedPackages": true** and **"go.gotoSymbol.includeGoroot": true** is not working as PyCharm, it's a pity, maybe in future)

**Comment by ramya-rao-a** [comment]
One way we can do this is to include workspace symbol search in the completion results. It may have some perf issues, but is definitely do-able.

**Comment by ramya-rao-a** [comment]
@RokkerRuslan Is the scenario here that you know the symbol name but dont know the package name or that you just dont want to type the package name?

**Comment by stamblerre** [comment]
@heschik: Is this something that `gopls` could support?

**Comment by heschik** [comment]
Sure, doing it for packages that have been loaded would be relatively easy. I don't think we'd want to do it for random packages in the module cache.

**Comment by ramya-rao-a** [comment]
There is no planned work to augment the out of the box auto-completion feature, and all future improvements will be done via the auto-completion feature from the language server.

@stamblerre Can we have an upstream feature request logged for this for `gopls`?

**Comment by stamblerre** [comment]
Yep, just filed https://github.com/golang/go/issues/38528. I'll close the issue here.
