### ISSUE TITLE
GOPATH not recognized when debugging

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-go#185]
_From @mvpmvh on January 28, 2016 5:41_

My $GOPATH is set and exported just fine. The go plugin even recognizes the path when viewing the Current GOPATH within the editor; however, as soon as I attempt to debug any go files, there is an error that the GOPATH is not set. Note that the GOROOT is located just fine.

![screenshot from 2016-01-27 23 37 11](https://cloud.githubusercontent.com/assets/5186821/12636092/6ddac17c-c54f-11e5-8c3a-a4cd32620324.png)

_Copied from original issue: Microsoft/vscode#2477_

**Comment by lukehoban** [comment]
@mvpmvh How are you configuring the GOPATH?  Are you overriding it in your VS Code workspace settings "go.gopath"?  Or do you have it configured in the environment where you launched `code` from?

**Comment by mvpmvh** [comment]
@lukehoban  - Both. I set an environment variable for my GOPATH, but when the editor didn't recognize that, I set the value in the settings "go.path". That did not work either for the debuggerr,  but the Current GOPath was set just fine. Couldn't identify the reasoning behind this. For w/e reason, I was able to get the debugger to work after uninstalling, re-installing and re-exporting my GOROOT/GOPATH. I have no idea what changed, but everything is working now.

**Comment by ctaggart** [comment]
I am able to set the path with the environment variable, but the `go.gopath` workspace setting does not work for me in 0.6.38.

This works `cd ~/go/nut; GOPATH=/Users/cameron/go/nut code .`.
This does not:
```
Camerons-iMac:nut cameron$ cat .vscode/settings.json 
// Place your settings in this file to overwrite default and user settings.
{
    "go.gopath": "/Users/cameron/go/nut"
}Camerons-iMac:nut cameron$ unset GOPATH; code .
```
![image](https://cloud.githubusercontent.com/assets/80104/14903576/c4439f6c-0d56-11e6-866a-8024f938a7f9.png)

**Comment by ctaggart** [comment]
There are 3 sources for GOPATH:

1. export in `~/.bash_profile` such as `export GOPATH=~/go`
2. environment variable such as ```GOPATH=`pwd` code .```
3. `go.gopath` workspace settings `.vscode/settings.json`

Currently, if 1 is used, it wins even if 2 is used. The problems appears to be that VSCode load is sourcing `~/.bash_profile`. If it didn't do that, I think the setting of GOPATH would make sense.

**Comment by mikepc** [comment]
In my version of VSCode on Mac OS 10.9.5 debugging simply does not use any of these, it simply produces the above error message. I've tried a number of different combinations, including just settings.json, just bash_profile, even just .bashrc setting it in the command line.  

It is important to note that while editing my GOPATH is being recognized by the main app, but when the debugger starts with no set GOPATH, and the GOROOT it refers to is not the GOROOT I'm setting (anywhere I set it it, it points to /usr/local/Cellar/go/1.6.2/libexec, completely ignoring my setting of GOROOT to /usr/local

**Comment by shakahub** [comment]
+1

**Comment by wilcosheh** [comment]
same problem

**Comment by ramya-rao-a** [comment]
@mikepc See https://github.com/Microsoft/vscode-go/issues/708#issuecomment-271119503 Setting GOPATH in `~/.profile` should help.

Note to rest:

- The debugger in the Go extension cannot read GOPATH from the user/workspace settings. You need to specifically set the GOPATH in the `env` property in the lanuch.json

- If your GOPATH was set as env variable outside of VS Code and you didnt have to set GOPATH in user/workspace settings, then debugger can read the GOPATH set as env variable.

Closing this issue for now as there is no actionable item
