### ISSUE TITLE
How to see global variables in visual studio for golang while debugging?

### ISSUE THREAD

**Issue by Sai-Venky** [Microsoft/vscode-go#1854]
While debugging in GoLang using delve only the local variables are shown. Cant see all the global variables. Is there any settings change to see the list of all variables
<img width="1111" alt="screen shot 2018-08-17 at 11 12 09 am" src="https://user-images.githubusercontent.com/22170596/44249779-15473f00-a20f-11e8-8f37-7ff01d3b677f.png">
Here a is not showing Even when I hover mouse over it its value is not coming.

I also added this setting :- 
"go.delveConfig": {
        "useApiV1": false,
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 2,
            "maxStringLen": 64,
            "maxArrayValues": 64,
            "maxStructFields": -1
        }
    }
Still not coming

**Comment by ramya-rao-a** [comment]
Displaying global variables is not supported at the moment, but this should be do-able

Delve supports[ listing of global variables across all packages](https://github.com/derekparker/delve/blob/c8fcc3c5b21fb0fa314acdf7578dcc6a62e505be/Documentation/api/ClientHowto.md#looking-into-variables). We can provide the current package name in a regex and should be able to get the global variables.

**Comment by ramya-rao-a** [comment]
@Sai-Venky I have the changes required for this feature in a branch. Can you try it out and give some feedback on how it works?

- Download https://github.com/Microsoft/vscode-go/blob/globals/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` or `code-insiders --install-extension Go-latest.vsix` based on whether you are using Stable or the Insiders
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by ramya-rao-a** [comment]
cc @lggomez

**Comment by Sai-Venky** [comment]
Its working now .Thanks
