### ISSUE TITLE
Codelens: guru processes saturate resources

### ISSUE THREAD

**Issue by lggomez** [Microsoft/vscode-go#1856]
I used to have some slowdowns from time to time but now with VS Code 1.26 (both original and hotfix update) it renders my machine unresponsive

<img width="913" alt="screen shot 2018-08-17 at 13 42 57" src="https://user-images.githubusercontent.com/6326271/44278660-108d8580-a225-11e8-94aa-219fd1847e84.png">

The workaround for now is disabling references codelens:

```json
    "go.enableCodeLens": {
        "references": false,
        "runtest": true,
    }
```

I don´t have a repro code I can share, but this happens shortly after triggering just a couple of codelenses in a medium sized project (30-50 KLOC with vendoring included)

**Comment by ramya-rao-a** [comment]
I don't believe 1.26 has anything to do with this. Can you check with 1.25?

**Comment by chrisduong** [comment]
Hi,

I faced the same issue. I went back to 1.25.1. The problem is fixed.

**Comment by ramya-rao-a** [comment]
> I faced the same issue. I went back to 1.25.1. The problem is fixed

We had an electron update in 1.26. That might change how the spawned processes behave in certain conditions. No solutions in mind yet. Will have to keep digging

**Comment by ramya-rao-a** [comment]
@napalm684 Can you also check if going back to 1.25.1 also solves the issue? Check that you are using the same version of the Go extension and the same Go code base to test in both versions of VS Code. This will help in narrowing down whether the issue is with the latest update to VS Code or the Go extension

**Comment by napalm684** [comment]
@ramya-rao-a  Just downgraded to 1.25.1 and it does appear that the system does not spin up multiple instances of the guru process.  I am just seeing a single instance with a small CPU spike, then it closes out.  The delay in VSCode is pretty much imperceptible.  Plugin is 0.6.88 by the way.

**Comment by ramya-rao-a** [comment]
Thanks @napalm684. Can you also share what OS you are on?

**Comment by ramya-rao-a** [comment]
Can you try the latest [Insiders](https://code.visualstudio.com/insiders) ?

**Comment by chadit** [comment]
same issue for me,  Manjaro (latest) full OS (no virtual machine), VS code 1.27.2

**Comment by cristim** [comment]
I also notice this and it happens after each significant change in the editor. I see dozens of guru processes that consume 100% of all my CPU cores for a minute or so and the vscode editor is pretty much unusable for that period of time.

Maybe those could be executed with a lower `nice` priority so at least I can type code?

**Comment by cwoodfield** [comment]
I'm seeing the same issue on version 1.30.1. It seems the issue is more about memory saturation vs CPU - I counted 28 guru processes, each with a RSIZE between 200-300MBytes. On a 8GB Macbook running other apps (particularly Docker Desktop), this gummed things up but good for about 5-10 minutes.

**Comment by ramya-rao-a** [comment]
I would suggest to disable the codelens for references if these perf issues with guru are seen.

Now that we have the Go team working on a language server, using that in the future should resolve the perf issues we have with using guru
