### ISSUE TITLE
go to definition: ignoring build constraints

### ISSUE THREAD

**Issue by illenial** [Microsoft/vscode-go#1857]
It refers me to `plugin_stubs.go` instead of `plugin_dlopen.go`. Should Vscode not be aware of build constraints? Or is this happening only to me?

![output](https://user-images.githubusercontent.com/41230766/44297623-4db54e80-a2dd-11e8-9782-f34e39cec4c1.gif)

**Comment by ramya-rao-a** [comment]
We use `godef` for this feature and it doesnt support the use of build tags.
`gogetdoc` on the other hand does support build tags.
Add `"go.docsTool": "gogetdoc"` in your settings
