### ISSUE TITLE
Can't autocomplete symbol name after updating vscode and vscode-go

### ISSUE THREAD

**Issue by Hawken94** [Microsoft/vscode-go#1858]
VS Code will not show the existed symbol when I type on the place "a ...interface{}" which happened.
![image](https://user-images.githubusercontent.com/12959892/44297709-a3532080-a308-11e8-80fc-44f382d3d002.png)

But after delete "a ...interface{}", save the file and the shadow disappeared. It works.
![image](https://user-images.githubusercontent.com/12959892/44297750-82d79600-a309-11e8-85e6-2ea13fcd151a.png)

![image](https://user-images.githubusercontent.com/12959892/44297772-bfa38d00-a309-11e8-88f3-2e567db03b4f.png)

vscode: 1.26.1
vscode-go:0.6.88
go:1.10.3
os: macOS 10.13.6
gocode: mdempsky/gocode 

other setting:
``` json
{
    "go.useCodeSnippetsOnFunctionSuggest": true
}
```

**Comment by ramya-rao-a** [comment]
This is intentional. Since we want "tab" key to move through the snippet and not accept suggestions in snippet mode, suggestions are disabled by default in snippet mode.

To fix this, please disable the setting "editor.suggest.snippetsPreventQuickSuggestions"
