### ISSUE TITLE
Unverified breakpoint

### ISSUE THREAD

**Issue by wopol** [Microsoft/vscode-go#1859]
I have a problem with debugging, i suppose so the reason is my project structure. Sometimes when i create new package, i create inside "cmd" directory where is my main file(attached file). In this case i can add breakpoints only in my main fail, because each breakpoints in other file is unverified. I get error: "Error on CreateBreakpoint: could not find ...src/location/scanner/monitor.go:34". Summarizing, main.go file is in main package, transport and monitor file is in scanner package. Is it possible to debugging project with structure lik this ? When i move monitor.go, transport.go and main.go to one main package, all works great.

<img width="1036" alt="zrzut ekranu 2018-08-18 o 22 41 31" src="https://user-images.githubusercontent.com/9054681/44303104-50915d00-a338-11e8-8e45-34cbfc3c1c16.png">

<img width="298" alt="zrzut ekranu 2018-08-18 o 22 38 03" src="https://user-images.githubusercontent.com/9054681/44303096-41121400-a338-11e8-9843-a038a3c1c447.png">

**Comment by qzyse2017** [comment]
The cause of the error can also be verified by using directly delve to set breakpoints and see whether it can perform correctly

**Comment by wopol** [comment]
Thank you for the response. I think that you have right and this is bug in delve debugger. I have last version delve (release 3 days ago) and still the same case. I also tried debugging directly in delve debugger and i got the same error "Command failed: could not find /Users/wojciechpolus/go-workspace/src/location/scanner/transport.go:43"
