### ISSUE TITLE
go.buildOnSave = "workspace" is building too much

### ISSUE THREAD

**Issue by EmpireJones** [Microsoft/vscode-go#1861]
Steps to Reproduce:

1. `go get` a library with conditional dependencies (those which are only needed if you use a particular sub-package), for example, I believe cloud.google.com/go fits this criteria
2. set go.buildOnSave setting to "workspace"

This ends up building all packages, even those which you have no need for. This results in numerous errors regarding "cannot find package", because you don't have all conditional dependencies.

Ideally only relevant files should be built.

---

Would it make sense to add a new buildOnSave option (or similar) to identify the applicable root folder of your project, and then only build packages outside of that when referenced from the code?

**Comment by ramya-rao-a** [comment]
I am not aware of what conditional dependencies are. Can you provide a small code sample that I can try this on?

> Would it make sense to add a new buildOnSave option (or similar) to identify the applicable root folder of your project, and then only build packages outside of that when referenced from the code?

If there is already a root folder you know that you want to build packages from, why not open just that in VS Code instead of its ancestor?

**Comment by EmpireJones** [comment]
Good point, previously I had my main package outside of the 'root' directory that I was targeting, but now that all of my code is under the same domain-named folder, that solution seems to work!

To illustrate what I was referring to, I made a basic project which you can check out with:
`git clone --recurse-submodules git@github.com:EmpireJones/issue_example.git`

All that I have in there is an empty main function, plus the tools that vscode-go or other addons requested to install.

When the "example" repo folder is selected as the workspace folder root (and set as the go.gopath), I get errors about not being able to find:
golang.org/x/html
golang.org/x/net/html/atom
golang.org/x/net/websocket

The empty main function isn't using these packages, so they are not built when a normal build is performed (e.g. via the ./build script).

**Comment by ramya-rao-a** [comment]
I see the errors you are talking about.

The one alternative I thought of was to use `go build ./...`. But that doesnt fare better either. I get the same error.

I would say that the go build tool should be smart enough to skip the conditional dependencies.

There isnt much we can do from the editor's perspective.

If you have any ideas, we can look into it, else I would close this issue.

**Comment by EmpireJones** [comment]
I don't think it's a an issue that go build is having the error, as vscode-go is specifically telling it to build those packages. For example:
```

/home/kevin/repos/example/src>Finished running tool: /usr/local/go/bin/go build -i -o /tmp/go-code-check.180164698 golang.org/x/tools/cmd/html2article
/home/kevin/repos/example/src/golang.org/x/tools/cmd/html2article/conv.go:21: cannot find package "golang.org/x/net/html" in any of:
/home/kevin/repos/example/src/golang.org/x/tools/cmd/html2article/conv.go:22: cannot find package "golang.org/x/net/html/atom" in any of:
```
I think the issue is more that vscode-go is building 'full projects' the same way as go build intended. I think the typical way to build a project is by specifying an entrypoint file (e.g. main.go).

Based on this, I think one solution might be to be able to set the entrypoint file(s) for the tool to build, which would result in a call such as:
`go build -o /tmp/go-code-check.180164698 ./src/example.com/cmd/app/main.go`

That'd build a lot faster too! The downside to that solution would be that it wouldn't build new packages that you were working on, which your entrypoints weren't yet (directly or indirectly) using. To work around this, it could build entrypoint files + current package (if triggered via a save).

**Comment by ramya-rao-a** [comment]
> Based on this, I think one solution might be to be able to set the entrypoint file(s) for the tool to build

Doesnt the default value for `buildOnSave` which is `package` do just that? It builds the package to which the current file you are editing belongs to.

Is it a common scenario that a file in one package is being edited, but you want to build another package?

**Comment by EmpireJones** [comment]
The use case is that I'll be making code changes to package A, and I update package B to properly use those changes, but I won't find out that it also breaks package C too until I do a full build via a script (and it won't show up in the nice VSCode Problems UI).

This is one improvement that I was excited to get out of VSCode when switching from Atom. If we can't improve this build strategy, I think that selecting a narrower root as you described in https://github.com/Microsoft/vscode-go/issues/1861#issuecomment-414877862 solves most of the issues (although it takes a few seconds to build and show output currently, and doesn't let me explore packages from libraries as easily).

**Comment by ramya-rao-a** [comment]
In that case, I would suggest to use [tasks](https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks)

You can have a `tasks.json` file for each project where you can specify a command to run a particular project. If set as a build task, then there is a keyboard shortcut to invoke it.

**Comment by EmpireJones** [comment]
Thanks, I'll take a look at that.
Thanks for your time in working through this with me!
