### ISSUE TITLE
Breadcrumb dropdown omits items unresolved in current file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1864]
_From @harikb on August 20, 2018 22:23_

 

- VSCode Version: 1.26.1
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Create two files in same directory, same package. Declare a new type and a method on it.
2. Move the definition of the type from one file to another. Only the file that resolves the declaration will have the correct breadcrumb

Does this issue occur when all extensions are disabled?: N/A

![bc1](https://user-images.githubusercontent.com/952886/44369823-98c19400-a48c-11e8-8317-48b5cf70bf1a.png)
![bc2](https://user-images.githubusercontent.com/952886/44369830-9bbc8480-a48c-11e8-9e39-625b32682a3a.png)

_Copied from original issue: Microsoft/vscode#56854_

**Comment by ramya-rao-a** [comment]
_From @jrieken on August 21, 2018 15:46_

Seems to be a problem with the go extension not providing elements

**Comment by ramya-rao-a** [comment]
@harikb I am able to see the breadcrumbs in both files

![image](https://user-images.githubusercontent.com/16890566/44438449-ef55cd80-a573-11e8-997e-b7dee40bd061.png)

Am I missing anything in my example?

**Comment by Hawken94** [comment]
@ramya-rao-a I am able to see the breadcrumbs in both files, too.

**Comment by harikb** [comment]
Thanks for looking in to this. It may be related to the experimental languageServer option.

The problem disappears if I turn of this setting

    "go.useLanguageServer": true,

How can I help debug further? I was experimenting with language server option based on our previous exchange https://twitter.com/ramyanexus/status/1006404820557709312

**Comment by ramya-rao-a** [comment]
Ah! I see it now.

In this case, the language server doesnt return any symbols for the file.
You can try `Ctrl+Shift+o` (use cmd on mac instead) and you will see that there are no symbols for the file

I have logged an upstream issue: https://github.com/sourcegraph/go-langserver/issues/311
You can subscribe to the above issue. Once fixed, just update your language server and you should see the fix.

Thanks for reporting!
