### ISSUE TITLE
Hovering over custom type constants shows wrong type

### ISSUE THREAD

**Issue by gbrlsnchs** [Microsoft/vscode-go#1867]
VSCode Version: 1.26.1
OS Version: Ubuntu 18.04
Steps to Reproduce:

1. Declare a custom type that's an alias of a basic type.
2. Declare a block of constants, assign to the first constant the type and value, making that constant explicitly of that custom type. Then declare other constants without type, and assign to them values that are a mix of basic type values in any operation with the first constant value. That mix will implicitly make the other constants that custom type, but the hover information shows their type as a basic type, not the custom one. A perfect example is the `time.Duration` type and its constants, as printed below. [Here's another example too](https://play.golang.org/p/ZfMKLKNfKeh).

![go_hover_correct](https://user-images.githubusercontent.com/7577128/44475676-09db8580-a60c-11e8-9023-8fb8f8ae6af9.png)
![go_hover_wrong](https://user-images.githubusercontent.com/7577128/44476099-275d1f00-a60d-11e8-80f8-46c8ac20d0b0.png)

**Comment by ramya-rao-a** [comment]
By default we use `godef` and `godoc` tools to find the definition of a symbol and docs respectively to show the information you see on hover. What you see is all these tools provide, so please log an issue in the repo for godef/godoc

You can try adding `"go.docsTool":"gogetdoc"` to your settings and reloading the window. You will then be using `gogetdoc` which might show results that you prefer
