### ISSUE TITLE
build output already exists and is not an object file

### ISSUE THREAD

**Issue by EmpireJones** [Microsoft/vscode-go#1868]
When "go.buildOnSave" is set to "workspace", I'm frequently (although inconsistently) getting this 'problem':
`go build example.com/my_package: build output "/tmp/go-code-check.180164698" already exists and is not an object file`

This may be a result of building many packages. In this case, it's building 55 packages, and I might only get that error on one of the package, although I often won't get it at all.

Based on the number of go processes that are spun up, my guess is that it's a race issue of some sort.

**Comment by ramya-rao-a** [comment]
I've updated the code to append a number to the end of the filename to ensure 2 parallel builds dont access the same file. Can you try it out and and see if it fixes the issue for you?

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` or `code-insiders --install-extension Go-latest.vsix` based on whether you are using Stable or the Insiders
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code
- The version of the Go extension should show as `0.6.89-beta.2`

**Comment by EmpireJones** [comment]
This seems to do the trick! thanks!
