### ISSUE TITLE
when l import pkg, can't get import suggestions

### ISSUE THREAD

**Issue by huangjiasingle** [Microsoft/vscode-go#1870]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed
go version : go1.10.3 darwin/amd64
vscode version: 1.26.1
Go for Visual Studio Code: 0.6.87 and 0.6.88

Steps to Reproduce:

1.  vi main.go
2. input "net/"    can't get import suggestions

**Comment by ramya-rao-a** [comment]
What are the contents of your file?

**Comment by huangjiasingle** [comment]
only like this ： 
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("")

}
```

**Comment by ramya-rao-a** [comment]
I have logged an upstream issue for this, see https://github.com/mdempsky/gocode/issues/38
If they dont respond soon enough, we can look into implementing this ourselves.
We already have the list of packages, only thing to do is to determine that we are inside the import block

**Comment by huangjiasingle** [comment]
@ramya-rao-a  thank u, l will notic it.
