### ISSUE TITLE
Download of vscode-go extension fails due to file corruption detected by anti-virus-scanner

### ISSUE THREAD

**Issue by mapl** [Microsoft/vscode-go#1871]
Please remove or upgrade package.

affected file inside "ms-vscode.go-0.x.xx.vsix": 
extension/node_modules/tar/test/  cb-never-called-1.0.1.tgz

Related to
https://github.com/npm/node-tar/issues/150

**Comment by ramya-rao-a** [comment]
- What anti-virus scanner did you use?
- How were you installing the extension? From the marketplace in the browser? Marketplace in VS Code? Or via the vsix?

**Comment by mapl** [comment]
I've updated the title because the download fails and not the installation. its actually the anti-virus portion of a network proxy which blocks the download. proxy is symantec

**Comment by ramya-rao-a** [comment]
- Do you see the same when downloading other extensions?
- Are you downloading directly from the marketplace website or VS Code?

**Comment by mapl** [comment]
- no, only vscode-go for now
- it makes no difference, all available download options fail, since its traversing the proxy which blocks it

**Comment by ramya-rao-a** [comment]
That same dependency (tar) is used in another extension called [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) by Pine Wu. Can you try downloading that and see if you get the same error?

**Comment by mapl** [comment]
confirmed, also fails.
When I try to use Winrar to open it, I also get an error.

`cb-never-called-1.0.1.tgz: Unexpected end of archive`
`node_modules\tar\test\cb-never-called-1.0.1.tgz: The archive is corrupt`

**Comment by ramya-rao-a** [comment]
Turns out that was only a dev dependency, I have pushed a fix. Can you try the below:

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by mapl** [comment]
Download working now! Thank you for fixing this.
