### ISSUE TITLE
go 1.11 intellisense not work when use go.mod

### ISSUE THREAD

**Issue by WangPengJu** [Microsoft/vscode-go#1873]
e.g.
![image](https://user-images.githubusercontent.com/9954852/44614659-90d26d00-a85b-11e8-9edf-5626c487776a.png)
![image](https://user-images.githubusercontent.com/9954852/44614665-a9428780-a85b-11e8-8d72-9c6d48e94864.png)
![image](https://user-images.githubusercontent.com/9954852/44614668-af386880-a85b-11e8-85c2-d67f576cd75d.png)
![image](https://user-images.githubusercontent.com/9954852/44614675-beb7b180-a85b-11e8-81fd-56890644b050.png)

**Comment by WangPengJu** [comment]
it can run by `go run main.go`  and it's work

**Comment by WangPengJu** [comment]
@deef0000dragon1

**Comment by francoishill** [comment]
@WangPengJu most of the `go` commands of 1.11 should do that by default, for example `go build` in your working directory.

**Comment by andrewmeissner** [comment]
I just came across this as well.

**Comment by mrkaspa** [comment]
It's working buggy with golang 1.11 and go modules dependencies

**Comment by edp1096** [comment]
Auto completion feature in current version support well vendor path with GOPATH.
It would be better to use ```go mod vendor``` during waiting update #1532 .

**Comment by ramya-rao-a** [comment]
We use `gocode` to provide completions and this tool along with many others do not yet have module support. 

#1532 is tracking the general module support

You can try https://github.com/Microsoft/vscode-go/issues/1532#issuecomment-419766453 which is one of the proposed solutions for `gocode`
