### ISSUE TITLE
`"useApiV1": false` vs `--api-version=2`

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode-go#1876]
`"useApiV1": false` works great but what if someday we have a V3

Can we have a refactor that is consistent with the dlv cli flags `--api-version=2` as in 

`"api-version":2` and the default is 1

Thanks

**Comment by lggomez** [comment]
It is a reasonable request

The intended release plan of the delve V2 integration was to have this compatibility config flag during a couple of releases using V1 as the default, and then make the final switch to V2

**Comment by gertcuykens** [comment]
If that's the case then it also fine, the less config the better :) +1 for default V2 and removing the useApiV1 flag completly

**Comment by ramya-rao-a** [comment]
I was meaning to set v2 as default for a while now, but was waiting to have an update which didnt have any other debug related changes, so that if there were any issues I could narrow it down to the version change.

Now is a good time, I'll make the change

**Comment by ramya-rao-a** [comment]
In the latest update to this extension (0.6.90), we use v2 by default. `useApiv1` is replaced with `apiVersion`
