### ISSUE TITLE
No build on save since 0.6.25

### ISSUE THREAD

**Issue by dstpierre** [Microsoft/vscode-go#188]
Just updated to latest version 0.6.25 and I lost build on save. Error are not displayed any more. 

I even did a full un-install, and added the `go.buildOnSave` to my config file in case.

```
"go.buildOnSave": true,
"go.lintOnSave": true,
"go.formatTool": "gofmt"
```

Auto-save is of course checked.

VS Code 0.10.6 on Windows 10.

I will try to update my fork and test it from the code to try and see wth. But any help would be appreciated.

**Comment by nexes** [comment]
I'm having a similar issue to this. Also, golint is not showing the errors and warnings any longer in the editor. The Golinter is working fine when ran in the cmd window.

**Comment by lukehoban** [comment]
Version 0.6.26 is now available, which has a fix that should address this.

If you are still seeing any issues after upgrading, please reopen.

**Comment by dstpierre** [comment]
so far so good, thank you very much, that was a hard day yesterday without it.

**Comment by nexes** [comment]
Working on my end. Thank you so much.
