### ISSUE TITLE
Generating unit tests for receiver function generates tests for other types, too

### ISSUE THREAD

**Issue by mrwonko** [Microsoft/vscode-go#1880]
Given two types with functions of the same name:

```
type foo int
type bar int

func (foo) Baz() {}
func (bar) Baz() {}
```

Trying to generate tests for one of them also generates them for the other. This is especially annoying when implementing standard interfaces like Stringer.

Possibly related to #1483.

**Comment by db47h** [comment]
`gotests` does not support this right now, see cweill/gotests/issues/35

**Comment by ramya-rao-a** [comment]
Thanks @db47h 
Once the upstream issue is fixed, I don't believe we need any changes in the extension to consume it.
So will close this.
