### ISSUE TITLE
Feature request: Command to run dep ensure followed by building the package

### ISSUE THREAD

**Issue by oneslash** [Microsoft/vscode-go#1883]
VS code does not recognises the `dep` ensure package. In order to make it work, I need to restart `vscode`.

Steps to Reproduce:
1. Create `main.go` import random package and use it (which is not already downloaded to your gopath)
2. do `dep init` && `dep ensure` 
3. see that package is underlined as red

**Comment by ramya-rao-a** [comment]
At this point, would running `Go: Build Current package` fix the error?

**Comment by oneslash** [comment]
it did help, however, why do I need to do build current package manually?

**Comment by ramya-rao-a** [comment]
The red underlines correspond to build errors. For them to go away after you have run `dep ensure` we need to build the package.

The Go extension cannot talk to the terminal and vice versa.
So when you run `dep ensure`, the Go extension doesn't realize that it has to build your package.

The package is built in 2 scenarios, either when you make a change and save the file or when you run the `Go: Build Current Package` command.

If there is indeed demand for `dep` support, then we can look into adding some commands to the Go extension for `dep ensure` which will then run the build as a follow up task

**Comment by ramya-rao-a** [comment]
> If you think it is a small task, I can take it and prepare PR for it.

That would be most welcome.

What other dep related commands do you think we should include?

Code pointers:
- Wiki for [Building and Debugging the Go extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- For a new command, you will have to declare it in the `package.json` file, register it in the `goMain.ts` file, define it in a new file say `goDep.ts`
- In the new file, export a function that would spawn a new child process to run the dep command and follow it up with a call to the [buildCode](https://github.com/Microsoft/vscode-go/blob/master/src/goBuild.ts#L13) function that will build the package

Let me know if you have any questions

**Comment by oneslash** [comment]
I will close this issue since go mods will be defecto standard for vendoring
