### ISSUE TITLE
No completions for symbols from unimported pkg if there are multiple matches for pkg name 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1884]
`fmt.` gives completions for all the symbols from the fmt package
`template.` doesn't do the same.

This is because we cannot determine which of the `text/template` and `html/template` should be used.

Proposed fix:
- When encountering `template.` provide completions for all the matching pkgs
- Once user chooses the package, the import should be added for that package, and completions should be triggered again.

This is possible to do because we can run commands as part of the completion. But since we can run one 1 command for a completion item, we will have to create a new command that internally runs `go.import.add` command followed by triggering suggestions again  with `editor.action.suggest` command

**Comment by shreyu86** [comment]
I am interested in working on a fix for this are can you provide any code pointers to get started?

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode-go/blob/0.6.89/src/goSuggest.ts#L415 is where we see that there are more than 1 matches and then decide to not do anything.

**Comment by shreyu86** [comment]
I was able show all the matching packages in case of `template`, was wondering how should I proceed to forward if the user selects one of the packages to add it in import path and provide subsequent completions. 
![image](https://user-images.githubusercontent.com/311217/44891294-b7e5d000-ac9b-11e8-9e62-e8f3c0346245.png)
For multiple matching packages I included the token and the matching packages in parenthesis, in this case would adding `command` which imports the package be the right thing to do?

**Comment by shreyu86** [comment]
Looked at references for `go.add.imports` in the source and was able to add support for this feature.

**Comment by ramya-rao-a** [comment]
The fix for this is in the latest update to this extension (0.6.90)
