### ISSUE TITLE
Feature Request: Syntax highlight for go.mod and go.sum

### ISSUE THREAD

**Issue by yookoala** [Microsoft/vscode-go#1886]
Please provide the syntax highlight for the go module files.

**Comment by ramya-rao-a** [comment]
I wonder if https://github.com/atom/language-go is the right place for this feature request. For go itself, we use the grammar from there.

@joefitzgerald, @zmb3 thoughts?

**Comment by brainsnail** [comment]
I'll take a look at this one on the Atom repository. Should be fun 👍

**Comment by ramya-rao-a** [comment]
The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension, the `go.mod` and `go.sum` files will now have syntax highlighting.

Thanks to @calebdoxsey and @brainsnail!

**Comment by ramya-rao-a** [comment]
This feature is out in the latest release(0.10.0) of the Go extension
