### ISSUE TITLE
go-symbols background process constantly using a CPU core

### ISSUE THREAD

**Issue by crawshaw** [microsoft/vscode-go#1887]
Vanilla VSCode 1.26.1 + Go plugin, macOS. A GOPATH that all builds.

After 15-20 minutes of editing code (which means saving in many states that do not compile), there will be a `go-symbols` process running constantly in the background on the machine using 100% of a CPU core

I have not yet found the exact intermediate code that causes this.

Reporting because it eats all the battery on my little MacBook.

**Comment by ramya-rao-a** [comment]
That is weird... `go-symbols` is only used when you perform a workspace symbol search. Did you happen to run `Go to symbol in workspace` command or `Cmd+#` ?

**Comment by crawshaw** [comment]
Yes, via the vim plugin I regularly use g-d to go to definition. All of the jumps are fast and correct, I assume I try it on an invalid name at some point and it starts spinning.

Is there some debug log I can provide to narrow this down?

**Comment by ramya-rao-a** [comment]
`Go to definition` is a different feature and doesn't use `go-symbols`
`Go to symbol in workspace` is a different command where you can type in the symbol you want to find.
Did you happen to try that?

Are you able to consistently repro this?
Do you have any other Go related extensions installed?

**Comment by crawshaw** [comment]
My only two plugins are vim and go. I'm not certain that vim is using the `Go to definition` and not `Go to symbol in workspace`.

It will reliably replicate after ~10 minutes of programming. But I haven't been able to narrow down the exact event that triggers it. If there's a log I can turn on, I could record it for my session and dissect it to find the `go-symbols` call that is broken.

**Comment by ramya-rao-a** [comment]
I dont think we have logs that can help in this case
The next time this happens, can you see which process is calling the `go-symbols`?

**Comment by ramya-rao-a** [comment]
Closing this issue because it needs more information and has not had recent activity.
