### ISSUE TITLE
PANIC shown for all autocomplete suggestions with Go 1.11

### ISSUE THREAD

**Issue by mholt** [Microsoft/vscode-go#1888]
Reproducing this bug is very easy. Install Go 1.11 and type the name of a value of a struct type, get PANIC:

<img width="541" alt="screen shot 2018-08-28 at 10 15 52 am" src="https://user-images.githubusercontent.com/1128849/44736077-7bec1880-aaab-11e8-9cef-20568755254d.png">

Expected to get a list of fields. This started happening after Go 1.11 is installed. I'm not using anything fancy like modules, just a very simple Go installation on macOS.

**Comment by ragurney** [comment]
Have you tried going to commands, selecting `Go: Install/Update Tools` and selecting `gocode`? That fixed this issue for me.

**Comment by mholt** [comment]
When I do that, it says:

```
Installing 0 tool at /Users/matt/Dev/bin


All tools successfully installed. You're ready to Go :).
```

And then the PANIC text persists...

**Comment by abradley2** [comment]
Having this issue as well. Specifically it happens when I'm using the new modules feature. But I guess given the issue mentioned it isn't specifically related. Let me know if there's any further details I can provide to help out.

**Comment by ramya-rao-a** [comment]
@abradley2 I'll be using #1873 to track the completions issue when using `go.mod`

@mholt, are you using `go.mod` as well?
Also, when running `Go: Install/Update Tools`, you might not have checked the tools to update. Try it again and update all the tools or in your case the `gocode` tool

**Comment by mholt** [comment]
@ramya-rao-a Thanks for the reply! I'm definitely not using go.mod.

> Also, when running Go: Install/Update Tools, you might not have checked the tools to update. Try it again and update all the tools

OH, it's a CHECKBOX interface! I see now. I had just clicked 'gocode' before, without realizing I had to select them and push a button. Mea culpa. It's working now. Thank you!

**Comment by jpfielding** [comment]
@ragurney didnt work for me until i included both gocode and gopkgs.  got it though, thanks!

**Comment by Lercher** [comment]
Hi, had the same problem, only in the `go mod init` case. Plus I'm using a custom GOBIN. Two different versions of gocode.exe existed, one in GOPATH/bin (old) and one in GOBIN (new). It turned out eventually, that "Go: Install/Update Tools" builds gocode to GOBIN but the extension started the old one from GOPATH/bin (via PATH?) that panics. So I deleted all the tools in GOPATH/bin and the extension asked for a tool rebuild. After that, intellisense worked again.

Details:
````
>go env
set GOARCH=amd64
set GOBIN=d:\bin
set GOCACHE=d:\Profiles\mlercher\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\Profiles\mlercher\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Daten\Go\src\innersource.soprasteria.com\BU270\casconfig\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=d:\Profiles\mlercher\AppData\Local\Temp\go-build054212822=/tmp/go-build -gno-record-gcc-switches

>go version
go version go1.11 windows/amd64
````

I guess, it's a bug, that the extension won't load what it built before.

Hope that helps, Martin.
