### ISSUE TITLE
Outline should exclude `_` "blank identifier"

### ISSUE THREAD

**Issue by mgood** [Microsoft/vscode-go#1889]
We use `var _` in the top-level of some of our Go files for various reasons, most notably the ["interface checks pattern"](https://golang.org/doc/effective_go.html#blank_implements) documented in Effective Go.

These should be excluded from the Outline view since they don't represent a real variable that can be referenced and they clutter the output.

For example this code will produce 3 entries for `_` in the outline view:
```go
package foo

var (
	_ io.Closer = Foo(nil)
	_ io.Closer = Bar(nil)
	_ io.Closer = Baz(nil)
)
```

**Comment by ramya-rao-a** [comment]
Good point. PRs are welcome.

Code Pointers:
- Checkout [Building and Debugging the extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) to learn how to set up a local dev version of the Go extension
- https://github.com/Microsoft/vscode-go/blob/0.6.88/src/goOutline.ts#L118 is the place where we can skip such symbols

**Comment by ramya-rao-a** [comment]
This issue has a PR: 
https://github.com/Microsoft/vscode-go/pull/1893

**Comment by mgood** [comment]
Nice, thanks!

**Comment by ramya-rao-a** [comment]
This but is now fixed in the latest update to this extension (0.6.90)
