### ISSUE TITLE
Click to goto definition doesn't work for the stdlib

### ISSUE THREAD

**Issue by peterbourgon** [Microsoft/vscode-go#189]
1. Type e.g. `err := fmt.Errorf("hello")`
2. Cmd-click on `Errorf`

Expected behavior: jump to [the definition of Errorf](https://golang.org/src/fmt/print.go?s=5673:5723#L201) in the stdlib

Actual behavior: nothing happens.

Do I need to tell gocode to index the stdlib or something like this?

**Comment by lukehoban** [comment]
This definitely works in general.

![errorfgotodef](https://cloud.githubusercontent.com/assets/223467/12801716/b14dcfaa-ca93-11e5-99dd-335166169ad3.gif)


Could you provide more details on your environment?  Does your code build without errors?  Do you have an `import "fmt"` in the file you are trying this?

**Comment by 0x434D53** [comment]
Same problem here. The Developer Console shows:
```
TypeError: Cannot read property 'file' of null: TypeError: Cannot read property 'file' of null
    at /Users/xxx/.vscode/extensions/lukehoban.Go-0.6.26/out/src/goDeclaration.js:75:68
e.onUnexpectedError @ workbench.main.js:91
(anonymous function) @ workbench.main.js:91
e.onUnexpectedError @ workbench.main.js:10
u @ workbench.main.js:10
(anonymous function) @ workbench.main.js:41
p @ workbench.main.js:6
__dirname.undefined.F.enter @ workbench.main.js:6
__dirname.undefined.t.Class.define._run @ workbench.main.js:6
__dirname.undefined.t.Class.define._error @ workbench.main.js:6
h.handle @ workbench.main.js:38
(anonymous function) @ workbench.main.js:67
(anonymous function) @ workbench.main.js:67
emitTwo @ events.js:87
emit @ events.js:172
handleMessage @ internal/child_process.js:685
channel.onread @ internal/child_process.js:440
```

**Comment by peterbourgon** [comment]
Go installed via `brew install go`.

```
$ go version
go version go1.5.3 darwin/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/peter"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.5.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.5.3/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

VSCode installed via `brew cask install visual-studio-code`. 

Here's what the developer console shows when I hold command and hover or try to click on e.g. Errorf:

```
TypeError: Cannot read property 'file' of null: TypeError: Cannot read property 'file' of null
    at /Users/peter/.vscode/extensions/lukehoban.Go-0.6.26/out/src/goDeclaration.js:75:68
    at process._tickCallback (node.js:368:9)
```

How do you create those handy gifs? :)

**Comment by lukehoban** [comment]
Hmm - I can't repro this myself under any conditions on my three machines.

If you put the following in `$GPATH/src/test.go`:

```go
package main

import "fmt"

func main() {
	_ = fmt.Errorf("hello")
}
```

What do you see when you run the following from `GOPATH/src`?

```
godef -t -i -f test.go -o 59 < test.go
```

For me, I get the following, which should not trigger the error condition folks are mentioning here.

```
c:\dd\go\src> godef -t -i -f test.go -o 59 < test.go
C:\Go\src\fmt\print.go:211:6
Errorf func(format string, a ...interface{}) error
```

Also, does the file mentioned in this result exist in your filesystem?  In my case on Windows above it was `C:\Go\src\fmt\print.go`.

**Comment by peterbourgon** [comment]
```fish
ugh ~/src cat test.go
package main

import "fmt"

func main() {
    _ = fmt.Errorf("hello")
}
ugh ~/src godef -t -i -f test.go -o 59 < test.go
godef: no declaration found for fmt.Errorf
ugh ~/src _
```

**Comment by peterbourgon** [comment]
☹️

[**:GoDef working for everything except Go standard library**](https://github.com/fatih/vim-go/issues/333)

```fish
ugh ~/src go get -u github.com/rogpeppe/godef
ugh ~/src godef -t -i -f test.go -o 59 < test.go
/usr/local/Cellar/go/1.5.3/libexec/src/fmt/print.go:211:6
Errorf func(format string, a ...interface{}) error
ugh ~/src _
```

Confirmed working in Code. Sorry for the noise. Maybe you can file this away as a troubleshooting tip in the future.

**Comment by lukehoban** [comment]
Wow - yeah - that's a subtle issue.  

> I was using godef compiled with an old version of Go that is no longer installed, so it couldn't find the correct libraries. I wish it would have a better error message including the paths it searched. Thank you!

It's not at all clear to me how that could lead to a problem.  How can the compiled `godef` binary have any knowledge of the compile-time go installation embedded within it?  Anyway - sounds like the workaround works, which is good.

**Comment by peterbourgon** [comment]
I presume compiling godef builds the GOROOT into the binary, and when I upgrade from e.g. go1.5.1 to go1.5.3, the old godef gets confused.
