### ISSUE TITLE
Rune type not colored like others

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1894]
VSCode version 1.26.1 (1.26.1) 493869ee8e8a846b0855873886fc79d480d342de
Go extension version 0.6.88

<img width="238" alt="screen shot 2018-08-29 at 7 18 36 pm" src="https://user-images.githubusercontent.com/63830/44825692-949a2280-abc0-11e8-8c13-a0f5b8656bdb.png">

**Comment by oneslash** [comment]
`rune` is defined as data storage type in `vscode`, same as `map` and etc

**Comment by db47h** [comment]
The [Go spec](https://golang.org/ref/spec#Numeric_types) says that `rune` is an alias for `int32`, likewise `byte` is an alias for `uint8`, so there's no reason to treat `rune` differently from any other basic type.

Additionally, themes tend to do their own thing:

![vscode_go](https://user-images.githubusercontent.com/879556/44849535-b647e800-ac5a-11e8-8fd5-71bb4408fb2b.png)

The same snippet of code with the `default` theme on the left and the `1337` theme on the right. The `1337` theme manages to display `rune` the same as `int`, yet handle map and chan differently. It even goes as far as colourize the `<-`!

**Comment by db47h** [comment]
@willfaught : After a bit of digging, it turns out that Go's syntax highlighting is defined in vscode's core in a file named `resources/app/extensions/go/syntaxes/go.tmLanguage.json`.

Here's the interesting bit:

```json
"storage_types": {
                        "patterns": [
                                {
                                        "match": "\\bbool\\b",
                                        "name": "storage.type.boolean.go"
                                },
                                {
                                        "match": "\\bbyte\\b",
                                        "name": "storage.type.byte.go"
                                },
                                {
                                        "match": "\\berror\\b",
                                        "name": "storage.type.error.go"
                                },
                                {
                                        "match": "\\b(complex(64|128)|float(32|64)|u?int(8|16|32|64)?)\\b",
                                        "name": "storage.type.numeric.go"
                                },
                                {
                                        "match": "\\brune\\b",
                                        "name": "storage.type.rune.go"
                                },
                                {
                                        "match": "\\bstring\\b",
                                        "name": "storage.type.string.go"
                                },
                                {
                                        "match": "\\buintptr\\b",
                                        "name": "storage.type.uintptr.go"
                                }
                        ]
                },
```

As you can see all storage types are defined properly, so the problem is with the theme you are using that handles `storage.type.rune` differently. You should report this issue to the theme creator (vscode main repo?).

On a side note, `map` and `chan` are defined as keywords (as they should).

**Comment by ramya-rao-a** [comment]
@db47h Thanks for digging into this @db47h, you hit all the right points.

@willfaught I see that you have logged an upstream issue, so I'll respond there.

**Comment by willfaught** [comment]
Thanks!
