### ISSUE TITLE
Remote debug is super slow

### ISSUE THREAD

**Issue by cscetbon** [microsoft/vscode-go#1904]
VSCode Version: 1.26.1
OS Version: MacOS 10.13.4
Extension : Go 0.6.89

Steps to Reproduce:

- remote debug a pod in Kubernetes
- test manually using dlv client (to connect to the remote dlv server running in the pod) and see that it takes 2 seconds to go to next step
- test with VSCode (which also uses the remote dlv server running in the pod) and see that it takes 40 seconds to go to next step

When I'm in debug mode I also noticed that I need to click twice for an operation (next step, restart) to work.

**Comment by ramya-rao-a** [comment]
Hey @cscetbon 

There have been quite some improvements in the last year in the debugging area, can you let us know if you still have the slowness problem? If yes, can you share a small sample code where you see this problem, so that we can attempt to replicate this?
