### ISSUE TITLE
gogetdoc too slow to retrieve docs and cpu is 100%

### ISSUE THREAD

**Issue by iamwwc** [Microsoft/vscode-go#1907]
I found a issue, but not solve my problem,[ https://github.com/Microsoft/vscode-go/issues/667
](url)

when I use gogetdoc, it's to slow to retrieve docs, and my cpu is 100%

![gogetdoc](https://user-images.githubusercontent.com/24750337/44955599-6e3df500-aee8-11e8-937c-d7ede6881e79.gif)

https://github.com/Microsoft/vscode-go/issues/667#issuecomment-347350320 said performance improved, but I still have problem.

```
cpu : i5-5200U
ram: 8G
and SSD

vscode-go version: 0.6.89
```

go-config
```
    "go.docsTool": "gogetdoc",
    "explorer.confirmDragAndDrop": false,
    "go.autocompleteUnimportedPackages": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.formatFlags": [
        "-w"
    ],
    "go.formatTool": "goreturns",
```

if you need more info, please tell me:)

**Comment by ramya-rao-a** [comment]
- Does this happen even in small simple programs or only large codebases?
- Can you run `gogetdoc` from the terminal on the same file as your example and see how it performs?

**Comment by iamwwc** [comment]
1. Yes, problem stills even in simple programs
my origin file have gone, but I have another codes, I think no difference between them.

main.go
```golang
package main

import (
	"context"
	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/client"
	log "github.com/sirupsen/logrus"
	"io"
	"os"
)

func main() {
	r := Record{}
	dockerClient, err := client.NewClientWithOpts(client.WithVersion("1.38"))
	if err != nil{
		log.Error("error when create dockerClient ",err)
	}

	ctx := context.Background()

	container, err := dockerClient.ContainerCreate(ctx,&container.Config{
		Image:"golang",
		OpenStdin:true,
		Tty:true,
		AttachStdin:true,
		Cmd:[]string{"bash","-c","go build && go run"},
		Env:[]string{"GOPATH=/go",
		"PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
		"GOLANG_VERSION=1.11"},
		AttachStdout:true,
		AttachStderr:true,

	},nil,nil,"")
	

	if err := dockerClient.ContainerStart(ctx,container.ID,types.ContainerStartOptions{});err != nil{
		log.Error("error when start container", err)
		return
	}

	reader, err :=dockerClient.ContainerLogs(ctx,container.ID,types.ContainerLogsOptions{
		ShowStdout:true,
		ShowStderr:true,
	})

	if err != nil{
		log.Error("error when containerLogs",err)
	}

	go io.Copy(os.Stdout,reader)

	<- make(chan struct{})
}
```

test.go
```golang
package main

//Record is a test comment to test gogetdoc
type Record struct{

}
```

but if I remove all external lib, only import my lib in project, gogetdoc works very good.
![reply](https://user-images.githubusercontent.com/24750337/45278186-86240300-b4fe-11e8-9332-7bd781104829.gif)

2. I cannot find enough `gogetdoc cli` doc, so I am not sure what I have done is right or not.
![shotcut](https://user-images.githubusercontent.com/24750337/45278323-24b06400-b4ff-11e8-8a97-47be5a430ea9.png)

when I run gogetdoc 
```
gogetdoc -pos main.go:#22
```

output is 
```
gogetdoc: no documentation found
```

**Comment by ramya-rao-a** [comment]
gogetdoc needs a byte offset, you are using line number

- Install the [show-offset](https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset#overview) extension
- add setting `"showoffset.offsetType": "byte"`
- Keep cursor on the symbol you want to get information on
- You will see the offset in the status bar. Use that when running `gogetdoc` in the terminal

**Comment by ramya-rao-a** [comment]
@iamwwc If you are seeing delays even when running from terminal, please log an issue at https://github.com/zmb3/gogetdoc/issues

**Comment by iamwwc** [comment]
I don't think that will help.. 
`gogetdoc` repo's last commit is May 22

**Comment by ramya-rao-a** [comment]
I would still encourage you to log the issue, as there is nothing much we can do from the extension's side.

Once we have Windows support for the [language server](https://github.com/Microsoft/vscode-go#go-language-server-experimental), you can give that a try.

**Comment by iamwwc** [comment]
closed, waiting upstream solve this problem or waiting language server
