### ISSUE TITLE
Go 1.11 imports of local packages in a module aren't recognized

### ISSUE THREAD

**Issue by tamasf97** [Microsoft/vscode-go#1909]
The problem is best described in the screenshot:
![screenshot from 2018-09-03 23-39-56](https://user-images.githubusercontent.com/25967296/45002224-f1d51000-afd4-11e8-83c6-313a5543bb71.png)
The app builds just fine, but the import doesn't work in vs code.

I cleared both the bin and pkg folders of my GOPATH, and updated all the tools.

To be honest, I haven't got my head around the new go modules yet, so I'm not sure whether this is a bug or me doing something wrong.

**Comment by avence12** [comment]
Try to replace `nsf/gocode` as `mdempsky/gocode` ?  
It works for me after the migration.

**Comment by tamasf97** [comment]
No success, it seems that several tools don't support modules yet at all, including gocode and go-langserver and who knows what else, see https://github.com/mdempsky/gocode/issues/46 and https://github.com/sourcegraph/go-langserver/issues/316 for example.

So it isn't a bug in the extension.
