### ISSUE TITLE
Tab should insert tabs in auto mode

### ISSUE THREAD

**Issue by peterbourgon** [Microsoft/vscode-go#191]
1. Set `"editor.insertSpaces": "auto"`
2. Open any .go file
3. Press the tab key

Expected behavior: a literal tab character is inserted.

Actual behavior: spaces are inserted.

(Perhaps the plugin doesn't currently have the ability to dictate this behavior to the editing engine?)

**Comment by egamma** [comment]
If you always want to insert a tab key then use the following settings:
```json
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
```

**Comment by peterbourgon** [comment]
I don't want to always insert a tab character across all files. I want VS Code to be smart about it, i.e. spaces in .py and .rb files, tab literals in Makefile and .go files, etc.

**Comment by egamma** [comment]
OK, then `auto` is the setting you want to use. 

Please file an issue against https://github.com/Microsoft/vscode/issues with the file where the guessing is wrong.

**Comment by peterbourgon** [comment]
Ah, okay! Will do :)

**Comment by lukehoban** [comment]
I think https://github.com/Microsoft/vscode/issues/2765 is tracking the potentially actionable piece of this, so I'll close this one out for now.
