### ISSUE TITLE
Cannot longer run unit-tests using check from vscode due to invalid stretchr/testify detection.

### ISSUE THREAD

**Issue by alex-kovoy** [Microsoft/vscode-go#1911]
This PR https://github.com/Microsoft/vscode-go/pull/1707 introduced a breaking change. Now it's no longer possible to run unit-tests from vscode if your tests have similar to 'stretchr/testify' suite.Run() call in them

For example, when using `gopkg.in/check.v1` package you may have the following test suite

```
import (
        ...
	check "gopkg.in/check.v1"
)

type LicenseSuite struct {	
}

var _ = check.Suite(&LicenseSuite{})

func (s *LicenseSuite) TestLicenseLegacy(c *check.C) {
  ...
}
```

which vscode would try to run with `stretchr/testify` flags assuming that this library is used (based on regex parsing).

I suggest to remove a support for 3d party libraries from a default behavior.

**Comment by ramya-rao-a** [comment]
@alex-kovoy In the above case, how are you running the unit tests? Using the commands from the command pallet or using the codelens? If codelens, then which codelens? The ones above each test function or above the package declaration?

**Comment by ramya-rao-a** [comment]
I tried using `go test -check.f` but I keep getting the usage of the generated .test file printed out instead. Am I missing something?

**Comment by ramya-rao-a** [comment]
Also, how have you been trying to run the tests? Using the commands to run tests in package/file/cursor or code lens to run tests in package/file/function?

**Comment by ramya-rao-a** [comment]
Thanks @alex-kovoy 

I have pushed a fix to the master branch. Can you follow the instructions to [download and install the beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension to test it out?

**Comment by ramya-rao-a** [comment]
I've also logged #1921 to support running such tests individually

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to this extension (0.6.90)
