### ISSUE TITLE
godef isn't work

### ISSUE THREAD

**Issue by chenyihui555** [Microsoft/vscode-go#1913]
I use vscode, but  guru is too slow, about 2 seconds,  it is very annoyed for me.

**Comment by ramya-rao-a** [comment]
@chenyihui555 The title of your issue is about `godef` but the description is about `guru`. Can you please elaborate on what the issue is?

**Comment by chenyihui555** [comment]
my godef cannot be used in vscode, so I use guru to find the definition, but the process of finding the function definition is slow, about 2 seconds

**Comment by chenyihui555** [comment]
@ramya-rao-a

**Comment by chenyihui555** [comment]
Hold on, let me write a small sample @ramya-rao-a

**Comment by chenyihui555** [comment]
@ramya-rao-a  This situation only exists in large projects at the moment. I define an interface and then implement the methods inside, but I cannot use godef to jump to the methods

**Comment by chenyihui555** [comment]
@ramya-rao-a  I can use sublime and I can jump

**Comment by ramya-rao-a** [comment]
> my godef cannot be used in vscode, so I use guru to find the definition, 

Do you know why `godef` cannot be used?

Can you run it from a terminal on the same file and see what error you get?
Can you run `guru` from a terminal on the same file and see if you get similar delays?

**Comment by chenyihui555** [comment]
@ramya-rao-a  
=================[Godef]Begin=================
[Godef]INFO: select_begin: 1179 offset: 1323
[Godef]INFO: spawning: F:/mygo\bin\godef.exe -f F:\gospace\src\GrandMainSer\app\action\counsellorExchange\CounsellorExchange_11908.go -o 1323
[Godef]ERROR: godef fail: godef: no declaration found for act.GetRid
[Godef]INFO: spawning: F:/mygo\bin\guru.exe -json definition F:\gospace\src\GrandMainSer\app\action\counsellorExchange\CounsellorExchange_11908.go:#1323
[Godef]INFO: guru output:
{
	"objpos": "F:\\gospace\\src\\GrandMainSer\\app\\core\\session.go:51:2",
	"desc": "func (GrandMainSer/app/core.IGameSession).GetRid() string"
}

**Comment by ramya-rao-a** [comment]
@chenyihui555  Where are you getting the above logs from? What did you run?

**Comment by chenyihui555** [comment]
@ramya-rao-a  my vscode user Settings eg：
 {
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "workbench.colorTheme": "One Dark Pro",
    "terminal.integrated.shell.windows": "D:\\Git\\Git\\bin\\bash.exe",
    "go.formatTool": "goimports",
    "editor.formatOnSave": true,
    "[go]": {
        "editor.insertSpaces": true,
        "editor.formatOnSave": true
    },
    "editor.fontSize": 18,
    "window.zoomLevel": -1,
    "editor.minimap.enabled": false,
    "go.useLanguageServer": true,
    "workbench.activityBar.visible": true,
    "editor.fontFamily": "Monaco,  Consolas,Lucida Sans Typewriter",
    "workbench.editor.showTabs": true,
    "go.gopath": "F:/mygo;F:/gospace",
    "go.goroot": "F:/goroot",
    // "workbench.iconTheme": "vs-minimal",
    "go.docsTool": "guru",
    "go.autocompleteUnimportedPackages": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
}

**Comment by chenyihui555** [comment]
@ramya-rao-a  can i have a look at your Settings?

**Comment by ramya-rao-a** [comment]
@chenyihui555 As per your settings, you have enabled the language server. This means that the language server is used for the "Go to definition" feature and not `guru`.

If you don't want to use guru and not the language server, then set `go.useLanguageServer` to `false`

**Comment by chenyihui555** [comment]
@ramya-rao-a  I had the same issue, and I resolved it by reinstalling godef package.

**Comment by chenyihui555** [comment]
@ramya-rao-a  thanks you  !

**Comment by ramya-rao-a** [comment]
Glad that things worked out, Happy Coding!
