### ISSUE TITLE
Follow-up to #1315, Cmd+Click (Go to Definition) still not working consistently

### ISSUE THREAD

**Issue by benguild** [Microsoft/vscode-go#1915]
I've noticed that this feature unfortunately still just does not work as consistently as IntelliJ IDEA Ultimate/Gogland, and it's the one feature preventing me from switching over. _(Follow-up to #1315)_

If it does work, it's quite frankly way too slow. :(

VSCode is a great IDE and I use it for non-Go projects, but this feature is really holding me back from not only switching but recommending it. — You guys have my support so if there's anything I can do to help or that you want me to test, please let me know.

**Comment by benguild** [comment]
Thanks for your response!

- Yes, I configured everything you'd suggested before.
- In general what I've noticed is there's no slowness in IntelliJ (it's pre-indexed) but occasionally multiple seconds of lag on larger projects in VSCode. — In addition, when jumping across projects using imports, the functionality is often broken even though everything's within the configured `GOROOT`.
- macOS Mojave but this was the same on High Sierra.
- Because it's larger projects across imports this is unfortunately kind of infeasible but perhaps I could test something for you?

**Comment by ramya-rao-a** [comment]
If you are using the language server (i.e the setting `go.useLanguageServer` is set to `true`), then we should log an issue in the repo for the language server itself which is https://github.com/sourcegraph/go-langserver. Folks there would be able to better diagnose the issue

**Comment by benguild** [comment]
I'm comparing the performance of key features of another IDE to VSCode's for Go. — If the only way to get anything similar is by using a third-party language server then I'd assume this is more a limitation of the VSCode IDE. There may also be issues with that particular language server, which could be considered a reason to improve VSCode's internal "Go To Definition" support in general as IntelliJ has opted to do themselves rather than deferring the issues. 🤷🏼‍♂️

**Comment by ramya-rao-a** [comment]
> There may also be issues with that particular language server, which could be considered a reason to improve VSCode's internal "Go To Definition" support in general as IntelliJ has opted to do themselves rather than deferring the issues

There is no "internal" support for any of the key features for Go in VS Code. We depend on third party tools to provide the said features in the editor. This is clearly called out in the README. This is what almost all editors do for Go (VS Code, Atom, Sublime, Vim, Emacs).

Goland by JetBrains is an IDE not an editor like VS Code, Atom, Sublime, Vim etc. If we were to opt to do the same and have custom internal implementation for all the key features, then we would be an IDE too. VS Code is a light weight editor not a full blown IDE.

Language servers and the Language server protocol is the answer to the question of repeated custom internal language implementations across multiple editors. Our aim is to support and encourage language server providers. Sourcegraph has implemented one. Google may implement another more robust and complete one.

A complete and robust language server can power multiple editors and that is the end goal.

> I'm comparing the performance of key features of another IDE to VSCode's for Go. — If the only way to get anything similar is by using a third-party language server then I'd assume this is more a limitation of the VSCode IDE. 

I appreciate your work. Goland by JetBrains is definitely backed by its own internal support for many of the key features. It is also backed by an entire development team where as the Go plugins for other editors including VS Code are open source projects maintained by 1 or 2 maintainers with amazing help from the community.

Therefore, if you feel Goland serves your interest, then by all means, I would suggest that you use it. (I am being genuine here and not sarcastic. I am specifically saying this as text does not always convey the intent).

**Comment by ramya-rao-a** [comment]
Yes, it is a marketed feature and it is up to extensions to decide how they want to implement it. And in the case of Go, it is done using third party tools.

Thanks for understanding.
