### ISSUE TITLE
Analysis Tools bad color in light themes

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode-go#1917]
https://github.com/Microsoft/vscode-go/blob/dc7c4739b7923c206ac9cc8b5ef95fa874cb17bd/src/goStatus.ts#L42

My suggestion is to remove this `yellow` color and keep the default one cuz' it's really hard to read it in some themes...

<img width="1026" alt="sidebar-left-yellow-text" src="https://user-images.githubusercontent.com/10441177/45202819-dd1da400-b282-11e8-9a14-c780c13add81.png">

**Comment by ramya-rao-a** [comment]
Thanks for reporting! That indeed is a very bad bug.

PRs are welcome to fix this.

**Comment by svipben** [comment]
So it's safe to simply delete that color line? I can definitely open a PR.

**Comment by ramya-rao-a** [comment]
I believe initially (and this is before my time), the intention was to get the user's attention to that item.
So if you can figure out some other way to do it like using a different color or using an icon, then that would be a good solution.

**Comment by ramya-rao-a** [comment]
The status bar item supports the use of [github octicons](https://octicons.github.com). See https://code.visualstudio.com/docs/extensions/example-word-count

**Comment by svipben** [comment]
I guess this https://octicons.github.com/icon/tools/ matches best since text says "Analysis Tools Missing". With coloring, it's way harder since it depends on theme, what I can think of is only red color, but still, if someone uses theme with red sidebar it will have same issue. So best solution is to use icon. What do you think @ramya-rao-a ?

**Comment by ramya-rao-a** [comment]
Icon sounds good

How about https://octicons.github.com/icon/alert/ ?

**Comment by svipben** [comment]
Sounds good, it was my first choice, but I changed my mind 😄 PR will be soon!

**Comment by svipben** [comment]
@ramya-rao-a opened a PR: https://github.com/Microsoft/vscode-go/pull/1922

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to this extension (0.6.90)
