### ISSUE TITLE
Does not autocomplete for third party packages with go 1.11

### ISSUE THREAD

**Issue by mrkaspa** [Microsoft/vscode-go#1918]
Updating to the new golang version it does not find these packages and I can not import them,  but using go modules and building work well. The problem is with the editor

**Comment by bitfield** [comment]
It looks like `vscode-go` is not detecting that the third-party packages have been installed outside GOPATH by Go 1.11's `go build`—that is, in 'module-aware' mode.

If I delete the `go.mod` file and run `go get PACKAGE`, installing it in 'non-module-aware' mode, VS Code finds it as expected and hover tips and auto-completion start working.

**Comment by husainaloos** [comment]
I am having a similar problem.

I am running vscode in linux, with golang 1.11 installed. I am writing my app outside GOPATH directory and I am using go mod for all the dependencies.

The following does not work:
1. Autocompletion
2. Renaming variables
3. Go to definition

I am not sure if something else doesn't work as well.

**Comment by ramya-rao-a** [comment]
We use `gocode` to provide completions and this tool along with many others do not yet have module support. 

#1532 is tracking the general module support

You can try https://github.com/Microsoft/vscode-go/issues/1532#issuecomment-419766453
