### ISSUE TITLE
Support codelens to run and debug tests supported by the check package

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#1921]
Tests that use the [check](http://labix.org/gocheck) package can be run as part of the whole package or file but not individually in VS Code.

This feature request is to support the below for individual tests using the check package in VS Code
- `Go: Test function at cursor` command
- Run Tests codelens
- Debug Tests codelens

**Comment by Charliekenney23** [comment]
I'll take this!

**Comment by ramya-rao-a** [comment]
@Charliekenney23 Thanks! Do you need any pointers?

**Comment by Charliekenney23** [comment]
@ramya-rao-a Yeah, pointers would be great if you have the time!

**Comment by mapuri** [comment]
@ramya-rao-a @Charliekenney23 Is this issue still being worked on? 

I would benefit from this feature. One of the repos that I work with uses the check package and vscode-go won't let me run/debug those tests individually.

**Comment by Charliekenney23** [comment]
Please feel free to take this! I'm no longer effected by this issue and forgot about it as a result.

**Comment by mapuri** [comment]
@Charliekenney23 thanks for letting me know. I haven't coded in node yet but I can give it a shot :)

@ramya-rao-a following your code pointers I think we would need to add the go-check package related flags in [targetArgs](https://github.com/Microsoft/vscode-go/blob/0.7.0/src/testUtils.ts#L356) function that is called from the [goTest](https://github.com/Microsoft/vscode-go/blob/0.7.0/src/testUtils.ts#L199) function. We don't yet have the information about the imported packages in that function but we can get that in similar lines from the **editor** object as we do it in [getTestFunctions](https://github.com/Microsoft/vscode-go/blob/0.7.0/src/testUtils.ts#L102). 

```node
function targetArgs(testconfig: TestConfig): Array<string> {

	const editor = vscode.window.activeTextEditor;
	if (!editor) {
		vscode.window.showInformationMessage('No editor is active.');
		return;
	}
	if (!editor.document.fileName.endsWith('_test.go')) {
		vscode.window.showInformationMessage('No tests found. Current file is not a test file.');
		return;
	}
...
	if (testMethods.length > 0) {
		if ( containsThirdPartyTestPackages(editor.document, null, [goCheckPkg]) ) {
			params = params.concat(['-check.f', util.format('^(%s)$', testMethods.join('|'))]);	
		} else if (containsThirdPartyTestPackages(editor.document, null, [testifyPkg])) {
			params = params.concat(['-testify.m', util.format('^(%s)$', testMethods.join('|'))]);
		}
	}
...
}

export async function containsThirdPartyTestPackages(doc: vscode.TextDocument, token: vscode.CancellationToken, pkgs: string[]): Promise<boolean> {
	const documentSymbolProvider = new GoDocumentSymbolProvider(true);
	const allPackages = await documentSymbolProvider
		.provideDocumentSymbols(doc, token)
		.then(symbols => symbols[0].children)
		.then(symbols => {
			return symbols.filter(sym => sym.kind === vscode.SymbolKind.Namespace && pkgs.some(pkg => sym.name === pkg));
		});
	return allPackages.length > 0;
}
```
I can create a PR for further discussion and review, if this sounds about right :)

**Comment by ramya-rao-a** [comment]
@mapuri Apologies for the late reply. Yes, please do go ahead and send a PR

**Comment by mapuri** [comment]
@ramya-rao-a I have created https://github.com/microsoft/vscode-go/pull/2680 to address this issue. It is failing some tests but they don't appear to be related to my changes. When you get a chance please take a look and let me know your feedback.

**Comment by tgturner** [comment]
Is this still being worked on? I saw there is an open PR that hasn't seen any activity in a while.

**Comment by mapuri** [comment]
@tgturner I am not working on this issue. The PR that I had created is out of date now. I will close it so anyone else who is interested can pick it up.

**Comment by tgturner** [comment]
I'm happy to take a look at this then! Thanks @mapuri

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Please subscribe to https://github.com/golang/vscode-go/issues/111 for further updates on this issue.

Thanks for all the support & Happy Coding!
