### ISSUE TITLE
Feature Request: Open Package in new window

### ISSUE THREAD

**Issue by davidwkeith** [microsoft/vscode-go#1928]
Similar to the URL detection in VSCode's terminal, when hovering over a supported import string (eg "github.com/google/uuid") the string would become underlined with a tool tip to "Cmd + click open source" (or appropriate OS modifier key)

When clicked it would open the source import path. This could be new window, or just navigating to the source in the file tree view, depending on the project root.

Extra cool would be an option to open the appropriate web page (but that can get complicated if it is not a top level package in a repo)

**Comment by ramya-rao-a** [comment]
Is the expectation to see the contents of the package?

Currently, when your cursor is on one of the packages in the import block, you can run `Go: Browse Packages`. That will open all the files in the package for you to navigate to.

**Comment by davidwkeith** [comment]
Those are great, but neither does quiet what I hoped.

- `Go: Browser Packages`: Does not auto jump to the currently package, still need to search, then browsing the files inside the package is not great.
- `Go: Add Package to Workspace`: The package is already in the workspace, I get "Could not find package…"

Ultimately the command would be `Go: Open Package in File Tree` that would open `vendor/github.com/google/uuid` in the file tree, and maybe load `uuid.go` from that directory in the editor (or README if it were super advanced)

Closest command I have found is "Go to Definition" contextual menu, which works on package contents, but not the package name itself.

**Comment by ramya-rao-a** [comment]
> Go: Browser Packages: Does not auto jump to the currently package, still need to search, then browsing the files inside the package is not great.

Keeping the cursor on the package in the import block and then calling `Go: Browse Packages` does indeed open the drop down with package files. If the package was already open in the workspace, and you selected one of the files from the drop down, the file explorer would automatically show the file that was opened.

**Comment by axetroy** [comment]
I have been expecting this feature for a long long time, but it has never been implemented.

In fact ``goLand`` integrates this function very well. 

This is worth learning and reference.

those great feature in ``goLand``:

**1. Tree View for External Libries** 

![2018-10-03 10 48 28](https://user-images.githubusercontent.com/9758711/46387580-f0912300-c6f9-11e8-8a63-ec55026c70f7.png)

**2. command-click to navigate to the import's source**

![2018-10-03 10 50 46](https://user-images.githubusercontent.com/9758711/46387707-8a58d000-c6fa-11e8-9dfa-379642f47934.png)

It is undeniable that goLand is a commercial software and does have a lot to learn.

I also hope to use these features in vscode.

**Comment by axetroy** [comment]
After a few months, can someone achieve this feature?

Because of this feature, I had to use `Goland`.

But I really like `VS Code`. This is really regrettable.

**Comment by stamblerre** [comment]
`gopls` supports this feature, and it will offer a list of files to jump to after [CL 210321](https://go-review.googlesource.com/c/tools/+/210321) is submitted. @ramya-rao-a: Is that sufficient for us to close this issue?

**Comment by ramya-rao-a** [comment]
Looks like the upstream code has been merged.

@stamblerre, Can you explain how this feature will work? We can close the issue after that

**Comment by stamblerre** [comment]
<img width="1370" alt="Screen Shot 2020-03-16 at 12 32 41 PM" src="https://user-images.githubusercontent.com/5856771/76779821-5a807980-6782-11ea-987c-094c77b3b45c.png">

Now, clicking go to definition on an import line gives you a list of files to choose from. This achieves #2 in @axetroy's request. I'm not sure if that's sufficient here, but it may be.

> **2. command-click to navigate to the import's source**
> 
> ![2018-10-03 10 50 46](https://user-images.githubusercontent.com/9758711/46387707-8a58d000-c6fa-11e8-9dfa-379642f47934.png)

**Comment by ramya-rao-a** [comment]
> Now, clicking go to definition on an import line gives you a list of files to choose from. 

This was already available via the `Go: Browse Packages` cmd when invoked after keeping the cursor on the import line

I believe the ask is more towards the ability to open the folder to the package in the file explorer. If the package is not already part of the current workspace, then perhaps adding it to the workspace

**Comment by ramya-rao-a** [comment]
>When clicked it would open the source import path. This could be new window, or just navigating to the source in the file tree view, depending on the project root.
Extra cool would be an option to open the appropriate web page (but that can get complicated if it is not a top level package in a repo)

The original ask has been addressed by the use of language server i.e navigating to the source path and the web page

`Go: Add Package to Workspace` can be used to add the package to the workspace.

To open the package in a new folder is not a feature we will be investing anytime soon, but can be implemented independent of this package in a separate extension.
