### ISSUE TITLE
Go 1.11 - PANIC in autocomplete

### ISSUE THREAD

**Issue by EmpireJones** [Microsoft/vscode-go#1929]
Steps to Reproduce:

1. Update to go 1.11
2. Delete/reinstall all tools (delete bin/pkg folders)
3. Restart vscode
4. Get PANIC in autocomplete

I think I followed all relevant steps in https://github.com/Microsoft/vscode-go/issues/1888 but am still getting a panic. Are there any other steps required for upgrading to Go 1.11?

**Comment by strtob01** [comment]
I tried a fresh install of Go 1.11 along with a fresh install of Visual Studio Code and also have the same problem.

**Comment by ramya-rao-a** [comment]
Are you using the new modules feature? If yes, then its not yet supported. If not, then follow the below:

- Close VS Code
- Check for any running process for `gocode`. If you find it, kill it.
- Open VS Code, Run `Go: Install/Update Tools`, select `gocode` and install it
- Try for auto-completions

**Comment by strtob01** [comment]
I just solved it. I had old gocode binaries in my PATH locations on my hard drive. I deleted all of them and the ran your instructions again and now it's working as expected.

**Comment by EmpireJones** [comment]
I still haven't figured this one out. I have it working on one of two computers.

Killing gocode processes and reinstalling gocode didn't help. I also tried rebooting and reinstalling the vscode-go extension.

Is there any way to output details of the panic?

**Comment by EmpireJones** [comment]
Figured out how to debug: `gocode -s -debug` from bin folder

Error is: `panic: embedded struct field without name?`
not sure if that helps me though...

**Comment by bjm88** [comment]
When do you plan to support the go 1.11 go.mod modules feature?  I'm getting weird package errors like it can't find the local go packages.     Example go.mod:
module company.com/product/identityservice

require (
	cloud.google.com/go v0.28.0 // indirect
        .....
)

replace company.com/product/go_common => ../go_common

**Comment by ramya-rao-a** [comment]
Closing this issue because:

- @strtob01 has the problem solved by deleting the old binaries
- @EmpireJones Looks like `gocode` itself is panicking. I am not sure what the extension can do in that situation :( Are you using Go modules? If yes, please try the [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)
- @bjm88 As mentioned above, please try the beta version and take a look at https://github.com/Microsoft/vscode-go/issues/1939

**Comment by EmpireJones** [comment]
Thanks, I created https://github.com/mdempsky/gocode/issues/66.
I'm not using go modules.
