### ISSUE TITLE
Indentation is replaced with tabs from spaces on save regardless of editor settings when this extension is enabled.

### ISSUE THREAD

**Issue by steviesama** [Microsoft/vscode-go#1930]
Steps to Reproduce:

1. Enable this extension.
2. Open a Go source code file with space indentation or convert to such indentation.
3. Save file and the space indentation will be replaced with tabs on save regardless of editor settings to the contrary.

**Comment by steviesama** [comment]
The format tool effects this. The only solution so far has be to pick a format tool that won't install so I guess the step is effectively skipped and when I manually format it to spaces and have the user settings setup properly it's fine. I was using goreturns...I think gofmt did it too...replacing spaces with tabs. Is there any way to change this? Though I'd prefer have an official option to skip the format tool step.

**Comment by ramya-rao-a** [comment]
Unfortunately, as you realized, its the formatting tool that is doing this and I am not aware of any workarounds at the moment
