### ISSUE TITLE
Feature Request: go.lintOnSave = "file"

### ISSUE THREAD

**Issue by jeffb4** [Microsoft/vscode-go#1931]
When using gometalint with all linters enabled, even a package lint can take a significant period of time. It'd be nice to have an additional go.lintOnSave option "file", to only run the linter on the file that was just saved.

**Comment by ramya-rao-a** [comment]
That sounds like a good idea.
We support the below linters today. Do you know if all of them support running on single files?
```
            "golint",
            "gometalinter",
            "megacheck",
            "golangci-lint",
            "revive"
```

PRs for this feature are most welcome. Code Pointers:
- [Build and Debug Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) to get started
- See [package.json](https://github.com/Microsoft/vscode-go/blob/0.6.89/package.json#L527) to add the new option
- See [goCheck.ts](https://github.com/Microsoft/vscode-go/blob/0.6.89/src/goCheck.ts#L104) to update the place from where lint on save is called
- See [goLint.ts](https://github.com/Microsoft/vscode-go/blob/0.6.89/src/goLint.ts#45) to update the actual calls to various linters

**Comment by jeffb4** [comment]
golint - supports individual files
gometalinter - allows individual files, but errors when they do not comprise a package
megacheck - allows individual files, but errors when they do not comprise a package
megacheck - allows individual files, but errors when they do not comprise a package
revive - supports individual files

given the general lack of robust support for single files, does this still seem like a good idea @ramya-rao-a  ?

**Comment by ramya-rao-a** [comment]
The event for file save gets fired for one file at a time. Therefore, we won't be falling under the "files not comprising a package" issue. So we should be good to go.

**Comment by ramya-rao-a** [comment]
@jeffb4 If you are working on this, wait a few days till October starts to win a t-shirt! See https://open.microsoft.com/2018/09/18/hacktoberfest-2018-microsoft/?WT.mc_id=hacktoberfest-twitter-beverst for more details

**Comment by brainsnail** [comment]
If @jeffb4 isn't working on it. I'd be interested in taking a shot at it.

**Comment by ramya-rao-a** [comment]
We haven't heard back from @jeffb4, so go ahead @brainsnail.

**Comment by brainsnail** [comment]
Hey @ramya-rao-a! 

I've got something sort-of-working in a branch, but I keep running into `"ENOENT: no such file or directory, open '[rootdirectoryofrepo]/.gitmodules'` when switching to the `file` option for `lintOnSave`. The call stack has the proper linting occurring - I'm declaring a variable and not using it in my Go code, but the lint result isn't it making it back up to the dev instance of VS Code. 

I'm not super familiar with the TypeScript / JavaScript workflow, so I apologize if there is an obvious approach to this that I haven't taken yet.  Any suggestions?

**Comment by ramya-rao-a** [comment]
@brainsnail Can you share the link to your branch?

**Comment by brainsnail** [comment]
@ramya-rao-a Yep, absolutely - https://github.com/brainsnail/vscode-go - I intend to clean up what I added in `goLint.ts` once I am able to verify the functionality, so this is definitely a WIP.

**Comment by ramya-rao-a** [comment]
`cwd` is always meant to have the current working directory. Looking at your changes, it has the file path instead when `lintOnSave` is set to `file`.

I believe the change should be that `lintOnSave` is set to `file`, the file should be passed as an argument.

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.92). Thanks @brainsnail!

**Comment by brainsnail** [comment]
Thank you @ramya-rao-a for being so patient and providing guidance as well!
