### ISSUE TITLE
Breakpoints set/removed during runtime are ignored until debugging is restarted

### ISSUE THREAD

**Issue by szszoke-apsis** [Microsoft/vscode-go#1934]
I am having an issue where when I set or remove a breakpoint while I debug my code, it is ignored until I stop the debugger and start it again. I found the issue to be present on both a Windows and an Ubuntu machine.

Here some minimal code to reproduce the issue:
main.go
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("Begin")
	time.Sleep(time.Duration(10) * time.Second)
	fmt.Println("End")
}
```

launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/main.go",
            "env": {},
            "args": [],
            "showLog": false,
            "trace": "verbose"
        }
    ]
}
```

### Breakpoint not hit
Verbose output:
```
Verbose logs are written to:
/tmp/vscode-go-debug.txt
3:24:54 PM, 9/21/2018
InitializeRequest
InitializeResponse
Using GOPATH: /home/<REDACTED>/go
Running: /home/<REDACTED>/go/bin/dlv debug practice --headless=true --listen=127.0.0.1:2345 --
API server listening at: 127.0.0.1:2345
InitializeEvent
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
Begin
SetBreakPointsRequest
All cleared
Creating on: /home/<REDACTED>/go/src/practice/main.go:11
End
continue state {"Running":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":0,"When":""}
TerminatedEvent
Error on CreateBreakpoint: Process 17803 has exited with status 0
All set:[null]
SetBreakPointsResponse
DisconnectRequest
```
Steps to Reproduce:

1. Start debugging the program using VS Code
2. Set a breakpoint at line 11 while the program is running

Actual behavior:
The breakpoint is not hit

Expected behavior:
The breakpoint gets hit

### Debugger pauses even though breakpoint was removed
Verbose output:
```
global vars [{"name":"statictmp_0","addr":5083264,"onlyAddr":false,"type":"string","realType":"string","flags":0,"kind":24,"value":"Begin","len":5,"cap":0,"children":[],"base":5036874,"unreadable":"","LocationExpr":"[block] DW_OP_addr 0x4d9080 ","DeclLine":0},{"name":"statictmp_1","addr":5083280,"onlyAddr":false,"type":"string","realType":"string","flags":0,"kind":24,"value":"End","len":3,"cap":0,"children":[],"base":5036474,"unreadable":"","LocationExpr":"[block] DW_OP_addr 0x4d9090 ","DeclLine":0}]
ScopesResponse
goroutines [{"id":1,"currentLoc":{"pc":4832223,"file":"/home/<REDACTED>/go/src/practice/main.go","line":11,"function":{"name":"main.main","value":4832048,"type":0,"goType":0,"optimized":false}},"userCurrentLoc":{"pc":4832223,"file":"/home/<REDACTED>/go/src/practice/main.go","line":11,"function":{"name":"main.main","value":4832048,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4532627,"file":"/usr/lib/go-1.10/src/runtime/asm_amd64.s","line":258,"function":{"name":"runtime.rt0_go","value":4532112,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4373072,"file":"/usr/lib/go-1.10/src/runtime/proc.go","line":109,"function":{"name":"runtime.main","value":4373072,"type":0,"goType":0,"optimized":true}},"threadID":18390},{"id":2,"currentLoc":{"pc":4374601,"file":"/usr/lib/go-1.10/src/runtime/proc.go","line":292,"function":{"name":"runtime.gopark","value":4374352,"type":0,"goType":0,"optimized":true}},"userCurrentLoc":{"pc":4374601,"file":"/usr/lib/go-1.10/src/runtime/proc.go","line":292,"function":{"name":"runtime.gopark","value":4374352,"type":0,"goType":0,"optimized":true}},"goStatementLoc":{"pc":4373957,"file":"/usr/lib/go-1.10/src/runtime/proc.go","line":237,"function":{"name":"runtime.init.4","value":4373904,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4373984,"file":"/usr/lib/go-1.10/src/runtime/proc.go","line":240,"function":{"name":"runtime.forcegchelper","value":4373984,"type":0,"goType":0,"optimized":true}},"threadID":0},{"id":3,"currentLoc":{"pc":[...]
ThreadsResponse [{"id":1,"name":"main.main"},{"id":2,"name":"runtime.gopark"},{"id":3,"name":"runtime.gopark"},{"id":4,"name":"runtime.gopark"},{"id":5,"name":"runtime.gopark"}]
VariablesRequest
VariablesResponse []
ContinueRequest
ContinueResponse
End
continue state {"Running":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":0,"When":""}
TerminatedEvent
DisconnectRequest
HaltRequest
DisconnectRequest to parent
```
Steps to Reproduce:

1. Set a breakpoint at line 11
2. Start debugging the program using VS Code

Actual behavior:
The debugger pauses at the line where the removed breakpoint was

Expected behavior:
The program exits without the debugger pausing

**Comment by rothskeller** [comment]
I am seeing this as well, in a different environment.  My environment is OSX 10.13.6, Go 1.11, vscode 1.27.2, dlv 1.1.0, vscode-go 0.6.89.  The behavior is the same:  breakpoints don't work when added after the program starts running, but once you restart the program they do.

**Comment by Shagrat2** [comment]
I am seeing this as well, in a different environment. OSX 10.14.1, Go 1.11.3 vscode 1.29.1, dlv 1.1.0, vscode-go 0.6.88

**Comment by segevfiner** [comment]
This is a limitation of delve. It can't set breakpoints while running, only while stopped. vscode-go should communicate this better to the user

**Comment by segevfiner** [comment]
This is a limitation of Delve. It can't set breakpoints while running, only while stopped. It should be communicated better to the user, but it's not really clear how this should be handled in the debug adapter protocol. Should the breakpoints request simply be delayed? Should the breakpoints be added unverified with a message explaining why? If so, what about breakpoints which are removed?

@ramya-rao-a

**Comment by ramya-rao-a** [comment]
@segevfiner is right. Delve cannot add/remove breakpoints while running.

> It should be communicated better to the user

We can return an error message from [setBreakpointsRequest](https://github.com/Microsoft/vscode-go/blob/b04fe03d5f24287424965e961c15f93ce69a1a2e/src/debugAdapter/goDebug.ts#L699) if we somehow can figure out if the debug session has not started yet or a breakpoint is hit.

@isidorn Inside the `setBreakpointsRequest`, is there a way for a debug adapter to know if the current debug session has hit a breakpoint or not?

**Comment by isidorn** [comment]
@ramya-rao-a the debug adapter is sending to vscode if the debug session stopped or not. So the debug adapter could simply remember if it already sent a [`StoppedEvent`](https://github.com/Microsoft/vscode/blob/f886dd4fb84bb82478bfab4a68cd3f31b32f5eb5/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L88) with `readon` `Breakpoint`

Regarding breakpoints request, there is only [`setBreakpoints`](https://github.com/Microsoft/vscode/blob/f886dd4fb84bb82478bfab4a68cd3f31b32f5eb5/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L459) request which sets breakpoints for a single source location. The debug adapter could remember those breakpoints and compute if a setBreakpoints request is removing a breakpoint

**Comment by segevfiner** [comment]
It seems that breakpoints added while running actually won't be hit ever. Even after you stop once on a different breakpoint, which gives the debug adapter an opportunity to register breakpoints.

**Comment by ramya-rao-a** [comment]
Thanks @isidorn 

To summarize:

- Both adding and removing of breakpoints result in the `setBreakpointsRequest` being called. Therefore, this would be the right place to show an appropriate error message to the user (using `logError()`) if the program is running
- `continueRequest` needs to keep track of whether at present any breakpoint is hit or not

PRs are welcome to fix this bug.
Code Pointers:
- [Build and Debug extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- [Debug the debugger](
https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter)
- Both `setBreakpointsRequest` and `continueRequest` are in the `goDebug.ts` file

**Comment by lggomez** [comment]
With Delve unable to apply the breakpoint changes being a separate issue, what @isidorn suggests is an optimization related to #1660, which we should plan to do either way

**Comment by ramya-rao-a** [comment]
With the latest update to the Go extension (0.9.0), we now can add/remove breakpoints when the program is running.
