### ISSUE TITLE
Debugger does not stop on breakpoints when debugging tests

### ISSUE THREAD

**Issue by jadolg** [microsoft/vscode-go#1935]
Hey there,
I'm writing an application and trying to debug one of my tests using the `debug test` option on top of the method 
![image](https://user-images.githubusercontent.com/5427672/45894840-9315e180-bd9d-11e8-85d6-7cbb7eb10046.png)
and I have set a breakpoint on this method. When the option is clicked my test runs but it won't stop on the breakpoint.
The breakpoint is listed on the breakpoints list and marked as a red dot in the IDE.
![image](https://user-images.githubusercontent.com/5427672/45894900-c193bc80-bd9d-11e8-9ca2-46c8f9c7fd9e.png)

**Comment by jadolg** [comment]
Exactly the same behavior. Is there any other way to collect more information?

**Comment by ramya-rao-a** [comment]
Yes of course, but before that try one more thing.

Instead of using the `debug test` codelens, use the debug configuration for debugging tests from the launch.json file.
See https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson

**Comment by jadolg** [comment]
This is the output I'm getting when I set the flags. The file and line exist both.
```
SetBreakPointsRequest
All cleared
Creating on: /media/akiel/data/GOLIBS/src/gitlab.cu.aleph.engineering/aleph.engineering/hivedm/other_test.go:6
Error on CreateBreakpoint: could not find /media/akiel/data/GOLIBS/src/gitlab.cu.aleph.engineering/aleph.engineering/hivedm/other_test.go:6
All set:[null]
```

**Comment by jadolg** [comment]
yes I'm using symlinks

**Comment by jadolg** [comment]
I don't have much space on my main harddrive so I have a lot of things symlinked :blush: 
```
$ dlv test
Type 'help' for list of commands.
(dlv) b other_test.go:6
Breakpoint 1 set at 0x8b4081 for gitlab.cu.aleph.engineering/aleph.engineering/hivedm.TestSimple() /home/akiel/GOLIBS/src/gitlab.cu.aleph.engineering/aleph.engineering/hivedm/other_test.go:6
(dlv) c
2018/09/27 19:46:44 Downloading http://127.0.0.1:45779/testconfig.yml...
2018/09/27 19:46:44   200 OK
2018/09/27 19:46:44 Download saved to ./test_data/download/testconfig.yml
2018/09/27 19:46:44 Downloading http://127.0.0.1:45779/filenotfound...
2018/09/27 19:46:44   404 Not Found
2018/09/27 19:46:44 Download failed: server returned a non-2XX status code
2018/09/27 19:46:44 Downloading http://127.0.0.1:36503/test_photo.jpg...
2018/09/27 19:46:44   200 OK
2018/09/27 19:46:44 Download saved to ./test_data/download_compress_split/FILE
> gitlab.cu.aleph.engineering/aleph.engineering/hivedm.TestSimple() /home/akiel/GOLIBS/src/gitlab.cu.aleph.engineering/aleph.engineering/hivedm/other_test.go:6 (hits goroutine(79):1 total:1)(PC: 0x8b4081)
     1: package hivedm
     2:
     3: import "testing"
     4:
     5: func TestSimple(t *testing.T) {
=>   6:         a := 1
     7:         t.Log(a)
     8: }
(dlv)
```

**Comment by ramya-rao-a** [comment]
dlv created the breakpoint at `/home/akiel/GOLIBS/src/gitlab.cu.aleph.engineering/aleph.engineering/hivedm/other_test.go:6` where as vs code is trying to do so at `/media/akiel/data/GOLIBS/src/gitlab.cu.aleph.engineering/aleph.engineering/hivedm/other_test.go:6`

- Is the file physically under `/home/akiel/GOLIBS/` or `/media/akiel/data/GOLIBS`?
- What is the path of the folder opened in VS Code?
- What is the path you get when you right click on the `other_test.go` file in the explorer and choose `Copy Path`? Is that the same you see when you hover on the editor tab where the file is open?

**Comment by jadolg** [comment]
* `/home/akiel/GOLIBS/` is a symlink for `/media/akiel/data/GOLIBS/`
* I always open my project @ `/home/akiel/GOLIBS/`
* The path resulting from `Copy Path` is `/media/akiel/data/GOLIBS/src/gitlab.cu.aleph.engineering/aleph.engineering/hivedm/other_test.go`

**Comment by ramya-rao-a** [comment]
Sorry for my ignorance, so the real files are under `/media/akiel/data/GOLIBS/` correct?

**Comment by jadolg** [comment]
indeed

**Comment by ramya-rao-a** [comment]
The last think I need to know is the working directory from which dlv was launched by VS Code.

- Install the [beta-version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension
- Add `"trace": "verbose"` back to your debug configuration and debug using this configuration. In the logs, you will now get statements like `Current working directory:`. Let me know if that points to `/media/akiel/data/GOLIBS/...` or `/home/akiel/GOLIBS/...`

**Comment by ovidiub13** [comment]
I'm also experiencing this issue while using a symlinked directory.
VS Code:
```
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.10-200.fc29.x86_64
```
Go extension version : 0.9.2

dlv version
```
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```

**Comment by tonywenoracle** [comment]
Yes, I experienced same issue. The symlink is the root cause. After changing to use physical path, everything works fine.

**Comment by suquant** [comment]
Hi all,

I got same issues and I was tried finding issues...
My investigations reveal that the problem may be in cache system of dlv.

When do you using smart variables in your launch.json configuration file like in example below.
 
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch server with smart var",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/cmd/server/main.go",
            "args": ["server"],
            "trace": "verbose"
        },
        {
            "name": "Launch server with full path",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "/Users/user/go/src/xxx/xxx/project/cmd/server/main.go",
            "args": ["server"],
            "trace": "verbose"
        }
    ]
}
```

So in case "Launch server with full path" it will works fine if that break points did not used in "Launch server with smart var" but in case if used, that breakpoints will failed with error "Error on CreateBreakpoint: could not find" in both configs!

**Comment by jtackaberry** [comment]
I just got bit by this bug involving symlinks as well.  In my case, `/home` is symlinked to an NFS volume mounted via autofs.  My .code-workspace file is in my project root and sources `.` so the easy workaround was to open the workspace from the absolute path (`/net/nas/home`), rather than under `/home`. 

This is also with Insiders and the remote development feature (which is pretty cool).

**Comment by ramya-rao-a** [comment]
I am not able to replicate this issue locally, so if anyone seeing this issue is willing to set up a local dev setup of the extension, then I can help guide the process.

- [Set up local dev env for extension](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- [Debug the debugger](https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter)

**Comment by robheerdink** [comment]
also experiencing this bug, debugger does not stop at symlinks under linux.
re-opening project through non symlink folder works

**Comment by ramya-rao-a** [comment]
Thanks for reporting @robheerdink 

While we have seen quite a few reports regarding debugging not working when using symlinks, we haven't been able to get a repro of it.

We would greatly appreciate it if you can [set up a local dev environment of this extension](https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter) and help in figuring out where exactly we are failing.
