### ISSUE TITLE
Test Plan for Sept 2018 (0.6.90)

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1939]
If you got a notification from this issue, then you are part of the next update to the Go extension.
Thanks and Welcome!

Here I will be listing the features and the bug fixes that will go in the next update along with the the folks who logged the bugs/feature requests, those who upvoted it, and those who fixed it by sending PRs.

The idea is to get the folks behind this update to give the update a trial run before I release it.
I always do basic testing before every update. But because I dont work with Go in my day job, I always feel that someone who does Go more than me can help in testing tremendously.

And when I say "test", you can do a minimum pass of just installing the update and then do nothing special other than going about using VS Code like you do everyday. Or you can test the feature you requested/implemented or the bug you logged/fixed. Or you can test all of the below. Every bit helps.

Drop in a comment in this issue after 2 or 3 days of [installing the update](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) with your findings.

**If you are using Go modules:**

- Go to definition, symbol info on hover and Signature Help when the setting `go.docsTool` is set to `gogetdoc` will now work. You will be prompted to update `gogetdoc`. @zmb3
- Go to definition feature will work event if you havent changed the `go.docsTool` setting. You will be prompted to install a [fork](https://github.com/ianthehat/godef) of `godef` that we are testing. @stamblerre
- Auto-completion. You will be prompted to install a [fork](https://github.com/stamblerre/gocode) of `gocode` that we are testing as well as to update the `gopkgs` tool. Currently it only works if the package is already imported and used atleast once. @stamblerre, @uudashr
- `Go: Add Import` & `Go: Browse Packages` commands that will show the appropriate packages from the current module instead of GOPATH @uudashr 
- [Go modules in VS Code](https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code) is the wiki that will track the status of Go module support

**Features not related to Go modules**

* @biancarosa, @lkarlslund 
    * New commands `Go: Benchmark File`, `Go: Benchmark Package` and codelens to run all the benchmarks in current file & package respectively. [Feature Request 1522](https://github.com/Microsoft/vscode-go/issues/1522) with [PR 1898](https://github.com/Microsoft/vscode-go/pull/1898) & [PR 1899](https://github.com/Microsoft/vscode-go/pull/1899)

* @jeffbean
    * New setting `go.generateTestsFlags` to provide flags for the `gotests` tool when generating tests using any of the `Go: Generate Unit Tests...` commands. [PR 1841](https://github.com/Microsoft/vscode-go/pull/1841)
    
* @johan-lejdung
    * New setting `go.testTags` to be used for running tests. This way, you can use the existing `go.buildTags` for compiling and a different set of tags for running tests. [Feature Request 1842](https://github.com/Microsoft/vscode-go/issues/1842) implemented with [PR 1877](https://github.com/Microsoft/vscode-go/pull/1877)

* @ragurney, @mgood
    * Skip the blank identifiers in file outline feature. Be it in the outline view in the explorer or the one that shows up when running `Go to symbol in file` command. [Bug 1889](https://github.com/Microsoft/vscode-go/issues/1889) fixed with [PR 1893](https://github.com/Microsoft/vscode-go/pull/1893)

* @svipben
    * Fix accessibility issues with the `Analysis Tools Missing` button in the status bar which shows up when you don't have the required Go tools installed. [PR 1922](https://github.com/Microsoft/vscode-go/pull/1922)

* @alecthomas
    * Improve snippets for `iferr` and `forr` i.e  "if err ..." the "for range". [Feature Request 1920](https://github.com/Microsoft/vscode-go/issues/1920) implemented with [PR 1924](https://github.com/Microsoft/vscode-go/pull/1924)

* @Charliekenney23, @antong
    * Create new tmp directory for each session to avoid insecure use of the temporary files created by the extension. Fixes [Bug 1905](https://github.com/Microsoft/vscode-go/issues/1905) with [PR 1912](https://github.com/Microsoft/vscode-go/pull/1912)

* @shreyu86
    * Provide auto-completions for symbols from unimported packages even when the package name has multiple matches. Fixes [Bug 1884](https://github.com/Microsoft/vscode-go/issues/1884) with [PR 1900](https://github.com/Microsoft/vscode-go/pull/1900)

* @ramya-rao-a
    * @antong Use random port instead of hard-coded 2345 when running delve. Fixes [Bug 1906](https://github.com/Microsoft/vscode-go/issues/1906)
    * @alex-kovoy Fix issue where tests using the check package cannot be run using the `Go: Test File` command. [Bug 1911](https://github.com/Microsoft/vscode-go/issues/1911)
    * @FiloSottile Disable module support when installing the Go tools. Fixes [Bug 1919](https://github.com/Microsoft/vscode-go/issues/1919)
    * @gertcuykens, @lggomez Use version 2 of delve apis by default instead of version 1. [Feature Request 1876](https://github.com/Microsoft/vscode-go/issues/1876)

**Comment by shreyu86** [comment]
✅ Provide auto-completions for symbols from unimported packages even when the package name has multiple matches. and testing other new features and fixes.

**Comment by johan-lejdung** [comment]
`go.testTags` is working fine 👌😍

**Comment by ragurney** [comment]
Blank identifiers in outline fix looks good :shipit:

**Comment by ramya-rao-a** [comment]
@shreyu86, @johan-lejdung, @ragurney Thanks for confirming!
Would you mind giving some of the other features a look as well?

**Comment by antong** [comment]
I've been casually using this for two days now. Nothing out of the ordinary has happened. The tempdir stuff seems to be working in that tempdirs do appear with expected contents. vscode-go-debug.txt still goes directly into TEMP with the predictable name, so that fix seems to not have gone in. I noticed the iferr snippet improvement, and that is cool!

**Comment by gertcuykens** [comment]
Not in the list but I think setting `export GO111MODULE=on` in your shell so that modules are always used has performance issues. Unfortunately I don't have more details and time to investigate, I can only mention that I think using modules has a more sophisticated inpact on `vscode-go`

**Comment by ramya-rao-a** [comment]
@gertcuykens That can very well be the case. If you find more details, please do log a new issue and we can investigate further.

**Comment by lkarlslund** [comment]
Great job on this release so far.

I have a huge project using Go Modules, with many local subpackages imported). The latest vsix (beta 6) works way better than the previous versions. It does not seem bogged down on CPU nearly as much. Previously I had like 10-12 go.exe running under VS Code when saving stuff, but this seems to have dissapeared.

The version of godef that the plugin installs does not support Go Modules, and that breaks that functionality. There is a fork at https://github.com/ianthehat/godef which works, and you might consider switching to that.

When are you enabling languageserver for Windows? :)

**Comment by lkarlslund** [comment]
Benchmark file and package works great!

**Comment by uudashr** [comment]
@lkarlslund better to ask the owner of https://github.com/ianthehat/godef to merge `godef` to the original. Last commit https://github.com/rogpeppe/godef Sep 12, 2018, still active.

**Comment by jeffbean** [comment]
The `go.generateTestsFlags` settings change tested. Looking good!

**Comment by ramya-rao-a** [comment]
**To those who use Go modules:**

The Go tools team have forks of the `godef` and `gocode` tools that work with Go modules. These 2 tools drive the `Go to definition` and auto-completion features respectively. The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has support for both.

Please install this beta version, follow through the prompts to install/update the tools and let us know how the `Go to definition` and auto-completion features are working out for you.

**Comment by alecthomas** [comment]
With that new beta I no longer get completions on packages:

![image](https://user-images.githubusercontent.com/41767/46117137-f0e57600-c242-11e8-8567-19c3121ed563.png)

Previous beta:
![image](https://user-images.githubusercontent.com/41767/46117149-09559080-c243-11e8-9e3d-80919d674a3c.png)

**Comment by ramya-rao-a** [comment]
@alecthomas 

- Are you using Go modules?
- Run `gocode close` and/or `gocode-gomod close` and try again.
- If that still doesnt work, run `gocode close` and `gocode -s -debug`. (Replace with `gocode-gomod` if using modules). This will start gocode in debug mode. Try for completions in VS Code. The terminal running gocode in debug mode should print out results (number of candidates or error message)
- If you see results in debug mode, but not in VS Code, then our last resort is to debug VS Code. Get latest from master and add a breakpoint at https://github.com/Microsoft/vscode-go/blob/master/src/goSuggest.ts#L170 to see if `gocode-gomod` or `gocode` is being used. Another breakpoint at https://github.com/Microsoft/vscode-go/blob/master/src/goSuggest.ts#L211 will show the output from gocode itself

**Comment by ramya-rao-a** [comment]
@alecthomas So from what I can understand you are using modules but are also vending the dependencies? And it is for such vendors dependencies that you are not getting completions? If so, can you open a new issue with a sample code (preferably a small repo that I can just clone)?

**Comment by uudashr** [comment]
Ya... same here with me. For project under GOPATH and also the module project. Even the `fmt` doesn't shows any completion.

**Comment by stamblerre** [comment]
@wolfeidau I wasn't able to reproduce using your case. The very first completion is a little slow, but after that, the stdlib was completing fine.

**Comment by alecthomas** [comment]
Another data point: `gocode-gomod` is *much* slower than `gocode`, when it does work. On a large codebase it takes ~5 seconds to bring up a local receiver completion list whereas `gocode` is basically instantaneous :(

**Comment by ramya-rao-a** [comment]
@alecthomas It is known that `gocode-gomod` is generally slower. But it is to be used when `gocode` doesnt give results. 
If what you said before still holds and you see this when you vendor your dependencies and use modules at the same time, then as requested in https://github.com/Microsoft/vscode-go/issues/1939#issuecomment-424950452, can you please log a new issue with a small sample repo?

**Comment by alecthomas** [comment]
@ramya-rao-a I'm guessing it is environment-specific, as @wolfeidau  has produced a test repo that fails for him, but does not for @stamblerre. So I don't think I'd be able to add anything that @wolfeidau 's existing repo doesn't already.

**Comment by uudashr** [comment]
Same here with me... the autocomplete doesn't works by using @wolfeidau case

**Comment by ramya-rao-a** [comment]
@wolfeidau 

Using your repo and the repro steps in the README of your repo, I do see that there is no completions for the `base64` package. But, once I save the file after typing `base64.anything()`, subsequent completions work as expected.

#1944 is tracking the case where auto-completions dont work, unless a package has been imported and used atleast once in the saved version of the file. I believe that is what is happening in this case.

Can you try saving the file after any usage of the stdlib and try again?

@alecthomas 
I am specifically interested in your case because it is the case of `gocode` working but not `gocode-mod` when using Go modules along with vendored dependencies. This is different from @wolfeidau's case.

**Comment by wolfeidau** [comment]
@ramya-rao-a I have tried doing as you instructed. 

Open `main.go` and add a line with `base64.anything()`, then save the file, then remove `.anything()` and type something else and I still get.

```
2018/10/04 07:35:48 -------------------------------------------------------
package main
import "encoding/base64"

import "github.com/sirupsen/logrus"

func main() {
	logrus.Printf("logging")

	base64.#

}
2018/10/04 07:35:48 -------------------------------------------------------
go list stderr <<# main.go
./main.go:8:2: undefined: base64
>>
2018/10/04 07:35:48 Elapsed duration: 150.517592ms
2018/10/04 07:35:48 Offset: 0
2018/10/04 07:35:48 Number of candidates found: 0
2018/10/04 07:35:48 Candidates are:
2018/10/04 07:35:48 =======================================================
```

I started digging into the fork which @stamblerre is currently maintaining, then quickly got lost in the go tools packages adding printf statements.

We really need to know where `gocode-mod` is looking for things, we only know what it found at the moment..

It would be amazing if there was a bit more tracing in the `gocode-mod` and more importantly the underlying libraries / routines as they don't give up their secrets willingly :) 

I have updated the readme in my with my `go env` https://github.com/wolfeidau/test-gocode repo.

**Comment by ramya-rao-a** [comment]
@wolfeidau I've logged #1963 to continue the discussion

**Comment by ramya-rao-a** [comment]
Everyone,

Thanks a lot for the participation!

0.6.90 version is now released.

If you have further feedback, please feel free to open an issue.
