### ISSUE TITLE
Unable to parse correctly libraries for a different OS

### ISSUE THREAD

**Issue by Nhoya** [Microsoft/vscode-go#1941]
Hi, I have a small issue with the latest version of the extension.

I'm unable to use the extension calling methods for other platforms since the function is not recognised 

Steps to Reproduce:

On linux just create a file with:

```
package main

import (
	"fmt"

	"golang.org/x/sys/windows/registry"
)

func GetSystemInfo() error {

	k, err := registry.OpenKey(registry.LOCAL_MACHINE, `SOFTWARE\Microsoft\Windows NT\CurrentVersion`, registry.QUERY_VALUE)
	if err != nil {
		return (err)
	}
	defer k.Close()
	productName, _, err := k.GetStringValue("ProductName")
	if err != nil {
		return (err)
	}

	fmt.Printf("%s\n", productName)
	return nil
}

func main() {
	err := GetSystemInfo()
	if err != nil {
		panic(err)
	}
}
```

as you can see here the call to ```registry.OpenKey(registry.LOCAL_MACHINE, `SOFTWARE\Microsoft\Windows NT\CurrentVersion`, registry.QUERY_VALUE)``` is not recognised 

![immagine](https://user-images.githubusercontent.com/7293260/46019178-cb8a2800-c0db-11e8-80cc-c8afbc1e7546.png)

building it manually using `GOOS=windows` will build succesfully

**Comment by Nhoya** [comment]
Ok I found out that the issue also affects the package creation, creating a file called `myfile_windows.go` and adding it to a new package will trigger an error `an't load package: package my_project_path_here: build constraints exclude all Go files in my_project_path_here` I suspect this may be related to https://github.com/golang/go/issues/24068

**Comment by ramya-rao-a** [comment]
In your first comment, did the file have the suffix `_windows.go`? 

If no, then you have to set GOOS=windows specifically, otherwise there is no way for the editor to know which platform to use for GOOS

If yes, this issue is covered in #1848.

**Comment by Nhoya** [comment]
Yes you are indeed right, my issue is coverd in https://github.com/Microsoft/vscode-go/issues/1848 I think we can close this and continue there

**Comment by ramya-rao-a** [comment]
Thanks @Nhoya 
Please upvote #1848 so that we know how many users are seeing this issue
