### ISSUE TITLE
Import comment occurred error - "cannot find main module"

### ISSUE THREAD

**Issue by edp1096** [Microsoft/vscode-go#1945]
![import_error](https://user-images.githubusercontent.com/15924482/46124736-c3a7c080-c260-11e8-953e-6889896d4c71.png)

Go extension config
- go.inferGopath : true
- go.toolsGopath : same as global GOPATH

Tested code
* path of import comment is not real.
```go
package main // import "github.com/practice-golang/pkghello"

import (
	hell "github.com/practice-golang/go111module-pkghello/v3"
)

func main() {
	hell.Hello()
}
```

Steps to Reproduce:
1. Works fine with below path structure, workspace as main package root.
* When ```go mod tidy```, tool try to download pkgs to global gopath
* Because occurring error ```$GOPATH/go.mod exists but should not```, go.inferGopath set false
```sh
$workspace (=pkghello)
└─pkghello.go
```

2. Show error and could not install but debug by press F5 or build is well, workspace as GOPATH.
* When ```go mod tidy```, tool try to download pkgs to workspace
```sh
$workspace
└─src
    └─pkghello
        └─pkghello.go
```

Inspite of inferGopath set as true, some tools which related to packages, is looked try finding packages at global gopath.

My bad, I forgot which version using.  
This is a situation when using vscode-go beta8.

**Comment by ramya-rao-a** [comment]
Using your sample code and running `go mod tidy`, I dont see any errors. 

Is the `pkghello` folder under your global GOPATH?
To use Go modules, your code should be outside of GOPATH

**Comment by ramya-rao-a** [comment]
> Is there needed that inferGopath should be set false?

If there is no `src` in your file path, then setting `inferGopath` to `true` will have no effect. But it is safer to set it to `false` when using Go modules.

> When go mod tidy, tool try to download pkgs to workspace
$workspace
└─src
    └─pkghello
        └─pkghello.go

Here `$workspace` is your global gopath?
You are saying that running `go mod tidy` moved or copied your source files to the global gopath?

**Comment by ramya-rao-a** [comment]
Is there any reason you have the `src` folder under `pkghello`? When `inferGopath` is set to `true`, it will set `workspace/pkghello` as GOPATH because your file is under `workspace/pkghello/src`. 

Therefore, packages get created under `workspace/pkghello/pkg`. At this point if you have `GO111MODULE` set to `off` or `auto`, then Go assumes you don't want to use modules.

If you set `GO111MODULE` to `on`, the modules will be used and packages will get created under `workspace/pkghello/pkg/mod`

To avoid all the confusion, I would strongly suggest to set `infergopath` to `false` when using modules.

**Comment by edp1096** [comment]
Because, I want to manage each projects separately. I don't want to mix pkg from several projects as my previous mention.  
With ```dep```, go.inferGopath gave me huge help until go 1.10.  

As [#2 in this](https://github.com/golang/go/wiki/Modules#how-to-define-a-module), I understood that ```go mod & project in gopath``` would give same effect as using dep, but maybe not :'(.

Thank you for your kindness.

Closing.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @edp1096 

I have made a change to disable the `infergopath` setting automatically if you have it on when using Go modules. This change is out in the latest update to this extension (0.6.90)
