### ISSUE TITLE
[proposal] Visualising inline/escape analysis output

### ISSUE THREAD

**Issue by prateek** [microsoft/vscode-go#1948]
Hey all,

I'd like to have VS Code visualise the output of the Go compilers escape analysis/inlining behaviour. For more context: http://www.agardner.me/golang/garbage/collection/gc/escape/analysis/2015/10/18/go-escape-analysis.html 

Currently, I go to the command line to find this information and have to grep and try to match up lines by hand. It'd help immensely if I could instead have this pop up in VS Code with some trigger. 

Two ways I can imagine doing this:
(1) Writing a "linter" and using the 'Problems' view. 
![screen shot 2018-09-28 at 21 31 49](https://user-images.githubusercontent.com/199982/46239380-f8ea0680-c365-11e8-9f28-10cc4e903d7b.png)

(2) Using code overlays (similar to "run test"/etc). 

What do you think?

**Comment by lkarlslund** [comment]
That would be really nice. I'm doing the same as you manually, when optimizing code for inlining.

**Comment by Southclaws** [comment]
I've used this recently and had the same thought. For now, I made a quick tasks.json for it:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Escape Analysis",
      "type": "shell",
      "command": "go build -gcflags '-m -m'",
      "problemMatcher": {
        "pattern": {
          "regexp": "^(.*):(.*):(.*): (.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "message": 4
        },
        "fileLocation": "relative"
      }
    }
  ]
}
```

But it would be great to have a more in-built feature for this.

**Comment by nealot** [comment]
Maybe this request could encompass various profiling features? Integration with [pprof](https://github.com/google/pprof) would be very attractive to me.

**Comment by ramya-rao-a** [comment]
Thanks for logging this feature request @prateek 

This definitely can be done by modeling it after our build/lint/vet process such that the analysis appears in the problems view. 

> Using code overlays (similar to "run test"/etc).

i didn't understand this though. Can you elaborate on this?

@Southclaws Tasks is definitely a good way to do this. I am guessing we can automatically create the task by defining a [task provider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TaskProvider)

**Comment by guiguan** [comment]
@Southclaws to make your task more stable:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Escape Analysis",
            "type": "shell",
            "command": "go build -gcflags '-m -m' $(dirname github.com/guiguan/test-proj/${relativeFile})",
            "problemMatcher": {
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+): (.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "message": 4
                },
                "fileLocation": "relative"
            },
        }
    ]
}
```

**Comment by FiloSottile** [comment]
This would be great, along with bounds checks (`-gcflags="-d=ssa/check_bce/debug=1"`).

**Comment by dgryski** [comment]
Related: https://github.com/loov/view-annotated-file

**Comment by tbg** [comment]
For anyone else wondering, this is what @guiguan's proposal looks like

![image](https://user-images.githubusercontent.com/5076964/61624293-a113e780-ac78-11e9-9866-46ccdd1ab92b.png)

**Comment by ramya-rao-a** [comment]
I do believe this is a cool feature to have, although I am afraid I don't believe this extension is the right place for it.

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features.

Therefore, one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.
