### ISSUE TITLE
out-line use high cpu

### ISSUE THREAD

**Issue by Qiaojiawei** [Microsoft/vscode-go#1949]
Problem Datail: 
When i use vscode edit  my go file, the cpu usage is very high, especially when the edited file was a go test file.
Steps to Reproduce:
1.open the go test file, add a go test function 
2.you will found that it was very slow, the editer is  stucked
3.the process manager displayed that there are many go-outline.exe running( at least 4).
![test](https://user-images.githubusercontent.com/26373243/46239978-17d2b200-c3d3-11e8-9445-d47a579ab245.PNG)

![outline-task](https://user-images.githubusercontent.com/26373243/46239817-b7427580-c3d0-11e8-9cd7-8ebef48c8e03.png)

[helloworld.zip](https://github.com/Microsoft/vscode-go/files/2430179/helloworld.zip)

**Comment by Qiaojiawei** [comment]
i have try to delete the out-line.exe, then there is ok, but go test run buttion is missed.

**Comment by Qiaojiawei** [comment]
i have test my workspace in my colleague's environment, it seems that there no go-outline.exe runing when he edit the test file, or its too fast that i can't catch?

**Comment by ramya-rao-a** [comment]
@Qiaojiawei Thanks for reporting.

The `go-outline` tool is for 2 separate features in the background:
- The outline view in the explorer
- The codelens (buttons) for `run tests` and `debug tests` that you see above each test function.

Let's figure out which of the 2 features are resulting in the high cpu usage.

Please add the below in your setting to disable the codelens (buttons) for `run tests` and `debug tests`
```
"go.enableCodeLens": {
	"references": false,
	"runtest": false
}
```

Now, try to edit your test file. If you still see `go-outline` taking a lot of CPU then its because of the outline view.

**Comment by Qiaojiawei** [comment]
@ramya-rao-a   sorry for the late replay,we just put a long vacation. 
I have add the setting you wrirte here in the Setings.json, then edit the go file, the cpu run at 40%~50%(before its 100%s), so  whats the problem?

**Comment by ramya-rao-a** [comment]
Can you disable the outline view as well and then see what the CPU usage for `go-outline` is?

![image](https://user-images.githubusercontent.com/16890566/46624649-54df2880-cae6-11e8-8f03-44774d6717cd.png)

**Comment by Qiaojiawei** [comment]
@ramya-rao-a  thanks for replay, my operate step as follows:
1)nothing changed, then cpu usage is 100% when i edit the go file

2)add  _"go.enableCodeLens": {"references": false,	"runtest": false}_ to the settings.json, the cpu usage is about 50%~70%.
![1](https://user-images.githubusercontent.com/26373243/46639282-bad7b880-cb97-11e8-95f3-a33e4e1ccd81.png)

3)nothing changed, but disable outline, the cpu usage is 100%.
![3](https://user-images.githubusercontent.com/26373243/46639393-45b8b300-cb98-11e8-9fa7-af47bacb91bd.png)

4)add  _"go.enableCodeLens": {"references": false,	"runtest": false}_ to the settings.json， then disable outline, the cpu usage is about 20%
![2](https://user-images.githubusercontent.com/26373243/46639295-c5924d80-cb97-11e8-96fa-35d570993097.png)


so i guess CodeLens spend cpu 100%, outline view spend 50%?

**Comment by ramya-rao-a** [comment]
Thanks for the detailed steps!

Can you try the same thing again with a smaller simpler test file?
And does this happen only when editing test files? What about non-test Go files?

**Comment by Qiaojiawei** [comment]
@ramya-rao-a  I have test the simple go program like follows:
func main(){

	log.Println("Hello world")
	log.Println("Hello world 11")
	log.Println("Hellow")
	log.Println("Hellow")
	log.Println("Hellowr")
	log.Println("Hello  world")
	log.Println("Hello word2 ")
	log.Println("Hello world 3")
	log.Println("Hello world 4")
	log.Println("Hello world5")
}


when type a line, the cpu usage is 100% percent...
i have count the cpu usage as follows:
![default](https://user-images.githubusercontent.com/26373243/46741306-56237780-ccd7-11e8-9eb5-c7523f651edd.PNG)

the last column data is cpu average usage in 60s, the data count as below:
gocode.exe  17.55  11.40  9.77  9.42  8.83  8.65  7.84  7.67  6.99  6.57  6.56  6.34
gopkgs.exe  8.41  8.11 
conhost.exe 7.84  6.40 
go-outlint.exe 7.49

get the cpu usage picture:
![default](https://user-images.githubusercontent.com/26373243/46742187-19588000-ccd9-11e8-8fe0-8b3e6b619d08.PNG)

so gocode.exe spends mostly cpu, i don't know why this happened, i have same compute with my colleague， in his computer everything is ok, is there any method to find out why gocode.exe use so many cpu resource?
i'm doubt about that when type a word in the editor, the gocode.exe is call every time? so there are so many gocode.exe running...

**Comment by Qiaojiawei** [comment]
i cannot find why this happen in my computer, maybe its really some configure is wrong, i have give up it... the issue can be closed.
