### ISSUE TITLE
The text editor colors changed with the last update

### ISSUE THREAD

**Issue by maxence-charriere** [Microsoft/vscode-go#195]
Really liked the almost all blue text colors.
Please revert the change on the color or make a option setting to have the old one.

**Comment by mattetti** [comment]
@maxence-charriere are you sure you didn't switch theme, check the Jan update on themes: https://code.visualstudio.com/updates#vscode  you might just need to switch to Dark+

**Comment by egamma** [comment]
>Please revert the change on the color or make a option setting to have the old one.

The old one is available as `Dark (Visual Studio)` or `Light (Visual Studio)`..

**Comment by maxence-charriere** [comment]
I didn't changed anything, I was on the dark theme all the time.
Before some part of the code like variables was in blue. 

Code asked me to update yesterday and change a lot of blue part in white.
I know it's not a big issue but the code was (in my tastes) more readable than now, it was one of the reason I ended up using code over sublime or atom.

**Comment by lukehoban** [comment]
There weren't any Go-specific changes to colorization.

As @egamma mentioned, the default theme was changed in VS Code recently, which changed the default coloring for all languages.

In VS Code 0.10.8, there is a `Dark (Visual Studio)` theme which matches the old VS Code default.
