### ISSUE TITLE
(go modules) gotype-live doesn't recognize imports in go modules

### ISSUE THREAD

**Issue by tamasf97** [microsoft/vscode-go#1950]
I'm posting the issue here because the gotype-live repo hasn't been touched for 2 years, and I don't know any other application that depends on it.

I would be more than happy to fix it, but it's beyond my knowledge at the moment. I believe the fix should be trivial for someone who knows his/her way around go compiling and package/module resolution though.

I'm using the latest beta of the extension.

**repro steps:** 
Create a module outside GOPATH as usual, and enable live errors.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @tamasf97 

I've logged https://github.com/tylerb/gotype-live/issues/3 to track this issue upstream.

@tylerb 

Would you have some time to look into this?
This tool is being tracked in https://github.com/golang/go/issues/24661 as well. So, folks from the Go tool team would be able to help if you have any questions working with modules.

**Comment by tylerb** [comment]
I'll take a look, but I doubt I can do much at this point. `gotype-live` is effectively a fork of `gotype` with the ability to pass in the data for a working file via stdin. As such, I probably need to wait for `gotype` to be updated to work with go modules, then merge those changes into my fork.

**Comment by ramya-rao-a** [comment]
@tylerb Understood.

On a side note, can you resolve https://github.com/tylerb/gotype-live/issues/1?

**Comment by tylerb** [comment]
Whoops! Not sure how that slipped by me. I resolved it.

**Comment by chespinoza** [comment]
Hi, are there some news about this issue? Thanks.

**Comment by tylerb** [comment]
As it stands now, I'd say this feature/functionality is going to be/has been made obsolete by the new `gopls` language server system. @ramya-rao-a thoughts?

**Comment by ramya-rao-a** [comment]
That is true. When the `diagnostics` feature of the new language server `gopls` is enabled, it provides diagnostics on type. 

Module users are suggested to use the language server already.

Can somebody here try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension. Here, the `diagnostics` feature of the language server will be used by default and the `gotype-live` tool will only be used in non-module and non language server scenarios

**Comment by nportas** [comment]
I've installed gopls and still I have a non-recognized import. Any ideas?

**Comment by ramya-rao-a** [comment]
@nportas Your case seem to be unrelated to the issue at hand here. Please log a new issue with screenshots of the problem along with your Go related settings

**Comment by ramya-rao-a** [comment]
In the latest update (0.11.0) to the Go extension, `gotypes-live` will not be invoked when using Go modules or when using the diagnostics feature from the language feature
