### ISSUE TITLE
Errors show up as warnings in the latest beta

### ISSUE THREAD

**Issue by tamasf97** [Microsoft/vscode-go#1951]
![screenshot from 2018-09-29 15-03-55](https://user-images.githubusercontent.com/25967296/46246107-ebca2780-c3f8-11e8-89ce-2da7505e3ff5.png)

**repro steps:**
Open any .go file, and write code that shouldn't compile using the latest version of the extension.

**Comment by ramya-rao-a** [comment]
Are you sure you don't have the `go.buildOnSave` disabled?

`go build` and `go vet` would both give the same results for the above code.
Results from the former is shown as errors, the ones from the latter is shown as warnings.
When the same position has both error and warning, we show only the error.

I believe in your case, the build on save feature is disabled. Therefore, you are seeing the results from `go vet`

**Comment by tamasf97** [comment]
Ah that was it then, sorry. I used gotype-live before with the auto build feature disabled. After enabling build on save it works now.
