### ISSUE TITLE
Renaming functionality not working at all

### ISSUE THREAD

**Issue by JoseFMP** [Microsoft/vscode-go#1954]
This bug happens in all operating systems. No matter what I set-up. Happens in Windows, Linux, and MaC.

**Steps to reproduce:**
1. Click on a symbol with the right button (not package name)
2. Click on "Rename Symbol" option in the context menu
![image](https://user-images.githubusercontent.com/24405049/46287169-dd703d00-c5ab-11e8-98f7-9cccea6d376a.png)

3. Enter the new different name of the symbol
![image](https://user-images.githubusercontent.com/24405049/46287152-cf222100-c5ab-11e8-88b0-5dc20b5ee842.png)

4. Press enter (return key)

**Expected behavior** 
Symbol is renamed

**Actual behavior**
Symbol is not renamed. the Output console will contain the error message:
```Rename failed: gorename: can't find package containing ****```
Where the stars point to the folder of your package. Wherever it is.
<br/>
This is not particular of any source code. Happens everywhere.

VS Code version 1.27.2
Extension version: 0.6.89

**Comment by ramya-rao-a** [comment]
@JoseFMP Are you using Go modules?

**Comment by JoseFMP** [comment]
No go modules. I tried multiple configurations for GOPATH. Same result all the time. I mean. Is, this supposed to be working? I really have the same error in different machines with different projects and completely different set-ups.

**Comment by ramya-rao-a** [comment]
Yes, when not using Go modules, rename feature should work.

Run `Go: Current GOPATH`. That is the GOPATH used by all the Go tools in the extension. Is the result what you expect?

Also see [GOPATH in VS Code](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)

**Comment by JoseFMP** [comment]
@ramya-rao-a Yes $GOPATH is set-up correctly. The issue of renaming not working happens in all the golang projects I tried. It never ever worked.
However I do believe the projects are configured correctly since all other go-related tools are working properly.

**Comment by ramya-rao-a** [comment]
@JoseFMP Can you try running `gorename` from the command line and see if the tool succeeds?

**Comment by grazimdeoliveira** [comment]
😈
