### ISSUE TITLE
gometalinter custom linter not working

### ISSUE THREAD

**Issue by pierrre** [Microsoft/vscode-go#1955]
My config:
```json
{
	"go.vetOnSave": "package",
	"go.lintTool": "gometalinter",
	"go.lintFlags": [
		"--disable-all",
		"--enable=deadcode",
		"--enable=gocyclo",
		"--enable=golint",
		"--enable=ineffassign",
		"--enable=misspell",
		"--enable=nakedret",
		"--enable=vet",
		"--enable=vetshadowstrict",
		"--linter='vetshadowstrict:go vet -shadow -shadowstrict:PATH:LINE:MESSAGE'",
		"--tests",
		"--vendor",
		"--deadline=30s"
	]
}
```

It displays this in the output:
```
Error while running tool: /home/pierre/go/bin/gometalinter --disable-all --enable=deadcode --enable=gocyclo --enable=golint --enable=ineffassign --enable=misspell --enable=nakedret --enable=vet --enable=vetshadowstrict --linter='vetshadowstrict:go vet -shadow -shadowstrict:PATH:LINE:MESSAGE' --tests --vendor --deadline=30s --aggregate
gometalinter: error: unknown linters: vetshadowstrict
```

If I run manually the command from the message above it works.

**Comment by ramya-rao-a** [comment]
Are you sure `vetshadowstrict` is supported by `gometalinter`? I dont see any reference to it in the gometalinter repo. See https://github.com/alecthomas/gometalinter/search?q=vetshadowstrict&unscoped_q=vetshadowstrict

**Comment by pierrre** [comment]
That's why I added `"--linter='vetshadowstrict:go vet -shadow -shadowstrict:PATH:LINE:MESSAGE'",` in the command line.
It allows to add custom linter command.
I don't understand why it works when I run the command manually in my terminal, but it doesn't work in vscode.

Anyway, after some thought, I decided not to use "vet shadow" in my app, because it has too many "false positive".
So it's not really a problem for me anymore.
But it could a problem for someone trying to use a custom linter command.

**Comment by pierrre** [comment]
I can simplify my problem to:
```
	"go.lintFlags": [
		"--disable-all",
		"--enable=mylinter",
		"--linter='mylinter:/bin/true:PATH:LINE:MESSAGE'",
	],
```

It prints:
```
Error while running tool: /home/pierre/go/bin/gometalinter --disable-all --enable=mylinter --linter='mylinter:/bin/true:PATH:LINE:MESSAGE' --aggregate
gometalinter: error: unknown linters: mylinter
```

If I run this command in my terminal, it works.

It seems to be an "escaping" issue, but I don't understand why.
This is working:
```
	"go.lintFlags": [
		"--disable-all",
		"--enable=mylinter",
		"--linter=mylinter:/bin/true:PATH:LINE:MESSAGE",
	],
```

I added simple quotes in my original command, because it contained spaces between the flags `-shadow -shadowstrict`.
But it causes an issue in vscode-go.

**Comment by alecthomas** [comment]
This is normal behaviour. Quotes are only interpreted by the shell, however most other applications (including vscode) execute subprocesses directly and treat the quotes as literals.

**Comment by pierrre** [comment]
OK, so it doesn't seem to be a real problem.
I'm closing the issue.
Thanks !

**Comment by ramya-rao-a** [comment]
Thanks @alecthomas!
