### ISSUE TITLE
Test coverage no coloring all functions in source unit

### ISSUE THREAD

**Issue by jcbritobr** [Microsoft/vscode-go#1956]
Hi all, the "toggle test coverage" isn't coloring go static functions

```
os - windows 10
Versão: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Data: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Arquitetura: x64
```

here a sample code and steps to reproduce:

unit point.go:

```go
package algebraic

type Point struct {
	x int32
	y int32
}

// NewPoint allocates a new Point in heap
func NewPoint(x, y int32) *Point {
	return &Point{x, y}
}

func (p *Point) Sum(point *Point) *Point {
	result := &Point{0, 0}
	result.x = p.x + point.x
	result.y = p.y + point.y

	return result
}
```

tests unit: point_test.go

```go
package algebraic

import "testing"

func TestPointSum(t *testing.T) {

	expected := NewPoint(2, 2)
	pointa := NewPoint(1, 1)
	pointb := NewPoint(1, 1)
	result := pointa.Sum(pointb)

	if !(expected.x == result.x && expected.y == result.y) {
		t.Error("fail to sum points")
	}
}

func TestNewPoint(t *testing.T) {
	result := NewPoint(0, 0)

	if result == nil {
		t.Error("fail to allocate a new Point ")
	}
}
```

Just run toggle test coverage. The results is below. Static functions ( NewPoint ) are not being covered and colored.

![image](https://user-images.githubusercontent.com/6579862/46294264-c7428c80-c56b-11e8-8e6d-faf0e40419ff.png)

**Comment by ramya-rao-a** [comment]
First lets make sure that the coverage data provided by Go has the static function covered.

- Open the `View` menu, choose `Output`
- Run the coverage command
- Choose `Go Tests` from the drop down on the top right corner of the Output panel

Here you will see the command used to get the coverage as well as the file to which the coverage was written.

Open this file, and check if the coverage there includes the range for the static functions
