### ISSUE TITLE
Start Without Debugging still launches program in debug mode

### ISSUE THREAD

**Issue by youngderekm** [Microsoft/vscode-go#1957]
I'm trying to launch a go program without debugging (debugging works fine).  I have a single launch configuration, open the source file I want to launch, then choose "Debug: Start Without Debugging".  I see in the debug output and in ps that dlv is still used to execute the program.  I've restarted and reloaded.  Is there something wrong with the launch configuration that would cause this?

My launch configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${fileDirname}",
            "env": {},
            "args": [],
            "showLog": true,
            "trace": "verbose"
        }
    ]
}
```

My debug output:
```
Verbose logs are written to:
/var/folders/k7/y2c0bqrj0p13css97dwy4y740000gn/T/vscode-go-debug.txt
3:48:51 PM, 10/1/2018
InitializeRequest
InitializeResponse
Using GOPATH: /Users/dyoung/go
Running: /Users/dyoung/go/bin/dlv debug --headless=true --listen=127.0.0.1:2345 --api-version=2 --log=true --
API server listening at: 127.0.0.1:2345
time="2018-10-01T15:48:51-04:00" level=info msg="launching process with args: [/Users/dyoung/src/2xapi/cmd/chat/debug]" layer=debugger
InitializeEvent
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
time="2018-10-01T15:48:52-04:00" level=debug msg=continuing layer=debugger
Chat server set to run on 8081
```

I'm using VSCode 1.27.2, Go plugin 0.6.90-beta.8.

**Comment by ramya-rao-a** [comment]
`Start Without Debugging` only works when the `program` points to a file and not a directory.

To `Start Without Debugging`, behind the scenes I run `go run` which only accepts file and not directory.

So change the `program` to your file or just `${file}` and it should work
