### ISSUE TITLE
Problems exist after file is deleted

### ISSUE THREAD

**Issue by lheinrichde** [Microsoft/vscode-go#1959]
Steps to Reproduce:

1. Create a .go file.
2. Type in something wrong.
3. Delete file.

The problem stil exists.

![grafik](https://user-images.githubusercontent.com/18228328/46357192-9c882f00-c664-11e8-9cc2-761c25155682.png)

**Comment by ramya-rao-a** [comment]
The reason for this is that we run `go build` only on file save. So when you delete a file, the build is not triggered and so the errors are not refreshed.

If you dont want to commit a dummy change to trigger a save, you can also run the command `Go: Build Current Package` and the error should go away.
