### ISSUE TITLE
Stop putting Go-latest.vsix in the github repo

### ISSUE THREAD

**Issue by flyinprogrammer** [Microsoft/vscode-go#1960]
Your repo is now 89mb to do a full clone. This is incredibly painful for most of the world to actually download.

This could be avoided if we purged the history of Go-latest.vsix from the repo, and instead used github releases with pre-release tags, or if ya'll actually hosted this module somewhere - maybe show off the power of Azure Storage😉?

**Comment by ramya-rao-a** [comment]
Good point.

The challenge always was to use the same link for the download, no matter the version of the extension.
I can use the Github releases, but the link would change based on the tag name.

The only way to keep the link consistent would be to re-use the tag.
This requires a few extra steps from my side every time I have an update
- delete existing `latest` tag
- tag the current commit as `latest`
- Edit the release to update the vsix

With https://github.com/Microsoft/vscode-go/commit/1347006d3b542728dd1edf2c18a4b14f302673c9 the above is in effect.
