### ISSUE TITLE
New `iferr` snippets on 0.6.90-beta.9

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode-go#1962]
vscode-go version: 0.6.90-beta.9

The new `iferr` snippet expand to:
```go
if err != nil {
  return [nil, ]err
}
```

I'm not seeing this as generic cases. We are not always need `return nil, err` or `return err` which covered by the new snippet, but for testing purpose such as `t.Error(err)` need extra works. Is there a workaround to accommodate for such non-returning statement case. Since unit test are also important deliveries.

Give it a try,  type below code using `iferr` snippet:
```go
if err != nil {
  t.Error(err)
}
```

**Comment by ramya-rao-a** [comment]
@uudashr Good point

cc @alecthomas who made the update.

@alecthomas We could revert the change to the `iferr` and create a new snippet for what you had in mind i.e returning `nil, err` or `err`

**Comment by ramya-rao-a** [comment]
I wanted to release the update today, so I have reverted the change to `iferr` and created a new snippet `iferrret` with the changes proposed by @alecthomas 

We can continue the discussion here though.

**Comment by alecthomas** [comment]
I just press the "select line" key combo and start typing in this situation. Another alternative would be to have a completion fragment cover the whole return, as well as the sub-parts.

But it's already been reverted so 🤷‍♂️

**Comment by ramya-rao-a** [comment]
You mean like this:

`if err != nil {\n\t${1:return} ${2:nil, err}\n}`?

**Comment by uudashr** [comment]
Got clue from @alecthomas 
Might be like this `if err != nil {\n\t${1:return ${2:nil, }${3:err}}\n}`

**Comment by ramya-rao-a** [comment]
This is fixed in the latest update to the Go extension (0.6.91)
