### ISSUE TITLE
Default Delve port 2345 is in exclusion range in Windows 10 October 2018 Update

### ISSUE THREAD

**Issue by schroding3rscat** [Microsoft/vscode-go#1964]
Today I noticed that I'm unable to debug any of my Go projects in vscode. I spent quite a time discovering that since the last Windows 10 October 2018 Update Microsoft added a bunch of ports to exclusion range.

This is what I get with 1709 version:
<img width="539" alt="screenshot_1" src="https://user-images.githubusercontent.com/3431598/46443800-b4040c80-c777-11e8-8ef3-fb7ff559921f.png">

And this is exclusion range for 1809 version:
<img width="541" alt="screenshot_2" src="https://user-images.githubusercontent.com/3431598/46443801-b4040c80-c777-11e8-9598-7e5b1c67a8de.png">

As you can see, they added Delve's default port 2345 to exclusion range. I think you should stop using this port and pick a random one as suggested in #1906 or use a port which is not excluded by Windows.

**Comment by ramya-rao-a** [comment]
The port 2345 is no longer used after I resolved #1906 

Which version of the Go extension are you on?

Are you doing local or remote debugging?

The only place it is used now is in the snippet generated for the remote debugging. In that case, it is a snippet and is meant to be replaced with whatever port is being used on the remote machine.

**Comment by schroding3rscat** [comment]
I'm using 0.6.93. The problem is with this snippet. When I hit F5 and vscode generates launch.js for me, I cannot start my project. I get an error with an unclear message that port 2345 is already used. Even if I don't want to remote debug anything, a port is still in the snippet.

**Comment by schroding3rscat** [comment]
I checked new launch.js generation and it seems that it doesn't add `port` there. My script was probably generated in the old version. I think this issue can be closed now.
