### ISSUE TITLE
Comments in the beginning of file throw off code insight

### ISSUE THREAD

**Issue by egonelbre** [Microsoft/vscode-go#1967]
In a repository with modules, comments in the beginning of the file are throwing off gocode-gomod (or godef-gomod or something else, not completely sure).

Without comment:
![2018-10-05 09_40_20-window](https://user-images.githubusercontent.com/192964/46519928-ddf62580-c882-11e8-87de-674518ff6af7.png)

With comment:
![2018-10-05 09_41_31-window](https://user-images.githubusercontent.com/192964/46519932-df275280-c882-11e8-9928-590d6ae1ec94.png)

It seems to be offset by the amount of bytes in the comment.

Code to reproduce:

```
// Copyright asdfasdfasdfasd
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("Hello, World")
	os.Open("file")
}
```

**Comment by ramya-rao-a** [comment]
I dont see this...

Have you changed the value for the below settings? If yes, can you share what you set them to?
- `go.useLanguageServer`
- `go.docsTool`

**Comment by egonelbre** [comment]
No, those are default. I've already sent a PR for godef-gomod to fix the offset calculation bug.

I forgot to clarify that it needs to be outside of GOPATH and it needs to have a go.mod file (otherwise it doesn't trigger the gomod specific tooling).

**Comment by mnewswanger** [comment]
I'm able to repro

**Comment by ramya-rao-a** [comment]
Now I see it.

Thanks @egonelbre!

**Comment by ramya-rao-a** [comment]
Now that the upstream PR has been merged, please follow the below in VS Code to get the fix:
- Run the command `Go: Install/Update Tools`
- Choose `godef-gomod`
- Press Ok to update.
