### ISSUE TITLE
%GOPATH%\bin commands not found, v 0.10.8 on Windows 10 x64

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-go#197]
Moved from Microsoft/vscode#2914
From @zanderz 

First time trying VS Code, all excited at first but... have to go back to liteide for now :disappointed:  

Prompted repeatedly with:
`The "godef" command is not available. Use "go get -u github.com/rogpeppe/godef" to install.`
 
I have:
`Current GOPATH:c:\work`
godef.exe is installed in `c:\work\bin`

**Comment by zanderz** [comment]
Note that it seems to work and the error goes away if %GOPATH%\bin is added to the %PATH%.

**Comment by lukehoban** [comment]
Unfortunately I haven't been able to reproduce this.  The logic for looking up the `godef` binary (and others) should certainly be looking in your $GOPATH\bin (see https://github.com/Microsoft/vscode-go/blob/master/src/goPath.ts#L16).  If you can provide more details about your environment we could look into this further - but going to close for now.
