### ISSUE TITLE
go definition or peak takes long time

### ISSUE THREAD

**Issue by lanox** [Microsoft/vscode-go#1971]
Hi, 

I seem to have issue where ```go to definition or peak``` takes long time to display anything , also if I hold command and hover over the method, all i get is ```loading``` for good 10 sec or more before it show anything.

**Comment by alecthomas** [comment]
I don't have a solution for "Go to definition" or "Peek definition", but I was also experiencing insanely long completion times (5-10 seconds). Enabling the language server with the following experimental flags brought this back to acceptable times:

```json
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    },
```

**Comment by lanox** [comment]
@ramya-rao-a  Yes I am using go modules and I am on go 1.11.1, using vscode Version 1.28.0 (1.28.0)
also I seem to have issues where go to definition is no longer working at all.

However testing go to def in vi using vim-go works fine, I am not sure if that helps anything or not.

**Comment by ramya-rao-a** [comment]
@lanox The slowness issue when using Go modules is a known issue as mentioned before.

When you say that go to definition is not work at all, are you still using modules? Can you check if you are using the language server? The language server doesnt work with modules either.

If you are using modules and go to definition is not working, try changing the setting `go.docsTool` to `gogetdoc` and see if that helps

**Comment by alecthomas** [comment]
That does seem to be a bit faster.

**Comment by saibing** [comment]
@lanox @ramya-rao-a 

[bingo](https://github.com/saibing/bingo) is a new go language server support go 1.11 module.

please try it.
