### ISSUE TITLE
Wrong variable scope displayed when debugging

### ISSUE THREAD

**Issue by christian-boks** [Microsoft/vscode-go#1974]
The debugger shows variable content from the wrong scope: 

![image](https://user-images.githubusercontent.com/10370084/46580628-b50f9500-ca28-11e8-8bcf-c299bd42cfe3.png)

Program output:
Inner animal: cat
Outer animal: dog

Using: 
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $

And Go Extension v 0.6.90

**Comment by ramya-rao-a** [comment]
We get the variable information from delve. 

Can you try running `dlv` from the command line to debug your code, run `locals` to get the local variables and see if `animal` points to `dog` or `cat`?

**Comment by chainhelen** [comment]
![image](https://user-images.githubusercontent.com/7046329/46715363-3ddd3980-cc92-11e8-80fd-4532b539823a.png)

**Comment by christian-boks** [comment]
This is the output I get when running `dlv`

```
> main.main() c:/gohome/src/play/scope_bug/main.go:9 (PC: 0x48df25)
     4:
     5: func main() {
     6:         animal := "dog"
     7:         if true {
     8:                 animal := "cat"
=>   9:                 fmt.Println("Inner animal:", animal)
    10:         }
    11:         fmt.Println("Outer animal:", animal)
    12: }
(dlv) locals
(animal) = "dog"
animal = "cat"
```

**Comment by jhendrixMSFT** [comment]
I have a fix for this, one thing that comes to mind is if we should also display the shadowed value(s) like delve does in the variables pane.

**Comment by ramya-rao-a** [comment]
I would stick to just showing the non-shadowed value.

**Comment by jhendrixMSFT** [comment]
I tend to agree however there are cases where having both values would be useful.  IMO what would be ideal is if we could display the shadowed value when hovering over the shadowed variable.  Can we subscribe to some event when hovering over a variable?

**Comment by jhendrixMSFT** [comment]
This starts to get a little unwieldy if a variable is shadowed more than once.  Perhaps it would be better if we displayed the shadowed variables as children of one another, what do you think (assuming vscode don't have problems with child vars with the same name)?

**Comment by ramya-rao-a** [comment]
Shadowed variables are now showing inside parentheses in the latest update (0.9.0) to the Go extension.
Thanks @jhendrixMSFT!
