### ISSUE TITLE
Install gocode-mod and godef-mod failed followd by vscode tips

### ISSUE THREAD

**Issue by Betula-L** [Microsoft/vscode-go#1979]
If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

(My go extension is https://github.com/Microsoft/vscode-go/releases/download/latest/Go-0.6.91-beta.2.vsix )

1. Create a empty project
2. Run go mod init and an empty main.go
3. Then vscode will instruct user to install gocode-mod

![](https://user-images.githubusercontent.com/6059935/46643034-cb465e00-cbac-11e8-8fc2-c15bf99aa7a2.png)

4. gocode-mod installed failed

```
Installing 2 tools at /home/mi/go/bin
  gocode-gomod
  gopkgs

Installing github.com/stamblerre/gocode FAILED
Installing github.com/uudashr/gopkgs/cmd/gopkgs SUCCEEDED

1 tools failed to install.

gocode-gomod:
Error: Command failed: /usr/local/go/bin/go build -o /home/mi/go/bin/gocode-gomod github.com/stamblerre/gocode
# github.com/stamblerre/gocode/internal/suggest
/home/mi/go/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:138:3: cannot use func literal (type func(*token.FileSet, string) (*ast.File, error)) as type func(*token.FileSet, string, []byte) (*ast.File, error) in field value
# github.com/stamblerre/gocode/internal/suggest
/home/mi/go/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:138:3: cannot use func literal (type func(*token.FileSet, string) (*ast.File, error)) as type func(*token.FileSet, string, []byte) (*ast.File, error) in field value
```

**Comment by Scapal** [comment]
This commit in `golang.org/x/tools/go/packages` introduces a breaking change:
https://github.com/golang/tools/commit/2f1727f1b37d7d257665debc72d4ae0b8e449748#diff-04792145c70ebd708928684da4875fe9R108

Both `github.com/ianthehat/godef` and  `github.com/stamblerre/gocode` depend on this.

**Comment by yfwz100** [comment]
By changing the function signatures (omitting the third parameter), it seems to work fine.

**Comment by ramya-rao-a** [comment]
cc @ianthehat, @stamblerre

**Comment by pbarker** [comment]
why use a forked version of `godef` here? We're somewhat at @ianthehat's mercy as to whether he's even around. Perhaps this is a good time to move upstream if we don't have a compelling reason otherwise

**Comment by ramya-rao-a** [comment]
@Betula-L Thanks for reporting!

I see that @egonelbre has already submitted a [PR](https://github.com/ianthehat/godef/pull/3) to fix the issue for godef. The PR is merged, so godef should be good. Thanks @egonelbre!

@stamblerre has pushed a fix for gocode as well.

All,
Please run `Go: Install/Update Tools`, select `godef-gomod` and `gocode-gomod`, press OK to install/update them.

**Comment by ramya-rao-a** [comment]
@pbarker We use the @ianthehat's forked version of `godef` to provide the `Go to definition` feature when using Go modules. You can choose to use `gogetdoc` instead if you want by adding the setting `"go.docsTool": "gogetdoc"`

**Comment by pbarker** [comment]
thanks for the context @ramya-rao-a, would it maybe make sense to fork that into the `Microsoft` namespace so there are at least multiple people able to push a fix in the event @ianthehat is unavailable?

**Comment by ramya-rao-a** [comment]
We won't be moving the fork to the `Microsoft` namespace, because Microsoft doesn't own the fork and neither do we maintain it.

@ianthehat leads the Go tools team in Google and is leading the effort in adding Go modules support in various Go tools in the Go ecosystem.  See https://github.com/golang/go/issues/24661

Today's incident was unfortunate, but it by no way means that @ianthehat is unavailable.

Yes, there was a delay in merging the PR, but I am sure @ianthehat and his team are on top of it to avoid such delays in the future.
