### ISSUE TITLE
The text editor colors changed with the last update - bis

### ISSUE THREAD

**Issue by maxence-charriere** [Microsoft/vscode-go#198]
Hello,
Sorry for ask that again but can you take another look with this issue: https://github.com/Microsoft/vscode-go/issues/195

I went back on my Windows laptop which was not updated since maybe 2 or 3 month and that is what it looks like:
![gobefore](https://cloud.githubusercontent.com/assets/2692731/12997698/ea7020fe-d0f0-11e5-87b7-3efe4f9ae866.jpg)

I updated with the current version and here is the result:
![gonow](https://cloud.githubusercontent.com/assets/2692731/12997730/28c933a4-d0f1-11e5-94fa-efee12c1b9fd.jpg)

The theme was the dark (visual studio), I didn't touch anything.
The same thing happened with my mac machine.

**Comment by egamma** [comment]
This change intentional and we have added a Dark+ default theme which provides more colors, pls see Microsoft/vscode#1849
