### ISSUE TITLE
Please change Go file icon

### ISSUE THREAD

**Issue by AlekSi** [microsoft/vscode-go#1982]
I created semi-humorous issue #1033 in the past. With VSCode 1.28 this becomes a serious problem: the eyeless gopher follows me even in Finder. Just look at the image from the [changelog](https://code.visualstudio.com/updates/v1_28#_file-icons-per-file-type):
![](https://code.visualstudio.com/assets/updates/1_28/file-icons.png)
Please use https://github.com/jesseweed/seti-ui/blob/master/icons/go.svg instead of https://github.com/jesseweed/seti-ui/blob/master/icons/go2.svg.

**Comment by AwesomeObserver** [comment]
I think that better use new Go logo.

**Comment by AlekSi** [comment]
I disagree: we love our mascot, and it does not go anywhere even with new branding.

**Comment by BillyPurvis** [comment]
I for one approve our new halloween eyeless Gopher.

**Comment by ramya-rao-a** [comment]
How in the world did this issue get 38 upvotes in 14 hours???
I didnt know we had such a traffic.

@AlekSi Did you happen to tweet this issue? Or use some other magic to get this much attention? I would love to know as I’d like to follow whatever you did when I want more people to try out some of the changes before I release an update to this extension :slightly_smiling_face:

Anyway, I tried using the other icon as suggested. Below is the comparison (left is old, right is new)

<img width="476" alt="screen shot 2018-10-09 at 4 43 00 pm" src="https://user-images.githubusercontent.com/16890566/46705003-6ad21380-cbe2-11e8-977b-32e289819ea7.png">

As you can see the other icon doesn't look that great either ...

**Comment by AlekSi** [comment]
That was a combination of [the power of Twitter](https://twitter.com/paaleksey/status/1049599618449887239) and the power of Golang Russian Slack chat. Unlike trying a new version of the extension, hitting 👍 and moving on takes much less time. Still, I follow you and will forward your requests to our chat.

So, to move forward, we need either a new icon or to add eyes to the current one.
On that picture – what size it is?

**Comment by ramya-rao-a** [comment]
> So, to move forward, we need either a new icon or to add eyes to the current one.

Thats what I think too.

> On that picture – what size it is?

In that picture, I am on a Mac with zoom level 1 (`"window.zoomLevel": 1) and the default light theme.
Other than that I am using the default settings.

**Comment by tmack8080** [comment]
@ramya-rao-a - Can you just try with the new logo so we can see what it looks like?

**Comment by timdmackey** [comment]
Aww, the poor guy just needs some cataract surgery! 
![go](https://user-images.githubusercontent.com/182772/48120793-feb9ee00-e227-11e8-9b05-b445adc788a2.png)

**Comment by MariaLetta** [comment]
Hi, my name is Maria and I'm author of Free Gophers Pack (https://github.com/MariaLetta/free-gophers-pack). I'd like to help with this issue and contribute. 
I prepared new colored icon (in 3 colors — blue, white, black). 

Preview:

![new_icons](https://user-images.githubusercontent.com/49082826/56331546-5ecc9d00-6195-11e9-93d5-cf3857ad2388.png)

I also made a gopher in one color (second one), but it looks less contrast and clean when applied to interface, so I suggest to use first one (colored).

Here are more previews:

![how_it_works](https://user-images.githubusercontent.com/49082826/56332147-d4d20380-6197-11e9-90ab-fb0bc95ab9a6.png)

![two_versions](https://user-images.githubusercontent.com/49082826/56331600-a6532900-6195-11e9-8a33-42764416e96d.png)


Last screen is rasterized in FullHD (1920*1080px).
Let me know if it’s ok I can send SVG or make a PR.

**Comment by AlekSi** [comment]
Yessss! I think that's awesome. Thank you very much!
@ramya-rao-a What is the best way to proceed? Create a new theme? Send PR?

**Comment by ramya-rao-a** [comment]
Thanks everyone for your patience and contribution!

Tagging our designer from the VS Code team

@misolori, Please guide us on what the next steps here should be?

**Comment by misolori** [comment]
This would have to get updated from the [seti-ui icon theme](https://github.com/jesseweed/seti-ui), but that repo has gone a bit stale (last updated in August 2018). The team needs to decide on next steps for this repo, will update when I know more.

**Comment by ramya-rao-a** [comment]
@misolori Would you prefer an issue in the VS Code repo?

**Comment by misolori** [comment]
@ramya-rao-a not until we have decided what to do with that repo. We've had other requests for other file icons to be updated and have closed and redirected them to the seti-ui repo.

**Comment by orta** [comment]
👋 I have the abilities to help out on the Seti-ui repo side, @MariaLetta the format only supports a single color icon, but I'll gladly help get that improved

**Comment by inliquid** [comment]
@orta actually there are some colored icons in `seti-ui` repo: https://github.com/jesseweed/seti-ui/blob/master/icons/kotlin.svg

However it seems that `seti-ui` does bad export into font format so as a result it converts to monocolor:
![изображение](https://user-images.githubusercontent.com/6797881/60847539-9b83bf80-a1eb-11e9-8450-a905770e232f.png)

In contrast here is how it looks like with `Material Icon Theme`:
![изображение](https://user-images.githubusercontent.com/6797881/60847545-a63e5480-a1eb-11e9-96e6-4c2e49bae7cd.png)

**Comment by orta** [comment]
Yeah, it's a part of how seti ensures colour consistency  across the editor, you you can have whatever image you want but it gets stamped down into into one of 9 colours in the end

**Comment by inliquid** [comment]
Sorry but I don't see a "color consistency" in seti case. I see a broken icon. If you take a precise look you may see the traces of badly converted vector image.
![изображение](https://user-images.githubusercontent.com/6797881/60900426-d251e800-a274-11e9-8c2b-95ec431e5625.png)

**Comment by orta** [comment]
Sure, happy to take a PR fixing that case 👍  - but as I said, the single color stamping is done for consistency and is applied across all icons which is why logos can be only one of 9 colors. I didn't make the decision, but I agree with it.

**Comment by ramya-rao-a** [comment]
Hey @orta,
Are there any updates on this?

**Comment by hyangah** [comment]
Discussed this with @spf13 (Go product lead).
We think the logo works better in a single color & at such small sizes.

The steps for update: https://github.com/jesseweed/seti-ui#adding-file-icons

@orta there are two go icon files (go.svg and go2.svg). should both need to be updated?

**Comment by orta** [comment]
I think only `go.svg` probably needs changing - I'm not really sure what the `go2` file does.

Does go have `.article` or `.slide` files?

**Comment by ramya-rao-a** [comment]
@hyangah I believe its the go2.svg that is being used in the file icon. I don't know why there are two in the first place. @misolori can confirm

**Comment by hyangah** [comment]
right, go2.svg is the file used for `.go`. go.svg is still in use for `.article` and `.slide` files that are meant for the go `present` and blog files and I will leave them untouched this time. :-)

Not finalized, but what do you think about this?

![image](https://user-images.githubusercontent.com/4999471/82614587-33856000-9b96-11ea-9623-c6246bd85bbb.png)

**Comment by inliquid** [comment]
1. Where is gopher?
2. `go.mod` and `go.sum` should have different icon to distinguish it visually. When it has same color as text it becomes less readable.

**Comment by hyangah** [comment]
1. See [the previous update](https://github.com/microsoft/vscode-go/issues/1982#issuecomment-629215353) You can still find gophers when you create files for the go present/blog tools. 
2. Any better icon you have in mind?

I am thinking to tone down `go.mod` and `go.sum` using light grey color instead. They are not meant to be edited, so less attention is better.

**Comment by ramya-rao-a** [comment]
Thanks @hyangah 

@orta, Are you aware of what the next steps here are to get VS Code to use the new icon?

**Comment by inliquid** [comment]
`go.mod` now looks like RSS feed?

I think what was finally done goes against that was actually requested by community.

**Comment by hyangah** [comment]
I filed https://github.com/microsoft/vscode/issues/98586 

@inliquid, the icon change is not what we intended as I described in my PR to seti-ui and also in the newly created issue.

All of us love the gopher mascot. If anyone finds a way to create a gopher icon that holds its original cuteness and beauty, please send the PR.

**Comment by inliquid** [comment]
@hyangah so what about this proposal?
https://github.com/microsoft/vscode-go/issues/1982#issuecomment-484328456

**Comment by hyangah** [comment]
@inliquid sadly it didn't work as nicely as we hoped with the seti-ui color constraints and the icon size, especially in a low resolution. :-( And, that's a new variation of gopher, so I am afraid people with different taste will still have different opinions.
https://storage.googleapis.com/golang-assets/Go-brand-book-v1.9.5.pdf

**Comment by inliquid** [comment]
@hyangah what do you mean, I see screenshots and ppl actually liked them. Can you show what's exactly not as nicely?

**Comment by hyangah** [comment]
@inliquid the screenshot uses three colors and high resolution. In low resolution, single color the eyes get smudged and doesn't look like a gopher.

**Comment by inliquid** [comment]
What's the problem with using 3 color image?

**Comment by orta** [comment]
The theme only uses 8 colors, and each icon has to only be one colour - this is a seti-ui design constraint that I'm not gonna budge on 👍
