### ISSUE TITLE
Modules: GoToDef should go to vendor if vendor is present

### ISSUE THREAD

**Issue by marwan-at-work** [microsoft/vscode-go#1983]
In the module system, your dependencies can either be in $GOPATH/pkg/mod or in a local vendor folder. Having a local vendor folder is still important if you want to debug things since the global cache is read-only. Gohack is a tool that lets you get around that, but it can get tedious. 

VSCode should recognize a project has a vendor folder, and then pass the `-mod=vendor` option when going to a definition (as always auto complete and other tools) 

To reproduce my issue, I create this repo: https://github.com/marwan-at-work/vscode-mod-vendor

**Comment by ramya-rao-a** [comment]
Apologies for the delay in getting to this.

You can add the below in your settings and `godef` picks it up and works as expected:
```
"go.toolsEnvVars": {
	"GOFLAGS": "-mod=vendor"
}
```

What we can do is automatically set the GOFLAGS environment variable when a `vendor` folder is detected at the same level as the `go.mod` file.

But before doing that, I have a question. Do you know what the "main module" is referring to in [How do I use vendoring with modules](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away). Is it the module that is at the same level as the `go.mod` file?

**Comment by pforpallav** [comment]
@ramya-rao-a Is there a spec somewhere that says the `vendor` should live under the same path as the `go.mod` file? I couldn't find as such.
The project I am working on, has a vendor folder just under the `$GOPATH`. I ended up creating a symlink to this in the folder with `go.mod`, to make `vscode` happy.

**Comment by ramya-rao-a** [comment]
@stamblerre Can you provide some guidance here?

**Comment by pforpallav** [comment]
@stamblerre ping :)

**Comment by stamblerre** [comment]
I believe that the vendor folder should be in the module root. That is where `go mod vendor` command places the vendor folder. For more advice on vendoring with modules, I would advise asking questions in the `#modules` channel of the [Gophers Slack](https://invite.slack.golangbridge.org/).

**Comment by ramya-rao-a** [comment]
@stamblerre Is there anything the extension can do here or will `gopls` now handle this case?

**Comment by marwan-at-work** [comment]
Tested VSCode/gopls with Go 1.14beta, and I can confirm that GoToDef automatically chooses vendor 👍

**Comment by ramya-rao-a** [comment]
Thanks @marwan-at-work!
