### ISSUE TITLE
Hover info about a field doesn't show the type's package

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1985]
For example:

<img width="524" alt="screen shot 2018-10-09 at 2 26 49 pm" src="https://user-images.githubusercontent.com/63830/46700027-89c7aa00-cbd0-11e8-8a9f-c8eafa23dd1a.png">

The the hover info about the field `r.Facets` is "Facets []ItemFacetToRetrieve", which suggests the type is declared in the same package, but you can see in the left part of the image that the actual package qualifier is `pb`.

OS: macOS High Sierra 10.13.6 (17G65)
VSCode: 1.28.0
Go extension: 0.6.90
Go: go version go1.11.1 darwin/amd64

**Comment by ramya-rao-a** [comment]
Do you see anything different when you use the setting `"go.docsTool": "gogetdoc"` ?

**Comment by willfaught** [comment]
I see something like `field Facets []foo.com/import/path.ItemFacetToRetrieve`, which is basically what I want. Thanks! Why not have that be the default?

**Comment by ramya-rao-a** [comment]
> Why not have that be the default?

Well, thats a long story :( I have #1025 tracking the need to make it default.
I just never got around to making a good benchmarking exercise to prove that it will not affect the performance.
