### ISSUE TITLE
Format on save not working with cmd folders

### ISSUE THREAD

**Issue by Scapal** [Microsoft/vscode-go#1986]
The format tool is not working properly when I'm under a `/cmd`folder, ex. `/cmd/server/main.go`.

To be more precise, under that tree branch, only `"go.formatTool": "gofmt"` works properly, all the other formatters wouldn't format on save.
Manually calling "Format Document" works as expected.

vscode 1.28.0
ms-vscode.go 0.6.90

**Comment by ameissnersofi** [comment]
I'm seeing similar behavior, but not with `cmd` folders.  I'm seeing this whenever a module is present (`go.mod`, `go.sum` files)

**Comment by Scapal** [comment]
I also use Go 1.11 modules.

I don’t have problems in the other local packages of my project, only the `main` packages under `/cmd`.

Maybe the `package main` is the common pattern.

**Comment by ramya-rao-a** [comment]
Formatting not working (unless you choose `gofmt`) when using Go modules is a known issue as the formatting tools themselves (goreturns, goimports) dont support Go modules yet.

Please see [Go modules in VS Code](https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code) which tracks the status of Go module support
