### ISSUE TITLE
The debugger doesn't show pointer values (like 0xf800000040)

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#1989]
So it seems like you can't tell if two pointers point to the same thing.

<img width="621" alt="screen shot 2018-10-10 at 6 25 33 pm" src="https://user-images.githubusercontent.com/63830/46774970-f36fb300-ccb9-11e8-944c-64c26a611fdd.png">

Latest version of macOS High Sierra (10.13.6 (17G65)), VSCode (1.28.0), and vscode-go (0.6.91).

**Comment by eternal-flame-AD** [comment]
I usually watch `uintptr(x)` to obtain the pointer value. Probably a hack but I think that helps in your case:)

**Comment by ramya-rao-a** [comment]
@willfaught Can you provide a small sample code and elaborate on what you would expect vs what actually is being shown?

**Comment by willfaught** [comment]
@ramya-rao-a Sure:

```go
func TestX(t *testing.T) {
	var i, j int
	var p = &i
	var q = &j
	t.Logf("%#v %#v", p, q)
}
```

When run, you see output like:

```
=== RUN   TestX
--- PASS: TestX (0.00s)
    foofile_test.go:9: (*int)(0xc000018150) (*int)(0xc000018158)
PASS
ok  	foopackage	0.010s
```

When debugging TestX, you see these local variables:

<img width="212" alt="screen shot 2018-10-29 at 7 50 20 pm" src="https://user-images.githubusercontent.com/63830/47692770-2cfa5680-dbb4-11e8-98a5-cea6c884a9e1.png">

The pointer addresses for p and q aren't shown there, so you can't tell if they're equal and thus point to the same thing:

```
p: <*int>
q: <*int>
```

Instead, you should see something like:

```
p: 0xc000018150 <*int>
q: 0xc000018158 <*int>
```

There should also be a way to drill down into them to view the values they point to, like you can for the *testing.T in that same screen shot.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest version of the Go extension (0.8.0)
