### ISSUE TITLE
Built-in types aren't colored anymore (visual studio dark theme)

### ISSUE THREAD

**Issue by zippoxer** [Microsoft/vscode-go#199]
As you can see in the screenshot at issue #198, int/string/error and other built-in types aren't colored anymore with the visual studio dark (not plus) theme. Disregard the old screenshot in this issue.

A couple versions back, they used to be the same color as keywords, which was really helpful.

**Comment by lukehoban** [comment]
This was a change in the default themes for VS Code recently.  It is not related the Go plugin, or something that the Go plugin has any control over.

You should likely switch to the `Dark +` theme if you haven't already. Per https://code.visualstudio.com/Updates#_editor, it is now the default for new installations of VS Code.
