### ISSUE TITLE
Can't copy value from the Debugger Variables list (Go/Delve)

### ISSUE THREAD

**Issue by altimac** [Microsoft/vscode-go#1990]
Issue Type: Bug
I'm using the Go delve debugger (remote mode) inside VSCode and right clicking any of the local variables in the debugger (displaying the correct variable values!) only displays a disabled contextual menu where I can't copy (or set) value.

Copying a variable value from the debugger is pretty basic debugging workflow.

Thanks
<img width="445" alt="screen shot 2018-10-11 at 11 26 17" src="https://user-images.githubusercontent.com/778986/46803165-b827bf80-cd5f-11e8-88d0-35af1242ef1b.png">

**Comment by ramya-rao-a** [comment]
Thanks for reporting @altimac 

@roblourens Do you know what needs to be done to enable the context menu entries here?

**Comment by roblourens** [comment]
@isidorn

**Comment by altimac** [comment]
I reported the bug at the wrong place first. @isidorn replied:

> Please file this agains the go and delve debugger and tell them they have to support evaluateName property for this actions to be enabled
>

**Comment by isidorn** [comment]
@ramya-rao-a yeah, please support the [`evaluateName`](https://github.com/Microsoft/vscode/blob/5d645696cc669e4bc9c8824749395c7112e8c845/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1387) property.

Example: in the casses in the picture the `evaluateName` is equal to `name`, however inside the `zone` object if it had the `id` property the evaluate name of that would be `zone.id`
So `evaluateName` is the full path to get to the variable

**Comment by ramya-rao-a** [comment]
Thanks @isidorn 

Marking this as `help-wanted`. PRs are most welcome.

Code Pointers:
- Get started with a [local set up of the Go extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- [Debug the debugger](https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter)
- Update [variableRequest](https://github.com/Microsoft/vscode-go/blob/0.6.91/src/debugAdapter/goDebug.ts#L958) to add the `evaluateName` property on the variables

**Comment by ramya-rao-a** [comment]
This feature is now implemented with https://github.com/Microsoft/vscode-go/pull/2020

Until I release an update, you can get the fix using the [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update to the Go extension (0.6.0)
Thanks to https://github.com/karthikraobr!
