### ISSUE TITLE
Release Notes Not Updated

### ISSUE THREAD

**Issue by bsvec** [Microsoft/vscode-go#1992]
The release notes in the [wiki](https://github.com/Microsoft/vscode-go/wiki/Release-Notes) don't seem to have been updated since `v0.6.89` on 8/30.  Is it not being maintained any longer or was this just an oversight?

**Comment by ramya-rao-a** [comment]
Thanks for reporting @bsvec 

It was indeed an oversight.

I have update the release notes in the wiki to point to the Changelog.md file in this repo which contains the same information.
