### ISSUE TITLE
golint fails to install due to wrong import path

### ISSUE THREAD

**Issue by mrwonko** [Microsoft/vscode-go#1993]
When trying to install the Go tools, golint fails:
```
golint:
Error: Command failed: /usr/local/bin/go get -u -v github.com/golang/lint/golint
github.com/golang/lint (download)
package github.com/golang/lint/golint: code in directory /Users/willi/code/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
github.com/golang/lint (download)
package github.com/golang/lint/golint: code in directory 
/Users/willi/code/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
```

That's because an hour ago they added a canonical import path, which is not the one you're using:  https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58

**Comment by STiAT** [comment]
Just ran into the same issue. Would love to see that fixed.

Did you find any workaround @mrwonko ?

**Comment by mrwonko** [comment]
I figured I can do with an outdated golint, but you could probably just manually run `go get -u -v golang.org/x/lint/golint`

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @mrwonko.

Yes, a fix has been pushed to master.

Until I release an update, the workaround which is already mentioned above is to manually run `go get -u -v golang.org/x/lint/golint`
