### ISSUE TITLE
"Start without Debugging" stops at breakpoints

### ISSUE THREAD

**Issue by cfiderer** [Microsoft/vscode-go#1995]
When I set a breakpoint I my Go program and start it with "Debug" -> "Start without Debugging", it still stops at the breakpoint.

Environment:
Visual Studio Code
Version: 1.28.1 (user setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

ms.vscode.go 0.6.91

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1. Take a simple "Hello, World" program.
2. Set a breakpoint on the fmt.Printf() line.
3. Start the program with Ctrl-F5 or "Debug" -> "Start without Debugging".

I expect the program to run without stopping.

[hello.zip](https://github.com/Microsoft/vscode-go/files/2473332/hello.zip)

**Comment by ramya-rao-a** [comment]
To `Start without Debugging`, it is important that you have a debug configuration in the launch.json file with program pointing to the file you want to run. This is because behind the scenes we use `go run` which expects a file path

**Comment by cfiderer** [comment]
Hello Ramya,
I am a bit confused by your reply:
- The autogenerated `launch.json` configuration has `program: ${fileDirname}` - what other variable would provide the name of the Go file that I'm currently editing?
- Do I need to provide separate launch configurations for each and every runnable Go file in my workspace?

**Comment by ramya-rao-a** [comment]
You can update the autogenerated configuration to use `${file}` instead. That will use the file in the currently open editor.
