### ISSUE TITLE
Show function declaration comments when hovering over a third-party function call

### ISSUE THREAD

**Issue by autinerd** [Microsoft/vscode-go#1999]
When hovering over a function embedded in Go, it shows the function declaration and the declaration comment.
But when hovering over functions of third-party packages, it does not work.

**Comment by ramya-rao-a** [comment]
Can you provide a sample code that I can try this on?
Also provide the Go version you are using and if you are using Go modules.

**Comment by autinerd** [comment]
I looked again at this and recognized that this happens at functions which are member functions of structs. Example: https://github.com/gobuffalo/validate/blob/master/validate.go

![screenshot-vscode-go-struct-member](https://user-images.githubusercontent.com/27780930/46998170-1834b200-d122-11e8-8c19-68d0b1b82426.png)

**Comment by ramya-rao-a** [comment]
Maybe gogetdoc gives better results. Can you try the below?
- Add `"go.docsTool": "gogetdoc"` to your settings
- Run the command `Go: Install/Update Tools`, choose `gogetdoc`, press `Ok` to install it
- Try the hover

**Comment by autinerd** [comment]
I tried it and it's a lot better then `godoc`, thank you very much!
