### ISSUE TITLE
Respect vendor folder for searching code

### ISSUE THREAD

**Issue by ardan-bkennedy** [Microsoft/vscode-go#200]
The go to definition found code inside the GOPATH, but when a vendor folder exists it will be important to look there first. You may want to look at the govendor tooling or talk with Daniel Theophanes to learn some best practices on how to handle this. He has done an amazing job.

**Comment by davidbarsky** [comment]
vscode-go uses [godef](https://github.com/rogpeppe/godef) to search for code definitions. While it currently doesn’t search through the `vendor` folder, there are [two open pull requests](https://github.com/rogpeppe/godef/pulls?utf8=✓&q=is%3Apr+is%3Aopen+vendor) to add support. I think that the VSCode team is waiting on godef, as per #162.

Hope that helps! :smile:

**Comment by ardan-bkennedy** [comment]
Brilliant and Thanks !!!
