### ISSUE TITLE
Use tasks & terminals to run tests to get colorized output

### ISSUE THREAD

**Issue by bandesz** [microsoft/vscode-go#2003]
![screen shot 2018-10-13 at 10 06 06](https://user-images.githubusercontent.com/868104/46903643-a7965700-cecf-11e8-818b-871b392c5c24.png)

## Steps to reproduce

1. Use e.g. ginkgo for testing
2. On a test file run "Go: Test File"
3. The output is barely readable as it contains a lot of color escape sequences.

I disabled all other plugins which might cause an issue, but it still doesn't work. (Should this even work?)

**Comment by bandesz** [comment]
@ramya-rao-a a random example:
![ginkgo](https://user-images.githubusercontent.com/868104/47073255-b8a4d800-d1ef-11e8-95a0-e90af209c191.png)

**Comment by bandesz** [comment]
I managed to disable the colored output in this case by using the following setting:
```
"go.testFlags": ["-ginkgo.noColor"]
```

**Comment by toaster** [comment]
Hi there, what are the arguments against making colorization available here?

**Comment by ramya-rao-a** [comment]
As mentioned in https://github.com/Microsoft/vscode-go/issues/2003#issuecomment-430068305, colorization never worked in the output channel for test output.

The example in https://github.com/Microsoft/vscode-go/issues/2003#issuecomment-430539228 is from running the tests in a terminal directly.

To show colors in the output channel, we need to provide a grammar to parse the contents first.

Another alternative is to run the tests in a terminal using tasks

**Comment by toaster** [comment]
Ok, thanks for the clarification.

**Comment by ramya-rao-a** [comment]
To achieve the colors, this extension should use tasks to run the tests and show the output in the integrated terminal which is capable of showing the colors.

**Comment by GeorgeErickson** [comment]
This used to work on save a while back, it stopped a few months ago

**Comment by segevfiner** [comment]
It seems the current code to run Go tests rewrites package paths in the output to be full paths, I guess that's so they are clickable.

VS Code tasks currently require running a process or a shell command, and won't support this easily (Without sticking an intermediate process wrapping `go test` in the way, which is ugly). Custom task executors is probably on the VS Code backlog (I think they actually planned to work on it this iteration: https://github.com/Microsoft/vscode/issues/65570)

**Comment by oliverpool** [comment]
@segevfiner do you refer to https://github.com/microsoft/vscode/issues/76492 ?

Now that it has been implemented into vscode, is it possible to solve this issue ?

**Comment by segevfiner** [comment]
Yeah. It was possible before minus the feature that rewrites paths in the output (Without introducing a binary/script that does so and invoking a shell pipeline that runs it and `go test`). With this API you can handle the output from tasks in code and as such implement such rewriting. But I think it might require lifting a lot of code for how to implement an executer that executes a process with all its features from VS Code.

Personally I had trouble wrapping my head around the task API and task providers to figure out how to do this and coming up with how to introduce that to the existing code.

**Comment by segevfiner** [comment]
Looking into this even further. I noticed that the official Python extension has a test explorer UI for running tests. Strangely enough, it is completely custom built inside the Python extension while there is also a third-party extension implementing a similar UI: https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer for the use of other extensions. Not sure how test execution and output is handled in those test explorer implementations.

**Comment by slnt** [comment]
Any updates on this? I'd give this feature request a +1. I use a tool called `richgo` which provides colorized test output and would benefit from being able to run a task such as the following when hitting the `Run Test` button.

```json
    {
      "label": "Test Go Code",
      "type": "shell",
      "presentation": {
        "echo": true,
        "reveal": "always",
        "panel": "shared",
        "showReuseMessage": false,
        "clear": true
      },
      "command": "richgo",
      "args": [
        "test",
        "???"
      ],
    },
```

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Since there are no clear steps on how to implement this, I will be closing this issue.
If anybody has clues on how to move forward, please log an issue or create a PR in https://github.com/golang/vscode-go

Thanks for all the support & Happy Coding!

**Comment by segevfiner** [comment]
@ramya-rao-a I still believe it is a good idea to improve the way tests are being run, supporting colors, etc. But not sure what the implementation should be so as to create an issue. It might take someone who is more familiar with VS Code extensions, or authors one, to help here. As I described previously the situations with the test explorers and that it is unclear what's the recommended way for extensions to handle tests.

**Comment by ramya-rao-a** [comment]
I agree @segevfiner 

@hyangah, @stamblerre, Do you want to consider having an issue to evaluate how we run tests and the possible improvements we can do there regarding displaying the output? It can include to explore how the test explorer extensions do this and take a look at [tasks](https://code.visualstudio.com/docs/editor/tasks) as well

**Comment by stamblerre** [comment]
Yep that makes sense, thanks @segevfiner. Filed https://github.com/golang/vscode-go/issues/187.
