### ISSUE TITLE
Intellisense appends code to my comments ending with periods.

### ISSUE THREAD

**Issue by egtork** [Microsoft/vscode-go#2006]
If I enter a C-style block comment such as:
```
/* 
This is a comment.
*/
```
and press enter to move to the next line, Intellisense autocompletes after the period. I end up something like:
```
/*
This is a comment.append
*/
```
Is this expected behavior? If I end a line with shift+enter, rather than just enter, this prevents auto-complete. Is this the only workaround?

**Comment by dhowden** [comment]
I also see this issue a lot, not just in comments but also when using float values.

@ramya-rao-a I think maybe the point here is that the completion should not be activated if the cursor is within a comment? (i.e. in the same way that completions don't show when the cursor is inside a string value).  Would be great if this could also be done for float values too.

To reproduce what I'm talking about:
```golang
// Try typing.<ENTER>
var x = 10.<ENTER>
```

and you'll get:

```golang
// Try typing.SOMECOMPLETION
var x = 10.ANOTHERCOMPLETION
```

**Comment by ramya-rao-a** [comment]
Completions being triggered when `.` is typed in multi line comments is being tracked in #1072

Stopping them in single line comments is easy and is implemented already.

@dhowden The case of floats is interesting. That I believe is a bug in `gocode` itself. I have logged an upstream bug https://github.com/mdempsky/gocode/issues/74 to track this.

Meanwhile, to avoid such scenarios, you can disable the setting `editor.acceptSuggestionOnEnter`. Suggestions are accepted if you press either ENTER or TAB. Disabling this setting stop accepting suggestions when pressing enter.

**Comment by ramya-rao-a** [comment]
@dhowden The upstream bug is fixed. Can you run `Go: Install/Update Tool`, select `gocode`, press Ok to update it?

**Comment by dhowden** [comment]
That works great.  Thanks.

The issue with single-line comments appears when the comment is describing an exported name. In that case adding a period to the end causes the completion to appear.

<img width="902" alt="exported_name" src="https://user-images.githubusercontent.com/2822/47273005-38101e00-d5d9-11e8-85fc-6cc57a7dc2e4.png">
