### ISSUE TITLE
Autocomplete does not work after update when multiple matches for package

### ISSUE THREAD

**Issue by dbarzdys** [Microsoft/vscode-go#2011]
I updated go to 1.11 and vscode 1.28.1. 
When I write package name I get a suggestion, but when I press enter box does not disappear and so cannot get any suggestion for names that exists in that package. Extension just tries to autocomplete package selection.
![bug](https://user-images.githubusercontent.com/9341303/46943980-94bf8600-d079-11e8-9599-c76726abeee2.png)

**Comment by heavydawson** [comment]
Seeing the same with:
VSCode 1.28.1
Go 1.11.1
vscode-go 0.6.91

**Comment by ramya-rao-a** [comment]
The fix for this issue is now out in the latest update to the Go extension (0.6.92)
