### ISSUE TITLE
Debug Console for Node 10 and Sailsjs outputs different than Node version < 8

### ISSUE THREAD

**Issue by L1qu1d1c3** [Microsoft/vscode-go#2018]
VSC version: 1.28.0
Platform: Windows 10
NodeJS version: 10.8.0
SailsJS version: 0.12

Hello,

When I installed NodeJS 10, all of the sudden I noticed that the output in the Debug Console wasn't the same as before. When I was in an older version, the output used to be like this:
![image](https://user-images.githubusercontent.com/7668505/47086374-92942d80-d219-11e8-8aea-42c97a8217a4.png)

After putting it on 10, the output all of the sudden came out to this:
![image](https://user-images.githubusercontent.com/7668505/47086200-25809800-d219-11e8-8e9c-f5cc24d8fbf5.png)

I think the main issue is that VSC only outputs things that are on "debug" level of logging, and not other levels - something I don't want, i'd like it to output everything.

Steps to Reproduce:

1. Install NodeJS >=10
2. Install SailsJS
3. Create an example app
4. Debug the app with basic node debug config (node app.js)

**Comment by ramya-rao-a** [comment]
@L1qu1d1c3 This repository is for the Go extension to VS Code. Please log your issue in the main repository for VS Code which is https://github.com/Microsoft/vscode

**Comment by L1qu1d1c3** [comment]
Omg so sorry!! I totally didnt see that!
