### ISSUE TITLE
golint installation failed

### ISSUE THREAD

**Issue by lqflqf** [Microsoft/vscode-go#2019]
System environment:

1. MacBook Pro late 2016, Mojave
2. go version go1.11.1 darwin/amd64
3. VS code version 1.28.1, Go plugin 0.6.91

Steps to reproduce:

1. Run command "Go: Install/Update Tools"
2. Select "golint" and then click ok to install

Expected result:
golint installed successfully

Actual result:
golint installation failed

Error message:
golint:
Error: Command failed: /usr/local/bin/go get -u -v github.com/golang/lint/golint
github.com/golang/lint (download)
package github.com/golang/lint/golint: code in directory /Users/qifan/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
github.com/golang/lint (download)
package github.com/golang/lint/golint: code in directory /Users/qifan/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"

Additional info

- According to guide on [golint](https://github.com/golang/lint), "go get -u golang.org/x/lint/golint" makes the installation succesfull
- There is code submitted several days ago to [golint](https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58#diff-5d137a611fd4de5bdbf3200f5cf19ef6). Not sure whether it is the root cause.

**Comment by karthikraobr** [comment]
golint has been moved from [github](github.com/golang/lint/golint) to [golangX](golang.org/x/lint/golint). Hence the issue. This [commit](https://github.com/Microsoft/vscode-go/commit/9608da32ef6c5677db19d076574ed5770997d011) fixes that, but you will have to wait for a release or manually install golint.

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to the Go extension (0.6.92)
