### ISSUE TITLE
gopkgs not be used 

### ISSUE THREAD

**Issue by fhbzyc** [Microsoft/vscode-go#202]
I 'm sure I run **go get -u -v github.com/tpng/gopkgs**
but  import not auto show available package
why?

**Comment by lukehoban** [comment]
Do you see any packages in the list at all?

You may need to have built the packages within the GOPATH before they will show up in the import list.

**Comment by fhbzyc** [comment]
http://123.59.44.48/2.png
see the picture, I have  $GOPATH/bin/gopkgs

http://123.59.44.48/1.png
not auto show me the "net" , "net/http" , ......

**Comment by ramya-rao-a** [comment]
@fhbzyc Do you still have this issue? The links are not opening for me. Can you provide screenshots of the problem you are seeing?

**Comment by ramya-rao-a** [comment]
@fhbzyc I'll close this issue as we havent heard back from you in a while.
If you still see the issue, please comment here and I will open the issue and investigate.
