### ISSUE TITLE
Outline double-click usability issues

### ISSUE THREAD

**Issue by mgood** [Microsoft/vscode-go#2022]
VSCode: 1.28.2
Go extension: 0.6.92

Clicking on an entry in the outline causes the view to scroll to center that entry. This makes it difficult to double-click and jump to an item since the view moves between clicks.

So, to go to an entry you have to:
1) single-click on the item
2) move your mouse to the new location after it scrolls
3) double-click to jump

I think the intended behavior is to scroll to make the current item visible when moving through the source file. Scrolling after clicking on an item in the view is unnecessary since it's inherently visible in that case.

Ideally the view should only scroll if the new highlight is not already visible, but if that's difficult it might also make sense to just avoid scrolling when triggered by a click in the outline view.

**Comment by ramya-rao-a** [comment]
The UI behavior is managed by VS Code itself and extensions have no control over it. Please log this issue in the main VS Code repo at https://github.com/Microsoft/vscode
