### ISSUE TITLE
`go vet` process along with `go build` keeps churning CPU even when VSCode is closed.

### ISSUE THREAD

**Issue by ankur-anand** [Microsoft/vscode-go#2023]
I've updated the go-tool today `0.6.91` and after that, it uses a huge chunk of CPU all the time,

average load
```command
 ankur ▶ ~/Desktop/…/twoSum ▶ $ ▶ uptime
 20:20:31 up 30 min,  1 user,  load average: 14.81, 14.53, 11.34
```
process consuming high % of CPU
```command
 ankur ▶ ~/Desktop/…/twoSum ▶ $ ▶ ps -eo pcpu,pid,user,args | sort -k1 -r -n | head -10
52.6  5406 ankur    /usr/bin/go build -o /tmp/vscode-goKgQCYU/go-code-check .
51.6  5415 ankur    /usr/bin/go vet ./...
51.4  5600 ankur    /usr/bin/go build -o /tmp/vscode-goKgQCYU/go-code-check .
51.2  5596 ankur    /usr/bin/go vet ./...
41.9  7757 ankur    go list -e -json -compiled -test=true -export=true -deps=true -tags= -- .
41.8  7644 ankur    /usr/bin/go build -o /tmp/vscode-gosPJvQE/go-code-check .
41.7  7784 ankur    /usr/bin/go vet ./...
41.5  7640 ankur    /usr/bin/go vet ./...
41.3  7791 ankur    /usr/bin/go build -o /tmp/vscode-gosPJvQE/go-code-check .
 3.7 13848 ankur    /usr/lib/chromium-browser/chromium-browser --type=renderer --field-trial-handle=16958379901938881904,8968544606741407184,131072 --service-pipe-token=7304318142105071701 --lang=en-US --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=7304318142105071701 --renderer-client-id=45 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
````

Next highest usage after `go` process is `chromium process` and its only consuming `3.7`% of cpu, as compared to all other `go` process consuming around `50`%

Observation:

Multiple `go vet` process keeps running along with the corresponding `go build`, even when vscode has been closed.

go version
`go version go1.11 linux/amd64`

CPU Consuming most time in the User Space
```command
 ankur ▶ ~/Desktop/…/twoSum ▶ $ ▶  mpstat
Linux 4.15.0-36-generic (thinkpad-e470) 	10/17/2018 	_x86_64_	(4 CPU)

08:17:21 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
08:17:21 PM  all   78.19    0.06    3.00    0.26    0.00    0.22    0.00    0.00    0.00   18.27
```

I closed the vscode process and waited for 15min but the CPU load never went down. And this issue started coming after tool update only.

_Originally posted by @ankur-anand in https://github.com/Microsoft/vscode-go/issues/1994#issuecomment-430664872_

**Comment by ramya-rao-a** [comment]
There was no change related to build/vet in the 0.6.91 release. Can you install an older version of the extension to confirm that this issue got introduced in 0.6.91? 

- You can get the older version say 0.6.89 by downloading the vsix file from https://github.com/Microsoft/vscode-go/releases/tag/0.6.89. 
- Disable the `extensions.autoUpdate` setting in VS Code
- Then run `code --install-extension Go-0.6.89.vsix` to install the older version

Can you also share your settings for `go.buildOnSave` and `go.VetOnSave`?

Do you see this issue in smaller projects as well?
