### ISSUE TITLE
When breakpoints that set inside init()s is hit, the IDE does not show which line the program is running to. And the callstack of the current go routine is empty.

### ISSUE THREAD

**Issue by szmcdull** [Microsoft/vscode-go#2038]
Steps to Reproduce:

Sample code:
![image](https://user-images.githubusercontent.com/2098590/47335946-3b320980-d6c0-11e8-980d-29e32b4c5084.png)

1. Set a breakpoint inside init()
2. Start Debugging

**Comment by szmcdull** [comment]
Using the dlv command line debugger, I can successfully set a line breakpoint inside init() and debug just like normal.

**Comment by ramya-rao-a** [comment]
This should be fixed with https://github.com/Microsoft/vscode-go/pull/2029

Can you try our latest [beta-version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)

**Comment by szmcdull** [comment]
Great! After installing the beta-version, it works again. But 'Check for Updates' of Visual Code return 502 error. Don't know if it is related to the beta-version?

**Comment by szmcdull** [comment]
Great! After installing the beta-version, it works again. But 'Check for Updates' of Visual Code says server returned 502. Don't know if it is related to the beta-version?

**Comment by ramya-rao-a** [comment]
The 502 error is not related to the Go extension. The update server for VS Code was down yesterday for some time. It should be up now.

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to the Go extension as well (0.7.0)
