### ISSUE TITLE
Add option to run long-running linters manually

### ISSUE THREAD

**Issue by Xjs** [Microsoft/vscode-go#2039]
I tried using gometalinter with many linters enabled in my day-to-day, but I found linting takes very long to complete. It would be great if I could trigger a full linting run (e. g. using gometalinter with many slow linters) manually, but have a fast linter (e. g. golint) set for lint-on-save.

**Comment by ramya-rao-a** [comment]
Manual linting can be triggered using the command `Go: Lint Current Package` or `Go: Lint Workspace`.
These commands will use the settings from `go.lintFlags` just like when the linter is run on file save.

One way to achieve what you want is to update the `go.lintFlags`, run the above command. Then change the flags back.

Another way is to use [tasks](https://code.visualstudio.com/Docs/editor/tasks) which you can set up any way you want to use at any time you want

**Comment by Xjs** [comment]
Reading https://github.com/Microsoft/vscode/issues/1435, I'm not sure if the support for global tasks is really that high on the vscode agenda. I put together a small patch that essentially duplicates the lint command to provide a global »Slow Lint« that can e. g. be used for gometalinter, and will send a PR. Feel free to discard it if you don't like it, but I'm going to use it for the time being. :)
