### ISSUE TITLE
Error message: "GOPATH is not set as an environment let iable or via `go.gopath` setting in Code"

### ISSUE THREAD

**Issue by jawnsy** [Microsoft/vscode-go#204]
This looks to be a find-and-replace issue (var -> let). I guess you meant "environment variable." This instance can be found using the GitHub repository text search, and shows that the problem is in ```src/goInstallTools.ts```. There are likely other instances of the same replacement problems; I have not looked for those.

**Comment by LiterallyElvis** [comment]
I didn't find any other instances of the term `let iable` or `letiable`, so hopefully this is the only change needed.

**Comment by lukehoban** [comment]
This was fixed with #205.
