### ISSUE TITLE
Environment variables not being resolved for GOPATH

### ISSUE THREAD

**Issue by dmlemos** [Microsoft/vscode-go#2040]
As I like to have my tools separated from the projects, I have set the config like this:
```json
`"go.toolsGopath": "${env:HOME}/bin/go"`
```

The error is always that the analysis tools are missing:
```
gocode-gomod:
Error: Command failed: /usr/local/bin/go build -o ${env/bin/gocode-gomod github.com/stamblerre/gocode
go: GOPATH entry is relative; must be absolute path: "${env".
For more details see: 'go help gopath'
```

According to [vscode #2809](https://github.com/Microsoft/vscode/issues/2809), more specifically this [post]( https://github.com/Microsoft/vscode/issues/2809#issuecomment-396842807) it is up to the extension to resolve environment variables.

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode-go/issues/2046#issuecomment-432848486
