### ISSUE TITLE
on ubuntu.. failed install tools go.

### ISSUE THREAD

**Issue by embiize** [Microsoft/vscode-go#2041]
Installing 12 tools at /home/user/go/bin
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  dlv
  gocode-gomod
  godef
  godef-gomod
  goreturns
  golint

Installing github.com/mdempsky/gocode FAILED
Installing github.com/mdempsky/gocode FAILED
Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED
Installing github.com/acroca/go-symbols FAILED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/derekparker/delve/cmd/dlv FAILED
Installing github.com/derekparker/delve/cmd/dlv FAILED
Installing github.com/stamblerre/gocode FAILED
Installing github.com/stamblerre/gocode FAILED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/ianthehat/godef FAILED
Installing github.com/ianthehat/godef FAILED
Installing github.com/sqs/goreturns FAILED
Installing github.com/sqs/goreturns FAILED
Installing golang.org/x/lint/golint FAILED

12 tools failed to install.

gocode:
Error: Command failed: /home/dumbdox/.go/bin/go get -u -v github.com/mdempsky/gocode
github.com/mdempsky/gocode (download)
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcexportdata?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcexportdata": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcexportdata?go-get=1
get "golang.org/x/tools/go/gcexportdata": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/internal/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/internal/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/internal/gcimporter": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/internal/gcimporter?go-get=1
get "golang.org/x/tools/go/internal/gcimporter": verifying non-authoritative meta tag
runtime
# runtime
.go/src/runtime/map.go:64:2: bucketCntBits redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:64:18
.go/src/runtime/map.go:65:2: bucketCnt redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:65:23
.go/src/runtime/map.go:69:2: loadFactorNum redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:69:18
.go/src/runtime/map.go:70:2: loadFactorDen redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:70:18
.go/src/runtime/map.go:76:2: maxKeySize redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:76:17
.go/src/runtime/map.go:77:2: maxValueSize redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:77:17
.go/src/runtime/map.go:82:2: dataOffset redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:85:4
.go/src/runtime/map.go:91:2: empty redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:91:19
.go/src/runtime/map.go:92:2: evacuatedEmpty redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:92:19
.go/src/runtime/map.go:93:2: evacuatedX redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:93:19
.go/src/runtime/map.go:93:2: too many errors
github.com/mdempsky/gocode (download)
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcexportdata?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcexportdata": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcexportdata?go-get=1
get "golang.org/x/tools/go/gcexportdata": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/internal/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/internal/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/internal/gcimporter": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/internal/gcimporter?go-get=1
get "golang.org/x/tools/go/internal/gcimporter": verifying non-authoritative meta tag
runtime
# runtime
.go/src/runtime/map.go:64:2: bucketCntBits redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:64:18
.go/src/runtime/map.go:65:2: bucketCnt redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:65:23
.go/src/runtime/map.go:69:2: loadFactorNum redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:69:18
.go/src/runtime/map.go:70:2: loadFactorDen redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:70:18
.go/src/runtime/map.go:76:2: maxKeySize redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:76:17
.go/src/runtime/map.go:77:2: maxValueSize redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:77:17
.go/src/runtime/map.go:82:2: dataOffset redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:85:4
.go/src/runtime/map.go:91:2: empty redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:91:19
.go/src/runtime/map.go:92:2: evacuatedEmpty redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:92:19
.go/src/runtime/map.go:93:2: evacuatedX redeclared in this block
	previous declaration at .go/src/runtime/hashmap.go:93:19
.go/src/runtime/map.go:93:2: too many errors

gopkgs:
Error: Command failed: /home/dumbdox/.go/bin/go get -u -v github.com/uudashr/gopkgs/cmd/gopkgs
github.com/uudashr/gopkgs (download)
github.com/karrick/godirwalk (download)
github.com/pkg/errors (download)
runtime

**Comment by ramya-rao-a** [comment]
Can you try running `go get -u -v github.com/mdempsky/gocode` from the terminal and see if that succeeds or if you get the same error?

**Comment by igorkim** [comment]
$ go get -u -v github.com/mdempsky/gocode

```github.com/mdempsky/gocode (download)
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcexportdata?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcexportdata": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcexportdata?go-get=1
get "golang.org/x/tools/go/gcexportdata": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/internal/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/internal/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/internal/gcimporter": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/internal/gcimporter?go-get=1
get "golang.org/x/tools/go/internal/gcimporter": verifying non-authoritative meta tag
runtime
# runtime
/usr/local/go/src/runtime/map.go:64:2: bucketCntBits redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
/usr/local/go/src/runtime/map.go:65:2: bucketCnt redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
/usr/local/go/src/runtime/map.go:69:2: loadFactorNum redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:69:18
/usr/local/go/src/runtime/map.go:70:2: loadFactorDen redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:70:18
/usr/local/go/src/runtime/map.go:76:2: maxKeySize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:76:17
/usr/local/go/src/runtime/map.go:77:2: maxValueSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:77:17
/usr/local/go/src/runtime/map.go:82:2: dataOffset redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:85:4
/usr/local/go/src/runtime/map.go:91:2: empty redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
/usr/local/go/src/runtime/map.go:92:2: evacuatedEmpty redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
/usr/local/go/src/runtime/map.go:93:2: evacuatedX redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:93:19
/usr/local/go/src/runtime/map.go:93:2: too many errors
```
