### ISSUE TITLE
when debug, can't get whole value if variable too long

### ISSUE THREAD

**Issue by ryzencool** [Microsoft/vscode-go#2043]
when in debug mode, if some variable's value too long, the debug panel can't display whole value, i try to right click, the options are gray

`macOS mojave version 10.14`
`vscoe Version 1.28.2 (1.28.2)`

![image](https://user-images.githubusercontent.com/12694592/47410409-4eb0a380-d798-11e8-9532-8fcd02f779a7.png)

**Comment by gangachris** [comment]
I think @ramya-rao-a covered this her [Gophercon 2018 Lightning Talk](https://youtu.be/mKdLiUuBnO4?t=313)

The limit is 64 characters. 

You may need to change the go delve config to enable this.

```js
go.delveConfig {
    useAPIV1: false,
    dlvLoadConfig: {
        // .....
       maxStringLen: 100
     }
}
```

**Comment by ramya-rao-a** [comment]
Thanks @gangachris 

From the 0.6.90 release of this extension on 3rd of this month, we are using version 2 of delve apis by default. So all you need to add in your settings is

```
go.delveConfig {
    dlvLoadConfig: {
       maxStringLen: 100
    }
}
```

The issue with the context menu entries being disabled is covered in #1990
