### ISSUE TITLE
Test code coverage for test not in the same package path

### ISSUE THREAD

**Issue by tarekbadrshalaan** [Microsoft/vscode-go#2044]
as you can find [here](https://github.com/tarekbadrshalaan/goStuff/tree/master/blockchainfiles), I write the package in main package directory and create the test package in sub directory 
- package files
|
-- package_test
|
-- package_example

and Test coverage check in the package directory only 
**/usr/local/go/bin/go test -timeout 30s github.com/tarekbadrshalaan/goStuff/configuration -coverprofile=/tmp/vscode-goQL6BAQ/go-code-cover**

so how should I pass the test package path to Test coverage?

**Comment by ramya-rao-a** [comment]
What did you do to get that command to run?

**Comment by tarekbadrshalaan** [comment]
this command **/usr/local/go/bin/go test -timeout 30s github.com/tarekbadrshalaan/goStuff/configuration -coverprofile=/tmp/vscode-goQL6BAQ/go-code-cover** printed in output tab when I used the command to toggle test coverage

I sent the command to you to make sure that the coverage test didn't run test in sub directory.

**Comment by ramya-rao-a** [comment]
I tried your example and the coverage file that gets generated is empty for me.
Can you open `/tmp/vscode-goQL6BAQ/go-code-cover` which is the cover profile file in your case and share its contents?

**Comment by tarekbadrshalaan** [comment]
Verstion : 0.6.94-beta.3
`/tmp/vscode-goDbs9q9/go-code-cover`
the contents
```
mode: set
```

**Comment by ramya-rao-a** [comment]
As you can see Go itself doesnt support this scenario. There is no coverage data in that file. Therefore, we cannot do much from the editor's perspective.
