### ISSUE TITLE
Test coverage color refresh issue in split view

### ISSUE THREAD

**Issue by SteelPhase** [Microsoft/vscode-go#2045]
macOS 10.13.6, and Windows 10 Version 1809 (OS Build 17763.55)
vscode 1.28.2
go plugin 0.6.93
golang v1.11.1

Tested with only the go plugin enabled

While writing unit tests for a go file, I had vscode split horizontally. The left panel being my actual code lets say `thing.go`. The right panel was `thing_test.go`. After code coverage highlighting has been toggled, any time you focus back on the `thing.go` panel, the code coverage highlighting intensity increases. I'm assuming this means that instead of redrawing the code coverage, it's just layering the code coverage over the existing rendered panel. During my testing I found that if `thing.go` shared it's panel with another file in a tab, switching tabs would reset the code highlighting to the expected state.
If you then select a file in another panel, and focus back on `thing.go` the issue will appear again.
Once the issue has occurred, you can not use the right click menu `Go: Toggle Test Coverage In Current Package` to hide the code coverage highlighting

I'm not 100% sure what the issue is, or what component is the culprit. I'm assuming that this is a problem with the vscode-go plugin.

Steps to Reproduce:

1. Start VScode however you like
2. Create a simple go file with a few functions to test
3. Create a simple unit test for those functions
4. Open the go file and unit test file in vscode
4. Select the unit test files tab, right click, and select split right
5. Close the unit test files tab in the left panel.
6. Execute the unit test
  - Click `run package tests` in unit test file, and click to bring focus back into the go file
  - **OR**: Right click in the go file and click `Go: Toggle Test Coverage In Current Package`
7. Switch focus to the unit test file in the right panel by clicking inside of the open file
8. Switch focus to the go file in the left panel by clicking inside of the open file

Here's a gif demonstrating the highlighting issue

![vscode-go-issue-2045](https://user-images.githubusercontent.com/2711058/47450155-7e5cad00-d792-11e8-8969-bed830fb6dde.gif)

Example code
`thing.go`
```golang
package thing

import (
	"bytes"
)

func function(times int) string {
	output := bytes.Buffer{}
	for i := 0; i < times; i++ {
		output.WriteRune('A')
	}

	return output.String()
}
```

`thing_test.go`
```golang
package thing

import (
	"testing"
)

func Test_function(t *testing.T) {
	type args struct {
		times int
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{"sanity-4-As", args{4}, "AAAA"},
		{"sanity-4-As", args{8}, "AAAAAAAA"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := function(tt.args.times); got != tt.want {
				t.Errorf("function() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @SteelPhase!

> I'm assuming this means that instead of redrawing the code coverage, it's just layering the code coverage over the existing rendered panel.

I believe so too.

PRs are welcome to fix this bug. 

Code Pointers:
- [Build and Debug the Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- [applyCodeCoverage](https://github.com/Microsoft/vscode-go/blob/0.6.93/src/goCover.ts#L230) is called every time the active editor changes. For example: when you move focus from one split editor to another
- We need to [disposeDecorators](https://github.com/Microsoft/vscode-go/blob/0.6.93/src/goCover.ts#L109) before adding a new layer of decorators.

**Comment by ramya-rao-a** [comment]
This is fixed with https://github.com/Microsoft/vscode-go/pull/2047

Until I release an update, you can get the fix using the [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension

**Comment by ramya-rao-a** [comment]
The fix is now out in the latest update to this extension (0.7.0)
Thanks @diogogmt!
