### ISSUE TITLE
substituteEnv doesn't work when installing Go tools

### ISSUE THREAD

**Issue by steeve** [Microsoft/vscode-go#2046]
When using this setting in the workspace's settings:
```json
	"go.toolsGopath": "${env:GOPATH}",
```

Then using the `Go: Install/Update Tools`, it fails with the following:
```
Installing 1 tool at ${env/bin
  goimports

Installing golang.org/x/tools/cmd/goimports FAILED

1 tools failed to install.

goimports:
Error: Command failed: /usr/local/bin/go get -u -v golang.org/x/tools/cmd/goimports
go: GOPATH entry is relative; must be absolute path: "${env".
For more details see: 'go help gopath'
go: GOPATH entry is relative; must be absolute path: "${env".
For more details see: 'go help gopath'
```

Which leads me to believe `substituteEnv` isn't used in that case.

For the record, the reason we do this, is because we have one `GOPATH` per project as we are using Bazel:
```json
	"go.gopath": "${workspaceFolder}/bazel-out/darwin-fastbuild/bin/code_completion_gopath",
	"go.toolsGopath": "${env:GOPATH}",
```

**Comment by ramya-rao-a** [comment]
We just merged a PR last week that should fix this. Try out our [beta-version](
https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)

**Comment by ramya-rao-a** [comment]
@steeve That's right. Fixed it.
