### ISSUE TITLE
Local variables are not displayed when gorilla handlers.LoggingHandler is used

### ISSUE THREAD

**Issue by dimdiden** [Microsoft/vscode-go#2049]
Hi Team,

I have an issue with local variables not being displayed in VSC debugger:
<img width="1231" alt="screen shot 2018-10-25 at 23 08 25" src="https://user-images.githubusercontent.com/9885385/47528178-2a92b680-d8ad-11e8-8bea-f0baa4703c40.png">

Go version: go version go1.11.1 darwin/amd64
Delve version: Version: 1.1.0

Sample code:
```
import (
	"fmt"
	"log"
	"net/http"
	"os"
	"runtime"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()
	router.HandleFunc("/test", TestFunc)
	err := http.ListenAndServe(":8080", handlers.LoggingHandler(os.Stdout, router))
	// err := http.ListenAndServe(":8080", router)
	log.Fatal(err)
}

func TestFunc(w http.ResponseWriter, r *http.Request) {
	s := "Hi there!"
	runtime.Breakpoint()
	fmt.Fprint(w, s)
}
```

Steps to Reproduce:
1. Run debug
2. Make a GET request to http://localhost:8080/test

Additional details:
Console Delve works without issues:
```
dlv debug
Type 'help' for list of commands.
(dlv) continue
> main.TestFunc() ./main.go:25 (PC: 0x13224d9)
    20:	}
    21:	
    22:	func TestFunc(w http.ResponseWriter, r *http.Request) {
    23:		s := "Hi there!"
    24:		runtime.Breakpoint()
=>  25:		fmt.Fprint(w, s)
    26:	}
(dlv) locals
s = "Hi there!"
```

**Comment by dimdiden** [comment]
Just in case, here are the logs:
[vscode-go-debug.txt](https://github.com/Microsoft/vscode-go/files/2516644/vscode-go-debug.txt)

**Comment by ramya-rao-a** [comment]
@dimdiden Local variables in the debug viewlet are only visible when a breakpoint is hit. In your screenshot above, the code is running and no breakpoint is hit.

**Comment by dimdiden** [comment]
@ramya-rao-a  I've set the breakpoint with the help of runtime.Breakpoint().
It doesn't matter the way I set the breakpoint, the issue remains the same.
Could you please reopen the issue?

**Comment by ramya-rao-a** [comment]
Unfortunately, we are only aware of the breakpoints created in VS Code itself. I dont see how we can support programmatic breakpoints like the ones created using `runtime.Breakpoint()` :(

**Comment by dimdiden** [comment]
@ramya-rao-a I took another screenshot, where you can see VSCode breakpoints and no variables:
<img width="1231" alt="screen shot 2018-10-31 at 06 29 27" src="https://user-images.githubusercontent.com/9885385/47766300-b013cd80-dcd6-11e8-9b11-951747aeaa35.png">

Kindly take a look at this issue, really looks like a bug. Thank you.

**Comment by ramya-rao-a** [comment]
@dimdiden 

When a breakpoint is hit, the debug tool bar looks like the below

![image](https://user-images.githubusercontent.com/16890566/47768606-0876ab00-dc96-11e8-9782-230f67087ae2.png)

You will see the play button
You can also see the breakpoint being hit. The whole line gets highlighted.
The running code is paused and we are able to ask delve for all the available variables and their values.
It is at this point that the debug pane will show the variables. 

When you hit continue after this or when no breakpoints are hit, then the debug tool bar looks like how it does in your screenshots. No play button, instead you see the pause button.
At this point the code is running, there is no breakpoint hit and therefore no variables to show.

**Comment by dimdiden** [comment]
@ramya-rao-a 
Thank you for the explanation. I understand the workflow, though.
I think I need to change the description of the issue to "no breakpoint hit and no variables showed if gorilla handlers.LoggingHandler is used"

I've recorded the behaviour for your convenience:
https://drive.google.com/file/d/1YEFCV4Z5OcWX3MuLRCJ5zTMUCO2ZoMEn/view

Could you please take a look once again?

**Comment by ramya-rao-a** [comment]
I am able to hit the breakpoint even with the loggingHandler

<img width="1042" alt="screen shot 2018-10-31 at 9 56 20 pm" src="https://user-images.githubusercontent.com/16890566/47833420-e04f8080-dd57-11e8-90cc-5f7794472973.png">

What version of Go and delve are you using ? And what OS are you on?
My details:
-  `go version go1.8 darwin/amd64`
- Mac OS
- Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $

**Comment by dimdiden** [comment]
My env is the same:
* Mac OS: 10.14 (18A391)
* go version go1.11.1 darwin/amd64
* Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $

I don't what to think now:( Maybe any debug configuration? I'm using the default one.

**Comment by ramya-rao-a** [comment]
I am using default too :)

Add `"trace": "verbose"` to your debug config and try again.
This will add logs in the debug console. Please share that

**Comment by dimdiden** [comment]
I've attached the logs in the second comment in this thread.
Could you please take a look?

**Comment by dimdiden** [comment]
Hi @ramya-rao-a ,
Thanks, here they are:
[vscode-go-debug_ERROR.txt](https://github.com/Microsoft/vscode-go/files/2541169/vscode-go-debug_ERROR.txt)
[vscode-go-debug_SUCCESS.txt](https://github.com/Microsoft/vscode-go/files/2541170/vscode-go-debug_SUCCESS.txt)

**Comment by ramya-rao-a** [comment]
This is most likely related to #1987

Can you use the latest [beta-version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension which has the fix?

**Comment by dimdiden** [comment]
Yes! It works. Thank you very much for the help @ramya-rao-a !

**Comment by ramya-rao-a** [comment]
Great! Happy Coding!

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to the Go extension as well (0.7.0)
