### ISSUE TITLE
Support colors from tests coverage on the minimap

### ISSUE THREAD

**Issue by Edznux** [Microsoft/vscode-go#2052]
Hi,

I think it would be pretty convenient to have the colors from tests displayed in the minimap.
It would allow a quick overview of the coverage in that file (which function are covered, is there a missing part over a big portion of fully covered code...)
thanks

**Comment by ramya-rao-a** [comment]
That does sound cool. The minimap is core VS Code feature to which extensions cannot contribute at the moment and so we cannot implement this feature.
