### ISSUE TITLE
go-langserver + modules failing to complete with "expected selector or type assertion, found 'return'"

### ISSUE THREAD

**Issue by alecthomas** [Microsoft/vscode-go#2053]
![image](https://user-images.githubusercontent.com/41767/47542979-d67bd800-d894-11e8-9db8-16f35fdb4c43.png)

**Comment by alecthomas** [comment]
This is from https://github.com/alecthomas/participle. I'm happy to provide more information if necessary.

**Comment by ramya-rao-a** [comment]
AFAIK the language server doesnt support modules yet.
But just to be sure, please log an issue at https://github.com/sourcegraph/go-langserver

**Comment by alecthomas** [comment]
I'm pretty sure [this commit](https://github.com/sourcegraph/go-langserver/commit/c4a270b23b2758e42bea161154f84d02e43f1aff) allows the langserver to support modules, similar to the equivalent change in @stamblerre 's [gocode](https://github.com/stamblerre/gocode/commit/a07fefd98fdcd9d2c16aa3f61d8e89eda396bf99) fork.

But I filed the issue here because it looks (?) like, from that error, vscode might be passing the wrong location through to the langserver?

**Comment by ramya-rao-a** [comment]
From your screenshot, the `expected selector or type assertion, found 'return'` error is showing up against the `textDocument/documentSymbol` request. That is related to the file outline feature and not auto-completion feature. 

Are you using the completion feature from the language server as well? Can you share your settings related to the language server?
