### ISSUE TITLE
IntelliSense activates on single-line comments for exported symbols.

### ISSUE THREAD

**Issue by dhowden** [Microsoft/vscode-go#2063]
Steps to Reproduce:

Add to a comment on an exported name, using the period charater `.` will cause IntelliSense to activate.

![](https://user-images.githubusercontent.com/2822/47273005-38101e00-d5d9-11e8-85fc-6cc57a7dc2e4.png)

Linked to https://github.com/Microsoft/vscode-go/issues/2006

**Comment by ramya-rao-a** [comment]
The suggestion for the exported member name should only appear in the start of the comment.

PRs are welcome to fix this
Code Pointers:
- [Build and Debug the Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- The fix should go here: https://github.com/Microsoft/vscode-go/blob/master/src/goSuggest.ts#L87
