### ISSUE TITLE
Type hint alignment

### ISSUE THREAD

**Issue by Delphier** [Microsoft/vscode-go#2064]
Can the field type be aligned?

![image](https://user-images.githubusercontent.com/6134731/47786057-7d54ee00-dd45-11e8-8ae3-39a103616bd0.png)

**Comment by karthikraobr** [comment]
I think [piece of code](https://github.com/Microsoft/vscode-go/blob/cb6257afbb6d9b54baf22c4319efc5ca403e757c/src/goExtraInfo.ts#L35) is responsible for the hover text. I am very bad at formatting/styling and  js/html, hence couldn't fix it :)

**Comment by ramya-rao-a** [comment]
We use external tools to fetch this information. By default, this is provided by `godoc`.
`gogetdoc` does a much better job

@Delphier 
- Set `go.docsTool` setting to `gogetdoc`
- Run `Go: Install/Update Tools` -> Select `gogetdoc` -> Press Ok to install it
- Reload VS Code and try the hover again.

Also, please log this isssue for the `godoc` tool as well.

@karthikraobr We just read the output from these tools and avoid doing any formatting on our own.
