### ISSUE TITLE
testutils: relax regex to include just Test, Example and Benchmark as valid test functions

### ISSUE THREAD

**Issue by buyology** [Microsoft/vscode-go#2071]
https://github.com/Microsoft/vscode-go/commit/ad95b526bcc4ca3f0edc6ffe8283271be804f305 introduced a stricter regex for `Test`, `Benchmark` and `Example` to avoid matching just Test, Example or Benchmark.

These are in fact perfectly fine as function names:

```go
package x

import "testing"

func Test(t *testing.T) {}
```

```
» go test -v
=== RUN   Test
--- PASS: Test (0.00s)
PASS
ok      x   0.007s
```

**Comment by ramya-rao-a** [comment]
I didnt realize that `Test`, `Benchmark` and `Example` were valid names for tests. Thanks for reporting!

PRs are most welcome!

Code Pointers:
- [Build and Debug the Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- The regular expressions to update are https://github.com/Microsoft/vscode-go/blob/0.6.93/src/testUtils.ts#L27-L29

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to the Go extension (0.8.0)
Thanks @Charliekenney23!
