### ISSUE TITLE
gorename: can't find package containing... when using modules

### ISSUE THREAD

**Issue by bitfield** [microsoft/vscode-go#2074]
Steps to Reproduce:

1. In this repo: https://github.com/bitfield/uptimerobot
2. Open `main.go`, select the `main` identifier, and 'Rename symbol' to anything.
3. Error message in output:

```
Rename failed: gorename: can't find package containing /Users/john/git/bitfield/uptimerobot/main.go 
```

`GOPATH` is not set and there is a valid `go.mod` file in the module root.

```
go version go1.11.1 darwin/amd64
vscode-go 0.6.94-beta4
Code 1.28.2
```

**Comment by lanrat** [comment]
I'm having the same issue, unfortunately it appears that the `gorename` tool does not yet support go modules. 

More info: https://github.com/Microsoft/vscode-go/issues/1954#issuecomment-426387803

**Comment by bitfield** [comment]
I thought @ramya-rao-a had already forked `gorename` to add module support... or was that wishful thinking on my part?

**Comment by ramya-rao-a** [comment]
`gorename` doesn't yet support modules.

See [Go modules support in Visual Studio Code](https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)

**Comment by rohmanhm** [comment]
![image](https://user-images.githubusercontent.com/7524911/48501542-043eb600-e870-11e8-9e49-7168e4c63b95.png)

Using with `Find All References` it works fine. I thought it was a bug. But after browsing `gorename` it turns out that it doesn't support go modules yet.

If you still curious, You can check the status about `gorename`, here's the links:
- https://github.com/golang/go/issues/27571
- https://github.com/golang/go/issues/24661

**Comment by lanrat** [comment]
Slight update in the [Go Modules in 2019](https://blog.golang.org/modules2019) blog post today. It looks like the new [golang.org/x/tools/go/packages](https://godoc.org/golang.org/x/tools/go/packages) package will be the place where this, and other IDE integrations will implemented with support for modules.

**Comment by shaodahong** [comment]
@ramya-rao-a go module in vscode now supported, please review this issue

**Comment by douglarek** [comment]
gopls have supported go rename

**Comment by ramya-rao-a** [comment]
Thanks for the update @douglarek and @shaodahong 

@douglarek The value for the setting `go.languageServerExperimentalFeatures` that you have shared is the default value, so one doesn't need to specify the same in settings again. Would you mind updating your instructions?

The only 2 things to ensure are
- Have the setting ` "go.useLanguageServer": true`
- Get the latest version gopls

**Comment by shaodahong** [comment]
ok, found need update `gopls` version
