### ISSUE TITLE
'Go to Definition' and 'Peek Definition' don't work with go module `+incompatible` packages

### ISSUE THREAD

**Issue by kidlj** [Microsoft/vscode-go#2077]
I'm using go1.11 outside GOPATH directory. 

While importing `github.com/go-pg/pg` and building my code, the `go.mod` file adds an entry like this:
```
github.com/go-pg/pg v6.15.1+incompatible
```
The code is simple - main.go:

```
package main

import (
    "fmt"

    "github.com/go-pg/pg"
    "github.com/go-pg/pg/orm"
)

type User struct {
    Id     int64
    Name   string
    Emails []string
}

func (u User) String() string {
    return fmt.Sprintf("User<%d %s %v>", u.Id, u.Name, u.Emails)
}

type Story struct {
    Id       int64
    Title    string
    AuthorId int64
    Author   *User
}

func (s Story) String() string {
    return fmt.Sprintf("Story<%d %s %s>", s.Id, s.Title, s.Author)
}

func main() {
    db := pg.Connect(&pg.Options{
        User: "postgres",
    })
    defer db.Close()

    err := createSchema(db)
    if err != nil {
        panic(err)
    }

    user1 := &User{
        Name:   "admin",
        Emails: []string{"admin1@admin", "admin2@admin"},
    }
    err = db.Insert(user1)
    if err != nil {
        panic(err)
    }

    err = db.Insert(&User{
        Name:   "root",
        Emails: []string{"root1@root", "root2@root"},
    })
    if err != nil {
        panic(err)
    }

    story1 := &Story{
        Title:    "Cool story",
        AuthorId: user1.Id,
    }
    err = db.Insert(story1)
    if err != nil {
        panic(err)
    }

    // Select user by primary key.
    user := &User{Id: user1.Id}
    err = db.Select(user)
    if err != nil {
        panic(err)
    }

    // Select all users.
    var users []User
    err = db.Model(&users).Select()
    if err != nil {
        panic(err)
    }

    // Select story and associated author in one query.
    story := new(Story)
    err = db.Model(story).
        Relation("Author").
        Where("story.id = ?", story1.Id).
        Select()
    if err != nil {
        panic(err)
    }

    fmt.Println(user)
    fmt.Println(users)
    fmt.Println(story)
}

func createSchema(db *pg.DB) error {
    for _, model := range []interface{}{(*User)(nil), (*Story)(nil)} {
        err := db.CreateTable(model, &orm.CreateTableOptions{
            Temp: true,
        })
        if err != nil {
            return err
        }
    }
    return nil
}
```

The code above builds and works.

However, for digging into the `go-pg/pg` source code by `Go to Definition` or `Peek Definition`, when I'm in the `main.go` file shown above, everything is fine; when I'm in a `go-pg/pg` source file, like `C:\Users\kdlij\go\pkg\mod\github.com\go-pg\pg@v6.15.1+incompatible\db.go`, the `Peek` or `Go to` a definition like `orm.Formatter` imported by `github.com/go-pg/pg/orm` package don't work.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @kidlj 

@ianthehat, 

What can we expect from `godef` when trying to find a definition of a symbol which is used in a package under `pkg/mod` ?

**Comment by ianthehat** [comment]
godef needs to be run in the "project" folder not the directory of the file.
Basically you need the CWD of godef to be below the module root so it can find the go.mod file (which also means you should be detecting it as the module branch the same way, by checking the directory you are going to use to run godef). Then you hand it the absolute path to a file in the module cache. If that does not work then it is a bug in godef or go/pacakges, but it should work (it did in my tests).

**Comment by rubenzinho07** [comment]
😈

Em Dom, 4 de nov de 2018 19:09, Ramya Rao <notifications@github.com>
escreveu:

**Comment by ianthehat** [comment]
https://go-review.googlesource.com/c/tools/+/148199 contains a fix.
Once that is submitted, running godef in the project folder with an absolute path into the module cache should work.

**Comment by lockp111** [comment]
godef-gomod not work,vscode-go version v0.7.0 on macos.

**Comment by qjebbs** [comment]
@lockp111 try update tool `gocode-gomod` and/or update to go extension beta, it works.

**Comment by saibing** [comment]
@kidlj 
[bingo](https://github.com/saibing/bingo) is a new go language server that support go 1.11 module.

you can try it.

**Comment by ramya-rao-a** [comment]
@ianthehat After syncing the latest from your fork of `godef`, now I get the error `godef: There must be at least one package that contains the file` for all symbols regardless of std lib or external packages.

**Comment by ianthehat** [comment]
That is normally the message you would get if you are compiling either a new godef against an old go/packages or vice versa, it happens because of the switch from "contains:" to "file=" in the query format.

**Comment by ramya-rao-a** [comment]
I have pushed 2 fixes that should essentially fix the problems listed in this issue
- Use current project that is opened in VS Code as cwd for all Go to Definition operations
- When the current file is from the module cache ($GOPATH/pkg/mod), use the module aware tools.

Please try the latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)

**Comment by ramya-rao-a** [comment]
The fix for this is now available in the latest version of the Go extension (0.8.0)
