### ISSUE TITLE
`The "godoc" command is not available` upon hover

### ISSUE THREAD

**Issue by kroppt** [Microsoft/vscode-go#2078]
Version of VS Code: `1.28.2`
Version of Go plugin: `0.6.93`
Version of Go: `1.11.1`

OS/Platform you are working on:
`Linux 4.18.3-gentoo`

- sample code which can be used to reproduce the issue:
```golang
package main

func main() {
}
```

- any Go related settings you might have added/changed:
None or valid `go.gopath`

Steps to Reproduce:

1. Update tools
2. Open a Go file with extension enabled
3. Hover over function
4. Minimal information shows up in tooltip, and a notification says, `The "godoc" command is not available.` No Go extension output. Warnings show up in dev tools upon hover:

`[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

Workaround:
- Change `go.docsTool` to `gogetdoc` after go-get'ing the binary.

**Comment by ramya-rao-a** [comment]
We use the `godoc` binary that is shipped with the Go distribution. You must be missing that. Check your $GOROOT/bin

See https://bugs.archlinux.org/task/60537

We should fallback to `go doc` in such cases though..

**Comment by kroppt** [comment]
The [portage ebuild](https://packages.gentoo.org/packages/dev-lang/go) just runs `make.bash` from source and copies the folders over (including bin). So, I think this is an issue with building from source.

**Comment by ramya-rao-a** [comment]
In the latest update to this extension (0.7.0), I have replaced the use of `godoc` with `go doc`. So this should be fixed now.
