### ISSUE TITLE
vscode-go breakpoints do not work in opensuse 15

### ISSUE THREAD

**Issue by wcn00** [microsoft/vscode-go#2079]
This isn't a request for help, but a comment to OpenSuse users out there trying to debug with vscode.
I installed an opensuse 15 machine and the latest code from the repo and found that no matter what I did (and I trolled a lot of the issues documented here to no avail) I could not get a breakpoint to hit.  My configuration has some common problems:
-my home dir (where the go source is) is a symlink.  In the past it has been sufficient to make sure that code and go are all using fully qualified dir names .. and that ~ and $HOME resolve to the real dirname.  Not so this time.
-When I set a breakpoing in code I see that it is relative to the workspace.  Yet when I get a traceback from a panic, the files go is using are fully qualified.  In the past this has been a problem, can't remember how I resolved it.

This time the problem was that I used the version of go and tools from the opensuse repo, which is 1.9.  Most things work but debugging does not.  Today I removed all those packages and installed go 1.11 from the tar archive and adjusted my env.  Now debugging works.
This may seem simple, but it has cost me about 3 days of distraction and resorting to printf debugging.  ick.

I hope this will be of some use to somebody sometime :)
wcn

**Comment by ramya-rao-a** [comment]
cc @polinasok and @quoctruong in case this is related to any of the other symlink issues we have been seeing

Thanks @wcn00!
