### ISSUE TITLE
Stop debugging in VSCode macOSX 10.14 hangs the process

### ISSUE THREAD

**Issue by nfons** [microsoft/vscode-go#2082]
Building a simple Go http server.

After starting the debugger, at a random chance, when stopping the debugger (either via stop, or restart) the service doesnt seem to be terminated properly.

I need to manually kill the zombie process to restart the debugger.

Vs code Version 1.28.2 (1.28.2)

**Comment by yuri-dzabaev** [comment]
same problem

**Comment by shay-novik** [comment]
Having the same issue

**Comment by frednomoon** [comment]
i agree - this is rly bad problem. plz solve

**Comment by bananabread** [comment]
Same for me on Ubuntu 18.04, VSCode version 1.30.2, Go extension version 0.8.0

Have to manually kill the debugging process each time I restart the debug server. Pain in the arse!

**Comment by nfons** [comment]
this was one of the reasons I switched to GoLand, having to manually kill debug process was a pain in the ass

**Comment by Esslamb** [comment]
@ramya-rao-a any ideas?

**Comment by ramya-rao-a** [comment]
Apologies for the silence on my end. I somehow missed the notification for this issue in the sea of github notifications.

I tried (on my Mac) the example at https://github.com/golang/example/tree/master/outyet, and I was able to hit breakpoints, continue, stop the debugging process and then see that the generated `debug` file is cleaned up and the debug process gracefully ends as well.

If someone here can provide a small code sample where you see this happening, then I can look into what is happening under the hood

**Comment by cousinbenson** [comment]
Thanks for the response. I can recreate the issue with this simple program...
```
package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/test", test).Methods("GET")

	srv := &http.Server{Handler: r, Addr: ":8080"}
	log.Fatal(srv.ListenAndServe())
}

func test(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("test"))
}
```

After the endpoint a few times and restarting the debugger a couple of times (2 or 3 attempts) i eventually hit the issue
`2019/02/04 10:34:31 listen tcp :8080: bind: address already in use`

This will persist until i kill the process via the terminal

Code - Insiders 1.31.0-insider
Delve 1.0.0
ms-vscode.Go@0.8.1-beta.3
OSX Mojave 10.14 (18A391)

**Comment by cousinbenson** [comment]
A couple of test results from members of my team:
```
Ubuntu 18.04
Delve 1.1.0
ms-vscode.go 0.8.0
Code 1.30.2

Reproducible: **YES**
```
```
OSX Sierra 10.12.16 (16G1408) 
Delve 1.0.0
ms-vscode.go 0.8.0
Code 1.30.2

Reproducible: **YES**
```
```
OSX Mojave 10.14 (18A391)
Delve 1.1.0
ms-vscode.go 0.8.0
Code 1.27.2

Reproducible: **NO**
```

**Comment by frednomoon** [comment]
Can confirm that the above steps replicate the issue for me. Works even if I already have a breakpoint added - adding an additional breakpoint/s will replicate.
I am on:

Delve 1.0.0-rc.1
ms-vscode.Go 0.8.1-beta.3
Code 1.30.2

**Comment by ramya-rao-a** [comment]
@cousinbenson, @frednomoon Can you try the latest version of the Go extension (0.9.0) and see if you still have the issue?

**Comment by cousinbenson** [comment]
@ramya-rao-a all good now with 0.9.0, thanks for your help

**Comment by ramya-rao-a** [comment]
There have been more improvements in the way we handle stopping of the debug process. Please try out the latest version of the extension (0.10.2) and if you still see problems, log a new issue with sample code and steps to replicate the problem.
