### ISSUE TITLE
vscode can't correctly handle type field or package variable or type highlight, but atom can.

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode-go#2083]
Left is vscode, while the right is atom.
![](https://i.postimg.cc/knGbjB30/WX20181104-121557-2x.png)

**Comment by rubenzinho07** [comment]
😈

Em Dom, 4 de nov de 2018 02:22, 李晓辉 <notifications@github.com> escreveu:

**Comment by ramya-rao-a** [comment]
Thanks for reporting @leaxoy 

I have logged an upstream bug https://github.com/atom/language-go/issues/161 to track this.
