### ISSUE TITLE
VS Code stops in init() but doesn't show anything

### ISSUE THREAD

**Issue by cfiderer** [Microsoft/vscode-go#2097]
When I set a breakpoint in an init() function and start my program with "Debug" -> "Start Debugging" or with F5, the program stops at that breakpoint - but the call stack is not available, the source line is not highlighted in the editor, I do not see any variables and I cannot step into any function called from the init() function. Sometimes, I cannot even continue.

Steps to Reproduce:

1. Take the attached "Hello, World" program.
2. Set breakpoints at line 6 and line 10.
3. Start the program with F5 or "Debug" -> "Start Debugging".

I expect that the program stops at the first breakpoint (in init()), allowing me to step into the fmt.Printf() call. 

[hello.zip](https://github.com/Microsoft/vscode-go/files/2549712/hello.zip)

**Comment by cfiderer** [comment]
PS: manually debugging the program with dlv.exe works fine.

**Comment by ramya-rao-a** [comment]
I believe this is same as #2038

Can you try our latest [beta-version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)?

**Comment by cfiderer** [comment]
Hi Ramya,

Go-0.6.94-beta.4.vsix fixes the issue.

Sorry for not detecting the older issue #2038 - and thanks for the quick response.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
