### ISSUE TITLE
Go debugger erorr:  Failed to continue - no G executing on thread 0

### ISSUE THREAD

**Issue by wcn00** [Microsoft/vscode-go#2104]
I have an http server project (not mine) and when I attempt to debug it with a breakpoint established I get 
Failed to continue - no G executing on thread 0

If I start it with no breakpoints it starts, but issues that message soon as I set a break.  

I've been through much of what is written about dlv problems here and can say:
-there is only one dlv, which was installed by "go get -u github.com/derekparker/delve/cmd/dlv"
-my GOPATH is a compound path:  /local/home/wcn00/go:/usr/local/go
-running code 1.28.2, but I tried rolling back to 27, 26, 25 and had same problem.
-go version go1.11.2 

If I run the debugger using code it creates processes:
wcn00    23881 23876  2 09:23 ?        00:00:00 /local/home/wcn00/go/bin/dlv debug .../.../dbs --headless=true --listen=127.0.0.1:8690 --api-version=2
wcn00    24091  3445  0 09:23 pts/14   00:00:00 grep --color=auto dlv
...
and immediately issues the message above.

If I run it via the console command
 dlv exec ./wcndbs
It creates processes:
wcn00    12432 12425  0 08:55 ?        00:00:00 /local/home/wcn00/go/bin/dlv debug ..../.../dbs --headless=true --listen=127.0.0.1:38110 --api-version=2
wcn00    23620 14169  2 09:22 pts/22   00:00:00 dlv exec ./wcndbs

I can set and hit breaks using the command line debugger.

Which basically looks identical from the dlv point of view.  So I think the problem is in the vscode-go extension.  Are there debug logging options for it? 
I can't share the code and creating a testcase by stripping this one down might take a long time.  And I have no time :(   (or I would just use the command line..)

Any suggestions you have will be welcome.

p.s.  The goland debugger works, but I cant afford it and I'm out of the trial period.

**Comment by ramya-rao-a** [comment]
> Which basically looks identical from the dlv point of view.

You ran `dlv exec`. I am guessing you are passing the binary to it? Can you run `dlv debug` instead in the terminal and see if it hits the breakpoints?

Can you share your debug configuration from the launch.json file?

You can add `"trace": "verbose"` to your debug configuration and then try debugging. This will add logs in the debug console which should tell us more

**Comment by wcn00** [comment]
With trace:verbose I get:
Verbose logs are written to:
/tmp/vscode-go-debug.txt
6:58:02 AM, 11/16/2018
InitializeRequest
InitializeResponse
Using GOPATH: /local/home/wcn00/go:/usr/local/go
Current working directory: /local/home/wcn00/go/src/git.tibco.com/git/product/ipaas/wi-dbservice.git/dbs
Running: /local/home/wcn00/go/bin/dlv debug git.tibco.com/git/product/ipaas/wi-dbservice.git/dbs --headless=true --listen=127.0.0.1:25777 --api-version=2
API server listening at: 127.0.0.1:25777
InitializeEvent
SetBreakPointsRequest
All cleared
Creating on: /local/home/wcn00/go/src/git.tibco.com/git/product/ipaas/wi-dbservice.git/dbs/main.go:30
SetBreakPointsRequest
All cleared
Creating on: /local/home/wcn00/go/src/git.tibco.com/git/product/ipaas/wi-dbservice.git/dbs/mysql/mysql.go:242
All set:[{"id":1,"name":"","addr":8436333,"file":"/local/home/wcn00/go/src/git.tibco.com/git/product/ipaas/wi-dbservice.git/dbs/main.go","line":30,"functionName":"main.main","Cond":"","continue":false,"traceReturn":false,"goroutine":false,"stacktrace":0,"LoadArgs":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":64,"MaxArrayValues":64,"MaxStructFields":-1},"LoadLocals":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":64,"MaxArrayValues":64,"MaxStructFields":-1},"hitCount":{},"totalHitCount":0}]
SetBreakPointsResponse
All set:[{"id":2,"name":"","addr":8131523,"file":"/local/home/wcn00/go/src/git.tibco.com/git/product/ipaas/wi-dbservice.git/dbs/mysql/mysql.go","line":242,"functionName":"git.tibco.com/git/product/ipaas/wi-dbservice.git/dbs/mysql.(*Connection).FunctionSchema","Cond":"","continue":false,"traceReturn":false,"goroutine":false,"stacktrace":0,"LoadArgs":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":64,"MaxArrayValues":64,"MaxStructFields":-1},"LoadLocals":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":64,"MaxArrayValues":64,"MaxStructFields":-1},"hitCount":{},"totalHitCount":0}]
SetBreakPointsResponse
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
**************************************************
 Program startup message....
     
Failed to continue - no G executing on thread 0
ThreadsRequest

**Comment by wcn00** [comment]
Debugging in the terminal works but is to cumbersome

**Comment by ramya-rao-a** [comment]
Well, the logs look good. No errors when creating breakpoints.

Again, when running from the terminal you are using `dlv exec` where as the Go extension is using `dlv debug`. 

- Please share the debug configuration you are using in the launch.json file
- Please try debugging in termainal using `dlv debug` and not `dlv exec` and let me know if that works

**Comment by wcn00** [comment]
I found a way for you to reproduce this (and the probable reason I stumbled on it in the first place).  
Install this parser:
go get -u github.com/lfittl/pg_query_go
go get -u github.com/kr/pretty
To into the pg_query_go package and run a test in the parse_test.go file.     it will run if there are no breakpoints set and fail if there are.
I now see that the parser package is written in c.  This is likely the wrinkle that causes the debugger problems.  So the error:

API server listening at: 127.0.0.1:32999
Failed to continue - no G executing on thread 0

may pertain to a non go thread running.

I made a little go main for this test:
package main

_import (
	"errors"
	"fmt"

	pg_query "github.com/lfittl/pg_query_go"
)

var parseErrorTests = []struct {
	input       string
	expectedErr error
}{
	{
		"SELECT CURRENT_DATE()",
		errors.New("syntax error at or near \"$\""),
	},
}

func main() {
	for _, test := range parseErrorTests {
		_, actualErr := pg_query.Parse(test.input)
		if actualErr != nil {
			fmt.Print(actualErr)
		}
	}
}_

I then ran it with 
dlv debug main.go

Set a break:
b main.go:24
continue

And it stops at the break.  
Is this enough for you to go on?
ttfn
wcn

**Comment by ramya-rao-a** [comment]
>  run a test in the parse_test.go file. it will run if there are no breakpoints set and fail if there are.

I was able to hit the breakpoints without any issues.

<img width="1012" alt="screen shot 2018-11-28 at 10 29 42 pm" src="https://user-images.githubusercontent.com/16890566/49203513-62ce5e80-f35d-11e8-8109-f48da8412869.png">

When trying out your sample code, I get the below error. Do you know what this is?

<img width="979" alt="screen shot 2018-11-28 at 10 34 28 pm" src="https://user-images.githubusercontent.com/16890566/49203627-ceb0c700-f35d-11e8-82df-e2afc2d64878.png">

**Comment by wcn00** [comment]
The error you got was to be expected.
What platform were you using?  I'm running ubuntu 18 (but it failed on 
suse as well).  Possibly a platform issue.  I don't have a mac, but I 
might be able to test on windows if I can find time.

wcn

**Comment by wcn00** [comment]
Tried on windoze, but pg_query requires gcc (as does go) so I give up.

wcn

**Comment by ramya-rao-a** [comment]
Can you try running `dlv test -- -test.run TestParse` in the terminal to debug that same test and see if that helps?

**Comment by wcn00** [comment]
Interesting.  I was able to reproduce this in dlv.  So not a code issue 
afterll:

> wcn00@gandalf:~/go/src/github.com/lfittl/pg_query_go$ dlv test -- 
> -test.run TestParseError
> Type 'help' for list of commands.
> (dlv) b TestParseError
> Breakpoint 1 set at 0x6c391b for 
> github.com/lfittl/pg_query_go_test.TestParseError() ./parse_test.go:711
> (dlv) bp
> Breakpoint unrecovered-panic at 0x435940 for runtime.fatalpanic() 
> /usr/local/go/src/runtime/panic.go:681 (0)
>         print runtime.curg._panic.arg
> Breakpoint 1 at 0x6c391b for 
> github.com/lfittl/pg_query_go_test.TestParseError() 
> ./parse_test.go:711 (0)
> (dlv) c
> > github.com/lfittl/pg_query_go_test.TestParseError() 
> ./parse_test.go:711 (hits total:1) (PC: 0x6c391b)
>    706:                 "SELECT * FROM y WHERE x IN (?, ",
>    707:                 errors.New("syntax error at end of input"),
>    708:         },
>    709: }
>    710:
> => 711: func TestParseError(t *testing.T) {
>    712:         for _, test := range parseErrorTests {
>    713:                 _, actualErr := pg_query.Parse(test.input)
>    714:
>    715:                 if actualErr == nil {
>    716:                         t.Errorf("Parse(%s)\nexpected error 
> but none returned\n\n", test.input)
> (dlv) si
> > github.com/lfittl/pg_query_go_test.TestParseError() 
> ./parse_test.go:711 (PC: 0x6c3922)
>    706:                 "SELECT * FROM y WHERE x IN (?, ",
>    707:                 errors.New("syntax error at end of input"),
>    708:         },
>    709: }
>    710:
> => 711: func TestParseError(t *testing.T) {
>    712:         for _, test := range parseErrorTests {
>    713:                 _, actualErr := pg_query.Parse(test.input)
>    714:
>    715:                 if actualErr == nil {
>    716:                         t.Errorf("Parse(%s)\nexpected error 
> but none returned\n\n", test.input)
> (dlv) si
> > github.com/lfittl/pg_query_go_test.TestParseError() 
> ./parse_test.go:711 (PC: 0x6c392a)
>    706:                 "SELECT * FROM y WHERE x IN (?, ",
>    707:                 errors.New("syntax error at end of input"),
>    708:         },
>    709: }
>    710:
> => 711: func TestParseError(t *testing.T) {
>    712:         for _, test := range parseErrorTests {
>    713:                 _, actualErr := pg_query.Parse(test.input)
>    714:
>    715:                 if actualErr == nil {
>    716:                         t.Errorf("Parse(%s)\nexpected error 
> but none returned\n\n", test.input)
> (dlv) s
> > github.com/lfittl/pg_query_go_test.TestParseError() 
> ./parse_test.go:712 (PC: 0x6c3945)
>    707:                 errors.New("syntax error at end of input"),
>    708:         },
>    709: }
>    710:
>    711: func TestParseError(t *testing.T) {
> => 712:         for _, test := range parseErrorTests {
>    713:                 _, actualErr := pg_query.Parse(test.input)
>    714:
>    715:                 if actualErr == nil {
>    716:                         t.Errorf("Parse(%s)\nexpected error 
> but none returned\n\n", test.input)
>    717:                 } else if !reflect.DeepEqual(actualErr, 
> test.expectedErr) {
> (dlv) s
> > github.com/lfittl/pg_query_go_test.TestParseError() 
> ./parse_test.go:713 (PC: 0x6c3a04)
>    708:         },
>    709: }
>    710:
>    711: func TestParseError(t *testing.T) {
>    712:         for _, test := range parseErrorTests {
> => 713:                 _, actualErr := pg_query.Parse(test.input)
>    714:
>    715:                 if actualErr == nil {
>    716:                         t.Errorf("Parse(%s)\nexpected error 
> but none returned\n\n", test.input)
>    717:                 } else if !reflect.DeepEqual(actualErr, 
> test.expectedErr) {
>    718:                         t.Errorf("Parse(%s)\nexpected error 
> %s\nactual error %s\n\n", test.input, test.expectedErr, actualErr)
> (dlv) si
> > github.com/lfittl/pg_query_go_test.TestParseError() 
> ./parse_test.go:713 (PC: 0x6c3a07)
>    708:         },
>    709: }
>    710:
>    711: func TestParseError(t *testing.T) {
>    712:         for _, test := range parseErrorTests {
> => 713:                 _, actualErr := pg_query.Parse(test.input)
>    714:
>    715:                 if actualErr == nil {
>    716:                         t.Errorf("Parse(%s)\nexpected error 
> but none returned\n\n", test.input)
>    717:                 } else if !reflect.DeepEqual(actualErr, 
> test.expectedErr) {
>    718:                         t.Errorf("Parse(%s)\nexpected error 
> %s\nactual error %s\n\n", test.input, test.expectedErr, actualErr)
> (dlv) si
> > github.com/lfittl/pg_query_go_test.TestParseError() 
> ./parse_test.go:713 (PC: 0x6c3a0f)
>    708:         },
>    709: }
>    710:
>    711: func TestParseError(t *testing.T) {
>    712:         for _, test := range parseErrorTests {
> => 713:                 _, actualErr := pg_query.Parse(test.input)
>    714:
>    715:                 if actualErr == nil {
>    716:                         t.Errorf("Parse(%s)\nexpected error 
> but none returned\n\n", test.input)
>    717:                 } else if !reflect.DeepEqual(actualErr, 
> test.expectedErr) {
>    718:                         t.Errorf("Parse(%s)\nexpected error 
> %s\nactual error %s\n\n", test.input, test.expectedErr, actualErr)
> (dlv) s
> > github.com/lfittl/pg_query_go.Parse() ./pg_query.go:16 (PC: 0x6b5df8)
>     11: func ParseToJSON(input string) (result string, err error) {
>     12:         return parser.ParseToJSON(input)
>     13: }
>     14:
>     15: // Parse the given SQL statement into an AST (native Go structs)
> =>  16: func Parse(input string) (tree ParsetreeList, err error) {
>     17:         jsonTree, err := ParseToJSON(input)
>     18:         if err != nil {
>     19:                 return
>     20:         }
>     21:
> (dlv) s
> > github.com/lfittl/pg_query_go.Parse() ./pg_query.go:17 (PC: 0x6b5e40)
>     12:         return parser.ParseToJSON(input)
>     13: }
>     14:
>     15: // Parse the given SQL statement into an AST (native Go structs)
>     16: func Parse(input string) (tree ParsetreeList, err error) {
> =>  17:         jsonTree, err := ParseToJSON(input)
>     18:         if err != nil {
>     19:                 return
>     20:         }
>     21:
>     22:         // JSON unmarshalling can panic in edge cases we don't 
> support yet. This is
> (dlv) s
> > github.com/lfittl/pg_query_go.ParseToJSON() ./pg_query.go:11 (PC: 
> 0x6b5cf3)
>      6:
>      7:         "github.com/lfittl/pg_query_go/parser"
>      8: )
>      9:
>     10: // ParseToJSON - Parses the given SQL statement into an AST 
> (JSON format)
> =>  11: func ParseToJSON(input string) (result string, err error) {
>     12:         return parser.ParseToJSON(input)
>     13: }
>     14:
>     15: // Parse the given SQL statement into an AST (native Go structs)
>     16: func Parse(input string) (tree ParsetreeList, err error) {
> (dlv) s
> > github.com/lfittl/pg_query_go.ParseToJSON() ./pg_query.go:12 (PC: 
> 0x6b5d17)
>      7:         "github.com/lfittl/pg_query_go/parser"
>      8: )
>      9:
>     10: // ParseToJSON - Parses the given SQL statement into an AST 
> (JSON format)
>     11: func ParseToJSON(input string) (result string, err error) {
> =>  12:         return parser.ParseToJSON(input)
>     13: }
>     14:
>     15: // Parse the given SQL statement into an AST (native Go structs)
>     16: func Parse(input string) (tree ParsetreeList, err error) {
>     17:         jsonTree, err := ParseToJSON(input)
> (dlv) s
> > github.com/lfittl/pg_query_go/parser.ParseToJSON() 
> ./parser/parser.go:21 (PC: 0x6b4953)
>     16: func init() {
>     17:         C.pg_query_init()
>     18: }
>     19:
>     20: // ParseToJSON - Parses the given SQL statement into an AST 
> (JSON format)
> =>  21: func ParseToJSON(input string) (result string, err error) {
>     22:         inputC := C.CString(input)
>     23:         defer C.free(unsafe.Pointer(inputC))
>     24:
>     25:         resultC := C.pg_query_parse(inputC)
>     26:
> (dlv) s
> > github.com/lfittl/pg_query_go/parser.ParseToJSON() 
> ./parser/parser.go:22 (PC: 0x6b4974)
>     17:         C.pg_query_init()
>     18: }
>     19:
>     20: // ParseToJSON - Parses the given SQL statement into an AST 
> (JSON format)
>     21: func ParseToJSON(input string) (result string, err error) {
> =>  22:         inputC := C.CString(input)
>     23:         defer C.free(unsafe.Pointer(inputC))
>     24:
>     25:         resultC := C.pg_query_parse(inputC)
>     26:
>     27:         defer C.pg_query_free_parse_result(resultC)
> (dlv) s
> > github.com/lfittl/pg_query_go/parser._Cfunc_CString() 
> _cgo_gotypes.go:117 (PC: 0x6b4058)
> (dlv) s
> > github.com/lfittl/pg_query_go/parser._Cfunc_CString() 
> _cgo_gotypes.go:118 (PC: 0x6b407b)
> (dlv) s
> > github.com/lfittl/pg_query_go/parser._cgo_cmalloc() 
> _cgo_gotypes.go:270 (PC: 0x6b488f)
> (dlv) stepout
> > github.com/lfittl/pg_query_go/parser._Cfunc_CString() 
> _cgo_gotypes.go:118 (PC: 0x6b4094)
> Values returned:
>         return value read error: "could not get g: no G executing on 
> thread 0"
>
> (dlv)


Not sure where to go from here.  I have found that the GoClipse debugger 
sorta works, but it has its own debugger implementation based on gdb.  
I'll finish this project with that tool and try to avoid native code in 
the future.

wcn

**Comment by wcn00** [comment]
I confess that I was working a similar issue with the goland folks and 
in that case they had me try a 1.16 version of dlv and it worked in that 
case.
So I updated my vscode version of dlv to the current master and ... now 
it works in vscode too!

  dlv version
Delve Debugger
Version: 1.1.0

Check it out.

wcn

**Comment by ramya-rao-a** [comment]
Thats great to know, thanks @wcn00

**Comment by b00f** [comment]
I have the same issue. It happens when I set a break point, no matter where. Without setting the break point it works. I am 100% sure that it worked before and after upgrading vscode I can see this issue. 
I believe it's because of `CGO_LDFLAGS`. Here is my configuration:
```
{
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/cmd/gallactic/main.go",
            "env": {"CGO_LDFLAGS":"${workspaceRoot}/../sputnikvm-ffi/c/libsputnikvm.a -ldl -lm"},
            "args": ["init", "-w=/tmp/chain2"],
            "showLog": false,
            "trace": "verbose"
        }
```
Link of the project: https://github.com/gallactic/gallactic

**Comment by ramya-rao-a** [comment]
@b00f Are you saying that you are seeing the `Failed to continue - no G executing on thread 0` error?
Did you try running `dlv debug` from the terminal with similar env vars and args and check if it works?

**Comment by b00f** [comment]
> Are you saying that you are seeing the Failed to continue - no G executing on thread 0 error?

Yes, Exactly. I try to check it with `dlv debug` . I will update it soon.
It's strange since I am almost sure that it worked before.

**Comment by wcn00** [comment]
I found that there is a fix in the dlv master branch for this. My 
problem, at any rate, was fixed.  Do a go get -u on dlv and see if it 
helps.  Make sure the dlv you are using is the one built from master...

wcn

**Comment by b00f** [comment]
@wcn00 The dlv in my PC (I am using Ubuntu) is the latest. Did you have `CGO_LDFLAGS` in your settings?
I have problem running dlv since it can't link with the given library.

**Comment by wcn00** [comment]
I do not have those flags in my settings.  I experimented with them in 
the GOClips plugin for eclipse (which doesn't appear to use dlv, but 
rolled its own).  I did not find that the defaults were wrong in any case.
If you are having linkage problems I would be suspicious of your 
installation.  My setup:
-go installed in   /usr/local/go
-so there is a /usr/local/go/bin/dlv


-My dev source is <home>/go

-So there is also a <home>/go/bin/dlv   so I specifically place that bin 
dir first in my PATH when debugging from code.

I have not had any problems with that setup so far.

wcn

**Comment by b00f** [comment]
I finally could run `dlv test`: find the output here:
```
CGO_LDFLAGS="/home/mostafa/go/src/github.com/gallactic/sputnikvm-ffi/c/libsputnikvm.a -ldl -lm" dlv test github.com/gallactic/gallactic/tests/  --  -test.run TestStackOverflow
Type 'help' for list of commands.
(dlv) b
Command failed: Malformed breakpoint location "" at 0: empty string
(dlv) bp
Breakpoint unrecovered-panic at 0x49b550 for runtime.fatalpanic() /usr/local/go/src/runtime/panic.go:681 (0)
        print runtime.curg._panic.arg
(dlv) b TestStackOverflow
Breakpoint 1 set at 0xb92c1b for github.com/gallactic/gallactic/tests.TestStackOverflow() ./tests/call_test.go:176
(dlv) bp
Breakpoint unrecovered-panic at 0x49b550 for runtime.fatalpanic() /usr/local/go/src/runtime/panic.go:681 (0)
        print runtime.curg._panic.arg
Breakpoint 1 at 0xb92c1b for github.com/gallactic/gallactic/tests.TestStackOverflow() ./tests/call_test.go:176 (0)
(dlv) c
> github.com/gallactic/gallactic/tests.TestStackOverflow() ./tests/call_test.go:176 (hits total:1) (PC: 0xb92c1b)
   171:         tx6 := makeCallTx(t, "gheis", crypto.Address{} /**/, testerBytes, 0, _fee)
   172:         executeAndWait(t, e.ErrNone, tx6, "gheis", crypto.Address{})
   173: }
   174:
   175: // Test creating a contract from futher down the call stack
=> 176: func TestStackOverflow(t *testing.T) {
   177:         setPermissions(t, "alice", permission.Call|permission.CreateAccount)
   178:
   179:         /*
   180:            contract Factory {
   181:               address a;
(dlv) si
> github.com/gallactic/gallactic/tests.TestStackOverflow() ./tests/call_test.go:176 (PC: 0xb92c22)
   171:         tx6 := makeCallTx(t, "gheis", crypto.Address{} /**/, testerBytes, 0, _fee)
   172:         executeAndWait(t, e.ErrNone, tx6, "gheis", crypto.Address{})
   173: }
   174:
   175: // Test creating a contract from futher down the call stack
=> 176: func TestStackOverflow(t *testing.T) {
   177:         setPermissions(t, "alice", permission.Call|permission.CreateAccount)
   178:
   179:         /*
   180:            contract Factory {
   181:               address a;
(dlv) si
> github.com/gallactic/gallactic/tests.TestStackOverflow() ./tests/call_test.go:176 (PC: 0xb92c2a)
   171:         tx6 := makeCallTx(t, "gheis", crypto.Address{} /**/, testerBytes, 0, _fee)
   172:         executeAndWait(t, e.ErrNone, tx6, "gheis", crypto.Address{})
   173: }
   174:
   175: // Test creating a contract from futher down the call stack
=> 176: func TestStackOverflow(t *testing.T) {
   177:         setPermissions(t, "alice", permission.Call|permission.CreateAccount)
   178:
   179:         /*
   180:            contract Factory {
   181:               address a;
(dlv) s
> github.com/gallactic/gallactic/tests.TestStackOverflow() ./tests/call_test.go:177 (PC: 0xb92c32)
   172:         executeAndWait(t, e.ErrNone, tx6, "gheis", crypto.Address{})
   173: }
   174:
   175: // Test creating a contract from futher down the call stack
   176: func TestStackOverflow(t *testing.T) {
=> 177:         setPermissions(t, "alice", permission.Call|permission.CreateAccount)
   178:
   179:         /*
   180:            contract Factory {
   181:               address a;
   182:               function create() returns (address){
(dlv) s
> github.com/gallactic/gallactic/tests.setPermissions() ./tests/permission_test.go:26 (PC: 0xb96b73)
    21:         require.NoError(t, err)
    22:
    23:         return tx
    24: }
```

**Comment by ramya-rao-a** [comment]
@b00f You mentioned a few times that you believe the CGO_LDFLAGS makes a difference. Can you try debugging without that?

**Comment by ramya-rao-a** [comment]
@b00f In that case, can you log a new issue to track this? Even if the error being thrown is the same as what this issue covers, the root cause may be different.

It would be super helpful if you can also provide a small code sample where you see this issue consistently along with the debug configuration you are using.
