### ISSUE TITLE
Lint tool not working

### ISSUE THREAD

**Issue by MattiaCostamagna** [Microsoft/vscode-go#2106]
Hi all!

I have a problem with the vscode-go extension that doesn't lint any errors in my code.
It stopped working since I upgraded my laptop's Ubuntu version to 18.10.

If I toggle the developer tools and save a file that contains a syntax error, I get these lines in the console:

```
[Extension Host] /path/to/my/file.go:11:1: expected declaration, found s log.ts:171
ERR An unknown error occurred. Please consult the log for more details.
```
I already tried to disable every extensions I had previously installed except for vscode-go. I also tried to uninstall and reinstall the extension, but nothing changed.

My user settings file contains the following:
```json
{
        "go.inferGopath": true,
	"go.buildOnSave": "workspace",
	"go.docsTool": "gogetdoc",
	"go.lintTool": "golint"
}
```

The "PROBLEMS" tab is empty and I can't see any error except for the one that appears after I save in the developer tools.

Here are some info:

> OS: Ubuntu 18.10
Extension version: 0.7.0
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mattia/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mattia/go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/3039"
GOTMPDIR=""
GOTOOLDIR="/snap/go/3039/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-Wa,-mrelax-relocations=no"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build184325656=/tmp/go-build -gno-record-gcc-switches"

I remember that the extension worked perfectly before upgrading the OS.
Everything that is not the golint tool is currently working.
What can I do to fix this?

Thanks a lot!

**Comment by ramya-rao-a** [comment]
What version of Go are you using?
Syntax errors should show up when the extension runs `go build` and not necessarily the linter.
Can you set `go.buildOnSave` to `package` and try again?

If this happens consistently in a small program, then can you share the same?

**Comment by MattiaCostamagna** [comment]
Hi @ramya-rao-a 
this is the output of "go version"
`go version go1.11.2 linux/amd64`

Setting `package` in `go.buildOnSave` didn't make any difference.
I don't know if the project I'm working on is big (it's actually my first real project using Go), the compiled program is 6 and a half MB, but I tried the same in a small program with just a `fmt.Println("Hello world")` and a syntax error, but nothing happens.

**Comment by ramya-rao-a** [comment]
- Can you share the small program you are using, with the expected error?
- Are you using Go modules or is your code under the GOPATH? Run `Go: Current GOPATH` to see your current gopath

**Comment by MattiaCostamagna** [comment]
Here's a sample code with a syntax error that is not linted:

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello world")
	this is a syntax error	
}
```

In the developer tools I can see the following errors:
- expected ';', found is
- expected '}', found 'EOF'
but none of them appears in the problems tab.

My project is not located under my GOPATH, if I run `Go: Current GOPATH` I see `/path/to/my/project:/path/to/my/real/gopath`, which I guess is correct since I've set `inferGopath` to `true` (setting it to `false` doesn't change anything). 
vscode-go tools are located under my real GOPATH of course.

**Comment by ramya-rao-a** [comment]
Make a change and save the file. Then open the output panel (View -> Output), select "Go" from the drop down on the top right of the panel.

This should show you the output from the build, lint and vet processes that run on each file save. Do you see errors there? Can you share a screenshot of that?

Are errors reported as expected when your code is under your GOPATH?

**Comment by MattiaCostamagna** [comment]
Hi!

I did what you asked. Here's the screenshot

![vscode-go](https://user-images.githubusercontent.com/4272711/48346080-456d7500-e67a-11e8-8446-69d7aaf32029.png)

Every time I saved the file, it writes those 3 lines and then nothing else.
I tried doing the same test under my GOPATH, but the result is the same:

![vscode-go2](https://user-images.githubusercontent.com/4272711/48346217-bad94580-e67a-11e8-9726-4a623787862f.png)

**Comment by ramya-rao-a** [comment]
Looks like the build/vet/lint processes are not giving any expected output...

Are you using symlinks by any chance? They have a habit of messing things up :(

**Comment by MattiaCostamagna** [comment]
@ramya-rao-a you're right, I installed Go using [snap](https://snapcraft.io/), and it created the following symlinks

![vscode-go3](https://user-images.githubusercontent.com/4272711/48398802-1c082400-e722-11e8-8422-8af37e63e1e1.png)

After trying to install Go manually I can now see the expected syntax errors! 
Thanks a lot for your support!

I suppose it would be nice to have it working for snap users, but it's not probably an issure related to vscode-go.
