### ISSUE TITLE
Support custom test flags

### ISSUE THREAD

**Issue by v2ray** [Microsoft/vscode-go#211]
My project uses tags to enable/disable features during compilation. For example, 
```
go build -tags featureA ...
```

This extension provides go.buildFlags to build with custom flags, but there is no "testFlags" settings. I can build my code with featureA enabled, but can't test it with same flags.

Hopefully there will be go.testFlags behaves similar to go.buildFlags.

**Comment by lukehoban** [comment]
I'm not sure I understand what the problem is.  You can just provide `go.buildFlags` along with `"mode": "test"`, right?  If that doesn't work, could you share a more complete workflow of what you are trying to do?

**Comment by v2ray** [comment]
Not sure where to put mode: test. Is it a debug flag?

My workflow is:
1. Go to a _test.go file;
2. F1 and Go: Run tests in current package;
3. See the test result;

The output doesn't show any test files marked '// +build featureA' . I suppose the 'go test' command wasn't invoke with '-tags featureA'.

**Comment by CannibalVox** [comment]
+1, This makes it very uncomfortable to use build directives, since since they wont' be built at all.

**Comment by lukehoban** [comment]
Got it.

For now, I'm going to make it so that `go.buildFlags` is applied to running tests as well.

If you think there is a need for a separate `go.testFlags` configuration flag as well/instead, I'd be interested in details of the scenario for that.

**Comment by CannibalVox** [comment]
That's plenty for me, thanks for doing that!
