### ISSUE TITLE
Build Tags In Test Files Cause Tests Not To Be Ran Inside VS Code 

### ISSUE THREAD

**Issue by ddrake17** [Microsoft/vscode-go#2110]
I've been running into an issue when using build tags in my unit/integration tests. Our workflow separates the two by using a build tag at the top of the file, e.g.  `// +build integration` or `// +build unit`. 

VS code go will give the following output when clicking `run test` shown above a TestFunction or when clicking `run package tests` at the top of the file with a build tag:
![image](https://user-images.githubusercontent.com/9723486/48241965-4068a700-e396-11e8-8c26-16b325e7b22d.png)

A little digging reveals the problem, the terminal command line call shown in the output tab of VS Code isn't running the `go test` command correctly. When there are build tags the go test command needs the `tags` flag to properly run, e.g. `go test -tags="unit integration"` to run both. 

Unfortunately this makes running tests when using build tags impossible in VS code from what I can tell.

**Comment by ramya-rao-a** [comment]
Have you tried setting either of `go.buildTags` or the `go.testTags` setting?

**Comment by ddrake17** [comment]
Didn't know about those settings. I tried both and either one will make things work, thanks!

It would be cool if VS code automatically detected tags, but perhaps that's too much to ask for :)

**Comment by ramya-rao-a** [comment]
We could detect the tags and use it, but that can also cause unintentional issues.
User might have set some tags intentionally say for OS or arch to exclude certain tests.

#1497 is tracking a feature where we would prompt the user to update the `buildtags` setting if current file has build tag but setting doesnt. That should help this case as well.

Closing this in favor of #1497
