### ISSUE TITLE
Can not debug in Golang

### ISSUE THREAD

**Issue by rathodmayur93** [Microsoft/vscode-go#2116]
Error : no Go Files In /Users/mrathod/Documents/Mayur/FAL/Go/Code/.vscode

My Go Environment Details are as below

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mrathod/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mrathod/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wg/kp78f6w53rb6j2bvj_w43z15jy_rx1/T/go-build278546118=/tmp/go-build -gno-record-gcc-switches -fno-common"
MUMMRATHODMCL:HRMS-Go mrathod$ cd %GOPATH%\src\github.com\derekparker\delve
bash: cd: %GOPATH%srcgithub.comderekparkerdelve: No such file or directory
MUMMRATHODMCL:HRMS-Go mrathod$ $GOPATH
MUMMRATHODMCL:HRMS-Go mrathod$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mrathod/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mrathod/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
MUMMRATHODMCL:HRMS-Go mrathod$ echo $GOPATH

MUMMRATHODMCL:HRMS-Go mrathod$ echo $go.gopath
.gopath
MUMMRATHODMCL:HRMS-Go mrathod$  go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mrathod/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mrathod/go"GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wg/kp78f6w53rb6j2bvj_w43z15jy_rx1/T/go-build302704713=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by ramya-rao-a** [comment]
> Error : no Go Files In /Users/mrathod/Documents/Mayur/FAL/Go/Code/.vscode

This tells me that you started debugging when the launch.json file was open in the active editor and the debug configuration had either `$file` to `$fileDirname` in the `program` field.

Open the Go file you want to debug and press F5 then.
