### ISSUE TITLE
"Debugging GO Code using VSCode" specifies default api version as v2 for headless delve, but troubleshooting says this is not supported

### ISSUE THREAD

**Issue by FrankSzendzielarz** [Microsoft/vscode-go#2117]
The documentation seems to be inconsistent.

As a separate issue, I am trying to understand why I am getting unverified breakpoints in a multi-debug session with one target being a docker instance with a headless delve server. 

In the troubleshooting section, I am told that v2 is not supported (though the remote launch defaults to v2 in vscode), but in the opening paragraphs of the document we are told that the default api for remoting to delve is v2. 

Either the document is inconsistent, or the implementation is inconsistent and to remote into delve we need to override the default settings.

**Comment by grazimdeoliveira7** [comment]
😆😆

**Comment by grazimdeoliveira7** [comment]
Seus capetas 😈 vao todos 🔥🔥🔥🔥

**Comment by brycekahle** [comment]
The extension does support v2 of the Delve API. The `Remote Debugging` section must be outdated.

**Comment by ramya-rao-a** [comment]
The wiki was outdated indeed. Thanks for reporting!
I have made the necessary changes
