### ISSUE TITLE
[URGENT] No output in debug console

### ISSUE THREAD

**Issue by mvrhov** [Microsoft/vscode-go#2118]
VS code just upgraded to the 1.29. When the code contains the errors the VSCode displays the dialog to cehck the debug console. However the debug debug console is completely empty.

Steps to Reproduce:

1. Upgrade to VSCode 1.29
2. Install Go 0.7.0
3. Type some go code with errors
4. Try to run the code, the VSCode displays the error dialog
5. check debug console, which is completely empty

**Comment by grazimdeoliveira7** [comment]
😅😅

**Comment by ramya-rao-a** [comment]
Thanks for reporting @mvrhov 

@isidorn We use `this.sendEvent(new OutputEvent(str, 'stderr'));` to log the errors in the debug console.
This is working in the latest Insiders but not in VS Code 1.29.1
Did anything change in this regard?

**Comment by isidorn** [comment]
I believe dup of https://github.com/Microsoft/vscode/issues/61986
And of https://github.com/Microsoft/vscode/issues/63114

**Comment by ramya-rao-a** [comment]
@isidorn This doesnt happen with the latest Insiders. Only in VS Code 1.29

We dont send any messages in the `initializeRequest` call. We start only in the `launchRequest` call.
In case of build failures, we use `sendErrorResponse` from inside the `launchRequest` call.
By this time, a bunch of OutputEvents are already sent

**Comment by isidorn** [comment]
Great to know this is fixed in latest insiders. Closing

**Comment by mvrhov** [comment]
Hey guys.. are we sure this is fixed.
Well this works for the first time now in VSCode 1.30.1, and then for the However it desn't for the 2nd+ occurence

**Comment by ramya-rao-a** [comment]
@mvrhov Can you elaborate?

**Comment by mvrhov** [comment]
Like I said. I get the output in debug console only when the first error happens. Each further error displays the old error message.

**Comment by ramya-rao-a** [comment]
Clearing the debug console before debugging a second time also results in showing the next error message. I'll create a new bug for this, thanks for reporting!

**Comment by mvrhov** [comment]
All the thanks goes to you for providing a plugin and a support for it
