### ISSUE TITLE
remotePath of '/' when debugging remote linux container translates breakpoint paths to windows local paths

### ISSUE THREAD

**Issue by FrankSzendzielarz** [microsoft/vscode-go#2119]
On Windows 10 , building a Linux docker container, add the files to a subfolder such as x/y/z

run the container with security-options="seccomp=unconfined' (and an entrypoint running dlv as follows: 

dlv test  --headless  --listen=:2345 --log=true  --api-version=1 )

In VSCODE, make sure the files you are debugging are also in a local c:\<workspace>\x\y\z (otherwise breakpoint matching does not work ever anyway). 

In launch.json set the  remotePath to "/" (see below)

With verbose logging, note that the breakpoint cannot be set or verified, because it translates the path to C:\<workspace>\x\y\z (windows file separator)

Repeat the process adding the source files instead to a subfolder eg /src/x/y/z

Set remote path to /src/

Breakpoints now work because VSCode translates the breakpoint path to Linux file separated absolute path.

 {

            "name": "Remote debug in Docker",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "program": "${workspaceFolder}",
            "env": {},
            "args": [],

            "remotePath": "/",

            "port": 2345, // Port 

            "host": "172.17.0.2" ,
            "showLog": true,
            "trace": "verbose"

        }

**Comment by ramya-rao-a** [comment]
> Repeat the process adding the source files instead to a subfolder eg /src/x/y/z

You do this in the container or on Windows?

**Comment by FrankSzendzielarz** [comment]
Always must be both for breakpoints to work. So src would be the root of the path on docker, and root relative to gopath locally

Sent from my Windows Phone
________________________________

**Comment by ramya-rao-a** [comment]
This has been fixed in the latest update to the Go extension (0.11.7)
Thanks @quoctruong for the fix & thanks @FrankSzendzielarz for logging the issue.

Happy Coding!
