### ISSUE TITLE
Configure selector keys for suggest widget

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode-go#212]
Whenever e.g. a completion list is summoned (by a configured trigger character, e.g. `.` or `>`), both Tab and Enter are valid for selection by default. More than once I've accidentally accepted the suggestion rather than doing a line break as intended.

https://github.com/mitaki28/vscode-clang/issues/8 is a good example of this where a `completionProvider` is configured and triggered by `>`, causing issues when trying to do a line break:
![](https://cloud.githubusercontent.com/assets/1016104/13473657/4b754dec-e088-11e5-8aa3-35e09aee946a.png)

At first I'd thought to suggest that the default should be Tab to avoid all of this. But then I came to think that perhaps more ideally this should be configurable by the extension that registers a provider with `triggerCharacters`. What do you think?

**Comment by lukehoban** [comment]
Just checking - did you intend to ask about this specifically for the Go extension, or is this a questions/ask for the core VS Code repo?

**Comment by csholmq** [comment]
Whoops. Accidentally clicked the wrong repo last night :)
