### ISSUE TITLE
Add support for "Go to Type Definition"/"Peek Type Definition"

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/vscode-go#2121]
Implement [TypeDefinitionProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TypeDefinitionProvider`) which would add support for "Go to Type Definition" and "Peek Type Definition". This would be really helpful for Go, which uses type inference a lot, so you rarely have a type to click on for "Go to Definition"/"Peek Definition".

**Comment by ramya-rao-a** [comment]
Doesnt the existing `Go to Implementation` command help do the same? It uses `guru implements`.

**Comment by segevfiner** [comment]
> Doesnt the existing `Go to Implementation` command help do the same? It uses `guru implements`.

I think the "Go to Implementation" command as implemented will go to the implementation of an interface/method. If you use it on a variable it will just fail.

What is asked here is being able to go to the definition of the type of the symbol under the cursor. Go to Type Definition on a struct variable should go to where that struct type is defined.

**Comment by ramya-rao-a** [comment]
Got it, thanks!

**Comment by segevfiner** [comment]
https://github.com/Microsoft/vscode-go/pull/2136 was merged. I guess this can be closed.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest version of the Go extension (0.8.0)
Thanks @hummerd!
