### ISSUE TITLE
problem starting the go debugger. 

### ISSUE THREAD

**Issue by odedpriva** [Microsoft/vscode-go#2127]
Hi, 

I have problem starting the go debugger. 

I'm using the latest macOS Mojave, go 1.11.2 and latest VSCode 

![image](https://user-images.githubusercontent.com/4990615/48508647-c5046b00-e857-11e8-86e9-0f39bed2367d.png)

I can't seem to find any log about this issue and the message I get is a generic "Failed to continue: Check the debug console for details." but the console does not print any data. 

![image](https://user-images.githubusercontent.com/4990615/48508696-e49b9380-e857-11e8-8f44-e1fcc539e517.png)

I'd appreciate any advice.

**Comment by georgewfraser** [comment]
Also having things bug after switching to mojave

**Comment by georgewfraser** [comment]
This is a problem with delve and can be fixed according to the instructions in https://github.com/derekparker/delve/issues/1398

Reproduced below:

It seems you have to download the updated command line tools from the Apple developer website (xcode-select --install) is broken for the latest MacOS Mojave version (10.14.1).

https://developer.apple.com/download/more/

**Comment by ramya-rao-a** [comment]
>  I get is a generic "Failed to continue: Check the debug console for details." but the console does not print any data.

@odedpriva  The console not showing anything is being tracked in https://github.com/Microsoft/vscode-go/issues/2118.  Use the latest [Insiders](https://code.visualstudio.com/insiders) which should show the errors in the console.

@georgewfraser Thanks for the links! @odedpriva I am hoping the links @georgewfraser has provided should solve your issue
