### ISSUE TITLE
VSCode cannot goto declaration in the special condition : golang code used "type SomeType=AnotherType" 

### ISSUE THREAD

**Issue by ayanmw** [Microsoft/vscode-go#2131]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:
1. Code True like:
===================
E:\work\go_type_equal>tree /F
卷 文档 的文件夹 PATH 列表
卷序列号为 3848-636F
E:.
├─pkg
│  └─windows_amd64
│          gamelib.a
│          scenelib.a
│
└─src
    │  main.go
    │
    ├─gamelib
    │      slice.go
    │
    └─scenelib
            nodePath.go
2. Code Are 
==============

E:\work\go_type_equal>type src\main.go
`
package main

import (
        "scenelib"
)

func main() {
        var test = scenelib.NewNode()
        test.SomeFunc()
}
`
E:\work\go_type_equal>type src\scenelib\nodePath.go
`
package scenelib

import (
        "gamelib"
)

type Node struct {
        allNode []*gamelib.NodeIDSlice
}

func NewNode() *Node {
        return &Node{}
}
func (this *Node) SomeFunc() {

}
`
E:\work\go_type_equal>
E:\work\go_type_equal>type src\gamelib\slice.go
`
package gamelib

import (
        "fmt"
)

type IntSlice []int

func (this *IntSlice) Decode(from string) {
        fmt.Println("IntSlice Decode implement")
}

//type NodeIDSlice []int //Not have problem,but I Muste redeclaration Decode func,that's bad !
type NodeIDSlice = IntSlice //has Problem with vscode goto declaration.

// ERROR of duplication Decode to IntSlice.Decode
// func (this *NodeIDSlice) Decode(from string) {
//      fmt.Println("NodeIDSlice Decode implement")
// }

func (this *NodeIDSlice) SomeFunc() {
        fmt.Println("NodeIDSlice SomeFunc implement")
}
`
3. when I am edit src\scenelib\nodePath.go ,I want jump to defination of *gamelib.NodeIDSlice , VS Code Just  cannot work correct;

If I use code "type NodeIDSlice []int" instead of " type NodeIDSlice = IntSlice ", the vscode can jump to *gamelib.NodeIDSlice ;

4.This is not a compile problem ,but VSCode BUG ,Golang support the feature ,but VSCode-Go not support this feature ,please fix this !!!!!!

[go_type_equal.zip](https://github.com/Microsoft/vscode-go/files/2588082/go_type_equal.zip)

**Comment by ramya-rao-a** [comment]
Add `"go.docsTool": "gogetdoc"` to  your settings and then the Go to definition feature should work.

By default, we use the `godef` tool, which doesnt seem to work in this case.
Please log a bug in https://github.com/rogpeppe/godef

**Comment by ayanmw** [comment]
all my bad,my godef is old!  (one version of 2017year) .
