### ISSUE TITLE
gocode-gomod daemon stays running after closing VSCode

### ISSUE THREAD

**Issue by ssergiienko** [Microsoft/vscode-go#2132]
Steps to Reproduce:

1. Open any Go project with Go modules and use auto-completion feature
2. Close VSCode

Actual result: daemon stays running in your system
Expected: It should be stopped with VSCode like original "gocode" daemon

Go extension v0.7.0

**Comment by oneslash** [comment]
I was trying to debug it and found this, #2134 it might be related.
What do you think @ramya-rao-a

**Comment by ramya-rao-a** [comment]
This is by design. See https://github.com/Microsoft/vscode-go/issues/26#issuecomment-254108679

**Comment by ssergiienko** [comment]
@ramya-rao-a Don't you think that it's slightly strange to ask users to do manual `pkill gocode/gocode-gomod` each time after closing IDE?

As a proposed solution for this ticket and for #26 why not just save PID and internal flag "started_by_vscode" and stop daemon on this condition:
`if pid == saved_pid AND started_by_vscode == True then stop_daemon()`.

It's easy to implement and it will work for all cases except for super corner case when User stared VSCode then start another editor which is also use gocode but unable to restart it itself, and then close VSCode.

**Comment by ramya-rao-a** [comment]
Yes, that can be done. 

The trick is to determine if gocode was started by VS Code or not.

When the Go extension deactivates which is when the VS Code window is closed/reloaded, we can add a step that cleans up the running gocode process if it was started by VS Code.

PRs are most welcome if you want to give this a try.

Code Pointers:
- [Build and Debug extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- [deactivate()](https://github.com/Microsoft/vscode-go/blob/0.7.0/src/goMain.ts#L431) is the place where the cleanup should happen
- https://github.com/Microsoft/vscode-go/blob/0.7.0/src/goSuggest.ts#L225 is where we spawn the process that would start gocode if it isnt already running

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to the Go extension (0.8.0)
Thanks @zmb3!
