### ISSUE TITLE
Go: Command not found & dlv debug is not working

### ISSUE THREAD

**Issue by imrandurani** [Microsoft/vscode-go#2138]
Hi,
I am trying to debug go program with delve. I have tried to setup Go extension and delve in vscode. But  there is something wrong with the GOPATH. I don't know why but for some reason GO extension neither picking up the GOPATH from env variable nor from the the User / Workspace settings. I tried  *$ go env GOPATH* in vscode integrated terminal and it's working fine. But each time when I run *Go: Current GOPATH*, it returns **Go: Command not found**. Also please help me setup Delve in vscode. I have read all suggested tutorials and previous issues, no luck in my case. I am using Ubuntu 16.04 LTS and my go and workspace paths detail is given below:

Go location: home/user/tools/go
Gopath location: home/user/tools/gopath
delve binary: home/user/tools/gopath/bin
Project Folder: home/user/git/go-program

vscode location: user/bin/code

**Go env variable paths**

export GOROOT=$HOME/tools/go
export GOPATH=$HOME/tools/gopath
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

I am stuck from days, please help me out of this.

**Comment by ramya-rao-a** [comment]
> But each time when I run Go: Current GOPATH, it returns Go: Command not found.

This means that the extension has not gotten activated. Can you uninstall the extension, install it again and see if that helps?

If that still doesn't work, then delete the corresponding folder from `~/.vscode/extensions`, install it again and see if that helps

**Comment by imrandurani** [comment]
Have tried both, its still the same. However my vscode extension tab shows Enabled. One more thing, I also tried to install Go extension tools/updates and some of them failed to install.

**Comment by ramya-rao-a** [comment]
- Help -> Toggle Developer Console -> Console
- Clear the console
- Run the command `Go: Current GOPATH`
- Share any errors that show up in the console.

**Comment by imrandurani** [comment]
![selection_002](https://user-images.githubusercontent.com/43948731/49059575-95386880-f244-11e8-877a-75e44f86200a.png)
There are no errors in the console. Please take a look at attached screenshot. Thanks

**Comment by ramya-rao-a** [comment]
Thanks for sharing the screenshot @imrandurani 

The `Go: Current GOPATH` or any other command from the extension for that matter is not to be run in the terminal. These are to be run in the command pallet. So press F1 to open the command pallet and then type in the command

**Comment by imrandurani** [comment]
Thank you for correcting me! my mistake. So, Go: Current GOPATH from the command palette says /home/imran/tools/gopath . I also gave a try to execute dlv debug in integrated terminal and i guess its working fine for now. However, when I tried to launch debug from vscode, console says "INFO no standard startup: not just one text editor" and "cannot find golint". Then I tried Go: "Install/Update Tools"  and it ended up with 11 tools failed. Please take a look at screenshot. Thanks
![selection_004](https://user-images.githubusercontent.com/43948731/49133271-5f65b380-f31a-11e8-87e8-f95eaa181998.png)

**Comment by ramya-rao-a** [comment]
For the tools that failed, try installing them manually by following the instructions in https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on

The `INFO no standard startup: not just one text editor` is not related to debugging.

Can you share the error you see in the editor (not in the console) when you start debugging?

**Comment by imrandurani** [comment]
Sure, Here are the errors. 

gocode:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v github.com/mdempsky/gocode
github.com/mdempsky/gocode (download)
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/gcexportdata: unrecognized import path "golang.org/x/tools/go/gcexportdata" (https fetch: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/mdempsky/gocode (download)
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/gcexportdata: unrecognized import path "golang.org/x/tools/go/gcexportdata" (https fetch: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

go-outline:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v github.com/ramya-rao-a/go-outline
github.com/ramya-rao-a/go-outline (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/ramya-rao-a/go-outline (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

go-symbols:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v github.com/acroca/go-symbols
github.com/acroca/go-symbols (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/acroca/go-symbols (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

guru:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v golang.org/x/tools/cmd/guru
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/guru: unrecognized import path "golang.org/x/tools/cmd/guru" (https fetch: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/guru: unrecognized import path "golang.org/x/tools/cmd/guru" (https fetch: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

gorename:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v golang.org/x/tools/cmd/gorename
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/gorename: unrecognized import path "golang.org/x/tools/cmd/gorename" (https fetch: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/gorename: unrecognized import path "golang.org/x/tools/cmd/gorename" (https fetch: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

gocode-gomod:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v -d github.com/stamblerre/gocode
github.com/stamblerre/gocode (download)
Fetching https://golang.org/x/tools/go/packages?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/packages?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/packages: unrecognized import path "golang.org/x/tools/go/packages" (https fetch: Get https://golang.org/x/tools/go/packages?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/stamblerre/gocode (download)
Fetching https://golang.org/x/tools/go/packages?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/packages?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/packages: unrecognized import path "golang.org/x/tools/go/packages" (https fetch: Get https://golang.org/x/tools/go/packages?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

godef-gomod:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v -d github.com/ianthehat/godef
github.com/ianthehat/godef (download)
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/ast/astutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/ast/astutil: unrecognized import path "golang.org/x/tools/go/ast/astutil" (https fetch: Get https://golang.org/x/tools/go/ast/astutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/go/packages?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/packages?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/packages: unrecognized import path "golang.org/x/tools/go/packages" (https fetch: Get https://golang.org/x/tools/go/packages?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/go/types/typeutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/types/typeutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/types/typeutil: unrecognized import path "golang.org/x/tools/go/types/typeutil" (https fetch: Get https://golang.org/x/tools/go/types/typeutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/ianthehat/godef (download)
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/ast/astutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/ast/astutil: unrecognized import path "golang.org/x/tools/go/ast/astutil" (https fetch: Get https://golang.org/x/tools/go/ast/astutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/go/packages?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/packages?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/packages: unrecognized import path "golang.org/x/tools/go/packages" (https fetch: Get https://golang.org/x/tools/go/packages?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/go/types/typeutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/types/typeutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/types/typeutil: unrecognized import path "golang.org/x/tools/go/types/typeutil" (https fetch: Get https://golang.org/x/tools/go/types/typeutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

goreturns:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v github.com/sqs/goreturns
github.com/sqs/goreturns (download)
Fetching https://golang.org/x/tools/imports?go-get=1
https fetch failed: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/sqs/goreturns (download)
Fetching https://golang.org/x/tools/imports?go-get=1
https fetch failed: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

golint:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v golang.org/x/lint/golint
Fetching https://golang.org/x/lint/golint?go-get=1
https fetch failed: Get https://golang.org/x/lint/golint?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/lint/golint: unrecognized import path "golang.org/x/lint/golint" (https fetch: Get https://golang.org/x/lint/golint?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/lint/golint?go-get=1
https fetch failed: Get https://golang.org/x/lint/golint?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/lint/golint: unrecognized import path "golang.org/x/lint/golint" (https fetch: Get https://golang.org/x/lint/golint?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

gotests:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v github.com/cweill/gotests/...
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
https fetch failed: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
https fetch failed: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

impl:
Error: Command failed: /home/imran/tools/go/bin/go get -u -v github.com/josharian/impl
github.com/josharian/impl (download)
Fetching https://golang.org/x/tools/imports?go-get=1
https fetch failed: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/josharian/impl (download)
Fetching https://golang.org/x/tools/imports?go-get=1
https fetch failed: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by ramya-rao-a** [comment]
Those are the errors from running the `Go: Install/Update tools` command. 

I was asking about the errors that you see when debugging. Thats your original problem correct?

**Comment by imrandurani** [comment]
Yes correct. But these are also related to debugging because previously when I tried to debug, all errors in the console were related to **[extension host] like missing *golint *symbol and other tools etc. More recent error that I am experiencing while debugging is:
*[Extension Host] Command failed: /home/imran/tools/go/bin/go doc -c -cmd -u testing/subfolder ints
doc: no symbol ints in package testing/subfolder
exit status 1
Besides, I https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on to manually install the missing tools but failed, listing the same errors as I pasted in my previous comment. 

And thanks for all of your help, I really appreciate.

**Comment by imrandurani** [comment]
Actually, I tried both, with proxy and without proxy but failed. I think it's not, because if it is a network error then why installation for rest of the 11 tools would succeed in the first place. 

Regarding delve debug, *dlv debug* says *cannot find package*

*cannot find package "github.com/ethereum/go-ethereum/common" in any of:
        /home/imran/tools/go/src/github.com/ethereum/go-ethereum/common (from $GOROOT)
        /home/imran/tools/gopath/src/github.com/ethereum/go-ethereum/common (from $GOPATH)*

I am trying to build geth with delve so that I may debug the main package. Each time I try to build with delve it says "cannot find package" for many github packages that are being included in the import section.

**Comment by ramya-rao-a** [comment]
Can you try running `dlv` from the terminal and see if you are able to debug that way?

**Comment by imrandurani** [comment]
@ramya-rao-a I was able to figure it out. Actually, I checked out my project somewhere else instead of gopath. So, I checked it out at my gopath and its wroking fine now. Thank You! for all of your help. Closing the issue.
