### ISSUE TITLE
function comments  takes long time

### ISSUE THREAD

**Issue by kybom** [microsoft/vscode-go#2140]
Function comments  take long time,about 4 seconds.

![gif01](https://user-images.githubusercontent.com/24692485/48920735-93357900-eed5-11e8-8cd5-34fc7853c44a.gif)

windows 10 
CPU i7 6820HK

go 1.11.2  envs:

```
"go.gopath": "Z:\\workspace\\gowork",
"go.toolsGopath": "D:\\programs\\gotools",
```

**Comment by doxxx** [comment]
AFAIK, it's an unfortunate side-effect of using external processes to get docs. Launching processes on Windows is not as fast as Linux, and the process has to then parse the file, find the symbol, find the original definition site of the symbol, parse that file, and then return the doc string.

Using the Go Language Server speeds this up a lot, but it is also unfortunately rather unstable and uses egregious amounts of memory.

**Comment by kybom** [comment]
@doxxx   Go Language Server doesn't work. What I can do?

**Comment by kybom** [comment]
```
 "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    }
```
Go Language Server  doesn't Reduce  the time.

**Comment by kybom** [comment]
> Do you have `"go.useLanguageServer": true` in your settings.json?

yes.

**Comment by kybom** [comment]
> AFAIK, it's an unfortunate side-effect of using external processes to get docs. Launching processes on Windows is not as fast as Linux, and the process has to then parse the file, find the symbol, find the original definition site of the symbol, parse that file, and then return the doc string.
> 
> Using the Go Language Server speeds this up a lot, but it is also unfortunately rather unstable and uses egregious amounts of memory.

You are right.
In my Ubuntu18.04 VM,it takes 1s.
In my Windows 10, It takes about 3s.
Under network mount ,it takes more than 4s.

**Comment by saibing** [comment]
@kybom 
[bingo](https://github.com/saibing/bingo) is a new go language server that support go 1.11 moudle.

you can try it. the first time it may be slowly when hover, and then it will become more fast.

**Comment by WangPengJu** [comment]
@saibing  how to use  in vscode?

**Comment by saibing** [comment]
@WangPengJu 
because vscode only support go-langserver by far. so you need rename bingo(or bingo.exe) to go-langserver(or go-langserver.exe),  and then you can use bingo in vscode as the same as go-langserver.

**Comment by WangPengJu** [comment]
@saibing  thanks.

**Comment by kybom** [comment]
@saibing bingo only support go module project.

**Comment by saibing** [comment]
@kybom 

I'm sorry,  I forgot this. 

I don't have any plans to support the traditional GOPATH mode project.

Go 1.12 will give up GOPATH support, so I think it is time to turn to go module project

**Comment by kybom** [comment]
@doxxx Remote Development extend solves the problem.
[https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack](url)

**Comment by ramya-rao-a** [comment]
@kybom Thanks for letting us know what worked for you in the end.

Happy Coding!
