### ISSUE TITLE
File tests include too many tests

### ISSUE THREAD

**Issue by JPMoresmau** [Microsoft/vscode-go#2144]
Steps to Reproduce:

1. Create two go test files, one with two test functions like TestA and TestB, the other with one test function TestAA
2. Choose "run file tests" on first file
3. TestAA runs too
4. This is because the regexp generated is `^TestA|TestB$`, it should be `^(TestA|TestB)$`. 

Code is in src/testUtils.ts:
`util.format('^%s$', testFunctions.join('|'))`

Should be `util.format('^(%s)$', testFunctions.join('|'))`

I can try to submit a PR if the change is confirmed, thanks.

**Comment by ramya-rao-a** [comment]
Nice catch!
Yes that change looks right. Please go ahead and submit the PR.

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update to the Go extension (0.8.0)
Thanks @JPMoresmau!
