### ISSUE TITLE
Option to make "Find all references" work on GOPATH

### ISSUE THREAD

**Issue by neclepsio** [Microsoft/vscode-go#2154]
It would be useful to have an option to make "Find all references" work on the entire GOPATH and not only the current package.

**Comment by ramya-rao-a** [comment]
We don't restrict the search to just the current package. I believe this is a limitation of the guru tool on certain OS. On Mac, I can confirm that the results from outside the current package are also returned. What OS are you on?

Can you run the `guru referrers` command on your code and see if it returns results from outside the  package? It would need the offset information which you can get using the [show-offset](https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset) extension

**Comment by neclepsio** [comment]
Thank you. I'm on Windows 7. `guru referrers` returns the same results as vscode.

**Comment by ramya-rao-a** [comment]
Then this is a limitation on the guru tool itself.


Closing this issue in favor of the upstream issue https://github.com/golang/go/issues/24699
