### ISSUE TITLE
Feature Request: Imports Autocomplete

### ISSUE THREAD

**Issue by donatj** [Microsoft/vscode-go#216]
I would ***love*** to see autocomplete/intelisense directly typing in the `imports` area as LiteIDE does.

The "Add Import" command works, but takes you away from the code, I'd rather it autocomplete while I type as normal.

![screen capture on 2016-03-03 at 15-04-55](https://cloud.githubusercontent.com/assets/133747/13509485/5d0973b6-e151-11e5-90c4-f0b83c412676.gif)

**Comment by lukehoban** [comment]
Great suggestion.  

We currently rely on https://github.com/nsf/gocode for most of the completion behaviour.  

Looks like there is an active request/work on supporting this in gocode here: https://github.com/nsf/gocode/issues/257. 

/cc @nhooyr

**Comment by nhooyr** [comment]
I'm working on this, hopefully done soon.

**Comment by nhooyr** [comment]
nsf/gocode#332 should be merged by tomorrow!

**Comment by lukehoban** [comment]
Great!

**Comment by nhooyr** [comment]
It's been merged.

**Comment by lukehoban** [comment]
Thanks @nhooyr.  I've made some `vscode-go` adjustments to handle these new `"import"` results in VS Code.  Anyone who updates both `vscode-go` and `gocode` should start seeing these completion results.
