### ISSUE TITLE
大量消耗CPU资源，已经基本没法用了

### ISSUE THREAD

**Issue by ssqf** [Microsoft/vscode-go#2162]
go相关配置
    "go.buildOnSave": "off",
    "go.enableCodeLens": {
        "references": false,
        "runtest": false
    },
    "go.formatTool": "gofmt",
    "go.lintOnSave": "file",
    "go.autocompleteUnimportedPackages": true,

自动提示，代码格式化，错误检查 ，要么没用，要么要过很久才其作用。经常性的不能跳转到定义。版本越升级越卡了。现在使用 vscode 1.29.1，最开始使用vscode 1.10版本，虽然有些功能没有，但是很流畅。

vscode 全部关闭，重新打开，能有那么几分钟还比较流畅，过一会就开始卡了。有个taskkill 长期大量占用CPU资源，不知道是干嘛的

![image](https://user-images.githubusercontent.com/13485967/49234075-50722480-f432-11e8-90eb-ba576fd32ddd.png)

突然间会启动大量go相关程序
![image](https://user-images.githubusercontent.com/13485967/49234089-55cf6f00-f432-11e8-974c-477452739891.png)

**Comment by saibing** [comment]
可以试用一下[bingo](https://github.com/saibing/bingo)或[go-langserver](https://github.com/sourcegraph/go-langserver)，使用语言服务，会减少vscode-go调用外部程序的数目。

因为Windows上启动进程比Linux要慢很多，所以在Windows调用大量外部工具会导致编辑器有点卡。

这么多go进程，应该是调用go vet, go build导致的，你查看一下命令行一列，看一下参数有哪些，具体在干什么？

**Comment by saibing** [comment]
@ssqf 

By the way, we should use English to talk on here.

**Comment by awking** [comment]
> @ssqf
> 
> By the way, we should use English to talk on here.

why bingo only support go mod ? go mod release will in go 1.12 , so many project only haven't go.mod

**Comment by saibing** [comment]
@awking 
I am very sorry for this.

Go 1.11 already supports go module, Go 1.12 will only support go module.

> How migrate GOPATH project  to go module project?  just need run 'go mod init' in the project root directory.

If bingo support both GOPATH project and go module project at the same time,   it's code will become very complicated and will have a high maintenance cost.　but my spare time is very limited

Why the features of vscode-go is so confusing?

Because it need to support so many tools, and support both go module and gopath at the same time.

**Comment by awking** [comment]
> @awking
> I am very sorry for this.
> 
> Go 1.11 already supports go module, Go 1.12 will only support go module.
> 
> > How migrate GOPATH project  to go module project?  just need run 'go mod init' in the project root directory.
> 
> If bingo support both GOPATH project and go module project at the same time, it's code will become very complicated and will have a high maintenance cost.　but my spare time is very limited
> 
> Why the features of vscode-go is so confusing?
> 
> Because it need to support so many tools, and support both go module and gopath at the same time.

ok, This is go's mistake, I understand your decision, wo will open config GO111MODULE=on and use it.

**Comment by saibing** [comment]
@awking 

bingo already support non-go module project. please see: saibing/bingo#5

**Comment by saibing** [comment]
@ssqf 
May be you can try [bingo](https://github.com/saibing/bingo)

bingo is designed for offline editors such as vscode, vim, it focuses on code editing.

**Comment by awking** [comment]
> @awking
> 
> 宾果已经支持非go模块项目。请看：[saibing /宾果＃5](https://github.com/saibing/bingo/issues/5)



> @awking
> 
> bingo already support non-go module project. please see: [saibing/bingo#5](https://github.com/saibing/bingo/issues/5)

I already use bingo instead of go tools, Although it seems that the bingo experience is not as good as the tools at the moment, the speed of your repair is too fast. chinese gopher is good,haha

**Comment by ramya-rao-a** [comment]
@ssqf Run the command `Developer: Open Process Explorer`. This will open the process explorer which will list out all the processes started by VS Code and their CPU usage. Using this, you will be able to figure out what exactly is causing the high CPU usage

<img width="398" alt="screen shot 2018-12-02 at 8 14 07 pm" src="https://user-images.githubusercontent.com/16890566/49352808-e1cdda80-f66e-11e8-9cf1-cc7d349d3eef.png">


<img width="836" alt="screen shot 2018-12-02 at 8 14 19 pm" src="https://user-images.githubusercontent.com/16890566/49352811-e4c8cb00-f66e-11e8-9791-324b26c27839.png">
