### ISSUE TITLE
break point is not working, i want to debug using the windbg

### ISSUE THREAD

**Issue by kimyw3007** [Microsoft/vscode-go#2163]
Hi i used to vscode thesedays

but i faced some problem about debugging

I wanted to debug vcxproj(vc++) using windbg extension (https://marketplace.visualstudio.com/items?itemName=reznikdi.windbg-debug)

i complete to set this but.. problem is happend

my windbg extension setting is below 

        {
            "type": "windbg",
            "request": "launch",            
            "name": "Launch Program[test3]",
            "target": "C:/performance_center_dev/NS_AGENT_CORE/LoadGenerator/Bin/Debug/LoadGenerator.exe",
            "verbosity" : "debug",
            "args": "-l cpp -s -q 1 -o 0 -r 1 -p C:/SampleScript/CPP/Bin/Debug/VuserScriptCPP.dll -a C:/SampleScript/CPP/Bin/Debug/nsparameter.json",
            "windbgpath": "C:/Program Files (x86)/Windows Kits/10/Debuggers/x86/dbgeng.dll",
            "workingDir": "C:/SampleScript/CPP/",
            "sources" : [
                "C:/SampleScript/CPP/",
                "C:/performance_center_dev/NS_AGENT_CORE/LoadGenerator/",
                "C:/Symbols/"
            ],            
        }        

Actually I want to debug the  "VuserScriptCPP.dll" (reference "args" : -p of json)

and I already set breakpoint in VuserScriptCPP.dll's source (and I already attach source's path in "sources")

and i already attach all of pdb files

but The breakpoint in VuserScirptCPP.dll's source cannot work.. 

so  on the contrary I tried to debug LoadGenerator.exe'source in connecting VuserScriptCPP.dll's source place (like interface)

and it worked well it mean already complete to attach right pdb file..

but i want to debug  workspace of vuserScriptCPP.dll's source..

but it didn't work

please help me..

**Comment by ramya-rao-a** [comment]
@kimyw3007 Please log your issues with the `windbg` extension in https://github.com/reedz/windbg-debug.

This repository is for the vscode-go extension
