### ISSUE TITLE
go-to-definiton for third-party packages failed

### ISSUE THREAD

**Issue by lylex** [Microsoft/vscode-go#2165]
I tried to `godef` a method of a third-party package(e.g. github.com/spf13/cobra), it shows `no definition found for XXX`. However, when I `godef` a built-in package method or a local package method, it works well.

**Here is a sample code:**

```
package main

import (
  "fmt"
  "strings"

  "github.com/spf13/cobra"
)

func main() {
  var echoTimes int

  var cmdPrint = &cobra.Command{
    Use:   "print [string to print]",
    Short: "Print anything to the screen",
    Long: `print is for printing anything back to the screen.
For many years people have printed back to the screen.`,
    Args: cobra.MinimumNArgs(1),
    Run: func(cmd *cobra.Command, args []string) {
      fmt.Println("Print: " + strings.Join(args, " "))
    },
  }

  var cmdEcho = &cobra.Command{
    Use:   "echo [string to echo]",
    Short: "Echo anything to the screen",
    Long: `echo is for echoing anything back.
Echo works a lot like print, except it has a child command.`,
    Args: cobra.MinimumNArgs(1),
    Run: func(cmd *cobra.Command, args []string) {
      fmt.Println("Print: " + strings.Join(args, " "))
    },
  }

  var cmdTimes = &cobra.Command{
    Use:   "times [# times] [string to echo]",
    Short: "Echo anything to the screen more times",
    Long: `echo things multiple times back to the user by providing
a count and a string.`,
    Args: cobra.MinimumNArgs(1),
    Run: func(cmd *cobra.Command, args []string) {
      for i := 0; i < echoTimes; i++ {
        fmt.Println("Echo: " + strings.Join(args, " "))
      }
    },
  }

  cmdTimes.Flags().IntVarP(&echoTimes, "times", "t", 1, "times to echo the input")

  var rootCmd = &cobra.Command{Use: "app"}
  rootCmd.AddCommand(cmdPrint, cmdEcho)
  cmdEcho.AddCommand(cmdTimes)
  rootCmd.Execute()
}
```

**Steps to Reproduce:**

1. Paste the sample code above to go source file
2. `go mod init && go mod download`
3. Open vscode, go to `cobra.Command` definition, it shows `no definition found for Command`

**Some environments:**

* Extension (VsCodeVim) version: 0.16.3
* VSCode version: 1.29.1
* OS: MacOS 10.12.6

**Comment by ramya-rao-a** [comment]
@lylex Can you try the latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension? It has some fixes that can help.

**Comment by lylex** [comment]
@ramya-rao-a Hi, I have tried Go-0.7.1-beta.5.vsix, but still not work for me. Could you tell me is there any simple way to debug on this issue, so that I may find it myself?

**Comment by ramya-rao-a** [comment]
First make sure you have the latest version of the `godef-gomod` tool by doing the below:
- Run `Go: Install/Update Tools`
- Choose `godef-gomod`
- Press Ok to update it

If you still get the `No definition found..` error, you can see the logs by doing the below:
- First update to VS Code 1.30 which supports showing of these logs
- Open the output panel. View -> Output -> Select "Log (Extension Host)" from the drop down on the top right corner section of the panel.
- Run `Go to definition` to replicate the error

The logs will now show the exact call being made to `godef-gomod` along with the error returned by it. Please share that error.

**Comment by lylex** [comment]
@ramya-rao-a I upgraded the VS Code to 1.30, but when I run `Go: Install/Update Tools`, I can not see `godef-gomod` from the drop down list. Did I do something that make it hidden?

**Comment by ramya-rao-a** [comment]
What version of Go are you using? And what version of the Go extension?

**Comment by ramya-rao-a** [comment]
Can you share a screenshot of what you are seeing in the drop down?

**Comment by lylex** [comment]
@ramya-rao-a 
![image](https://user-images.githubusercontent.com/4638962/49983234-69371a00-ff9c-11e8-821e-c2c3fe77a9d8.png)

**Comment by ramya-rao-a** [comment]
Ah! Thats because `go.docsTool` is set to `gogetdoc`. Set that back to `godoc`.

**Comment by lylex** [comment]
@ramya-rao-a `godef` is fine. Actually, after I changed "User Setting" -> go.useLanguageServer from `true` to `false`, everything works now. Looks like something wrong with go.useLanguageServer. :)

**Comment by ramya-rao-a** [comment]
Thanks @lylex 

The language server from Sourcegraph doesnt support modules, so that might explain why disabling it fixed the issue for you.
