### ISSUE TITLE
Unable to create break points when remote debugging unless using lldb backend

### ISSUE THREAD

**Issue by seflerZ** [Microsoft/vscode-go#2169]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1. Remote run "dlv --headless --listen 0.0.0.0:30010 attach 239910 --log" which 239910 is the target process id 

2. Local VS Code launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Remote Debug",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "program": "${workspaceRoot}/cmd/pilot-discovery",
            "apiVersion": 1,
            "remotePath": "/home/sefler/mygo/src/istio.io/istio",
            "host": "172.16.9.245",
            "port": 30010,
            "trace": "verbose",
            "env": {},
            "args": []
        }
    ]
}
```

3. Press "Start Debugging" button and the VS Code says connected, but nothing shows in the "DEBUG CONSOLE"

4. Create any break points result in no response at all
![image](https://user-images.githubusercontent.com/2093588/49378211-fc738280-f746-11e8-9568-73cb9956bfbb.png)

5. Unable to add break points after waiting. The verbose logs are:
9:44:30 PM, 12/3/2018
InitializeRequest
InitializeResponse
Using GOPATH: C:\Users\Sefler Zhou\go
InitializeEvent
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
SetBreakPointsRequest
All cleared
Creating on: C:\Users\Sefler Zhou\go\src\istio.io\istio\pilot\pkg\config\kube\crd\controller.go (C:/Users/Sefler Zhou/go/src/istio.io/istio/pilot/pkg/config/kube/crd/controller.go) :221

6. By using "gdlv" it works fine so my remote dlv API server should probably be well configured.

**Comment by seflerZ** [comment]
Well, I managed to solve my problem by setting the dlv backend to lldb. That is, using the following command:
```
dlv --headless --backend lldb --listen 0.0.0.0:30010 attach 239910 --log
```

**Comment by ramya-rao-a** [comment]
In the launch.json file,
- `program` needs to point to the package or the entrypoint file in the local machine that is being debugged.
- `remotePath` should point to the entrypoint file in the remote machine that is being debugged.

So the changes you made are in line with the above.

About lldb, I am not sure why that would make a difference...
Maybe because you are using api version 1?

I would be interested to know if things work when you use api version 2, keep the changes in the launch.json and not provide the `--backend` argument for dlv

**Comment by seflerZ** [comment]
Thanks for replying. I've tried many times without "--backend", unfortunately resulted in the some. My dlv version is:
```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```

I'm running VS Code on Windows 10 Pro and the target program is Ubuntu 16.04 LTS. The target program is pilot-discovery component of Istio. Both side of dlv installed the same version.

**Comment by ramya-rao-a** [comment]
@derekparker, @aarzilli This is a case of running the dlv headless on an ubuntu machine and attaching to it on a Windows machine using VS Code. Any idea why the --backend should be set to lldb here?

**Comment by aarzilli** [comment]
I'd like to see the output of `dlv --headless --listen 0.0.0.0:30010 attach 239910 --log --log-output=rpc 2>send-me-this-file.thank-you` and then attaching to it with VSCode.

**Comment by seflerZ** [comment]
Sorry keep you waiting. This is all I've got. @aarzilli 

[debugfile.txt](https://github.com/Microsoft/vscode-go/files/2684522/debugfile.txt)

**Comment by seflerZ** [comment]
Sorry keep you waiting. Here is all I've got. @aarzilli 

[debugfile.txt](https://github.com/Microsoft/vscode-go/files/2684617/debugfile.txt)

The log tells there is no file in: /home/sefler/mygo/src/istio.io/istio/mixer/pkg/api/grpcServer.go:133

But when backing with lldb, as the picture shows, the file can be found.

![image](https://user-images.githubusercontent.com/2093588/50069699-34c69680-0206-11e9-8500-4ddd15b73b79.png)

**Comment by aarzilli** [comment]
Never mind, I see that you posted the wrong long and edited the message. It's very strange that you are getting that message on the native backend but not on with the lldb backend. That error shouldn't really depend on the backend at all. Even stranger is that you say that it works with gdlv. I'm not sure what to make of this. Maybe also post the same log but with `--backend lldb`?

**Comment by ramya-rao-a** [comment]
@seflerZ Do you still have this issue? If so, can you provide the logs like @aarzilli asked for in the previous comment?

**Comment by seflerZ** [comment]
I'm terribly sorry that the whole development environment has been lost. I'm using Hyper-V to experience the Istio, but last day the machine state went wrong(it was stuck at initiation phase)  and could not work anymore. I've tried to make recovery but in vain.

Thank you for being active for this issue. Because I can not provide any further information at present, I think you can mark this issued as closed. If encountered the same problem again, I will mark it again.

Thanks, again!

**Comment by ramya-rao-a** [comment]
Thanks @seflerZ
