### ISSUE TITLE
a lot of /tmp/go-build* files.

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#2173]
After working for a few hours, I noticed my /tmp is filled with (mostly empty) go-buildXXXXXX folders.

```
┏━ oneofone@Ava ❰/tmp❱
┗━● ls /tmp/go-build* | wc -l
296
```

**Comment by zmb3** [comment]
This is a [feature](https://golang.org/cmd/go/#hdr-Build_and_test_caching) of the `go` tool.

> The go command caches build outputs for reuse in future builds. The default location for cache data is a subdirectory named go-build in the standard user cache directory for the current operating system. Setting the GOCACHE environment variable overrides this default, and running 'go env GOCACHE' prints the current cache directory. You can set the variable to 'off' to disable the cache.

**Comment by ramya-rao-a** [comment]
Thanks @zmb3!

@OneOfOne Hope that answers your concern.

**Comment by OneOfOne** [comment]
That is not related to `GOCACHE`.

`go-buildXXXX` are created by `go run`, which i'm assuming sometimes gets killed before it finishes cleaning up.

**Comment by ramya-rao-a** [comment]
`go run` is only run by the Go extension if you run the `Debug: Start without debugging` command. Do you use that command often?

**Comment by OneOfOne** [comment]
I don't use that at all, nor I ever run `go run` manually.

Most of those folders are empty, or contains an empty folder called b305.

**Comment by iaburton** [comment]
+1 to this being a relatively recent issue, unrelated to Go cache. Having spent about two hours working on a Go package today, saving frequently, I have 113 go-build* directories in /tmp for a total of 326 if you include the subdirectories.

**Comment by zmb3** [comment]
I wonder if it is [this](https://github.com/golang/go/blob/b7d3f4c0b2f421c6b7bf6ce3533f1b34b470b39d/src/cmd/go/internal/work/action.go#L227) working directory used by `go build`, which should be [cleaned up on exit](https://github.com/golang/go/blob/b7d3f4c0b2f421c6b7bf6ce3533f1b34b470b39d/src/cmd/go/internal/work/action.go#L245).
