### ISSUE TITLE
Autocompletion doesn't work for packages which were imported before saving the file

### ISSUE THREAD

**Issue by nezorflame** [Microsoft/vscode-go#2179]
Continuing the discussion started in https://github.com/Microsoft/vscode-go/issues/1944 and https://github.com/Microsoft/vscode-go/issues/2164 in a new issue.

With `"go.toolsEnvVars": { "GO111MODULE": "on" }`, `gocode-gomod` is being launched now, which is good.
But, it still fails to give suggestions to the package functions before you save the file.

**Prerequisits**
**Ext. version:** 0.7.1-beta.5
**OS:** macOS 10.14.1
Latest vscode, Go 1.11.2, all Go tools updated through `vscode-go`.
Create simple `main.go` with empty `main()`, enable modules by `go mod init`.

Steps to reproduce:
1. **Action:** Start writing `fm`
**Expect:** `fmt` package should be suggested to be imported
**Result:** success - got the suggestion:
<img width="625" alt="default" src="https://user-images.githubusercontent.com/3906766/49651224-a866e780-fa3f-11e8-8231-43065cc03477.png">

2. **Action:** Import `fmt`, write `.` to have function suggestions
**Expect:** `fmt` package functions should be suggested
**Result:** failure - nothing happens:
<img width="282" alt="default" src="https://user-images.githubusercontent.com/3906766/49651318-dfd59400-fa3f-11e8-8d41-9091afdce40a.png">

`gocode-gomod -s -debug` output (doubled for some reason?..):
```
2018/12/07 16:41:00 Got autocompletion request for '/Users/nezorflame/Go/src/test-project/main.go'
2018/12/07 16:41:00 Cursor at: 52
2018/12/07 16:41:00 -------------------------------------------------------
package main

import (
        "fmt"
)

func main() {
        fmt.#
}
2018/12/07 16:41:00 -------------------------------------------------------
2018/12/07 16:41:00 error in package test-project: /Users/nezorflame/Go/src/test-project/main.go:4:2:could not import fmt (no metadata for fmt)
2018/12/07 16:41:00 Elapsed duration: 103.788631ms
2018/12/07 16:41:00 Offset: 0
2018/12/07 16:41:00 Number of candidates found: 0
2018/12/07 16:41:00 Candidates are:
2018/12/07 16:41:00 =======================================================
2018/12/07 16:41:00 Got autocompletion request for '/Users/nezorflame/Go/src/test-project/main.go'
2018/12/07 16:41:00 Cursor at: 65
2018/12/07 16:41:00 -------------------------------------------------------
package main
import "fmt"

import (
        "fmt"
)

func main() {
        fmt.#
}
2018/12/07 16:41:00 -------------------------------------------------------
2018/12/07 16:41:00 error in package test-project: /Users/nezorflame/Go/src/test-project/main.go:2:8:could not import fmt (no metadata for fmt)
2018/12/07 16:41:00 error in package test-project: /Users/nezorflame/Go/src/test-project/main.go:5:2:fmt redeclared in this block
2018/12/07 16:41:00 error in package test-project: /Users/nezorflame/Go/src/test-project/main.go:2:8:    other declaration of fmt
2018/12/07 16:41:00 Elapsed duration: 98.44108ms
2018/12/07 16:41:00 Offset: 0
2018/12/07 16:41:00 Number of candidates found: 0
2018/12/07 16:41:00 Candidates are:
2018/12/07 16:41:00 =======================================================
```

But, if you save the file and try again, it will work this time!

3. **Action:** Save the file, delete the `.` and insert it again:
**Expect:** `fmt` package functions should be suggested
**Result:** success - got the functions now:
<img width="799" alt="default" src="https://user-images.githubusercontent.com/3906766/49651478-5a061880-fa40-11e8-90c9-78d094b5d071.png">

**Comment by ramya-rao-a** [comment]
@nezorflame The fix for this has been pushed in the upstream. Can you run the command `Go: Install/Update Tools`, choose `gocode-gomod`, press Ok to update it and try again?

**Comment by nezorflame** [comment]
Yes, it works. Great job @stamblerre!
