### ISSUE TITLE
A problem matcher generating a path to a non-existent file and jump to problem leads to an infinite loop

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-go#2184]
- VSCode Version: 1.29.1
- OS Version: macOS 10.14.1
- vscode-go 0.7.1-beta.5

Steps to Reproduce:

1. Create the following:
    **hello-nested/hello.go**:
    ```go
    package main

    import "fmt"

    foo

    func main() {
	    fmt.Println("Hello, World!")
    }
    ```

    **.vscode/tasks.json**:
    ```jsonc
    {
        // See https://go.microsoft.com/fwlink/?LinkId=733558
        // for the documentation about the tasks.json format
        "version": "2.0.0",
        "tasks": [
            {
                "label": "build",
                "type": "shell",
                "command": "go build",
                "options": {
                    "cwd": "hello-nested"
                },
                "problemMatcher": "$go",
                "group": {
                    "kind": "build",
                    "isDefault": true
                }
            }
        ]
    }
    ```

2. Run the build task.
3. Press `F8`.
4. VS Code seems to enter some infinite loop. The open editors view is flickering and the UI becomes unresponsive.

Originally reported as: https://github.com/Microsoft/vscode/issues/64346
Git repo: https://github.com/segevfiner/vscode-issue-64346

**Comment by ramya-rao-a** [comment]
@segevfiner Apologies for the late response. I am not able to replicate this issue. Do you still see this?
