### ISSUE TITLE
Call Stack shows only the top frame

### ISSUE THREAD

**Issue by vmatyusGitHub** [Microsoft/vscode-go#2187]
Steps to Reproduce:

1. Debug any Go file
2. When the debugger stops at a breakpoint the Call Stask shows only the top frame.

To create a sample I used a simple example from github: https://github.com/CloudMQTT/go-mqtt-example/blob/master/main.go
 I set a breakpoint in the connect() function to line 14 and I see this in the Call Stack:
![vscode_callstack](https://user-images.githubusercontent.com/26717393/49996661-e5773080-ff8f-11e8-9eaa-1e8458bc71c0.png)

I also collected debug trace:
[debug_trace.txt](https://github.com/Microsoft/vscode/files/2679504/debug_trace.txt)

How can I correct this behavior?
I want to see the whole Call Stack, not just the top of it.

**Comment by rosulucian** [comment]
+1

**Comment by rosulucian** [comment]
I installed a previous version (Go-0.7.0.vsix) and it works fine. i think Go-0.8.0.vsix broke the debugger.

**Comment by vmatyusGitHub** [comment]
I use indeed Go-0.8.0.vsix! I switched back to Go-0.7.0.vsix and now it works fine!

**Comment by ramya-rao-a** [comment]
Thanks for reporting everyone!

@segevfiner has submitted a PR for this issue which I just merged.

To get the fix, please use the [latest beta version of this extension](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)

**Comment by ramya-rao-a** [comment]
This fix is now out in the latest update (0.9.0) to the Go extension
