### ISSUE TITLE
Cannot debug programs which read from STDIN

### ISSUE THREAD

**Issue by joshpearce** [microsoft/vscode-go#219]
[EDIT] 
I think the Debugger Console cannot accept input, or in other words, work as an interactive console. Is that right?

Is there an alternative, like attaching to a process?
[/EDIT]

I tried to debug a little program I wrote a while back. I don't really know what I'm doing, but I did get the program to start, it just display the following error when trying to read from stdin. I typed "1" and pressed ENTER.

```
{
"version": "0.2.0",
"configurations": [
    {
        "name": "Launch",
        "type": "go",
        "request": "launch",
        "mode": "debug",
        "program": "${workspaceRoot}/start",
        "env": {},
        "args": []
    }
]
}
```

2016/03/03 16:31:44 debugger.go:61: launching process with args: [./debug]
2016/03/03 16:31:44 debugger.go:374: continuing

Run your crypto challenge code!
Enter a set #: 
1

TypeError: Cannot read property 'currentGoroutine' of null\n    at GoDebugSession.evaluateRequest (/Users/joshuapearce/.vscode/extensions/lukehoban.Go-0.6.29/out/src/debugAdapter/goDebug.js:497:45)\n    at GoDebugSession.DebugSession.dispatchRequest (/Users/joshuapearce/.vscode/extensions/lukehoban.Go-0.6.29/node_modules/vscode-debugadapter/lib/debugSession.js:347:22)\n    at GoDebugSession.ProtocolServer._dispatch (/Users/joshuapearce/.vscode/extensions/lukehoban.Go-0.6.29/node_modules/vscode-debugadapter/lib/protocol.js:162:22)\n    at GoDebugSession.ProtocolServer._handleData (/Users/joshuapearce/.vscode/extensions/lukehoban.Go-0.6.29/node_modules/vscode-debugadapter/lib/protocol.js:142:26)\n    at Socket.<anonymous> (/Users/joshuapearce/.vscode/extensions/lukehoban.Go-0.6.29/node_modules/vscode-debugadapter/lib/protocol.js:24:60)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Socket.Readable.push (_stream_readable.js:110:10)\n    at Pipe.onread (net.js:523:20)
1

**Comment by lukehoban** [comment]
Yes - the VS Code debugger console doesn't currently support piping any input through to `stdin`.

Sounds like we need to improve the error behaviour when debuggee's attempt to read from `stdin`.

We do intend to add support for `attach` debugging, so that you could run the binary outside of VS Code and then attach to from VS Code.  That should make this possible.

**Comment by egamma** [comment]
FYI, you can tell the Code debugger to use an external console in the launch config:
```json
    "externalConsole": true
```

**Comment by joshpearce** [comment]
You mean: [proj dir]/.vscode/launch.json ?
I get a validation warning: "Property externalConsole is not allowed" and it doesn't work.

**Comment by lukehoban** [comment]
Yeah, I think that setting only works for the Node debuggee right now, but we should be able to add support for it in the Go debuggee as well, which would be simpler than setting up attach debugging.

**Comment by egamma** [comment]
@lukehoban is correct, sorry. This needs to be implemented by the debug adapter and it is currently only supported for node debugging. 

There are other requests to make this support available // @weinand

**Comment by weinand** [comment]
@lukehoban here is the request: https://github.com/Microsoft/vscode-node-debug/issues/52

For now you could just copy https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/terminal.ts plus two scripts into your project.

**Comment by louy2** [comment]
@weinand 
Could you elaborate on

> For now you could just copy https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/terminal.ts plus two scripts into your project.

What "two scripts" do I need in addition to terminal.ts? And where in my project shall I copy them to?

**Comment by kisPocok** [comment]
Hi, I'm in the same shoes. The _terminal.ts_ is missing. Could you tell me where I can find it?
https://github.com/Microsoft/vscode-node-debug/tree/master/src/node

Thanks

**Comment by weinand** [comment]
@kisPocok the functionality previously available in terminal.ts has been moved to the VS Code core. A debug adapter can now just call `runInTerminalRequest` to launch the debug target in a configurable external terminal.

See how this is done for node-debug:
https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L875

**Comment by ramya-rao-a** [comment]
@roblourens Can we update the debug side of the extension to make use the updates that @weinand has listed above?

**Comment by mattetti** [comment]
I agree with @ramya-rao-a that would be really great, @roblourens can you help by any chance?

**Comment by cemsozgen** [comment]
Any updates on this?

**Comment by CreativeCactus** [comment]
@cemsozgen Try this in your launch.json:
`console - what kind of console to use, e.g. internalConsole, integratedTerminal, externalTerminal.`
https://code.visualstudio.com/Docs/editor/debugging

Sorry if this doesn't apply. I'm working in node.

**Comment by ramya-rao-a** [comment]
@CreativeCactus The Go extension does not support the `console` attribute at the moment. #843 is tracking this feature request.

cc @roblourens

**Comment by roblourens** [comment]
Is anyone debugging with stdin working while using Delve? Using delve in a terminal, it's not listening to the terminal's stdin because that's how I'm sending commands to Delve. If I start Delve in headless mode, the server doesn't use stdin/out. I might be wrong but I'm not sure this is actually possible right now.

**Comment by cheetahfm** [comment]
Can you say (approximately) when debugging with stdin will be available?

**Comment by ramya-rao-a** [comment]
@derekparker Can you help out @roblourens in his query? See https://github.com/Microsoft/vscode-go/issues/219#issuecomment-288225992

**Comment by DeadGame** [comment]
I have encountered this problem, when you can solve?

**Comment by DeadGame** [comment]
I have encountered this problem, when you can solve?@ramya-rao-a

**Comment by ramya-rao-a** [comment]
@DeadGame I am not working on this yet, you are welcome to give it a try

**Comment by DeadGame** [comment]
@ramya-rao-a thanks

**Comment by DeadGame** [comment]
@derekparker @roblourens What is the problem?Do you have a solution now?

**Comment by weinand** [comment]
@derekparker try to debug a Go program that reads from stdin with delve from the command line (not VS Code). If this works, it should be possible to fix the VS Code problem. If not, then I don't think that the problem can be fixed in VS Code.

**Comment by bikehike** [comment]
this would help with debugging online coding problems that use stdin for everything

**Comment by mbenkmann** [comment]
The Python support for VS Code at least on Linux seems to have a very simple implementation of this. When I launch a Python script with the launch config option  "console": "integratedTerminal" it actually runs the command to launch the program in the terminal. I can then simply switch to the terminal and interact as normal with the program. Would it not be possible to just do the exact same with with the delve call?

**Comment by bfhike** [comment]
This launch.json works for me where run.bat is a script that pipes an "input" file into node.js.  When I press F5 in vs code, it starts node and attaches to the process, and I am able to set breakpoints in app.js.  I believe the runtimeArgs are needed to attach to the process.

> "runtimeArgs": [
				"--debug-brk=5858 --nolazy"
			],

**run.bat:**
type input | node %*

**launch.json**

> {
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/app.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": "${workspaceRoot}/run.bat",
			"runtimeArgs": [
				"--debug-brk=5858 --nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"console": "integratedTerminal",
			"sourceMaps": false,
			"outFiles": []
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858
		}
	]
}

**Comment by lirao** [comment]
If anyone really need this, debugging with stdin is supported in console-only delve right now, you can upload to the latest delve master branch (or any version after May 2018). Here's how you do it: https://github.com/derekparker/delve/issues/1274#issuecomment-406969034

**Comment by bryanmacfarlane** [comment]
I was able to successfully debug stdin using [remote debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#remote-debugging) since it's that terminal I enter stdin (not the vscode window).

To make it easier, I [created an alias](https://github.com/bryanmacfarlane/dev-macos/blob/master/devenv.sh#L90) in my bash env.  

launch.json
```javascript
    "configurations": [      
        {
            "name": "Remote",
            "type": "go",
            "request": "launch",            
            "mode": "remote",
            "program": "${fileDirname}",
            "remotePath": "${fileDirname}",
            "port": 2345,
            "host": "127.0.0.1",            
            "env": {},
            "apiVersion": 1,
            "args": []
        }
]
```

**Comment by HowieLiuX** [comment]
using remote debug + vscode task:
task.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "cd ${fileDirname} && dlv debug --headless --listen=:2345 --log --api-version=2",
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

lanuch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Connect to server",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "remotePath": "${fileDirname}",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }
    ]
}

```

Run the task using shortcut key(shift + cmd + B in Mac OS),  vscode will start a new shell and run the delve server.
Pressing F5 to debug the .go file. It works fine for me.

**Comment by najunuoyan** [comment]
any update on this, it should be a basic feature.

**Comment by ramya-rao-a** [comment]
Since based not the current state of delve, this feature is not doable, I am closing this issue as there is no action item at present

If anything changes in the future that will make this feature a possibility, a new feature request can be created.
