### ISSUE TITLE
Failed to continue - no G executing on thread

### ISSUE THREAD

**Issue by b00f** [microsoft/vscode-go#2192]
When I start debugging methods which is linking to external library I got this error:
```
Failed to continue - no G executing on thread xxx
```

I am able to debug it via `dlv test`. Please check the log [here](https://github.com/Microsoft/vscode-go/issues/2104#issuecomment-445853255)
I am using version 0.8.0.

**Comment by ramya-rao-a** [comment]
Adding details as was previously discussed in #2104. 

Debug configuration:
```
{
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/cmd/gallactic/main.go",
            "env": {"CGO_LDFLAGS":"${workspaceRoot}/../sputnikvm-ffi/c/libsputnikvm.a -ldl -lm"},
            "args": ["init", "-w=/tmp/chain2"],
            "showLog": false,
            "trace": "verbose"
        }
```

Link to project: https://github.com/gallactic/gallactic

**Comment by ramya-rao-a** [comment]
@b00f The debug configuration above is to debug the main program where as you mentioned using `dlv test`. Are you seeing the error when debugging the main program or the tests?

If it is for the tests, then can you share the debug configuration you are using to debug the test? Or are you using the codelens (the links above test functions in the editor for running and debugging tests) to debug the tests?

> I think it is related to CGO_LDFLAGS (When it's needed to link the app with an external library).
I did debug some test methods that doesn't link with my library and they work fine. Hopefully I could clear the air...

If I understood this correctly, the CGO_LDFLAGS  is required to link your app with the external library.

**Comment by ramya-rao-a** [comment]
cc @vscode-gophers

**Comment by b00f** [comment]
>  Are you seeing the error when debugging the main program or the tests?

Yes. I can see the same issue if I put a breakpoint in the code. Without any breakpoint it works.

**Comment by b00f** [comment]
Is there any update about this issue?

**Comment by ramya-rao-a** [comment]
No updates @b00f, I was out on vacation for 2 weeks, and am catching up on all notifications now.

There are few traces you can enable, that can help us to see which step in the debugging process is causing the problem.
Please add `"trace": "verbose"` which will add logs from the Go debug adapter and share the logs that get printed out to the debug console.

**Comment by b00f** [comment]
Here is the verbose log. Thanks
[vscode-go-debug.txt](https://github.com/Microsoft/vscode-go/files/2758238/vscode-go-debug.txt)

**Comment by b00f** [comment]
I found something. If I use the debug dll (not release) breakpoints hit and works fine!

**Comment by ramya-rao-a** [comment]
> If I use the debug dll (not release) breakpoints hit and works fine!

@b00f Can you elaborate on what you mean by "debug dll (not release)"?

cc @jhendrixMSFT

**Comment by b00f** [comment]
when the dll is build with debug flag in this case using rust-lang debug dll.

**Comment by b00f** [comment]
Do you need more information to fix this bug?

**Comment by R-Niagra** [comment]
Facing the same issue when I am trying to debug go test-file. It runs fine without breakpoint, however, the moment I add a breakpoint the very same error pops up:
Failed to continue - no G executing on thread 7140
Any way around?

**Comment by b00f** [comment]
Try to build the dll with debug information. It worked for me.

**Comment by yaephin** [comment]
@b00f May I ask how to  build dll with debug info,like what flags ? I'm new to rust-lang.Thanks.

**Comment by b00f** [comment]
> @b00f May I ask how to build dll with debug info,like what flags ? I'm new to rust-lang.Thanks.

`cargo build` without `--release` flag I think it is work fine here.

**Comment by yaephin** [comment]
Thanks for your reply . It's true that `cargo build` without `--release` contains debug infos with `gdb` confirming . But I got the issue again , when I check it again , may be it's because of linking with slib(_.a_) . I'll try linking with dlib(_.so_) or have to debug with cmdline.

**Comment by yaephin** [comment]
@b00f It works when linking with dlib_(.so)_ , thanks.

**Comment by ramya-rao-a** [comment]
Closing this issue as a work-around was found and there is no action item planned from the extension's perspective.
