### ISSUE TITLE
Fork of godef is no longer needed for Go modules support

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#2194]
Now that the godef fork https://github.com/ianthehat/godef has been merged back to the original repo, we no longer need to use it for Go modules support

- Remove `godef-gomod` from the list of tools to install/update in `goInstallTools.ts` file
- Add a notification to let the user know that they need to update their version of `godef` tool. This notification should be shown atmost once in a VS Code session.

**Comment by SylvainGarrigues** [comment]
Hey, godef-gomod doesn't work any longer in vscode with modules, but godef does.

Until https://github.com/Microsoft/vscode-go/blob/master/src/goDeclaration.ts#L83 is updated to remove reference to this tool, I found out that 

`# cd ${GOPATH}/bin && rm godef-gomod && ln -s godef godef-gomod`

Makes vscode usable again with Go modules and definitions :)

**Comment by Delphier** [comment]
VSCode: 1.30.1
Go Extension: 0.8.0
Go 1.11.4
Enabled go.mod

godef-gomod install failed:

```
# cd ........\src\github.com\ianthehat\godef; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package github.com/ianthehat/godef: exit status 128
```

rename godef.exe to godef-gomod.exe, works fine.

**Comment by oneslash** [comment]
@ramya-rao-a, I am almost done with PR, however, I am not sure how to display one time notifications.

**Comment by ramya-rao-a** [comment]
@oneslash Do you have a PR open?

**Comment by oneslash** [comment]
@ramya-rao-a here is it https://github.com/Microsoft/vscode-go/pull/2234

**Comment by ramya-rao-a** [comment]
I have merged your PR. I'll take care of the notification in another PR that I am currently reviewing
