### ISSUE TITLE
Shown call stack always of depth 1 with version 0.8.0

### ISSUE THREAD

**Issue by christian-fortini** [Microsoft/vscode-go#2196]
The call stack only shows the current frame when code is stopped at breakpoint. With version 0.7.0, you can see the whole stack (up to 20 I believe). With version 0.8.0, only one frame is shown. This is 100% repro as far as I can tell.

**Comment by hatricker** [comment]
I am seeing the same issue.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @christian-fortini and @hatricker 

@ToothlessGear Yes, you are right. We should have a default there. @segevfiner has submitted a PR for the same which I just merged.

To get the fix, please use the [latest beta version of this extension](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)

**Comment by christian-fortini** [comment]
Thanks for the quick turnaround on this!

Christian
