### ISSUE TITLE
"Find All References" shows no result but "Peek References" shows correct results.

### ISSUE THREAD

**Issue by krasoffski** [Microsoft/vscode-go#2197]
**Environment:**
 - OS: Xubuntu 18.04.1 LTS
 - vscode: 1.30.1, dea8705087adb1b5e5ae1d9123278e178656186a, x64

**Steps to Reproduce:**
1. Open big go project. 
2. Select function and use Right Mouse Click choose "Find All References" - NO RESULT
3. Select "Peek References" - all results provided.

**Addition info:**
After some amount time or after using "Peek References"  "Find All References" shows correct result but then might fail.

Trace logs does not show correct info about root cause, only error like: `ERR An unknown error occurred. Please consult the log for more details.` (I use -v with --debug=trace).
![image](https://user-images.githubusercontent.com/1073415/50206503-a88aaf80-037c-11e9-8817-b522806fdff9.png)
"Peek References" always works correctly but "Find All References" fails about 70% of cases.

This might be important, that adding following error too:
```
[Extension Host] Command failed: /opt/go/bin/go doc -c -cmd -u repo/module resolutionID
doc: no symbol resolutionID in package repo/module exit status 1
```

**Comment by saibing** [comment]
@krasoffski 

Microsoft/vscode#65127

**Comment by saibing** [comment]
@krasoffski 
It's may be a go language server's bug. [bingo](https://github.com/saibing/bingo) already fixed this bug.

you can try it.

**Comment by ramya-rao-a** [comment]
I was not aware of any upstream fixes here, but if you don't see this problem anymore, I'll go ahead and close this issue

**Comment by firstnoises** [comment]
I am still seeing this issue with VS Code 1.33.1 and vscode.go 0.10.2. 
@krasoffski what is the combination of builds resolved the issue?
