### ISSUE TITLE
running the debugger against test suite

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#22]
This might be a feature request but I didn't figure out how to change the launch.json config to start dlv test and debug my test suite instead of my actual code. This is very useful when writing Go libs.

**Comment by lukehoban** [comment]
Yeah - this is not yet implemented.  Something that should be added.

**Comment by gmlexx** [comment]
+1

**Comment by lukehoban** [comment]
This should be fixed with 1dda079.  Could you upgrade to `0.6.10` and validate whether you are still seeing this issue?

**Comment by lukehoban** [comment]
Note - The README also now contains some text on how to configure debugging tests instead of normal builds.

**Comment by mattetti** [comment]
Just in case someone finds this old issue, it is indeed fixed and it works great.
