### ISSUE TITLE
Multi-file find and replace spawns multiple processes per file

### ISSUE THREAD

**Issue by wbrefvem** [Microsoft/vscode-go#2202]
Steps to Reproduce:

1. Search workspace for a common string.
2. Replace it with any other string.

Results:
1. System resource usage should spike
2. Process table should reveal a large number of go-related processes (gofmt, golint, goreturns, etc).
3. Processes do not appear to be children of any VS Code process, so they persist even after exiting VS Code.

**Comment by ramya-rao-a** [comment]
> Search workspace for a common string.

The built-in search feature (either in the file or the workspace) is text based search implemented by VS Code itself and is not related to the Go extension.

Are you using these built-in search features or are you referring to the commands like `Go to symbol in file` or `Go to symbol in Workspace`

**Comment by ramya-rao-a** [comment]
This can be fixed by ensuring that we only run the build/lint/vet/format actions on an active document instead of each of the saved document.

I have pushed a commit for the same, thanks for reporting!

**Comment by ramya-rao-a** [comment]
The fix for this is now out in the latest update (0.9.0) to the Go extension
