### ISSUE TITLE
Debugger output and application stdout have to be splitted

### ISSUE THREAD

**Issue by Ri0n** [microsoft/vscode-go#2204]
vscode: 1.30.1
go ext: 0.8.0
go: 1.10.4
dlv: 1.0.0

Debug console is flooded with "Eval error: could not find symbol value for"

In valid scope it's resovled properly. but as soon as I start jumping between functions in step-by-step debugging it floods debug console with this making app's stdout almost unreadable.

I think there have to be two terminals. One for application output and another one for debugger output. And in fact vscode has both. But for some reason all the output from debugger itself and from the debugged application comes to "DEBUG CONSOLE".

**Comment by segevfiner** [comment]
That's how a debug adapter works by default in VS Code. But a debug adapter can implement [Debug Adapter Specification - RunInTerminal](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_RunInTerminal) and support a `console` debug configuration property allowing to select between running in `internalConsole`, `integratedTerminal` or `externalTerminal`.

Also see [VS Code Documentation - Debugging - launch.json attributes](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes).

vscode-go currently does not support that.

**Comment by Ri0n** [comment]
Thanks for the info. If ever start working on improving vscode-go I'll try to fix it and provide a PR. 
But if guess it won't happen any soon. Thanks anyway.

**Comment by ramya-rao-a** [comment]
#186 and #289 are tracking the requests to support `console` in debug configuration.
Closing this issue in favor of those issues
