### ISSUE TITLE
Running Install/Update Tools failed with `mkdir: operation not permitted`

### ISSUE THREAD

**Issue by egonelbre** [Microsoft/vscode-go#2211]
Opened Visual Studio Code and tried to update all tools. It failed with mkdir operation not permitted.

It seems it's trying to `mkdir` my home directory for some reason.

```
17 tools failed to install.

gocode:
Error: Command failed: /usr/local/bin/go get -u -v github.com/mdempsky/gocode
github.com/mdempsky/gocode (download)
package github.com/mdempsky/gocode: mkdir /home/egon: operation not supported
github.com/mdempsky/gocode (download)
package github.com/mdempsky/gocode: mkdir /home/egon: operation not supported
...
```

<details><summary>Full error log</summary>
Installing 17 tools at /home/egon/go/bin
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  dlv
  gocode-gomod
  godef
  godef-gomod
  goimports
  golint
  gotests
  gomodifytags
  impl
  fillstruct
  goplay

Installing github.com/mdempsky/gocode FAILED
Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/derekparker/delve/cmd/dlv FAILED
Installing github.com/stamblerre/gocode FAILED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/ianthehat/godef FAILED
Installing golang.org/x/tools/cmd/goimports FAILED
Installing golang.org/x/lint/golint FAILED
Installing github.com/cweill/gotests/... FAILED
Installing github.com/fatih/gomodifytags FAILED
Installing github.com/josharian/impl FAILED
Installing github.com/davidrjenni/reftools/cmd/fillstruct FAILED
Installing github.com/haya14busa/goplay/cmd/goplay FAILED

17 tools failed to install.

gocode:
Error: Command failed: /usr/local/bin/go get -u -v github.com/mdempsky/gocode
github.com/mdempsky/gocode (download)
package github.com/mdempsky/gocode: mkdir /home/egon: operation not supported
github.com/mdempsky/gocode (download)
package github.com/mdempsky/gocode: mkdir /home/egon: operation not supported

gopkgs:
Error: Command failed: /usr/local/bin/go get -u -v github.com/uudashr/gopkgs/cmd/gopkgs
github.com/uudashr/gopkgs (download)
package github.com/uudashr/gopkgs/cmd/gopkgs: mkdir /home/egon: operation not supported
github.com/uudashr/gopkgs (download)
package github.com/uudashr/gopkgs/cmd/gopkgs: mkdir /home/egon: operation not supported

go-outline:
Error: Command failed: /usr/local/bin/go get -u -v github.com/ramya-rao-a/go-outline
github.com/ramya-rao-a/go-outline (download)
package github.com/ramya-rao-a/go-outline: mkdir /home/egon: operation not supported
github.com/ramya-rao-a/go-outline (download)
package github.com/ramya-rao-a/go-outline: mkdir /home/egon: operation not supported

go-symbols:
Error: Command failed: /usr/local/bin/go get -u -v github.com/acroca/go-symbols
github.com/acroca/go-symbols (download)
package github.com/acroca/go-symbols: mkdir /home/egon: operation not supported
github.com/acroca/go-symbols (download)
package github.com/acroca/go-symbols: mkdir /home/egon: operation not supported

guru:
Error: Command failed: /usr/local/bin/go get -u -v golang.org/x/tools/cmd/guru
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/guru?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/guru": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/guru?go-get=1
get "golang.org/x/tools/cmd/guru": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/cmd/guru: mkdir /home/egon: operation not supported
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/guru?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/guru": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/guru?go-get=1
get "golang.org/x/tools/cmd/guru": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/cmd/guru: mkdir /home/egon: operation not supported

gorename:
Error: Command failed: /usr/local/bin/go get -u -v golang.org/x/tools/cmd/gorename
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/gorename?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/gorename": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/gorename?go-get=1
get "golang.org/x/tools/cmd/gorename": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/cmd/gorename: mkdir /home/egon: operation not supported
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/gorename?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/gorename": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/gorename?go-get=1
get "golang.org/x/tools/cmd/gorename": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/cmd/gorename: mkdir /home/egon: operation not supported

dlv:
Error: Command failed: /usr/local/bin/go get -u -v github.com/derekparker/delve/cmd/dlv
github.com/derekparker/delve (download)
package github.com/derekparker/delve/cmd/dlv: mkdir /home/egon: operation not supported
github.com/derekparker/delve (download)
package github.com/derekparker/delve/cmd/dlv: mkdir /home/egon: operation not supported

gocode-gomod:
Error: Command failed: /usr/local/bin/go get -u -v -d github.com/stamblerre/gocode
github.com/stamblerre/gocode (download)
package github.com/stamblerre/gocode: mkdir /home/egon: operation not supported
github.com/stamblerre/gocode (download)
package github.com/stamblerre/gocode: mkdir /home/egon: operation not supported

godef:
Error: Command failed: /usr/local/bin/go get -u -v github.com/rogpeppe/godef
github.com/rogpeppe/godef (download)
package github.com/rogpeppe/godef: mkdir /home/egon: operation not supported
github.com/rogpeppe/godef (download)
package github.com/rogpeppe/godef: mkdir /home/egon: operation not supported

godef-gomod:
Error: Command failed: /usr/local/bin/go get -u -v -d github.com/ianthehat/godef
github.com/ianthehat/godef (download)
package github.com/ianthehat/godef: mkdir /home/egon: operation not supported
github.com/ianthehat/godef (download)
package github.com/ianthehat/godef: mkdir /home/egon: operation not supported

goimports:
Error: Command failed: /usr/local/bin/go get -u -v golang.org/x/tools/cmd/goimports
Fetching https://golang.org/x/tools/cmd/goimports?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/goimports?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/goimports": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/goimports?go-get=1
get "golang.org/x/tools/cmd/goimports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/cmd/goimports: mkdir /home/egon: operation not supported
Fetching https://golang.org/x/tools/cmd/goimports?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/goimports?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/goimports": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/goimports?go-get=1
get "golang.org/x/tools/cmd/goimports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/cmd/goimports: mkdir /home/egon: operation not supported

golint:
Error: Command failed: /usr/local/bin/go get -u -v golang.org/x/lint/golint
Fetching https://golang.org/x/lint/golint?go-get=1
Parsing meta tags from https://golang.org/x/lint/golint?go-get=1 (status code 200)
get "golang.org/x/lint/golint": found meta tag get.metaImport{Prefix:"golang.org/x/lint", VCS:"git", RepoRoot:"https://go.googlesource.com/lint"} at https://golang.org/x/lint/golint?go-get=1
get "golang.org/x/lint/golint": verifying non-authoritative meta tag
Fetching https://golang.org/x/lint?go-get=1
Parsing meta tags from https://golang.org/x/lint?go-get=1 (status code 200)
golang.org/x/lint (download)
package golang.org/x/lint/golint: mkdir /home/egon: operation not supported
Fetching https://golang.org/x/lint/golint?go-get=1
Parsing meta tags from https://golang.org/x/lint/golint?go-get=1 (status code 200)
get "golang.org/x/lint/golint": found meta tag get.metaImport{Prefix:"golang.org/x/lint", VCS:"git", RepoRoot:"https://go.googlesource.com/lint"} at https://golang.org/x/lint/golint?go-get=1
get "golang.org/x/lint/golint": verifying non-authoritative meta tag
Fetching https://golang.org/x/lint?go-get=1
Parsing meta tags from https://golang.org/x/lint?go-get=1 (status code 200)
golang.org/x/lint (download)
package golang.org/x/lint/golint: mkdir /home/egon: operation not supported

gotests:
Error: Command failed: /usr/local/bin/go get -u -v github.com/cweill/gotests/...
github.com/cweill/gotests (download)
package github.com/cweill/gotests/...: mkdir /home/egon: operation not supported
github.com/cweill/gotests (download)
package github.com/cweill/gotests/...: mkdir /home/egon: operation not supported

gomodifytags:
Error: Command failed: /usr/local/bin/go get -u -v github.com/fatih/gomodifytags
github.com/fatih/gomodifytags (download)
package github.com/fatih/gomodifytags: mkdir /home/egon: operation not supported
github.com/fatih/gomodifytags (download)
package github.com/fatih/gomodifytags: mkdir /home/egon: operation not supported

impl:
Error: Command failed: /usr/local/bin/go get -u -v github.com/josharian/impl
github.com/josharian/impl (download)
package github.com/josharian/impl: mkdir /home/egon: operation not supported
github.com/josharian/impl (download)
package github.com/josharian/impl: mkdir /home/egon: operation not supported

fillstruct:
Error: Command failed: /usr/local/bin/go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct
github.com/davidrjenni/reftools (download)
package github.com/davidrjenni/reftools/cmd/fillstruct: mkdir /home/egon: operation not supported
github.com/davidrjenni/reftools (download)
package github.com/davidrjenni/reftools/cmd/fillstruct: mkdir /home/egon: operation not supported

goplay:
Error: Command failed: /usr/local/bin/go get -u -v github.com/haya14busa/goplay/cmd/goplay
github.com/haya14busa/goplay (download)
package github.com/haya14busa/goplay/cmd/goplay: mkdir /home/egon: operation not supported
github.com/haya14busa/goplay (download)
package github.com/haya14busa/goplay/cmd/goplay: mkdir /home/egon: operation not supported
</summary>

**Comment by egonelbre** [comment]
Running from command line does work.

Running the update without any file or project open. And I haven't set explicitly `GO111MODULE=`.

For settings.json, I have these:

```
    "go.formatTool": "goimports",
    
    "go.lintOnSave": "package",
    "go.lintTool": "golint",
    
    "go.gopath": "/home/egon/go",
    "go.toolsGopath": "/home/egon/go",

    "go.buildOnSave": "off",
    "go.installDependenciesWhenBuilding": false,
```

**Comment by egonelbre** [comment]
Ah, wait, just realized what was happening. The `go.gopath` needed to be:

```
    "go.gopath": "/Users/egon/go",
    "go.toolsGopath": "/Users/egon/go",
```

Not sure whether it's useful to notify user about the wrong gopath. Anyways at least there's now an issue that people can find for the issue. Feel free to close as you see fit.

**Comment by ramya-rao-a** [comment]
> Not sure whether it's useful to notify user about the wrong gopath.

The problem is that there is no way for the extension to know that given path is a "wrong" gopath


>  "go.gopath": "/Users/egon/go",
    "go.toolsGopath": "/Users/egon/go"

A side note: You don't need to specify `go.toolsGopath` if it is the same as `go.gopath`

Also, looks like you are using the default GOPATH in which case, you don't need to add the `go.gopath` setting either.

**Comment by egonelbre** [comment]
> A side note: You don't need to specify go.toolsGopath if it is the same as go.gopath.

Yeah, I know. I occasionally have them `go.gopath` different in workspaces but still want the tools still to be in the default location. The `go.gopath` is redundant, but I like to be explicit to keep some clarity in settings file.
