### ISSUE TITLE
Feature Proposal: Add command to add Environment Vars for Tests

### ISSUE THREAD

**Issue by rhnvrm** [Microsoft/vscode-go#2214]
Hello,

I wanted to run go tests with environment vars although it was not immediately possible to reach this feature through skimming through the README. I searched through and landed on #475  and recently discovered that we can set env vars for go tests through vs code like this:

```
    "go.testEnvVars": {
        "AWS_S3_BUCKET":"",
        "AWS_S3_ACCESS_KEY":"",
        "AWS_S3_SECRET_KEY":"",
        "AWS_S3_REGION":""
    }
```

It would be great to have a prompt (Go: Add Environment Var for Tests) added as a subscription in goMain.ts and an exported function in goTest.ts that can add these.

I would be happy to add support for this if you think it would be useful.

Regards

**Comment by nezorflame** [comment]
You could just open the Go extension page on the `Contributions` page and find it there, though:
![image](https://user-images.githubusercontent.com/3906766/50472349-7d7e0c80-09c9-11e9-8c34-1c64efdbcfa9.png)

**Comment by ramya-rao-a** [comment]
@rhnvrm Thanks for reporting.

We don't have the precedent of having a command to edit a setting. Users are expected to edit the settings directly in the settings editor.

By having a command to add the env variables, I believe what you are trying to solve is the discoverability of the `go.testEnvVars` setting. In which case, what @nezorflame suggests is one of the right things to do. Another is to use the settings editor (Use Ctrl+, or Cmd+, keyboard shortcut or use the corresponding command). Here you can either search for keywords or click on "Go" under "Extensions" to see all the settings contributed by the Go extension.

Is there any other concern that you hope to solve by having a command that edits a setting?

**Comment by rhnvrm** [comment]
@ramya-rao-a @nezorflame - Thanks for clarifying, I guess the change is not required.
