### ISSUE TITLE
Changing debug value fails in simple scenario

### ISSUE THREAD

**Issue by Sharpiro** [Microsoft/vscode-go#2219]
environments tested:
* Win 10
* Debian

versions:
* vscode 1.30.1
* vscode-go 0.8.0
* go 1.11.4
* dlv 1.1.0 - build: 1990ba12450cab9425a2ae62e6ab988725023d5c

steps to Reproduce:
1. setup sample code from below
2. set a breakpoint on line 6: ```x++```
3. debug to line 6
4. in the debug sidebar, change the value of ```x``` to 99
5. hit F10 to step over line 6
6. see that x is now incorrectly the value ```13``` instead of ```100```
7. uncomment line 5 and repeat the above steps to see that ```x``` is now set to ```100```

sample Code:
```
package main

func main() {
	x := 12
	// println("here's the fix...")
	x++
	println(x)
}
```

**Comment by ramya-rao-a** [comment]
@Sharpiro Thanks for reporting, I see this when using `dlv` from the terminal directly as well.

**Comment by ramya-rao-a** [comment]
Thanks @aarzilli 

@Sharpiro Based on the information @aarzilli has shared, please log an issue using the go issue tracker.
