### ISSUE TITLE
go to definition delay && doesn't work on some third-party packages

### ISSUE THREAD

**Issue by sunliver** [microsoft/vscode-go#2222]
#### Example code and some tests:
https://github.com/sunliver/mod-test

After tested some third-party packages, I've found some third-party packages fail to `go to definition`(github.com/spf13/cobra), and some work very slow (github.com/spf13/viper). Results can be seen in my repo.

As the readme says, 
1. when you are outside the mod directory (for example, workspace dir), `godef` will fail on some cases
2. `godef` works much slower than expected

#### Reason:
Current vscode-go extension misused the new `godef`, now always run `godef` on workspace dir.
Because new `godef` relays on [packages](https://godoc.org/golang.org/x/tools/go/packages) to find definitions.
A quick example for verifying this => [gopackages](https://github.com/golang/tools/blob/master/go/packages/gopackages/main.go)

So the new godef working with `go mod`, it should run inside the mod project, otherwise it will fallback to the old version.

```
├── gomod-test   => workspace dir
│   └── mod-test    => mod root
│       ├── Readme.md
│       ├── go.mod
│       ├── go.sum
│       ├── mod-test.go
│       └── modinner
```

#### How to fix
I've fixed this on this [PR](https://github.com/Microsoft/vscode-go/pull/2216), or may other ways.

**Comment by mhr3** [comment]
Looks like this is related to #2180 and #2194

**Comment by ramya-rao-a** [comment]
@sunliver Can you try the latest [beta version](
https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension?

**Comment by sunliver** [comment]
@ramya-rao-a 
Thank you! It works now.
