### ISSUE TITLE
Comment colorization regression inside var block

### ISSUE THREAD

**Issue by mafredri** [Microsoft/vscode-go#223]
Hi, I just noticed that there was a regression in colorization of comments due to https://github.com/Microsoft/vscode-go/commit/62b294ba1d3ffd6e53c0514a0893b61dc0a22423. Comments inside `var (...)` declarations aren't detected any more, example:

![](https://www.dropbox.com/s/ykr906qnlxamsgs/Screenshot%202016-03-04%2010.58.00.png?dl=1)

I guess this might actually be a vscode issue, but I thought I'd bring it up here first.

**Comment by lukehoban** [comment]
Thanks - I've opened a PR against the VS Code repo that should fix this.

**Comment by mafredri** [comment]
That was quick, thanks! :smile:
