### ISSUE TITLE
Megacheck has been deprecated. Please use staticcheck instead.

### ISSUE THREAD

**Issue by mrwonko** [Microsoft/vscode-go#2231]
With `go.lintTool` set to `megacheck` (for performance reasons) the Go output upon running the linter shows:

> Error while running tool: /Users/willi/code/go/bin/megacheck
> Megacheck has been deprecated. Please use staticcheck instead.

Can you please add support for staticcheck?

**Comment by oneslash** [comment]
@mrwonko here is the PR https://github.com/Microsoft/vscode-go/pull/2232

cc: @ramya-rao-a

**Comment by mrwonko** [comment]
Awesome! Happy to see it required so few changes.
