### ISSUE TITLE
"Find All References" does not find code in other packages outside GOPATH

### ISSUE THREAD

**Issue by martinrode** [microsoft/vscode-go#2236]
This all is on:

* Mac OS 10.14.2
* Vscode Version 1.30.2 (1.30.2)
* Vscode Go 0.8.0
* go1.11.4 darwin/amd64.
* Fresh Gotools update / install (all SUCCEED)

**The problem described here is a bug while calling "guru" to "Find All References" in a project outside GOPATH (with go.mod, go.sum), the same works fine for .go files inside the GOPATH!**

With right click -> Find All References on a certain line in Vscode I see in the Output Log (Extension Host):

```
[2019-01-09 22:35:22.668] [exthost] [error] Error running guru: Command failed: /Users/martin/go/bin/guru -modified referrers /Users/martin/work/commands/server/api/mask.go:#557
guru: no object for identifier: *ast.SelectorExpr
```

From Terminal (inside Vscode) I see this:

```
$ /Users/martin/go/bin/guru referrers /Users/martin/work/commands/server/api/mask.go:#557
/Users/martin/work/commands/server/handler/util.go:11.6-11.10: references to func github.com/programmfabrik/commands/server/handler.Error(rw net/http.ResponseWriter, req *net/http.Request, status int, err error)
```

The output appears sane and parsable.

```
martin:~/work$ env | grep GO111
GO111MODULE=on
```

It is also set in my user settings:

```
"go.toolsEnvVars": {
        "GO111MODULE": "on"
    },
```

If I overwrite GO111MODULE to **off** in Terminal (Vscode), I get the **same** error:

```
martin:~/work$ GO111MODULE=off /Users/martin/go/bin/guru referrers /Users/martin/work/commands/server/api/mask.go:#557
guru: no object for identifier: *ast.SelectorExpr
```

Any ideas what is going on here?

**Comment by bercab** [comment]
I have the same problem working with modules outside GOPATH.
It seems related to this issue:
https://github.com/golang/go/issues/24661

guru tool needs an update to support modules.

**Comment by ramya-rao-a** [comment]
@martinrode Thanks for reporting and apologies for the very late reply. 

From what you have shared it looks like the extension is not respecting the GO111MODULE setting. Can you try again with the latest version of the Go extension?

What @bercab is saying is right as well. `guru` doesn't support modules yet, so the results from it is not guaranteed to be accurate
