### ISSUE TITLE
No hover doc for modules

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-go#2244]
Steps to reproduce:
1. Create any go module. (`go mod init`).
2. Try to hover over some symbol in it that has docs.

`go doc` will fail due to setting `GOPATH` by the extension to a path containing the module, which causes it to operate in `GOPATH` mode. We shouldn't set that when we are in a module so that it will operate module-aware mode.

**Comment by ramya-rao-a** [comment]
Does `go doc` work as expected when in module mode? Have you tried `go doc` in a terminal directly?

**Comment by segevfiner** [comment]
Yes. It does and I did.

Check out the docs for `GO111MODULE=auto` to understand why setting `GOPATH` that way causes this to fail.

**Comment by ramya-rao-a** [comment]
@segevfiner Is this for symbols from the same package or external?

If it is for the same package, then I believe the issue was using the right working directory when running `go doc`. I have the fix for that in https://github.com/Microsoft/vscode-go/pull/2262

**Comment by hotinherre** [comment]
Hi, I have the same issue.

No hover/code-navigation on external or standard library in go module.
Go doc works fine in terminal.

**Comment by ramya-rao-a** [comment]
Thanks @hotinherre 

I have pushed another commit to #2262 and this should take care of symbols from external packages as well.

**Comment by hotinherre** [comment]
Thanks for quick response. When will this patch release to stable version we can use?

**Comment by ramya-rao-a** [comment]
@hotinherre Can you try the latest beta version? I have updated it just now with the fixes from #2262

**Comment by ramya-rao-a** [comment]
Thanks @hotinherre 

@segevfiner Can you try the latest beta version as well?

**Comment by ramya-rao-a** [comment]
@segevfiner Closing this issue as I believe it has been resolved and I don't see the problem anymore.
Please log a new issue if you still see this

**Comment by segevfiner** [comment]
It's probably resolved by `gopls` (Didn't check), not sure if it's resolved without it, but even if it is, should I even bother checking? I don't think using modules without `gopls` is recommended or expected to work well anymore.

**Comment by ramya-rao-a** [comment]
That is true @segevfiner 
In the tooling ecosystem, there is more focus on getting gopls to work with modules than putting the same effort in individual tooling
