### ISSUE TITLE
Uses all CPU spawning doc commands

### ISSUE THREAD

**Issue by tj** [Microsoft/vscode-go#2248]
Hello, I'd love to switch from Atom to VScode, but seemingly at random the autocomplete stops working, and my machine grinds to halt due to these commands:

![](https://user-images.githubusercontent.com/25254/50995630-87e6ed00-1517-11e9-9d10-2b369ece5ebe.png)

- Go go1.12beta1
- Mac 10.12.6
- VSCode: 1.30.2

Let me know if there's anything I can do to help debug that.

cheers

**Comment by OneOfOne** [comment]
Using [bingo](https://github.com/saibing/bingo/wiki/Install) langserver works better for most cases atm, at least for me, you might wanna try that.

Here are my settings for it:

```
"go.alternateTools": {
		"go-langserver": "bingo"
	},
	"go.useLanguageServer": true,
	"go.languageServerFlags": ["-format-style=goimports"],
	"go.languageServerExperimentalFeatures": {
		"format": true,
		"autoComplete": true,
		"rename": true,
		"goToDefinition": true,
		"hover": true,
		"signatureHelp": true,
		"goToTypeDefinition": true,
		"goToImplementation": true,
		"documentSymbols": true,
		"workspaceSymbols": true,
		"findReferences": true
	},
```

**Comment by tj** [comment]
nice thanks! I'll try it out, sounds like the issue should be opened on go-langserver

**Comment by tj** [comment]
going to reopen, I'm a little confused about which repo is responsible for doing the `go doc` calls, but this happens every few minutes

**Comment by tj** [comment]
dup of #2276
