### ISSUE TITLE
Multiple configurations

### ISSUE THREAD

**Issue by gdamore** [Microsoft/vscode-go#2250]
We have a product build where we have to support multiple different targets, and we use build tags to select differences, as well as different environment variables passed to CGO, etc.

It would be super nice if this extension offered the ability to use multiple different configurations, like the C/C++ side does, so that I can select which configuration (e.g. native, Windows x64, Linux, etc.) and have those settings take effect.  Ideally these configurations would be stored just like the C/C++ extension does, as a JSON dictionary.  Then button in the bottom of the editor could be used to select which configuration I'm using.

Ideally pretty much any of the settings could be overridden in a configuration, so that for example I could set up remote debugging for a configuration, but have local debugging for a different configuration.

**Comment by ramya-rao-a** [comment]
@gdamore When you say "configuration"/"setting", are you referring to just the debug configurations or settings in general?

**Comment by gdamore** [comment]
Well, for me, I need to be able to set a variety of settings... the GOPATH, GOROOT, CGO_ENABLED, CC, the system root path (where include files are found etc.)

Basically, this is everything to switch to a target for cross compilation.

**Comment by ramya-rao-a** [comment]
This seems like an extension agnostic feature request, doesnt it?

In which case, it makes better sense for VS Code to provide this feature so that users can switch in/out the configurations they want (for the same project), based on the scenario.

Please log this as a feature request in the VS Code repo at https://github.com/Microsoft/vscode
