### ISSUE TITLE
[ms-vscode.Go] Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by vladyslav2** [Microsoft/vscode-go#2252]
After I updated golang,  go-extension completely stop working

OS: Mac Os 10.12.6 (16G29)
Golang: version go1.11.4 darwin/amd64
vscode: 1.30.2
61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
x64

Process list:
![2019-01-15 12 00 24](https://user-images.githubusercontent.com/704096/51206559-2e871100-18bd-11e9-88ee-28712de9ef86.png)

Vscode errors:
![2019-01-15 12 01 00](https://user-images.githubusercontent.com/704096/51206585-3e9ef080-18bd-11e9-9dce-b21b9e0ce5d3.png)

Tried to install golang from different sources (website, brew and etc), the same problem
Tried to purge vscode and install everything from scratch including configs - did not worked 

looks like go-langserver does not respond on the commands

I guess the problem that go-langserver is not updating anymore and there is a new project https://github.com/saibing/bingo which, I guess, vscode need to use instead of langserver

**Comment by vladyslav2** [comment]
Killing go-langserver and manually running bingo seems helped 
will report after using it for a few days

**Comment by vladyslav2** [comment]
After playing with it for a while I found one strange pattern:
- Go to Defenition
- Go to Type Definition
- Find All Reference 
- etc

will work only for the first time when you install go-langserver
if you will close and reopen visual code you will be missing that functions

It does not depend on the golang version, I got the same problem with 1.10 and 1.11

**Comment by vladyslav2** [comment]
Hopefully, my monolog will help somebody.
Manage to make it work without removing GOPATH.

1. Do not use go mod, stay with vgo or anything but without go mod
2. Make sure to purge go-langserver completly 
3. Run gocode manually before you open vscode 

I tried to play with bingo but problem that I don't know how to get error logs so if something not working I cannot dig deeper and understand why. Would be nice to have some simple examples how to use bingo ....

**Comment by saibing** [comment]
@vladyslav2 

[How to use bingo with vscode-go](https://github.com/saibing/bingo/wiki/Language-Client)

How to get error logs ?

you can add "--trace", "--logfile=/tmp/bingo.log" to bingo,

**Comment by ramya-rao-a** [comment]
Thanks for reporting @vladyslav2 

This is due to an upstream issue with the Go language server. See #356

If you want to continue to use the Go language server from Sourcegraph, then I would suggest the below workaround
- Open the code for the language server in VS Code. This would be in your `$GOPATH/src/github.com/sourcegraph/go-langserver`
- Undo the commits in the master branch until you reach https://github.com/sourcegraph/go-langserver/commit/bc3adb4a5b1092cd713b279a11217e2e54243c58
- Run the command `Go: Install Current Package`

**Comment by vladyslav2** [comment]
@ramya-rao-a I would say the problem is not that I still want to use go-language server.
The Problem that visual studio offers me to install it everytime I open golang file and it seems awkward when I install tool from recommendation tooltip and everything stop working

**Comment by ramya-rao-a** [comment]
@vladyslav2 There is a difference between the [Go language server](https://github.com/sourcegraph/go-langserver) which has the bug and the [VS Code Go extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go) which Visual Studio Code recommends you to install.

To understand how the Go extension uses the Go language server, please see https://github.com/Microsoft/vscode-go#go-language-server-experimental

You can use the VS Code Go extension, but not use the language server by editing the setting `go.useLanguageServer`

**Comment by vladyslav2** [comment]
@chrismwendt Chris, just to confirm go-langserver working fine right now
thank you
