### ISSUE TITLE
switch the default language server to bingo or golsp

### ISSUE THREAD

**Issue by OneOfOne** [microsoft/vscode-go#2253]
From https://github.com/sourcegraph/go-langserver:

>  Note: We have deprioritized work on this language server for use in editors in favor of Google's upcoming Go language server. It is in the best interests of the community to only have a single language server. If you want to use a Go language server with your editor in the meantime, try https://github.com/saibing/bingo, which is a partial fork of this repository with fixes for Go modules and other editor bugs.

Bingo is actively maintained and the works the best out of the 3 available options that I personally tried, the 3rd being [golsp](https://github.com/golang/tools/tree/master/cmd/golsp) is getting there but it's still lacking behind partly because it's maintained in the official go tree and it takes longer time and reviews to improve it.

**Comment by OneOfOne** [comment]
@webframp  you can do that already:

```
	"go.useLanguageServer": true,
	"go.alternateTools": {
		"go-langserver": "bingo"
	},
	"go.languageServerFlags": ["-format-style=goimports"],
```

But making it the default would provide a better experience to new comers.

**Comment by inliquid** [comment]
+1 for bingo as default language server
For configuration with VS Code I suggest following [this page](https://github.com/saibing/bingo/wiki/Language-Client):
```json
    "go.useLanguageServer": true,

    "go.alternateTools": {
        "go-langserver": "bingo"
    },

    "go.languageServerFlags": ["--format-style", "goimports"],

    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    }
```

**Comment by webframp** [comment]
Great info thanks @inliquid and @OneOfOne

**Comment by OneOfOne** [comment]
They added support for [autocomplete unimported packages](https://github.com/saibing/bingo/commit/2ab1ae17c8807830786fde9b661ee54b7205727b), woohoo.

**Comment by lggomezml** [comment]
After a couple of days of using it at work I can't say I feel inclined to use bingo as the default. It is way more responsive than the sourcegraph server but it also has some annoying bugs that result in false errors like this one: 

![screen shot 2019-02-08 at 14 50 15](https://user-images.githubusercontent.com/29546751/52496319-c7a20280-2bb1-11e9-85ec-57c373e7d1c0.png)

Is golsp (now renamed to gopls) still isn't ready, but it can be tested via a local extension setup: https://github.com/golang/tools/tree/master/cmd/gopls/integration/vscode

**Comment by inliquid** [comment]
@lggomezml if you see some bug, please report it at bingo's repo. It's under active development, and  maintainer is also very active, closing all major issues literally in hours. Not sure what you mean btw, I have not seen any big problems with it so far, and it's the only language server that works normally with `GO111MODULES=on`, finds interface implementations (and doesn't spend hours on this) and the only server that works on Windows.

**Comment by nezorflame** [comment]
+1 for `bingo` since `gopls` is still in its infancy.

**Comment by bcomnes** [comment]
> It seems that golsp (now renamed to gopls) still isn't ready, but it can be tested via a local extension setup: https://github.com/golang/tools/tree/master/cmd/gopls/integration/vscode

Frustrating I have to float a development package to test that out.  They should make it work like bingo!

**Comment by broady** [comment]
@bcomnes I got that working, per docs on the wiki: https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code#can-i-use-the-language-server-when-using-go-modules

```
  "go.alternateTools": {
    "go-langserver": "gopls", // or bingo
  },
  "go.languageServerExperimentalFeatures": {
    "format": true,
    "autoComplete": true
  },
  "go.useLanguageServer": true
```
and it works really well.
though I lost syntax highlighting. any idea how to get that back?

**Comment by bcomnes** [comment]
Interesting, I'll try it out.

**Comment by tonywenoracle** [comment]
I tried bingo. It's awesome. It first loading is slower compare to sourcegraph/go-lanserver. But, when it's done, "Find All Reference" can be done in a flash. Amazing!

**Comment by broady** [comment]
Did you try comparing to gopls?

**Comment by nezorflame** [comment]
`gopls` is still in eary stages, `bingo` is more comlete and feature-rich right now.

**Comment by inliquid** [comment]
I tried. Configured as they recommend, compiled... On my Windows machine it simply didn't work. Runs, but nothing... Deleted. To the moment it will be at least functional, Bingo will do a lot more.

**Comment by tonywenoracle** [comment]
@broady Sorry, I haven't yet. I'll post the result when I try it.

**Comment by thegtproject** [comment]
@inliquid i had this issue on my Windows machine as well. I fixed it by deleting the bingo.exe binary from `%GOPATH%\bin\bingo.exe` and deleting `%GOPATH%\src\github.com\saibing\bingo`. Then, I updated everything with `go get -u -v github.com/saibing/bingo/...` using the 3 periods at the end to also make sure to get all dependencies updated as well. I had added the environment variable `GO111MODULE=on` but I'm not actually sure that was required. At this point I ran `go clean github.com/saibing/bingo` just for grins. Finally, `go install -i github.com/saibing/bingo`. After these steps, my vscode was working with bingo perfectly again! Note: when you do this, make sure bingo or vscode is not running. Good luck!

**Comment by inliquid** [comment]
@thegtproject I never had any problems with installing/running Bingo on Windows, my previous comment was regarding `gopls` (the "official" LSP server)

As for installing Bingo on Windows it's quite simple, and same as with other OSes, actually
1. `git clone https://github.com/saibing/bingo.git`
2. `cd bingo`
3. `go install`

**Comment by xlucas** [comment]
Is there a way to disable the language server warning from this extension? It's super annoying and in my experience gopls/bingo simply don't work as well right now with projects not using go modules. This would be better if we could turn that off until there's a more mature alternative.

**Comment by ramya-rao-a** [comment]
Closing this issue as `gopls` is now the default language server choice. One can still choose to use bingo in its place. Details are in the [language server section in the README](https://github.com/microsoft/vscode-go#go-language-server)

@xlucas AFAIK the warnings/notification for the language server does have the option of "Don't show again". If it doesn't show up or doesn't work, please log a new issue
