### ISSUE TITLE
Change Extension logo to the new Go logo

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode-go#2255]
Currently there will be this logo used for the extension store:
https://github.com/Microsoft/vscode-go/blob/master/images/goIcon.png

What about using the new Go logo from their styleguide?

Reference:
- https://blog.golang.org/go-brand
- https://golang.org/s/logos

Some idea:
![image](https://user-images.githubusercontent.com/17984549/51372204-b444cf80-1afc-11e9-859e-2e6ff22adbf1.png)

**Comment by ramya-rao-a** [comment]
I dont have an opinion here either way.

We can make the switch if there are enough upvotes to this issue.

**Comment by welkie** [comment]
Logo makes more sense to me than mascot for things like this.
