### ISSUE TITLE
vscode very very slow with go plugin

### ISSUE THREAD

**Issue by dreamer-nitj** [Microsoft/vscode-go#2256]
If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1. Installed latest vscode along with latest go plugin.
2. my settings file is as follows:

```
{
    "editor.fontSize": 18,
    "extensions.ignoreRecommendations": true,
    "window.zoomLevel": -1,
    "workbench.colorTheme": "Quiet Light",
    // "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.editor.enablePreview": false,
    // go related settings
    "go.autocompleteUnimportedPackages": true,
    "files.autoSave": "afterDelay", // for go tools to work correctly
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.formatTool": "goreturns",
    "go.testEnvVars": {
        "GOCACHE": "off"
    },
    // The number of spaces a tab is equal to. This setting is overriden
    // based on the file contents when `editor.detectIndentation` is true.
    "editor.tabSize": 4,
    // Insert spaces when pressing Tab. This setting is overriden
    // based on the file contents when `editor.detectIndentation` is true.
    "editor.insertSpaces": true,
    // When opening a file, `editor.tabSize` and `editor.insertSpaces`
    // will be detected based on the file contents. Set to false to keep
    // the values you've explicitly set, above.
    "editor.detectIndentation": false,
    "workbench.sideBar.location": "left",
    "json.schemas": [
        {
            "fileMatch": [
                "manifest.json"
            ],
            "url": "http://json.schemastore.org/chrome-manifest",
        }
    ],
    "go.addTags": {
        "tags": "json",
        "options": "json=omitempty",
        "promptForTags": true,
        "transform": "camelcase"
    },
}
```

I have been using visual studio code for over a year now with go plugin and recently it has become very very slow to navigate and scroll. I am using MacOS Mojave and go version reports this:

go version go1.11.4 darwin/amd64

My vscode version is 1.30.2 and go plugin version is 0.8.0 I have also updated all the go tools after i updated my go version. Is anyone else facing this issue?

This also makes my whole MacOS very slow. I also see heavy CPU usage and fan speed when i do editing constantly.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @dreamer-nitj 

Please follow the part about using the Process Explorer in VS Code in the wiki: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu 

This will help us narrow down what process exactly is causing the heavy CPU usage.

Other questions:
- Do you see the slowness even when working on small simple Go programs or only on large projects?
- Try turning off all the [on save features](https://github.com/Microsoft/vscode-go/wiki/On-Save-features) of this extension and see if that makes any difference.
- Are you using Go modules?

**Comment by dreamer-nitj** [comment]
Hi Ramya,

* Yes, slowness is there even for small go projects. I also saw that if i turn off go extension, then vscode becomes responsive and very fast.
* I am not using go modules.
* turning off all the  "on save features" seems to have made lot of difference in speed but i feel its not as fast as it used to be in past.

Also attaching the profile for extension host.
[CPU-20190121T041818.552Z.cpuprofile.txt](https://github.com/Microsoft/vscode-go/files/2777576/CPU-20190121T041818.552Z.cpuprofile.txt)

**Comment by Nerzal** [comment]
Hi, 
are you on Windows, Linux or Mac?

I only experience such a behavior on Windows. Never had the problem of VSCode being terribly slow on Linux.

**Comment by ramya-rao-a** [comment]
You seem to have auto-save enabled. So that will trigger the on save features much more frequently than if you were saving the files manually.

Try turning the on save features back on, but disable auto-save. How much of a difference does that make?

The part that is most helpful from https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu is what the Process Explorer shows.

So the next time you see high CPU usage, can you check the Process Explorer and share a screenshot of that?
