### ISSUE TITLE
Capitalize test command title in *_test.go

### ISSUE THREAD

**Issue by Delphier** [Microsoft/vscode-go#2257]
Can it be displayed like this：
run test  -> `Run Test`
debug test -> `Debug Test`
run package tests -> `Run Package Tests`
run file tests -> `Run File Tests`

![image](https://user-images.githubusercontent.com/6134731/51384478-6c9f6180-1b57-11e9-87d5-bbdb068009ed.png)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Delphier 

We did consider this when we added the links.
The reason we decided to go with all lower case was to make them look as small as possible, compared to the code around it i.e to not grab the user's attention away from the code.
