### ISSUE TITLE
Error message: builtin is out of GOPATH workspace

### ISSUE THREAD

**Issue by inliquid** [Microsoft/vscode-go#2259]
VS Code: 1.30.3
OS: Windows 10
vscode-go: 0.8.1-beta.5
GO111MODULE=on

When I try to open some particular project's folder I'm getting this error message:
```c:\Go\src\builtin is out of GOPATH workspace [C:\Users\*****\go], but not a go module project```
![1](https://user-images.githubusercontent.com/6797881/51414791-aaff4580-1b84-11e9-9786-5608f75ac7d6.png)
All IDE features such as definitions, go to *, etc, seems not working. Nothing in output console.

However, when I open subfolder, there is no error. See the pictures.

![2](https://user-images.githubusercontent.com/6797881/51414792-acc90900-1b84-11e9-9c9c-513dd92ca996.png)

**Comment by ramya-rao-a** [comment]
@inliquid Can you try our [latest beta version](url
https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of the extension that has a couple of bug fixes that haven't been released yet?

**Comment by inliquid** [comment]
@ramya-rao-a yep I don't see it anymore.
