### ISSUE TITLE
Not sure about goreturns: formatting whitespaces

### ISSUE THREAD

**Issue by flddr** [Microsoft/vscode-go#2267]
Hi,

thank you for this amazing extension.

I am not sure, i have issued https://github.com/sqs/goreturns/issues/58#issue-400707404

Please have a look if it's correct or should be issued elsewhere. I did not find another package as this and it states only

> A gofmt/goimports-like tool for Go programmers that fills in Go return statements with zero values to match the func return types

Thank you ☺️

**Comment by ramya-rao-a** [comment]
@flddr 

The Go extension uses just the formatting tool to do the formatting.
But you may have some other extension that might be interfering here as well.
To eliminate this possibility, please try disabling all extensions other than Go and try to see if you still get this error

**Comment by flddr** [comment]
@ramya-rao-a 

thank you - sorry for waiting

I have reduced to

![image](https://user-images.githubusercontent.com/42785945/51778318-59653680-2101-11e9-9658-f38f1fa0f4e9.png)

This does not change anything

**Comment by ramya-rao-a** [comment]
In that case, it must be a problem with goreturns

As a last attempt to be sure that this is indeed an issue with goreturns, can you try running `goreturns` from the terminal and see if you see the same issue?

**Comment by flddr** [comment]
Oh yes, i would like to try that in the evening, but didn't found anything else related to **goreturns** than

https://github.com/sqs/goreturns

Is this the extension used by _VS Code_? Actually i am not sure where to found some information

**Comment by flddr** [comment]
Sorry, i had less time these days

I tried `goreturns` and `gofmt` with those files from terminal/commandline (Windows 17763.292) and on ubuntu 18.04, but i got same output (_different whitespaces_, as seen on sqs/goreturns#58 (comment))

😕

**Comment by ramya-rao-a** [comment]
Thanks @flddr, then this indeed is an issue with `goreturns`. Closing this issue as there is nothing more we can do in the extension.

> Is this the tool used by VS Code? 

Yes, `goreturns` is the default formatting tool used by the Go extension. You can change this to either `goimports` or `gofmt` by changing the setting `go.formatTool`.
