### ISSUE TITLE
Binary file created by delve not deleted after stepping over the debug process

### ISSUE THREAD

**Issue by michaelweidmann** [Microsoft/vscode-go#2268]
EDIT: Here is a issue which seems to be the same but there is not much information given: #2265 

Hello together,

I migrated a few days ago my Go development setup from eclipse to VSCode because the eclipse plugin is no longer supported. And today I spotted a bug that the debug binary produced by delve (the golang debugger the Go extension uses) is not always deleted by the debugger. 

For these tests I used this example program with a breakpoint at the line `fmt.Println("Hello World")`: 

```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello World")
}
```
1. Case (success) - steps to reproduce
- Debug a Go Program
- Stop debugging (via `Stop` or Ctrl+F2)
--> The debug binary is deleted

Here is the end of the verbose logs:
```
DisconnectRequest
HaltRequest
time="2019-01-23T20:08:51+01:00" level=debug msg=halting layer=debugger
HaltResponse
DetachRequest
DisconnectRequest to parent
DisconnectResponse
Process exiting with code: 0
Sending TerminatedEvent as delve is closed
```
Old issue: #1345 

2. Case (failure) - steps to reproduce
- Debug a Go Program
- Continue debugging this application via `Continue` (F8) or `Step Over` (F6) until the end of the application
--> The debug binary is not deleted

Here is the end of the verbose logs:
```
DisconnectRequest
HaltRequest
time="2019-01-23T20:13:26+01:00" level=debug msg=halting layer=debugger
DisconnectRequest to parent
DisconnectResponse
```

Seems that there is not TerminatedEvent thrown and the HaltRequest does not get any response.
<hr>
Here is listed what I use:

- VSCode Version: 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
- OS: Windows 10 Enterprise 1703 (15063.483)
- Extensions I installed:
<table>
  <tr>
    <th>Extenstion</th>
    <th>Author</th>
    <th>Version</th>
  </tr>
  <tr>
    <td>Atom One Dark Theme</td>
    <td>Mahmoud Ali</td>
    <td>2.1.0</td>
  </tr>
  <tr>
    <td>Eclipse Keymap</td>
    <td>Alphabot Security</td>
    <td>0.10.0</td>
  </tr>
  <tr>
    <td>Go</td>
    <td>Microsoft</td>
    <td>0.8.0</td>
  </tr>
  <tr>
    <td>Material Icon Theme</td>
    <td>Philipp Kief</td>
    <td>3.6.2</td>
  </tr>
  <tr>
    <td>Shell launcher</td>
    <td>Daniel Imms</td>
    <td>0.3.0</td>
  </tr>
</table>

<hr>

Thanks in advance! 😊
Michael Weidmann

**Comment by ramya-rao-a** [comment]
@michaelweidmann Thanks for reporting and apologies for not responding sooner.

Can you try the latest version of the Go extension (0.9.2) and see if you still have the issue?
The latest version have some logging updates that can help she some more light on your case 2.

**Comment by michaelweidmann** [comment]
@ramya-rao-a Thanks for your response.

I updated the Go extension but the issue still persists. Here are the logs:

```
API server listening at: 127.0.0.1:11830
time="2019-03-12T13:48:05+01:00" level=info msg="launching process with args: [Y:\\SCM\\Go\\src\\test\\debug]" layer=debugger
time="2019-03-12T13:48:06+01:00" level=info msg="created breakpoint: &api.Breakpoint{ID:1, Name:\"\", Addr:0x4a81d4, File:\"Y:/SCM/Go/src/test/main.go\", Line:6, FunctionName:\"main.main\", Cond:\"\", Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(0xc000142db0), LoadLocals:(*api.LoadConfig)(0xc000142de0), HitCount:map[string]uint64{}, TotalHitCount:0x0}" layer=debugger
time="2019-03-12T13:48:06+01:00" level=debug msg=continuing layer=debugger
time="2019-03-12T13:48:17+01:00" level=debug msg=continuing layer=debugger
Hello World
time="2019-03-12T13:48:17+01:00" level=debug msg=halting layer=debugger
```
Tonight I will try to debug the extension and hopefully find something 😅

**Comment by michaelweidmann** [comment]
@ramya-rao-a Thanks for your response.

I updated the Go extension but the issue still persists. Here are the logs:

```
API server listening at: 127.0.0.1:11830
time="2019-03-12T13:48:05+01:00" level=info msg="launching process with args: [Y:\\SCM\\Go\\src\\test\\debug]" layer=debugger
time="2019-03-12T13:48:06+01:00" level=info msg="created breakpoint: &api.Breakpoint{ID:1, Name:\"\", Addr:0x4a81d4, File:\"Y:/SCM/Go/src/test/main.go\", Line:6, FunctionName:\"main.main\", Cond:\"\", Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(0xc000142db0), LoadLocals:(*api.LoadConfig)(0xc000142de0), HitCount:map[string]uint64{}, TotalHitCount:0x0}" layer=debugger
time="2019-03-12T13:48:06+01:00" level=debug msg=continuing layer=debugger
time="2019-03-12T13:48:17+01:00" level=debug msg=continuing layer=debugger
Hello World
time="2019-03-12T13:48:17+01:00" level=debug msg=halting layer=debugger
```
Tonight I will try to debug the extension and hopefully find something which helps to solve this problem. 😅

**Comment by michaelweidmann** [comment]
@ramya-rao-a Thanks for your response.

I updated the Go extension but the issue still persists. Here are the logs:

```
API server listening at: 127.0.0.1:11830
time="2019-03-12T13:48:05+01:00" level=info msg="launching process with args: [Y:\\SCM\\Go\\src\\test\\debug]" layer=debugger
time="2019-03-12T13:48:06+01:00" level=info msg="created breakpoint: &api.Breakpoint{ID:1, Name:\"\", Addr:0x4a81d4, File:\"Y:/SCM/Go/src/test/main.go\", Line:6, FunctionName:\"main.main\", Cond:\"\", Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(0xc000142db0), LoadLocals:(*api.LoadConfig)(0xc000142de0), HitCount:map[string]uint64{}, TotalHitCount:0x0}" layer=debugger
time="2019-03-12T13:48:06+01:00" level=debug msg=continuing layer=debugger
time="2019-03-12T13:48:17+01:00" level=debug msg=continuing layer=debugger
Hello World
time="2019-03-12T13:48:17+01:00" level=debug msg=halting layer=debugger
```

Tonight I will try to debug the extension and hopefully find something which helps to solve the problem. 😅

**Comment by michaelweidmann** [comment]
@ramya-rao-a Thanks for your response.

I updated the Go extension but the issue still persists. Here are the logs:

```
API server listening at: 127.0.0.1:11830
time="2019-03-12T13:48:05+01:00" level=info msg="launching process with args: [Y:\\SCM\\Go\\src\\test\\debug]" layer=debugger
time="2019-03-12T13:48:06+01:00" level=info msg="created breakpoint: &api.Breakpoint{ID:1, Name:\"\", Addr:0x4a81d4, File:\"Y:/SCM/Go/src/test/main.go\", Line:6, FunctionName:\"main.main\", Cond:\"\", Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(0xc000142db0), LoadLocals:(*api.LoadConfig)(0xc000142de0), HitCount:map[string]uint64{}, TotalHitCount:0x0}" layer=debugger
time="2019-03-12T13:48:06+01:00" level=debug msg=continuing layer=debugger
time="2019-03-12T13:48:17+01:00" level=debug msg=continuing layer=debugger
Hello World
time="2019-03-12T13:48:17+01:00" level=debug msg=halting layer=debugger
```

In the evening I will try to debug the extension and hopefully find something which helps to solve the problem. 😅

**Comment by ramya-rao-a** [comment]
Hey @michaelweidmann, we have some more improvements in the latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension). Can you give that a try?
