### ISSUE TITLE
Clarify what pressing Alt-Shift-F (formatting) does in fact

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode-go#2270]
For instance:
Set `"go.formatTool": "goimports"` in config.
1. Change `LF` in some *.go file to `CRLF` (Windows) line ending. [That's what git does by default when pulling from repository with <-> `core.autocrlf=true`]
2. Press `Alt-Shift-F`, nothing in Go output console (see #2269), "something" removes empty line between `package` and `import` statements:
 _before `Alt-Shift-F`_
![default](https://user-images.githubusercontent.com/6797881/51642266-a4ecd880-1f79-11e9-971f-a30b38c7fff0.png)
_after `Alt-Shift-F`_
![default](https://user-images.githubusercontent.com/6797881/51642245-93a3cc00-1f79-11e9-84e2-30a412c581c9.png)

and nothing else.

__At the same time__ running `goimports -w <filename>` changes `CRLF` to `LF`, __formats__ file properly with no issues. So what is going on when  `Alt-Shift-F` pressed? It's obvious that VS Code is not actually running goimports as configured!

**Comment by OneOfOne** [comment]
Are you using langserver?

**Comment by inliquid** [comment]
@OneOfOne yes, "bingo" is the langserver I'm using.

**Comment by OneOfOne** [comment]
When the langserver is enabled it takes over formatting unless you set formatting to false in:
```
	"go.languageServerExperimentalFeatures": {
		"format": false, <<<<<<< this
		"autoComplete": true,
		"rename": true,
		"goToDefinition": true,
		"hover": true,
		"signatureHelp": true,
		"goToTypeDefinition": true,
		"goToImplementation": true,
		"documentSymbols": true,
		"workspaceSymbols": true,
		"findReferences": true
	},
```

Also make sure you update bingo every few days as vscode-go can't update it.

**Comment by inliquid** [comment]
@OneOfOne I think it's must be clearly documented in config and dependency added to formatter options. Probably some logging is to be introduced to 'Go' output anyways. Right know it's counter-intuitive and the only way to find out what's happening is to post an issue.

**Comment by ark3** [comment]
Yikes. I was bitten by this as well. I followed the instructions [here](https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code#updates-as-of-080) and discovered that formatting stopped updating imports.

**Comment by ramya-rao-a** [comment]
> I think it must be clearly documented in config and dependency added to formatter options. 

With https://github.com/Microsoft/vscode-go/commit/0faec7e5a8a69d71093f08e035d33beb3ded8626
- The README now has a note on unused imports being removed during formatting based on the formatting tool used
- The setting description for `go.formatTool` has been updated with the same.

The [FAQ](https://github.com/Microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting) for this project has had a note on the same for quite some time.

> Probably some logging is to be introduced to 'Go' output anyways. 

What kind of logging would you suggest?

**Comment by inliquid** [comment]
> What kind of logging would you suggest?
As I said, probably 'Go' output has to provide any idea on what kind of formatter was or wasn't run. For example, when VS Code runs `go vet` or `go-lint`, I can see it there. So why when it runs `goimports` or uses LSP embedded formatting feature - there is nothing?

**Comment by ramya-rao-a** [comment]
Apologies for the very late reply

The `Go` output channel at the moment only logs the diagnostics related processes like build, vet and lint. The `Go test` output channel gets used to show test output.

The `gopls` output channel gets used to log everything related to the language server based on the values passed to the `go.languageServerFlags` setting.

#526 tracks the need to do more logging which we can use to discuss more logging needs.
