### ISSUE TITLE
Update root README with known formatTool issue

### ISSUE THREAD

**Issue by chamilad** [Microsoft/vscode-go#2272]
Please mention the below known issue with Go Formatters that override editor settings in the root README. The only known workaround is to set the `"go.formatTool"` to an uninstallable value such as `"none"` in the JSON view. 

Steps to Reproduce:

1. Follow steps mentioned in #1930

**Comment by ramya-rao-a** [comment]
Updated the [FAQ wiki](https://github.com/Microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting) and updated root README to point to FAQ
