### ISSUE TITLE
Struct tips not pretty with go modules

### ISSUE THREAD

**Issue by xujintao** [Microsoft/vscode-go#2274]
Struct tips not pretty with go modules.

vscode verson: 1.30.2
go extension: Go: Install/Update Tools
go version: 1.11.2

//model/person.go
```golang
package model

type Person struct {
	Name string
	Age  int
}
```

// main.go
```golang
package main

import (
	"fmt"

	"github.com/xujintao/teststruct/model"
)
func main() {
	p := model.Person{"pi", 20}
	fmt.Println(p)
}
```
When mouse focus on Person, it tips:
```golang
type Person struct{Name string; Age int}
```
i expect:
```golang
type Person struct {
	Name string
	Age  int
}
```

**Comment by Delphier** [comment]
+1

**Comment by ramya-rao-a** [comment]
Is it different in a non module mode?

**Comment by xujintao** [comment]
@ramya-rao-a 
Yes, it tips normally in non module mode.

**Comment by ramya-rao-a** [comment]
Can you please provide a screenshot showing the difference for the same struct in module and non module mode?

**Comment by xujintao** [comment]
module
![image](https://user-images.githubusercontent.com/5418373/52186303-7c11f080-2861-11e9-82fb-767637695d89.png)

non-module
![image](https://user-images.githubusercontent.com/5418373/52186240-23425800-2861-11e9-9ca2-9605a4e93327.png)

**Comment by ramya-rao-a** [comment]
Thanks @xujintao!

This data comes from `godef` which seems to be using different formatting for the content between modules and non modules.


 I'll move this issue to the `godef` repo.

**Comment by ramya-rao-a** [comment]
This issue was moved to rogpeppe/godef#109
