### ISSUE TITLE
Compiler is missing DEP CHECK on startup

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode-go#2275]
I'm currently contributing to the [GitLab Runner](https://gitlab.com/gitlab-org/gitlab-runner) project.

They are using [`dep`](https://golang.github.io/dep/) as a package manager tool.

Can we have an option to run `dep check` as a pre-build step, before compiling GO, to get a notion whether all vendor packages are correctly referenced?

Compiling GO should be aborted if the pre-build step (i.e. `dep check` in this case) fails.

**Comment by OneOfOne** [comment]
`dep` is for the most part is deprecated, if you can't switch to go modules, you can always run `dep` manually using tasks:

`.vscode/tasks.json`:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "dep check",
			"type": "process",
			"command": "dep",
			"args": ["check"],
			"problemMatcher": "$go",
			"group": "build"
		},
		{
			"label": "build",
			"dependsOn": "dep check",
			"type": "process",
			"command": "go",
			"args": ["build"],
			"problemMatcher": "$go",
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

**Comment by SetTrend** [comment]
Thanks so much, @OneOfOne, for this valuable information! ❤️ 👍
