### ISSUE TITLE
Package symbol navigation

### ISSUE THREAD

**Issue by anacrolix** [Microsoft/vscode-go#2283]
There doesn't appear to be support package-level navigation. There is file navigation, but other IDE plugins usually provide ways to jump between symbols within the same package. I've asked on gitter and Slack and not received any reply on how to accomplish this. I believe the behaviour is somewhere between "goto symbol in file" and "goto symbol in workspace".

**Comment by axetroy** [comment]
ref #1928

I am waiting this feature

**Comment by anacrolix** [comment]
Yeah it's the Ctrl + . , Ctrl + L in GoSublime. All the symbols in the current package are shown.
