### ISSUE TITLE
Allow passing of flags to gorename

### ISSUE THREAD

**Issue by oschwald** [Microsoft/vscode-go#229]
Currently, it does not appear possible to pass flags to gorename. My use case is a project I work on requires particular tags to be set for `gorename` to work properly with its tests.

**Comment by lukehoban** [comment]
Yeah - this is not yet possible.  We should be able to add a `go.renameFlags` setting which gets appended to the flags passed to `gorename`.

Which flag is it that you want to pass?  I wasn't aware of any flags that are useful but not passed automatically.  Is it the `tags` flag you want to use?

**Comment by oschwald** [comment]
Right, I want to use `tags`.
