### ISSUE TITLE
Documentation suggestions to help users diagnose extension issues

### ISSUE THREAD

**Issue by pwaller** [microsoft/vscode-go#2290]
Hi!

I'm treading a fresh path and trying out the new `gopls` language server. @stamblerre helped me on slack by pointing me at the "View" => "Output" pane, where I could choose `go-langserver` from the dropdown.

This showed that the language server was crashing with panics. I had missed this point because I was following the log outputs which I had configured as so:

```
    "go.languageServerFlags": [
        "-logfile=/home/pwaller/gopls.log"
    ]
```

Of course, when `gopls` crashes it doesn't have time to write to the log, so that was missing. But it did appear in the output pane.

Before reaching out on slack I consulted the following documentation to try and diagnose what was going on:

* [README.md#go-language-server-experimental](https://github.com/Microsoft/vscode-go/tree/5c31292031ddd1861ca92f42377ab2fb36f10fa3#go-language-server-experimental)
* [Wiki: Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code/866c092cf4fc1c99ecc5ec75f7e1e050a5df772e#building-and-debugging-the-extension)
* [CONTRIBUTING.md#reporting-issues](https://github.com/Microsoft/vscode-go/blob/master/CONTRIBUTING.md#reporting-issues)

But I didn't come across the output pane as a potential source of log messages. I think it'd be great to add a note in these places to help people collect pertinent diagnostic information and figure out what's going wrong.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @pwaller and apologies for the late reply.

A few months ago, I revised our [README](https://github.com/microsoft/vscode-go/blob/master/README.md#go-language-server) around language server to add more details. Just now, I added another section for [helpful links](https://github.com/microsoft/vscode-go/blob/master/README.md#helpful-links-for-gopls)

I believe this should cover the concerns you have raised.

Happy coding!
