### ISSUE TITLE
Test snippet should support Parallel execution by default

### ISSUE THREAD

**Issue by a-h** [microsoft/vscode-go#2291]
Currently, the `tdt` snippet produces the following code:

```go
func Test(t *testing.T) {
	testCases := []struct {
		desc	string
		
	}{
		{
			desc: "",
			
		},
	}
	for _, tC := range testCases {
		t.Run(tC.desc, func(t *testing.T) {
			
		})
	}
}
```

This is useful, but doesn't make use of parallel execution as per https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks

So my proposal is that they change to add this in (and match the naming convention in the docs).

```go
func Test(t *testing.T) {
	tests := []struct {
		name	string
	}{
		{
			name: "",

		},
	}
	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			
		})
	}
}
```

It needs 10 thumbs up on the issue to be considered, so please vote if you think it's a good change!

**Comment by lggomez** [comment]
Is it a good idea to have it as the default?

Altough these should be edge cases, there is a certain possibility of testing code which doesn't support parallel execution due to shared package state, like in-memory caches being used from the tests

**Comment by a-h** [comment]
Good point. I don't think we should optimise for the edge case though. If 99% of the time, when you write a test, it's safe for parallel execution, then I think that should be the default.

**Comment by lggomez** [comment]
I agree. It's completely reasonable, considering that the user will have to edit the created code anyway and therefore be conscious about what it does

**Comment by stamblerre** [comment]
As per [#2380 (comment)](https://github.com/microsoft/vscode-go/issues/2380#issuecomment-622009130), we will be pausing development on snippets so that we can reevaluate all of the extension's snippets as a whole. I am sorry, but I'm going to go ahead and close this issue. However, I have noted your suggestion [here](https://github.com/microsoft/vscode-go/issues/2380#issuecomment-629041632).
