### ISSUE TITLE
Update CI to metalinter v3 and the new install script

### ISSUE THREAD

**Issue by vladbarosan** [microsoft/vscode-go#2292]
- Seems that the v3 of the metalinter together with the new install script broke the CI
 - See https://github.com/Microsoft/vscode-go/pull/2059

**Comment by ramya-rao-a** [comment]
[gometalinter](https://github.com/alecthomas/gometalinter) is now deprecated.
We should drop the tests that we have for it

**Comment by ramya-rao-a** [comment]
#2509 will handle the clean up regarding gometalinter
