### ISSUE TITLE
Go to definition fails the second time, when the first time is on a sub module

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#2296]
Sample repo: https://github.com/kidlj/demo

- Open the `main.go` file in the sub module for `gin`
- Run `Go to definition` on any of the symbols from the context package. (This doesnt work in 0.8.0, but will work on the beta package of 0.8.1)
- In the file that opens, run `Go to definition` again on any of the symbols from the context package.

This fails with the error
`godef: There must be at least one package that contains the file`

**Comment by ramya-rao-a** [comment]
This is probably because we are using the root folder i.e the one mapping to the main module, when running the `godef` the second time.

At this time, all we know is the file for the which the operation is being made i.e the one from module cache. For such case, we fall back to the project root folder as the working directory. Because by this time, we have lost the context that we landed in the current file from the sub module.

**Comment by clor09** [comment]
hi, is there any plan to fix this?~  @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@clor09 There is no good solution at hand at the moment, ideas are welcome

**Comment by jellevandenhooff** [comment]
Does the language server protocol have some support for communicating the root? Could paths be munged somehow to give the language server an idea that we are looking at a submodule? This feature is the one holding me back from switching from gocode+vendor to gopls+modules. CC @stamblerre

**Comment by stamblerre** [comment]
@jellevandenhooff: This should work correctly now in `gopls`, as the LSP does provide the module root.

@ramya-rao-a: This issue could probably be closed since modules support will be provided through `gopls` anyway.

**Comment by jellevandenhooff** [comment]
Yes, it totally works now! Thanks!

**Comment by ramya-rao-a** [comment]
Closing this issue as the recommendation for modules is to use the language server
