### ISSUE TITLE
Should packages be auto-imported / removed & grouped?

### ISSUE THREAD

**Issue by grabbou** [Microsoft/vscode-go#23]
Just asking, because I recently moved from `Atom` and the go package made specifically for it does:
- auto import core packages when they are referenced from code (+ also the 3rd party ones)
- auto removes packages that are no longer used (currently we print error about `unused` one)
- automatically groups packages (first core packages, then after blank line 3rd parties). Not sure if that works, since I am having issues with imports described in another issue.

If answer to any of these questions is `Not yet`, I am happy to contribute. It's quite a deal breaker for me, since after working with Atom for a couple of weeks I constantly forget about jumping onto the beginning of the file and editing that import section.

Thanks! Apart from that, all works pretty well, really happy with the autocompletion & hints.

**Comment by shurcooL** [comment]
This functionality is provided by `goimports` and `goreturns` (but not `gofmt`).

So you'd need to use one of those 2 tools, and use Format Code option until there's an option to format-on-save (see #14).

**Comment by lukehoban** [comment]
Yeah - sounds like the missing piece here is the missing format-on-save support that's being tracked in #14.  I'll close this out for now.

**Comment by grabbou** [comment]
Ah, cool. Thanks!
