### ISSUE TITLE
Github imports are sorted differently than when using go fmt manually

### ISSUE THREAD

**Issue by samuell** [Microsoft/vscode-go#230]
#### How to reproduce

Paste this code (which is manually formatted with `go fmt`) in a new go file:

```go
package main

import (
    "fmt"
    "github.com/samuell/scipipe"
    "strings"
)

func main() {
    fmt.Println(strings.ToLower("Hello World!"))
    scipipe.NewShellProcess("echo")
}
```

... and press Ctrl + Shift + I to format the code.

The imports will now be formatted like this:

```go
package main

import (
	"fmt"
	"strings"

	"github.com/samuell/scipipe"
)

func main() {
	fmt.Println(strings.ToLower("Hello World!"))
	scipipe.NewShellProcess("echo")
}

```

So, the github URL is sorted separately from the other imports, with an empty line in between. Manually running `go fmt` on the file again, will restore the code to the first version above.

**Comment by freeformz** [comment]
That is how [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) formats imports, which is the default formatting tool used go vscode-go.

**Comment by samuell** [comment]
@freeformz Ok, IC!

**Comment by freeformz** [comment]
I was wrong about the default. It's [goreturns](https://github.com/sqs/goreturns), but it operates similarly to goimports.

**Comment by lukehoban** [comment]
That's right. Note that you can change the formatting tool with the `go.formatTool` setting. See https://github.com/Microsoft/vscode-go/blob/master/README.md#options.
