### ISSUE TITLE
'Can't load package:' when using somepackage_test

### ISSUE THREAD

**Issue by Nerzal** [microsoft/vscode-go#2303]
I started putting my tests into separate packages after i've read [this](https://stackoverflow.com/a/24731583/4992212) answer on SO 

Steps to Reproduce:

1. Clone the sample repository on https://github.com/Nerzal/vscode-go-bug
2. That's it

These errors won't ever go away.

Steps to reproduce manually:
1. move main to projectroot/cmd/service/main.go
2. create any test under projectroot/pkg/* using an "_" in the package name of the test

![grafik](https://user-images.githubusercontent.com/9110370/52237943-1ce8c600-28cb-11e9-88a6-005a4da9fe38.png)

Note: This happens on Windows & Linux

If this is the intended behavior and i'm doing it wrong, just tell me and close this :)

**Comment by ramya-rao-a** [comment]
@Nerzal Apologies for the late reply.

Do you still see this issue with the latest version of the Go extension? I followed the below steps and I don't see these errors
-  I ran `go get github.com/Nerzal/vscode-go-bug/cmd/service`, 
- then opened the `vscode-go-bug` folder in VS Code
- then opened the file foobar_test.go
