### ISSUE TITLE
Compile with `--strictNullChecks` and `--strictPropertyInitialization` flags

### ISSUE THREAD

**Issue by lggomez** [microsoft/vscode-go#2304]
Continuation of #2284, as discussed with @ramya-rao-a and @vladbarosan. There are about 390 compilation errors with both flags activated, so there's quite a bit of work to do

I'd copy the list but running tsc from the console works differently than the VS Code task, and I get the following error (even with the flags deactivated and no errors running the task):

```
tsconfig.json(14,3): error TS5023: Unknown compiler option 'strictBindCallApply'.
^[[A^[[Bsrc/goImport.ts(79,9): error TS7034: Variable 'edits' implicitly has type 'any[]' in some locations where its type cannot be determined.
src/goImport.ts(85,4): error TS7005: Variable 'edits' implicitly has an 'any[]' type.
```

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode/issues/60565 is a reference to how the VS Code team is tackling the strictNullCheck problem

**Comment by ramya-rao-a** [comment]
If anyone is interested in helping out with this issue, consider enabling `strictNullChecks` in tsconfig.json, and then send PRs to fix smaller subsets of errors. This way we don't have to fix all 400 odd errors at once :)

**Comment by hyangah** [comment]
Closing this in favor of https://github.com/golang/vscode-go/issues/57 
I will make the change to `tsconfig.json` once all the outstanding PRs in the golang/vscode-go repo land.
