### ISSUE TITLE
editor.formatOnSave formats on save always

### ISSUE THREAD

**Issue by garethjensen** [Microsoft/vscode-go#2307]
**Summary:**

Maybe I'm trying to set the wrong setting, but I'm having issues with editor.formatOnSave. When set to false, the formatter set by go.formatTool is called regardless. Not a huge issue, but can sometimes get in the way of my frantic saving habit (I usually run gofmt before checking in). Thanks. Here are my versions:

- VSCode: 1.30.2 (User setup)
- Go Extension: 0.8.0
- Go Compiler: 1.11.4 amd64

**Steps to Reproduce:**

1. Set editor.formatOnSave to false in vscode workspace/user settings 
2. Change the spacing of the code such that it would need to format the file
3. Save the file

**Sample code:**
```
package main

func main() {
    println("Hello world"  )
}
```

**Comment by OneOfOne** [comment]
Do you have the langserver set?

**Comment by garethjensen** [comment]
> Do you have the langserver set?

I do not. I tried setting the language server's experimental "format" setting to false, but that didn't resolve it either, so I reset my configuration. Here are my current workspace settings:

```
{
    "go.formatTool": "gofmt",
    "[go]":  {
        "editor.insertSpaces": true,
        "editor.formatOnSave": true,
    }
}
```

**Comment by garethjensen** [comment]
So, I reinstalled everything and now it works with that same configuration above. I suppose that was the solution. Thanks for your time, love the extension.
