### ISSUE TITLE
Limit concurrent CGO builds

### ISSUE THREAD

**Issue by elgatito** [Microsoft/vscode-go#2312]
Hello,

I tried to search, but did not find something like my issue.

Description:
When I edit project, that is using CGO/Swig and there are non-compiled changes in C code, go build is firing swig to re-compile. 
This is fine.

But when I edit go code, it tries to compile the project and is starting go build (which fires swig, because it's a long compilation) many times, so I see more than 2 processes, and my system hangs totally due to throttling and so on (have to wait few minutes till mouse starts to move, you know).

In perfect, new compilation would not start until previous is running, or maybe a special case for Swig projects or something like that is needed?

**Comment by ramya-rao-a** [comment]
Thanks for reporting @elgatito 

I am not well versed with how CGO or swig works, so bear with me as I have a few questions...

> When I edit project, that is using CGO/Swig and there are non-compiled changes in C code, go build is firing swig to re-compile.

So this is when you are editing non go files?

**Comment by elgatito** [comment]
@ramya-rao-a 

> I am not well versed with how CGO or swig works

It's just a simple `go build ...` command that calls swig+CC to build C code.

 > So this is when you are editing non go files?

No, it happens when I edit Go code, which imports package, which is not yet compiled with Swig/CC.

So when I edit Go files in package A, which imports package B (which has cgo), vscode is starting many `go build` for package B (well, it probably runs `go build` for package A, while it's chaining build for package B, but anyway), and they are starting compilers.

**Comment by ramya-rao-a** [comment]
When the extension runs a `go build`, and there is a previously one already running, the previous one is cancelled i.e. the process that was spawned by for the previous `go build` and all its child processes are killed.

If that is not what you see, then you have 2 options
1. Set `go.buildOnSave` to `false` in your settings. This would stop the the build that gets triggered on file save
2. Or you can set up a local dev environment of this extension and help us figure out why the previous `go build` is not getting cancelled.

If you choose option 2, then
- [Build and Debug extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- For the sake of debugging, disable the other save participants using the `go.lintOnSave` and `go.vetOnSave` settings
- https://github.com/Microsoft/vscode-go/blob/0.6.89/src/goBuild.ts#L51 is the code that ensures previous processes are killed before creating a new one 
- https://github.com/Microsoft/vscode-go/blob/0.6.89/src/util.ts#L603 is the code that actually runs the build
