### ISSUE TITLE
Why is GO111MODULE explicitly disabled for tools ?

### ISSUE THREAD

**Issue by sylr** [Microsoft/vscode-go#2315]
https://github.com/Microsoft/vscode-go/blob/5fda91ac1bd0ef137c0ae52ed24599e572d2dd63/src/goInstallTools.ts#L321

**Comment by ramya-rao-a** [comment]
That was due to 
https://github.com/Microsoft/vscode-go/issues/1919#issuecomment-419765212

Any reason you want it not disabled when installing tools?
