### ISSUE TITLE
Error on CreateBreakpoint: could not find file on Windows

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#2318]
_From 
https://github.com/Microsoft/vscode-go/issues/1307#issuecomment-462069232 by @ravidborse_

Getting Error

> Error on CreateBreakpoint: could not find C:\Users\raborse\go\src\RestAPI\main.go:7

`
Verbose logs are written to:
C:\Users\raborse\AppData\Local\Temp\vscode-go-debug.txt
2019-2-9, 18:29:27.904 UTC
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"go","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"})
InitializeRequest
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsSetVariable":true}}
InitializeResponse
From client: launch({"name":"Launch","type":"go","request":"launch","mode":"debug","program":"c:\\Users\\raborse\\go\\src\\RestAPI\\main.go","showLog":true,"trace":"verbose","logOutput":"rpc","dlvLoadConfig":{"followPointers":true,"maxVariableRecurse":1,"maxStringLen":64,"maxArrayValues":64,"maxStructFields":-1},"env":{"GOPATH":"C:\\Users\\raborse\\go","ALLUSERSPROFILE":"C:\\ProgramData","AMD_ENTRYPOINT":"vs/workbench/services/extensions/node/extensionHostProcess","APPDATA":"C:\\Users\\raborse\\AppData\\Roaming","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"RABORSE-1Q0HR","ComSpec":"C:\\WINDOWS\\system32\\cmd.exe","DEFLOGDIR":"C:\\ProgramData\\McAfee\\Endpoint Security\\Logs","ELECTRON_RUN_AS_NODE":"1","GOROOT":"C:\\Go\\","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\raborse","LOCALAPPDATA":"C:\\Users\\raborse\\AppData\\Local","LOGONSERVER":"\\\\ADC-BGL-PN-1","NUMBER_OF_PROCESSORS":"4","OS":"Windows_NT","Path":"C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\WebEx\\Productivity Tools;C:\\Program Files (x86)\\Cisco\\OSD-ShellApplications;C:\\Program Files\\PuTTY\\;C:\\Python27\\Scripts;C:\\Go\\bin;C:\\Pr[...]
Using GOPATH: C:\Users\raborse\go
Current working directory: c:\Users\raborse\go\src\RestAPI
Running: C:\Users\raborse\go\bin\dlv.exe debug RestAPI --headless=true --listen=127.0.0.1:11879 --api-version=2 --log=true --log-output=rpc
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"API server listening at: 127.0.0.1:11879\n"}}
API server listening at: 127.0.0.1:11879
To client: {"seq":0,"type":"event","event":"initialized"}
InitializeEvent
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
From client: setBreakpoints({"source":{"name":"main.go","path":"C:\\Users\\raborse\\go\\src\\RestAPI\\main.go"},"lines":[7],"breakpoints":[{"line":7}],"sourceModified":false})
SetBreakPointsRequest
All cleared
Creating on: C:\Users\raborse\go\src\RestAPI\main.go:7
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"time=\"2019-02-09T23:59:38+05:30\" level=debug msg=\"<- RPCServer.GetVersion(api.GetVersionIn{})\" layer=rpc\n"}}
time="2019-02-09T23:59:38+05:30" level=debug msg="<- RPCServer.GetVersion(api.GetVersionIn{})" layer=rpc
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"time=\"2019-02-09T23:59:38+05:30\" level=debug msg=\"-> *api.GetVersionOut{\\\"DelveVersion\\\":\\\"Version: 1.1.0\\\\nBuild: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $\\\",\\\"APIVersion\\\":2} error: \\\"\\\"\" layer=rpc\n"}}
time="2019-02-09T23:59:38+05:30" level=debug msg="-> *api.GetVersionOut{\"DelveVersion\":\"Version: 1.1.0\\nBuild: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $\",\"APIVersion\":2} error: \"\"" layer=rpc
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"time=\"2019-02-09T23:59:38+05:30\" level=debug msg=\"<- RPCServer.CreateBreakpoint(rpc2.CreateBreakpointIn{\\\"Breakpoint\\\":{\\\"id\\\":0,\\\"name\\\":\\\"\\\",\\\"addr\\\":0,\\\"file\\\":\\\"C:\\\\\\\\Users\\\\\\\\raborse\\\\\\\\go\\\\\\\\src\\\\\\\\RestAPI\\\\\\\\main.go\\\",\\\"line\\\":7,\\\"Cond\\\":\\\"\\\",\\\"continue\\\":false,\\\"traceReturn\\\":false,\\\"goroutine\\\":false,\\\"stacktrace\\\":0,\\\"LoadArgs\\\":{\\\"FollowPointers\\\":true,\\\"MaxVariableRecurse\\\":1,\\\"MaxStringLen\\\":64,\\\"MaxArrayValues\\\":64,\\\"MaxStructFields\\\":-1},\\\"LoadLocals\\\":{\\\"FollowPointers\\\":true,\\\"MaxVariableRecurse\\\":1,\\\"MaxStringLen\\\":64,\\\"MaxArrayValues\\\":64,\\\"MaxStructFields\\\":-1},\\\"hitCount\\\":null,\\\"totalHitCount\\\":0}})\" layer=rpc\n"}}
time="2019-02-09T23:59:38+05:30" level=debug msg="<- RPCServer.CreateBreakpoint(rpc2.CreateBreakpointIn{\"Breakpoint\":{\"id\":0,\"name\":\"\",\"addr\":0,\"file\":\"C:\\\\Users\\\\raborse\\\\go\\\\src\\\\RestAPI\\\\main.go\",\"line\":7,\"Cond\":\"\",\"continue\":false,\"traceReturn\":false,\"goroutine\":false,\"stacktrace\":0,\"LoadArgs\":{\"FollowPointers\":true,\"MaxVariableRecurse\":1,\"MaxStringLen\":64,\"MaxArrayValues\":64,\"MaxStructFields\":-1},\"LoadLocals\":{\"FollowPointers\":true,\"MaxVariableRecurse\":1,\"MaxStringLen\":64,\"MaxArrayValues\":64,\"MaxStructFields\":-1},\"hitCount\":null,\"totalHitCount\":0}})" layer=rpc
Error on CreateBreakpoint: could not find C:\Users\raborse\go\src\RestAPI\main.go:7
All set:[null]
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":7}]}}
SetBreakPointsResponse
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"time=\"2019-02-09T23:59:38+05:30\" level=debug msg=\"-> *rpc2.CreateBreakpointOut{\\\"Breakpoint\\\":{\\\"id\\\":0,\\\"name\\\":\\\"\\\",\\\"addr\\\":0,\\\"file\\\":\\\"\\\",\\\"line\\\":0,\\\"Cond\\\":\\\"\\\",\\\"continue\\\":false,\\\"traceReturn\\\":false,\\\"goroutine\\\":false,\\\"stacktrace\\\":0,\\\"LoadArgs\\\":null,\\\"LoadLocals\\\":null,\\\"hitCount\\\":null,\\\"totalHitCount\\\":0}} error: \\\"could not find C:\\\\\\\\Users\\\\\\\\raborse\\\\\\\\go\\\\\\\\src\\\\\\\\RestAPI\\\\\\\\main.go:7\\\"\" layer=rpc\n"}}
time="2019-02-09T23:59:38+05:30" level=debug msg="-> *rpc2.CreateBreakpointOut{\"Breakpoint\":{\"id\":0,\"name\":\"\",\"addr\":0,\"file\":\"\",\"line\":0,\"Cond\":\"\",\"continue\":false,\"traceReturn\":false,\"goroutine\":false,\"stacktrace\":0,\"LoadArgs\":null,\"LoadLocals\":null,\"hitCount\":null,\"totalHitCount\":0}} error: \"could not find C:\\\\Users\\\\raborse\\\\go\\\\src\\\\RestAPI\\\\main.go:7\"" layer=rpc
From client: setExceptionBreakpoints({"filters":[]})
To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
ConfigurationDoneRequest
ContinueRequest
To client: {"seq":0,"type":"response","request_seq":5,"command":"configurationDone","success":true}
ContinueResponse
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"time=\"2019-02-09T23:59:38+05:30\" level=debug msg=\"(async 3) <- RPCServer.Command(api.DebuggerCommand{\\\"name\\\":\\\"continue\\\",\\\"ReturnInfoLoadConfig\\\":null})\" layer=rpc\n"}}
time="2019-02-09T23:59:38+05:30" level=debug msg="(async 3) <- RPCServer.Command(api.DebuggerCommand{\"name\":\"continue\",\"ReturnInfoLoadConfig\":null})" layer=rpc
From client: threads(undefined)
To client: {"seq":0,"type":"response","request_seq":6,"command":"threads","success":true,"body":{"threads":[{"id":1,"name":"Dummy"}]}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"Hello World !!!\n"}}
Hello World !!!
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"time=\"2019-02-09T23:59:38+05:30\" level=debug msg=\"(async 3) -> rpc2.CommandOut{\\\"State\\\":{\\\"Running\\\":false,\\\"Threads\\\":null,\\\"NextInProgress\\\":false,\\\"exited\\\":true,\\\"exitStatus\\\":0,\\\"When\\\":\\\"\\\"}} error: \\\"\\\"\" layer=rpc\n"}}
time="2019-02-09T23:59:38+05:30" level=debug msg="(async 3) -> rpc2.CommandOut{\"State\":{\"Running\":false,\"Threads\":null,\"NextInProgress\":false,\"exited\":true,\"exitStatus\":0,\"When\":\"\"}} error: \"\"" layer=rpc
continue state {"Running":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":0,"When":""}
To client: {"seq":0,"type":"event","event":"terminated"}
TerminatedEvent
From client: disconnect({"restart":false})
DisconnectRequest
HaltRequest
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"time=\"2019-02-09T23:59:38+05:30\" level=debug msg=\"(async 4) <- RPCServer.Command(api.DebuggerCommand{\\\"name\\\":\\\"halt\\\",\\\"ReturnInfoLoadConfig\\\":null})\" layer=rpc\n"}}
time="2019-02-09T23:59:38+05:30" level=debug msg="(async 4) <- RPCServer.Command(api.DebuggerCommand{\"name\":\"halt\",\"ReturnInfoLoadConfig\":null})" layer=rpc
Failed to halt - Process 18676 has exited with status 0
DisconnectRequest to parent
To client: {"seq":0,"type":"response","request_seq":7,"command":"disconnect","success":true}
DisconnectResponse
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"time=\"2019-02-09T23:59:38+05:30\" level=debug msg=\"(async 4) -> <nil>null error: \\\"Process 18676 has exited with status 0\\\"\" layer=rpc\n"}}
time="2019-02-09T23:59:38+05:30" level=debug msg="(async 4) -> <nil>null error: \"Process 18676 has exited with status 0\"" layer=rpc`

**Comment by ramya-rao-a** [comment]
@ravidborse Are you using symlinks for this project?

**Comment by ravidborse** [comment]
@ramya-rao-a Thanks.. It's Working Fine Now..

Actually In Windows.. Go Installed in  `C:\Go`  which also contained bin, src, pkg folder, 
But my GOPATH is  `C:\Users\raborse\go\src\RestAPI`.

So during Debugging it was pointing to source in `C:\Go\src` which was invalid. But it's working fine now.
