### ISSUE TITLE
"undefined" source when using LSP

### ISSUE THREAD

**Issue by inliquid** [Microsoft/vscode-go#2321]
VS code: 1.31
vscode-go: 0.9.1

![default](https://user-images.githubusercontent.com/6797881/52582498-62167600-2e3e-11e9-92e9-524afa1cd173.png)

**Comment by ramya-rao-a** [comment]
@inliquid Please log this issue in the repo of the language server you are using.

This is most probably because the language server is not returning the data in the right format to VS Code.

**Comment by inliquid** [comment]
@ramya-rao-a 
Same "undefined" message with Language server turned off:
![default](https://user-images.githubusercontent.com/6797881/53017682-9d79fb80-3461-11e9-879a-5742bd3014f5.png)

**Comment by inliquid** [comment]
Please reopen.

**Comment by ramya-rao-a** [comment]
Thanks @inliquid !
This is indeed not related to the language server, but it is not caused because of this extension either.

I have opened https://github.com/Microsoft/vscode/issues/69091 in the VS Code repo to track this issue
