### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by timthesinner** [Microsoft/vscode-go#2322]
(https://github.com/Microsoft/vscode-go/files/2853003/ms-vscode.Go-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.9.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

[ms-vscode.Go-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-go/files/2853005/ms-vscode.Go-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment]
@timthesinner Thanks for reporting

Can you use the command `Developer: Open Process Explorer` and share the output when you see a high cpu load? This will allow us to see which process is causing the high cpu load
