### ISSUE TITLE
Allow changing showGlobalVariables in settings

### ISSUE THREAD

**Issue by aschade92** [Microsoft/vscode-go#2323]
If I'm using the extension version `0.8.1-beta.7` debugging is very fast and only `local` appears in the variable window:
![image](https://user-images.githubusercontent.com/39062967/52595388-c411b400-2e1b-11e9-9737-c312559a93c6.png)
config: 
```
{
    "go.delveConfig": {
        "apiVersion": 1,
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 600,
            "maxArrayValues": 64,
            "maxStructFields": -1,
            "showGlobalVariables": false
        },
    }
}
```

Now if I install `0.8.1-beta.12` or `0.9.1`, debugging is slightly to significantly slower depending on the amount of variables that are getting collected by the debugger. Setting `showGlobalVariables` to false (as mentioned here: https://github.com/Microsoft/vscode-go/issues/2133#issuecomment-461569056) doesn't really seem to do anything for me (there might be a slight improvement but there is noticeable lag here that is not present in the beta version `0.8.1-beta.7` I mentioned above). Regardless of whether or not `showGlobalVariables` is set to `false`, `global` still appears in the frame: 

![image](https://user-images.githubusercontent.com/39062967/52595811-c45e7f00-2e1c-11e9-8a20-591425796a89.png)

I'm guessing that there is still some other processing being done here in the latest versions that wasn't being done in versions where the debugger works much more fluidly. Is there a way to just completely disable global variables? Is this even expected when `showGlobalVariables` is set to `true`? Global variables aren't really recommended in general by the go community anyways so an option to disable them completely in favor of higher performance would be appreciated.

Steps to Reproduce:

1. Run debug session with above config
2. Debugging is slow, global variables still appear in the variables pane.

**Comment by ramya-rao-a** [comment]
@aschade92 The `showGlobalVariables` needs to be set in the debug configuration in your launch.json file and not in the `go.delveConfig` setting. Can you try doing that?

> Global variables aren't really recommended in general by the go community anyways

Can you point us to some docs or discussion around this?

**Comment by aschade92** [comment]
Cool yeah that worked for me. Is there any way to apply this settings from the workspace settings so that it can be used for running tests? (ie pressing the test or debug button above a test?)

> Can you point us to some docs or discussion around this?

Here are a couple that discuss this issue but I don't think that's super important for the purposes of the thread anymore:

- https://groups.google.com/d/msg/golang-nuts/g_zHm1E3sIs/AIjeUPihuvwJ
- https://dave.cheney.net/2017/06/11/go-without-package-scoped-variables

**Comment by mhr3** [comment]
I'd be also interested in a way to disable the global variables when using the "Debug test" code lens.

**Comment by ramya-rao-a** [comment]
> Is there any way to apply this settings in the workspace settings?

Not at the moment, but we should be able to enable add it to the `go.delveConfig` setting.

PRs are welcome to do this
Code Pointers:
- See [Build and Debug Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) to set up local dev environment
- The `delveConfig` property in the `package.json` file needs to be updated to support `showGlobalVariables` setting
- `goDebugConfiguration.ts` can then be updated to read this setting and update the debug configuration

**Comment by aschade92** [comment]
@ramya-rao-a easy enough, I made a PR for this one

**Comment by ramya-rao-a** [comment]
In the latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension, `showGlobalVariables` is now configurable in the `go.delveConfig` and is disabled by default as well

**Comment by ramya-rao-a** [comment]
This feature is out in the latest release(0.10.0) of the Go extension
