### ISSUE TITLE
[features request] Add a command to restart language server just like restart a typescript language server

### ISSUE THREAD

**Issue by shynome** [Microsoft/vscode-go#2324]
somtimes go language server can't found I have add a new pkg to go.mod, then I can't get any tips from the pkg until I exec `reload the window` command if have a command to restart language server I can just `reload go language server` and don't lose my running cmd or others

**Comment by ramya-rao-a** [comment]
Have you opted in to use the language server explicitly by adding the setting `"go.useLanguageServer": true`?

**Comment by shynome** [comment]
- I have added this setting `"go.useLanguageServer": true`
- `Go: Build current Package` the command seem is helpful, but I'm not sure , because vscode notice me `go.mod changed, rebuild module` , and then the tips have worked. 

the rebuild progress somtimes spend too much time, enough to make me think it stuck and want restart it, I can't find a way to rsetart language server , so I have to run commad `reload the window` to restart it

**Comment by OneOfOne** [comment]
IMO this is related to #2253, `go-langserver` is just broken right now.

**Comment by ramya-rao-a** [comment]
@shynome It is not clear to me if you set `"go.useLanguageServer": true` before or after my question.

Can you share all you go related settings?

**Comment by shynome** [comment]
@ramya-rao-a  it like this 
```jsonc
{
    "go.useLanguageServer": true,
    "go.alternateTools": {
        "go-langserver": "bingo"
    },
    "go.languageServerFlags": ["--format-style", "goimports"],
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    },
}
```

**Comment by ramya-rao-a** [comment]
Ok, looks like you are using the bingo language server. Please log an issue at https://github.com/saibing/bingo/issues first. If it is determined there that this is an issue with the Go extension, then we can re-open this issue.

**Comment by shynome** [comment]
if use anthor language server also need a command to restart language server, so this is not about bingo or others language server.

**Comment by ramya-rao-a** [comment]
>  I can't get any tips from the pkg until I exec `reload the window` common

The original problem was with getting auto-completions and other features when adding packages to the go.mod file.

The language server should be able to give you these features without needing a restart which is why I suggested that this should be an issue for the language server.

**Comment by shynome** [comment]
Tank's your reply. 
I will log an issue to bingo
