### ISSUE TITLE
Go To Definition Not Working after v0.9.0 in symlinked folders

### ISSUE THREAD

**Issue by wmh** [microsoft/vscode-go#2327]
'Go To Definition' works for me on 0.8.0, but after upgrade to 0.9.0 several days ago, it's not working. Even on 0.9.1 and 0.9.2 are not working too. And once I downgrade it to 0.8.0, it works again.

When it's not working, it raises an unknown error on console too, at `log.ts:173`
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/log/common/log.ts#L173
But without further information.

VSCode version: January 2019 (version 1.31)
vscode-go version: 0.9.0+
go version: 1.11.1~1.11.5
OS version: Ubuntu 18.04.1

VSCode settings:
```
{
    "editor.fontFamily": "Consolas, 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'",
    "editor.fontSize": 16,
    "editor.formatOnSave": true,
    "window.zoomLevel": 0,
    "php.validate.enable": true,
    "php.executablePath": "/usr/bin/php",
    "php.validate.run": "onType",
    "explorer.confirmDragAndDrop": false,
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": false,
        "suppressShowKeyBindingsNotice": true
    },
    "explorer.confirmDelete": false,
    "dart.flutterSdkPath": "/usr/local/lib/flutter",
    "editor.rulers": [
        100
    ],
    "[dart]": {},
    "files.associations": {
        "*.php": "php",
        "*.go": "go"
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true
    },
    "eslint.autoFixOnSave": true,
    "eslint.alwaysShowStatus": true,
    "phpformatter.composer": true,
    "go.testFlags": [
        "-count=1",
        "-v"
    ],
    "window.titleBarStyle": "custom",
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true
}
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @wmh 

- Are you using Go modules?
- Can you share a small sample code where you see the problem consistently?
- You should be able to see the actual error on the logs. Select `View` (from the menu) -> `Output `-> `Log (Extension Host)` (from the drop down on the top right side of the panel)

**Comment by wmh** [comment]
Yes, I'm using Go modules. 

Sample code:
```go
package main

import "fmt"

func main() {
	print()
}

func print() {
	fmt.Println("Hello")
}
```
Can't go to definition of print() on version 0.9.0+

Error message from Extension Host:
```
[exthost] [error] [ms-vscode.Go] provider FAILED
[exthost] [error] Command failed: /workspaces/go/bin/godef -t -i -f /workspaces/go/src/tmp/test-godef/main.go -o 46
godef: There must be at least one package that contains the file
```

Update godef:
```
Installing 1 tool at /workspaces/go/bin
  godef

Installing github.com/rogpeppe/godef SUCCEEDED

All tools successfully installed. You're ready to Go :).
```
Same error still shown after update godef.

**Comment by ramya-rao-a** [comment]
Clearly `godef` is failing to provide the location.

Can you provide the folder structure for your project pointing at which folder is the root that was opened in VS Code?

Does running `/workspaces/go/bin/godef -t -f /workspaces/go/src/tmp/test-godef/main.go -o 46` from the terminal give an error or works as expected?

**Comment by wmh** [comment]
`/workspaces/go` is a symbolic link folder that cause the problem. I add the original folder to my workspace and `godef` works again with the same file.

**Comment by ramya-rao-a** [comment]
Thats good to know, thanks @wmh.

So to summarize, the go to definition works in the original folder, but not in sym link folder.
And older version of the extension (0.8.0) works in sym link folders. 
Is that right?

**Comment by wmh** [comment]
In VS Code:
1. the go to definition works in the original folder, but not in sym link folder.
2. And older version of the extension (0.8.0) works in sym link folders.

In termianl, running `/workspaces/go/bin/godef -t -f /workspaces/go/src/tmp/test-godef/main.go -o 46` gives the correct result:
```
/workspaces/go/src/tmp/test-godef/main.go:9:6
print func()
```

**Comment by ramya-rao-a** [comment]
Thanks @wmh 
This is mostly related to the folder from where we are running `godef`. That is the only difference between 0.8.0 and the latest version of the extension.

We will look into this, thanks for reporting.

**Comment by ramya-rao-a** [comment]
Hello @wmh,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

In over a year that has passed since this issue was reported, `gopls` has had improvements in support for various language features, especially when using modules. Hopefully, the above issue is resolved for you when using the language server. If not, then please log a new issue in 
https://github.com/golang/vscode-go/


Thanks for all the support & Happy Coding!
