### ISSUE TITLE
Some types fail to display their content in locals/watch window while debugging

### ISSUE THREAD

**Issue by jhendrixMSFT** [Microsoft/vscode-go#2328]
Per discussion https://github.com/Microsoft/vscode-go/issues/2288#issuecomment-460919209 some types were failing expression evaluation due to '-' character in the type name.  To fix this enclose the type name in quotes, see https://github.com/go-delve/delve/issues/1476 for more info.

**Comment by ramya-rao-a** [comment]
The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension has the fix for this issue

**Comment by ramya-rao-a** [comment]
This feature is out in the latest release(0.10.0) of the Go extension
