### ISSUE TITLE
vscode-go stopped working, gives spawn /usr/local/go EACCES

### ISSUE THREAD

**Issue by jayel-87** [Microsoft/vscode-go#2331]
Issue Type: <b>Bug</b>

Hi, I'm facing a problem with the vscode-go package. It stopped working and when trying to update with go: install/update tools here is what I get:

Installing 16 tools at /Users/jayel/go/bin
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  dlv
  gocode-gomod
  godef
  goreturns
  golint
  gotests
  gomodifytags
  impl
  fillstruct
  goplay

Installing github.com/mdempsky/gocode FAILED
Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/go-delve/delve/cmd/dlv FAILED
Installing github.com/stamblerre/gocode FAILED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/sqs/goreturns FAILED
Installing golang.org/x/lint/golint FAILED
Installing github.com/cweill/gotests/... FAILED
Installing github.com/fatih/gomodifytags FAILED
Installing github.com/josharian/impl FAILED
Installing github.com/davidrjenni/reftools/cmd/fillstruct FAILED
Installing github.com/haya14busa/goplay/cmd/goplay FAILED

16 tools failed to install.

gocode:
Error: spawn /usr/local/go EACCES
gopkgs:
Error: spawn /usr/local/go EACCES
go-outline:
Error: spawn /usr/local/go EACCES
go-symbols:
Error: spawn /usr/local/go EACCES
guru:
Error: spawn /usr/local/go EACCES
gorename:
Error: spawn /usr/local/go EACCES
dlv:
Error: spawn /usr/local/go EACCES
gocode-gomod:
Error: spawn /usr/local/go EACCES
godef:
Error: spawn /usr/local/go EACCES
goreturns:
Error: spawn /usr/local/go EACCES
golint:
Error: spawn /usr/local/go EACCES
gotests:
Error: spawn /usr/local/go EACCES
gomodifytags:
Error: spawn /usr/local/go EACCES
impl:
Error: spawn /usr/local/go EACCES
fillstruct:
Error: spawn /usr/local/go EACCES
goplay:
Error: spawn /usr/local/go EACCES

Never changed any configuration nor did any update. After searching for a good amount of time I've tried to reinstall go and vs code and still the same issue.

I'm using go1.11.5 darwin/amd64
Go Env:

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jayel/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jayel/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bh/734372_j3y1f_8yfbv36pzz40000gn/T/go-build257014597=/tmp/go-build -gno-record-gcc-switches -fno-common"

process.env['PATH']
"/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/bin/:/Users/jayel/.symfony/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/bin/"

I don't have much more information about the error.

Extension version: 0.9.2
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jayel-87** [comment]
Works on version 0.8.0. Going back to this version meanwhile.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @jayel-87 

This is most likely due to https://github.com/Microsoft/vscode-go/pull/2230

Is `/usr/local/go` the go binary or a folder or some other file? Run `/usr/local/go version`

**Comment by jayel-87** [comment]
It's a folder:

```
 => /usr/local/go version
-bash: /usr/local/go: is a directory
```

**Comment by lloiser** [comment]
https://golang.org/doc/install#tarball

> Add /usr/local/go/bin to the PATH environment variable. You can do this by adding this line to your /etc/profile (for a system-wide installation) or $HOME/.profile:
>
>     export PATH=$PATH:/usr/local/go/bin

**Comment by jayel-87** [comment]
It was already set up:
```
export GOPATH="/Users/jayel/go"
    export GOBIN="/usr/local/go/bin"
    PATH=$PATH:$GOPATH:$GOBIN
    export PATH
```

```
=> go env
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/jayel/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jayel/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bh/734372_j3y1f_8yfbv36pzz40000gn/T/go-build634270499=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
I don't know why it's missing in my first message.

**Comment by lloiser** [comment]
https://golang.org/cmd/go/#hdr-Environment_variables
> GOBIN
> The directory where 'go install' will install a command.

Pls unset GOBIN.

It tries to install all those helper tools required by vscode-go into your GOROOT but actually they should go in your GOPATH.

**Comment by jayel-87** [comment]
Same result even with GOBIN unset.

**Comment by aeikenberry** [comment]
Having this same issue. Reverting back to the previous version fixes it.

**Comment by ramya-rao-a** [comment]
@jayel-87, @aeikenberry  Is `/usr/local` in your `PATH` env variable?

I have pushed a possible fix for this to master. Can you try the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension and let me know if this solves the issue for you?

**Comment by seventy-two** [comment]
@ramya-rao-a I've experienced this issue and can confirm that the latest beta version `0.9.3-beta.1` has resolved it.

**Comment by ramya-rao-a** [comment]
Thanks @seventy-two, can you also confirm if  `/usr/local` is in your `PATH` env variable?

**Comment by seventy-two** [comment]
@ramya-rao-a `/usr/local/bin:~/go/bin:/usr/local/go/bin` , not `/usr/local` but I guess it applies

**Comment by jayel-87** [comment]
Thanks @ramya-rao-a, `0.9.3-beta.1` works like a charm. I confirm `/usr/local` is in my `PATH` env variable.

**Comment by ramya-rao-a** [comment]
Great, closing this issue. Will add a comment here when we release the official update
