### ISSUE TITLE
Update tslint

### ISSUE THREAD

**Issue by vladbarosan** [microsoft/vscode-go#2333]
The tslint file has not been updated in 3 years. I would suggest to using:
[tslint:recommended](https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts) ( or latest ) and overwrite any rule we want to overwrite.

Something like:
```json
{
  "defaultSeverity": "error",
  "extends": ["tslint:latest"],
  "jsRules": {},
  "rules": {
    "interface-name": false,
    "object-literal-sort-keys": false,
    "no-console": false,
    "member-ordering": false,
    "no-implicit-dependencies": [true, "dev"]
  }
}
```
...etc

**Comment by ramya-rao-a** [comment]
Thanks for logging this @vladbarosan 
I have reviewed the recommended rules, and updated our tslint.json appropriately with 
https://github.com/Microsoft/vscode-go/commit/3703d35f50c4978dc1c2c59fb0a967f46b1fee78

Few of the rules are commented as they would require work and we can pick them off one by one. Listing them below:
```
{
"arrow-parens": true,
"callable-types": true,
"curly": true,
 "interface-name": {
	"options": ["always-prefix"]
},
"jsdoc-format": true,
"max-line-length": { "options": 120 },
"member-access": true,
"member-ordering": {
     "options": {
	"order": "statics-first"
	}
},
"no-consecutive-blank-lines": true,
"no-empty": true,
"no-shadowed-variable": true,
"no-var-requires": true,
"object-literal-key-quotes": { "options": "consistent-as-needed" },
"object-literal-shorthand": true,
"object-literal-sort-keys": true,
"one-variable-per-declaration": { "options": ["ignore-for-loop"] },
"only-arrow-functions": {
	"options": ["allow-declarations", "allow-named-functions"]
 },
"ordered-imports": {
	"options": {
		"import-sources-order": "case-insensitive",
		"module-source-path": "full",
	        "named-imports-order": "case-insensitive"
	}
},
 "prefer-const": true,
"prefer-for-of": true,
"radix": true,
}
```

**Comment by ramya-rao-a** [comment]
The pending rules have been applied one by one in the master branch

<img width="1237" alt="Screen Shot 2020-01-20 at 11 41 21 PM" src="https://user-images.githubusercontent.com/16890566/72784783-6dd9f300-3bde-11ea-90ad-049344b76960.png">
