### ISSUE TITLE
Every so often, the extension stops working

### ISSUE THREAD

**Issue by tatecapone** [Microsoft/vscode-go#2340]
Latest Macos Mojave
VSCode 1.31.1

@Every so often, the extension stops working, it does not format the code, it does not autoimport the libraries. I have to uninstall it, restart vscode, and reinstall it. It can happen several times during the same work session. It does not give any error, it just stops working.

**Comment by marco-m** [comment]
Same for me on macOS. To get it back to work it is enough, at least for me, to restart VSCode.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @tatecapone and @marco-m 

> it does not autoimport the libraries

Which feature are you referring to here? The one where on file save, the missing imports get added? Or auto-completion adding imports for the symbols from external packages

It will be really be helpful to know exactly which features stop working or if the entire extension stops working.

Another place to look for errors in the output channel. Select the `View` menu -> `Output` -> Select  `Log (Extension Host)` in the drop down channel on the top right side of the panel

**Comment by marco-m** [comment]
Thanks for chiming in @ramya-rao-a . I understand this is a though one to repro for you.

**Comment by OneOfOne** [comment]
Are you using the default langserver?

**Comment by marco-m** [comment]
I am not using the language server at all.

**Comment by tatecapone** [comment]
In my case, the missing packages are not imported nor the code is formatted, when saving the file.

**Comment by ramya-rao-a** [comment]
Those who see formatting issues, try the below
- Change the `go.formatTool` to either `gofmt` or `goimports`
- Increase the `editor.formatOnSaveTimeout` setting if the logs show error about formatting taking too long

To see the logs `View` -> `Output` -> `Logs (Extension Host)` in the dropdown on the top right corner of the panel

**Comment by tatecapone** [comment]
> Those who see formatting issues, try the below
> 
> * Change the `go.formatTool` to either `gofmt` or `goimports`
> * Increase the `editor.formatOnSaveTimeout` setting if the logs show error about formatting taking too long
> 
> To see the logs `View` -> `Output` -> `Logs (Extension Host)` in the dropdown on the top right corner of the panel

I have followed your suggestion ramya, I will tell you if the problem has been solved. Thank you!

**Comment by Keleir** [comment]
`View` -> `Output` -> `Logs (Extension Host)` indicates that vscode-go extension starts failed: 
```
[2019-03-05 17:40:17.227] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.Go {"startup":false, "activationEvent":"onLanguage:go"}
```
My vscode setting for golang is: 

```
"go.formatTool": "goimports",
"editor.formatOnSave": true,
```

Meanwhile, When I use vim to edit the *.go file it works well and also auto import and fmt on save.

My .vimrc config is like this:

```bash
" Golang Plugin
Plugin 'fatih/vim-go'
let g:go_fmt_command = "goimports"
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
"let g:go_metalinter_autosave = 1
let g:syntastic_go_checkers = ['go', 'golint', 'errcheck']
au BufRead,BufNewFile *.go set filetype=go
```

vscode version:  `1.31.1`
vscode-go version:  `0.9.2`
os version: MacOS Mojave `10.14.3`

**Comment by ramya-rao-a** [comment]
@Keleir The log "ExtensionService#_doActivateExtension ms-vscode.Go {"startup":false, "activationEvent":"onLanguage:go"}" does not mean that the extension failed to start. It means that the extension has gotten activated but not on startup i.e it got activated when a Go file was opened.

Please perform the format operation, and then look at the logs for errors

**Comment by Keleir** [comment]
I pretty sure that the current version `0.9.2` leads to this issue, when I downgrade to the version `0.9.1` everything works well for me, such as fmt, lint and auto complete. 

![image](https://user-images.githubusercontent.com/7112075/53929536-fdf77280-40c8-11e9-97f6-5105f9d20162.png)

**Comment by ramya-rao-a** [comment]
@Keleir Please log a new issue with your Go related settings, a clear description of which features work, which features don't work as well as any errors from the logs 

The original issue here by @tatecapone was specific to formatting which has been solved.
Therefore, closing this issue
