### ISSUE TITLE
Find All Reference : Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by serbrech** [Microsoft/vscode-go#2343]
Issue Type: <b>Bug</b>

Open go project, pick a struct or a func, right click, Find all reference.
The Reference result opens with the number of results, but the panel is empty.
an error at the bottom of the screen states "Cannot read property '0' of undefined"

Extension version: 0.9.2
VS Code version: Code - Insiders 1.32.0-insider (7ff2398cfd0776409ff687ce811f1d7ff3375dc8, 2019-02-11T11:40:52.304Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ramya-rao-a** [comment]
Thanks for reporting @serbrech! Can you please provide some more details?

- A screenshot of the error would help.
- Does this happen consistently? Even in a small sample hello world program?
- The next time you see this, can you share any errors you see in the logs? To open the logs, select `View` from the menu -> select `Output` -> select `Log (Extension Host)` from the dropdown on the top right corner. Clear the logs to reduce noise, and go through your steps to see the error corresponding to your scenario

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity.
