### ISSUE TITLE
Add a window to show the dependences in the go.mod

### ISSUE THREAD

**Issue by Allenyn** [Microsoft/vscode-go#2349]
Just like the title.
Add a window to show the dependences in the go.mod

**Comment by ramya-rao-a** [comment]
@Allenyn Please elaborate.

- What window would this be?
- Wont you be able to see the dependencies if you just opened the go.mod file?

**Comment by Allenyn** [comment]
![modules](https://user-images.githubusercontent.com/33450817/53541061-0db80980-3b53-11e9-8ced-0ce9f3540345.png)
like this!

I can see the dependencies by open the go.mod file . But I can't view the source code of dependencies directly.

So.  I think vscode-go should add a window to support this.
 thanks

**Comment by Allenyn** [comment]
@ramya-rao-a

**Comment by ramya-rao-a** [comment]
I do believe this is a cool feature to have, although I am afraid I don't believe this extension is the right place for it. 

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features. 

Therefore, one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.
