### ISSUE TITLE
Find references in all packages in GOPATH

### ISSUE THREAD

**Issue by tejainece** [Microsoft/vscode-go#235]
Thanks for the feature rich and complete Go extension.

I am missing a feature that LiteIDE has: Find usage (GOPATH).

This feature very useful when we have multiple Go package libraries in the same project.

Thanks.

**Comment by lukehoban** [comment]
Have you tried using `Find All References`?  That should provide the same functionality - but is the standard VS Code command across a few languages.

If you think there is something not handled sufficiently by that - feel free to reopen.

**Comment by tejainece** [comment]
Doesn't work. It only find references in current open folder. Doesn't find references in all packages in GOPATH.
