### ISSUE TITLE
idea: run last test function

### ISSUE THREAD

**Issue by agubarev** [Microsoft/vscode-go#2350]
Hello,

I thought of one convenient function but haven't found an easy way to do it (other than run specific test function on save). 

At some point in projects you might no longer want to run tests automatically on save, and want to run tests manually for specific package, file or function (explicitly by name); there is a way to bind keys to these functionalities and all is good, but what if I don't want to run a file or hardcode test function name and just run the last executed test function from non-test file context?

E.g. I run specific test and then jump around my code a lot to fix things, then to test it, I have to switch back to test file or press available keybind to test all or specific test functions.

Suggestion: please add "Run last test" keybind option (bonus kudos: add an easy way to toggle certain functions I want to run alone)

If there's already such functionality exists then please, point out what I've failed to notice, thanks!

**Comment by ramya-rao-a** [comment]
There is a command called `Go: Test Previous` that does just what you have described.
You can assign your own keybinding to this command. Please see https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by agubarev** [comment]
read it late, thanks. this solves it
