### ISSUE TITLE
golang gocode and gopkg install success but doesn't work in vscode

### ISSUE THREAD

**Issue by litianjiao** [Microsoft/vscode-go#2352]
```
env: win10 64   go 1.11.5 go extension 0.9.2
```
My network can't access golang.org directly for the GFW in CN,but I download require package in github,like gocode and gopkg,and put them to the right place in GOPATH .When I open the vscode ,it remind me to update gopkg and gocode. And it output  `Installing github.com/mdempsky/gocode SUCCEEDED`,but it doesn't work actually and remind me update gocode and gopkg when I open the VS code.

**Comment by ramya-rao-a** [comment]
> I download require package in github,like gocode and gopkg,and put them to the right place in GOPATH

Do you mean that you cloned the github repositories for gocode and gopkg?
Can you share the links that you used?

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity.
