### ISSUE TITLE
"Go to Definition" not working with gogetdoc

### ISSUE THREAD

**Issue by leakyshoe** [Microsoft/vscode-go#2353]
Steps to Reproduce:

On a Mac version 10.14.3 using go1.11.5 darwin/amd6 and modules

1. Delete vscode
2. Delete $HOME/go
3. Delete $HOME/.vscode
4. Download vscode Version 1.31.1
5. Install Go plugin
6. Open a go file and agree to "Analysis Tools Missing / install"
7. After tools install re-start vscode
8. Make sure app builds and runs
9. Open a go file and try to navigate to a function in the same package in another file and the gogetdoc process starts but runs and never finds the function "No definition found for ..."
10. Kill the 'gogetdoc' process and repeat 9 after renaming the 'gogetdoc' binary in $HOME/go/bin
11. Confirm there is a error since the binary is not found. The "gogetdoc" command is not available. Use "go get -v github.com/zmb3/gogetdoc" to install.
12. Rename the 'gogetdoc' binary back to its proper name and repeat 9
13. Confirm that the function cannot be found "No definition found for ..."

**Comment by leakyshoe** [comment]
On a Mac version 10.14.3 using go1.11.5 darwin/amd6 and modules

1. Delete vscode
2. Delete $HOME/go
3. Delete $HOME/.vscode
4. Download vscode Version 1.31.1
5. Install Go plugin
6. Open a go file and agree to "Analysis Tools Missing / install"
7 After tools install re-start vscode
8. Make sure app builds and runs
9. Open a go file and try to navigate to a function in the same package in another file and the gogetdoc process starts but runs and never finds the function "No definition found for ..."
10. Kill the 'gogetdoc' process and repeat 9 after renaming the 'gogetdoc' binary in $HOME/go/bin
11. Confirm there is a error since the binary is not found
-> The "gogetdoc" command is not available. Use "go get -v github.com/zmb3/gogetdoc" to install.
12. Rename the 'gogetdoc' binary back to its proper name and repeat 9
13. Confirm that the function cannot be found "No definition found for ..."

**Comment by leakyshoe** [comment]
Sorry for the spam, the formatting was hiding some of the information

**Comment by leakyshoe** [comment]
If I remove "go.docsTool": "gogetdoc" from .vscode/settings.json then after agreeing to the prompt to install godef, code navigation works

**Comment by ramya-rao-a** [comment]
- Can you share a small sample code where you see this issue with `gogetdoc`?
- Are you using Go modules?

**Comment by leakyshoe** [comment]
I installed Go go1.12 and deleted $HOME/go and now it works. We are using modules with vendored dependencies and I think the real problem is performance which the latest version of Go seems to have fixed.

**Comment by leakyshoe** [comment]
OK stopped working again with gogetdoc just spinning its wheels. Basically it doesn't work with medium projects using modules and vendored deps. If I delete "go.docsTool": "gogetdoc" from settings.json to engage godef things work fine. My trial modules project works fine with gogetdoc

[Archive.zip](https://github.com/Microsoft/vscode-go/files/2913414/Archive.zip)

**Comment by leakyshoe** [comment]
FYI our projects have around 15 deps in their mod file

**Comment by leakyshoe** [comment]
Here's another example with vendored dips which works with gogetdoc. So we would really need a fairly large project to test this issue

[Archive2.zip](https://github.com/Microsoft/vscode-go/files/2913448/Archive2.zip)

**Comment by ramya-rao-a** [comment]
@leakyshoe As you have already observed, the problem seems to be with `gogetdoc`. Please log this issue at https://github.com/zmb3/gogetdoc with all the details that you have shared here.
