### ISSUE TITLE
gocode extra flags not passed

### ISSUE THREAD

**Issue by cornfeedhobo** [Microsoft/vscode-go#2355]
After specifying custom flags for `gocode`, they are not used.

```bash
$ code --version
1.31.1
1b8e8302e405050205e69b59abb3559592bb9e60
x64
```

Steps to Reproduce:

1. Edit `go.gocodeFlags` in `settings.json`
    ```json
    "go.gocodeFlags": [
        "-builtin",
        "-ignore-case",
        "-unimported-packages",
        "-fallback-to-source"
    ],
    ```
2. Restart VSCode and check `ps`
    ```bash
    $ ps aux | grep gocode | grep -v grep | cut -f 6- -d'/'
    gocode -s -sock unix -addr 127.0.0.1:37373
    ```

**Comment by ramya-rao-a** [comment]
These flags are meant to be passed on each request to `gocode` in "client" mode. What you see in `ps aux` is `gocode` in server mode.

cc @stamblerre to confirm

**Comment by stamblerre** [comment]
Yes, @ramya-rao-a is right - these are client-side flags, so VSCode-Go is passing them in per-request.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre

**Comment by cornfeedhobo** [comment]
@stamblerre & @ramya-rao-a Thanks for looking into this and clarifying
