### ISSUE TITLE
Import auto population doesn't appear to be working with non system packages

### ISSUE THREAD

**Issue by SteelPhase** [Microsoft/vscode-go#2356]
- OS `macOS 10.14.3`
- VSCode `Version 1.31.1 (1.31.1) 1b8e8302e405050205e69b59abb3559592bb9e60`
- Go pluging `0.9.2`
- Go `go version go1.12 darwin/amd64`

I have disabled all extensions, except for Go, and commented out my settings.json file

### Steps to Reproduce:

Code located here. https://github.com/SteelPhase/vscode-go-issues-2356

1. force vscode to format main.go. adding a space, and saving the file will cause this
2. Code is formatted, but import `"github.com/steelphase/vscode-go-issue-2356/thing"` isn't added to imports

I expect the code to be replaced with

```golang
package main

import (
        "log"

        "github.com/steelphase/vscode-go-issue-2356/thing"
)

func main() {
        s := thing.NewStuff()
        log.Fatal(s.TestThing().Error())
}
```

**Comment by SteelPhase** [comment]
Found a temporary solution in #2336, and adding `"editor.formatOnSaveTimeout": 1500` does appear to resolve it.

Is there anyway vscode-go could not that formatting timed out?

> @lloiser The timeout issue with format on save issue can be fixed with updating the `editor.formatOnSaveTimeout` setting
> 
> `goreturns` is not known to be working with modules reliably yet. I would suggest to use `goimports` instead. Remember to update your version of `goimports` to get the latest fixes that enables it to work with modules. Run `Go: Install/Update Tools` -> select `goimports` -> Press Ok

_Originally posted by @ramya-rao-a in https://github.com/Microsoft/vscode-go/issues/2336#issuecomment-465855645_

**Comment by ramya-rao-a** [comment]
We do add an entry to the logs (View -> Output -> Log (Extension Host))

Can you reset the timeout to 750 and see if you get a warning in the logs?

**Comment by SteelPhase** [comment]
Found it in Log(Window) `2019-02-27 23:19:19.893] [renderer1] [warning] Aborted format on save after 750ms`

**Comment by ramya-rao-a** [comment]
Updated the [FAQ](https://github.com/Microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting) with a note on the logs
