### ISSUE TITLE
Cannot debug golang

### ISSUE THREAD

**Issue by rajkrishnamurthy** [Microsoft/vscode-go#2358]
Issue Type: <b>Bug</b>

I have been using vscode for more than a year now. 
I run on Ubuntu 18.04. There seems to be some inconsistent behavior with new vscode releases. The debugging breaks intermittently. I'm on the latest vscode version. Reinstalled delve. But unable to debug.
Plus, I'm also not able to use basic go linting features on vscode.

Extension version: 0.9.2
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3380M CPU @ 2.90GHz (4 x 2462)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.48GB (0.46GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ramya-rao-a** [comment]
Regarding debugging, please [enable logs for debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#enabling-debug-logs) that might shed some more light on what is happening.

Regarding linting, does running the command `Go: Lint current package` give expected results?
