### ISSUE TITLE
Collapsible Comment Block not working

### ISSUE THREAD

**Issue by TLKG** [Microsoft/vscode-go#2364]
This [feature ](https://github.com/Microsoft/vscode-go/issues/805)on how to make a collapsible comment block is not working, both lines have tab leading space.

![image](https://user-images.githubusercontent.com/22269729/53704790-837ed800-3dd4-11e9-8684-d36c18a4f9ef.png)

**Comment by ramya-rao-a** [comment]
It works as expected for me. 
```
package main

import (
	"fmt"

	"rsc.io/quote"
)

func main() {
	fmt.Prinln(quote.Hello())
	/*
		hello
		this works
	*/
}
````

**Comment by TLKG** [comment]
Version 
VSC = 1.31.1 

![image](https://user-images.githubusercontent.com/22269729/53932923-f98f7300-4050-11e9-8d7c-957ef43eb988.png)

![image](https://user-images.githubusercontent.com/22269729/53932984-38252d80-4051-11e9-88b1-888d780d38e0.png)

**Comment by TLKG** [comment]
one more
![image](https://user-images.githubusercontent.com/22269729/53933036-6c005300-4051-11e9-8330-8bb403188afa.png)

**Comment by ramya-rao-a** [comment]
@TLKG You code sample seems to be for javascript and not Go. This repository is for the extension that supports the Go language in VS Code.

Please log your issue in the main [VS Code](https://github.com/Microsoft/vscode) repo
