### ISSUE TITLE
Syntax higliting wrong when defining the contents of a map

### ISSUE THREAD

**Issue by mjarkk** [Microsoft/vscode-go#2367]
This is what it is supposed to look like:
![screenshot from 2019-03-05 08-32-14](https://user-images.githubusercontent.com/15320763/53788182-5724a200-3f21-11e9-97cc-b86be6650f07.png)

But when i type `var test map[string]string = map[string]string{}` it breaks the syntax highlighting  
![screenshot from 2019-03-05 08-29-45](https://user-images.githubusercontent.com/15320763/53788219-702d5300-3f21-11e9-9601-6cb6a293eec5.png)

What is exactly wrong:
```
var test map[string]string = map[string]string{}
//                   | This string             | The last closing curly bracket
```

**Comment by vladbarosan** [comment]
@mjarkk  tracking this in the upstream repo in VSCode
