### ISSUE TITLE
Run Test cursor create go cache files under testing package

### ISSUE THREAD

**Issue by silentred** [Microsoft/vscode-go#2368]
1. Click "Run Test" cursor above testing function
2. A dir named "on" will be created under the current package. There are many subdirs and a README file in it. 
```
This directory holds cached build artifacts from the Go build system.
Run "go clean -cache" if the directory is getting too large.
See golang.org to learn more about Go.
```

Go 1.12 requires GOCACHE=on, so how can I stop it from generating go cache files under my 
project package?

**Comment by ramya-rao-a** [comment]
@silentred Check if https://github.com/Microsoft/vscode-go/issues/1754 helps

**Comment by ramya-rao-a** [comment]
If https://github.com/Microsoft/vscode-go/issues/1754, doesnt help, then feel free to re-open this issue

**Comment by silentred** [comment]
@ramya-rao-a #1754 deos not help. This problem has something to do with compiling cache. The cache files are used to be created in a temp dir. Now they are created under the project package, where the testing function file lies.

**Comment by ramya-rao-a** [comment]
@silentred As far as I know, this extension doesnt create these files. It must be `go` itself that is doing this either as part of `go build` or `go test`

I dont see how we can provide a fix for this in the extension. I suggest that you log this issue for the Go language itself
