### ISSUE TITLE
Enhance the outline view in vscode

### ISSUE THREAD

**Issue by jhendrixMSFT** [microsoft/vscode-go#2370]
We use the following tool to populate the outline view in vscode.

https://github.com/ramya-rao-a/go-outline

At present all it provides is package name and top-level functions.  Compare this to the outline for say a node program where you get much more information (interfaces, enums, callbacks within funcs etc).  At a minimum we should add the following info.

- package-level constants and vars
- interfaces
- structs/typedefs and their associated methods

Once this is working we can investigate if there's any info inside funcs/methods we want to include.

**Comment by vuongggggg** [comment]
I agree. Go Outliner extension has a better explorer than, but it would be very good by enhancement of this package instead.

**Comment by ramya-rao-a** [comment]
When `go.useLanguageServer` setting is enabled and `gopls` is used, the outline feature is powered by the language server and it does show more useful information. Any further information we would like to see should be logged as a feature request to `gopls` in the [go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fgopls%3A%20%3Cfill%20this%20in%3E)

![image](https://user-images.githubusercontent.com/16890566/70677923-67527600-1c45-11ea-8ed5-d4af0b2f4176.png)

There are no plans to enhance the non-language server scenario at the moment, therefore closing this issue.
