### ISSUE TITLE
support line comment in envFile

### ISSUE THREAD

**Issue by xcaptain** [Microsoft/vscode-go#2373]
In https://github.com/Microsoft/vscode-go/blob/master/src/goPath.ts#L130

env setting like 
```sh
ARG1=1 # it's a comment
```
was parsed as
```sh
ARG1=1 # it's a comment
```

It would be awesome to ignore the trailling hash, so the above line will be parsed as
```sh
ARG1=1
```

It's not a big deal but good to have :)

`godotenv` implementation see [https://github.com/joho/godotenv/blob/master/godotenv.go#L218](https://github.com/joho/godotenv/blob/master/godotenv.go#L218)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @xcaptain 

Is `#` a well known way to have comments in env files? If so, can you point us to some documentation on this?

If it is indeed a well known way to have comments, then PRs are most welcome to support such comments.

Code Pointers:
- See [Build and Debug Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) to set up local dev environment
- The [parseEnvFile](https://github.com/Microsoft/vscode-go/blob/0.9.2/src/goPath.ts#L118) function is the one that parses the envFile

**Comment by xcaptain** [comment]
I didn't find any specification for the env file, according to docker's document [https://docs.docker.com/compose/env-file/](https://docs.docker.com/compose/env-file/)
> Lines beginning with # are processed as comments and ignored.

So I think it's ok we stick with current implementation.
