### ISSUE TITLE
Debugging fails in macOS when "cwd" is set

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode-go#2374]
I am attempting to debug a Go program. When I set `"cwd"` in `launch.json`, debugging fails, claiming that `debugserver` does not exist.

  1. If I comment out `"cwd"`, debugging works.
  2. If I run `dlv exec $(which bake)` in `~/path/to/other/project`, debugging works.
  3. I ran `go get -u github.com/go-delve/delve/cmd/dlv`. Nothing changed.
  4. I have the XCode command-line tools installed, and `debugserver` exists at the expected path and is executable by everyone
  5. Per go-delve/delve#1398, I logged into the apple dev portal and installed the latest version of the command line tools. Nothing changed.
  6. I restarted VSCode after doing all of this, and tried again. It didn't work.

debug console:
```
could not launch process: fork/exec /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: no such file or directory
```

`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}/cmd/bake",
            "cwd": "~/path/to/other/project",
            "args": ["help"]
        },
    ]
}
```

**Comment by firelizzard18** [comment]
This is the project I'm debugging: https://gitlab.com/firelizzard/bake

**Comment by ramya-rao-a** [comment]
@firelizzard18 Does `${workspaceFolder}/cmd/bake` point to a folder or a binary file?

**Comment by firelizzard18** [comment]
It's a folder that is a main package.

**Comment by ramya-rao-a** [comment]
- Is `~/path/to/other/project` related to `${workspaceFolder}` in any way or its a completely different folder?
- In `~/path/to/other/project`, are you able to run `dlv debug ${workspaceFolder}/cmd/bake` and debug your code? Replace `${workspaceFolder}` with the actual path

**Comment by firelizzard18** [comment]
They are in different folders:
* `~/path/to/workspace`
  * `src/other/project`
  * `util/bake/cmd/bake`

```
% dlv debug ../../../util/bake/cmd/bake
go: directory ../../../util/bake/cmd/bake outside available modules
exit status 1
```

```
% dlv debug ~/path/to/workspace/util/bake/cmd/bake
go: directory ../../../util/bake/cmd/bake outside available modules
exit status 1
```

The error message I'm getting is rather odd, but I guess the core issue is that `dlv` doesn't handle this kind of scenario? Looks like `dlv` has a `--wd` flag. Is there a way to set the value of this in `launch.json`?

If possible, I would think a fix for this issue would be modifying `vscode-go` to pass `cwd` as `--wd` to `dlv`, while not actually changing the current working directory.

**Comment by ramya-rao-a** [comment]
The `cwd` that you pass in the launch.json gets passed to delve in the `--wd` flag.
Set `"trace": "log"` in your debug configuration.
This will print some logs in the Debug Console and you will be able to see the exact arguments that are being passed to delve

**Comment by firelizzard18** [comment]
If I run `dlv debug --wd ../../../../src/other/project` from within `${workspaceFolder}/cmd/bake`, I am able to debug.

**Comment by ramya-rao-a** [comment]
What are the arguments passed to `dlv debug` as per the logs?
Does that match with what you are expecting?
Are you using symlinks anywhere?

**Comment by firelizzard18** [comment]
```shell
# fails
dlv debug --headless=true --listen=127.0.0.1:PORT --api-version=2 --wd=~/path/to/workspace/src/other/project

# works
dlv debug --headless=true --listen=127.0.0.1:PORT --api-version=2 --wd=../../../../src/other/project

# works
dlv debug --headless=true --listen=127.0.0.1:PORT --api-version=2 --wd=/Users/me/path/to/workspace/src/other/project
```

I don't see anything unexpected. No symlinks involved. `dlv debug --wd=~/path/to/workspace/src/other/project` works when I run it from Terminal. It seems that `dlv` breaks when `vscode-go` sends it a path starting with `~/`. Easy to work around, but still rather perplexing.

With `cwd` set to `~/path/to/workspace/src/other/project`:
```
Verbose logs are written to:
/var/folders/vy/7b8vfhcx2v7036h99kzs188h0000gn/T/vscode-go-debug.txt
InitializeRequest
InitializeResponse
Using GOPATH: /path/to/go
Current working directory: /Users/me/path/to/workspace/util/bake/cmd/bake
Running: /path/to/go/bin/dlv debug --headless=true --listen=127.0.0.1:37689 --api-version=2 --wd=~/path/to/workspace/src/other/project
API server listening at: 127.0.0.1:37689
could not launch process: fork/exec /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: no such file or directory
Process exiting with code: 1
Sending TerminatedEvent as delve is closed
```

With `cwd` set to `../../../../src/base/node`:
```
Verbose logs are written to:
/var/folders/vy/7b8vfhcx2v7036h99kzs188h0000gn/T/vscode-go-debug.txt
InitializeRequest
InitializeResponse
Using GOPATH: /path/to/go
Current working directory: /Users/me/path/to/workspace/util/bake/cmd/bake
Running: /path/to/go/bin/dlv debug --headless=true --listen=127.0.0.1:5861 --api-version=2 --wd=../../../../src/other/project
API server listening at: 127.0.0.1:5861
InitializeEvent
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
continue state {"Running":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":0,"When":""}
TerminatedEvent
DisconnectRequest
HaltRequest
Failed to halt - Process 38151 has exited with status 0
DisconnectRequest to parent
DisconnectResponse
```

With `cwd` set to `/Users/me/path/to/workspace/src/other/project`:
```
Verbose logs are written to:
/var/folders/vy/7b8vfhcx2v7036h99kzs188h0000gn/T/vscode-go-debug.txt
InitializeRequest
InitializeResponse
Using GOPATH: /path/to/go
Current working directory: /Users/me/path/to/workspace/util/bake/cmd/bake
Running: /path/to/go/bin/dlv debug --headless=true --listen=127.0.0.1:41803 --api-version=2 --wd=/Users/me/path/to/workspace/src/other/project
API server listening at: 127.0.0.1:41803
InitializeEvent
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
continue state {"Running":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":0,"When":""}
TerminatedEvent
DisconnectRequest
HaltRequest
Failed to halt - Process 38478 has exited with status 0
DisconnectRequest to parent
DisconnectResponse
```

**Comment by firelizzard18** [comment]
So this looks like a delve bug. For whatever reason, passing `--wd=~/...` along with `--headless=true`, `--listen=127.0.0.1:$PORT`, and `--api-version=2` fails.

```
% dlv debug --headless=true --listen=127.0.0.1:37689 --api-version=2 --wd=~/path/to/workspace/src/other/project
API server listening at: 127.0.0.1:37689
could not launch process: fork/exec /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: no such file or directory
```

**Comment by quoctruong** [comment]
This seems to be expected behavior from `dlv` so I don't think there's anything the extension can do.

**Comment by firelizzard18** [comment]
The extension can expand `~` before passing flags to `dlv`

**Comment by ramya-rao-a** [comment]
@firelizzard18 is right. We can expand `~` in the `cwd` property that is set, before passing it to delve.

PRs are welcome to do the same

Code Pointers:
- See [Build and Debug Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) to set up local dev environment
- The `resolveDebugConfiguration()` method in `goDebugConfiguration.ts` file is where we can intercept the launch configuration before it gets passed to the debug adapter, so the fix should go here
- You can use the `resolvePath()` function from `util.ts` file to do the resolve `~` and `${workspaceRoot}`

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Please subscribe to https://github.com/golang/vscode-go/issues/117 for further updates on this issue.

Thanks for all the support & Happy Coding!
