### ISSUE TITLE
Unexpectred problem

### ISSUE THREAD

**Issue by kberlinquette** [Microsoft/vscode-go#2378]
I'm new to coding, BUT I'm watching a tutorial and I'm getting errors that he is not. Can't figure out why. How can I recieve an error in my coding when there is no error here is a link to the tutorial also https://www.youtube.com/watch?v=9CDPw1lCkJ8

![Capture](https://user-images.githubusercontent.com/48566775/54382372-da4ea200-465d-11e9-89d1-4824850047cf.PNG)

**Comment by vladbarosan** [comment]
@kberlinquette  this is not a vscode-go issue, please open here only VS Code Go related issues. (FYI probably you want `=` and not `-` in your code) .

**Comment by kberlinquette** [comment]
Thank You :)
