### ISSUE TITLE
removing case sensitvity

### ISSUE THREAD

**Issue by kberlinquette** [Microsoft/vscode-go#2379]
I'm pretty new to javascript and would like to know how to start my string to make all messages ignore case sensitivity. this is the verry start of my string from 1-10

const Discord = require(`discord.js`);
const bot = new Discord.Client();

bot.on(`message`,(message) => {

    if(message.content == `Hi Cortana`){
        //message.reply(`Hi there! My functionality is limited, but my creator is working on it!`);
        message.channel.sendMessage(`Hi there! My functionality is limited, but my creator is working on it!`);
    }
});

**Comment by vladbarosan** [comment]
@kberlinquette this repository is for issues related to the VS Code **Go** extension( https://code.visualstudio.com/docs/languages/go)

If you are writing Go code using VS Code and are using this extension and find any problem with it open an issue here please.

This repo is not:
 - a forum for JS questions
 - a place for issues related in general to VS Code

Thanks and please be mindful of the above before opening any new issue.

**Comment by kberlinquette** [comment]
Ok thanks, I was unawear and will keep that in mind
