### ISSUE TITLE
Source navigation with vendoring does not work

### ISSUE THREAD

**Issue by tnine** [Microsoft/vscode-go#238]
Steps to reproduce.

1. Pull this project. https://github.com/30x/shipyard
1. Run `glide install`
1. Navigate to shipyard/docker.go
1. Find this code

`if err := imageCreator.client.BuildImage(buildImageOptions); err != nil {
		Log.Fatal(err)
		return nil, err
	}
`

Right client on BuildImage, then select "Go to Definition". It does not navigate to the source in the vendor directory.

**Comment by lukehoban** [comment]
This is a limitation of `godef`.  See https://github.com/rogpeppe/godef/pull/25 and https://github.com/rogpeppe/godef/issues/13.  Sounds like this is just waiting on @rogpeppe to review the open PR there.
