### ISSUE TITLE
Add automated tests to debug adapter

### ISSUE THREAD

**Issue by lggomez** [microsoft/vscode-go#2382]
This issue is to keep track and brainstorm about ideas on how to add unit test support to the debug adapter

As of today, the debug adapter is the only part of the extension without tests and the most prone to regressions, due to the fact that it relies on the debugger process to work, and we still lack a standarized set of fixtures to run smoke tests (and, additionally, an automated way to do so)

I think that we should be able to add coverage for any basic scenarios we want (forget about remote for now), but some changes may be required to achieve this. The obvious to me are these:

- Decouple GoDebugSession.Delve into an interface so it can be mocked
- Finding a way to 'record' real scenarios so we can use those as the test cases. This means being able to intercept the json-rpc2 client apicalls. I believe this would allow us to test the debug protocol request implementations to some extent; logging request I/O and using those would be enough for now
- Extra (and harder): Make a runner that is able to create and communicate with a GoDebugSession instance, which is the main entry point and contains most of the debugger-related logic of the adapter. This implies simulating a basic debug adapter lifecycle for each desired scenario (run and exit, breakpoints, pause, etc)

@ramya-rao-a @jhendrixMSFT @vladbarosan what do you think? as Go and Delve evolve this should be a priority in the medium to long term roadmap, as it makes the development process more resilient against big changes and refactors in this area

**Comment by ramya-rao-a** [comment]
I do believe this is essential and hope that as we work with DAP, we can invest time in this.

Closing in favor of https://github.com/golang/vscode-go/issues/137 due to the [repo move](https://github.com/microsoft/vscode-go#we-are-moving---)
