### ISSUE TITLE
VSCode is unable to detect Go binary path

### ISSUE THREAD

**Issue by sankarp-kavach** [microsoft/vscode-go#2384]
Issue Type: <b>Bug</b>

I am running WSL - Windows Subsystem for Linux.

In my vscode integrated terminal:
```
➜  which go
/usr/local/go/bin/go
➜  echo $PATH
/home/sankarp/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/Docker/Docker/resources/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Git/cmd:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin:/c/Program Files/Microsoft VS Code/bin:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R)
Management Engine Components/DAL:/usr/local/go/bin
➜
```

But when I try to install the Golang tools, I get an error message that Go is not installed and that I should update my PATH or GOPATH.

Extension version: 0.9.2
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (3.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ramya-rao-a** [comment]
Hello @sankarp-kavach,

Apologies for the late reply, do you still have this issue?
I am not sure why in WSL, the extension fails to read the PATH properly.

While we try to figure that out, one workaround is to specify the goroot (or the location where the go binary is, minus the "bin" in that location) in the `go.goroot` settings.

Did you get a chance to try the new WSL experience in VS Code? Please see https://code.visualstudio.com/docs/remote/wsl
