### ISSUE TITLE
docs: "You can also run the command"

### ISSUE THREAD

**Issue by broady** [Microsoft/vscode-go#2385]
Could you update the docs to be more specific about what a command is and how to run it?

From the Marketplace store, the docs say:

> You can also run the command Go: Install/Update tools to install/update the same.

I'm new to vscode, so I had no idea what a command is. A link would have been helpful.

**Comment by ramya-rao-a** [comment]
You bring up a good point @broady, thanks for reporting. Your PR has been merged and the changes will show up when the next update to the extension is released.

Welcome to VS Code & Happy Coding!

**Comment by ramya-rao-a** [comment]
This bug fix  is out in the latest release(0.10.0) of the Go extension
