### ISSUE TITLE
When hitting Stop during Debug it kills valiantly the process

### ISSUE THREAD

**Issue by juliandroid** [microsoft/vscode-go#2387]
This occurs due to bugfix #438

In Goland editor the normal process stopping works like this:
1. Process is killed with TERM (0xf) signal once you hit stop button
2. Second click on the stop button does a force kill with -9 in case the first kill does not succeed.

The problem with direct -9 kill is that you cannot handle the stop process gracefully and thus you loose data (in case you save the non-persisted data upon process shutdown).

```
sigs := make(chan os.Signal, 1)
signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
select {
	case sig := <-sigs:
	fmt.Println("Shutdown")
}
```
Code like this works correctly in Goland, but never executed in VS Code

**Comment by tms320** [comment]
+1

**Comment by OneQuid** [comment]
After some searches and tries and looking at the source of dlv after that, I'm afraid that `dlv exec` and `dlv debug` have a different implementation handling `exiting` the progress with `dlv attach`, where they will send `SIGKILL` to the debugging process.
(It would be a delight, if I was wrong about it. Please tell me in that case)

The solution to accomplish `graceful shutdown` without changing the source code of `dlv` command is to use `dlv attach` instead, something might be like:
```
1. build a debug executable,
2. run the executable,
3. get the pid of the running executable,
4. use `sudo dlv attach <pid>` followed by any args
    (yes, the command requires to be root to run correctly on my machine.)
5. work on debuging and exit "gracefully"
6. delete the executable.
```
I am not sure if the root priviledge is required by the command `dlv attach` on all the platforms.

Here's some info of my machine:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.2 Tina
Release:	19.2
Codename:	tina
```
Hope this could help a bit.

**Comment by omcnoe** [comment]
Would be very grateful for a fix. It's good that #438 allows shutting programs that doesn't respond to signals, but it would be great to still be able to close programs that do nicely handle signals.

**Comment by ramya-rao-a** [comment]
> The solution to accomplish graceful shutdown without changing the source code of dlv command is to use dlv attach instead, something might be like:

We do have support for `dlv attach` added recently. You can change the `request` attribute in your debug configuration (in the launch.json file) to `attach` to make use of the `dlv attach` command.

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Closing this issue in favor of https://github.com/golang/vscode-go/issues/120. Please subscribe to it for further updates and upvote it as well

Thanks for all the support & Happy Coding!
