### ISSUE TITLE
Why does vscode ask me to install the go-langserver over and over?

### ISSUE THREAD

**Issue by ericshen881027** [Microsoft/vscode-go#2396]
After I installed the go-langserver, and got the following output:
```
Installing 1 tool at C:\Users\EricS\go\bin
  go-langserver

Installing github.com/sourcegraph/go-langserver SUCCEEDED

Reload VS Code window to use the Go language server
All tools successfully installed. You're ready to Go :).
```
I thought go-langserver had been installed, but after I reloaded the vscode, I still got the message to ask me to install the go-langserver.
I has tried several times, but the vscode still asks me to install it again.
How can I install the go-langserver correctly?

**Comment by deckvig** [comment]
+1，the same

**Comment by ramya-rao-a** [comment]
@ericshen881027, @deckvig 

- Please share the version of VS Code and the Go extension you are using along with OS details
- Can you check if the language server actually got installed? i.e please check for the executable in the location where the logs say that it is installed

**Comment by deckvig** [comment]
```
Extension Name: Go
Extension Version: 0.9.2
OS Version: macOS 10.14.2 (18C54)


~ ➜ go-langserver --version
v3-dev

~ ⍉ ➜ code --version
1.32.3
a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
x64
```

after install go-langserver success and reload window,vscode ask to install again

`The "go-langserver" command is not available. Use "go get -v github.com/sourcegraph/go-langserver" to install.`

**Comment by ramya-rao-a** [comment]
@deckvig 
- Can you share the Go related settings that you have edited as well?
- Run `which go-langserver` in the terminal to see where it got installed
- Run the command `Go: Current GOPATH` in VS Code and see `go-langserver` got installed in the GOPATH that is determined by the VS Code or not

**Comment by ericshen881027** [comment]
> @ericshen881027, @deckvig
> 
> Please share the version of VS Code and the Go extension you are using along with OS details
> Can you check if the language server actually got installed? i.e please check for the executable in the location where the logs say that it is installed

Here is my information:
```
VS Code version: 1.32.3
Go Extension version: 0.9.2
OS version: Version:  Windows_NT x64 10.0.17763

Go related settings: 
{
    "go.alternateTools": {
        "go-langserver": "bingo",
    },
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    },
    "go.useLanguageServer": true
}

go-langserver installed path:  C:\Users\EricS\go\bin\go-langserver.exe
Go: Current GOPATH result: C:\Users\EricS\go is the current GOPATH.
```

**Comment by ramya-rao-a** [comment]
@ericshen881027

I believe what is happening is the below:
- you have updated the settings to use `bingo` instead of `go-langserver
- The extension cannot find bingo, but instead of telling you it can't find bingo, it is telling that it can't find go-langserver
- Now, even if you install `go-langserver`, since the setting tells the extension to use `bingo`, we are now stuck in a loop

I'll push a fix for this soon. For the time being, either install `bingo` or remove the `go.alternateTools` setting that is telling VS Code to use `bingo` in the place of `go-langserver`

**Comment by ramya-rao-a** [comment]
The [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the fix for this issue.

I will be releasing an update later in the week
