### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by koyasama** [Microsoft/vscode-go#2397]
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.9.2`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/a-929/ms-vscode.Go-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment]
Are you using Go modules?
If not, then please run `Developer: Open Process Explorer` command to see which process is causing the high cpu load.

If you are using Go modules, then please use the [language server](https://github.com/golang/go/wiki/gopls) for better performance
