### ISSUE TITLE
Add contributing and style guide

### ISSUE THREAD

**Issue by mgutz** [Microsoft/vscode-go#24]
I would like to contribute and fix some of the issues but since this is a Microsoft project is there anything I need to be made aware of?

Code could be a little more consistent in style. Sometimes strings are single quoted, other times double quoted. Sometimes properties are accessed like `process.env["GOPATH"]`, other times `process.env.GOPATH`.

Willing to help in any way I can to make this more awesome.

**Comment by lukehoban** [comment]
Thanks @mgutz.  I'll work on pulling together a coding guidelines page for this project.

For now though, the guidelines here are a good starting point for code style: https://github.com/Microsoft/vscode/wiki/Coding-Guidelines.

Soma additional general details on contributing to Microsoft repos will be similar to what's in https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md.

**Comment by lukehoban** [comment]
Style is now enforced with the tslint run in TravisCI.  Going to close this out for now as there's nothing more immediate planned here.
