### ISSUE TITLE
No symbols in symbol explorer when using gopls

### ISSUE THREAD

**Issue by tylerb** [Microsoft/vscode-go#2401]
Simple file for testing:

```go
package main

type test struct {
	Field        string
	fieldPrivate string
}

func main() {
}
```

When invoking the symbol explorer (shift+cmd+o), it displays "No symbols found".
Output from the `gopls` trace is:

```
[Trace - 10:40:12 AM] Sending request 'textDocument/documentSymbol - (33)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/tylerb/Projects/go/src/github.com/tylerb/test/test.go"
  }
}


[Trace - 10:40:12 AM] Received response 'textDocument/documentSymbol - (33)' in 0ms.
Params: [
  {
    "name": "test",
    "detail": "struct{...}",
    "kind": 23,
    "range": {
      "start": {
        "line": 2,
        "character": 5
      },
      "end": {
        "line": 5,
        "character": 1
      }
    },
    "selectionRange": {
      "start": {
        "line": 2,
        "character": 5
      },
      "end": {
        "line": 2,
        "character": 9
      }
    }
  },
  {
    "name": "main",
    "detail": "()",
    "kind": 12,
    "range": {
      "start": {
        "line": 7,
        "character": 0
      },
      "end": {
        "line": 8,
        "character": 1
      }
    },
    "selectionRange": {
      "start": {
        "line": 7,
        "character": 5
      },
      "end": {
        "line": 7,
        "character": 9
      }
    }
  }
]
```

It appears gopls is correctly returning symbols, but they are not being used by the extension?

Extension version: `0.9.3-beta.5`
`gopls` was installed via the `Install/Update Go Tools` menu item.

`settings.json` is set up as:
```json
"go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "diagnostics": true,
        "findReferences": true,
        "rename": true
    },
    "go.buildOnSave": "off",
    "go.vetOnSave": "off",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
```

And, lastly, symbols are displayed correctly if I switch to `bingo`.

**Comment by stamblerre** [comment]
I believe that is because the `vscode-languageclient` dependency in VSCode-Go is too low. I have found that upgrading it from 4.3.0 to 4.4.0 and rebuilding the extension has solved the problem for me. I believe that bingo is sending back `SymbolInformation`, while `gopls` uses the newer `DocumentSymbol` (as described [here](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol)).

@ramya-rao-a: would it be possible to bump the version on the `vscode-languageclient` dependency?

**Comment by tylerb** [comment]
I just bumped to `4.4.0`, rebuilt, reinstalled and that fixed the issue.

Thanks @stamblerre!

**Comment by ramya-rao-a** [comment]
The [latest beta version of 0.9.3-beta.6](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) has the language client version updated

Thanks for reporting this @tylerb!
