### ISSUE TITLE
Excessive amounts of /tmp/go-build left behind

### ISSUE THREAD

**Issue by daenney** [Microsoft/vscode-go#2403]
This appears similar/identical to #2173 but unfortunately conversation is locked on that.

I was using VSCode today and running a lot of `> Go: Test file` as well as a bunch of "run test" invocations. This seems to have resulted in as many `tmp/go-buildxxxxx` stale folders as I've run the tests:

```
drwx------   2 daenney   40 Mar 30 12:52 go-build000601375/
drwx------   2 daenney   40 Mar 30 12:39 go-build001444575/
drwx------   2 daenney   40 Mar 30 16:31 go-build003557977/
drwx------   3 daenney   60 Mar 30 12:45 go-build006143658/
drwx------   2 daenney   40 Mar 30 15:34 go-build006457532/
drwx------   3 daenney   60 Mar 30 12:17 go-build007796758/
drwx------   2 daenney   40 Mar 30 12:30 go-build008442069/
drwx------   2 daenney   40 Mar 30 12:20 go-build010041728/
drwx------   2 daenney   40 Mar 30 12:41 go-build010086755/
drwx------   2 daenney   40 Mar 30 12:20 go-build010222779/
drwx------   2 daenney   40 Mar 30 12:07 go-build010486223/
drwx------   3 daenney   60 Mar 30 12:45 go-build010775158/
...
```

```
/tmp ❯❯❯ ls -hFGa -l | grep go-build | wc -l
797
```

All folders are empty.

Running a `go build` by hand for this package does not result in stale `go-build` folders in `/tmp`.

**Comment by daenney** [comment]
I can consistently cause this to happen if I invoke the tests through `> Go: Test file`. It doesn't matter if the tests pass or fail.

**Comment by daenney** [comment]
On second pass I'm not sure if it's related to tests. This seems to happen with BuildOnSave if there's an error during build.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @daenney 

The exact arguments passed to `go build` for the build on save feature is printed to the output channel. Can you try that and it in the terminal to see if such files get created?

In the `View` menu, select `Output`, then select `Go` from the drop down on the top right corner
