### ISSUE TITLE
Superfluous lightbulb 

### ISSUE THREAD

**Issue by fpsqdb** [Microsoft/vscode-go#2405]
Go modules: yes
Go version: 1.12.1
Version: 0.9.3-beta.6

A lightbulb shows on every line.

![vscode_bug](https://user-images.githubusercontent.com/6482819/55308571-bb3d7600-548d-11e9-8b12-2081cd6728c8.png)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @fpsqdb and for trying out the beta version!

I have pushed a fix such that these appear only if there is a selection. Please install the [latest beta](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) version. (0.9.3-beta.7)
