### ISSUE TITLE
Code collapsing doesn't work properly when a multi-line string has a line not beginning with whitespace

### ISSUE THREAD

**Issue by dcormier** [microsoft/vscode-go#2408]
This is a revival of #395. Now that Microsoft/vscode#3422 has been resolved by [adding a new API](https://code.visualstudio.com/updates/v1_23#_folding-provider-api), perhaps this can be made to work correctly with `vscode-go`?

----

Problem: This code doesn't collapse properly because the multi-line string doesn't have whitespace after its newline:

```golang
package thing

func folding() string {
	return `This is a multi-line string.
This line breaks code collapsing.`
}
```

Expected: That it would collapse like this:
![image](https://user-images.githubusercontent.com/216265/55414489-3445d780-5539-11e9-95d9-c68e84419bc3.png)

Actual: It doesn't completely collapse:
![image](https://user-images.githubusercontent.com/216265/55414464-26905200-5539-11e9-95df-1845d88bdb1f.png)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @dcormier 

The Go extension itself is not aware of the AST of the Go file, it relies on external Go tools to provide most language features. Therefore, the Go language server is better candidate to implement a provider for folding.

@stamblerre Can we have this as a feature request for `gopls`?

**Comment by ramya-rao-a** [comment]
@stamblerre Does the language server support folding at the moment?

**Comment by stamblerre** [comment]
Yes it does

**Comment by ramya-rao-a** [comment]
Just tested it with the sample code in this issue, it works!!
Closing :)
