### ISSUE TITLE
Goto line on double click of build/test output w/ file & line #

### ISSUE THREAD

**Issue by natefinch** [Microsoft/vscode-go#241]
I have no idea if this is possible in VSCode (I would hope so)... but it's super handy to be able to just double click a build or test error in the output and jump to the right line in the editor so you can read the exact code.  The filename and line number are right there in the output, so hopefully that's possible.

**Comment by ironcladlou** [comment]
I never found a way to implement this, but the "Show Errors and Warnings" command is a decent substitute in the meantime.

/cc @lukehoban

**Comment by lukehoban** [comment]
@egamma Is there any way to set a problem matcher to use to cause links to appear in the file/line/col references that appear in the output window under a specific (in this case `Go`) output channel?

**Comment by egamma** [comment]
>Is there any way to set a problem matcher to use to cause links to appear in the file/line/col references that appear in the output window under a specific (in this case  Go ) output channel? 

@lukehoban this is currently not possible sorry, we haven't connected `problem matching` with `link detection`. Currently we have some well known patterns we use to turn output into links, see
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputWorker.ts#L72

If you have control over the output of the tool then you can tweak the output to match one of those patterns...

**Comment by joebehymer** [comment]
@lukehoban @egamma Is this supposed to work out of the box with TypeScript?  I feel like it used to..

I have a pretty vanilla `tasks.json` that calls grunt (which uses grunt-ts).  The output seems to match [line 80](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputWorker.ts#L80) of the file you linked above, yet I can't click the lines to navigate.

I took a screenshot if that helps: http://imgur.com/qePitPw

**Comment by ramya-rao-a** [comment]
@natefinch 
The output from build, vet and linting is also sent to the Problems view from where they are clickable and would take you to the right file and line.

**Comment by ramya-rao-a** [comment]
The output channel "Go" that gets the build/lint/vet output as been showing clickable links for a while.

With the latest update (0.6.56) to the Go extension, you can now get the same in the test output as well.
