### ISSUE TITLE
Autocompletion from `gopls` is missing placeholders

### ISSUE THREAD

**Issue by tylerb** [microsoft/vscode-go#2412]
`gopls` autocompletion does not insert placeholders when you select an option.

For example:

1. Type `fmt.Printl`
2. Choose `fmt.Println`
3. You get `fmt.Println` instead of `fmt.Println(a)`

This is exceptionally aggravating because having the parens and placeholders inserted for me automatically has become baked into my fingers. Not having it happen causes all kinds of fumbling.

**Comment by stamblerre** [comment]
The version of gopls at head should insert parentheses and then display signature help that shows you the parameters for the function. We only use placeholders if the client has signature help disabled. I believe that if you configure `"signatureHelp"` to be `"false"` in your `"go.languageServerExperimentalFeatures"`, you should get placeholders.

**Comment by tylerb** [comment]
I'll give this a try. Thanks!

**Comment by stamblerre** [comment]
I'm sorry I spoke to soon - we hardcoded signature help to be enabled by default. I'll send out a fix for that ASAP.

**Comment by stamblerre** [comment]
Looks like there's not a great way to check if the client supports / wants signature help. 

@ramya-rao-a: what do you think - is there a good way to pass the "signatureHelp" setting to the client? Maybe in `initializationOptions`?

cc @ianthehat

**Comment by tylerb** [comment]
The insertion of the parens on tip is working for me. That's a huge help!

Does setting `signatureHelp:false` mean that the little bubble showing the signature will be disabled?

**Comment by stamblerre** [comment]
I think it might just mean that another tool provides the signature help instead of the LSP. But yes, that bubble is the signature help.

**Comment by tylerb** [comment]
It seems odd to me that disabling signature help would give us placeholders, but take away something valuable.

Is it not possible to have both? I feel like it should be something like `signatureHelp:true` and `insertPlaceholders:true` or something like that.

**Comment by ramya-rao-a** [comment]
Signature Help as a feature is usually referred to the parameter hints that show as a tooltip when you are typing inside the (). It can be triggered with Cmd+Shift+Space or Ctrl+Shift+Space as well

<img width="425" alt="Screen Shot 2019-04-03 at 8 17 12 PM" src="https://user-images.githubusercontent.com/16890566/55527346-7bbd8800-564d-11e9-9dbf-3824b6361078.png">

@stamblerre Any flag to gopls about signature help should be related to this.

What @tylerb is asking for is that when a function is chosen from the list of completion results, it should not only enter the function name in the editor, but also the (). The setting `go.useCodeSnippetsOnFunctionSuggest` goes one step further and adds the placeholder text inside the braces

**Comment by stamblerre** [comment]
@tylerb: the latest change I submitted to gopls should allow you to set

```
    "gopls": {
        "usePlaceholders": true,
    }
```

to get placeholders back.

VSCode will complain that it doesn't know about this setting, but it should work once you reload your window. I'm now going to try to wire that setting up to the corresponding VSCode Go extension setting.

**Comment by tylerb** [comment]
@stamblerre it works perfectly! Thanks so much!!

**Comment by ramya-rao-a** [comment]
@stamblerre Do you need any help in syncing the configuration settings between the extension and the language server?

**Comment by billyyumyum** [comment]
If this is of any help to anybody.... my autocomplete params stopped working when I accepted some update yesterday (or day before... I just clicked accept the update and can't remember exactly when) to do with language server. When I unchecked Use Language Server in the GO settings my params began to autocomplete again. Not a very technical contribution but hopefully might put someone on the right path.....

**Comment by ramya-rao-a** [comment]
Thanks @billyyumyum 
That is exactly the case this issue is tracking. The completion feature from the new language server `gopls` doesnt support the parameters being placed in the autocompleted text.
The latest update prompts you to use the new language server in certain scenarios, see https://github.com/Microsoft/vscode-go#go-language-server

**Comment by stamblerre** [comment]
@ramya-rao-a: we do support the placeholders - just behind that config. It might be worth syncing that setting up with the VSCode version of that setting. We actually add placeholders in other places too, like when completing a struct literal - I don't know if that would be under a different setting or just a default behavior?

**Comment by ramya-rao-a** [comment]
The best way to sync the settings is for the extension to pass in the relevant information via [initializationOptions](https://github.com/microsoft/vscode-go/blob/0.10.2/src/goMain.ts#L130). Is that something `gopls` would be able to read?

**Comment by ianthehat** [comment]
Yes, we can, in fact I already sent a pr to use it for something else in #2493

**Comment by ramya-rao-a** [comment]
That's great @ianthehat, thanks!
@stamblerre Would you be able to re-use the `funcSnippetEnabled` option that is meant for the placeholders feature?

**Comment by ramya-rao-a** [comment]
@stamblerre ?

**Comment by stamblerre** [comment]
Filed https://github.com/golang/go/issues/32988.

**Comment by vincepri** [comment]
We also have `go.useCodeSnippetsOnFunctionSuggestWithoutType` which seems currently unsupported in gopls

**Comment by stamblerre** [comment]
What is the difference between the two settings? It would probably be best to have one consistent setting.

**Comment by vincepri** [comment]
It's almost the same, but it omits the type.

For example in `gopls` Server, if I autocomplete `addView`, it'll result in:
```go
s.addView(ctx context.Context, name string, uri span.URI)
```

while the other option, I'd expect:
```go
s.addView(ctx, name, uri)
```

Usually I prefer the second one, because it removes the amount of errors the live linter has to deal with given that having types a function call doesn't compile.

**Comment by stamblerre** [comment]
Makes sense. In `gopls`, we intend to improve the placeholders (https://github.com/golang/go/issues/31548), so I think we will not need both settings. Basically, we should be able to put actual in-scope variables in the placeholders rather than type information.

**Comment by ramya-rao-a** [comment]
Closing in favor of https://github.com/golang/go/issues/32988
