### ISSUE TITLE
`gopls` errors and warnings get stuck

### ISSUE THREAD

**Issue by tylerb** [Microsoft/vscode-go#2417]
Unfortunately I don't have explicit reproduction steps for this.

I've noticed, as I am going along coding, that some of the errors returned by LSP get stuck. It doesn't seem to matter what the error is. There are several different kinds of errors that just stick around.

Reloading the VSCode window will clear them. Other than that, I can not get them to go away. Additionally, `go build` completes with no errors even when the LSP says there are many.

**Comment by stamblerre** [comment]
This is a known issue that I'm currently investigating: https://github.com/golang/go/issues/30786.

**Comment by tylerb** [comment]
Great! Thanks! Should I close this issue? Sorry for the dupe.

**Comment by stamblerre** [comment]
No worries. Up to you, but it will be easier to track issues with gopls specifically in the Go issue tracker.
