### ISSUE TITLE
using auto complete package with gopls enabled doesn't complete everything

### ISSUE THREAD

**Issue by primalmotion** [microsoft/vscode-go#2419]
I've noticed that when I want to auto complete a package, some of them are missing. It seems that if 2 packages have the same name (`json` and `github.com/something/json`) only one is presented in auto complete. I feel there is a map key overlap here. I have goals enabled, but I'm not sure if this is related

**Comment by ramya-rao-a** [comment]
@primalmotion Are you using modules in this case? And are these completions for unimported packages i.e do you have `go.autocompleteUnimportedPackages` setting enabled?

**Comment by primalmotion** [comment]
I'm not using go modules, and yes

**Comment by ramya-rao-a** [comment]
The code to provide completions for unimported packages whether you have enabled the language server or not is essentially the same. Can you check if you see the same behavior with the language server disabled?

**Comment by didil** [comment]
when I enable gopls using:
````
"go.useLanguageServer": true,
"go.alternateTools": {
     "go-langserver": "gopls"
},
````
completion for unimported packages stops working, all the other settings are set to default
using vscode-go 0.9.3-beta.7
(adding go.autocompleteUnimportedPackages has no effect )

**Comment by tj** [comment]
In my case I was also using modules and `"go.autocompleteUnimportedPackages": true`

**Comment by primalmotion** [comment]
@ramya-rao-a it also happen without language server enabled

**Comment by ramya-rao-a** [comment]
Apologies for the delay in getting back to this.

The feature of unimported packages showing up in the completion list is driven by the `go.autocompleteUnimportedPackages` setting.

@didil and everyone who upboted https://github.com/microsoft/vscode-go/issues/2419#issuecomment-480576201, this feature doesnt work when using modules. This issue is being tracked in #2484, so please subscribe to it.

@primalmotion Coming back to your original issue, do you still have the problem? If so, can you provide a sample code that I can use to see the same?

**Comment by primalmotion** [comment]
Yes I still have the issue. To reproduce you need a package with a standard name. For instance github.com/me/json. If you do so, it will auto complete json to be the one from github.com/me, but never the standard encoding/json. My guess is a map key override or something like that.

**Comment by ramya-rao-a** [comment]
I tried the set up you suggested and added a custom "json" package. I am able to see both the standard json and custom one in the implementation. I am not using modules

![json](https://user-images.githubusercontent.com/16890566/60400315-e3894f00-9b26-11e9-87c4-09075ea2794b.gif)

**Comment by primalmotion** [comment]
Weird. It always suggests the json package from kubernetes for me :(

**Comment by ramya-rao-a** [comment]
@primalmotion Try running `gopkgs -format {{.Name}};{{.ImportPath}}` in the folder of your file and see if the output contains both "json" for you. The results from this command is what is used as reference when providing this feature

**Comment by primalmotion** [comment]
I do see `encoding/json` in that (huge) list, however if doesn't not show in my completion list

[gopkgs.zip](https://github.com/microsoft/vscode-go/files/3346876/gopkgs.zip)

**Comment by ramya-rao-a** [comment]
Not sure what is going on here...
Can you debug the extension and find out perhaps? I know you have contributed to the extension before, so you know your way around it :)

https://github.com/microsoft/vscode-go/blob/0.11.0/src/goSuggest.ts#L529 is the function that provides such completion items

**Comment by primalmotion** [comment]
I already dig into that part of the code :). This function takes a map[string]string (allPkgMap) where the key seems to be the short name of the package. So if 2 packages have the name "foo", then the second "foo" overrides the first in the map. That was my original diagnosis. Then I got lost in typescript :)

**Comment by primalmotion** [comment]
But in your gif above it seems to work. Something is fishy. I'll try to find some time tomorrow to look a bit more deeply into that

**Comment by tj** [comment]
hmm FWIW I don't get autocompletes for unimported packages at all anymore, with `"go.autocompleteUnimportedPackages": true,` in a go module at least

**Comment by tj** [comment]
hmm FWIW I don't get autocompletes or suggestions for unimported packages at all anymore, with `"go.autocompleteUnimportedPackages": true,` in a go module at least,

**Comment by stamblerre** [comment]
@tj: `gopls` is used for Go modules, and it does not yet support that behavior: https://github.com/golang/go/issues/31906.

**Comment by primalmotion** [comment]
@ramya-rao-a I printed the content of the completion items list at the output of `getPackageCompletions`: this is what I get

```
github.com/uber/jaeger/model/json
k8s.io/apimachinery/third_party/forked/golang/json
k8s.io/apimachinery/pkg/util/jsonmergepatch
github.com/jaegertracing/jaeger/model/converter/json
github.com/gogo/protobuf/jsonpb/jsonpb_test_proto
k8s.io/apimachinery/pkg/util/json
github.com/docker/go/canonical/json
github.com/docker/docker/pkg/jsonmessage
go.aporeto.io/regolithe/cmd/rego/jsonschema
github.com/aws/aws-sdk-go/private/protocol/jsonrpc
gopkg.in/square/go-jose.v2/json
github.com/gogo/protobuf/test/jsonpb-gogo
github.com/json-iterator/go
github.com/golang/protobuf/jsonpb/jsonpb_test_proto
net/rpc/jsonrpc
k8s.io/client-go/util/jsonpath
github.com/jaegertracing/jaeger/model/json
github.com/gogo/protobuf/jsonpb
github.com/googleapis/gnostic/jsonschema
github.com/go-kit/kit/transport/http/jsonrpc
github.com/golang/protobuf/jsonpb
github.com/docker/docker/daemon/logger/jsonfilelog
github.com/googleapis/gnostic/jsonwriter
github.com/uber/jaeger/model/converter/json
github.com/docker/docker/daemon/logger/jsonfilelog/jsonlog
k8s.io/apimachinery/pkg/runtime/serializer/json
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil
github.com/uber/tchannel-go/json
encoding/json
```

Could vscode limit the number of entries it suggests?

**Comment by primalmotion** [comment]
yep.. by sorting the completion item differently makes `encoding/json` to appear

**Comment by primalmotion** [comment]
if I change 

```
const item = new vscode.CompletionItem(pkgName, vscode.CompletionItemKind.Keyword);
```

by 

```
const item = new vscode.CompletionItem(pkgPath, vscode.CompletionItemKind.Keyword);
```

Then everything works as expected

**Comment by primalmotion** [comment]
So I think VScode somehow doesn't handle multiple identical labels in `CompletionItem`. but again your gif... :/

If you are ok with this, this is the patch I can send

```
diff --git a/src/goSuggest.ts b/src/goSuggest.ts
index 9b4e531..94d3e51 100644
--- a/src/goSuggest.ts
+++ b/src/goSuggest.ts
@@ -537,7 +537,7 @@ function getPackageCompletions(document: vscode.TextDocument, currentWord: strin
        allPkgMap.forEach((pkgName: string, pkgPath: string) => {
                if (pkgName.startsWith(currentWord) && importedPackages.indexOf(pkgName) === -1) {
 
-                       const item = new vscode.CompletionItem(pkgName, vscode.CompletionItemKind.Keyword);
+                       const item = new vscode.CompletionItem(pkgPath, vscode.CompletionItemKind.Module);
                        item.detail = pkgPath;
                        item.documentation = 'Imports the package';
                        item.insertText = pkgName;
@@ -546,7 +546,6 @@ function getPackageCompletions(document: vscode.TextDocument, currentWord: strin
                                command: 'go.import.add',
                                arguments: [{ importPath: pkgPath, from: 'completion' }]
                        };
-                       item.kind = vscode.CompletionItemKind.Module;
 
                        // Unimported packages should appear after the suggestions from gocode
                        const isStandardPackage = !item.detail.includes('.');
```

The downside is that it shows the full package identifier instead of just the name, the upside is that, well it works

**Comment by primalmotion** [comment]
I spent my day using the patch above, and my life dramatically improved :)

**Comment by ramya-rao-a** [comment]
@primalmotion 

>  This function takes a map[string]string (allPkgMap) where the key seems to be the short name of the package. So if 2 packages have the name "foo", then the second "foo" overrides the first in the map.

The key to the map is the package import path and not the package name. So as long as the import paths are different, both `foo` should have an entry

In https://github.com/microsoft/vscode-go/issues/2419#issuecomment-507795571, are you printing out the `detail` property of each completion item? `encoding/json` is definitely showing up in that list.

Can you compare the number of items returned by `getPackageCompletions()` with and without your patch?

**Comment by primalmotion** [comment]
Yeah. I got confused by js giving the value before the key... I ended up looking at the completion items returned with and without my patch, and they are identical. It's the way vscode handles the completion that seems to be causing troubles. It shows only one entry for per identical label for me. Moreover the one it chooses to show is random upon reload

**Comment by ramya-rao-a** [comment]
Let's try a few more things
- comment out anything related to `sortText` in `goSuggest.ts` file. This will force VS Code to use the label of the completion item for sorting
- Add `"editor.suggestSelection": "first"` in your settings

**Comment by primalmotion** [comment]
@ramya-rao-a I did what you suggested, removed my patch and commented out all sortText reference.  Same issue as before

**Comment by ramya-rao-a** [comment]
@primalmotion Do you still have this issue?

**Comment by primalmotion** [comment]
I'm using my patch above since then, so no. But last time I checked without it, yes it was still happening.

**Comment by tamerh** [comment]
I am still have the slow autosuggestion issue when go module is enabled although i have tried the suggestions :(

**Comment by alshdavid** [comment]
I'm using:
- Windows 10
- WSL1
- Windows Terminal
- Go Modules

And VSCode does not autocomplete for me on unimported packages. 
However when I set `go.useLanguageServer` from `true` to `false` it works.

**Comment by stamblerre** [comment]
`gopls` will soon provide full support for autocompletion of unimported packages (see https://github.com/golang/go/issues/31906). You can enable autocompletion of unimported standard library packages by adding:

```json5
"gopls": {
    "completeUnimported": true
}
```

to your `settings.json` file.

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of logging upstream issues against gopls in case of problems with auto completion when using the language server as there is no action item here for the extension itself.

Thanks for your patience
