### ISSUE TITLE
Find references in all packages in GOPATH

### ISSUE THREAD

**Issue by tejainece** [Microsoft/vscode-go#242]
Thanks for the feature rich and complete Go extension.

I am missing a feature that LiteIDE has: Find usage (GOPATH).

This feature very useful when we have multiple Go package libraries in the same project.

Thanks.

Reopening of the previous issue at: https://github.com/Microsoft/vscode-go/issues/235

**Comment by lukehoban** [comment]
We've moved `Find All References` over to use the Go `oracle`, which always searches the full GOPATH/GOROOT.  So this should be fixed now.
