### ISSUE TITLE
go.mod - syntax highlighting for comments has some quirks

### ISSUE THREAD

**Issue by brainsnail** [microsoft/vscode-go#2423]
There are a few scenarios where the comment highlighting doesn't work as expected without a space preceding the comment pattern -`//` :

**Doesn't recognize the comment**
* After the `go` keyword and version
* After the `module` keyword and module 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/444193/55674293-c4e92400-5867-11e9-984c-10317b609fad.png">

**Recognizes the comment string, but breaks subsequent highlighting**
* After the `replace` keyword before a paren
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/444193/55674298-d8948a80-5867-11e9-810b-2d496298505f.png">

_Originally posted by @brainsnail in https://github.com/Microsoft/vscode-go/issues/2410#issuecomment-480531910_

**Comment by ramya-rao-a** [comment]
cc @calebdoxsey

**Comment by calebdoxsey** [comment]
@ramya-rao-a @brainsnail I think https://github.com/Microsoft/vscode-go/pull/2424 should fix these issues.

**Comment by ramya-rao-a** [comment]
This bug fix is now available in the latest update (0.11.0) to the Go extension. Thanks @calebdoxsey and @brainsnail!
