### ISSUE TITLE
can not dynamic detect code change

### ISSUE THREAD

**Issue by zouyee** [Microsoft/vscode-go#2425]
Steps to Reproduce:

1. typ bool
2. complete bool word

<img width="483" alt="屏幕快照 2019-04-08 上午11 20 44" src="https://user-images.githubusercontent.com/5785605/55696764-048f4780-59f1-11e9-9fc1-565d2e678c8d.png">

**Comment by primalmotion** [comment]
I guess you are using gopls, and this case this also happens to m. I have to reload to get my changes visible by gopls

**Comment by ramya-rao-a** [comment]
@stamblerre Is there an issue in the gopls tracking this?

**Comment by stamblerre** [comment]
This sounds like an instance of https://github.com/golang/go/issues/30786. We've been working on trying to investigate this bug, but it's been tricky to reproduce and understand. If you have any logs, they would be much appreciated!

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@zouyee Please add your scenario in https://github.com/golang/go/issues/30786

Meanwhile, you can disable diagnostics from language server by setting `diagnostics` to `false` in the `go.languageServerExperimentalFeatures` setting
