### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bhanu011** [Microsoft/vscode-go#2427]
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.9.2`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.0`
[ms-vscode.Go-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-go/files/3057450/ms-vscode.Go-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment]
- Are you using Go modules?
- Please use the `Developer: Open Process Explorer` to see which process is causing the high cpu usage and share a screen shot if possible
- Also share any Go related settings you have changed
