### ISSUE TITLE
when Find All Reference, clear old result first

### ISSUE THREAD

**Issue by ijesonchen** [microsoft/vscode-go#2428]
If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1. enable language server from Sourcegraph and enable trace
config:
    "go.useLanguageServer": true,
    "go.languageServerFlags": ["-trace", "-logfile", "D:\\dev\\vscode\\langsrv.log"]
2. select a symbol, right click, and Find All Reference
results will show in "reference" window （may take a few seconds）
3. select another symbol, right click, and Find All Reference again
1)With a large project, this may take a few seconds, and old result remains in "reference" window.  
2)With "Output" window, results is retrieve from language server continuously, but only after all result returned,  the "reference" window will be updated.
This may cause confusion, and feel too slow.

Suggestion:
1)When "Find All Reference”, clear old result first. 
2)When retrieve from language server, update "reference" window at the same time, and with a icon or something to indicate all result retrieved. If sort is needed, sort only when all result retrieved, or with option to sort in real-time.

**Comment by ramya-rao-a** [comment]
Apologies for the late reply

The feature request to clear the old results when a new request to find references is fired should be logged against VS Code in https://github.com/Microsoft/vscode. The extension doesnt have control over the UI.

Updating the references as and when each reference is received from the language server is not something that VS Code supports either. That should also be a feature request directly to VS Code as it doesnt provide APIs for updating references this way.
