### ISSUE TITLE
Cursor disappears after using gorename

### ISSUE THREAD

**Issue by sprt** [Microsoft/vscode-go#243]
**Repro**:
- Place cursor on identifier
- Press F2 and rename it
- Press Enter

**What should happen**:
Cursor is moved right before/after the renamed identifier.

**What happens**:
The cursor disappears and I can't bring it back up using the keyboard. The only way to show it again is to click somewhere.

OS: Ubuntu 15.10
VSC: 0.10.10
Ext: 0.6.33

**Comment by lukehoban** [comment]
This is ultimately the same issue as https://github.com/Microsoft/vscode-go/issues/13.  I'm going to close this one and use that other issue to track fixing this generally.
