### ISSUE TITLE
go.uselanguageserver does not work on multi-project workspaces (NodeJS)

### ISSUE THREAD

**Issue by ChrisTrenkamp** [Microsoft/vscode-go#2431]
1. Create a Go module project in a subdirectory of your workspace
2. Create a NodeJS project in a different subdirectory of your workspace
3. Turn on go.uselanguageserver
4. Autocomplete does not seem to work.

I am running VSCode 1.33.0 and am using vscode-go 0.9.3-beta.7.

A workaround is to open a workspace in the Go subdirectory of your project.

**Comment by ramya-rao-a** [comment]
Do you get any error messages? Any notifications?

I am guessing you should have seen something like `The Go language server is not supported in a multi root set up with different GOPATHs`?

**Comment by vanackere** [comment]
@ramya-rao-a I believe this is the same issue reported here on gopls:
https://github.com/golang/go/issues/30841
See also the (duplicate) bug for more information:
https://github.com/golang/go/issues/29174

**Comment by ramya-rao-a** [comment]
Ah! Thats right, thanks @vanackere 

@ChrisTrenkamp At present the language server only supports modules when they are at the root of the workspace. Please subscribe to the links @vanackere has shared above.

Closing this issue in favor of the upstream issues

**Comment by ramya-rao-a** [comment]
fyi @stamblerre
