### ISSUE TITLE
gopls: hovering on something doesn't show documentation anymore

### ISSUE THREAD

**Issue by primalmotion** [Microsoft/vscode-go#2432]
Since I switched to gopls (latest master), I don't see the documentation of a function when I mouse hover it.

Setting `"hover": false` makes it work again

conf: 

```json
go.docsTool": "gogetdoc",
"go.alternateTools": {
        "go-langserver": "gopls"
},
"go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": true
    }
```

**Comment by saibing** [comment]
@primalmotion 

You can try the enhanced version of [gopls](https://github.com/saibing/tools)

**Comment by primalmotion** [comment]
@saibing it works with your fork. Is there any plan to merge your changes upstream?

**Comment by primalmotion** [comment]
for reasons, it also makes https://github.com/Microsoft/vscode-go/issues/2419 work

**Comment by ramya-rao-a** [comment]
@primalmotion Can you check if there is an issue for this at https://github.com/golang/go/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Agopls? If not, can you please log one?

cc @stamblerre In case she knows the current tracking issue for this

**Comment by stamblerre** [comment]
Yep, this is something we are working on (https://github.com/golang/go/issues/29151). We will be supporting all of the features from bingo in gopls eventually.

**Comment by ramya-rao-a** [comment]
Great! Closing this issue in favor of https://github.com/golang/go/issues/29151

**Comment by aknuds1** [comment]
@saibing Thanks, your fork works (better) for me!

**Comment by stamblerre** [comment]
@aknuds1: we actually have added this feature to `gopls`, but we are still deciding on the best way to display documentation (i.e., how much of a comment to show). You can try out this behavior by adding this setting:

```json5
"gopls": {
    "enhancedHover": true
}
```

**Comment by aknuds1** [comment]
@stamblerre When I try adding that to my VS Code settings, it marks "gopls" as an unknown configuration setting.

**Comment by stamblerre** [comment]
Sorry I forgot to mention that would happen, but it will still work. Once we finalize all of the `gopls` settings we will merge these configs with the VSCode extension.

There's more information here: https://github.com/golang/go/wiki/gopls.

**Comment by aknuds1** [comment]
OK thanks!

**Comment by aknuds1** [comment]
@stamblerre I've switched back to the official `gopls` now, let's see how it works.
