### ISSUE TITLE
v0.9.3-beta.7: Format tool stopped working

### ISSUE THREAD

**Issue by VojtechVitek** [Microsoft/vscode-go#2435]
Hi,
looks like the format tool doesn't work for me with this v0.9.3-beta.7 release when saving new changes to the Go files.

I tried "goreturns", "goimports", "gofmt" and nothing is triggered. The debug console doesn't report any errors.

My settings:
```
  "editor.formatOnSave": true,
  "go.formatTool": "goreturns",
```

Hope this is useful report. Keep up the great work, you guys are amazing! 🎉

**Comment by ramya-rao-a** [comment]
- Are you using Go modules?
- Does manual formatting work? right click -> format document
- The debug console has logs for only debugging. Check the logs in the output channel. View -> Output -> Go
- Are there any other Go related settings that you might have changed?
- Are you using the language server?

**Comment by VojtechVitek** [comment]
- Yes, I'm using Go modules and the project has `vendor/` directory.
    `go version go1.12 darwin/amd64`
- Manual formatting doesn't work either
- View->Output->Go: `Finished running tool: /usr/local/go/bin/go vet ./...` vet found 2 problems; both the missing import paths, which should have been fixed by the `gofmt/goimports/goreturns`.
- I don't recall anything special, except for trying out the gopls lang server. My setting worked with the stable version.
- Yes, I'm trying out the new experimental gopls lang server
```json
  "go.useLanguageServer": true,
  "go.alternateTools": {
    "go-langserver": "gopls"
  },
```

Ok, I just verified that if I **disable the lang server, the fmt tool starts working again**. And it doesn't matter if I use "gopls" or not. Hope this helps!

**Comment by ramya-rao-a** [comment]
Thanks @VojtechVitek 
We do suggest the use of language server going forward, so it is worth our time to figure out why formatting didn't work for you. 

The language server doesn't add missing imports on formatting. Is this what you are checking or actual formatting like removing extra tabs/spaces/newlines

Can you check if there are any format related settings that have been changed?

**Comment by kzinglzy** [comment]
I've met the same problem as @VojtechVitek said,

and after setting 

```
"go.languageServerExperimentalFeatures ": {
    "format": false, 
    "autoComplete": true
}
```
the format tool works again

**Comment by VojtechVitek** [comment]
@ramya-rao-a an easy reproducer is to remove one line from the `import()` statements. The format tool doesn't re-add the import line back on file save, when I enable the "gopls" experimental lang server. It does when I disable the lang server.

I don't know how, but the lang server is affecting the format tool.

**Comment by ramya-rao-a** [comment]
The formatting feature from `gopls` doesn't add missing imports back.

It relies on the below setting to add the imports
```
"editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
```

You can try adding the above or disabling the language server or disabling just the format feature from the language server
