### ISSUE TITLE
Intellisens not working when function return struct

### ISSUE THREAD

**Issue by antonmashko** [microsoft/vscode-go#2437]
Hello,
Intellisens not working when function return struct. 
Example:
![image](https://user-images.githubusercontent.com/13744401/55957291-a079b700-5c6e-11e9-9e67-8e411c66b5bb.png)
as you can see func2 is not in the list. same issue for function arguments.
![image](https://user-images.githubusercontent.com/13744401/55957472-1d0c9580-5c6f-11e9-91b7-4f1f92bf1c70.png)

Note: If function return built-in type, everything works fine.
![image](https://user-images.githubusercontent.com/13744401/55957657-8391b380-5c6f-11e9-8077-4ba4c3b48cc4.png)

Environment:
- go version go1.12 darwin/amd64
- macOS Mojave version 10.14.3

**Comment by ramya-rao-a** [comment]
- Are you using Go modules?
- Are you using the language server?
- Please share all the go related settings that have been changed

**Comment by antonmashko** [comment]
@ramya-rao-a 
1. No. 
2. No.
3. I'm using default settings. 

This case reproduce even in one file project (without imports).
Also I did `gocode close` and `Go: Install/Update Tools` and still have same result.

**Comment by antonmashko** [comment]
@ramya-rao-a 
1. No. 
2. No.
3. I'm using default settings. 

This case reproduce even in one file project (without imports).
Also I did `gocode close` and `Go: Install/Update Tools` and still have same result.

**Comment by antonmashko** [comment]
> * Are you using Go modules?
No
> * Are you using the language server?
No
> * Please share all the go related settings that have been changed
 I'm using default settings. 

This case reproduce even in one file project (without imports).
Also I did `gocode close` and `Go: Install/Update Tools` and still have same result.

**Comment by antonmashko** [comment]
> * Are you using Go modules?
No
> * Are you using the language server?
No
> * Please share all the go related settings that have been changed
 I'm using default settings. 

This case reproduce even in one file project (without imports).
Also I did `gocode close` and `Go: Install/Update Tools` and still have same result.

**Comment by ramya-rao-a** [comment]
@antonmashko My apologies for missing to reply on this issue. Can you please provide a sample code using which I can try to replicate this issue?

Can you also try the [new language server gopls](https://github.com/Microsoft/vscode-go#go-language-server) and let us know if you see the same issue?

**Comment by antonmashko** [comment]
Hi @ramya-rao-a,
I've updated golang plugin to version 0.11.7 and turned on useLanguageServer. 
Now everything is fine. Thanks

**Comment by ramya-rao-a** [comment]
Thanks for confirming @antonmashko 

Happy Coding!
