### ISSUE TITLE
Add gofumpt to the format tools

### ISSUE THREAD

**Issue by klaidliadon** [Microsoft/vscode-go#2438]
The gofumpt tool should be added to the accepted format tools:

https://github.com/mvdan/gofumpt

**Comment by ramya-rao-a** [comment]
Have you tried installing gofumpt and then adding the below setting
```
"go.alternateTools": {
   " goformat": "gofumpt"
}
```

This will make the extension use `gofumpt` in the place of the `goreturns` (which is the default formatting tool)

If you have changed the setting `go.formatTool` to something else, then use that instead of `goreturns` above

**Comment by ramya-rao-a** [comment]
Feel free to re-open this issue or add a comment if you have trouble making the above work

**Comment by klaidliadon** [comment]
Hi, I tried your method but it does not seem to work:
![image](https://user-images.githubusercontent.com/5322228/55979080-a339d380-5c91-11e9-89c8-9ea8e3f5c90d.png)

**Comment by ramya-rao-a** [comment]
Sorry, I made a mistake there. Try
```
"go.formatTool": "goreturns",
"go.alternateTools": {
   " goreturns": "gofumpt"
}
```

**Comment by klaidliadon** [comment]
This works, thanks!
