### ISSUE TITLE
Do not recommend Bingo as language server in readme

### ISSUE THREAD

**Issue by Nerzal** [Microsoft/vscode-go#2439]
The readme "recommends" Bingo as an example alternate language server. 
But bingo is discontinued, as the go languageserver people invited that guy to work with them together.

So we should switch the example to any other language server.

Quote from the bingo project:
> 
> I am very sorry that I have planned not continue to maintain this project.
> 
> According to the issue #13 collaborating on golsp, I hope that we will eventually have a unified language server: gopls.
> 
> It is Google's upcoming Go language server. It is in the best interests of the community to only have a single language server.
> 
> I have ported some features such as references, rename, workspace symbol, implementation of bingo to gopls.
> 
> If you want to use the enhanced version of gopls, try https://github.com/saibing/tools.

**Comment by ramya-rao-a** [comment]
There is no other alternative language server to use at the moment.
The recommendation is `gopls`. The instructions in the readme is for anyone not wanting to use `gopls`.

**Comment by Nerzal** [comment]
I thought there might be other language servers, but it short google session told me there really is nothing noticeable. 
From my point of view this issue can be closed

**Comment by alex-shpak** [comment]
From my experience `bingo` still works better than `gopls` so I think it worth mentioning.
