### ISSUE TITLE
[Feature Request] Shortcut to run current file

### ISSUE THREAD

**Issue by kokizzu** [Microsoft/vscode-go#244]
There's a need to `go run` current file.

**Comment by lukehoban** [comment]
Agreed.  I'm hoping we can do that as part of https://github.com/Microsoft/vscode-go/pull/134 or building upon that.  We need all of `build`, `install`, `run` and `generate`.

**Comment by ironcladlou** [comment]
Dupe of https://github.com/Microsoft/vscode-go/issues/73

**Comment by ironcladlou** [comment]
Close enough to a dupe, at least.

**Comment by ramya-rao-a** [comment]
@kokizzu As mentioned in https://github.com/Microsoft/vscode-go/issues/73#issuecomment-270196488 you can use the debugging feature to launch current package. As long as the `program` property in the launch.config points to your package, using `F5` will run your package.
