### ISSUE TITLE
Unknown import path error in file's own package; Error jumps to any file saved.

### ISSUE THREAD

**Issue by threejeez** [microsoft/vscode-go#2440]
I have an issue with only one of my projects in my workspace. For go-a8-web-hooks the IDE can't find the package for the file that I'm currently in (web.go in the screenshot). The crazy thing is that when I save another file (main.go), the error will leave web.go and jump to the file I just saved. I can't build/run the program in the IDE, but I can build/run on the command line. This folder is under my GOPATH directory.

To fix this I tried deleting all VS Code directories and completely reinstalling VS Code. That didn't fix the issue. 

Screenshot

![image](https://user-images.githubusercontent.com/1144520/56037306-f301b480-5cfc-11e9-9cda-23c5423e5fd2.png)

Steps to Reproduce:

I don't know how to reproduce this as it just started happening out of the blue. Nothing has changed.

**Comment by threejeez** [comment]
Can anyone help with this?

**Comment by ramya-rao-a** [comment]
Apologies for the late reply.

- Run `Go: Current GOPATH` and see if it shows the expected GOPATH
- What is the command you ran to successfully build from the command line? Can you try this in the integrated terminal in VS Code and see if you are able to still build?
- If you click on the "OUTPUT" tab in the panel where you are seeing the error, you will see the command (`go build`) that is used by this extension to build your code. Can you copy all the arguments passed to this command and then try the same on the terminal to see if it works?
