### ISSUE TITLE
sort of imports of gopls differs from goreturns

### ISSUE THREAD

**Issue by ulrichSchreiner** [microsoft/vscode-go#2441]
hi,

i use vscode-go 0.9.2 and `gopls`. it looks like gopls adds needed imports to the bottom of the whole import list.

`goreturns` on the other side always splits the imports.

if i have this import list
~~~go
import (
	"fmt"
	"net/http"
	"text/template"
	"time"

	"github.com/inconshreveable/log15"
)
~~~
and enter in my code a `io` then gopls shows a suggestion for the io-Package and if i hit enter, the list now looks like this:
~~~go
import (
	"fmt"
	"net/http"
	"text/template"
	"time"

	"github.com/inconshreveable/log15"
	"io"
)
~~~
if on the other hand i do **not** hit enter when the io-Package is suggested and really enter "io.ByteReader" (no do not select the suggested type from gopls, simply enter the string or paste it) and save, the import list looks like this:
~~~go
import (
	"fmt"
	"io"
	"net/http"
	"text/template"
	"time"

	"github.com/inconshreveable/log15"
)
~~~
you can also delete the empty line in the import list, and save, then the thing looks like this:
~~~go
import (
	"fmt"
	"github.com/inconshreveable/log15"
	"io"
	"net/http"
	"text/template"
	"time"
)
~~~
if you do a ctrl-shift-p and do a "Add Import" and add "archive/tar" this import is added and after saving it is removed (because i do not use it), but now the import is reformatted:
~~~go
import (
	"fmt"
	"io"
	"net/http"
	"text/template"
	"time"

	"github.com/inconshreveable/log15"
)
~~~
i'm not sure which tool is formatting my source, but it would be great to have one way to do it. i had today two git-diffs which only occured because of different formatting of my imports. the imported packages did not change, but the ordering. 

so it would be great to have **one** way of organizing the imports. i like the way goreturns does it, but i can live with any ordering as long as the whole thing stays consistent

**Comment by ramya-rao-a** [comment]
Thanks for reporting @ulrichSchreiner 
cc @stamblerre

**Comment by stamblerre** [comment]
`gopls` does not suggest unimported packages, so I don't believe that `gopls` could be causing the first case. `gopls` follows the convention of having standard library imports separate from third-party imports, but if you delete the line and merge the two, it will just sort the list. I'm not sure that `goimports` and `goreturns` are different.

**Comment by ramya-rao-a** [comment]
@ulrichSchreiner Can you share your Go related settings so that we can determine which tool is doing the ordering of imports in each of scenarios? You can get these by running the command `Preferences: Open Settings (JSON)`

**Comment by stamblerre** [comment]
`gopls` will suggest unimported packages if you add the following to your VSCode settings:

```json5
"gopls": {
    "completeUnimported": true
}
````

**Comment by ulrichSchreiner** [comment]
thanks for the setting. i tried it and now it seems the imports are correctly sorted when i select the suggested package. i'll close this issue as it seems to work now.
