### ISSUE TITLE
Run Package Tests & Run File Tests missing in latest beta no longer appear in 0.9.3-beta.7

### ISSUE THREAD

**Issue by SteelPhase** [Microsoft/vscode-go#2443]
macOS Mojave v10.14.4
vscode v1.33.1
vscode-go v0.9.3-beta.7

Created a folder with the below files, and expected to see `run package tests | run file tests` displayed at the top of `main_test.go`. It appears to reappear if I switch back to vscode-go v0.9.2

main.go
```golang
package main

func main() {
	println(doAThing())
}

func doAThing() string {
	return "test"
}
```

main_test.go
```golang
package main

import "testing"

func Test_doAThing(t *testing.T) {
	tests := []struct {
		name string
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := doAThing(); got != tt.want {
				t.Errorf("doAThing() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @SteelPhase!
The [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.8) has the fix. Can you try that out?

**Comment by SteelPhase** [comment]
@ramya-rao-a I can confirm that the fix resolves this.
