### ISSUE TITLE
Go to Definition for builtin types doesn't work (gopls)

### ISSUE THREAD

**Issue by krpn** [Microsoft/vscode-go#2448]
`Go to Definition` for builtin types doesn't work when use `gopls` language server.

* Visual Studio Code: 1.33.1
* vscode-go: 0.9.3-beta.8
* Go Tools: latest

Steps to Reproduce:

1. settings.json:
```
...
    "go.useLanguageServer": true,
    "go.alternateTools": {
        "gopls": "gopls"
    },
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "diagnostics": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "findReferences": true,
        "goToImplementation": true
    }
...
```
2. Code example:
```
package main

import (
	"fmt"
)

func main() {
	var x string
	x = "example"
	fmt.Println(x)
}

```
3. Try `Go to Definition` for type `string`.

**Comment by ramya-rao-a** [comment]
Where would you expect the definition to be for `string`?
[godef](https://github.com/rogpeppe/godef) and [gogetdoc](http://github.com/zmb3/gogetdoc) which are popular tools to find definition of a symbol also don't provide any definition for built-in types.

cc @stamblerre

**Comment by krpn** [comment]
I expect jump to [builtin.go](https://github.com/golang/go/blob/master/src/builtin/builtin.go) like in GoLand.

P.S. @ramya-rao-a are you forget to release 0.10.0? CHANGELOG.md was updated and contains release date `0.10.0 - 17th April, 2019`.

**Comment by stamblerre** [comment]
I can file an upstream issue for `gopls`, but I was generally curious if that behavior is useful. I can't imagine many people jump to the definition of `string`, and it might be annoying if you clicked it by accident. Of course, if people do find it useful, we can absolutely add it.

**Comment by ramya-rao-a** [comment]
> are you forget to release 0.10.0? CHANGELOG.md was updated and contains release date 0.10.0 - 17th April, 2019.

:) I did think I would be able to release on 17th, but got very busy with work and this slipped.
0.10.0 was released today.

> I can file an upstream issue for gopls, but I was generally curious if that behavior is useful.

@rogpeppe, @zmb3 What are your thoughts here? Have you had such requests for `godef` and `gogetdoc` respectively?

**Comment by zmb3** [comment]
gogetdoc has some special logic for builtins. The definition isn’t very useful as it’s just a stub, but the doc is handy.

**Comment by libnux** [comment]
I got the same problem. And "Go to Definition" does not work for builtin functions either, such append, make, etc.
For standard and custom packages, it works well.

**Comment by libnux** [comment]
> gogetdoc has some special logic for builtins. The definition isn’t very useful as it’s just a stub, but the doc is handy.

for builtin functions, the definition is quite useful.

**Comment by smith-30** [comment]
It did not work well even with 0.10.1, so it now works correctly if I comment out all languageServerFlags.

**Comment by stamblerre** [comment]
@smith-30: `gopls` doesn't have such flags, which is why it was crashing. You can run goimports on save by configuring:

```json5
"[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
},
```

All additional gopls configurations are specified on the wiki: https://github.com/golang/go/wiki/gopls.

**Comment by smith-30** [comment]
@stamblerre thanks for the advise! I should have confirmed the setting, sorry.

**Comment by ramya-rao-a** [comment]
@stamblerre Can we have an issue for this for `gopls`? And then your team can take the call on whether to implement it or not

**Comment by stamblerre** [comment]
Filed https://github.com/golang/go/issues/31696.

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of the upstream issue https://github.com/golang/go/issues/31696
