### ISSUE TITLE
VScode golang plugin

### ISSUE THREAD

**Issue by sathishcaffeine** [Microsoft/vscode-go#2454]
`VSCode Version:` 1.33.1
`Extension:` go
`go Version:` 1.12

For some reason the auto save formatter was broken for me. Have checked the formatter settings from go configuration and everything was enabled and was using `goreturns` on the Format tool section. It was working fine till yesterday and id didn't made an new updates from the extension.  

It is not blocking me as reinstalling VScode fixed the issue for me. Just wanted to make sure you guys are aware of this issue

**Comment by ramya-rao-a** [comment]
It most likely looks like that the formatter was taking longer than what was configured in the `editor.formatOnSaveTimeout` setting.

Next time, look at the logs (View -> Output -> Logs (Extension Host)` . It may have something that might explain why the formatting failed.

Also try manual formatting (right-click -> Format Document) to rule out actual formatting issues vs format on save issues.
