### ISSUE TITLE
Blank line appended on save

### ISSUE THREAD

**Issue by cyb70289** [Microsoft/vscode-go#2455]
I have a fresh install of vscode 1.33.1 and vscode-go extension 0.9.2. Without changing any configuration.

Whenever I save a go file, a blank line is appended at the end of file automatically. I don't want blank line at end of file (go format also discourages it). This issue doesn't happen if disabling go extension, so I guess go extension causes it.

I tried some vscode-go configurations but without luck. Any suggestion? Thanks.

**Comment by ramya-rao-a** [comment]
- Can you share any of the go related settings you might have changed?
- If you are not using the language server, then try changing the `go.formatTool` setting.

**Comment by cyb70289** [comment]
I tried below settings:
- go.formatTool = gofmt
- go.buildOnSave = off

BTW: this issue happens on both Windows10 and Ubuntu18.04, per my test.

**Comment by ramya-rao-a** [comment]
This extension uses the tool you choose in the `go.formatTool` setting to format the files.
In this case `gofmt` tool is adding the new blank line. Please log an issue against it as we simply apply the changes from it.
