### ISSUE TITLE
The latest releases do not contain vsix extention

### ISSUE THREAD

**Issue by ibuziuk** [Microsoft/vscode-go#2456]
The latest stable releases e.g. https://github.com/Microsoft/vscode-go/releases/tag/0.9.2 do not contain `vsix` files unlike the beta one https://github.com/Microsoft/vscode-go/releases/tag/latest
Will it be possible to add `vsix` files to the latest and upcoming releases similar to what is done for other extentions e.g. python https://github.com/Microsoft/vscode-python/releases

**Comment by ramya-rao-a** [comment]
I believe that is because I didnt create a github release for either 0.9.1 or 0.9.2
The latest (0.10.0) release has the right vsix attached.

Do you still need a vsix for 0.9.2 or the one for 0.10.0 is enough?

**Comment by ibuziuk** [comment]
@ramya-rao-a hello, would be great to have vsix for `0.9.2` since this one we are currently using in Eclipse Che

**Comment by ramya-rao-a** [comment]
Done. https://github.com/Microsoft/vscode-go/releases/tag/0.9.2
