### ISSUE TITLE
Use vscode-go without GOPATH

### ISSUE THREAD

**Issue by dancojocaru2000** [Microsoft/vscode-go#2458]
Leaving the religious, almost cult-like defense of GOPATH aside, Go 1.11 allows people to use Go without a GOPATH using modules.

Yet when trying to use Go in VSCode, the following notification appears:
```
Some Go analysis tools are missing from your GOPATH. Would you like to install them?
```

How should someone who isn't using GOPATH at all set up their environment in order to use VSCode for coding in Go?

Can the solution also be included [here](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)?

**Comment by ramya-rao-a** [comment]
That notification is about the extension's inability to find the tools.

Are you suggesting that we remove the reference to GOPATH in that notification or not look at GOPATH for finding the tools?

**Comment by dancojocaru2000** [comment]
Ah, sorry, my bad. I thought that no GOPATH is set by default.

So, if not using GOPATH in projects, one shouldn't worry about it, right?

**Comment by ramya-rao-a** [comment]
> So, if not using GOPATH in projects, one shouldn't worry about it, right?

Yes. I also agree that, that notification might be confusing to new users to Go, who might never had to think about GOPATH.

Updated the messaging there to avoid reference to GOPATH with https://github.com/Microsoft/vscode-go/commit/21bab081b1253ed9342a83f005a640ac3f05575a
