### ISSUE TITLE
The gopls server crashed when upgrade vscode-go to 0.10.0

### ISSUE THREAD

**Issue by gotoxu** [Microsoft/vscode-go#2459]
I just upgraded vscode-go to 0.10.0, but once I open the project I found that vscode has been reporting gopls crashed:

```
The gopls server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

It works fine in version 0.9.2, or change gopls to bingo can also return to normal.

This is my vscode-go related configuration:
```json
{
    "go.formatTool": "goimports",
    "go.languageServerFlags": [
        "-trace"
    ],
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true
    },
    "go.useLanguageServer": true,
}
```

**Comment by stamblerre** [comment]
Can you try switching the flag to `-rpc.trace`? I think we switched that one.

**Comment by gotoxu** [comment]
@stamblerre Yes, it works! So the [README.md](https://github.com/Microsoft/vscode-go/tree/8ea6e4708dfd141ab65b4c7eb4f71e55d098a222#go-language-server-experimental) file needs to be updated.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @gotoxu!

@stamblerre Was that intentional? Do you plan to keep that or move back to `-trace` at any point?

**Comment by stamblerre** [comment]
@ramya-rao-a: Yes, it was. I think we will likely stick with `-rpc.trace` for now. 

Perhaps we could add some additional handling for invalid flags so that they don't completely crash the server, though I'm not sure how that would look. I expect it would have to be in the extension, so that it could notify the user that they've passed an incorrect flag.

**Comment by ramya-rao-a** [comment]
We can't handle all invalid flags, but we definitely can handle this one.
Updated the extension to pass `-rpc.trace` to `gopls` if user has `-trace` with https://github.com/Microsoft/vscode-go/commit/d0eed0883597d32b86f07f7a0a07795e250813e7

**Comment by ramya-rao-a** [comment]
The fix is out in the update I just released (0.10.1)

Thanks again for reporting @gotoxu!

**Comment by wolfeidau** [comment]
I am getting this error as well 

```
The gopls server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

```

**Comment by stamblerre** [comment]
@wolfeidau: What flags are you passing to the language server?

**Comment by wolfeidau** [comment]
@stamblerre I didn't change or update any settings for gopls, just did the upgrade to vscode-go.

Ended up cleaning out go modules cache to fix this, not sure what was up.

**Comment by stamblerre** [comment]
@wolfeidau: Glad it's working now, thanks for reporting this. Please file an issue [here](https://github.com/golang/go/issues) if you encounter this again.

**Comment by adk9** [comment]
I am also getting this error on `0.10.2`.

VS Code version is:
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-13-generic
```

golang version is:
```
$ go version
go version go1.12 linux/amd64
```

Cleaned the modules cache and reinstalled the extension, but neither helped. Adding the `-rpc.trace` flag doesn't print anything in the output panel. How can I debug what's going on?

**Comment by stamblerre** [comment]
Do you see "gopls" under the list of "Tasks" in the output panel?

**Comment by adk9** [comment]
@stamblerre, Thanks, I see it now.

I was able to get a stacktrace of the crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6a80b6]

goroutine 6 [running]:
golang.org/x/tools/internal/lsp/source.(*IdentifierInfo).Hover(0x0, 0x0, 0x819280, 0xc4200b6120, 0x81a140, 0xc42c5485a0)
	golang.org/x/tools/internal/lsp/source/definition.go:50 +0x76
golang.org/x/tools/internal/lsp.(*server).Hover(0xc420074900, 0x819dc0, 0xc4343e4400, 0xc4343e18c0, 0xc4343e18c0, 0x0, 0x0)
	golang.org/x/tools/internal/lsp/server.go:225 +0x185
golang.org/x/tools/internal/lsp/protocol.serverHandler.func1(0x819dc0, 0xc4343e4400, 0xc4200e53b0, 0xc4343e1880)
	golang.org/x/tools/internal/lsp/protocol/server.go:211 +0xd6d
golang.org/x/tools/internal/jsonrpc2.(*Conn).run(0xc4200e53b0, 0x819e00, 0xc420012170, 0xc420045fc8, 0x5f54e3)
	golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:327 +0x5d3
golang.org/x/tools/internal/jsonrpc2.NewConn.func4(0xc4200e53b0, 0x819e00, 0xc420012170)
	golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:107 +0x3f
created by golang.org/x/tools/internal/jsonrpc2.NewConn
	golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:106 +0x329
```

Let me know if you want me to create a new issue.

**Comment by stamblerre** [comment]
@adk9: what version of gopls are you currently using? There is no longer a `golang.org/x/tools/internal/lsp/source/definition.go` file, so I imagine this bug is likely already resolved. `gopls` moves quite quickly, so it is worth updating the binary regularly.

**Comment by adk9** [comment]
I'm not sure what version I was running but updating/reinstalling Go tools seems to have fixed this and a host of other issues I was seeing.

1. Ctrl-Shift-P
2. Go: Install/Update Tools

Thanks!
