### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rbo54** [Microsoft/vscode-go#2460]
[ms-vscode.Go-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-go/files/3109684/ms-vscode.Go-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.10.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\watsot3\ms-vscode.Go-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by rbo54** [comment]
[ms-vscode.Go-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-go/files/3109687/ms-vscode.Go-unresponsive.cpuprofile.txt)
Attached the requested file.

**Comment by ramya-rao-a** [comment]
- Are you using Go modules?
- Please use the `Developer: Open Process Explorer` to see which process is causing the high cpu usage and share a screen shot if possible
- Also share any Go related settings you have changed

**Comment by rbo54** [comment]
Yes, using go modules. I was able to resolve this issue by loading a different version of go, which forced reload of all the go utilities processes, so I'm no longer blocked. Is there a way to force that reload otherwise? I had not changed in Go settings that I'm aware of. I will reopen if I encounter this again and can get the Process Explorer information you requested. 
Thank you for your help.

**Comment by ramya-rao-a** [comment]
> Is there a way to force that reload otherwise

- Reloading VS Code window, restarts all the tools
- You can use `Go: Install/Update Tools` to re-install the tools
