### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by danclive** [Microsoft/vscode-go#2465]
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.10.0`
- OS Version: `Linux x64 4.15.18-041518-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/danc/ms-vscode.Go-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment]
- Are you using Go modules?
- Can you share any Go related settings you may have?

If using Go modules and the language server, then can you try the steps at https://github.com/Microsoft/vscode-go/issues/2461#issuecomment-486097632 and see if that helps?

**Comment by ramya-rao-a** [comment]
@danclive Can you share what helped your case?
