### ISSUE TITLE
Debug ignoring args (launch.json configurations)

### ISSUE THREAD

**Issue by kylewolfe** [Microsoft/vscode-go#247]
Related to #74 

Currently on Windows, I can test again on Linux tonight.

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "${workspaceRoot}",
			"env": {},
			"args": ["export"]
		}
	]
}
```

First line indicated that it's supposed to be sending my argument, last line is a print of os.Args first thing within main()
```
2016/03/15 13:41:16 debugger.go:61: launching process with args: [./debug export]
2016/03/15 13:41:16 debugger.go:225: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x402374, File:"C:/Users/kylewolfe/projects/go/src/kylewolfe/infa-vc/main.go", Line:28, FunctionName:"main.main", Cond:"", Tracepoint:false, Stacktrace:0, Goroutine:false, Variables:[]string(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2016/03/15 13:41:16 debugger.go:374: continuing
[c:\Users\kylewolfe\projects\go\src\kylewolfe\infa-vc\debug]
```

**Comment by lukehoban** [comment]
It looks like the args aren't being ignored - they are shown in the first line of your output.  

If you are still having issues here, could you share some more details?

**Comment by kylewolfe** [comment]
Please reread my issue before closing it. The first line of output is from vs-code. The last line is from fmt.Println(os.Args). They are not being passed to the executable.

**Comment by kylewolfe** [comment]
@lukehoban, please see last comment.

**Comment by lukehoban** [comment]
Got it - I'll need to look into this again. I suspect https://github.com/derekparker/delve/pull/478 may be related.

**Comment by lukehoban** [comment]
Yes - this appears to be because of the lack of arguments support in Delve on Windows, which is being tracked in https://github.com/derekparker/delve/pull/478.  Once that is merged, this should work in VS Code.
