### ISSUE TITLE
Autoimport not working

### ISSUE THREAD

**Issue by asdine** [Microsoft/vscode-go#2473]
Since version 0.10.0 (0.10.1 included), autoimport doesn't work anymore.
This happens in a regular GOPATH as well as using go modules.

I am using Visual Studio Code Version: 1.33.1 on Ubuntu 18.04.2 LTS.
I have selected `goimports` in the settings, but it doesn't work with `goreturn` either

**Comment by tj** [comment]
ditto, auto-import and auto-complete for unimported packages fail for me

**Comment by tj** [comment]
actually formatting on save is broken now as well

**Comment by huguesalary** [comment]
Both of those work for me when the `gopls` language server is disabled

**Comment by csprl** [comment]
Yeah, it looks like it's related to gopls. Disabling it (Settings -> Use Language Server) solved it for me too.

**Comment by arbent** [comment]
try del "go.useLanguageServer" and reload goimports

**Comment by huguesalary** [comment]
Looking into the vs-code source, and at the settings sections here's what I gathered:

1- When using the language server (`gopls`), the format tools are disabled:

![image](https://user-images.githubusercontent.com/755890/56755804-30c2fc00-6745-11e9-9141-5313458093e9.png)

So, it makes sense that `goimports` won't work.

2- Now, enabling the language server isn't sufficient. It needs to be configured, and that part is not easily found in the documentation.

You need to make sure to use this configuration(from https://github.com/golang/go/wiki/gopls#editors-instructions) to get the auto-import feature back:

```json
"go.useLanguageServer": true,
"go.languageServerExperimentalFeatures": {
        "diagnostics": true // for diagnostics as you type
},
"[go]": {
    "editor.snippetSuggestions": "none",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
},
"gopls": {
    "usePlaceholders": true, // add parameter placeholders when completing a function
    "enhancedHover": true,   // experimental to improve quality of hover (will be on by default soon)
}
```

Now, unfortunately, on my end, using this configuration restores the import feature, but it breaks the autocompletetion, as seen here:

![image](https://user-images.githubusercontent.com/755890/56756056-c65e8b80-6745-11e9-9688-b940df9a7533.png)

**Comment by stamblerre** [comment]
For the goimports/gofmt behavior, you need to configure this setting:

```json5
"[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
}
```

**Comment by stamblerre** [comment]
@huguesalary: imports should not be related to autocompletion. Does autocompletion work when you turn off the setting?

**Comment by huguesalary** [comment]
@stamblerre The auto completion broke when I enabled the language server, but, disabling the language server did not bring back the auto-completion. Meanwhile, the reformatting also broke.

I'm totally unclear about what is going on.

**Comment by stamblerre** [comment]
Can you confirm that the language server is running? Go to "View: Debug Console" -> "Output" tab -> "Tasks" drop down, and check that there is an item titled `gopls`. You should be able to see more debug information there. Remember that you have to reload VSCode every time you change language server settings.

**Comment by huguesalary** [comment]
I figured it out.

The language server was correctly running. 

The issue was that the autoimport feature imported `github.com/Sirupsen/logrus` (note the capital `S`). This import in turn was breaking, all the `go` tools with an error `go: github.com/Sirupsen/logrus@v1.4.1: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"`

This error was completely invisible as far as `vscode` is concerned. It simply was breaking, but not showing any information, not even in the debug console.

Fixing this import fixed my issue.

**Comment by stamblerre** [comment]
Glad you were able to resolve your issue, and I'm sorry the errors weren't showing up. We're going to try and do a better job of showing errors to the user - you can track this on https://github.com/golang/go/issues/31668.

**Comment by huguesalary** [comment]
Oh, I don't think the error reporting issue is a `gopls` one. I _did_ get `gopls` errors in the console:

```
cacheAndDiagnose: publishing diagnostics
[Error - 11:01:26 AM] Request textDocument/documentSymbol failed.
  Message: no file information for file:///Users/hugues/Documents/bbctl/pkg/cmd/helpers.go
  Code: 0 
```
The issue, I think, was `vscode` not showing me at any moment the other error (and cause of everything else):

`go: github.com/Sirupsen/logrus@v1.4.1: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"`

**Comment by Hawken94** [comment]
#2469 this issue has an solution.

### jellevandenhooff said, 
>This happens to me both go.useLanguageServer and without. It started happening recently. It make autocompleteUnimportedPackages impossible to use. Reverting to 0.9.2 makes the problem disappear.

**Comment by ramya-rao-a** [comment]
So to summarize,

- When using `gopls`, adding of missing imports or removal of unused imports don't work on file save until the setting regarding `source.organizeImports` is added. 
    - I have updated our [README](https://github.com/Microsoft/vscode-go/tree/5b40cfbf22cfb8e4e82dec4140c5bb5ac23c599a#settings-to-control-the-use-of-the-go-language-server) regarding this
- Auto import of unimported packages do not work anymore on auto-completion.
   - This is being tracked in #2469. Please see the comment https://github.com/Microsoft/vscode-go/issues/2469#issuecomment-487788624 for the fix
- Importing of a wrong package broke all features of `gopls`
   - @huguesalary At this point, did VS Code show any error at all?
   - @stamblerre This is a situation where the language server fails to provide any feature I guess. We will need to think of the best way to notify users about this. I believe the middleware is where we can add something to check for rejected promise from the language service and then do something appropriate. Thoughts?

**Comment by huguesalary** [comment]
@ramya-rao-a the only visible error was in the `output` tab of vscode, under the `gopls` selector.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/755890/56937020-808c2500-6aaf-11e9-8412-05e89de26cf3.png">

And the error was:

```
cacheAndDiagnose: publishing diagnostics
[Error - 11:01:26 AM] Request textDocument/documentSymbol failed.
  Message: no file information for file:///Users/hugues/Documents/bbctl/pkg/cmd/helpers.go
  Code: 0 
```

**Comment by zephinzer** [comment]
Same problem, switched back to 0.9.2 and it started working again

**Comment by stamblerre** [comment]
@huguesalary and @zephinzer: do you mind each filing issues in https://github.com/golang/go/issues? I can help you debug it there.

**Comment by ramya-rao-a** [comment]
In the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension,
- The `source.organizeImports` code action is enabled by default for Go files. So, no setting needs to be added to get missing imports or remove unused imports on file save when using `gopls`
- Auto-import during auto-completion should be fixed as well.

If anyone is seeing issues after enabling `gopls`, please log a new issue at https://github.com/golang/go/issues, share any Go related settings you have and the logs from `View` -> `Output` -> `gopls`

Closing this issue as most of the concerns have been addressed. Please log new issues for the rest

**Comment by ramya-rao-a** [comment]
The fix to make the setting in https://github.com/Microsoft/vscode-go/issues/2473#issuecomment-486773935 a default so that users don't have to set them has been released in the latest update (0.10.2)

**Comment by fastreles** [comment]
I have seen this issue repeatedly, since the functionality was first introduced. It comes and goes over time (on both Mac and Windows). Sometimes it works with `goimports` but not `goreturns`, and sometimes it doesn't. I used to try debugging it, but after the Nth time, I just gave up and accepted that it's faster and less stressful not to worry about it and type the imports I need.

**Comment by ramya-rao-a** [comment]
@fastreles The latest `goimports` definitely works well with modules. `goreturns` does not. This is a known issue and https://github.com/golang/go/issues/24661 is tracking the work to get module support for various tools.

The language server `gopls` also works well in adding missing imports, removing unused imports on file save. If you don't see that happening, please log an issue at https://github.com/golang/go/issues. We can use all the feedback we can get to keep improving the language server
