### ISSUE TITLE
gopls: no autoimport, no autocomplete, no hover docs

### ISSUE THREAD

**Issue by bitfield** [Microsoft/vscode-go#2476]
Code Version 1.33.1 (1.33.1),
vscode-go 0.10.0

Steps to reproduce:

1. Create a main.go file.
2. Enter this code:

```go
package main

func main() {
	os.Exit(1)
}
```

3. Save

I would expect to see an automatic `import "os"` added, but it is not.

If I add it manually, I would expect to be able to hover over the `os.Exit` and see pop-up information about the function. I do not.

If I delete the `Exit(1)`, place the cursor after `os.` and hit Ctrl-Space, I expect to see an auto-complete menu showing the available functions in os. Instead I see only the identifiers in the current file (func, import, main, and so on).

Settings as here: https://github.com/golang/go/wiki/gopls

`gopls` is running, as shown in the process list.

**Comment by detailyang** [comment]
same here 0.10.1 :(

**Comment by bitfield** [comment]
To be honest, this support was intermittent and mostly not working before `gopls`, at least outside of GOPATH. To my knowledge the external tools used by vscode-go like `goimports`, `go-guru` and so on still do not fully support Go modules. It's hard to believe that `gopls` doesn't, though!

**Comment by detailyang** [comment]
Try the config and update the gopls `go get -u golang.org/x/tools/cmd/gopls` as the below:
````golang
"go.useLanguageServer": true,
"go.languageServerExperimentalFeatures": {
        "diagnostics": true // for diagnostics as you type
},
"[go]": {
    "editor.snippetSuggestions": "none",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
},
"gopls": {
    "usePlaceholders": true, // add parameter placeholders when completing a function
    "enhancedHover": true,   // experimental to improve quality of hover (will be on by default soon)
}

````

**Comment by stamblerre** [comment]
Please let me know if you encounter more issues while using that config.
For the record, both `goimports` and `gopls` do support modules.

**Comment by bitfield** [comment]
Upgrading to the latest `gopls` fixed the problem!

What version of `gopls` does `vscode-go` install? Is it just always the latest available? Perhaps I was unlucky enough to update `vscode-go` at a moment when the latest `gopls` was broken.

**Comment by bitfield** [comment]
Hmm, scratch that: it works in some windows, not others. Reloading the window doesn't make any difference.

**Comment by bitfield** [comment]
Specifically, it does not work if a `go.mod` file is present in the package.

1. Create a new directory
2. Create a `main.go` file containing the test code.
3. Save the file. `import "os"` will be auto-added.
4. Delete the `import "os"` line.
5. Run `go mod init tmp`.
6. Save the file. No auto-imports will be added, no formatting happens, hover and autocomplete no longer work.

**Comment by stamblerre** [comment]
`gopls` does work with modules, but perhaps you encountered an issue that we haven't yet seen. Please file an issue [here](https://github.com/golang/go/issues) with some additional information, such as the contents of the file you are testing with.

**Comment by bitfield** [comment]
Thanks @stamblerre, done!

**Comment by divmgl** [comment]
I'm having this problem still. No autocomplete at all with `gopls`. I'm on version 1.12 and I'm using `go.mod` in most of my project files. This was working previously with `go-langserver` I believe.

**Comment by bitfield** [comment]
@divmgl hop over to https://github.com/golang/go/issues/31712 😄

**Comment by gdoctor** [comment]
I enabled gopls.. and quite literally nothing works. Not a single feature of vscode-go. I don't know what else to say.

**Comment by stamblerre** [comment]
@gdoctor: thanks for the update - please file an issue [here](https://github.com/golang/go/issues) if you see anything else.
