### ISSUE TITLE
It seems that the integration with gopls stops working if there is a custom build tag

### ISSUE THREAD

**Issue by wtask** [Microsoft/vscode-go#2477]
I have intergration test. First line is:
// +build integration

All features (autocomplete, hovers, ...) of vscode-go 0.10.1 are working until suddenly moment, after which I only have stay with syntax highlighting without any other Go support.

I use modules and gopls. 
When I try to get hover tooltip for standard function, gopls reports error like this (part of file path is hidden with '...'):

```
Request textDocument/definition failed.
  Message: no file information for file:///c:/dev/go/src/github.com/.../mysql/mysql_test.go
  Code: 0 
```

But when I removed build tag and save file, extension is became alive and started to work as usual...

**Comment by stamblerre** [comment]
This is a known issue that we are working on handling: https://github.com/golang/go/issues/29202.

**Comment by ramya-rao-a** [comment]
Thanks for the link @stamblerre
