### ISSUE TITLE
Completions show package names when they shouldn't

### ISSUE THREAD

**Issue by Divni** [Microsoft/vscode-go#2478]
Steps to Reproduce:

1. Start typing `os.Rena`
2. See the following:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/34585078/56831689-ba52f680-6837-11e9-97fd-07af2adf8fc4.png">

It should not be showing me package names when my caret is positioned after the dot.

If I press ESC and continue typing the completions show up as expected:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/34585078/56831717-d3f43e00-6837-11e9-9fe5-a3e73ef2ea28.png">

**Comment by rusenask** [comment]
I have started noticing this as well, most of the time those random suggestions are in the top for me so I actually have to scroll up and down to find something meaningful :D

**Comment by lixiangzhong** [comment]
this issue also bothers me.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Divni, @rusenask and @lixiangzhong 

This is coming from the "auto complete unimported packages" feature. Until we have a fix for this, one workaround is to stop packages from appearing in suggestions entirely by disabling the setting `go.autocompleteUnimportedPackages` in your settings.

To fix this issue though, we need to pre-empt this feature when there is a `.` in the word preceeding the cursor

PRs are most welcome to fix this bug
Code pointers:
- [Build and Debug extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- File where the fix should be made: `goSuggest.ts`
- Function in the above file that provides these completions: `getPackageCompletions`
- Fix is to update `includeUnimportedPackages` variable at https://github.com/Microsoft/vscode-go/blob/0.10.1/src/goSuggest.ts#L144 to be `false` when there is a `.` preceeding the current word

**Comment by ramya-rao-a** [comment]
@Divni, @rusenask and @lixiangzhong The same issue is being tracked in #2469. I have pushed a fix for the same. Please try the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension which has the fix for this and let me know how it goes.

**Comment by imkos** [comment]
I tried this version (0.10.2-beta.1) and it seems that the recovery is as good as the 0.9.2 version.

**Comment by Naatan** [comment]
@ramya-rao-a thank you! That resolved the issue for me.

**Comment by Divni** [comment]
@ramya-rao-a That fixed it, thanks!
