### ISSUE TITLE
Configuration descriptions need localization

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-go#248]
[Descriptions in `package.json`](https://github.com/Microsoft/vscode-go/blob/master/package.json#L204) need localization.

Here's how it shows in vscode https://cloud.githubusercontent.com/assets/17735796/13794845/50d1049c-eabb-11e5-9b0e-a019fb93c92d.png

**Comment by lukehoban** [comment]
@isidon Do you have a pointer to documentation on how to do this localization?  I can see examples like https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.nls.json for built-in extensions, but I'm unclear on how the localized text is bundled with extensions that ship separately.

**Comment by isidorn** [comment]
@dbaeumer and @weinand would be best to answer this

**Comment by weinand** [comment]
@lukehoban As far as I know, translation is not (yet) required or planned for extensions not bundled with VS Code.

**Comment by lukehoban** [comment]
Right - that makes sense.  I'll close this then for now.
