### ISSUE TITLE
Unable to eval expression when debugging

### ISSUE THREAD

**Issue by DevopsDood** [microsoft/vscode-go#2485]
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic snap
```

Steps to Reproduce:

1. 
```
package main

import (
	"fmt"
	"strings"
)

func WordCount(s string) map[string]int {
	m := make(map[string]int)
	a := strings.Fields(s)
	for _, v := range a {
		m[v]++
	}
	return m
}

func main() {
	m := WordCount("some some-words some words")
	fmt.Println(m)
}

```
2. Add breakpoint in the for loop and attempt to add your own value to m in the debug console

![screenshot67](https://user-images.githubusercontent.com/46793942/57055964-f6c98c80-6c53-11e9-82b2-82389f4fa201.png)

**Comment by lggomez** [comment]
@DevopsDood the += expression is not supported by delve: https://github.com/go-delve/delve/blob/master/Documentation/cli/expr.md

As you will see, the expression support is quite limite to only a subset of accessors and language features, so these are not issues on the extension side

Although, I can vouch for improving the Eval exception handling so these errors get more user friendly
