### ISSUE TITLE
gopath from `go env` not used when using snap

### ISSUE THREAD

**Issue by galgalesh** [microsoft/vscode-go#2486]
# Steps to Reproduce:

1. Install `go` from snap on Ubuntu 19.04
2. Install `code` from snap on Ubuntu 19.04
3. Start project with go code
4. Use one of the go-specific functions such as "find all references"

# What happens

VSCode asks you if you want to install the required tool. If you click install, it will fail with the message "Cannot install Go tools. Set either go.gopath or go.toolsGopath in settings."

# What I expect to happen

Go gets gopath from the `go env` command as explained in https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension

> Out of the box, the extension uses the value of the environment variable GOPATH. From Go 1.8 onwards, if no such environment variable is set, then **the default GOPATH as deciphered from the command go env is used.**

# Workaround

Setting go.gopath manually to the value displayed by `go env` fixes the issue.

# info

```console
$ go version
go version go1.12.2 linux/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/merlijn/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/merlijn/go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/3584"
GOTMPDIR=""
GOTOOLDIR="/snap/go/3584/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build715249666=/tmp/go-build -gno-record-gcc-switches"
$ code --version
1.33.1
51b0b28134d51361cf996d2f0a1c698247aeabd8
x64
```

Go extension version: 0.10.2

**Comment by ramya-rao-a** [comment]
@galgalesh On my Windows machine, the Go extension is able to pick up the GOPATH as it appears in `go env GOPATH`. I ensured that I didnt have GOPATH set as environment variable and I turned off the `go.inferGopath` setting that I usually have enabled.

Please run the command `Go: Current GOPATH` with and without the `go.gopath` setting that you have set. What does it say when you don't have the go.gopath setting set?

This could be specific to your setup, do you mind setting up a local environment for this extension and debugging the method that determines the GOPATH?
- [Build and Debug this extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- Add breakpoints at https://github.com/Microsoft/vscode-go/blob/0.10.2/src/goInstallTools.ts#L416 and https://github.com/Microsoft/vscode-go/blob/0.10.2/src/goInstallTools.ts#L431

Thats where we run `go env GOPATH` to determine the GOPATH, if it is not already available as an environment variable

**Comment by galgalesh** [comment]
* With `go.gopath` set: `/home/merlijn/go is the current GOPATH.`
* Without `go.gopath` set: `undefined is the current GOPATH.`

## debugging

Debugging the issue showed something weird.

No env variable

![image](https://user-images.githubusercontent.com/1492981/57213332-c03e9980-6fe6-11e9-8c2a-c2dafea176f7.png)

Getting go from `go env` succeeds

![image](https://user-images.githubusercontent.com/1492981/57213489-4529b300-6fe7-11e9-82ed-2a3f825da671.png)

But vscode still shows gopath is undefined.

![image](https://user-images.githubusercontent.com/1492981/57214533-8f606380-6fea-11e9-8e90-4975c7b80635.png)

If I try running `Go: Current GOPATH` again, it shows the correct value.

![image](https://user-images.githubusercontent.com/1492981/57214249-b79b9280-6fe9-11e9-8212-c7f303c69555.png)

Trying this test a bunch of times shows that, after a restart of vscode, `Go: Current GOPATH` will sometimes return `undefined` on the first execution. The second execution seems to always show the correct value.

Also, **if I continue the debugger using "step over" after line 431, instead of clicking "continue", `Go: Current GOPATH` shows the correct value!** So I assume there is a timing/async issue here.

**Comment by ramya-rao-a** [comment]
Those are interesting findings, lets dig in a little more.

https://github.com/microsoft/vscode-go/blob/0.10.2/src/goMain.ts#L328 is the code that runs when you run the command `Go: Current GOPATH`. Can you add a breakpoint there as well and see which breakpoint gets hit first?

**Comment by galgalesh** [comment]
The flow goes like this:

1. https://github.com/Microsoft/vscode-go/blob/0.10.2/src/goInstallTools.ts#L416
2. https://github.com/microsoft/vscode-go/blob/0.10.2/src/goMain.ts#L328
3. https://github.com/Microsoft/vscode-go/blob/0.10.2/src/goInstallTools.ts#L431

**Comment by ramya-rao-a** [comment]
And do you see the same flow when you run the `Go: Current GOPATH` command after opening a Go file?

**Comment by gartnera** [comment]
Can we reopen this? It's happening to me too under the same conditions (Ubuntu 19.04) with both vscode and go installed via snap?

I suspect it's something to do with snap confinement. After setting `go.gopath`, the analysis tools fail to install automatically inside vscode. I can manually `go get` them from my terminal.

**Comment by ramya-rao-a** [comment]
@gartnera Can you follow the steps that @galgalesh went through above and share your findings as well? I believe this is particular to snap as well, but I don't have the the right environment to get a repro.

But I can help figure out the root cause if you are willing to look into the source code like @galgalesh did above
