### ISSUE TITLE
Tabsize being forced to 8 as of version 0.10.2-beta.2

### ISSUE THREAD

**Issue by Divni** [microsoft/vscode-go#2489]
I updated to the beta to get around the auto completion issue, but now my tabsize is being forced to 8 on all Go files. Verified that downgrading to an older version solves the problem.

**Comment by ramya-rao-a** [comment]
That change went in as part of 0.10.2-beta.1 and got reverted in 0.10.2-beta.2

Can you try the latest stable 0.10.2 ?

**Comment by ramya-rao-a** [comment]
I believe this has been fixed in 0.10.2
Please feel free to re-open the issue if thats not the case
