### ISSUE TITLE
gb support

### ISSUE THREAD

**Issue by anidotnet** [Microsoft/vscode-go#249]
This extension is great for go development, but it would be better if we have built in support for gb tool. Recently more and more projects are using gb for building and vendor management. Can we expect the same for near future?

**Comment by c3mb0** [comment]
If you go to File -> Preferences -> Workplace Settings, you can override the GOPATH for the current project. Thus, you can configure your GOPATH on a project basis. A typical gb project is as follows:

/myGbProject
  /src
  /vendor
    /src

If you set your GOPATH to "/full/path/to/myGbProject:/full/path/to/myGbProject/vendor" and reload VS Code, everything starts working swimmingly. :)

PS: Don't use tilde in the path.

**Comment by lukehoban** [comment]
Thanks @c3mb0.  I don't use Gb myself, but that definitely sounds like it should work.

Note also that as of https://github.com/Microsoft/vscode-go/pull/261, which was merged today, you can configure this even more simply in your `.vscode/settings.json` in your `myGbProject` folder:

```json
{
  "go.gopath": "${workspaceRoot}:${workspaceRoot}/vendor"
}
```

@anidotnet Please reopen if you see problems even after configuring your per-project GOPATH.

**Comment by winduptoy** [comment]
@lukehoban How does one specify to build with the `gb` tool instead of the standard `go build`?
