### ISSUE TITLE
Please make custom types themeable

### ISSUE THREAD

**Issue by joeshaw** [Microsoft/vscode-go#2491]
The various primitive types are assigned TextMate scopes, but custom types are not.  I'd like for all my types to have the same color in my theme.

![image](https://user-images.githubusercontent.com/39916/57156858-11634900-6dad-11e9-87cc-f1938d5b4c9f.png)

In the above screenshot, I would like for `io.Reader` and `*x509.Certificate` to be red like `error`.  Unfortunately, there are no scopes attached to it.

![image](https://user-images.githubusercontent.com/39916/57156904-3788e900-6dad-11e9-8514-23d0cb3827af.png)

**Comment by ramya-rao-a** [comment]
This would require a change to the grammar that is being used.
Once the grammar assigns the right scope, VS Code can color the code appropriately.

VS Code uses the grammar for Go from https://github.com/atom/language-go
Please log a feature request there for this issue.
