### ISSUE TITLE
Pasting on a selection causes entire document to be deleted

### ISSUE THREAD

**Issue by tekmaven** [microsoft/vscode-go#2492]
Steps to Reproduce:

1. Enable experimental langauge server `gopls` with reccomended settings
2. Select a block of text, copy it
3. Select another block of text in the same document, and paste the clipboard

Result:
The entire document is deleted.  The text on the clipboard is added to the document, and the cursor is at `0,0`.  

Output of gopls:
```
didChange: file:///path/to/file.go
[Error - 5:26:35 PM] invalid position for file 
[Error - 5:26:35 PM] invalid position for file 
[Error - 5:26:35 PM] invalid position for file 
[Error - 5:26:36 PM] invalid position for file 
[Error - 5:26:36 PM] Request textDocument/documentSymbol failed.
  Message: no file information for file:///path/to/file.go
  Code: 0 
[Error - 5:26:36 PM] invalid position for file 
[Error - 5:26:36 PM] Request textDocument/documentSymbol failed.
  Message: no file information for file:///path/to/file.go
  Code: 0 
[Error - 5:26:36 PM] invalid position for file 
[Error - 5:26:36 PM] Request textDocument/codeAction failed.
  Message: no file information for file:///path/to/file.go
  Code: 0 
[Error - 5:26:36 PM] invalid position for file 
[Error - 5:26:36 PM] Request textDocument/documentSymbol failed.
  Message: no file information for file:///path/to/file.go
  Code: 0 
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @tekmaven 
Do you see this when the language server is disabled?

**Comment by tekmaven** [comment]
Nope.  It does not happen if I toggle `"go.useLanguageServer": false`.

I'm running VSCode (Version 1.33.1) on OS X, extension version 0.10.2.

This is my config:
```
"go.languageServerExperimentalFeatures": {
        "diagnostics": true,
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function
        "enhancedHover": true, // experimental to improve quality of hover (will be on by default soon)
    },
    "go.toolsGopath": "/Users/rhoffman/.go",
    "go.useLanguageServer": true,
```

**Comment by artisin** [comment]
I ran into the same issue, although, regrettably I don't have the time to invest to fix the issue nonetheless this is what I've ascertained thus far. This behavior problem originates from the language server (`gopls`) and an issue has already been created detailing the same behavior - [the issue in question](https://github.com/golang/go/issues/31854). Until the root issue has been patched and or fixed the good news is there's two "quick/temporary" fixes.

1. The easiest and quickest solution is to change the vscode setting `editor.formatOnPaste` to `false` (or toggle the gui "formatOnPaste" setting).
2. Alternatively, you can rollback `gopls` before this issue was introduced

**Comment by shreyu86** [comment]
I can confirm I see this issue as well. Currently on `0.10.3-beta.1` and `go version go1.12.5 darwin/amd64`

**Comment by tekmaven** [comment]
@artisin thanks for helping! Based on your reccomendation, as a temporary workaround, I've added the following editor setting, which only disables formatOnPaste for go files:

```
"[go]": {
    "editor.formatOnPaste": false
}
```

It may be desirable to edit these wiki pages to suggest this setting:

- https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code
- https://github.com/golang/go/wiki/gopls#editors-instructions

**Comment by stamblerre** [comment]
This should be fixed with the latest version of `gopls`, so it shouldn't be necessary anymore. The range formatting behavior was broken, so we have temporarily disabled it.

**Comment by tekmaven** [comment]
Thanks, I removed that setting, updated `gopls`, and pasting now does not delete my source code.  Thanks!
