### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by abg1964** [microsoft/vscode-go#2494]
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.10.2`
- OS Version: `Linux x64 5.0.0-13-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/bag/ms-vscode.Go-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment]
- Are you using Go modules?
- Can you share any Go related settings you might have added/changed?
- Please run `Developer: Open Process Explorer` to identify which process is consuming high cpu. Share a screenshot of the process explorer here

**Comment by Erdk** [comment]
Have you enabled codelens in VS Code? I saw that its causing very high CPU load, because for each function/structure/interface in file instance of guru was spawned, looking for references of them in the whole project. Putting following lines in settings helped me:

```
"go.enableCodeLens": {
        "references": false,
        "runtest": false
},
```

**Comment by ramya-rao-a** [comment]
Thanks for that note @Erdk, that is the reason we don't enable the references codelens by default.
@abg1964 Please share the details asked for in https://github.com/microsoft/vscode-go/issues/2494#issuecomment-489496746 so that we can better help you
