### ISSUE TITLE
Hitting stop doesn't kill process when webserver is running

### ISSUE THREAD

**Issue by stefanwebb** [microsoft/vscode-go#2495]
My issue is similar to #438, which has been closed but is still a problem for me.

I am running a web server in Go 1.12.4 with Windows 10, Visual Studio Code 1.33.1, and the most recent plugin:

`func main() {

    http.HandleFunc("/", handler)

    err := http.ListenAndServe("127.0.0.1:8080", nil)
    if err != nil {
        log.Fatal(err)
    }
    os.Exit(0)
}`

When I hit stop it doesn't kill the process `main.exe` and the web server is still running. This only happens for "Start without Debugging" and not "Start Debugging."

It may be related to another issue I have noticed, sometimes clicking "Start without Debugging" doesn't do anything for Python programs, presumably because a previous process is still running

**Comment by ramya-rao-a** [comment]
Thanks for reporting @stefanwebb 
Can you add `"trace": "logs"` to your debug configuration, try the same command again and share the logs? It will show the sequence of steps the debug adapter went through and possible issues
