### ISSUE TITLE
[features request] Add a command to restart language server just like restart a typescript language server 

### ISSUE THREAD

**Issue by shynome** [microsoft/vscode-go#2500]
The same as #2324 

Today I use vscode to develop a golang project , and find I am so in need this features if without it just can kill language server in task manager and wait vscode restart the language server 

the best developer also can't catch various situations, like move a go file to another package the language server can't know how to do and I lose tips , why not give the language server a choice to restart

**Comment by SteelPhase** [comment]
`BaseLanguageClient` exposes a `start()` method, and `LanguageClient` exposes a `stop()` method. I'm assuming a command could use those to restart the underlying language server. Would anyone be willing to confirm that?

**Comment by shynome** [comment]
@SteelPhase  Thanks your help

**Comment by ramya-rao-a** [comment]
The [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the command `Go: Restart Language Server` that can be used to restart the language server. Thanks @SteelPhase!

**Comment by ramya-rao-a** [comment]
The command to restart the language server is now available in the latest update (0.11.0) to this extension. Thanks @SteelPhase!
