### ISSUE TITLE
[Go To Definition] goes to indefinite window

### ISSUE THREAD

**Issue by eaglexiang** [microsoft/vscode-go#2502]
Steps to Reproduce:

1. Open multi files in different sub-windows in code
2. Ctrl + Left_Click go to definition of any function

You would find the jump-opration works in a sub-window. But which window? It seems indefinite or random.

**Comment by ramya-rao-a** [comment]
@eaglexiang Can you provide more details for this issue? A sample code and details on what is opened in each VS Code window will help

Also, when you say "sub-windows" do you refer to different instances of VS Code or different tabs in the same VS Code instance?

**Comment by eaglexiang** [comment]
Sorry I find it's my own fault. Dozens of tabs confused me.
