### ISSUE TITLE
Type unimport package name no suggestion

### ISSUE THREAD

**Issue by monkeyWie** [microsoft/vscode-go#2503]
When I type unimport package name,editor has no suggestions,there was no problem before, until upgraded the latest __gopls__.

### My project is enabled go modules,and vscode setting as below:

```
{
  "go.useLanguageServer": true
}
```

### environment

go version: 1.12.2
vscode-go version: 0.10.2

### Steps to Reproduce:

1. Type unimport package name
2. No suggestions

#### Now:
![image](https://user-images.githubusercontent.com/13160176/57352839-2d922c00-7199-11e9-963f-201a552a600c.png)

#### Before:
![image](https://user-images.githubusercontent.com/13160176/57352885-4ef31800-7199-11e9-989c-0e72f829b475.png)

**Comment by ramya-rao-a** [comment]
You need the setting `go.autocompleteUnimportedPackages` enabled for that feature. Can you try enabling it?

**Comment by monkeyWie** [comment]
@ramya-rao-a 
Thank you for your reply,but still no suggestion.
settings.json:
```
{
  "go.useLanguageServer": true,
  "go.autocompleteUnimportedPackages":true
}
```

**Comment by ramya-rao-a** [comment]
My mistake, yes, this feature is not yet supported for modules. #2484 is tracking the need for the same.
Please subscribe to that issue
