### ISSUE TITLE
`gopls` Autocompletion missing some parameters when inline typing

### ISSUE THREAD

**Issue by wotmshuaisi** [microsoft/vscode-go#2506]
i got code like below:

```go
type Options struct {
	Code string
}

func test(opt Options) error {
	var t = opt.
	var slice = []string{opt.}
}
```
if you type `opt.` outline it works fine

![image](https://user-images.githubusercontent.com/16408269/57496885-cb0b6e00-7307-11e9-855a-407fe61dfbd7.png)

but if you type it inside of `{}` autocompletion won't pop up the parameters from structure 

![image](https://user-images.githubusercontent.com/16408269/57496893-d2cb1280-7307-11e9-959d-dc6aea131919.png)

vscode configuration for golang:

```js
    // go
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": true
    },
    "go.autocompleteUnimportedPackages": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "go.alternateTools": {
        "go-langserver": "gopls"
    },]
```

**Comment by stamblerre** [comment]
There are some cases where `gopls` will fail because of broken code. Filed an upstream bug: https://golang.org/issue/31973.

**Comment by wotmshuaisi** [comment]
> There are some cases where `gopls` will fail because of broken code. Filed an upstream bug: https://golang.org/issue/31973.

i see, thanks for notice, beautiful lady
