### ISSUE TITLE
Docs tool

### ISSUE THREAD

**Issue by ZCY01** [microsoft/vscode-go#2508]
hello, I am confusion about docs tool. 
There will be a docs windows when  I choose a function api, but it do not disappear when I finish the api.
and I enter RETURN three times, it still there.
![alt](https://s2.ax1x.com/2019/05/11/EWOsyQ.gif)

surely, it will disappear if I click mouses, but I am a vimer.

**Comment by ramya-rao-a** [comment]
That feature is called signature help or parameter hints.
It is triggered when you are typing inside the `()` of a function call to show docs on the current parameter you are typing.
You can press the escape key to make it disappear 
If you don't want this feature at all then set `editor.parameterHints.enabled` to `false` in your settings
