### ISSUE TITLE
gometalinter has been depreacated. golangci-lint is the suggested replacement

### ISSUE THREAD

**Issue by mick-io** [microsoft/vscode-go#2509]
Just a reminded to update the documentation.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @mick-io 
PRs are welcome to update the readme

**Comment by mick-io** [comment]
I'll take care of it. Haha.

**Comment by ramya-rao-a** [comment]
Below is the set of next steps
- Remove `gometalinter` from the list of tools that can be installed using the `Go: Install/Update Tools` command. `goInstallTools.ts` file is the one that should be updated for this
- Remove all the tests related to `gometalinter` from go.test.ts file
- Move `gometalinter` to the bottom of the list for the `go.lintTool` setting. This needs to be done in the package.json file
- Remove all `gometalinter` specific steps from the `travis.yml` file

@samanthakem Feel free to pick this up!

Check out the wiki to [set up local dev environment](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) if needed

**Comment by samanthakem** [comment]
Thank you! I will pick this up.

**Comment by ramya-rao-a** [comment]
This has been taken care of with #2726 by @samanthakem 
Thanks @samanthakem!
