### ISSUE TITLE
Fix syntax highlighting

### ISSUE THREAD

**Issue by mick-io** [microsoft/vscode-go#2510]
Syntax highlight on Go source files is poor.
Left: Sublime Text 3
Right: Visual Studio Code (stable build)
![Screen Shot 2019-05-13 at 14 56 31](https://user-images.githubusercontent.com/23181878/57653641-d4bffa80-75c1-11e9-9b6e-26f6da16f2c8.png)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @mick-io 
Unfortunately, there is not much this extension can do in this matter.

VS Code (the editor, not this extension) uses the grammar from https://github.com/atom/language-go. the different themes can only add color to differently identified scopes which are done using the grammar.

I would suggest to log an issue in https://github.com/atom/language-go with specific code samples.
