### ISSUE TITLE
[Go to definition] is too slow

### ISSUE THREAD

**Issue by erifan** [microsoft/vscode-go#2511]
Go to definition is too slow, it takes about 2 to 3 seconds, this is simply unbearable.. All of the go tools are installed and works fine. So is some of my configurations wrong?

VSCode Info:
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

vscode-go version `0.10.2`

vscode-go settings.json:
```
{
    "window.zoomLevel": 1,
    "extensions.ignoreRecommendations": true,
    "explorer.confirmDelete": false,
    "editor.fontSize": 17,
    "editor.formatOnSave": true,
    "go.delveConfig": {
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 64,
            "maxArrayValues": 64,
            "maxStructFields": -1
        },
        "apiVersion": 2,
        "showGlobalVariables": true
    },
    "workbench.activityBar.visible": true,
    "editor.renderControlCharacters": false,
    "go.buildOnSave": "off",
    "go.useLanguageServer": false,
    "go.vetOnSave": "off"
}
```

**Comment by ramya-rao-a** [comment]
Are you seeing this slow behavior only when using Go modules or event projects that don't use Go modules?

The [new language server](https://github.com/microsoft/vscode-go#go-language-server) `gopls` from Google is known to perform better, especially when using Go modules. Please give that a try

**Comment by erifan** [comment]
Hi @ramya-rao-a , this is the only case when using Go modules, when the project doesn't use Go modules, it's  much faster. I'll try gopls, thanks.

**Comment by erifan** [comment]
When use Language server, "go to definition" fails to work.

**Comment by stamblerre** [comment]
@erifan: Are your `gopls` settings configured according to https://github.com/golang/go/wiki/gopls? Can you share the output logs that can be found by going to "View: Debug Console" -> "Output" -> "Tasks" -> "gopls"?

**Comment by erifan** [comment]
Yes. My configurations:
```
{
    "window.zoomLevel": 1,
    "extensions.ignoreRecommendations": true,
    "explorer.confirmDelete": false,
    "editor.fontSize": 17,
    "editor.formatOnSave": true,
    "go.delveConfig": {
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 64,
            "maxArrayValues": 64,
            "maxStructFields": -1
        },
        "apiVersion": 2,
        "showGlobalVariables": true,
    },
    "workbench.activityBar.visible": true,
    "editor.renderControlCharacters": false,
    "go.buildOnSave": "off",
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        // "format": true,
        // "autoComplete": true,
        // "rename": true,
        // "goToDefinition": true,
        // "hover": true,
        // "signatureHelp": true,
        // "goToTypeDefinition": true,
        // "goToImplementation": true,
        // "documentSymbols": true,
        // "workspaceSymbols": true,
        // "findReferences": true,
        "diagnostics": true,
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function
        "enhancedHover": true, // experimental to improve quality of hover (will be on by default soon)    
    },
    "go.vetOnSave": "off",
    "window.title": "${dirty}${activeEditorLong}${separator}${rootName}${separator}${appName}"
}
```

The output logs :
```
[Info  - 11:44:49 AM] #### Build info

no module information, gopls not build with go 1.11 or earlier


#### Go info

go version devel +3080b7d Mon May 14 00:20:16 2018 +0000 windows/amd64

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\hostname\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\hostname\OneDrive\Desktop\goPath
set GORACE=
set GOROOT=C:\Users\hostname\OneDrive\Desktop\go
set GOTMPDIR=
set GOTOOLDIR=C:\Users\hostname\OneDrive\Desktop\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\hostname\AppData\Local\Temp\go-build461325270=/tmp/go-build -gno-record-gcc-switches

[Error - 11:44:49 AM] Request textDocument/documentLink failed.
  Message: no file information for file:///c:/Users/hostname/OneDrive -/Desktop/golang/src/cmd/compile/main.go
  Code: 0 
```

**Comment by stamblerre** [comment]
My guess is that it's not working because it looks like you are opening files in the Go project that are located outside of your `$GOROOT`. Can you try it with a project that uses modules?

**Comment by erifan** [comment]
It's ok on projects use modules. I'm not sure if the Go project uses modules although there's a go.mod file in go/src/, but it indeed doesn't work when using languageserver. And when I don't use languageserver, "Go to definition" is too slow. Is there any good advice for this problem? Thanks.

**Comment by stamblerre** [comment]
I think that this only happens if you clone the Go project into a second place outside of your `$GOROOT`. Filed https://golang.org/issue/32173.

**Comment by ramya-rao-a** [comment]
@erifan Is your issue only when using Go to definition on symbols from the standard library?

**Comment by erifan** [comment]
No, the issue occurs when Go to definition to any symbols. Of course I didn't test all the symbols, I tried some Go API functions and some internal functions, neither worked. It's easy to reproduce, just download the Go project and open it in vscode.

**Comment by stamblerre** [comment]
I was using the term "standard library" interchangeably with "Go project", so I think the upstream issue I filed should be enough to track this.

**Comment by erifan** [comment]
@stamblerre Thanks.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

Closing this issue in favor of the upstream issue

@erifan Please subscribe to the upstream issue. Once it is fixed, update your version of the language server
