### ISSUE TITLE
Remote debug is super slow to get variables

### ISSUE THREAD

**Issue by ericshen881027** [microsoft/vscode-go#2512]
```
VS Code version: 1.33.1
Go Extension version: 0.10.2
OS version: Windows_NT x64 10.0.17763
dlv in remote server: 1.2.0
Remote server OS version: CentOS Linux release 7.6.1810
```

debug setting:
```
{
            "name": "Remote",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "remotePath": "/root/go/src/test-remote-debug",
            "port": 2345,
            "host": "10.142.113.181",
            "program": "C:/Users/EricS/go/src/test/test-remote-debug",
            "env": {}
}
```

Steps to Reproduce:

1. set a breakpoint in the local code
2. start the remote dlv server
3. start debug in local machine
4. check the variables in local machine

You have to wait a long time to get parts of variables, the others seem like will never show up. But in Goland it works ok.

**Comment by SteelPhase** [comment]
I'm running into this as well, and the remote dlv server is local to my machine running on 127.0.0.1

**Comment by ramya-rao-a** [comment]
> You have to wait a long time to get parts of variables, the others seem like will never show up

Can you elaborate on how are you checking the variables?
Are you referring to the variables pane, the watch pane or the debug console?

**Comment by SteelPhase** [comment]
I was seeing this behavior in the variables pane. Not sure about the OP.

**Comment by hyangah** [comment]
Without the exact repro case, it's hard to investigate exactly what caused slowness or how 'slow' it was. But we understand the go debug adapter is chatty and needs improvement.
(e.g. https://github.com/golang/vscode-go/issues/139, https://github.com/golang/vscode-go/issues/138). 

I hope [the current work to utilize delve's native DAP implementation](https://github.com/golang/vscode-go/issues/23) to address the efficiency issues.  

As we are moving to a new repo and we do not have enough info for investigation, I am closing this issue. Please file a new issue in the new repo https://github.com/golang/vscode-go. It would be great if the report includes:

* the version of extension, delve version (`dlv version`).
* debug trace: https://github.com/golang/vscode-go/blob/master/docs/debugging.md#enabling-debug-logs
* repro case if possible
