### ISSUE TITLE
Ctrl-V replaces all content of file

### ISSUE THREAD

**Issue by slayer** [microsoft/vscode-go#2513]
Hi

I have a problem with `Ctrl-V` - it replaces all content of file with buffer's content

Steps to Reproduce:

1. Install VSCode Go extension
2. Open any .go file
3. Select line, copy it to clipboard (`Ctrl-C`)
4. Paste (`Ctrl-V`)
![out](https://user-images.githubusercontent.com/57521/57708465-101a0200-7672-11e9-86fd-8d9cb618b1af.gif)

How to fix: uninstall vscode-go

**Comment by toqueteos** [comment]
Duplicate of #2492

**Comment by slayer** [comment]
Close as duplicate
