### ISSUE TITLE
sqs/goreturns won't install

### ISSUE THREAD

**Issue by quanglewangle** [microsoft/vscode-go#2516]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1.
2.

**Comment by quanglewangle** [comment]
Installing 1 tool at /home/peter/go/bin
  goreturns

Installing github.com/sqs/goreturns FAILED

1 tools failed to install.

goreturns:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/sqs/goreturns
github.com/sqs/goreturns (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/packages?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/packages?go-get=1 (status code 200)
get "golang.org/x/tools/go/packages": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/packages?go-get=1
get "golang.org/x/tools/go/packages": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcexportdata?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcexportdata": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcexportdata?go-get=1
get "golang.org/x/tools/go/gcexportdata": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/internal/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/internal/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/internal/gcimporter": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/internal/gcimporter?go-get=1
get "golang.org/x/tools/go/internal/gcimporter": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/internal/packagesdriver?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/internal/packagesdriver?go-get=1 (status code 200)
get "golang.org/x/tools/go/internal/packagesdriver": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/internal/packagesdriver?go-get=1
get "golang.org/x/tools/go/internal/packagesdriver": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/internal/gopathwalk?go-get=1
Parsing meta tags from https://golang.org/x/tools/internal/gopathwalk?go-get=1 (status code 200)
get "golang.org/x/tools/internal/gopathwalk": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/internal/gopathwalk?go-get=1
get "golang.org/x/tools/internal/gopathwalk": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/internal/fastwalk?go-get=1
Parsing meta tags from https://golang.org/x/tools/internal/fastwalk?go-get=1 (status code 200)
get "golang.org/x/tools/internal/fastwalk": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/internal/fastwalk?go-get=1
get "golang.org/x/tools/internal/fastwalk": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/internal/semver?go-get=1
Parsing meta tags from https://golang.org/x/tools/internal/semver?go-get=1 (status code 200)
get "golang.org/x/tools/internal/semver": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/internal/semver?go-get=1
get "golang.org/x/tools/internal/semver": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/internal/module?go-get=1
Parsing meta tags from https://golang.org/x/tools/internal/module?go-get=1 (status code 200)
get "golang.org/x/tools/internal/module": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/internal/module?go-get=1
get "golang.org/x/tools/internal/module": verifying non-authoritative meta tag
golang.org/x/tools/go/internal/gcimporter
# golang.org/x/tools/go/internal/gcimporter
go/src/golang.org/x/tools/go/internal/gcimporter/iimport.go:188:16: undefined: fakeFileSet
github.com/sqs/goreturns (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/packages?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/packages?go-get=1 (status code 200)
get "golang.org/x/tools/go/packages": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/packages?go-get=1
get "golang.org/x/tools/go/packages": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcexportdata?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcexportdata": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcexportdata?go-get=1
get "golang.org/x/tools/go/gcexportdata": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/internal/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/internal/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/internal/gcimporter": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/internal/gcimporter?go-get=1
get "golang.org/x/tools/go/internal/gcimporter": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/internal/packagesdriver?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/internal/packagesdriver?go-get=1 (status code 200)
get "golang.org/x/tools/go/internal/packagesdriver": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/internal/packagesdriver?go-get=1
get "golang.org/x/tools/go/internal/packagesdriver": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/internal/gopathwalk?go-get=1
Parsing meta tags from https://golang.org/x/tools/internal/gopathwalk?go-get=1 (status code 200)
get "golang.org/x/tools/internal/gopathwalk": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/internal/gopathwalk?go-get=1
get "golang.org/x/tools/internal/gopathwalk": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/internal/fastwalk?go-get=1
Parsing meta tags from https://golang.org/x/tools/internal/fastwalk?go-get=1 (status code 200)
get "golang.org/x/tools/internal/fastwalk": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/internal/fastwalk?go-get=1
get "golang.org/x/tools/internal/fastwalk": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/internal/semver?go-get=1
Parsing meta tags from https://golang.org/x/tools/internal/semver?go-get=1 (status code 200)
get "golang.org/x/tools/internal/semver": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/internal/semver?go-get=1
get "golang.org/x/tools/internal/semver": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/internal/module?go-get=1
Parsing meta tags from https://golang.org/x/tools/internal/module?go-get=1 (status code 200)
get "golang.org/x/tools/internal/module": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/internal/module?go-get=1
get "golang.org/x/tools/internal/module": verifying non-authoritative meta tag
golang.org/x/tools/go/internal/gcimporter
# golang.org/x/tools/go/internal/gcimporter
go/src/golang.org/x/tools/go/internal/gcimporter/iimport.go:188:16: undefined: fakeFileSet

**Comment by ramya-rao-a** [comment]
Are you able to install using `go get -u github.com/sqs/goreturns`? If that also returns the same errors, the please log an issue at https://github.com/sqs/goreturns

**Comment by quanglewangle** [comment]
It's solved it I am slightly ashamed that I am not quite sure how I did it. One thing I did notice was that three or four of the files in tool directory did not have execute permission. Once I did chmod +x it all worked.

**Comment by ramya-rao-a** [comment]
No problem at all, Happy Coding!
