### ISSUE TITLE
Changing package names causes LSP to return error

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode-go#2520]
Code Version 1.34.0
VSCode-Go 0.10.2
Go version go1.12.5 darwin/amd64
Gopls commit: b9584148efcb10d08933a70e48b8f7b0732a1b47

Renaming a package will cause an error from LSP to appear `package package2; expected package LSP [1,1]`

Restarting vscode resolves the issue

Steps to Reproduce:

1. create a simple go package
2. save package
3. change package name
4. error should appear

**Comment by ramya-rao-a** [comment]
Restarting VS Code forces a restart of the language server which might explain why things work afterwords.

@SteelPhase Can you share all the Go related settings you might have added/changed?

@ianthehat and @stamblerre, Is this something you would like to have logged against gopls or you expect us to send the language server some kind of indication that the package name as changed?

**Comment by SteelPhase** [comment]
I trimmed down my workspace, and tested this with the settings here [gopls vscode](https://github.com/golang/go/wiki/gopls#vscode)

My settings, and the default settings I'm using below produced this issue. I tried it as a no go-module, and as a go-module outside the GOPATH.

- Only vscode-go extension enabled

settings.json
```json
{
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true // for diagnostics as you type
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function
        "enhancedHover": true, // experimental to improve quality of hover (will be on by default soon)
    }
}
```

**Comment by ianthehat** [comment]
This is just a gopls bug, I have refiled it as an issue in our tracker.

**Comment by SteelPhase** [comment]
@ianthehat is there a better way for me to determine vs-codego/gopls issues. I've been wary about opening these already because I have no great way to tell.

**Comment by ianthehat** [comment]
Not really, the boundaries between gopls and the editor hosts are very complex, and intended to be invisible to the user, which also makes it hard to decide where to file the bug. In general I think you can file a bug in either project and we will try to make sure it goes to the right person, I would err on the side of assuming it is gopls unless you have a reason to think otherwise.

**Comment by ramya-rao-a** [comment]
Looks like the upstream issue is closed.
@SteelPhase Can you ensure you have the latest version of `gopls` and try again?

**Comment by SteelPhase** [comment]
There still appears to be a problem. I have to save, and then do anything(like add a space) before the error goes away. I feel like it doesn't resolve the 'package test; expected api' until after the document is saved. I'm going to guess that vscode has a method of provided the unsaved document/changes to gopls, and the fix doesn't work with that.

**Comment by stamblerre** [comment]
Thanks for the update. Re-opened the issue and will continue investigating.

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of https://github.com/golang/go/issues/32149
Please subscribe to the upstream issue
