### ISSUE TITLE
save (ctrl + s) looses focus in editor, make it go to the start location (line 1 char 1)

### ISSUE THREAD

**Issue by marcelloh** [microsoft/vscode-go#2522]
Steps to Reproduce:

1. edit a big go file
2. Scroll a bit down
3. the package line should not be visible at this point
4. add an extra space or something
5. save
6. press a key (like 'a')
7. now the a is printed in front of the file
8. you now see apackage

The expected behavior is that the cursor is at least somewhere around where I left it,
when I pressed ctrl-s

I work with gopls (so perhaps that is influencing the behaviors)

**Comment by ramya-rao-a** [comment]
> now the a is printed in front of the file

Do you mean at the beginning of the file? Is it on the first line?
Can you share all the Go related settings you might have changed or added
Also share if you are using Go modules or not

**Comment by marcelloh** [comment]
Do you mean at the beginning of the file? Is it on the first line? : yes
(I did mention you now see apackage, and before package was of course the first word...)
Did you actually try this yourself?

Go modules: yes

Go related settings (I don't know what go-vscode uses, so I do them all)
```
\{
	"git.autofetch": true,
	"php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar",
	"php-cs-fixer.lastDownload": 1557307620542,
	"editor.detectIndentation": false,
	"editor.insertSpaces": false,
	"editor.minimap.enabled": false,
	"editor.tabSize": 4,
	"window.zoomLevel": 2,
	"window.menuBarVisibility": "default",
	"[php]": {
		"editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
	},
	"breadcrumbs.enabled": true,
	"git.enableSmartCommit": true,
	"search.exclude": {
		"**/*.html": true,
		"**/vendor": true
	},
	"gitlens.defaultDateFormat": "DD-MM-YY",
	"indenticator.color.dark": "#FF530D",
	"todohighlight.defaultStyle": {
		"backgroundColor": "#101010",
		"borderRadius": "5px",
		"isWholeLine": true,
		"fontStyle": "italic",
		"outlineWidth": "10px",
		"borderSpacing": "50px",
	},
	"todohighlight.keywords": [
		{
			"text": "NOTE:",
			"color": "#b0b0b0",
			"border": "1px solid #a0a0a0",
		},
		{
			"text": "## ",
			"color": "#b0b0b0",
			"border": "1px solid #a0a0a0",
		},
		{
			"text": "### ",
			"color": "#b0b0b0",
			"border": "1px solid #a0a0a0",
		},
		{
			"text": "TODO:",
			"color": "#FF5050",
			"border": "1px solid red",
			"backgroundColor": "#101010",
		},
		{
			"text": "BUG:",
			"color": "#CD853F",
			"border": "1px solid #CD853F",
		},
		{
			"text": "HACK:",
			"color": "#FFA500",
			"border": "1px solid #FFA500",
		},
		{
			"text": "IDEA:",
			"color": "#32CD32",
			"border": "1px solid #32CD32",
		},
		{
			"text": "???:",
			"color": "#FFFF66",
			"border": "1px solid #FFFF66",
		},
	],
	"php-cs-fixer.allowRisky": true,
	"ecs.configPath": "./vscode/easy-coding-standard.yml",
	"ecs.ruleSet": "clean-code",
	"workbench.editor.showTabs": true,
	"terminal.integrated.fontSize": 13,
	"workbench.editor.enablePreviewFromQuickOpen": false,
	"workbench.editor.enablePreview": false,
	"explorer.confirmDragAndDrop": false,
	"explorer.confirmDelete": false,
	"workbench.editor.highlightModifiedTabs": true,
	"multiCommand.commands": [
		{
			"command": "multiCommand.makeRoom",
			"sequence": [
				"workbench.action.toggleSidebarVisibility",
				"workbench.action.toggleActivityBarVisibility"
			]
		}
	],
	"workbench.activityBar.visible": true,
	"go.lintTool": "golangci-lint",
	"go.lintFlags": [
		"--fast"
	],
	"cSpell.enabledLanguageIds": [
		"asciidoc",
		"css",
		"go",
		"handlebars",
		"html",
		"javascript",
		"javascriptreact",
		"json",
		"latex",
		"less",
		"markdown",
		"php",
		"scss",
		"text",
		"typescript",
		"typescriptreact",
		"yml"
	],
	"cSpell.language": ",nl,en",
	"cSpell.userWords": [
		"itereert",
		"repo"
	],
	"workbench.tree.indent": 15,
	"go.useLanguageServer": true,
	"go.languageServerExperimentalFeatures": {
		"diagnostics": true // for diagnostics as you type
	},
	"[go]": {
		"editor.snippetSuggestions": "none",
		"editor.formatOnSave": true,
		"editor.codeActionsOnSave": {
			"source.organizeImports": true
		},
	},
	"gopls": {
		"usePlaceholders": true, // add parameter placeholders when completing a function
		"enhancedHover": true, // experimental to improve quality of hover (will be on by default soon)
	},
	"editor.formatOnSave": true,
	"go.formatTool": "goimports"
}
```

**Comment by daleyshek** [comment]
I have the same problem

**Comment by marcelloh** [comment]
perhaps you can show too what your configuration is, so they can look for similarities

**Comment by stamblerre** [comment]
This is a known issue with `gopls`: https://github.com/golang/go/issues/31937. Current workaround is adding `"files.eol": "\n"` to VSCode settings.

**Comment by daleyshek** [comment]
I've solved this problem by closeing go extension setting Go:Use Language Server.

ctrl+shift+x, on the Go extension right click, chose Configure Extension Settings.

scroll at the bottom of this page, find the Go:Use Language Server, uncheck and then reload.

it is usefull to me. when I turn on Go:Use Language Server, the problem was occurred agian.

May be help.

**Comment by marcelloh** [comment]
I have the ```"files.eol": "\n"``` settings now, but without any luck. Still the first thing typed after a cltr-s comes up as the very first character in the file (so: before package)

**Comment by stamblerre** [comment]
You will have to make sure that the line endings in your file actually changed from LF to CRLF. You also may have a git configuration that automatically changes the line endings. I think you will find that if you create a new file, it will work correctly.

**Comment by marcelloh** [comment]
wait? my line endings have to be CRLF? to fix this bug? so everybody that used CR has this problem?
(That's about 2/3rd of all operating systems.) And if I do that, I can undo it when the bug is solved?
hahahaha, my watch mentions the year, and it's 2019. No way I'm going down that path. In these times, such a bug should be solved before throwing this at us.

**Comment by marcelloh** [comment]
hey Rebecca, I think your explanation is almost correct, but when the file is LF, it seems to work, and when I have a CRLF based file, it jumps to the beginning. (I can fix those, because they are a minority in my files.) So I know what to do to solve it :-) 👍

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of https://github.com/golang/go/issues/31937
Please subscribe to the upstream issue
