### ISSUE TITLE
vs Insiders  linux go gofmt err

### ISSUE THREAD

**Issue by gie777** [microsoft/vscode-go#2529]
vs Insiders  linux go gofmt err
Unable to format code automatically

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/gocode"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build255131723=/tmp/go-build -gno-record-gcc-switches"
```
vs set
```
    "remote.SSH.showLoginTerminal": true,
    "git.ignoreLegacyWarning": true,
    "git.autofetch": false,
    "git.confirmSync": false,
    "workbench.colorTheme": "Monokai ST3",
    "editor.fontSize": 18,
    "go.gocodeAutoBuild": true,
    "go.gopath": "/root/gocode",
    "go.goroot": "/usr/local/go",
    "go.inferGopath": true,
    "go.formatTool": "gofmt",
    "go.gocodeFlags": [
        "-builtin",
        "-ignore-case",
        "-unimported-packages"
    ],
    "go.gotoSymbol.includeGoroot": true,
    "files.autoSave": "off"
          //"go.formatFlags": ["-l -w"],
```

**Comment by jgrigg2017** [comment]
Does it work when you roll back the version to 0.9.2?

**Comment by jgrigg2017** [comment]
I had the same pr similar problem on Linux Mint... gofmt was formatting on save perfectly for months, then just stopped working the other day. After playing around with for a while, I realized that my unit tests had stopped working as well with an error like: ` stdlib.h: No such file or directory`

The fix for me was to run `sudo apt-get install g++`
Now my tests and format on save work properly.

**Comment by gie777** [comment]
> I had the same or similar problem on Linux Mint... gofmt was formatting on save perfectly for months, then it just stopped working the other day. After playing around with it for a while, I realized that my unit tests had stopped working as well with an error like: ` stdlib.h: No such file or directory`
> 
> The fix for me was to run `sudo apt-get install g++`
> Now my tests and formatting on save work properly.

invalid ..........not auto format

**Comment by ramya-rao-a** [comment]
Does manual formatting work? Right-click -> Format Document?

**Comment by gie777** [comment]
No formatter for the "Go" file is currently installed.


Visual Studio Code - Insiders  is err
but Insiders   config
``
    "go.formatTool": "gofmt",
  "go.gopath": "/root/gocode",
    "go.goroot": "/usr/local/go",
``
Visual Studio Code  is success

**Comment by gie777** [comment]
> 手动格式化是否有效？右键单击 - >格式文档？

解决了,linux下区分大小写,
vsgo 默认关联的 "go" 改成GO就要可以了

**Comment by gie777** [comment]
add      "files.associations": {
        "*.go": "go"
    },
