### ISSUE TITLE
documentation: gopls does not support go <= 1.10

### ISSUE THREAD

**Issue by virtuald** [microsoft/vscode-go#2531]
Reference: https://github.com/golang/go/issues/31693

Please update the wiki/settings documentation to note that the language server isn't supported for go <= 1.10.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @virtuald!
Made changes in https://github.com/microsoft/vscode-go/commit/9655d527548b286fee424983378560ce83adf8a2
