### ISSUE TITLE
The gopls server crashed when create new file

### ISSUE THREAD

**Issue by wuchujiecode** [microsoft/vscode-go#2532]
I found a gopls bug. When I need to create a new file.  gopls will be closed.

here is my golang setting

```
   // golang 
    // linters检测
    "go.formatFlags": ["--disable=all"],
    "go.lintFlags": ["--disable=all"],
    // go 自动补全括号
    "go.useCodeSnippetsOnFunctionSuggest":true,
    "go.formatTool": "goreturns",
    // 使用gopls为语言服务器
    "go.useLanguageServer": true,
    "go.alternateTools": {
        "go-langserver": "gopls"
    },
    "go.languageServerFlags": [
        "-rpc.trace",
    ],
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "diagnostics": true
    },
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false
        }
    },
```
1. When I create a new file   xxx.go
2. vscode outline will loading.
3. Because the file is news.  there are nothing.
4. then vscode show me `The gopls server crashed 5 times in the last 3 minutes. The server will not be restarted.`

![WeChatc4627308c03f4d39e8e0f25027b597c3](https://user-images.githubusercontent.com/12055501/58236027-9d490f00-7d74-11e9-82a7-7f78701e3527.png)

![WeChat4ad582faecc0f54f4ad60b4dcf97f7f3](https://user-images.githubusercontent.com/12055501/58235882-522efc00-7d74-11e9-9930-0d5caec9cd03.png)

**Comment by wuchujiecode** [comment]
You can see  request.go  just create and its empty..
Then gopls will be down.

**Comment by stamblerre** [comment]
I am not able to reproduce this error. What version of `gopls` are you using? You can check by running the `gopls version` command.

**Comment by wuchujiecode** [comment]
@stamblerre 
Hmm...I found the proplem.
When I create new file  like main.go
Then vscode outline will loading more then 5 times..but main.go was empty..so more than 5 times later.
`gopls` will be down..

BTW I think vscode outline loading is normal.  But after loading failed. it will be always loading more again. then will be `The gopls server crashed 5 times in the last 3 minutes. The server will not be restarted.`

I am trying make a `.gif`

**Comment by stamblerre** [comment]
Yes, VSCode does try to reload the server a maximum of 5 times if it crashes. However, I am not able to reproduce the crashing behavior with the latest version of `gopls`. Please update your version of `gopls` to the latest version by running `go get -u golang.org/x/tools/cmd/gopls`.

**Comment by wuchujiecode** [comment]
@stamblerre  Thank you!
I updated gopls...fix the problem.
