### ISSUE TITLE
"Go To Definition" not working within module

### ISSUE THREAD

**Issue by bmhatfield** [microsoft/vscode-go#2533]
Hi,

I've recently added a `go.mod` and `go.sum` to my project, and moved the project out of the `$GOPATH` (as a means of turning on modules). I also totally wiped my gopath clean to ensure stale stuff was not left behind. I've also subsequently rebooted (related to an OSX update). I'm using `gopls` via the checkbox in settings.

I'm on `go version go1.12.5 darwin/amd64`.

In general things are working (my code compiles/runs/tests pass/etc), however, I was attempting to follow a function chain, and once I got within a module, all "go to definition" functionality stopped working.

<img width="655" alt="Screen Shot 2019-05-23 at 10 43 40 AM" src="https://user-images.githubusercontent.com/1119967/58262358-26961c80-7d48-11e9-9116-31b8bdd36042.png">

I expect to be able to CMD+Click "Code" there and be dropped into the relevant file. The import is correct at the top of the file (see also: my code compiles/runs/etc)

**Comment by stamblerre** [comment]
What version of `gopls` are you using? You can determine this by running the `gopls version` command.

**Comment by bmhatfield** [comment]
hrm, something seems wrong here:

```
% gopls version
no module information, gopls not built in module mode
```

I installed `gopls` via VSCode's `install/update tools` list when I was in a modules context (ie, in a repo outside the `GOPATH`.

**Comment by bmhatfield** [comment]
I reinstalled `gopls` via `go get -u golang.org/x/tools/cmd/gopls`, however I am unfortunately seeing the same results - I can code navigate into a module, but once I am there, I can't make the next hop.

```
% gopls version
golang.org/x/tools/cmd/gopls
    golang.org/x/tools@v0.0.0-20190521203540-521d6ed310dd h1:7E3PabyysDSEjnaANKBgums/hyvMI/HoHQ50qZEzTrg=
```

**Comment by stamblerre** [comment]
Filed https://github.com/golang/go/issues/32209 upstream. Do you mind adding a repro case to that issue?

**Comment by ramya-rao-a** [comment]
Closing in favor of the upstream issue
