### ISSUE TITLE
It appears that gopls should be installed with module support

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode-go#2534]
vscode 1.34.0
vscode-go 0.10.2

`gopls version` returns `no module information, gopls not built in module mode` when installed by vscode. it appear that `GO111MODULE` must be set to `on` for gopls to be built with version info.

Should vscode-go force `GO111MODULE` to `on` when installing `gopls`?

Note: I do not have `GO111MODULE` set to `on` by default in my current environment.

**Comment by SteelPhase** [comment]
You can see some of the confusion this can cause here. https://github.com/microsoft/vscode-go/issues/2533#issuecomment-495268293

**Comment by stamblerre** [comment]
I don't think that should be necessary. It just sounds like we should improve the output of the version command. I don't think it's a good idea to mess with people's configurations, and then this problem will go away once `GO111MODULE` is on by default in future Go versions.

**Comment by SteelPhase** [comment]
That's a fair point, just thought I'd offer it up. I'm not sure there are a whole lot of options when it comes to go get and versioning. I was impressed that it worked with modules on.

**Comment by ramya-rao-a** [comment]
When running `go get`, the extension intentionally turns off `GO111MODULE`. This change was made as part of #1919 

@stamblerre Do you think that we no longer need to do this?

**Comment by stamblerre** [comment]
No, I think https://github.com/microsoft/vscode-go/issues/1919 is still an issue. The `gopls version` command is really not important enough to justify changing anything. I will just try to improve the quality of that command.
