### ISSUE TITLE
Clicking on function in outline view doesn't jump to function

### ISSUE THREAD

**Issue by satishvaltix** [microsoft/vscode-go#2535]
Issue Type: <b>Bug</b>

I am seeing this issue with the Code Insiders build, and using the remote-ssh extension to edit files on a remote host.

Clicking on the first function in the outline view doesn't directly jump to the function. Clicking on another function and coming back to the first function works. 

Extension version: 0.10.2
VS Code version: Code - Insiders 1.35.0-insider (94f7de61ece171f4390ece488a220d22cbb0fddd, 2019-05-23T05:15:43.589Z)
OS version: Darwin x64 18.5.0
Remote OS version: Linux x64 3.10.0-957.1.3.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.16GB free)|
|Process Argv|-psn_0_3834792|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: satish-dev|
|OS|Linux x64 3.10.0-957.1.3.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (2 x 2299)|
|Memory (System)|3.70GB (1.05GB free)|
|VM|0%|
</details>

**Comment by ramya-rao-a** [comment]
Apologies for the late response @satishvaltix 

Is the problem only ever for the first function in the outline view? Other functions work as expected?
