### ISSUE TITLE
Issue with symbolic links

### ISSUE THREAD

**Issue by sryze** [microsoft/vscode-go#2539]
There seems to be a problem with using symbolic links in project path and GOPATH:

If the path to your currently open Go file contains symlinks, none of the breakpoints are hit because the debugger can't find the source files. 

Steps to reproduce:

1. Set GOPATH to some path containing a symlink:

```bash
export GOROOT=$HOME/Tools/go                                                    
export GOPATH=$HOME/Tools/go-packages:$HOME/Projects/Go                         
export PATH=$PATH:$GOROOT/bin:$HOME/Tools/go-packages/bin:$HOME/Projects/Go/bin 
```

`$HOME/Projects` is a link to another directory here, in my case it points to `/datax/Projects`.

3. Create `hello.go` in `$HOME/Projects/Go/src/hello/hello.go`

```
package main

import "fmt"

func main() {
	x := 123
	fmt.Println(x)
	fmt.Printf("Hello, world!\n")
}
```

4. Open `$HOME/Projects/Go` in VS Code.
5. Create a launch configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": [],
            "showLog": true,
            "trace": "log",
            "logOutput": "rpc"
        }
    ]
}
```
6. Set a breakpoint at line 7 or 8
7. Run hello.go

Result:

The debugger does not stop at breakpoints and outputs these errors:

```
Error on CreateBreakpoint: could not find /datax/Projects/Go/src/hello/hello.go:7
Error on CreateBreakpoint: could not find /datax/Projects/Go/src/hello/hello.go:8
```

Workaround:

I've discovered that the following steps can improve the situation:

1. Open the project via its real path, not a path with links (in my case `/datax/Projects/Go`)
2. Use paths without links in GOPATH (in .profile or .bashrc):

```bash
export GOROOT=`realpath $HOME/Tools/go`                                       
export GOPATH=`realpath $HOME/Tools/go-packages`:`realpath $HOME/Projects/Go` 
export PATH=$PATH:`realpath $GOROOT/bin`:`realpath $HOME/Tools/go-packages/bin`:`realpath $HOME/Projects/Go/bin`
```

System info:

VSCode version: 1.34.0
go version go1.12.5 linux/amd64
dlv version: 1.2.0
OS: Linux amd64 (Ubuntu 18.04)

**Comment by pkmarcotte** [comment]
Just to add a minor comment on this, because I ran into it:

This happens on Mac OS X Mojave as well, and it's not just symlinks.
Mac's filesystem is not case sensitive, and referring to a path with a different case also causes the issue. So in the example given above, if you had '/datax/Projects/Go' on a Mac, and you opened the project using 'code ~/datax/projects/go', the editor would work, but debugger breakpoints would not be hit. The 'realpath' workaround above also works with this issue.

**Comment by ramya-rao-a** [comment]
Hello all,

If you are still seeing this issue, please log a new issue at https://github.com/golang/vscode-go as [we are moving](https://github.com/microsoft/vscode-go#we-are-moving---)!

Thanks for the support and Happy Coding!
