### ISSUE TITLE
Can't see errors from failed test

### ISSUE THREAD

**Issue by someone235** [microsoft/vscode-go#2540]
Hi, I have this version of VSCode:

    Version: 1.34.0
    Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
    Date: 2019-05-15T21:55:35.507Z
    Electron: 3.1.8
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Linux x64 4.15.0-50-generic snap

And Go extension v0.10.2.

Whenever I run this test:

    package hello
    
    import "testing"
    
    func TestFoo(t *testing.T) {
    	t.Fatalf("Failure message")
    }

I see in the output:

    Running tool: /snap/bin/go test -timeout 30s github.com/someone235/hello -run ^(TestFoo)$
    
    Error: Tests failed.

But I don't see the expected `Failure message`. Do you know what could be the problem?

Thanks in advance

**Comment by ramya-rao-a** [comment]
Apologies for the late response.

I used your code and I am able to see the message

![image](https://user-images.githubusercontent.com/16890566/60379240-47efc580-99e4-11e9-857b-6b96023d95d3.png)


Can you share any Go related settings you might have added/edited?
