### ISSUE TITLE
Version mismatch: fail to launch debug with delve 1.2.0 

### ISSUE THREAD

**Issue by DeXtmL** [microsoft/vscode-go#2541]
I get this error when trying to launch the debug:
**API server listening at: 127.0.0.1:23552
could not launch process: executables built by Go 1.11 or later need Delve built by Go 1.11 or later
Process exiting with code: 1**

tools versions:

Go:
go version go1.12.5 windows/amd64

Delve:
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $

My system only has one Go and gotools installation.

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Settings changed:
GoPath is changed to %WORKPATH%/Go

Steps to Reproduce:

1. install the latest Go 1.12.5 x64 on Windows 10.
2. Install Go plugin and all related tools in VSCode
3. Open a go project in VSCode
4. Click the run button in the Debug tab
5. See the error message in the DEBUG CONSOLE

**Comment by ramya-rao-a** [comment]
Can you try updating your version of delve? 
- Run the command `Go: Install/Update Tools`
- Select `delve`
- Press Ok
- Ensure that it gets updated successfully
- Try debugging again

**Comment by DeXtmL** [comment]
> Can you try updating your version of delve?
> 
> * Run the command `Go: Install/Update Tools`
> * Select `delve`
> * Press Ok
> * Ensure that it gets updated successfully
> * Try debugging again

That works
