### ISSUE TITLE
promptForTags also prompt for transform

### ISSUE THREAD

**Issue by bhenderson** [microsoft/vscode-go#2546]
Hi, I was hoping for a way for Go: Add Tags to prompt for the transform parameter. I often want to switch between camelCase and snake_case even within the same project.

I was thinking that if go.addTags.promptForTags is true, it would also prompt for the transform parameter.

I can't find the current version of the plugin. "0.10.2 - 30th April, 2019" is at the top of the changelog.

thanks,

**Comment by ramya-rao-a** [comment]
That's a valid request. PRs are welcome to add the feature to prompt for transform when `go.addTags.promptForTags` is set to `true`

Code Pointers:
- [Set up local dev environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- `getTagsAndOptions()` function in `goModifytags.ts` file is the place to make the change.

**Comment by haryps** [comment]
Dear All,

Could you provide steps to reproduce since i'm still not really familiar with vscode-go.

Regards

**Comment by bulentrahimkazanci** [comment]
I think this was already implemented. [This](https://github.com/microsoft/vscode-go/blob/7e2de145389fbfe42d6f782f4a0c17af9e0daa3b/package.json#L1249) links is the JSON format of `go.addTags`.

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Please subscribe to https://github.com/golang/vscode-go/issues/115 for further updates on this issue.

Thanks for all the support & Happy Coding!
