### ISSUE TITLE
Highlighting, linting and errors do not work when Golang is installed using snap (ubuntu)

### ISSUE THREAD

**Issue by zom-pro** [microsoft/vscode-go#2547]
After installing golang using snap, no errors where shown on VSCode (code tab or output section when choosing Go).

This issue was solved by uninstalling the snap and installing golang using apt.

Steps to Reproduce:

1. Install golang using snap (rather than apt or source)
2. Install plugins and configure as required in VSCode
3. No errors are shown and the output console build command shows no errors neither
4. If the build command is pasted into a terminal, it fails to build as expected.

**Comment by dimovnike** [comment]
any solution to this? i checked many snap channels and result is the same, while switching from the version from apt  works. The same version from apt and snap go1.10.8 produces different results.

**Comment by ramya-rao-a** [comment]
Sorry, I don't have a snap set up and can't delve into what the problem could be here.
@mattouille you mentioned you have a linux set up and are familiar with snap. Can you help out here?

**Comment by mattouille** [comment]
I do.

@zom-pro when you installed the GoLang snap did you happen to add the appropriate /snap directory to your `PATH`?

**Comment by mattouille** [comment]
I just did this on KDE neon.

I removed my Go compiler and installed Go using the Snap:
![uninstall_go](https://user-images.githubusercontent.com/8207468/63989642-dee50680-ca95-11e9-9d53-1239e57fb4d7.png)

I then loaded up VSCode with a project that I know has errors:
![errors3](https://user-images.githubusercontent.com/8207468/63989884-d4773c80-ca96-11e9-846b-dddcc73778c3.png)

I wasn't able to replicate it but I'll continue to use the Snap to see if it breaks at some point.

**Comment by ramya-rao-a** [comment]
Thanks @mattouille!

@dimovnike There are a couple of things that might be happening
- The Go extension failed to activate
    - In this case you would have absolutely no features from the extension. Try running the command `Go: Current GOPATH` and let us know if that command fails or shows a notification with your current gopath
- The Go extension activates, the go build command is run the by the extension, but is not able to parse the results
    - Check the output channel. View -> Output -> select "Go" from the drop down on the top right corner. This is where the parsed output of all go build, lint, vet commands get printed out. Save your file and see if it triggers the build, lint, and vet commands
