### ISSUE TITLE
gopls: strange autocompletion behaviour for function arguments

### ISSUE THREAD

**Issue by fotonmoton** [microsoft/vscode-go#2549]
Sometimes autocompletion do not insert parentheses and if I add them by hand I can use completion again, inside parentheses. But there are cases when parentheses inserted on tab/enter and completion for arguments stop working, for example, at the end of a function block.

```go
package main

import (
	"fmt"
	"math"
	"math/rand"
	"strconv"
)

func myCooFunc(str string, number int32) string {
	return  str + " " + strconv.Itoa(int(number)) 
}

func typeOmmiting(str, anotherStr string) string {
	return str + " and " + anotherStr
}

func multipleResult(x, y string) (string, string) {
	return y, x
}

func main() {
	fmt.Printf("Squared PI %f\n", math.Pow(math.Pi, 2))
	fmt.Printf("loool %s Here some rand int %d\n", "what?", rand.Intn(10))
	fmt.Printf("here my cool func %s \n", myCooFunc("hi", 10))
	fmt.Println(typeOmmiting("str", "str"))
	fmt.Println(typeOmmiting("fist", "second"))
	fmt.Println(multipleResult("1", "2"))
	fmt.Println(multipleResult("first", "second"))
}

```
settings:
```json
{
	"go.useLanguageServer": true,
	"go.languageServerExperimentalFeatures": {
			"diagnostics": true,
	},
	"[go]": {
	    "editor.snippetSuggestions": "none",
	    "editor.formatOnSave": true,
	    "editor.codeActionsOnSave": {
	        "source.organizeImports": true
	    }
	},
	"gopls": {
	    "usePlaceholders": true
	},
	"files.eol": "\n"
}
```

To reproduce:
1. Start typing at the end of a function block
2. Hit tab or enter to get completion with parentheses
3. Try to enter function argument and get no suggestions

Another problem to reproduce:
1. Start typing in the middle of the code
2. Hit tab or enter to get completion without parentheses
3. Add parentheses by hand and only after that get completion for argument

with usePlaceholders:
![with_usePlaceholders_cut](https://user-images.githubusercontent.com/7763084/58672330-25b84880-834f-11e9-9da6-834778e2f3e3.gif)

without usePlaceholders:
![without_usePlaceholders](https://user-images.githubusercontent.com/7763084/58672331-25b84880-834f-11e9-80e8-43c4429830b3.gif)

**Comment by stamblerre** [comment]
Thank you for the detailed issue report! I have just filed an issue upstream for it against `gopls`: https://github.com/golang/go/issues/32375.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @fotonmoton! Closing this issue in favor of the upstream issue @stamblerre has logged
