### ISSUE TITLE
[gopls] : Following links on imports opens the browser 

### ISSUE THREAD

**Issue by jhernandezb** [microsoft/vscode-go#2550]
Steps to Reproduce:

1. Start a project with go modules
2. Configure vscode according to https://github.com/golang/go/wiki/gopls#vscode
3. [a copy of my exact settings](https://gist.github.com/jhernandezb/a2a3b57eb75dfcc6c9dad001d0a6eba6)
3. import a library and try to Cmd+ Click
4. [See example ](https://d1sz9tkli0lfjq.cloudfront.net/items/0y44252T1U3k2y2x1n0H/Screen%20Recording%202019-05-30%20at%2010.25%20PM.gif)

![example](https://d1sz9tkli0lfjq.cloudfront.net/items/0y44252T1U3k2y2x1n0H/Screen%20Recording%202019-05-30%20at%2010.25%20PM.gif)

**Comment by stamblerre** [comment]
This an intentional feature of `gopls`. In the next release of VSCode-Go, you should be able to disable this feature by configuring `"documentLink": false` in your `"go.languageServerExperimentalFeatures"`.

**Comment by jhernandezb** [comment]
Makes sense, I'm closing it
