### ISSUE TITLE
autocomplete on packages doesnt work

### ISSUE THREAD

**Issue by ignishub** [microsoft/vscode-go#2552]
![изображение](https://user-images.githubusercontent.com/1565839/58715317-43c58d80-83cf-11e9-9af7-2f9239a0d9b1.png)

1. Absolutely clean go install on new system
2. New VSCode (Insiders and Stable, Systm and Userspace)
3.  Just installed extension and tools

**Comment by ignishub** [comment]
I tires latest beta extension and i have laest go version
go version go1.12.5 windows/amd64

**Comment by ignishub** [comment]
i made it work BUT when i initialized go modules in this folder. It is required to to initialize go modue in non GOPATH directory to import standart packages and have autocompletion for them?

**Comment by engineeror** [comment]
Same exact problem on Arch Linux.
Sadly, there isn't a FLOSS editor for Go with typing suggestions and hover information. I've no idea what the Go language server is for, if I can't tell the difference between `"go.useLanguageServer": true` and `"go.useLanguageServer": false`. Also, [the extension showcase website](https://code.visualstudio.com/docs/languages/go) must be fake or something, as I've never seen vscode do any typing suggestion or hover info of that sort for Go. Are we living in the same world, what's happening?

**Comment by ramya-rao-a** [comment]
> Is it required to initialize go modue in non GOPATH directory to import standart packages and have autocompletion for them?

@ignishub Yes, when your code is outside of the GOPATH, the Go tools need to be aware of the go.mod file to provide the relevant features.

@engineeror Please share the below details of your set up
- Version of Go, VS Code and the Go plugin to VS Code
- Any Go related settings you might have added/changed
- Are you working with Go modules or inside GOPATH or both?

**Comment by ramya-rao-a** [comment]
@engineeror Your issue seem to be different from what @ignishub is seeing. @ignishub was able to solve the issue by having a go.mod file in the project.  Please create a new issue with the below details of your set up
- Version of Go, VS Code and the Go plugin to VS Code
- Any Go related settings you might have added/changed
- Are you working with Go modules or inside GOPATH or both?

**Comment by ignishub** [comment]
My issue is still there. Beacause i still need a full initilized module to autocomplete even standart golang modules. So even if i want to write simple dev ops script in just one file or sample script for play.golang.org sandbox, i need full initilized module for this. Even if it just standart libraries

**Comment by ramya-rao-a** [comment]
@ignishub Can you please share your settings so that we can determine if you are using the language server or not?

@stamblerre Is it fair to say that a `go.mod` file is absolutely required for `gopls` to provide completions event for the standard libraries when outside of GOPATH?

**Comment by ignishub** [comment]
I am using language server. As i mention in other issues. Settings was the same. Do i need to duplicate my settings to this thread?

**Comment by stamblerre** [comment]
Yes, for now, it is required to use a `go.mod` outside of `$GOPATH`. Our answer on this may change in the future, but for now, these are the only supported modes. @ignishub: You should be able to write such scripts inside of your `$GOPATH`.

**Comment by ignishub** [comment]
@stamblerre  Ok. Got it. 

I will be really appreciate if you will consider this idea. Because as you know all devops script need to be on the same comfortable place that you can run anytime. And its really uncomfortable to have separate folder for example/play.golang.org scripts and even save on disc those things. If i want for example to write example to answer to stackoverflow question i just want to write this code in editore and send id. I dont want to create folder and save this file

**Comment by ramya-rao-a** [comment]
Thats great feedbacl @ignishub, thanks!

@stamblerre Can we have a tracking issue for this upstream?
