### ISSUE TITLE
gopls: Message: no room in queue

### ISSUE THREAD

**Issue by OneOfOne** [microsoft/vscode-go#2553]
Autocompletion stops working and the log gets spammed with that until I restart vscode, killing gopls doesn't help.

**Comment by stamblerre** [comment]
This is an upstream `gopls` issue that we are currently investigating: https://github.com/golang/go/issues/32368.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @OneOfOne 
Closing in favor of the upstream issue that @stamblerre has linked above
