### ISSUE TITLE
Language server error

### ISSUE THREAD

**Issue by ignishub** [microsoft/vscode-go#2554]
![изображение](https://user-images.githubusercontent.com/1565839/58753682-e9f6bd80-84cb-11e9-8b0d-72ac93871b70.png)

LSP thinks that main is not a part of a package. I use go module initialized.

go 1.12.5 windows

**Comment by ramya-rao-a** [comment]
Please share the below details

- all the Go related settings you have added/edited. 
- a screenshot of the error in the Problems view or a screenshot of the error when you hover over the red line. This is first let us determine if the language server is indeed being used for diagnostics.
- The folder structure of your Go project along with indicator to which folder is opened as root in VS Code

**Comment by SteelPhase** [comment]
This should be related to golang/go#32341

**Comment by ignishub** [comment]
Settings

```
{
    "go.buildOnSave": "off",
    "go.useLanguageServer": true,
    "go.alternateTools": {
         "go-langserver": "gopls"
    },
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "diagnostics": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "findReferences": true,
        "rename": true,
        "workspaceSymbols": true,
        "documentSymbols": true
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "go.autocompleteUnimportedPackages": true,
    "go.formatTool": "goimports",
    "go.gotoSymbol.includeGoroot": true,
    "go.inferGopath": true,
    "go.gotoSymbol.includeImports": true,
    "go.testOnSave": true
}
```

Screenshot
![изображение](https://user-images.githubusercontent.com/1565839/58920428-ceddb500-873a-11e9-89b5-a39ea53b1cde.png)

**Comment by ramya-rao-a** [comment]
Thanks @ignishub, the error is definitely coming from the language server. Does the error persist if you reload VS Code window?

**Comment by ignishub** [comment]
Yes its on every project. Even after restarting my PC

**Comment by ramya-rao-a** [comment]
Thanks @ignishub 
@stamblerre Would you consider this the same as https://github.com/golang/go/issues/32341 or a separate issue?

**Comment by stamblerre** [comment]
Yes, I think so. I will try to investigate ASAP.

**Comment by freman** [comment]
I wonder if we couldn't do with a temporary patch that lets us use different language servers depending on if a go.mod exists or not.

I find gopls (or even the old language-server) works beautifully for all our legacy projects and bingo works perfectly for now modules code, but I have to switch between the two :(

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of the upstream issue https://github.com/golang/go/issues/32341

@freman You can add the below in your workspace settings to use bingo. This way you can decide which of the two to use per project
```
"go.alternateTools": {
   "gopls": "bingo"
}
```
