### ISSUE TITLE
Set go.toolsGopath automatically to the extension installation folder

### ISSUE THREAD

**Issue by karim** [microsoft/vscode-go#2558]
The required tools for the Go extension are installed in `GOPATH` by default. With the removal of `GOPATH` in the next version of Go, where the Go extension will install these tools?

What I understand so far is, `GOPATH`-mode builds will be deprecated, and modules will be used instead, but `GOPATH` environment variable is still being used, for example, to identify the module cache location (`GOPATH/mod`).

On Windows, and when it is not set, it defaults (`go env GOPATH`) to the current user directory (`C:\Users\<name>\go`). Does that mean Go extension will install the tools there?

What I suggest here is to let the Go extension install all the tools it requires where the extension is installed and ignore the `GOPATH` completely. Since these tools are mostly (only?) needed by this extension alone.

By setting the `go.toolsGopath` automatically, the extension will have complete control over the tools and will free the user from managing them.

For example:

- The extension can include a list of the latest known working version of each tool, instead of installing the latest version of it when it is missing.

- The extension can be tested versus a specific known working version/commit of a tool and then upgrade/downgrade the tool as required. It can trigger a tool update when it finds that the installed tool is older than the recommended one (currently users have to do this manually), or it can downgrade a tool when its latest version isn't working correctly.

- It can cleanup/delete old/unused tools when they are no longer needed.

**Comment by ramya-rao-a** [comment]
The value returned by `go env GOPATH` is already being used as the GOPATH by this extension when no explicit `GOPATH` is set as an environment variable. So as far as `go env GOPATH` gives a value, we are good. Is there any evidence of this going away as well?

When an extension is updated (say a new version is available), the existing folder where the extension is installed is replaced with the new bits. So installing the Go tools there would mean that the tools are re-installed with every extension update.

Also, we have users would prefer to control the tools that are getting installed and sometimes want to use specific versions or run `go get` themselves to get the tools.

**Comment by karim** [comment]
> Is there any evidence of this going away as well?

No, it is not going anywhere. It is still being used by modules (`GOPATH/mod`) but I'm not sure if it will also have `GOPATH/bin` and `GOPATH/src`.

> When an extension is updated (say a new version is available), the existing folder where the extension is installed is replaced with the new bits. So installing the Go tools there would mean that the tools are re-installed with every extension update.

I didn't know that, sorry.

> Also, we have users would prefer to control the tools that are getting installed and sometimes want to use specific versions or run `go get` themselves to get the tools.

My suggestion was about making the extension handle all the logistics of installing/updating/removing the tools as required. Deleting the ones that are no longer used. Updating the installed ones when the extension is updated, and so on.

Example..
- A bug is reported.
- Bug seems to be related to a tool.
- Bug is fixed.
- Extension is updated with this tool working version tag/commit.
- Extension version is increased to trigger an update.
- Extension gets updated automatically in VS Code, which updates the tool with the working tag/commit.

**Comment by jayschwa** [comment]
> The value returned by `go env GOPATH` is already being used as the GOPATH by this extension when no explicit `GOPATH` is set as an environment variable.

This doesn't seem to be the case for me. When I open VSCode and click "Install All", the extension complains: "Cannot install Go tools. Set either go.gopath or go.toolsGopath in settings."

**Comment by ramya-rao-a** [comment]
@jayschwa Does `go env GOPATH` return anything for you?

**Comment by jayschwa** [comment]
`/home/jayschwa/go`

**Comment by ramya-rao-a** [comment]
@jayschwa Then that is what the extension should use. Can you log a new issue so that we don't hijack this thread which is about the go.toolsGopath setting?

**Comment by mattouille** [comment]
`$GOPATH/bin` will not go anywhere because when you use modules to install a package with the name of main (like gopls) it builds the binary there. I haven't seen any suggestions to change that.

**Comment by ramya-rao-a** [comment]
> A bug is reported.
Bug seems to be related to a tool.
Bug is fixed.
Extension is updated with this tool working version tag/commit.

@karim It was a very intentional move to not update any tools on behalf of the user automatically. It is a sensitive topic for quite a few people as to what gets installed on their machine.

We have the `Go: Install/Update Tools` command which one can use to update the tools they want to.
We have prompts to update tools in case the extension is using a feature of the tool which is not available in the version of the tool on the user's machine.

The case of bug fixes on the tool that is relevant for the user is rare and is mostly around actively developing tools like `gopls` the language server, for which we are working on ensuring there is a prompt to update when a new version is found to be available.

Hopefully this addresses the concerns you have put forth here.

Happy Coding!

**Comment by karim** [comment]
Fair enough. Looking back at this again I think you are right. :+1:
