### ISSUE TITLE
Changing to a different goroutine and executing Step Over goes back to the previous goroutine

### ISSUE THREAD

**Issue by aarzilli** [microsoft/vscode-go#2560]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

1. Debug https://github.com/aarzilli/delve_client_testing/blob/master/08gswitch/main.go
2. Click on one of the paused goroutines executing `main.coroutine` in the left column
3. Click Step Over

### Expected:

Cursor moves to the next line on the goroutine I'm currently watching.

### What actually happend

Debuggers switches back to the goroutine it was originally stopped at and moves to the next line.

**Comment by ramya-rao-a** [comment]
Hello @aarzilli,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Closing this issue in favor of https://github.com/golang/vscode-go/issues/118. Please subscribe to it for further updates.

Thanks for all the support & Happy Coding!
