### ISSUE TITLE
Debugger freezes

### ISSUE THREAD

**Issue by aarzilli** [microsoft/vscode-go#2562]
1. Debug https://github.com/aarzilli/delve_client_testing/blob/master/20bigstuff/main.go.

I expected a slight slowdown but the debugger should keep working. What happend is that the debugger freezes slowing down the whole system. Possible causes include VSCode-go trying to read the 100MB string, 10 million stack frames or 1 million goroutines. Possibly all three.

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of https://github.com/golang/vscode-go/issues/129 due to the [repo move](https://github.com/microsoft/vscode-go#we-are-moving---)
