### ISSUE TITLE
Debugger reports only one breakpoint when multiple goroutines stop simultaneously

### ISSUE THREAD

**Issue by aarzilli** [microsoft/vscode-go#2564]
1. Debug https://github.com/aarzilli/delve_client_testing/blob/master/04simbp/main.go
2. set a breakpoint on main.go:9
3. hit continue repeatedly

I expect that a total of 100 breakpoint hits will be reported but what happens is that many fewer (between 20 and 30 on a 4 core system) will be reported. The reason is that when multiple goroutines hit the breakpoint at the same time only one is reported, with the other being silently discarded.

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of https://github.com/golang/vscode-go/issues/130 due to the [repo move](https://github.com/microsoft/vscode-go#we-are-moving---)
