### ISSUE TITLE
Autocompletion of symbols from unimported packages doesnt work with modules

### ISSUE THREAD

**Issue by ignishub** [microsoft/vscode-go#2565]
New error with same name :)
Initilized module. Installed iris package for this module. Completition doesnt work for iris.

![изображение](https://user-images.githubusercontent.com/1565839/58928541-900c2700-875b-11e9-8caf-b9de3b787736.png)
![изображение](https://user-images.githubusercontent.com/1565839/58928600-d3ff2c00-875b-11e9-9ccc-a3712f8dd137.png)

mod file:
```
go 1.12

require (
	github.com/BurntSushi/toml v0.3.1 // indirect
	github.com/Joker/jade v1.0.0 // indirect
	github.com/Shopify/goreferrer v0.0.0-20181106222321-ec9c9a553398 // indirect
	github.com/aymerick/raymond v2.0.2+incompatible // indirect
	github.com/eknkc/amber v0.0.0-20171010120322-cdade1c07385 // indirect
	github.com/fatih/structs v1.1.0 // indirect
	github.com/flosch/pongo2 v0.0.0-20190505152737-8914e1cf9164 // indirect
	github.com/iris-contrib/blackfriday v2.0.0+incompatible // indirect
	github.com/iris-contrib/formBinder v0.0.0-20190104093907-fbd5963f41e1 // indirect
	github.com/iris-contrib/go.uuid v2.0.0+incompatible // indirect
	github.com/json-iterator/go v1.1.6 // indirect
	github.com/kataras/golog v0.0.0-20180321173939-03be10146386 // indirect
	github.com/kataras/iris v11.1.1+incompatible // indirect
	github.com/kataras/pio v0.0.0-20190103105442-ea782b38602d // indirect
	github.com/klauspost/compress v1.6.1 // indirect
	github.com/klauspost/cpuid v1.2.1 // indirect
	github.com/microcosm-cc/bluemonday v1.0.2 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.1 // indirect
	github.com/ryanuber/columnize v2.1.0+incompatible // indirect
	github.com/shurcooL/sanitized_anchor_name v1.0.0 // indirect
	golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5 // indirect
)
```

Settings:
```
{
    "go.buildOnSave": "off",
    "go.useLanguageServer": true,
    "go.alternateTools": {
         "go-langserver": "gopls"
    },
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "diagnostics": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "findReferences": true,
        "rename": true,
        "workspaceSymbols": true,
        "documentSymbols": true
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "go.autocompleteUnimportedPackages": true,
    "go.formatTool": "goimports",
    "go.gotoSymbol.includeGoroot": true,
    "go.inferGopath": true,
    "go.gotoSymbol.includeImports": true,
    "go.testOnSave": true
}
```

**Comment by stamblerre** [comment]
You will first need to add `iris` as an import for the package into your file - `gopls` does not yet work with unimported packages.

**Comment by ramya-rao-a** [comment]
@stamblerre If there is an upstream issue for gopls to provide such completions, can you please provide it here so that users can subscribe to it?

**Comment by ignishub** [comment]
Wait. On old version of vscode i dont need to manally insert any package. I just can autocomplete package name. Why do i even need to do manually that kind o things? All information we have on my machine and module file.  This is standart functionality of all code editors.

**Comment by stamblerre** [comment]
See https://github.com/golang/go/issues/31906. For the time being, when using modules, you will need to add the import. The manual work can be reduced by using `goimports` on save.

**Comment by ignishub** [comment]
Then i don't understand why vscode suggest to switch to language server when it can't even handle this simple things. No offense of course. I just really don't get it. This language server is still not ready to be recommended to be default autocomplete tool.

**Comment by stamblerre** [comment]
The feature that does this in VSCode only works for `$GOPATH` mode. The language server is only used in module mode. Unfortunately, we don't have as much editor support for modules at the moment, as modules are relatively new.

**Comment by ramya-rao-a** [comment]
@ignishub Below is the reccommendation model at the moment
- If using modules, use the language server. Because it fares much better than the existing Go tools when it comes to modules
- If you are not using modules, you don't need to use the language server. Existing tooling work just fine.
