### ISSUE TITLE
go.lintOnSave is ignored

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode-go#2567]
Hi

Steps to Reproduce:

**1.** Put this line in VS Code `settings.json`
```
    "go.lintOnSave": "off"
```

**2.** Put this code in a file called `test.go`
```
package main

import "fmt"

func main() {
	
}
```

**3.** Save using `Ctrl+S` default shortcut

**4.** Watch as the code gets linted (`import "fmt"` gets removed because it is unused)

How can I save a file as-is, without linting, without disabling the extension?

I believe I missed something so I apoligize in advance. Thank you.

**Temporary workaround**
Disable the extension

**Comment by karim** [comment]
Lint tool is for finding errors with your code. What you are looking for is the format tool.

To keep the unused imports, either use a formatting tool that does not remove unused imports, or disable formatting on save.

What is your `"go.formatTool"`? If it is `goreturns` (the default), or `goimports` then unused imports will be removed. Change it to `gofmt` or `goformat`.

You can also disable formatting on save..
```json
"[go]": {
   "editor.formatOnSave": false
}
```

**Comment by sguillia** [comment]
I apologize for having mixed up linting and formatting.

`editor.formatOnSave` was indeed the setting I was looking for.

Thank you!
