### ISSUE TITLE
Intellisence does not respond to navigation commands

### ISSUE THREAD

**Issue by davmaz** [microsoft/vscode-go#2571]
When writing go code, intellisense pops up information on the particular func or object. However, the only way to get rid of it is to press Esc. If the Home, End, Up, or Down keys are hit to get rid of the "help", there is no change. In addition, it seems to always show the help over top of the previous lines, so Esc HAS to be pressed to regain context on the current line.

If the python package had not responded correctly, this problem would have looked like something in vscode, not the go extension. To see how things should work ideally, load a python program and notice how the python extension correctly removes the pop-up information if any navigation key is pressed.

**Comment by ramya-rao-a** [comment]
I don't work with python at all, would you be able to provide a video comparing Go and Python?

**Comment by davmaz** [comment]
Actually that's not reasonable in my case. The bottom line is that navigation keys don't work when something is being displayed. At first I thought I had a way around it by hitting the Home key (or what I have it mapped to) and that doesn't work either. It seems you either accept what it's suggesting OR hit ESC which is very annoying since I don't want to take my hands off the home keys.


Nevertheless, the go support is so nice I won't uninstall it. I'll just hit Esc until it gets changed. To see for yourself, you really don't need to do much python -- just load any python file and vscode will suggest support for it. Once you type any command it can help with you'll see that if you hit a navigation key it will disappear.


Do you want me to send you a walk through? I can send a simple Python file and you'll be able to see how it reacts.


Best,

Dave

________________________________

**Comment by ramya-rao-a** [comment]
When you "intellisence", are you referring to the auto-completion widget or the parameter hint widget? Can you share a screenshot?

If this is about the auto-completion widget, then all navigation keys (up arrow, down arrow, home, end) are used to navigate inside the list of suggestions in the widget. So, not sure how the python extension can override that.

If this is about the parameter hint widget, then I am able to dismiss it using the navigation keys in Go code

Autocompletion widget:

<img width="660" alt="Screen Shot 2019-07-06 at 6 17 29 PM" src="https://user-images.githubusercontent.com/16890566/60762666-7855e600-a01a-11e9-8d1e-cedb03561a3a.png">

Parameter hint widget:

<img width="770" alt="Screen Shot 2019-07-06 at 6 17 13 PM" src="https://user-images.githubusercontent.com/16890566/60762667-7b50d680-a01a-11e9-8cb1-803636c05abe.png">
