### ISSUE TITLE
Editor breaks import path when Go module replacements are used

### ISSUE THREAD

**Issue by andig** [microsoft/vscode-go#2572]
My code contains various imports:

    import (
        "fmt"
        "log"
        "os"
        "strconv"

        "github.com/crabmusket/gosunspec"
        bus "github.com/crabmusket/gosunspec/modbus"
        _ "github.com/crabmusket/gosunspec/models" // import models

        "github.com/grid-x/modbus"
    )

I'm also using the types imported from `gosunspec` in `main.go`:

	in.Do(func(d sunspec.Device) {
		d.Do(func(m sunspec.Model) {
            ...
		})
	})

Using `go.mod`, I have to temporarily replace `crabmusket/gosunspec` with a custom fork until an upstream issue is resolved:

    module github.com/volkszaehler/mbmd

    require (
        github.com/crabmusket/gosunspec v0.0.0-20170310004250-4c2adf6161ca
        github.com/eclipse/paho.mqtt.golang v1.2.0
        github.com/goburrow/modbus v0.1.0 // indirect
        github.com/goburrow/serial v0.1.0 // indirect
        ...
    )

    replace github.com/crabmusket/gosunspec => github.com/andig/gosunspec v0.0.0-20190613063246-3c54c2ccb77a

Now, when editing `main.go`, two things are happening:

1. vscode modifies the `"github.com/crabmusket/gosunspec"` import into the `"github.com/andig/gosunspec"` replacement
2. subsequently `"github.com/andig/gosunspec"` is added to `go.mod` (I assume rather by go than by vscode)

**Synopsis** if types are part of a replacement package, import path *must* match the *replaced* package instead of the *replacement* package.

Full source is available in https://github.com/andig/mbmd/blob/scan-sunspec/cmd/scan/main.go

**Comment by ramya-rao-a** [comment]
Please share any Go related settings you might have added/edited

**Comment by andig** [comment]
There is only `settings.json`, nothing I have specifically tweaked:

````
{
    "go.formatTool": "goimports"
}
````

If you need anything else please let me know.

**Comment by chgeuer** [comment]
I believe I'm experiencing the same problem. Check out this sample repro solution:

https://github.com/chgeuer/repo-go-mod-vs-code

There are two VS Code workspaces, called "good" and "bad". The "good" one only shows the main folder, while "bad" shows everything. I would love to open "bad", but then the whole F12 navigation etc doesn't work any longer.

**Comment by andig** [comment]
ping @ramya-rao-a is there anything else we could contribute?

**Comment by ramya-rao-a** [comment]
Hi @andig, apologies for the late reply.

Your settings show that you are not using the language server. @chgeuer Can you share your settings as well?

In the absence of the language feature, the tool specified in `go.formatTool` setting is used for formatting. In @andig's case, this is `goimports` which does edit import statements.

@andig Can you add the below in your settings to disable the format on save feature and see if you still see the issue? This can confirm if the formatting is indeed making this change
```
"[go]": {
   "editor.formatOnSave": false
}
```

**Comment by andig** [comment]
Thank you @ramya-rao-a. I wasn‘t aware that I needed to manually enable the language server istead of this being the default (I haven‘t touched the config at all). I will test both your suggestion and using the language server.

**Comment by chgeuer** [comment]
> Your settings show that you are not using the language server. @chgeuer Christian Geuer-Pollmann FTE Can you share your settings as well?

I updated by [comment above](https://github.com/microsoft/vscode-go/issues/2572#issuecomment-506719205)

**Comment by andig** [comment]
I can no longer reproduce this when not using the language server (i.e. inside a workspace). Instead now, my import `"github.com/crabmusket/gosunspec"` is being rewritten to `sunspec "github.com/crabmusket/gosunspec"` which is correct but not necessary. The replacement module is no longer added `go.mod`.

**Comment by ramya-rao-a** [comment]
The language server doesnt work with workspaces. There is a known issue tracking that.

**Comment by stamblerre** [comment]
`gopls` requires you to manually add workspace folders. Here is the issue: https://github.com/golang/go/issues/32394.

**Comment by andig** [comment]
> gopls requires you to manually add workspace folders. Here is the issue: golang/go#32394.

At least in my case thats the setup I have. Above issue has been fixed for me by getting rid of the replace statement.

**Comment by ramya-rao-a** [comment]
@stamblerre Is there anything that can be done for this issue?

From what I understand @andig resolved the situation by removing the replace statement entirely

**Comment by stamblerre** [comment]
What @andig is describing sounds like an issue with an old version of `goimports`. It shouldn't be occurring anymore, but if you still see it with the latest version of `gopls`  we can investigate further.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

Closing this issue.

If the problem still persists with the new version of the Go tools, please log a new issue
