### ISSUE TITLE
Auto-complete didn't work before saving file with at least one time usage

### ISSUE THREAD

**Issue by zulhfreelancer** [microsoft/vscode-go#2575]
Hi,

I'm on OSX and currently using `go1.11.4 darwin/amd64` with `GO111MODULE` is set to `on`. My VS Code editor version is _1.35.1_ (_c7d83e57cd18f18026a8162d042843bda1bcf21f_) and here is my _.zshrc_ content:

```
export GOPATH=/Users/zulh/go
export PATH=$GOPATH/bin:$PATH
export GO111MODULE=on
```

From what I noticed, the auto-complete is not working if I haven't use the package:

<img width="385" alt="Screen Shot 2019-06-14 at 5 01 39 PM" src="https://user-images.githubusercontent.com/3416976/59497967-13015000-8ec7-11e9-860b-429cdfecd415.png">

After using a package and save the file, the auto-complete works:

<img width="641" alt="Screen Shot 2019-06-14 at 5 02 20 PM" src="https://user-images.githubusercontent.com/3416976/59498058-388e5980-8ec7-11e9-9366-1e74b78ed761.png">

**Note**: 

This _main.go_ file is located in _/Users/zulh/go/src/github.com/zulhfreelancer/go_parity_next_nonce_

Here is the result for `Go: Browse Packages`:

<img width="705" alt="Screen Shot 2019-06-14 at 5 02 39 PM" src="https://user-images.githubusercontent.com/3416976/59498150-6b385200-8ec7-11e9-82ec-7a2193aa3a1b.png">

When I try to close the `gocode`, here is what I got:

```
$ gocode-gomod close
2019/06/14 17:13:18 dial unix /var/folders/qb/j82t6fhn56gd5qjmr6xwlxyc0000gn/T/gocode-gomod-daemon.zulh: connect: no such file or directory

$ gocode close
2019/06/14 17:13:26 dial unix /var/folders/qb/j82t6fhn56gd5qjmr6xwlxyc0000gn/T/gocode-daemon.zulh: connect: no such file or directory
```

When I run `gocode-gomod -s -debug`, nothing appears in my Terminal when I'm typing code in VS Code editor.

Here are my settings:

```
{

    "workbench.startupEditor": "newUntitledFile",
    "window.zoomLevel": 0,
    "workbench.statusBar.visible": true,
    "editor.minimap.enabled": true,
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": false,
    "editor.fontSize": 14,
    "workbench.colorTheme": "One Dark Pro Vivid",
    "terminal.integrated.rendererType": "dom",
    "workbench.iconTheme": "vscode-icons",
    "sync.gist": "b098aaded0ef7d5274b0f1e482b97f4e",
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false,
    "sync.removeExtensions": true,
    "sync.syncExtensions": true,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastUpload": "2018-08-23T10:56:18.264Z",
    "sync.lastDownload": "2018-08-13T17:46:45.531Z",
    "sync.forceDownload": false,
    "todohighlight.isEnable": true,
    "todohighlight.keywords": [
        {
            "text": "TODO",
            "color": "#000",
            "backgroundColor": "#f1c40f"
        }
    ],
    "explorer.confirmDragAndDrop": false,
    "extensions.ignoreRecommendations": true,
    "editor.wordWrap": "on",
    "files.insertFinalNewline": true,
    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
        "vue-html": "html"
    },
    "go.useLanguageServer": true,
    "ruby.useLanguageServer": true,
    "go.enableCodeLens": {
        "references": false,
        "runtest": false
    },
    "go.autocompleteUnimportedPackages": true,
    "solidity.linter": "",
    "solidity.compileUsingRemoteVersion": "v0.4.25+commit.59dbf8f1",
    "ruby.intellisense": "rubyLocate",
    "git.path": "/usr/local/bin/git",
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }
}
```

What should I do to make the auto-complete work before I import and save the package?

Thank you.

**Comment by ysantalla** [comment]
I have the same problem.

**Comment by ramya-rao-a** [comment]
@zulhfreelancer It looks like you are using the language server, in this case `gocode` or `gocode-mod` are not used for the auto-completion feature. Instead, the language server is used.

The language server at the moment does not support the auto-completion feature for packages that haven't been imported yet.

@stamblerre Is there an issue tracking this for gopls?

**Comment by zulhfreelancer** [comment]
Thank you for the respond @ramya-rao-a. How do I switch from language server to `gocode` or `gocode-mod`?

**Comment by ramya-rao-a** [comment]
@zulhfreelancer Set `go.useLanguageServer` to `false` to stop using language server altogether or keep that to `true` and add the below to turn off just the completion feature from the language server
```json
  "go.languageServerExperimentalFeatures": {
    "autoComplete": false
  }
```

Though, if you are using modules, we strongly suggest to use the language server as the back up tools are no longer under active development in favor of the language server

**Comment by stamblerre** [comment]
The upstream issue is https://github.com/golang/go/issues/31906.

**Comment by ramya-rao-a** [comment]
@stamblerre https://github.com/golang/go/issues/31906 is about getting the unimported packages themselves in the completion list, and then on completion, the import statement gets added automatically 

This issue is that typing `.`  after an unimported package, does not give completions.

**Comment by stamblerre** [comment]
I think the two are effectively the same issue though. In the case that you type `fmt.` without importing `"fmt"`, we will add the import statement if you select a completion.

**Comment by zulhfreelancer** [comment]
@ramya-rao-a thank you. I can confirm it's working now after adding the snippet above.

<img width="698" alt="Screen Shot 2019-06-18 at 12 39 07 PM" src="https://user-images.githubusercontent.com/3416976/59653801-34638400-91c6-11e9-8361-181f6fbc8702.png">

This is my full settings file content:

```
{

    "workbench.startupEditor": "newUntitledFile",
    "window.zoomLevel": 0,
    "workbench.statusBar.visible": true,
    "editor.minimap.enabled": false,
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": false,
    "editor.fontSize": 14,
    "workbench.colorTheme": "One Dark Pro Vivid",
    "terminal.integrated.rendererType": "dom",
    "workbench.iconTheme": "vscode-icons",
    "sync.gist": "b098aaded0ef7d5274b0f1e482b97f4e",
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false,
    "sync.removeExtensions": true,
    "sync.syncExtensions": true,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastUpload": "2018-08-23T10:56:18.264Z",
    "sync.lastDownload": "2018-08-13T17:46:45.531Z",
    "sync.forceDownload": false,
    "todohighlight.isEnable": true,
    "todohighlight.keywords": [
        {
            "text": "TODO",
            "color": "#000",
            "backgroundColor": "#f1c40f"
        }
    ],
    "explorer.confirmDragAndDrop": false,
    "extensions.ignoreRecommendations": true,
    "editor.wordWrap": "on",
    "files.insertFinalNewline": true,
    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
        "vue-html": "html"
    },
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "autoComplete": false
    },
    "ruby.useLanguageServer": true,
    "go.enableCodeLens": {
        "references": false,
        "runtest": false
    },
    "go.autocompleteUnimportedPackages": true,
    "solidity.linter": "",
    "solidity.compileUsingRemoteVersion": "v0.4.25+commit.59dbf8f1",
    "ruby.intellisense": "rubyLocate",
    "git.path": "/usr/local/bin/git",
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "breadcrumbs.enabled": false
}
```

**Comment by ramya-rao-a** [comment]
> I think the two are effectively the same issue though. In the case that you type fmt. without importing "fmt", we will add the import statement if you select a completion.

@stamblerre They are not the same

https://github.com/golang/go/issues/31906 or at least the vscode-go issue it is referring to https://github.com/microsoft/vscode-go/issues/2484 is about typing `ti` and getting `time` as a completion item.

This issue is about typing `time.` and getting all the symbols from the time package in the completion item list.

**Comment by stamblerre** [comment]
Added a note to the issue. I think they will still be implemented effectively the same way, so that issue can cover both cases.

**Comment by stamblerre** [comment]
@ramya-rao-a: https://github.com/golang/go/issues/31906 is now closed, and unimported completions will be on by default for `gopls/v0.3.0`, so I think that this issue can be closed.
