### ISSUE TITLE
cgo syntax highlighting

### ISSUE THREAD

**Issue by rustyx** [microsoft/vscode-go#2581]
It seems the cgo (C code embedded in Go) isn't recognized.

**Steps to reproduce:**

Create a file `main.go` with the following contents:
```go
package main

/*
#include <pthread.h>
#include <time.h>
#include <stdio.h>

static long long getThreadCpuTimeNs() {
	struct timespec t;
	if (clock_gettime(CLOCK_THREAD_CPUTIME_ID, &t)) {
		perror("clock_gettime");
		return 0;
	}
	return t.tv_sec * 1000000000LL + t.tv_nsec;
}
*/
import "C"
import "fmt"
import "time"

func main() {
	cputime1 := C.getThreadCpuTimeNs()
	doWork()
	cputime2 := C.getThreadCpuTimeNs()
	fmt.Printf("CPU time = %d ns\n", (cputime2 - cputime1))
}

func doWork() {
	x := 1
	for i := 0; i < 100000000; i++ {
		x *= 111
	}
	time.Sleep(time.Second)
}
```

Notice the cgo section is highlighted as a comment.

**What should happen instead:**

The C highlighter (if available) should be invoked for the cgo section.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @rustyx 

The grammar used for Go files doesnt support embedded languages at the moment. This feature, though useful is currently out of scope of this extension.
