### ISSUE TITLE
Wrong method autocomplete

### ISSUE THREAD

**Issue by ignishub** [microsoft/vscode-go#2588]
go version go1.12 windows/amd64

Config:
```
{
    "go.formatTool": "goimports",
    "go.lintTool": "golangci-lint",
    "go.buildOnSave": "off",
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "go.autocompleteUnimportedPackages": true,
    "go.gotoSymbol.includeGoroot": true,
    "go.gotoSymbol.includeImports": true,
    "go.useLanguageServer": true
}
```

![изображение](https://user-images.githubusercontent.com/1565839/59832042-af09dc00-934b-11e9-80c6-f89f2c1f5eb3.png)

**Comment by ignishub** [comment]
There is something strange. Its insider version of VS Code. When i am trying to save this file line removes

**Comment by ramya-rao-a** [comment]
@stamblerre Is it ok if @ignishub logs this issue against gopls in https://github.com/golang/go?

**Comment by stamblerre** [comment]
@ignishub: Can you try reproducing this with the latest version of `gopls` on master (`go get -u golang.org/x/tools/gopls@master`)? We have made some changes recently that may have fixed this. However, if it's still happening, please feel free to file an issue in the Go issue tracker that @ramya-rao-a linked.

**Comment by ramya-rao-a** [comment]
Closing this issue as we haven't heard back from @ignishub in a while.
Please try the latest version of the Go extension and `gopls`. There have been quite some improvements over the months.
