### ISSUE TITLE
impl support to generate method stubs for implementing an interface

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#259]
Any chance of adding support for [impl](https://github.com/josharian/impl)?

**Comment by lukehoban** [comment]
Nice idea.  Happy to accept a PR on this.

**Comment by OneOfOne** [comment]
I'll see what I can do when I get some free time.

**Comment by itsjamie** [comment]
As mentioned in #822 here's a little bit of research from the person behind goimpl.
```
impl is parsing AST, goimpl is using reflection.
impl is much faster and has better error reporting.
goimpl generates complete code that (usually) compiles (package/imports).
goimpl can generate a minimum update for the exising implementation.
goimpl can work with ambiguous package names.
```

To me after reading the above, I'd rather use impl the code is easier to grok because of AST parse vs loading code with template and then doing reflection. As a user, I wouldn't mind just manually removing any additional methods I already had implemented.

Thoughts? @mattetti @ramya-rao-a

**Comment by mattetti** [comment]
interesting comparison, I'd probably go with `impl` because of the AST and performance. Note also that our good friend @fatih of awesome vim-go has been using `impl` for a while and therefore vetted it for us :) https://github.com/fatih/vim-go/blob/master/plugin/go.vim#L23

**Comment by ramya-rao-a** [comment]
`impl` for the win.

@itsjamie Feel free to submit a PR for this. If you have questions or doubts on how to go about integrating this, I can answer them for you.

**Comment by itsjamie** [comment]
@ramya-rao-a I put a PR (#939) up that implements the josharian/impl package as a command `go.impl.cursor`. Couple of feature things in that PR that aren't implemented, but it's very much usable.

**Comment by ramya-rao-a** [comment]
This is now available in the latest update 0.6.62

**Comment by renannprado** [comment]
@ramya-rao-a should it work for interfaces in the same file?

I'm getting the following error: Cannot stub inteface: unrecognized interface: MyInterface

**Comment by ramya-rao-a** [comment]
@renannprado Did you provide the package name along with the interface?

For example: I had to use `f *File stringutil.Boo` where `Boo` is the interface and `stringutil` is the package name

**Comment by Mistobaan** [comment]
This could be very useful if implemented properly. Many values of the method could be inferred from the code. Ideally I would like to have >GO: GEneratate interface for variable at mouse point -> AutoComplete available interfaces for the given package -> ENTER -> <autogen code>

**Comment by ramya-rao-a** [comment]
@Mistobaan So the advantage over the current method is that you will be able to choose the interface and not remember/type the name of the interface?

**Comment by Mistobaan** [comment]
@ramya-rao-a yes. right now if you miss one character of the whole command the prompt resets and you have to type the whole thing again

**Comment by ramya-rao-a** [comment]
Ok, so the flow can be
- Run the command
- The quick pick control shows all the imported packages, asking you to select the package
- On selecting a package, the quick pick control now shows the list of interfaces from the selected package
- Select the interface 
- The stubs will be introduced with placeholders for recievers which you can now update.

?

**Comment by ramya-rao-a** [comment]
Say you want stubs for the `io.Reader` interface. You can today type `io.` and autcomplete will suggest all symbols from the `io` package.

In this list, for every interface, we can have another entry which when selected, will insert the stubs. Thoughts?
