### ISSUE TITLE
gofmt-on-save even with typechecking errors

### ISSUE THREAD

**Issue by josharian** [microsoft/vscode-go#2590]
I have noticed that gofmt-on-save doesn't appear to happen when there are typechecking errors. This is frustrating. gofmt and goimports both work fine when run standalone on code that fails typechecking; gofmt doesn't resolve imports at all, and goimports just shrugs and keeps on going. Manually requesting "Format document" does nothing. Is there some way I can get VSCode to format fikes despite the fact that the Go extension cannot build/typecheck it? Typechecking shouldn't be a pre-requisite for formatting.

Note that this is particularly troublesome in the following sequence:

* Start editing a.go. Typechecking starts to fail, since you are mid-stream.
* Realize you need to make a minor edit to b.go as well. Make the edit there. Hit save. b.go is now unformatted.
* Switch back to a.go.  Finish your work; hit save. a.go gets formatted.

b.go remains unformatted. :(

> If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

I asked this on gitter a week ago (https://gitter.im/Microsoft/vscode-go?at=5d033575ecc6a91b31e031e9) but got no reply. It doesn't appear anyone is checking in there.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @josharian 
Can you please share any Go related settings that you might have added/edited?

If you are using the language server, then the formatting feature no longer comes from the formatting tool as set by the `go.formatTool` setting

**Comment by josharian** [comment]
go-related settings (others deleted):

```json
{
    "go.goroot": "/Users/josh/go/tip",
    "go.useLanguageServer": true,
}
```

> If you are using the language server, then the formatting feature no longer comes from the formatting tool as set by the go.formatTool setting

That would explain it. (Well, kind of; it just means that this is a `gopls` bug.)

Is there any way to keep the local formatting tool in change of formatting?

**Comment by josharian** [comment]
Also, so that I can file an effective upstream bug report, is there any good way to get diagnostic information about what gopls is doing (or not doing) when formatting fails? I don't see anything one way or the other in the debug console.

**Comment by ramya-rao-a** [comment]
> Is there any way to keep the local formatting tool in change of formatting?

You can add the below to skip the formatting feature from the language server

```json
{
  "go.languageServerExperimentalFeatures": {
    "format": false
  }
}
```

For troubleshooting gopls, see https://github.com/golang/go/wiki/gopls#troubleshooting

Closing this issue in favor of the one you will be creating upstream :)
Please do add a link to that issue here

**Comment by josharian** [comment]
Thanks, @ramya-rao-a. By way of follow-up, watching the logs, it appears that there were actually many things going wrong.

* There doesn't appear to be a way to globally set a PATH envvar in vscode's settings. As a result, depending on how I happened to open gopls, the PATH would sometimes be empty. When gopls tried to exec the go tool (as part of go/packages), that would fail when PATH was empty. A gopls PATH envvar setting would be helpful.

* Even when PATH was set appropriately, I was hitting https://github.com/golang/go/issues/32467 very regularly. Though gopls eventually recovers, the format request didn't get retried. I think that it'd be good to (a) retry on failure or (b) alert the user that formatted has failed. (It is embarrassing to accidentally commit non-gofmt'd code.)

* Another failure (slightly redacted):

```
[Error - 2:03:45 PM] unable to check package for file:///Users/josh/path/to/main: no packages found for /Users/josh/path/to/main.go
[Error - 2:03:46 PM] failed to deliver diagnostic for file:///Users/josh/path/to/no%20packages%20found%20for%20/Users/josh/path/to/main.go: stat /Users/josh/path/to/no packages found for /Users/josh/path/to/main.go: no such file or directory
```

That path (`/Users/josh/path/to/no packages found for /Users/josh/path/to/main.go`) looks pretty broken. :)

There may be more issues as well; that's all I noticed in the first five minutes.

The first problem (PATH) seems like something that perhaps should be fixed in VSCode. The second problem is known; it seems pretty severe, at least in my environment. I'll report the third problem upstream soonish.

In the meantime, thank you so much for the workaround. I had given up on vscode; I'll try it again.

**Comment by stamblerre** [comment]
@josharian can you update to a more recent version of `gopls` (`go get -u golang.org/x/tools/gopls@master`). One of the issues you report was fixed in https://github.com/golang/go/issues/32603.

`gopls` will not format code with syntax errors, not type errors. This is because there have been some issues with the way the `format.Node` function works (it will occasionally re-write malformed code.) We are tracking this in https://github.com/golang/go/issues/31291.

**Comment by ramya-rao-a** [comment]
> There doesn't appear to be a way to globally set a PATH envvar in vscode's settings. As a result, depending on how I happened to open gopls, the PATH would sometimes be empty. 

The PATH should never be empty unless explicitly set so. VS Code inherits all environment variables from the terminal from which it was started from. If you want to set the env variables explicitly, you can also use the `go.toolsEnvVars` setting
