### ISSUE TITLE
Selection does not work in auto-completion

### ISSUE THREAD

**Issue by w20089527** [microsoft/vscode-go#2591]
### Environment
`go version go1.12.5 linux/amd64`

![image](https://user-images.githubusercontent.com/7413974/59963562-47a88380-9527-11e9-8775-72a7f2c2cfda.png)

![image](https://user-images.githubusercontent.com/7413974/59963549-162fb800-9527-11e9-885a-1acbb0b22197.png)

### Issue

When I select an item in auto-completion, it does not work. Illustration as follows:

![vscode](https://user-images.githubusercontent.com/7413974/59963581-abcb4780-9527-11e9-8b23-45e3075c44ee.gif)

This situation happens frequently. It does very very annoying me :sob:

**Comment by ramya-rao-a** [comment]
Thanks for reporting @w20089527 
Can you share any Go related settings you might have added/edited?

**Comment by w20089527** [comment]
> Thanks for reporting @w20089527
> Can you share any Go related settings you might have added/edited?

No other special settings. Here is my project dir structure:
![image](https://user-images.githubusercontent.com/7413974/60146052-a9544080-97fa-11e9-9d17-3c70df3a5261.png)

`launch.json`
![image](https://user-images.githubusercontent.com/7413974/60146151-094ae700-97fb-11e9-9f8b-0287e2204d87.png)

Just a go project with go mod in VSCode.

**Comment by ramya-rao-a** [comment]
@w20089527 I meant the settings that can be seen by running the command `Preferences: Open Settings (JSON)`. Anything there related to `go`?

**Comment by w20089527** [comment]
@ramya-rao-a 
The whole setting as follows:
![image](https://user-images.githubusercontent.com/7413974/60154022-a5cfb200-9818-11e9-9221-0089cbb248a1.png)

I just do something on testFlags.

**Comment by stamblerre** [comment]
I see you are also using the language server - can you share your logs? Go to View: Debug Console -> Output -> Tasks -> gopls. Are there any other features that you have issues with? What happens when you save the file?

**Comment by w20089527** [comment]
Below is one situation and its `gopls` logs.

![Peek 2019-06-29 16-38](https://user-images.githubusercontent.com/7413974/60381777-a3758e00-9a8c-11e9-98db-37231142e779.gif)


![image](https://user-images.githubusercontent.com/7413974/60381764-7fb24800-9a8c-11e9-877e-14fe740c2f47.png)

**Comment by stamblerre** [comment]
Do you see any errors from the `textDocument/completion` requests in the logs?
Can you check if this happens on the latest version of `gopls` (`go get -u golang.org/x/tools/gopls@master`?

**Comment by w20089527** [comment]
Maybe it is caused by `gopls`. Currently, the `gopls`  is not stable, especially when I open several projects.
