### ISSUE TITLE
golang outline  no symbols found

### ISSUE THREAD

**Issue by kylinhao** [microsoft/vscode-go#2594]
this issue is the almost same as https://github.com/golang/go/issues/31535

it says it has been fixed, but it's version is 0.10.3, i can not find it. Now version is 0.11.0。
so do u forget to fix this bug?

hope it can be fixed as soon as possible, it always  makes me into trouble!

![image](https://user-images.githubusercontent.com/5234656/59971439-c4327500-95ae-11e9-84d3-7088bc975ffb.png)

**Comment by ramya-rao-a** [comment]
The outline feature is working as expected for me.

<img width="329" alt="Screen Shot 2019-07-06 at 3 49 35 PM" src="https://user-images.githubusercontent.com/16890566/60761818-a977eb80-a005-11e9-87cc-eb897d6660c3.png">

- Can you run the command `Go to symbol in File...` and see if you get any symbols?
- Are any of the other language features working? Like `go to definition` or auto-completion?
- Can you share any Go related settings you might have added/edited? You can get these from running the command `Preferences: Open Settings (JSON)`
