### ISSUE TITLE
High CPU usage when working with cgo

### ISSUE THREAD

**Issue by RadhiFadlillah** [microsoft/vscode-go#2598]
As title said, I'm experiencing high CPU usage when working with a `cgo` project. This problem happened everytime I type a character which can be seen [here](https://giant.gfycat.com/WateryUnnaturalCrane.webm).

Here are my `vscode-go` settings :

```
"go.formatTool": "goimports",
"go.autocompleteUnimportedPackages": false,
"go.installDependenciesWhenBuilding": false,
"go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
"go.buildOnSave": "off",
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @RadhiFadlillah 

@stamblerre Based on the settings shared above, the only tool that the Go extension calls on each letter being typed is your fork of `gocode`. Is it also responsible for the calls to gcc, go list etc?

@RadhiFadlillah Can you try the [new language server feature](https://github.com/microsoft/vscode-go#go-language-server) we have? That will avoid calling `gocode` for completion feature.

**Comment by RadhiFadlillah** [comment]
Hi @ramya-rao-a, thanks for the response.

> Can you try the new language server feature we have? That will avoid calling gocode for completion feature.

Yes, I've already tried the language server. Unfortunately, it doesn't work any better, as can be seen [here](https://giant.gfycat.com/DiligentUglyGrouper.webm). After I enabled the language server and reload the window, the CPU usage started to spike even before I type anything. Soon after, `gopls` crashed.

> ... the only tool that the Go extension calls on each letter being typed is your fork of `gocode`. Is it also responsible for the calls to gcc, go list etc?

Yes, that's also my first thought, and I was planned to submit this issue in @stamblerre repository. However, when I checked the source code for `gocode`, I didn't see any call to `go list -compiled=true` command. Hence why I decided to post this issue here.

**Comment by RadhiFadlillah** [comment]
After looking around, I found out that while `gocode` doesn't call `go list` by itself, it depends on `golang.org/x/tools/go/packages` which uses `go list`.

Since `gocode` [uses](https://github.com/stamblerre/gocode/blob/81059208699789f992bb4a4a3fedd734e335468d/internal/suggest/suggest.go#L138) `go/packages` with `LoadSyntax` mode, the `go/packages` end up [using](https://github.com/golang/tools/blob/252024b8295926254bbc18903b9b7d4f0389df2f/go/packages/golist.go#L725) `go list` with `-compiled` flag set to true, which lead to high CPU usage in cgo project.

The same thing also happened with `gopls`, because it [uses](https://github.com/golang/tools/blob/252024b8295926254bbc18903b9b7d4f0389df2f/internal/lsp/cache/view.go#L118) `go/packages` with `NeedCompiledGoFiles` mode, which lead to high CPU usage as well.

With that said, I guess the problem is not from `vscode-go`, `gocode` or `gopls`, but instead from `go/packages`.

**Comment by ramya-rao-a** [comment]
Thanks for the follow up @RadhiFadlillah!

Can you log an issue with your findings at https://github.com/golang/go/ and provide a link here?

cc @stamblerre, @ianthehat

**Comment by stamblerre** [comment]
@RadhiFadlillah are you using `go1.12`? There were some issues with `cgo` and `go/packages` that should have been improved in `go1.12`.

**Comment by RadhiFadlillah** [comment]
@ramya-rao-a sorry for late response, I've opened it in [go#32821](https://github.com/golang/go/issues/32821).

@stamblerre I'm using Go 1.12.5. Both `gocode` and `go/packages` have been updated to latest commit as well.

**Comment by stamblerre** [comment]
@RadhiFadlillah: Is this still an issue for you? [`gopls`](https://github.com/golang/tools/blob/master/gopls/doc/vscode.md) should work better for cgo than `gocode` does.
