### ISSUE TITLE
gocode.exe does not close when VS Code exits

### ISSUE THREAD

**Issue by syncore** [Microsoft/vscode-go#26]
On Windows, gocode.exe continues to run even after VS code is completely closed. I am not sure of the behavior on other platforms. Is there a way to automatically close gocode.exe when the editor itself is exited?

**Comment by lukehoban** [comment]
Yes - we should be invoking `gocode close` when the extension is deactivated to try and stop the gocode deamon.

**Comment by egamma** [comment]
just a heads-up, in 0.10.1 a deactivate() function for cleaning-up isn't supported yet.

**Comment by lukehoban** [comment]
Thanks @egamma - is there an issue already tracking this that we can link here?  

I think that means we can't really fix this for now.  Will keep this active waiting for the `deactivate` call to be added in Code.

**Comment by egamma** [comment]
you could listen on the 'exit' event of the extension host process.
```
process.on('exit', function(code) {
```

**Comment by lukehoban** [comment]
@egamma Unfortunately it doesn't look like that will work - shutting down `gocode` requires shelling out to `gocode close` and I'm not seeing that run inside the 'exit' handler.  The [node.js docs](https://nodejs.org/api/process.html#process_event_exit) say that you cannot do async work in this handler, which is likely the reason this isn't working?

> There is no way to prevent the exiting of the event loop at this point, and once all exit listeners have finished running the process will exit. Therefore you must only perform synchronous operations in this handler.

**Comment by egamma** [comment]
never tried this, but could spawning another process that runs `gocode close` work? There is a sync function to spawn a process: `childProcess.execSync`.

**Comment by lukehoban** [comment]
I tried that, and it doesn't seem to work either.  I also tried just doing a `fs.writeFileSync` and even that's not working.

**Comment by ramya-rao-a** [comment]
Closing this issue as a "won't fix" because of https://github.com/Microsoft/vscode-go/issues/26#issuecomment-254108679
