### ISSUE TITLE
Debugger fails when I hover over a variable (and at times even before hitting the first breakpoint)

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-go#260]
_From @harikb on March 15, 2016 19:37_

Environment: MacOSX 10.10.5 (Yosemite, not El Capitan). Latest VS Code 0.10.11
Debugging Golang via Delv. However the error message does not seem to be from delv.
Go plugin is the current most popular plugin `lukehoban.Go`
![image](https://cloud.githubusercontent.com/assets/952886/13791203/2990332e-eaa9-11e5-934f-176470e75af8.png)

I am able to use Delve directly for debugging.

_Copied from original issue: Microsoft/vscode-debugadapter-node#14_

**Comment by weinand** [comment]
@harikb the delv debug adapter seems to send some unexpected data back via stdout or stderr. This breaks the communication mechanism between VS Code and the debug adapter.

Moving to Go extension.

**Comment by lukehoban** [comment]
@harikb If you have a reliable repro for this - could you share?  Also - do you have the latest `vscode-go` installed?  There were some fixes related to this recently.

**Comment by lukehoban** [comment]
BTW - this sounds like it's likely the same issue as #240, and should hopefully be addressed in the `0.6.34` update which is available now.  If you are still seeing issues after that update, please reopen with more detailed steps for reproducing.
