### ISSUE TITLE
Unapproved personal package remove on saving

### ISSUE THREAD

**Issue by goyapp** [microsoft/vscode-go#2600]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1.
2.

**Comment by goyapp** [comment]
Hi, 
I am beginning to learn golang.
I first created my personal package called - mymath ( I can see mymath.a created )
import the package into the program

//%GOPATH%/src/mathapp/main.go code.package main

package main
import (
	"mymath"
	"fmt"
)
func main() {
	fmt.Println("Hello , world. sqrt(2) = %v\n", mymath.sqrt(2))
}

On saving, the package 'mymath' disappear from the import line.

Appreciate your help.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @goyapp 

Can you please share any Go related settings in VS Code that you might have changed/added?

**Comment by goyapp** [comment]
Hi ramya,
Thank you in advance for helping.

Appended below is the workspace setting from .vscode directory

C:\goProjects\.vscode>more launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }
    ]
}

BELOW is the User Settings from the directory :

 Directory of C:\Users\goyapp\AppData\Roaming\Code\User

26/06/2019  01:13 PM    <DIR>          .
26/06/2019  01:13 PM    <DIR>          ..
26/06/2019  01:16 PM    <DIR>          globalStorage
26/06/2019  01:13 PM                60 settings.json
20/06/2019  12:39 AM    <DIR>          snippets
25/06/2019  01:53 PM    <DIR>          workspaceStorage
               1 File(s)             60 bytes
               5 Dir(s)  181,963,702,272 bytes free

C:\Users\goyapp\AppData\Roaming\Code\User>more settings.json
{
    "editor.find.seedSearchStringFromSelection": false
}

**Comment by ramya-rao-a** [comment]
Thanks @goyapp 

I believe the formatting tool is causing this. Can you add the below to your settings to disable the format on save feature and try again?
```
"[go]": {
    "editor.formatOnSave": false
}
```
