### ISSUE TITLE
Debugging is not working when the project path is too long

### ISSUE THREAD

**Issue by xzzh999** [microsoft/vscode-go#2602]
Hi~ Great job!

I have confirmed: 

when debugging **a long path** project it not working, the process exit after a few seconds, but if i copied the project to **a short path** folder, it's working.

Other conditions:
```
no breakpoints or breakpoints in other files or in goroutine.
```

For example:
```
long path:  E:\work\svn\abcd\abcdefghijk\root\src\abcd\abcd2.0\test_build
result:
       API server listening at: 127.0.0.1:42720
       Process exiting with code: 0  //(exit after a few seconds)

short path: E:\work\test_build
result:
      Everything just OK.
```

Environment:
```
版本: 1.35.1 (system setup)
提交: c7d83e57cd18f18026a8162d042843bda1bcf21f
日期: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
ms-vscode.go: 0.11.0
```
go.delveConfig:
```
"go.delveConfig": {
        "useApiV1": false,
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 3,
            "maxStringLen": 1024,
            "maxArrayValues": 1024,
            "maxStructFields": -1
        }
    }
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @xzzh999 

We use [delve](https://github.com/go-delve/delve) as the debugger to provide the debugging feature. Can you try using it [via the command line ](https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_debug.md) with the 2 paths and let us know if it works as expected? 

First add `"trace": "logs"` to your debug configuration to see how exactly VS Code calls delve i.e what arguments are passed to it and then replicate it in the command line. Remember to run the command in the folder that you are trying it for

**Comment by xzzh999** [comment]
change the configure to:
```
"version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": [],
            "showLog": true,
            "trace": "log",
        }
    ]
```

here the logs:

![](https://github.com/xzzh999/markdown-pictures/blob/master/vs%20code%20debug%20log%20-%20test.png?raw=true)

**Comment by ramya-rao-a** [comment]
In the above example, did you stop debugging explicitly or did it stop on its own?

**Comment by xzzh999** [comment]
on its own

**Comment by ramya-rao-a** [comment]
In a terminal, go to the folder that is printed above as the "Current working directory". From there run the command `dlv debug`, pass the import path of the package which you see as the first argument to delve in the screenshot above. This will start delve in a interactive mode.

See https://github.com/go-delve/delve/tree/master/Documentation/cli to learn how you can set breakpoints and step through the code. If you are not able to debug successfully this way, then the problem is with delve itself
