### ISSUE TITLE
can't turn off format on save

### ISSUE THREAD

**Issue by meowao** [microsoft/vscode-go#2604]
when i save go file, it will auto format. and i have no idea how turn off this
![66](https://user-images.githubusercontent.com/13918627/60172134-9f543100-983e-11e9-9eba-27644ccbfc63.gif)

that is my setting.json in .vscode folder
![QQ图片20190626181408](https://user-images.githubusercontent.com/13918627/60172196-c7dc2b00-983e-11e9-90e5-809ba59e2322.png)

extensions version:0.11.0
vscode version:1.35.1

**Comment by ramya-rao-a** [comment]
The extension enables format on save feature specifically for Go files, so you would need the below
```
"[go]": {
    "editor.formatOnSave": false
}
```

A side note by looking at your settings

The below is not needed with the past few versions of the extension. `gopls` is the default language server we are using now
```
"go.alternateTools": {
   "go-langserver": "gopls"
}
```

**Comment by ramya-rao-a** [comment]
Your case brings up a good point though. It is not very clear on how to disable the format on save feature. I've updated our README with a note on this with https://github.com/microsoft/vscode-go/commit/019f4562f091bb6695257647f70c9098b81423f2

Thanks for reporting!
