### ISSUE TITLE
gopkgs failed to install

### ISSUE THREAD

**Issue by wtask** [microsoft/vscode-go#2605]
gopkgs failed to install from VSCode, but successfully installed from console

VSCode Version: 1.35.1 (user setup), 
OS: Windows_NT x64 10.0.18362
VSCode-Go: 0.11.0
GO111MODULE=on
GOPATH=C:\dev\go

Steps to Reproduce:
1. Ctrl+Shift+P
2. Go: Install/Update Tools
3. Select All

```
1 tools failed to install.

gopkgs:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/uudashr/gopkgs/cmd/gopkgs
github.com/uudashr/gopkgs (download)
github.com/karrick/godirwalk (download)
# cd C:\dev\go\src\github.com\karrick\godirwalk; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
	go.mod
Please commit your changes or stash them before you merge.
Aborting
package github.com/karrick/godirwalk: exit status 1
github.com/pkg/errors (download)
github.com/uudashr/gopkgs (download)
github.com/karrick/godirwalk (download)
# cd C:\dev\go\src\github.com\karrick\godirwalk; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
	go.mod
Please commit your changes or stash them before you merge.
Aborting
package github.com/karrick/godirwalk: exit status 1
github.com/pkg/errors (download)
```
4. Copy and paste install command into console:
```
D:\Users\webta\Development>go.exe get -u -v github.com/uudashr/gopkgs/cmd/gopkgs
go: finding github.com/uudashr/gopkgs/cmd/gopkgs latest
go: finding github.com/uudashr/gopkgs/cmd latest

D:\Users\webta\Development>
```
Check %GOPATH%\bin and make sure gopkgs is up-to-date now..

Also I have a question. Do I need all go-tools to install and to update so far as I use gopls?

**Comment by stamblerre** [comment]
`gopks` covers functionality that `gopls` does not yet support, so I would say you still need it.

My guess is that something modified your `go.mod` earlier before you updated `gopkgs`. Can you install if you run `go mod tidy` in that directory?

**Comment by wtask** [comment]
I just checked this issue under Go project which does not use modules and got the same erroneous result in VSCode.
I think the reference on go mod in the error details does not depend on current VSCode project (with or without module support).

**Comment by stamblerre** [comment]
When you download a tool in module mode, it can modify the `go.mod` in your current directory. However, I believe that VSCode does explicitly disable `GO111MODULE` when updating tools, so I'm surprised that this error would occur. @ramya-rao-a, what do you think?

**Comment by ramya-rao-a** [comment]
Yes, we disable `GO111MODULE` in the process that runs `go get` to install the tools. https://github.com/microsoft/vscode-go/blob/0.11.0/src/goInstallTools.ts#L314

**Comment by ramya-rao-a** [comment]
@wtask Can you share any Go related settings you might have added/edited?

**Comment by wtask** [comment]
I manually set GOPATH and GO111MODULE=on only. Which other settings do you mean?

**Comment by ramya-rao-a** [comment]
@wtask I mean the settings you see in the json file that is opened when you run the command `Preferences: Opens Settings (JSON)`

**Comment by wtask** [comment]
Hmm, I have config:
```json
 "go.alternateTools": {
    "go-langserver": "gopls"
  },
  "go.languageServerExperimentalFeatures": {
    "format": true,
    "autoComplete": true,
    "goToDefinition": true,
    "hover": true,
    "signatureHelp": true,
    "goToTypeDefinition": true,
    "documentSymbols": true,
    "workspaceSymbols": true,
    "findReferences": true,
    "rename": true,
    "diagnostics": true
  },
 "go.autocompleteUnimportedPackages": true,
  "go.buildOnSave": "off",
  "go.vetOnSave": "off",
  "go.enableCodeLens": {
    "references": false,
    "runtest": true
  },
  "go.useCodeSnippetsOnFunctionSuggest": true,
  "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
  "go.useLanguageServer": true,
  "go.languageServerExperimentalFeatures": {
    "diagnostics": true, // for diagnostics as you type
    "findReferences": true
  },
  "[go]": {
    "editor.snippetSuggestions": "none",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true,
    }
  },
  "gopls": {
    "usePlaceholders": true, // add parameter placeholders when completing a function
    // "enhancedHover": true,      // experimental to improve quality of hover (will be on by default soon)
  },

```

**Comment by ramya-rao-a** [comment]
Its not clear why the module mode would be enabled back after we expliclity disable it before running t `go get`

Can you delete the folder `C:\dev\go\src\github.com\karrick\godirwalk` and try again to install using the `Go: Install/Update Tools` command?

You mention that running `go get` from the console works. If you ran that on the external console, can you try running it in the integrated terminal in VS Code?

**Comment by wtask** [comment]
- Update for gopkgs from VSCode terminal is also successful. But the command has modified project's go.mod and go.sum, so I need to run go mod tidy to revert its changes. That behaviour does not appear when update started in external console outside Go project.
- I checked go\src\github.com\karrick\godirwalk and  go.mod/go.sum here are in modified state. After deletion the package, VSCode successfully install gopkgs: 

```
Installing 1 tool at C:\dev\go\bin
  gopkgs

Installing github.com/uudashr/gopkgs/cmd/gopkgs SUCCEEDED

All tools successfully installed. You're ready to Go :).

```
Thank you for the help!
