### ISSUE TITLE
False positive warning

### ISSUE THREAD

**Issue by wtask** [microsoft/vscode-go#2606]
From time to time VSCode-Go flashes a warning that my GOROOT has changed, but it is not true:

![nodifference](https://user-images.githubusercontent.com/45894304/60179814-2f867c00-9827-11e9-972e-b10e74d9cea6.png)

VSCode-Go: 0.11.0
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by ramya-rao-a** [comment]
Your screenshot shows that this is a casing issue. I have pushed a fix for this. Until I release an update, you can use the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension which has the fix

**Comment by ramya-rao-a** [comment]
Thanks for reporting!

**Comment by ramya-rao-a** [comment]
This issue is now fixed in the latest update (0.11.1) to the Go extension
