### ISSUE TITLE
VSCode needs to be reloaded when gopls is updated

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode-go#2607]
Would there be any interest in replacing the message after installing gopls with a call to `Go: Restart Language Server`, or a similar method instead.

```
Installing 1 tool at /Users/ebajumpa/Code/Go/bin
  gopls

Installing golang.org/x/tools/cmd/gopls SUCCEEDED

Reload VS Code window to use the Go language server
All tools successfully installed. You're ready to Go :).
```

**Comment by ramya-rao-a** [comment]
I guess now that we have a command to restart the language server, we don't need to reload VS Code window? It needs to be tested though.

If so, then we can update the code that prints this message to instead just restart the language server.

**Comment by ramya-rao-a** [comment]
cc @stamblerre

**Comment by stamblerre** [comment]
I think we could probably go as far as running the command ourselves without asking the user to, right?

**Comment by ramya-rao-a** [comment]
What is the behavior when neither VS Code is reloaded, nor the language server is restarted after an update?

**Comment by stamblerre** [comment]
I would imagine that the server wouldn't start, since we only start it on extension activation or if the restart command is executed.

**Comment by stamblerre** [comment]
This is fixed in the nightly extension by https://github.com/golang/vscode-go/pull/30.
