### ISSUE TITLE
Code coverage only shows for focused file when multiple are visible

### ISSUE THREAD

**Issue by zikaeroh** [microsoft/vscode-go#2608]
Steps to Reproduce:

1. Run the "toggle test coverage in current package" command with two files in the same package open, split so both are visible.
2. Only the file which has focus shows code coverage.

I might be remembering incorrectly, but I don't believe this used to happen. An example where I just click from one side to the other:

![image](https://user-images.githubusercontent.com/48577114/60234711-295dc300-985a-11e9-9441-7d799a8361c7.png)

![image](https://user-images.githubusercontent.com/48577114/60234714-2e227700-985a-11e9-8710-61f39e6321fb.png)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @zikaeroh 
This definitely used to work before, am not sure if something changed in the Go extension or VS Code itself to cause this.

I'd appreciate any help in figuring out the root cause here

Code Pointers:
- See [Build and Debug Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) to set up local dev environment
- `goCover.ts` is the file with all the code regarding code coverage

**Comment by zikaeroh** [comment]
I went back to 0.9.0 and tested, and the same thing happened (and I definitely didn't have this issue 3 months ago). On to the VSC bisect, I guess...

**Comment by zikaeroh** [comment]
I'm utterly confused. I went all the way back to 1.32.1 and 0.8.0, and every combination did what I showed above. Surely this worked before and I'm not insane...

**Comment by ramya-rao-a** [comment]
@zikaeroh I believe you are not insane :) I remember testing this exact feature once before.
This would mean that there is some issue with the API between VS Code and the extensions. Can you try going back to an older version of VS Code itself? You can find all versions at https://code.visualstudio.com/updates/v1_35

**Comment by zikaeroh** [comment]
That's what I did, I built VS Code from source after failing to bisect this repo (thinking I'd bisect it instead), but even bringing that back to 1.32.1 didn't fix it. I don't remember this not working back then, hence my confusion.

**Comment by ramya-rao-a** [comment]
Ah! found the issue, looks like the bug got introduced about 9 months ago.
I have pushed a fix.
Can you give it a try by getting the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension?

**Comment by zikaeroh** [comment]
Yes, it seems to be working. Thank you!

**Comment by ramya-rao-a** [comment]
Thanks for reporting @zikaeroh!

This issue is now fixed in the latest update (0.11.1) to the Go extension
