### ISSUE TITLE
Autoimports not working with GoPls if inside a workspace

### ISSUE THREAD

**Issue by bragagia** [microsoft/vscode-go#2609]
I am experiencing an issue everytime i'm trying to work on a Go project loaded with other projects inside a single workspace.

The Go project uses Go modules, and i'm using GoPls.

It sometimes works when I open the go project, and only then add more folders to the workspace.

Steps to reproduce :
- Open a workspace with a Go project and anything else.
- Create a main.go : 
```Go
package main

func main() {
    fmt.Println("Hello, world !\n")
}
```
- Save

I would expect autoimports to be triggered when saving the file but nothing happens.

**Comment by stamblerre** [comment]
Which version of `gopls` are you using (`gopls version`)? This sounds like an error that was fixed a few weeks ago. You can update by running (`go get -u golang.org/x/tools/gopls@master`).

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity
