### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ankitforcode** [microsoft/vscode-go#2612]
- Issue Type: `Bug`
- Extension Name: `Go`
- Extension Version: `0.11.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 177,
		"activateCallTime": 5,
		"activateResolvedTime": 1012,
		"activationEvent": "onLanguage:go"
	},
	"runtimeErrors": []
}
```

**Comment by ramya-rao-a** [comment]
Can you please proved more details on what the issue here is?

**Comment by ankitforcode** [comment]
This runs very slow during active development. During the initial startup, the includes and imports work fine but get slower by time.

**Comment by ramya-rao-a** [comment]
Can you share the Go related setting you might have added/edited? You can find these by running the command `Preferences: Open Settings (JSON)`.

Also, the next time this happens, can you run the command `Developer: Open Process Explorer`? This will show all the processes started by VS Code, their CPU and memory consumption. This will give an idea on what is going on

**Comment by ankitforcode** [comment]
```{
    "window.zoomLevel": 0,
    "extensions.ignoreRecommendations": false,
    "editor.formatOnSave": true,
    "python.pythonPath": "python3",
    "git.confirmSync": false,
    "git.autofetch": true,
    "files.associations": {
        "*.tmpl": "json"
    },
    "json.format.enable": true,
    "terraform.format": {
        "enable": false,
        "ignoreExtensionsOnSave": [
            ".tfsmurf"
        ],
        "formatOnSave": false
    },
    "workbench.editor.enablePreview": false,
    "workbench.colorTheme": "Visual Studio Light"
}```

**Comment by ramya-rao-a** [comment]
Based on your settings, you are using the Go extension as is, out of the box without any customization. In this case, the next step is to use the process explorer as mentioned in https://github.com/microsoft/vscode-go/issues/2612#issuecomment-507916527 to figure out the culprit

**Comment by ramya-rao-a** [comment]
Are you using Go modules?
