### ISSUE TITLE
Issue with mongo-go-driver

### ISSUE THREAD

**Issue by farzadmf** [microsoft/vscode-go#2613]
Hi,

Steps:
1. Create code
```bash
mkdir mongo-test
cd mongo-test
go mod init mongo-test
go get go.mongodb.org/mongo-driver/mongo
code .
```
2. Now, in VSCode, I create a `context`, and when I type this:
```go
client, err := mongo.Client
```
and I do `Ctrl + .` on it, and then select `Organize all imports`, it imports the package like this:
```
"github.com/mongodb/mongo-go-driver/mongo"
```
So, my final code will look like this (if I rely on VSCdoe to organize imports):
```go
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/mongodb/mongo-go-driver/mongo"
	"github.com/mongodb/mongo-go-driver/mongo/options"
)

func main() {
	ctx, _ := context.WithTimeout(context.Background(), 10*time.Second)
	client, err := mongo.Connect(ctx, options.Client().ApplyURI("mongodb://localhost:27107"))
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(client)
}
```

But I see this error:
![image](https://user-images.githubusercontent.com/5768792/60345003-fadd0680-9985-11e9-9075-58ef3cd4c15f.png)

I have to manually change the imports to be this:
```go
import (
	// ...
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)
```

But, then it seems that extension gets confused because IntelliSense and everything else (format on save etc.) stops working, and I have to restart VSCode to get back to a working environment

**Comment by ramya-rao-a** [comment]
Can you please share any Go related settings you might have added/edited?

**Comment by farzadmf** [comment]
Thank you @ramya-rao-a for your follow-up. Actually, I tested in my Linux home computer, and it seems to be working fine, and this was happening on my Windows work computer.

There's actually another thing I did with my Windows: first time, I did `go get github.com/mongodb/mongo-go-driver` (in my go module directory), and later I realized that the Github `README` says to use `go.mongodb.org/mongo-driver/mongo`, so I did that.

Is it possible that the first `go get` that I did was messing things up there? The only setting I have in my personal settings related to go is `"go.useLanguageServer": true`. If you think the `go get` wasn't responsible for this issue, I can try to update go tools on my Windows and try again

**Comment by ramya-rao-a** [comment]
Since you are using the language server, most features are coming from it like build errors and completion.
@stamblerre Would you have some ideas here as to why the wrong imports are getting added by the `Organize Imports` feature?

**Comment by stamblerre** [comment]
@farzadmf: I think you're right that the first `go get` would be the cause of this problem. If you have a directory `github.com/mongodb/mongo-go-driver` under your `$GOPATH`, you may want to delete it. Likely the 2 directories are confusing `goimports`.

**Comment by farzadmf** [comment]
Thank you @stamblerre . That's what I was suspecting. I close this and re-open in case the issue is still there.
