### ISSUE TITLE
gopls: Ctrl-Click in import section both leads to opening doc page in browser and in editor

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode-go#2614]
OS: Windows 10
VS Code: 1.35.1
vscode-go: 0.11.1-beta.1

For example, clicking (Ctrl-Click) on `fmt` here leads to opening `scan.go` in new tab in editor while at the same time godoc tab with fmt is silently opened in browser on background.
![изображение](https://user-images.githubusercontent.com/6797881/60362045-91421400-99e8-11e9-99ec-b2200269acc2.png)

**Comment by stamblerre** [comment]
This can be disabled by setting

```json5
"go.languageServerExperimentalFeatures": {
    "documentLink": false
}
```

**Comment by inliquid** [comment]
@stamblerre is opening two things fine? This start happening at some point back in time, as I remember this wasn't acting like this before. I think it should either open one, or another, basically being controlled by some setting. F.e. I'd like to have godoc option only, without seeing some random file from that package (why `scan.go`?).

**Comment by stamblerre** [comment]
This is a result of VSCode playing strangely with LSP. Basically, CTRL + Click is a shortcut for jump to definition, which `gopls` isn't aware of (it just knows that it received a jump-to-definition request), but CTRL + Click is also the shortcut for clicking on links in a VSCode file. The `documentLink` feature is sent per-file, so `gopls` has no idea if you've clicked on a link, it just sends information about all of the available links in the file. 

One approach would be to disable jump-to-definition for import paths. We pick the longest, or "most interesting" file in a package as the "definition" for an import path, hence `scan.go`.

@ramya-rao-a, what do you think?

**Comment by ramya-rao-a** [comment]
@stamblerre `gopls` has information on all available links as well as the position where the definition request was made from. When the position is known to be part of the link, can it not return empty results for the definition request?

**Comment by stamblerre** [comment]
It could - that's what I was referring to when I suggested disabling jump to definitions for import paths. My issue is more that some users may prefer jumping to definitions of import paths, versus some may prefer opening the Godoc for an import path. I'm not certain that the right approach would be to completely remove the jump to definition behavior (for example, what if a user doesn't have an Internet connection while working?).

**Comment by ramya-rao-a** [comment]
> My issue is more that some users may prefer jumping to definitions of import paths,

I didnt realize that was a feature that was supported :) A package can have multiple files. Which file do you land on when a definition request is made on a package?

**Comment by stamblerre** [comment]
We pick the longest file in a package (this is just a heuristic, we assume that the longest file is the "most interesting"). We could definitely disable this behavior though.

**Comment by ramya-rao-a** [comment]
We had a feature request to do exactly this, see #330
Since there is no single destination in case of multiple files in a package, we settled on 
- not using ctrl+click to do this, but use a command 
- use a quick pick control to show all the files

I would suggest to disable this feature and just keep the document links. Having the same keyboard shortcut trigger 2 separate features is not user friendly

**Comment by daqingshu** [comment]
> We had a feature request to do exactly this, see #330
> Since there is no single destination in case of multiple files in a package, we settled on
> 
> * not using ctrl+click to do this, but use a command
> * use a quick pick control to show all the files
> 
> I would suggest to disable this feature and just keep the document links. Having the same keyboard shortcut trigger 2 separate features is not user friendly

how about if the package is priavte host on enterprise github? open the document links just 404.

**Comment by stamblerre** [comment]
I think the solution you are describing, Ramya, would be to send back a list of locations for a go-to-definition request, which I think can be done. Filed # to track this.
I'm not sure how to handle private packages - perhaps we can test that the links are valid in `textDocument/documentLink`, but that may be too expensive.

**Comment by ramya-rao-a** [comment]
@stamblerre That will still not solve the original problem here which is that 2 separate operations are being triggered by the same user action.

**Comment by stamblerre** [comment]
Agreed. I think this is a case where the editor should decide what to do with the Ctrl + Click shortcut. `gopls` has no control over this behavior, and it seems quite clear to me that both jump to definition and document link should work correctly for import statements.

**Comment by stamblerre** [comment]
I left a comment (https://github.com/microsoft/vscode/issues/81520#issuecomment-578546940) on https://github.com/microsoft/vscode/issues/81520, which is a report of this issue to VS Code, so we can follow the advice given there once we get a response.

**Comment by stamblerre** [comment]
I've opened an upstream `gopls` issue to track this (https://github.com/golang/go/issues/39065), so I'll close this one now.
