### ISSUE TITLE
snippets: add friendly failing test output snippet

### ISSUE THREAD

**Issue by tkivisik** [microsoft/vscode-go#2615]
I propose two snippets for friendly failing test output as 10 upvotes are required for the PR to get accepted.
Snippet would ask 5 slots to be filled in:
```t.Fatalf("1(2) = 3, want 4", 5)```

Example result:
```t.Fatalf("sum(%d, %d) = %d, want %d", a, b, got, want)```

```
"test got want error": {
	"prefix": "gwe",
	"body": "t.Errorf(\"${1:funcName}(${2:args}) = ${3:got}, want ${4:want}\",${5:vars})",
	"description": "Snippet for a failing test output. E.g. t.Errorf(\"sum(%d, %d) = %d, want %d\", a, b, got, want)"
},
"test got want fatal": {
	"prefix": "gwf",
	"body": "t.Fatalf(\"${1:funcName}(${2:args}) = ${3:got}, want ${4:want}\",${5:vars})",
	"description": "Snippet for a fatal test output. E.g. t.Fatalf(\"sum(%d, %d) = %d, want %d\", a, b, got, want)"
}
```

**Comment by tkivisik** [comment]
Nice, more than 10 upvotes gathered. It's ready to be merged and solved.

**Comment by tkivisik** [comment]
@ramya-rao-a , would you be able to give this a look?

**Comment by stamblerre** [comment]
@tkivisik: I'm sorry about closing your PR and the delay on replying to it. As I said, we're planning on reevaluating the snippets provided by this extension as a whole, so we won't be introducing new snippets for the time being. However, I have noted your feature request [here](https://github.com/microsoft/vscode-go/issues/2380#issuecomment-629041632) and we will consider it as part of our review.
