### ISSUE TITLE
Replace gorename with gopls' rename feature

### ISSUE THREAD

**Issue by jclc** [microsoft/vscode-go#2618]
`gorename` has never worked on projects outside the $GOPATH. Instead of updating `gorename`, the Go team has instead decided to add the same functionality to `gopls` and abandon `gorename`. vscode-go should replace the old renaming functionality with that of `gopls`.

reference: https://github.com/golang/go/issues/27571#issuecomment-506592987

**Comment by ramya-rao-a** [comment]
If the user has enabled the use of language server and has the latest version of `gopls`, then the rename feature will be coming from `gopls` and not `gorename`. The code needed to do this is already in place

Are you suggesting that this extension use `gopls` for the rename feature even if user has not opted to use the language server?

**Comment by jclc** [comment]
I'm sorry, I wasn't aware `gopls` renaming was in already. I reinstalled the extension and it works great now!
