### ISSUE TITLE
GOOS file suffix ignored for compilation

### ISSUE THREAD

**Issue by mreynolds** [microsoft/vscode-go#2619]
This seems related to #1848.

For reference : https://blog.ralch.com/tutorial/golang-conditional-compilation/

Steps to Reproduce:

1. Create a file `mymodule.go`
2. Create a GOOS conditional compilation for current platform (say `mymodule_linux.go`)
```
package test

var string v = "test"
```

3. Create a GOOS conditional compilation for a separate platform (say `mymodule_darwin.go`)
```
package test

var string v = "test"
```

VSCode-go treats both files as actively compile-able and, if code is repeated (say a var in the package scope) in both files, VSCode-go lists them as "redeclared" despite only one of them being compile-able on the current platform.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @mreynolds 

The fix for #1848 will resolve this issue to
So, closing this in favor of #1848
