### ISSUE TITLE
Package not found error from language server

### ISSUE THREAD

**Issue by phungvandat** [microsoft/vscode-go#2620]
- VSCode Version: 1.35.1 
- OS Version: Macos 10.13.6
- Go Version: 1.12.6

I installed all packages from the suggested Go extension. But when I tried to import a package from GOPATH I was not recommend. The error .go file immediately does and not ref to the previously imported pakage. I turned off vscode and rebooted it before I ran out of errors.

**Comment by ramya-rao-a** [comment]
@phungvandat I am not able to understand what the problem is. Can you provide steps and screenshots?

**Comment by phungvandat** [comment]
> @phungvandat I am not able to understand what the problem is. Can you provide steps and screenshots?

[https://github.com/phungvandat/chatrealtime/blob/master/bug.gif](https://github.com/phungvandat/chatrealtime/blob/master/bug.gif)
You can view at here

**Comment by ramya-rao-a** [comment]
Thanks @phungvandat. From the gif, I could determine the below points
- You are using Go modules
- You are using the Go language server
- The error shows while typing the new import statement and doesn't go away

@stamblerre Thoughts?

**Comment by ramya-rao-a** [comment]
@phungvandat Can you share a screenshot of the entire error? The gif doesn't show the complete error?

**Comment by stamblerre** [comment]
This looks like https://github.com/golang/go/issues/32797, which is fixed at tip. @phungvandat: Can you update your version of `gopls` to master (`go get -u golang.org/x/tools/gopls@master`)?

**Comment by phungvandat** [comment]
> This looks like [golang/go#32797](https://github.com/golang/go/issues/32797), which is fixed at tip. @phungvandat: Can you update your version of `gopls` to master (`go get -u golang.org/x/tools/gopls@master`)?

I tried and succeeded. Thank you very much

**Comment by phungvandat** [comment]
> Thanks @phungvandat. From the gif, I could determine the below points
> 
> * You are using Go modules
> * You are using the Go language server
> * The error shows while typing the new import statement and doesn't go away
> 
> @stamblerre Thoughts?

I fixed the error when importing moduels. But I still have no suggestions when trying to import existing moduels in GOPATH or Go default like "fmt" "os", ....

**Comment by phungvandat** [comment]
I tried import a moduel inside GOPATH but get this error: 

> "could not import github.com/phungvandat/life-cafe-backend/ (no parsed files for package github.com/phungvandat/life-cafe-backend/)"

![image](https://github.com/phungvandat/Vscode-bugs/blob/master/Screen%20Shot%202019-07-09%20at%2013.54.17%20(2).png?raw=true)

**Comment by stamblerre** [comment]
Do you always manually type the imports, or do you use `goimports` to add them?
It actually still looks like `gopls` got stuck because it isn't reading the full package path.
What happens when you reload the VSCode window? Does it work?

**Comment by phungvandat** [comment]
> Do you always manually type the imports, or do you use `goimports` to add them?
> It actually still looks like `gopls` got stuck because it isn't reading the full package path.
> What happens when you reload the VSCode window? Does it work?

I always manually type the imports. I have restarted the VScode but it still doesn't work

**Comment by stamblerre** [comment]
Can you confirm your `gopls` version (`gopls version`)? Can you share your `gopls` logs (View: Debug Console -> Output -> Tasks -> gopls)?

**Comment by phungvandat** [comment]
> Can you confirm your `gopls` version (`gopls version`)? Can you share your `gopls` logs (View: Debug Console -> Output -> Tasks -> gopls)?

This is information 
```
golang.org/x/tools/gopls v0.1.3
golang.org/x/tools/gopls@v0.0.0-20190710184609-286818132824 h1:WOA3PhHc1h4W4Ho8Wm6aZ9D+nAKR1strK6cCh+lb9fM=
```
My Debug Console and Output is empty.

**Comment by stamblerre** [comment]
Were you unable to go to the "Tasks" section of the output and find "gopls"? There should definitely be logging there. Please see the information here: https://github.com/golang/go/wiki/gopls#troubleshooting.

**Comment by phungvandat** [comment]
> Were you unable to go to the "Tasks" section of the output and find "gopls"? There should definitely be logging there. Please see the information here: https://github.com/golang/go/wiki/gopls#troubleshooting.

This is my console when I try to import package inside GOPATH. 

![image](https://github.com/phungvandat/Vscode-bugs/blob/master/Screen%20Shot%202019-07-21%20at%2001.29.39.png?raw=true)

```
[Error - 1:27:02 AM] no highlight for /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:13:52: /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:13:52 is not an identifier
[Error - 1:27:06 AM] Request textDocument/codeAction failed.
  Message: /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:7:2: invalid import path: ""
  Code: 0 
[Error - 1:27:21 AM] Request textDocument/codeAction failed.
  Message: /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:7:2: invalid import path: ""
  Code: 0 
[Error - 1:27:22 AM] Request textDocument/codeAction failed.
  Message: /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:7:2: invalid import path: ""
  Code: 0 
[Error - 1:27:38 AM] Request textDocument/hover failed.
  Message: no import for "github.com/p"
  Code: 0 
[Error - 1:27:38 AM] no highlight for /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:7:3: /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:7:3 is not an identifier
[Info  - 1:27:48 AM] no completions found for file:///Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:6:2: this is a definition, of package _ ("github.com/p")
[Error - 1:27:52 AM] Request textDocument/hover failed.
  Message: no import for "github.com/p"
  Code: 0 
[Error - 1:27:52 AM] no highlight for /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:7:17: /Users/phungvandat/go/src/github.com/phungvandat/life-cafe-backend/http/encode/encode.go:7:17 is not an identifier
[Error - 1:28:52 AM] Request textDocument/hover failed.
  Message: no import for "github.com/phungvandat/"
  Code: 0 

```

**Comment by stamblerre** [comment]
Do you mind opening an issue on the Go issue tracker: https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Agopls? Basically, what's going wrong here is that `gopls` tries to detect when your imports change so that it can determine the package metadata, but when you manually type imports it's constantly re-running `go list`, which is expensive. We need to figure out a good solution to this problem.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@phungvandat Please log an issue in the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)
