### ISSUE TITLE
Go/Peek Implementation calls guru and loads 100% of all CPU cores

### ISSUE THREAD

**Issue by eugeneradionov** [microsoft/vscode-go#2621]
When trying to Go/Peek Implementation my computer gets stacked and all CPU cores 100% loaded.

**Project Structure**
Have opened `project_root` folder with 3 microservices in vscode
```
$GOPATH
├── bin
├── pkg
└── src
    └── gitlab.com
        └── eugeneradionov
           └── project_root
              └── service1
              └── service2
              └── service3
```

**htop**
![image](https://user-images.githubusercontent.com/11798339/60424199-7cd46600-9bf8-11e9-8866-f10ca1ccb27e.png)

**Go config**
```json
        "[go]": {
            "editor.insertSpaces": false,
            "editor.formatOnSave": true
        },
        "go.lintOnSave": "package",
        "go.lintTool": "gometalinter",
        "go.lintFlags": [
            "--fast"
        ],
        "go.useCodeSnippetsOnFunctionSuggest": true,
        "go.autocompleteUnimportedPackages": true,
        "go.formatTool": "goreturns",
        "go.gotoSymbol.includeImports": true,
```

**System Information**
Ubuntu 18.04.2 LTS 64-bit
GNOME 3.28.2

**Comment by ramya-rao-a** [comment]
Thanks for reporting @eugeneradionov 
I see multiple instances of `guru` in the screenshot. Is the high cpu usage from calling goto/peek implementation multiple times or is this from a single call?

**Comment by eugeneradionov** [comment]
@ramya-rao-a single call only. I call go/peek implementation from the editor once and see loading bar for 2-4 seconds and after that I have 100% CPU usage and can't even move the mouse and have to reload the computer

**Comment by jeremyHD** [comment]
I've got the same issue on my macOS.
Need some help here.

**Comment by ramya-rao-a** [comment]
Thanks @eugeneradionov 

That looks like an issue with `guru` itself failing to find the results.

Can you try to run `guru` from the command line and see if that yields any results?
`guru -scope the-import-path-to-your-package/.... -json implements path-to-current-file:#offset`

-  the-import-path-to-your-package: like `github.com/golang/example/hello`
-  offset: Install the [show-offset](https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset) extension, place cursor over the word for which you find to find the implementations, the status bar below should give you the offset

**Comment by eugeneradionov** [comment]
@ramya-rao-a 
it loads all cores as well and executing during ~30-60 sec but returns the result
```
$ guru -scope gitlab.com/my/project/... -json implements persistence/my_interface.go:#85                                                                                                                 
{
	"type": {
		"name": "gitlab.com/my/project/src/persistence.MyInterface",
		"pos": "/home/user_name/Projects/go/src/gitlab.com/my/project/src/persistence/my_interface.go:7:6",
		"kind": "interface"
	},
	"to": [
		{
			"name": "*gitlab.com/my/project/src/persistence/postgres/impl.implDAO",
			"pos": "/home/user_name/Projects/go/src/gitlab.com/my/project/src/persistence/postgres/impl/impl.go:9:6",
			"kind": "pointer"
		}
	]
}

```

**Comment by ramya-rao-a** [comment]
Thanks @eugeneradionov 

We have an ongoing effort to add timeouts to requests that spawn external tools like `guru`, but that will not fix the cpu issue :(

Long term, we are looking at [gopls](https://github.com/golang/go/wiki/gopls) to provide a better solution for finding references and implementation.

Closing this issue as unfortunately, there isnt much we can do at this point from the extension's side.
