### ISSUE TITLE
gbimporter: no package found

### ISSUE THREAD

**Issue by zhwentao** [microsoft/vscode-go#2622]
go version: go1.11 darwin/amd64
packages are all in gopath

debug output:
2019/07/01 17:00:35 -------------------------------------------------------
2019/07/01 17:00:35 gbimporter: no package found for golib/commArray: can't find import: "golib/commArray"
2019/07/01 17:00:35 gbimporter: no package found for golib/utils: can't find import: "golib/utils"
2019/07/01 17:00:35 gbimporter: no package found for golib/utils/conv: can't find import: "golib/utils/conv"

**Comment by ramya-rao-a** [comment]
Are you able to debug using [delve](https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_debug.md) directly on the terminal?
