### ISSUE TITLE
Action "restart language server" doesn't work

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode-go#2633]
Sometimes it works (in normal situation), but if there are any problems with `gopls`, in most of the cases, "restart language server" dosn't work and full restart of VS Code required.

For instance
1. Called "restart language server", `gopls` disappeared from list of outputs by `Ctrl-Shift-U`
2. Task list shows `gopls`
![изображение](https://user-images.githubusercontent.com/6797881/60745870-d7691b80-9f84-11e9-8d23-aa048a794618.png)
3. Another calls of "restart language server" do nothing, language features don't work
![изображение](https://user-images.githubusercontent.com/6797881/60745916-15663f80-9f85-11e9-8e63-80ae36d9de3f.png)
 4. VS Code restart required.

VS Code: 1.36.0
vscode-go: 1.11.1

**Comment by ymmt2005** [comment]
I saw this with vscode-go 0.11.2 several times.
A workaround is to kill `gopls` manually, say, by `pkill gopls`.

**Comment by ramya-rao-a** [comment]
@stamblerre Have you seen this command to be working as expected?

**Comment by diaochan** [comment]
VS Code: 1.36.1
go1.11.5
also have this probem

**Comment by stamblerre** [comment]
I had to admit that I typically use the "Developer: Reload Window" when I want to restart VSCode, but I can investigate this issue further.

**Comment by SteelPhase** [comment]
Sad to see this isn't working like I expected it would. Are there any ideas on how I could improve the  gopls restart command?

**Comment by itcuihao** [comment]
So sad."Reload VS Code window after installing the Go language server".

**Comment by stamblerre** [comment]
@SteelPhase: I will take a look at fixing this. I believe the issue is that we aren't clearing diagnostics from the language server before restarting it.

@itcuihao: The need to reload VSCode after installing the language server is separate from this issue, and should only be a one-time issue. The reason for this is that VSCode behaves very differently on startup if it is using the language server or not. We could potentially do some work to change this.

**Comment by ramya-rao-a** [comment]
There have been quite a few changes in the extension since September around the area of how we handle the language server, one of which was to clear the diagnostics.

The `Restart Language Server` command should now be working as expected.
