### ISSUE TITLE
Autocomplete does not work as expected

### ISSUE THREAD

**Issue by wtask** [microsoft/vscode-go#2635]
I bored to fight with VSCode-GO and gopls integration:

```
type Foorer interface {
   Foo()
}

type Bar struct {
   foo Foorer
}

func(b *Bar) Work() {
   b.foo.?
}
```
Autocompletion on dot after b.foo suggests anything but not Foo() method of Foorer... It suggests standard Go types, vars somewhere outside, everything BUT NOT Foo()!
Lets type `F`. OMG, now i see Foo(). 
Should I always need to type the first letter for method from now?

**Comment by ramya-rao-a** [comment]
I see the expected autocompletions 

![foobar](https://user-images.githubusercontent.com/16890566/60760751-86424180-9fef-11e9-870e-f5a325f0ae74.gif)

Can you share any Go related settings you might have added/edited? You can find these by running the command `Preferences: Open Settings (JSON)`

**Comment by bryonbaker** [comment]
@wtask - check the modules you have installed. I had exactly the same problem until I installed all the go modules.

**Comment by ramya-rao-a** [comment]
Works fine for me when using modules and the language server.

Please share any Go related settings you might have added/edited. You can find these by running the command Preferences: Open Settings (JSON)

**Comment by wtask** [comment]
It works fine only for one-file app. Inside internal package autocompletion constantly stop working in following cases:
- if package contains several files and one of them has a syntax error, then autocompletion is not working for all package files
- always fails for `defer` statements as for single call `defer type.field.?` as far for deffered function call `defer func(){.?.}()`.

Also there is a problem with autocompletion after the newly file was added to package (and was saved). Language server always fails on the `package` statement with error "{...file...} is not part of a package". This error also can stop autocompletion for the whole project. Restarting LSP helps remove this error, but I need to restart gopls again and again...

**Comment by stamblerre** [comment]
The defer error is a known issue, tracked here: https://github.com/golang/go/issues/29313.
For specific problems with `gopls` autocompletion, please file a separate issue on the Go issue tracker (https://github.com/golang/go/issues) with a repro case.
