### ISSUE TITLE
Parameter name hints shown inline all the time (like GoLand/JetBrains)

### ISSUE THREAD

**Issue by RelicOfTesla** [microsoft/vscode-go#2636]
like JetBrains Goland
like vscode extension "JS Parameter Annotations"
----

![go_parameter_hints](https://user-images.githubusercontent.com/4145299/60759715-44031980-a05c-11e9-863e-3377ed69f9ea.png)

**Comment by oneslash** [comment]
I think it’s more for vscode repository

**Comment by ramya-rao-a** [comment]
Hey @RelicOfTesla,

Thanks for reporting.

I do see the merits of this feature, although I am afraid I don't believe this extension is the right place for it. 

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features. 

Therefore, one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.

This can be achieved by using api for decorations. See https://vscode.rocks/decorations/ or https://github.com/Microsoft/vscode-extension-samples/tree/master/decorator-sample for examples on how to use decorations.

Happy Coding!
