### ISSUE TITLE
Default GOPATH not being detected

### ISSUE THREAD

**Issue by jayschwa** [microsoft/vscode-go#2637]
Possible regression related to #1879 with VSCode v1.36.0 and Go extension v0.11.2.

When I open a Go project with no explicit `GOPATH` set, I get the following notifications:

![vscode-go](https://user-images.githubusercontent.com/475017/60772167-73e40880-a0c0-11e9-8a6b-be0a978ffdd3.png)

Clicking on the "Install All" button produces the following error:

> Cannot install Go tools. Set either go.gopath or go.toolsGopath in settings.

Run from VSCode's integrated terminal:
```
$ go version
go version go1.12.6 linux/amd64
$ echo $GOPATH

$ go env GOPATH
/home/jayschwa/go
```

"Go: Current GOPATH" from the command palette returns "undefined is the current GOPATH."

**Comment by ramya-rao-a** [comment]
Thanks for reporting @jayschwa 

I have a bad feeling that this is a regression.. Can you please try out a couple of older versions of the Go extension to see if the GOPATH was being determined correctly before? 

You can find the older versions at https://github.com/microsoft/vscode-go/releases
Download the vsix file and then run the command `Extensions: Install from VSIX...`

**Comment by jayschwa** [comment]
v0.9.0 did not work either. Same behavior.

**Comment by ramya-rao-a** [comment]
May be there is a race condition somewhere...
Do you mind [setting up a local dev set up](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) for the extension and debugging the extension?

Add breakpoints below
- Add breakpoint at https://github.com/microsoft/vscode-go/blob/0.11.4/src/goMain.ts#L345. This should be hit when you run the command `Go: Current GOPATH`
- Add breakpoint at https://github.com/microsoft/vscode-go/blob/0.11.4/src/goInstallTools.ts#L445. This is where the result of `go env GOPATH` is parsed to find the gopath

**Comment by jayschwa** [comment]
My debugging session is showing something strange. The implementation of `cp.execFile` that gets called has most of its args commented out. The only thing being passed through is the path to the Go executable.
![vscode_wtf](https://user-images.githubusercontent.com/475017/60982248-c104ec00-a305-11e9-8471-c98a8b820ab8.png)

**Comment by jayschwa** [comment]
The values in the `cp.execFile` callback: `err` is `null` and both `stdout` and `stderr` are `""`.

**Comment by jayschwa** [comment]
If I change the sub-command in the `execFile` to be nonsense, `err` is populated. It seems like Go is being called, but `stdout` and `stderr` aren't being copied correctly.

**Comment by jayschwa** [comment]
Found upstream issue https://github.com/microsoft/vscode/issues/75581. Closing this one. Thanks.
