### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by chriswilliams1977** [microsoft/vscode-go#2638]
Hello,

I seem to encounter continuing issues with the autocomplete for GO in VS Code. I have version 1.35.1 running with extension 0.11.3. I am not getting any intellisense at all. I have try to reinstall but this still does not work. My settings file is as follows:

{
    "window.zoomLevel": 1,
    "go.formatTool": "gofmt",
    "go.autocompleteUnimportedPackages": true,
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.useCodeSnippetsOnFuctionSuggest": true,
    "go.formatOnSave": false,
    "go.formatTool": "goreturns"
    },
    "go.useLanguageServer": true
}

Please help.

Best
Chris

**Comment by ramya-rao-a** [comment]
cc @stamblerre

**Comment by stamblerre** [comment]
Can you share your `gopls` logs please? They can be found by going to "View: Debug Console" -> "Output" -> "Tasks" -> "gopls".

**Comment by chriswilliams1977** [comment]
Hi Rebecca,

I managed to get it working. I am using Go modules thus I had to play
around with the settings.json to get things working. I am currently using
the following:

{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goimports",
    "go.gocodeAutoBuild": false,
    "go.toolsEnvVars": {
        "GO111MODULE": "on",
    },
    "window.zoomLevel": 1,
}


Best
Chris

**Comment by ramya-rao-a** [comment]
@chriswilliams1977 Looks like you disabled the use of language server to get things working.
That's unfortunate as we are advocating the use of language server especially when using modules.

Regardless, if you do end up enabling it again, share the logs with us next time.

Happy Coding!
