### ISSUE TITLE
gorename invocations do not honor go.gopath

### ISSUE THREAD

**Issue by jmmv** [Microsoft/vscode-go#264]
If the user's `go.gopath` configuration setting contains more than one directory and the `GOPATH` environment variable is not defined to match that value, invocations of gorename fail because gorename cannot find all packages.

The problem is that the code in `goRename.js` to execute the gorename tool only queries `GOPATH` from the environment but does not look up the value of the `go.gopath` property defined in `settings.json` for the workspace.

**Comment by lukehoban** [comment]
What error exactly are you seeing?  Are you on Windows?

> The problem is that the code in goRename.js to execute the gorename tool only queries GOPATH from the environment but does not look up the value of the go.gopath property defined in settings.json for the workspace.

I expect that's not actually the problem.  The `go.gopath` is used to overwrite `process.env.GOPATH` inside `vscode-go`.  That said, it looks like the code there doesn't handle multi-part GOPATH.  But that should only cause a problem on Windows.

**Comment by jmmv** [comment]
Hmm, maybe you are right. What I did before was copy/paste the failed gorename command in the terminal and got an error saying that it could not find the package for my source file. Then, after adjusting `GOPATH` on that manual invocation, the error changed to something else—so the rename was failing anyway for other reasons. I cannot make this fail now in any other way, so I guess it works.

And no, this is not on Windows.

Thanks for the fix and for the great plugin!
