### ISSUE TITLE
Plugin generates uncompilable package name

### ISSUE THREAD

**Issue by jadekler** [microsoft/vscode-go#2641]
1. Create folder named "foo-bar"
2. Right click folder
3. Create new .go file (with any name)

It gets generated as:

```
package foo-bar # does not compile because it has a hyphen

import (
)

```

**Comment by jadekler** [comment]
Also, BTW, I would argue that the import statement should be elided, since gofmt would remove it.

**Comment by ramya-rao-a** [comment]
This extension does not generate contents for the file when it is created....
Are you referring to the auto-completion result for when you type `package`?

**Comment by jadekler** [comment]
Ah, hm. I could've sworn it is generated when I create the file, but now I can't get it to reproduce.
