### ISSUE TITLE
File -> Save All does not run golint 

### ISSUE THREAD

**Issue by 10x10sw** [microsoft/vscode-go#2642]
Issue Type: <b>Bug</b>

I made changes to several files in my golang project, chose File -> Save All in VS Code, and then entered "go build" in the terminal. But there were several build errors due to missing imports and the build failed. Manually saving each changed file in VS Code ran golint on save, and added the missing imports. File -> Save All should run golint if that option is enabled for File -> Save. 

Extension version: 0.11.3
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

**Comment by ramya-rao-a** [comment]
Unfortunately, there is no API from vscode to signal multiple files being saved at once. Therefore, at its current state, it is not trivial for the Go extension to react to Save All command and trigger build/lint/vet processes for all the files saved.

An alternative in such scenarios for you is to manually run the build/lint/vet command. You can assign your own keybindings to these commands in case you find yourself using them often.
- Go: Build Current Package
- Go: Vet Current Package
- Go: Lint Current Package
- Go: Build Workspace
- Go: Vet Workspace
- Go: Lint Workspace
