### ISSUE TITLE
file:///path/to/file/main.go is not part of a package - LSP

### ISSUE THREAD

**Issue by Wulfheart** [microsoft/vscode-go#2644]
Hello,

after setting up a project via gomod I get the following error when hovering over the package: 
```
file:///path/to/file/main.go is not part of a package - LSP
```

But it compiles just fine but the autocomplete e.g. for package names is not working.

I made a repo with my current situation: https://github.com/Wulfheart/vscode-go-issue

I'm using VS Code 1.36.1 with vscode go 0.11.4 and langserver (whatever it is).

Do you have any idea how this can be fixed?

**Comment by wtask** [comment]
Close editor tab with this file and wait or restart `gopls`

**Comment by stamblerre** [comment]
Can you check your `gopls` version (`gopls version`)? A number of improvements have recently been made, so it is worth updating to the latest (`go get golang.org/x/tools/gopls@latest`).

**Comment by Wulfheart** [comment]
Restarting works just fine. Thank you.

**Comment by marco-m** [comment]
Maybe related: https://github.com/golang/go/issues/33001
