### ISSUE TITLE
VSCode does not compile with updated dependencies until project reloaded

### ISSUE THREAD

**Issue by James-Z-Tang** [microsoft/vscode-go#2646]
Steps to Reproduce:

1. Run go get -u ./... to update dependencies and check go.mod is updated with new version of dependencies.
2. Compilation errors in editor remains. Follow link to reference in editor, it's linked to old version of dependencies.
3. Close workspace or project and reload it, compilation errors disappear and the references are correctly pointing to updated version.

Ideally it would be nice for the VSCode to automatically compile with correct version right after  dependencies updated.

**Comment by zeimbeekor** [comment]
This has happened with the latest VSCode updates. Hopefully, this problem is solved very soon, it is very uncomfortable.

**Comment by ramya-rao-a** [comment]
After Step 1, if you reload the window, do you still see the errors?
Can you provide a small code sample along with sample go.mod file where I can try this?

**Comment by James-Z-Tang** [comment]
I could build golfing program in the console but in vscode it displayed the error sign in editor. After reloading project the error disappeared.

**Comment by ramya-rao-a** [comment]
@zeimbeekor Can you confirm that the VS Code reload fixes the problem?

> This has happened with the latest VSCode updates. Hopefully, this problem is solved very soon, it is very uncomfortable.

There was nothing done in the recent updates around this. The Go extension is not aware of the external `go get` commands that run and update `go.mod` file. Therefore, it will not know to re-run `go build` and to update the errors.
