### ISSUE TITLE
Document currently supported version of Delve

### ISSUE THREAD

**Issue by tnine** [Microsoft/vscode-go#265]
I'm currently using the following versions.

Vs Code: 0.10.11 
Go Plugin: 0.6.33
Go Runtime: 1.6.0
Delve Version:  0.11.0-alpha

I've tried the latest tag, as well as the latest master.  I receive a lot of unexpected tokens and crashes, as well as strange stepping behavior.  Is there a specific sha that should be used when building the delve debugger?

**Comment by lukehoban** [comment]
In principle, the extension aims to work with any version of Delve.  The recent issues mentioned in for example #240 are actually rooted in breaking changes in VS Code, not in Delve.

If Delve does make an API breaking change in the future, then we'll need to document required version (or automatically acquire the binary).  But for now I don't think we yet can say anything particularly helpful about expected Delve versions.
