### ISSUE TITLE
Allow using goimports with gopls

### ISSUE THREAD

**Issue by vincepri** [microsoft/vscode-go#2650]
Follow-up from https://github.com/microsoft/vscode-go/issues/2446, I would like to disable format/imports from gopls and keep using `goimports` instead.

**Comment by ramya-rao-a** [comment]
You can do this by adding the below in your settings

```json
"go.languageServerExperimentalFeatures": {
    "format": false
}
```

Have you tried the above?

**Comment by vincepri** [comment]
Already tried with the settings you shared and it seems, from the process explorer, to always run gopls on save instead of goimports

**Comment by stamblerre** [comment]
Yeah, this setting won't stop the `goimports` behavior because that happens through a code action, not the `textDocument/formatting` request. You would have to set

```json5
"[go]": {
    "editor.codeActionsOnSave": {
        "source.organizeImports": false
    }
},
```

**Comment by vincepri** [comment]
Seems setting them both to `false` doesn't actually trigger `goimports` or any other formatter, can you confirm that's the case as well?

**Comment by stamblerre** [comment]
I think you need this combination of settings to use regular `goimports`:

```json5
"go.languageServerExperimentalFeatures": {
    "format": false,
},
"[go]": {
    "editor.codeActionsOnSave": {
        "source.organizeImports": false,
    },
    "editor.formatOnSave": true,
},
"go.formatTool": "goimports"
```

**Comment by vincepri** [comment]
That worked 🙌 thank you!
