### ISSUE TITLE
goimports does not execute on save with gopls

### ISSUE THREAD

**Issue by bobhancock** [microsoft/vscode-go#2651]
vscode on Liniux
settings.json
{
    "editor.minimap.enabled": false,
    "go.autocompleteUnimportedPackages": true,
    "go.gocodeAutoBuild": true,
    "files.autoSave": "afterDelay",
    "[go]": {
        "editor.codeActionsOnSaveTimeout": 3000,
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": true // add parameter placeholders when completing a function
    },
    "files.eol": "\n",
    "go.useLanguageServer": true, // formatting only supports LF line endings
    "go.languageServerFlags": [
        "-rpc.trace", // for more detailed debug logging
        "serve",
        "--debug=localhost:6060", // to investigate memory usage, see profiles 
    ],
    "go.formatTool": "goimports",
}
------------------------------------
I have a file with the imports

import (
	"encoding/csv"
	"fmt"
	"io"
	"math"
	"math/rand"
	"os"
	"runtime"
	"strconv"
	"strings"
)
- Delete "fmt"
- Save the file
- fmt is not inserted 

This is the debug output from gopls which seems to show that recognizes that fmt should be inserted.

[Trace - 6:21:06 PM] Received response 'textDocument/codeAction - (9)' in 0ms.
Params: [{"title":"Organize Imports","kind":"source.organizeImports","edit":{"changes":{"file:///home/rwh/go/src/goxmeans/km_test.go":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":0}},"newText":"\t\"fmt\"\n"}]}}}]

[Trace - 6:21:06 PM] Sending notification 'textDocument/codeAction' in 28ms.
Params: {"textDocument":{"uri":"file:///home/rwh/go/src/goxmeans/km_test.go"},"range":{"start":{"line":5,"character":4},"end":{"line":5,"character":4}},"context":{"diagnostics":[]}}

**Comment by ramya-rao-a** [comment]
cc @stamblerre

**Comment by stamblerre** [comment]
I actually redirected https://github.com/golang/go/issues/33089 to this repository because it doesn't seem to be a `gopls` problem. Based on the logs, `gopls` is returning the correct responses, but VSCode does not seem to be applying them.

**Comment by ramya-rao-a** [comment]
Apologies for the very late reply here.

@bobhancock Do you still have this issue? Are you using any of the vscode-remote extensions? We have had few reports where text edits werent being applied as expected when using the vscode-remote extensions
