### ISSUE TITLE
it takes too much time to navigate to implementation of interface

### ISSUE THREAD

**Issue by xq840622** [microsoft/vscode-go#2652]
I use 'cmd+f12' to find the Implementations of interfaces (using guru), but it take more than 10 second to do that.
But in goland or sublime, this operation will be so much faster.

**Comment by ramya-rao-a** [comment]
Please share the Go related settings you might have added/edited. You can get these from running the command `Preferences: Open Settings (JSON)`

**Comment by xq840622** [comment]
> Please share the Go related settings you might have added/edited. You can get these from running the command `Preferences: Open Settings (JSON)`
{
    "go.formatTool": "goimports",
    "window.zoomLevel": 0,
    "go.testTimeout": "6000s",
    "go.testFlags": [
        "-v",
        "-count=1"
    ],
    "gitlens.advanced.messages": {
        "suppressFileNotUnderSourceControlWarning": true,
        "suppressShowKeyBindingsNotice": true
    },
    "workbench.startupEditor": "newUntitledFile",
    "todo-tree.defaultHighlight": {
        "foreground": "green",
        "type": "none"
    },
    "todo-tree.customHighlight": {
        "TODO": {},
        "FIXME": {}
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "go.enableCodeLens": {
        "references": true,
        "runtest": true
    },
    "go.autocompleteUnimportedPackages": true,
    "go.toolsGopath": "/Users/xq840622/go",
    "go.gopath": "/Users/xq840622/go",
}

**Comment by ramya-rao-a** [comment]
Thanks @xq840622 

As discussed in #2621, `guru` is inherently slow in such cases.

For long term, we are looking at [gopls](https://github.com/golang/go/wiki/gopls) to provide a better solution for finding references and implementation.

Closing this issue as unfortunately, there isnt much we can do at this point from the extension's side.
