### ISSUE TITLE
Option to disable red highlighting/checking as you type when using gopls

### ISSUE THREAD

**Issue by blocknonip** [microsoft/vscode-go#2654]
Latest stable vscode-go, with latest build of `gopls` from cmd-shift-P, on macOS Mojave.

Apologies if this is in the docs/README, but I was unable to find it. Also, feel free to update the title if my terminology is wrong.

When test driving `gopls`, I find the constant lighting up of my UI with red highlighting as I type extremely distracting. Is there an option to turn this off until I save the file, similar to how it works if I do not have the language server enabled? Coming from my daily use without the language server, it seems unnecessary to have every half-typed word highlight in red constantly.

Thanks!

**Comment by ramya-rao-a** [comment]
You can add the below to disable diagnostics from gopls and use the diagnostics that appear on file save from vscode-go
```
  "go.languageServerExperimentalFeatures": {
    "diagnostics": false
  }
```

Ensure that you havent turned off `go.buildOnSave` and `go.lintOnSave` settings

**Comment by blocknonip** [comment]
Thank you for the clarification.
