### ISSUE TITLE
gopls: rename symbol in all files

### ISSUE THREAD

**Issue by benoitmasson** [microsoft/vscode-go#2657]
I have successfully updated `gopls` to v0.1.3, now I can rename symbols from VS Code (https://github.com/microsoft/vscode-go/issues/2618 and https://github.com/Microsoft/vscode-go/issues/2074#issuecomment-507117831)

However, it seems symbols are not renamed outside of the current file, even when this file is open, like `gorename` used to do.

Am I missing something, or is it ongoing work for `gopls` to account for symbol usage accross files?

**Comment by stamblerre** [comment]
`gopls` rename only supports renaming within a package or its tests, not in other packages yet: https://github.com/golang/go/issues/32869.

**Comment by ramya-rao-a** [comment]
Closing in favor of the upstream issue
