### ISSUE TITLE
vscode-go is spamming me with "Reload vscode after installing Go language server"

### ISSUE THREAD

**Issue by jadekler** [microsoft/vscode-go#2659]
I deleted the gopls binary and declined to install it when I opened vscode. However, every single time I type a key in a .go file, I get a popup that says "Reload vscode after installing Go language server".

If I ignore this popup and type another character, the popup minimizes itself and re-opens. Could we remove this behavior?

[Screenshot from 2019-07-17 09-42-48](https://user-images.githubusercontent.com/3584893/61390161-80622100-a877-11e9-8adb-c2a39597bb9f.png)

**Comment by ramya-rao-a** [comment]
While we look into it, disable the use of language server in your settings, reload VS Code window once. You shouldnt get that prompt again.

To disable the use of language server, set `go.useLanguageServer` to `false` or remove that setting altogether

**Comment by ramya-rao-a** [comment]
@stamblerre Is this something you can take up?

**Comment by stamblerre** [comment]
I've been reworking all of the language server code in the extension in https://github.com/microsoft/vscode-go/pull/2703.

**Comment by ramya-rao-a** [comment]
@stamblerre's changes are now in the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension.

@jadekler Can you please try the beta version and let us know if you still see this issue?
