### ISSUE TITLE
the go-* toolset should have a option to specify its path.

### ISSUE THREAD

**Issue by abadcafe** [Microsoft/vscode-go#266]
If gocode and other commands are not in $PATH or $GOPATH/bin, all functions are failed. But in OSX, the global environment (include $PATH and $GOPATH) is difficult to set.

**Comment by lukehoban** [comment]
You can also set your GOPATH with the `"go.gopath": "/my/path/to/go"` in your settings, either globally or per-workspace.  see https://github.com/Microsoft/vscode-go#options.

You can also launch code from a shell with a GOPATH environment configured.

Hopefully one of those options works for you?

**Comment by abadcafe** [comment]
@lukehoban 
gocode and other commands are installed by package manager and put in global path like /usr/local/bin usually. Set go.gopath to /usr/local is not grace.

In the other hand, if I set go.gopath to "${workspaceRoot}", which is convenient when work in multi-workspaces, then every workspace need to "go get" a gocode, which is duplicated.

**Comment by lukehoban** [comment]
Is `/usr/local/bin` not in your PATH?  Presumably the location that your package manager is installing these tools needs to be one that's in your PATH or else it will be inconvenient to use them from a shell as well.

Curious what option you would have liked to have aswell or instead of what's available now.

**Comment by abadcafe** [comment]
@lukehoban 
In fact, this assumed "go.path" option is just a workaround for a stupid OSX design.

In OSX, I can set the PATH in terminal with bash like this "export PATH=xxx", but this action never affect the global environment, and it is hard to set global envirionment in OSX system boot. So the GUI application in OSX have a default PATH value as '/usr/bin:/bin:/usr/sbin:/usr/sbin:/sbin'.

But the package manager like Homebrew install CLI applications into /usr/local/bin, which can not access by the GUI application.

**Comment by lukehoban** [comment]
When you launch VS Code through the OS X UI, it should inherit it's environment, including `PATH` from your `~/.bash_profile` or similar.  Run `Toggle Developer Tools` command in VS Code, then eval `process.env` to see what environment VSCode is running with.

**Comment by abadcafe** [comment]
@lukehoban 
now I got this:
![91ae2a4782a7736a83662e706e008235](https://cloud.githubusercontent.com/assets/922228/14052466/776620a4-f305-11e5-9151-5166c8eb119f.jpg)

and this is the PATH:
"~/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

and this is the ~/bin:
$ ls ~/bin
bcomp  eagle.py  gocode  upload.py

run the gocode in the terminal:
$ gocode -v
flag provided but not defined: -v
Usage: gocode [-s] [-f=<format>] [-in=<path>] [-sock=<type>] [-addr=<addr>]
       <command> [<args>]
......

So here, the PATH in the VS Code is not take effect.

**Comment by abadcafe** [comment]
OK, I found the problem.

If i change the ~/bin to $HOME/bin, everything is OK.

Thank you for your help.
