### ISSUE TITLE
LSP is showing errors that were fixed long ago

### ISSUE THREAD

**Issue by ahmetb** [microsoft/vscode-go#2661]
This happens to me all the time lately and it started to pretty annoying. 

I use setting `  "go.useLanguageServer": true` and `"go.buildOnSave": "package",`.

Steps to Reproduce:

1. take perfectly fine code: 
![image](https://user-images.githubusercontent.com/159209/61485420-f89f1400-a955-11e9-9727-0b7e429f184c.png)
2. introduce an error (like adding a `x` character at the end)  WITHOUT SAVING
![image](https://user-images.githubusercontent.com/159209/61485438-06ed3000-a956-11e9-81de-d6d253cccee6.png)

3. see the error shown in OUTPUT clearly: 
![image](https://user-images.githubusercontent.com/159209/61485452-140a1f00-a956-11e9-8188-05758e5c84fc.png)

3. Fix the error + save. The error never goes away despite saving: 
![image](https://user-images.githubusercontent.com/159209/61485494-28e6b280-a956-11e9-9181-57d2f9415bf1.png)

3. easily reproducible by deleting `}` etc as well.

I'm on the v0.11.4 of the extension.

**Comment by stamblerre** [comment]
What version of `gopls` are you using (`gopls version`)?

**Comment by stamblerre** [comment]
I would recommend making sure you are using the latest version by running `go get golang.org/x/tools/gopls`).

**Comment by ahmetb** [comment]
Looks like `gopls version` command or flag doesn't exist on my local copy.

<details>
<summary>`gopls version` output</summary>
<pre>
gopls version
gopls: Unknown command version
The Go Language source tools.

Usage: gopls [flags] <command> [command-flags] [command-args]

Available commands are:
  serve : run a server for Go code using the Language Server Protocol
  query : answer queries about go source code
  check : show diagnostic results for the specified file

gopls flags are:
  -listen string
    	address on which to listen for remote connections
  -logfile string
    	filename to log to. if value is "auto", then logging to a default output file is enabled
  -mode string
    	no effect
  -port int
    	port on which to run gopls for debugging purposes
  -profile.cpu string
    	write CPU profile to this file
  -profile.mem string
    	write memory profile to this file
  -profile.trace string
    	write trace log to this file
  -remote string
    	*EXPERIMENTAL* - forward all commands to a remote lsp
  -rpc.trace
    	Print the full rpc trace in lsp inspector format
</pre>
</details>

I don't think I've ever installed gopls directly. I'm suspecting VSCode is managing its installation for me:

I have setting `"go.toolsGopath": "~/gotools"` on my vscode settings, and I can clearly see:

```
$ which gopls
/Users/ahmetb/gotools/bin/gopls
```

Since vscode-go has machinery to detect the version of installed go tooling such as (go-langserver  go-symbols  gocode-gomod  goimports  gopkgs  gorename   gotests....) and it offers pop-ups to upgrade these tools periodically, I will say I probably should not be running `go get` myself.

**Comment by ahmetb** [comment]
It also appears like vscode-go has stopped auto-upgrading the tools it's depending on since April. This is my `go.toolsGopath/bin` directory:

```
bin $ ls -al
total 158968
drwxr-xr-x 18 ahmetb primarygroup      576 Jul 18 14:06 .
drwxr-xr-x  6 ahmetb primarygroup      192 May  2 15:25 ..
-rwxr-xr-x  1 ahmetb primarygroup 16352108 Apr  8 21:18 dlv
-rwxr-xr-x  1 ahmetb primarygroup 26141012 Apr  8 21:18 go-langserver
-rwxr-xr-x  1 ahmetb primarygroup  4568128 Apr  8 21:18 go-outline
-rwxr-xr-x  1 ahmetb primarygroup  4351360 Apr  8 21:18 go-symbols
-rwxr-xr-x  1 ahmetb primarygroup 13244796 Apr  8 21:17 gocode
-rwxr-xr-x  1 ahmetb primarygroup 12681660 Apr  8 21:18 gocode-gomod
-rwxr-xr-x  1 ahmetb primarygroup  9904400 Apr  8 21:18 godef
-rwxr-xr-x  1 ahmetb primarygroup  7744608 Apr  4 12:03 goimports
-rwxr-xr-x  1 ahmetb primarygroup  6358656 Apr  8 21:18 golint
-rwxr-xr-x  1 ahmetb primarygroup  5400416 Apr  8 21:17 gopkgs
-rwxr-xr-x  1 ahmetb primarygroup 10443760 Apr  4 10:56 gopls
-rwxr-xr-x  1 ahmetb primarygroup  6330624 Apr  8 21:18 gorename
-rwxr-xr-x  1 ahmetb primarygroup  8450048 Apr  8 21:18 goreturns
-rwxr-xr-x  1 ahmetb primarygroup 13627308 May  2 15:25 gotests
-rwxr-xr-x  1 ahmetb primarygroup  6458288 Apr  9 14:07 goweight
-rwxr-xr-x  1 ahmetb primarygroup  9447168 Apr  8 21:18 guru
```

Since vscode-go used to offer updating these with a pop-up reminder, I'm thinking something is broken.

**Comment by stamblerre** [comment]
It sounds like you are using a very old version of `gopls` - one from before the addition of the version command. You can update by either using the command I suggested, or by opening the command palette (Ctrl + Shift + P) and selecting "Go: Install/Update Tools" and choosing `gopls`.

**Comment by ahmetb** [comment]
I upgraded & restarted (now at `v0.1.3-cmd.gopls`).

The issue persists, but a bit differently. (the deleting/re-adding `}` no longer causes the snipped issue above).

Take a look at highlighted and valid import path on a *.go file:

![image](https://user-images.githubusercontent.com/159209/61494512-2e022c80-a96b-11e9-90b8-9e0831b903be.png)

I delete the last slash (`/`), **and add it back** immediately _without_ saving. With  about **4 seconds delay** it freaks out again (on code that is now  valid) and starts showing errors again (about the old code):
![image](https://user-images.githubusercontent.com/159209/61494574-5ab64400-a96b-11e9-9261-9da29113bd15.png)

And about several seconds later, it fixes itself.

The feedback loop seems to be quite delayed like ~8s. (During this period, gopls process peaks 30% cpu very briefly.)

**Comment by stamblerre** [comment]
What is the output of `gopls -v -rpc.trace /path/to/file.go`?

**Comment by ahmetb** [comment]
That treats file path as a subcommand, hence not working.
(gopls version: v0.1.3)

**Comment by stamblerre** [comment]
Sorry, I meant to say `gopls -v -rpc.trace check /path/to/file.go`

**Comment by ahmetb** [comment]
<details>
<summary>output here</summary>
2019/07/18 16:14:08 Info:136.923482ms for GOROOT= GOPATH= GO111MODULE= PWD=/Users/ahmetb/workspace/krew go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "builtin", stderr: <<>>
2019/07/18 16:14:09 Info:Build info
----------
version v0.1.3, built in $GOPATH mode

Go info
-------
go version go1.12.6 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ahmetb/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ahmetb/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/ahmetb/.homebrew/Cellar/go/1.12.6/libexec"
GOTMPDIR=""
GOTOOLDIR="/Users/ahmetb/.homebrew/Cellar/go/1.12.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ahmetb/workspace/krew/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h7/n46zg3md4l57vzsgxcs355hw00dl55/T/go-build512788898=/tmp/go-build -gno-record-gcc-switches -fno-common"
2019/07/18 16:14:11 Info:2.33005993s for GOROOT= GOPATH= GO111MODULE= PWD=/Users/ahmetb/workspace/krew go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "/Users/ahmetb/workspace/krew/pkg/installation", stderr: <<>>
2019/07/18 16:14:11 Info:go/packages.Load
	packages = 2
2019/07/18 16:14:11 Info:go/packages.Load
	package = sigs.k8s.io/krew/pkg/installation
	files = [/Users/ahmetb/workspace/krew/pkg/installation/install.go /Users/ahmetb/workspace/krew/pkg/installation/move.go /Users/ahmetb/workspace/krew/pkg/installation/upgrade.go /Users/ahmetb/workspace/krew/pkg/installation/util.go]
2019/07/18 16:14:11 Info:go/packages.Load
	package = sigs.k8s.io/krew/pkg/installation
	files = [/Users/ahmetb/workspace/krew/pkg/installation/install.go /Users/ahmetb/workspace/krew/pkg/installation/move.go /Users/ahmetb/workspace/krew/pkg/installation/upgrade.go /Users/ahmetb/workspace/krew/pkg/installation/util.go /Users/ahmetb/workspace/krew/pkg/installation/install_test.go /Users/ahmetb/workspace/krew/pkg/installation/move_test.go /Users/ahmetb/workspace/krew/pkg/installation/util_test.go]
</details>

Again, functionally it's working, but there's a significant delay in processing the changes, and therefore the results a modification are reflected very delayed.

**Comment by stamblerre** [comment]
Is it only slow when you edit the import paths or is it also slow in other parts of the file?

**Comment by ahmetb** [comment]
It varies depending on the situation:

- obvious syntax errors, like missing }, ) &rarr; ~instant feedback showing error.
- import paths &rarr; 3-4 seconds showing error
- undeclared identifier &rarr; ~instant feedback showing error
- changing the package name on an invocation (e.g. errors.Wrap &rarr; errorz.Wrap) &rarr; ~instant feedback showing error
- fixing it back (e.g. errorz.Wrap &rarr; errors.Wrap) &rarr; ~1 second for the error to disappear

**Comment by giulianob** [comment]
I'm having the same issue. I have to just often reload VSCode to clear errors otherwise it just seems like it's stuck. If there's any tracing that would help debug it let me know it happens several times an hour.

**Comment by stamblerre** [comment]
@ahmetb: Do you always type import paths or do you use the `source.organizeImports` feature? Can you please share your `gopls` logs? They can be found by going to View: Debug Console -> Output -> Tasks -> gopls.

@giulianob: Can you confirm your version of `gopls` (`gopls version`)? You can update to the latest by running `go get golang.org/x/tools/gopls@latest`. If you are still seeing these issues, please open an issue on the Go issue tracker: https://github.com/golang/go/issues.

**Comment by jadekler** [comment]
+1, also seeing this.

**Comment by ahmetb** [comment]
I don’t really do manual imports so my problem is gone for the moment. 

But the fact that vscode-go isnt prompting for such an outdated tool + others are hitting it is concerning. Vscode-go’s Go tools update feature was such a nice thing to have, lately it has been gone for me.

**Comment by ahmetb** [comment]
The situation is worse now for some reason. It still shows errors that are long gone in some situations, it stops working after a while when there are way too many errors (shows no errors anymore).

Reload Window fixes everything, and I have to do it like every 5 minutes.

I'm afraid I have no clean repro for any of it. I recommend using vscode-go to develop a project that uses Go modules heavily.

**Comment by stamblerre** [comment]
Has it gotten worse with the same version of `gopls`? Can you share your logs from when this happens?

**Comment by ahmetb** [comment]
I have no idea where to find gopls logs. Also happy to jump on hangouts and show this in action.

**Comment by polak-jan** [comment]
I was getting the same issue, updated all tools today but it still does it though quite less often, only happened once in the few hours and it only stayed for few seconds.

But before that it used to hang after less than a minute, I almost couldn't type a single character without loosing all go related functionality. The errors that cause this seem to be random ones, can't say that there would be one specific error that would cause it every time, even import doesn't do it every time. It also seems to happen more frequently when there are multiple instances of VSCode opened.

 The whole go extension seems to hang while this is happening, hovering over variables just shows "loading", outline is stuck loading and so on. One notable example is when I write a new import it gets stuck on showing error `invalid import path ""` even though there is a valid path written in there since.

It does fix it self after a while, the time isn't always the same but generally over 10 minutes.

**Comment by stamblerre** [comment]
@ahmetb: See https://github.com/golang/go/wiki/gopls#troubleshooting for more information. I also mentioned how to get logs in https://github.com/microsoft/vscode-go/issues/2661#issuecomment-513390585. I would be happy to take a look with you over hangouts, but seeing your logs may help me get a sense of the issue first.

@polak-jan: Are you still seeing such errors, and if so, can you share your logs as well? `gopls` is still very much in alpha, so updating it frequently is the best course of action for now. We are making changes and improvements quite quickly, so old versions will likely not give the optimal experience.

**Comment by jadekler** [comment]
I experienced this delay again today. I exited vscode, opened it again, and had roughly 8 incorrect red squigglies (fixed things, wrong line, wrong characters, etc). One by they disappeared with ~5-10s in between each disappearing. Here's the log:

```
[Info  - 2:16:18 PM] Build info
----------
golang.org/x/tools/gopls v0.1.2
    golang.org/x/tools/gopls@v0.1.3 h1:CB5ECiPysqZrwxcyRjN+exyZpY0gODTZvNiqQi3lpeo=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20190710153321-831012c29e42 h1:4IOeC7p+OItq3+O5BWkcmVu2uBe3jekXau5S4QZX9DU=

Go info
-------
go version go1.12.6 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/deklerk/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/deklerk/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/deklerk/workspace/google-cloud-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/go-build651669238=/tmp/go-build -gno-record-gcc-switches -fno-common"

[Error - 2:16:35 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:21:6: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:21:6 is not an identifier
[Error - 2:16:49 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:23:33: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:23:33 is not an identifier
[Error - 2:16:49 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:27:33: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:27:33 is not an identifier
[Error - 2:16:54 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:29:18: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:29:18 is not an identifier
[Error - 2:17:03 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:29:18: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:29:18 is not an identifier
[Info  - 2:17:21 PM] no signature help for file:///Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:28:12 : cannot find an enclosing function
[Info  - 2:17:25 PM] no signature help for file:///Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:28:13 : cannot find an enclosing function
[Error - 2:17:25 PM] Request textDocument/codeAction failed.
  Message: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:29:13: expected ';', found w (and 1 more errors)
  Code: 0 
[Info  - 2:17:25 PM] no signature help for file:///Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:28:12 : cannot find an enclosing function
[Error - 2:17:32 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:12:59: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:12:59 is not an identifier
[Error - 2:17:39 PM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0 
[Error - 2:17:44 PM] Request textDocument/hover failed.
  Message: no object for ident port
  Code: 0 
[Error - 2:17:52 PM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0 
[Error - 2:18:00 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:27:43: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:27:43 is not an identifier
[Error - 2:18:18 PM] Request textDocument/codeAction failed.
  Message: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:27:44: missing ',' in argument list (and 61 more errors)
  Code: 0 
[Error - 2:18:30 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:23:42: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:23:42 is not an identifier
[Error - 2:18:44 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:21:32: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:21:32 is not an identifier
[Error - 2:19:08 PM] Request textDocument/hover failed.
  Message: no object for ident s
  Code: 0 
[Error - 2:19:08 PM] no highlight for /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:38:35: /Users/deklerk/workspace/google-cloud-go/spanner/internal/fakeserver/fakeserver.go:38:35 is not an identifier
[Error - 2:19:21 PM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0 
[Error - 2:19:21 PM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0 
[Error - 2:19:21 PM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0 
```

**Comment by gyuho** [comment]
`goimports` and `gopls` did not work at all for me.

I tried deleting all Go related configuration in `settings.json` except: And restarted the editor, prompted a bunch of messages to reinstall/update tools. Now, imports for stdlib works but not for others! (`goimports -w *.go` works fine in my machine...)


For reference,

```
$ gopls -rpc.trace -v check pkg/verify/verify.go
2019/08/11 01:20:21 Info:30.274072ms for GOROOT= GOPATH=/Users/leegyuho/go GO111MODULE= PWD=/Users/leegyuho/go/src/go.etcd.io/etcdx go "list" "-m" "-json" "all", stderr: <<go list -m: not using modules
>>
2019/08/11 01:20:21 Info:31.58233ms for GOROOT= GOPATH=/Users/leegyuho/go GO111MODULE= PWD=/Users/leegyuho/go/src/go.etcd.io/etcdx go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "builtin", stderr: <<>>
2019/08/11 01:20:21 Info:33.656557ms for GOROOT= GOPATH=/Users/leegyuho/go GO111MODULE= PWD=/Users/leegyuho/go/src/go.etcd.io/etcdx go "env" "GOPATH", stderr: <<>>
2019/08/11 01:20:21 Info:Build info
----------
version v0.1.3, built in $GOPATH mode

Go info
-------
go version go1.12.7 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/leegyuho/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/leegyuho/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y_/_dn293xd5kn7xlg6jvp7jpmxs99pm9/T/go-build338164485=/tmp/go-build -gno-record-gcc-switches -fno-common"
2019/08/11 01:20:22 Info:519.365063ms for GOROOT= GOPATH=/Users/leegyuho/go GO111MODULE= PWD=/Users/leegyuho/go/src/go.etcd.io/etcdx go "list" "-m" "-json" "all", stderr: <<go list -m: not using modules
>>
2019/08/11 01:20:22 Info:16.120762ms for GOROOT= GOPATH=/Users/leegyuho/go GO111MODULE= PWD=/Users/leegyuho/go/src/go.etcd.io/etcdx go "env" "GOPATH", stderr: <<>>
2019/08/11 01:20:22 Info:871.012877ms for GOROOT= GOPATH=/Users/leegyuho/go GO111MODULE= PWD=/Users/leegyuho/go/src/go.etcd.io/etcdx go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "/Users/leegyuho/go/src/go.etcd.io/etcdx/pkg/verify", stderr: <<>>
2019/08/11 01:20:22 Info:go/packages.Load
	packages = 1
2019/08/11 01:20:22 Info:go/packages.Load
	package = go.etcd.io/etcdx/pkg/verify
	files = [/Users/leegyuho/go/src/go.etcd.io/etcdx/pkg/verify/verify.go]
```

**Comment by stamblerre** [comment]
@gyuho: Please open a new issue on the [Go issue tracker](https://github.com/golang/go/issues/new), and I can help you investigate there. Please include the additional information requested here: https://github.com/golang/go/wiki/gopls#troubleshooting.

**Comment by gyuho** [comment]
@stamblerre The trick was increase the timeout `"editor.codeActionsOnSaveTimeout": 3000` as the wiki https://github.com/golang/go/wiki/gopls#troubleshooting says

```json
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "[go]": {
        "editor.codeActionsOnSaveTimeout": 3000,
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": true // add parameter placeholders when completing a function
    },
    "files.eol": "\n", // formatting only supports LF line endings
```

Now, everything works!

Thanks for the help!

**Comment by stamblerre** [comment]
A lot has changed in `gopls` since this issue was filed, so @ramya-rao-a, I think this can be closed.

**Comment by ramya-rao-a** [comment]
I agree, thanks @stamblerre.

If anyone sees problems using the latest version of `gopls`, please log new issues.
