### ISSUE TITLE
Auto-import auto-complete is very slow with go mod and takes 4-5 seconds

### ISSUE THREAD

**Issue by fananchong** [microsoft/vscode-go#2662]
The project uses go module to manage dependencies, no vendor

**Comment by ramya-rao-a** [comment]
Please provide more details on the steps for this issue i.e what exactly is slow?
- Showing of the auto-completion list?
- Adding of the text after a completion item is selected?

A screenshot of the feature you are referring to can help as well.
Please share any Go related settings you might have edited/added

**Comment by fananchong** [comment]
https://github.com/fananchong/test_travis_ci_for_golang/blob/master/temp/vscode_compress.gif
![p1](https://github.com/fananchong/test_travis_ci_for_golang/blob/master/temp/vscode_compress.gif)

**Comment by ramya-rao-a** [comment]
@fananchong I can't see the gif actually running in the above link. Can you try again by some other means?

**Comment by fananchong** [comment]
18.8 MB , try download

**Comment by ramya-rao-a** [comment]
Ok, looks like there are 2 separate problems here
- After saving a file with no imports, the feature that adds the imported packages is slow
- Auto-completion is slow after the above point.

When using modules, we suggest that you use the language server which fares better than the other tools for many features. Have you tried the [language server](https://github.com/Microsoft/vscode-go#go-language-server)?

**Comment by fananchong** [comment]
I am in China, in an "oversized LAN", unable to access the language server = =|

**Comment by fananchong** [comment]
use language server ，there is an error message : 'There is no formatter for 'go'-files installed.'

settings.json :
```json
{
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "window.zoomLevel": 3,
    "go.useLanguageServer": true
}
```

**Comment by ramya-rao-a** [comment]
@fananchong,

My apologies for not responding sooner.
Do you still have this issue?
Can you try using the latest version of this extension (0.11.5) and updating your language server?
You can do this by running the command `Go: Install/ Update Tools`, select `gopls` and then press Ok

**Comment by fananchong** [comment]
Now I am using a language server very smooth, thanks

**Comment by harmnot** [comment]
@ramya-rao-a I can't autocomplete after I got latest update, and I have tried uninstall and reinstall VSCode , but not work, I am new for VSCode anyway,

**Comment by ramya-rao-a** [comment]
@harmnot Please log a new issue with details around all Go related settings you might have added/edited which you can get by running the command `Preferences: Open Settings(JSON)`. Also share if you are using Go modules or not
