### ISSUE TITLE
dlv remote debugging using vscode

### ISSUE THREAD

**Issue by adibrastegarnia** [microsoft/vscode-go#2663]
We have a dlv server running in the exec mode in a Kubernetes pod and we already exposed the port that we can connect to it using dlv client or IDEs. We can connect using dlv connect but we cannot connect to it using vscocde.  First of all, it is not clear for me what should be type of request: attach or launch? When I set it to launch it says: couldn't start listener: listen tcp 127.0.0.1:40000: bind: address already in use. Would you please tell me what should be lunch.json look like?

**Comment by sagarkrkv** [comment]
@adibrastegarnia this config should work.
```json
{
    "name": "Debug in Container",
    "type": "go",
    "request": "attach",
    "mode": "remote",
    "remotePath": "The absolute path of the project root dir where the binary was built",
    "port": 40000,
    "host": "127.0.0.1",
    "apiVersion": 2
}
```

**Comment by adibrastegarnia** [comment]
@sagarkrkv 
Thanks for your response. What I found out If I run dlv connect localhost:40000 from another terminal and then start the debugger from vscode it will connect to the server but without that it doesn't work. Is that an intended behavior?

**Comment by sagarkrkv** [comment]
>  --accept-multiclient   Allows a headless server to accept multiple client connections. Note that the server API is not reentrant and clients will have to coordinate
https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv.md#options

Yes, according to delve documentation, the clients have to co-ordinate in this scenario, so I would assume what you're describing is not possible.

**Comment by quoctruong** [comment]
@ramya-rao-a I think the issue is resolved so we can close it?

**Comment by adibrastegarnia** [comment]
Yep
