### ISSUE TITLE
find all references only shows itself

### ISSUE THREAD

**Issue by jadekler** [microsoft/vscode-go#2665]
When I search for references for a method on a struct, it just shows itself, instead of any references. I am able to navigate to a different file that uses the method, ctrl+f the usage of that method, and Go To Definition and it lands me on the method, so that direction works fine. Just the other direction that does not.

Not sure if this is `gopls` related or not. If so, here is my version:

```
deklerk at deklerk-macbookpro2 in ~/workspace/google-cloud-go on ordered*
$ go get golang.org/x/tools/gopls@latest
go: finding golang.org/x/tools/gopls v0.1.3
go: finding golang.org/x/tools v0.0.0-20190710153321-831012c29e42
go: downloading golang.org/x/tools v0.0.0-20190710153321-831012c29e42
go: extracting golang.org/x/tools v0.0.0-20190710153321-831012c29e42
go: downloading golang.org/x/tools/gopls v0.1.3
go: extracting golang.org/x/tools/gopls v0.1.3
deklerk at deklerk-macbookpro2 in ~/workspace/google-cloud-go on ordered*
$ go install golang.org/x/tools/gopls
```

<img width="832" alt="Screen Shot 2019-07-19 at 5 07 03 PM" src="https://user-images.githubusercontent.com/3584893/61570077-a6d6b680-aa47-11e9-9b10-db1ecebf4acf.png">

**Comment by stamblerre** [comment]
Is the different file in the same package or a different package? See https://github.com/golang/go/issues/32869.

**Comment by jadekler** [comment]
Different package. Closing to track 32869.
