### ISSUE TITLE
how do I debug plugin problems?

### ISSUE THREAD

**Issue by jadekler** [microsoft/vscode-go#2666]
Occasionally some combination of this plugin and its dependencies stop working. For example, right now I have incorrectly tabbed Go content, and when I hit save, nothing happens. (I expect it to re-tab my code appropriately)

I'd like to see some sort of running log of what's happening under the hood to figure out if some plugin is broken or something. Is such a thing possible?

**Comment by jadekler** [comment]
Nevermind! @stamblerre notes how to in https://github.com/microsoft/vscode-go/issues/2661.

**Comment by stamblerre** [comment]
Also, see https://github.com/golang/go/wiki/gopls#troubleshooting.
