### ISSUE TITLE
vscode-go compile  taking too much cpu

### ISSUE THREAD

**Issue by proudlily** [microsoft/vscode-go#2668]
Steps to Reproduce:
1. i use vscode to write go
2. while i save file in the vscode ,the vscode is goint to compile code.
3.then it will takes too much cpu and mem .
4. i tried to use difference version of vscode-go,suce as
0.11.4;  0.11.1; 0.6.89
5.but all the version of vscode-go all is  taking too much cpu and mem that i cant do anything

see pic below:
![ZHHAEV.jpg](https://s2.ax1x.com/2019/07/16/ZHHAEV.jpg)

![eVF4mj.jpg](https://s2.ax1x.com/2019/07/24/eVF4mj.jpg)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @proudlily 

- Please share a screenshot of the process explorer after running the command `Developer: Open Process Explorer` when this happens
- Also share any Go related settings you may have added/edited
- Are you using Go modules?
- Does this happen if you set `go.buildOnSave` to `off`?
