### ISSUE TITLE
v0.11.4 breaks all commands for extension, and cannot run go files with debug mode

### ISSUE THREAD

**Issue by ho-wan** [microsoft/vscode-go#2669]
Cannot run go files using launch.json with debug mode with v0.11.4.  Also, none of the commands for the extension seems to be able to be found (error: command 'go.gopath' not found).

Works with all versions of vscode-go v0.11.3 and previous.

OS: Windows 10
VS Code Version: 1.36.1
Go version: go1.12.6 windows/amd64

Steps to Reproduce:
1. With Go extension v0.11.4 installed and launch.json configured, press F5 to run debugging, debug toolbar pops up for 1 second then closes, nothing else happens. No messages appear in debug console.
2. Try to run any command for extension, get error "command ... not found".
3. Using the 'Install another version..' in extension panel, install v0.11.3 through side bar, reload window. Debug and other commands all work as normal.

**Comment by ramya-rao-a** [comment]
I believe the extension is not getting loaded properly in your case, please try the below

- Install the latest version of the Go extension
- Reload VS Code window
- Run `View` -> `Output` -> `Log (Extension Host)` in the drop down on the top right corner of the panel
- Check for any errors indicating that the vscode-go extension failed to load
- Run the command `Go: Current GOPATH` to test if the extension got activated properly

**Comment by ho-wan** [comment]
Thanks, the problem fixed itself after restarting computer and installing the latest version of the extension.
