### ISSUE TITLE
Debugger hangs in OSX

### ISSUE THREAD

**Issue by lennykean** [Microsoft/vscode-go#267]
On OSX, when I try to start the debugger it just hangs until I stop it.

**Comment by lukehoban** [comment]
Could you provide any details?  Does this happen on all code?  What versions of Delve, VS Code and `vscode-go`, etc?

Please reopen if you have any additional info on this.

**Comment by lennykean** [comment]
Sure. 

It does happen on all code. I don't get any errors, and there is nothing in the debug console. 

Go: 1.6
Delve: v0.11.0-alpha
VS-Code: 0.10.11
vscode-go: 0.6.30

**Comment by lukehoban** [comment]
Could you try updating to the latest `vscode-go` (currently 0.6.35)?  There were some fixes for recent breaking changes in the VS Code debugger which may be what you are hitting.
