### ISSUE TITLE
There is no formatter for 'go'-files installed

### ISSUE THREAD

**Issue by mjaseem** [microsoft/vscode-go#2670]
When I try to format go code I get the error mentioned in the title. I am using latest version of vscode and vscode-go. 

If I enable Go language server, I don't get any error message, but document remains unformatted.

**Comment by stamblerre** [comment]
If you use the language server, you need to add these settings.

```json5
"[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
},
```

**Comment by ramya-rao-a** [comment]
@stamblerre Those are the default settings at the moment, so users don't have to set that explicitly anymore.

@mjaseem Are you able to use other features like the `Go To Definition` feature? Can you share all the settings you might have added/changed related to Go? Are you using modules?

**Comment by mjaseem** [comment]
There was an error in my file that was causing the issue I guess. First line didn't have package information. There were no squiggly lines to indicate this. When I added package info as the first line, formatting and error detection started working properly. Is this expected behavior?

**Comment by ramya-rao-a** [comment]
The error "There is no formatter for go files" is not the expected behavior regardless of the contents of your Go file.

@stamblerre Are you able to replicate this?

**Comment by stamblerre** [comment]
Based on @mjaseem's first comment, it sounds like that specific error message only occurs when the language server is disabled.

@mjaseem: You should definitely get a red squiggle if the top of your file is missing a package declaration. Can you file an issue with a repro case [here](https://golang.org/issue)?

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity.
