### ISSUE TITLE
Need the ability to save vs code setting in cloud through email and retrieve it any time

### ISSUE THREAD

**Issue by chandradeepak** [microsoft/vscode-go#2674]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1. Install vscode. Do necessary changes in setting file according to what you need.
2. Uninstall 
3. Re install vscode. you need to setup machine again. Instead if the setting is tied to an email id or some thing with registration that would be lot of help.
4. It should install all extensions for languages we use previously .
5. Configure IDE as we use before. This would help if some one is switching to new laptop or computer.

**Comment by ramya-rao-a** [comment]
This feature request is language agnostic and therefore the [VS Code repo](https://github.com/Microsoft/vscode) is the right place for it than this repo.
