### ISSUE TITLE
Example of how to specify buildFlags in launch.json for -gcflags="all=-N -l"  

### ISSUE THREAD

**Issue by rook2pawn** [microsoft/vscode-go#2677]
I want to use these flags to build my binary

i.e. 

`go build -gcflags="all=-N -l" hello.go`

How do I specify this exactly in my `launch.json` for debugging?
I know the instructions / manual says `"-tags=whatever_tag"`

But I have a quotes in my flag that need to get passed. Thanks in advance!

**Comment by ramya-rao-a** [comment]
Delve adds the gcflags itself to build your code before using the built binary for debugging.
Do you have any reason to overrride what delve uses?

Related issues #2415
