### ISSUE TITLE
"Rename Symbol" with gorename doesn't work

### ISSUE THREAD

**Issue by coxx** [Microsoft/vscode-go#268]
I have fresh `gorename` available in the PATH but I'm getting the message:

```
Cannot rename due to errors: Error: Command failed: /usr/local/go/bin/gorename -offset /path/to/the/file.go:#17 ...
```
The message is truncated so I can't reproduce it using command line.
How to debug the issue?

**Comment by lukehoban** [comment]
If you hover over the message for a second, you should see the full error text.

You could also try running `/usr/local/go/bin/gorename -offset /path/to/the/file.go:#17 -to foo` in a shell to see what error it reports.

**Comment by coxx** [comment]
This error reproduced when you *select* an identifier but your text cursor is not at its first character.
I think the offset should be first character of selection in case of selection.

![image](https://cloud.githubusercontent.com/assets/349949/14059106/c1416ba0-f348-11e5-950c-74af4a214167.png)

**Comment by pierznj** [comment]
This shouldn't be closed IMO. I always got it and gave up trying to rename symbols because of this error, until I saw this. You shouldn't get a nasty error like this just because you selected the text of the symbol before trying to rename it.

**Comment by ramya-rao-a** [comment]
@pierznj Can you share more details?

I tried renaming with below 3 scenarios and all worked as expected

- cursor inside the symbol
- full text of the symbol selected
- partial text of the symbol selected

**Comment by pierznj** [comment]
Hmm, I just tried again and it worked with the text selected. However, I can definitely say that this feature is unreliable in practice for me. As noted above I gave up trying to use the feature due to errors saying this: 
`failed MSpanList_Insert 0x464110 0x3c235d63c754c 0x0`
It worked when I placed the cursor at the start of the symbol to be renamed, but I have since seen the problem occur that way too, so this may be a red herring.

**Comment by ramya-rao-a** [comment]
> failed MSpanList_Insert 0x464110 0x3c235d63c754c 0x0

that seems very Go specific, most likely an issue with gorename itself.

Am curious, where did you see this error now if the renaming works now

**Comment by pierznj** [comment]
It came up apparently randomly. I wasn't doing anything obviously different. Not helpful, I know :(

**Comment by codeliveroil** [comment]
Same `failed MSPanList_Insert` error for me as well. Rename would work in single file projects like a HelloWorld.go but not in larger ones where the rename would span multiple files and sometimes within a single file as well.

I deleted gorename and had vscode reinstall it and it works fine now.

I couldn't obtain version differences between the old and the new version though I have both binaries. Let me know if there is anything useful that I can retrieve from them. Attached is a bit of the stack:
<img width="250" alt="error" src="https://user-images.githubusercontent.com/16970305/27301528-54063a86-54e8-11e7-9eb1-ef7d4be06045.png">

Out of curiosity, where do the error logs for vscode go to, on the filesystem?

**Comment by ramya-rao-a** [comment]
@codeliveroil If a newer version of `gorename` fixed the issue, then that's the solution. There is nothing else we can do from the Go extension

> Out of curiosity, where do the error logs for vscode go to, on the filesystem?
Actually nowhere. When you are debugging Go code, there is an option to collect traces. But nothing for the rest of the extension features
