### ISSUE TITLE
Feature Request: Support for VSCode's Call Hierarcy Feature

### ISSUE THREAD

**Issue by loganintech** [microsoft/vscode-go#2682]
This functionality would be very useful to me at work: https://code.visualstudio.com/updates/v1_33#_call-hierarchy

![](https://code.visualstudio.com/assets/updates/1_33/call-hierarchy.png)

Sidebar: Asked in gitter, but there didn't seem to be anyone available to answer questions (last messages were 3 and 13 days ago).

**Comment by ramya-rao-a** [comment]
Thanks for bringing this to our attention @loganintech 

The corresponding API is still in preview. I would expect this feature to be provided out of the [language server](https://github.com/Microsoft/vscode-go/#go-language-server) once the api is moved to a stable state

@stamblerre Is this something that gopls can do once the api is stable?

**Comment by stamblerre** [comment]
We intend for `gopls` to support all language features offered by the LSP, so absolutely we can provide the feature once the API stabilizes.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre!

@loganintech Please log a feature request for gopls using the [Go issue tracker ](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)
