### ISSUE TITLE
Add Import could prioritize stdlib packages

### ISSUE THREAD

**Issue by tj** [microsoft/vscode-go#2683]
Currently the "Go: Add Import" command doesn't prioritize core packages, so you often get a bunch of random packages over-powering the standard ones.  Here's a few examples:

<img width="473" alt="Screen Shot 2019-08-03 at 11 10 51 AM" src="https://user-images.githubusercontent.com/25254/62410591-6fd3d980-b5df-11e9-8d06-8d1526ef28b9.png">

<img width="280" alt="Screen Shot 2019-08-03 at 11 15 24 AM" src="https://user-images.githubusercontent.com/25254/62410616-0d2f0d80-b5e0-11e9-9e2e-92a2113c4723.png">

It wasn't a big deal when autocompletion of core packages worked without imports, but I can't seem to get that working anymore `go.autocompleteUnimportedPackages` enabled — maybe a gopls issue?

**Comment by stamblerre** [comment]
The autocompletion of unimported packages is not yet supported in `gopls`, but you can track updates here: https://github.com/golang/go/issues/31906.

**Comment by ramya-rao-a** [comment]
Its a fair ask to sort the standard libraries, PRs are welcome to make the change.

Code Pointers:
- [Set up local dev environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- The `listPackages` method in the `goImport.ts` file is the one that provides the packages that get shown.

**Comment by ramya-rao-a** [comment]
Please try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the fix for this

**Comment by ramya-rao-a** [comment]
The latest update to this extension (0.11.8) has the fix for this.

Thanks for reporting @tj and for the fix @karthikraobr 

Happy Coding!
