### ISSUE TITLE
Do vscode-go support monorepo(not multi-root) multiple project settings

### ISSUE THREAD

**Issue by xujintao** [microsoft/vscode-go#2689]
Steps to Reproduce:

1. Given structure:
```
repo
  |------project1
  |               |---.vscode
  |               |         |----settings.json(eg. "GOOS": "windows" pair in "go.toolsEnvVars")
  |               |
  |               |---src
  |
  |------project2
  |               |---.vscode
  |               |         |----settings.json(eg. "GOOS": "linux" pair in "go.toolsEnvVars")
  |               |---src
```
2. Open repo folder, the project1 will report some "undefined" error. However, open project1 separetely will be ok. Meanwhile https://github.com/microsoft/vscode/issues/32693 says vscode already support monorepo.

**Comment by ramya-rao-a** [comment]
I went through the issue you linked https://github.com/microsoft/vscode/issues/32693, but I don't see anything there that says that the individual vscode settings file in a monorepo are respected.

If you want settings from each folder to be respected, then have to be in a multi-root set up.

Can you elaborate on which part of the linked issues says that what you have described above is supported?

**Comment by xujintao** [comment]
Yes, i went through the issue too. The result is that vscode has not support monorepo until now.
Please close this issue.

**Comment by ramya-rao-a** [comment]
Thanks for confirming
