### ISSUE TITLE
Debugger hangs in OSX

### ISSUE THREAD

**Issue by lennykean** [Microsoft/vscode-go#269]
It happens on all code. When I start the debugger, it looks like its starting but just hangs. I don't get any errors, and there is nothing in the debug console.

Go: 1.6
Delve: v0.11.0-alpha
VS-Code: 0.10.11
vscode-go: 0.6.30

**Comment by lukehoban** [comment]
Could you try updating to the latest vscode-go (currently 0.6.35)? There were some fixes for recent breaking changes in the VS Code debugger which may be what you are hitting.

**Comment by lennykean** [comment]
I updated to 0.6.35 I'm still getting the hanging, but now I have some information in the debug console

`2016/03/25 17:42:56 debugger.go:61: launching process with args: [./debug]
could not launch process: could not fork/exec`

**Comment by lukehoban** [comment]
Sounds like you possibly haven't installed Delve according to the instructions: https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md?  The `could not launch process: could not fork/exec` error is the standard one I've seen when dlv is not signed.  (Delve error messages should definitely be more helpful around this...)

**Comment by lennykean** [comment]
Ah, it was delve. Thanks for pointing me in the right direction. I had to set trust levels higher on my cert before signing. Thanks!

**Comment by ctaggart** [comment]
This is pretty easy to get wrong on the Mac with so many manual steps. I missed the step to set `Code Signing` to `Always Trust`.

In keychains select “System”, and you should find your new certificate. Use the context menu for the certificate (not the public or private keys), select “Get Info”, open the “Trust” item, and set “Code Signing” to “Always Trust”.

![image](https://cloud.githubusercontent.com/assets/80104/14656784/598948d0-063e-11e6-8b5e-8e816a673a8f.png)

After enabling that and making the `dlv` executable again, debugging is working. :-)

**Comment by jb-san** [comment]
I am having the same problem, have followed the install instructions for delve, and no errors when `CERT=dlv-cert make install `, but i also get the ```2016/04/20 14:58:00 server.go:38: Using API v1
2016/04/20 14:58:00 debugger.go:61: launching process with args: [./debug]
could not launch process: could not fork/exec``` any ideas ?

**Comment by lennykean** [comment]
I had a lot of issues getting that to work too. Make sure you are setting the trust levels high enough before you sign it. And it may take multiple tries. It's really a delve issue. You'll see the same problem if you run dlv manually.

**Comment by lukehoban** [comment]
Yeah - installing Delve on OS/X is unfortunately still a manual process.  @steeve just shared a HomeBrew formula that may help folks https://github.com/derekparker/delve/issues/508, and @derekparker is working on producing signed binaries out of the Delve release process https://github.com/derekparker/delve/issues/494.  These should help here.
