### ISSUE TITLE
WSL Not formatting on save

### ISSUE THREAD

**Issue by syc0x00** [microsoft/vscode-go#2691]
This issue is on Windows 10 1809 with WSL Debian
Formatting on save works fine on my MacOS machine

Reproduce:
* Open a go file from WSL in VSCode
* Write incorrectly formatted go
* Save

The output under `Go` doesn't show anything related to the formatting leading me to think it never even runs.

So far I've completely wiped my VSCode settings, `go/src`, and `go/bin` and then reinstalled everything with no luck. Tried both goimports and goreturns and neither worked.

Manually selecting `Format Document` does work.

**Comment by themowski** [comment]
@syc0x00 -- Here's a workaround that I found (taken from my report for #2695):

> I did find a temporary hacky fix. Since Format Document works, I added the following configuration to my settings.json for the remote workspace, which tells VS Code to automatically format my documents on save when I am working on a Go file:
> 
> "[go]": {
>     "editor.formatOnSave": true
> }
> 
> This seems to have fixed the issue, but again, I think it's a hack -- the extension should be handling formatting for me when I save, without needing to set this manually.

I think this might work as a temporary fix for you?

**Comment by syc0x00** [comment]
I'll close this in favor of #2695 which has more information.
