### ISSUE TITLE
Generates go.mod file automatically 

### ISSUE THREAD

**Issue by mrdulin** [microsoft/vscode-go#2692]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ldu020/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ldu020/workspace/go:/Users/ldu020/workspace/github.com/mrdulin/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ldu020/workspace/github.com/mrdulin/golang/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/38/s8g_rsm13yxd26nwyqzdp2shd351xb/T/go-build159636335=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am using vscode and go extension. Recently, I found each project of my workspace has a `go.mod` file in the project root path.

### What did you expect to see?

DON'T generate `go.mod` file in my project of the workspace even it's not related to Golang.

### What did you see instead?

```bash
├── dl-toolkits
│   ├── LICENSE
│   ├── README.md
│   ├── dist
│   ├── go.mod
│   ├── jest.config.js
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── src
│   ├── tsconfig.json
│   └── tslint.json
├── docker-research
│   ├── LICENSE
│   ├── README.md
│   ├── examples
│   ├── go.mod
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   └── test.txt.gz
├── dotfiles
│   ├── LICENSE
│   ├── README.md
│   ├── go.mod
│   ├── iTerm2
│   ├── vim
│   └── zsh
```

As you can see, there is `go.mod` file in each project of my workspace, even these projects are not related to Golang

**Comment by ramya-rao-a** [comment]
Please run the command `Preferences: Open Settings (JSON)` and share any go related settings you might have added/edited.

Also, can you delete these files, and see when do they re-appear? That can help in narrowing down on what feature of the extension is causing this.
