### ISSUE TITLE
Trouble with autocomplete after `go`

### ISSUE THREAD

**Issue by aimran-adroll** [microsoft/vscode-go#2693]
I am having issue with intellisense/autocomplete after typing `go` (goroutine). I am attaching a gif to illustrate the problem

Not sure if this is intended or just an operator error.

![](http://g.recordit.co/w22dZPuiWE.gif)

Details:
I just ran Go:Install/Update tools to make sure I have all the up to date tools.  I have the language server enabled  ` "go.useLanguageServer": true`
```
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by stamblerre** [comment]
This is a know issue with the Go language server that we are working on resolving. See https://github.com/golang/go/issues/29313.

**Comment by aimran-adroll** [comment]
Thanks for the prompt reply. Please close as necessary

**Comment by wtask** [comment]
When the issues like "known issues of gpls" will be done? These issues do not allow to work normally in the vscode. The history is over the years...
