### ISSUE TITLE
Format not running automatically on save with Remote SSH to Linux VM from Windows host

### ISSUE THREAD

**Issue by themowski** [microsoft/vscode-go#2695]
Last night, I updated VS Code to 1.37 (I had been running 1.33.1) and installed VS Code's new Remote SSH extension pack. My use-case is connecting over SSH to a CentOS 7 Linux VM that I have running on my host machine in order to edit code inside the VM, but to have VS Code running on Windows. The VM is running inside VirtualBox; I am not using Windows Subsystem for Linux.

I was originally wondering whether this issue the same as #2691, but the original reporter didn't mention whether they were running Code inside WSL or connecting via Remote SSH, so I figured I'd log a fresh ticket. I wouldn't be surprised if these tickets were related, though.

The overall Remote SSH experience was great, and the vscode-go add-on seemed to work once I got everything squared away configuration-wise, but I immediately noticed that my Go code wasn't formatting when I saved. However, as @syc0x00 noted in #2691, the `Format Document` command **does** work when invoked manually.

I'm working in GOPATH mode and I have everything configured correctly. I am not using the language server (although I tried switching to `gopls` and the issue was still happening).

I also have VS Code installed on the Linux VM, so I did some additional testing there (without Remote SSH) to try to see whether the problem was just that vscode-go is broken on Linux, or whether it's a problem with Remote SSH + vscode-go.

Here are some relevant stats about versions and whatnot:

- **Host machine:** Windows 10 Pro x64
- **Target VM:** CentOS 7 Linux x64
- **VS Code version (Host):** 1.37 x64
- **VS Code version (VM):** 1.35.1 x64 then updated to 1.37 x64
- **vscode-go version:** 0.11.4 (also tried 0.10.2)
- **ms-vscode-remote.remote-ssh version:** 0.45.5

I didn't change any of the settings regarding formatters, so the default for the extension is what I'm using (`goreturns` I believe?).

Below is a table that I put together based on my testing. I tried running VS Code on Windows, on my VM directly, and also via Remote SSH from Windows to Linux. I tried 2 different versions of the extension as well, since originally I had VS Code 1.35.1 with vscode-go 0.10.2 on Linux.

VS Code version | Editing method | vscode-go version | Auto-format?
-----------------|-----------------|--------------------|--------
1.35.1 | CentOS 7 Linux | 0.10.2 | Yes
1.37 | CentOS 7 Linux | 0.10.2 | Yes
1.37 | CentOS 7 Linux | 0.11.4 | Yes
1.37 | Windows 10 | 0.11.4 | Yes
1.37 | Remote SSH to Linux VM | 0.10.2 | No
1.37 | Remote SSH to Linux VM | 0.11.4 | No

These tests imply that the problem is with Remote SSH and the vscode-go extension, and not actually an issue with the extension running in Code natively on Linux.

I did find a temporary hacky fix. Since `Format Document` works, I added the following configuration to my `settings.json` for the remote workspace, which tells VS Code to automatically format my documents on save when I am working on a Go file:

```json
"[go]": {
    "editor.formatOnSave": true
}
```

This seems to have fixed the issue, but again, I think it's a hack -- the extension should be handling formatting for me when I save, without needing to set this manually.

I don't really know anything about how the extension works, but I'm wondering if there's some kind of "save" event that the extension monitors for that is not being captured when in Remote SSH mode?

I would also be interested to see whether anyone can replicate this behavior while SSH'ing into a machine with a different OS (non-Linux).

**Comment by syc0x00** [comment]
@themowski 

I'm running VSCode with the remote WSL extension - not remote SSH.

![1](https://user-images.githubusercontent.com/20033376/63207323-a2b6ac80-c078-11e9-9a4f-2634aef24568.png)

The `settings.json` fix you provided does work for me. Thanks!

Here's more of my version information:

```
VSCode
Version: 1.37.0-insider (user setup)
Commit: 5e08ee01b7daee99cdda2456f19d77e715fb8762
Date: 2019-08-05T21:18:05.921Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Go Extension:
0.11.4

Go:
go version go1.12.5 linux/amd64

Windows:
```
![2](https://user-images.githubusercontent.com/20033376/63207401-11483a00-c07a-11e9-8f88-68e49c0e45d4.png)

**Comment by yaegashi** [comment]
Probably the same problem.  I'm running VSCode Insider on macOS and connecting to a Raspbian stretch host.  With the following `.vscode/settings.json` auto-formatting works on save, but it still fails to fix missing/unused imports on save.

```console
{
    "[go]": {
        "editor.formatOnSave": true
    },
    "go.useLanguageServer": true
}
```

It gives correct suggestions to fix import problems, but won't automatically fix them on save.

![image](https://user-images.githubusercontent.com/106724/63964692-9ac42700-cad2-11e9-92d9-37180ed3061a.png)

```
Version: 1.38.0-insider
Commit: 8cd00a7935eabef4aad0b0130b1d46daca0a47aa
Date: 2019-08-27T06:10:29.182Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

```
Name: Go
Id: ms-vscode.go
Description: Rich Go language support for Visual Studio Code
Version: 0.11.4
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go
```

```console
$ code --list-extensions --show-versions
ms-vscode-remote.remote-containers@0.71.0
ms-vscode-remote.remote-ssh@0.45.6
ms-vscode-remote.remote-ssh-edit@0.45.6
ms-vscode-remote.remote-ssh-explorer@0.45.6
ms-vscode-remote.remote-wsl@0.39.4
ms-vscode-remote.vscode-remote-extensionpack@0.16.0
```

```console
$ go version
go version go1.12.9 linux/arm
```

**Comment by ezzak** [comment]
I've noticed that increasing the default timeout for format on save has fixed the issue for me with prettier on WSL.

`"editor.formatOnSaveTimeout": 1500`

**Comment by jlmelville** [comment]
The solution given by @ezzak also worked for me with formatting python code with the `black` tool, using WSL, so it seems like at least some of these problems are just due to needing a longer timeout due to the latency introduced by using the `Remote - WSL` extension.

**Comment by stamblerre** [comment]
I believe that the formatting on save timeouts no longer apply in recent versions of VS Code. Import organization can be applied on save by adding the following setting:

```json5
"[go]": {
	"editor.codeActionsOnSave": {
		"source.organizeImports": true,
	}
}
``` 

If you see this issue again, please file a new issue in our new repository (https://github.com/golang/vscode-go/issues/new/choose), as we are migrating: https://github.com/microsoft/vscode-go/issues/3247.
