### ISSUE TITLE
When debugging with "go.toolsEnvVars" that are incompatible with host machine, the failure message is opaque

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode-go#2696]
Steps to Reproduce:
1. Open a Go project that has launch configurations
2. Open settings and edit `"go.toolsEnvVars"` and add `"GOOS": "windows"` (or `"GOOS": "linux"` if your OS is Windows)
3. Attempt to launch a debug session

The error:

```
could not launch process: stub exited while waiting for connection: exit status 0
Process exiting with code: 1
```

The issue is that it is not at all obvious why this is failing. Ideally, `vscode-go` would know that the debugger failed because of GOOS/GOARCH. But I don't know how it would do that, without `dlv` providing a more meaningful error. Failing that, a warning would be nice. "By the way, we see you've changed GOOS/GOARCH such that the debugger will likely fail."

**Comment by ramya-rao-a** [comment]
Thanks for reporting @firelizzard18!

Are you saying that we should ensure that these env vars should get passed to the process in which delve is launched?
Or that such env vars shouldn't apply to debugging, because well, we cannot debug a binary built for one OS in another OS?

**Comment by firelizzard18** [comment]
If I set `GOOS` to another OS, or if I set `GOARCH` to an incompatible architecture, debugging should fail. That is the behavior I expect, and the behavior that makes the most sense. My ask is for a more useful failure message.

Realistic solution (1):

> When I launch the debugger, `vscode-go` checks `go.toolsEnvVars` and notices that I've changed `GOOS` and/or `GOARCH`, and creates a notification that says, "You have configured `go.toolsEnvVars` in such a way that debugging is likely to fail"

Realistic solution (2):

> I launch the debugger, and it fails. `vscode-go` notices that `dlv` failed to launch, checks `go.toolsEnvVars`, notices `GOOS`/`GOARCH`, and creates a notification that says, "The debugger failed to launch, likely because you have configured `go.toolsEnvVars` in a way that is not compatible with this host"

Ideal solution:

> I launch the debugger, and it fails. `vscode-go` somehow knows that it failed specifically because `dlv` tried to launch a binary that is incompatible with this system. It creates a notification that says, "The debugger failed to launch because `GOOS`/`GOARCH` in `go.toolsEnvVars` is incompatible with this host"

**Comment by ramya-rao-a** [comment]
Thanks for the clarification @firelizzard18!

We can definitely work on the ideal solution that you have proposed and PRs are most welcome to do this.

Code Pointers:
- [Set up local dev environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- After the below point in the code, we have access to the env vars set in the toolsEnvVars setting as well as the ones set in the debug configuration from launch.json file. https://github.com/microsoft/vscode-go/blob/0.11.4/src/goDebugConfiguration.ts#L69-L74
- You should be able to make the relevant checks and throw an error if the GOOS/GOARCH is incompatible.

**Comment by sagardutta** [comment]
@ramya-rao-a I would like to take a shot at this issue.
Need a clarification though, can we check the GOOS var set in toolEnvVars against the OS we are currently running  instead of values inside launch.json ?
We are trying to notify the user when the GOOS var in toolEnvVars is different from the OS it is running on, right ?

**Comment by ramya-rao-a** [comment]
@sagardutta you can try `process.platform` and `process.arch`. These should give you what you are looking for. But do test it out on multiple platforms to ensure you don't have any casing issue or different forms of representing the arch.

**Comment by hyangah** [comment]
Out of curiosity - when and why do people want to use a different GOOS/GOARCH for toolsEnvVars? I am wildly guessing they are used for program analysis e.g. gopls running for different mode, etc. If so, is it appropriate to apply them when invoking `dlv`?  Shouldn't we unset any GOOS/GOARCH env vars for debugging?

**Comment by firelizzard18** [comment]
@hyangah Your guess is correct. I work on tools that need to operate in multiple environments, so I configure the tools to use a different GOOS/GOARCH so `gopls` etc work correctly as I am working.

> If so, is it appropriate to apply them when invoking `dlv`?

It is not. You may notice that the issue as I wrote it is not that I think this should work, it's that "the failure message is opaque".

> Shouldn't we unset any GOOS/GOARCH env vars for debugging?

Yes, but I forget. Depending on the circumstances, it may be hours or days between when I modify GOOS/GOARCH and when I need to debug locally. The issue is that the error message, `could not launch process: stub exited while waiting for connection: exit status 0` is not at all clear.

**Comment by ramya-rao-a** [comment]
From https://github.com/microsoft/vscode-go/pull/3218#discussion_r420390471

> BTW, delve doesn't return a meaningful error message in this case? I think we should file a bug upstream.

I agree with this. We should log an issue for delve and see if there is a chance to provide better error messages from there. It is very much possible that one uses delve directly with incompatible GOOS value. Such users should get meaningful errors as well

>  If so, is it appropriate to apply them when invoking dlv? Shouldn't we unset any GOOS/GOARCH env vars for debugging?

Another option is to ignore values for these env variables from `go.toolsEnvVars`. Such a change would go to https://github.com/microsoft/vscode-go/blob/0.14.2/src/goDebugConfiguration.ts#L69-L74

**Comment by hyangah** [comment]
If the feature request is not accepted
I think we can still compare `GOHOSTARCH/GOHOSTOS` and `GOARCH/GOOS` values from `go env` output and reject early before `launch`ing. But I am not sure if there are any advanced use cases where such simple environment checks can't capture or cause false positives. (e.g. using `alternateTools` to shell out `dlv` magically)

**Comment by firelizzard18** [comment]
Maybe show a warning instead of rejecting?

**Comment by hyangah** [comment]
Was told `dlv@master` already has more sensible error message. `not an executable file`.
Is the error message more helpful? 

Or do you want to have more specific error messages mentioning the misleading Go env vars?

**Comment by firelizzard18** [comment]
That is more helpful, but "not an executable file" is still a less than ideal error message. I work for a customer who requires that I use rather invasive AV software when working on their systems. Depending on the day of the month and its mood, the AV software may decide my compiled executable is a virus (I think it has a grudge against Go). If I saw "not an executable file," I can see myself assuming that the AV software is causing the issue, and then spending the next 20 minutes yelling at my computer before realizing my mistake.

When delve fails with this error, I'd like a warning that says, in essence:

> I noticed that dlv failed with 'not an executable file' and you have configured GOOS and/or GOARCH. You might want to change that and relaunch.

*Actually*, it would be awesome if the warning notification had a button for "do what I just did but ignoring GOOS/GOARCH". So any time I try to launch the debugger and dlv fails like this, I get:

> Delve failed with 'not an executable file'. This may be caused by overriding GOOS and/or GOARCH.
> [Launch without overrides]

**Comment by ramya-rao-a** [comment]
I am reluctant on relying on the contents of the error message from delve as error messages can change any day. That takes us back to showing a warning before even starting delve. We can have this warning include 2 buttons: `Ignore GOOS and GOARCH from settings` and `Continue`

Thoughts?

**Comment by firelizzard18** [comment]
> `Ignore GOOS and GOARCH from settings` and `Continue`

Works for me

**Comment by ramya-rao-a** [comment]
Hey @firelizzard18,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Please subscribe to https://github.com/golang/vscode-go/issues/114 for further updates on this issue.

Thanks for all the support & Happy Coding!
