### ISSUE TITLE
Autocompletion is showing weird info, not actual docs

### ISSUE THREAD

**Issue by henrahmagix** [microsoft/vscode-go#2699]
Context:
- workspace is not in GOPATH
- `gopls` is not installed or running
- this extension is up-to-date
- `go version go1.12.7 darwin/amd64`, so go modules are being used (outside of GOPATH)

Steps to Reproduce:

1. import a package
2. write the package name followed by dot `.` and wait for the autocompletion to show
3. see correct methods appear in autocomplete list
4. see odd autocompletion info for the first method
5. cycle through the methods
6. see the info is identical for every method apart from the `index` incrementing

This may be related to my problems in #2698. I will close this if solved by the other issue.

These screenshots were made with `"cloud.google.com/go/storage"` package; the same occurred with `strconv` (stdlib).

![image](https://user-images.githubusercontent.com/1429026/63097625-de625100-bf68-11e9-8a9a-1c7cd96d20f9.png)
![image](https://user-images.githubusercontent.com/1429026/63097634-e4583200-bf68-11e9-890f-0bb0588c1081.png)

However, hovering over a method call shows the correct documentation, so at least I can use the autocomplete list to find the method, select it, then hover to see what it does, i.e. I'm not 100% lost.
![image](https://user-images.githubusercontent.com/1429026/63098155-29c92f00-bf6a-11e9-95f0-8dee73d8d714.png)

**Comment by ramya-rao-a** [comment]
That is very weird indeed. By the looks of it, it looks like internal data used by VS Code or the language server to determine sorting and fuzzy matching of completion results.

- Are you using the language server?
- Which version of VS Code are you using?
- Please share any Go related settings you might have edited/added. You can get this after running the command `Preferences: Open Settings(JSON)`

**Comment by henrahmagix** [comment]
> * Are you using the language server?

Narp.



> * Which version of VS Code are you using?

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0



> * Please share any Go related settings you might have edited/added. You can get this after running the command `Preferences: Open Settings(JSON)`

```json
"go.autocompleteUnimportedPackages": true,
"go.buildOnSave": "workspace",
"go.gocodeAutoBuild": true,
"go.useCodeSnippetsOnFunctionSuggest": true,
"go.coverageOptions": "showUncoveredCodeOnly",
"go.formatTool": "goimports",
"go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
"go.coverOnSave": true,
"go.testOnSave": true,
```

**Comment by ramya-rao-a** [comment]
Thanks @henrahmagix 

@jrieken The below (on the right) looks like data used by VS Code internally to rank the completion items. Any idea on what could cause this?

![image](https://user-images.githubusercontent.com/1429026/63097625-de625100-bf68-11e9-8a9a-1c7cd96d20f9.png)

**Comment by jrieken** [comment]
Yes - that's a debug feature (explain mode) which you toggle when pressing `Cmd+/` (while suggest is visible).

**Comment by henrahmagix** [comment]
Aha! That's it! Thanks @ramya-rao-a and @jrieken, I just toggled `cmd+/` while suggestions were visible, and now the correct information is showing when I changed suggestion!

![](https://media3.giphy.com/media/26u43S8HNqOcJ1rfG/giphy.gif?cid=790b7611f3412cb94eaae61536c4d2b3a5cb13c7cc819589&rid=giphy.gif)

**Comment by henrahmagix** [comment]
![](https://media3.giphy.com/media/LOW71WsuI5B3vcyhdY/giphy.gif?cid=790b76117bf01eef0fe9ecfb5986a29288193c1708ba1996&rid=giphy.gif)

**Comment by ramya-rao-a** [comment]
Thanks @jrieken!

**Comment by harmnot** [comment]
@henrahmagix is your setting.josn u mention above work well for autocomplete ? because my go can't atucomplete at all , I have tried uninstall and reinstall VSCode but nothing

**Comment by henrahmagix** [comment]
@harmnot Yes, although slowly because I'm running go with modules turned on, i.e. outside of GOPATH, and I'm _not_ using gopls (Go language server) because it's still experimental support in vscode-go.
