### ISSUE TITLE
launch.json options (args,cwd) may not effective

### ISSUE THREAD

**Issue by yuntan** [Microsoft/vscode-go#27]
When I debug my go program, I want to change workdir and pass some args to program and modify `launch.json`

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch main.go",
			"type": "go",
			"request": "launch",
			"program": "main.go",
			"stopOnEntry": false,
			"env": {},
			"args": ["../sample"],
			"cwd": "build"
		}
	]
}
```

and start debugging. But I couldn't find args is passed to it and its' work dir was different from I specified. I run `ps aux|grep myprogram` and got

```
yuntan    9879 18.5  0.3 383580 27368 ?        Sl   12:19   0:01 /home/yuntan/Workspace/go/bin/dlv debug --headless=true --listen=127.0.0.1:2345 --log /home/yuntan/Workspace/go/src/github.com/passto/myprogram/main.go
yuntan    9941  0.0  0.1 201576 11940 ?        tl   12:19   0:00 ./debug /home/yuntan/Workspace/go/src/github.com/passto/myprogram/main.go
```

It seems `debug` is debug binary of my program built by delve and vscode passes invalid argument. When I run `dlv debug -- somearg` in project dir and run `ps aux|grep somearg` I got

```
yuntan   14269  1.2  0.3 505404 31268 pts/4    Sl+  12:25   0:00 dlv debug -- somearg
yuntan   14329  0.0  0.1 137356 10996 pts/4    Sl   12:26   0:00 ./debug somearg
```

argument I specified is passed to `debug` binary.

VS Code 0.10.1 Go Extension 0.6.7 on Linux

**Comment by lukehoban** [comment]
Yes - this is a bug.  

Currently the `stopOnEntry`, `args`, `cwd` and `env` debug settings are not being passed through to Delve, so none of these settings will work yet.

**Comment by yuntan** [comment]
I made `args` and `env` settings passed to Delve. https://github.com/yuntan/vscode-go/commit/fb0907e8f5ddc24d2f8850467a4d49805ec8d936

At the moment, Delve has no option to specify workdir of debug target process. So I've made issue to add `--wd` command arg to Delve. https://github.com/derekparker/delve/issues/295
