### ISSUE TITLE
Can not reference or find function or identifiers from another file under the same package

### ISSUE THREAD

**Issue by DeshErBojhaa** [microsoft/vscode-go#2702]
Program structure
<img width="325" alt="Screenshot 2019-08-16 at 9 58 31 PM" src="https://user-images.githubusercontent.com/46394832/63182133-9aa83e00-c073-11e9-8e16-7216e650bb77.png">
in the api directory, simplified main file contains,
```go
package main

import (
	"github.com/globalsign/mgo"
)
type Server struct {
	db *mgo.Session
}
func main(){}
```

When I try to write method for `Server` in `pool.go` file, it can not reference `Server` (Code simplified)
```go
package main

import (
	"net/http"
)
func (s *Server) handlePolls(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case "GET":
		s.handlePollsGet(w, r)
		return
	}
}
```
<img width="796" alt="Screenshot 2019-08-16 at 10 47 20 PM" src="https://user-images.githubusercontent.com/46394832/63183873-e3fa8c80-c077-11e9-904c-f473eec86d30.png">
Also notice in the picture, vscode can not import the external modules. But this error occurs randomly and goes away automatically. I believe I have all the updated go tolls by running 
 `Go: Install/UpdateTools`

The program builds fine.

**Comment by ramya-rao-a** [comment]
- Please share any Go related settings you might have added/edited. You can get these after running `Preferences: Open Settings(JSON)` command
- Are you using Go modules? 
- Is your project under your GOPATH? You can find the GOPATH by running the command `Go: Current GOPATH`
- Please share the errors you are seeing

**Comment by elebertus** [comment]
I'm seeing this behavior as well.

Oddly after running through your bullets to post information the package started resolving after I ran `Go: Current GOPATH`, unfortunately didn't catch any logs for it though. Not sure if this is really helpful or not though.

**Comment by DeshErBojhaa** [comment]
Hi, @ramya-rao-a thanks for your response, here is the data you asked fo,
``` json
    "go.useLanguageServer": true,
    "go.toolsEnvVars": {
        "GO111MODULE": "on",
    },
```
- I am not using Go modules
- My project is under my gopath
  - Project path : `/Users/tamjidahmed/code/Go/src/github.com/DeshErBojhaa/x`
  - Gopath : `/Users/tamjidahmed/code/Go`
- Errors:
  - undeclared name: Serve LSP [10,10]
  - undeclared name: respond LSP [23,3]
  - undeclared name: Serve LSP [38,10]
And so on...

**Comment by yulrizka** [comment]
I have the same issue when the go.mod is not on the root path of directory. Most of the command has PWD='[vscode root directory]'. Would it work if I can configure that to the root module directory?

**Comment by asciifaceman** [comment]
Experiencing the same issue with struct methods not being found by a referencing project if those methods are not in the same file as the struct.

The dependent package is included in the workspace as well.

This is fundamentally broken behavior

**Comment by stamblerre** [comment]
> If you are using the language server with modules, you have to open VSCode to the directory of the module root (the directory that contains the `go.mod` file). There is additional information on how to troubleshoot with `gopls` on the [wiki](https://github.com/golang/go/wiki/gopls#troubleshooting) page.

Reiterating my previous comment that for `gopls` to work with modules, you have to open your directory to the module root. We are working on modifying this requirement, but for now, if you want to have multiple modules in your VSCode window, you can use VSCode's workspace folders feature (File -> Add Folder to Workspace). You can save this workspace configuration file and open workspaces automatically.

**Comment by asciifaceman** [comment]
My gopls is working with modules, it's worked fine until I came across struct methods not in the same file as the struct.

> The dependent package is included in the workspace as well.

This issue is not that.

**Comment by stamblerre** [comment]
Can you include a bit more information so that I can help you investigate this? Information for troubleshooting `gopls` and what to include in an issue can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md). The output of `gopls -rpc.trace -v check path/to/file.go` will be the most useful.

**Comment by ramya-rao-a** [comment]
Closing this issue because it needs more information and has not had recent activity. 

If there are any issues regarding finding references when using the language server, please see the [Troubleshooting guide for gopls](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md)
