### ISSUE TITLE
Code navigation and lsp doesn't work when using go.mod replace

### ISSUE THREAD

**Issue by krasi-georgiev** [microsoft/vscode-go#2704]
As soon as you put something in the go.mod replace as
```
replace github.com/calvernaz/rak811 => ../local/rak811
```

The code navigation(clicking on the function name) still takes you to `github.com/calvernaz/rak811`

If I change some code in ../local/rak811 LSB complains about errors as it uses the `github.com/calvernaz/rak811`  and ignores the replace directive.

**Comment by stamblerre** [comment]
Are you using `gopls` for LSP? If so, please file an issue on the Go issue tracker: https://github.com/golang/go/issues.

**Comment by krasi-georgiev** [comment]
thanks, can't you just move this issue there?

**Comment by krasi-georgiev** [comment]
moved to https://github.com/golang/go/issues/33731
