### ISSUE TITLE
Install/Update tools fails silently when go binary is built from non-stable release

### ISSUE THREAD

**Issue by Goodwine** [microsoft/vscode-go#2705]
### Steps to Reproduce

1. Build go from source at go1.13beta1
```sh
$ pwd
/home/goodwine/go

$ go version
go version devel +60f14fddfe Wed Jun 26 16:35:14 2019 +0000 linux/amd64

$ git log -n 1
commit 60f14fddfee107dedd76c0be6b422a3d8ccc841a (HEAD, tag: go1.13beta1)
[...]
```

2. In VSCode `Ctrl + Shift + P` -> "Go: Install/Update Tools"
    * This works!
3. Go to VSCode settings and add:
```json
  "go.useLanguageServer": true,
```
4. In VSCode `Ctrl + Shoft + P` -> "Go: Install/Update Tools"
    * This **doesn't** work!

### Why it happens
I opened the devtools screen and saw this exception:
```
TypeError: Cannot read property 'major' of null
	at getTools (/home/goodwine/.vscode/extensions/ms-vscode.go-0.11.4/out/src/goInstallTools.js:117)
	at getMissingTools (/home/goodwine/.vscode/extensions/ms-vscode.go-0.11.4/out/src/goInstallTools.js:507)
	at util_1.getGoVersion.then.goVersion (/home/goodwine/.vscode/extensions/ms-vscode.go-0.11.4/out/src/goInstallTools.js:444)
```

Then I look at the code that checks whether to display `gopls` and noticed that there's a check [here](https://github.com/microsoft/vscode-go/blob/094225996e3ee75a1561eb190702a853dbb36f84/src/goInstallTools.ts#L125-L127) that looks at `goVersion` to see that the semver is > 1.10

The problem is that for builds that aren't from a stable release, the goversion obtained from utils.ts is `null`.

**Related issue**: https://github.com/golang/go/issues/11972

**Comment by Goodwine** [comment]
I may have a fix for this today or monday if no one else is taking it, just have to make sure i can do the CLA thingy

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Goodwine!

I have pushed a fix and you should be able to see it in the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension
