### ISSUE TITLE
vscode go debug is unusable

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-go#2706]
```go
package main

import (
	"net/http"
)

func main() {
	url := "http://www.xxx.com?a=111111111111111111111111111111111111111111111111111111"
	http.Get(url)
}
```

for example, if I make a breakpoint at "http.Get(url)" 

I want to see what url is.

vscode go only shows part of the string.

I have to use fmt print to see what the url is.

In other extensions, like python, I don't see things like this when using default settings.

The go extension can't show variables when debugging.

AND THAT'S WHAT DEBUGGING IS FOR

**Comment by kzhui125** [comment]
```py
strLine = ','.join([str(x) for x in range(1000000)])
print("1")
```

In the VSCode python extension, if I make a breakpoint at line 2, I can see and copy the value of strLine

But in go extension, I can only see extremely few characters.

What a big difference!

Now I have to add fmt.Println in code again and again to debug.

**Comment by SteelPhase** [comment]
You should be able to resolve this with the information [https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code](here).

`maxStringLen` can be adjusted to display more bytes of a string.

**Comment by kzhui125** [comment]
The default setting of maxStringLen is very small, it's unusable.

Because go extension has performance issue with larger values?

I will try a larger value

**Comment by ramya-rao-a** [comment]
Thanks @SteelPhase!

We use [delve](https://github.com/go-delve/delve) to provide the debugging feature which has these values set as default, and so we use the same.
