### ISSUE TITLE
go.liveErrors won't disable

### ISSUE THREAD

**Issue by GrimTheReaper** [microsoft/vscode-go#2707]
Under `~/.config/Code/User/settings.json`, I have put the section `go.liveErrors` and set it to be disabled, but it won't turn off. Not sure how to troubleshoot this, and I'm not sure how to fix it. I updated an hour ago and now its a thing. 

``` json
    "go.liveErrors": {
        "enabled": false
    }
```

**Comment by ramya-rao-a** [comment]
This setting is for the live errors feature from the extension.
Do you have the language server enabled? If yes, then the language server itself also provides the live diagnostics feature
