### ISSUE TITLE
go add struct tags failed

### ISSUE THREAD

**Issue by tsyzthh** [microsoft/vscode-go#2709]
thank you for help!

Issue Type: <b>Bug</b>

Cannot modify tags: invalid line directive found: "//line /path/to/file:1"

go settings

![image](https://user-images.githubusercontent.com/28971411/63575376-82c54280-c5bc-11e9-9def-3a2775f1984e.png)

keybindings

![image](https://user-images.githubusercontent.com/28971411/63575394-8c4eaa80-c5bc-11e9-8118-cddc82b58f2f.png)

Extension version: 0.11.4
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.16GB free)|
|Process Argv|E:\gopath\src\gitlab.dev.zhixin2018.cn\learning\gin-blog|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pmkroeker** [comment]
Related here https://github.com/fatih/gomodifytags/issues/45

**Comment by ramya-rao-a** [comment]
Thanks for reporting @pmkroeker 
I have replied on the upstream issue, this is a problem with the `gomodifytags` tool itself and not the VS Code plugin unless the usage of the tool has changed.

**Comment by ramya-rao-a** [comment]
Closing in favor of the upstream issue
