### ISSUE TITLE
OOTB Syntax Highlighting is poor

### ISSUE THREAD

**Issue by ProTip** [Microsoft/vscode-go#271]
Out of the box I see three different colors:

* Blue for certain key words
* Orange-ish for strings
* White for everything else

This is pretty bare bones. Does this sound right or am I doing something wrong?

**Comment by rogeralsing** [comment]
Changing the color theme makes it better, seems like the default theme just use white for a lot of different token types.

**Comment by egamma** [comment]
The recommendation is to use the `Light+' or `Dark+` themes if you want more color.
Pls see this issue for the background https://github.com/Microsoft/vscode/issues/1849.

**Comment by lukehoban** [comment]
Per @egamma's comment, I think this is just an issue with the default theme being used.  Closing for now.
