### ISSUE TITLE
go debug launch doesn't work

### ISSUE THREAD

**Issue by CarpeDiemKopi** [microsoft/vscode-go#2712]
![grafik](https://user-images.githubusercontent.com/32836136/63640625-b5496b00-c6a2-11e9-908b-7ce7b8439f4c.png)

and nothing happens.   
If I use Debug Start Debugging everything is OK.

launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }
    ]
}
```

What am I doing wrong?

**Comment by ramya-rao-a** [comment]
Can you elaborate on what the exact issue is and the exact steps?

**Comment by CarpeDiemKopi** [comment]
I can debug this little go program with Debug Start Debugging: 

![image](https://user-images.githubusercontent.com/32836136/63702197-c7ecad00-c826-11e9-9cf0-9a1d7d05081e.png)

![image](https://user-images.githubusercontent.com/32836136/63701989-59a7ea80-c826-11e9-9330-e709cdd81a31.png)

But nothing happens if I go this way: 

![image](https://user-images.githubusercontent.com/32836136/63702555-7264d000-c827-11e9-902b-0b0e9b981e19.png)

The program is neither executed nor debugged.
