### ISSUE TITLE
Key binding for organize imports

### ISSUE THREAD

**Issue by suzmue** [microsoft/vscode-go#2715]
I am using vscode-go with gopls.

settings.json: 
```
    "go.useLanguageServer": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "files.eol": "\n",
    "go.languageServerFlags": [
        "serve",
        "-debug=localhost:6060",
        "-rpc.trace"
    ],
    "go.toolsEnvVars": {
        "GO111MODULE": "on",
    },

```

If I invoke the organize imports keybinding, I expect the codeAction with kind="source.organizeImports" to be requested and applied, but nothing happens.

Organize Imports keybinding is invoked when: `editorTextFocus && !editor.Readonly && supportedCodeAction = source.OrganizeImports`

Running with a patched version that has gopls initialized with CodeActionOptions set, does not appear to fix the issue:
```
codeActionProvider: CodeActionOptions {
   CodeActionKinds: {"source.organizeImports"},
}
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @suzmue!

@stamblerre Do you have any ideas here as to why the keybinding would not work as expected for organize imports?

**Comment by stamblerre** [comment]
It's actually fixed with the latest version of the language client as well - increasing the version should fix it.

**Comment by ramya-rao-a** [comment]
Version 0.11.5 of this extension released in September has the updated language client which has the fix.
