### ISSUE TITLE
Tooltip background color

### ISSUE THREAD

**Issue by rogeralsing** [Microsoft/vscode-go#272]
The tooltips when hovering method names etc. are somewhat hard to read as the background and syntax highlight is the same as the rest of the code window.
it would be nice if at least the background color was a bit different, (lighter/darker depending on theme)

For example, the peek definition makes things much clearer, there is a distinct bg color that shows that this block of code is from somewhere else.

**Comment by lukehoban** [comment]
This issue was moved to Microsoft/vscode#4933

**Comment by lukehoban** [comment]
Moving this to VS Code since it's a general issue.  There doesn't appear to be anything an extension can do to override this, but even if there was, it seems to make sense to address generally.
