### ISSUE TITLE
Cannot import xxxx LSP with go mod

### ISSUE THREAD

**Issue by dingrui37** [microsoft/vscode-go#2720]
![image](https://user-images.githubusercontent.com/22718365/64016218-f1744400-cb58-11e9-8c22-202c95c97e22.png)

The demo is from  https://github.com/golang/go/wiki/Modules, I can execute `go run hello.go` 
but it always gives an error note "cannot import rsc.io/quote (no package data for import path rsc.io/quote) LSP" , it cannot jump to the package too.

**Comment by dingrui37** [comment]
![image](https://user-images.githubusercontent.com/22718365/64020230-a7449000-cb63-11e9-94c3-a59ee4164c7d.png)

**Comment by stamblerre** [comment]
@dingrui37: Can you check if this issue reproduces with the latest version of `gopls` (`gopls version`)? Run `go get golang.org/x/tools/gopls@latest` to update.

**Comment by dingrui37** [comment]
yes, it reproduces with the  latest version of gopls
```
dingrui@dingrui:~/go/src/etcd-proxy$ gopls version
golang.org/x/tools/gopls v0.1.2
    golang.org/x/tools/gopls@v0.1.3 h1:CB5ECiPysqZrwxcyRjN+exyZpY0gODTZvNiqQi3lpeo=
```
but after go mod vendor, it works.
`it dingrui@dingrui:~/go/src/etcd-proxy$ go mod vendor`

**Comment by ramya-rao-a** [comment]
@stamblerre Do you have any leads here?

**Comment by stamblerre** [comment]
@dingrui37: It looks like you are using modules, but `gopls` is looking for your dependencies in your `$GOPATH`. What is the value of `GO111MODULE`? Have you configured it in your VSCode `go.toolsEnvVars`?

**Comment by oiar** [comment]
just set go mod on and set go.toolsEnvVars on

**Comment by dingrui37** [comment]
@oiar  Can you give me a screenshot about how to set? thank you

**Comment by oiar** [comment]
![image](https://user-images.githubusercontent.com/44365441/65486244-88bd8480-ded6-11e9-90cd-f16b7d63608b.png)

![image](https://user-images.githubusercontent.com/44365441/65486317-b4406f00-ded6-11e9-873f-fa1ecec99c3e.png)

set them and restart

**Comment by dingrui37** [comment]
thank you @oiar

**Comment by asfaltboy** [comment]
That worked for me too! @oiar @stamblerre is this workaround documented somewhere? If it is not, I'd love to contribute by documenting it.

Note: it seems the most appropriate location for this to be mentioned is in [the "Go modules support in Visual Studio Code" wiki page][1]. However, it seems one cannot easily contribute to the wiki, as edits are closed to maintainers only... we may want to consider moving the docs to a folder in the repo, GitHub will render markdown nicely.

[1]: https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code

**Comment by dastier** [comment]
@oiar 's solution (setting 'GO111MODULE' in 'go.toolsEnvVars' resolves the issue. Why is this closed without updating the wiki?

**Comment by stamblerre** [comment]
This workaround should only be needed if the user has not configured `GO111MODULE` in their environment, or if the value of `GO111MODULE` needs to be different in the VSCode environment for some reason. I would be hesitant to suggest it as a necessity. Perhaps a better alternative would be to link users to the [Modules wiki page](https://github.com/golang/go/wiki/Modules), which has some description of the `GO111MODULE` environment variable. What do you think, @ramya-rao-a?

**Comment by ramya-rao-a** [comment]
@stamblerre If I got this right, then the issues is that `gopls` needs GO111MODULE to be set to `on` when the project is under GOPATH and that it is not able to respect the `auto` value?

**Comment by stamblerre** [comment]
No,  since `gopls` uses the `go` command under the hood, it does respect the value of `GO111MODULE`. I am not sure why setting `GO111MODULE=on` would fix an issue, unless `GO111MODULE` was not set to `auto`, or a module had not yet been initialized.

**Comment by asfaltboy** [comment]
> No, since `gopls` uses the `go` command under the hood, it does respect the value of `GO111MODULE`. I am not sure why setting `GO111MODULE=on` would fix an issue, unless `GO111MODULE` was not set to `auto`, or a module had not yet been initialized.

I think that's what's going on for me, my vscode env was not initialized with all variables (in fact even go failed to be found, and I had to add a `PATH`  (alongside `GO111MODULE` et-al) in `go.toolsEnvVars` to make any of the go tools work...

**Comment by stamblerre** [comment]
@asfaltboy: Do you mind sharing your VSCode settings (`Ctrl + Shift + P` -> `Preferences: Open Settings (JSON)`)? What is the output of `go env`?
