### ISSUE TITLE
Extension does not respect "workspaceSymbols" config option

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode-go#2721]
Language server (gopls) enabled, This configuration option:
```
    "go.languageServerExperimentalFeatures": {
        // ...
        "workspaceSymbols": true,
        // ...
    },
```
doesn't work. No matter if it's `true` or `false`, extension will always invoke `go-symbols`.

**Comment by ramya-rao-a** [comment]
I believe this is because `gopls` doesn't yet support workspace symbols feature.
@stamblerre ?

**Comment by inliquid** [comment]
It may not support, but the thing is that as you can see from the description, VS Code doesn't even try to reach LSP. instead it just invokes the tool.

**Comment by stamblerre** [comment]
The language server tells VSCode which features it supports, so that VSCode can determine which requests it should propagate to the language server. Since `gopls` does not yet support workspace symbols, VSCode does not try to reach it.

**Comment by ramya-rao-a** [comment]
https://github.com/microsoft/vscode-go/blob/0.11.4/src/goMain.ts#L280-L282 is the part where the extension realizes that `gopls` does not support workspace symbols feature and so registers its own provider which calls `go-symbols`

**Comment by ramya-rao-a** [comment]
Since the workspace symbol features is not part of the [capabilities](https://github.com/microsoft/vscode-go/blob/0.11.4/src/goMain.ts#L239) returned by `gopls`, VS Code does not bother sending workspace symbol requests to it.

Hope this clarifies things.

**Comment by inliquid** [comment]
In this case how can I, as a user, know that `gopls` is not working for this feature if I set 
```
"workspaceSymbols": true,
```
feature explicitly?

**Comment by ramya-rao-a** [comment]
I believe the best way to know that is check the [status for gopls](https://github.com/golang/go/wiki/gopls#status).

@stamblerre Is the above linked status section for gopls up to date?

**Comment by inliquid** [comment]
I believe that `vscode-go` has to at least issue a log message saying that it's working "by default", ignoring the explicit setting. Otherwise how do I know is it too slow `gopls` or anything else?

**Comment by ramya-rao-a** [comment]
Fair point.

@stamblerre Would you consider logging the capabilities from the language server to the output channel when it gets started just like you log other information like gopls version, go env etc?

**Comment by inliquid** [comment]
I think it should be extension since it's extension's decision to override setting and go for a default. Maybe even better if it was a popup with action buttons; disable language server option and use default tool or turn it off completely (if applicable).
