### ISSUE TITLE
Hovering over a builtin function shows nothing

### ISSUE THREAD

**Issue by zouyxdut** [microsoft/vscode-go#2725]
When hovering over a builtin function, it shows nothing.
vscode version:  1.37.1
vscode-go version: 0.11.4

**Comment by stamblerre** [comment]
Are you using the language server?

**Comment by zouyxdut** [comment]
No. It's disabled.
Hovering over non-builtin functions is OK.

**Comment by stamblerre** [comment]
What is the contents of your `settings.json` file? In particular, what is the setting for `go.docsTool`?

**Comment by zouyxdut** [comment]
The contents of `~/./config/Code/User/settings.json` are:
```
{
    "workbench.colorTheme": "Monokai Dimmed",
    "editor.tabSize": 8,
    "editor.fontFamily": "consolas,monospace",
    "editor.fontSize": 16,
    "terminal.integrated.fontFamily": "monospace",
    "window.zoomLevel": 0,
    "explorer.confirmDelete": false,
    "C_Cpp.updateChannel": "Insiders",
    "C_Cpp.dimInactiveRegions": false,
    "[cpp]": {
        "editor.defaultFormatter": "ms-vscode.cpptools"
    }
}
```
There is nothing about go, and I don't have any other `settings.json` file, the `go.docsTool` is as below:
![image](https://user-images.githubusercontent.com/11425914/64416939-b202a600-d0ca-11e9-8bf1-54b76593d3dd.png)

**Comment by ramya-rao-a** [comment]
@zouyxdut Can you share a sample code snippet where I can try this out?
