### ISSUE TITLE
Wrong warning

### ISSUE THREAD

**Issue by fedevilensky** [microsoft/vscode-go#2727]
Issue Type: <b>Bug</b>

I simply open a go file and there is a warning in in the first line, in the package declaration. And when i go and check what it says in the problems tab, it says "not found:[1, 1]"

Reproducible in different PCs and distros

Extension version: 0.11.4
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|7.58GB (1.63GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by stamblerre** [comment]
Can you share the contents of your `settings.json` file? Are you using the language server?

**Comment by fedevilensky** [comment]
I simply installed the go extension and started working. Been having this problem since day 1, and it is present on multiple PCs

Is this the settings.json you where looking for? Sorry, I am kinda new to vsc
> {
>     "debug.console.fontFamily": "Hack",
>     "editor.acceptSuggestionOnEnter": "smart",
>     "editor.fontFamily": "'Hack'",
>     "editor.fontSize": 10,
>     "editor.mouseWheelZoom": true,
>     "haskell.hlint.executablePath": "/home/fedevile/.cabal/bin/hlint",
>     "python.pythonPath": "/home/fedevile/.conda/envs/machine_learning",
>     "terminal.integrated.fontFamily": "'Hack'",
>     "window.titleBarStyle": "custom",
>     "window.zoomLevel": 0,
>     "workbench.iconTheme": "material-icon-theme",
> }

**Comment by stamblerre** [comment]
Yep, that's it, thank you for sharing. @ramya-rao-a: Have you ever seen such an error before?

**Comment by fedevilensky** [comment]
Here is a pic with the bug itself
https://imgur.com/a/mfEwUg2

**Comment by ramya-rao-a** [comment]
The first line gets the error if any of the go build, lint or vet processes find an error that is not associated with any particular line.

@fedevilensky, 
- Run the command `Go: Current GOPATH`. Does this show you your GOPATH? Is your current file under this path?
- Can you share the logs in the output channel? From the `View` menu, select `Output`. Then select "go" from the dropdown on the top right corner of the output panel.
- Can you share the folder structure of your project?
- Does running `go build` from the integrated terminal give you errors?
