### ISSUE TITLE
Cursor flies to top of file on save and text flashes

### ISSUE THREAD

**Issue by selfup** [microsoft/vscode-go#2728]
#### Steps to Reproduce

1. Save any go file
1. Cursor moves to top of file
1. Text flashes
1. Focus is still on section (so if I am 100 lines down I don't see the cursor fly up)

#### Video

Recorded a quick video showing this behavior on Windows 10.

1080p60fps available on YouTube (auto might not select that)

[Video on YouTube](https://youtu.be/8fe2XGBT-dY)

Raw link: https://youtu.be/8fe2XGBT-dY

#### Environment

Windows 10 (1903)

Go 1.13rc1 and the newly released Go 1.13

Go module based project

```json
"go.useLanguageServer": true
```

Tried all of the formatters. Same behavior.

***

Here is my project if you want to try it out yourself: https://github.com/selfup/moat

**Comment by selfup** [comment]
Works fine on Linux (Ubuntu 18.04 LTS)

Latest version of  VSCode

```
~ $ go version
go version go1.13rc1 linux/amd64
```

**Comment by stamblerre** [comment]
This is a known issue that will be fixed soon (https://github.com/golang/go/issues/31937). You can work around this by setting your line endings to be `\n` instead of `\r\n`. Add `"files.eol": "\n"` to your VSCode configuration.

**Comment by selfup** [comment]
@stamblerre thanks! I tried a ton of keywords and wasn't able to find that issue. I will try it out now 😄

**Comment by selfup** [comment]
Closing in favor of https://github.com/golang/go/issues/31937

**Comment by selfup** [comment]
Seems that this isn't a `x/tools/gopls` issue? Keeping open if this repo can fix it?

**Comment by stamblerre** [comment]
My understanding is that the VSCode language client team do not intend to fix this issue (see https://github.com/microsoft/vscode-languageserver-node/issues/493). My understanding is that the expectation is on the language server to produce the smallest diffs possible, which would avoid this issue.

**Comment by selfup** [comment]
Ok fair enough. I usually use editorconfig anyways, and of course the one project I don't use it with I see this behavior 😂 

Thanks!
