### ISSUE TITLE
Go removing proper import after adding it

### ISSUE THREAD

**Issue by sayajin101** [microsoft/vscode-go#2729]
func (n name) saveToFile(filename string) error {
       return ioutil.WriteFile(filename, []bytes(d.toString()), 0666)
    }

Steps to Reproduce:
1. add the above code to vs code (using the extension "Go")
2. vs code automatically adds the "bytes" import but on saving removes it again

**Comment by stamblerre** [comment]
The code should read `[]byte` not `[]bytes`. There is a package called `"bytes"` in the standard library, which is likely why the import got added, but you don't need it here.

**Comment by sayajin101** [comment]
thank you
