### ISSUE TITLE
Why Install Tools Not Use Go mod

### ISSUE THREAD

**Issue by arrebole** [microsoft/vscode-go#2731]
Steps to Reproduce:
1. open vscode && shift + p 
2. Go: Install/Update Tools && select all

Environment
Windows 10 (1903)
Go Version 1.13
GO111MODULE=on

It download to $GOPATH not pkg

**Comment by stamblerre** [comment]
This will be fixed in the next version of the extension (https://github.com/microsoft/vscode-go/pull/2700).

**Comment by ramya-rao-a** [comment]
The [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension does use modules when installing the tools
