### ISSUE TITLE
General comment after type, var tokens mis-colored

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode-go#2732]
It appears white instead of green:

<img width="383" alt="Screen Shot 2019-09-04 at 10 48 25 AM" src="https://user-images.githubusercontent.com/63830/64278416-8a141680-cf01-11e9-837b-886055af697c.png">

**Comment by ramya-rao-a** [comment]
@willfaught The colors are controlled by the grammar being used and the grammar is part of the main VS Code project. Therefore, please log this issue in the [VS Code repo](https://github.com/Microsoft/vscode)

In order for the folks at VS Code to repro this easily, please include a code snippet that they can paste into a Go file.
