### ISSUE TITLE
Colors of names, types of declarations inconsistent

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode-go#2733]
<img width="169" alt="Screen Shot 2019-09-04 at 11 07 52 AM" src="https://user-images.githubusercontent.com/63830/64279589-42db5500-cf04-11e9-8767-8ab044e3d7b1.png">

For var declarations, names are blue and types are white, whereas for const declarations, names are white and types are blue.

For type declarations without parentheses, the names are green and the types are white, whereas for type declarations with parentheses, both the names and types are white.

I'm guessing that for both var and const declarations, the names should be white and types blue?

I'm guessing that for type declarations, the names should be white and the types should be blue, except for built-in types like `int`, which should be green?

**Comment by ramya-rao-a** [comment]
@willfaught The colors are controlled by the grammar being used and the grammar is part of the main VS Code project. Therefore, please log this issue in the [VS Code repo](https://github.com/Microsoft/vscode)

In order for the folks at VS Code to repro this easily, please include a code snippet that they can paste into a Go file.
