### ISSUE TITLE
Go 1.13 number literal syntax highlighting 

### ISSUE THREAD

**Issue by DavidArchibald** [microsoft/vscode-go#2735]
With Go 1.13's release, the syntax highlighting of the [new number literals](https://golang.org/doc/go1.13?referrer=qmeta.net#language) should be recognized as such in the Go extension. Currently the new additions are simply white text, or in the case of a hexadecimal numbers with a mantissa and exponent, partially coloured.

This is easily reproduced by going into any Go file and putting in any of the newly added number literals such as these examples(there are many permutations):

```go
// Ok
0xabc
1000000
0x1.0p-1021 // Partially Ok

// Bad
0b1011
0B1011
0Xabc
0o660
0O660

// Imaginary Variants
0b1011i
0xabci
0o660i

// Underscores to Split Digits
1_000_000
```

This also reproduces almost the same way with the Github syntax highlighting(it also recognizes 0X while VSCode does not) so there may be an upstream issue to make instead or a sister PR to make. For posterity and for the relevance of the issue, here is a screen shot of what it looks like:

![incorrect number literal syntax highlighting](https://user-images.githubusercontent.com/19630496/64377677-c9b13000-cfdf-11e9-96c0-1acb5ae7dc63.png)

I don't expect that this would be too hard to change as the change would have a pretty small footprint and the release notes explain it pretty well.

**Comment by ramya-rao-a** [comment]
@DavidArchibald The colors are controlled by the grammar being used and the grammar is part of the main VS Code project. Therefore, please log this issue in the [VS Code repo](https://github.com/Microsoft/vscode)

Also, please note that we can't possibly have different grammars being used for different versions of Go. So any solution put in place here will be applied for any Go file regardless of the Go version being used.
