### ISSUE TITLE
Test Plan for September 2019 release

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#2738]
If you got a notification from this issue, then you are part of the next update to the Go extension which I plan to release early next week.
Thanks and Welcome!

Here, I am listing some of the features and the bug fixes that will go in the next update and for which I need some help in testing. Since I dont work with Go in my day job, I always feel that someone who does Go more than me can help in testing tremendously.

And when I say "test", you can do a minimum pass of just installing the update and then do nothing special other than going about using VS Code like you do everyday. Or you can test the feature you requested/implemented or the bug you logged/fixed. Or you can test all of the below. Every bit helps.

Drop in a comment in this issue after 2 or 3 days of [installing the update](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) i.e the beta version with your findings.

- Warn if any edits to a Go file is saved when a debug session is in progress @haryps 
- Use the `latest` tag to install `gopls` instead of master branch @stamblerre, @banks
- Prompt to update `gopls` if you have an older version @stamblerre
- Tools are now installed in module mode @stamblerre
- `gopls` can now be used when you are using Go from the tip @stamblerre @Goodwine
- Allow alternate tools to be used in place of `gopls` @anurbol
- Show status bar for "Modules" when in module mode @mattetti 
- Debugging improvements @quoctruong, @BaronChen
     - Fix the bug where setting breakpoint fails if the remote program is started through dlv with --continue switch. Bug #2690
     - Fix the bug where disconnecting (after attaching to) the remote program terminates it. Bug #2592
    -  Fix the bug where setting breakpoint will fail if a breakpoint already exists (if dlv is started through multi client and another client sets the breakpoint).

**Comment by stamblerre** [comment]
Regarding the automatic updates for gopls, I realized that I didn't add correct handling for people who use `gopls` at master by running `go get golang.org/x/tools/gopls@master`. I will send a PR for that later today.

**Comment by quoctruong** [comment]
There is a bug on clearing breakpoints after detaching from the remote process. I'll send out a PR later today for that.

**Comment by mattetti** [comment]
> Show status bar for "Modules" when in module mode

Confirmed to work as expected (status bar only shows up when go modules is on). But there is an important caveat: the status doesn't change unless extension/vs code is restarted. In other words, a user might change their go module settings in they env variables, that change won't be reflected in the editor. I can't really think of a good solution so I think we are good to go.

**Comment by stamblerre** [comment]
> In other words, a user might change their go module settings in they env variables, that change won't be reflected in the editor. I can't really think of a good solution so I think we are good to go.

@mattetti: A partial solution might be to watch changes to the `go.toolsEnvVars` config setting (see an example [here](https://github.com/microsoft/vscode-go/blob/7fab4f3ac6f8b3b2711d137886f26d5412c99aae/src/goLanguageServer.ts#L65)).

**Comment by mattetti** [comment]
@stamblerre I think that's a good idea, it can't hurt to check on VSCode custom env variables.

**Comment by ramya-rao-a** [comment]
0.11.5 version has now been released, thanks everyone!
Link to changelog: https://github.com/microsoft/vscode-go/blob/0.11.5/CHANGELOG.md#0115---19th-september-2019
