### ISSUE TITLE
Completion candidates out of order with new gopls

### ISSUE THREAD

**Issue by muirrn** [microsoft/vscode-go#2739]
gopls recently added server side fuzzy completion matching (only on master, not released yet). The completion results are now marked as IsIncomplete=true so the client re-requests completions after every change.

Sometimes VSCode displays completion candidates in a different order than expected.

VSCode
Note that "a" is incorrectly ranked before "a.i":
![VSCode](https://user-images.githubusercontent.com/11356572/64573348-e02cf380-d31f-11e9-9797-04310f26e2e5.gif)

Here is a sample "complete" response for completing `foo(a<>)` (note that "a.i" is ranked first):
```
[Trace - 16:17:44.087 PM] Received response 'textDocument/completion - (110)' in 0ms.
Result: {"isIncomplete":true,"items":[{"label":"a.i","kind":5,"detail":"int","preselect":true,"sortText":"00000","filterText":"a.i","insertTextForm
at":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"a.i"}},{"label":"a","kind":6,"detail":"struc
t{...}","sortText":"00001","filterText":"a","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":
6}},"newText":"a"}},{"label":"append","kind":3,"detail":"func(slice []Type, elems ...Type) []Type","sortText":"00002","filterText":"append","insert
TextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"append(${1:slice []Type}, ${2:elems
...Type})"},"command":{"title":"","command":"editor.action.triggerParameterHints"}},{"label":"iota","kind":21,"sortText":"00003","filterText":"iota
","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"iota"}},{"label":"main","ki
nd":3,"detail":"func()","sortText":"00004","filterText":"main","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"l
ine":7,"character":6}},"newText":"main()"},"command":{"title":"","command":"editor.action.triggerParameterHints"}},{"label":"cap","kind":3,"detail"
:"func(v Type) int","sortText":"00005","filterText":"cap","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":
7,"character":6}},"newText":"cap(${1:v Type})"},"command":{"title":"","command":"editor.action.triggerParameterHints"}},{"label":"false","kind":21,
"sortText":"00006","filterText":"false","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"false"}},{"label":"float32","kind":25,"sortText":"00007","filterText":"float32","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"float32"}},{"label":"float64","kind":25,"sortText":"00008","filterText":"float64","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"float64"}},{"label":"imag","kind":3,"detail":"func(c complex128) float64","sortText":"00009","filterText":"imag","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"imag(${1:c complex128})"},"command":{"title":"","command":"editor.action.triggerParameterHints"}},{"label":"make","kind":3,"detail":"func(t Type, size ...int) Type","sortText":"00010","filterText":"make","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"make(${1:t Type}, ${2:size ...int})"},"command":{"title":"","command":"editor.action.triggerParameterHints"}},{"label":"panic","kind":3,"detail":"func(v interface{})","sortText":"00011","filterText":"panic","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"panic(${1:v interface{\\}})"},"command":{"title":"","command":"editor.action.triggerParameterHints"}},{"label":"real","kind":3,"detail":"func(c complex128) float64","sortText":"00012","filterText":"real","insertTextFormat":2,"textEdit":{"range":{"start":{"line":7,"character":5},"end":{"line":7,"character":6}},"newText":"real(${1:c complex128})"},"command":{"title":"","command":"editor.action.triggerParameterHints"}}]}
```

@stamblerre did you have anything to add?

**Comment by muirrn** [comment]
@ramya-rao-a Thanks. I wasn't able to get the explain popup to show up, but it seems like VSCode is doing scoring/ranking on top of what the LSP server does. Is it possible to disable the rescoring/reranking and just have VSCode use the completions as-is?

**Comment by ramya-rao-a** [comment]
Am not sure about that @muirrn 
@jrieken Can you help?

**Comment by jrieken** [comment]
> Is it possible to disable the rescoring/reranking and just have VSCode use the completions as-is?

No, as soon as the user starts typing (e.g `a` in this case) VS Code's ranking kicks in (before that we use the provider ranking) We do that to provide a consistent feeling across all languages. In this specific case `a` wins over `a.i` because it's a perfect (full) match. This is the issue to disable sorting on our side: https://github.com/microsoft/vscode/issues/64367

**Comment by ramya-rao-a** [comment]
@stamblerre, @muirrn Is there something that needs to be done here or anything else we can help with?

**Comment by muirrn** [comment]
In general we want a way to use the gopls candidates verbatim without VSCode reordering, excluding or adding anything. I think microsoft/vscode#64367 would help, but there are other cases where VSCode completely omits candidates. For example:

```go
var b *bytes.Buffer
b = b<>
```

The server sends a candidate of `&bytes.Buffer{}`, but VSCode does not display it. If you type `bytes.B` and trigger the `bytes.Buffer{}` completion, then the above example will mysteriously start showing `&bytes.Buffer{}` if you try it again, but sorted at the bottom.

Do you have any idea in general why candidates in the response wouldn't show up in VSCode?

**Comment by jrieken** [comment]
VSCode compares the text that's to be overwritten with the completion, e.g `b` with `&b` which is considered a weak match and hence filtered. To tweak this you can use `filterText`

**Comment by muirrn** [comment]
> VSCode compares the text that's to be overwritten with the completion

That behavior would be disableable as part of microsoft/vscode#64367, right? If so then I'll close this issue out.

**Comment by jrieken** [comment]
Yeah, likely. The story around disabling fuzzy-filtering hasn't been finalised or thought of much and given that the request isn't very popular it also won't happen too soon. 

Generally, I would recommend to play with how vs code works by default. Reason being is that users should not to need to "relearn" how IntelliSense works in a certain language. I understand that authors of a language service are naturally bias towards "their" ordering but users often haven different plans. So for us the responsibilities are divided like this: Users ask for IntelliSense and extension can return them in their order. Users then insert whatever suggestion they want. Insertion can happen by selecting via mouse gestures or (more commonly) via the keyboard gestures - often by "typing to select" first. This "typing to select" should generally not* be interpreted as signals to recompute completions but it's the user's way to select and insert items. 

*recomputing on type (`CompletionList#isIncomplete`) should only be used when the current more typing would yield in more completions, e.g. a database, like npmjs, is queried and the prefix `a` yields no finite set in a reasonable time.

**Comment by muirrn** [comment]
Thanks for outlining your standpoint. It makes sense that VSCode wants to provide a consistent completion experience across languages.

> authors of a language service are naturally bias towards "their" ordering but users often haven different plans.

What is the "user's plan" in this scenario? When would the user not want the best completion candidate matching their input to be listed first?

I want to reemphasize that "our" ordering is not arbitrary. It is based on type information and other heuristics not available to VSCode. In my original example above, `a` is not a good candidate because it is the wrong type. Being able to directly insert `a.i` saves the user time. The time savings is even more obvious in a candidate like `a.b.c().d()`.

Anyway, it sounds like the disable-fuzzy-filtering feature will cover all the bases, so I'll close this issue. I think you are right that for now we can fool around with filterText to get things ordered the way we want, i.e. give our best (all?) candidates a perfectly matching filterText so they aren't downranked. Thanks for your help!

**Comment by jrieken** [comment]
> When would the user not want the best completion candidate matching their input to be listed first?

➡️ https://github.com/microsoft/vscode/issues/84587 in cases like this... 

> I want to reemphasize that "our" ordering is not arbitrary. It is based on type information and other heuristics not available to VSCode.

I understand that you want to advertise the "perfect" sorting but be aware that you don't see the whole picture and this causes headaches for your users.

**Comment by tj** [comment]
Thanks for the help @jrieken — yeah I can say personally I would always want my snippets to take precedence, _especially_ when it exactly matches my snippet prefix, many of the matches I'm provided by vscode-go are not close matches at all (see screenshots in #84587)

**Comment by muirdm** [comment]
I opened https://github.com/golang/go/issues/35782 upstream to track this issue.
