### ISSUE TITLE
compilation / tools output

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#274]
It would be very useful if the output of the compilation / various tools run when saving files would be available through the output menu. Errors might be happening in different files than the one being open and the developer doesn't get any feedback.
Ideally stderr would go to the output pane.

**Comment by lukehoban** [comment]
I think this will have to be combined with running an explicit build command - something separate from just saving.  Either through a `Go: Build` command or a `Build` task.  There's some discussion on those at https://github.com/Microsoft/vscode-go/issues/21 and https://github.com/Microsoft/vscode-go/pull/134.  

Would that address what you are looking for?

**Comment by mattetti** [comment]
Luke, thanks for looking into this issue. Unfortunately I don't really want to run a command manually, I want to get feedback as tools automatically run in the background. For instance, when saving, go build, go vet and probably other tools are running. When possible, some output is shown within the IDE, but that's not always the case and the information is lost. I wish all stdout/stderr would be redirected to an output I could look at anytime.
Does that make sense?

**Comment by lukehoban** [comment]
Got it - that makes sense.

I took a look at this, and it appears we can fairly easily send the results from `check` to the output window as well as producing he diagnostics for VS Code.  We can also do this without forcing the Output windows to open up, so it shouldn't get in the way for those who aren't interested in seeing this.

**Comment by mattetti** [comment]
This is awesome, thank you so much. I think that now @goinggo won't have any excuses to not use VScode, his main excuse was the lack of `go build` output ;)
