### ISSUE TITLE
Extension says gopls is out of date when using @master version

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode-go#2742]
Having this annoying message:
![изображение](https://user-images.githubusercontent.com/6797881/64613165-2ba5d700-d3de-11e9-8a88-d4f023aa250e.png)

```
>gopls version
golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@(devel)
```

**Comment by stamblerre** [comment]
Are you on Windows?

**Comment by inliquid** [comment]
Yep, it's Windows.

**Comment by stamblerre** [comment]
Thanks for confirming. https://github.com/microsoft/vscode-go/pull/2743 will fix it.

**Comment by ramya-rao-a** [comment]
The [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)  (0.11.5-beta.4) should have the fix for this.
Thanks for reporting @inliquid!

**Comment by clar** [comment]
I'm on mac, and see the same issue .

> ➜  src gopls version         
version v0.1.6, built in $GOPATH mode

**Comment by stamblerre** [comment]
What version of Go are you using? We recommend building `gopls` in module mode, and you can get a stable version by running `go get golang.org/x/tools/gopls@latest`. You can install master by running `go install` inside of the `golang.org/x/tools/gopls` directory, and that shouldn't show any warnings.

**Comment by stamblerre** [comment]
@benthal: What is the output of `gopls version`?

**Comment by nodirg** [comment]
mine says `version v0.1.6, built in $GOPATH mode`. I am using `go.toolsGopath` setting where gopls code is fetched. 

what version should it be?

**Comment by nodirg** [comment]
I've just compiled https://github.com/golang/tools/tree/8abd42400456fce151cb3933ab7a177008cdad06/gopls with `go build`. Its `./gopls version` returns `version v0.1.6, built in $GOPATH mode`. This seems the latest version

**Comment by stamblerre** [comment]
`gopls` should be installed in module mode. If you are hoping to build at master (which is prone to breakages, etc.), you can install it by `cd`ing into the `gopls` directory and running `GO111MODULE=on go install`, then VSCode will stop complaining. However, our recommendation is that you installed a released version, so I would suggest running `GO111MODULE=on go get golang.org/x/tools/gopls@latest`.

**Comment by nodirg** [comment]
thanks. this solved my problem

**Comment by benthal** [comment]
@stamblerre  thanks for your help.
my problem has solved by `GO111MODULE=on go install`. 
I pulled `github.com/golang/tools` before this operation this day.
`goals version` has changed from 0.1.6 to 0.1.7
