### ISSUE TITLE
a lot of unexpected config warning

### ISSUE THREAD

**Issue by 678uhb** [microsoft/vscode-go#2749]
![image](https://user-images.githubusercontent.com/6631439/64837161-ab6eb400-d61f-11e9-9bb2-7db0f9d066eb.png)

**Comment by 678uhb** [comment]
![image](https://user-images.githubusercontent.com/6631439/64882216-43f04d00-d68f-11e9-812e-76073507de60.png)

**Comment by 678uhb** [comment]
go 1.13

**Comment by lerixhe** [comment]
same problem

**Comment by 0xdeafcafe** [comment]
Also having this problem, but on `go1.12.5`

**Comment by lerixhe** [comment]
> same problem
I closed the GOPATH dir in the workspace,and fixed it. But when I open it again, the problem reappears

**Comment by 678uhb** [comment]
// "go.useLanguageServer": true,
  // "go.languageServerFlags": [
  //   "-rpc.trace", // for more detailed debug logging
  //   "serve",
  //   "--debug=localhost:6060", // to investigate memory usage, see profiles 
  // ],
  // "[go]": {
  //     "editor.snippetSuggestions": "none",
  //     "editor.formatOnSave": true,
  //     "editor.codeActionsOnSave": {
  //         "source.organizeImports": true
  //     }
  // },
  // "gopls": {
  //     "usePlaceholders": true, // add parameter placeholders when completing a function
  //     "wantCompletionDocumentation": true // for documentation in completion items
  // },

i don't know which one fix that
guess  leave  the go.useLanguageServer unset  works

**Comment by stamblerre** [comment]
Can I ask what the name of the directory you opened was? `gopls` requests per-folder configuration from VSCode, and I imagine what happened is that if your directory is called `go`, then the extension returned every `go` configuration.

**Comment by 678uhb** [comment]
yes , it's called go

**Comment by 678uhb** [comment]
change the directory name works

**Comment by stamblerre** [comment]
Ah ok, thanks for confirming. This is a `gopls` bug, so I'll work on fixing it and releasing an updated version tomorrow. I will update here when that has been done.

**Comment by stamblerre** [comment]
Just released a new version to fix this. You can get it via `go get golang.org/x/tools/gopls@v0.1.7`.
