### ISSUE TITLE
Feature Request: Supporting additional environment variable configuration when executing `go get`

### ISSUE THREAD

**Issue by 910JQK** [microsoft/vscode-go#2750]
Sorry for my bad English. There is an annoying problem. If some analysis tools are missing, `vscode-go` can install them automatically using `go get`, which is a convenient feature. But due to the fact that `golang.org` is blocked by the Great Firewall of China, `go get` could require a HTTP proxy to work in China. The HTTP proxy used by `go get` can be set by the environment variables `http_proxy` and `https_proxy`. Could you add a configuration option to `vscode-go` for those environment variables?
The problem is not critical because some workarounds are available, such as using a local mirror of `golang.org`, but I will be very grateful if the feature described above can be implemented.

**Comment by kidlj** [comment]
Just set "http.proxy": "http://$SERVER:$PORT", this should work.

**Comment by 910JQK** [comment]
> 
> 
> Just set "http.proxy": "http://$SERVER:$PORT", this should work.

Thanks a lot. I didn't know it.
