### ISSUE TITLE
Analysis Tools Missing and Go Language Server

### ISSUE THREAD

**Issue by riobard** [microsoft/vscode-go#2753]
The extension warns about "Analysis Tools Missing" in the status bar at the bottom even if it's configured to use Go Language Server. According to the wiki those tools are not necessary. Is it better to suppress the warning if gopls is used?

**Comment by ramya-rao-a** [comment]
Fair point, but there are still some tools that you would need even if you were using the language server. I have gone through these and we have prompts showing up to install them when the feature they power are used and the tool is not found. So we are good there.

Except for the linting feature where we don't prompt if the linter tool is missing. If we add that, then yes, we can remove the "Analysis Tools Missing" status bar item when language server is enabled.

PR is most welcome for this.
Code Pointers:
- [Set up local dev environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- `goLint.ts` is the file that needs to be updated to call the `promptForMissingTool` method when the linter tool is not available which can be determined by making a call to `getBinPath`
- `offerToInstallTools` method in `goInstallTools.ts` file is the one that enables the "Analysis Tools Missing" status bar. It is here that you can choose to not enable it when language server is in use.
- `dlv` for debugging
- the linting tool of choice



So, we can't

**Comment by ramya-rao-a** [comment]
cc @stamblerre

**Comment by zmb3** [comment]
go-outline should not be necessary when using gopls, right?

**Comment by stamblerre** [comment]
> * `go-outline`. Used to get functions in current file for various test features and codelens

Based on this comment, it sounds like the extension is using `go-outline` directly for this behavior. Though I agree that it could directly ask the DocumentSymbol provider rather than relying on a specific tool.

**Comment by ramya-rao-a** [comment]
I am not aware of any way the extension can ask the language server for symbols, so we would continue to use `go-outline` for the test features & codelens

**Comment by zmb3** [comment]
The language server will respond to the [document symbols request](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_documentSymbol), which includes all functions and methods in the document along with their positions.

**Comment by iatsiuk** [comment]
Is there any way to suppress "Analysis Tools Missing" warning right now?

**Comment by stamblerre** [comment]
Not that I am aware of, but I know that @hyangah is working on a list of tools that are not required when `gopls` is installed.

**Comment by stamblerre** [comment]
I just filed an issue upstream to track this, so I'm going to close this in favor of https://github.com/golang/vscode-go/issues/51.
