### ISSUE TITLE
support for GOPACKAGESDRIVER env variable?

### ISSUE THREAD

**Issue by jmhodges** [microsoft/vscode-go#2755]
`gopls`, by way of `golang.org/x/tools/go/packages`, supports using the environment variable `GOPACKAGESDRIVER` to allow for build systems other than the `go` tooling (such as `bazel`) to provide the look ups for `gopls`.

However, there doesn't seem to be a way to set that env var as a workspace setting. I'm trying to help out with bazel's attempt at supporting `gopls` (documented at https://github.com/bazelbuild/rules_go/issues/512 and https://github.com/bazelbuild/rules_go/wiki/Editor-and-tool-integration) which relies on this.

(While there's no godoc.org documentation of it, `GOPACKAGESDRIVER` is described in the `go/packages` code base in [external.go](https://github.com/golang/tools/blob/2dc213d980bc4ad623aefc805006b0864edeaac4/go/packages/external.go#L24))

Is there some way to set the `GOPACKAGESDRIVER` environment variable in my settings.json?

**Comment by jmhodges** [comment]
(I also opened https://github.com/golang/go/issues/34341 to get that env var documented in a more public way)

**Comment by jmhodges** [comment]
Oh, I think I was reading outdated docs on the wiki? Is using `go.toolsEnvVars` the way to do this?

**Comment by jmhodges** [comment]
Or maybe there's an undocumented `gopls.env` that I've seen mentioned in the vscode channel in the gophers slack?

**Comment by stamblerre** [comment]
You can set the `GOPACKAGESDRIVER` used by `gopls` in 2 different ways, either:

```json5
"go.toolsEnvVars": {
    "GOPACKAGESDRIVER": "mygopackagesdriver"
} 
```

or

```json5
"gopls": {
    "env": {
        "GOPACKAGESDRIVER": "mygopackagesdriver"
    }
} 
```

The difference is that if you set `"go.toolsEnvVars"`, the same driver will be used by any other tools that use `go/packages` that are used by VSCode. The configuration in the `"gopls"` settings just tells `gopls` to use that driver. It's also needed for editors that do not have a setting akin to `"go.toolsEnvVars"`.

**Comment by ramya-rao-a** [comment]
I agree with @stamblerre
