### ISSUE TITLE
Green/Blue Screen of Death upon opening specific projects in VSCode

### ISSUE THREAD

**Issue by Shamdan17** [microsoft/vscode-go#2756]
Hello everyone,

I have been having an issue with VSCode recently. Every time I open the project I am working on, I get a green screen of death (I am running a Windows Insider Build). This happens 100% of the time, with no exceptions, and it is always within a few seconds of opening a .go file in the project. 

I would like to provide more info, but I can not provide the specific code as it is confidential. However, I made the following observations:
1. It is not universal, a coworker who is also running Windows 10 and working on the same project does not have the same issue
2. The issue seems to be related to the contents of the folder for some reason. When I open the main project folder or subfolder within the main directory I face the same issue.
3. Relocating the folder and reopening it in VSCode does not solve the issue.
**BUT** 
4. Relocating only a subfolder somewhere else and opening it in VSCode will work fine. 

I have not faced the same issue with other go projects other than this one. I am ready to provide whatever information can help diagnose the issue as long as it is within my limits. The issue is 100% with the VSCode Go extension. Uninstalling the extension allows me to work with the folder just fine and without any issues whatsoever. Installing it and opening the same project results in an GSOD again instantly.

Moreover, regarding the GSOD, the Stop Code that is shown is: SYSTEM_SERVICE_EXCEPTION and what failed shows: cldflt.sys

In case any more information is needed regarding my OS/Setup/anything please inform me and I will be happy to provide the information. This is the information that comes to mind:

How it is reproduced:
1. Have the extension enabled
2. Open any .go file in the project

VSCODE:
- Version: 1.38.1 (user setup)
- Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
- Date: 2019-09-11T13:35:15.005Z
- Electron: 4.2.10
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.17134

GO Extension
- Name: Go
- Id: ms-vscode.go
- Version: 0.11.4

GO
- go version go1.12.7 windows/amd64

**Comment by Shamdan17** [comment]
While experimenting with different previous versions of VSCode Go, I have boiled down the update that introduced the issue to version 0.7.0. Working with 0.6.93 gives be no issues so far.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Shamdan17 and for narrowing down to which release started causing the problem.

Please share any Go related settings you might have added/edited. You can get these after running the command `Preferences: Open Settings (JSON)`.

As per the [Changelog for 0.7.0](https://github.com/microsoft/vscode-go/blob/master/CHANGELOG.md#070---6th-november-2018), 2 things got introduced that might be related to your issue here
- Docs when using auto-completion
- Language server support in Windows

By seeing the settings you have added/edited, we can rule out one of the above.
If you are not using language server, then I'd like you to add the below in your settings and try again. This disables the docs feature in autocompeltion
```
{
"go.gocodeFlags": [
    "-builtin",
    "-ignore-case",
    "-unimported-packages",
    "-exclude-docs"
  ]
}

**Comment by Shamdan17** [comment]
Thank you for the quick response.

I ran the command, and I got the following Go related settings:
```    
"go.formatTool": "goimports",
"go.useLanguageServer": true,
```

I have tried your suggestion, and now I am facing no issues so far with the latest version of the extension. I think this means that it indeed is the docs feature behind the issue. 

What can I do to help you further diagnose the issue?

**Comment by ramya-rao-a** [comment]
The `go.gocodeFlags` control the way the extension provides the completion feature. But if you are using the language server, then the extension doesnt provide any completion feature of its own, instead it relies on the language server to provide this feature.
So, changing the `go.gocodeFlags` setting should not have made any difference when you are using the language server.

Can you share the version of the language server that you are using? Running `gopls version` on your terminal should give you the value.

cc @stamblerre
