### ISSUE TITLE
Debugging with race detection on Windows requires gcc

### ISSUE THREAD

**Issue by omcnoe** [microsoft/vscode-go#2757]
Setting `"buildFlags": "-race"` in a debug config in launch.json causes vscode debugging to fail if it can't find gcc on the PATH. Yet calling `go run -race main.go` outside of vscode works fine without gcc. Is this a limitation of building with debugging?

go version go1.13 windows/amd64
extension version 0.11.4

**Comment by ramya-rao-a** [comment]
Thanks for reporting @omcnoe 

Can you try running [dlv](https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_debug.md) from the terminal with race flag and see if it behaves any differently?
If it does, then we can look into what VS Code is doing differently when calling dlv

**Comment by omcnoe** [comment]
Unfortunately the behavior is the same, seems like a limitation of delve.

**Comment by ramya-rao-a** [comment]
Thanks @omcnoe 
In that case, I would suggest to first log the issue against delve to get a better understanding of what is happening.

Closing this issue for now. If you find something that you believe should be done on the extension's side, please do drop in a comment here
