### ISSUE TITLE
Go Install/Update Tools gives me FAILED and 'permission denied'

### ISSUE THREAD

**Issue by bygui86** [microsoft/vscode-go#2758]
I read this link `https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension` but I found no answers.

Steps to Reproduce:
1. Open VSCode
2. Open Command palette
3. Run `Go Install/Update Tools`
4. Select go tools to be installed

Trying to install `gopls` VSCode shows following output:
```
Installing 1 tool at /golang/bin
  gopls

Installing golang.org/x/tools/cmd/gopls FAILED

1 tools failed to install.

gopls:
Error: Command failed: /usr/local/opt/go/libexec/bin/go get -u -v golang.org/x/tools/cmd/gopls
get "golang.org/x/tools/cmd/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/cmd/gopls?go-get=1
get "golang.org/x/tools/cmd/gopls": verifying non-authoritative meta tag
golang.org/x/tools (download)
package golang.org/x/tools/cmd/gopls: mkdir /golang: permission denied
get "golang.org/x/tools/cmd/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/cmd/gopls?go-get=1
get "golang.org/x/tools/cmd/gopls": verifying non-authoritative meta tag
golang.org/x/tools (download)
package golang.org/x/tools/cmd/gopls: mkdir /golang: permission denied
```
All packages have the same result.

If I run the same command normally in a terminal, it works perfectly.

Any info about this?
What I'm doing wrong?

**Comment by bygui86** [comment]
Here my `go env`:
```
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/Users/***/projects/golang/bin"
GOCACHE="/Users/***/Library/Caches/go-build"
GOENV="/Users/***/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/***/projects/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t6/q9vcvg3j11x_q890t43mgc700000gn/T/go-build565157615=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by ramya-rao-a** [comment]
> If I run the same command normally in a terminal, it works perfectly.

Is this when you tried in an external terminal or the integrated terminal in VS Code?

If it was using the external terminal, then can you please try the below?
- Close all instances of VS Code
- From the external terminal, run `code` and try again. This ensures that all the env vars from your terminal gets inherited by VS Code

**Comment by bygui86** [comment]
Giving a try right now. Keeping you posted.

**Comment by bygui86** [comment]
> Is this when you tried in an external terminal or the integrated terminal in VS Code?
I tried from an external terminal and from integrated terminal as well.
From external it works, from integrated it doesn't.

> If it was using the external terminal, then can you please try the below?
I tried and it works! But this means that if I make some changes in my shell profile, do I need to start at least once VSCode from external terminal?

This behaviour looks a bit weird to me...

**Comment by ramya-rao-a** [comment]
The problem boils down to VS Code not able to read the changes in your shell profile. This is an extension agnostic problem. I would suggest to look up existing issues in the VS Code repo that might have already covered this as there is nothing we can do from the extension's perspective here.

Closing this issue.

Happy Coding!
