### ISSUE TITLE
Go: Build Workspace never ends

### ISSUE THREAD

**Issue by padurean** [microsoft/vscode-go#2765]
Issue Type: <b>Bug</b>

Go: Build Workspace never ends with latest version.

Extension version: 0.11.5
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 11, 13|
|Memory (System)|16.00GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ramya-rao-a** [comment]
Thanks for reporting @padurean!

I have the fix in the master branch and you can use the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of the extension until I ship the fix later in the week

**Comment by padurean** [comment]
@ramya-rao-a Thank you! I can confirm the bug is fixed in the latest beta version.

**Comment by ramya-rao-a** [comment]
The latest update (0.11.7) has the fix for this issue.
Thanks for reporting and Happy Coding!
