### ISSUE TITLE
Command "Test All Packages In Workspace" not working

### ISSUE THREAD

**Issue by soyangel** [microsoft/vscode-go#2766]
Since extension updated to 0.11.5 command "Test All Packages In Workspace" seems to not execute tests, with no visible output on logs and no visual indication that tests are running.

The link to run package's tests & links on test functions work ok.

Vscode:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.68-1-lts
```

Steps to Reproduce:

1. Create a project with a main_test.go file like this:
```go
package main

import "testing"

func TestSomething(t *testing.T) {
	t.Error("error on main test")
}
```
2. Run "Test All Packages In Workspace"

**Comment by ramya-rao-a** [comment]
Thanks for reporting @soyangel 

I have the fix in the master branch and you can use the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of the extension until I ship the fix later in the week

**Comment by ramya-rao-a** [comment]
The latest update (0.11.7) has the fix for this issue.
Thanks for reporting and Happy Coding!
