### ISSUE TITLE
Please document all options available for go.languageServerExperimentalFeatures

### ISSUE THREAD

**Issue by darren** [microsoft/vscode-go#2772]
Neither  the document in Readme of vscode-go [settings  to control the use of the go-language-server ](https://github.com/microsoft/vscode-go#settings-to-control-the-use-of-the-go-language-server) nor [gopls's wiki](https://github.com/golang/go/wiki/gopls) lists  which options go.languageServerExperimentalFeatures provides.

I googled several times and still can not find the full list, forgive me if I have missed something.

It seems that not all ExperimentalFeatures enabled by default, so to know all the options available is essential for the use of gopls.

I am currently using this

```json
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true
    }
```

**Comment by ramya-rao-a** [comment]
I have just updated the Readme of vscode-go [settings  to control the use of the go-language-server ](https://github.com/microsoft/vscode-go#settings-to-control-the-use-of-the-go-language-server) with the note on all features that you control with this setting and their default values.

Happy Coding!
