### ISSUE TITLE
Prompts to update gopls as and when a new stable version is out

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#2776]
In 0.11.5, we introduced a feature where the extension prompts users to update their `gopls` if it was found to be out of date when compared to the latest stable version.

This was done by making calls to https://proxy.golang.org

This approach has a couple of concerns
- The call would fail for users behind corporate or private proxies or in China. See #2768
- Users might have their own GOPROXY set up in which case that is what should be respected
- Some users might not want such outgoing calls and so would want a way to turn it off.

In 0.11.6, we are no longer making such outgoing calls and have instead hard-coded the currently known latest version of `gopls` in the check that results in the prompt to update `gopls`

This issue is to discuss next steps that will allow us to prompt users to update gopls as and when a new stable version is out while keeping the above concerns in mind

cc @stamblerre

**Comment by ramya-rao-a** [comment]
cc @stamblerre

**Comment by ramya-rao-a** [comment]
Current proposals:
- Add a setting so that user can opt out of such outgoing calls. See https://github.com/microsoft/vscode-go/pull/2773
- if user has configured GOPROXY, use that. See https://github.com/microsoft/vscode-go/pull/2774

**Comment by stamblerre** [comment]
I think the combination of the two current proposals will be sufficient to make sure that the user has enough control over the auto-updating behavior. The `go` command will make requests to `GOPROXY` when VSCode runs `go get` to install packages, so this will behave in a similar fashion. The setting adds another level of protection, so if a user doesn't want the auto-updating behavior, it can be turned off. This sounds pretty solid to me. What do you think, @ramya-rao-a?

**Comment by ramya-rao-a** [comment]
The latest beta version of the extension has this feature where the GOPROXY is used to determine whether a newer update is available. This can be disabled using the new setting `go.useGoProxyToCheckForToolUpdates`
