### ISSUE TITLE
Golang HTML Templates: typing "{{" produces "{{}}}", not "{{}}"

### ISSUE THREAD

**Issue by adiabatic** [microsoft/vscode-go#2777]
Alternate title for better searchability: unbalanced braces generated in `html/template` templates.

I forget when I started noticing this. I think it's been a month or two now. 

Steps to Reproduce:

1. Open a terminal to ~.
2. Run `touch foo.gohtml`.
3. Run `code foo.gohtml`. You are now in Visual Studio Code, editing foo.gohtml.
4. Type "{". Notice how "{}" is in the buffer.
5. Type "{" again. Notice how "{{}}}" is in the buffer now, with an extra closing brace ("}").

My ~/Library/Application Support/Code/User/settings.json:

```javascript
{
    "[yaml]": {
        "editor.tabSize": 2
    },
    "emmet.includeLanguages": {
        "gohtml": "html"
    },

    "emmet.syntaxProfiles": {
        "html": {
            "attr_quotes": "single",
            "tag_nl": "decide",
        },
    },

    "todo.symbols.box": "-",
    "todo.symbols.cancelled": "-",
    "todo.symbols.done": "-",
    "todo.timekeeping.finished.format": "YYYY-MM-DD HH:mm",

    "html.format.wrapAttributes": "aligned-multiple",
    "javascript.preferences.quoteStyle": "single",
    "typescript.preferences.quoteStyle": "single",
    "workbench.colorTheme": "Monokai Pro (Filter Machine)",
    "workbench.iconTheme": "Monokai Pro (Filter Machine) Icons",
    "workbench.editor.highlightModifiedTabs": true,
    "editor.minimap.enabled": false,
    "editor.wordWrap": "on",
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "window.zoomLevel": 1,
    "python.pythonPath": "/usr/local/bin/python",
    "html.format.indentInnerHtml": true,
    "search.exclude": {
        "**/.src/*": true
    },

    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
            "diagnostics": true // for diagnostics as you type
    },
    "[go]": {
        "editor.snippetSuggestions": "inline",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "workbench.sideBar.location": "left",
    "editor.cursorSurroundingLines": 6,
}
```

This happens on both my iMac and MacBook. I'm  currently running the latest version of VSCode with Go 1.13, although this happened on 1.12 as well. I've run `Go: Install/Update Tools` on both installations and reloaded the window afterwards. That hasn't helped at all. Any idea what could be going wrong?

**Comment by ramya-rao-a** [comment]
> Type "{". Notice how "{}" is in the buffer.

Can you elaborate on what you mean by "in the buffer"?

This extension does not support gohtml files. You might have some other extension installed that might be causing this. If you see this after disabling all extensions you have, then please log this issue in the [VS Code](https://github.com/Microsoft/vscode) repo.

**Comment by adiabatic** [comment]
> > Type "{". Notice how "{}" is in the buffer.
> 
> Can you elaborate on what you mean by "in the buffer"?

In the window. Here's what it looks like with the insertion caret visible:

<img width="503" alt="{} visible in an otherwise-empty .gohtml file" src="https://user-images.githubusercontent.com/101246/65395788-60a61800-dd54-11e9-9dde-5873de2046ff.png">

> This extension does not support gohtml files. You might have some other extension installed that might be causing this. 

I disabled https://github.com/casualjim/vscode-gotemplate and the offending behavior stopped. I'll ping its author. Thanks!
