### ISSUE TITLE
Strings in debugger only show up to 64 characters

### ISSUE THREAD

**Issue by lirao** [Microsoft/vscode-go#278]
Hope it's not a dlv issue. In the debug view, string values are displayed only up to 64 characters, which is really confusing when someone misinterprets it as string truncation. 

Why not put some sort of ellipses to show that the string has more content than is being displayed, or have the full contents display in a mouseover, or both?

**Comment by egamma** [comment]
// FYI @weinand

**Comment by weinand** [comment]
The VS Code debugger front end does not truncate strings in any way. So the 64 character limit is either imposed by the go debug extension or the go debugger itself.

/cc @egamma @isidorn

**Comment by lukehoban** [comment]
I've fixed this to match what Delve itself does - which is render "...+121 more" at the end if there are more than 64 chars.  Until Delve adds a way to request the full contents, this appears to be the best we can do.

**Comment by domaa11** [comment]
Does this give a way to extract more than the first 64 characters: `from the command line you can read the next 64 by using this syntax: print variable[64:]`: https://github.com/derekparker/delve/issues/609#issuecomment-239161459

**Comment by jbwiv** [comment]
I'm curious....should using the debug console in vscode give you access to the print command referenced above? It doesn't seem to work on my end. If you could make it to where print was accessible via the console, I'd bet that would be enough.

**Comment by pavittr** [comment]
This would be really useful. I'm currently trying to read a ~200 char string 64 chars at time. Being able to either configure the truncation or to call `print variable` would be a lot nicer.

**Comment by ramya-rao-a** [comment]
@pavittr #868 has a hack to get around the issue.
Looks like we have to use v2 of dlv apis to be able to configure the max string length.

**Comment by pavittr** [comment]
@ramya-rao-a thanks for that pointer, I've followed those instructions and now have full length strings, much appreciated :)
