### ISSUE TITLE
Picking a PID to attach to

### ISSUE THREAD

**Issue by eyalch** [microsoft/vscode-go#2780]
Taking note of the PID and updating the `launch.json` file with it every time I want to attach a debugger is a bit tedious.

**Is there a way I could make this a bit easier?**

For example, I can get the PID by running:
```sh
pidof go
```
And attach the Delve debugger to the process manually:
```sh
dlv attach $(pidof go) --headless --listen=:2345 --api-version=2
```
And then use the "Connect to server" launch configuration, but then I'll have to detach manually (instead of pressing a button in VS Code).

In the built-in Node.js debugger there's an option to pick a process from a list by specifying `${command:PickProcess}` in the `processId` field. Maybe something similar is possible?

**Comment by stamblerre** [comment]
We are migrating to a new repository (https://github.com/microsoft/vscode-go/issues/3247), so I have moved this issue to https://github.com/golang/vscode-go/issues/183. Thank you for this report!
