### ISSUE TITLE
can't autocomplete file, function and struct

### ISSUE THREAD

**Issue by harmnot** [microsoft/vscode-go#2781]
I have been uninstal Vscodel many time and install  again , then install rich go as well without change the setting

but I still can't get autocomplete import file and struct , functions 
what is wrong ?? 
I am really stuck about this

**Comment by ramya-rao-a** [comment]
- Please share any Go related settings you may have added/edited. You can get these by running the command `Preferences: Open Settings (JSON)`
- Does running the command `Go: Current GOPATH` give you the expected output?

**Comment by harmnot** [comment]
I have `.vscode` folder on my project path it has `setting.json `
and on that file 
```
{
    "go.inferGopath": false,
    "go.autocompleteUnimportedPackages": true,
    "go.buildOnSave": "workspace",
    "go.gocodeAutoBuild": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.coverageOptions": "showUncoveredCodeOnly",
    "go.formatTool": "goimports",
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.coverOnSave": true,
    "go.testOnSave": true,
}
```

and here on my `Preferences: Open Settings (JSON)`
```
{
    "go.formatTool": "goimports",
    "window.zoomLevel": 0,
    "go.autocompleteUnimportedPackages": true,
        "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": true,
        "documentLink": true
      },
      "go.inferGopath": false,
      "go.gocodeAutoBuild": true,
      "go.useCodeSnippetsOnFunctionSuggest": true,
      "go.coverageOptions": "showUncoveredCodeOnly",
      "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
      "go.coverOnSave": true,
      "go.testOnSave": true,
      "go.vetOnSave": "workspace",
      "go.docsTool": "gogetdoc",
}
```

I put on my .zshrc 
```
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
```

my project is on` ~/go/src/github.com/myProject`

yes I am using `go.mod`
and yes I install go extensions after I reinstall vscode , 
I have tried to uninstall and reinstall many time but didn't work 

do I missing something ?

**Comment by ramya-rao-a** [comment]
If you are using Go modules, then we suggest that you use[ language server.](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
Please add `"go.useLanguageServer": true` to your settings.
If you get prompted to install the language server (gopls), then install it and reload the VS Code window

**Comment by harmnot** [comment]
to my setting on` Preferences: Open Settings (JSON) ` ? or .vscode/setting.JSON

because I have 2 setting.json ?

**Comment by harmnot** [comment]
I did both but doesn't work, autocomplete not showing 
 here for  setting.json / user 
```
{
    "go.formatTool": "goimports",
    "window.zoomLevel": 0,
    "go.autocompleteUnimportedPackages": true,
        "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": true,
        "documentLink": true
      },
    "go.useLanguageServer": true
}
```

and here for .vscode/setting.json
```
{
    "go.inferGopath": false,
    "go.autocompleteUnimportedPackages": true,
    "go.buildOnSave": "workspace",
    "go.gocodeAutoBuild": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.coverageOptions": "showUncoveredCodeOnly",
    "go.formatTool": "goimports",
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.coverOnSave": true,
    "go.testOnSave": true,
    "go.useLanguageServer": true
}
```

**Comment by stamblerre** [comment]
You can check if the language server is running by going to View -> Output and then click on the Tasks dropdown. Is `gopls` in the list of tasks?

**Comment by harmnot** [comment]
no output doesn't show off there , it was nothing
 are my settings above I show u correct ?

**Comment by stamblerre** [comment]
They do look correct. Make sure to reload the VSCode window when you change settings related to the language server. Can you check that `gopls` is installed (it should be in`$GOPATH/bin`)?

**Comment by harmnot** [comment]
yes it already on $GOPATH/bin but still does not work

**Comment by harmnot** [comment]
any idea?

**Comment by stamblerre** [comment]
It may be related to your having multiple `settings.json` files. Can you try only using the one under `User` and see if that has any effect?

**Comment by ramya-rao-a** [comment]
Closing this issue as we need more information and there hasnt been any recent activity here.
