### ISSUE TITLE
Highlighting issue with go.useLanguageServer:true

### ISSUE THREAD

**Issue by asavchuk** [microsoft/vscode-go#2785]
Steps to reproduce:

- use in your settings: 
`"go.useLanguageServer":true`

- create a simple file:
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("main start")
	fmt.Println("ok")
}
```

- single click on one of the `Println` — it's not highlighted and the second `Println` is not highlighted also

Now let's turn off language server: `"go.useLanguageServer":false`
So, if you single click one of the `Println` then both `Println` function names will be highlighted — this is a **normal** expected behaviour.

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of the upstream issue

#2664 is another related issue as it tracks the need to disable the highlighting feature from `gopls`
