### ISSUE TITLE
Could not find packages, valid install of gopkgs

### ISSUE THREAD

**Issue by mickyco94** [microsoft/vscode-go#2786]
Currently getting an issue where I'm being consistently prompted to update to latest version of gopkgs. Receiving error messages:

`Could not find packages. Ensure `gopkgs -format {{.Name}};{{.ImportPath}}` runs successfully.`
`Your version of gopkgs appears to be out of date. Please update for an improved experience.`

Output of `gopkgs -format {{.Name}};{{.ImportPath}}` in Powershell:
```
PS C:\Users\michael.clerkin> gopkgs -format "{{.Name}};{{.ImportPath}}"       
gosym;debug/gosym
crc32;hash/crc32
httptest;net/http/httptest
clean;cmd/go/internal/clean
strings;strings
parse;text/template/parse
cryptobyte;vendor/golang.org/x/crypto/cryptobyte
render;github.com/cweill/gotests/internal/render
unreachable;golang.org/x/tools/go/analysis/passes/unreachable
mips64;cmd/compile/internal/mips64
palette;image/color/palette
nettest;vendor/golang.org/x/net/nettest
...
Omitted for brevity
...
ppc64;cmd/internal/obj/ppc64
elfexec;cmd/vendor/github.com/google/pprof/internal/elfexec
mime;mime
intsets;golang.org/x/tools/container/intsets
wasm;cmd/internal/obj/wasm
```

Curiously within bash I get no output for the same command.

My env:
```
PS C:\Users\michael.clerkin> go env                                                                                     set GO111MODULE=
set GOARCH=amd64
set GOBIN=C:\Users\michael.clerkin\go\bin
set GOCACHE=C:\Users\michael.clerkin\AppData\Local\go-build
set GOENV=C:\Users\michael.clerkin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\michael.clerkin\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\MICHAE~1.CLE\AppData\Local\Temp\go-build040422078=/tmp/go-build -gno-record-gcc-switches
PS C:\Users\michael.clerkin> code -v                                                                                    1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
PS C:\Users\michael.clerkin>     
```
Seeing these error messages in VSCode extension logs:
```
[2019-09-25 00:15:34.629] [exthost] [error] Error: write EPIPE
	at afterWriteDispatched (internal/stream_base_commons.js:78:25)
	at writeGeneric (internal/stream_base_commons.js:73:3)
	at Socket._writeGeneric (net.js:713:5)
	at Socket._write (net.js:725:8)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at Socket.Writable.end (_stream_writable.js:579:10)
	at Socket.end (net.js:544:31)
	at runGoCode.Promise (c:\Users\michael.clerkin\.vscode\extensions\ms-vscode.go-0.11.6\out\src\goSuggest.js:326:25)
	at new Promise (<anonymous>)
	at GoCompletionItemProvider.runGoCode (c:\Users\michael.clerkin\.vscode\extensions\ms-vscode.go-0.11.6\out\src\goSuggest.js:183:16)
	at provideCompletionItemsInternal.__awaiter.ensureGoCodeConfigured.then.Promise (c:\Users\michael.clerkin\.vscode\extensions\ms-vscode.go-0.11.6\out\src\goSuggest.js:129:33)
	at new Promise (<anonymous>)
	at provideCompletionItemsInternal.__awaiter.ensureGoCodeConfigured.then (c:\Users\michael.clerkin\.vscode\extensions\ms-vscode.go-0.11.6\out\src\goSuggest.js:104:24)
```

Steps to Reproduce:

1. Install golang windows amd64
2. Install vs code extension
3. Install tools using extension `Go: Install/Update Tools` or manually using `go get`

Results in no intellisense, linting, imports etc. Tried reinstalling go, vscode and of course the extension. This is on a relatively fresh install of Windows as well. Cannot see any documentation on what to do after you receive the error message `Could not find packages. Ensure gopkgs -format {{.Name}};{{.ImportPath}} runs successfully.` and have successfully ensured that is the case.

**Comment by ramya-rao-a** [comment]
The fact that you are getting the message about updating `gopkgs` and not installing `gopkgs` tells me that the `gopkgs` that the extension found is the wrong one.

Your attempts to run the command in Powershell vs bash giving different results hint at the same conclusion that you might be having different values for PATH

What does running `gopkgs -format {{.Name}};{{.ImportPath}}` in the integrated terminal in VS Code give you?

There might be an older `gopkgs.exe` lying around somewhere in your machine that the extension is picking up

**Comment by mickyco94** [comment]
Yeah so I originally had the same thought, removing gopkgs from `~/go/bin` results in 
```
$ gopkgs
bash: /c/Users/michael.clerkin/go/bin/gopkgs: No such file or directory
```
So I don't think there are any other versions lingering in my PATH variable. Running from integrated terminal in vscode gives me no output. Which makes sense since my integrated terminal is bash.

**Comment by ramya-rao-a** [comment]
@mickyco94 Sorry, I couldn't back to the issue sooner. Do you still have the problem?

> Running gopkgs -format {{.Name}};{{.ImportPath}} from integrated terminal in vscode gives me no output. Which makes sense since my integrated terminal is bash.

Why would it make sense for bash not to show any results?
