### ISSUE TITLE
SQL highlighting in multiline strings

### ISSUE THREAD

**Issue by tevariou** [microsoft/vscode-go#2788]
A proposal to support SQL highlighting in strings as in this Python extension https://marketplace.visualstudio.com/items?itemName=ptweir.python-string-sql

**Comment by ramya-rao-a** [comment]
Hey @tevariou, thanks for reporting!

I do see the merits of this feature, although I am afraid I don't believe this extension is the right place for it. 

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features. 

Therefore, one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.

Happy Coding!
