### ISSUE TITLE
No autocomplete for localpackages - gopls, go modules

### ISSUE THREAD

**Issue by nbaztec** [microsoft/vscode-go#2797]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1. `go mod init && go get github.com/go-kit/kit`
2. Type `func Foo(end(_)

**Expected Output**
Suggestion to gokit pacakge `endpoint`

**Actual Output**
No Suggestion

**Versions**
VS Code
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0

gopls
golang.org/x/tools/gopls v0.1.7
    golang.org/x/tools/gopls@v0.1.7 h1:YwKf8t9h69++qCtVmc2q6fVuetFXmmu9LKoPMYLZid4=

**Comment by stamblerre** [comment]
`gopls` does not yet support autocompletion for unimported third-party packages. You can track updates to this issue in https://github.com/golang/go/issues/31906.

**Comment by ramya-rao-a** [comment]
Closing in favor of the upstream issue in gopls
