### ISSUE TITLE
[quick info] HTML entities are decoded

### ISSUE THREAD

**Issue by movsb** [microsoft/vscode-go#2798]
Sample code:

```go
package main

import "html"

func main() {
	html.UnescapeString("aaa")
}
```

Now hover over `UnescapeString`:

What it shows (wrapped):

Notice this string `like "<" to become "<"`.

```
UnescapeString func(s string) string

UnescapeString unescapes entities like "<" to become "<". It unescapes a
larger range of entities than EscapeString escapes. For example, "á"
unescapes to "á", as does "á" and "á".
UnescapeString(EscapeString(s)) == s always holds, but the converse isn't
always true.
```

Comment for EscapeString:

```
// UnescapeString unescapes entities like "&lt;" to become "<". It unescapes a
// larger range of entities than EscapeString escapes. For example, "&aacute;"
// unescapes to "á", as does "&#225;" and "&#xE1;".
// UnescapeString(EscapeString(s)) == s always holds, but the converse isn't
// always true.
```

HTML entities like `&lt;` `&aacute;` shouldn't be decoded.

**Comment by stamblerre** [comment]
@movsb: Can you share your VSCode settings? Are you using the language server?

**Comment by movsb** [comment]
Almost the default settings:

```json
{
    "workbench.statusBar.visible": true,
    "workbench.activityBar.visible": true,
    "editor.minimap.enabled": false,
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": false,
    "editor.fontFamily": "Monaco, Menlo, monospace",
    "workbench.colorTheme": "Monokai Dimmed",
    "editor.lineNumbers": "relative",
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "terminal.integrated.scrollback": 9999,
    "window.zoomLevel": 0,
    "editor.fontWeight": "bold",
    "extensions.ignoreRecommendations": false,
    "gitlens.currentLine.enabled": false,
    "go.testFlags": [
        "-v"
    ],
    "go.formatTool": "goimports"
}
```

Think it's very easy to reproduce.

**Comment by ramya-rao-a** [comment]
@stamblerre The language server does handle this correctly, though it shows only the first sentence.

<img width="659" alt="Screen Shot 2020-01-21 at 10 18 44 PM" src="https://user-images.githubusercontent.com/16890566/72870080-02565b00-3c9c-11ea-8cce-68ba1aed7545.png">

**Comment by stamblerre** [comment]
The first sentence is because `gopls` defaults to showing a synopsis of the documentation rather than the full text. You can see the full text by switching the [hover kind](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#hoverkind-string) setting to "FullDocumentation".

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@movsb Future investment for language features will be done in the language server area. Since the language server does support rendering the encoded values correctly, I'll be closing this issue.

**Comment by movsb** [comment]
Thanks. I see it has been fixed in the latest version of VSCode.
