### ISSUE TITLE
Analysis Tools Missing

### ISSUE THREAD

**Issue by rvdwijngaard** [Microsoft/vscode-go#28]
I get the message that the analysis tools are missing but they are certainly not; the first time I used the extension I got this message and chose Install and some missing tools were installed. The extension seems to work fine with the go analysis tools. After restarting Code, however, it's again complaining about the analysis tools. Am I missing something here? 

Please advice.

**Comment by rvdwijngaard** [comment]
is this somehow related to this config? 
*"go.gopath": "/Users/lukeh/go"*

In my case GOPATH is set as an environment variable.

**Comment by rvdwijngaard** [comment]
yes it does; so maybe it's better to not include this setting in the standard config of the readme? please close this issue.

**Comment by newhook** [comment]
I get this message too and don't have go.gopath set (it comes from my environment also). Furthermore, pressing "install" doesn't do anything. What is the solution?

**Comment by jhonghee** [comment]
Having same issue on windows. The extension doesn't seem to detect environment variables at all. I tried to set go.gopath and go.gobin in user setting but didn't work either.

**Comment by jchannon** [comment]
I think you have to open VSCode from the terminal. This also applies to Atom, that way it loads the environment variables. Please close if this solves it, this issue is tracked in #10

**Comment by newhook** [comment]
That does not solve theproblem. The GOPATH is correct, it looks for the binaries in the wrong way. Furthermore, install does not attempt to install them.

**Comment by lukehoban** [comment]
I'm pretty certain this is the same issue as #19.  

@rvdwijngaard and @newhook - Could you confirm that you both have multi-workspace GOPATHs?  If not there may be some other issue.  I'll close for now.
