### ISSUE TITLE
Type Hover ignores package prefixes

### ISSUE THREAD

**Issue by Nokel81** [microsoft/vscode-go#2801]
Given the following structure:

In `foo/bar.go`
```
package foo

type BAR int
```
In `goo/bar.go`
```
package goo

type BAR uint
```
In `main.go`:
```
package main

import (
    "./goo"
    "./foo"
)

func iceCream(a foo.BAR, b goo.BAR) bool {
    ...
}
```

If you were to hover over the definition of `iceCream` then the signature would read `iceCream func(a BAR, b BAR) bool` which is is sort of correct, but doesn't help much. 

This is even less helpful when working with multiple packages that all use the same names (since idiomatic go recommends to use the package name as part of the type) this can be quite prevalent.

**Comment by ramya-rao-a** [comment]
Can you share your Go related settings so that I can know which tool is being used for this feature in your case? You can get this information by running the command `Preferences: Open Settings (JSON)`.

Few alternatives you can try are:
- If you are not using the language server, try changing your setting `go.docsTool` to `gogetdoc`.
- Or use the language server, by adding the setting `go.useLanguageServer` to `true`

**Comment by Nokel81** [comment]
<details><summary>Config</summary>
<p>

#### Just the `go.` fields

```json
{
    "go.lintTool": "golangci-lint",
    "go.lintFlags": [
        "--fast"
    ],
    "go.coverOnSingleTest": true,
    "go.vetOnSave": "workspace",
    "go.languageServerFlags": [
        "-rpc.trace"
    ],
    "go.toolsEnvVars": {
        "GO111MODULE": "on"
    },
    "go.formatTool": "goimports"
}
```

</p>
</details>

**Comment by ramya-rao-a** [comment]
So, looks like you are using the default Go tools and not the language server. Please try the below
- Add the setting `go.docsTool` setting to `gogetdoc` 
- If you dont get prompted to install `gogetdoc`, then run the command `Go: Install/Update Tools`, select `gogetdoc`, press ok.
- Reload VS Code window after installation of gogetdoc is complete and try again

**Comment by Nokel81** [comment]
I have added that setting, and after it was installed I force reloaded vscode. However, the same outcome still happens.

**Comment by ramya-rao-a** [comment]
I followed your code structure and I am able to see the hover text including the package information

<img width="489" alt="Screen Shot 2019-10-20 at 7 22 30 PM" src="https://user-images.githubusercontent.com/16890566/67172188-29388480-f36f-11e9-9891-778e5eaf979d.png">

**Comment by Nokel81** [comment]
Ah I see my problem in my description. It seems to be working for relative imports but not for imports from GOPATH.
