### ISSUE TITLE
The line is added to go.mod when saving file

### ISSUE THREAD

**Issue by huiyifyj** [microsoft/vscode-go#2809]
Everytime I type `crtl+s` to save `*.go` file, `go 1.13` is added to the end of `go.mod` file.
So I have to waste time removing the line before I commit changes by git.
How can I do to avoid it ?
Or, is it set as the unchangeable default behavior ?

**Comment by yulrizka** [comment]
I believe this is go mod that added this line. if you run `go mod tidy` for example, it will also add this line

**Comment by stamblerre** [comment]
@yulrizka is correct - this is an expected behavior of the `go` command. The VSCode extension calls the `go` command, which is why this modification is happening.

**Comment by ramya-rao-a** [comment]
Closing this issue as this is expected behavior from how the Go command behaves when in module mode
