### ISSUE TITLE
gopls causes disconnects in remote workspace

### ISSUE THREAD

**Issue by orn688** [microsoft/vscode-go#2815]
The remote VS Code extension has been (seemingly) randomly disconnecting with the message "Cannot reconnect. Please reload the window." This happens roughly once every one to two hours, sometimes when the VS Code window is out of focus and sometimes when I'm working in it. This does not happen in other workspaces in which I don't use the Go extension as heavily.

Here is the window log (I wasn't able to see any other logs after it had disconnected):
https://gist.github.com/orn688/a1d8edfb05eef4214bb3a32d0ec61262

And here is a gopls log I found on the extension host, which seems more useful (full paths redacted and replaced with ellipses): https://gist.github.com/orn688/81d7303147ef32c18741b901fd6f1460

This is the `main.go` file that's referenced; it's only slightly modified in my local workspace (though it definitely still doesn't have any text in it that looks like "357.000000:31.000000"): https://github.com/luci/luci-go/blob/master/cipd/client/cli/main.go

Steps to Reproduce:

1. Connect to a remote VS Code server using the remote SSH extension, in a Go workspace
2. Work for a couple hours until client disconnects

(sorry I can't provide more specific reproduction steps – it happens very reliably locally though)

Go-specific settings:
```json
{
    "go.useLanguageServer": true,
    "go.lintFlags": [
        "--fast"
    ],
    "go.formatTool": "gofmt",
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
        "editor.formatOnSave": true
    }
}
```

VS Code version: 1.38.1
Go extension version: 0.11.7

(Moved from [vscode-remote-release issue #1473](https://github.com/microsoft/vscode-remote-release/issues/1473))

**Comment by stamblerre** [comment]
Do you see this behavior when you don't use `gopls`?

**Comment by stamblerre** [comment]
Also, can you add `"go.languageServerFlags": ["-rpc.trace"]` to your VSCode settings. That will result in more detailed logs.

**Comment by orn688** [comment]
Sure, I'll do that. I'll haven't tried disabling gopls yet, so I'll do that after and see if it helps.

**Comment by orn688** [comment]
Here's the log with rpc traces enabled! Hope it helps:
https://gist.github.com/orn688/fd8e4d2e3f8774afe96c3ddd31686739

**Comment by orn688** [comment]
I disabled `"go.useLanguageServer"` and it still happens... So maybe not a gopls issue after all?

**Comment by orn688** [comment]
Pretty sure this is unrelated to gopls after all – the issue seems to be that the file watcher can't handle an excessive number of files in the workspace. I deleted a bunch of old cached files in the root of my workspace and now things seem to be working fine.

Thanks for the help!
