### ISSUE TITLE
Syntax highlighting fails to colorize chan of chans

### ISSUE THREAD

**Issue by AaronReboot** [microsoft/vscode-go#2816]
Example, note the `<-chan <-chan` on line 73

![image](https://user-images.githubusercontent.com/14034112/66335783-b7d9ea00-e909-11e9-86b2-88f8a49df870.png)

Expected to see both occurrences of `<-chan` to have the same colorization

**Comment by ramya-rao-a** [comment]
@AaronReboot The colors are controlled by the grammar being used and the grammar is part of the main VS Code project. Therefore, please log this issue in the [VS Code repo](https://github.com/Microsoft/vscode)
