### ISSUE TITLE
Code disappears on save

### ISSUE THREAD

**Issue by jpvillaseca** [microsoft/vscode-go#2820]
Issue Type: <b>Bug</b>

When editingg with vscode-go, after a while any edit on a file gets dropped when saving, and it defaults back to normal or sometimes it repeats the last 2 lines of the code file. The only solution is to restart vscode. But the error appears many times during the day. It's similar to issue #2787 but it occurs even when not debugging. 

Extension version: 0.11.7
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.86GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by xaavito** [comment]
Same Here, but it happenson every save, it goes back to original version of any file

Name: Go
Id: ms-vscode.go
Description: Rich Go language support for Visual Studio Code
Version: 0.11.7
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go

Microsoft Windows 10
version 1809 (Build 17763.775)

**Comment by jpvillaseca** [comment]
I tried it with or without setting any Go settings, but it happens just the same. 
Using go1.13.1 windows/amd64

`	"go.inferGopath": true,
	"go.useLanguageServer": true,
	"go.formatTool": "gofmt",
	"go.languageServerExperimentalFeatures": {
		"format": false,
		"autoComplete": true,
		"rename": true,
		"goToDefinition": true,
		"hover": true,
		"signatureHelp": true,
		"goToTypeDefinition": true,
		"goToImplementation": true,
		"documentSymbols": true,
		"workspaceSymbols": true,
		"findReferences": true,
		"diagnostics": true,
		"documentLink": true
	},
	"[go]": {
		"editor.formatOnSave": false
	}`

**Comment by stamblerre** [comment]
Can everyone in this thread please share their settings? It will be helpful to understand if this is being caused by the language server, so please make sure to disable it.

**Comment by xaavito** [comment]
What Do you mean by settings? Windows? VC?

**Comment by ramya-rao-a** [comment]
You can find the settings you have added/edited by running the command `Preferences: Open Settings(JSON)`. If you share those, then we can determine if this is being caused by the language server or not.

@jpvillaseca When you change any language server related setting, you will need to restart VS Code for it to take affect. Please let us know if you see the same when language server is disabled

**Comment by jpvillaseca** [comment]
> @jpvillaseca When you change any language server related setting, you will need to restart VS Code for it to take affect. Please let us know if you see the same when language server is disabled

Thank you . Disabling the language server the issue goes away

**Comment by stamblerre** [comment]
@jpvillaseca: Could you share which version of the language server you were using (`gopls version`)?
