### ISSUE TITLE
extension does not eager load when workspace contains .go files

### ISSUE THREAD

**Issue by theryansmith** [microsoft/vscode-go#2821]
The extension does not load on activationEvent  ""workspaceContains:**/.go"

This means users loading a workspace containing go files need to open a .go file, or run specific go commands before they can build the workspace.

Steps to Reproduce:
1. close all vscode instances
2. open a workspace that has .go files, ensure that the default state does not focus on a .go code file
3. try to ctrl-shift-p->"Go: Build Workspace"
4. Notice that it fails because the extension is not loaded

Possible solution: Modify package.json to include the workspaceContains event:
	"activationEvents": [
		"workspaceContains:**/.go",
		"onLanguage:go",
		"onCommand:go.gopath",
		"onCommand:go.tools.install",
		"onDebugResolve:go"
	],

**Comment by ramya-rao-a** [comment]
Fair point, thanks for reporting!

PRs to add this feature is most welcome.

**Comment by aykejriw** [comment]
@ramya-rao-a  I want to work on this.

**Comment by ramya-rao-a** [comment]
Sorry @aykejriw 
There was an open PR for this in (#2859) that I just now approved and merged

**Comment by ramya-rao-a** [comment]
The latest version of this extension (0.12.0) has this feature now.

Thanks to @theryansmith for reporting and to @zmb3 for the PR :)

Happy Coding!
