### ISSUE TITLE
Search for implementations doesn't work

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode-go#2823]
1. go1.13
2. vscode-go 0.11.7
3. gopls@master

Peek implementations `Ctrl-Shift-F12` used. `Ctrl-F12` has same result. There are 2 implementations of given service, however `guru` returns immediately:
![изображение](https://user-images.githubusercontent.com/6797881/66496278-5f4e4c80-eac3-11e9-849b-9ecd74f851d7.png)

**Comment by ramya-rao-a** [comment]
Can you run the guru command with those exact arguments and see if it returns any results?

**Comment by inliquid** [comment]
it returns exactly this:
```
guru: no packages specified for pointer analysis scope
```

**Comment by ramya-rao-a** [comment]
Are you using modules? If yes, then we know that `guru` does not have module support yet.

@stamblerre Does the language server support the implementation provider yet?

**Comment by inliquid** [comment]
@ramya-rao-a yes, with modules. It worked previously, I just didn't use often it because it's too slow. Not sure what changed now.

**Comment by stamblerre** [comment]
`guru` will not have module support and is not being actively developed. `gopls` does not yet have the implementation feature, but it is something we intend to add support for soon (https://github.com/golang/go/issues/32973).

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of the upstream issue linked above.
