### ISSUE TITLE
Saving inserts parts of old code

### ISSUE THREAD

**Issue by Tobi696** [microsoft/vscode-go#2824]
As shown in the video below, if I want to save the file, parts of the old code get inserted.
Go version: go1.13.1 windows/amd64
[Video](https://imgur.com/a/WicLcLJ)
Thanks for your help!

**Comment by stamblerre** [comment]
Can you share your VSCode settings? Are you using the language server?

**Comment by ramosisw** [comment]
Same problem
https://recordit.co/tkQaDUembb

**Comment by ramya-rao-a** [comment]
@Tobi696, @ramosisw Please share any Go related settings you might have added/edited. You can get these by running the command `Preferences: Open Settings (JSON)`

**Comment by ramosisw** [comment]
My settings.json
```json
{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "diffEditor.renderSideBySide": true,
    "window.zoomLevel": 0,
    "files.exclude": {
        "**/.classpath": true,
        "**/.factorypath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/bin": true,
        "**/obj": true
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "diffEditor.ignoreTrimWhitespace": true,
    "[csharp]": {},
    "javascript.updateImportsOnFileMove.enabled": "always",
    "workbench.startupEditor": "welcomePage",
    "extensions.ignoreRecommendations": false,
    "workbench.editor.revealIfOpen": true,
    "go.useLanguageServer": false,
    "go.buildFlags": [
        "--check-go-version",
        "false"
    ],
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "go.autocompleteUnimportedPackages": true,
    "go.buildOnSave": "off",
    "go.formatTool": "gofmt"
}
```

**Comment by ramya-rao-a** [comment]
@ramosisw Can you clarify what the problem in your recording is?
From what I could see,
You are typing in the first file main.go. Everything seems ok there
Then, you move to the other file and start typing the comment, and it disappears on save. Is that the probelm?

Also, from your settings it looks like the language server is disabled, but in your recording the imports are clickable and have underlines, which is a feature from the language server I believe. So, are you seeing the problem when the language server is enabled or disabled?

@Tobi696 Please share your settings as well. Are you using the language server too?

**Comment by ramosisw** [comment]
@ramya-rao-a Sure, some times when write code, comments, etc... then save my changes, and the file are "restored", i read about "LanguageServer: false" change these setting and problem disapears, also change format to gofmt.

**Comment by ramya-rao-a** [comment]
Thanks @ramosisw 
Can you share the version of `gopls` you are using? You can run the command `gopls version` to find this.

**Comment by ramosisw** [comment]
@ramya-rao-a  the output is
```sh
golang.org/x/tools/gopls v0.1.7
golang.org/x/tools/gopls@v0.1.7 h1:YwKf8t9h69++qCtVmc2q6fVuetFXmmu9LKoPMYLZid4=
```

**Comment by stamblerre** [comment]
Enough people have reported this issue that I have started a thread in the Go issue tracker. Please follow the suggestions here: https://github.com/golang/go/issues/34955. Hopefully we'll be able to track this down. Thank you!

**Comment by ramya-rao-a** [comment]
Thanks @ramosisw 

Closing this issue in favor of the upstream issue for gopls https://github.com/golang/go/issues/34955
