### ISSUE TITLE
step into and debug console reports: go list failed on

### ISSUE THREAD

**Issue by xujintao** [microsoft/vscode-go#2826]
### vscode version
```
1.38.0
```
### vscode-go version
```
0.11.7
And relevant go tools are latest.
```
### What did you do?
when step into a namespace.function here is block.Encrypt, debug console print:
```
go list failed on .: can't load package: package .: no Go files in /home/pi
```
### Steps to Reproduce:
```
package main

import (
	"crypto/aes"
	"fmt"
)

func main() {
	block, _ := aes.NewCipher([]byte("0123456789012345"))
	buf := []byte("hello")
	var encbuf [256]byte
	block.Encrypt(encbuf[:], buf) // go list failed on .: can't load package: package .: no Go files in /home/pi
	fmt.Print("123")
}
```
![Screenshot from 2019-10-11 15-41-28](https://user-images.githubusercontent.com/5418373/66633607-c55edf00-ec3d-11e9-9b27-329d041a5c10.png)
### What did you expect to see?
step into successfully.

**Comment by ramya-rao-a** [comment]
This error is coming from delve.
Can you run `delve debug` command from the terminal and see if you are able to step in/out without errors?

**Comment by xujintao** [comment]
Hi, ramya. You are right. It's dlv who should take the blame.
The abstract example is like this:
```
package main

type barError struct {
	fooError
}

type fooError struct{}

func (e *fooError) Error() string {
	return "foo error"
}

func main() {
	err := func() error {
		return &barError{}
	}()
	str := err.Error() // can not step into
	println(str)
}
```
barError derives from fooError, 
and *fooError implemented error, so *barError also implemented error. This is right in golang world.
However, dlv debug can not step into (*fooError).Error method guided by *barError

**Comment by ramya-rao-a** [comment]
Thats great to hear!
Please log an issue at https://github.com/go-delve/delve/issues

Happy Coding!
