### ISSUE TITLE
Debug test feature doesn't work for modules in gopath

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode-go#2828]
Example is [here](https://github.com/SteelPhase/vscode-go-2828)

Running `Run Unit Test` while this module is outside of the gopath will result in the test debugging correctly.
Running `Run Unit Test` while this module is in the gopath will result in the test failing.

It appears that the execution of dlv test differs for modules outside of the gopath

- Module outside gopath `Running: /Users/steelphase/Code/Go/bin/dlv test --headless=true --listen=127.0.0.1:37823 --api-version=2 --log=true` 
- Module in gopath `Running: /Users/steelphase/Code/Go/bin/dlv test github.com/steelphase/vscode-go-2828/pkg/printer --headless=true --listen=127.0.0.1:47612 --api-version=2 --log=true`

The offending code appears to be here. I think there needs to be an additional check that the workspace we are in even if in gopath is a module. This is was changed in go 1.13 when the default for  `GO111MODULE` determines if project is a module differently.

https://github.com/microsoft/vscode-go/blob/9874b406352dbec2cb33648e9cc27fd1729bee06/src/debugAdapter/goDebug.ts#L433-L439

**Comment by SteelPhase** [comment]
From #modules on the Gophers slack, it appears that relying on the output of `go env GOMOD` returning the go.mod file for the current working directory could be a decent solution to this. It would also support all the settings of `GO111MODULE`.

**Comment by ramya-rao-a** [comment]
This only affects the time when GO111MODULE is set to `auto` right?

**Comment by SteelPhase** [comment]
it does affect auto.  I'll check if the same behavior happens with on

**Comment by ramya-rao-a** [comment]
> This is was changed in go 1.13 when the default for GO111MODULE determines if project is a module differently.

@SteelPhase Can you elaborate on what changed in go 1.13 for GO111MODULE?
cc @stamblerre

**Comment by stamblerre** [comment]
I do believe the correct approach would be to use the result of `go env GOMOD`. This way, you don't have to worry about the changing meanings of `GO111MODULE`--you can rely on the `go` command to tell you that you are in a module.

https://golang.org/doc/go1.13#modules explains the changes to the meaning of `auto` for Go 1.13.

**Comment by ramya-rao-a** [comment]
Please try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the fix for this

**Comment by ramya-rao-a** [comment]
The latest update to this extension (0.11.8) has the fix for this.

Thanks for reporting @SteelPhase 

Happy Coding!
