### ISSUE TITLE
go.testEnvVars doesn't resolve referencing other environment variable while running test

### ISSUE THREAD

**Issue by raushan2016** [microsoft/vscode-go#2829]
I need to set a environment variable for the go test to use. This environment variable references default variable $USER.

### To Reproduce

```
 # .vscode/settings.json
{
"go.testEnvVars": {
  "CRD_DOMAIN": "${env:USER}.io"
 },
}
```
**main_Test.go**

```
package main

import (
	"fmt"
	"os"
	"testing"
)

func TestEnvVar(t *testing.T) {
	foo := os.Getenv("CRD_DOMAIN")
	fmt.Printf("foo: %v \n", foo)
}
```

### Behaviour
When i use `run test` button on top of the test it results
`foo: ${env:USER}.io`

where as with `debug test` button the environment variable is fully resolved
`foo: foobar.io`

**Comment by ramya-rao-a** [comment]
The env variable resolution is done by VS Code in settings for the top level values. So, for example, if you had set your `go.gopath` setting to `${env:USER}`, that value would flow correctly.

But, I believe VS Code does not do the resolution if the value of the setting is anything more complex than a string which is what happens in the case of `go.testEnvVars` setting.

The `go.testEnvVars` is specifically read by this extension to set the env variables in the process that runs the test.
The values in launch.json is used by VS Code itself and set appropriately before it starts a debugging session.

To fix this, either VS Code has to start replacing the `${env:USER}` format in nested values in setting or the Go extension should do something similar. I would suggest logging an issue in VS Code first. Only if it is determined there that this is something that the extension should handle, we can look into it.
