### ISSUE TITLE
go execution: execFile doesn't respect alternative absolute path

### ISSUE THREAD

**Issue by jeffbean** [microsoft/vscode-go#2830]
# the issue
In having a unique go setup where in the IDE we set an absolute path for the Go binary. While this works for most cases like tests, it is failing to use this setting in the go modules system.

running on OSX 10.14.6 with go 1.12 and or 1.13

## Steps to Reproduce:
It's a bit convoluted but the idea is there is a go command in your path that is not the same as the alternateTools path in the settings. These steps are **a bit risky** since its setting up a non-default go binary so ensure to do in some amount of isolation.
 
1. set the vscode go bin to an absolute path and enable the Language server (only to force the go env GOMOD command to run.

```json
    "go.alternateTools": {
        "go": "/usr/local/bin/go"
    },
    "go.useLanguageServer": true,
```
2. create a go executable that is in your path but does not match the alternateTools value `echo "#!/bin/bash \nfalse" > ${HOME}/go-code/bin/go`
3. append your shell PATH to have this go wrapper first.
`export PATH=${HOME}/go-code/bin:${PATH}`
4. Open a Go file and do anything to trigger code inspection in vscode. 

```
[Info  - 10:14:19 AM] 2019/10/12 10:14:19 1.090392449s for GOROOT=/usr/local/Cellar/go@1.12/1.12.10/libexec GOPATH=/Users/jeffbean/go-code GO111MODULE= PWD=/Users/jeffbean/go-code/src/code.internal/foo go "env" "GOPATH", stderr: <<REDACTED
```
Under the hood, this PWD has a direnv that has a `go` in its path that wraps the native go for certain things but is not able to execute here and fails. 

**The issue** here is we need the `go` binary to be `/usr/local/bin/go`

### the env 
I can also show the env context from debugging for this command: I have removed content and trimmed unrelated paths but in PATH you can see `'/Users/jeffbean/go-code/bin` may be causing the exec system to assume a relative path for `go` since  `'/Users/jeffbean/go-code/bin/go` exists.
```
GOBIN: '/Users/jeffbean/go/bin',
PATH:
   '/Users/jeffbean/go-code/bin:/usr/local/sbin:/usr/local/bin:/Users/jeffbean/go/bin:/usr/bin:/bin:/usr/sbin:/sbin',
PWD: '/Users/jeffbean/go-code/src/code.internal/dns',
GOPATH: '/Users/jeffbean/go-code',
GOROOT: '/usr/local/Cellar/go@1.12/1.12.10/libexec'
```
```shell
ls -l /Users/jeffbean/go-code/bin/go 
-rwxr-xr-x  1 bean  bean  4177 Aug 16 11:17 /Users/jeffbean/go-code/bin/go
```

## Investigation
I think this is from the child_process.execFile doing some implicit path reducing. https://github.com/microsoft/vscode-go/blob/master/src/goModules.ts#L26

In debugging the extention at this line the `goExecutable` value is correct in this case, but the 
resulting command does not have the absolute path.

**Comment by ramya-rao-a** [comment]
So what we have is
- The extension is figuring out the right path to the Go binary which is what you see in the `goExecutable` variable in https://github.com/microsoft/vscode-go/blob/master/src/goModules.ts#L26. Did you find this to be the absolute path or relative path?
- The `execFile()` is internally using some other executable even though an absolute path was provided for it
?

**Comment by jeffbean** [comment]
> * The extension is figuring out the right path to the Go binary which is what you see in the `goExecutable` variable in https://github.com/microsoft/vscode-go/blob/master/src/goModules.ts#L26. Did you find this to be the absolute path or relative path?

This was the absolute path. My findings were that the variable passed into `execFile` was always absolute. But once the command is executed it was then just `go`.

> * The execFile() is internally using some other executable even though an absolute path was provided for it

This is my current thought, I have no definitive proof and not versed in node/typescript enough to definitely make this case. But the behavior of the inputs and outputs of this execFile seem to be doing something implisit with paths.

**Comment by hyangah** [comment]
Is this still an issue? 
Early this year, we somehow tricked underlying tools (language server, etc) by mutating the `PATH` env var so they all pick the same `go` by default.
https://github.com/microsoft/vscode-go/blob/master/src/goInstallTools.ts#L446
I expect that would fix the problem described here. 

If you still see the issue, please file a new issue in https://github.com/golang/vscode-go as we are moving. Thanks!
