### ISSUE TITLE
clicking "debug test" above "func Test..." says, "'${MODULES_USE_COMPAT_VERSION:-0}' cannot be resolved because command has no value"

### ISSUE THREAD

**Issue by reiki33** [microsoft/vscode-go#2831]
Issue Type: <b>Bug</b>

Uninstalling both go and vsc, and reinstalling does not help. Debug on a test used to work, and I likely did something to confound vsc. "run test" will run the test. Internet search provided nothing that made sense to me.
Attempting to uninstall the go pluging refuses, saying the extension is needed for VSCode essentials.

Extension version: 0.11.7
VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:03.188Z)
OS version: Linux x64 5.2.18-200.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz (4 x 3059)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.59GB (0.21GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ramya-rao-a** [comment]
Can you share a screenshot of the error?

Are you able to debug the test using a launch configuration? See https://github.com/microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#sample-configuration-to-debug-a-single-test for an example.

**Comment by ulodciv** [comment]
I have the same issue, debugging on a test raises error "'${MODULES_USE_COMPAT_VERSION:-0}' cannot be resolved because command has no value", with Python, not go. I did not get that error before.

Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.18-200.fc30.x86_64

**Comment by reiki33** [comment]
The text in the OUTPUT window at the bottom is from the successful run when
clicking on "run test". The pop-up window appears when I click in the
"debug test" area.
After sleep, I was thinking it may be go-delve, since dlv did not produce
this message. However, the post indicating the same problem with Python
testing suggests it is either not go-delve, or it is a common issue between
the two language versions and launching something.
I do not see how to start dlv on a unit test, yet, but on the main routine,
"dlv debug mv.go" puts me at the dlv prompt, so it is not dlv itself.

**Comment by zaro** [comment]
can confirm the same issue with python. After I updated vscode to 
```
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.18-200.fc30.x86_64
```
I see this message when I try to start debugger with python flask app.

**Comment by gkhanna79** [comment]
I can confirm this issue reproes with attempting to launch a go program as well, under the debugger and without it as well.

Golang: 1.13
OS: Fedora 30

VSCode details:

Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.1.15-300.fc30.x86_64

**Comment by gkhanna79** [comment]
![VSCode_Golang_Bug](https://user-images.githubusercontent.com/9451457/66763288-7216a780-ee5c-11e9-832a-0f44ca586bf2.png)

@ramya-rao-a Please see the screenshot.

**Comment by gkhanna79** [comment]
@ramya-rao-a Have you had a chance to look into this?

**Comment by reiki33** [comment]
I uninstalled 1.39.1 (#dnf remove code), installed 1.38.1, and successfully
ran "debug test" on:
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.18-200.fc30.x86_64

During the install, I saw this error (and I remember it from the install on
1.39 as well).
Is this another issue?

# dnf install code-1.38.1-1568209352.el7.x86_64.rpm
Repository for Ozon OS                          0.0  B/s |   0  B     00:10

Error: Failed to download metadata for repo 'ozonos': Cannot download
repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: ozonos
Last metadata expiration check: 2:38:54 ago on Mon 14 Oct 2019 07:47:10 PM
PDT.
Dependencies resolved.
================================================================================
 Package    Architecture Version                       Repository
 Size
================================================================================
Installing:
 code       x86_64       1.38.1-1568209352.el7         @commandline
 78 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 78 M
Installed size: 232 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :
 1/1
  Installing       : code-1.38.1-1568209352.el7.x86_64
 1/1
  Running scriptlet: code-1.38.1-1568209352.el7.x86_64
 1/1
  Verifying        : code-1.38.1-1568209352.el7.x86_64
 1/1

Installed:
  code-1.38.1-1568209352.el7.x86_64


Complete!

**Comment by derba** [comment]
@reiki33 thank you. I ran into the same issue with the same setup (Fedora 30, VS Code, Go).

I issued `sudo dnf downgrade code-1.38.1`.
To avoid update undo it I use `sudo dnf update --exclude=code`.
Unfortunately I could not find a working guide on making `dnf versionlock` work.

Could you update your [SO](https://stackoverflow.com/questions/58360459/visual-studio-code-debug-go-test-error-modules-use-compat-version-0-cann) entry to point to this page? At the moment it is put on hold, so you cannot answer it, but at least you can edit the question.

**Comment by jpkrohling** [comment]
I can confirm that downgrading to 1.38.1 makes debugging work again.

**Comment by twiest** [comment]
I have the same issue and downgrading to 1.38.1 worked for me as well.

I filed [this](https://github.com/microsoft/vscode/issues/82611) bug against vscode, but it got closed and I was asked to open a bug against `vscode-go` instead.

**Comment by reiki33** [comment]
Why does that make sense if it also fails with Python as noted by Svetlozar
Argirov?

**Comment by ramya-rao-a** [comment]
The upstream issue in VS Code has been re-opened.
I'll update this issue once a fix is available, until then please consider using an older version of VS Code to be able to debug

**Comment by ramya-rao-a** [comment]
It looks like the [latest Insiders](https://code.visualstudio.com/insiders) should have the fix to this issue.
Can anyone here try it out and confirm?

**Comment by reiki33** [comment]
It works for Go after installing the Go plugin.

Is the following an issue?
[root@reikinet visualstudiocode]# dnf install
code-insiders-1.40.0-1571377603.el7.x86_64.rpm
Repository for Ozon OS                          0.0  B/s |   0  B     00:10

Error: Failed to download metadata for repo 'ozonos': Cannot download
repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: ozonos
Last metadata expiration check: 0:48:49 ago on Sun 20 Oct 2019 09:42:02 AM
PDT.
Dependencies resolved.

Mark

**Comment by dtibljas12** [comment]
> It looks like the [latest VS Code Insiders](https://code.visualstudio.com/insiders) should have the fix to this issue.
> Can anyone here try it out and confirm?

Can confirm that insiders works fine with python.

**Comment by ramya-rao-a** [comment]
Thanks @dtibljas12
