### ISSUE TITLE
VS Module support is really bad

### ISSUE THREAD

**Issue by pradeepkusingh** [microsoft/vscode-go#2832]
I am noticing too many issues with Module and VS
1- Fix preview not available for errors.. takes lot of time to appear.
2- Auto imports bad and taking hell lot of time compare to non module apps.
3- Error is appearing/mark very late.
4- Suggestion pop up is useless..example struct, I try to populate struct field and it doesn't appear unless I type more than 5 char.
5- I have gopls, go lang server enable, autoimport enanbled.
6- noticed another issue where when I tried to same file, VS keep importing saem package 4 to 5 times, this is NEW. after couple of restart it got fix.

**Comment by stamblerre** [comment]
Please share your VSCode settings (they can be found by opening the Command Palette (Ctrl + Shift + P) and selecting `Preferences: Open Settings (JSON)`. What version of `gopls` are you using (`gopls version`)?

**Comment by pradeepkusingh** [comment]
{
  
    "go.autocompleteUnimportedPackages": true,
    "go.inferGopath": true,
    "go.useCodeSnippetsOnMethodSuggest" : true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "gitlens.advanced.messages": {
        "suppressFileNotUnderSourceControlWarning": true
    },
    "go.formatTool": "goimports",
    "aws.samcli.location": "/usr/local/bin/sam",
    "aws.telemetry": false,
    "go.useLanguageServer": true,
    
    "files.autoSave": "afterDelay",
    "go.lintTool":"golangci-lint",
    "go.lintFlags": ["--fast"]
}

**Comment by stamblerre** [comment]
I would suggest configuring your settings as recommended here: https://github.com/golang/tools/blob/master/gopls/doc/vscode.md. Hopefully you will see some improvements with those additional configurations. Please comment if you are still seeing issues after updating your settings.

**Comment by pradeepkusingh** [comment]
I applied all above ad still not getting any suggestions for method signature or for loop,struct.

**Comment by stamblerre** [comment]
@pradeepkusingh: If you encounter any further issues with `gopls`, please open a new issue on the Go issue tracker (https://github.com/golang/go/issues/new).
