### ISSUE TITLE
'${MODULES_USE_COMPAT_VERSION:-0}' can not be resolved because the command has no value.

### ISSUE THREAD

**Issue by dmmilby** [microsoft/vscode-go#2834]
Issue Type: <b>Bug</b>

With a ____.go file open, I click "Debug > Start Daebugging" and expected it to run my code and allow me to debug. Instead, I get the following error:

'${MODULES_USE_COMPAT_VERSION:-0}' can not be resolved because the command has no value.

Extension version: 0.11.7
VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:03.188Z)
OS version: Linux x64 5.2.17-200.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (3.30GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ramya-rao-a** [comment]
This is being tracked in #2831

The problem is upstream with VS Code itself. For now, you can downgrade to an older version where this issue does not occur.
