### ISSUE TITLE
Clear output doesn't clear output buffer, it just pretends by only clearing the output screen

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode-go#2835]
vscode: 1.39.1
extension: 0.11.7

Step 1) Click run test

![image](https://user-images.githubusercontent.com/863731/66951578-fc2c5f00-f05a-11e9-8172-cebe9a7559eb.png)

Step 2)

![image](https://user-images.githubusercontent.com/863731/66951337-6b558380-f05a-11e9-9b3a-79b7d3288731.png)

Step 3) Clear output 

![image](https://user-images.githubusercontent.com/863731/66951356-75778200-f05a-11e9-8451-0fcf4ba1a071.png)

Step 4) Repeat steps above until the output buffer gets so large it freezes vscode despite clearing it every time.

**Comment by ramya-rao-a** [comment]
This is an interesting catch...

The clear button in Step 4 is implemented by VS Code itself, and the extension has no control over this.
Please log this issue in the VS Code repo.

If it is determined that the extension is not using the output panel the right way, then we can look into fixing that.

Also, please note that when logging the issue in the vscode repo, its beneficial if you can provide a code snippet that the team can use to replicate the issue.

**Comment by gertcuykens** [comment]
Any run test output will do, for example

```
func ExampleUnmarshal() {
	m := make(map[string]interface{})
	if err := json.Unmarshal([]byte(`{"test":1}`), &m); err != nil {
		fmt.Println(err)
	}
	fmt.Println(m["test"])
	// Output:
	// 2
}
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting the issue upstream.
Closing this issue in favor of https://github.com/microsoft/vscode/issues/82750

If it is determined there that the fix should be in the extension, then I'll re-open this one
