### ISSUE TITLE
Reconsider default of go.installDependenciesWhenBuilding

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-go#2836]
Do any Go tools we use still depend on installed packages, that is `go build -i`? If the answer is no, then as AFAIK installing dependencies is just a waste of time and space at that point and we should consider changing the default of `go.installDependenciesWhenBuilding` to `false`.

I think it's a mechanism left for backwards compatibility for stuff that depended on it, from the Go 1.10 release notes:
> Installing dependency packages should not be necessary in general, and the very concept of installed packages may disappear in a future release. 

&mdash; https://golang.org/doc/go1.10#build

**Comment by ramya-rao-a** [comment]
I am not an expert on the `go build` command and would like to loop in a few more people into this discussion.

Looping in @mattetti who made the initial PR #718 to add the `-i` flag to the `go build` command
Looping in @ardan-bkennedy who I know via #1064 uses the `-i` flag
Looping in @stamblerre who I hope can loop in someone working on the go command itself

**Comment by mattetti** [comment]
> The old advice to add the -i flag for speed, as in go build -i or go test -i, is no longer necessary: builds run just as fast without -i. For more details, see [go help cache](https://golang.org/cmd/go/#hdr-Build_and_test_caching).

It's quite clear that this flag isn't needed and might indeed slow things down. Thanks @segevfiner

**Comment by jayconrod** [comment]
Assuming nothing actually depends on .a files being installed into `$GOPATH/pkg`, I don't think this flag is necessary anymore.

In GOPATH mode, there may be some performance cost to using `-i`, since it will be copying .a files out of the cache into `$GOPATH/pkg`.

In module mode, I don't think `-i` has any effect, since we don't install .a files.

**Comment by ramya-rao-a** [comment]
So, we are leaning towards not using `-i` regardless of whether one is using modules or not, correct?

**Comment by segevfiner** [comment]
Seems like it...? I think the only thing we need to make sure is that we don't use some tool that otherwise depends on `$GOPATH/pkg` and didn't learn to rely on the Go build cache instead.

**Comment by segevfiner** [comment]
Looks like github.com/mdempsky/gocode (non-modules) still relies on "go/pkg" installed packages as it doesn't show any completion for me when I disable `go.installDependenciesWhenBuilding`.

**Comment by ramya-rao-a** [comment]
Thanks @segevfiner 

People not using modules or the language server still end up using github.com/mdempsky/gocode, so we will keep this default value as is for now.
