### ISSUE TITLE
Add fill selected struct fields feature

### ISSUE THREAD

**Issue by pigletfly** [microsoft/vscode-go#2838]
vscode-go now supports fill all the struct fields,sometimes we just want to fill selected fields.

**Comment by ramya-rao-a** [comment]
We use the [fillstruct](https://github.com/davidrjenni/reftools/tree/master/cmd/fillstruct) tool to provide this feature.

As far as I know, this tool works on the entire struct and individual fields cannot be targeted. Therefore, we cannot support only selected fields
