### ISSUE TITLE
Switch from oracle to guru

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode-go#284]
Alan Donovan has [renamed oracle to guru](https://groups.google.com/forum/#!msg/golang-dev/trpStscxjKQ/ujuxvypIAgAJ) where (incompatible) progress is finally being made on the tool. Progress is being tracked [here](https://docs.google.com/document/d/1UErU12vR7jTedYvKHVNRzGPmXqdMASZ6PfE7B-p6sIg/edit#heading=h.t5rbcuy7di7j) and the new tool page is [here](https://godoc.org/golang.org/x/tools/cmd/guru).

I think we should get ahead of this by immediately switching to use guru and abandoning oracle since:

1. It's very slow for large projects in common use cases
2. It's now deprecated

@lukehoban, I noticed you just [switched to oracle](https://github.com/Microsoft/vscode-go/commit/509d6abbe360319596d44eeebfb7917832d89dbb) for the find references implementation, so this is probably very fresh on your mind. Would you be willing to change to `guru`? I haven't yet had a chance to investigate any changes in the CLI or API which might require work in vscode beyond executing the new binary.

**Comment by ironcladlou** [comment]
Turned out the change was easier than I thought it would be. Opened https://github.com/Microsoft/vscode-go/pull/285.

**Comment by lukehoban** [comment]
I hadn't seen the news about the change to the new name - definitely makes sense to use `guru` going forward.

FWIW - Tried this out for `referrers` just now, and CPU time on a large workspace was 75% of `oracle` with 50% the max memory usage, so seems there have already been non-trivial performance improvements.
