### ISSUE TITLE
panic when debug test, no panic when run test

### ISSUE THREAD

**Issue by LuChuanBing** [microsoft/vscode-go#2842]
Steps to Reproduce:

1. create a test file named Sample_test.go , with the following cod in it:
```

func Test1(t *testing.T) {
	if !myFn("dkwahdiowa_", 0) {
		t.FailNow()
	}
}

func myFn(s string, i int) bool {
	i++
	if s[i] == '_' {
		return true
	}
	return myFn(s, i)
}
```
2. click debug test in vscode
3. step into/over to execute
4. panic hanppend when calling myFn in itself
5. debug console logs below messages:
```
runtime.throw(0x59af66, 0x5)
	/usr/lib/go/src/runtime/panic.go:774 +0x72 fp=0xc00003c688 sp=0xc00003c658 pc=0x431cd2
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:401 +0x1e2 fp=0xc00003c6c0 sp=0xc00003c688 pc=0x446652
gitee.com/luchuanbing/leetcode/0010%2eisMatch.myFn(0x59c056, 0xb, 0x1, 0xfd89f9a5)
	/home/chuanbing/code/leetcode/0010.isMatch/isMatch_test.go:40 +0x9b fp=0xc00003c6c8 sp=0xc00003c6c0 pc=0x547cfb
gitee.com/luchuanbing/leetcode/0010%2eisMatch.myFn(0x59c056, 0xb, 0x1, 0x430800)
	/home/chuanbing/code/leetcode/0010.isMatch/isMatch_test.go:45 +0x7d fp=0xc00003c700 sp=0xc00003c6c8 pc=0x547cdd
gitee.com/luchuanbing/leetcode/0010%2eisMatch.Test1(0xc0000b2100)
	/home/chuanbing/code/leetcode/0010.isMatch/isMatch_test.go:35 +0x3f fp=0xc00003c740 sp=0xc00003c700 pc=0x547c1f
testing.tRunner(0xc0000b2100, 0x5a43f8)
	/usr/lib/go/src/testing/testing.go:909 +0x13c fp=0xc00003c7d0 sp=0xc00003c740 pc=0x4f26dc
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00003c7d8 sp=0xc00003c7d0 pc=0x461d11
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:960 +0x64f

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000b2100, 0x59af25, 0x5, 0x5a43f8, 0x5da98200)
	/usr/lib/go/src/testing/testing.go:961 +0x67d
testing.runTests.func1(0xc0000b2000)
	/usr/lib/go/src/testing/testing.go:1202 +0xdc
testing.tRunner(0xc0000b2000, 0xc00004bc60)
	/usr/lib/go/src/testing/testing.go:909 +0x13c
testing.runTests(0xc00000c060, 0x68d6e0, 0x2, 0x2, 0x7fb02a460100)
	/usr/lib/go/src/testing/testing.go:1200 +0x39a
testing.(*M).Run(0xc0000a0000, 0x0)
	/usr/lib/go/src/testing/testing.go:1117 +0x454
main.main()
	_testmain.go:46 +0xc1
```

**Comment by ramya-rao-a** [comment]
I am able to debug the test without any issues.

![debug](https://user-images.githubusercontent.com/16890566/67161939-19d81d80-f314-11e9-91ca-6c8b9d76f882.gif)

Please try debugging the test using delve directly from the terminal to see if that works.

**Comment by LuChuanBing** [comment]
@ramya-rao-a thanks for your help, it had been stuck when I try to step in/over  
![2019-10-28_10-54](https://user-images.githubusercontent.com/4416199/67648786-a799b580-f971-11e9-800c-a991c29aa4a1.png)

![Peek 2019-10-28 10-38](https://user-images.githubusercontent.com/4416199/67648794-aec0c380-f971-11e9-87e0-0ca01ade7b34.gif)

**Comment by ramya-rao-a** [comment]
Is it stuck event when using delve directly in the terminal?

**Comment by LuChuanBing** [comment]
yes, as you can see from the first picture, I set a breakpoint on main.go:14 where myFn call itself , and run to it,
after this, I entered n, but it was struck ,and no response returned.
Maybe it's an issuse of delve

**Comment by LuChuanBing** [comment]
Hi @ramya-rao-a , I just trid it ,and  there is no issue running on windows or ubuntu
It just not work on my system , because I am using 5.3.6-1-MANJARO

Again thank you sincerely
