### ISSUE TITLE
comment out ill code but not delete it

### ISSUE THREAD

**Issue by Yahasana** [microsoft/vscode-go#2843]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1. 
```go
package main

import (
	"fmt"  // no use import will be deleted after saving
)

func main() {
	// fmt.Printf("Hello vs-go")
}
```
2. save and "fmt" is deleted

expect:
```go
import (
	// "fmt"  // comment it out but not delete
)
```
it's hard to key in this code and i don't like it gone silently when i save. it' look like `vs-go` eats it

**Comment by ramya-rao-a** [comment]
The unused imports are removed by the formatting tool which is run when you save the file.
Please read the `Why do my imported packages keep getting removed or re-ordered?` section in the [FAQ](https://github.com/microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting) for ways of getting around this.
