### ISSUE TITLE
could not import "C"

### ISSUE THREAD

**Issue by dingrui37** [microsoft/vscode-go#2849]
![image](https://user-images.githubusercontent.com/22718365/67203908-e514b500-f43e-11e9-9c6b-3dc21b1fa349.png)

![image](https://user-images.githubusercontent.com/22718365/67203939-f8278500-f43e-11e9-92f4-a38b776e2e10.png)

**Comment by cbluth** [comment]
i am having the same issue, as reported here: https://github.com/microsoft/vscode/issues/83532

Here is copypasta from that issue:
---
The Issue:
```
could not import C (no package data for import path C) LSP
```

![image](https://user-images.githubusercontent.com/6709636/67765922-9625db80-fa4d-11e9-8356-97a6bbe767c5.png)


vscode is failing to import the "C" module when it is apart of a local module.
all tooltips then stop working.


- VSCode Version:
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.0-19-generic
```
- OS Version:
```
user@linux:~$ uname -a
Linux linux 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
user@linux:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
user@linux:~$ 
```

Steps to Reproduce:

1. extract attached file `example-project.zip` [example-project.zip](https://github.com/microsoft/vscode/files/3783446/example-project.zip)
2. run `./build.sh` (please read it first)


Does this issue occur when all extensions are disabled?:
`No`, but then it doesnt recognize any golang code.

**Comment by cbluth** [comment]
i have just tried downgrading to `v1.12` and it still has the same issue.

**Comment by cbluth** [comment]
@dingrui37 
your screenshot is not very clear, is your issue in a vendor'ed module, or a local module? or is it in the `main` module of the project?
i can only reproduce the issue if it is in a module, if its in the `main`, then it is working fine for me.

**Comment by stamblerre** [comment]
`gopls` does not yet support cgo. You can track updates here: https://github.com/golang/go/issues/32898.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @dingrui37 and @cbluth 

Closing in favor of the upstream issue
