### ISSUE TITLE
Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED

### ISSUE THREAD

**Issue by yuwenlong** [microsoft/vscode-go#2857]
https://github.com/uudashr/gopkgs/cmd/gopkgs
The link will open and report 404.

Installing 18 tools at /data/app/go/bin
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gotests
  gomodifytags
  impl
  fillstruct
  goplay
  godoctor
  dlv
  gocode-gomod
  gogetdoc
  goreturns
  golint
  gopls

Installing github.com/mdempsky/gocode SUCCEEDED
Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/cweill/gotests/... SUCCEEDED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/josharian/impl SUCCEEDED
Installing github.com/davidrjenni/reftools/cmd/fillstruct SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
Installing github.com/godoctor/godoctor SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv SUCCEEDED
Installing github.com/stamblerre/gocode SUCCEEDED
Installing github.com/zmb3/gogetdoc SUCCEEDED
Installing github.com/sqs/goreturns SUCCEEDED
Installing golang.org/x/lint/golint SUCCEEDED
Installing golang.org/x/tools/gopls SUCCEEDED

1 tools failed to install.

gopkgs:
Error: Command failed: /usr/local/go/bin/go get -v github.com/uudashr/gopkgs/cmd/gopkgs
go: finding github.com/uudashr/gopkgs/cmd/gopkgs latest
go get: github.com/uudashr/gopkgs/cmd/gopkgs@v0.0.0-20191022034909-9ad6b82ad5c3 requires
	github.com/uudashr/gopkgs/v2@v2.0.3: reading github.com/uudashr/gopkgs/go.mod at revision v2.0.3: unknown revision v2.0.3
go: finding github.com/uudashr/gopkgs/cmd/gopkgs latest
go get: github.com/uudashr/gopkgs/cmd/gopkgs@v0.0.0-20191022034909-9ad6b82ad5c3 requires
	github.com/uudashr/gopkgs/v2@v2.0.3: reading github.com/uudashr/gopkgs/go.mod at revision v2.0.3: unknown revision v2.0.3

**Comment by MooseTheory** [comment]
I am also seeing this same error using VS Code 1.39.2, Windows 10.0.18362, WSL (Ubuntu 18.04.2 LTS) and go1.13.3 linux/amd64.
If I run the '/usr/local/go/bin/go get -v github.com/uudashr/gopkgs/cmd/gopkgs' command from a terminal, it seems to complete successfully, and I can run gopkgs from there, but it still does not seem to be available inside VS Code.

**Comment by stamblerre** [comment]
This is an issue with with the upstream repo: https://github.com/uudashr/gopkgs/issues/22.

**Comment by nezorflame** [comment]
As a temporary workaround, you could install the older version of it manually, like go get github.com/uudashr/gopkgs/cmd/gopkgs@v2.0.1

**Comment by yuwenlong** [comment]
This is the command that vscode automatically executes when it executes the Go Install/Update tool.
@nezorflame

**Comment by nezorflame** [comment]
I know it does, but if you manually get the package, at least it'd work for the new installments.
As for the updating it - yeah, we need @uudashr to merge the https://github.com/uudashr/gopkgs/pull/21 and (ideally) to release `cmd/gopkgs/v1.0.0` and maintain proper release versioning.

**Comment by wtask** [comment]
Try first to delete pkg sources under GOPATH, then reinstall pkg from vscode.

**Comment by uudashr** [comment]
Please try it again. Just fix some and test on my end and it works.

**Comment by nezorflame** [comment]
It works, but the version is currently not the latest one. We are continuing investigation in the linked issue.
