### ISSUE TITLE
delve: attaching to pid results into unpredictable display behavior

### ISSUE THREAD

**Issue by hhrutter** [microsoft/vscode-go#2865]
Attaching to an already running process or remote debugging using a headless dlv instance
results in unpredictable behavior on hitting breakpoints.

Sometimes local and global vars are displayed, sometimes neither local nor global vars
are displayed and on many occasions global vars are displayed and a running gear next to local vars keeps showing forever.

Sometimes hiding and showing the Variables pane helps and the vars show up suddenly
indicating some kind of refresh problem.

**VSCode settings**
```{
    "workbench.editor.tabSizing": "shrink",
    "files.autoSave": "off",  
    "workbench.sideBar.location": "right",
    "workbench.editor.openSideBySideDirection": "down",
    "window.zoomLevel": 1,
    "editor.minimap.enabled": false,
    "git.enableSmartCommit": true,
    "window.openFilesInNewWindow": "off",
    "window.restoreWindows": "all",
    "window.nativeTabs": true,
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": false,
    "editor.tabCompletion": true,
    "gitlens.advanced.messages": {
      "suppressCommitHasNoPreviousCommitWarning": false,
      "suppressCommitNotFoundWarning": false,
      "suppressFileNotUnderSourceControlWarning": false,
      "suppressGitVersionWarning": false,
      "suppressLineUncommittedWarning": true,
      "suppressNoRepositoryWarning": false,
      "suppressResultsExplorerNotice": false,
      "suppressShowKeyBindingsNotice": true,
      "suppressUpdateNotice": true,
      "suppressWelcomeNotice": true
    },
    "go.liveErrors": {
      "enabled": true,
      "delay": 500
    },
    "go.testTimeout": "60s",
    "go.formatTool": "goimports",
    "go.autocompleteUnimportedPackages": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "workbench.startupEditor": "newUntitledFile",
    "gitlens.keymap": "none",
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "git.enableCommitSigning": true,
    "gitlens.historyExplorer.enabled": true,
    "terminal.external.osxExec": "iTerm.app",
    "editor.multiCursorModifier": "alt",
    "diffEditor.ignoreTrimWhitespace": true,
    "diffEditor.renderSideBySide": true,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true,
    "printcode.disableTelemetry": true,
    "workbench.colorTheme": "Argon (Editor & Workbench)",
    "breadcrumbs.enabled": true,
    "vsicons.dontShowNewVersionMessage": true,
    "go.useLanguageServer": false,
  }
```

**Expected behavior**
During debugging I want to see reliably local andglobal vars.

**System information:**
 - OS: MacOS 10.14.6
 - Extension Version 0.11.7
 - VS Code Version 1.39.2]

**Additional context**
```
dlv version
Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 $

go version
go version go1.13.1 darwin/amd64
```

**Comment by vishal-wadhwa** [comment]
I recently encountered this very issue. I am connecting to a headless delve instance running inside docker.
The variables pane is completely empty. The call stack is still there. I can see the variable values if I set a watch.

The log output (`"trace": "log"`) in the debug console is showing a json of all the locals. So, the response is being returned. Its just that none of it is being displayed in the Variables window pane.

**Comment by hhrutter** [comment]
I observe smth different with `"trace":"log"`
In my case the debugger pane usually shows the global vars and a busy gear next to an empty local vars section. This is the corresponding log output indicating we are still waiting for the json response containing the local vars:

```
VariablesRequest
VariablesRequest
VariablesResponse [
 {
  "name": "foo",
  "value": "bar",
  "variablesReference": 0
 }
```

**Comment by cpoole** [comment]
I have this same issue. I am running delve in docker and 95% of the time the panes are totally empty. But 5% of the time after hiding or just random clicking they will display. 

Similar to hhrutter I see all of the variables in the json `VariablesResponse`

my launch.json:

```        
{
            "name": "Remote Debug",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "host":"127.0.0.1",
            "port": 48345,
            "remotePath": "/src/api/foo",
            "program": "${workspaceRoot}/foo",
            "showLog": false,
            "logOutput": "rpc",
            "trace": "log"
        }
```
```
dlv version
Delve Debugger
Version: 1.3.0
Build: $Id: 2f59bfc686d60989dcef9de40b480d0a34aa2fa5 $
```
I have basically stock global vscode settings for golang

**Comment by stamblerre** [comment]
Thank you for these reports. I'm sorry we haven't made progress on investigating them. I filed https://github.com/golang/vscode-go/issues/184 in our new repository, as we are migrating (https://github.com/microsoft/vscode-go/issues/3247). Please follow along on this new issue.
