### ISSUE TITLE
I get formatting even if turned off in settings

### ISSUE THREAD

**Issue by hedefalk** [microsoft/vscode-go#2868]
**Describe the bug**
Formats on save no matter settings

**VSCode settings**
```json
"[go]": {
    "editor.insertSpaces": false,
    "editor.formatOnSave": false
  },
```

**Expected behavior**
Expected no formatting

**System information:**
 - OS: OSX Catalina
 - Extension Version 0.11.7
 - VS Code Version 1.39.2

**Additional context**
Verified that this plugin is to blame by toggling enable/disable. Tried disabling in user/workspace/folder but no matter what I get formatting.

Previous issue suggested uninstalling this plugin and re-installing again but that doesn't help either. #2307

**Comment by hedefalk** [comment]
I've run a bisect with versions and this bug was introduced between 0.10.1 and 0.10.2. Currently workaround by running 0.10.1 to be able to save without formatting on a legacy code base…

![image](https://user-images.githubusercontent.com/116520/67777919-bf049b80-fa62-11e9-8513-550b8e3248b6.png)

**Comment by hedefalk** [comment]
Really strange because I can't see anything obvious here: https://github.com/microsoft/vscode-go/compare/0.10.1...0.10.2

However, I've really nailed it down to 0.10.2. Previous to that, my settings of not doing formatting are honoured, but anything later than that and I get formatting on save no matter what.

**Comment by stamblerre** [comment]
Are you using the language server or are the VSCode settings above the only thing in your settings.json file?

**Comment by hedefalk** [comment]
Doesn't seem to matter if I use lang server or not.

**Comment by stamblerre** [comment]
Ok, so then it sounds like an actual bug in the VSCode extension. Looks like you will want to add the following to your settings:

```json5
"editor.codeActionsOnSave": {	
    "source.organizeImports": false	
}
```

**Comment by ramya-rao-a** [comment]
@hedefalk When using the language server, please add what @stamblerre suggested above and let us know if that helps

**Comment by hedefalk** [comment]
@ramya-rao-a Error persists without the language server.  `"source.organizeImports": false` makes no difference.

```
		"go.useLanguageServer": true,
		"editor.insertSpaces": false,
		"editor.formatOnSave": false,
		"editor.codeActionsOnSave": {	
			"source.organizeImports": false	
		}
```

Still formats. Also, still formats without language server so it's not that one.

**Comment by stamblerre** [comment]
Just to confirm, are you restarting the VSCode window when you change a setting? That may be necessary for the setting to take effect.

**Comment by hedefalk** [comment]
yes, if by restart we agree that reload is good enough.

**Comment by ramya-rao-a** [comment]
@hedefalk If you are seeing the formatOnSave setting being ignored even when not using the language server, then I suspect that one of your other extensions might be the culprit.

Can you disable all your extensions other than Go and retry?

**Comment by hedefalk** [comment]
I currently have 44 enabled plugins and I'm not in the position to disable them all right now. I'm pretty sure this plugin is the culprit though. If I disable it or downgrade it to 0.10.1, the unwanted formatting disappears. Do you suggest that there is some kind of interaction of another non-go plugin (I have no other plugins related to Go) that for some reason sends an event that makes this plugin format?

**Comment by ramya-rao-a** [comment]
The only [change](https://github.com/microsoft/vscode-go/commit/778b770930b143a37024ef3f925dca877bca8427) between 0.10.1 and 0.10.2 related to formatting is the one where the below settings were made default

```
"[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
          "source.organizeImports": true
        }
      }
```

You can look at rest of the commits [here](https://github.com/microsoft/vscode-go/commits/0.10.2).


I noticed the settings you shared in https://github.com/microsoft/vscode-go/issues/2868#issuecomment-549246023. I wonder if the problem is due to your changes not being specific to `go` and the `go` specific settings above not getting overridden due to that

Can you try adding the below?

```
"[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
          "source.organizeImports": false
        }
      }
```

**Comment by EliasCK** [comment]
I'm also experiencing this issue.

![image](https://user-images.githubusercontent.com/11874914/68212470-dc44e700-ffd9-11e9-835b-7bd9c8be6487.png)

No way to turn it off, I'm literally using Notepad right now lol.

**Comment by hedefalk** [comment]
>I wonder if the problem is due to your changes not being specific to go and the go specific settings above not getting overridden due to that

@ramya-rao-a that seems to be it! Finally got rid of it!
