### ISSUE TITLE
[GO] Auto complete randomly stops

### ISSUE THREAD

**Issue by steelx** [microsoft/vscode-go#2869]
Issue Type: <b>Bug</b>

Autocomplete and IntelliSense doesn't work for GO file. It used to work fine earlier.

Even auto-import doesn't work, though it imports after the file is saved after about 1-2 seconds.

Extension version: 0.11.7
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by stamblerre** [comment]
Can you share your VSCode settings (`Ctrl + Shift + P -> Preferences: Open Settings (JSON)`). Are you using the Go language server?

**Comment by ramya-rao-a** [comment]
@steelx Please share your Go related settings as suggested by @stamblerre above

**Comment by naivefun** [comment]
Typescript the same. Newly created types/files randomly never appear in type list until restart the IDE. Really drive me crazy.

**Comment by ramya-rao-a** [comment]
@naivefun Typescript features are driven out of the box in VS Code, please log an issue at https://github.com/microsoft/vscode
