### ISSUE TITLE
Add `go install` and `go build` commands

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode-go#287]
Requirement extracted from discussion at https://github.com/Microsoft/vscode-go/pull/134#issuecomment-200588242. Also covered previously in https://github.com/Microsoft/vscode-go/issues/21.

> I think it does make sense to go ahead with adding a Go: Install command to the extension whcih behaves similarly to the existing Go: Run tests commands.
> 
> I think it's okay for this to be fully separate from the diagnostic reporting and build-on-save.
> 
> The one place they should overlap is in reusing the go.buildFlags settings.
> 
> The big question is how to scope this. I can imagine either:
> 
> Run go install ./... in ${workspaceRoot}
> Run go install in the directory of the currently opened file
> For advanced uses, I'm okay with saying that folks should use VS Code Tasks. So I think this should try to cover the most common 80% for folks who don't want/need to set up the task.

**Comment by vastbinderj** [comment]
Why not mirror this functionality from the [golang team plugin for sublime](https://github.com/golang/sublime-build)?

**Comment by lukehoban** [comment]
@vastbinderj Sounds like a good idea.

**Comment by Mparaiso** [comment]
How about adding a new default task runner for Go ? when I execute the build command and I don't have tasks configured there is a menu that displays an number of task runners, why not add a default task runner for Go in that list ? Or can the plugin install a new default task runner ?

**Comment by sharno** [comment]
Also "go run" is being ignored in this issue, it's so useful while developing scripts to test them on the fly. I'd appreciate adding it so much.

**Comment by ramya-rao-a** [comment]
The below commands have been added and will be available in the next update
- `Go: Install Current Package`
- `Go: Build Current Package`
- `Go: Build Workspace`

**Comment by Mparaiso** [comment]
thank you

**Comment by ramya-rao-a** [comment]
Can folks here help me with testing this and give feedback before I release the next update later this week? All you have to do is: 

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code-insiders --install-extension Go-latest.vsix` and reload VS Code

**Comment by ramya-rao-a** [comment]
The below commands are now available in the latest update to the Go extension (0.6.69)
- `Go: Install Current Package`
- `Go: Build Current Package`
- `Go: Build Workspace`
