### ISSUE TITLE
Auto convert 4 spaces to Tab when press CTRL + S

### ISSUE THREAD

**Issue by dingrui37** [microsoft/vscode-go#2871]
When I write golang code with vscode,  I want to use formatOnSave feature, but I don't want to convert tabs automatically. If I  press CTRL + S, it will convert 4 spaces to tab. I used Google to find many related problems. My solution is as follows:
1. Modify go format source code in order to use 4 spaces instead of tab
`/usr/local/go/src/go/format/format.go`
![image](https://user-images.githubusercontent.com/22718365/67842319-e1ff8000-fb34-11e9-9d2f-e715e6528113.png)
2. Modify goimports source code which I choosed as my format tool
![image](https://user-images.githubusercontent.com/22718365/67842922-0c9e0880-fb36-11e9-9fdc-62d78a0c1edc.png)

![image](https://user-images.githubusercontent.com/22718365/67843075-440cb500-fb36-11e9-8105-91b724ecc399.png)

3. Reinstall goimports and test
![image](https://user-images.githubusercontent.com/22718365/67843267-9ea61100-fb36-11e9-874c-359e30ab7fb5.png)

4. CTRL + S test
Before press CTRL + S,  I use sed to convert tab to 4 spaces,
![image](https://user-images.githubusercontent.com/22718365/67843369-ceedaf80-fb36-11e9-8b0e-f3284b4eaf60.png)
 Then press CTRL + S:
![image](https://user-images.githubusercontent.com/22718365/67843564-2ee45600-fb37-11e9-898e-5bfc7bbf01f1.png)

Unfortunately, it doesn't work, ｗho knows what the problem is?　I've tried other languages, for example C, but it don't convert automatically when I save code.

**Comment by ramya-rao-a** [comment]
- In Step 3, how are you re-installing `goimports`? Are you using the `go install` command from the terminal or using the extensions `Go: Install/Update Tools` command?
- Your approach seems to be to change the source code of `goimports`. I would suggest to test your change by running `goimports` in the terminal first before trying it in VS Code.

**Comment by dingrui37** [comment]
Yes, I have reinstalled `goimports`  ,  and the picture in step3 is the result of using goimports manually.

**Comment by ramya-rao-a** [comment]
Try the command `Convert indentation to Spaces` and see if that helps?

**Comment by simonchan2013** [comment]
I have the same issue. When I save *.go file, it will convert space to tab. How can I disable this feature? Thanks

**Comment by ramya-rao-a** [comment]
@simonchan2013 You can disable the format on save feature by adding the below to your settings
```
"["go"]: {
   "editor.formatOnSave": false
}
```

**Comment by simonchan2013** [comment]
![image](https://user-images.githubusercontent.com/5954048/68558026-ba80af80-0472-11ea-8762-d0bfbf3c0c91.png)
I have added this item. But it does not work

**Comment by ramya-rao-a** [comment]
@simonchan2013 Can you share all the go related settings you have?

**Comment by simonchan2013** [comment]
> @simonchan2013 Can you share all the go related settings you have?

the code below is all the go related settings
````
"[go]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4,
        "editor.formatOnSave": false
},
"go.useLanguageServer": true,
 "go.toolsEnvVars": {
        "GO111MODULE": "on",
        "GOPROXY": "https://goproxy.io",
},
"go.docsTool": "gogetdoc",
"go.lintOnSave": "off"
````

and my go version is: go version go1.13.1 darwin/amd64

**Comment by zmb3** [comment]
I feel obliged to share that fighting with`gofmt` is not something I'd personally recommend.  One of the great things about working with Go code is that is all looks the same.  Have you considered just leaving format on save enabled and letting the formatter [do its thing](https://blog.golang.org/go-fmt-your-code)?

**Comment by ramya-rao-a** [comment]
I agree with @zmb3 

@simonchan2013 Since you are using the language server, the act of organizing imports might be changing things around. Can you try updating the go specific setting as below to disable that feature as well
```
"[go]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4,
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false
         },
}
```

**Comment by simonchan2013** [comment]
@ramya-rao-a This wil disable all feature of goimports

**Comment by ramya-rao-a** [comment]
@simonchan2013 Like @zmb3 is saying the Go tooling follows certain rules regarding tabs and spacing that are not really configurable. So, if you don't prefer the default behavior, the only solution I can think of is to not use any features from such tools.
