### ISSUE TITLE
Error: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by lexxish** [microsoft/vscode-go#2872]
**Describe the bug**
"Error: Error: spawn UNKNOWN" when opening vscode and go to declaration doesn't do anything.

**VSCode settings**
`Preferences: Open Settings (JSON)`
```json
{
    "editor.formatOnSave": true,
    "window.zoomLevel": 1,
    "go.gopath": "C:\\Users\\User\\code",
    "go.formatTool": "goimports",
    "go.formatFlags": [
        "-w"
    ],
    "go.docsTool": "guru",
    // "editor.autoClosingBrackets": "never",
    // "editor.autoClosingQuotes": "never",
    //"workbench.colorTheme": "GitHub Clean White",
    "go.lintTool": "golangci-lint",
    "go.lintFlags": [
        "--enable-all",
        "-Dgoimports",
        "-Dgofmt"
    ],
    "go.lintOnSave": "file"
}
```

**To Reproduce**
1. Install Visual Studio Code
2. Install GoLang plugin
3. Set user system env variable GOPATH to %USERPROFILE%\code
4. Restart VSCode
5. Open a GoLang Project
6. See error in bottom right tooltip popup (and go to declaration doesn't work).

**Expected behavior**
No error and go to declaration should work.

**System information:**
 - OS: Windows 10 Enterprise x64
 - Extension Version 11.7
 - VS Code Version 1.39.2

**Additional context**
```
[2019-10-29 08:43:11.739] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-10-29 08:43:11.739] [exthost] [error] Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:358:11)
	at spawn (child_process.js:543:9)
	at Object.execFile (child_process.js:226:15)
	at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:179:31)
	at Promise (c:\Users\User\.vscode\extensions\ms-vscode.go-0.11.7\out\src\goOutline.js:48:16)
	at new Promise (<anonymous>)
	at runGoOutline (c:\Users\User\.vscode\extensions\ms-vscode.go-0.11.7\out\src\goOutline.js:34:12)
```

**Comment by ramya-rao-a** [comment]
Apologies for the delay in response.

- Do you still see this issue?
- Are you on the latest version of VS Code and the Go extension?

**Comment by ramya-rao-a** [comment]
@roblourens A web search on this error message points to the child process spawn() not being able to find node. A similar error is noted in https://github.com/microsoft/vscode/issues/74197

From the stack trace, it looks like electron is involved here as well. Any ideas on what the next steps can be here?

**Comment by lexxish** [comment]
No, it turned out be being blocked by app locker
