### ISSUE TITLE
Coverage on a single file (via run file tests)

### ISSUE THREAD

**Issue by cristaloleg** [microsoft/vscode-go#2873]
**Is your feature request related to a problem? Please describe.**
When I'm running tests from 1 specific file (via `run file tests` on the top of the file), the coverage isn't calculated.

**Describe the solution you'd like**
`run file tests` should use the same configuration as run single test ( `"go.coverOnSingleTest"` see https://github.com/Microsoft/vscode-go/issues/1637)

**Describe alternatives you've considered**
A new configuration param, probably `"go.coverOnSingleTestFile"`

**Additional context**
Nothing to add.

**Comment by ramya-rao-a** [comment]
We have settings for applying coverage when tests in entire package is run and when a single test is run
- `go.coverOnTestPackage`
- `go.coverOnSingleTest`

PRs are most welcome to add another setting `go.coverOnSingleTestFile` to extend this feature to apply to when tests in the file are run.

Code Pointers:
- [Set a local dev environment of the extension](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- `goTest.ts` is the file where you should start. Look at how the 2 above features are implemented in the `testCurrentPackage` and `runTestAtCursor` functions.
- The function `testCurrentFile` is the function to tweak to add the same feature to testing files

**Comment by ramya-rao-a** [comment]
The latest version of this extension (0.12.0) has this feature now.
Use the setting `go.coverOnSingleTestFile` to enable it.

Thanks to @cristaloleg for reporting and for the PR as well :)

Happy Coding!
