### ISSUE TITLE
Add import doesn't show all package from gopkgs

### ISSUE THREAD

**Issue by imjuanleonard** [microsoft/vscode-go#2874]
**Describe the bug**
Go: Add import doesn't show all package from gopkgs 

**VSCode settings**
`Preferences: Open Settings (JSON)`
```json
{
    "breadcrumbs.enabled": true,
    "window.zoomLevel": 0,
    "window.newWindowDimensions": "maximized",
    "editor.renderWhitespace": "all",
    "terminal.integrated.fontFamily": "Roboto Mono for Powerline",
    "go.useLanguageServer": true,
    "go.formatTool": "goimports",
    "go.gopath": "/Users/imjuanleonard/go",
}
```

gopkgs show that I have testify and many other package but it doesn't show on go import

gopkgs sample result
```
github.com/jhump/protoreflect/internal/testprotos/nopkg
google.golang.org/genproto/googleapis/cloud/scheduler/v1
google.golang.org/genproto/googleapis/cloud/talent/v4beta1
internal/syscall/windows/registry
reflect
github.com/fullstorydev/grpcui/standalone
inbox/vendor/google.golang.org/genproto/googleapis/api/servicecontrol/v1
cmd/go/internal/auth
golang.org/x/text/encoding/charmap
```

**To Reproduce**
1. Go to vscode
2. use Go: Add Imports
3. Package not found

**Expected behavior**
I should be able to import all of the package I have

**System information:**
 - OS: MacOs Mojave 10.14.6
 - Extension Version: 0.11.7
 - VS Code Version 1.39.2

** Question **
How to fix it?

I am also using `gopls` in the package

**Comment by ramya-rao-a** [comment]
Thanks for reporting @imjuanleonard, I have a few questions
- Do you see this only when using modules?
- When you ran `gopkgs` did you use the `-workDir` flag? We use the directory to which the current file belongs as the value for this flag when we call `gopkgs`

**Comment by imjuanleonard** [comment]
oh cool and strange, it is coming now. Maybe there are some kind of cache on my PC. 

Thanks for checking out  ramya closing this issue now :)
