### ISSUE TITLE
Documentation nit: Gometalinter still referenced in Wiki

### ISSUE THREAD

**Issue by jennielees** [microsoft/vscode-go#2875]
`gometalinter` is deprecated as of https://github.com/microsoft/vscode-go/pull/2726 (issue https://github.com/microsoft/vscode-go/issues/2509) but the ["Go tools that the Go extension depends on"](https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on) wiki page, which is linked directly from the extension's installation page, still refers to it at the bottom of the copy-and-paste block.

**Comment by ramya-rao-a** [comment]
Fixed!

Thanks for reporting & Happy Coding!
