### ISSUE TITLE
Support new binary literals

### ISSUE THREAD

**Issue by Nokel81** [microsoft/vscode-go#2879]
**Describe the bug**
The new binary numeric literal syntax is not highlighted as a number from GO 1.13

**To Reproduce**
1. Use either `0b111` or `0B101`or something like that
2. Notice that it is black and not coloured the same as a interger base 10

**Screenshots**
![Screen Shot 2019-11-01 at 10 45 46 AM](https://user-images.githubusercontent.com/8225332/68032783-c4e1c300-fc94-11e9-966f-17e224aa8366.png)
![Screen Shot 2019-11-01 at 10 46 07 AM](https://user-images.githubusercontent.com/8225332/68032813-d0cd8500-fc94-11e9-8354-ba0600b8ad03.png)

**System information:**
 - OS: macos Catalina
 - Extension Version 0.11.7
 - VS Code Version  1.39.2

**Comment by ramya-rao-a** [comment]
This is an upstream issue with the grammar being used. Please see #2735
