### ISSUE TITLE
Investigate replacing gocode with guru for completion

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode-go#288]
One of the new (very exciting) upcoming features of `guru` is context aware completion. From the [guru plan](https://docs.google.com/document/d/1UErU12vR7jTedYvKHVNRzGPmXqdMASZ6PfE7B-p6sIg/edit#):

> complete: do type- and context-aware identifier completion.  I have a pending CL for this and it’s more precise than anything else out there while still being fast, and it’s pretty robust to type errors.  Needs a fair amount of editor integration though.
> [See https://github.com/nsf/gocode/blob/master/docs/autocomplete_formats.md]
> [See https://go-review.googlesource.com/#/c/10318/]

Gocode is the best tool available for completion today, but it has many important problems which [probably won't be resolved any time soon](https://github.com/nsf/gocode/issues/307).

I'm opening this issue to track the progress of guru's completion support and open discussions about whether a switch will make sense.

**Comment by lukehoban** [comment]
As far as I can tell - support for completion in `guru` does not exist yet.  I can't tell if there's any active work on it.  Is there any near term expectation that this will be available?

**Comment by ironcladlou** [comment]
When I was reviewing the pending change set in Gerritt for completion, I think I misinterpreted the activity dates on it... Now it's not clear to me exactly how soon it might be coming. I'll try and reach out to Alan Donovan to get clarification.

**Comment by ironcladlou** [comment]
I reached out to see what the status of that stale Gerrit changeset and offered help (not that I have that much experience to offer with that particular tool).

Do you think there's any value in "tracking issues" like this which discuss/track possible future features for upcoming community tools? I had a thought that if people were generally interested in the idea, it might at least serve as publicity for the tool to drive potential contributors to accelerate its development. Or not! If you think this is just premature/noise in the issue list, please feel free to close it and I'll reopen it later when there's something actionable in vscode-go itself.

**Comment by lukehoban** [comment]
Totally happy to leave this as a tracking issue - just wanted to make sure I was right that there wasn't any near term action we can take on this.

**Comment by ramya-rao-a** [comment]
@ironcladlou Are you aware of any updates in this space?

**Comment by ironcladlou** [comment]
@ramya-rao-a 

Sorry, haven't had time to track this. No hard feelings if you want to close the issue and let me or someone else re-open it when/if interest is renewed.

**Comment by ramya-rao-a** [comment]
@ironcladlou Looks like this was abandoned https://go-review.googlesource.com/#/c/10318/
So will close this.
