### ISSUE TITLE
Allow to disable active debug session warning

### ISSUE THREAD

**Issue by TrueCarry** [microsoft/vscode-go#2880]
**Is your feature request related to a problem? Please describe.**
New feature to show warning when you're saving file that's being debugged is very annoying. https://github.com/microsoft/vscode-go/issues/2559

**Describe the solution you'd like**
Can you please add setting to turn it off?

**Comment by ramya-rao-a** [comment]
Thanks for reporting @TrueCarry 

We can add a button `Don't show again` that will persist your choice and not show the warning again.

PRs are most welcome to do this
Code Pointers:
- [Set up local dev env for the extension](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- The place to make the edits is https://github.com/microsoft/vscode-go/blob/master/src/goMain.ts#L396
- For reference, you can use the [warning we have for using the launch request with remote](https://github.com/microsoft/vscode-go/blob/master/src/goDebugConfiguration.ts#L117-L126) debugging.

**Comment by csmadhav** [comment]
Hey! I would like to work on this!

**Comment by ramya-rao-a** [comment]
The latest version of this extension (0.12.0) has the option on the warning to not show it again.

Thanks to @TrueCarry for reporting and to @csmadhav for the PR :)

Happy Coding!
