### ISSUE TITLE
goimports not adding imports

### ISSUE THREAD

**Issue by onwsk8r** [microsoft/vscode-go#2882]
**Describe the bug**

With `go.formatTool` set to either `goimports` or `goreturns`, imports are not added, but they are rearranged and deleted. This is using `Remote - WSL` and modules, and running the same command from a WSL terminal works as expected.

**VSCode settings**

```json
    "editor.formatOnSave": true,
    "go.coverOnSave": true,
    "go.lintTool": "golangci-lint",
    "go.testOnSave": true,
    "go.autocompleteUnimportedPackages": true,
    "go.gocodeAutoBuild": true,
    "vsicons.dontShowNewVersionMessage": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.formatTool": "goimports"
```

**To Reproduce**

Hop on down to your shell and

```bash
mkdir myproj
cd $_
go mod init github.com/you/myproj
```

Then, in this case, I'm writing like 50 LOC to interact with a non-Azure cloud provider, that's probably the whole issue...

```golang
// main.go
package main // import github.com/me/myproj

import (
	"github.com/aws/aws-sdk-go/aws/session"
)

func main() {
	sess := session.Must(session.NewSession())
	svc := s3.New(sess, &aws.Config{Credentials: creds})
}
```

<kbd>ctrl</kbd> + <kbd>s</kbd> / <kbd>cmd</kbd> + <kbd>s</kbd>

... And no imports are added. But from the terminal, given the same code:

```bash
$ goimports . | tail -n+3 | head -5
import (
        "github.com/aws/aws-sdk-go/aws"
        "github.com/aws/aws-sdk-go/aws/session"
        "github.com/aws/aws-sdk-go/service/s3"
)
```

**BUT**! Given this file:

```golang
package main // import github.com/me/myproj

import (
	"github.com/aws/aws-sdk-go/aws/session"
)

func main() {
sess := session.Must(session.NewSession())
	// svc := s3.New(sess, &aws.Config{Credentials: creds})
}
```

A little <kbd>ctrl</kbd>+<kbd>s</kbd> results in

```golang
package main // import github.com/me/myproj

import (
	"github.com/aws/aws-sdk-go/aws/session"
)

func main() {
	sess := session.Must(session.NewSession())
	svc := s3.New(sess, &aws.Config{Credentials: creds})
}
```

Also, given this file:

```golang
package main // import github.com/me/myproj

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
)

func main() {
	sess := session.Must(session.NewSession())
	// svc := s3.New(sess, &aws.Config{Credentials: creds})
}
```

<kbd>ctrl</kbd>+<kbd>s</kbd> gives us

```golang
package main // import github.com/me/myproj

import (
	"github.com/aws/aws-sdk-go/aws/session"
)

func main() {
	sess := session.Must(session.NewSession())
	// svc := s3.New(sess, &aws.Config{Credentials: creds})
}
```

**Expected behavior**

It is expected that running the tool via VSCode would yield the same results as running it via the command line.

**System information:**
 - OS: Windows + WSL Ubuntu 18.04
 - Extension Version 0.11.7
 - VS Code Version 1.39.2

**Additional context**

Obviously this project uses modules, and this is running Go 1.13.4 ala Gimme (eg, from the `OUTPUT` window: `Finished running tool: /home/brian/.gimme/versions/go1.13.4.src/bin/go build`). The following commands, regardless of whether they are run from the VS Code terminal or elsewhere, work as expected:

```
$ bash -c "cd $PWD && goimports -w ."
$ bash -lc "cd $PWD && goimports -w ."
$ zsh -c "cd $PWD && goimports -w ."
$ zsh -lc "cd $PWD && goimports -w ."
```

As does:

```
$ unset GOROOT GOPATH
$ env | grep GO
$ echo $?
1
$ goimports -w .
```

Goimports is clearly running because it is removing imports and it will add stdlib imports (eg `fmt`), but it seems to be unable to reconcile imports from modules when run via VS Code.

I was looking at https://github.com/microsoft/vscode-go/blob/master/src/goFormat.ts#L69 -

```typescript
const p = cp.spawn(formatCommandBinPath, formatFlags, { env, cwd });
```

And then at https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options and wondering if maybe it should be something like

```typescript
const p = cp.spawn(formatCommandBinPath, formatFlags, {
    env: env,
    cwd: cwd
});
```

**Comment by ramya-rao-a** [comment]
Apologies for the late reply here @onwsk8r and thanks for your patience.

Can you try a project that uses GOPATH, not modules and see if you see similar issues?
I wonder if the problem lies in the `goimports` not able to recognize the modules being used when invoked from the extension.

**Comment by ramya-rao-a** [comment]
And for your observation on `{ env, cwd }` vs `{ env: env, cwd: cwd }`, the former is shorthand for the latter. More on this here: https://alligator.io/js/object-property-shorthand-es6/
