### ISSUE TITLE
go vet errors are swallowed when using multiple build tags

### ISSUE THREAD

**Issue by giniedp** [microsoft/vscode-go#2887]
In our project we use multiple tags to distinguish between different kind of test files, for example:

- `name_unit_test.go`
- `name_integration_test.go`
- `name_mock_test.go`

For us the `go vet` errors are not shown in vscode, for these kind of test files.

**To Reproduce**
1. create a new project with a basic `main.go` file
2. create the VSCode workspace settings like this
```json
{
  "go.vetOnSave": "package",
  "go.vetFlags": [
    "-tags='unit mock'"
  ],
  "go.testOnSave": true,
  "go.testFlags": [
    "-tags='unit mock'"
  ]
}

```

3. add a `my_mock_test.go` file with following content

```go
// +build mock

package main_test

func MyTest(t) {
  // obviously the argument type is missing
}
```

**Expected behavior**
vet errors should show up in vscode.

**Additional info**

Running go vet manually in the terminal shows the expected errors

```
go vet -tags='unit mock' .                                                                                                                                                                   
# testgovet_test [testgovet.test]
./my_mock_test.go:5:13: undefined: t
```

The go output in VSCode does not show any error

```
Starting linting the current package at /Users/alex/repositories/go/src/testgovet
Starting "go vet" under the folder /Users/alex/repositories/go/src/testgovet
/Users/alex/repositories/go/src/testgovet>Finished running tool: /Users/alex/repositories/go/bin/golint

Starting building the current package at /Users/alex/repositories/go/src/testgovet
/Users/alex/repositories/go/src/testgovet>Finished running tool: /usr/local/opt/go/libexec/bin/go vet -tags='unit mock' .

/Users/alex/repositories/go/src/testgovet>Finished running tool: /usr/local/opt/go/libexec/bin/go test -c -i -tags='unit mock' -o /var/folders/k1/wpppkyn91v7239smq8l90flh0000gn/T/vscode-goJndhyV/go-code-check testgovet
```

When using only a single tag in the `vetFlags` and `testFlags`

```diff
{
  "go.vetOnSave": "package",
  "go.vetFlags": [
-   "-tags='unit mock'"
+   "-tags='mock'"
  ],
  "go.testOnSave": true,
  "go.testFlags": [
-   "-tags='unit mock'"
+   "-tags='mock'"
  ]
}

```

the go output is as expected and errors are shown in VSCode

```
Starting linting the current package at /Users/alex/repositories/go/src/testgovet
Starting "go vet" under the folder /Users/alex/repositories/go/src/testgovet
/Users/alex/repositories/go/src/testgovet>Finished running tool: /Users/alex/repositories/go/bin/golint

Starting building the current package at /Users/alex/repositories/go/src/testgovet
/Users/alex/repositories/go/src/testgovet>Finished running tool: /usr/local/opt/go/libexec/bin/go test -c -i -tags='mock' -o /var/folders/k1/wpppkyn91v7239smq8l90flh0000gn/T/vscode-goJndhyV/go-code-check testgovet
/Users/alex/repositories/go/src/testgovet/my_mock_test.go:5: undefined: t

/Users/alex/repositories/go/src/testgovet>Finished running tool: /usr/local/opt/go/libexec/bin/go vet -tags='mock' .
/Users/alex/repositories/go/src/testgovet/my_mock_test.go:5: undefined: t
```

Having multiple tags in the settings.json but removing the empty line in `my_mock_test.go` between package name and build tags also fixes the go output and error display.
(this is probably a side effect because without the empty line the comment is not recognized to contain build tags)

```diff
// +build mock
- 
package main_test
```

**System information:**
 - OS: occurs on OSX as well as on Linux
 - Extension Version: 0.11.8
 - VS Code Version: 1.39.2

**Comment by giniedp** [comment]
i hooked into [runTool](https://github.com/microsoft/vscode-go/blob/61b612e60346c663368e173150d1248610bebbc7/src/util.ts#L648) function and printed `stdout` and `stderr` right after the tool returns and it gives me

```
/Users/alex/repositories/go/src/testgovet>Finished running tool: /usr/local/opt/go/libexec/bin/go vet -tags='unit mock' .

stdout:
?   	testgovet	[no test files]

stderr:

--
```

When i now use `exec` instead of `execFile` at https://github.com/microsoft/vscode-go/blob/61b612e60346c663368e173150d1248610bebbc7/src/util.ts#L670

like this

```diff
-p = cp.execFile(cmd, args, { env, cwd }, (err, stdout, stderr) => {
+p = cp.exec([cmd, ...args].join(' '), { env, cwd }, (err, stdout, stderr) => {
```

this fixes the issue. The output and the error reporting works as expected.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @giniedp 

I also noticed that when you remove the quotes around the tags, the vet output is as expected
`"go.vetFlags": ["-tags=unit mock"]`

Another option is to use the buildTags setting instead `"go.buildTags": "unit mock"`

**Comment by ramya-rao-a** [comment]
Please try either of the 2 options above.

**Comment by giniedp** [comment]
@ramya-rao-a thanks, that works perfectly.

However it still leaves a malformed output line

> Finished running tool: /usr/local/opt/go/libexec/bin/go vet -tags=unit mock .

Not a big issue, but might be misleading for anyone who relies on that output to be a valid command.
