### ISSUE TITLE
Sometimes Golang  intelligence not working (go imports etc etc) 

### ISSUE THREAD

**Issue by ArifulProtik** [microsoft/vscode-go#2888]
- VSCode Version:1.39.2
- OS Version: Windows 10 Pro (1903)

Sometimes Vscode doesn't import existing packages.
Sometimes Vscode doesn't show intelligence code suggestions
Linting gets superslow

**Comment by stamblerre** [comment]
Can you share your VSCode settings (`Ctrl + Shift + P -> Preferences: Open Settings (JSON)`)?

**Comment by stamblerre** [comment]
Are you using Go modules for your projects?

**Comment by ArifulProtik** [comment]
Yeah i am Using Go Modules

**Comment by stamblerre** [comment]
I would suggest enabling the use of the Go language server when you are using modules. It is designed to work with modules, so it will work better than the default tooling.

**Comment by ArifulProtik** [comment]
It is Enabled, But still, the same issue occurring

**Comment by stamblerre** [comment]
Make sure to reload your VS Code window after enabling the language server. It's also difficult to debug your issue as it sounds very general. Can you attach a specific repro case of an import not being added when expected, or some other example?
