### ISSUE TITLE
Cannot do rename

### ISSUE THREAD

**Issue by hongchaodeng** [Microsoft/vscode-go#289]
I am having following error when doing rename:
```
Cannot rename due to errors: Error: stderr maxBuffer exceeded.
```

What's the problem here? How can I solve it?

**Comment by lukehoban** [comment]
That would mean that there was more than 200kb of output on stderr when using `gorename` - presumably because you have errors in your program?  That said, we could bump up the maxBuffer to some larger constant so that we can provide a better error more of the time.

**Comment by hongchaodeng** [comment]
I'm just testing rename functionality with simple file like:
```Go
type item struct {...}
func main(){
  it := &item{}
  ...
}
```
And then rename item.

**Comment by lukehoban** [comment]
@hongchaodeng I can't repro with the most minimal complete example I can build off of what you have shared.  Can you share a complete project where this repros, along with any details about your system/environment?

**Comment by hongchaodeng** [comment]
Closing this

**Comment by hongchaodeng** [comment]
Reinstalling everything seems to fix the problem :)

**Comment by lukehoban** [comment]
Good to hear.
