### ISSUE TITLE
Documentation issue for remote debugging

### ISSUE THREAD

**Issue by keyoti** [microsoft/vscode-go#2891]
Reading https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#remote-debugging

It gives the following code snippets

`$ dlv debug --headless --listen=:2345 --log --api-version=2`

and

`$ dlv debug --headless --listen=:2345 --log -- -myArg=123`

however these won't work (or didn't for me) you need to specify the package to run, eg.

`$ dlv debug --headless --listen=:2345 --log --api-version=2 /path/to/go/src/package/to/run`

and

`$ dlv debug --headless --listen=:2345 --log -- -myArg=123 /path/to/go/src/package/to/run`

**Comment by ramya-rao-a** [comment]
Apologies for the delay in responding @keyoti 

I believe running `dlv debug` does work without specifying the package if it is being run from the folder that holds the package. 

cc @quoctruong

**Comment by keyoti** [comment]
I think you're right, but for a Go newbie it wasn't obvious and I don't see that mentioned in the text anywhere.

**Comment by quoctruong** [comment]
Perhaps we can make the documentation more clear using wording from the `dlv debug` documentation (link [here](https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_debug.md))

**Comment by ramya-rao-a** [comment]
Yes, there is definitely scope for improvement here.
I have updated the text as below:

![image](https://user-images.githubusercontent.com/16890566/73318425-35de3b80-41ee-11ea-91b1-9117bc4ae8d9.png)

Thanks for reporting @keyoti
