### ISSUE TITLE
Add syntax highlighting for structs

### ISSUE THREAD

**Issue by Jacalz** [microsoft/vscode-go#2892]
**Is your feature request related to a problem? Please describe.**
I have been using Atom with the go-plus extension and the syntax highlighting is just wonderful, but switching over to the, I see some things that aren't highlighted correctly compared to go-plus. The frustration comes with the fact that structs and struct fields are uncoloured, it makes it hard to see it in my opinion.

**Describe the solution you'd like**
I would like struct and struct fields to stand out more, like in go-plus for atom.

**Additional context**

Atom:
![image](https://user-images.githubusercontent.com/25466657/68406460-29fc5380-0182-11ea-86da-6efc775565bb.png)
![image](https://user-images.githubusercontent.com/25466657/68406486-3680ac00-0182-11ea-9996-749ee30c84c4.png)

Visual Studio Code:
![image](https://user-images.githubusercontent.com/25466657/68406385-033e1d00-0182-11ea-9291-9174bb7c4b3d.png)
![image](https://user-images.githubusercontent.com/25466657/68406415-16e98380-0182-11ea-9e29-4bf3a925e030.png)

As you can see the differences are quite big and atom wins by miles in my opinion.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Jacalz 

The colors are controlled by the grammar being used and the grammar is part of the main VS Code project. Therefore, please log this issue in the [VS Code repo](https://github.com/Microsoft/vscode)

In order for the folks at VS Code to repro this easily, please include a code snippet that they can copy and paste into a Go file.

**Comment by Jacalz** [comment]
Alright, I will make sure to file the bug upstream then :slightly_smiling_face:
