### ISSUE TITLE
Go to Definition Not Working

### ISSUE THREAD

**Issue by vk7055** [microsoft/vscode-go#2893]
I am using the Go extension since a month. Its current version is 0.11.9

Go to definition never worked for me across my own packages.

Go to definition works for built-in packages and within the package.

**Comment by stamblerre** [comment]
Can you share your VS Code settings (`Ctrl + Shift + P -> Preferences: Open Settings (JSON)`)? Are you using the language server?

**Comment by vk7055** [comment]
This is my `settings.json`
```
{
    "workbench.colorTheme": "Solarized Light",
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "workbench.startupEditor": "welcomePage",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "go.formatTool": "goimports",
    "window.zoomLevel": 1,
    "files.autoSave": "afterDelay"
}
```
I am not using Language Server.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @vk7055 

Are you using Go modules? If so, then the language server would be the tool of choice to provide better support.

If not, then we use the [godef](https://github.com/rogpeppe/godef) tool to provide definitions. Can you use this tool from the terminal and see if it gives you expected results?

**Comment by vk7055** [comment]
It resolved. I got a pop-up for some extension. I installed it. And it started working.
