### ISSUE TITLE
Go to definition not working when using Go modules

### ISSUE THREAD

**Issue by wangguoxi** [microsoft/vscode-go#2896]
1、my workspace  settings.json  "go.useLanguageServer": true,  
2、go env 
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/data/home/wang/.cache/go-build"
GOENV="/data/home/wang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/home/wang/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build951617228=/tmp/go-build -gno-record-gcc-switches"
3、 when go.sum and go.mod   exists in the project directory(For example, my project directory is  myproject),  I can not use  Go to definition,  but  when I delete go.sum and go.mod , I can use "Go to definition"

4、my workspace  settings.json  "go.useLanguageServer": false,  I can't use it either.

**Comment by stamblerre** [comment]
Go to definition should work for modules, with or without the language server. To understand a bit more what's going on with the language server, could you try running `gopls -rpc.trace -v check /path/to/file.go` inside of your module?

**Comment by wangguoxi** [comment]
ok  thanks,  It's ok now, I don't know what I did. Maybe because I restarted the computer

**Comment by cnjeffliu** [comment]
I had met the same problem, but not work fine after try anything I know

**Comment by wangguoxi** [comment]
1、you can disable GoModules， and try&nbsp; again
2、If you use ssh-remote,make sure Go tool has been installed both windows and remote
3、list your&nbsp; “go env”




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jeff"<notifications@github.com&gt;; 
发送时间: 2019年12月27日(星期五) 下午5:25
收件人: "microsoft/vscode-go"<vscode-go@noreply.github.com&gt;; 
抄送: "王国洗"<318175542@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [microsoft/vscode-go] Go to definition not working when using Go modules (#2896)




I had met the same problem, but not work fine after try anything I know

**Comment by cnjeffliu** [comment]
first , it can work find if i disable the Gomodules;
then, I use Go tool locally, On windows10 by use vscode 1.41.1;
at last.  I execute the 'go env', here is the result:

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jeff\AppData\Local\go-build
set GOENV=C:\Users\jeff\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\jeff\AppData\Local\Temp\go-build578706650=/tmp/go-build -gno-record-gcc-switches

**Comment by stamblerre** [comment]
If you are using modules with the language server (`gopls`), then you will need to open VS Code from the directory that contains the `go.mod` file. If you are still encountering issues, please file an issue on the [Go issue tracker](https://github.com/golang/go/issues/new) with some of the troubleshooting information requested [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md).

**Comment by cnjeffliu** [comment]
I cannot using the language server , because of the gfw.
