### ISSUE TITLE
Unable run build using Tasks - throws /bin/bash go command not found

### ISSUE THREAD

**Issue by byteshiva** [microsoft/vscode-go#2899]
Issue Type: <b>Bug</b>
I'm getting below error when executing a simple go file using a vscode task. I'm using a go version manager hence there is not global go Binary installed on OS.

```
> Executing task in folder automate: go build  <

/bin/bash: go: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```

```
go env 
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xyz/.cache/go-build"
GOENV="/home/xyz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xyz/.asdf/installs/golang/1.13.4/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/xyz/.asdf/installs/golang/1.13.4/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/xyz/.asdf/installs/golang/1.13.4/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build040679981=/tmp/go-build -gno-record-gcc-switches"
```

Extension version: 0.11.9
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 5.3.0-21-generic

**Comment by ramya-rao-a** [comment]
Can you share the task definition you are using?
Also, I am not familiar with "go version manager", can you point me to some docs with some information on how that works?

**Comment by byteshiva** [comment]
> Can you share the task definition you are using?

I'm trying to execute the task that's mentioned in vscode-go wiki. Please let me know if you need more information. I presume vscode-go task is unable to find the ```go binary``` since its located in a different location., i.e., @ 

```
GOPATH="/home/xyz/.asdf/installs/golang/1.13.4/packages"
GOROOT="/home/xyz/.asdf/installs/golang/1.13.4/go"
```

https://github.com/microsoft/vscode-go/wiki/Tasks-with-Go
```
{
	"version": "2.0.0",	
	"type": "shell",	
	"echoCommand": true,
	"cwd": "${workspaceFolder}",
	"tasks": [
		{
			"label": "rungo",
			"command": "go run ${file}",
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},		
	]
}
```
> Also, I am not familiar with "go version manager", can you point me to some docs with some information on how that works?
1. https://asdf-vm.com/#/  -- Manage multiple runtime versions with a single CLI tool
1.1 Plugin for Golang - **golang plugin for asdf version manager** https://github.com/asdf-vm/asdf

**Comment by ramya-rao-a** [comment]
Is `/home/xyz/.asdf/installs/golang/1.13.4/go` part of your PATH?

**Comment by byteshiva** [comment]
> Is `/home/xyz/.asdf/installs/golang/1.13.4/go` part of your PATH?

Yes

**Comment by s0kil** [comment]
Related to: https://github.com/Microsoft/vscode/issues/55941

**Comment by byteshiva** [comment]
> Related to: [microsoft/vscode#55941](https://github.com/microsoft/vscode/issues/55941)

Thanks @s0kil for the lead,

the following are the changes I did to make it work in my usecase where go is installed using Go Version Manager.

Here are the steps 

Step1:
(Reference : https://code.visualstudio.com/docs/editor/integrated-terminal#_shell-arguments)
```
For example, to enable running bash as a login shell (which runs .bash_profile), pass in the -l argument (with double quotes):

// Linux
"terminal.integrated.shellArgs.linux": ["-l"]
```
Step 2:
Configure your custom shell settings in .bash_profile, say for example, I'm using `go version manager`. In order to kick in `Go Version Manager`, it needs the below shell file to be executed before bash prompt.

```
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
```

Step 3:
Once the Go version manager is set, now you can have go runtime available to be used by tasks.

```
			"command": "go run ${file}",
```

**Comment by stamblerre** [comment]
@byteshiva: Sounds like you go this working - can this issue be closed?

I'll defer to @ramya-rao-a to determine if the Go extension should support situations where users don't have `go` on their PATHs.

**Comment by byteshiva** [comment]
> @byteshiva: Sounds like you go this working - can this issue be closed?

@stamblerre - Please go ahead and close this issue.

**Comment by pecigonzalo** [comment]
Could we re-open this? Im using `asdf-vm` and I have a similar but related issue:

```
gocode:
Error: Command failed: /home/davyjones/.asdf/shims/go get -v github.com/mdempsky/gocode
asdf: No version set for command go
you might want to add one of the following in your .tool-versions file:

golang 1.14
```

This is because the exec of `go get -v` seems to happen outside of the code repository, causing `asdf` to not find the `.tool-versions` file and be able to select the correct binary.

**Comment by stamblerre** [comment]
@pecigonzalo: Can you open a new issue for this? Both issues are related to `asdf-vm`, but they are not the same.

**Comment by pecigonzalo** [comment]
Will do, thanks for letting me know.
