### ISSUE TITLE
Errors always reported in currently opened file

### ISSUE THREAD

**Issue by kjk** [Microsoft/vscode-go#29]
To reproduce:

1) Create two empty files: `main.go` and `second.go`.

2) Launch vscode and open `main.go`

3) Make `main.go` a minimally valid go program, e.g.:

```
package main

func main() {
}
```

4) Save `main.go`

What happens: we get an error: `"expected 'package', found 'EOF' in main(1,1)"`.

What should happen: the error message is correct but the error is in `second.go` (empty) file, not `main.go`. It looks like all errors are attributed to file that was saved (and triggered error check), not necessarily the file that contains an error.

**Comment by epsniff** [comment]
was this fixed by https://github.com/Microsoft/vscode-go/commit/821b545737d672bde4a3ff6b391c4e9a7ae4f199 ?

**Comment by lukehoban** [comment]
The fix for this is in the `0.6.10` release, please reopen if you are still seeing issues after upgrading.

**Comment by epsniff** [comment]
thx, it seems fixed now.
