### ISSUE TITLE
testify-enabled test templates generation

### ISSUE THREAD

**Issue by gsora** [microsoft/vscode-go#2903]
Since [this commit](https://github.com/cweill/gotests/commit/12fe222a297e88969cf56dc8ea5eb26181511def), `gotests` can generate test templates using `testify` instead of `reflect`.

**Describe the solution you'd like**
Having a configuration parameter to specify what template to use when generating tests would be really handy.

**Describe alternatives you've considered**
Right now I'm generating test templates in CLI since I always end up replacing the core testing logic with a `testify`-based one, so having a toggle directly in this plugin would be awesome!

**Comment by ramya-rao-a** [comment]
From the commit you shared, it looks that you need to be able to pass the `-template` flag to `gotests`
We have a setting `go.generateTestsFlags` which  that get passed to `gotests` which you can use for this. It takes an array.

Please let us know how that goes.
