### ISSUE TITLE
Disable "A debug session is currently active"

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-go#2909]
<img width="449" alt="xx" src="https://user-images.githubusercontent.com/11925432/69300723-fffd6380-0c4e-11ea-80bd-ff48e1d85273.png">

It's very annoying.

It pops up again and again.

Please disable it.

I can change python file when debugging.

**Comment by ramya-rao-a** [comment]
The [latest beta version of this extension](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) will now show a `Don't show again` button on the notification which should help.

**Comment by ramya-rao-a** [comment]
The December update for the extension has the `Don't show again` button that can be used to suppress this message
