### ISSUE TITLE
TypeError: Cannot read property 'lines' of null 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-go#291]
from our error telemetry

```
TypeError: Cannot read property 'lines' of null 
at /lukehoban.Go-0.6.30/out/src/goExtraInfo.js:13:39 

```

**Comment by lukehoban** [comment]
Pretty sure this was fixed a month ago with https://github.com/Microsoft/vscode-go/commit/c49a964f5690487948773fa37c612694c378166f.
