### ISSUE TITLE
outline complete package

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode-go#2910]
Currently outline only shows the outline of the selected file. Consider implementing a flag to always have a outline of the complete package (like for example the index outline of godoc, example fmt index https://godoc.org/fmt#pkg-index which is a index of the complete pkg fmt, not just of one file)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @gertcuykens 
Closing this issue in favor of #2793 which I believe is the same feature request

**Comment by ramya-rao-a** [comment]
Please subscribe to #2793 for further discussions
