### ISSUE TITLE
outline layout

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode-go#2911]
Currently the words `package`, `variable`, `function` after the name are meaningless and already represented by a symbol in front. Please replaced by `full package name from mod` the type `int, string, ...` and function definition `(x int, y int) err`

![image](https://user-images.githubusercontent.com/863731/69304518-3c19cf80-0c21-11ea-84b9-ce15917bd8cb.png)

**Comment by ramya-rao-a** [comment]
The extension currently uses the `go-outline` tool which does not give the information that we would need to show what you presented above.

But, when `go.useLanguageServer` setting is enabled, the outline feature is powered by the language server and it does show more useful information 

![image](https://user-images.githubusercontent.com/16890566/70677923-67527600-1c45-11ea-8ed5-d4af0b2f4176.png)

There are no plans to enhance the non-language server scenario at the moment, therefore closing this issue.
