### ISSUE TITLE
Run named test in tables tests 

### ISSUE THREAD

**Issue by kylebrandt** [microsoft/vscode-go#2912]
**Is your feature request related to a problem? Please describe.**
The run test under cursor is a very useful feature. It would be more useful if one could select a specific named test within a table test, and execute just that test.

For example a common pattern is:

```
tests := map[string]struct {
        input string
        sep   string
        want  []string
    }{
        "simple":       {input: "a/b/c", sep: "/", want: []string{"a", "b", "c"}},
        "wrong sep":    {input: "a/b/c", sep: ",", want: []string{"a/b/c"}},
        "no sep":       {input: "abc", sep: "/", want: []string{"abc"}},
        "trailing sep": {input: "a/b/c/", sep: "/", want: []string{"a", "b", "c"}},
    }
```

or similar but a slice of structs with a name property.

Reference: https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

**Describe the solution you'd like**
Some common table tests patterns to be recognized, and then have the name of the subtest be passed to generated go test command, so only that one entry in the test table is run. 

**Describe alternatives you've considered**
I don't have any other then running the whole test or going to the terminal (`/usr/local/go/bin/go test -timeout 30s foo/foo/ -run 'TestFooTableTest/foo_works$' -v`. Ideas welcome :-) 

I imagine table tests are varied enough that maybe adding this feature to this project doesn't work, in which case no offense taken if this issue is closed in my face :-)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @kylebrandt 
Is this related to #2850?

**Comment by ramya-rao-a** [comment]
Closing this issue as this feature cannot be implemented in this extension for the same reason as mentioned in #1748
