### ISSUE TITLE
Find all reference is not working when using gopls

### ISSUE THREAD

**Issue by tharun-d** [microsoft/vscode-go#2914]
Vs code latest: Ubuntu 18.04
Go version: go version go1.12.7 linux/amd64

.bashrc
export GOROOT=/usr/local/go
export GOPATH=/home/tharun/work/nsdcserverside
export PATH=$PATH:$GOROOT/bin

Intellisense is working and everything is working only find all reference is not working. Previously it used to work i think after updating vscode it stopped working. go settings in vscode default.
I downloaded every pakage of go for vscode support it shows success also

Find all reference is working if calling the method in same file. even though if i import in other package then used in function  find all reference is not working, but go is building

I am not using go modules 
my settings
"go.formatTool": "goimports",
    "go.useLanguageServer": true

**Comment by ramya-rao-a** [comment]
Thanks for reporting @tharun-d 

cc @stamblerre

**Comment by stamblerre** [comment]
@tharun-d: What directory did you open VS Code with? `gopls` finds references within your workspace, so if you aren't using modules, you will need to open your entire `$GOPATH` to find references in other projects.

**Comment by tharun-d** [comment]
i am opening entire project folder only still it is not working I am pretty sure it broke after updating vscode to latest

**Comment by stamblerre** [comment]
@tharun-d: Can you share the output of `gopls -rpc.trace -v check /path/to/file.go`?

**Comment by tharun-d** [comment]
gopls -rpc.trace -v dal/trainer.go 
gopls: command not found
I tried to install gopls with go install update tools in vscode
then i got
go.toolsGopath setting is not set. Using GOPATH /home/tharun/work/nsdcserverside
Installing 1 tool at /home/tharun/work/nsdcserverside/bin in module mode.
  gopls

Installing golang.org/x/tools/gopls SUCCEEDED

Reload VS Code window to use the Go language server
All tools successfully installed. You're ready to Go :).

**Comment by stamblerre** [comment]
It looks like your GOPATH is not on your PATH. You can try either adding your GOPATH to your PATH or you can run `gopls` with the full path: `/home/tharun/work/nsdcserverside/bin/gopls -rpc.trace -v check dal/trainer.go`.

**Comment by tharun-d** [comment]
gopls is not present in bin

**Comment by tharun-d** [comment]
I manually installed now gopls binary is present in bin. and I reloaded vscode also
But still Find all reference is not working
attaching screenshot

1. Here changeTrainer Find all reference showing only once

![Screenshot from 2019-12-17 09-44-22](https://user-images.githubusercontent.com/24644710/70964469-fcc09080-20b1-11ea-87ae-4b53cc644dcd.png)

2. But I did overall search it is used in routes package
![Screenshot from 2019-12-17 09-47-46](https://user-images.githubusercontent.com/24644710/70964563-53c66580-20b2-11ea-97f2-b23376107811.png)

**Comment by stamblerre** [comment]
If your `$GOPATH/bin` is not on your `$PATH` you would have to execute `./gopls` in the directory that contains `gopls`.

Regarding find references, the currently released version of `gopls` does not support find references in multiple packages. The next version of `gopls` will support this feature in your workspace scope.

**Comment by stamblerre** [comment]
As a follow-up to this, the next version of `gopls` will support finding references in your workspace (instead of just in your package).

@tharun-d: Please follow up if there is anything else I can help investigate.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

Since the next version `gopls/v0.3.0` will have the fix, closing this issue.
For folks who want to try the fix before the next version is out, please try out `gopls` from the master branch. You can download it by running 
```
GO111MODULE=on 
go get golang.org/x/tools/gopls@master golang.org/x/tools@master
```
