### ISSUE TITLE
code suggestion is not suggesting struct when using gopls

### ISSUE THREAD

**Issue by oneslash** [microsoft/vscode-go#2916]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.4 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- Version: 1.40.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.11.9
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- darwin/amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
```json
"go.useLanguageServer": true,
"go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": true,
        "documentLink": true,
        "highlight": true
    }
```

### Describe the bug
When I type
```go
type example (cursor is here) {
}
```
I don't get struct as a suggestion

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/15870134/69614447-6f020000-1033-11ea-9749-a4e6a5c74a8a.png)

**Comment by ramya-rao-a** [comment]
@stamblerre Any thoughts?

**Comment by stamblerre** [comment]
The work on keyword autocompletion is still in progress (see https://github.com/golang/go/issues/34009).

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@oneslash Closing this issue in favor of the upstream one. Please subscribe to the same.
