### ISSUE TITLE
The editor cannot import package automatically

### ISSUE THREAD

**Issue by nicewahson** [microsoft/vscode-go#2918]
# What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.4 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.40.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- vscode-go 0.11.9
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin amd64

### Share the Go related settings you have added/edited

{
"go.useLanguageServer": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.snippetSuggestions": "top",
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": true, 
        "enhancedHover": true,
        "completeUnimported": true
    },
    "go.languageServerExperimentalFeatures": {
        "autoComplete": false,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": false
    },
    "go.autocompleteUnimportedPackages": true
}

### Describe the bug
the editor cannot show import list automatically
![image](https://user-images.githubusercontent.com/15240937/69712423-c5f3fc00-113d-11ea-987e-dbf3e97d4c85.png)

Hoping your reply.

**Comment by stamblerre** [comment]
Autocompletion inside of import blocks isn't something that we've considered supporting `gopls`. Filed an issue upstream for this (https://github.com/golang/go/issues/35877). In the meantime, the best approach here would be rely on the import on save behavior. The import "fmt" should be added for you automatically on save, based on your settings.

**Comment by nicewahson** [comment]
Thanks for your reply.  @stamblerre It's nice of you.
