### ISSUE TITLE
Set go.inferGopath true,make running go.lintTool Error

### ISSUE THREAD

**Issue by HyaZraeLN** [microsoft/vscode-go#2922]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.13 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.40.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.11.9
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- Windows amd64

### Share the Go related settings you have added/edited

"go.inferGopath": true,
	"go.buildOnSave": "off",
	"go.toolsGopath": "G:/Workspace/GOPATH",
	"go.vetOnSave": "package",
	"go.coverOnSave": false,
	"go.useCodeSnippetsOnFunctionSuggest": true,
	"go.coverOnSingleTest": true,
	"go.useGoProxyToCheckForToolUpdates": false,
	"go.useLanguageServer": true,
	"go.testFlags": ["-v"],
	"go.languageServerExperimentalFeatures": {
		"format": true,
		"autoComplete": true,
		"rename": true,
		"goToDefinition": true,
		"hover": true,
		"signatureHelp": true,
		"goToTypeDefinition": true,
		"goToImplementation": true,
		"documentSymbols": true,
		"workspaceSymbols": true,
		"findReferences": true,
		"diagnostics": true,
		"documentLink": true,
		"highlight": true
	},
	"go.docsTool": "gogetdoc",
	"go.lintTool": "golangci-lint", // both of this selection will run error while go.inferGopath:true
	"go.lintOnSave": "file",
	"go.gotoSymbol.includeGoroot": true,
	"go.gotoSymbol.includeImports": true

### Describe the bug

Set go.inferGopath true 
Run go.lingTool occured Error 
Set lintOnSave both. it will run error ,every saving, editor delete some other code

(MAC OS doesn't occured this)

- Output:
Error while running tool: G:\Workspace\GOPATH\bin\golangci-lint.exe run --print-issued-lines=false {workfile}
level=error msg="[runner/goanalysis_metalinter] typechecking error: {workfile}: undeclared name: testing"
level=error msg="[runner/goanalysis_metalinter] typechecking error: {workfile}: undeclared name: fmt"
...

Run error both go.inferGopath and go.lintTool
expect it work

**Comment by ramya-rao-a** [comment]
Thanks for reporting @HyaZraeLN 

Are you using Go modules?

**Comment by HyaZraeLN** [comment]
Using Go modules or not ，will occure this Error either

**Comment by stamblerre** [comment]
`"go.inferGopath"` should not have any effect when you are using modules, so it sounds like there is some other issue happening here. What is the directory structure of your project - what do you expect the inferred GOPATH to be?
