### ISSUE TITLE
impl doesn't generate stubs from interface for one-file app 

### ISSUE THREAD

**Issue by koddr** [microsoft/vscode-go#2923]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.4 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
>Version: 1.40.2
>Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
>Date: 2019-11-25T14:52:45.129Z
>Electron: 6.1.5
>Chrome: 76.0.3809.146
>Node.js: 12.4.0
>V8: 7.6.303.31-electron.0
>OS: Darwin x64 18.7.0
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.11.9
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin amd64

### Share the Go related settings you have added/edited

```
  "go.gopath": "~/.go",
  "go.useCodeSnippetsOnFunctionSuggest": true,
  "go.inferGopath": false,
  "go.autocompleteUnimportedPackages": true,
  "go.formatTool": "goimports",
  "go.useLanguageServer": true,
  "[go]": {
    "editor.formatOnSave": true
  },
```

### Describe the bug
Get error each time then I run `> Go: Generate Interface Stubs`:

> `Cannot stub interface: unrecognized interface: Inter`

My `main.go` is:

```go
package main

import (
	"fmt"
)

// Inter ...
type Inter interface {
	MethodOne()
}

// Struct ...
type Struct struct {
	String string
}

func main() {
	m := &Struct{
		String: "hello world",
	}

	exampleFunc(m)
}

func exampleFunc(i Inter) {
	// ...
}
```

But if I separate interface to another package (ex. `example/models/myInter.go`) and import them — all okay, interface methods are generating successfully.

### Steps to reproduce the behavior:
1. Create one-file (all-in-one) app at `main.go`
2. Click `cmd+shift+p`and choose `> Go: Generate Interface Stubs`
3. See error

### Screenshots or recordings
![Screenshot 2019-11-30 at 19 49 24](https://user-images.githubusercontent.com/11155743/69903460-8bdb6200-13aa-11ea-82e2-50e6ec3ff48b.png)

![Screenshot 2019-11-30 at 19 51 38](https://user-images.githubusercontent.com/11155743/69903577-5f284a00-13ac-11ea-98c0-1a18f9e79888.png)

**Comment by ramya-rao-a** [comment]
We use the [impl](https://github.com/josharian/impl) tool to provide this feature via the command `Go: Generate Interface Stubs`. 

Please try the command line tool directly and let us know if the tool works without any problems or gives you the same error `Cannot stub interface: unrecognized interface: Inter`

**Comment by koddr** [comment]
@ramya-rao-a yes, I understand that vscode-go plugin use `impl`.

If I try on console, I see the seems thing:

```console
$ impl 's *Struct' Inter

unrecognized interface: Inter
```

But, I have interface `Inter` into `main.go`:

```go
package main

// Inter ...
type Inter interface {
	MethodOne()
}

// Struct ...
type Struct struct {
	String string
}

func main() {
	m := &Struct{
		String: "hello world",
	}

	exampleFunc(m) // <-- error line
}

func exampleFunc(i Inter) {
	// ...
}
```

🤔

**Comment by ramya-rao-a** [comment]
In that case, please log the issue in the [repo for the impl tool](https://github.com/josharian/impl)
If it is determined that the extension is invoking the impl tool incorrectly, then we can re-open this issue.

Thanks for reporting & Happy Coding!
