### ISSUE TITLE
Add Go: Generate Interface Stubs to error's `Quick fix` or|and context menu

### ISSUE THREAD

**Issue by koddr** [microsoft/vscode-go#2924]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to generate interface stubs. 

Can you please add this feature to error's `Quick fix` or|and context menu?

![Screenshot 2019-11-30 at 20 05 23](https://user-images.githubusercontent.com/11155743/69903630-0f964e00-13ad-11ea-8820-3730176a0f6d.png)

**Describe the solution you'd like**
1. I click to `Quick fix` link on error line (where VS Code show `cannot use m (variable of type *MyStruct) as MyInterface value in argument to exampleFunc: missing method MethodOne`);
2. Choose `Generate Interface Stubs ...`;
3. Automatically open `impl` field;
4. I'm entering `s *MyStruct MyInterface` and Enter;
4.1. Alternative solution: when I start type name of interface, VS Code scan current file and suggest me founded variants;
5. Undeclared methods was generated at the bottom of current file;

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by ramya-rao-a** [comment]
A similar feature request is being tracked in #1823
Please subscribe to it and add any extra thoughts you have there.
