### ISSUE TITLE
Go Modules support announcement can't be hidden

### ISSUE THREAD

**Issue by coderanger** [microsoft/vscode-go#2925]
It would be nice to either have it be dismissed on click or (more easy to implement) have a setting to disable it. Not something I need in my status bar forever once I know things are set up for modules :)

**Comment by ramya-rao-a** [comment]
As of version 1.36 of VS Code, you can now [hide status bar items](https://code.visualstudio.com/updates/v1_36#_hide-individual-status-bar-items) by right clicking on the status bar and selecting the item to hide. The same action is used to un-hide it as well.

The catch is that once hidden, it doesnt show up unless you un-hide it.

The main intention of the status bar item for Go modules was to help understanding if the extension is currently treating your project to be in module mode or not. The fact that it links to the wiki was an add-on.
