### ISSUE TITLE
VSCode go linter allows importing internal packages not in the hierarchy

### ISSUE THREAD

**Issue by manikawnth** [microsoft/vscode-go#2926]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.12.1 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.39.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- golang.org/x/tools/gopls v0.1.7
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- windows/amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.

None go specific
```
{
    "window.zoomLevel": 1,
    "editor.tabSize": 2,
    "workbench.colorTheme": "Visual Studio Light",
    "go.useLanguageServer": true,
    "extensions.ignoreRecommendations": false
}
```

### Describe the bug
Linter is not flagging while importing internal packages that belong to a different hierarchy

__In the below hierarchy, importing `ast` package from `cache` package is not flagged as an error__

```
go-rules (repo)
|__ parser (package)
|	|__ internal
|		|__ ast (package)
|__ cache (package)
```

### Steps to reproduce the behavior:
Create a internal package structure and import the internal package from a different hierarchy

### Screenshots or recordings
Not applicable

**Comment by stamblerre** [comment]
Thanks for reporting this! I filed https://github.com/golang/go/issues/35937 to track this in `gopls`, because that's really where the error lies.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @manikawnth 
Closing in favor of the upstream issue, please subscribe to the same.
