### ISSUE TITLE
vscode always hint "gopls is out of date" after go get gopls

### ISSUE THREAD

**Issue by PseudoCowboy** [microsoft/vscode-go#2927]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.11.4 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.40.2
           f359dd69833dd8800b54d458f6d37ab7c78df520
           x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- gopls version
           version 0.2.0, built in $GOPATH mode
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin
           amd64

### Share the Go related settings you have added/edited

"go.useLanguageServer": true,
    "go.toolsGopath": "/Users/jiangzejia/go",
    "go.alternateTools": {
      "go-langserver": "gopls"
    },
    "go.languageServerExperimentalFeatures": {
      "format": true,
      "autoComplete": true,
      "goToDefinition": true,
      "hover": true,
      "signatureHelp": true,
      "goToTypeDefinition": true
    },
"go.buildOnSave": "off",
    "go.vetOnSave": "off",
    "[go]": {
      "editor.snippetSuggestions": "none",
      "editor.formatOnSave": true,
      "editor.codeActionsOnSave": {
        "source.organizeImports": true
      },
    },

### part of go env

GOARCH="amd64"
GOBIN="/Users/jiangzejia/go/bin"
GOCACHE="/Users/jiangzejia/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jiangzejia/go"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"

### Describe the bug
when I open a go program, vscode always hint that gopls is out of date, I click update and vscode print installed successfully, need restart vscode. when I restart vscode, the hint still exists.

BTW, sometimes, I go to a function definition, this will cause high cpu usage and jump very slow. Is there something wrong with my setting.Or I install gopls incorrectly?

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/20549450/70209148-6c598600-176a-11ea-9448-c20177aa84b8.png)
![image](https://user-images.githubusercontent.com/20549450/70209188-8dba7200-176a-11ea-9894-83b8817c2fe6.png)

**Comment by stamblerre** [comment]
What is the output of `gopls version` on the command line?

**Comment by PseudoCowboy** [comment]
@stamblerre 
version 0.2.0, built in $GOPATH mode
![image](https://user-images.githubusercontent.com/20549450/70290985-b7c86e80-1814-11ea-9e8d-3d0182d5791c.png)

**Comment by PseudoCowboy** [comment]
vscode go extension is 0.11.9

**Comment by stamblerre** [comment]
Looks like you might have multiple versions of `gopls` installed. In your screenshot above VS Code says that it's installing `gopls` in module mode, but with `gopls` version it says GOPATH mode. What is the output of `which gopls`? And what is the output of `/Users/jiangzejia/go/bin/gopls version`?

**Comment by PseudoCowboy** [comment]
@stamblerre 
here is the output
![image](https://user-images.githubusercontent.com/20549450/70304791-b19ab800-183d-11ea-88cf-de2b60ca1376.png)

**Comment by stamblerre** [comment]
Seems like VS Code is not installing `gopls` correctly in module mode. This is probably related to the fact that you are using Go 1.11 - there may be some bug with installing it in module mode. We can investigate this further, but a quick work-around will be for you to install `gopls` manually on the command line by running `GO111MODULE=on go get golang.org/x/tools/gopls@latest`.

**Comment by PseudoCowboy** [comment]
@stamblerre 
It doesn't work. Here's the ouput
![image](https://user-images.githubusercontent.com/20549450/70306450-d5f89380-1841-11ea-8979-59ec7f60167b.png)

**Comment by PseudoCowboy** [comment]
I tried to delete **/Users/jiangzejia/go/bin/gopls** and **/Users/jiangzejia/go/pkg/mod/golang.org/x** whole directory, and install gopls again
It doesn't work
![image](https://user-images.githubusercontent.com/20549450/70308950-5b327700-1847-11ea-9cea-79f233f463e4.png)

**Comment by stamblerre** [comment]
I was able to reproduce this with `go1.11.4`, seems like a bug in that version of Go. Is it possible for you to upgrade to Go 1.12 or 1.13?

**Comment by PseudoCowboy** [comment]
OK, I got it. Thanks for your help. I will close this issue.
