### ISSUE TITLE
Is just vscode-go just debug go project and can NOT build go project

### ISSUE THREAD

**Issue by luweijie007** [Microsoft/vscode-go#293]
I installed vscode-go as doc llustration in window, and I can build same go code and debug it
 I git go project but I can not build go project. How can I build go project? 
or  vscode-go has not this feature.

**Comment by lukehoban** [comment]
There is no explicit `Go: Build` command in the extension currently - that is being tracked with #287.

But the extension does run builds on save by default, and results are available in the output window if you open it with `View: Toggle Output`.

There is also a Task framework in VS Code which lets you configure more complex or specialized build tasks.

**Comment by luweijie007** [comment]
I see now ,thanks your time for answer
