### ISSUE TITLE
Set CPU `nice` for Go builds

### ISSUE THREAD

**Issue by jim-minter** [microsoft/vscode-go#2932]
**Is your feature request related to a problem? Please describe.**
Especially when I upgrade Go to a new version, or start working on a new large project, or change branches on a large project, it takes a long time for Go to compile the codebase in the background in order for VS Code to offer IntelliSense-like capabilities.  At the same time, the Go compiler aggressively parallelises, and this hurts the interactivity on my laptop.

**Describe the solution you'd like**
I'd like VS code to execute external Go build processes "niced" (i.e. at a lower scheduling priority) - see https://linux.die.net/man/1/nice - so that they have less adverse effect on interactivity of VS Code.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @jim-minter 

I'll be closing this issue in favor of #1557 which deals with the same problem.
Please add your thoughts there.

**Comment by jim-minter** [comment]
Thanks!  I did look for an issue that was already open, honest ;-)

**Comment by ramya-rao-a** [comment]
I believe you :)
