### ISSUE TITLE
need option to pass args to the dlv debugger itself

### ISSUE THREAD

**Issue by iGeek098** [microsoft/vscode-go#2933]
i have non main stream go version causes the following to happen

Version of Go is too old for this version of Delve (minimum supported version 1.11, suppress this error with --check-go-version=false)

need option in launch.json to pass args to the debugger itself (like miDebuggerArgs for GDB in vscode c extension)

**Comment by renthraysk** [comment]
Same problem running go 1.14rc1

**Comment by ramya-rao-a** [comment]
Is the ask here to pass the `--check-go-version=false` to delve?

**Comment by iGeek098** [comment]
Yeah,

To be more precise to allow it optionally

**Comment by ramya-rao-a** [comment]
Wouldn't this result in unexpected behavior from delve?

**Comment by lijinglin2019** [comment]
Is there any updates? 
I want to pass `--output=<output>` to `dlv debug`, the default value is always `__debug_bin`

```
Flags:
      --continue        Continue the debugged process on start.
      --output string   Output path for the binary. (default "./__debug_bin")
```
