### ISSUE TITLE
Vscode Can't Go Defintion In Go Lang

### ISSUE THREAD

**Issue by vctqs1** [microsoft/vscode-go#2934]
Code not suggest method or struct. and can not suggest arg of func
it just show `loading`. Can not go to define of else

I am using Ubuntu 19.10

**Comment by ramya-rao-a** [comment]
Please share any Go related settings you might have added or edited. You can get these by running the command `Preferences: Open Settings (JSON)`

Are you using Go modules?
Can you share more details around your folder structure if you are using modules?

**Comment by vctqs1** [comment]
`{
    "go.useLanguageServer": true,
    "explorer.confirmDelete": false,
    "window.zoomLevel": 0,
}`

It seem unstable. 
I open project 1, `Go Defintion`  work. But dont work for another project

**Comment by stamblerre** [comment]
What is the output of `gopls version`? Can you share the output of `gopls -rpc.trace -v check /path/to/file.go` for the broken project?

**Comment by vctqs1** [comment]
> gopls -rpc.trace -v check /path/to/file.go
`version v0.1.3, built in $GOPATH mode`


`2019/12/11 13:25:20 Info:8.428785ms for GOROOT= GOPATH= GO111MODULE=on PWD=/home/thu go "list" "-m" "-json" "all", stderr: <<warning: pattern "all" matched no module dependencies
>>
2019/12/11 13:25:20 Info:9.311892ms for GOROOT= GOPATH= GO111MODULE=on PWD=/home/thu go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "builtin", stderr: <<>>
check: getFile: file:///path/to/file.go: open /path/to/file.go: no such file or directory
`

**Comment by stamblerre** [comment]
@vctqs1: It looks like you are using a very old version of `gopls`. Current versions of the VS Code Go extension automatically update to latest, so I imagine you will want to update to a more recent version of the VS Code Go extension.

To update just `gopls` to latest, please follow these steps: Ctrl + Shift + P -> `Go: Install/Update Tools` -> `gopls`. The current version of `gopls` is `v0.2.2`.

**Comment by vctqs1** [comment]
> @vctqs1: It looks like you are using a very old version of `gopls`. Current versions of the VS Code Go extension automatically update to latest, so I imagine you will want to update to a more recent version of the VS Code Go extension.
> 
> To update just `gopls` to latest, please follow these steps: Ctrl + Shift + P -> `Go: Install/Update Tools` -> `gopls`. The current version of `gopls` is `v0.2.2`.

Tkank you. I tried to do industry. 

`Using the value /home/thu/go from the go.toolsGopath setting.
Installing 0 tool at /home/thu/go/bin in module mode.


All tools successfully installed. You're ready to Go :).
`

**Comment by stamblerre** [comment]
What is the output of `which gopls`? It sounds like you may have two versions installed. Based on the output from VS Code, I would expect that you want the version of `gopls` in `/home/thu/go/bin`. What is the output of `/home/thu/go/bin/gopls version`?
