### ISSUE TITLE
golang extension is not working for "Add folder to workspace" project

### ISSUE THREAD

**Issue by JCzz** [microsoft/vscode-go#2935]
```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

I have a project with sub projects folders

Workspace
-- main.go
-- Project(Add folder to workspace...)
---- main.go << not working - no intellisense

go code under workspace works but not for go code in sub project in workspace?

I an using modules and added this` "go.useLanguageServer": true"` to both workspace project and sub project.

**Note**:  note intellisense does work for root workspace but not for sub project

**Comment by stamblerre** [comment]
For `gopls` to work, the folder that you add to your workspace has to be the one that contains the `go.mod` file. Opening directories that contain a module will not work with `gopls` until https://github.com/golang/go/issues/32394 is resolved. Where is the `go.mod` in relation to the projects that you opened?

**Comment by wtask** [comment]
In current time, unhappinessly, to make VSCode work with submodules I think we need to add folders with submodules to workspace independently. First to add the main folder, then add independent "duplicate" of submodule folder. Then edit code opened from appropriate workspace folder. It is crazy...

**Comment by stamblerre** [comment]
We are currently working on addressing this (follow along with the bug linked above), but yes - this is currently the required workflow for nested modules.

**Comment by wtask** [comment]
This is not a frequent case, but sometimes it occurs :(

**Comment by JCzz** [comment]
Thanks @stamblerre looking forward to an update.

@wtask In the sub-project, that includes a .vscode - the go module is in a sub folder to the sub-project:
`root-project/sub-project/go/server`

And it works if I open vscode in this folder containing the module. But I have a bigger project where go is just one part of it all - so it would be very cool to be able to have just one instance of vs code open.

**Comment by stamblerre** [comment]
You can add multiple folders to your workspace to have only one VS Code instance open, as @wtask suggested above (File -> Add Folder to Workspace).

**Comment by ramya-rao-a** [comment]
Thanks all

Closing this issue in favor of the upstream issue that @stamblerre has linked above
