### ISSUE TITLE
Install/Update Tools support HTTP proxy

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode-go#2937]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

**Is your feature request related to a problem? Please describe.**

Toolkit cannot be downloaded in some regions due to network inaccessibility to Google

**Describe the solution you'd like**

There are some options:

1. support HTTP proxy
2. Invoke the toolkit in $GOPATH so that developers can download it themselves (I installed it by go get -v xxxx, but it seems that the extension does not detect its existence?)

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by ramya-rao-a** [comment]
Can you provide some details around what you refer to as "toolkit"? Do you mean the Go tools that the extension depends on?

**Comment by axetroy** [comment]
> Can you provide some details around what you refer to as "toolkit"? Do you mean the Go tools that the extension depends on?

yes.

**Comment by ramya-rao-a** [comment]
https://code.visualstudio.com/docs/setup/network goes through some proxy related set ups for VS Code. Can you check if any of this helps?
