### ISSUE TITLE
golint tool still appears to run when using language server

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode-go#2940]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.4 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.40.2 f359dd69833dd8800b54d458f6d37ab7c78df520 x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	- `0.11.9`
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- `darwin amd64`

### Share the Go related settings you have added/edited

```json
{
"go.delveConfig": {
    "dlvLoadConfig": {
      "followPointers": true,
      "maxVariableRecurse": 1,
      "maxStringLen": 128,
      "maxArrayValues": 64,
      "maxStructFields": -1
    }
  },
  "go.coverOnSingleTest": true,
  "go.useLanguageServer": true,
  "[go]": {
    "editor.snippetSuggestions": "none",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
    "editor.formatOnSaveTimeout": 15000,
    "editor.codeActionsOnSaveTimeout": 15000
  },
  "gopls": {
    "usePlaceholders": true,
    "completeUnimported": true,
    "watchFileChanges": true,
    "deepCompletion": true,
    "hoverKind": "FullDocumentation",
  },
  "files.eol": "\n"
}
```

### Describe the bug

golint still appears to run on save

```bash
Starting linting the current package at /Users/steelphase/Code/go-modules/go.company.org/org/lib/pkg/package
/Users/steelphase/Code/go-modules/go.company.org/org/lib/pkg/package>Finished running tool: /Users/steelphase/Code/Go/bin/golint
```

### Steps to reproduce the behavior:

Just save any go file with the language server enabled

**Comment by ramya-rao-a** [comment]
`gopls` doesnt yet provide linting abilities and therefore the extension continues to run the tool set in the `go.lintTool` setting.

cc @stamblerre for plans on having `gopls` providing linting features

**Comment by stamblerre** [comment]
The linter still has to be re-written to use the `go/analysis` API before it can be integrated into `gopls`, so I don't expect this to be implemented in the near future, though it is something we would like achieve long-term.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre
