### ISSUE TITLE
How to install the additional tools offline? with out git

### ISSUE THREAD

**Issue by dhineshbabu** [microsoft/vscode-go#2942]
Hi,
I have a restriction here in my org. that I can not install git. So the additional files/tools installations fail all the time because of Git absence.

Is there any other way to install them without Git?

Thanks,
Dhinesh

**Comment by ramya-rao-a** [comment]
How do you otherwise install any of the other Go tools that your workflow might need?

@stamblerre Any ideas here?

**Comment by stamblerre** [comment]
The best alternative I can think of is manually downloading and installing the packages and their dependencies, though that will be tedious.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@dhineshbabu,
 
From the extension's perspective, we do not plan to offer any means of installing the tools that does not use git. You can refer to other alternatives to install the Go tools yourself. 

Refer to the wiki on [Go tools used by the extension](https://github.com/microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on) for a list of such tools
