### ISSUE TITLE
add struct `tag` snippets like `goland`

### ISSUE THREAD

**Issue by iiinsomnia** [microsoft/vscode-go#2946]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ramya-rao-a** [comment]
Please provide more details on your feature request
