### ISSUE TITLE
auto-complete not working for custom packages

### ISSUE THREAD

**Issue by en-vee** [microsoft/vscode-go#2949]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	`go version go1.13.5 windows/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	`1.28.2  
7f3ce96ff4729c91352ae6def877e59c561f4850  
x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	0.11.4
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	`
windows
amd64
        `

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
  // Configure editor settings to be overridden for [go] language.
  "[go]": {
    "editor.insertSpaces": false,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  },

  // Tags and options configured here will be used by the Add Tags command to add tags to struct fields. If promptForTags is true, then user will be prompted for tags and options. By default, json tags are added.
  "go.addTags": {
    "tags": "json",
    "options": "json=omitempty",
    "promptForTags": false,
    "transform": "snakecase"
  },

  // Alternate tools or alternate paths for the same tools used by the Go extension. Provide either absolute path or the name of the binary in GOPATH/bin, GOROOT/bin or PATH. Useful when you want to use wrapper script for the Go tools or versioned tools from https://gopkg.in.
  "go.alternateTools": {},

  // Include unimported packages in auto-complete suggestions.
  "go.autocompleteUnimportedPackages": false,

  // Flags to `go build`/`go test` used during build-on-save or running tests. (e.g. ["-ldflags='-s'"])
  "go.buildFlags": [],

  // Compiles code on file save using 'go build -i' or 'go test -c -i'. Options are 'workspace', 'package', or 'off'.
  "go.buildOnSave": "package",

  // The Go build tags to use for all commands, that support a `-tags '...'` argument. When running tests, go.testTags will be used instead if it was set.
  "go.buildTags": "",

  // This option lets you choose the way to display code coverage. Choose either to highlight the complete line or to show a decorator in the gutter. You can customize the color for the former and the style for the latter.
  "go.coverageDecorator": {
    "type": "highlight",
    "coveredHighlightColor": "rgba(64,128,128,0.5)",
    "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
    "coveredGutterStyle": "blockblue",
    "uncoveredGutterStyle": "slashyellow"
  },

  // Use these options to control whether only covered or only uncovered code or both should be highlighted after running test coverage
  "go.coverageOptions": "showBothCoveredAndUncoveredCode",

  // If true, runs 'go test -coverprofile' on save and shows test coverage.
  "go.coverOnSave": false,

  // If true, shows test coverage when Go: Test Function at cursor command is run.
  "go.coverOnSingleTest": false,

  // If true, shows test coverage when Go: Test Package command is run.
  "go.coverOnTestPackage": true,

  // Delve settings that applies to all debugging sessions. Debug configuration in the launch.json file will override these values.
  "go.delveConfig": {
    "dlvLoadConfig": {
      "followPointers": true,
      "maxVariableRecurse": 1,
      "maxStringLen": 64,
      "maxArrayValues": 64,
      "maxStructFields": -1
    },
    "apiVersion": 2,
    "showGlobalVariables": true
  },

  // Pick 'godoc' or 'gogetdoc' to get documentation. Not applicable when using the language server.
  "go.docsTool": "godoc",

  // Experimental Feature: Enable/Disable entries from the context menu in the editor.
  "go.editorContextMenuCommands": {
    "toggleTestFile": true,
    "addTags": true,
    "removeTags": false,
    "testAtCursor": true,
    "testFile": false,
    "testPackage": false,
    "generateTestForFunction": true,
    "generateTestForFile": false,
    "generateTestForPackage": false,
    "addImport": true,
    "testCoverage": true,
    "playground": true,
    "debugTestAtCursor": true
  },

  // Feature level setting to enable/disable code lens for references and run/debug tests
  "go.enableCodeLens": {
    "references": false,
    "runtest": true
  },

  // Flags to pass to format tool (e.g. ["-s"])
  "go.formatFlags": [],

  // Pick 'gofmt', 'goimports', 'goreturns' or 'goformat' to run on format. Not applicable when using the language server. Choosing 'goimport' or 'goreturns' will add missing imports and remove unused imports.
  "go.formatTool": "goreturns",

  // Additional command line flags to pass to `gotests` for generating tests.
  "go.generateTestsFlags": [],

  // Enable gocode's autobuild feature. Not applicable when using the language server.
  "go.gocodeAutoBuild": false,

  // Additional flags to pass to gocode. Not applicable when using the language server.
  "go.gocodeFlags": [
    "-builtin",
    "-ignore-case",
    "-unimported-packages"
  ],

  // Used to determine the Go package lookup rules for completions by gocode. Only applies when using nsf/gocode. Latest versions of the Go extension uses mdempsky/gocode by default. Not applicable when using the language server.
  "go.gocodePackageLookupMode": "go",

  // Specify GOPATH here to override the one that is set as environment variable. The inferred GOPATH from workspace root overrides this, if go.inferGopath is set to true.
  "go.gopath": null,

  // Specifies the GOROOT to use when no environment variable is set.
  "go.goroot": null,

  // Folder names (not paths) to ignore while using Go to Symbol in Workspace feature
  "go.gotoSymbol.ignoreFolders": [],

  // If false, the standard library located at $GOROOT will be excluded while using the Go to Symbol in File feature
  "go.gotoSymbol.includeGoroot": false,

  // If false, the import statements will be excluded while using the Go to Symbol in File feature
  "go.gotoSymbol.includeImports": false,

  // Infer GOPATH from the workspace root.
  "go.inferGopath": false,

  // If true, then `-i` flag will be passed to `go build` everytime the code is compiled.
  "go.installDependenciesWhenBuilding": true,

  // Use this setting to enable/disable experimental features from the language server.
  "go.languageServerExperimentalFeatures": {
    "format": true,
    "autoComplete": true,
    "rename": true,
    "goToDefinition": true,
    "hover": true,
    "signatureHelp": true,
    "goToTypeDefinition": true,
    "goToImplementation": true,
    "documentSymbols": true,
    "workspaceSymbols": true,
    "findReferences": true,
    "diagnostics": true,
    "documentLink": true
  },

  // Flags like -trace and -logfile to be used while running the language server.
  "go.languageServerFlags": [],

  // Flags to pass to Lint tool (e.g. ["-min_confidence=.8"])
  "go.lintFlags": [],

  // Lints code on file save using the configured Lint tool. Options are 'file', 'package', 'workspace' or 'off'.
  "go.lintOnSave": "package",

  // Specifies Lint tool name.
  "go.lintTool": "golint",

  // Use gotype on the file currently being edited and report any semantic or syntactic errors found after configured delay.
  "go.liveErrors": {
    "enabled": false,
    "delay": 500
  },

  // 
  "go.playground": {
    "openbrowser": true,
    "share": true,
    "run": true
  },

  // Tags and options configured here will be used by the Remove Tags command to remove tags to struct fields. If promptForTags is true, then user will be prompted for tags and options. By default, all tags and options will be removed.
  "go.removeTags": {
    "tags": "",
    "options": "",
    "promptForTags": false
  },

  // Absolute path to a file containing environment variables definitions. File contents should be of the form key=value.
  "go.testEnvFile": null,

  // Environment variables that will passed to the process that runs the Go tests
  "go.testEnvVars": {},

  // Flags to pass to `go test`. If null, then buildFlags will be used.
  "go.testFlags": null,

  // Run 'go test' on save for current package. It is not advised to set this to `true` when you have Auto Save enabled.
  "go.testOnSave": false,

  // The Go build tags to use for when running tests. If null, then buildTags will be used.
  "go.testTags": null,

  // Specifies the timeout for go test in ParseDuration format.
  "go.testTimeout": "30s",

  // Environment variables that will passed to the processes that run the Go tools (e.g. CGO_CFLAGS)
  "go.toolsEnvVars": {},

  // Location to install the Go tools that the extension depends on if you don't want them in your GOPATH.
  "go.toolsGopath": "",

  // Complete functions with their parameter signature, including the variable types
  "go.useCodeSnippetsOnFunctionSuggest": false,

  // Complete functions with their parameter signature, excluding the variable types
  "go.useCodeSnippetsOnFunctionSuggestWithoutType": false,

  // Experimental: Use Go language server from Google or Sourcegraph for Hover, Definition, Signature Help, Auto Completion and Formatting features instead of tools like godef, gocode and goreturns
  "go.useLanguageServer": false,

  // Flags to pass to `go tool vet` (e.g. ["-all", "-shadow"])
  "go.vetFlags": [],

  // Vets code on file save using 'go tool vet'. Options are 'workspace', 'package or 'off'.
  "go.vetOnSave": "package",

### Describe the bug
I recently updated to GO 1.13.5.
Whenever I try to use a custom package which is in my $GOPATH/src directory, VSCode does not seem to be able to find it.
Thus, auto-complete does not work.
Even if I add the import path manually to the top of the import statements, VSCode removes it because it cannot find my package.

### Steps to reproduce the behavior:
As mentioned above

**Comment by ramya-rao-a** [comment]
@en-vee The settings you have shared are the default values for all Go related settings. What we are looking for are the ones you have edited/added. They will be available on the right side of the split view you see when running the command `Preferences: Open Settings (JSON)`.
