### ISSUE TITLE
Action "Restart  language server" doesn't work as expected when there are problems with `gopls`

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode-go#2951]
1. VS Code 1.41.0 
2. vscode-go 0.11.10-beta.5
3. gopls@master

Restart language server works __only__ if there are no problems with `gopls`. However it's obvious that when there are no problems nobody will even think to restart any moving part from the internals of IDE.

If `gopls` is stuck or hung which happens quite often, action "Restart language server" doesn't work at all. First run just does nothing - there is no output for `gopls` in "output" drop down list, there are no symbols or language features available. Second try to restart usually brings this message:

![изображение](https://user-images.githubusercontent.com/6797881/71096783-f587a880-21bf-11ea-9829-5901a5392e04.png). 
However 3rd or 4th try usually restarts it normally. But sometimes reload of entire VS Code may be required.

Related: #2633

**Comment by ramya-rao-a** [comment]
Thanks for reporting @inliquid 
There are some changes that were made to this command in the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension). Can you confirm you see the same here as well?

cc @stamblerre

**Comment by inliquid** [comment]
0.11.10-beta.5 seems to be latest beta.

**Comment by stamblerre** [comment]
Thanks for reporting. I'm not very familiar with the API here, but perhaps we need to add a delay and confirm that `gopls` has been shutdown before we try restarting it?

**Comment by stamblerre** [comment]
There have been a number of changes in the way the language server restart works since this issue was filed. @inliquid are you still seeing these types of errors?

**Comment by inliquid** [comment]
Haven't seen this quite for while, so I think I can close it.
