### ISSUE TITLE
Gotests console logging trimmed

### ISSUE THREAD

**Issue by leguminosa** [microsoft/vscode-go#2952]
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.12.7 linux/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.41.0 9579eda04fdb3a9bba2750f15193e5fafe16b959 x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	- <Paste Go extension version here>
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- `linux amd64`

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
1. Click on `run test` or just save the editor (if `go.coverOnSave` is enabled)
3. The writing (everything we see usually) in console output tab is...like somehow trimmed.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

![image](https://user-images.githubusercontent.com/38403278/71159472-4529ab00-2278-11ea-8c0c-78d4c77123ee.png)

**Comment by ramya-rao-a** [comment]
Please provide a small code snippet for the test you are running, expected output and actual output.
