### ISSUE TITLE
go.debug.cursor looses build tags

### ISSUE THREAD

**Issue by cfiderer** [microsoft/vscode-go#2953]
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	go version go1.12.9 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	1.41.0
        9579eda04fdb3a9bba2750f15193e5fafe16b959
        x64

- Check your installed extensions to get the version of the VS Code Go extension 
	0.11.9
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	windows amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
```
    "go.testTimeout": "5m",
    "go.enableCodeLens": {
        "references": false,
        "runtest": true,
        "go.delveConfig": {
            "maxStringLen": 128
        }
    },
    "go.delveConfig": {
        "useApiV1": false,
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 600,
            "maxArrayValues": 600,
            "maxStructFields": -1
        }
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "go.coverOnSingleTest": true,
    "go.installDependenciesWhenBuilding": false,
    "go.testFlags": [
        "-v",
        "-vet=off"
    ],
    "go.buildOnSave": "off",
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.autocompleteUnimportedPackages": true,
    "go.buildTags": "containers_image_openpgp",
    "go.testTags": "containers_image_openpgp"
```

### Describe the bug

I have bound the "Go: Debug Test at Cursor" command to Ctrl-F9.
I have code with tests, and I position the cursor inside a test function.

When clicking the "debug test" inject above the func line, everything is fine.
When hitting Ctrl-F9, the `dlv` debugger starts without build tags.

I expect `dlv` to be called with the same arguments on both ways.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @cfiderer 

The [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the fix for this bug. Can you please try it out and let us know how it goes? We will release an official update next week

**Comment by cfiderer** [comment]
Hello Ramya,

the Go-0.11.10-beta.6.vsix version fixes the bug; using “Go: Debug Test At Cursor” gets the required build tags.
Thanks for the fast response, and all the best for the New Year!

Christian

**Comment by ramya-rao-a** [comment]
The latest version of this extension (0.12.0) has the fix to this issue.

Thanks for reporting @cfiderer :)

Happy Coding!
