### ISSUE TITLE
Add setting to disable "Go Modules" status bar item

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode-go#2954]
**Is your feature request related to a problem? Please describe.**
I cannot selectively hide or disable the `📣 Go Modules` status bar icon.

**Describe the solution you'd like**
I would like a setting added: `go.enableModuleStatusBarIcon: bool`. This would default to `true`, but allow users to disable the status bar icon.

**Describe alternatives you've considered**
VSCode lets me hide status bar items, but that is per-extension, not per-item, so doing so prevents me from seeing *any* status bar items from this extension.

**Additional context**
I have seen #2925, but again, that setting is per-extension, not per-item.

**Comment by stamblerre** [comment]
Thanks for the report! I have filed it in our new repository: https://github.com/golang/vscode-go/issues/156, as we are migrating: https://github.com/microsoft/vscode-go/issues/3247.
