### ISSUE TITLE
Installing Go extension failure

### ISSUE THREAD

**Issue by GordonHK** [microsoft/vscode-go#2955]
Issue Type: <b>Bug</b>

go.toolsGopath setting is not set. Using GOPATH C:\Users\gordo\go
Installing 7 tools at C:\Users\gordo\go\bin in module mode.
  gocode
  gopkgs
  go-outline
  gocode-gomod
  godef
  goreturns
  golint

Installing github.com/mdempsky/gocode FAILED
Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/stamblerre/gocode FAILED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/sqs/goreturns FAILED
Installing golang.org/x/lint/golint FAILED

7 tools failed to install.

gocode:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/mdempsky/gocode
go: finding github.com/mdempsky/gocode latest
go: finding golang.org/x/tools latest
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40
go: finding github.com/mdempsky/gocode latest
go: finding golang.org/x/tools latest
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40

gopkgs:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/uudashr/gopkgs/cmd/gopkgs
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40

go-outline:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/ramya-rao-a/go-outline
go: finding github.com/ramya-rao-a/go-outline latest
go: finding golang.org/x/tools latest
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40
go: finding github.com/ramya-rao-a/go-outline latest
go: finding golang.org/x/tools latest
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40

gocode-gomod:
Error: Command failed: C:\Go\bin\go.exe build -o C:\Users\gordo\go\bin\gocode-gomod.exe github.com/stamblerre/gocode
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40

godef:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/rogpeppe/godef
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40

goreturns:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/sqs/goreturns
go: finding github.com/sqs/goreturns latest
go: finding golang.org/x/tools latest
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40
go: finding github.com/sqs/goreturns latest
go: finding golang.org/x/tools latest
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40

golint:
Error: Command failed: C:\Go\bin\go.exe get -v golang.org/x/lint/golint
go: finding golang.org/x/lint latest
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40
go: finding golang.org/x/lint latest
runtime
# runtime
c:\go\src\runtime\stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at c:\go\src\runtime\stubs_amd64x.go:10:6
c:\go\src\runtime\unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:321:40
c:\go\src\runtime\unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at c:\go\src\runtime\alg.go:329:40

Extension version: 0.11.9
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by stamblerre** [comment]
This looks like an issue with your Go installation. Do you have multiple Go installations? What is the output of `go version`?

**Comment by GordonHK** [comment]
Here you go!

`>go version
go version go1.13.5 windows/amd64`

**Comment by GordonHK** [comment]
Sorry about the belated reply. Please find the reply below.

`go version go1.13.5 windows/amd64`

**Comment by stamblerre** [comment]
Thanks. /cc @jayconrod for help on the Go command.
Can you run other `go` commands from the command line like `go build` or `go test`?
If not, it may be worth opening an issue on the [Go issue tracker](https://github.com/golang/go/issues/new).
