### ISSUE TITLE
When to support read var from stdin in debug mode

### ISSUE THREAD

**Issue by xieyuanhuata** [microsoft/vscode-go#2959]
I have verified it is OK which read stdin in debug mode on JetBrains GoLand 2019.2.3 x64, and the debugging tool is also dlv.
I think it is necessary！

**Comment by ramya-rao-a** [comment]
You can follow the discussion in #219 as to why this feature is not possible to implement in the current state of dlv.

I am not aware of how GoLand has implemented this using delve.

If anyone is able to implement the same in this extension, they are most welcome.

cc @quoctruong who conducted the investigation for this in #219
