### ISSUE TITLE
Some Go analysis tools are missing from your GOPATH

### ISSUE THREAD

**Issue by crazw** [Microsoft/vscode-go#296]
Hello, I am from china.
Because I cannot visit http://golang.org
When I install the extension of the following tools:
```
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v github.com/golang/lint/golint
go get -u -v github.com/lukehoban/go-outline
go get -u -v sourcegraph.com/sqs/goreturns
go get -u -v golang.org/x/tools/cmd/gorename
go get -u -v github.com/tpng/gopkgs
go get -u -v github.com/newhook/go-symbols
go get -u -v golang.org/x/tools/cmd/guru
```
It will be failed!
So I find a tool: [https://github.com/gpmgo/gopm](https://github.com/gpmgo/gopm)
and I intsall the need tools,eg: gocode、golint...
This is my GOPATH
![image](https://cloud.githubusercontent.com/assets/4703608/14581750/38bfad38-0427-11e6-829a-14d1ea29a5ff.png)
and I have installed this tools:
```
~/Github/go ☁  22:48:42
$ go list ./... | grep gocode
github.com/nsf/gocode

~/Github/go ☁  22:48:44
$ go list ./... | grep godef 
github.com/rogpeppe/godef
github.com/rogpeppe/godef/go/ast
github.com/rogpeppe/godef/go/parser
github.com/rogpeppe/godef/go/printer
github.com/rogpeppe/godef/go/scanner
github.com/rogpeppe/godef/go/sym
github.com/rogpeppe/godef/go/token
github.com/rogpeppe/godef/go/types

~/Github/go ☁  22:48:54
$ go list ./... | grep golint
github.com/golang/lint/golint

~/Github/go ☁  22:49:01
$ go list ./... | grep go-outline
github.com/lukehoban/go-outline

~/Github/go ☁  22:49:09
$ go list ./... | grep goreturns 
sourcegraph.com/sqs/goreturns
sourcegraph.com/sqs/goreturns/returns

~/Github/go ☁  22:49:16
$ go list ./... | grep gorename 
golang.org/x/tools/cmd/gorename

~/Github/go ☁  22:49:24
$ go list ./... | grep gopkgs  
github.com/tpng/gopkgs

~/Github/go ☁  22:49:31
$ go list ./... | grep go-symbols
github.com/newhook/go-symbols

~/Github/go ☁  22:49:38
$ go list ./... | grep guru      
golang.org/x/tools/cmd/guru
golang.org/x/tools/cmd/guru/serial
```
When I restart the vs code, 
it still notice me: 
**Some Go analysis tools are missing from your GOPATH. Would you like to install them?**
Can you give me some suggests?
Thank you so much!

**Comment by pdwx** [comment]
you can download tools package on
http://golangtc.com/download/package

**Comment by crazw** [comment]
@pdwx Thank you!

**Comment by lukehoban** [comment]
I can't tell from the report here what is going wrong in your setup - but it sounds like perhaps you found a solution.  I'm going to close this, but if you do still have any specific issue, please reopen.

**Comment by f839903061** [comment]
I  have the same problem !  China
vscode  version:1.18.1
It's auto install golang tools 20% successfully and 80% failed
目前我只能手动一个一个的安装了
