### ISSUE TITLE
configuration "go.vetFlags": ["-composites=false"] seems not having affect

### ISSUE THREAD

**Issue by AlieksandraK** [microsoft/vscode-go#2960]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.13.4 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.11.9
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- windows amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
settings.json file looks like:
{
    "go.vetFlags": ["-composites=false"],
}

### Describe the bug
With the configuration setting added 'go vet' still produces the warning "go.mongodb.org/mongo-driver/bson/primitive.E composite literal uses unkeyed fieldscomposites" for the piece of code:
filter := bson.D{
		{"id", id},
		{"columnname", value1},
	}

Go file with this code is located in the project folder: project/package/mygofile.go and it uses mongodb driver "go.mongodb.org/mongo-driver/bson" , "go.mongodb.org/mongo-driver/mongo"

**Comment by ramya-rao-a** [comment]
Apologies for the late response here

The extension doesnt do any vetting on its own. All it does is run `go vet` with the flags you provide, parse the output and show the errors/warnings. Therefore, I don't see what we can do from the extension's perspective to fix this.

You probably will see the same issue when you run the `go vet -composites=false` command in the terminal on the package. In which case I would recommend logging the issue for Go directly in the [Go issue tracker 
](https://github.com/golang/go/issues).

**Comment by ramya-rao-a** [comment]
If you don't see this issue when running `go vet -composites=false`, then please do log an issue and we can investigate further. Since [we are moving](https://github.com/microsoft/vscode-go#we-are-moving---), please log the issue at https://github.com/golang/vscode-go
