### ISSUE TITLE
code prompt not working when filling parameters

### ISSUE THREAD

**Issue by cjqpker** [microsoft/vscode-go#2961]
Code prompt not working when filling function parameters, and the background inside the brackets turns gray, is this a special input mode ?

<img width="617" alt="Screen Shot 2019-12-30 at 3 19 43 PM" src="https://user-images.githubusercontent.com/14192091/71572355-a0ca2300-2b19-11ea-821d-c988c9de4efe.png">

After hitting ESC twice, it works fine.
<img width="836" alt="Screen Shot 2019-12-30 at 3 36 39 PM" src="https://user-images.githubusercontent.com/14192091/71572479-4aa9af80-2b1a-11ea-8704-a0ad26cf0a2a.png">

**Comment by ramya-rao-a** [comment]
The special mode is called the snippet mode. In this mode completions are not enabled by default.
This is the nature of VS Code itself and is beyond the control of this extension.

I believe you can overwrite this behavior using the `editor.suggest.snippetsPreventQuickSuggestions` setting.
