### ISSUE TITLE
+build directives in go source files breaks code navigation

### ISSUE THREAD

**Issue by evadnoob** [microsoft/vscode-go#2962]
When source files include `// +build` directives, code navigation is broken. 

I also see this error:
```
[Error - 10:26:28 AM] Request textDocument/codeAction failed.
  Message: go/packages.Load: no packages found for file:///Redacted/Path/somefile.go
  Code: 0 
[Info  - 10:26:28 AM] 2019/12/30 10:26:28 go/packages.Load
	packages = 0
```

Removing the build directive comment and reload window and code navigation works(add it back and it breaks). 

Using gopls/Language Server
vscode version: Version: 1.41.1 (November update)
go extension: Using version `0.11.10-beta.6`
Project is using go modules, is outside GOPATH, and has a go.mod file.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @evadnoob 

@stamblerre Does `gopls` support the above scenario? Would it require to know build flags?

**Comment by stamblerre** [comment]
This falls under the category of https://github.com/golang/go/issues/29202. If you would like to develop in a file with build tags, you will have to add the following configuration to your VS Code settings:

```json5
"gopls": {
    "buildFlags": ["-tags=<your tags>"],
}
```

**Comment by stamblerre** [comment]
This issue is also pretty closely related to the discussion on https://github.com/microsoft/vscode-go/issues/2965, so maybe https://github.com/microsoft/vscode-go/issues/2965 could be used to track general issues related to build tags?

**Comment by ramya-rao-a** [comment]
Yes, we can use #2965 to continue the conversation around the `go.buildTags` setting and gopls.
Meanwhile, the workaround provided in https://github.com/microsoft/vscode-go/issues/2962#issuecomment-574792821 should be good enough for this issue.
