### ISSUE TITLE
Go configuration title

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode-go#2964]
Go is the only extension that put the word `configuration` in its title.
![image](https://user-images.githubusercontent.com/863731/71653470-e9a5f580-2d2c-11ea-85fe-fd69f244df64.png)

**Comment by hyangah** [comment]
I think the fix for it is included in v0.12.1 (I confirmed it's fixed in v0.12.1-beta2)

**Comment by ramya-rao-a** [comment]
The latest version of the extension (0.13.0) has the fix for this

Thanks for reporting @gertcuykens !
