### ISSUE TITLE
go.buildTags description does not warn that it is ignored when language server is used.

### ISSUE THREAD

**Issue by RobertBaruch** [microsoft/vscode-go#2965]
Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.4 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1
	- 26076a4de974ead31f97692a0d32f90d735645c0
	- x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux
	- amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

    "go.inferGopath": true,
    "go.lintTool": "revive",
    "go.formatTool": "goimports",
    "go.buildOnSave": "workspace",
    "go.buildTags": "integration",
    "go.lintOnSave": "workspace",
    "go.useLanguageServer": true,
    "go.languageServerFlags": [
        "-tags=integration"
    ],

### Describe the bug
go.buildTags is ignored when go.useLanguageServer is true. Instead, you have to set go.languageServerFlags.

Expected:
  Either go.languageServerFlags should automatically include the build tags, or there should be a warning in the description of go.buildTags, similar to  go.formatTool, which says "Not applicable when using the language server."

### Steps to reproduce the behavior:
1. Create two files in the same package with a build tag. One file should refer to public functions in the other file.
2. Set the language server to on.
3. Set go.buildTags to the build tag from step 1.
4. Do NOT change go.languageServerFlags.
5. You should end up getting a bunch of red lines for references to the public functions from step 1.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by RobertBaruch** [comment]
Oh, well now it looks like gopls doesn't even accept -tags :/

**Comment by stamblerre** [comment]
To pass `-tags` into `gopls`, your settings should look like this:

```json5
"gopls": {
    "buildFlags": ["-tags=integration"]
}
```

VS Code Go and `gopls` are not yet aligned on all settings.

**Comment by RobertBaruch** [comment]
OK, that works, so the main issue does remain: once the settings are aligned, either there should be a warning on go.buildTags, or go.buildTags should work with gopls.

**Comment by ramya-rao-a** [comment]
@stamblerre I haven't tried passing configuration to the language server from the extension. Do you know if it is possible for the extension to read the `go.buildTags` setting and somehow set the `gopls` setting when calling the language client?

**Comment by stamblerre** [comment]
Yes - I've looked into it, and it is possible. I have a few things that need to be finalized on the `gopls` end (https://golang.org/cl/212521), but I intend to use the `gopls` code directly to generate contents for vscode-go's `package.json`, and then to connect the middleware to pass in the relevant settings.

I'm still not sure if it's a good idea to reuse something like `"go.buildTags"` in the middleware, however. `gopls` still needs to expose its own configuration for build tags (for other editor clients), so what would the behavior be if a user has different settings in the `gopls.buildTags` and `go.buildTags` configurations?

**Comment by hyangah** [comment]
Given that there are functionalities and commands implemented outside gopls or language servers (e.g. cover, test, lint, ...), I think `go.buildTags` is needed outside the language server context. Having two different setting fields for build tags (and other configurations gopls may need to understand) is not ideal for users. How about letting the middleware append the value of `go.buildTags` to the `gopls.buildFlags` option for now as @ramya-rao-a suggests ? 

Maybe the tool (golang.org/cl/212521) can special case some fields so they are not touched when updating `package.json`.

**Comment by ramya-rao-a** [comment]
I would suggest the below

If both `gopls.buildTags` and `go.buildTags` are configured by the user, then the former wins.
If only `go.buildTags` is configured by the user, then the extension should do the needful to pass the same as `gopls.buildTags` to the language server

**Comment by ramya-rao-a** [comment]
@stamblerre, Can you log an issue at https://github.com/golang/vscode-go/issues regarding the next steps for this issue?

**Comment by stamblerre** [comment]
Yep - https://github.com/golang/vscode-go/issues/155.
