### ISSUE TITLE
Build is only building single file

### ISSUE THREAD

**Issue by Wingboy-Jim2** [microsoft/vscode-go#2967]
I have a package spread across multiple files within a directory.

Prior to the latest update I had no errors in any file.  Now each time I go to edit a file I get a litany of undeclared names.  They are not defined in the file being edited, but one of the other files in the directory.

This would appear to be related to the Dec 31 update.  Well, it might be rleated to the Dec 31 update, but it appears that the issue can be resolved by creating a go.mod file.   Apparently there has bene an update to gopls such that the module file is now required to pick up the other files when the is no module file and the the current directory is not in the gopath (unless something changed with an OS update and . got dropped from the path)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Wingboy-Jim2 

Since the upstream issue is already being looked at, I'll close this one.

@stamblerre Please let me know if you need this issue open to track any further work
