### ISSUE TITLE
rename is very slow

### ISSUE THREAD

**Issue by rana** [Microsoft/vscode-go#297]
Is there a faster way to rename? 
The current rename tool is very slow using vscode-go.
A rename can take near sixty seconds.

**Comment by paddie** [comment]
I also don't know if it is maybe my configuration for oracle (which I assume is being used) that is to blame. Does anyone else have this issue?

**Comment by rana** [comment]
I don't experience the issue anymore and I only upgraded. Unclear if there is a setting/state to create slowness or if it's resolved.

**Comment by paddie** [comment]
It takes around 10 seconds to rename, and then it runs forever until I
close the tab.

**Comment by ramya-rao-a** [comment]
@paddie Which platform are you on? I see the slowness in Windows but not in Mac

And also it is more slow when renaming symbols across files compared to renaming local symbols that are scoped to a single file

**Comment by paddie** [comment]
I did the renaming yesterday and it was significantly faster but there has
been at least one update since then. I assumed it was due to that update. I
can't be sure it wasn't just a local change though.

At the time of reporting it was on OS X, El Capitan with the latest
updates.

**Comment by mattetti** [comment]
Sounds like we should close this issue

**Comment by ramya-rao-a** [comment]
Thanks for the follow up @mattetti. Closing.

**Comment by jmhodges** [comment]
This is happening on Mac 10.12.6 with VSCode  for me. Maybe a large GOPATH problem? Not sure the best way to hook in profiling info. Imagine I'll just have to try to duplicate the gorename calls vscode-go is making?

**Comment by ramya-rao-a** [comment]
@jmhodges Yes, try running `gorename` in the command line on the same file. If that takes a long time, then there is nothing we can do from our side.
