### ISSUE TITLE
"Occurrences Highlight" doesn't work when vscode-go plugin is enabled

### ISSUE THREAD

**Issue by normal-cock** [microsoft/vscode-go#2972]
"Occurrences Highlight" doesn't work when vscode-go plugin is enabled.

- VSCode Version:1.41.1
- OS Version: Mac OS 10.15.2
- golang plugin: go 0.12.0
- java plugin: Language Support for Java(TM) by Red Hat 0.55.1

Does this issue occur when all extensions are disabled?: No

Steps to Reproduce:
1.  Occurrences Highlight doesn't work.
2. Disable go plugin.
3. Occurrences Highlight works normally.

![ScreenFlow2](https://user-images.githubusercontent.com/2618306/71900100-124c4600-3198-11ea-86e5-8fbba1a1bca5.gif)
**Click the image to get a normal size view**

My `Settings(JSON)` is:
```
{
    "window.zoomLevel": 0,
    "python.pythonPath": "/Users/dae/venv-python3/bin/python",
    "workbench.sideBar.location": "left",
    "files.eol": "\n",
    "workbench.tree.indent": 16,
    "workbench.colorTheme": "Monokai",
    "editor.fontSize": 14,
    "editor.scrollBeyondLastLine": false,
    "window.title": "${activeEditorFull}${separator}${rootName}",
    "editor.formatOnPaste": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "explorer.confirmDragAndDrop": false,
    "go.vetOnSave": "off",
    "go.formatTool": "goimports",
    "go.gocodeAutoBuild": false,
    "go.goroot": "/usr/local/go",
    "go.gopath": "/Users/dae/go",
    "powermode.enabled": true,
    "[markdown]": {
        "editor.defaultFormatter": "fcrespo82.markdown-table-formatter"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.factorypath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/Frameworks/**": true,
        "**/node_modules": true,
        "/Applications/XCode.app": true
    },
    "java.errors.incompleteClasspath.severity": "ignore",
    "vsintellicode.python.completionsEnabled": false,
    "vsintellicode.typescript.completionsEnabled": false,
    "vsintellicode.java.completionsEnabled": false,
    "python.autoUpdateLanguageServer": false,
    "markdown-toc.depthTo": 3,
    "extensions.ignoreRecommendations": false,
    "search.followSymlinks": false,
    "markdown-table-formatter.markdownGrammarScopes": [
        "markdown",
        "diagram"
    ],
    "editor.copyWithSyntaxHighlighting": false,
    "C_Cpp.loggingLevel": "Debug",
    "C_Cpp.workspaceParsingPriority": "low",
    "search.exclude": {
        "**/Frameworks": true
    },
    "C_Cpp.exclusionPolicy": "checkFilesAndFolders",
    "gitlens.advanced.messages": {
        "suppressFileNotUnderSourceControlWarning": true
    },
    "go.useLanguageServer": true,
    "go.lintOnSave": "off",
    "go.gotoSymbol.includeGoroot": true
}
```

**Comment by ramya-rao-a** [comment]
Please share any Go related settings you might have added or edited. You can get these by running the command `Preferences: Open Settings (JSON)`

**Comment by normal-cock** [comment]
I've add the `Setting(JSON)` below the image. @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Thanks @normal-cock 

@stamblerre This is mostly related to how the language server deals with highlighting. Can you take a look?

**Comment by stamblerre** [comment]
The highlight feature has been significantly improved in the current version of `gopls` (which is not yet released), but I don't believe that we support the case of highlighting an import and its uses. I'll file this issue upstream: https://github.com/golang/go/issues/36590.

**Comment by normal-cock** [comment]
Neither the case of highlighting an import and its uses is supported, nor `test2` in definition line is highlighted when cursor is placed around `test2` in `test` function as the following example shows. @stamblerre 
```golang
package main

import (
	"fmt"
)

type StructA struct {
	field1 bool
	field2 string
}

func (video *StructA) test() {
	fmt.Println("test")
	video.test2()
}

func (video *StructA) test2() {
	fmt.Println("test")
}

func main() {
	s := StructA{}
	s.test()
}
```

**Comment by stamblerre** [comment]
The issue with your `test2` example is already fixed at master and will be part of the next `gopls` release. You can try it out now by running master: `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@normal-cock We are closing this issue in favor of the upstream issue
