### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined at GoDebugSession.findPathSeperator.

### ISSUE THREAD

**Issue by farzonl** [microsoft/vscode-go#2974]
Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.13.5 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1
        - 26076a4de974ead31f97692a0d32f90d735645c0
        - x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin
        - amd64

### Share the Go related settings you have added/edited

no settings.json. have the following launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch remote",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "remotePath": "${workspaceRoot}",
            "port": 5000,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {},
            "args": [],
          }
    ]
}

### Describe the bug
A clear and concise description of what the bug.
when I try an launch a remote debugging with delv listening. I  get a
TypeError: Cannot read property 'includes' of undefined
    at GoDebugSession.findPathSeperator.
This looks to be a similar issue to: https://github.com/Microsoft/vscode-go/issues/1159, but as you can see in my lauch.json I have defined program.

I expect for the debugger to attach.
### Steps to reproduce the behavior:
3. See error

Try and launch a remote debugging session with the above launch.json.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/1802579/72095726-e29f5a00-32cd-11ea-936d-c3e18282cb68.png)

**Comment by quoctruong** [comment]
@farzonl, for the attach case, the extension is using `cwd` instead of `program` for the path. Can you change `program` to `cwd` and try again?

**Comment by farzonl** [comment]
@quoctruong thanks!  I don't get the type error anymore but ran into something new I will close and resolve this issue.
