### ISSUE TITLE
Attempting to [debug test] fails with "can't load package" error

### ISSUE THREAD

**Issue by oceanful** [microsoft/vscode-go#2975]
What version of Go, VS Code & VS Code Go extension are you using?

- Run `go version` to get version of Go
go version go1.13.6 darwin/amd64

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

- Check your installed extensions to get the version of the VS Code Go extension 
0.12.0

- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
darwin
amd64

### Share the Go related settings you have added/edited
    "go.useLanguageServer": true,
    "go.toolsEnvVars": {
        "GO111MODULE": "on",
    },
    "go.testEnvVars": {
        "GO111MODULE": "on",
    },
    "go.testFlags": [
        "-race",
        "-tags",
        "all debug fake",
    ],
 
### Describe the bug

When I click on the [debug test] link in any *_test.go file, I get an immediate failure with the following output in the Debug Console:

```
can't load package: package debug: no Go files in /usr/local/homebrew/Cellar/go/1.13.6/libexec/src/debug
can't load package: package fake: malformed module path "fake": missing dot in first path element
Process exiting with code: 1
```

And a dialog pops up:

```
Failed to continue: Check the debug console for details.
```

This is only happening for [debug test] links. I can successfully run the debugger on any main program.

Here's my `go env`:

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/ocean/go/bin"
GOCACHE="/Users/ocean/Library/Caches/go-build"
GOENV="/Users/ocean/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ocean/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/homebrew/Cellar/go/1.13.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/homebrew/Cellar/go/1.13.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qq/7ws9mntx1s1gqqwmqtwyn0480000gn/T/go-build091963543=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Any help is appreciated! Thanks!

**Comment by ramya-rao-a** [comment]
Are you able to debug the tests using the debug configuration?
You will need to create a new one for tests. The default one is for non tests files.

An example can be found at https://github.com/microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#sample-configuration-to-debug-a-single-test

**Comment by oceanful** [comment]
Thanks Ramya.

Yes, if I run `Debug -> Start Debugging` while viewing a test file, that works (and it runs all of the tests in the file). If I explicitly add a debug configuration for a single test (per the instructions you referenced), `Start Debugging` also works.

The problem only happens when using the `run test | debug test` links above the test method. `run test` works, but `debug test` results in an error. I'm actually getting slightly different error now:

```
can't load package: package 1: malformed module path "1": missing dot in first path element
can't load package: package debug: no Go files in /usr/local/homebrew/Cellar/go/1.13.6/libexec/src/debug
can't load package: package fake: malformed module path "fake": missing dot in first path element
Process exiting with code: 1
```

**Comment by ramya-rao-a** [comment]
It could be possible that a wrong file/folder path is being passed when `debug test` code lens is used. This would depend on your project folder structure.

Would you mind setting up a local dev environment of the Go extension and debug this locally?
Code pointers:

- [Set up dev env for extension](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- Add a breakpoint at https://github.com/microsoft/vscode-go/blob/master/src/goDebugConfiguration.ts#L127

Now debug the test using the code lens once and then using the debug configuration for a single test. In both cases the above breakpoint will be hit. Compare the value for the `debugConfiguration` variable and see if it differs for the two cases

**Comment by ramya-rao-a** [comment]
Re-opening to give @oceanful some more time to respond :)

**Comment by oceanful** [comment]
Thanks Ramya!

It turns out the issue was in my `go.testFlags`.

What I had:

```json
"go.testFlags": [
    "-race",
    "-tags",
    "all debug fake",
],
```

Should have been:

```json
"go.testFlags": [
    "-race",
    "-tags='all debug fake'",
],
```

So, silly operator error after all. Thanks again for helping me figure this out!

**Comment by ramya-rao-a** [comment]
You can also use `go.testTags` where you provide just the tag value

**Comment by oceanful** [comment]
That's helpful. Thank you!
