### ISSUE TITLE
canot work in online.visualstudio.com

### ISSUE THREAD

**Issue by fushang318** [microsoft/vscode-go#2977]
run
```
>Go: Current GOPATH
```
show error
```
command 'go.gopath' not found
```

vscode-go not support vsonline ?

**Comment by hyangah** [comment]
This extension requires go is installed.
It looks like Go is not one of the languages with general containers available. So, extra configuration is necessary.  
https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring

Would be cool if someone share their configuration :-)

**Comment by stamblerre** [comment]
Thank you for the report, @fushang318! I have filed https://github.com/golang/vscode-go/issues/157 upstream, as this repository is migrating: https://github.com/microsoft/vscode-go/issues/3247. Please follow along with that issue.
