### ISSUE TITLE
bad cache

### ISSUE THREAD

**Issue by harrybin815** [microsoft/vscode-go#2982]
I ran ```go test``` several times with the same result (although I set ```go test -count=1```), eventually removing everything from test and still running the cached content. I had to run ```go test``` from the terminal to get what I wanted to run.

There are other ways to disable caching entirely?

**Comment by wtask** [comment]
I set count=1 inside settings:
```
"go.testFlags": [
    "-count=1",
    "-v",
  ],
```
After this the test cache is not used when starting test from VSCode

**Comment by harrybin815** [comment]
> I set count=1 inside settings:
> 
> ```
> "go.testFlags": [
>     "-count=1",
>     "-v",
>   ],
> ```
> 
> After this the test cache is not used when starting test from VSCode

I also set this configuration.

```
    "go.testFlags": ["-v","-count=1"],
    "go.testEnvVars": {
        "GOCACHE": "off"
    },
```

**Comment by ramya-rao-a** [comment]
In the last release, we did refactor the code around how the test flags are used.
Can you use the previous release and let us know if the issue you are seeing existed before also or got introduced in the last release?

You can install the older version by using the command `Extensions: Install Specific Version of Extension`. Select the Go extension from the resulting drop down and then choose 0.11.9
