### ISSUE TITLE
Install/Update Tools does not list goimports when goreturns is the selected formatTool

### ISSUE THREAD

**Issue by UberFarmer** [microsoft/vscode-go#2983]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.13.4
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin amd64

### Describe the bug
Install/Update tools does not list or update goimports when `go.formatTool` is set to goreturns.

This is an issue because goreturns internally uses goimports, so you should really have an up-to-date version of goimports. However, your version of goimports will never get updated to latest.

### Screenshots or recordings
![Screen Shot 2020-01-15 at 11 50 46 AM](https://user-images.githubusercontent.com/8562683/72466226-4ffb3100-378d-11ea-8566-05541604f707.png)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @UberFarmer 

@stamblerre If `goreturns` has `goimports` listed as a dependency, then wouldn't installing/updating the former install/update the latter as well?

**Comment by stamblerre** [comment]
`goreturns` uses https://pkg.go.dev/golang.org/x/tools/imports, which is the `goimports` API, so it doesn't rely on the `goimports` binary in your `GOPATH`. Updating `goreturns` will update its dependency on `golang.org/x/tools/imports`, but it won't reinstall the binary.

**Comment by ramya-rao-a** [comment]
@stamblerre Would there be a need for the end user to update https://pkg.go.dev/golang.org/x/tools/imports explicitly?

**Comment by stamblerre** [comment]
I don't see any reason that there would be.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@UberFarmer Let us know if the above satisfies your concerns

**Comment by UberFarmer** [comment]
The bad behavior I ran into (which is why I filed this task) was that an old version of goimports was being used (and doing unexpected import grouping), and running "Go: Install/Update Tools" > select all > click "OK" did not fix it. (goreturns was the selected formatter).

After I switched the formatter to goimports and followed the same process of "Go: Install/Update Tools" > select all > click "OK", an up-to-date version of goimports was installed and my imports started being grouped correctly. Switching back to goreturns at this point kept the up-to-date goimports formatting.

I believe a fix is required so that Running Go: Install/Update Tools" > select all > click "OK" should give you the latest goimports behavior, even if goreturns is the current formatter.

**Comment by stamblerre** [comment]
How were you running `goimports` separately from `goreturns`? If your formatter was set to `goreturns`, it sounds like the issue was in the `goreturns` update. What is your Go version (`go version`)? It's possible that there is an issue with the way that Go tools are being updated in module mode, particularly since `goreturns` doesn't have a `go.mod` file.

**Comment by UberFarmer** [comment]
My go version is `go1.13.4 darwin/amd64`

I'm "running" `goimports` / `goreturns` just by saving my file. Here's my go config:
```
    "go.inferGopath": true,
    "go.gopath": "/Users/[username]/go-code",
    "go.lintTool": "golint",
    "go.lintFlags": [],
    "go.lintOnSave": "file",
    "go.formatTool": "goreturns",
    "go.formatFlags": [],
    "go.delveConfig": {
        "useApiV1": false,
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 128,
            "maxArrayValues": 10,
            "maxStructFields": -1
        },
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
        "editor.codeActionsOnSaveTimeout": 500000
    },
    "go.useLanguageServer": false,
```

Updating `goreturns` via "Go: Install/Update Tools" causes this output:
```
go.toolsGopath setting is not set. Using GOPATH /Users/[username]/go-code
Installing 1 tool at /Users/[username]/go-code/bin in module mode.
  goreturns

Installing github.com/sqs/goreturns SUCCEEDED

All tools successfully installed. You're ready to Go :).
```

**Comment by stamblerre** [comment]
If your `go.formatTool` is `goreturns`, then the `goimports` binary will not be invoked, so you should only need to update `goreturns`.
