### ISSUE TITLE
Smart select inside double quotes jumps to select the whole line

### ISSUE THREAD

**Issue by ayubmalik** [microsoft/vscode-go#2984]
When the cursor is inside a double quoted string in the editor and I expand the selection repeatedly using using smart select shortcut (Shift + Alt + Right Arrow), the selection does not stop when all the content inside the quotes  is selected, rather it jumps to select the whole line.

For example with the following valid go code:

`content := "some string here"`

if the cursor is anywhere inside the double quotes and I press Shift+Alt+Right Arrow twice, the selection 'jumps' and the whole line is selected. 

I would only expect the text inside the quotes to be selected _first_. This problem is specific to .go files as I **don't** have this problem with JavaScript files, the selection expands correctly.

Version information as below:
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-26-generic
```

The contents of my settings.json are:

```
{
    "breadcrumbs.enabled": false,
    "editor.folding": false,
    "editor.minimap.enabled": false,
    "editor.parameterHints.enabled": false,
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "all",
    "editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false
    },
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "files.autoSave": "afterDelay",
    "files.exclude": {
        "**/.bin": true,
        "**/.classpath": true,
        "**/.factorypath": true,
        "**/.gradle": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.vscode": true,
        "**/bin": true,
        "**/build": true
    },
    "files.trimTrailingWhitespace": true,
    "go.gopath": "/home/XXX/go",
    "go.toolsEnvVars": {
        "GO111MODULE":"auto"
    },
    "go.useLanguageServer": true,
    "go.vetFlags": [
        "-composities",
        "false"
    ],
    "telemetry.enableTelemetry": false,
    "workbench.activityBar.visible": true,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "window.menuBarVisibility": "default",
    "window.title": "${dirty}${separator}${activeEditorLong}${separator}${appName}",
    "window.zoomLevel": 0,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
}
```

**Comment by ayubmalik** [comment]
fixed example :(

**Comment by ramya-rao-a** [comment]
Thanks for reporting @ayubmalik 

This is most likely a feature from VS Code itself and is outside the control of this extension.
Please log an issue upstream at https://github.com/Microsoft/vscode

If it is determined that this needs to be solved based on the word pattern for the Go language, then the appropriate fix can be made in this extension at https://github.com/microsoft/vscode-go/blob/0.12.0/src/goMain.ts#L361

**Comment by jrieken** [comment]
> This is a feature from VS Code itself and is outside the control of this extension.
Please log an issue upstream at https://github.com/Microsoft/vscode

@ramya-rao-a It is in your control. The is the `SelectionRangeProvider`-API which an extension can implement. If that's missing then a heuristic is being used - and that's likely not always correct

**Comment by ramya-rao-a** [comment]
Thanks @jrieken 

@stamblerre Can you log an issue for `gopls` for implementing the `SelectionRangeProvider` via the language server?

**Comment by stamblerre** [comment]
Sure thing. This is a newer feature which is why we haven't added it yet. Filed an issue upstream.

**Comment by ramya-rao-a** [comment]
Thanks!

Closing this issue in favor of the upstream https://github.com/golang/go/issues/36679
