### ISSUE TITLE
golangci-lint output not shown in problems view if critical code error occured

### ISSUE THREAD

**Issue by pztrn** [microsoft/vscode-go#2985]
### What version of Go, VS Code & VS Code Go extension are you using?

* go version go1.13.6 linux/amd64
* VSCode 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, x64, WSL2, Ubuntu-18.04 image)
* go extension v0.12.0
* golangci-lint has version v1.22.2 built from (unknown, mod sum: "h1:iaihss3Tf6NvZVjun3lHimKSgofPV1+FqE/cbehoiRQ=") on (unknown)

### Share the Go related settings you have added/edited

```json
{
    "go.formatTool": "goimports",
    "go.gotoSymbol.includeGoroot": true,
    "go.gotoSymbol.includeImports": true,
    "go.lintOnSave": "workspace",
    "go.lintTool": "golangci-lint",
    "go.autocompleteUnimportedPackages": true,
    "go.coverOnSingleTest": true,
    "go.buildOnSave": "off",
    "go.vetOnSave": "off",
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "go.lintFlags": [
        "--fast"
    ]
}
```

### Describe the bug

When running golangci-lint as linter and some critical code error appeared (like missing parameter) - nothing shown in problems view. Yet golangci-lint prints error with file path and lineno, but not from the very beginning.

### Steps to reproduce the behavior:

Use that code:

```go
req, _ := http.NewRequest("GET", "https://microsoft.com")
```

As you can see there is clearly a problem - no third parameter which should implement ``io.Reader`` for reading request's body. Yet:

![изображение](https://user-images.githubusercontent.com/869402/72593473-de56ea80-3926-11ea-8f96-7927d5d3769a.png)

(No problems was found).

golangci-lint output about that problem:

```
% golangci-lint run
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/home/pztrn/projects/go/src/HOSTNAME/GROUP/PROJECT/internal/cache/clustering.go:51:121: too few arguments in call to http.NewRequest]
WARN [runner] Can't run linter goanalysis_metalinter: bodyclose: failed prerequisites: buildssa@HOSTNAME/GROUP/PROJECT/internal/cache
ERRO Running error: bodyclose: failed prerequisites: buildssa@HOSTNAME/GROUP/PROJECT/internal/cache
```

Even if I add ``--fast`` to linter parameters it shows up an error which should be somehow shown:

```
WARN [runner] Can't run linter goanalysis_metalinter: unparam: failed prerequisites: buildssa@HOSTNAME/GROUP/PROJECT/internal/cache
ERRO Running error: unparam: failed prerequisites: buildssa@HOSTNAME/GROUP/PROJECT/internal/cache
```

**Comment by pztrn** [comment]
If I'll enable ``go.vetOnSave`` (set to ``package``) - I'll see something like:

![изображение](https://user-images.githubusercontent.com/869402/72601923-2d594b80-3938-11ea-95c0-7d062d8128d9.png)

Can vscode-go run ``go vet`` if golangci-lint is used and exitcode != 0? In my examples golangci-lint exits with 3 and fast mode (with ``--fast`` added to linter parameters in vscode settings) doesn't produce file:lineno output, and running ``go vet`` is actually fast and doesn't load system too much.

Yes, I've enable running ``go vet`` on package and problem is "kind of" solved, but in terms of UX if I disable running ``go vet`` on file saving and will use golangci-lint as linter - vscode won't show any error which is a bad UX IMO.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @pztrn 

The idea was for build and vet on save features to surface any critical errors.
Linting results are parsed only on a successful run.

I see that you have disabled the `go.buildOnSave` setting. Can you share the motivation for this?

**Comment by pztrn** [comment]
Hey @ramya-rao-a 

I've disabled buildOnSave because it heats my laptop :) Linters are much less heat-producing and much faster.

**Comment by ramya-rao-a** [comment]
:) Fair enough.

What we can do is allow the critical failures from linters to show up if both `vetOnSave` and `buildOnSave` are disabled. PRs are most welcome to do this

Code Pointers:
- [Set up local dev environment for the extension](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- The `useStdErr` argument to `runTool()` at https://github.com/microsoft/vscode-go/blob/0.12.0/src/goLint.ts#L125 should be set to `true` when the errors from stderr needs to be parsed

**Comment by fastest963** [comment]
I was considering working on this but in my case I'm using gopls but I want to turn diagnostics off and leave it to my linter since gopls it seems to speed up gopls for now.

Would I still just be checking `buildOnSave` and `vetOnSave` or if they're using a language server are those flags ignored and should I be checking `diagnostics: false` instead?

**Comment by stamblerre** [comment]
Turning off diagnostics in `gopls` actually has no effect on its speed. It will compute the diagnostics either way - VS Code Go will just choose to hide them. For speed improvements with `gopls`, you can try out the latest pre-release by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.0-pre2`.

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Closing this issue in favor of https://github.com/golang/vscode-go/issues/121. Please subscribe to it for further updates and upvote it as well

Thanks for all the support & Happy Coding!
