### ISSUE TITLE
Debug Console can not input parameters.

### ISSUE THREAD

**Issue by skyterra** [microsoft/vscode-go#2986]
Issue Type: <b>Bug</b>

Hi, I need to input string data to debug my golang program, but the Debug Console can not be input.

Extension version: 0.12.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)

**Comment by ramya-rao-a** [comment]
This is a known limitation of this extension.
Please see #2959 and #219 for more details
