### ISSUE TITLE
Failed to Run "go env" to find GOPATH as the "go"binary.....

### ISSUE THREAD

**Issue by jnewton00** [microsoft/vscode-go#2989]
The version of GO I have installed is 0.12.0 and the version on VS code is 1.41.1 (user setup). I have the following error 

Failed to run "go env" to find GOPATH as the "go" binary cannot be found in either GOROOT(undefined) or PATH;

<Details>

Failed to run "go env" to find GOPATH as the "go" binary cannot be found in either GOROOT(undefined) or PATH(C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Users\theb0\AppData\Local\Microsoft\WindowsApps;C:\Users\theb0\.dotnet\tools;C:\Users\theb0\AppData\Local\Microsoft\WindowsApps;C:\Users\theb0\AppData\Local\GitHubDesktop\bin)

**Comment by jnewton00** [comment]
I have read through > https://github.com/Microsoft/vscode-go/issues/755 < yet to no avail. Any assistance appreciated.

**Comment by KaiRoesner** [comment]
Same over here, also with version 0.12.0. #1542 seems to be related, but doesn't help either...

**Comment by hyangah** [comment]
Where is the go command (not the VSCode Go extension) installed? Is the path included in the `PATH`?

**Comment by jnewton00** [comment]
I haven't installed go. I just installed it from VSCode. I assume I need a full go installation as I currently don't have any PATH configuration.

**Comment by stamblerre** [comment]
You will have to install Go separately from the VS Code Go extension - see https://golang.org/dl/. We should still probably improve this error message.

**Comment by jnewton00** [comment]
@stamblerre thanks I have done this now :) All good!!!!

**Comment by jnewton00** [comment]
Thanks All!!
