### ISSUE TITLE
Support golines as a formatter

### ISSUE THREAD

**Issue by yolken** [microsoft/vscode-go#2990]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
I recently released a new golang formatter that shortens long lines and aligns struct tags (on top of whatever is done by an underlying formatter like goimports): https://github.com/segmentio/golines. It would be nice to have it as an option in vscode since I think it could be useful for many. I'm happy to implement the change.

**Describe alternatives you've considered**
Using the existing formatters.

**Comment by ramya-rao-a** [comment]
Please see #2438 on how you can hook up any formatter to the Go extension without changing the extension itself.
