### ISSUE TITLE
"go to definition" should jump to vendor  if exist, even in go mod

### ISSUE THREAD

**Issue by mozhata** [microsoft/vscode-go#2991]
**Is your feature request related to a problem? Please describe.**
before switch to go module, I use vendor to keep my dependencies, and `go to definition` jump to vendor file if exist, this very convenient, I can check all files in that refered pkg to figure out more interesting thing.
 
but things not good when I switch to go modles, `go to definition` always jumpt  `xx/pkg/mod`, even a vendor exist in my project.

**Describe the solution you'd like**
I think It's a good idea to refer vendor first, if vendor not exist, then refer to `xx/pkg/mod`

**Comment by ramya-rao-a** [comment]
I believe this is being discussed in #1983
Please follow the discussions there.
