### ISSUE TITLE
Pass "dlv commands" from debug console to dlv

### ISSUE THREAD

**Issue by hashier** [microsoft/vscode-go#2992]
**Is your feature request related to a problem? Please describe.**

When I debug sometimes I want to see what the context of a struct is. The "variables" view to the top left often truncates things and sometimes doesn't even show every element of an array/list/slice. 
Screenshot shows a slice with 682 elements (according to dlv) but the "variables view" only shows the first 64 (0-64):
![Screenshot 2020-01-20 at 14 18 33](https://user-images.githubusercontent.com/92332/72730053-dbf7c900-3b90-11ea-8965-535224ae1544.png)
![Screenshot 2020-01-20 at 14 19 04](https://user-images.githubusercontent.com/92332/72730054-dbf7c900-3b90-11ea-9d7c-4cf26942f022.png)
![Screenshot 2020-01-20 at 14 23 27](https://user-images.githubusercontent.com/92332/72730055-dc905f80-3b90-11ea-8d73-59b2a8ba9837.png)

So to access anything over 64 I use the debug console with for example: `userlist.Members[123]
` which then returns me a one liner of the element, which then I have to use the mouse again to "unfold" all the struct nesting to dig down into the struct. Here it would be helpful if I could just use the dlv command
```
(dlv) print userlist.Members[123]
```
to get directly the printed out the whole struct and all nested structs.

**Describe the solution you'd like**

Forwarding dlv commands from the debug console to dlv and print the output.

**Describe alternatives you've considered**

Right now I use the mouse a lot to click down into nested structs. It is possible, but sometimes I find myself using dlv on the console when it gets too much clicking on the debug console.

Alternatively, maybe expand the whole structs and sub structs directly when writing the name of the variable in the debug console? (See screenshot below. By default everything is collapsed and I have to press 2 times to see the whole struct)

**Additional context**

Additional screenshot, that shows the "button" (red circle) I have to click to open the struct. If I want to inspect 5 elements I have to click 10 buttons. With even more nested structs this gets quickly into a lot of clicking.
![Screenshot 2020-01-20 at 14 31 00](https://user-images.githubusercontent.com/92332/72730547-e4043880-3b91-11ea-9858-d63c01114e7f.png)

PS: Another thing that is tiresome is, that if I type `userlist.Members[64]` and then click to unfold the struct, I have to scroll down, click the nested struct, and scroll down again. It took me a while to actually figure out that I could click down into the nested structs because the console doesn't scroll if I open a struct.

**Comment by ramya-rao-a** [comment]
cc @quoctruong

**Comment by A-UNDERSCORE-D** [comment]
As an additional thing this would help, as I understand it there is no function call support on VScode's side, whereas [delve supports it with the `call` command](https://github.com/go-delve/delve/blob/master/Documentation/cli/README.md#call) (related: https://github.com/microsoft/vscode-go/issues/2655, https://github.com/go-delve/delve/issues/119)

Ive found myself repeatedly looking for the result of some diagnostic function while working on code

**Comment by lggomez** [comment]
The console commands when sent trigger an [EvaluateRequest](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) method of the debug adapter, which instead calls [Eval method](https://godoc.org/github.com/derekparker/delve/service/rpc2#RPCServer.Eval) of the delve RPC server

As a first step, we would need to execute the call command from the debug adapter client as calling the CLI command isn't viable here. I can't seem fo find it exposed by the the RPC API, so we have to check with the delve team if the functionality es present and equivalent in the v2 API

Then, we need to decide how to tell apart function calls from expressions, and that will be the most tricky part as we don't have any explicit UI support for that

**Comment by hyangah** [comment]
I want this feature too!

https://github.com/golang/vscode-go/issues/100 discusses the `call` command support already. Let's continue discussing this there.
