### ISSUE TITLE
Go fmt on save workflow

### ISSUE THREAD

**Issue by kylebrandt** [Microsoft/vscode-go#30]
Coming from working with Go in sublime I'm used to a workflow where every save runs go fmt. In my particular case, I also have save on loss of focus (but seems like VSCode's autosave fulfills this). That way if I switch to a terminal it is saved before I do something in the terminal.

I use this workflow in two main different ways I can think of now:
 - I've got lazy to the point where I might not even indent code when typing it, since once it saves it will fmt. 
 - I use the change in formatting as a signal that there are no syntax errors in my code, because the format won't run otherwise.

So fmt as a commit hook is later than I would like in the workflow I'm used to. Is it possible to get the fmt on save workflow in VSCode as it stands? If not maybe this could be a feature? Or do you think I'm just "doing it wrong"?.

I've also seen this come up in /r/golang and it was a comment on the recent HN post: 'Awesome! Last time I tried VSC it had no gofmt-on-save functionality which I consider mandatory. Now that it does have that and much more, I'm very much looking forward to trying it again.'

**Comment by adamjedlicka** [comment]
At the moment you can use ctrl+shift+i (format code), but yeah automatic go fmt on save would be super useful.

**Comment by fsomers** [comment]
+1 on that - again, coming from Sublime, and tripping over our CI format checker on all my commits now that I've come to rely on auto gofmt :)

**Comment by mattetti** [comment]
This is already tracked in https://github.com/Microsoft/vscode-go/issues/14 and it's on the roadmap (feel free to contribute, I'm sure @lukehoban would appreciate any help)

**Comment by jchannon** [comment]
Yeah I think close this as its already tracked in the other ticket

**Comment by fsomers** [comment]
(oops - sorry - hadn't seen the other ticket)
