### ISSUE TITLE
Is any way to debugging application with input in CLI?

### ISSUE THREAD

**Issue by kkdai** [Microsoft/vscode-go#300]
Hi,

I would like to debugging some CLI with stdin input, but I could debugging it.
I saw there is a input (I don't know what it call)  under the "Debug Console", but it doesn't work.
Any suggestion or direction how to do it?

Here is what I have tried:

-  Change `launch.json` : "mode" to "remote" with specific file address on local and local port, but not working.
-  Change `launch.json` : "request" to "attach", but not working.

By the way, I saw here describe on README.md 

    [partially implemented] Debugging (using delve)

Any specific information about the debugging support list?

**Comment by lukehoban** [comment]
I believe this is being tracked in https://github.com/Microsoft/vscode-go/issues/219 and that all of the approaches you could take are currently blocked by missing features in the Go debugging implementation.  Hopefully we can get some of those addressed soon.

I'll close this one out and keep the discussion in #219 for now.
