### ISSUE TITLE
CodeLens references do not work in module mode if it is in another file

### ISSUE THREAD

**Issue by karim** [microsoft/vscode-go#3003]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.6 windows/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	- `0.12.0`
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- `windows amd64`

### Share the Go related settings you have added/edited

```json
"go.useLanguageServer": true,
"go.languageServerExperimentalFeatures": {
    "documentLink": false,
},
"gopls": {
    "completeUnimported": true,
    "hoverKind": "FullDocumentation",
    "staticcheck": true,
},
"go.enableCodeLens": {
    "references": true,
    "runtest": true
}
```

### Describe the bug

Showing references does not work in module mode if they are in different files.

![2](https://user-images.githubusercontent.com/8761081/73134000-92e4c080-4039-11ea-833f-72005c563fcb.png)

However, if I moved the function to the same file it works.

![3](https://user-images.githubusercontent.com/8761081/73134007-b0b22580-4039-11ea-9570-acc4cbb946ee.png)

Or if I moved the whole project inside `GOPATH`.

![1](https://user-images.githubusercontent.com/8761081/73134016-dccda680-4039-11ea-8809-cfd759dee3f4.png)

**Comment by stamblerre** [comment]
This is probably because the references codelens relies on the default references provider, which I would guess doesn't work with modules (see [here](https://github.com/microsoft/vscode-go/blob/9dc503792fdb651b9103aeda7fba9da26dff872b/src/goReferencesCodelens.ts#L65)). We should be able to get the references provider from the language server if it's in use. Does that sound right to you, @ramya-rao-a?

**Comment by ramya-rao-a** [comment]
The catch is in figuring out if the extension can call the reference provider from the language server.
Am not sure if that is possible..

I would suggest that we start looking into the language server it self implementing the code lens

**Comment by stamblerre** [comment]
That sounds reasonable. Filed https://github.com/golang/go/issues/36787 to track this upstream.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@karim Closing this issue in favor of the upstream issue logged above.
There is no further work in `guru` to fix references in module mode, so we will need to wait for `gopls`, the language server to support this.
