### ISSUE TITLE
gopls returning completely unrelated completions

### ISSUE THREAD

**Issue by alecthomas** [microsoft/vscode-go#3005]
Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.13.5
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin amd64

### Share the Go related settings you have added/edited

```
    "go.lintTool": "golangci-lint",
    "go.lintFlags": [
        "--fast",
        "--disable=goimports"
    ],
    "go.toolsGopath": "/Users/aat/go",
    "editor.snippetSuggestions": "bottom",
    "editor.lineNumbers": "off",
    "go.coverageDecorator": {
        "type": "gutter",
        "coveredHighlightColor": "rgba(64,128,128,0.5)",
        "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
        "coveredGutterStyle": "blockgreen",
        "uncoveredGutterStyle": "blockyellow"
    },
    "go.autocompleteUnimportedPackages": true,
    "go.formatTool": "goimports",
    "go.formatFlags": [
        "-local",
        "git.sqcorp.co"
    ],
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "diagnostics": true,
        "documentLink": true
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
        "editor.codeActionsOnSaveTimeout": 3000,
    },
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function
        // Experimental settings
        "completeUnimported": true, // autocomplete unimported packages
        "watchFileChanges": true, // watch file changes outside of the editor
        "deepCompletion": true, // enable deep completion
    },
```

### Describe the bug

Completion works for some period then starts failing randomly, returning unrelated completions, then completely ceases to work.

### Steps to reproduce the behavior:

I don't believe I'm doing anything too exotic. Just using completion on a smallish sized project (3.2K lines).

### Screenshots or recordings

First it starts failing intermittently like so:

![image](https://user-images.githubusercontent.com/41767/73155538-2c41ce80-412f-11ea-984b-63ea9000ee5a.png)

Tap ".":

![image](https://user-images.githubusercontent.com/41767/73155571-41b6f880-412f-11ea-8c90-c04b20efb474.png)

Tap "I" (just to see what happens):

![image](https://user-images.githubusercontent.com/41767/73155886-24365e80-4130-11ea-8802-521746a2a833.png)

But eventually it fails completely and completions no longer work at all. Killing gopls resurrects it briefly.

Contrast this with another symbol in the same scope, which works fine:

![image](https://user-images.githubusercontent.com/41767/73155957-521ba300-4130-11ea-99da-633ea565c18f.png)

**Comment by alecthomas** [comment]
I opened up the gopls console to check if different errors would be reported for the two cases, but they are identical with both reporting:

```
[Error - 6:15:08 pm] Request textDocument/codeAction failed.
  Message: /Users/aat/Projects/buildkit/script.go:413:2: expected selector or type assertion, found 'return' (and 1 more errors)
  Code: 0 
```

**Comment by stamblerre** [comment]
What are your expected results in the failing cases above? It's not clear to me why these results are incorrect. Also, please note that completion may not always work perfectly when your code is in a broken state. Specifically, if there is a syntax error, completion may not pick up any symbols declared below the syntax error. We are working on improving this, but these are some current limitations.

Can you share your `gopls` logs when completion begins to fail? Instructions on how to capture them can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

**Comment by alecthomas** [comment]
In the first example you can see `it.Iterate()`. This is correct. As soon as I press `.` this disappears and a completely unrelated *package* is suggested.

Using a different symbol (thread) in the exact same location is successful (last image).

There are no syntax errors beyond those introduced by me typing in these symbols.

The only relevant log line (AFACT) is the one I already pasted, but I can get the rest if you really need it.

**Comment by stamblerre** [comment]
Thanks for the explanation. This does seem like a genuine failure with completion. What version of `gopls` are you using (`gopls version`)?

The log line you've pasted here is actually not relevant, as it pertains to `textDocument/codeAction` rather than `textDocument/completion`. You will likely not see all of the relevant log line until you add the following setting to your `settings.json`:

```json5
"go.languageServerFlags": [
  "-rpc.trace"
]
```
