### ISSUE TITLE
IntelliSense failed

### ISSUE THREAD

**Issue by Limitless-loong** [microsoft/vscode-go#3007]
Issue Type: <b>Bug</b>

`fmpl=>fmt.Println($1)` => no IntelliSense when you following type unless move cursor

Expect：have IntelliSense

Extension version: 0.12.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by ramya-rao-a** [comment]
Please share any Go related settings you might have added or edited. You can get these by running the command `Preferences: Open Settings (JSON)`

**Comment by Limitless-loong** [comment]
`"go.autocompleteUnimportedPackages": true,`
`"go.formatTool": "goimports",` 
`"go.useLanguageServer": true,`

**Comment by stamblerre** [comment]
Is `"fmt"` imported in your program in this case? `"go.autocompleteUnimportedPackages": true` doesn't get propagated to `gopls`, so you will also need the following setting:

```json5
"gopls": {
    "completeUnimported": true
}
```

See https://github.com/golang/tools/blob/master/gopls/doc/vscode.md for more information on recommended settings with `gopls` and VS Code.

**Comment by Limitless-loong** [comment]
`fmt` is imported in my program in this case. 
fmpl=>fmt.Println($1) => no IntelliSense when you following type and your input is selected in this case,  unless move cursor.

**Comment by stamblerre** [comment]
Do you mind providing a repro case or a screenshot/screencast with your example? I'm afraid I don't understand what you mean when you say that you have to move your cursor to get Intellisense.

**Comment by Limitless-loong** [comment]
This is an example.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rebecca Stambler"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月28日(星期二) 下午2:45
收件人:&nbsp;"microsoft/vscode-go"<vscode-go@noreply.github.com&gt;;
抄送:&nbsp;"俩龙"<limitless-loong@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode-go] IntelliSense failed (#3007)




Do you mind providing a repro case or a screenshot/screencast with your example? I'm afraid I don't understand what you mean when you say that you have to move your cursor to get Intellisense.

**Comment by Limitless-loong** [comment]
This is an example.

![Image of example](http://chuantu.xyz/t6/713/1580212919x2073530529.gif)

**Comment by stamblerre** [comment]
Are you referring to the fact that completions for `year`, `month`, and `day` don't come up as you start typing? In this case, this isn't the Intellisense failing, but rather VS Code not triggering completions. You can manually trigger them by hitting Ctrl + Space.

To have them come up automatically, we would need to have another command associated with the completion item, which isn't currently possible as far as I can tell. I filed https://github.com/microsoft/language-server-protocol/issues/905 to get this question answered.

**Comment by Limitless-loong** [comment]
Yes, you're right. That's exactly what I expected.

**Comment by stamblerre** [comment]
We can handle this by following the suggestion in https://github.com/microsoft/language-server-protocol/issues/905#issuecomment-580247602.

@ramya-rao-a: The label for this issue could be changed to `needs-fix`, since the first change necessary to implement this would have to be in VS Code Go, and not in `gopls`.

**Comment by stamblerre** [comment]
Filed a new issue to track this upstream. Going to close this issue in favor of https://github.com/golang/vscode-go/issues/49.
