### ISSUE TITLE
Vscode Go Extension Occasionally Corrupting File On Save

### ISSUE THREAD

**Issue by johneboldt** [microsoft/vscode-go#3008]
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.4 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- windows amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
```
    "go.useLanguageServer": true,
    "go.coverOnSave": true,
    "go.autocompleteUnimportedPackages": true,
    "go.gotoSymbol.includeImports": true,
    "go.buildOnSave": "package",
    "go.lintOnSave":"off",
    "go.vetOnSave": "package",
```

### Describe the bug
A clear and concise description of what the bug.
The go extension occasionally corrupts a .go file on save. There is no clear repeatable path; it just happens intermittently. I have isolated the issue to the go extension; when I disable the extension, the issue does not occur.

I expect VS Code to save the file as is without removing random characters.

### Steps to reproduce the behavior:
1. Open a .go file
2. Make at least one change
3. Save the file (I normally use ctrl-s).
4. Occasionally, BUT NOT ALWAYS, the extension will drop random characters and the file becomes corrupt.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by stamblerre** [comment]
Can you try downloading the pre-release of `gopls/v0.3.0` to see if it fixes the problem? It can be installed by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.0-pre1`.

**Comment by johneboldt** [comment]
> Can you try downloading the pre-release of `gopls/v0.3.0` to see if it fixes the problem? It can be installed by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.0-pre1`.

I tried this and so far so good. It will require us to shift to using go modules (which is a good thing) but I want to proceed cautiously.

**Comment by stamblerre** [comment]
Using `gopls` doesn't actually require users to switch to modules - it should work in GOPATH mode as well. You just need to install it with modules on for that one command.

**Comment by johneboldt** [comment]
Thanks @stamblerre - I switched back to GOPATH mode and had VSCode update to the latest gopls version. Everything, including formatting and linting on save, is working much better now. I will monitor over the weekend and close this issue if I don't have any problems.

**Comment by stamblerre** [comment]
Glad to hear it! Thank you for checking back in.

**Comment by gittim** [comment]
I'm seeing this too. go version go1.13.4 windows/amd64, VS Code 1.41.1. Tried with deployed gopls & the 0.3.0-pre1 suggested above. Removing gopls stops the corruption. With gopls in the last week or so, saving removes some characters at the start of lines, others from middle. e.g. (original, corrupted):

func (c *Cache) HandlePktImpl(pkt []byte) *StreamData {
	//timrSafeStop(&(c.timrGC))
corrupts to:
func (c *Cache) andlePktImpl(pkt []byte) *StreamData {
	/timrSafeStop(&(c.timrGC))

Note missing 'H' and forward slash.

**Comment by johneboldt** [comment]
@gittim that is exactly what was happening to me. Following @stamblerre 's advice seems to have fixed the problem - just make sure that VSCode recognizes the new gopls and updates to it.

Thanks for your help everyone!

**Comment by hyangah** [comment]
Echoing what @johneboldt said - @gittim `v0.3.0` is the official release. The vscode-go extension should pick up the new version. Plz report an issue otherwise. v0.3.0 official release includes a fix for Windows found in the prerelease versions such as `v0.3.0-pre1`.

**Comment by gittim** [comment]
Hello @hyangah I'm still getting corruption. My gopls version "golang.org/x/tools/gopls v0.3.0
    golang.org/x/tools/gopls@v0.3.0 h1:l9KKK1/n6CIbfgaUvHBWAvCfOxcl1N+KSOK79OlPIao="

I've uninstalled and re-installed both Go and Visual Studio Code. I also have Visual Studio Enterprise 2019 installed, in case this is something to do with it. Go env gives this:

d:\code\go\bin>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\tim\AppData\Local\go-build
set GOENV=C:\Users\tim\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=d:\code\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\tim\AppData\Local\Temp\go-build866335826=/tmp/go-build -gno-record-gcc-switches

**Comment by hyangah** [comment]
@gittlm thank you for the update. Since this issue is closed, why don't we create a new issue and discuss your case more thoroughly? https://github.com/microsoft/vscode-go/issues/new?assignees=&labels=&template=bug_report.md&title=

Thanks!
