### ISSUE TITLE
Supporting relative paths in breakpoints with Delve

### ISSUE THREAD

**Issue by yalcinmelihyasin** [microsoft/vscode-go#3011]
Currently, I could not find a way support relative paths when trying to attach Delve debugger.

Example case:

Lets assume that your build configuration converts all the paths to relative such as

<project_dir>/server/server.go -> server/server.go
<project_dir>/client/client.go -> client/client.go

I have thought of using the `cwd' in launch.json as '${workspaceFolder}' and leaving the remote path empty. But then the local path is not removed from the file path. But if I do 
```
"cwd": "${workspaceFolder}/server",
`"remotePath": "server/", 
```
then it converts to path to `server/server.go` but in this case only the files under `server` directory can be put breakpoints.

Another issue is, if I use this setting,

```
"cwd": "${workspaceFolder}/server/",
`"remotePath": "server", 
```

then the path separator for remote path defaults to `\` as there is no information to parse the path separator in remote path. The end result become `\server\server.go`

It would be nice to have a capability of sending relative path to delve. A suggestion would be, when it is empty remote path, VSCode should still trim the cwd from the filepath and maybe should have another parameter to get path separator for remote.

**Comment by tschundler** [comment]
Seems related to #2908

**Comment by hyangah** [comment]
@yalcinmelihyasin 

I don't know what's the best way to handle the arbitrary file mappings like 
```
<project_dir>/client/client.go -> database/database.go
```
This seems more than the relative path mappings. I guess this is a typo?

@quoctruong, can you please take a look if your plan on utilizing `ListSources`/`ListPackagesBuildInfo` can handle the correct remote path separator inference and mapping in this case?

**Comment by yalcinmelihyasin** [comment]
@hyangah thanks for pointing it out. Yes it was a typo. I have edited the original post as well. It should be `client/client.go`

**Comment by quoctruong** [comment]
@hyangah It should work for this case in theory but I need to test it out more. @yalcinmelihyasin Can you share the build command that you use?

**Comment by yalcinmelihyasin** [comment]
we use bazel for building.

**Comment by quoctruong** [comment]
@yalcinmelihyasin This is now fixed in the nightly Go build (https://github.com/golang/vscode-go). Please give it a try: https://github.com/golang/vscode-go/blob/master/docs/nightly.md

**Comment by stamblerre** [comment]
Please follow the discussion on https://github.com/golang/vscode-go/issues/45 or [file a new issue](https://github.com/golang/vscode-go/issues/new?assignees=&labels=&template=bug_report.md&title=) if this still isn't working for you.
