### ISSUE TITLE
package.json: vscode-language-client dependency requires VS Code 1.41

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-go#3019]
Just noticed this when trying out the beta. Some companies may not be running the latest version of VS Code, and as such may not support the new client library. I'm not sure if this is a release blocker, or if we should just require that users upgrade their VS Code versions.

**Comment by stamblerre** [comment]
@ramya-rao-a: Is there anyway to make the update conditional on the user's version of VS Code? Otherwise, I think we should probably downgrade it.

**Comment by ramya-rao-a** [comment]
The `engines` field determines the lowest version of VS Code that will get the latest version of the extension (either via auto update, or manual update).
This field has `1.30.0`.

Where does it say that the latest `vscode-languageclient` requires 1.41 of VS Code?

**Comment by hyangah** [comment]
I think this is the place: https://github.com/microsoft/vscode-languageserver-node/blob/4c0963d6fdfd657044092c5d4db61a87b54471ef/client/src/main.ts#L43

We got an error like the following and failed to start the language server. 
<pre>
rejected promise not handled within 1 second: Error: The language client requires VS Code version ^1.41.0 but received version 1.39.2
extensionHostProcess.js:787
stack trace: Error: The language client requires VS Code version ^1.41.0 but received version 1.39.2
	at LanguageClient.checkVersion (/usr/local/google/home/hakim/project/vscode-go/node_modules/vscode-languageclient/lib/main.js:122:19)
	at new LanguageClient (/usr/local/google/home/hakim/project/vscode-go/node_modules/vscode-languageclient/lib/main.js:103:18)
	at Object.<anonymous> (/usr/local/google/home/hakim/project/vscode-go/out/src/goLanguageServer.js:64:19)
	at Generator.next (<anonymous>)
	at fulfilled (/usr/local/google/home/hakim/project/vscode-go/out/src/goLanguageServer.js:9:58)
	at process._tickCallback (internal/process/next_tick.js:68:7)
extensionHostProcess.js:787
</pre>

**Comment by ramya-rao-a** [comment]
https://github.com/microsoft/vscode-languageserver-node/blob/master/client/package.json#L8 is where it is defined that 1.41 is the min version of VS Code needed to support the latest version of the language client

Usually, I keep at least current VS Code version minus 3 to 4 versions as the min version of VS Code supported by the latest version of the Go extension. Therefore, unless there is a feature of the language client that is only available in v6 and is critical to `gopls`, I'd say we should revert the change in #2988
