### ISSUE TITLE
Find References does not work on build 1.0 and insider build as well

### ISSUE THREAD

**Issue by billshu** [Microsoft/vscode-go#302]
I tried both VSCode 1.0 and latest insider build, the "Find All References" doesn't work at all, it always shows message "No results", I already installed guru. I am running the latest Windows 10 build 14316. GOPATH and GOROOT are properly set.

**Comment by lukehoban** [comment]
I cannot repro this on several machines, including VSCode 1.0 on Windows 10 14328.  Can you provide more details?

**Comment by billshu** [comment]
Then can I know what do I need to do to make "Find All References" work for Go code? When I first run, there is a prompt suggest me to go get some go tools, I think it's guru, I did that, the prompt is gone, but "Find All References" still don't work.

**Comment by billshu** [comment]
The "Find All Reference" works on Linux version of VS Code. So I inclined to think this is a go on Windows issue itself, not the extension. Thanks for your help anyway.
