### ISSUE TITLE
Method names don't show in breadcrumbs, only function names

### ISSUE THREAD

**Issue by sampart** [microsoft/vscode-go#3021]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.7 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- Those commands didn't work for me on MacOS, but here's what the About box says:
> Version: 1.41.1
> Commit: 26076a4de974ead31f97692a0d32f90d735645c0
> Date: 2019-12-18T14:57:51.166Z
> Electron: 6.1.5
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Darwin x64 19.2.0
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin
amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

```
"go.useLanguageServer": true,
```

### Describe the bug

If I'm in the body of a function in Go, the function's name is shown in the breadcrumbs.  Example:

In

```
func NewResultsServer(...)
```

I see

![image](https://user-images.githubusercontent.com/1507328/73535253-0b24fa80-441b-11ea-8c6a-8ef60b9d6f44.png)

However, if I'm inside a *method*, the function name is not shown.  For example, in

```
func (s *ResultsResolver) GetAll(...)
```

the breadcrumbs look like this:

![image](https://user-images.githubusercontent.com/1507328/73535323-33acf480-441b-11ea-8034-405facc4d99d.png)

Furthermore, the menu which appears when clicking `...` only includes functions, not methods.

### Steps to reproduce the behavior

See description above.

### Screenshots or recordings

See description above.

**Comment by sampart** [comment]
Turning off `"go.useLanguageServer": true,` solved this.

**Comment by hyangah** [comment]
@stamblerre When using gopls, the breadcrumbs behave as @sampart described. We should take a look.

**Comment by stamblerre** [comment]
Filed https://github.com/golang/go/issues/36949 to track this issue. By the way, @sampart: Turning off the language server may have additional consequences beyond this issue, particularly if you are using modules.

**Comment by sampart** [comment]
@stamblerre thanks for the heads-up, and for filing the issue 👍
