### ISSUE TITLE
Defined alternate tools should be skipped by the Install/Update Tools command

### ISSUE THREAD

**Issue by jlucktay** [microsoft/vscode-go#3024]
**Is your feature request related to a problem? Please describe.**
If an alternate location for a tool is already defined (e.g. `"go.alternateTools": { "gometalinter": "/usr/local/bin/golangci-lint" }`) the **Install/Update Tools** command will still install the same command at another location.

**Describe the solution you'd like**
When such an alternate definition is already in place for any tool, **Install/Update Tools** should skip said tool.

**Additional context**
In my own circumstance, I also have `"go.toolsGopath": "~/vscode-go"` set, to reduce clutter by keeping VSCode's tools out of my `~/go/bin` directory.

**Comment by ramya-rao-a** [comment]
Fair point, PRs are most welcome to make this change to have the `Go: Install/Update Tools` command skip such tools.

Code Pointers:
- [Set up local dev env for the extension](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- https://github.com/microsoft/vscode-go/blob/0.13.0/src/goInstallTools.ts#L60 is where we show the drop down with all the tools

**Comment by ramya-rao-a** [comment]
This should be fixed in the latest version (0.13.1) of the extension.

Thanks for reporting @jlucktay!
