### ISSUE TITLE
Debug: "Pretty Print" a Struct

### ISSUE THREAD

**Issue by esinek** [microsoft/vscode-go#3032]
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

**Is your feature request related to a problem? Please describe.**
When debugging, it slows me down to inspect a struct to see the information I'm interested in. I want to see the relevant info at a glance. Having a tooltip (or other quick info mechanism) would allow me to step through my program and quickly see struct details. I want to keep my fingers on the function keys and not have to move the mouse and drill down into a struct to see multiple bits of info in the struct.

**Describe the solution you'd like**
When debugging, it would be really useful to see a tooltip (or other visualization) of a string representation of a struct. This could be as simple as using the stringer implementation (if exists) or a scripting solution (I remember using this in Visual Studio for C++ several years back). Of course, we'd probably want a limit to the character count allowed for this feature. Perhaps a single line, char count limited representation for in-line and then a multi-line representation for hover tooltip.
One could argue that's what watch variables are for - and I agree they are certainly useful, but for more complex structs where you want to see multiple pieces of info together in one place, this visualization would be a nice to have. If using watch variables, you sometimes end up with too many or, depending on what you're debugging, you have to clear out the currently unused ones and add back the ones you want. The proposed solution would solve this problem as the format (stringer or scripting) would persist.

**Describe alternatives you've considered**
I've gone on the gophers slack channel (vscode then delve) and Alessandro Arzilli pointed me to his repo for gdlv where he has implemented this feature via delve scripting. To quote Alessandro, "We can't use the String method because it would involve executing code in the target process. I implemented the scripting thing in [gdlv](https://github.com/aarzilli/gdlv) so it's definitely possible."

**Additional context**
slack link: https://gophers.slack.com/archives/C07EXM5E0/p1580707374004300

**Comment by hyangah** [comment]
This is somewhat related to #2655 (that may be used to invoke a `String` method if exists) but more targeted to the pretty printing of complex objects.

@quoctruong - is the DAP protocol (work-in-progress) capable to provide means to implement this type of features?

**Comment by lggomez** [comment]
@esinek the DAP only has a ValueFormat field on the [EvaluateRequest](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) which specifies whether the field should for formatted in hexadecimal or not (and makes sense from the protocol perspective, I guess having anything more liberal would be a pandora box for implementers). From our side on the response, formatting the output of an expression is up to us, as the issue mentions

I don't know which is the best way to do so, @stamblerre does gopls have any method to format a given code palyload?

**Comment by stamblerre** [comment]
LSP does have a rangeFormatting request which will format a given part of a file, but `gopls` doesn't support it yet. Would that work?

**Comment by stamblerre** [comment]
Let's move this discussion to https://github.com/golang/vscode-go/issues/158, as this repository is migrating (https://github.com/microsoft/vscode-go/issues/3247). Thanks all!
