### ISSUE TITLE
Error not cleared after fixing 

### ISSUE THREAD

**Issue by jd84** [microsoft/vscode-go#3039]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.5 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.42.0
ae08d5460b5a45169385ff3fd44208f431992451
x64

- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux
amd64

### Share the Go related settings you have added/edited

```json
{
    "go.useLanguageServer": true,
}
```

### Describe the bug
Maybe related with: https://github.com/Microsoft/vscode-go/issues/1036
After fixing the syntax error, vscode continues shows errors and does not update. I created a video to describe the problem. The problem exists on MacOS and Linux (Windows not tested).

### Steps to reproduce the behavior:
For me to reproduce this, create an error so that golint will detect it, after fixing the error, the error will not cleared in vscode.

### Screenshots or recordings
I attached a short video. (MP4 file)

[error_not_cleared.zip](https://github.com/microsoft/vscode-go/files/4184871/error_not_cleared.zip)

**Comment by stamblerre** [comment]
Renaming a package is pretty specific case, because it forces `gopls` to clear its metadata cache. Do you see this issue with other types of errors or just with package renames?

**Comment by jd84** [comment]
No, the error exists only if I rename the package. To clear the error a restart of vscode is required. I tested it again on MacOS and Linux (same results).

**Comment by stamblerre** [comment]
Thanks for clarifying. The issue you are referring to is https://github.com/golang/go/issues/36593, which I just moved to the `gopls/v0.4.0` milestone. I will close this issue in favor of that one, so please follow along there.
