### ISSUE TITLE
document delve remote debugging

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/vscode-go#304]
Now that local debugging is working, I'd like to get remote debugging working. The problem could be that I don't yet understand how to use the `dlv` executable yet. Following [dlv debug](https://github.com/derekparker/delve/blob/master/Documentation/usage/dlv_debug.md) docs, I did:

``` bash
Camerons-iMac:helloworld cameron$ pwd
/Users/cameron/go/src/github.com/GoogleCloudPlatform/golang-samples/docs/managed_vms/helloworld
Camerons-iMac:helloworld cameron$ go run helloworld.go 
2016/04/19 16:11:14 ctaggart
Camerons-iMac:helloworld cameron$ dlv debug -l 127.0.0.1:5050
Type 'help' for list of commands.
(dlv)
```

In `.vscode/launch.json`, I added the `remote` configuration with the `remotePath`, `host`, and `port` params. To begin with, I'm simply trying to launch it locally.
``` json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "${workspaceRoot}",
			"env": {},
			"args": []
		},
		{
			"name": "remote",
			"type": "go",
			"request": "launch",
			"mode": "remote",
			"program": "${workspaceRoot}",
			"env": {},
			"args": [],
			"remotePath": "/Users/cameron/go/src/github.com/GoogleCloudPlatform/golang-samples/docs/managed_vms/helloworld",
			"host":"127.0.0.1",
			"port": 5050
		}
	]
}
```

When I hit the play button, vscode just seams to scroll the blue bar:
![image](https://cloud.githubusercontent.com/assets/80104/14658812/81c4112e-064b-11e6-82d5-89663b5199e1.png)

Not really sure how to get remote debugging to work. More documentation would really help.

**Comment by lukehoban** [comment]
I added a few more notes to the README.  For your example, I think the issue is that you missed the `--headless` argument to `dlv`, which runs it in server more instead of server+client mode.

**Comment by JCzz** [comment]
Did you manage to get this work? I have [this](http://stackoverflow.com/questions/39194562/how-to-remote-debug-with-delve-debugger-in-visual-studio-code) on stackoverflow
