### ISSUE TITLE
Debugger fails to open file when debugging remotely with Delve

### ISSUE THREAD

**Issue by tsaarni** [microsoft/vscode-go#3043]
I'm trying to debug my program remotely with vscode + delve.  Program is running on Kubernetes and I forwarded debug port to my local machine.  Everything seems to start correctly.

My program crashes and headless delve debugger prints error

> [unrecovered-panic] runtime.fatalpanic() .home/tsaarni/sdk/go1.13.7/src/runtime/panic.go:847 (hits goroutine(75):1 total:1) (PC: 0x431340)

vscode tries to open `panic.go` and I get error in vscode:

> Unable to open 'panic.go': Unable to read file '/home/tsaarni/work/home/tsaarni/sdk/go1.13.7/src/runtime/panic.go' (Error: Unable to resolve non-existing file '/home/tsaarni/work/home/tsaarni/sdk/go1.13.7/src/runtime/panic.go').

The correct path to `panic.go` is  `/home/tsaarni/sdk/go1.13.7/src/runtime/panic.go`, not `/home/tsaarni/work/home/tsaarni/sdk/go1.13.7/src/runtime/panic.go`

The workspace directory I have open is `/home/tsaarni/work/myproject`.

I have started delve by running `dlv exec /mybinary --headless --api-version=2 --log --listen 0.0.0.0:8181` on my remote target.

I wonder where this wrong path prefix comes to vscode and how could I fix it?

### Version information:

vscode-go 0.13.0
vscode 1.42.0
go1.13.7 linux/amd64

### launch.json config

```json
{
    "name": "Attach remote",
     "type": "go",
     "request": "attach",
     "mode": "remote",
     "remotePath": "/mybinary",
     "port": 8181,
     "host": "127.0.0.1",
}
```

### Go related vscode settings:

 "go.useLanguageServer": true

**Comment by tsaarni** [comment]
I comment out `"remotePath": "/mybinary",` from `launch.json` and it started to work: I can open all files within vscode debugger! 

The `remotePath` property is [documented](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson) :

> Absolute path to the file being debugged on the remote machine in case of remote debugging i.e when mode is set to remote. See the section on Remote Debugging for details

but on the other hand, this property is probably only for remote debugging with `dlv debug` and not `dlv exec`?  

In my case the file is set at the remote target within `dlv exec` command, not via vscode debugger. Apparently it confuses paths. I wonder, is this working as intended or a bug somewhere in the toolchain?

**Comment by quoctruong** [comment]
@tsaarni I think the `remotePath` should be set to `/home/tsaarni/sdk/go1.13.7/src/` and not `/mybinary` in this case? Also I don't see where `/mybinary` appears in your log as well.

**Comment by tsaarni** [comment]
I don't think that is correct, since `remotePath` is documented to point a path of the file being debugged on the remote machine.  That is the binary name I execute under headless delve debugger on remote machine.  On the other hand `/home/tsaarni/sdk/go1.13.7/src/` is a local path on my laptop where Go SDK lives, so I don't see how that could be correct - it does not exist in remote machine.

Regardless of this I tried this but I think whatever I put in `remotePath`, vscode stats to prefix the paths wrongly and is unable to open files when clicking frames in backtrace.   But since I'm able to work around this problem by not defining `remotePath` in the `launch.json` at all, maybe I misunderstood the documentation and the correct way is to NOT define that property at all...  
So maybe we can close this issue?

**Comment by quoctruong** [comment]
Yes, I think we can close this issue. Feel free to reopen if you run into other issues with the remotePath.
