### ISSUE TITLE
Function completion does not work across multiple cursors

### ISSUE THREAD

**Issue by sparrc** [Microsoft/vscode-go#305]
First off, thanks for the great vscode plugin!

Here's a full dummy script to reproduce my problem:

```go
package main

import "bytes"

func main() {
	var buf bytes.Buffer
	buf.WriteString("mystring")
	var mylen int
	if true {
		mylen = 8
	} else {
		mylen = 8
	}
}
```

steps are:

1. select the first `8`
2. ctrl+d or cmd+d to select both `8` variables
3. begin typing `buf.Le...` and wait for completion of `buf.Len()` to appear
4. select `buf.Len()` with tab or enter

When I do this, only the first of the `8` variables gets completed to buf.Len()

I'm on OSX using VSCode 1.0

**Comment by lukehoban** [comment]
It appears this only happens for your repro steps if you have `"go.useCodeSnippetsOnFunctionSuggest": true`.  

In that case, the item you are selecting in the completion list is a snippet.  

It appears that when there are multiple cursorts, and a user tries to complete on a snippet, VS Code only inserts it in the first location.

That appears to be a bug/limitation in VS Code.  I'll move over to that repo.

**Comment by lukehoban** [comment]
This issue was moved to Microsoft/vscode#5578
