### ISSUE TITLE
Cannot install gopkgs tool

### ISSUE THREAD

**Issue by jedebarbieri** [microsoft/vscode-go#3050]
Hello, I can't install gopkgs and the "auto-completion" and "go to definition" feature are not working.

- go version go1.13.7 windows/amd64
- VS Code : 1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
- VS Code Go extension : v0.13.0
- windows / amd64
- settings.json: 
`"go.formatTool": "goimports",`

1. Go to "GO: Install/Update Tools"
2. Select "gopkgs"
3. Wait until install finish. It shows me this error:
```
go.toolsGopath setting is not set. Using GOPATH C:\GoPath
Installing 1 tool at C:\GoPath\bin in module mode.
  gopkgs

Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED

1 tools failed to install.

gopkgs:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/uudashr/gopkgs/cmd/gopkgs
go: finding github.com/uudashr/gopkgs/cmd/gopkgs latest
go get: github.com/uudashr/gopkgs/cmd/gopkgs@v0.0.0-20191024034442-58e9141cd7d6 requires
	github.com/uudashr/gopkgs/v2@v2.1.0 requires
	github.com/uudashr/gopkgs@v0.0.0: reading github.com/uudashr/gopkgs/go.mod at revision v0.0.0: unknown revision v0.0.0
go: finding github.com/uudashr/gopkgs/cmd/gopkgs latest
go get: github.com/uudashr/gopkgs/cmd/gopkgs@v0.0.0-20191024034442-58e9141cd7d6 requires
	github.com/uudashr/gopkgs/v2@v2.1.0 requires
	github.com/uudashr/gopkgs@v0.0.0: reading github.com/uudashr/gopkgs/go.mod at revision v0.0.0: unknown revision v0.0.0
```
And a message "Analysis Tools Missing" is shown in the right bottom side:
![image](https://user-images.githubusercontent.com/49592738/74538073-67067d80-4f09-11ea-99df-7a730ae1c126.png)
And when I press "Install" button the process is repeated.

**Comment by stamblerre** [comment]
I think you're running into this issue: https://github.com/uudashr/gopkgs/issues/25. You can try downloading manually with modules turned off (`GO111MODULE=off go get github.com/uudashr/gopkgs`), but you may not get the correct version.

**Comment by nezorflame** [comment]
Yup, this is `gopkgs` issue.
@ramya-rao-a we're gonna need to update the tool installer to use `v2` version of `gopkgs`. While we work on fixing the `v1` import, tool has been updated a few months ago already so there's no point in consuming the old binary version anymore.

**Comment by nezorflame** [comment]
Until the fix is merged, install it manually:
`go get github.com/uudashr/gopkgs/v2/cmd/gopkgs`

**Comment by metalim** [comment]
Not again. https://github.com/microsoft/vscode-go/issues/2857
How about NOT using unstable packages instead of waiting for upsteam fix?

**Comment by nezorflame** [comment]
How about showing some respect to the people who make this work for free so that everyone can benefit from it instead?
No one is perfect: things happen, software breaks, we all learn from it and move forward.

**Comment by smaTc** [comment]
manual installation doesn't work for me somehow. Any ideas?

**Comment by hyangah** [comment]
@smaTc is there any error message explaining why it doesn't work?

**Comment by smaTc** [comment]
@hyangah well not really. When I try to run my main it tells me: "found packages X and Y in /the/directory". But various imports are not working at all and half my project is red now in VS-Code.
How can I verify that it is installed or reinstall the tool or maybe all tools ?

**Comment by smaTc** [comment]
OK Update: I don't even know if it is related but: if I remove all test files and therefore all Imports of the "testing" package my project is working again. Including the Imports etc. Does that make any sense to anyone here?

**Comment by cdreier** [comment]
had the same issue, [installing manually](https://github.com/microsoft/vscode-go/issues/3050#issuecomment-589526494) alone did not resolve it - after removing and reinstalling the vscode-go plugin everything works fine again!

**Comment by pierrre** [comment]
Is gopkgs useful if I'm using gopls ?

**Comment by nezorflame** [comment]
@pierrre yes if you're using command `Go: Add Import`

**Comment by pierrre** [comment]
@nezorflame ok thank you 👍 
I'm never using this command.
I use the gopls autocompletion, and it's still working fine.

**Comment by Wumms** [comment]
Finally (re-)enabling `go.useLanguageServer` fixed it for me (after [manual install](https://github.com/microsoft/vscode-go/issues/3050#issuecomment-589526494) and reinstalling ms-vscode) . No idea how it got disabled though.

**Comment by nezorflame** [comment]
@ramya-rao-a thanks! This one will probably require a minor release so that people stop having these errors.

**Comment by stamblerre** [comment]
@nezorflame: Yep, @ramya-rao-a's planning on doing a patch release tomorrow.

**Comment by ramya-rao-a** [comment]
Hey all,

Sorry for the radio silence, I've been on vacation and @stamblerre has been helping steer the ship in my absence :)

Thanks for all the work here @nezorflame!
The patch release of 0.13.1 has the fix to use v2 of gopkgs

Places where `gopkgs` is used other than code completion for packages when not using language server are
- `Go: Add Import` command
- `Go: Browse Packages` command
