### ISSUE TITLE
Language Server is not compatible with go < 1.12

### ISSUE THREAD

**Issue by cornfeedhobo** [microsoft/vscode-go#3054]
Please add the option to toggle the checking and/or notification of newer `gopls` versions. I'm pretty sure your update code is broken anyways. Either way, this pop-up has gotten so annoying. I spent an hour ensuring I had the newest version installed.

**Comment by stamblerre** [comment]
This setting is already available: `"go.useGoProxyToCheckForToolUpdates": false`.
You can check your `gopls` version by running `gopls version`. What is the output of that command? Both the check and the update should be working correctly, as we haven't heard other complaints. What error messages are you seeing?

**Comment by cornfeedhobo** [comment]
Thank you so much! I wish I had found that sooner.

To the issue... Every time I start or reload, I am shown the message that gopls is out of date.

Clicking "Update" results in failure:
```
gopls:
Error: Command failed: /usr/lib64/go/1.11/bin/go get -v golang.org/x/tools/gopls
```

Running `gopls version` is confusing because it doesn't match [github releases](https://github.com/golang/tools/releases):
```
version 0.2.0, built in $GOPATH mode
```

My hunch now is that this relates to my use of GOMODULES.

**Comment by stamblerre** [comment]
Yes, sounds like the warning is correct - the latest version of `gopls` is `v0.3.2`.  What happens if you run `GO111MODULE=on go get golang.org/x/tools/gopls`? Are you using Go 1.11?

Also, regarding the setting, make sure to reload your VS Code window after you configure it.

**Comment by cornfeedhobo** [comment]
```bash
$ go get -u golang.org/x/tools/gopls
# golang.org/x/tools/internal/lsp/source
go/src/golang.org/x/tools/internal/lsp/source/completion.go:629:21: file.LineStart undefined (type *token.File has no field or method LineStart)
go/src/golang.org/x/tools/internal/lsp/source/format.go:251:27: fset.File(f.Pos()).LineStart undefined (type *token.File has no field or method LineStart)
go/src/golang.org/x/tools/internal/lsp/source/format.go:276:13: tok.LineStart undefined (type *token.File has no field or method LineStart)
```
and
```bash
$ GO111MODULE=on go get -u golang.org/x/tools/gopls
go: cannot find main module; see 'go help modules'
```

Yes, I'm using 1.11.

**Comment by stamblerre** [comment]
Make sure not to use `-u` flag, as it will give you the wrong versions of the dependencies.
I would recommend updating to 1.13, if possible, but if not, you can run the following commands to install `gopls`:

```shell
$ cd $(mktemp -d)
$ go mod init gopls
$ GO111MODULE=on go get golang.org/x/tools/gopls@latest
```

It's possible that the installation logic is broken for 1.11 - I will investigate that.

**Comment by cornfeedhobo** [comment]
Looks like my distro published go1.12. Upgrading to 1.12 fixes this. I'm wondering if maybe this is upstream? But it's probably good it's flagged either way.

**Comment by stamblerre** [comment]
Thanks for following up - glad you were able to resolve the issue. I'll leave this open to make sure that we confirm that the installation works for Go 1.11.

**Comment by cornfeedhobo** [comment]
Likewise, thanks for all the help!

**Comment by cornfeedhobo** [comment]
Follow up testing: I cleared out my tools and let the plugin install them this time. Everything completed successfully and without hiccup. I'm guessing this is isolated to 1.11.

**Comment by hyangah** [comment]
New versions of `gopls` require at least go1.12.

`gopls` depends on `golang.org/x/tools/internal/lsp/source/completion.go'  which uses `go/token.Faile.LineStart`. That method wasn't available until go1.12 (https://golang.org/doc/go1.12#go/token).

**Comment by cornfeedhobo** [comment]
well, that'd do it

**Comment by cornfeedhobo** [comment]
Is there a way to get debugging output from the plugin? Today I can't get it to even find any dependencies, including standard libs like `context`.

**Comment by hyangah** [comment]
@cornfeedhobo Extension outputs are in "View: Toggle Output" -> select 'gopls' from the drop down menu on the right side. If you are using gopls, you can add the following in the setting to make gopls more verbose and some of its endpoints accessible through the port for inspection. 

 ```
go.languageServerFlags": [
    "-rpc.trace", // for more detailed debug logging
    "serve",
    "--debug=localhost:6060", // to investigate memory usage, see profiles
],
```

**Comment by cornfeedhobo** [comment]
@hyangah thank you. this was very helpful and I was able to figure out my issue (pebkac).

**Comment by cornfeedhobo** [comment]
I've updated the title to better reflect the issue. I assume the only thing now is to notify a user that if they are using < 1.12 then they will be incapable of using `gopls`.

**Comment by stamblerre** [comment]
Closing this, as https://github.com/golang/vscode-go/pull/31 has been merged into the Nightly.
