### ISSUE TITLE
Notification about generated file when open in editor window during regeneration

### ISSUE THREAD

**Issue by meling** [microsoft/vscode-go#3056]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.8 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.42.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin, amd64

### Share the Go related settings you have added/edited
```json
{
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": true,
        "documentLink": true
    },
    "go.useLanguageServer": true,
    "go.enableCodeLens": {
        "references": false,
        "runtest": true
    },
    "go.autocompleteUnimportedPackages": true
}
```

### Describe the bug
vscode-go displays a notification with `This file seems to be generated. DO NOT EDIT.` even when the generated file is not being edited. Even if the file is just open in another tab, it will display this notification every time the file is generated. This is confusing because I'm not editing a generated file, but I do want to see the changes (since I'm building a generator)...

### Expected behavior
The notification should only be displayed if one attempts to actually edit the file from within VSCode. VSCode should not display this notification for open files being regenerated by an external tool.

### Steps to reproduce the behavior:
(If needed I can supply a protobuf example, unless there is already a test case that can be used to trigger this scenario.)

I should note that when first trying to reproduce this with just a protobuf example, the notification didn't appear. However, if I edit the generator code (written in Go), it consistently gives the notification. On my second attempt to modify the proto file, it also displayed the notification after regenerating the file.

### Screenshots or recordings
I have a recording in QuickTime format that can be downloaded [here](https://www.dropbox.com/s/ajciv01wym2k3gd/Screen%20Recording%202020-02-18%20at%2009.43.51.mov?dl=0).

**Comment by stamblerre** [comment]
Thank you for the report! This warning comes from `gopls`, but I wonder if there is a bug in the VS Code language client, since the `gopls` code is supposed to only show this warning if you are typing in the file. Can you share the `gopls` logs from when this happens? You can find info [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs) on how to do this.

**Comment by meling** [comment]
I'm unable to reproduce the bug on my home computer, which has a slightly different configuration. I will try again in the office tomorrow.

**Comment by meling** [comment]
I'm unable to reproduce this bug. I guess I will re-open if it reappears.
