### ISSUE TITLE
gpls import order

### ISSUE THREAD

**Issue by zxwtry** [microsoft/vscode-go#3059]
alphabetical：'
	"fmt"
	"github.com/xxx"
	"log"

"os / github / xxx" :
	"fmt"
	"log"
	"github.com/xxx"

i want to order imports in alphabetical
but formatTool will change to  "os / github / xxx"

how to keep alphabetical? thx

**Comment by ruinshe** [comment]
I meet similar problem when using vscode with basic Go plugin configuration.

When I put all imports together, the plugin split the imports into multiple blocks (I used `gofmt source.go` it shows all imports are put together), and my `go.formatTool` was set to `gofmt`.

Any idea?

**Comment by stamblerre** [comment]
If you want your imports to be organized on save then they will be grouped this way, as the default behavior of the `goimports` tool is to separate standard library and third-party imports. This is the structure for the majority of Go code, and I would recommend sticking with this default. (cc @heschik)

If you only want to use the language server but only have formatting on save (@ruinshe, I believe this is your case), then you can add the following configuration to your `settings.json` file:

```json5
"[go]": {
	"editor.codeActionsOnSave": {
		"source.organizeImports": false,
	},
	"editor.formatOnSave": true
}
```

**Comment by ruinshe** [comment]
@stamblerre Thanks for the quick reply, and Your solution works for me.

**Comment by stamblerre** [comment]
Going to close this issue since it hasn't had much activity in the last month. @zxwtry: please reopen this issue if you're still encountering problems.
