### ISSUE TITLE
Go Extension is very slow

### ISSUE THREAD

**Issue by Aditya267** [microsoft/vscode-go#3060]
Go Extension is very slow. Auto completion, add import, go to definition all features are taking a lot time to respond.

When i profile the extension using 
https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu
I saw unresponsive symbol for Go extension

- Issue Type: `Bug`
- Extension Name: `Go`
- Extension Version: `0.13.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.42.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 5229,
		"activateCallTime": 157,
		"activateResolvedTime": 44,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.Go",
				"_lower": "ms-vscode.go"
			},
			"activationEvent": "onLanguage:go"
		}
	},
	"runtimeErrors": []
}
```

**Comment by Aditya267** [comment]
Attaching CPU profile
[CPU-20200221T063010.347Z.cpuprofile.txt](https://github.com/microsoft/vscode-go/files/4234581/CPU-20200221T063010.347Z.cpuprofile.txt)

**Comment by hyangah** [comment]
@Aditya267 have you tried the [language server (`gopls`)](https://github.com/microsoft/vscode-go#go-language-server)?  I noticed from the profile it is spawning multiple tools underneath. Use of `gopls` may help avoiding the problem and support go modules mode better in general. See https://github.com/golang/tools/blob/master/gopls/doc/vscode.md for configuration.

**Comment by Aditya267** [comment]
@hyangah yeah I have tried the language server(gopls)... with the configuration mention in the link  https://github.com/golang/tools/blob/master/gopls/doc/vscode.md , but still it is very slow.
Do you want the cpu profile with language server enabled?

**Comment by hyangah** [comment]
@Aditya267 do you think this is due to the excessive CPU usage?  (the process explorer or general cpu monitoring tools). Otherwise, I think `gopls` log may be more helpful in debugging the latency and response time issue.

```
"go.languageServerFlags": [
    "-rpc.trace", // for more detailed debug logging
    "serve",
    "--debug=localhost:6060", // to investigate memory usage, see profiles
],
```

The `gopls` log can be found in "View: Toggle Output" and select "gopls" from the drop-down menu. Thank you!

**Comment by NilsJPWerner** [comment]
I am having similar issues. Whenever I save it takes gopls 30 seconds to lint and format and prevents the document from being saved while it happens. Sometimes it causes the window to crash. 

I am running: 
`golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=`
`go version go1.14 darwin/amd64`

Here is a gopls log gist with debugging turned on: https://gist.github.com/NilsJPWerner/ac2d237f99ff3f2403d3529ad2c48e0a

This started happening after upgrading to go 1.14 from 1.12

**Comment by NilsJPWerner** [comment]
I actually don't think it's gopls fault. I disabled gopls, govet, build on save, live errors and I still have 30 second saves and crashing windows. The main log has the following error: `[2020-03-11 11:43:57.976] [main] [error] [VS Code]: render process crashed!`

**Comment by NilsJPWerner** [comment]
I figured out that it was another extension: https://github.com/beerose/go-group-imports-vscode that was causing the issue. Disabling it fixed the slow save.

**Comment by stamblerre** [comment]
Glad to hear you figured it out! Thanks for following up.

**Comment by taipoxin** [comment]
> I figured out that it was another extension: https://github.com/beerose/go-group-imports-vscode that was causing the issue. Disabling it fixed the slow save.

@NilsJPWerner Man, thank you, you saved my time! :3
