### ISSUE TITLE
Workspace Symbol Blocks Other Providers in Non-Go Workspaces

### ISSUE THREAD

**Issue by jvilk-stripe** [microsoft/vscode-go#3066]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.8 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	-  1.42.0 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- `darwin amd64`

### Share the Go related settings you have added/edited

None.

### Describe the bug

Hey there. I support VS Code internally at my company, and I discovered an issue today where this extension tanks workspace symbols performance in a very large workspace that contains no* Go code. Specifically, it fails with the following message (after installing the requested workspace symbols package):

```
[error] TypeError: Cannot read property 'forEach' of undefined
    at convertToCodeSymbols (/Users/jvilk/.vscode/extensions/ms-vscode.go-0.13.0/out/src/goSymbol.js:24:19)
    at /Users/jvilk/.vscode/extensions/ms-vscode.go-0.13.0/out/src/goSymbol.js:42:13
```

Is there any way to disable this extension's workspace symbol provider? I'd like to prevent it from causing harm for our many developers in this one repository without outright forbidding people to use it in our actual internal Go workspace.

I did not see a relevant configuration option, but there are many options so perhaps I missed something.

### Steps to reproduce the behavior:
1. Install the extension and the Go package required for workspace symbols.
2. Open a very large workspace without any* Go code in it, and perform a workspace symbol request.
3. Watch as VS Code takes many seconds to return workspace symbols, with the above-pasted error appearing in the logs.

\* There's one loose Go file buried in the tree, but I didn't open it or view it in the VS Code session, so I'm not sure why this extension is activating.

**Comment by stamblerre** [comment]
This extension activates if there are any Go files in the directory opened in VS Code. My guess is that VS Code would combine the output from multiple extensions, but workspace symbols are failing in the Go extension, causing no other symbols to appear. I will investigate this issue.

**Comment by jvilk-stripe** [comment]
>This extension activates if there are any Go files in the directory opened in VS Code.

That confirms my hypothesis -- the single Go file in this very large workspace causes the extension to activate. :(

**Comment by stamblerre** [comment]
Is this workspace open-source or private code? If it's open-source, could you point me to it so I can try to reproduce the issue?

**Comment by jvilk-stripe** [comment]
Unfortunately, it's private. :( 

If you aren't able to reproduce the issue, I can see if I can cajole it into failing in a different workspace.

**Comment by stamblerre** [comment]
https://github.com/microsoft/vscode-go/pull/3068 may help, if you'd be willing to check it out and follow the steps to rebuild the extension here: https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code.

**Comment by jvilk-stripe** [comment]
> if you'd be willing to check it out and follow the steps to rebuild the extension here

Absolutely; I'll build and sideload it, and will get back to you shortly.

**Comment by jvilk-stripe** [comment]
```
[2020-02-25 16:22:44.055] [exthost] [error] [ms-vscode.Go] provider FAILED
[2020-02-25 16:22:44.055] [exthost] [error] TypeError: decls is not iterable
	at convertToCodeSymbols (/Users/jvilk/vendor/vscode-go-branch/out/src/goSymbol.js:24:32)
	at /Users/jvilk/vendor/vscode-go-branch/out/src/goSymbol.js:42:13
```

I think you need to expect `decls` to be `undefined`.

**Comment by jvilk-stripe** [comment]
The execFiles call in `callGoSymbols` is failing with an error:

```
> err
Error: Command failed: /Users/jvilk/go/bin/go-symbols (path to my workspace; redacted) hello
```

Running it manually yields the following:

```
$ time /Users/jvilk/go/bin/go-symbols (path to workspace) hello
[]

real	0m8.447s
user	0m16.260s
sys	1m6.121s
```

**Comment by stamblerre** [comment]
I'm not sure why the command would fail, but I've pushed an update to the PR, if you'd like to try again.

**Comment by stamblerre** [comment]
@jvilk-stripe: Are you still encountering this issue? If speed is still an issue, you may consider using `gopls`, the Go language server: https://golang.org/s/gopls.
