### ISSUE TITLE
Remote-ssh + Go: go tools does not work.

### ISSUE THREAD

**Issue by aprilweet** [microsoft/vscode-go#3067]
Issue Type: <b>Bug</b>

Remote-ssh + Go:
go-outline does not work, and searching only workds inside current file, and so on.
i have installed all the go tools suggested by Go extension, but it seems not working at all.

Extension version: 0.13.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0049

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz (8 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|

|Item|Value|
|---|---|
|Remote|SSH: 9.134.9.186|
|OS|Linux x64 3.10.107-1-tlinux2_kvm_guest-0049|
|CPUs|Intel(R) Xeon(R) CPU E5-26xx v4 (8 x 3199)|
|Memory (System)|15.42GB (2.40GB free)|
|VM|0%|
</details>

**Comment by hyangah** [comment]
[`go-outline`](https://github.com/ramya-rao-a/go-outline)  is designed to work with a single file.

And reading https://github.com/microsoft/vscode-go/issues/2793, I thought outline view only would work for the current file.

**Comment by stamblerre** [comment]
@aprilweet: Can you share your VS Code settings in your `settings.json` file? Are you using modules or GOPATH mode?

**Comment by aprilweet** [comment]
I have found the OUTPUT of gopls, the extension on remote host complains something wrong about import path, because of certificate of my private git repo is not configured properly。
Thank you all.
