### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Limza** [microsoft/vscode-go#3069]
- Issue Type: `Bug`
- Extension Name: `Go`
- Extension Version: `0.13.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.42.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by stamblerre** [comment]
Looks like there's no information associated with this issue. @Limza: What exactly is going wrong?
