### ISSUE TITLE
"No suggestions" on go core libs

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode-go#307]
fmt, log or http and all those do not get any completion anymore.

I upgraded 15.10 to 16.04(last rc) and I hav no clue if has something to do with that. Nontheless after that, there is no completion or intellisense for go core stuff anymore.

**Comment by vkryukov** [comment]
I have the same problem now, with latest Code (1.0.0) and vscode (0.6.38). All the go tools are installed, but Intellisense works only occasionally.

**Comment by vkryukov** [comment]
Update: I was able to resolve the issue by updating to go 1.6.2, reinstalling VS Code, reinstalling Go extension, and rebuilding all go development/analysis tools.

**Comment by lukehoban** [comment]
Yeah - I cannot repro this myself - and I can only imagine this happening when you have some incompatibility between your Go toolchain and the build of `godef` that you installed locally.  It wouldn't be something that `vscode-go` can really control.

If anyone does have complete repro steps for getting into this state - feel free to add comment here and/or open an issue on `godef`.
