### ISSUE TITLE
Add click to "run" button on main function

### ISSUE THREAD

**Issue by rakyll** [microsoft/vscode-go#3074]
It would be great if VSCode was able to recognize a main function in a main package and automatically put a "run" button on it. Then, you can build the package, run it and show the output on the terminal tab.

**Comment by hyangah** [comment]
Interesting idea. The go extension currently offers code lens for test/benchmark functions, so this may be similar. But, my concern is that many programs need input, output, flags, and sometimes configuring the right execution environment, so, a simple run is not going to be helpful in many cases.

**Comment by SaberD** [comment]
What about a run current file in terminal button similar to the python extension? (go run {filename}.go)
It is located in the upper right corner of the opened file only.
![run](https://user-images.githubusercontent.com/13253873/76302928-222ff580-62c1-11ea-94eb-bc4fe63e769e.png)

Forget about implementing inputs, outputs, flags, and configuring the execution environment. This would be useful for quick tests to confirm expected results from isolated functions in a small test.go file.

**Comment by ramya-rao-a** [comment]
The ability to run the current file is available via the `Run: Start Without Debugging` command which I believe is mapped to Ctrl+F5 keybinding. This already suffers from the pitfalls of not taking any inputs, flags etc, but is considered helpful.

Having the codelens `run` would make the existing feature more visible and accessible.

**Comment by stamblerre** [comment]
I have transferred this to https://github.com/golang/vscode-go/issues/159, so let's continue the discussion there, as this repo is migrating (https://github.com/microsoft/vscode-go/issues/3247).
