### ISSUE TITLE
How to disable parameter hints post completion when using gopls

### ISSUE THREAD

**Issue by kybom** [microsoft/vscode-go#3075]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.14
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.42.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux amd64

### Share the Go related settings you have added/edited

```
{
    "editor.parameterHints.enabled": false,
    "go.useLanguageServer": true
}
```

### Describe the bug
editor.parameterHints.enabled does not work,I want to disable parameter hints.
![QQ截图20200228143509](https://user-images.githubusercontent.com/24692485/75517051-b932bd00-5a38-11ea-9cdd-0df4746001ba.png)

**Comment by hyangah** [comment]
I see vscode issues `textDocument/signatureHelp` requests even when `editor.parameterHints.enabled` is set false. 

```
[Trace - 08:46:27.845 AM] Sending request 'textDocument/signatureHelp - (63)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/projects/tools/internal/lsp/cache/analysis.go"},"position":{"line":37,"character":11}}


[Trace - 08:46:27.865 AM] Received response 'textDocument/signatureHelp - (63)' in 20ms.
Result: {"signatures":[{"label":"Print(a ...interface{}) (n int, err error)","documentation":"Print formats using the default formats for its operands and writes to standard output.","parameters":[{"label":"a ...interface{}"}]}],"activeSignature":0,"activeParameter":0}
```

I am guessing this is an upstream bug (either vscode or vscode-languageclient) but am not sure exactly which of them is responsible for checking this `editor.parameterHints.enabled` configuration and adjusting the behavior. @stamblerre @ramya-rao-a can you help?

**Comment by hyangah** [comment]
@kybom have you tried this? 

```
  "[go]": {
           "editor.parameterHints.enabled": false,
    },
```

**Comment by kybom** [comment]
> @kybom have you tried this?
> 
> ```
>   "[go]": {
>            "editor.parameterHints.enabled": false,
>     },
> ```

It doesn't work

**Comment by hyangah** [comment]
@kybom Strange. I see difference with the setting. Here are the screen capture before/after. 

Setting `"[go]"{ "editor.parameterHints.enabled": true }`

![enabled](https://user-images.githubusercontent.com/4999471/75562632-e53d4680-5a16-11ea-964e-b98f63ff533b.gif)

Setting `"[go]"{ "editor.parameterHints.enabled": false }`

![disabled](https://user-images.githubusercontent.com/4999471/75562656-ef5f4500-5a16-11ea-9350-22fd3cb27744.gif)

At the end, I hovered around the function name, so the documentation appeared, but that's not the parameter hint.

Maybe this is not what you want.

**Comment by kybom** [comment]
@hyangah 
I select the "Print" function.
![2020-2-28 23-59-16](https://user-images.githubusercontent.com/24692485/75564104-7ac3ef00-5a86-11ea-841f-7097101e289e.gif)

**Comment by stamblerre** [comment]
This is probably because the language server explicitly triggers parameter hints after a user completes a function with parameters (see [here](https://github.com/golang/tools/blob/71482053b885ea3938876d1306ad8a1e4037f367/internal/lsp/completion.go#L128)). I'm not sure if this setting is respected when a user has disabled parameter hints. In @hyangah's example, she didn't select the completion item, and I think that's the difference.

**Comment by hyangah** [comment]
Thanks @stamblerre - looking into the gopls log, I think that's it. I opened https://github.com/microsoft/vscode-languageserver-node/issues/580 for input.

**Comment by hyangah** [comment]
Got an answer for the upstream issue for inquiry. We need to handle this from our extension's language client middleware and also stop the language server to send the vscode editor specific command.

Another approach -
I noticed that when language server is disabled, the old autocomplete logic completes only the function/method name part without `()`. The editor parameter hint then pops up (or does not pop up depending on the `editor.parameterHints.enabled` value) when users type the remaining `(`. So, another option is to make the language server not include the `()` and parameter holders. @stamblerre  thought?

**Comment by stamblerre** [comment]
> Got an answer for the upstream issue for inquiry. We need to handle this from our extension's language client middleware and also stop the language server to send the vscode editor specific command.

I'm fine handling this in middleware, but I'm not sure which middleware function applies here - is there a "completion accepted" method? Otherwise, this doesn't work.
> 
> Another approach -
> I noticed that when language server is disabled, the old autocomplete logic completes only the function/method name part without `()`. The editor parameter hint then pops up (or does not pop up depending on the `editor.parameterHints.enabled` value) when users type the remaining `(`. So, another option is to make the language server not include the `()` and parameter holders. @stamblerre thought?

I don't think we should remove placeholders or parentheses - I doubt users would be happy with that UX, since it requires typing extra characters that shouldn't have to. The upstream response is a little surprising, since I asked https://github.com/microsoft/language-server-protocol/issues/905 not too long ago, but I agree, it's not ideal to have editor-specific commands in `gopls`.

**Comment by hyangah** [comment]
> I'm fine handling this in middleware, but I'm not sure which middleware function applies here - is there a "completion accepted" method? Otherwise, this doesn't work.

I was thinking it can be done from `ProvideCompletionItem`. When receiving function/method completion type CompletionItems, the middleware stuff in the `command` conditionally if the `editor.parameterHints.enabled` is true. (Or if gopls keeps filling in the field, maybe remove the command field if `editor.parameterHints.enabled` is false).

**Comment by stamblerre** [comment]
That sounds reasonable to me. https://github.com/microsoft/vscode-go/pull/3038 is the PR I mentioned offline.

**Comment by ramya-rao-a** [comment]
> Another approach -
I noticed that when language server is disabled, the old autocomplete logic completes only the function/method name part without (). The editor parameter hint then pops up (or does not pop up depending on the editor.parameterHints.enabled value) when users type the remaining (. So, another option is to make the language server not include the () and parameter holders. @stamblerre thought?

> I don't think we should remove placeholders or parentheses - I doubt users would be happy with that UX, since it requires typing extra characters that shouldn't have to.

Not having the () part of the completion has been the default experience. Even in Typescript/Javascript for example, there is a setting to allow the () be part of the completion. 

<img width="903" alt="Screen Shot 2020-03-15 at 8 20 53 PM" src="https://user-images.githubusercontent.com/16890566/76720596-7d674b00-66fa-11ea-9d09-39bbf39247bf.png">

**Comment by ramya-rao-a** [comment]
The fix here is available in the [latest beta version of this extension](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension). Please do try and share feedback

**Comment by kybom** [comment]
> The fix here is available in the [latest beta version of this extension](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension). Please do try and share feedback

Thanks,it works.

**Comment by ramya-rao-a** [comment]
This should now be fixed in the latest version of this extension
