### ISSUE TITLE
You are neither in a module nor in your GOPATH. !!!!!!

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-go#3076]
I have a folder go-projects, in go-projects I have project1, project2, project3...

I have created go modules in each project, when I open folder go-projects, "go build" in each project is OK. But VSCode Go extension IntelliSense doesn't work, and it keeps popping up "You are neither in a module nor in your GOPATH."

I have to open each folder project1, project2, project3 to work.

Please fix this issue!!!!!!!!!!!!

**Comment by marvinhosea** [comment]
Same problem how did you fix it?

**Comment by kzhui125** [comment]
You have to create go mod in VSCode workspace folder now. (go-projects folder)

**Comment by kzhui125** [comment]
https://github.com/microsoft/vscode-go/issues/3086

**Comment by raphaelreis** [comment]
> You have to create go mod in VSCode workspace folder now. (go-projects folder)

I'd say more clearly: You have to open a vscode workspace in a folder where there is a go.mod in

**Comment by jeanluclariviere** [comment]
> I'd say more clearly: You have to open a vscode workspace in a folder where there is a go.mod in

to add to this, I found that initializing the module in the root dir you've added in vs code after the fact isn't sufficient. I had to remove it and re-add the folder to my workplace to get this to stop.

**Comment by stamblerre** [comment]
Thanks for mentioning this, @jeanluclariviere! https://golang.org/cl/226017 should fix this issue.
