### ISSUE TITLE
enable auto completion to fill in argument names in functions

### ISSUE THREAD

**Issue by birraasmile** [microsoft/vscode-go#3077]
**Is your feature request related to a problem? 
No

**Describe the solution you'd like**
-a feature that fills in argument names for a functions as part of auto completion.
I have seen this feature in other IDEs including like goLand.  :)  thanks 

**Describe alternatives you've considered**

**Additional context**
![auto fill in arg names](https://user-images.githubusercontent.com/47379928/75554933-58ad7b00-5a4c-11ea-95fb-f4e8cea5647a.png)

**Comment by hyangah** [comment]
For auto-completion, if you are using the language server (`gopls`, enabled by setting `go.useLanguageServer`), the following setting will include the parameter name/types when completing a function.

```
    "gopls": {
        // Add parameter placeholders when completing a function.
        "usePlaceholders": true,
    }
```

For the inlined parameter name info like in intellij, 
there is an outstanding feature request upstream  https://github.com/microsoft/vscode/issues/16221
which I also think is useful.

**Comment by stamblerre** [comment]
I filed https://github.com/golang/vscode-go/issues/48 to track issues that are actually upstream feature requests in VS Code, so I'm going to close this in favor of that issue.
