### ISSUE TITLE
Popup help misleading due to shortening the docs

### ISSUE THREAD

**Issue by andig** [microsoft/vscode-go#3078]
Please consider this:

<img width="424" alt="Screenshot 2020-02-28 at 17 53 17" src="https://user-images.githubusercontent.com/184815/75568336-5e5a8f00-5a53-11ea-902e-b5717f06103e.png">

This omits *very* important information:

> Stop turns off a ticker. After Stop, no more ticks will be sent. Stop does not close the channel, to prevent a concurrent goroutine reading from the channel from seeing an erroneous "tick".

..and leads to https://stackoverflow.com/questions/60455978/why-all-goroutines-are-asleep-deadlock-with-ticker/60456030#60456030.

It would be great to reconsider if at least indicating that there's more to the docs than displayed wouldn't be a great idea.

**Comment by hyangah** [comment]
If you are using the language server (`gopls`) this should be possible with

```
"gopls": {
        "hoverKind": "FullDocumentation",
    },
```

And https://go-review.googlesource.com/c/tools/+/217727 makes it the default.
If it's not the default yet, the next version of `gopls` (`v0.3.3`) will include the change.

**Comment by andig** [comment]
Great, closing as almost fixed ;)
