### ISSUE TITLE
Overwrite GOPATH in workspace settings

### ISSUE THREAD

**Issue by localhosted** [Microsoft/vscode-go#308]
It would be good to be able to overwrite the project's GOPATH in the workspace settings, regardless of whether GOPATH is defined or not. 

I have to juggle several different paths for projects that have vagrant machines with synced folders, having to manually copy each new package to my Windows path is dreadful.

**Comment by lukehoban** [comment]
You should be able to do this with `"go.gopath": "/path/to/gopath/"` in your workspace settings. Is that not working?

**Comment by localhosted** [comment]
All suggestions are coming from packages in the system's GOPATH env. variable, not from my workspace-defined gopath.

**Comment by localhosted** [comment]
Never mind, it just looks first in GOROOT then in GOPATH.

**Comment by saggafarsyad** [comment]
I'm using vscode 1.1.0 in Windows and I cannot overwrite GOPATH in workspace settings. 

I write like this `"go.gopath": "C:\\Users\\<user_folder>\\Lab\\go-vscode\\bin"`

Everytime I check Current GOPATH it returns undefined. I have no idea what I missed
