### ISSUE TITLE
Ignore: exported method *.Unwrap should have comment or be unexported

### ISSUE THREAD

**Issue by billyzaelani** [microsoft/vscode-go#3080]
Go 1.13 errors package introduce Unwrap. Implementing Unwrap method should ignore the warning.

**Comment by billyzaelani** [comment]
It's golint, so I made a pull request https://github.com/golang/lint/pull/487

**Comment by stamblerre** [comment]
Thanks for doing that! I added the owner of that repository as a reviewer.

**Comment by stamblerre** [comment]
The above change has been merged upstream, so I'll close this issue now. Thanks for the contribution!
