### ISSUE TITLE
expected ';', found 'package' syntax 

### ISSUE THREAD

**Issue by kybom** [microsoft/vscode-go#3082]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.14
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.42.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux amd64
- gopls version
         0.3.3

### Share the Go related settings you have added/edited
{
    "go.useLanguageServer": true
    //"editor.parameterHints.enabled": false
    //"editor.formatOnSave": true
}

### Describe the bug
A go file works well ,but have a syntax error. The error is not always ,and disappears after restarting vscode.
```
expected ';', found 'package'
```
### Screenshots or recordings
![QQ截图20200304012243](https://user-images.githubusercontent.com/24692485/75802559-da3c3a80-5db7-11ea-9e23-232d94a6a0ae.png)
![QQ截图20200304012301](https://user-images.githubusercontent.com/24692485/75802563-db6d6780-5db7-11ea-9ff0-54f511f6fba4.png)

**Comment by stamblerre** [comment]
Thanks for the report! I believe that this is the same issue as https://github.com/golang/go/issues/36960, which is tracked upstream. I'll close this in favor of the upstream issue.
