### ISSUE TITLE
Unable to find go binary. PATH variable incorrect.

### ISSUE THREAD

**Issue by ibalajiarun** [microsoft/vscode-go#3085]
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

    "go.formatTool": "goimports",
    "go.useLanguageServer": true,

### Describe the bug
A clear and concise description of what the bug.

I installed the Go extension on a Remote-SSH server and opened a Go project and the extension complained with the error below:

```
Failed to run "go env" to find GOPATH as the "go" binary cannot be found in either GOROOT(undefined) or PATH(/home/balaji/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/bin:/home/balaji/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

I understand the what the problem is. My go installation path is not specified in the PATH variable. I use fish shell by default, but I figured vscode uses bash and updated the .bashrc file accordingly. I also added the "-i" argument to "terminal.integrated.shellArgs.linux" setting, but it does still read the correct PATH. Where does the Go extension read the PATH variable from?

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by stamblerre** [comment]
You can select your shell in VS Code by running `Ctrl + Shift + P` -> `Terminal: Select Default Shell`. VS Code Go looks for your `PATH` in the process env [here](https://github.com/microsoft/vscode-go/blob/eae5825b572a4458aadfa4013d1110215febcb49/src/goPath.ts#L17). You can try running `echo $PATH` in the integrated terminal to see what the `PATH` looks like to VS Code.

**Comment by ibalajiarun** [comment]
My default shell is set to fish. The PATH on the integrated terminal is:
```
~/workplace/mygo/go-consensus master* balaji@winter
❯ echo $PATH
/opt/go/bin /home/balaji/workplace/gohome//bin /snap/bin /home/balaji/.cargo/bin /home/balaji/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/bin /home/balaji/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /opt/sgxsdk/bin /opt/sgxsdk/bin/x64
```
Notice `/opt/go/bin` above. Below is the error from the extension.

```
Failed to run "go env" to find GOPATH as the "go" binary cannot be found in either GOROOT(undefined) or PATH(/home/balaji/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/bin:/home/balaji/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

**Comment by hyangah** [comment]
@ibalajiarun You are using remote-ssh, right? I think you need to configure the right `PATH` env var in the login script on the remote host. For many shells including `bash`, it is often `.profile` (or `.bash_profile` file for `bash`). 

For remote ssh environment setup, VS Code's remote dev tips and tricks page has a lot of useful info. https://code.visualstudio.com/docs/remote/troubleshooting#_configure-the-environment-for-the-remote-extension-host

I am guessing `terminal.integrated.*` settings are probably used only for the integrated terminal after login & starting vs code, which may be too late.

**Comment by ibalajiarun** [comment]
Turns out, it was a configuration error. My PATH variables were overridden in my fish config file causing issues for notty shells.
