### ISSUE TITLE
Why can't I READ from CMD when debug

### ISSUE THREAD

**Issue by GeniusDai** [microsoft/vscode-go#3088]
**Is your feature request related to a problem? Please describe.**
When I want to read from stdin when debug, I DONOT know how to do it??
`reader := bufio.NewReader(os.Stdin)`
`line, _, _ := reader.ReadLine()`

**Describe the solution you'd like**
I may consider something like the setting like vscode-python, just like internalTerminal, the process is attached to a go-debug-terminal and I can read input from it...

**Comment by hyangah** [comment]
Maybe try remote debugging + headless dlv to work around the current limitation of the extension & delve.

See https://github.com/microsoft/vscode-go/issues/219#issuecomment-449621513  

cc @quoctruong

**Comment by GeniusDai** [comment]
yeah, I tried it and it's really cool...I wonder that the solution of this issue may better be added to some doc or Q&A since I've seen this problem several times.I'll close this issue..
