### ISSUE TITLE
Issue with breakpoints

### ISSUE THREAD

**Issue by sinistersig** [Microsoft/vscode-go#309]
I have a webapp that is separated across several packages. When I try to debug the application using the following launch config, I am unable to reach the breakpoints outside of the main file. Here's the launch config:

``` json
{
    "version": "0.2.0",
    "configurations": [{
    "request": "launch",
        "name": "testapp",
        "type": "go",
        "program": "/Users/sigi/Dev/go/src/github.com/sinistersig/goproject/testapp.go",
    "mode": "debug"
    }]
}
```

Any advice would be appreciated.

**Comment by lukehoban** [comment]
Could you share a more complete repro and system information?  Note that `program` points to a package folder - not sure if `testapp.go` is the main function for package in `goproject`.

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from the OP in a long time.
