### ISSUE TITLE
No debug adapter found VSCODE 1.42

### ISSUE THREAD

**Issue by snigle** [microsoft/vscode-go#3090]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.42.1
          c47d83b293181d9be64f27ff093689e8e7aed054
          x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- Name: Go
Id: ms-vscode.go
Description: Rich Go language support for Visual Studio Code
Version: 0.13.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go

- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux
          amd64

**I'm using remote SSH extension also**

- Delve version **1.4.0 (works with delve 1.3.2)**

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
nothing
### Describe the bug

When I try do debug a go programme or a test, I have only this in the debug console : 
API server listening at: 127.0.0.1:35325
Some time later I see the message `no debug adapter found`

The issue appeared after the upgrade of VSCode to 1.42.0 , the version 1.42.1 didn't fix.

### Steps to reproduce the behavior:
Create a main.go with a print in a folder, run the debug action.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

Launch config : 
```
		{
			"name": "Launch",
			"type": "go",
			"request": "launch",
			"mode": "auto",
			"program": "${fileDirname}",
			"env": {},
			"args": []
		}
```

**Comment by ErmakovDmitriy** [comment]
@snigle,

I am not the extension's developer but could you share your `delve` version?

I have possibly the same problem but only with delve v1.4.0 while delve v1.3.2 works well.
Is it possible for you to try the delve v1.3.2?

**Comment by snigle** [comment]
> Hi @snigle,
> 
> I am not the extension's developer but could you share your `delve` version?
> 
> I have possibly the same problem but only with delve v1.4.0 while delve v1.3.2 works well.
> Is it possible for you to try the delve v1.3.2?

It works with delve v1.3.2 ! Thanks

**Comment by ErmakovDmitriy** [comment]
@snigle,
I am glad that it helped you but there is one more problem (for me at least): delve 1.3.2 does not support go 1.14.

Aren't you interested in further investigation?

**Comment by snigle** [comment]
Yes of course, I update the issue.

**Comment by stamblerre** [comment]
@ErmakovDmitriy: If you believe that Delve doesn't support Go 1.14, please file on the upstream repository: https://github.com/go-delve/delve. They will likely be able to assist you better there.

**Comment by hyangah** [comment]
fyi - Delve supports 1.14, and v1.4.0 is the version that started to include the support.

**Comment by stamblerre** [comment]
Thanks, @hyangah! Release notes can be found [here](https://github.com/go-delve/delve/blob/master/CHANGELOG.md#140-2019-02-11). I will close this issue then.
