### ISSUE TITLE
vscode debug golang program used go modules,can not find package or missing dot in first path

### ISSUE THREAD

**Issue by JK-97** [microsoft/vscode-go#3093]
# my program
**it used go modules**
**path : /home/benjamin/go/src/web-go**
code :

`package main

import (
	"web-go/cmd"
)

func main() {
	rootCmd := cmd.GetRootCmd()
	rootCmd.GenBashCompletionFile("webdemo-complstion")

}`

# issue:
## first 
when my launch.json :

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}/main.go",
            "env": {
				"GOROOT":"/usr/local/go",
				"GOPATH": "/home/benjamin/go",
                                 "GO111MODULE": "on",
			},
			"showLog": true,
            "args": []
        }
    ]
}

run with ctrl +F5:
![image](https://user-images.githubusercontent.com/16853338/76142798-ebcd5d00-60ab-11ea-913b-2679bd47a84b.png)
we cant see when i set  "GO111MODULE": "on",,vscode can not find and  load web-go/cmd package ,but can  load the go  modules package

## second 
when my launch.json :

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}/main.go",
            "env": {
				"GOROOT":"/usr/local/go",
				"GOPATH": "/home/benjamin/go",
                // "GO111MODULE": "on",
			},
			"showLog": true,
            "args": []
        }
    ]
}

run with ctrl +F5:
![image](https://user-images.githubusercontent.com/16853338/76142861-afe6c780-60ac-11ea-8f66-9c11833e9036.png)

we cant see when i don‘t set  "GO111MODULE" ,vscode cant not find and  load the modules package, but cant load the web-go/cmd package.

# so , how can i debug or run  golang program used go modules on vscode ???

**Comment by hyangah** [comment]
@JK-97 

The first case: what is your `go.mod` file like? The module name defined in the `go.mod` should be of url-like form (whose first path element should include . like domain names).

The second case: seems like it fell back to the GOPATH mode. Do you have those mentioned packages already downloaded in `$GOPATH/src` directory? If not, you need to download them by running `GO111MODULE=off go get github.com/spf13/viper github.com/spf13/cobra ...`.

**Comment by gioachino** [comment]
For my program (not using GOPATH mode), after ctrl+F5, I see the output similar to **second** case.

It's OK when no .go File is in the foreground in the editor (then the last active "Run" configuration is chosen).
Another workaround is described [here](https://github.com/microsoft/vscode-go/issues/2841#issuecomment-571940491): after deleting the launch.json file ctrl+F5 works OK also.

**Comment by hyangah** [comment]
@JK-97 Do you still have the same issue with the latest versions of the VS Code Go extension (0.14.x) and the Go (1.14.x)? If so, is it possible to share a repro case (the code for web-go/main.go and web-go/cmd/*.go)?
