### ISSUE TITLE
Debugging doesn't do anything.

### ISSUE THREAD

**Issue by 00sivan** [microsoft/vscode-go#3101]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.14
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.0
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- windows amd64

### Share the Go related settings you have added/edited
All defaults.

### Describe the bug
A clear and concise description of what the bug.
When pressing F5, or Ctrl+F5, or selecting Run -> Start Debugging, or Run -> Run without debugging; nothing happens.

It is expected that doing any of the above should run the currently open .go file.

### Steps to reproduce the behavior:
Install VS Code.
Install Go extension.
Open a .go file.
Press F5.
Nothing happens.
Type go run *.go, the file runs in the terminal.

**Comment by 00sivan** [comment]
To add:
Ctrl-Shift-P
"Go: Install Update/Tools"
command 'go.tools.install' not found.

**Comment by 00sivan** [comment]
Resolved. In addition to Go you must have git installed and you must also add %GOPATH%\bin to the PATH environment variable.

Please ensure that these requirements are included in the setup instructions and FAQ sections.

**Comment by hyangah** [comment]
@00sivan Based on one of your comment https://github.com/microsoft/vscode-go/issues/3101#issuecomment-599088115 I am guessing the go extension was not activated successfully for some reasons.  Did you see any popup or error messages when you start or reload VS Code?  Or did you notice any errors mentioning (`ms-vscode.go`) in one of the Output channels? `View: Toggle Output` and navigate available channels.

**Comment by 00sivan** [comment]
No errors or issues were apparent at the time.

**Comment by hyangah** [comment]
@stamblerre @ramya-rao-a can you relabel this issue? This is more about documentation and  surfacing error messages appropriately even when the extension activation fails.

**Comment by ramya-rao-a** [comment]
The message `command 'go.tools.install' not found.` definitely indicates that the extension has not been activated.

@00sivan Can you try uninstalling and then reinstalling the Go extension? It could be possible that the extension is in a corrupted state.

Another place to look for errors is the Dev tools console. Run the command `Developer: Toggle Developer Tools`

**Comment by 00sivan** [comment]
I apologize for the confusion. The issue for me is resolved. I've left it open so that the documentation will updated to reflect the correct requirements for this module.

The documentation should clearly list Git as a system requirement as the extension does not install properly without it. It should also specify the exact environment variable requirements since alternative settings don't work. (Specifically it should specify that %GOPATH%\bin must be added to the PATH variable.)

Would it be better to open a separate issue to recommend changes to the documentation?

**Comment by ramya-rao-a** [comment]
> The documentation should clearly list Git as a system requirement as the extension does not install properly without it.

git is a requirement for the `Go: Install/Update Tools` to successfully run, but not to be found. The error you saw is that the command itself cannot be found. I don't see why the extension would need git in order to be installed (I might be wrong). 

> Specifically it should specify that %GOPATH%\bin must be added to the PATH variable.

This is not true. If the GOPATH env variable is set correctly, there shouldn't be a need to add it to the PATH variable too. More on GOPATH can be found in [GOPATH in VS Code Go extension](https://github.com/microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)

> Also, no error message was visible. An error should warn the user if something is wrong.

The problem here was the extension not being activated. Therefore, none of the changes we do to the extension itself will help here. But, we can definitely add it to the [FAQs](https://github.com/microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting) that an error of the form `command cannot be found` is tied to extension not being installed properly and suggest a re-install

> Would it be better to open a separate issue to recommend changes to the documentation?

Generally, I would say yes. But, since we are already knee deep in discussions here, its fine to continue here :)

**Comment by 00sivan** [comment]
Oh okay. I did attempt to reinstall the extension six or seven times with
no luck.

Maybe the gopath not being setup correctly in the settings was the primary
issue? I'm not sure.

I'm a beginner to go. I'm sure someone who had used the language before
would already have that set up and would have git installed.

That said, it would be really cool to install vs code, install go, install
the extension, and everything just works. And if it doesn't work, an error
could offer some direction. It's unexpected that VS indicates the extension
is successfully installed but to not do anything.

Maybe that is more of an issue with VS like you said.

**Comment by ramya-rao-a** [comment]
> Maybe the gopath not being setup correctly in the settings was the primary
issue? I'm not sure.

That still wouldn't result in the `command not found` situation.

For now, I have made the below changes to docs:
- Updated [FAQs](https://github.com/microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting) on what the `command not found` error means
- Update readme to [add a note on the dependency on git](https://github.com/microsoft/vscode-go/commit/87bfe7297dcd0b90688d1f7c82f3461c1c040749) for tool installation

Please log a new issue for any other suggestions on improving the docs

Happy Coding!
