### ISSUE TITLE
Debug with build tags fails: cannot find module for path . 

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/vscode-go#3102]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.5 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
```
1.43.0
78a4c91400152c0f27ba4d363eb56d2835f9903a
x64
```
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details

```
go env GOOS GOARCH
windows
amd64
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

_settings.json_ (global)

```
{
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "window.zoomLevel": 0,
    "liveshare.featureSet": "insiders",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "workbench.colorTheme": "Solarized Dark",
    "terminal.integrated.fontFamily": "'DejaVu Sans Mono for Powerline'",
    "terminal.integrated.rendererType": "dom",
    "[go]": {},
    "go.formatTool": "goimports",
    "go.goroot": "/home/ushio/.goenv/versions/1.13.4",
    "go.useLanguageServer": true,
    "python.jediEnabled": false
}
```
_settings.json_ local

```
{
    "[go]": {},
    "go.formatTool": "goimports",
    "go.goroot": "C:\\Go",
    "go.useLanguageServer": true
}
```

### Describe the bug
When I start a debugging session, It always fails with this message.  I also update the vscode to the latest, also done Go: Install/Update tools. All of them are a success. 

```
build .: cannot find module for path .
Process exiting with code: 1
```

### Steps to reproduce the behavior:
1. click debug test
![image](https://user-images.githubusercontent.com/1390976/76670902-5a993300-6550-11ea-9380-82d7e93cc104.png)
2. go to the Debug console, you can see the error. 
3. Configure launch.json and run the test. -> the same error. 

```
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Launch test function",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${workspaceFolder}",
            "cwd": "${fileDirname}",
            "args": [
                "-test.run",
                "Test01_Init_Storage",
                "01_storage_integration_test.go"
            ]
        },
```

I also want to know what this extension is doing under the hood. 
It might try to compile my code and can't find it.

**Comment by hyangah** [comment]
It seems to me that the go command failed to compile the test binary.
I couldn't find an easy way to check the underlying commands invoked by 'debug test' yet. @ramya-rao-a or @quoctruong may know. 

Have you tried "run test" code lens instead? The exact command will be in the "View: Toggle Output" > "Go Tests" channel. (select from the dropdown on the right side after toggle to Output).
You can double check if it compiles the test binary without an issue.

And, I also noticed the launch.json is slightly different from the minimal config shown in https://github.com/microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson or https://github.com/microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#sample-configuration-to-debug-a-single-test How about trying the minimal setting and see if that helps?

**Comment by TsuyoshiUshio** [comment]
Thank you for the comment. I already have a minimal config one.  
These are my current settings.  I notice one thing. I'm using a build tag. If I use a build tag, the debug doesn't work even if I add it as one of the args. I remove my build tag from the target go file; then, the debug starts working. 

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Launch test function",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${workspaceFolder}",
            "args": [
                "-test.run",
                "01_Init_Storage",
                "-tags=01"
            ]
        },
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": [
            ]
        }
    ]
}
```

# build tags

```go
// +build 01

package terraform
         
```
# command line
on the workspace directory. This command works. However, debug "Launch test function" Doesn't work. 
```
$ go test -v ./... -test.run Test01_Init_Storage -tags=01
````
This command works. However, if I click the debug link on the code, it doesn't work. (cannot fild module for path . error.) even if I modify "Launch" settings with adding args, it doesn't work. 
```
$ go test -v ./... -tags=01
``` 

This command will ignore the target test. (It is expected behavior for build tags)
```
$ go test -v ./...
```

**Comment by hyangah** [comment]
@TsuyoshiUshio thanks for the followup. From your description, I am guessing the build tags is not correctly forwarded to the debug processes. The error message 'cannot find module for path .' is a bit misleading but maybe it meant the go command couldn't find the source code. 

I will try create a small repro if you already have something handy.

**Comment by hyangah** [comment]
@TsuyoshiUshio To pass tags, see https://github.com/microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#using-build-tags.

**Comment by ramya-rao-a** [comment]
Thanks @hyangah, that indeed is the solution here.
@TsuyoshiUshio Please refer to the link shared above. If you still see issues, feel free to re-open this issue
