### ISSUE TITLE
replace entered content instead append when autocomplete happend

### ISSUE THREAD

**Issue by gainskills** [microsoft/vscode-go#3103]
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.1 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- February 2020 (version 1.43)
- Check your installed extensions to get the version of the VS Code Go extension 
	- Bug fixes and update latest version of gopls to be 0.3.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- go env GOOS GOARCH
        - darwin
        - amd64

### Share the Go related settings you have added/edited
- "go.useLanguageServer": true

### Describe the bug
- From the snap, autocompletion append content instead of replacing the inputted content
    ![2](https://user-images.githubusercontent.com/1937472/76679951-9f54c500-6649-11ea-9691-68b8520330c6.gif)

### A clear and concise description of what you expected to happen.

- Refer to Python extension, replace inputted content
![1](https://user-images.githubusercontent.com/1937472/76679986-da56f880-6649-11ea-9d09-99ccd5adb8e7.gif)

### Steps to reproduce the behavior:

The function runs while you are typing

**Comment by hyangah** [comment]
@gainskills thanks for the bug report. What is the version of `gopls` you are using?
From the integrated terminal, run `gopls version`. The latest `gopls` is `v0.3.3`.

**Comment by gainskills** [comment]
@hyangah ,
Thanks for your response. gopls's version is v0.3.3

~~~code
% ./gopls version
golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
~~~

**Comment by stamblerre** [comment]
@gainskills: Would you be able to provide a full repro case? It's a bit hard to see exactly what your example is, particularly because completion is very sensitive to surrounding context.

/cc @muirdm

**Comment by gainskills** [comment]
@stamblerre @hyangah  thank for your time.

Tried my sample again but failed to reproduce the issue. I'll close the issue and paste the example here later I could reproduce the issue.
