### ISSUE TITLE
multi config or default config for lint

### ISSUE THREAD

**Issue by elvizlai** [microsoft/vscode-go#3107]
**Is your feature request related to a problem? Please describe.**
read config file from workfolder or workspaceRoot first, it not exist, using default one.
```
  "go.lintFlags": [
    "-config=${workspaceRoot}/.revive.toml",
    "-config=~/.revive.toml",
  ],
```

**Describe the solution you'd like**
```
  "go.lintFlags": [
    "-config=${workspaceRoot}/.revive.toml",
    "-config.default=~/.revive.toml",
  ],

or something like
  "go.lintFlags": [
    "-config=${workspaceRoot}/.revive.toml;~/.revive.toml",
  ],
```

**Comment by hyangah** [comment]
The `-config` flag values are passed to the underlying lint tool as they are after doing minimal work to resolve the file path correctly. And some lint tools (e.g. `golint` doesn't take `-config` flag so this is not universal. I feel that this feature request belongs to the underlying tools, not this extension.

**Comment by stamblerre** [comment]
That sounds reasonable to me. Closing this issue as a result. Please file this feature request with your lint tool.
