### ISSUE TITLE
Cannot save files after upgrade to v1.43 - line added and removed in loop

### ISSUE THREAD

**Issue by vedev9** [microsoft/vscode-go#3109]
Issue Type: <b>Bug</b>

When i try to save a file it starts adding and removing really fast an empty row inside the import block. The code seems to "shaking" and it goes on and on without stopping. It only stops when the window crash...

This start happening right after upgrade to v1.43.0 the following are my specs:

Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Extension version: 0.13.1
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by hyangah** [comment]
@vedev9 thanks for the report. For triaging the issue, please answer the following questions:

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- <Paste go version here>
- Run `go env` to get the go build environment details
	- <Paste OS and arch details here>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

If you are using the language server, please run `gopls version` (from the integrated terminal),

Also, if you can share an example (code) that reproduces the issue or a video recording, that will be super!

**Comment by vedev9** [comment]
Thank you!

Here's the info:

Go version go1.14 windows/amd64

ENV:
```
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Projects\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Ve\AppData\Local\Temp\go-build020472354=/tmp/go-build -gno-record-gcc-switches
```

gopls: 
```
golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=

```
Settings:
```
{
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "go.testFlags": ["-test.v"]
}

```
And this is the screen capture of the error:
[bug-vscode.zip](https://github.com/microsoft/vscode-go/files/4345817/bug-vscode.zip)

Thanks for the support

**Comment by hyangah** [comment]
Thanks, @vedev9 ! 

That's pretty bad. Temporarily you may disable code action and formatting on save but yeah, that's not ideal. 

```
"[go]": {
    "editor.formatOnSave": false,
    "editor.codeActionsOnSave": {
        "source.organizeImports": false,
    },
},
```

* I suppose you are not using any other extensions that may interfere right?
* Do you still have the same issue if downgrade VS Code to 1.42? 
Go extension 0.13.x and gopls 0.3.3 have been out for a while, so I suspect VS Code.

Since it's crashing, I am not sure if we can get useful debug logs from Go extension or `gopls` with the [usual troubleshooting setting](https://github.com/golang/tools/blob/master/gopls/doc/vscode.md#vscode). @stamblerre @ramya-rao-a any better idea to capture logs? It's using `gopls` and running in `GOPATH` mode.

**Comment by vedev9** [comment]
Downgrading to v1.42 fix the issue, and it's what i have done to continue working, so no probs for me.
Just wanted to let you know about the issue with the new version v1.43

**Comment by vedev9** [comment]
I'm closing this. See previously edit 

> edit:
> ok, it's a problem with an extension as you suggested: go-group-imports
> It tries to organize imports dividing them into groups (std, 3party and organization) at save. Probably this goes against some of the formatting rules of the new v1.43 update and causes the "formatting loop"
> 
> Anyway, disabling the extension fixed the problem.

Thanks for your time
