### ISSUE TITLE
Vet and new warnings in latest version

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/vscode-go#311]
I am getting a hint that i did not get before.

"Complex literal using unkeyed fields"

I did not get this last week on the same code. The latest extension update asked to install the analysis tools, which it did ( i assume successfully).

I guess i am wondering if i can control the Vet and Hints ?
Is this actually a golang bug for vet ? See the link:
https://github.com/golang/go/issues/9171

````

sresEx.SizeFacets = append(sresEx.SizeFacets, mod.FacetResult{"L", 1})
````

My Settings file:
````

// Place your settings in this file to overwrite default and user settings.
{
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.gocodeAutoBuild": false,

    // "files.autoSave": "onFocusChange", "files.autoSave": "afterDelay",
    "files.autoSave": "onFocusChange",
    
     "telemetry.enableTelemetry": false
}

```

**Comment by lukehoban** [comment]
Yeah - sounds like a change in `go vet`, which would be a question/issue for the `golang/go` repo.

From `vscode-go` you have two options:

1. Turn off `vet` with `"go.vetOnSave": false`
2. Pass flags to `go vet` with `"go.vetFlags": []`  The syntax for flags is at https://golang.org/cmd/vet/ and each space seperated flag would be passed as an element of the flags array.

Beyond that - I don't think we would want to change the defaults from what `go vet` does by default.

**Comment by joeblew99** [comment]
Ok. I guess the go tram will sort it out, but the analysis install toll will pick it up on the next updatr
