### ISSUE TITLE
Installing golang.org/x/tools/gopls FAILED

### ISSUE THREAD

**Issue by stereoit** [microsoft/vscode-go#3111]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	-  go version go1.13.6 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.0
          78a4c91400152c0f27ba4d363eb56d2835f9903a
          x64

- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- linux
          amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
```
"go.useLanguageServer": true,
    
    "go.vetFlags": [
        "-composites=false"
    ],
```

### Describe the bug
After opening VS Code I get message to update tools, clicking update I get failure in the Output tab.

### Steps to reproduce the behavior:
```
go.toolsGopath setting is not set. Using GOPATH /home/rsmol/go
Installing 1 tool at /home/rsmol/go/bin in module mode.
  gopls

Installing golang.org/x/tools/gopls FAILED

1 tools failed to install.

gopls:
Error: Command failed: /usr/lib/golang/bin/go get -v golang.org/x/tools/gopls
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools?go-get=1
get "golang.org/x/tools/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/gopls?go-get=1
get "golang.org/x/tools/gopls": verifying non-authoritative meta tag
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20200318054722-11a475a590ac
go: extracting golang.org/x/tools v0.0.0-20200318054722-11a475a590ac
go get: golang.org/x/tools/gopls@v0.3.3 requires
	golang.org/x/tools@v0.0.0-20200227200655-6862ededa516: invalid version: unknown revision 6862ededa516
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools?go-get=1
get "golang.org/x/tools/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/gopls?go-get=1
get "golang.org/x/tools/gopls": verifying non-authoritative meta tag
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20200318054722-11a475a590ac
go: extracting golang.org/x/tools v0.0.0-20200318054722-11a475a590ac
go get: golang.org/x/tools/gopls@v0.3.3 requires
	golang.org/x/tools@v0.0.0-20200227200655-6862ededa516: invalid version: unknown revision 6862ededa516
```

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/66460/76950535-731b9b80-690a-11ea-81b6-d07670b14d0d.png)

**Comment by hyangah** [comment]
It looks like the go command was trying to download dependencies using `git` instead of using GOPROXY proxies and hit a git bug. Can you try the workaround mentioned in https://github.com/golang/go/issues/37140#issuecomment-583776533 ?

**Comment by stamblerre** [comment]
Going to close this issue since there hasn't been much activity here. @stereoit: please reopen if you're still having this issue.
