### ISSUE TITLE
"Find all References" now broken

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/vscode-go#312]
When asking, it says loading but does not do anything.
Works on simple ones, but fails on ones with lots of references.

I think it could be related to the issue wth the Vet command for go, but just speculating.

**Comment by joeblew99** [comment]
It makes me wonder if it might be better for all the Analysis tool to be not compiled on the client, but instead included in the release I know there are arguements for both.

But right now, the Analysis tools are like running a project without Vendoring. One dependency breaks and the whole things breaks.
SO, maybe do the same with the extension. Include the source that it is known to work with, and let the analysis tools compile those.
But then, mabe a user will have their own versions of the same tool ? 

mhh. not sure...

**Comment by ironcladlou** [comment]
@joeblew99 can you describe a way to reproduce the problem you're experiencing?

**Comment by joeblew99** [comment]
@ironcladlou thanks for responding...

Here is what i am experiencing:
1. All my external dependencies it works fine. Like for example i use gin for the web routing stuff and it find references to gin function with no sweat.
2. Its the links between MY code that is having the issues.


Steps to reproduce, with actual code below.
If i right click on "getMyInterfaceAddr" for "Find all References", the GUI opens with the modal "Loading..." and does nothing...

Also my Settings might be worth putting in here. Maybe i screwed them up ?
````
// Place your settings in this file to overwrite default and user settings.
{
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.gocodeAutoBuild": false,

    // "files.autoSave": "onFocusChange", "files.autoSave": "afterDelay",
    "files.autoSave": "onFocusChange",
    
     "telemetry.enableTelemetry": false
}

````


The child code:
````
package controllers

import (
	"errors"
	"fmt"
	"log"
	"net"
	"net/http"
	"net/url"
)

// getMyInterfaceAddr gets this private network IP. Basically the Servers IP.
func getMyInterfaceAddr() (net.IP, error) {

	ifaces, err := net.Interfaces()
	if err != nil {
		return nil, err
	}
	addresses := []net.IP{}
	for _, iface := range ifaces {

		if iface.Flags&net.FlagUp == 0 {
			continue // interface down
		}
		if iface.Flags&net.FlagLoopback != 0 {
			continue // loopback interface
		}
		addrs, err := iface.Addrs()
		if err != nil {
			continue
		}

		for _, addr := range addrs {
			var ip net.IP
			switch v := addr.(type) {
			case *net.IPNet:
				ip = v.IP
			case *net.IPAddr:
				ip = v.IP
			}
			if ip == nil || ip.IsLoopback() {
				continue
			}
			ip = ip.To4()
			if ip == nil {
				continue // not an ipv4 address
			}
			addresses = append(addresses, ip)
		}
	}
	if len(addresses) == 0 {
		return nil, fmt.Errorf("no address Found, net.InterfaceAddrs: %v", addresses)
	}
	//only need first
	return addresses[0], nil
}

````

The parent code that calls the child code:
````
package controllers

import (
	"fmt"
	"log"

	// Vendor
	"github.com/gin-gonic/gin"
)

// GetSessionServerIP is used so that the network IP can be discovered.
// This is useful because the Warehouse and Fitting room computers can be configured with the riht Server IP to use.
func GetSessionServerIP(c *gin.Context) {
	serverIP, err := getMyInterfaceAddr()
	log.Printf("debug: serverIP: %v", serverIP)

	if err == nil {
		c.JSON(201, serverIP)
	} else {
		message := fmt.Sprintf("error: Getting Session Server IP. %v", err)
		log.Printf(message)
		c.JSON(500, mod.Message{message})
	}

}
````

**Comment by ironcladlou** [comment]
@joeblew99 what is your GOPATH set to? I don't see a `go.gopath` setting specified. Are you relying on environment? What do you see when running `Go: Current GOPATH` from the command palette?

**Comment by OneOfOne** [comment]
You have `"go.gocodeAutoBuild": false`, and gocode depends on the compiled code, while I'm not very familiar with how vscode-go works, I think if you set this to true it will work fine.

Otherwise you will have to manually do go install every now and then.

**Comment by joeblew99** [comment]
Thanks for pointing me in right direction. I try out that setting and see
if it works

**Comment by joeblew99** [comment]
@ironcladlou The gopth is fine. Everything compiles outside oof vscode fine. So can't be that I feel
