### ISSUE TITLE
“Run without debugging” unable to run on macOs when used gomod.

### ISSUE THREAD

**Issue by hawkwzh** [microsoft/vscode-go#3121]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.14 
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.31.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- darwin/amd64

### Share the Go related settings you have added/edited
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "git.enabled": false,
    "window.zoomLevel": 0,
    "workbench.iconTheme": "vscode-icons",
    "editor.defaultFormatter": "ms-vscode.Go",
    "go.autocompleteUnimportedPackages": true,
    "extensions.ignoreRecommendations": false,
    "go.docsTool": "gogetdoc",
    "go.useLanguageServer": true
}

“Start debugging” can run ,but “Run without debugging” unable to run on macOs when used gomod.

log:
Verbose logs are written to:
/var/folders/5v/f083s3c147b8xhll1wng2_8m0000gq/T/vscode-go-debug.txt
InitializeRequest
InitializeResponse
Using GOPATH: /Users/fish/Documents/code/go_path
../../../../code/go_workspace/ro/main.go:5:2: package ro/local is not in GOROOT (/usr/local/go/src/ro/local)
Process exiting with code: 1
Sending TerminatedEvent as delve is closed
DisconnectRequest
DisconnectRequest to parent

My code:
<img width="602" alt="p" src="https://user-images.githubusercontent.com/15761455/77277278-86a67800-6cf7-11ea-83fa-ef3e7396841e.png">

Please check it.

**Comment by stamblerre** [comment]
I was able to reproduce this issue with a minimal repro. My guess is that this is running explicitly in GOPATH mode. This needs investigation and a fix.

**Comment by hyangah** [comment]
Can any of you share the minimal repro case including the `go.mod` file? `.zip` file is fine.

**Comment by stamblerre** [comment]
Ah, this was my mistake - I thought that this command came from the Go extension, but it comes from the user's `launch.json`. I'm seeing flaky behavior - if I use the default configuration, it works fine, but if I create a default `launch.json` file, I see the error. I'm not sure how to see what command is being executed under the hood.

@hawkwzh: What is the contents of your `launch.json`?

I've attached the repro.
[mod1.zip](https://github.com/microsoft/vscode-go/files/4371319/mod1.zip)

**Comment by hawkwzh** [comment]
@stamblerre 
Just create launch.json, nothing changed.
<img width="750" alt="f" src="https://user-images.githubusercontent.com/15761455/77388223-76ab9880-6dca-11ea-88b3-75ed99f118f8.png">

**Comment by hyangah** [comment]
I think I know what's going on. 

Bug 1: When `Run Without Debugging` is invoked, `resolveDebugConfiguration` in goDebugConfiguration.ts is called with the initial debugConfiguration object with `"noDebug": true`, but it is overwritten [here](https://github.com/microsoft/vscode-go/blob/28bab92821e0233f2a3467b396ebfba22f94131e/src/goDebugConfiguration.ts#L50) and the noDebug info is lost. As a result, later, I observed the debug adapter runs the program with debugging enabled (i.e. run through `dlv`).

Bug 2: When the debug adapter receives the request with `"noDebug": true`, it invokes `go run <currentFIle>` where the currentFile is the absolute path to the test file. And, it runs this command from the root directory `/`, which means the main module doesn't exist. The `go run` command operates in GOPATH mode and fails. So in this case, we should make the `go run` command to run inside the module. 

I will prepare a cl.


When launch.json doesn't exist,

**Comment by ramya-rao-a** [comment]
The fix to this is available in the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension. Please do try it out and share feedback

**Comment by hawkwzh** [comment]
@ramya-rao-a   it's worked. 
thanks.

**Comment by ramya-rao-a** [comment]
The latest version of the extension has the fix to this issue
