### ISSUE TITLE
Change definition / signature of method or function

### ISSUE THREAD

**Issue by karuppiah7890** [microsoft/vscode-go#3122]
**Is your feature request related to a problem? Please describe.**
I use IntelliJ and VS Code - both for development. VS Code usually for my open source contributions. I noticed that IntelliJ has this cool feature to change the definition / signature of a method or a function - where one can change the parameter's type, add a parameter with a default value for all the callers, and change the return parameters too

**Describe the solution you'd like**
VS Code to provide the feature to change the definition / signature of a method or function, which changes all the references of the method or function based on the change

**Describe alternatives you've considered**
Some features of the change signature feature can still be used currently - For example changing the name of the parameters - which will only cause a change inside the method or function and it can be done by doing just a rename. Other than that, the only alternate solution for me now is - to find all the references and change all the callers to add a parameter and do something similar for other things too.

**Additional context**
It would be cool for VS code to provide this feature. Not sure how it will be implemented. Is this a feature that should be provided by `gopls`? And if help is needed, I can pitch in - raise some PRs. I need to learn some stuff, which I can surely do. It would be a pleasure to raise PR for one of the greatest extensions for Golang 😄

**Comment by stamblerre** [comment]
Thanks for the feature request! We are planning on working on this in `gopls`, so I will move this request to golang/go#38028 and close this issue in favor of the upstream one.

**Comment by karuppiah7890** [comment]
Thanks @stamblerre ! :)
