### ISSUE TITLE
When using gopls, Find All References fails

### ISSUE THREAD

**Issue by josh-tepper** [microsoft/vscode-go#3124]
Issue Type: <b>Bug</b>

This follows up on https://github.com/microsoft/vscode-go/issues/2914 submitted by another user.  I'm experiencing the same behavior: Find all references only resolves references within the symbol's package, but not in other packages.

However, I'm using a version of gopls that supposedly includes the fix for this (per the discussion on the ticket):
```
$ gopls version
golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=
```
Reverting the vscode config to not use gopls fixes the issue.

Similarly invoking guru and gopls on the command line reveals the same disparity (guru includes references from other packages, gopls does not).

Please let me know what you need to debug

Extension version: 0.13.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by stamblerre** [comment]
@josh-tepper: Are you using modules or GOPATH?

**Comment by josh-tepper** [comment]
I am.

After looking at [this comment](https://github.com/golang/go/issues/32869#issuecomment-559662189) on the gopls issue, I thought that this might have to do with the workspace root.  My workspace root is a _parent_ of the relevant go/src dir (an artifact of our mono-repo setup).  I tried opening the go/src directory as the root, and this resolved the issue.

However this is frustrating.  Given our monorepo setup, I don't want to have to restrict to the child directory.  Actually, I have two $GOPATH entries that are both children of my workspace root (as well as other non-go code).

**Comment by josh-tepper** [comment]
Even lacking a fix for the "multiple GOPATH entries as children" issue, it would still be helpful if it could handle the case when one is a child (in my case, the second is just an experimental dir for playing with non-production code -- and I could exclude it if that would help).

**Comment by stamblerre** [comment]
You can add additional folders to your VS Code workspace to have a multi-project workspace (File > Add Project to Workspace). We don't currently support searching across multiple folders in a project (unless you open their common parent directory), but we will be adding support for that in [`gopls/v0.5.0`](https://github.com/golang/go/milestone/138).

**Comment by josh-tepper** [comment]
Actually, I _am_ talking about opening a common parent directory.  And I wasn't even able to get it to work with _one_ child directory. Consider the following directory structure:
```
/a/
 | - go/     <-- GOPATH
      |- src/
          | - b/..
          | - c/...
```

1. Workspace root set to `/a/`: Does _NOT_ work.  Each symbol only finds references within its own package.
2. Workspace root set to `/a/go/src/`: _Works_.  Symbols find references anywhere in /a/go/src/..
3. Workspace root set to ` /a/go/src/b/`: _Works_.  Symbols find references anywhere in /a/go/src/b/.. (even outside of their own package), but correctly don't find references from /a/go/src/c/..

When I mentioned two directories before, I was just saying that my initial setup when I first reported the failure had to directories in my GOPATH -- In the structure above, /a/go and /a/experimental/go, and the workspace root was set to /a/.  However, since it _also_ fails in the simpler case where there is only one child dir in the go path (ie case 1 above), we can ignore the two GOPATH setup for now.

**Comment by stamblerre** [comment]
Thank you for the clarification! I just filed https://github.com/golang/go/issues/38078 to track this upstream.
