### ISSUE TITLE
gopls: suggest filing an issue if the user restarts the language server

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-go#3128]
If the user manually runs `Go: Restart Language Server`, we should suggest filing an issue. The options should look something like "Yes", "No", and "Never" so that users can opt out.

**Comment by hyangah** [comment]
Will the suggestion pop up when we trigger (or were asked to trigger) the lsp restart command because we update settings.json?

**Comment by stamblerre** [comment]
Yeah, I was thinking it could pop up once that command is run, and then if the user chooses "Never" we could update the settings so we never ask again.

**Comment by stamblerre** [comment]
Closing in favor of https://github.com/golang/vscode-go/issues/25.
