### ISSUE TITLE
Failed to install go tools in China,  please help to add cn site. thanks very much .

### ISSUE THREAD

**Issue by lypat2008** [microsoft/vscode-go#3129]
Dear,
   Could you help on this issue ?  thanks.

**error message:**
C:\Users\ypluo\go\src>Finished running tool: C:\Go\bin\go.exe vet .

Installing github.com/mdempsky/gocode FAILED
Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs FAILED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/cweill/gotests/... FAILED
Installing github.com/fatih/gomodifytags FAILED
Installing github.com/josharian/impl FAILED
Installing github.com/davidrjenni/reftools/cmd/fillstruct FAILED
Installing github.com/haya14busa/goplay/cmd/goplay FAILED
Installing github.com/godoctor/godoctor FAILED
Installing github.com/go-delve/delve/cmd/dlv FAILED
Installing github.com/stamblerre/gocode FAILED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/sqs/goreturns FAILED
Installing golang.org/x/lint/golint FAILED

17 tools failed to install.

**Reason:** 
China Firewalled killed all of google's web sites.

Maybe Solution:
can help add this google's Chinese web stie for package source ? or it is a bad idea ?
https://golang.google.cn/    

Thanks very much .

**Comment by hyangah** [comment]
Have you tried to set `GOPROXY` environment variables? You will need it anyway for most Go commands to work.

**Comment by lypat2008** [comment]
> Have you tried to set `GOPROXY` environment variables? You will need it anyway for most Go commands to work.

the default setting is : 
GOPROXY=https://proxy.golang.org/

so I changed it to : 
GOPROXY=https://goproxy.io/

and OK now.

**Comment by stamblerre** [comment]
Glad to hear it! I'll close this issue now then.

**Comment by DachuanZhao** [comment]
> > Have you tried to set `GOPROXY` environment variables? You will need it anyway for most Go commands to work.
> 
> the default setting is :
> GOPROXY=https://proxy.golang.org/
> 
> so I changed it to :
> GOPROXY=https://goproxy.io/
> 
> and OK now.

The command is ```go env -w GOPROXY=https://goproxy.io/,direct```
