### ISSUE TITLE
golang-vscode docker image

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/vscode-go#313]
I bundled VSCode with this extension and its dependencies on top of the official golang docker image. I'll do a subsequent blog post about it, but here is one way to run it via Docker for Windows:

https://twitter.com/cmr0n/status/726984126176202752
http://blog.ctaggart.com/2016/05/visual-studio-code-served-from-docker.html

Happy to take question and feedback here. I guess my question is, would someone like to make this even more official way to distribute and try out this extension?

**Comment by mattetti** [comment]
It's really cool but as a VS Code user and a Docker for Mac beta tester, I would probably still not want to run VSCode in a container unless I need to write code for Linux only for instance (raspberry programming or whatever).

**Comment by ramya-rao-a** [comment]
Closing this as there has not been any ongoing discussion here
