### ISSUE TITLE
Test for build tags failing on Go tip

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#3130]
The test with title `Build Tags checking` is failing consistently, but only on Go tip

https://travis-ci.org/github/microsoft/vscode-go/jobs/666658067?utm_medium=notification&utm_source=github_status

cc @stamblerre, @hyangah

**Comment by hyangah** [comment]
Probably https://go-review.googlesource.com/c/go/+/185345
I see the test look for the specific error message. Does the Go extension's behavior depend on the  specific error message?

**Comment by ramya-rao-a** [comment]
> Does the Go extension's behavior depend on the specific error message?

No, it doesnt. Am fine with removing checks on the exact contents of the error message
