### ISSUE TITLE
gofmt formating seems bit weired on map keys

### ISSUE THREAD

**Issue by Jeyanthinath** [microsoft/vscode-go#3133]
This is the gofmt autoformatted text, while saving the file.

<img width="893" alt="Screenshot 2020-03-27 at 10 28 03 AM" src="https://user-images.githubusercontent.com/2253649/77723191-c16d2080-7015-11ea-8799-10cc699b1cc4.png">

but if you see the final element of map `testingalerts` which is having less characters is aligning the colon to left side (see above image), but if I add more characters its aligning to right side  (see below image)

<img width="883" alt="Screenshot 2020-03-27 at 10 33 08 AM" src="https://user-images.githubusercontent.com/2253649/77723433-743d7e80-7016-11ea-9a39-56aacd0fb702.png">

is this is expected behaviour or there is a problem around here ?

**Comment by stamblerre** [comment]
Looks like this is working as intended: https://github.com/golang/go/issues/10392.
