### ISSUE TITLE
"go to definition" and other navigation function doesn't work in VSCode / Go / MacOS

### ISSUE THREAD

**Issue by neo-liang-sap** [microsoft/vscode-go#3138]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.4 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.2
0ba0ca52957102ca3527cf479571617f0de6ed50
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- only VSCode Go extension is installed, version is 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- darwin
           amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

```
{
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "http.proxy": "xxxxxx",
    "editor.fontSize": 14
}
```

### Describe the bug
"go to definition" and other navigation function doesn't work in VSCode / Go / MacOS

### Steps to reproduce the behavior:
1. Open one of source go file
2. Right Click on any function, go to definition
3. See error , it keeps `loading` but never returns

This error suddenly occurs, i have tried reinstall vscode/ go extension/ downgrade vscode/ downgrade go extension but none help

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/42594392/77900687-fc3eb500-72b0-11ea-825d-63612565209b.png)
![image](https://user-images.githubusercontent.com/42594392/77900690-fea10f00-72b0-11ea-8d43-c68854794099.png)
![image](https://user-images.githubusercontent.com/42594392/77900700-019bff80-72b1-11ea-916b-7bf036ae0a93.png)
![image](https://user-images.githubusercontent.com/42594392/77900703-03fe5980-72b1-11ea-88dd-1419ff0bb2f2.png)
![image](https://user-images.githubusercontent.com/42594392/77900711-0791e080-72b1-11ea-9763-a8834f0b58d8.png)

**Comment by neo-liang-sap** [comment]
fix by
```
rm -rf /Users/wilbertliu/Documents/go/src/github.com/ianthehat/godef
/usr/local/bin/go get -u -v -d github.com/ianthehat/godef
```

**Comment by hyangah** [comment]
@neo-liang-sap  When using `gopls` as the language server, `godef` shouldn't be necessary for Go To Definition functionality.
What is the language server you are using, and what is the version?

If you are using gopls, you can check its version by running `which gopls; gopls version` from the VS Code integrated terminal. The latest released gopls is v0.3.4.

**Comment by neo-liang-sap** [comment]
```
~/git_repo/gardenctl(master*) »  which gopls                                                                                                                     (test-aks/kube-system)
/Users/i352986/go/bin/gopls
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/git_repo/gardenctl(master*) » gopls version                                                                                                                    (test-aks/kube-system)
golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=
```

**Comment by hyangah** [comment]
@neo-liang-sap Have you tried to delete godef completely and see if Go To Definition breaks? (I don't use godef myself and didn't have an issue unless I invoke it manually).

**Comment by stamblerre** [comment]
@neo-liang-sap: Can you run `gopls -rpc.trace -v query definition path/to/file.go:<line>:<col>`?

**Comment by neo-liang-sap** [comment]
hi, without go-def the function of `go to definition` won't work, please close this issue as i've solved this by manually install go-def

**Comment by hyangah** [comment]
@neo-liang-sap  Good to hear that your problem is fixed. 
But, `gopls` supports `go to definition` (F12, or mouse right click->"Go to Definition") feature and you shouldn't have a problem if `gopls` performs correctly. FYI I don't have godef or any of its variation installed.
