### ISSUE TITLE
Terminal (bash) ignores control codes

### ISSUE THREAD

**Issue by mwat56** [microsoft/vscode-go#3139]
Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- linux
amd64

### Describe the bug

For some time now the `bash` in the editor terminal ignores certain characters.
First I noticed that I had to input certain keystrokes twice (e.g. Ctrl-R and Ctrl-M) but now those keystrokes are apparently ignored completely – which, if I may say so, is quite annoying. For example, Ctrl-R is used to find an entry in the `bash` history, something I use quite frequently. Now I have to use the Up-key several time instead of a single Ctrl-R.

### Steps to reproduce the behavior:
    Terminal window
    Enter e.g. Ctrl-R to navigate bash history
3. See error
    Nothing happens (input is ignored)

Any ideas how to restore the usual `bash` behaviour?

-- 
     Matthias

**Comment by hyangah** [comment]
The terminal is managed by VS Code, and this is not VS Code Go extension issue. 

--

Are you using bash? Is your bash and key binding set up correctly?
You can check your current shell and your key bindings with commands like
```
$ echo $0
$ bind -p   
```

**Comment by stamblerre** [comment]
> The terminal is managed by VS Code, and this is not VS Code Go extension issue.

As @hyangah said, this is a VS Code issue, not a VS Code Go issue, so I'd recommend opening it in https://github.com/microsoft/vscode.

**Comment by mwat56** [comment]
Hi @stamblerre!

> > The terminal is managed by VS Code, and this is not VS Code Go extension issue.
> 
> As @hyangah said, this is a VS Code issue, not a VS Code Go issue, so I'd recommend opening it in https://github.com/microsoft/vscode.

Thank's for your kind note.

I went through the issues there and just for reference

    "terminal.integrated.allowChords": false,

fixes the problem with ignored Ctrl keys in the terminal.

**Comment by stamblerre** [comment]
Glad to hear you've been able to resolve the issue!
