### ISSUE TITLE
Your workspace is misconfigured

### ISSUE THREAD

**Issue by belolap** [microsoft/vscode-go#3142]
I have workspace with multiple folders. Some of them - go modules and one - no, it just documentation (named `meta` in my case).

When vscode starts I see error message, that my `meta` package is not go module:

```
Your workspace is misconfigured: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module, but found .git/config in /home/gik/Код/go/src/<cut>/meta
	to create a module there, run:
	go mod init
. Please see https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md for more information or file an issue (https://github.com/golang/go/issues/new) if you believe this is a mistake.
```

But there is no go module in this folder and I must no see this error message. I need either option to disable this error at all or another way to detect is folder go package or not. May be count *.go files, and if there is no *.go files, disable this message.

**Comment by hyangah** [comment]
This is expected given the current limitation of `gopls` (https://github.com/golang/go/issues/33030#issuecomment-510151934). See the upstream bugs like https://github.com/golang/go/issues/32394. 

The current workaround is to add each folder to workspace using VS Code's  ["Add Folder to Workspace"](https://code.visualstudio.com/docs/editor/multi-root-workspaces)

**Comment by Delphier** [comment]
Running the following command can temporarily resolve outside the gomod directory:
`
go get golang.org/x/tools/gopls@a5e5fedfe7429586fde86c123b10f1bc23d21a25 golang.org/x/tools@a5e5fedfe7429586fde86c123b10f1bc23d21a25
`

**Comment by hyangah** [comment]
@stamblerre the description of the [commit]((https://go.googlesource.com/tools/+/a5e5fedfe7429586fde86c123b10f1bc23d21a25)  mentioned in the above comment just talks about the suppressing of the error message. Does it mean that the error message was spurious and `gopls` can detect the modules in subdirectories in the upcoming release?

**Comment by stamblerre** [comment]
> This is helpful for users to diagnose issues, but it annoys people who
have workspaces with both non-Go and Go projects.

There error message isn't spurious, but if `gopls` gets started in a workspace that contains both Go and non-Go projects, we will report failures for the non-Go workspace. Users don't want error messages about workspaces that shouldn't work, which is why we suppressed the message. `gopls` can't detect modules in the coming release, but this issue will be resolved because the error message won't show up.
