### ISSUE TITLE
env gopath being ignored

### ISSUE THREAD

**Issue by zeph** [microsoft/vscode-go#3144]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.2 0ba0ca52957102ca3527cf479571617f0de6ed50 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- ms-vscode.go 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- linux amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
 - "go.formatTool": "goimports"

### Describe the bug
I open vscode and I get asked to import dependencies... I allow, it starts to download them in a random $HOME/go place that I did not specify anywhere.
I expect the GOPATH env variable to be respected. If I open a terminal within vscode, I type "go env", i see it correctly set. No, I do not override it in any launch.json or similar file.

### Steps to reproduce the behavior:
1. checkout github.com/oauth2-proxy/oauth2-proxy
2. open the vscode in the folder 
3. it will ask for importing dependencies and will download where not expected

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by hyangah** [comment]
Does the output (popup) of `Command Palette ->  "Go: Current GOPATH"` match what you expect?

**Comment by zeph** [comment]
@hyangah no, it does not

**Comment by stamblerre** [comment]
> I open vscode and I get asked to import dependencies... I allow, it starts to download them in a random $HOME/go place that I did not specify anywhere.

`$HOME/go` is the default `GOPATH`, so it seems like VS Code is not using your configured GOPATH for some reason. Do you mind sharing a screenshot of what you're seeing? I'm not sure if VS Code imports dependencies, but it may be installing tools, in which case it should specify which `GOPATH` it will use in the pop-up.

**Comment by zeph** [comment]
@stamblerre what kind of screenshot? all the relevant informations are in the ticket

**Comment by hyangah** [comment]
@zeph We want to help but we need more info - I cannot reproduce the issue following your repro intro, so there is something particular in your environment.  

- How did you set the GOPATH? 
- How did you launch your VS Code and how did you pass the GOPATH env var to the VS Code? (typically this is done by invoking 'code' from command line and inheriting the environment variables of the terminal, or by configuring the program launcher).
- I think VS Code terminal may execute your login shell which may set different env vars.

**Comment by zeph** [comment]
@hyangah I know you are trying to help and I didn't mean to be rude or anything, I just didn't see the point of a screenshot... (also because I'm currently working on it). Anyhow, GOPATH is set from `.bashrc` with an `export`. I either execute VS Code via terminal (from a running bash process) or from the helper of i3 (a compact window manager), which inherits my environment variables defined in my .bashrc. My VS Code terminal, might indeed source my login shell

aha... wait... 

`code` ran from the terminal, comes up with a correct setup... `code` ran from the i3, no

ok, it is insourcing different env settings... good lead

**Comment by zeph** [comment]
ok, back to the `.profile`, already stumbled on this pointer
https://www.reddit.com/r/i3wm/comments/d0tyzk/cant_initialize_environment_variables_for_i3_exec/ 

a UI reload of i3 doesn't seem enough... I'll give it a try later doing a full logout/in

**Comment by zeph** [comment]
nope, doesn't work even with `export GOPATH="${HOME}/tmp/.go"` inside `.profile`
(I did stop/start the `slim` daemon and therefore X11/Xorg)... still aiming to the wrong GOPATH

**Comment by hyangah** [comment]
@zeph Can you check if the vscode got the right env variable form  'Developer: Toggle Developer Tools'? (Command Palette -> 'Developer: Toggle Developer Tools', which opens the chrome developer tools window. Select 'Console' tab, and enter 'process.env.GOPATH'. If it is set as you set in your bashrc or profile, this is Go extension's problem. Otherwise, needs to ask vscode community.

**Comment by zeph** [comment]
`undefined` :/

**Comment by stamblerre** [comment]
A workaround for the time being would be to set your `go.gopath` or your `go.toolsGopath` explicitly in your VS Code settings.
