### ISSUE TITLE
Feature request: hover info on runes

### ISSUE THREAD

**Issue by clipperhouse** [microsoft/vscode-go#3149]
In Go, runes can be expressed as single-quoted readable glyphs, single-quoted escaped `\u` codes, or number literals (usually hex). It’s often hard to know what a particular rune is, short of extensive commenting as in [this example](https://github.com/golang/go/blob/master/src/unicode/tables.go#L7108).

It would be very helpful in VSCode to hover over _any_ of these forms to get info on the rune, such as:

- visual glyph (if any)
- description e.g. “ARABIC THOUSANDS SEPARATOR” 
- `\u` representation
- hex representation

Thanks for the consideration, happy to discuss.

**Comment by stamblerre** [comment]
Thanks for the suggestion! This is probably not something that we will do in this extension, but we can consider implementing it in `gopls`. I've opened up golang/go#38239 to track this. I'll close this issue, but you can follow along with the progress there.
