### ISSUE TITLE
vscode-go regularly fails to properly detect valid syntax

### ISSUE THREAD

**Issue by Sebi2020** [microsoft/vscode-go#3151]
### What version of Go, VS Code & VS Code Go extension are you using?
- `go version`
	- go version go1.14.1 windows/amd64
- VS Code version
	-  1.43.2 ... x64
- VS Code go extension version
	- 0.13.1
- `go env GOOS GOARCH`
	-  windows, amd64

### Share the Go related settings you have added/edited

"go.useLanguageServer": true,

### Describe the bug
vscode-go constantly fails to detect valid golang syntax.

### Steps to reproduce the behavior:
1. Write Code like this:
![buggy-vscode](https://user-images.githubusercontent.com/1862664/78450455-f49b5980-767e-11ea-9fac-04c3e2f81e77.png)

Produces the following error:
```
expected ';', found 'package' [syntax 25,2] (red line in the image)
```
Which absolutly makes no sense at all with go. Go does not have any semicolons in the entire language.

**Comment by hyangah** [comment]
- Does the error message always appear, or while editing? 

-  Does the error disappear if you save the file or restart the language server? (From the command palette "Go: Restart Language Server")

- Can you please share your extension settings (those start with `go.`, `gopls.` and `[go]`) and [gopls logs](https://github.com/golang/tools/blob/master/gopls/doc/vscode.md)? The gopls logs will appear in the "Output" -> 'gopls' channel.

FYI the error message is from the go command. Even though Go does not use semicolons, it uses semicolons internally in its parser. But yeah, the stale, misleading diagnosis message is annoying. :-(

**Comment by stamblerre** [comment]
@Sebi2020: Was this after you created a new file? This is the error message that the `go` command shows when you have an empty file, and there used to be a `gopls` bug in the creation of new files. It should be fixed in the next version of `gopls` - you can give that a try by installing the pre-release (`GO111MODULE=on go get golang.org/x/tools/gopls@v0.4.0-pre1`).

**Comment by Sebi2020** [comment]
@hyangah 


> * Does the error message always appear, or while editing?
Not always, but vscode-go often keeps showning errors were already have been fixed.

> * Does the error disappear if you save the file or restart the language server? (From the command palette "Go: Restart Language Server")
I cannot reproduce this bug. I does not have the file anymore. My fault.,. I try to add more details as soon as I experience the bug again.

> * Can you please share your extension settings (those start with `go.`, `gopls.` and `[go]`) and [gopls logs](https://github.com/golang/tools/blob/master/gopls/doc/vscode.md)? The gopls logs will appear in the "Output" -> 'gopls' channel.
I have only one entry regarding go: `"go.useLanguageServer": true`

Maybe this is caused by the bug of `gopls` as @stamblerre suggested.

**Comment by jerkinson92** [comment]
Expecting the same issue sometimes, also same error.
I will give more information when find the way to reproduce error.
One thing that I may say - such error appears oftenly.

After Cmd+P > Reload Window error disappear.

**Comment by stamblerre** [comment]
If you are using `gopls`, please share a screenshot and your `gopls` logs (https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs) if you can.
