### ISSUE TITLE
Add support for installing pre-release versions of gopls

### ISSUE THREAD

**Issue by deoren** [microsoft/vscode-go#3153]
Existing conversation: https://twitter.com/deoren/status/1246447039099133952

In short, there is a new pre-release of v0.4.0 for `gopls` that users have been encouraged to try and give feedback on. Steps were provided to manually download/install `gopls` and I'll follow those steps soon.

What would be useful is to have either a setting in the stable version of `ms-vscode.go` or a separate "Preview" extension of `ms-vscode.go` (as with the PowerShell Preview extension for Visual Studio Code) to install pre-release versions of `gopls`. 

Thank you for your time and consideration!

**Comment by stamblerre** [comment]
Thanks for filing this issue! 

> What would be useful is to have either a setting in the stable version of `ms-vscode.go` or a separate "Preview" extension of `ms-vscode.go` (as with the PowerShell Preview extension for Visual Studio Code) to install pre-release versions of `gopls`.

We actually already have this exact set up through the nightly build of this extension ([Go Nightly](https://marketplace.visualstudio.com/items?itemName=golang.go-nightly)). It also offers auto-updates for `gopls` pre-releases.

**Comment by deoren** [comment]
> We actually already have this exact set up through the nightly build of this extension ([Go Nightly](https://marketplace.visualstudio.com/items?itemName=golang.go-nightly)). It also offers auto-updates for `gopls` pre-releases.

Apologies, I completely missed seeing that extension! Thanks for being so kind in your response. :)
