### ISSUE TITLE
placeholder of `Launch file` is missing `}`

### ISSUE THREAD

**Issue by tom-shan** [microsoft/vscode-go#3154]
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.0
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- windows 10 x86-64

### Share the Go related settings you have added/edited
Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

no edited setings of go extension

### Describe the bug
A clear and concise description of what the bug.

whem add configuration of go extension, the placeholder  of `Launch file` is missing }.

### Steps to reproduce the behavior:
1. click add configution and choose `Go: Launch file`
2. See the placehold of `${file}`

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

![image](https://user-images.githubusercontent.com/7686800/78498958-4e377d00-7780-11ea-9446-cc56e39e8635.png)

**Comment by tom-shan** [comment]
fixed by https://github.com/microsoft/vscode-go/commit/383c0c0bd826ebcc6256d2da3039f8ed8da11217

**Comment by ramya-rao-a** [comment]
The latest update 0.14.2 has the fix for this, Thanks @tom-shan
