### ISSUE TITLE
Go: Add Imports adds full path to vendored dependency, instead of the vendored path

### ISSUE THREAD

**Issue by MikeMangialardi** [Microsoft/vscode-go#316]
Let's say you have a dependency vendored at <$GOPATH/src/vendor/github.com/foo/bar>. If you use cmd+shift+p > Go: Add Import to import that dependency into your current working file, it will add the string "vendor/github.com/foo/bar" instead of "github.com/foo/bar" to that file's imports. Since vendoring is now officially suppported in Go 1.6 (and support for ignoring vendoring will be removed in Go 1.7), I think that the Go: Add Import functionality should conform to the standard.

**Comment by ivahaev** [comment]
Mike, i think, vendor dir must be in project, not in $GOPATH/src

**Comment by MikeMangialardi** [comment]
While I know that Glorious Leader 'Commander' Rob Pike says we should put all of our go source code within a single GOPATH, my coworkers and I have been following the GOPATH per project paradigm, and we are able to vendor files within the /src directory without issue. If the 'go' tool supports $GOPATH/src/vendor working for vendored dependencies, I think it's only fair that go tools for VS Code support that as well. If you want, I would be happy to spend some time to put together a pull request to get this to work.

**Comment by freeformz** [comment]
FWIW: The go tool supports `$GOPATH/src/vendor/<package>`. This surprised me as well when I was rewriting `godep`'s resolver and while I don't know what the use case it, it's something that the tool supports and so should integrations.

**Comment by peterbourgon** [comment]
When resolving import paths for vendored code, the compiler starts at the current directory and walks backwards, up to $GOPATH, looking for directories called `vendor`.

**Comment by ramya-rao-a** [comment]
This has been fixed in the latest version of the extension : 0.6.45
