### ISSUE TITLE
Can't fold a slice

### ISSUE THREAD

**Issue by islishude** [microsoft/vscode-go#3160]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.1 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.2 0ba0ca52957102ca3527cf479571617f0de6ed50 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.0-beta.3
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- darwin/amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

```json
{
    "go.formatTool": "goimports",
    "go.lintTool": "golangci-lint",
    "go.useLanguageServer": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": true,
        "completeUnimported": true,
        "deepCompletion": true,
        "hoverKind": "FullDocumentation",
        "staticcheck": false
    },
    "go.lintFlags": [
        "--fast"
    ]
}
```
### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings

The `List` variable has no fold button(-)

![屏幕快照 2020-04-08 下午3 18 48](https://user-images.githubusercontent.com/24730006/78755774-4bb96b00-79ac-11ea-9a0c-d49cd233ced3.png)

**Comment by hyangah** [comment]
@islishude I am guessing you are using the language server (`"go.useLanguageServer": true`). Is it true?

@stamblerre I observed folding range responses from `gopls` do not include the slice variable ranges. Disabling language server, I don't know which tool is supplying the folding range info yet but I could see the folding range markers for the entire list and for each element. (e.g. line 9, line 10, line 15 in the above example). Is there any option for users to turn on or a tracking bug for gopls already?

**Comment by islishude** [comment]
yes,I using gopls.

**Comment by stamblerre** [comment]
Thanks for reporting! Moved this bug to https://github.com/golang/go/issues/38360, so I'll close this issue in favor of the upstream one.
