### ISSUE TITLE
Example of Debugging Go CLI with vscode in Documentation

### ISSUE THREAD

**Issue by danielhelfand** [microsoft/vscode-go#3166]
**Is your feature request related to a problem? Please describe.**

As part of working on a CLI developed using the [cobra](https://github.com/spf13/cobra) framework, I didn't find many examples or documentation on debugging a CLI with vscode. Most information I have seen is focused web applications, but obviously a CLI is more focused on passing subcommands/flags with arguments to the root command of the project.

What I ultimately put together to debug my CLI was something along the lines the following `launch.json`:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "/path/to/cli/cmd/root",
            "env": {},
            "args": ["subcommand", "argument", "--flag", "arg"],
        }
    ]
}
```

The keys to this is how to specify args (i.e. a list of strings for each part of the command)/running in debug mode.

**Describe the solution you'd like**

This is obviously a very specific use case, so maybe the appropriate way to handle this really centers around sharing this information beyond just documentation (e.g. a tutorial video or some other way), but I think it would at the very least be helpful to add an example in the documentation [here](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#snippets-for-debug-configurations).

**Additional context**

Not sure if the way I am suggesting above in my `launch.json` is the recommended approach, but I found it was what worked for me.

**Comment by hyangah** [comment]
Utilizing `args` is the right thing to use for passing args. Agree we need to document that.

**Comment by ramya-rao-a** [comment]
Closing this in favor of https://github.com/golang/vscode-go/issues/136 as [we are moving](https://github.com/microsoft/vscode-go#we-are-moving---)!

Please subscribe to the new issue for further updates
