### ISSUE TITLE
UI to examine core dumps

### ISSUE THREAD

**Issue by ajax16384** [microsoft/vscode-go#3169]
Please add launch "mode" : "core" to be able to examine go core dumps as command line debugger "dlv core ..." does.

**Comment by hyangah** [comment]
@ajax16384 I love delve's core dump feature. Go extension heavily depends on [DAP](https://github.com/Microsoft/vscode-debugadapter-node) and I don't know if DAP is capable of doing this. Maybe need research on how c++ extension implemented [the similar feature](https://code.visualstudio.com/docs/cpp/cpp-debug#_memory-dump-debugging).

cc/ @polinasok @lggomez @quoctruong for debug ideas.

**Comment by lggomez** [comment]
@hyangah I will look into this, but if anyone alse also wants to give it a shot or research it here's what I found:

For comparison, here's the [goland feature](https://www.jetbrains.com/help/go/exploring-go-core-dumps.html#)

This is the cli entry point for the `dlv core` command
https://github.com/go-delve/delve/blob/master/cmd/dlv/cmds/commands.go#L258-L276

And here is the debugger service entry point:
https://github.com/go-delve/delve/blob/00aab8d6902d2bc24550ed598ecfc63d04bb5a44/service/debugger/debugger.go#L125-L135

There is no direct action done to be done or supported additionally from the DAP callbacks, but I could be wrong. What is clear is that the debug server starts and loads the dump as the current program state, thus requiring us to be able to configure this parameter (the dump file path and core action or backend property in out `launch.json`)

This looks very similiar to the work I've done for #2414 (as it is just another backend aside from `rr`), so for a quick test I might fork that branch to try this and come back in case it can be applied to this scenario

**Comment by lggomez** [comment]
As I said, I'm working on the rr replay branch and there is some support ready for core files:

![Captura de pantalla de 2020-04-19 00-26-18](https://user-images.githubusercontent.com/6326271/79678814-98cfe500-81d5-11ea-8aba-841853f30452.png)

Locals are not loaded but lines can be still traced from the stacktrace correctly, I think tihs can be polished further and according to the capabilities of the core debug process in this instance

**Comment by lggomez** [comment]
Here's the core dump and the application, for reference and testing:

[core.zip](https://github.com/microsoft/vscode-go/files/4498341/core.zip)
[helloworld_modules.zip](https://github.com/microsoft/vscode-go/files/4498343/helloworld_modules.zip)

Additionally, the debug configuration used (attached to the local debugServer for adapter debug purposes but it can be commented):

```
{
            "name": "core:Launch",
            "debugServer": 4711,
            "type": "go",
            "request": "launch",
            "mode": "core",
            "program": "${workspaceRoot}/main/main.go",
            "env": {},
            "args": [],
            "dlvLoadConfig": {
                "followPointers": true,
                "maxVariableRecurse": 1,
                "maxStringLen": 5,
                "maxArrayValues": 5,
                "maxStructFields": -1
            },
            "backend": "coredump",
            "executable": "${workspaceRoot}/main/helloworldmodules",
            "coreDumpDirectory": "pathtodump...",
            "trace": "verbose"
        },
```

**Comment by hyangah** [comment]
Created a new issue in the new home https://github.com/golang/vscode-go/issues/168. Let's follow up there.

Closing as we are migrating the repo.
