### ISSUE TITLE
Allow reading from stdin

### ISSUE THREAD

**Issue by prasannavl** [Microsoft/vscode-go#317]
Allow "-" commandline flag instead of a file name to allow reading from stdin. 

This is very useful when working with the commandline, and to pass the result directly into the editor. Unfortunately, not make programs support this on Windows (Notepad, Sublime etc), however *nix programs tend to do so. 

Eg: `ls -Force -Recurse | vim -` 

Allow doing something like this for the VS Code command line.

**Comment by jakearchibald** [comment]
Just ran into this issue. It's especially useful for getting a file out of git's history, eg:

```sh
git show branch-name path/to/file.js | code
```

FWIW, this works in Sublime & Atom.

**Comment by jakearchibald** [comment]
Hm, this seems to be the wrong repo though.

**Comment by jakearchibald** [comment]
Reposted at https://github.com/Microsoft/vscode/issues/6161

**Comment by prasannavl** [comment]
@jakearchibald, oh damn! I must have pulled up a link from history and wrote it in a hurry. This was an awful mistake to do. Sorry, will close it and file it correctly under vscode in a bit. Thanks for pointing it out.
