### ISSUE TITLE
Your version of gopls appears to be out of date. Please update for an improved experience.

### ISSUE THREAD

**Issue by ice2002** [microsoft/vscode-go#3172]
Issue Type: <b>Bug</b>

"Gopls" has always been outdated, obviously updated just now, and VSCODE has also been updated. Restarting VSCODE prompts "Your version of gopls appears to be out of date. Please update for an improved experience."

Extension version: 0.13.1
VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz (8 x 3299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (13.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by stamblerre** [comment]
Did you update your `gopls` version, or is there some reason you want to stay on an older version?

**Comment by ice2002** [comment]
Gopls is the latest version. I did not keep the old version. Every time you open VSCODE, VSCODE will prompt "Your version of gopls appears to be out of date. Please update for an improved experience." This prompt is very annoying.

**Comment by stamblerre** [comment]
You can check what version VS Code is using by running `gopls version` in the VS Code integrated terminal (Ctrl + Shift + P -> View: Toggle Integrated Terminal). It's possible that you have multiple versions of `gopls` installed on your system and VS Code is using the wrong one. The latest version is `v0.4.0`, for your reference.

What are your VS Code settings for the Go extension (Ctrl + Shift + P -> Preferences: Open Settings (JSON))? Do you have `go.toolsGopath` set?

**Comment by hyangah** [comment]
There is a new command `Go: Located Configured Go Tools` that prints the list of tools and their paths. Please try to use the command to verify the `gopls` VS Code is in the expected place. The binary (determined mostly based on the `PATH` env var) chosen in the integration terminal can be different from what the extension picks.

**Comment by xgdgsc** [comment]
I have gopls at 

```
gopls version
version master, built in $GOPATH mode
```
And it warns about outdated everytime. Should I install a fixed version?

**Comment by stamblerre** [comment]
@xgdgsc: Yes, that is an old version of `gopls`. It should be installed in module mode, and the version number 0.4.0 should be the output.

**Comment by xgdgsc** [comment]
Thanks. Solved.
