### ISSUE TITLE
Frequent pop-up when saving with "Getting code actions: Go, Go, ..."

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-go#3179]
If you encounter this issue, please try the following steps to troubleshoot:

1. Check your other installed extensions. [Go Group Imports](https://marketplace.visualstudio.com/items?itemName=aleksandra.go-group-imports) and [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) have both been identified as causing slow saves.
2. Your workspace may have errors which are causing `gopls` to be slow. [Capture](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs) your `gopls` logs and post them here (if you're able to share them). Detailed `gopls` logs are best, so please add the `-rpc.trace` to `go.languageServerFlags`.

For reference, this bug is referring to an error that appears like this:
![image](https://user-images.githubusercontent.com/5856771/79361744-b837eb00-7f13-11ea-8bae-9683b4b61afc.png)

This issue consolidates https://github.com/microsoft/vscode-go/issues/3063, https://github.com/microsoft/vscode-go/issues/3105, https://github.com/microsoft/vscode-go/issues/3141, https://github.com/microsoft/vscode-go/issues/3170, etc.

**Comment by hairyhenderson** [comment]
@stamblerre I was seeing this dialog for a little bit, but now it's not popping up at all and `gopls` seems to be ... napping?

I'm seeing this error in the logs:

```
[Error - 5:05:20 p.m.] 2020/04/16 17:05:20 failed to load workspace packages, skipping diagnostics: github.com/myorg/myproject/api/model has no metadata
	snapshot=10087
	directory=file:///Users/hairyhenderson/go/src/github.com/myorg/myproject
```

I _did_ delete the `api/model` directory (with a `git rm` command in a shell), but it appears something went out of sync and thinks that directory is still around?

**Comment by stamblerre** [comment]
That's definitely possible - thanks for the report @hairyhenderson. I'll add a regression test for this case (https://github.com/golang/go/issues/38407#issuecomment-614938365). `Ctrl + Shift + P` -> `Go: Restart Language Server` should fix it temporarily.

**Comment by hairyhenderson** [comment]
@stamblerre thanks! That's a super-helpful shortcut! I usually just `ps -eaf | grep gopls` and kill one at random until the right one restarts 😂

**Comment by Wisgon** [comment]
> That's definitely possible - thanks for the report @hairyhenderson. I'll add a regression test for this case ([golang/go#38407 (comment)](https://github.com/golang/go/issues/38407#issuecomment-614938365)). `Ctrl + Shift + P` -> `Go: Restart Language Server` should fix it temporarily.

It doesn't work for me. When I `Ctrl + Shift + P` -> `Go: Restart Language Server` , Nothing happen and there is no code hintting any more, though I wait a long time. Finally I have to restart vscode.

**Comment by stamblerre** [comment]
@Wisgon: If you add

```json
"go.languageServerFlags": [
  "-rpc.trace"
]
```

to your VS Code settings, it should give you more detailed information. However, if your project is very large / has a lot of dependencies, it's possible that something else is going wrong.

**Comment by bobheadxi** [comment]
Restarting the language server didn't do anything for me, but @onlyafly 's [recommendation to downgrade the Go extension to 0.13.1](https://github.com/microsoft/vscode-go/issues/3105#issuecomment-626217371) solved the issue completely

**Comment by stamblerre** [comment]
@bobheadxi: This error usually starts happening when there is some misconfiguration or issue with `gopls`. Please take a look at the first comment on this issue (https://github.com/microsoft/vscode-go/issues/3179#issue-600430641) for advice on how to troubleshoot this.

**Comment by stamblerre** [comment]
Going to close this issue, as I haven't heard of many people encountering this recently.
