### ISSUE TITLE
Debug a single test

### ISSUE THREAD

**Issue by kdeenanauth** [Microsoft/vscode-go#318]
It's possible to debug a single test with delve:
https://github.com/derekparker/delve/issues/422

It would be handy to be able to Go: Debug Test (cursor)

**Comment by kdeenanauth** [comment]
Quick workaround is to add an arg to the test configuration:
```json
{
    "name": "Tests",
    "type": "go",
    "request": "launch",
    "mode": "test",
    "remotePath": "",
    "program": "${fileDirname}",
    "env": {},
    "args": ["^TestGenerateConfigurationFailure$"]
}
```

**Comment by lukehoban** [comment]
Yeah - I think the workaround is about the best that can be done given VS Code's debugging support currently.  I don't believe there is any way to have a custom command invoke a debug launch with parameterized launch configuration.  /cc @egamma in case he has thoughts.

**Comment by toodlez** [comment]
@kdeenanauth Adding an arg containing the test's name does not work for me.  It still runs all of the tests in the directory rather than just the one I specified. Any suggestions?

My test looks like this:
```
func TestStringTracesPOST(t *testing.T) {
...
}
```

And my configuration looks like this:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Tests",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "remotePath": "",
            "program": "${workspaceRoot}/implementation/handlers",
            "env": {},
            "args": ["^TestStringTracesPOST$"]
        }
    ]
}
```

**Comment by kdeenanauth** [comment]
@toodlez I'm having trouble with it too - my mistake. I could've sworn I had a working configuration.

**Comment by giacoman** [comment]
A workaround is to use remote debugging instead.  When you run delve for remote debugging, you could do something like this:

dlv test $(PKG) --headless --listen "0.0.0.0:2345" --log=true

**Comment by marklap** [comment]
This is how I got it to work:

`        {
            "name": "Launch Tests",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "remotePath": "",
            "port": 2346,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {
                "GOPATH": "${workspaceRoot}/.gopath"
            },
            "args": [
                "-test.v",
                "-test.run",
                "TestMySuperCoolTestName"
            ],
            "showLog": true
        }
`

**Comment by ramya-rao-a** [comment]
Like the [README](https://github.com/Microsoft/vscode-go#optional-debugging) says, to debug tests, you need to add a configuration in the launch.config with `"mode": "test"`

For debugging single tests, as @marklap has shown you can pass `-test.run` and the Test name as args.
These args will be passed to `dlv`.

**Comment by nikhilraog09** [comment]
I'm trying to debug some test (lets say TestABC with some build tags and command line options for verbosity and so on). I run it as Ex: 

> go test -tags=BUILDTAG -v -run=TestABC

what would be the right test/sample configuration to debug with dlv ?

**Comment by marklap** [comment]
I'd try this...

    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Launch TestABC",
                "type": "go",
                "request": "launch",
                "mode": "test",
                "remotePath": "",
                "port": 2346,
                "host": "127.0.0.1",
                "program": "${workspaceRoot}",
                "env": {},
                "args": [
                    "-test.v",
                    "-test.tags",
                    "BUILDTAG",
                    "-test.run",
                    "TestABC"
                ],
                "showLog": true
            }
        ]
    }

**Comment by ramya-rao-a** [comment]
@nikhilraog09 Also ensure that the `program` property points to the package to which your test belongs

**Comment by aphillips801** [comment]
Two quick questions: What .JSON file do you add the above to? How do you invoke it from within VSCode? (I've been searching and experimenting for some time and it is not obvious to my weak brain. :)

**Comment by ramya-rao-a** [comment]
@aphillips801 The json file being referred to is `launch.json`. 
See https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson

**Comment by darylng** [comment]
> I'm trying to debug some test (lets say TestABC with some build tags and command line options for verbosity and so on). I run it as Ex:
> 
> go test -tags=BUILDTAG -v -run=TestABC
> what would be the right test/sample configuration to debug with dlv ?



> I'd try this...
> 
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Launch TestABC",
>             "type": "go",
>             "request": "launch",
>             "mode": "test",
>             "remotePath": "",
>             "port": 2346,
>             "host": "127.0.0.1",
>             "program": "${workspaceRoot}",
>             "env": {},
>             "args": [
>                 "-test.v",
>                 "-test.tags",
>                 "BUILDTAG",
>                 "-test.run",
>                 "TestABC"
>             ],
>             "showLog": true
>         }
>     ]
> }

I think it should actually be the following as it's a build tag and not a test argument. 

```
    "configurations": [
        {
            "name": "Launch TestABC",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "remotePath": "",
            "port": 2346,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {},
            "buildFlags": "-tags=BUILDTAG",
            "args": [
                "-test.v",
                "-test.run",
                "TestABC"
            ],
            "showLog": true
        }
    ]
```
