### ISSUE TITLE
Way to disable go.mod codelens

### ISSUE THREAD

**Issue by mbertschler** [microsoft/vscode-go#3181]
My `go.mod` file shows code lens lines that look like **Upgrade dependency to ...**. 

I would like to have the option to remove them, maybe with the same config that can remove the other codelens features:
```
    "go.enableCodeLens": {
        "references": false,
        "runtest": false,
        "go.mod": false,
    },
```

**Comment by hyangah** [comment]
Try
```
   "[go.mod]": {
        "editor.codeLens": false
    }
```

For go files, use "[go]". Currently, there is no way to fine-control code lens behavior yet.

**Comment by hyangah** [comment]
Let's follow up in golang/go#38339 (specific to the current `go.mod` codelens behavior) and golang/go#36787 (which will require changes in vscode-go side to use codelens info from `gopls` instead of its custom codelens)

@stamblerre

**Comment by mbertschler** [comment]
@hyangah thanks for that quick suggestion, does exactly what I want!
