### ISSUE TITLE
Be more resilient to missing Go installation

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-go#3183]
I'm not sure if we have an open issue for this, but we've discussed adding support to install Go for users who don't already have it on their machines. We should also pop up a warning if the Go installation is missing.

Should VS Code Go continue working without a Go installation? (In case the user is using another build system). 

/cc @hyangah

**Comment by hyangah** [comment]
I think the original discussion was from https://github.com/microsoft/vscode-go/issues/2989.
Currently the extension already pops up messages like https://github.com/microsoft/vscode-go/blob/dfa9cbb5e5cb2d8f29fc251358f92092adcf2e16/src/goInstallTools.ts#L426

Do we want the message to be more specific to suggest how to download the go binary?
(Some OS distributions have their own way of installing Go)

**Comment by ramya-rao-a** [comment]
The extension cannot be expected to work without a Go installation at the moment. One can map `go` to something else in the `alternateTools` setting, but am not sure what would that end up breaking.

I don't believe the expectation to have a working Go installation is much to be able to use this extension and wouldnt invest much time here. Feel free to log an issue in the golang/vscode-go repo if you feel there are improvements that should be done here
