### ISSUE TITLE
No debugger variables but can see a stack trace c++

### ISSUE THREAD

**Issue by DylanReedy** [microsoft/vscode-go#3184]
I'm debugging a c++ application and, once I've hit a break point, cannot see any variables.  I can see a call stack. Additionally, when I stop the debugger, the application remains open in gdb, and I have to kill gdb from the command line. 

OS: centos-release-7-7.1908.0.el7.centos.x86_64
gdb --version:  GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-115.el7

What other information can I add to be helpful?

**Comment by stamblerre** [comment]
@DylanReedy: Was your intention to open an issue with the VS Code repository (https://github.com/microsoft/vscode)? This is the repository for the VS Code Go extension, so it doesn't handle debugging C++ programs.

**Comment by DylanReedy** [comment]
Absolutely, yes. Apologies - I'll move there
