### ISSUE TITLE
autocomplete for packages doesn't work at all

### ISSUE THREAD

**Issue by sudhNau** [microsoft/vscode-go#3187]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.5 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- MacOs darwin
amd64

### Share the Go related settings you have added/edited

```
{
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "autoComplete": true,
        "diagnostics": true,
        "documentLink": true,
        "documentSymbols": true,
        "findReferences": true,
        "format": true,
        "goToDefinition": true,
        "goToImplementation": true,
        "goToTypeDefinition": true,
        "hover": true,
        "rename": true,
        "signatureHelp": true,
        "workspaceSymbols": true,
    },
"[go]": {
    

    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true,
    },
    // Optional: Disable snippets, as they conflict with completion ranking.
    "editor.snippetSuggestions": "none",
},
"[go.mod]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true,
    },
},
"gopls": {
     // Add parameter placeholders when completing a function.
    "usePlaceholders": true,
    "completeUnimported": true,
    // If true, enable additional analyses with staticcheck.
    // Warning: This will significantly increase memory usage.
    "staticcheck": false,
},
"go.autocompleteUnimportedPackages": true,
"editor.tabCompletion": "on",
"go.addTags": {

}

}
```

### Describe the bug
Autocomplete does not work at all, no function suggestions or anything even for stdlib. 

I would expect autocomplete to provide me with a list of functions.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
Screenshot [attached]
<img width="716" alt="Screenshot 2020-04-17 at 20 01 48" src="https://user-images.githubusercontent.com/2093393/79599851-7e6b0e00-80e6-11ea-946d-8567da04d4b9.png">

**Comment by hyangah** [comment]
There is no exported function starting with `prin` in `fmt`, so there is nothing to suggest. 
In go,  all exported names should start with an upper case character.

**Comment by stamblerre** [comment]
`gopls` does fuzzy matching so the completion should still work with lowercase letters. @sudhNau: Can you please provide the output of `gopls -rpc.trace -v check path/to/file.go`? Or you can capture your `gopls` logs directly by following the steps here: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.

**Comment by sudhNau** [comment]
@stamblerre I could not find any gopls logs following the steps on the link (see the screenshot attached
<img width="1087" alt="Screenshot 2020-04-17 at 21 01 13" src="https://user-images.githubusercontent.com/2093393/79604651-c4c46b00-80ee-11ea-9d28-02bf44ee9300.png">
)

```gopls -rpc.trace -v check hello.go``` gives ```gopls not found``` but I am confused now, vscode is supposed to take care of installing gopls right ?

@hyangah It doesn't work with upper case either.

**Comment by hyangah** [comment]
@sudhNau Yeah, as @stamblerre said, there is another problem. 

It doesn't seem like `gopls` is not being used - didn't the VS Code pop up to install 'gopls'? Can you try to install it - from the command palette `Go: Install/Update Tools`. 

Then check all are installed in the expected location with `Go: Locate Configured Go Tools` command.

**Comment by BKasin** [comment]
Attempting to install gopls currently results in a failure.
![image](https://user-images.githubusercontent.com/31324979/79680919-e34b6480-81c9-11ea-9313-5444116cb1ae.png)

**Comment by BKasin** [comment]
It would appear that my error is cause by having go version 1.11. I could have sworn I just updated, but I guess not.

**Comment by stamblerre** [comment]
Ah yes, `gopls` is only supported for Go >= 1.12. Did updating resolve this issue for you?

**Comment by BKasin** [comment]
It did! So since some of the symptoms match mine, perhaps updating go is
worth a shot for OP.

**Comment by stamblerre** [comment]
Going to close this issue since there hasn't been activity on it in a while. @sudhNau: please re-open this if you're still encountering this problem.
