### ISSUE TITLE
Launch.json's update won't take effect until restart vscode

### ISSUE THREAD

**Issue by liuhewei** [Microsoft/vscode-go#319]
When I'm using debug, any change of launch.json (e.g. change the "program") won't take effect until restart vscode (windows 7 64 bit, vscode-stable).

**Comment by dearplain** [comment]
Are you using the latest vs code? this should be fixed in the newest vs code.

**Comment by liuhewei** [comment]
Already resolved. Sorry for not close this issue in time.
