### ISSUE TITLE
v0.14.1 does not seem to install gopls anymore

### ISSUE THREAD

**Issue by MorpheusXAUT** [microsoft/vscode-go#3194]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.2 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.44.2 ff915844119ce9485abfe8aa9076ec76b5300ddd x64 (Windows 10)
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- linux amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

```
{
    "go.useLanguageServer": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
        "editor.snippetSuggestions": "none",
    },
    "[go.mod]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "gopls": {
        "usePlaceholders": true,
        "staticcheck": false,
    },
    "go.autocompleteUnimportedPackages": true,
    "go.lintTool": "golangci-lint",
    "go.lintFlags": [
        "--fast"
    ],
    "go.testFlags": [
        "-cover",
        "-race",
        "-count=1",
        "-v"
    ]
}
```

### Describe the bug
I am using a Devcontainer setup for Go, running an golang:1.14.2 Docker image on a Windows 10 host. After updating to the latest version of vscode-go (0.14.1), the extension doesn't seem to install `gopls` in the devcontainer anymore and no prompt to install/update it is shown.

Using the `"go.useLanguageServer": true` setting as described [here](https://github.com/microsoft/vscode-go/blob/master/docs/Go-modules-support-in-Visual-Studio-Code.md), I expected the extension to install `gopls` as required.

Manually downgrading vscode-go to version 0.13.1 and reloading the window prompts for a `gopls` install as it was detected missing.

### Steps to reproduce the behavior:
1. Install vscode-go 0.14.1
2. Setup devcontainer environment with golang:1.14.2 image
3. Re-open project in container, no prompt to install gopls appears

**Comment by hyangah** [comment]
I could reproduce this.

https://github.com/microsoft/vscode-go/blob/master/src/goLanguageServer.ts#L302 
The return statement is misplaced. Will send a fix.

cc @stamblerre @ramya-rao-a

**Comment by rmuddana** [comment]
Is this the reason for code auto completion, code navigation (IntelliSense) is not working while using modules (go.mod)?
When i try with simple go file code suggestions and completion works however when i workspace with go.mod file it doesnt work.
I am using the latest build i.e 1.44.2 and the ms-vscode.go is 0.14.1

**Comment by hyangah** [comment]
@rmuddana It's unlikely to be related. This bug affects only the gopls auto-upgrade functionality.

Please file a separate issue (remember to include the related settings (those starting with "go", "gopls", "[go]" prefixes), enough details to reproduce the issue, gopls version, and if possible, the gopls trace (https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code)

**Comment by ramya-rao-a** [comment]
The latest update 0.14.2 has the fix for this, Thanks @hyangah 
And thanks for reporting @MorpheusXAUT
