### ISSUE TITLE
Cannot view nested maps on watch/variables panes - "Failed to eval expression"

### ISSUE THREAD

**Issue by lggomez** [microsoft/vscode-go#3198]
## What version of Go, VS Code & VS Code Go extension are you using?

- Run go version to get version of Go
        go version go1.13.5 darwin/amd64
- Run code -v or code-insiders -v to get version of VS Code or VS Code Insiders
        Version: 1.41.1 Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Check your installed extensions to get the version of the VS Code Go extension
        Version: 0.12.0
- Run go env GOOS GOARCH to get the operating system and processor arhcitecture details
        darwin amd64

## Describe the bug

1- Have a nested map variable:
```go
	nestedmap := map[string]interface{}{}
	nestedmap["issuer"] = map[string]interface{}{
		"foo": "bar",
	}
```
2- Expand the variable in the variables pane up to foo, and the debug adapter request will fail with the following:

```
VariablesRequest
Failed to eval expression:  {
 "Expr": "nestedmap.data.data[\"foo\"]",
 "Scope": {
  "goroutineID": -1,
  "frame": 0
 },
 "Cfg": {
  "followPointers": true,
  "maxVariableRecurse": 1,
  "maxStringLen": 100,
  "maxArrayValues": 5,
  "maxStructFields": -1
 }
} 

Eval error: nestedmap (type map[string]interface {}) is not a struct
Failed to evaluate expression - nestedmap (type map[string]interface {}) is not a struct
```

## Screenshot
<img width="1097" alt="Screen Shot 2020-04-20 at 20 43 16" src="https://user-images.githubusercontent.com/6326271/79810520-a1e1c300-8349-11ea-95cc-183079f4f0ca.png">

The watch and variables pane expect a tree object which we create from the delve response in order to show the key and value properties of the map, and on traversal from the pane we're not converting back this object to go syntax, thus being `b.data.data["issuer"]` instead of `b["issuer"]` and/or `b["issuer"]["foo"]`

**Comment by lggomez** [comment]
Here is the relevant code which does the variables request to delve and converts said response's variable representations from the delve response into DAP variables:

request:
https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L1149-L1233

variable mapper:
https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L1614-L1694

**Comment by Aisuko** [comment]
@lggomez Thanks for helping create the issue. Mark and waiting for fixing.

**Comment by lggomez** [comment]
For reference, the correct expression to get the innermost property of this map:

```go
	nestedmap := map[string]interface{}{
		"issuer": map[string]interface{}{
			"foo1": map[string]interface{}{
				"foo2": "bar2",
			},
		},
	}
```

is the following:

`p nestedmap["issuer"].(data)["foo1"].(data)["foo2"]`

**Comment by ramya-rao-a** [comment]
Closing this in favor of https://github.com/golang/vscode-go/issues/135 as [we are moving](https://github.com/microsoft/vscode-go#we-are-moving---)!

Please subscribe to the new issue for further updates
