### ISSUE TITLE
Add support to configure workspace with a go installed version

### ISSUE THREAD

**Issue by felipecaputo** [microsoft/vscode-go#3201]
I'm currently using [GVM](https://github.com/moovweb/gvm) to manage versions of some projects we are currently using.

I've run into sobre problem, that I needed to use `-default` to be able to use it correctly in VSCode and toolpath.

I was thinking about adding a command to `Configure workspace to use goVersion`, that will edit `Workspace Setting` and change the value of `gopath, gotoolpath and goroot` configurations of the extension to use the selected gvm instaled version.

It would be just a syntatic sugar using configurations that already exists in the extension, I was considering send a PR, but would like to validate the idea with you

Congrats for the great extension!!!

**Comment by hyangah** [comment]
I am curious about a more general approach that allows easy switch between different go versions even without GVM. For example, the vscode python extension offers a similar feature and I think it searches usual installation locations:  https://code.visualstudio.com/docs/python/environments 

@felipecaputo I am not very familiar with GVM so want to learn about it more. I think switch between go versions got easier nowadays - we just need to change the go binary (`GOROOT` is bound to the version of the go binary and maybe never needs to be set). `GOPATH` is going to be less critical with modules and we expect it to be deprecated eventually. Are there any functionalities of GVM that we want to keep and expose to make the Go development workflow easier?

**Comment by felipecaputo** [comment]
I was thinking exactly in the same way python extension works, when you can select interperter for the workspace, and add a status bar info with selector of "environment", searching for possible environments.

GVM install GO versions and uses each on in a diferente goRoot, but something that was hard for me with it is that it is integrated with `bash` or `zsh` and in VSCode somethimes it goes to my previous selected version.

Another problem was with GoToolsPath that was looking into the wrong folder in  a project yesterday.

We could map possible go instalations or allow the user to configure himself (just like python interpreter) and offer GVM installed versions and even a GVM integration to install and use a version.

What do you think

**Comment by felipecaputo** [comment]
I was thinking here, and was thinking about creating the GVM extension, to allow install and choose version of GVM outside of the vscode-go, but allow support to configure the version in the vscode-go extension

**Comment by stamblerre** [comment]
I think that this issue will be covered by this new one upstream: https://github.com/golang/vscode-go/issues/146. This repository is migrating (https://github.com/microsoft/vscode-go/issues/3247), so let's continue the discussion on the new issue.
