### ISSUE TITLE
Debugger fails to connect to remote headless multi-client session

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode-go#3206]
# What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.44.0
2aae1f26c72891c399f860409176fe435a154b13
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- windows
amd64

### Share the Go related settings you have added/edited

```json
{
    "go.lintOnSave": "off",
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
}
```

### Describe the bug

When I run `dlv debug --headless --accept-multiclient --continue`, attempting to connect to it remotely does not work. I expect it to work.

### Steps to reproduce the behavior:

+ Does not work with VSCode
  1. Target> `dlv debug --headless --api-version=2 --log --listen=:8181 --accept-multiclient --continue -- ARGS`
  2. Local> Launch VSCode Debugger
  3. Nothing happens.
+ Works as expected with CLI
  1. Target> Launch Delve
  2. Local> `dlv connect 1.2.3.4:8181`
  3. Delve pauses the process and shows the normal prompt. The target logs "debugger halting"

It does seem like VSCode is doing *something*. If I connect on the CLI, then disconnect without continuing (leaving the debugger halted), when I connect with VSCode, the debugger continues. VSCode thinks its in a debug session, but variables/watch/call stack show nothing and using VSCode to pause the process has no effect.

#### Configuration
```json
{
    "name": "REDACTED",
    "type": "go",
    "request": "attach",
    "mode": "remote",
    "remotePath": "${workspaceFolder}/REDACTED",
    "port": 8181,
    "host": "REDACTED",
    "trace": "verbose"
}
```

#### Logs

```
2020-4-24, 21:22:05.987 UTC
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"go","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true})
InitializeRequest
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsSetVariable":true}}
InitializeResponse
From client: attach({"name":"REDACTED","type":"go","request":"attach","mode":"remote","remotePath":"REDACTED","port":8181,"host":"REDACTED","trace":"verbose","packagePathToGoModPathMap":{"REDACTED":"REDACTED","REDACTED\\.vscode":"REDACTED","REDACTED\\REDACTED":"REDACTED",".":""},"env":{"GOPATH":"C:\\Users\\ME\\go","ALLUSERSPROFILE":"C:\\ProgramData","AMD_ENTRYPOINT":"vs/workbench/services/extensions/node/extensionHostProcess","APPDATA":"C:\\Users\\ME\\AppData\\Roaming","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","ChocolateyInstall":"C:\\ProgramData\\chocolatey","ChocolateyLastPathUpdate":"132258403956604533","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"REDACTED","ComSpec":"C:\\WINDOWS\\system32\\cmd.exe","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","ELECTRON_RUN_AS_NODE":"1","FPS_BROWSER_APP_PROFILE_STRING":"Internet Explorer","FPS_BROWSER_USER_PROFILE_STRING":"Default","GOPROXY":"https://proxy.golang.org,direct","GOROOT":"c:\\go","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\ME","LOCALAPPDATA":"C:\\Users\\ME\\AppData\\Local"[...]
To client: {"seq":0,"type":"event","event":"initialized"}
InitializeEvent
To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":true}
From client: configurationDone(undefined)
ConfigurationDoneRequest
From client: disconnect({"restart":false})
DisconnectRequest
HaltRequest
```

**Comment by hyangah** [comment]
@polinasok @quoctruong I am not familiar with DAP client's expectation when during initialization - based on the log, it seems DAP client was unhappy about something after ConfigurationDoneRequest is done. Can you please take a look? (Note the use of `--accept-multiclient --continue`. This is reproducible.)

**Comment by bulentkazanci** [comment]
@firelizzard18 Are you running the application on your local? If so, set the `"remotePath": "${workspaceFolder}"` and make sure that you set breakpoints on vscode before running debug on vscode. It looks like on the debug log you provided that no breakpoint was provided.

**Comment by firelizzard18** [comment]
@bulentkazanci I was not running locally, hence `"host": "REDACTED"`. I'm fairly certain I had breakpoints set in the code.

**Comment by quoctruong** [comment]
Please give the nightly build a try: https://github.com/golang/vscode-go/blob/master/docs/nightly.md. We now automatically try to infer the path so you don't have to supply `remotePath` at all.

**Comment by stamblerre** [comment]
Please follow the discussion on [golang#45](https://github.com/golang/vscode-go/issues/45) or [file a new issue](https://github.com/golang/vscode-go/issues/new?assignees=&labels=&template=bug_report.md&title=) if this still isn't working for you.
