### ISSUE TITLE
Improve Error Messaging. When a pointer based type has all the interface methods defined, the messaging in the editor is incorrect.

### ISSUE THREAD

**Issue by artivilla** [microsoft/vscode-go#3210]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.14.2 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
- Code Insiders
	```
	Version: 1.45.0-insider
	Commit: 0778354f3a6a2c21b7f738a5e6b02e2f1c765e73
	Date: 2020-04-27T05:39:56.514Z (19 hrs ago)
	```
- Go Extension Nightly
![image](https://user-images.githubusercontent.com/2120159/80434860-f09ed800-88c8-11ea-9ada-9a12c7724a8e.png)

- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- `darwin amd64`

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
```
    "go.autocompleteUnimportedPackages": true,
    "go.lintFlags": [
        "--fast"
    ],
    "go.lintOnSave": "file",
    "go.lintTool": "golint",
    "go.useLanguageServer": true,
```

### Describe the bug
Improve Error Messaging. When a pointer based type has all the interface methods defined, the messaging in the editor is incorrect.

Run the following error in the shared playground: https://play.golang.org/p/l7YETLSrYeL

Expected Error (shown in playground):
> ./prog.go:21:6: cannot use SimpleReader literal (type SimpleReader) as type io.ReadCloser in assignment:
	SimpleReader does not implement io.ReadCloser (Close method has pointer receiver)

Actual Error from VS Nightly Code Editor:
![image](https://user-images.githubusercontent.com/2120159/80435234-fa750b00-88c9-11ea-8a82-6d77c444f792.png)

**Comment by stamblerre** [comment]
This is actually an issue in the Go standard library, and it will be fixed in Go 1.15 (see https://golang.org/cl/229801). If you're interested in trying it out now, you can download Go from source (https://golang.org/doc/install/source) and rebuild `gopls` with it. Otherwise, this fix will be released approximately 3 months from now (in keeping with Go's 6 month release cycle).
