### ISSUE TITLE
Fill in with function signature as we have for structs.

### ISSUE THREAD

**Issue by GAZ082** [microsoft/vscode-go#3216]
We have the cool fill struct, can we have the same for functions?

Thanks.

**Comment by hyangah** [comment]
If you are using the language server (`"go.useLanguageServer": true`), the following additional settings will do the work.
```
   "gopls": {
        "usePlaceholders": true
    },
```

If you are not using the language server, try 
`"go.useCodeSnippetsOnFunctionSuggest": true`.

**Comment by GAZ082** [comment]
Thanks!
