### ISSUE TITLE
Run custom vet tools alongside the standard one.

### ISSUE THREAD

**Issue by jmalloc** [microsoft/vscode-go#3219]
**Is your feature request related to a problem? Please describe.**

We wish to implement a custom Go vet tool at my workplace, however I am unable to find a way to use that vet tool in vscode without preventing the standard checks (or other custom checks) from being run.

This is because `go vet` only allows a single `-vettool` argument to be provided, and doing so makes the standard checks unavailable.

**Describe the solution you'd like**

The ability to configure separate invocations of `go vet` each with their own `vetFlags`.

This approach would allow specifying a different `-vettool` argument for each invocation, while still allowing the current behavior of replacing the standard tools with a single custom tool entirely, if desired.

**Describe alternatives you've considered**

I had hoped that `go vet` itself might offer a way to run multiple vet tools in a single invocation, or at least be able to run a custom vet tool alongside the standard one, but this does not seem to be possible. The specified `vettool` "takes over" much of the flag/parameter parsing for `go vet` itself.

As a workaround I will try building the standard checks into our custom vet tool, then add `-vettool=mytool` to `vetFlags`. This should get us over the line at my workplace, but the problem resurfaces if the user then wants to use additional custom vet tools, which our developers may already be doing.

👍 Thank you to everyone has contributed to this extension!

**Comment by hyangah** [comment]
Thanks for the feature request. 

In the world with the Go language server most of the standard + well-known vet checks can be done by the language server. For example, you can configure the set of analyses with `gopls.analyses` (https://github.com/golang/tools/blob/master/gopls/doc/settings.md#analyses-mapstringbool). Have you considered this instead of a separate `go vet` invocation?

**Comment by jmalloc** [comment]
Thanks for the reply, I wasn't aware of that feature as I haven't been using `gopls` yet.

It doesn't appear `gopls` allows adding checkers that aren't already part of `go vet`, do I have that right? It would at least take care of running the standard checkers so that a custom vet tool configured via `vetFlags` wouldn't them compiled into it.

**Comment by hyangah** [comment]
@jmalloc If there are checkers that you believe useful but not listed, adding them to the supported analyses set (https://github.com/golang/tools/blob/master/gopls/doc/analyzers.md) as optional ones is a possibility too. Have you be in the [gopher slack](http://gophers.slack.com/)?  Gophers in the `#gopls` and `#gopls-dev` channels are supportive and knowledgeable.

**Comment by jmalloc** [comment]
I don't believe the kinds of tools I'm talking about are broadly applicable enough to be included in any standard Go tooling. [Here's an example](https://github.com/bflad/tfproviderlint) of the *kind* of thing I'm talking about. My workplace's tool would be even more esoteric.

I guess there's a question of whether or not `gopls` itself will offer a way to run these custom vet tools in the future, in which case this isn't something that the VSCode extension would need to support at all. I'll definitely ask the question on Slack and see what the general feeling is. 

Thanks again :)

**Comment by hyangah** [comment]
Can't it be adopted in the golangci-linter (https://github.com/golangci/golangci-lint) framework? Then you can invoke golangci-linter with lintOnSave feature.

**Comment by jmalloc** [comment]
It seems like the problems with that approach are much the same, insofar as `golangci-linter` only runs a single `go vet` instance, and the kinds of custom checkers I'm talking about aren't applicable to enough people to be integrated into the mainline of `go vet`.

I could submit a feature request to `golangci-linter`, much like this one, to support multiple `go vet` invocations, but my preference would be to do so using VSCode without having to adopt `golangci-linter`.

You've presented me with quite a few more options to consider :) I am becoming increasingly  convinced that `go vet` itself should offer a way to run multiple vet tools, since they are built using packages from `go/tools`, after all.

Just to put another idea out there - Is there some standard reporting format that VSCode and/or the Go extension use to annotate source code with warnings and errors? Perhaps there's some mechanism to run arbitrary linting commands without specific support from the Go extension?

**Comment by hyangah** [comment]
`golangci-linter` supports custom linters according to their README.

I think the best option is to build a super set of the vet tool (that includes both the standard and your own custom analyzers) and pass the tool to `go vet` as you already planned. That way, other editor users can utilize your analyzer. 

For general pluggable analyzer discussion, I recommend gopher slack `#tools` channel or https://groups.google.com/forum/#!forum/golang-tools.

**Comment by jmalloc** [comment]
Ok, I will move this discussion elsewhere.

In parting, I do still think there's room for such a feature here - to be able to run more than one vet (or lint) tool, from separate providers, without having to replace some existing tool with a custom build/fork.

Thanks for hearing me out :)

**Comment by hyangah** [comment]
Thanks for being patient. Yes, I think it would be nice if we can configure to run multiple tasks on save (not limited to vet, but linters etc).

**Comment by ramya-rao-a** [comment]
Have you considered the `go.alternateTools` setting? You can map the default linter used by the extension to a script that would run your custom tool. Assuming that the output is in the same format, the extension should be able to provide diagnostics after parsing the output.

Another alternative is to use [Tasks that are meant to integrate VS Code with external tools](https://code.visualstudio.com/docs/editor/tasks)

**Comment by stamblerre** [comment]
Sounds like this discussion has resolved. Please open a new issue [in the Go repository](https://github.com/golang/go/issues/new) if you would like to discuss `go vet` further.
