### ISSUE TITLE
Issues with VS Code 1.1

### ISSUE THREAD

**Issue by aaronkavlie-wf** [Microsoft/vscode-go#322]
After upgrading to Visual Studio Code 1.1, some important features of this plugin don't seem to work properly:

- Linting and code error notifications seem to be entirely broken; even basic build errors are not showing up.
- The "Format Code" command doesn't do anything most of the time (no errors are shown)

**Comment by aaronkavlie-wf** [comment]
I do have one (and only one, that I can see) green underline, suggesting that the exported method should have a comment or be unexported. If I add a comment to that method, the next method above it that is lacking a comment is then underlined, and so on. 

In other words, there are a number of public methods lacking comments in this file, but only the last one gets a green underline.

**Comment by mattetti** [comment]
I do see something weird too, it looks like one of the tools is dying in a panic but I can't see any logs (in the output panes or developer tools)
 
![serum_go_-_serum](https://cloud.githubusercontent.com/assets/113/15199349/4d69b5b6-1792-11e6-988a-99a1aa897337.png)

**Comment by egamma** [comment]
CC @jrieken did we change anything in the area of diagnostics and linting between 1.0 and 1.1?

**Comment by jrieken** [comment]
things have changed wrt to being able to [read](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2516) the diagnostics in the extension host but nothing else. Since those changes have great self host coverage I am confident. Debugging this, I see that the extension computes an empty array of errors:

<img width="776" alt="screen shot 2016-05-12 at 11 28 55" src="https://cloud.githubusercontent.com/assets/1794099/15210126/1775e67a-1835-11e6-99a6-5116d8f92160.png">

**Comment by jrieken** [comment]
Having a simple syntax error like this,
```go
fumc bar(){
    bioklr();
}

```
 makes `golint` produce an error, but some `go check` is configured to read from `stdout` but not from `stderr`.

<img width="1177" alt="screen shot 2016-05-12 at 11 35 40" src="https://cloud.githubusercontent.com/assets/1794099/15210402/b1879f8c-1836-11e6-9162-4e379580d57a.png">

**Comment by vastbinderj** [comment]
Linting won't fire on save if there are no changes in the file.  I found this annoying, that to lint a file for a code review, I had to edit it and save it...

**Comment by mattetti** [comment]
@jrieken any clue on how to debug this issue? I'd be glad to give a hand

**Comment by deejross** [comment]
I'm noticing the same behavior and would be happy to help resolve it. This issue makes VSCode nearly unusable for Go development. I've had to fallback to IntelliJ and using fmt.Println() statements for debugging since the Go plugin for IntelliJ doesn't work with debugging on the Mac.

**Comment by lukehoban** [comment]
@jrieken I don't think you previous note is right.  The `vscode-go` extension is computing the errors correctly, and passing them to `diagnosticsCollection.set`, but only the first item of the array passed to that function is showing up in VS Code.

<img width="960" alt="pic" src="https://cloud.githubusercontent.com/assets/223467/15269318/e237cbf0-19af-11e6-9d7b-5d1221432909.png">

No matter what the original source of the errors, VS Code is only ever displaying the first item of the array passed to `DiagnosticsCollection#set`.  If the same set of items are permuted, the new first item will be the one VS Code displays.  

I'll open an issue in the `vscode` repo on this.  But in the meantime the Go extension will need to find a way to work around this.

**Comment by OneOfOne** [comment]
@mattetti https://github.com/nsf/gocode/issues/305#issuecomment-219234073 that's a gocode bug with go 1.7, either use < go 1.7 or apply the patch to your git tree.

**Comment by mattetti** [comment]
@OneOfOne thanks a lot, I went back to VSCode 1.0 and still saw the error. I'm indeed on 1.7 and not planning on going back ;)

**Comment by OneOfOne** [comment]
@mattetti no problem, gocode got fixed and the patch isn't needed anymore.

**Comment by tchoomak** [comment]
@lukehoban after upgrading vscode to 1.1.1 have the same - code errors and warnings notification seems to be entirely broken. Whether the plugin to be updated too?

**Comment by luca-moser** [comment]
Same as @tchoomak on 1.1.1, I still don't get any errors inside VS Code, for example when a package import is missing.

**Comment by jrieken** [comment]
@lukehoban Yes, [`DiagnosticsCollection#set`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2502) when called with an array of uri/diagnostics tuples has changes such that repeating tuples for one uri overwrites the previous data. The change wasn't on purpose.

Ultimately, the grouping [here](https://github.com/Microsoft/vscode-go/blob/master/src/goMain.ts#L147) which was also in a way the root cause for this (#328) won't be needed anymore which I believe will yield in more easy to use API.

**Comment by AlekSi** [comment]
vscode-go update released and works as expected. Thank you!

**Comment by stevematdavies** [comment]
Same issue now with latest go code and plugin, can no longer use vs code for go dev, until this is fixed

**Comment by gargamelius** [comment]
@stevematdavies you might want to try updating gocode.

`gocode close && go get -u github.com/nsf/gocode`

**Comment by stevematdavies** [comment]
@gargamelius Ive done that, and reinstalled the tools, now nothing works, no linting, formatting etc

**Comment by stevematdavies** [comment]
Switch to vim for now, working very well.

**Comment by giefferre** [comment]
@mirza-s this solved the problem, thank you
