### ISSUE TITLE
You are neither in a module nor in your GOPATH. If you are using modules, please open your editor at the directory containing the go.mod. 

### ISSUE THREAD

**Issue by Shadrocks** [microsoft/vscode-go#3220]
I have tried uninstalling, reinstalling and all kinds of flip flops all over the place. 

go version go1.14.2 windows/amd64
The error message is SOO VAGUE!
I've opened my editor in the root directory of the install as stated and still get this message..
Please help..

**Comment by stamblerre** [comment]
Can you please capture your `gopls` logs, as described [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs)? Are you using modules or GOPATH mode?

**Comment by Shadrocks** [comment]
I hope this is correct.. @stamblerre 

[Info  - 2:42:04 PM] 2020/05/05 14:42:04 Build info
----------
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200407041343-bf15fae40dea h1:DUwLyMDMUauGMd9kSLIlhhYJNELm06HuxeBdkFkeax4=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.14.2 windows/amd64


[Info  - 2:42:05 PM] 2020/05/05 14:42:05 go env for C:\Go
(valid build configuration = false)
(build flags: [])
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\pc\AppData\Local\go-build
set GOENV=C:\Users\pc\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\pc\AppData\Local\Temp\go-build748583242=/tmp/go-build -gno-record-gcc-switches

[Info  - 2:42:05 PM] 2020/05/05 14:42:05 go/packages.Load
	snapshot=0
	directory=C:\Go
	query=[./ builtin]
	packages=2
[Info  - 2:42:05 PM] 2020/05/05 14:42:05 go/packages.Load
	snapshot=0
	directory=C:\Go
	query=[./]
	packages=1
[Info  - 2:42:05 PM] 2020/05/05 14:42:05 go/packages.Load
	snapshot=1
	directory=C:\Go
	query=[./]
	packages=1
[Info  - 2:42:07 PM] 2020/05/05 14:42:07 go/packages.Load
	snapshot=1
	package_path="command-line-arguments"
	files=[C:\Go\projects\botproj\main.go]
[Info  - 2:42:07 PM] 2020/05/05 14:42:07 go/packages.Load
	snapshot=1
	directory=C:\Go
	query=[file=C:\Go\projects\botproj\main.go]
	packages=1
[Error - 2:42:07 PM] 2020/05/05 14:42:07 no dep handle: no metadata for github.com/newrelic/go-agent
	package="github.com/newrelic/go-agent"
[Error - 2:42:07 PM] 2020/05/05 14:42:07 no dep handle: no metadata for github.com/slack-go/slack
	package="github.com/slack-go/slack"
[Error - 2:42:07 PM] 2020/05/05 14:42:07 no dep handle: no metadata for github.com/spf13/viper
	package="github.com/spf13/viper"
[Error - 2:42:07 PM] 2020/05/05 14:42:07 no dep handle: no metadata for botproj/bus
	package="botproj/bus"
[Info  - 2:42:07 PM] 2020/05/05 14:42:07 go/packages.Load
	snapshot=1
	directory=C:\Go
	query=[file=C:\Go\projects\botproj\main.go]
	packages=1
[Info  - 2:42:07 PM] 2020/05/05 14:42:07 go/packages.Load
	snapshot=1
	package_path="command-line-arguments"
	files=[C:\Go\projects\botproj\main.go]
[Info  - 2:42:37 PM] 2020/05/05 14:42:37 background imports cache refresh starting
[Info  - 2:42:37 PM] 2020/05/05 14:42:37 background refresh finished after 117.9701ms

**Comment by stamblerre** [comment]
Ah, looks like you are missing a `src` directory under your GOPATH: https://golang.org/doc/gopath_code.html#Organization. Your code needs to go under `$GOPATH/src`, not `$GOPATH` directly.

**Comment by Altiano** [comment]
@stamblerre I also have this issue,
but in my case I'm using go modules, and it can be outside of `src` right?

**Comment by Altiano** [comment]
Oh.. I see,
so `vscode` only check the `go.mod` in the root folder of our explorer,
instead of recursively trying to find `go.mod` in parent folder of the current file.

my structure is like this:
```
project_dir
-- server_a
-- -- go.mod
-- -- main.go
-- server_b
```

VS code not expecting the `main.go` directly inside `project_dir`

**Comment by Shadrocks** [comment]
> Ah, looks like you are missing a `src` directory under your GOPATH: https://golang.org/doc/gopath_code.html#Organization. Your code needs to go under `$GOPATH/src`, not `$GOPATH` directly.

I believe this solved my issue! Thank you a ton.. to recap, I am using an SSD drive in Windows. The drive is my X:\ drive and I placed my src directory there so it's X:\src\project a.. b.. c.. etc..
I had my gopath originally set to X:\src.

**Comment by stamblerre** [comment]
@Altiano: Please see details about supported workspace configurations here: https://github.com/golang/go/issues/36899. If you have further questions, please open a new issue.

**Comment by ItsCosmas** [comment]
> Oh.. I see,
> so vscode only check the `go.mod` in the root folder of our explorer,
> instead of recursively trying to find `go.mod` in parent folder of the current file if it not as the same level.
> 
> my structure is like this:
> 
> ```
> project_dir
> -- server_a
> -- -- go.mod
> -- -- main.go
> -- server_b
> ```
> 
> VS code not expecting the `main.go` directly inside `project_dir`
> 
> I'm using
> 
> ```
> "go.useLanguageServer": true,
> "go.formatTool": "goimports",
> ```

Having the same exact issue where VS Code complains if the `go.mod` is not inside the root directory of the project directory opened. Any solutions, the issue got closed?

**Comment by ItsCosmas** [comment]
> @Altiano: Please see details about supported workspace configurations here: [golang/go#36899](https://github.com/golang/go/issues/36899). If you have further questions, please open a new issue.

Ooh I see this is under consideration. Thanks for the heads up!
