### ISSUE TITLE
unable to eval const variables when debugging

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-go#3226]
<img width="1094" alt="1" src="https://user-images.githubusercontent.com/11925432/81276198-458add00-9085-11ea-97b1-22a7fe549b2d.png">

**Comment by hyangah** [comment]
Same as https://github.com/golang/go/issues/35527
The local constant is inlined and also the debug information for it is not available.

**Comment by hyangah** [comment]
Please follow the upstream bug.
