### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by viveknangal** [microsoft/vscode-go#3228]
Issue Type: <b>Bug</b>

The auto complete doesnt work for packages where i updated the "function definition" or added new function . GO autocomplete still continues to show the older versions, please suggest what to do in these cases

Extension version: 0.14.1
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|-psn_0_5395749|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by viveknangal** [comment]
<img width="440" alt="Screen Shot 2020-05-08 at 1 05 28 AM" src="https://user-images.githubusercontent.com/5039071/81337563-d6cf7300-90c8-11ea-95b1-92edd6b31340.png">

**Comment by viveknangal** [comment]
Please suggest why the auto-complete shows the incomplete list of functions & at times i deleted some functions in the parent package but the Visual Code still continues to show the functions which are not present anymore in the Parent package, Please help

**Comment by stamblerre** [comment]
Can you please share your VS Code settings related to Go? (Anything with `"[go]"` or `go.` in the prefix).

**Comment by viveknangal** [comment]
<img width="766" alt="Screen Shot 2020-05-08 at 10 40 28 AM" src="https://user-images.githubusercontent.com/5039071/81372675-9992d180-9118-11ea-8ae5-93a29f1b16a7.png">
<img width="795" alt="Screen Shot 2020-05-08 at 10 40 39 AM" src="https://user-images.githubusercontent.com/5039071/81372684-9e578580-9118-11ea-8136-a55483224109.png">
<img width="789" alt="Screen Shot 2020-05-08 at 10 40 47 AM" src="https://user-images.githubusercontent.com/5039071/81372690-a0214900-9118-11ea-9f8c-12f1ec7fa3f4.png">
<img width="764" alt="Screen Shot 2020-05-08 at 10 40 54 AM" src="https://user-images.githubusercontent.com/5039071/81372692-a1527600-9118-11ea-9f3a-ff662fe414d2.png">
<img width="777" alt="Screen Shot 2020-05-08 at 10 41 05 AM" src="https://user-images.githubusercontent.com/5039071/81372696-a283a300-9118-11ea-8a86-6729c1859d72.png">
<img width="778" alt="Screen Shot 2020-05-08 at 10 41 44 AM" src="https://user-images.githubusercontent.com/5039071/81372704-a6172a00-9118-11ea-9964-66e650938aac.png">
<img width="752" alt="Screen Shot 2020-05-08 at 10 41 54 AM" src="https://user-images.githubusercontent.com/5039071/81372706-a7e0ed80-9118-11ea-9645-a56ef4830b8a.png">
<img width="804" alt="Screen Shot 2020-05-08 at 10 42 03 AM" src="https://user-images.githubusercontent.com/5039071/81372710-a9aab100-9118-11ea-8741-0904c961b061.png">

**Comment by viveknangal** [comment]
Please find above setting  . I shared the screenshots as i m not sure there is a better way to share the settings ..

**Comment by viveknangal** [comment]
<img width="669" alt="Screen Shot 2020-05-08 at 10 54 37 AM" src="https://user-images.githubusercontent.com/5039071/81373411-59cce980-911a-11ea-8cc9-70ad20aef7c1.png">

here is the auto complete seeting s

**Comment by stamblerre** [comment]
Thank you for sharing this. In the cases where you don't see autocompletion for the new functions - are the files all saved? Also, are you using modules or GOPATH mode?

**Comment by viveknangal** [comment]
@stamblerre  yes all files are saved, the autocomplete is not working as expected for the packages which i m creating myself(like if i change anything in my packages it wont reflect in autocomplete).Its working for all other open-source Go packages I m using. ANd i m relying on the GOPATH set at the system level no specific setting related to GOPATH at the VS code level.

**Comment by viveknangal** [comment]
@stamblerre please suggest what i m doing wrong ,,i seriuosly want this work ..need ur help here

**Comment by stamblerre** [comment]
I believe that the autocompletion for unimported packages feature works by indexing the files on disk when the extension starts, so it probably doesn't handle new files/new symbols as they change (@ramya-rao-a - am I correct here?).

Once you import `greetings` into your file, you should see all of the expected symbols. You can also type `greetings.MyFunctionName` and save, and the import will be added automatically.

Alternatively, you can try using the language server, which does support this feature. You can enable it by adding `"go.useLanguageServer": true` in your settings.

**Comment by viveknangal** [comment]
<img width="1007" alt="Screen Shot 2020-05-08 at 10 42 53 PM" src="https://user-images.githubusercontent.com/5039071/81430703-7ea67880-917d-11ea-85fd-41f344ad9b00.png">

@stamblerre thanks for ur response, I have added the ""go.useLanguageServer": true in the settings & reloaded VS code as you suggested but still issue remains the same. Now even if i add new package eg "Car" (screenshot below) even new packages are not getting auto-complete.

**Comment by viveknangal** [comment]
THe "main.go" program just runs fine if i manually add the "Car" package function , the issue is why the auto-complete is not working

**Comment by stamblerre** [comment]
I can help investigate issues with the language server if you'd like to continue trying to use it. If so, please attach your logs by following these steps: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.

Otherwise, you can disable the language server and use the default tooling that worked before. The lack of completion for a new symbol is a limitation, and I don't expect improvements to be made to this feature.

**Comment by viveknangal** [comment]
i've disabled the language server , but now the problem remains the same that all my custom packages are getting "auto-complete" if these get updated (as updated in my 1 comment )

**Comment by stamblerre** [comment]
To confirm, they are not getting autocompletion when they are not yet imported? Do the correct completions show up once it is imported?

To reiterate what I said above regarding unimported completions:

> I believe that the autocompletion for unimported packages feature works by indexing the files on disk when the extension starts, so it probably doesn't handle new files/new symbols as they change (@ramya-rao-a - am I correct here?).
> 
> Once you import `greetings` into your file, you should see all of the expected symbols. You can also type `greetings.MyFunctionName` and save, and the import will be added automatically.

We will likely not devote time to improving the unimported completions feature outside of the language server, so if the issue is only with unimported completions, than this is working as intended.

**Comment by viveknangal** [comment]
No @stamblerre  , auto-completion doesnt work even after i imprt the package . Its kind of weird that at times it works for imported packages at other time it doesnt. SOme auto complete works after importing doesnt it doesnt reflect the change if i do the parant package function or add /remove new functions in parent package. 
please suggest is there any other setting or cache which i need to cleaup on my MAC machine to make it work consistently

**Comment by stamblerre** [comment]
One thing you can try is running the `gocode` debug server on the command line and see what's happening. You can do this by running `gocode -s -debug` on the command line and then triggering completions from your VS Code window. You can also look in the Go output channel (Ctrl + Shift + P -> View: Toggle Output -> Tasks -> Go) to see if there are any error messages there.
