### ISSUE TITLE
go.formatFlags not working with gofmt -s (simplify)

### ISSUE THREAD

**Issue by Graham42** [microsoft/vscode-go#3230]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.14.2 linux/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- ```
	  1.45.0
	  d69a79b73808559a91206d73d7717ff5f798f23c
	  x64
	  ```
- Check your installed extensions to get the version of the VS Code Go extension 
	- `0.14.1`
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
  ```
  linux
  amd64
  ```

### Share the Go related settings you have added/edited

```json
{
  "[go]": {
    "editor.formatOnSave": true
  },
  "go.formatTool": "gofmt",
  "go.formatFlags": ["-s"],
  "go.lintTool": "golangci-lint",
  "go.useLanguageServer": true
}
```

### Describe the bug

Setting `"go.formatFlags": ["-s"],` doesn't work. My code is formatted on save, but the `-s` flag is not applied.

```go
type foo struct{}

func Do() {
	x := []foo{
		foo{},
		//^^^ `gofmt -s` should remove the type annotation here
	}
	println(x)
}
```

### Steps to reproduce the behavior:
1. Use the above code snippet and vscode settings.
2. Delete some whitespace.
3. Save the file.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

![formatting-on-save](https://user-images.githubusercontent.com/2476733/81417976-fe9af700-9119-11ea-8647-6409caee4d54.gif)

**Comment by stamblerre** [comment]
Thanks for the report. The language server now does this though a `source.FixAll` code action, so you will need to add the following to the your `"[go]"` settings block:

```json5
"[go]": {
	"editor.codeActionsOnSave": {
		"source.fixAll": true,
	},
 },
 ```

**Comment by Graham42** [comment]
Thanks! That snippet solves the "on save" use case for me. However, if I use the editor "Format Document" command the `-s` flag is still not applied.

**Comment by stamblerre** [comment]
You can run the simplifications manually by opening the Command Palette (Ctrl + Shift + P) and selecting "Source Action". I believe this will be added to the right click menu in the next VS Code release.

**Comment by Graham42** [comment]
This issue is effectively solved for me with the `fixAll` action on save, I just wanted to share that finding.  If you don't consider it a bug that the `formatFlags` option doesn't apply to the "Format Document" command then feel free to close this issue :slightly_smiling_face:

**Comment by stamblerre** [comment]
Ok - thanks! The reason it no longer works as part of formatting is that it's now been split out as a code actions, as defined in the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_codeAction), which is intentional. Closing as result.
