### ISSUE TITLE
Unable to run Go in VS Code - command not found 

### ISSUE THREAD

**Issue by nageshcaparthy** [microsoft/vscode-go#3233]
Hi, 

I have read the details on GoPath and also the previous issues reported. I am not able to fix the issue. 

I am using 

VS Code 1.39.2
Ubuntu 14.6

I have tried to remove the .vscode extensions folder as mentioned in https://github.com/Microsoft/vscode-go/issues/1514 but no luck. 

Here is the image of this issue:

![image](https://user-images.githubusercontent.com/11992979/81679964-400c0900-9470-11ea-96e2-6b219910beb9.png)

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
go: Command not found.

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
1.39.2
6ab598523be7a800d7f3eb4d92d7ab9a66069390
x64

- Check your installed extensions to get the version of the VS Code Go extension 
Go 0.14.0

- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
go: command not found

Regards,
Nagesh

**Comment by hyangah** [comment]
@nageshcaparthy Please follow the Go installation guide in https://golang.org/doc/install
Eventually this extension also suggests and manages the go installation, but we are not there yet.

**Comment by nageshcaparthy** [comment]
@hyangah that did not work... I get command not found...

@ramya-rao-a Any suggestions on this?? it will be really helpful.

**Comment by stamblerre** [comment]
@nageshcaparthy: Did you get any errors from the Go installation? What directory did you extract the archive to? You will need to add that directory to your `PATH` (https://golang.org/doc/install#tarball).

This extension will not be useful without a Go installation, so configuring your installation correctly will be the fix.

**Comment by nageshcaparthy** [comment]
I guess Path was the issue. Thank you for your support. 

Might need the documentation to be adding the PATH or maybe I missed it.
