### ISSUE TITLE
Can not use VS code for GO:   Installing github.com/go-delve/delve/cmd/dlv FAILED

### ISSUE THREAD

**Issue by tojkamaster** [microsoft/vscode-go#3236]
VS Code want install from repository which does not exist !

```
Installing github.com/go-delve/delve/cmd/dlv FAILED

1 tools failed to install.

dlv:
Error: Command failed: /usr/bin/go get -v -u github.com/go-delve/delve/cmd/dlv
```

**Comment by stamblerre** [comment]
That directory does exist (see https://github.com/go-delve/delve/tree/master/cmd/dlv). What is the output of `/usr/bin/go get -v -u github.com/go-delve/delve/cmd/dlv` when you run it on the command line?

**Comment by tojkamaster** [comment]
`$ /usr/bin/go get -v -u github.com/go-delve/delve/cmd/dlv
github.com/go-delve/delve (download)
github.com/go-delve/delve/pkg/dwarf/op
github.com/go-delve/delve/pkg/dwarf/godwarf
github.com/go-delve/delve/pkg/dwarf/reader
github.com/go-delve/delve/pkg/proc
github.com/go-delve/delve/service/api
github.com/go-delve/delve/pkg/proc/winutil
github.com/go-delve/delve/pkg/proc/linutil
github.com/go-delve/delve/pkg/proc/core/minidump
github.com/go-delve/delve/pkg/proc/native
github.com/go-delve/delve/pkg/proc/gdbserial
github.com/go-delve/delve/pkg/locspec
github.com/go-delve/delve/pkg/proc/core
github.com/go-delve/delve/service/debugger
github.com/go-delve/delve/service
github.com/go-delve/delve/service/rpc2
github.com/go-delve/delve/service/dap
github.com/go-delve/delve/service/rpc1
github.com/go-delve/delve/service/rpccommon
github.com/go-delve/delve/pkg/terminal/starbind
github.com/go-delve/delve/pkg/terminal
github.com/go-delve/delve/cmd/dlv/cmds
github.com/go-delve/delve/cmd/dlv
# github.com/go-delve/delve/cmd/dlv
/home/m3697603/.cache/go-build/d0/d097b42f035864356d4972715f8e756bf66c4fd1aa344aaf9b80f5b969302430-d(_go_.o): In function `github_com_go_delve_delve_vendor_go_starlark_net_starlark.hashString':
/home/m3697603/go/src/github.com/go-delve/delve/vendor/go.starlark.net/starlark/hashtable.go:357: undefined reference to `runtime.stringHash'
collect2: error: ld returned 1 exit status`

**Comment by hyangah** [comment]
@tojkamaster what is your go version and platform? (`go version` and `go env GOOS GOARCH`)

**Comment by tojkamaster** [comment]
Go version:
`go version go1.10.3 gccgo (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0 linux/amd64`

Go env GOOS GOARCH:
`linux
amd64`

**Comment by hyangah** [comment]
@tojkamaster thanks. Unfortunately, dlv does not support gccgo. https://github.com/go-delve/delve/issues/1790 

Maybe the extension should detect it and prompt a warning.

p.s. `go1.10.3` is quite old.
