### ISSUE TITLE
Disable real-time syntax error highlighting with gopls

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/vscode-go#3239]
Hi when using gopls, how can I disable the real-time syntax error highlighting? 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When using gopls, syntax check runs as I type and highlight syntax errors while I'm writing symbols. Without the language server, VS Code would highlight syntax errors on save only. 

I find continuous error highlighting very distracting and would like to turn it off and have it on file save only. I've looked at the docs for both this extension and for gopls, but it doesn't seem that this is an option available.

**Describe alternatives you've considered**
Turning off gopls doesn't seem to be a valid alternative, because I have many modules and autocomplete takes forever.

**Comment by stamblerre** [comment]
This is currently unsupported with `gopls`, but it may be available in the future (https://go-review.googlesource.com/c/vscode-go/+/222338). A workaround for now would be to disable the diagnostics that come from `gopls`, but not `gopls` entirely:

```json5
"go.languageServerExperimentalFeatures": {
	"diagnostics": false
}
```
