### ISSUE TITLE
Some compile errors are not being highlighted if there are also lint errors

### ISSUE THREAD

**Issue by darylng** [Microsoft/vscode-go#324]
```go 
package demo

var LintError int

func foo() {
	bar
}
```

For the above example, `bar` is does not have the red squiggly line under it but `var LintError int` has the green line under it.  "Show Errors and Warnings" only lists the `var LintError int`.  If I comment out or remove `var LintError int` then bar has the red squiggly line under it as expected.  

I'm running vscode 1.1.0 on Windows and vscode-go 0.6.38

**Comment by ecunal** [comment]
I also have a similar problem, even if I have multiple errors or warnings, only highlights and lists one of them (generally the last one in the file). I also use the same vscode and vscode-go versions on Mac.

**Comment by lukehoban** [comment]
I believe this is the same issue as https://github.com/Microsoft/vscode-go/issues/322.  There's a fix for that now in master - should be a new release pushed soon with the fix.
