### ISSUE TITLE
Problem in mouse hover tooltip

### ISSUE THREAD

**Issue by ashishka13** [microsoft/vscode-go#3240]
![Screenshot from 2020-05-14 14-57-23](https://user-images.githubusercontent.com/45966064/81919074-fa2c7d80-95f4-11ea-9a8e-cac3e0eeba82.png)

Issue Type: <b>Bug</b>

1) Declare a constant block and add comment for it shown in the picture. 2) Add few constants in it with comments of their own. 3) Use that constant somewhere else in the program. 4) Take your mouse pointer over that constant. 
In step 4 we are expected too see the comment written for that declared "constant" to show up in the tooltip, but insted it shows us the comment tip of "constant block"

I have attached a screen shot for the reference.
In that screenshot we are expected to see "this is constant1" for the constant "a", but instead we are seeing "constants list" in the mouse hover tool-tip.

Extension version: 0.14.2
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 4.15.0-76-generic

**Comment by hyangah** [comment]
@ashishka13 Are you using the language server? `"go.useLanguageServer": true`

I am guessing associating each const in a const block with the block's comment was based on the assumption on the block comments (as described at the end of https://golang.org/doc/effective_go.html#commentary). So, the recommendation is to group only related consts and name the const descriptive enough as itself within the const group. 

But I wonder if there is any plan to utilize the immediate comment. @stamblerre

**Comment by stamblerre** [comment]
Thanks for the report. This is just a silly mistake - will be fixed in https://go-review.googlesource.com/c/tools/+/234101.

**Comment by stamblerre** [comment]
I'll close this issue since it's been addressed, but the fix won't be available till the next `gopls` release.
