### ISSUE TITLE
0.14.2 broken on macos

### ISSUE THREAD

**Issue by ooZberg** [microsoft/vscode-go#3246]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.3 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.45.1 5763d909d5f12fe19f215cbfdd29a91c0fa9208a x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.2
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- darwin amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

### Describe the bug

When trying to use the latest 0.14.2 version of the extension nothing works, like "Go: Current GOPATH", and if you look in the developer console you get

    abstractExtensionService.ts:396 Activating extension 'ms-vscode.Go' failed: Cannot find module 'tough-cookie'
    Require stack:
    - /Users/oozberg/.vscode/extensions/ms-vscode.go-0.14.2/node_modules/request/lib/cookies.js
    - /Users/oozberg/.vscode/extensions/ms-vscode.go-0.14.2/node_modules/request/index.js
    - /Users/oozberg/.vscode/extensions/ms-vscode.go-0.14.2/node_modules/web-request/index.js
    - /Users/oozberg/.vscode/extensions/ms-vscode.go-0.14.2/out/src/goLanguageServer.js
    - /Users/oozberg/.vscode/extensions/ms-vscode.go-0.14.2/out/src/goInstallTools.js
    - /Users/oozberg/.vscode/extensions/ms-vscode.go-0.14.2/out/src/goPackages.js
    - /Users/oozberg/.vscode/extensions/ms-vscode.go-0.14.2/out/src/goBrowsePackage.js
    - /Users/oozberg/.vscode/extensions/ms-vscode.go-0.14.2/out/src/goMain.js
    - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
    - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
    - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.
    notificationsAlerts.ts:40 Command 'Go: Current GOPATH' resulted in an error (command 'go.gopath' not found)

### Steps to reproduce the behavior:
1. Install the 0.14.2 extension on macos, as well as the official golang pkg installer
2. Try to run Go: Current GOPATH

And for the record, downgrading to 0.14.1 works fine.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by butuzov** [comment]
Can't confirm bug. 

1) `tough-cookie` is on a place (have to check it with vsix extension)
2) `Go: Current GOPATH` gives `/Users/butuzov/go is the current GOPATH.` 

The only diff I am still on 1.14.2, but I do believe it doesn't matter. 

Try to delete the extension and install it again. it also possible to check is about subject npm module at `~/.vscode/extensions/ms-vscode.go-0.14.2`. Npm modules a bundled with extension, so it supposes to be some client error.

**Comment by ooZberg** [comment]
Thanks for the hints. Uninstalling and re-installing did not work, tried that multiple times, including restarting VS Code in between, but what did work was:

- Uninstall the extension 0.14.1 which I was using now
- `rm -r ~/.vscode/extensions/ms-vscode.go-0.14.1`
- Install the extension 0.14.2
- Now it works as expected

**Comment by stamblerre** [comment]
Thanks for following up, @ooZberg! It's possible you had a corrupted installation. I'll close this issue unless we get more reports of similar issues.
