### ISSUE TITLE
Extension Repository Migration Plan

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-go#3247]
We are moving to https://github.com/golang/vscode-go, managed by the Golang github organization. Read the [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in the readme to learn more.

This issue tracks the progress of the repo move.

_Start Date: beginning of May_
_Target Date: end of May_

- [x] Create a public issue with the checklist. @hyangah 
- [x] Pin this issue and update the README. @ramya-rao-a
- [x] Update github.com/microsoft/vscode-go/README.md and issue templates. @ramya-rao-a 
- [x] Update github.com/golang/vscode-go documentation and issue templates. @hyangah @stamblerre  
- [x] Notify open PR authors, and ask to move to https://github.com/golang/vscode-go.
- [x] Transfer or close remaining open issues.
- [x] ~~Commit-- all remaining PRs and get ready for the final version of `ms-vscode.Go` (v0.14.N) with `github.com/golang/vscode-go/issues` as the issue tracker. @ramya-rao-a~~ (we will skip this)
- [x] Update wiki pages @ramya-rao-a

**Comment by ramya-rao-a** [comment]
See #3253 for the next steps
