### ISSUE TITLE
Debugging uses wrong working directory

### ISSUE THREAD

**Issue by JoseFMP** [microsoft/vscode-go#3251]
I looked into the source code of this repo and I actually found the problem. It should take... 2 minutes to create a PR to fix it.  Glad to suggest the fix.

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.14.3 linux/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.45.0
d69a79b73808559a91206d73d7717ff5f798f23c
x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.2
- Run `go env` to get the go development environment details
	- `GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/josem/.cache/go-build"
GOENV="/home/josem/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/josem/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/5759"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5759/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/***********/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fme`

# Describe the bug
Cannot debug my Go application using this VSCode extension. The problem is that the extension is setting the working directory as the directory where the Go package is. However, this is wrong as the working directory is set through the launch configuration "cwd" property. But this value is by a mistake not used, and instead the path to the go package is used. I can see the problem in the source code of the extension.
`
## Steps to reproduce:
* Create a launch configuration in `launch.json` to debug a go package
* Specify the working directory using `cwd` property
* Run a debug configuration to launch the debugger with delve
* See wrong working directory logged in the console. The working directory logged is the directory to the package to be debugged, instead of the working directory specified in the run configuration.
The message says "Current working directory: [here the path to the package to be debugged, not the working directory]"
* As a consequence of the previous step, you get error in the console "main.go:4:2: package ****** is not in GOROOT (*******)"
`
# A clear and concise description of what you expected to happen.
The debugging functionality works. This implied the working directory must be taken correctly.

**Comment by hyangah** [comment]
@JoseFMP Please send a PR to the new repository `github.com/golang/vscode-go` (https://github.com/microsoft/vscode-go#we-are-moving)

I still need to understand the error message `"main.go:4:2: package ****** is not in GOROOT (*******)"`  - that's a build error so I am not yet sure how changing `cwd` will help finding the `main.go` file. But I hope it will become obvious with the PR for fix. 

cc @quoctruong @ramya-rao-a

**Comment by quoctruong** [comment]
@JoseFMP, the `cwd` property is only used for remote attach scenario (the correct property to use for the normal scenario is `program`).

**Comment by ramya-rao-a** [comment]
@quoctruong Actually, `cwd` is also used in other scenarios. See https://github.com/microsoft/vscode-go/blob/0.14.3/src/debugAdapter/goDebug.ts#L499-L501

But it is used for the `wd` flag that is passed to delve and not as the folder from where delve should be launched.

@JoseFMP Can you share the scenario where you would want the working directory to be different from the folder corresponding to the package of the file?
