### ISSUE TITLE
numeric constants containing underscore are not colored correctly

### ISSUE THREAD

**Issue by WBare** [microsoft/vscode-go#3254]
Go version 1.14.1
VS Code Go: 0.14.2
VS Code version:
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Go allows embedded underscore characters in numeric constants.  Please see language spec:
https://golang.org/ref/spec#Integer_literals
and
https://golang.org/ref/spec#Floating-point_literals

the following program compiles correctly where 5_3_1 == 531, but only the number 3.1415 is colored correctly.

    package main
    import (
    	"fmt"
    )
    func main() {
    	fmt.Println(5_3_1, 1_000_000, 3.1415)
    }

**Comment by hyangah** [comment]
Thanks for the report.

There is already an open bug. Let's follow up there. 
https://github.com/jeff-hykin/better-go-syntax/issues/3
