### ISSUE TITLE
Gopls does not support versions of go <=1.12

### ISSUE THREAD

**Issue by bvwells** [microsoft/vscode-go#3255]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
```
$ go version
go version go1.12.17 windows/amd64
```
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
```	

```
- Check your installed extensions to get the version of the VS Code Go extension 
	- <Paste Go extension version here>
- Run `go env` to get the go development environment details
```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\bwells\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\bwells\go
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\bwells\AppData\Local\Temp\go-build198506238=/tmp/go-build -gno-record-gcc-switches
```
### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
When updating VSCode to use the latest version of gopls I get the following error:

```
gopls:
Error: Command failed: C:\Go\bin\go.exe get -v golang.org/x/tools/gopls
Fetching https://golang.org/x/tools/gopls?go-get=1
Parsing meta tags from https://golang.org/x/tools/gopls?go-get=1 (status code 200)
get "golang.org/x/tools/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/gopls?go-get=1
get "golang.org/x/tools/gopls": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools/internal/jsonrpc2
# golang.org/x/tools/internal/jsonrpc2
..\..\..\..\..\go\pkg\mod\golang.org\x\tools@v0.0.0-20200513154647-78b527d18275\internal\jsonrpc2\messages.go:168:5: undefined: errors.As
Fetching https://golang.org/x/tools/gopls?go-get=1
Parsing meta tags from https://golang.org/x/tools/gopls?go-get=1 (status code 200)
get "golang.org/x/tools/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/gopls?go-get=1
get "golang.org/x/tools/gopls": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools/internal/jsonrpc2
# golang.org/x/tools/internal/jsonrpc2
..\..\..\..\..\go\pkg\mod\golang.org\x\tools@v0.0.0-20200513154647-78b527d18275\internal\jsonrpc2\messages.go:168:5: undefined: errors.As
```

gopls failed to install due to a dependency on a package which uses a newer go language feature (errors.As) than is available in the version of go I am using (go 1.12). I have also submitted an issue here:
https://github.com/golang/go/issues/39146

Depending on the outcome of this issue you may need to update your documentation to say that you only support go >= 1.13 as currently the extension says:

Note: 

![image](https://user-images.githubusercontent.com/22873967/82364519-4a497c80-9a07-11ea-900d-30ebbebf7d3a.png)

### Steps to reproduce the behavior:
1. Install go 1.12
2. Run 'Go Install/Update Tools'
3. See error

**Comment by bvwells** [comment]
Will update my vscode/extension version later...

**Comment by stamblerre** [comment]
Thanks for the report. This has been reported upstream as https://github.com/golang/vscode-go/issues/66 (see https://github.com/microsoft/vscode-go/issues/3247 for details on the repository migration). Going to close in favor of the upstream issue.
