### ISSUE TITLE
Unable to set breakpoint when using gutter and clear Code coverage 

### ISSUE THREAD

**Issue by JCzz** [microsoft/vscode-go#3256]
How do you clear the codecover in the go file covered - it is kind of not great to look at when coding.

II tried to use gutter to turn down the distraction color, but then I am unable to set any breakpoints as the gutter is now all code coverage:

```
    "go.coverOnSave": true,
    "go.coverageDecorator": {
        "type": "gutter",
        "coveredHighlightColor": "rgba(64,128,128,0.5)",
        "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
        "coveredGutterStyle": "blockgreen",
        "uncoveredGutterStyle": "blockred"
    },
    "go.coverOnSingleTest": true,
```

**Comment by hyangah** [comment]
There is an open bug #3252 about not being able to clear the code coverage. 
Will you still need the workaround (gutter instead of highlight) if the bug is fixed?

**Comment by JCzz** [comment]
Thanks

I turned down the color using "highlight", this makes it acceptable to look at :-)

Regarding "gutter", it is very nice - that is if you could still set breakpoints.

**Comment by ramya-rao-a** [comment]
Hey @JCzz 

#3252 was indeed a regression and I have released an update with the fix
Do try the latest version (0.14.3) of the extension and the code coverage should get cleared on file save.
