### ISSUE TITLE
Updated to 0.14.3 or the nightly and entirely stopped working

### ISSUE THREAD

**Issue by dioptre** [microsoft/vscode-go#3258]
I keep references to multiple objects throughout the package I'm working on. Restarted with the new extension and nothing works. I have 300 errors in my code where there were none. It still compiles without errors. 

You can test the extension on my code if you'd like:
https://github.com/sfproductlabs/roo

Thanks!
Andrew

**Comment by stamblerre** [comment]
Can you please share your Go-related VS Code settings (Ctrl+Shift+P -> Open Settings (JSON))?

**Comment by dioptre** [comment]
ah its working again :/
