### ISSUE TITLE
Highlighting the argument name is string matching, instead of highlighting the actual argument number

### ISSUE THREAD

**Issue by prashantv** [Microsoft/vscode-go#327]
If the argument name is a substring of the function name (or a previous argument), the wrong thing is highlighted.

E.g.
![image](https://cloud.githubusercontent.com/assets/140159/15265914/370fd22a-1948-11e6-87eb-9c137900fd97.png)

**Comment by lukehoban** [comment]
@egamma Is this expected to be possible to fix in extensions?  As far as I can tell, this is controlled by logic in VS Code.

**Comment by prashantv** [comment]
Should I file an issue on the vscode repository instead?

**Comment by egamma** [comment]
Moving to vscode

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode#10293
