### ISSUE TITLE
When Importing a package, ask for the import name

### ISSUE THREAD

**Issue by matwachich** [Microsoft/vscode-go#329]
When importing a package using gopkgs, just after selecting the package to import, we should be prompted to enter a name for the import.

Example:
I import the package github.com/test/gopher-mylib, `import "github.com/test/gopher-mylib"` will be added in the top of the source file.
But what if I want to import it as mylib, or as _? It should be `import mylib "github.com/test/gopher-mylib"`

Hope this will be implemented, thanks :)

**Comment by lukehoban** [comment]
Does it make sense to always prompt for this?  It feels like that will make the 90% case meaningfully more cumbersome.

Any opinions one way or the other?

Note that you can use go to definition and/or rename to fairly easily change the name after it's added - though these don't cover all the cases that explicitly prompting would address.

**Comment by JohanSJA** [comment]
Just wondering how the user experience would be like when `goimports`/`goreturns` is run on each save.

**Comment by matwachich** [comment]
I think that yes it makes sens if the prompt is pre-filled with the default
import name.
If you want the standard default import name you just have to hit Enter key
a second time, if you want another import name, just type it and hit Enter.

Le Mer 18 Mai 2016 8:28, Johan Sim Jian An <notifications@github.com> a
écrit :

**Comment by peterbourgon** [comment]
Changing the import name isn't a 10% case, or even a 1% case. It's fine to have the user do this manually.

**Comment by ramya-rao-a** [comment]
@JohanSJA `goimports/goreturns` do not change the alias on the imports

@matwachich Like @lukehoban and @peterbourgon have mentioned, this is a very corner case. Closing this for now. If there are more people supporting this, then we can circle back.
