### ISSUE TITLE
Browse selected package

### ISSUE THREAD

**Issue by kdeenanauth** [Microsoft/vscode-go#330]
It would be handy to be able go to an import, similar to how `ctrl + click` works.

**Comment by ramya-rao-a** [comment]
@kdeenanauth Do you mean to be able to go to the line where the import statement lies? Or go to the go files which are part of the imported package?

**Comment by kdeenanauth** [comment]
When clicking on an import statement line, go to the associated file(s). I realize there may be some disambiguation problems though :\

**Comment by ramya-rao-a** [comment]
Yup, when there are multiple files associated with a package, where would the click go

**Comment by kdeenanauth** [comment]
I'm not sure ¯\_(ツ)_/¯

Ideally showing a popup so you can click the file you want. But I've heard it's not possible for extensions to implement custom menus. You might just be limited to going to the first file.

**Comment by ramya-rao-a** [comment]
`Browse Packages` in Sublime does something similar. 
We can use the quickpick control to show the list of files in the selected package.

**Comment by jackie-qiu** [comment]
@ramya-rao-a When will this PR be implemented?

**Comment by ramya-rao-a** [comment]
@jackie-qiu As far as I know, there is no PR open for this.

Do you mean to ask when will this feature be implemented?

**Comment by jackie-qiu** [comment]
@ramya-rao-a Yes, when will this feature be implemented?

**Comment by ramya-rao-a** [comment]
Definitely in June

**Comment by jackie-qiu** [comment]
Has this feature been implemented?

**Comment by ramya-rao-a** [comment]
Hey @jackie-qiu, not yet. I'll try to get it into the next update

**Comment by ramya-rao-a** [comment]
Re-opening to do the below

The Browse Packages feature relies on the running of `go list all` when extension gets activated (when you open a VS Code window).
`go list all` is  a little slow, but much more slower on slower machines.

- Will add a message saying "Still collecting all packages, try after some time"
- Will also cache the result, so that the second time you open VS Code, you will have something to browse, while in the background `go list all` is run again and cache is updated.

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update (0.6.63) to the Go extension
 - If cursor is on an import statement, then files from the imported package will be shown in the quick pick control
- Else, all packages are shown in the quick pick control. Select any and corresponding Go files will be shown next.
- Selecting any of the Go files, will open the file in a new editor.
