### ISSUE TITLE
Indicate task start/end in the output pan

### ISSUE THREAD

**Issue by matwachich** [Microsoft/vscode-go#331]
It will be usefull to know when a task starts and when it ends in the lower output pan.

Example:

```
[2016/05/18 16:00:00] Task "task_name" started
some task output
some task output
[2016/05/18 16:00:30] Task "task_name" ended (30s)
```

**Comment by ramya-rao-a** [comment]
@matwachich Are you referring to tasks in general or the build/linting/testing output from the Go extension?

**Comment by matwachich** [comment]
Any task

Le ven. 13 janv. 2017 à 01:40, Ramya Rao <notifications@github.com> a
écrit :

**Comment by ramya-rao-a** [comment]
In that case, that should be feature request for VS Code and the Go extension.
Please create an issue at https://github.com/Microsoft/vscode
