### ISSUE TITLE
[Windows] Debug fails - ENOENT

### ISSUE THREAD

**Issue by harnash** [Microsoft/vscode-go#332]
I have `GOPATH` set to `P:\_golang_` and when trying to run Debug I get the following error:

`Failed to continue: "Error: spawn P:_golang_\bin\dlv.exe ENOENT"`

Setting `GOPATH` to the following values still doesn't fix it:

- `P:\\_golang_`
- `P:/_golang_`

**Comment by hickeng** [comment]
I have a similar issue. If I don't have dlv.exe on the path I get a diiferent error:
```
Failed to continue: "Cannot find Delve debugger. Ensure it is in your `GOPATH/bin` or `PATH`."
```

so having it on the PATH evidently has an impact but not a successful one.

**Comment by lukehoban** [comment]
I can't seem to reproduce this.  How do you have your GOPATH configured? (globally set env var, settings.json, something else?)

**Comment by harnash** [comment]
I had it set through user environment vars. I did try to override it with global settings and it didn't helped.

**Comment by hickeng** [comment]
I tried both as well. Notes:
delve installed via the following, run in git-bash: https://github.com/derekparker/delve/blob/master/Documentation/installation/windows/install.md
Delve runs fine when run directly

As an alternative approach I also have Bash on Ubuntu on Windows install and go (sort of) working on there. If there's any available mechanism to leverage that I'm happy to try it.

**Comment by harnash** [comment]
Here is my launch.json

```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}\\src\\github.com\\harnash\\watcher\\main.go",
            "env": {},
            "args": []
        }
    ]
}
```
I had to reinstall my Windows and after reinstall I have the following env variables set:
```
GOPATH=D:\_golang_
GOROOT=C:\Go\
```
my `PATH` is set to:
```
C:\Go\bin;d:\_golang_\bin\
```
dlv.exe is runnable from command line without problems.

**Comment by christian-boks** [comment]
I can reproduce the error if I write an errornous program path in launch.json. 

- If I write `"program": "${workspaceRoot}/ght/view"` (which is where my code is located) everything works fine.
- If I write `"program": "${workspaceRoot}/ght/view1"` I get `can't load package: package ght: no buildable Go source files in c:\gohome\src\ght
exit status 1` in the debug console.
- If I write `"program": "${workspaceRoot}/ght1/view"` I get the `"Failed to continue: "Error: spawn c:\gohome\bin\dlv.exe ENOENT""` dropdown.


The error is a bit misleading because it says it can't find dlv.exe, but what it really means is that it can't find the program specified in launch.json

**Comment by harnash** [comment]
@christian-boks: that explains a lot. I will try to tune my `launch.json` and see if I can get rid of the bug. Still the error I get has additional problem since it is missing `\` after the drive descriptor.

**Comment by juloliveira** [comment]
Work! Bellow my launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "C:\\Users\\joliveira\\Documents\\Go\\src\\local\\test",
            "env": {},
            "args": []
        }
    ]
}
```

**Comment by harnash** [comment]
Yup. I've changed my path to the correct one and I don't have this problem.
@lukehoban I wish error message was more meaningful in this case. I'm closing this issue. You can try to fix the message later :-)
