### ISSUE TITLE
Can't step into any code with interactive debugger

### ISSUE THREAD

**Issue by andrewrgoss** [Microsoft/vscode-go#334]
I am testing VSCode interactive debugging out on a simple program. I can't get the call stack to populate and actually step into any code starting at my breakpoint and the console output offers no reasons as to why. Installed Delve Debugger version = 0.11.0-alpha. Using latest version of your VSCode extension, 0.6.38. Other than the .gif image for debugging from the documentation is there a step-by-step video for debugging Go programs with this extension? Haven't been able to find anything and it would limit questions like this.

launch file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
        }
    ]
}
```

When I launch the debugger, this is the message from the console:

```
2016/05/17 16:44:44 server.go:41: Using API v1
2016/05/17 16:44:44 debugger.go:61: launching process with args: [./debug]
API server listening at: 127.0.0.1:2345
2016/05/17 16:44:45 debugger.go:235: created breakpoint: &api.Breakpoint
{ID:1, Name:"", Addr:0x401066, File:"C:/Users/andgoss/GoLangCode/src/_ag_working/debugging/gocode_print_yyyymmdd.go",
Line:26, FunctionName:"main.main", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0,
Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil),
HitCount:map[string]uint64{}, TotalHitCount:0x0}
2016/05/17 16:44:45 debugger.go:390: continuing
```

**Comment by dearplain** [comment]
Is C:/Users/andgoss/GoLangCode your $GOPATH?
this is my suggestion: you should put everything under $GOPATH, do not create soft link, do not use vendor folder.

**Comment by andrewrgoss** [comment]
Yes, this is currently my GOPATH. ARe you suggesting changing this setting in the launch file? 
`"program": "${workspaceRoot}",`

```bash
$ echo $GOPATH
C:\Users\andgoss\GoLangCode
```

**Comment by orloffm** [comment]
I'm strangely having this on Windows, but on Linux everything went smoothly after doing the same things.

**Comment by mattetti** [comment]
Is that still an issue? AFAIK the debugger integration received a bunch of fixes over the last few months and hopefully that specific problem was fixed within the last 8 months.

**Comment by andrewrgoss** [comment]
Yes, I was able to resolve this issue several months ago by reinstalling Delve altogether - it had originally conflicted with an existing library in the first installation. The cryptic error message wasn't too helpful obviously - figured out the underlying problem through guess-and-check basically. Closing this issue now.
