### ISSUE TITLE
No build errors displayed if golint have some warnings

### ISSUE THREAD

**Issue by mileusna** [Microsoft/vscode-go#335]
I experienced strange bug: If there are golint warnings and build errors, it will show only warnings from the first tool (golint) and not the errors from the go build.
I have checked the output console and go build does returns errors, but they are not displayed in errors or editor.
When I fix golint warnings, on next save go build errors will be displayed as they should. It looks like it lists errors/warnings only from the first tool.

**Comment by mafredri** [comment]
I've experienced the same ever since the vscode `1.1.0` update. It's become really hard to fix all errors after a slightly longer coding session since only a few are shown at a time.

**Comment by lukehoban** [comment]
Yes - this was fixed with https://github.com/Microsoft/vscode-go/commit/e989b977b35a16d77280d56c36685ac4ba2dcc64, but there was a delay in getting a new release out.  Version 0.6.39 is available now with this fix included.
