### ISSUE TITLE
dlv exec ./mydebug

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode-go#336]
(code v 1.1.1, plugin v 0.6.38, osx 10.11.5, dlv 0.11.0-alpha, golang 1.6.2)
mode debug works
mode test works
mode exec fails: `could not launch process: could not fork/exec`

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch dlv exec.",
			"request": "launch",
			"type": "go",
			"mode": "exec",
			"program": "${workspaceRoot}",
			"env": {},
			"args": ["./mydebug"]
		}
	]
}
```
manually `dlv exec ./mydebug` in (mac os) terminal works

**Comment by lukehoban** [comment]
To recreate the equivlanet of `dlv exec ./mydebug` you would need to set `"mode": "exec"` and `"program": `${workspaceRoot}/mydebug` (assuming that myDebug is in the root of your workspace.  The `"args"` setting is for arguments to the application you are debugging, not arguments to Delve.
