### ISSUE TITLE
[Go] Command not available warning messages displaying after installing

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode-go#337]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

On first time use the Go extension is constantly showing a warning to install gocode and golint even after installing and restarting Code. Any way to fix this?

**Comment by lukehoban** [comment]
Are you sure these tools are installed?  If so, where are they on your GOPATH on your system? Can you share what the `Go: Current GOPATH` command returns in VS Code for you?

**Comment by lukehoban** [comment]
Closing for now - if you have additional details - please reopen.
