### ISSUE TITLE
Rename symbol not working

### ISSUE THREAD

**Issue by davyzhang** [Microsoft/vscode-go#342]
error: 
Cannot rename due to errors: gorename: can't find package containing /Users/xxx/go/src/xxx/lib/xxx.go

no matter how simple the go source is

**Comment by lukehoban** [comment]
I expect this is going to be related to your source code not being under your active GOPATH.  

There's a report of a similar issue here: https://github.com/fatih/vim-go/issues/221 - the tips there should mostly apply here as well.

If you are not able to resolve the problem could you share exact details about your environment - including the result of running `Go: Current GOPATH`?

**Comment by davyzhang** [comment]
Thanks for the reply, my GOPATH is a symlink of other directory, So for now it shows :Current GOPATH:/Users/myname/go

but it is actually a symlink of /Users/myname/Dropbox/go

I don't know if it will cause the problem,

**Comment by davyzhang** [comment]
Yep, it turns out that the symlinked directory is the culprit of this problem

**Comment by jontonsoup** [comment]
I am getting this same issue but my path does not have symlinks. 

I am using two different locations for the GOPATH, though. 

```
go env GOPATH                                                                                                                                         [~/go/bin]
/Users/jonathan/go:/Users/jonathan/src/spout
```

**Comment by ramya-rao-a** [comment]
@jontonsoup Do you still have this issue? Can you share your error message?

**Comment by jontonsoup** [comment]
@ramya-rao-a I ended up changing the way I do my GOPATH and it fixed. I think the src needed to be moved to the bottom level.

**Comment by ramya-rao-a** [comment]
@jontonsoup Good to know, thanks!

**Comment by njsrikar** [comment]
I am seeing a similar issue. Renaming anything vscode-code via the right-click menu never worked for me. How can I get more debug info? For example, all I get right now is "Sorry, rename failed to execute." when I tried to rename a package or a method.

`$ go env GOPATH
D:\git\Go`

**Comment by ramya-rao-a** [comment]
@njsrikar You should also be getting a "Rename failed: " followed by the error thrown by the `gorename` tool

**Comment by deepakjois** [comment]
I am not able to rename symbols. I don’t have an explicit GOPATH set.

```
go env GOPATH
```

I get the error `Sorry, rename failed to execute`.

**Comment by ramya-rao-a** [comment]
@deepakjois 

- Do you see any message of the form `Rename failed: ...`
- Do you see any errors in the console? Run `Developer: Toggle Developer Tools` to open the console
- Can you run `gorename` in the terminal outside VS Code and see if it works as expected.

**Comment by deepakjois** [comment]
I am running this on Linux under Gnome. I managed to fix the error by launching VS Code from my commandline, as opposed to launching it the usual way from Gnome shell. There seems to be a subtle difference in the way the environment is setup in the two cases.

Anyway, the error still persists when I launch VSCode directly from the Gnome menus, so here are the answers to your questions, in case it helps.
* No I do not see any message of the form `Rename failed: ...`
* I have attached the log of the errors in the console: [vscode.txt](https://github.com/Microsoft/vscode-go/files/1206770/vscode.txt)
* I did not try that. But looks like gorename is working.

**Comment by ramya-rao-a** [comment]
@deepakjois 
- Run the command `Go: Current GOPATH`.
- In the integrated terminal, run `echo $GOPATH` and `go env GOPATH`. 

Compare the output in all 3 cases with your expected GOPATH. All match? None?

**Comment by deepakjois** [comment]
All match.

**Comment by ramya-rao-a** [comment]
Ya, but all match with the GOPATH you expect? And your current Go file is under that GOPATH?

**Comment by deepakjois** [comment]
Yes. I have not set an explicit GOPATH anywhere in my environment, so I expect it to be `~/go`. All the cases you enumerated above give the same value `/home/deepak/go`, which is what I expect.

Did you look at the log of errors in the console I attached above? Did that contain anything helpful? If not, happy to do something that might help. I can reproduce this consistently.

**Comment by ramya-rao-a** [comment]
@deepakjois 

The stack trace has the error message of the format `Rename failed: ...`

The reason I was looking for this was that anything following the `Rename failed:` words are the words from the error message from running `gorename`

From the stack trace I see a lot of `"go": executable file not found in $PATH`. This error is coming from `gorename`

Can you either add the location of the `go` executable to $PATH or set the `go.goroot` to your GOROOT?

**Comment by BTooLs** [comment]
I solved the problem on Windows by
1. Create  an ENV variable "GOPATH=D:\go-projects\" (don't forget the last \)
2. Move the project inside "D:\go-projects\src" folder

**Comment by ryo-endo** [comment]
> 2. Move the project inside "D:\go-projects\src" folder

I solved too. thankyou.

NG: $GOPATH/myproject/main.go
OK: $GOPATH/src/myproject/main.go

`gorename` check that the tartget file is included in $GOPATH/src.

**Comment by ramya-rao-a** [comment]
@meddario Go supports the use of multiple GOPATHs. Why not add the location of your source code to the GOPATH?

**Comment by talentwill** [comment]
It is true ! @lukehoban 
>  I expect this is going to be related to your source code not being under your active GOPATH.

Now I resolved it by this solution: [automatically-defining-gopath-on-a-per-project-basis](https://stackoverflow.com/questions/17780754/automatically-defining-gopath-on-a-per-project-basis).  Setting `go.toolsGopath.` and` go.inferGopath` can work.
