### ISSUE TITLE
Find All References reporting No results.

### ISSUE THREAD

**Issue by 21E14** [Microsoft/vscode-go#346]
"Find All References" consistently reports "No results" in Visual Studio Code Version 1.1.1 for go version go1.6.2 linux/amd64 (Ubuntu 14.04). All required tools installed.

**Comment by foobar** [comment]
I'm having the same issue with vscode 1.2.0, on Fedora23, go version go1.6.2 linux/amd64

**Comment by georghendrik** [comment]
@foobar @21E14 Updating the go extension from 0.6.38 to 0.6.39 fixed it for me on vscode 1.2.1, go1.6.2 windows/amd64.

**Comment by 21E14** [comment]
@foobar @georghendrik Upgrading to Version 1.2.1 corrected the issue for me. Closing this issue.

**Comment by foobar** [comment]
updated to vscode 1.2.1 and go extension 0.6.39, but still not working.

**Comment by s-u-p-e-r-t-r-a-m-p** [comment]
same here - no results; fedora 23 vscode 1.7.1 02611b40b24c9df2726ad8b33f5ef5f67ac30b44

**Comment by foobar** [comment]
update: I've no issue with current version so the problem should have been fixed somewhere

**Comment by tagatac** [comment]
@foobar did you uninstall and reinstall or something? I am experiencing this issue with VS Code 1.7.1, Go extension 0.6.49.

**Comment by foobar** [comment]
@tagatac I did not uninstall it.
Another guess is that it has something to to with your project. Did you try other projects?

**Comment by tagatac** [comment]
I can try, but my coworker was able to find references in the same project right next to me.

**Comment by Jerry7X** [comment]
Hi，i have this issue too at the latest version, any suggestion?

**Comment by ramya-rao-a** [comment]
@Jerry7X @georgeonofrei This issue is an old one. Can you guys comment/upvote #652 ?
