### ISSUE TITLE
hitting tab goes out of the file editor

### ISSUE THREAD

**Issue by tugberkugurlu** [Microsoft/vscode-go#347]
hitting tab goes out of the file editor, not sure why though.

**Comment by lukehoban** [comment]
Can you provide any more details on this?  Is it specific to the Go language in VScode, or a general problem with vscode?  Do you have repro steps?

**Comment by tugberkugurlu** [comment]
I figured why this was happening which is kind of silly of me :smile: Most probably, I accidentally hit `CTRL + M` which gets you into "Tab moves focus" mode in VS Code.
