### ISSUE TITLE
`Go: test coverage in current package` doesn't work

### ISSUE THREAD

**Issue by akrisanov** [Microsoft/vscode-go#350]
Hi there,
trying to run test coverage, but nothing happens. `Go: Test (package)` works fine.

My `setting.json` looks like:

``` json
{
    "stylelint.enable": true,

    "editor.fontFamily": "Fira Code",
    "editor.fontSize": 14,

    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goimports"
}
```

ENV: Go 1.6.2, Visual Studio Code Version 1.1.1, OS X El Capitan 10.11.6 Beta (15G7a).

**Comment by namsral** [comment]
Same here.

ENV: Go 1.6.2, Visual Studio Code Version 1.1.1, OS X El Capitan 10.11.4

**Comment by galacto** [comment]
same here 

ENV Go 1.7, VS code 1.4.0, OS X El Capitan 10.11.6

**Comment by dongjk** [comment]
same here,
go version go1.6.2 windows/amd64
Win7

**Comment by ramya-rao-a** [comment]
When I run `Go: Test coverage in current package`, the non `_test` files of the current package get updated with highlighted code that has been covered.

I am using go 1.7 in a Windows 10 machine and OS X El Capitan 10.11.6

Do any of you see any errors in the console?

**Comment by nochso** [comment]
I can confirm this. There is no output in the console. Turns out my tests were failing, but the extension kept quiet.

This doesn't capture any errors: https://github.com/Microsoft/vscode-go/blob/a46f3133d463e811661666a8369d207d5c41cc75/src/goCover.ts#L110

I've submitted a pull request that made this work for me #721

**Comment by ramya-rao-a** [comment]
The latest update (0.6.53) has the fix to this issue. Thanks @nochso 
The fix being that we now show an error message when tests fail while attempting to run test coverage
