### ISSUE TITLE
download of vsix file

### ISSUE THREAD

**Issue by athingisathing** [Microsoft/vscode-go#353]
is there a location i can just download the vsix file so i can automate the installation?

**Comment by lukehoban** [comment]
I think a URL along the lines of this will work:

https://lukehoban.gallery.vsassets.io/_apis/public/gallery/publisher/lukehoban/extension/Go/0.6.27/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage 

No idea if that's a stable API from the gallery or not though.  + @joaomoreno.

**Comment by lukehoban** [comment]
This also looks relavant: http://www.growingwiththeweb.com/2016/06/syncing-vscode-extensions.html.  

/cc @Tyriar.

**Comment by joaomoreno** [comment]
Not entirely sure whether that's API or otherwise, but that would be my answer too. 👍
