### ISSUE TITLE
Documentation of public types should be displayed in intellisense on usage

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode-go#354]
On mouseover as well. Go always complains if a func or a type is not documented and then one does it.
But intellisense does not show it, which is a pity.

**Comment by lukehoban** [comment]
Totally agreed.  This is tracked by https://github.com/Microsoft/vscode-go/issues/87, which I think we can continue to use to track progress on this.

**Comment by DasJott** [comment]
Thank you!
