### ISSUE TITLE
GOROOT and GOPATH are not passed from settings to the delve debugger.

### ISSUE THREAD

**Issue by bawr** [Microsoft/vscode-go#356]
Okay, so here's my general workflow:
1. I've set GOROOT as a global environment variable.
2. I want to set GOPATH only locally, in my workspace settings.json.

Unfortunately, while that works for Go tools, the delve debugger doesn't pick up my go.gopath setting. I've done some digging, and the core reason is that the node process doesn't pick up the environment variables that are set only by vscode, and GOPATH is set from go.gopath in such a way.

While GOROOT is not a problem for me, it would be a welcome addition as well.

My current workaround is basically to include `"env": {"GOPATH" : "${workspaceRoot}"}` in my launch.json configuration, but it feels a bit hackish. Is there another way I could pass the editor / workspace settings to the debugger and handle them from there? Do we even want to be able to do that?

I don't mind writing a PR for this, but I thought I'd ask in advance.

**Comment by shakahub** [comment]
+1

**Comment by ramya-rao-a** [comment]
As of now, there is no way to pass the settings to the debugger.
Therefore, setting the `env` property in `launch.json` is the way to go.
