### ISSUE TITLE
Make gofmt on save as default behaviour

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode-go#359]
The current behaviour is that we have to manually add a user preference file, it is annoying to add that file to each repository, it would be great if we have the gofmt on save functionality enabled by default.

**Comment by lukehoban** [comment]
Format on save has been the default for a little over a month.  See https://github.com/Microsoft/vscode-go/commit/36f705ffa8bd45d8bceb88dcab8dab8740d2e4b8 and https://github.com/Microsoft/vscode-go/issues/253.

Can you clarify whether you are seeing something different?

**Comment by thewhitetulip** [comment]
I am not sure what was wrong, when I was writing https://github.com/thewhitetulip/prettydiff, I had to manually add the gofmt on save thing in settings.json.

Thanks for letting me know!
