### ISSUE TITLE
buildOnSave should use 'go test -short'

### ISSUE THREAD

**Issue by tbroyer** [Microsoft/vscode-go#363]
`buildOnSave` runs `go test`, which might result in slow tests being run. It should default to short tests only, for a quicker feedback, i.e. `go test -short`.

(fwiw, my tests spawn PhantomJS instances, with tests exercising various timeouts, meaning that one test is **expected** to last at least 30s; those tests are disabled when `testing.Short()` is true, and I'd expect an _“on save”_ feature to only run fast tests)

**Comment by lukehoban** [comment]
Build on save runs `go test -c` which only compiles the test binary, it does not run tests.  

Are you sure you are seeing this 30s delay on `build on save`?  Does compiling your test binary take that long somehow?

**Comment by tbroyer** [comment]
Oh, I'm so so sorry.

I do have issues (first) because I setup my `GOPATH` to a symlink (`~/go` linking to `/mnt/ssd/tbr/go`), and vscode sometimes opens files from `~/go` and other times from `/mnt/ssd/tbr/go`, and has trouble reporting errors/warnings to the appropriate editor. This is my fault and I should try to find another, better setup.  
I must have misinterpreted this, plus some lag+CPU-usage probably due to other reasons at the time, and misread the vscode-go code (missing the `-c` flag).
