### ISSUE TITLE
No syntax highlighting out of the box

### ISSUE THREAD

**Issue by mrichman** [Microsoft/vscode-go#364]
Running vscode 1.2.1 and installed this plugin. My $GOPATH is set correctly. The additional tools installed and I restarted vscode.

Using OS X El Capitan and Go 1.6.

**Comment by ipfans** [comment]
I checked VSC OUTPUT for Go plugins: all plugins works fine, but errors are not highlight correctly.

**Comment by mrichman** [comment]
I accidentally installed this plugin when looking for other Go plugins: https://marketplace.visualstudio.com/items?itemName=ccirello.go-no-syntax-highlight

Works fine now.
