### ISSUE TITLE
waiting for debug protocol on stdin/stdout error

### ISSUE THREAD

**Issue by shouhong** [Microsoft/vscode-go#365]
On Mac, I installed delve with "go get -u github.com/derekparker/delve/cmd/dlv", then created a certificate and codesigned the dlv. Then I launched the debug with "F5" but got below error:
**[ERROR] waiting for debug protocol on stdin/stdout**

**Comment by orloffm** [comment]
https://github.com/Microsoft/vscode-go/issues/321

**Comment by shouhong** [comment]
It seems the reason is my dlv was installed by "go get -u github.com/derekparker/delve/cmd/dlv", not exactly following the manual install steps of https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md. 

The problem was fixed on my machine by below steps:
1. Make sure the $GOPATH value is single-valued, not colon-separated.
2. Delete $GOPATH/src/github.com/derekparker and $GOPATH/bin/dlv
3. mkdir $GOPATH/src/github.com/derekparker && cd $GOPATH/src/github.com/derekparker
4. git clone https://github.com/derekparker/delve.git && cd delve
5. CERT=dlv-cert make install
