### ISSUE TITLE
Line just diapered on [Ctrl + S]

### ISSUE THREAD

**Issue by seemsindie** [Microsoft/vscode-go#368]
Ok, i don't know if this is about this package, but it happened just after i installed it.
So i found the package, and installed dependencies, and restarted the editor(not full, the button restart now). And when i click Ctrl + S the line goes away, but it's perfectly correct line....
I am going to post gif of this, because i don't believe what is happening to me :)

http://imgur.com/ZahFSS2

**Comment by adlangx** [comment]
I just installed the package as well and I can't seem to change the file. No matter what I do the lines get undone immediately. Strange.

**Comment by adlangx** [comment]
OK, I figured out my issue. I think its the gofmt tool combining with a VSCode auto save setting
I get the same if I add a few carriage returns and pause before typing code.
I have the following in my user settings.json

  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 2500,

1000ms or 1500ms was too fast.

**Comment by seemsindie** [comment]
@adlangx That doesn't work for me, still getting deleted... :(

**Comment by lukehoban** [comment]
Yes - this is because of the change to turn `Format on Save` on by default per https://github.com/Microsoft/vscode-go/issues/253.

It is true that `Format on Save` and `Auto Save` interact rather poorly.  Since `Auto Save` is off by default in VS Code, and many Go users expect `Format on Save` to be on by default based on experience in other Go editors, we decided that was the best set of defaults.  There's some discussion of that in issue, and we added this to the README documentation:

> Note: Users may want to consider turning Auto Save on in Visual Studio Code ("files.autoSave": "afterDelay") when using this extension. Many of the Go tools work only on saved files, and error reporting will be more interactive with Auto Save turned on. If you do turn Auto Save on, you may also want to turn format-on-save off ("go.formatOnSave": "false"), so that it is not triggered while typing.

You can turn off Auto Save by removing the `"files.autosave"` setting from your settings, or setting it to `"offf"`.

**Comment by seemsindie** [comment]
Neither of these two solutions works, my line is still getting deleted :)
I tried adding afterDelay and set it to 2500ms, and turning it off, nothing works.

**Comment by ramya-rao-a** [comment]
@seemsindie Do you still have this issue? Can you give an example of a line of code that gets deleted for you? Is it packages that have been imported but not used yet? Or blank lines?

**Comment by joelsinbarba** [comment]
Had this issue today, it seems like the formatting tool deletes all the packages that are **imported** and are **not used**, it's a bit annoying when you are addicted to save changes on every line, but you should not import packages without using it in Go anyways.

**Comment by ramya-rao-a** [comment]
@joelsinbarba You can change the formatting tool being used to gofmt. Just add this line to your user settings:

`"go.formatTool": "gofmt"`

`gofmt` does not remove unused imports where as `goimports` and `goreturns` do

**Comment by color1934** [comment]
If you don't want vs code to change your code. 
Just change user settings like that:
` "go.formatTool": "gofuck"`
