### ISSUE TITLE
Debugger picture in readme broken

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#372]
![image](https://cloud.githubusercontent.com/assets/159209/16509482/1e799870-3ef2-11e6-8c48-df46472f43d2.png)

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode-go/commit/5e6498f66fb7ff0e74c0fd08a3672d7a7b219e09 has fixed this
