### ISSUE TITLE
Unable to use Delve

### ISSUE THREAD

**Issue by seanlindo** [Microsoft/vscode-go#377]
This seems to be a new issue, as I remember this working recently. 

**Vscode Version**: 1.3
**Delve Version**: 0.11.0-alpha
**Go Version**: 1.62

Attempting to hit any breakpoint in Vscode prints the below panic. Has anyone else experienced this? I'm using Gin, if that makes any difference. 

`goroutine 53 [running]:
panic(0x4621800, 0xc820f7d290)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc8211adf90, 0xc8203571c0, 0xfffffffffffffffd, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/threads_darwin.go:112 +0x9c
github.com/derekparker/delve/proc.cacheMemory(0x5bb1c50, 0xc82119d1a0, 0xc8203571c0, 0xfffffffffffffffd, 0x0, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/mem.go:42 +0xf2
github.com/derekparker/delve/proc.(*Variable).loadArrayValues(0xc8200a5060, 0x1)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:938 +0xa6
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8200a5060, 0x1)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:744 +0x939
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820ff4540, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:758 +0x1272
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820ff4380, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:724 +0xd04
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc820ff4380)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:710 +0x2a
github.com/derekparker/delve/proc.(*EvalScope).extractVariableFromEntry(0xc8209f7380, 0xc820eb7ce0, 0x0, 0x0, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:499 +0x98
github.com/derekparker/delve/proc.(*EvalScope).variablesByTag(0xc8209f7380, 0xc800000005, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:1484 +0x174
github.com/derekparker/delve/proc.(*EvalScope).FunctionArguments(0xc8209f7380, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:535 +0x46
github.com/derekparker/delve/service/debugger.(*Debugger).collectBreakpointInformation(0xc820138690, 0xc821206190, 0x0, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:333 +0x631
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc820138690, 0xc8211a77a0, 0x0, 0x0, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:255 +0xa1f
github.com/derekparker/delve/service/rpc.(*RPCServer).Command(0xc82012e960, 0xc8211a77a0, 0xc8211ade50, 0x0, 0x0)
	/private/tmp/delve-20160707-38466-1kgzd6z/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/rpc/server.go:96 +0x3f
reflect.Value.call(0x45cdba0, 0x46c59d8, 0x13, 0x46e5498, 0x4, 0xc820f61ed8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x45cdba0, 0x46c59d8, 0x13, 0xc820f61ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc8204a4040, 0xc8204a4000, 0xc8211b0480, 0xc820eb5d80, 0xc8211a7440, 0x44eb120, 0xc8211a77a0, 0x16, 0x44eb180, 0xc8211ade50, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
	/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d`

**Comment by mattetti** [comment]
```
$ dlv version
Delve Debugger
Version: 0.11.0-alpha
Build: b9b3e4ac03c1033fe6a8866813670fe58e96e0fd
$ go version
go version go1.6.2 darwin/amd64
$ code --version
1.3.0
```

Not seeing this issue here. Have you tried other libraries?

**Comment by seanlindo** [comment]
Will try with no framework and report back.

**Comment by lukehoban** [comment]
That error message indicates a failure in Delve itself.  You'll likely want to open a bug in the Delve repo and include repro steps for investigation.
