### ISSUE TITLE
Add ability to focus terminal & panels

### ISSUE THREAD

**Issue by aaronkavlie-wf** [Microsoft/vscode-go#381]
While there are ways to shift focus from a bottom panel to the editor, there's no apparent keyboard shortcut to shift focus back to the bottom panel, short of toggling it off and back on.

**Comment by ramya-rao-a** [comment]
@aaronkavlie-wf Do you mean the integrated terminal when you say "bottom panel"? If yes, then you can add a keybinding to `workbench.action.terminal.focus` command. Details are on the [vscode blog for the Integrated terminal](https://code.visualstudio.com/docs/editor/integrated-terminal#_key-bindings)

**Comment by aaronkavlie-wf** [comment]
@ramya-rao-a the terminal is one of them, but there's also the notification message panel and the debug console, and maybe others.

I realize that I filed this against the wrong code base though, sorry.

**Comment by ramya-rao-a** [comment]
@aaronkavlie-wf In that case can you open an issue in the repo for [vscode](https://github.com/Microsoft/vscode)?

**Comment by ramya-rao-a** [comment]
@aaronkavlie-wf In the latest VSCode there are more commands around focusing editors/panels that you can add keybindings for

// - workbench.action.focusFirstEditor
// - workbench.action.focusLeftEditor
// - workbench.action.focusPanel
// - workbench.action.focusRightEditor
// - workbench.action.focusSecondEditor
// - workbench.action.focusThirdEditor

Can you give these a try?

**Comment by aaronkavlie-wf** [comment]
@ramya-rao-a thanks, confirmed that the focus panel option does what I expect. I didn't assign a keyboard shortcut, but triggered the action via the cmd-shift-p action list.

I hope they assign a keyboard shortcut for that in a future update; I rarely assign shortcuts by hand as it can be difficult to find good shortcuts that don't conflict with other system or editor shortcuts.
