### ISSUE TITLE
Uncaught Exception:  Error: write EPIPE seen hover and Goto Definition

### ISSUE THREAD

**Issue by mavenugo** [Microsoft/vscode-go#383]
am trying to switch to vscode for my golang development from vim. But this issue is blocking me to make that switch. 

am using the golang extension with vscode ( version 1.3.0 - e724f269ded347b49fcf1657fc576399354e6703 in OSX).

I see these errors in the developer console for every mouse hover on top of a symbol or trying to jump to a definition using `Go to Definition`. Ofcourse. `Go to Definition` isnt working even with all the Golang tools properly installed.

```
[Extension Host] Uncaught Exception:  Error: write EPIPE(anonymous function) @ threadService.ts:214emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
threadService.ts:214 [Extension Host] Error: write EPIPE
    at exports._errnoException (util.js:890:11)
    at WriteWrap.afterWrite (net.js:769:14)(anonymous function) @ threadService.ts:214
emitTwo @ events.js:100
emit @ events.js:185
handleMessage @ internal/child_process.js:718
channel.onread @ internal/child_process.js:444


write EPIPE: Error: write EPIPE
    at exports._errnoException (util.js:890:11)
    at WriteWrap.afterWrite (net.js:769:14)
e.onUnexpectedError @ shell.ts:416
(anonymous function) @ shell.ts:318
e.onUnexpectedError @ errors.ts:73
u @ errors.ts:88
e.onUnexpectedExtHostError @ mainThreadErrors.ts:12
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:269
f @ ipcRemoteCom.ts:226
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
threadService.ts:214

 [Extension Host] Uncaught Exception:  Error: write EPIPE(anonymous function) @ threadService.ts:214
emitTwo @ events.js:100
emit @ events.js:185
handleMessage @ internal/child_process.js:718
channel.onread @ internal/child_process.js:444
```

**Comment by lukehoban** [comment]
Hmm - it's not clear what would be causing this.

Do you see this on multiple different machines?
Do you see this on a very simple project (single main.go file)?
Do you have 'Analysis Tools Missing' in the bottom right corner of your window?
Have you installed `godef`?

**Comment by mavenugo** [comment]
@lukehoban thanks for your response. 

> Do you see this on multiple different machines?

I tried it in only 1 machine.

> Do you see this on a very simple project (single main.go file)?

Yes.

> Do you have 'Analysis Tools Missing' in the bottom right corner of your window?

No.

> Have you installed godef?

Yes.

**Comment by ramya-rao-a** [comment]
@mavenugo Quite a few things have changed in the extension since July, can you try the latest VS Code and the latest Go extension and see if you still have these issues?

**Comment by ramya-rao-a** [comment]
@mavenugo Closing this for now, as we havent heard back from you.
Like I said, quite a few things have changed since July, please give latest VS Code and the latest Go extension a try.

If you still have issues, freel free to comment here, and I can re-open the issue and investigate
