### ISSUE TITLE
How to disable snippets?

### ISSUE THREAD

**Issue by reorx** [Microsoft/vscode-go#385]
I want to disable snippets like `for` or `make`, I've tried to user define snippets with same prefix, and body is just the work, for example:

```
	 "disable for": {
		"prefix": "for",
		"body": ["for"],
		"description": "disable for"
	}
```
but it could only add a new one not replacing the existing one, since VS Code does not support `disabled` attribute for snippets (Atom does), could you please provide an option to let user disable the entire `go.json` snippet file, thus we could copy and modify to get what fit our needs most?

**Comment by ramya-rao-a** [comment]
This issue has been moved to [Microsoft/vscode#10565](https://github.com/Microsoft/vscode/issues/10565)
