### ISSUE TITLE
Rename Symbol doesn't refresh editor view

### ISSUE THREAD

**Issue by prencher** [Microsoft/vscode-go#387]
When using Rename Symbol, the open editor views do not refresh content to reflect the change.

Windows 10, Visual Studio Code 1.3, Go extension 0.6.39.

**Edit**: Since I reported this, it has started working; It seems sporadic. I'm trying to find a reproducible case.

**Comment by ramya-rao-a** [comment]
@prencher Feel free to re-open if you are able to reproduce the bug

**Comment by pradhul-dev** [comment]
I am using Version 1.4.0 in Ubuntu 14.04 , VSCode is not refreshing if I switched over to different branches while working. I need to close the whole editor and restart it again. Is this an expected behaviour? I would really like it if the files would've been refreshed to sync with my git repo.

**Comment by ramya-rao-a** [comment]
Hey @pradhul-dev, this repo is for the Go extension for vscode. Can you log your issue in the repo for [vscode](https://github.com/Microsoft/vscode)?
