### ISSUE TITLE
Search relevance in 'Add import'

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#390]
Obviously `os` should be the first output here:

![image](https://cloud.githubusercontent.com/assets/159209/16785612/d05abd4e-4843-11e6-8ab1-5a81fb78c69b.png)

In this case `io` is literally at the end

![image](https://cloud.githubusercontent.com/assets/159209/16785616/da19125e-4843-11e6-84e0-e163b30489c8.png)
![image](https://cloud.githubusercontent.com/assets/159209/16785621/e0357ea2-4843-11e6-8be2-3adbb37a5d50.png)

**Comment by ahmetalpbalkan** [comment]
This is still very much an issue.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#18003
