### ISSUE TITLE
Method tooltip shows only 2 lines of godoc

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#391]
if I type `ioutil.TempDir(` the tooltip that comes up is only showing 2 lines of the godoc:

![image](https://cloud.githubusercontent.com/assets/159209/16785796/e94825a2-4844-11e6-842c-f17e13161e31.png)

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#10593
