### ISSUE TITLE
Formatting silently overwrites changes

### ISSUE THREAD

**Issue by aaronkavlie-wf** [Microsoft/vscode-go#392]
This plugin's formatting & error checking (at least with `formatOnSave` on) runs in the background without blocking the editor. This is unlike other editors I've used with Go integration, like Atom. This seemed like an advantage at first, but it tends to silently overwrite changes.
### Steps to reproduce
1. Make some changes in a Go project, and save with `"go.formatOnSave": true`. (The delay after save tends to be sporadic for me -- once completed the first time, subsequent saves in a session are completed much faster.)
2. Immediately start editing some other code.
3. After `gofmt` etc. completes, observe that any changes you made after saving are gone.

Relevant config:

``` json
    "go.formatTool": "goimports",
    "go.formatOnSave": true
```

**Comment by azazi-sa** [comment]
+1

**Comment by ylns1314** [comment]
There is a walkaround:
    "go.formatOnSave": false,
    "editor.formatOnSave": true,

**Comment by ramya-rao-a** [comment]
With the changes to the format on save feature in the latest release of this extension (0.6.70), you should no longer have this issue
