### ISSUE TITLE
when go to decalre file error info

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-go#393]
_From @luohoufu on July 13, 2016 2:29_

- VSCode Version: 1.3.1
- OS Version: Debian 3.10 X86_64

Steps to Reproduce:
golang extention installed
1. open one .go file and click object method to open the declare file。
2. get a tip on top: Error: Error: Illegal value for `line`。

_Copied from original issue: Microsoft/vscode#9164_

**Comment by lukehoban** [comment]
@luohoufu - Can you provide a more detailed repro?

**Comment by lukehoban** [comment]
Closing for now - please reopen if you have more details.
