### ISSUE TITLE
feedback: getting new users setup

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#394]
Hello all. I wanted to share with you my experience getting a few gophers setup during GopherCon.

On the first day, a Googler who's leading the Guru project showed his work and kept on mentioning VS Code has a first class IDE integrating with Guru (Guru is an official Go tool that allows features such as finding all references/usages of a symbol, find what interfaces a value/type implements, advance search, jump to definition etc...)

A decent amount of developers were interested in knowing more about Code and wanted to get setup. I was scheduled to record a remote meetup on the topic but the conf connection wasn't good enough for us to record the event. That said, you can read [here](https://github.com/remotemeetup/go/issues/9#issuecomment-231481045) some of the questions I received.

Today was the last day of GopherCon and the conference turns into a big hack day with multiple tracks. Some tracks are organized by speakers (GoBot, Go Team, go-vim, Docker..) and some are self organized by the community. A group of people decided to come together and setup/learn VS Code.

Before I mention what I think this project should improve, I'd like to say that I'm very thankful to all the people who've been putting so much energy in both Code and vscode-go. I use Code daily thanks to you!
## Go extension setup is incomplete.

This is the number issue I've seen and it's probably more of a Code issue than an extension issue. None of the users who installed Code then installed the extension realized that they needed to go to the GitHub repo, find the readme and copy/paste the settings to turn on the various features.
Some developers were barely learning how to code and all a sudden they had to figure out what was their Go path, what features to turn on/off etc...

Suggestions:
- inject some default settings into the user settings
- If that's not possible, have some default options on by default
- use the users's $GOPATH env variable on mac by default
## "Missing analysis tools" warning is too hard to see

Suggestion:
- also add a popup error like when your gopath isn't set
## What can I do with VS Code?

Users don't know the potential of Code/Go and don't know where to get started

Suggestion:
- better link to the GitHib readme
- small gifs for each feature. This is something the community can contribute to and add to the README. VS Code for Go does a LOT, but most features aren't advertised.
- A good FAQ

Once the users are setup, they seemed to really enjoy using Code for Go \0/

/cc @lukehoban @egamma

**Comment by egamma** [comment]
@mattetti thanks for the feedback. 

Adding @kieferrm, @seanmcbreen, @chrisdias

**Comment by mattetti** [comment]
Is there a way to register default config entries so users can be started right away? I couldn't find anything in the extension documentation.

**Comment by egamma** [comment]
@mattetti 

>Is there a way to register default config entries so users can be started right away? 

What would be an example for such an entry?

**Comment by mattetti** [comment]
@egamma Ideally, we would add the following settings to the user's settings.json file:

```
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintTool": "golint",
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "go.gocodeAutoBuild": false
}
```

All users I onboarded expected to be able to edit some sort of settings file. Having to find the README to see what settings can be set is quite challenging. I didn't even know we could switch the default lint tool until I dug into the code. 

I do realize that if each extension starts adding settings it might get messy but at this point, I will take a bit messy vs confusing.

**Comment by egamma** [comment]
@mattetti I see, you want to add these settings for discoverability, the default values of these setting are already defined as you list them above. 

Adding a setting to the user's settings file has the draw back that you can no longer easily change defaults or add new ones inside the extension. 

We plan to improve the discoverability of an extension's contribution in general. One idea we want to try is to show the contributions in the details view of an extension.  This would show the settings an extension contributes. 

If this isn't good enough then we can provide some 1st run guidance, e.g., show a message box on first run that invites the user to configer the go settings.

**Comment by mattetti** [comment]
@egamma I see what you mean. Honestly, if there was a simple way to access
a README/setup guide/help after installing an extension it would make a big
difference. I have ~5 extensions I use often and I probably doesn't know
most of the available features/settings. For instance, I didn't realize the
Python extension required installing some extra libs by hand. Having to
have to go to the marketplace or GitHub to find more info is quite
cumbersome. (And in the case of the Go extension, you have to go to the
GitHub's readme)

**Comment by mattetti** [comment]
My bad, I didn't realize that if you were to click on the extension name in the extension list, it does load the README. We might want to open that pane automatically or offering to open it after installing a plugin.

**Comment by egamma** [comment]
>We might want to open that pane automatically or offering to open it after installing a plugin.

Well we already show the pane before you the install the extension.

**Comment by mattetti** [comment]
@egamma I setup a few people last night at our local Go beginner night and none saw the README.
The reason why was that they clicked on install without clicking on the extension card (also, what's up with this (potentially) fake go 0.0.1 extension).
The installation went through, asked to restart, they never saw the README.

Note also that the README gets loaded from github directly, which is great but if you are on a half decent wifi connection, the content will load in a couple seconds (the markdown is also rendered locally) and there aren't any visual indications that the content is loading. You only see the header.

**Comment by egamma** [comment]
@mattetti thanks for the feedback, we will revisit this topic.

**Comment by ramya-rao-a** [comment]
@mattetti I wanted to revisit a few of the topics here based on the updates we have done for the extension in the past few months

**Missing GOPATH**
In the next update (0.6.48), if GOPATH is not set, a info box will pop

![image](https://cloud.githubusercontent.com/assets/16890566/19909344/7bab07aa-a044-11e6-99a9-a543fd4e8547.png)

Clicking on "Set GOPATH in Workspace Settings" will open the workspace settings where once you can set the gopath.

About your comment on GOPATH in Mac

>use the users's $GOPATH env variable on mac by default

I believe we already do this. Have you found it to behave otherwise?

**Default Settings**
The default values you mention in https://github.com/Microsoft/vscode-go/issues/394#issuecomment-240182136 are already the default values. 
One good thing in the upcoming VS Code 1.7 release, is that in the default settings file, all settings are collapsed, thus making it less overwhelming to first timers, who wanted to check out what settings matter to the Go extension

![image](https://cloud.githubusercontent.com/assets/16890566/19909477/29dd194e-a045-11e6-865e-3d6bd299f70f.png)


**Missing Analysis Tools**
I totally agree that this is hard to see. I'd prefer a msg box just like for GOPATH mentioned above with an extra option of "Don't ask again" just in case if anyone explicitly does NOT want to install one of the tools. The individual features already have their own msg boxes if the dependent tool is not found.
Thoughts?

**Discoverability**
Created #596 to track the suggestion about adding gifs for features for better discoverability.
Created https://github.com/Microsoft/vscode/issues/14826 to track the showing of README when user clicks on the Install button.

Have I missed anything? :)

**Comment by mattetti** [comment]
This is awesome, note also that the next version of go (1.8) will use a
default gopath.
The changelogs have been super useful, and I wish I had a bit more time to
provide a few additional features (list of interfaces implemented by a
strict or value would be neat and already supported by Guru).
I am all having issues when using cgo on some files and the jump to
declaration being broken. I would need to set some time aside to look into
that.

**Comment by ramya-rao-a** [comment]
In the extensions view, you can now see more details about the extension

![image](https://cloud.githubusercontent.com/assets/16890566/21998398/5ac982f6-dbe9-11e6-9898-b4ea2398442c.png)

By default, you get read the same README that is part of the repo for the Go extension
The second tab "Contributions" lists out all the settings and commands that are shipped by the Go extension.
Changelog of course shows you the changelog.

Closing this issue for now, as most of the concerns have been addressed and separate issues have been created for the remaining ones.
