### ISSUE TITLE
Code folding or collapse doesn't work properly if there's a multi-line flush left string in the function

### ISSUE THREAD

**Issue by billgraziano** [Microsoft/vscode-go#395]
I'm not sure if this is a VSCODE issue or an issue with this extension. 

If I collapse a function that has a multi-line string left justified delimited with back-ticks it only collapses down into the string and not the entire function.  The string in question is a SQL statement and it collapses down to the FROM clause.

I'm using the latest VSCODE and running on Windows.

This doesn't collapse properly:

```
func t() string {
	bigstring := `
this
IsInteractive
my
test

	`
	return "x"
}
```

But this does:

```
func t() string {
	bigstring := `
	this
	IsInteractive
	my
	test

	`
	return "x"
}

```

**Comment by billgraziano** [comment]
FYI - I also notice that it tries to use Intellisense inside the string.

**Comment by lukehoban** [comment]
The same thing happens for JS using template literals with backtick, so I think this is an issue with VS Code.  Can you reopen this in the vscode repo?

**Comment by billgraziano** [comment]
For future reference the VS Code issue is here: https://github.com/Microsoft/vscode/issues/3422
