### ISSUE TITLE
Go current gopath display info :Current GOPATH:undefined

### ISSUE THREAD

**Issue by gatspy** [Microsoft/vscode-go#397]
after installing this plugin, Go current gopath display info :Current GOPATH:undefined
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Hello/Home/Work/golang/vender:/Users/Hello/Home/Work/golang/project"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
"""

tools command in gopath bin folder as follow:
go-outline
go-symbols
gocode
godef
golint
gopkgs
gore
gorename
goreturns
guru
#

**Comment by lukehoban** [comment]
That indicates that you don't have a GOPATH set in the environment in which VS Code was launched.  If you launch it with `code .`  from a shell with the environment you list above, you should see the right GOPATH.  If you launch directly from an OS launcher, you will need to ensure that your GOPATH is configured in your default environment.
