### ISSUE TITLE
go.gopath not working when set in workspace settings

### ISSUE THREAD

**Issue by erica-zhou** [Microsoft/vscode-go#398]
when i run `go run `, show error : `$GOPATH not set`,but i set it in workspace settings
I already quit vsCode when i open the project. 
os : osx 10.11
vsCode:1.3.1
i open project by `code .`

**Comment by lukehoban** [comment]
What do you men by `go run`?

I cannot reproduce this in any configuration.  Can you provide more details?

Note that you can use the "go.gopath" setting in your Preferences > User Settings to override what's available from your environment.

Please reopen if you have more details.

**Comment by erica-zhou** [comment]
I don't remember reproduce step clearly. there are another  case:

**Comment by erica-zhou** [comment]
I don't remember reproduce step clearly. there are another  case:

1. set **gopath1**  for **project1**  in  project1's workspace settings
1. set **gopath2**  for **project2**  in  project3's workspace settings
1. in bash ,unset GOPAH
1. open **project1**  by `code /path/to/project1`
1. open **project2**  by `code /path/to/project2`

i expect the GOPATH value in project1 is "**gopath1**" and  GOPATH value in project2 is "**gopath2**",but  the GOPATH value in project1 and project2 are both "**gopath1**"

**Comment by ramya-rao-a** [comment]
@erica-zhou Do you still see this issue?

I followed your steps and I get the right (different) GOPATH for both the projects
