### ISSUE TITLE
Support running tests without the -v flags

### ISSUE THREAD

**Issue by fsouza** [Microsoft/vscode-go#401]
Sometimes, specially when tests are failing, it's useful to omit the -v flag to prevent noise. It would be nice to make the flag optional or let users include `-v` in extra flags.

**Comment by lukehoban** [comment]
Good idea.  PR definitely welcomed.

**Comment by ramya-rao-a** [comment]
@lukehoban  would a setting to toggle verbosity suffice or would a testFlags setting just like build/format/lint/vet flags be preferred?

**Comment by lukehoban** [comment]
I think flags would be best.  Will have to make a call about how to handle the current `-v` and `-timeout` flags that are provided by default (the latter based on a separate settings).  Perhaps leave timeout as is and make `-v` the default for a new `testFlags` setting?

**Comment by tsandall** [comment]
First off, thanks for making VS Code my favourite editor for Go!

It would be really nice to see this resolved. As it stands, I have to remove the verbose flag in my copy of the extension. The problem with this is that it gets stomped every time I upgrade.

I see there's a PR resolving this, is there any chance of getting it merged?

**Comment by ramya-rao-a** [comment]
@tsandall I'd love to get this PR merged as well.

Currently, the `go.buildFlags` are used for running tests. Other than `-v` do you foresee the need to change/add other flags while running `go test` which are different from `go.buildflags`?

The current bone of contention is whether there should be a separate setting to control the verbosity of `go test`  or we should have a setting for test flags as a whole and stop using the build flags

**Comment by tsandall** [comment]
I don't have any other use cases for tweaking the flags right now.

That being said, whenever I have to run tests with different flags, I find myself dropping down to the command line because modifying settings.json for a one-off run is not intuitive.

**Comment by calrsom** [comment]
I would like to see the `-short` flag available.  That said, it would be really nice to bind this variation to a keyboard shortcut.  I already have a set of Ctrl+U chords for the various unit test scopes, and this would be a nice addition.  I would probably use Test Package short the most.

**Comment by ramya-rao-a** [comment]
The latest update (0.6.53) has the option to add testflags applicable to all tests as well as key bindings to run any of the 3 test commands with any flags.

From the ChangeLog:

   * A new setting `go.testFlags` that can be used to run tests. If null, `go.buildFlags` will be used. [PR 482](https://github.com/Microsoft/vscode-go/pull/482)
    * Customize flags for each of the test command by using different keybindings. [PR 482](https://github.com/Microsoft/vscode-go/pull/482). In the below example, `ctrl+shift+t` is bound to run the tests in current file with `-short` flag. The commands here can be `go.test.package`, `go.test.file` or `go.test.cursor`.
        ```json
        {
            "key": "ctrl+shift+t",
            "command": "go.test.file",
            "args": {
                "flags": ["-short"]
            },
            "when": "editorTextFocus"
        }
        ```
