### ISSUE TITLE
Updated to 0.6.41, can no longer debug

### ISSUE THREAD

**Issue by CarlMCook** [Microsoft/vscode-go#402]
In Visual Studio Code I was advised there was an update to Go, updated, then debug stopped working.  When starting debugging my code I only get one line in the debug console:
API server listening at: 127.0.0.1:2345
Nothing else happens.
Thank you.
Carl

**Comment by reekdeb** [comment]
+1

**Comment by ITSecMedia** [comment]
+1 Same here

**Comment by mantzas** [comment]
+1

**Comment by lukehoban** [comment]
Sorry about that. What OS and VSCode version are folks using who are seeing this?

**Comment by mantzas** [comment]
No worries. windows 10 and vscode 1.3.1. ;)

**Comment by lukehoban** [comment]
I've pushed a 0.6.42 update with a fix for this.

If anyone is still seeing issues after upgrading to 0.6.42, please provide details on Delve version, and also  whether you are seeing "API server listening at: 127.0.0.1:2345" in the console.

**Comment by mantzas** [comment]
Windows 10 and Lubuntu 16.04 are working again. Thanks, great response

**Comment by reekdeb** [comment]
Windows 8.1 x64. Delve latest 0.11.0-alpha. Working again. Thanks. :)

**Comment by ITSecMedia** [comment]
Looks fine here again too. Windows x64  / VSCode 1.3.1

**Comment by CarlMCook** [comment]
Thank you.  I can report it is working.  I will close the issue.
