### ISSUE TITLE
Where are release notes / changelog?

### ISSUE THREAD

**Issue by AlekSi** [Microsoft/vscode-go#403]
http://keepachangelog.com

**Comment by mattetti** [comment]
I think that currently, the only way to find out about changes is to look at the git history.

**Comment by ramya-rao-a** [comment]
@mattetti Not anymore :)

https://github.com/Microsoft/vscode-go/wiki/Release-Notes

**Comment by roblourens** [comment]
@ramya-rao-a If you keep the notes in changelog.md, it will show up in the extensions view in vscode 1.6+. You can see how this looks for the Chrome extension.
