### ISSUE TITLE
suggest unexpected completion items including special character.

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-go#405]
Moved from https://github.com/Microsoft/vscode/issues/9649:
- Mac OSX
- VS Code 1.3.1
- vscode-go 0.6.39

With displaying completion widget, when inputting a character VSCode cannot 
correctly filter completion items including special characters (`$`, `_`, `/` and so on).

![vscode-js](https://cloud.githubusercontent.com/assets/1453749/17075967/5cacc914-50e0-11e6-835c-921e4780fd3b.png)

I think that special character is not equal to upper case for matching camel case.
In this case, VSCode should suggest `ArrayBufferConstructor` and `abc`.
(And I cannot understand why `a$b_c` isn't suggested.)

In golang this issue is particularly problematic, since most of package name is separated `/` (e.g. `io/ioutil`, `internal/golang.org/x/net/http2/hpack`).
[Search relevance in 'Add import' · Issue #390 · Microsoft/vscode-go](https://github.com/Microsoft/vscode-go/issues/390)

---

When filtering completion items, VSCode seems to consider the keyword including special characters camel case.
[vscode/filters.ts at 35e5c9af12045c89790be81d51a742dd7c2a30c4 · Microsoft/vscode](https://github.com/Microsoft/vscode/blob/35e5c9af12045c89790be81d51a742dd7c2a30c4/src/vs/base/common/filters.ts#L168)

Is this  bug?

**Comment by ramya-rao-a** [comment]
@kieferrm This is not related to the Go extension, any particular reason, it was moved here?

**Comment by kieferrm** [comment]
@ramya-rao-a That is a mistake.

**Comment by ramya-rao-a** [comment]
Thanks, I am closing this one and re-opening the original issue in vs code
