### ISSUE TITLE
Autocomplete Should Complete From Packages Which Haven't Been Imported Yet

### ISSUE THREAD

**Issue by a-h** [Microsoft/vscode-go#407]
Just thinking how vscode-go could be even more awesome for me.

I sometimes find myself hunting through APIs. For example...

- I know that in the `fmt` package, there is a function called `Prints` which formats to a string, but I can't remember the parameters.
- So, I type `fmt.Prints(`, but I don't see any autocompletion. This is because `fmt` hasn't been imported yet.
- I hit save, but it still doesn't import the package. I wonder why...
- I put a value into the method's parameters and hit save, but it still doesn't add the import automatically.
- I google the docs for the `fmt` package and realise that the function is actually called `Sprint` not `Prints`, so I fix it and hit save... the plugin now imports `fmt` and I can browse the parameters and return value in the popup.

I wanted to use vscode-go to help me browse the `fmt` package and choose the correct method, but it's not helping me to do that. Note how when I've typed `fmt.` I can't see anything...

![autocomplete](https://cloud.githubusercontent.com/assets/1029947/17145792/a86c5cb4-5353-11e6-9047-4f7848fa4c2d.gif)

It would be better if:

- I type `fmt.` and a list of possible functions and their parent packages appears. `fmt` is already in my path (but not listed in my imports), so all the methods from `fmt` are listed. I notice `Prints` isn't in the list.
- I notice that `fmt.Sprint` is there, I hit the down arrow a couple of times to choose it and press the open bracket. I'm in the parameters list, and I can see the popup detailing the parameters the method accepts.
- I hit `Save` and the `import` statement is updated as usual.

Does anyone else think this would be good?

**Comment by leaxoy** [comment]
+1

**Comment by apognu** [comment]
This is an issue most editors I've used suffer from. It would be amazing is this could be implemented.

**Comment by a-h** [comment]
Visual Studio (not VS Code) solves this problem in C# by adding a blue 'tag' to a type that can be imported, as well as by providing autocomplete for namespaces.

Hitting the blue tag provides a selection of assemblies which contain a MailMessage type, when one is selected then a using statement is added (similar to importing a package in Go).

Here's what it looks like in LinqPad:

![visualstudio](https://cloud.githubusercontent.com/assets/1029947/17212669/812ed2a0-54c8-11e6-8b23-c2c635f0dda4.gif)

(In the screencast, I've used the mouse to click on the little bar instead of the keyboard shortcut to make it clearer.)

**Comment by ramya-rao-a** [comment]
We have a quickfix (Ctrl+.) on un-imported packages which will import the package.

If you have `files:autoSave` and `go.buildOnSave`  turned on and `go.formatOnSave` turned off then you get the below experience:
- Type `fmt` in a go file where `fmt` is not imported
- autosave kicks in which triggers build which will give red squiggly line on the `fmt` you just typed
- trigger quickfix (Ctrl + .) and codeaction pops with an option to import fmt.
- Choose the code action to import fmt, press . to get intellisense on all the methods fmt has to offer

If you don't like autoSave, then you can still get this feature by saving the file after typing `fmt`. Just keep `go.buildOnSave` on and `go.formatOnSave` off

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest version of the Go extension : 0.6.44

You need to set `go.autocompleteUnimportedPackages` to true to enable this feature.

Do give it a try and give feedback

We will turn it on by default in the next update

**Comment by a-h** [comment]
@ramya-rao-a - I'd just like to say thanks for implementing this feature, I've really been enjoying it!

**Comment by ramya-rao-a** [comment]
@a-h Thanks for bringing up the feature request in the first place. There has been a lot of positive feedback around this!
