### ISSUE TITLE
On save, infinite formatting + build

### ISSUE THREAD

**Issue by lunchboxsuhi** [Microsoft/vscode-go#409]
When I save a GO project It seems to be changing the project constantly from 4 spaces into 4 tabs. It builds the project and triggers a reformat which in turn triggers a re-build...

this will keep happening until I focus the OUTPUT window with the GO as the output selection. which then shows that the tools have all been run more than once. example

![image](https://cloud.githubusercontent.com/assets/10443153/17181496/5bbed766-53ee-11e6-9532-021aebf8c27d.png)

this is all triggered on 1 save... which freezes vsCode (until I click on the output window this will run the loop)

any suggestions ? possible set-up issues? also notice that the current build is failing? does that have to do with this issue?

**Comment by lunchboxsuhi** [comment]
after setting go.formatOnSave: false in vsCode user settings it no longer goes in the infinite loop while everything else is still set to true (build,lint,vet) this has something to do with the format on save functionality or perhaps just my vsCode setup?

**Comment by ramya-rao-a** [comment]
@lunchboxsuhi this is definitely a formatting issue.

Can you share your user and workspace settings and list of extensions you have installed?

**Comment by ramya-rao-a** [comment]
@lunchboxsuhi Do you still have this issue?
We have had others who had similar infinite save+edit+save+edit problem. Turns out there was another extension interfering and causing the problem.

If you still have this problem, can you disable all other extensions to see if any of them have been causing this?

**Comment by lunchboxsuhi** [comment]
not sure what was the issue but after a re-install and update everything was fixed. Sorry for the massive delay in responding.

**Comment by ramya-rao-a** [comment]
no problem @lunchboxsuhi, glad that you are unblocked.
Happy Coding!
