### ISSUE TITLE
Goreturns / goimports no longer work correctly for vendor/ packages

### ISSUE THREAD

**Issue by Velds** [Microsoft/vscode-go#411]
**vscode-go** 0.6.42
**vscode** 1.3.1

Every time I saved the file, vscode-go used to call the go.formatTool (which used to be Goimports), which would update my file and add imports and such.  Specifically, packages in the vendor/ directory would be imported.

As of the latest vscode-go version, I'm not seeing any imports for vendor/ packages at all.  Setting go.formatTool to either goreturns or goimports makes no difference.  Imports from the standard lib, and also from any other packages in /src/ still works perfectly.

Adding the imports manually works fine, so if it's me making a mistake somewhere I can't see it.

vscode-go output on save:

![screen shot 2016-07-28 at 4 48 10 pm](https://cloud.githubusercontent.com/assets/7088852/17203473/1a788c5c-54e3-11e6-9165-feba7b00c589.png)

Please advise!

**Comment by josedepaz** [comment]
**vscode-go** 0.6.42
**vscode** 1.3.1

I have the same problem, and if you are looking for goreturns in sourcegraph you can find a **404** code for the repository.

Thank's @lukehoban for the plugin.

**Comment by ramya-rao-a** [comment]
@Velds @josedepaz Do you still see this issue?
I am able to get imports from the vendor directory using both `goimports` and `goreturns`

**Comment by josedepaz** [comment]
I already no, thank you @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Closing this issue, as there has been no more updates on if this is still a problem. @Velds feel free to re-open this if you are still having problems with your imports
