### ISSUE TITLE
Debug keyboard shortcut (F10) colision

### ISSUE THREAD

**Issue by typekpb** [Microsoft/vscode-go#414]
Env:
* RHEL 7.2
* vscode: 1.3.1
* Go ext: 0.6.42

I have `go` file holding some warnings, namely `exported ... should have comment ... or be unexported`

Once debugging and standing on the breakpoint I'd like to `Step Over (F10)`. However if I push `F10` it rather gains focus and shows the warning than stepping over. This is quite irritating as I have to use mouse in debugging in the situation like this.

**Comment by lukehoban** [comment]
This is something that I think would need to be addressed in https://github.com/Microsoft/vscode.  I'd suggest moving this issue over there.  I believe all the keybindings here are VS Code defaults.  (`vscode-go` doesn't define any keybindings itself).
