### ISSUE TITLE
Incorrect highlightning of closing brace

### ISSUE THREAD

**Issue by syniuhin** [Microsoft/vscode-go#415]
Hi,

I've encountered a bug while using VSCode for golang - when you're in a block of code and have `'}'` literal inside it's matched against opening curly brace for this block of code.
For instance:

```
if (true) {
    s := '}'
}
```

highlights incorrectly:
![vscode_bug](https://cloud.githubusercontent.com/assets/6153943/17362111/7b1dbeba-596b-11e6-8081-402aa8a636c4.png)

while the real closing bracket is not highlighted properly:
![vscode_bug1](https://cloud.githubusercontent.com/assets/6153943/17362209/f565eeae-596b-11e6-95c5-680951283940.png)

which stacks throughout all the hierarchy and is really confusing.

The same applies for brackets and parentheses.

**Comment by ramya-rao-a** [comment]
Another case:

![image](https://cloud.githubusercontent.com/assets/16890566/19874286/45317998-9f81-11e6-9619-8cb85c257289.png)


This doesn't happen when the bracket is inside double quotes or back ticks. Only happens with single quotes

**Comment by ramya-rao-a** [comment]
@aeschli Any pointers on how we can fix this?

**Comment by aeschli** [comment]
@ramya-rao-a The bracket pair matching code looks at the scopes and ignores brackets in strings, regexes and comments. Unfortunately the go grammar seems to treat single quoted characters as none of there (constant.other.rune.go). 
One way to fix this would be to make a request to the grammar authors (https://github.com/atom/language-go) to also mark it as a string.
Alternatively we would need a way to configure which scopes should be excluded from a bracket match.
@alexandrudima Alex is the author of the feature. Alex, any other idea?

**Comment by alexandrudima** [comment]
I'd recommend for the go grammar to align with other grammars and emit a token containing "string" in its scopes for `'['`... We can ofcourse make it configurable, but IMHO that looks like it doesn't have a syntactical purpose -- i.e. it looks to me like a character / string constant...

**Comment by ramya-rao-a** [comment]
@syniuhin I don't see this happening in the latest VS Code.
Must have gotten fixed somewhere along the line.
