### ISSUE TITLE
Rename symbol doesn't work

### ISSUE THREAD

**Issue by narqo** [Microsoft/vscode-go#416]
VSCode version: 1.4.0 (MacOS 10.11)
vscode-go version: 0.6.42

GOROOT: `/usr/local/opt/go/libexec`
GOPATH: `/Users/varankinv/Workspace/golang`

Every time I try to rename a symbol I got an error:

> Cannot rename due to errors: /usr/local/opt/go/libexec/src/runtime/internal/sys/arch_arm64.go:8:2: TheChar redeclared in this block...

To be noted: the error changes if unset `GOROOT` env variable, but the rename functionality doesn't work.

I'd like to add more debug information but can't find a way to grab it somewhere.

**Comment by honzajde** [comment]
> I'd like to add more debug information but can't find a way to grab it somewhere.

I have similar issue. I don't see any errors. F2 rename does not work (looks like it hangs up). Also find references shows empty pane.
I am on clean installation of Windows 7 (all required updates installed). 
I have tried to uninstall and reinstall go extension - it didn't help...

VSCode version: 1.4.0 (Win 7)
vscode-go version: 0.6.42.

**Comment by Scratch-net** [comment]
In my case on Windows 10 F2 rename does it's job but the progress bar on the top keeps spinning infinitely.

VSCode version: 1.4.0 (Win 7, 32bit)
vscode-go version: 0.6.42.

go 1.7 (same was on go 1.6.3)

**Comment by lukehoban** [comment]
I believe this is the same as https://github.com/Microsoft/vscode-go/issues/431 which is fixed now.

**Comment by honzajde** [comment]
Fixed in my case. THX
Only that it now takes 15 seconds F2 or Shift+F12 on very small project. When I repeat the same action on the same type subsequently it takes the same time.
