### ISSUE TITLE
Debugger Hangs on OSX with no messaging

### ISSUE THREAD

**Issue by swimorsink** [Microsoft/vscode-go#417]
I saw a couple of other bugs related to this, but all have been closed, so I figured I'd start a new thread (feel free to mark as dupe).

I'm running El Capitan with VS Code 1.40 and the extension version 0.6.42

I installed Delve via Homebrew. Debugging works from the command line.

When I launch the debugger within VsCode, it just sits there. No error messages, nothing.

This happens on any go program, even simple Hello Worlds.

I tried to download the source code to debug, but same thing. I can't get my go instance to connect to the debug adapter instance. Again, it just sits there.

**Comment by sl1pm4t** [comment]
I was having this same problem but solved it by manually building the latest delve code.

**Comment by spacewrangler** [comment]
I also had this issue and was able to fix by getting the latest:

brew uninstall go-delve/delve/delve
brew install go-delve/delve/delve --HEAD

**Comment by swimorsink** [comment]
Worked for me. Thanks @spacewrangler

**Comment by vasu1124** [comment]
+1 
I recommend this to be documented in the top level. drove me crazy till I found this hint ...
