### ISSUE TITLE
Difference between goimports and goreturns?

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode-go#418]
goimports and goreturns are duplicated.
Can we merge goreturns to goimports?

**Comment by mattetti** [comment]
`goreturns` and `goimports` are two different tools that behave differently. VSCode lets you pick the one you want to use. Note also that these tools aren't maintained by the people maintaining VSCode.

If my comment makes sense, please close this issue.

**Comment by ramya-rao-a** [comment]
@leaxoy  This [incomplete list of go tools](http://dominik.honnef.co/posts/2014/12/go-tools/) gives you a good idea of `gofmt` vs `goimports` vs `goreturns`

Like @mattetti said, the user gets to choose which tool they want to use.
