### ISSUE TITLE
Go to definition silently fails on Mac OS X 

### ISSUE THREAD

**Issue by alexbrand** [Microsoft/vscode-go#419]
Is there a place where I can look at output coming from the extension? I opened up the Output pane but nothing shows up when I do a "Go to definition". Wondering if it's a misconfiguration on my end, or an actual issue with the extension.

**Comment by egamma** [comment]
Please try `Help>Open Toggle Tools`.

**Comment by alexbrand** [comment]
Hmm, nothing showing up in the console. I have found that go to definition works in the same file, but not across files.

**Comment by LYY** [comment]
I also have same problem. I use mac osx with go 1.6.2, vscode can't find references and can't goto definition.

I tested the tools, find out when I use godef from go1.5.2 , it works fine.

**Comment by lukehoban** [comment]
Does anyone have a repro they can share?  Does this happen for everything?  Does this happen in a simple app in it's own GOPATH?

**Comment by alexjomin** [comment]
Same here since I move to 1.7, but `go get -u github.com/rogpeppe/godef` did the trick !

**Comment by liggitt** [comment]
I can reproduce for some stdlib structs

golang: 1.6
OS: osx 10.11.6
vscode: 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27)
vscode-go: 0.6.43

```
# environment
env | grep GO
GOROOT=/Users/jliggitt/.gvm/gos/go1.6
GOPATH=/Users/jliggitt/go

# installed all helper tools successfully
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v github.com/golang/lint/golint
go get -u -v github.com/lukehoban/go-outline
go get -u -v sourcegraph.com/sqs/goreturns
go get -u -v golang.org/x/tools/cmd/gorename
go get -u -v github.com/tpng/gopkgs
go get -u -v github.com/newhook/go-symbols
go get -u -v golang.org/x/tools/cmd/guru

# get testcase repo
go get github.com/liggitt/vscode-godef-testcase
# open vscode
code $GOPATH/src/github.com/liggitt/vscode-godef-testcase
```

things that work:
* format on save
* goimports
* autocomplete of the x509 struct names and functions
* go to definition finds the definition of `X` in test2.go
* go to definition of fmt.Println

things that don't work:
* go to definition on `x509.Certificate{}`

I have no workspace or user settings

**Comment by liggitt** [comment]
looks like an error with stdlib packages containing cgo files...

```
$ godef -t -i -f test2.go -o 100 < test2.go -debug
2016/09/27 00:39:44 exprType tuple:false pkg: *ast.SelectorExpr x509.Certificate [
2016/09/27 00:39:44 exprType tuple:false pkg: *ast.Ident x509 [
2016/09/27 00:39:44 exprType tuple:false pkg: *ast.ImportSpec "crypto/x509" [
2016/09/27 00:39:44 ] -> 0x0, Type{package "" *ast.ImportSpec "crypto/x509"}
2016/09/27 00:39:44 ] -> 0xc8200dc730, Type{package "" *ast.ImportSpec "crypto/x509"}
2016/09/27 00:39:44 member Type{package "" *ast.ImportSpec "crypto/x509"} 'Certificate' {
2016/09/27 00:39:44 	/Users/jliggitt/.gvm/gos/go1.6/src/crypto/x509/root_cgo_darwin.go:63:8: cannot find identifier for package "C": cannot find package "C" in any of:
	/Users/jliggitt/.gvm/gos/go1.6/src/vendor/C (vendor tree)
	/Users/jliggitt/.gvm/gos/go1.6/src/C (from $GOROOT)
	/Users/jliggitt/go/src/C (from $GOPATH)
2016/09/27 00:39:44 } -> <nil>
2016/09/27 00:39:44 ] -> 0x0, Type{bad "" <nil> }
godef: no declaration found for x509.Certificate
```

**Comment by ramya-rao-a** [comment]
In one of the recent updates, we provide an option to use `gogetdoc` for the Goto/Peek Definition, Hover and Signature Help features.

Until the upstream bug with `godef` is solved, you can set `"go.docsTool": "gogetdoc"` in your settings to make use of `gogetdoc` instead of `godef`.
