### ISSUE TITLE
Intellisense in go does not work - creates high CPU go process

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-go#421]
_From @ericoff on August 9, 2016 23:48_

- VSCode Version: 1.4.0
- OS Version: 10.12 Beta (16A270f)

Steps to Reproduce:

1. In any context where intellisense should pop-up start typing the name of any existing function
2. Notice intellisense does not show
3. Press Ctrl-Space - a small window pops up that reads "Loading..."
4. Check activity monitor and a process named `go` will be consuming high CPU. No intellisense after waiting at least 1 minute.

If there's any other information I can give to help diagnose this, I'll be happy to provide.

_Copied from original issue: Microsoft/vscode#10369_

**Comment by abarisain** [comment]
I've also noticed this on my computer. This seems to happen because of the 10.12 beta, on which go often panics or freezes. Running the extension in a debugger and breaking on the process stdout reads will show that many calls fail.

Most of my issues have been fixed by updating to the 1.7 RC, so this is probably more a Go issue than a vscode one.

**Comment by mattetti** [comment]
make sure you are on the latest go RC and you restart gocode (type `gocode stop` in your terminal and restart vscode).

**Comment by mattetti** [comment]
Note that this issue is with `gocode`, now that 1.7 is out, more people are having the same problem, see https://twitter.com/mschoch/status/765409009251647489

**Comment by ericoff** [comment]
After update to go 1.7 and updating gocode I can reliably get intellisense again.

**Comment by donatj** [comment]
I have recompiled all the tools, updated the extension, all I get is `PANIC` in intellisense.

![screen shot 2016-08-16 at 11 36 24 am](https://cloud.githubusercontent.com/assets/133747/17707376/bbbe6b7e-63a5-11e6-845c-a5557b599053.png)
![screen shot 2016-08-16 at 11 36 16 am](https://cloud.githubusercontent.com/assets/133747/17707377/bbbebe94-63a5-11e6-9382-0c160600efc3.png)

**Comment by mattetti** [comment]
Did you restart Gocode?

**Comment by donatj** [comment]
@mattetti Several times. I just recompiled gocode as well. Still just PANIC.

**Comment by donatj** [comment]
@mattetti Derp on my part - I mean no. That fixed it.

**Comment by mattetti** [comment]
No worries, I had the same issue,  for whoever trying to solve this issue, run `gocode stop` to stop gocode, even if you updated the tool.

**Comment by lukehoban** [comment]
Going to close this - since the workaround is known, and I've updated the README.  I'm not sure there's anything great we can/should do in the extension itself at this point.  If there are suggestions on improvements to make this sort of thing smoother in the future though, PRs welcome.
