### ISSUE TITLE
Tools not run when a source file has a build tag

### ISSUE THREAD

**Issue by kallekoo** [Microsoft/vscode-go#423]
Hello!

VSCode 1.4.0
up-to-date vscode-go on 11. Aug 2016
OS X Yosemite 10.11.6

A source file has its contents examined by golint and others until a build tag such as

    // +build integration

... is added to the top of the file. No tools seem to be run on it afterwards.

I could not find a way to alter the behavior with the go.buildTags in the project's .vscode/settings.json

**Comment by lukehoban** [comment]
There is actually a `"go.buildTags"` setting which handles this for all the tools that support it (build, test, rename, oracle). 

See https://github.com/Microsoft/vscode-go/commit/083cee83cd19a6b68254a76d8dc1fb2d01ad6651.
