### ISSUE TITLE
Debug not working under MacOS

### ISSUE THREAD

**Issue by DSuhinin** [Microsoft/vscode-go#429]
Everything is configure with current instructions, all path's are correct. When I run Debugger I can see nothing in the console log, and my breakpoint don't work and debugger seems not working without any message. Can someone help me with that?

**Comment by dragosbulugean** [comment]
I am having the same issue. 
VS Code 1.4.0, golang 1.6.3, delve 0.11.0-alpha
VS Code starts debug process, gets stuck there, no error messages, does not hit breakpoints, and also doesn't run.

**Comment by DSuhinin** [comment]
Hello! I strictly recommend to do next steps:
1. If you installed it through the brew - uninstall delve and also GO
2. Open you keychain and try to search any Certificate/Key with name 'dlv' or 'delve' and remove everything.
3. Again install GO though the brew
4. Go there https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md and do everything step by step. Keep in mind when you are working under console that $GOPATH pointed to your project. Also keep in mind that you have to have next project structure - https://golang.org/doc/code.html, I mean to have bin, src, pkg dirs.
5. Then carefully do this steps - https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md. After you did this command 'CERT=dlv-cert make install' check your project 'bin' directory -it has to contains executable 'dlv' file
6. Then open VSCode and change you settings like this:
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "go.goroot": "YOUR_GO_ROOT",
    "go.gopath": "YOUR_CURRENT_PROJECTPATH",
    "go.gocodeAutoBuild": false
}

Then simply configure your launcher with this settings:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
        }
    ]
}

Save please everything and reload VSCode and if you did everything correct it will work. For me after I did this steps everything is work perfect. So I think it was a problem with the Certificate that brew tried to install. Let me know if you will have some questions.

**Comment by dragosbulugean** [comment]
@DSuhinin thanks! i think you are right, something's wrong with brew installed certificate. your instructions worked.

**Comment by DSuhinin** [comment]
Hah, Great!
