### ISSUE TITLE
feature request: switch to test file

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#432]
Like probably a lot of you, I switch back and forth between my tests and my implementation.
I'd like to be able to:
- jump to the test file (current file name but with `_test` suffix)
- jump to the test implementation (based on name conventions)
- open test file in other pane (so I can have both files side to side)
- jump to implementation file when looking at a test file

Bonus:
- create a test file if missing
- generate stubbed test for a function/method (generic table test)

I have to find out where is the documentation to open files and to define targets, but I think that should be quite doable.

**Comment by mattetti** [comment]
API to open a specific file using filename only: https://code.visualstudio.com/docs/extensionAPI/vscode-api#1108

**Comment by ramya-rao-a** [comment]
@mattetti The latest update has these features:

Commands to switch to test file and back. You can add your own shortcuts for these commands.
        - `Go: Open Test File`
        -  `Go: Open Implementation for Test File`
Navigate to test file after generating unit tests using the `Go: Generate unit tests ...` commands that were added last month

This should cover most of your asks here :)

Happy Coding!
