### ISSUE TITLE
Rename symbol - after rename the progress indicator keeps "rolling" and CPU usage increases

### ISSUE THREAD

**Issue by skyflyer** [Microsoft/vscode-go#434]
VS Code: Version 1.4.0 (1.4.0)
Go version: 1.7 (same with 1.6)
vs-code: 0.6.42

Steps to reproduce:

1. Create folder `~/tmp/renametest/src/foo
1. Open terminal and go to `~/tmp/renametest`
1. Add current dir to GOPATH: `export GOPATH=$GOPATH:~/tmp/renametest`
1. Launch vscode: `code .`
1. Create a `main.go` file:
```go
package main

import "fmt"

type TestMeSomething struct {
	NameFoo int
	Blabla  string
}

func main() {
	x := TestMeSomething{1, "foo"}
	fmt.Println(x)
}
```
1. Rename `TestMeSomething` symbol to `TestMeSomethingElse`

Expected  result:
1. Symbol is renamed quickly

Actual result:
1. Symbol is renamed after apx. 1.5 seconds (though that might be an acceptable delay)
1. The progress indicator (blue line sliding from left to right just under the document tab controls) keeps moving on and on (does not stop until document is closed)
1. CPU usage increases

The interesting thing is that the process `Code Helper` is using ~17% CPU. Process info from ps:
```
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --lang=en-US --node-integration=true --background-color=#131313 --num-raster-threads=2 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=34037 --channel=50713.1.1653753182
```

**Comment by lukehoban** [comment]
I believe this is the same as https://github.com/Microsoft/vscode-go/issues/431 which is fixed now.
