### ISSUE TITLE
Feature request: call multiple format tools upon save

### ISSUE THREAD

**Issue by cdevr** [Microsoft/vscode-go#435]
Why do I need to choose between goreturns, gofmt and goimports ? All 3 would be so much better.

**Comment by lukehoban** [comment]
Goreturns is a superset of goimports which is a superset of gofmt.  So I'm not sure what scenario is not supported?

**Comment by cdevr** [comment]
Issue is that the company I work for has custom versions of gofmt and goimports. So the goreturns integration with those tools doesn't work.

**Comment by erikjohnston** [comment]
> Goreturns is a superset of goimports which is a superset of gofmt. So I'm not sure what scenario is not supported?

Its not anymore: https://go-review.googlesource.com/c/tools/+/45390 (from [this thread](https://groups.google.com/forum/#!topic/golang-nuts/RyWfs9ddn8c)).

The issue I have is that `goimports` doesn't have support `-s` flag from `gofmt`.
