### ISSUE TITLE
Code completion not working at all

### ISSUE THREAD

**Issue by skyflyer** [Microsoft/vscode-go#436]
Go version: 1.7
VSCode version: 1.4.0
vscode-go version: 0.6.42

Code completion for go code is not working at all. The only code completion I get is for PANIC. I've tried a very simple empty project as well. Nothing visible in the developer console.
<img width="391" alt="screen shot 2016-08-16 at 11 07 00" src="https://cloud.githubusercontent.com/assets/415535/17693937/bf4831ca-63a1-11e6-8f65-22fd829527b8.png">

**Comment by azr** [comment]
same here

**Comment by LeeQY** [comment]
Try update gocode:

`go get -u github.com/nsf/gocode`

And stop gocode:

`gocode close`

Then it should be fine.

**Comment by skyflyer** [comment]
@LeeQY this works fine, thanks! Strangely enough, Sublime Text's GoSublime package was working fine...
