### ISSUE TITLE
feature request: autocomplete non imported packages

### ISSUE THREAD

**Issue by trajber** [Microsoft/vscode-go#437]
The Go plugin for IntelliJ has a very useful feature that allows code completion works even when the package is not imported yet.
On this example you can see **"fmt"** and **"os"** packages being used even with no imports at all.

![output](https://cloud.githubusercontent.com/assets/291612/17714200/2d2dc442-63d5-11e6-86bc-66b9f964cedb.gif)

**Comment by derekperkins** [comment]
Duplicate of #407

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest version of the Go extension : 0.6.44

You need to set `go.autocompleteUnimportedPackages` to true to enable this feature.

Do give it a try and give feedback

We will turn it on by default in the next update
