### ISSUE TITLE
When hitting Stop during Debug, it does not always kill debug process

### ISSUE THREAD

**Issue by intdel** [Microsoft/vscode-go#438]
I am running a web server in Go (1.6) with visual studio code and the most recent plugin:

```
func main() {

    http.HandleFunc("/data", htmlHandler)

    err := http.ListenAndServe(":8080", nil)
    if err != nil {
        log.Fatal(err)
    }
    os.Exit(0)
}
```

When I hit the stop button on the small debug window, it does not kill the webserver, because after I hit F5 again I get:

>  2016/08/16 15:34:13 server.go:71: Using API v1
> 2016/08/16 15:34:13 debugger.go:61: launching process with args: [./debug]
> API server listening at: 127.0.0.1:2345
> 2016/08/16 15:34:13 debugger.go:393: continuing
> 2016/08/16 15:34:13 listen tcp :8080: bind: address already in use

So I will have to look manually for the PID and kill it. Then it works again.

**Comment by lukehoban** [comment]
What OS, and do you have a full precise repro?  I tried a few times on Windows and OSX with the closest full example I could derive from the above and couldn't reproduce this.

Happy to reopen if you have more info to investigate.

**Comment by intdel** [comment]
Sure. I am using Debian Testing with Google Chrome:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
```

Here is an example code that I used to successfully verify the issue:
web.go:
```
package main

import "net/http"
import "fmt"
import "log"

func welcomeHandler(w http.ResponseWriter, r *http.Request) {

	fmt.Fprintln(w, "hello")
}

func main() {

	http.HandleFunc("/", welcomeHandler)

	err := http.ListenAndServe(":8080", nil)

	if err != nil {
		log.Fatal(err)
	}

}
```

launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}
```

Steps to reproduce:

1. Press F5 to launch the debug process
2. Open terminal and do pidof debug:
```
$ pidof debug                                                                                                                                                       
5441     
```                          
\3. Open browser and go to http://localhost:8080. You will see "hello
4. Hit the red stop button in VS Code
5. Refresh browser again and it's still hello
6. Pidof again:
```
$ pidof debug                                                                                                                                                       
5441    
``` 
\7. Hit F5 again and you will get error
:
```
2016/08/21 19:13:05 server.go:71: Using API v1
2016/08/21 19:13:05 debugger.go:61: launching process with args: [./debug]
API server listening at: 127.0.0.1:2345
2016/08/21 19:13:06 debugger.go:393: continuing
2016/08/21 19:13:06 listen tcp :8080: bind: address already in use
```

You can use pidof again and you will see that it is still the same process.

**Comment by jaylittle** [comment]
Can confirm this.  Seeing this exact same behavior with go debugging on Arch Linux.

**Comment by bsphere** [comment]
same behavior with Ubuntu 16.04

**Comment by therox** [comment]
+ vscode 1.5.2, Ubuntu 16.04

**Comment by d10r** [comment]
Same here. Ubuntu 14.04, vscode 1.6.0, vscode-go 0.6.44

**Comment by roblourens** [comment]
I can repro this, and confirm that it works correctly with delve. So maybe we can do whatever delve does.

**Comment by jferrer21** [comment]
Hi, 

I'm getting the same messages

2016/10/22 13:37:09 server.go:71: Using API v1
2016/10/22 13:37:09 debugger.go:61: launching process with args: [./debug]
API server listening at: 127.0.0.1:2345
2016/10/22 13:37:09 debugger.go:393: continuing

Is there a way to clear the messages?

Thank you

OSX 10.12
GO 1.7.3
GO Plug-in 0.6.45

**Comment by intdel** [comment]
@jferrer21 As far as I can see, your messages are not "errors" but rather informative. It would be an error if it had the line `2016/08/21 19:13:06 listen tcp :8080: bind: address already in use`. Maybe you omitted it when pasting it?

Otherwise you can get rid of those messages by setting `"showLog": true` to `"showLog": false` in launch.json

**Comment by jferrer21** [comment]
I didn’t get the last line.  Thank you for the info, about setting the showLog.

**Comment by nezorflame** [comment]
Getting the same behaviour on Mint 18 with the vscode 1.7.1 and go 1.7.3.

**Comment by cgroves3** [comment]
same behavior with ubuntu 14.04.5 LTS and vscode 1.8.1

**Comment by TobiEiss** [comment]
Same here. Ubuntu 16.04, vscode 1.8.0, vscode-go 0.6.51

**Comment by YokiWorks** [comment]
Same here Ubuntu 16.04 vscode 1.8.0

**Comment by sysroad** [comment]
Same here Ubuntu 16.04 and VSCode 1.9.0

**Comment by ramya-rao-a** [comment]
I can't repro the issue and so cannot test the fix. Can anyone on this thread volunteer to test this?
Steps:
- Clone the repo https://github.com/Microsoft/vscode-go
- `cd` into the repo
- Get the branch with the fix `roblou/killProcs`
- `npm install`
- If you don't have the `vsce` tool, then `npm install -g vsce`
- `vsce package` to get the vsix file for the extension
- `code --install-extension Go-0.6.53.vsix` to install the extension from the six
- now run vs code as you normally would

**Comment by intdel** [comment]
@ramya-rao-a I was trying out the steps you provided. However, at `npm install` I get:

```
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/fs-extra' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'Go'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

**Comment by ramya-rao-a** [comment]
@intdel Am not sure why you are seeing that error, I am able to `npm install` successfully on a freshly cloned repo. What is your version of node and npm?

Nevertheless, you can comment the line for `@types/fs-extra` from `package.json` and continue. It is just a dev dependency, and since you will directly be packaging the code into a vsix, you wont need it

**Comment by intdel** [comment]
@ramya-rao-a Thanks. Now I am getting

```
 vsce package

/usr/local/lib/node_modules/vsce/node_modules/denodeify/index.js:40
                        return new Promise(promiseHandler);
                                   ^
ReferenceError: Promise is not defined
    at /usr/local/lib/node_modules/vsce/node_modules/denodeify/index.js:40:15
    at readManifest (/usr/local/lib/node_modules/vsce/out/package.js:359:20)
    at pack (/usr/local/lib/node_modules/vsce/out/package.js:523:12)
    at Object.packageCommand (/usr/local/lib/node_modules/vsce/out/package.js:532:12)
    at Command.<anonymous> (/usr/local/lib/node_modules/vsce/out/main.js:62:31)
    at Command.listener (/usr/local/lib/node_modules/vsce/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/vsce/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/vsce/node_modules/commander/index.js:458:21)
    at module.exports (/usr/local/lib/node_modules/vsce/out/main.js:110:13)

```

**Comment by ramya-rao-a** [comment]
wow, can you share what version of node, npm and typescript you have?

**Comment by intdel** [comment]
` npm version
{ http_parser: '1.0',
  node: '0.10.29',
  v8: '3.14.5.8',
  ares: '1.10.0',
  uv: '0.10.27',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1k',
  npm: '1.4.21',
  Go: '0.6.53' }
`
`node --version
v0.10.29
`

`typescript@2.1.5`

In package.json I had to remove all of the devdependencies with "@types" otherwise I could not run npm install. Not sure if this is the reason.

I am running this on Debian Jessie.

**Comment by roblourens** [comment]
That's a very old version of node and npm. You'll need to use something more recent.

**Comment by intdel** [comment]
@roblourens Thanks! I tried it on Debian Testing and it did not work either. Did not think it would ship with a very old version.

Anyways, I built the extension on Fedora 25 and it worked well and didn't have to comment out anything.

Finally was able to test the extension. I can confirm that it properly kills the process when hitting stop.

**Comment by ramya-rao-a** [comment]
Yay! Thanks @intdel !!

**Comment by YCF** [comment]
Getting the same behaviour on Manjaro with the vscode 1.9.1 ,vscode-go 0.6.53 and go 1.8.
"debug" process is not being killed after Stop button is pressed.

**Comment by ramya-rao-a** [comment]
@YCF Thanks for reporting, the fix will out in the next update of the Go extension early next week.

**Comment by cevn** [comment]
Any update on this? It's pretty annoying to use the debugger on linux right now.

**Comment by ramya-rao-a** [comment]
Fixed in the latest update (0.6.54) to the Go extension.

@cevn This update was due for a while, sorry to keep you waiting :)

**Comment by YCF** [comment]
0.6.54 this fix not worked.
"debug" process is not being killed after Stop button is pressed.

I binding  hotkey F4-> "killall debug"

**Comment by roblourens** [comment]
@YCF That would probably be a different issue. The `debug` process should have always been killed. This is for other processes spawned by the program.

Can you open a new issue and tell us your OS, vscode version, etc?

**Comment by kisPocok** [comment]
> "debug" process is not being killed after Stop button is pressed.

vscode 1.10.1
go extension 0.6.54
macOS 10.12.3

**Comment by YCF** [comment]
@kisPocok I set it in windows manager not in vscode:
http://docs.xfce.org/xfce/xfce4-settings/keyboard

your OSX maybe here:
http://apple.stackexchange.com/questions/24063/create-global-shortcut-to-run-command-line-applications

**Comment by YCF** [comment]
Fixed at go extension 0.6.55
@kisPocok have a try.

**Comment by hyacinthus** [comment]
ArchLinux still have this behavior.

**Comment by ramya-rao-a** [comment]
@hyacinthus Can you share sample code and repro steps?

Are you saying that using the same code in other platforms in VS Code, you don't see the issue?

**Comment by hyacinthus** [comment]
Yes，I use Windows 10, Mac OS, and Archlinux in different places, but same project. Only Archlinux have this issue. I must kill dlv and debug process every time.

When I arrive my office next Monday ,  I'll create a simple demo to try if this behavior appears in every golang project.

**Comment by ramya-rao-a** [comment]
@roblourens Can you think of any reason why this solution wouldn't work in just linux?

**Comment by roblourens** [comment]
It should work. The code that kills the processes is

```
 terminateTree() {
  	for cpid in $(/usr/bin/pgrep -P $1); do
  		terminateTree $cpid
  	done
  	kill -9 $1 > /dev/null 2>&1
  }
```

I don't know if there's something particular about archlinux that would make this not work.

**Comment by hyacinthus** [comment]
@ramya-rao-a  After the upgrade 1.13, it no longer appears this morning.
I will continue to focus on it.

**Comment by ramya-rao-a** [comment]
Hello all,

We have revisited the fix to this issue by using the detach command from dlv instead of manually killing the processes from our end. I would appreciate it, if anyone here can give the fix a try. Please follow the below instructions to do so:

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code
