### ISSUE TITLE
Error while setting up on environment on windows 10 - Help needed

### ISSUE THREAD

**Issue by dotnetjalps** [Microsoft/vscode-go#44]
HI I have download latest version of GO, Code and vscode-go and installed it in my machine windows 10. 

Here is the my user settings file.
{
	"editor.fontFamily": "Consolas",
	"editor.fontSize": 20,
	"go.buildOnSave": true,
         "go.lintOnSave": true,
         "go.vetOnSave": true,
         "go.formatTool": "goreturns",
          "go.gopath": "F:\Data\Projects\GO\src"
}
and this is my go environment.

![goenv](https://cloud.githubusercontent.com/assets/5141580/11292688/7d496568-8f77-11e5-8251-3d50cb0a672c.png)

 Now I have setup 3 folders in my go directory like following as we are doing for each go project.

![goenv2](https://cloud.githubusercontent.com/assets/5141580/11292703/ba83970a-8f77-11e5-8098-829f25e0a1b6.png)

I have downloaded the all the package of go to make all the things working in go code extension. You can specially gocode and godef is already  installed and available.

![goenv3](https://cloud.githubusercontent.com/assets/5141580/11292724/092b4d8a-8f78-11e5-883d-0c4dda522830.png)

The project I have opened under "F:\Data\Projects\GO\src\MyWebApp" folder where its a simple web app created in go . But whenever I tried to modify I am getting error  
golint is not installed like following.

![error](https://cloud.githubusercontent.com/assets/5141580/11292758/82f483d4-8f78-11e5-999d-ccf41e57a9aa.png)

But if you see in above screenshots golint is already there. So am I doing anything wrong here or is there a bug in vscode. Please help me resolve this issue. This setup works fine with other editors like intellij idea or webstorm. I am getting error in vs code only.

Please suggest what's need to be there. Any help will be appreciated.

**Comment by Mistermatt007** [comment]
I have the same problem as you, all the env set up, all the env vars set but vscode keep saying me "goxxx is not installed please run..."

I suggest you to modify the path you supply in your user config file from `"go.gopath": "F:\Data\Projects\GO\src"` to `"go.gopath": "F:\\Data\\Projects\\GO\\src"`, backslashes need to be escaped ! (:

**Comment by lukehoban** [comment]
Yes - string literals in the settings file need to use escaped backslashes.  You should see an error reported in your settings file about the literal not being valid.

**Comment by Mistermatt007** [comment]
That didn't resolved the problem, I'm. in the same case, string is formatted as it should but it's not working..
Should the `go.gopath` points to the directory where all the utilities are installed ?

**Comment by lukehoban** [comment]
The `go.gopath` should point to the same place as you `GOPATH`.

Could you share OS, `go env` and result of `Go: current gopath`?

**Comment by Mistermatt007** [comment]
I'm using W10 Pro

This is the result of `go env` : 
    set GOARCH=amd64
    set GOBIN=
    set GOEXE=.exe
    set GOHOSTARCH=amd64
    set GOHOSTOS=windows
    set GOOS=windows
    set GOPATH=E:\GoWorkspace
    set GORACE=
    set GOROOT=E:\Go
    set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
    set GO15VENDOREXPERIMENT=
    set CC=gcc
    set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
    set CXX=g++
    set CGO_ENABLED=1

Result of : `Go: current gopath` :
    No handler found for the command: 'go.gopath'

Thanks for caring !

**Comment by lukehoban** [comment]
@Mistermatt007 Two things:

1. Can you open a `.go` file before running `Go: Current GOPATH`?
2. How is your `GOPATH` set up?  Do you have this in your system or user environment globally?  Or do you set it locally in a command shell?

**Comment by Mistermatt007** [comment]
1) WIth a file open `Go: Current GOPATH` returns : `Current GOPATH:E:\GoWorkspace`
2) GOPATH, and GOROOT are set up system-wide, not in a command shell

**Comment by lukehoban** [comment]
@Mistermatt007 Okay thanks.  And what exactly do you see then?  Does "Analysis Tools Missing" show in the bottom right?  What happens if you click it?  What is the contents of your `e:\GoWorkspace\bin` folder?  Have you tried running the `go get` commands that the popups suggest manually in your shell, what do you see if you run those?

**Comment by dotnetjalps** [comment]
I have also updated my path in settings.json "F:\\Data\\Projects\\GO\\src"  but still same error is there. Still its saying golint is not there.

![Uploading Path.png…]()

You can see the Go:Current Path returns F:\\Data\\Projects\\GO\\src and still this error comes.
error comes.

![error](https://cloud.githubusercontent.com/assets/5141580/11357601/dae3e49a-928e-11e5-8543-324dd15f7894.png)





I have also updated my path in settings.json "F:\\Data\\Projects\\GO\\src"  but still same error is there. Still its saying golint is not there.

![Uploading Path.png…]()

You can see the Go:Current Path returns F:\\Data\\Projects\\GO\\src and still this error comes.
error comes.





I have also updated my path in settings.json "F:\\Data\\Projects\\GO\\src"  but still same error is there. Still its saying golint is not there.

![Uploading Path.png…]()

You can see the Go:Current Path returns F:\\Data\\Projects\\GO\\src and still this error comes.
error comes.





I have also updated my path in settings.json "F:\\Data\\Projects\\GO\\src"  but still same error is there. Still its saying golint is not there.

![Uploading Path.png…]()

You can see the Go:Current Path returns F:\\Data\\Projects\\GO\\src and still this error comes.
error comes.

**Comment by Mistermatt007** [comment]
I have done all the go get commands that are in the readme.md and I'm getting the same errors that @dotnetjalps on his second screenshot /:

**Comment by Mistermatt007** [comment]
For some unknown reasons, now it's building fine, I don't know how...

**Comment by lukehoban** [comment]
FWIW - It's possible the issue you were seeing was related to this: https://github.com/Microsoft/vscode/issues/560#issuecomment-159573986.

**Comment by dotnetjalps** [comment]
@lukehoban - Now its working fine after adding Analysis tool!
