### ISSUE TITLE
Hover info does not show doc string for structs

### ISSUE THREAD

**Issue by nii236** [Microsoft/vscode-go#440]
I'm not sure if this is expected behaviour, but here is a screenshot. The struct has a docstring but it is not shown in the hover info.

![](https://puu.sh/qE0wj/f1cdf1cc4d.png)

**Comment by lukehoban** [comment]
This is not supported currently - only functions, and only from standard library.  See https://github.com/Microsoft/vscode-go/issues/87 for some discussion on this.  PRs welcome.

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.50), we now support the use of `gogetdoc` for **Goto/Peek Definition, Hover info and Signature Help** features. Add `"go.docsTool": "gogetdoc"` to your setting to enable the use of `gogetdoc` and that should fix this issue.
