### ISSUE TITLE
Need go.formatFlags to support gofmt -s simplify mode

### ISSUE THREAD

**Issue by gbrayut** [Microsoft/vscode-go#444]
Our build server enforces the use of gofmt with the simplify mode. Right now I don't see a way to pass the -s flag to the formatting tool in vscode. Can we add a go.formatFlags setting?

Example code for testing:

```
var final = strings.Split("a b c", " ")
var first = strings.Split("d e f", " ")
final = append(final, first[2:len(first)]...)
//gofmt -s main.go would change the previous line to
final = append(final, first[2:]...)
```

**Comment by lukehoban** [comment]
PRs welcome for this.  Should be a simple addition modelled after `go.buildFlags`/`go.lintFlags`.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest version of the Go extension : 0.6.44

**Comment by gbrayut** [comment]
Thanks! The following in my settings.json worked exactly as I wanted:
```
// Place your settings in this file to overwrite the default settings
{
    "go.formatTool": "gofmt",
    "go.formatFlags": ["-s", "-e"]
}
```
