### ISSUE TITLE
Configured debug type 'go' is not supported.

### ISSUE THREAD

**Issue by thessem** [Microsoft/vscode-go#445]
I get the above error message when I try and debug/run tests, it has been like this since I upgraded to go 1.7. The error persists after removing vscode-go (`rm -rf ~/.vscode/extensions/lukehoban.Go-0.6.43`) and reinstalling

OS: OS X 10.11.6
Code: 1.4.0
vscode-go: 0.6.43
Go: go version go1.7 darwin/amd64 (installed using homebrew)
Delve: v0.11.0 (installed using homebrew)

My launch.json:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "program": "${workspaceRoot}",
      "env": {},
      "args": []
    },{
      "name": "Test",
      "type": "go",
      "request": "launch",
      "mode": "test",
      "program": "${workspaceRoot}",
      "env": {},
      "args": []
    }
  ]
}
```

I have also run the following just in case

```
$ go get -u github.com/nsf/gocode
$ gocode close
```

**Comment by ramya-rao-a** [comment]
@thessem @rogchap Do you still have this issue?

**Comment by thessem** [comment]
No, It went away after a complete flatten and re-install of vscode

**Comment by cylof22** [comment]
@ramya-rao-a I also see the same problem in Mac OSX 10.13, Visual Studio Code: Version 1.16.1 (1.16.1) , go1.8.1, vscode-go: 0.6.65. delve: v0.11.0.

**Comment by ramya-rao-a** [comment]
This error means that the extension is not activated.
Please ensurethe Go extension is not disabled. Open the Extensions viewlet Ctrl+X or Cmd+X and ensure you have the Go extension installed and is enabled
