### ISSUE TITLE
cannot import more than one package 

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode-go#447]
this ![](http://i.imgur.com/eUzoZVG.png)
becomes ![](http://i.imgur.com/7hAirpt.png)
and this too ![](http://i.imgur.com/KlXeLRL.png)
becomes ![](http://i.imgur.com/7hAirpt.png)

so there is no way to use multiple packages in a project what makes this extension completely useless

**Comment by ramya-rao-a** [comment]
@NikosEfthias Just to confirm, do you see your imports disappearing on save? And do you have any references to these imports in your code?

When you add an import, but don't use it, the formatting tool removes it for you when formatting is triggered. Formatting is triggered in the below cases

- You intentionally click on Format Code option in the context menu
- You use keyboard shortcut for the same (Alt+Shift+F in Windows)
- You save the file manually while the `formatOnSave` setting is set to true. By default the `formatOnSave` feature for the Go extension is turned on.
- You did not manually save the file but have both `AutoSave` and `formatOnSave` turned on

I am guessing yours would be the third or the fourth case.

If its the third, then don't save the file before using the new import.
If its the fourth, then turn either `AutoSave` or `formatOnSave` off based on your preferences. Or start using the import without adding it. The import will get added automatically.

**Comment by NikosEfthias** [comment]
well i was saving and format on save is true so i think thats the issue its just a habit to save after every single word i write

**Comment by ramya-rao-a** [comment]
glad you are unblocked

**Comment by ramya-rao-a** [comment]
@NikosEfthias another thing you can do is change your formatting tool setting to "gofmt". This tool will not remove your unreferenced imports.
But at the same time, you will lose the feature of the formatting tool adding missing imports too.

So your call.
