### ISSUE TITLE
Running Go AppEngine tests always fails after 30 seconds

### ISSUE THREAD

**Issue by chrisolsen** [Microsoft/vscode-go#449]
When I run my tests I always get a `panic: test timed out after 30s` message when running my tests via the vscode-go commands, but when I run them with a terminal everything passes.

I have verified that no matter what tests are run, after 30 seconds it panics. Is there a setting that would allow me to extend this timeout period?

OS: Windows 10
VSCode: 1.4.0
vscode-go: 0.6.43

**Comment by bredov** [comment]
There is a `go.testTimeout` configuration parameter which defaults to 30s. Change it to a larger value (`go test` by default uses 10m), that should help.

**Comment by chrisolsen** [comment]
That fixes it. Thanks!
