### ISSUE TITLE
Getting error when trying to use alt+shift+f

### ISSUE THREAD

**Issue by Gacnt** [Microsoft/vscode-go#45]
I have my 

`"go.formatTool": "gofmt"`

but when I try to press `alt+shift+f` I get:

`The 'goreturns' command is not available. Use 'go get -u sourcegraph.com/sqs/goreturns' to install.`

running on Mac OS X, it doesn't seem to be trying to use my setting unless `alt-shift-f` is strictly bound to goreturns, I can't find the keybindings anywhere. Thanks.

**Comment by lukehoban** [comment]
This should be fixed now with the changes in #47.
