### ISSUE TITLE
Syntax error not being caught - No hightlight

### ISSUE THREAD

**Issue by nikhilraog09** [Microsoft/vscode-go#450]
version 1.4, Windows 10 - newly installed; configured all the tools, restarted,
Syntax error not being highlighted by go lint; Auto complete takes ton of time, 
Godef rarely works, spinning lot of threads - cpu hogging

**Comment by ramya-rao-a** [comment]
@nikhilraog09 Sorry for responding so late. Do you still have these issues with the latest VS Code and the latest Go extension?
Do you see this in all Go projects or is it restricted to large projects only?

**Comment by nikhilraog09** [comment]
@ramya-rao-a ,  its restricted to Large projects, Golint, auto complete works fine now But definitely Godef  needs a revamp or the way it works needs to be more memory efficient. Its v slow compared to atom or sublime with latest Go extension.

**Comment by ramya-rao-a** [comment]
Thanks @nikhilraog09 
We have a few other issues tracking the need for godef usage to be better. Therefore will close this issue.
