### ISSUE TITLE
"Go to Definition" not working for structs

### ISSUE THREAD

**Issue by apkrieg** [Microsoft/vscode-go#459]
This is a feature my colleagues and I use very often when programming in Go (and other languages). I'm not sure if this is already implemented and I have not enabled it or if it is simply missing.

**Comment by apkrieg** [comment]
Correction, it seems this feature does work, but only for functions and not `struct`s, fields, or `interface`s. It should work for all types.

**Comment by ramya-rao-a** [comment]
@zmb3 @abarisain Would integrating `gogetdoc` help here?

**Comment by abarisain** [comment]
I think so !

**Comment by abarisain** [comment]
Actually, it already works on my gogetdoc2 branch.

@apkrieg if you can do a small repro file that fails with the current version, I could confirm that gogetdoc fills this gap

**Comment by apkrieg** [comment]
```
package main

import (
	"database/sql"
	"log"

	"github.com/go-sql-driver/mysql"
)

var (
	DBConn *sql.DB
)

func init() {
	log.Println("mcrm: Initializing...")
}

func main() {
	log.Println("mcrm: Starting...")
	// Establish a database connection
	dbconfig := mysql.Config{
		Addr:   "localhost:3066",
		User:   "mcrm_usr",
		Passwd: "---",
		DBName: "mcrm_db",
		Params: map[string]string{"parseTime": "true"},
	}
	var err error
	DBConn, err = sql.Open("mysql", dbconfig.FormatDSN())
	if err != nil {
		log.Fatalf("mcrm: error: Could not create DB connection.\n\tMore Info: %s\n", err.Error())
	}
	err = DBConn.Ping()
	if err != nil {
		log.Fatalf("mcrm: error: Unable to connect to the DB.\n\tMore Info: %s\n", err.Error())
	}
	// ---
	defer func() {
		log.Println("mcrm: Exiting...")
		err = DBConn.Close()
		if err != nil {
			log.Fatalf("mcrm: error: Could not close the DB connection. Exiting anyway.\n\tMore Info %s\n", err.Error())
		}
	}()
}
```
If you try to go to the definition of `mysql.Config` on line 21, it goes nowhere.

**Comment by apkrieg** [comment]
I wrote this just to test the issue and it seems "Go to Definition" works for `structs`. Maybe it's just the sql library I'm using?

```
// Testing "Go to Definition"
package main

import (
	"github.com/satori/go.uuid"
	"fmt"
)

var (
	id uuid.UUID
)

func main() {
	id = uuid.NewV4()
	fmt.Println(id.String())
}
```

**Comment by abarisain** [comment]
Thanks for the repro, I got the same results on my windows computer on the master branch.

While it is a little slower than godef, the abarisain/vscode-go gogetdoc2 branch handles this correctly.
Couldn't try glfw, only MySQL, since I don't have gcc installed on this box

**Comment by nochso** [comment]
The current implementation fails mostly because of these few lines: https://github.com/Microsoft/vscode-go/blob/8c7d2d364059d4ed30d8931476306c6b9ef011bc/src/goDeclaration.ts#L66-L70

From what I can tell, it looks for `func Name..` even for structs. However the output of godoc for structs looks like `func (t *Type) Name..`

**Comment by ramya-rao-a** [comment]
Is this still a problem? I tried the example at https://gobyexample.com/interfaces which uses structs and interfaces. I was able to use the `Go to Definition` feature without any problem

I am running VS Code 1.6.1 with Go extension 0.6.45 in Mac OS X

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.50), we now support the use of `gogetdoc` for **Goto/Peek Definition, Hover info and Signature Help** features. Add `"go.docsTool": "gogetdoc"` to your setting to enable the use of `gogetdoc`, restart VS Code and that should fix this issue.
