### ISSUE TITLE
Debug output is empty

### ISSUE THREAD

**Issue by lazyfingers** [Microsoft/vscode-go#462]
When I run debugger inside VS code the debug output is empty and the program doesn't run at all. I've started having this problem about 2-3 weeks ago, everything worked magically fine from the start. I think it began after I've updated VS code. Debug output does show if there's an error but it stays blank when no errors encountered even though my program runs fine inside terminal.

here's my debug mode config:
{
        "name": "Launch",
        "type": "go",
        "request": "launch",
        "mode": "debug",
        "program": "${workspaceRoot}",
        "env": {},
        "args": []
 }
GOPATH is set environmentally and inside VS code config

P.S. i did reinstall go and delve. it was and is up-to-date

**Comment by ramya-rao-a** [comment]
@lazyfingers Is this still a issue ?

**Comment by lazyfingers** [comment]
Not really. I've switched to another computer lately and have no issues. Back then it was sort of a permission issue, everything worked fine when I tested running vs code as root though.

**Comment by ramya-rao-a** [comment]
Great, will close this issue then.
