### ISSUE TITLE
Tool installation is broken

### ISSUE THREAD

**Issue by calmh** [Microsoft/vscode-go#467]
While setting up a new installation, `lukehoban.Go-0.6.43`:

![screen shot 2016-09-02 at 07 10 03](https://cloud.githubusercontent.com/assets/125426/18193311/8a5dab14-70dc-11e6-8479-27528f4685ae.png)

For searchability:

`The "goimports" command is not available. Use "go get -v undefined" to install.`

("undefined" is not a good package path here.)

Obviously "Install" does nothing, and also not "Install all".

**Comment by ramya-rao-a** [comment]
This fix is now available in the latest version of the Go extension : 0.6.44
