### ISSUE TITLE
Auto format and highlight should support Go assembly language

### ISSUE THREAD

**Issue by chai2010** [Microsoft/vscode-go#468]
like this:
![](https://github.com/chai2010/notepadplus-go/raw/master/screenshot-asm.png)

https://github.com/chai2010/notepadplus-go

**Comment by lukehoban** [comment]
Given that these are just `.s` files, presumably they would need to be handled by a general purpose assembly colorizer?  Is this / should this really be Go specific?

**Comment by lukehoban** [comment]
Closing for now - I'm not sure this is something we would do in `vscode-go` vs somewhere else.
