### ISSUE TITLE
Cgo dependency strange building

### ISSUE THREAD

**Issue by heretic13** [Microsoft/vscode-go#472]
Hello. 

I'm trying to compile and debug the test program to work with the database.

I've completed these steps:

**go get github.com/mattn/go-sqlite3**

and

**go install github.com/mattn/go-sqlite3** inside mingw-w64.bat environment

I copied to a separate folder file https://github.com/mattn/go-sqlite3/blob/master/_example/simple/simple.go, manually build the application, and then checked his work:

**go build** inside mingw-w64.bat environment (Without the environment I was not able to compile a program)

Run program - it's working.

I am trying to build and debug same program from a VS Code.

I do not understand how the program can be builded and can start debugging if before she asked gcc? VS Code said nothing and allow debugging.

The resulting file is much smaller than if it were builded manually.

Of course debugging unsuccessful. When I start program manually (from command line) - it goes into a state of panic.

Okay, maybe I'm wrong. I run mingw-w64.bat the command line and in the same VS Code.
That is, the VS Code must see gcc.
I am trying to build and debug program from a VS Code.

The result is the same: Debugging unsuccessful. When I start program manually (from command line) - it goes into a state of panic.

what is that?

--------------------
My Configuration:
Windows 10 x64
go amd64 1.7
VS Code 1.5.1 (actual for 2016.09.09)
Go for Visual Studio Code - 0.6.43
delve (actual for 2016.09.09)
MinGW x64, gcc 6.2 with or no mingw-w64.bat

**Comment by heretic13** [comment]
Please add the ability to edit the command line for build the program.

**Comment by heretic13** [comment]
The program is in a state of panic in the source code C.
If I put the setting sqlite to use the database in memory, then everything works and is debugged.

I think your plugin builds a program using bad compiler settings.
I repeat once again - the program compiled manually works normally.


I tested on Linux - there are no such problems.

**Comment by heretic13** [comment]
sorry. This is delve problem.
**dlv debug** produce wrong binaries

**Comment by aarzilli** [comment]
Did you try to compile the program using `go build -gcflags='-N -l'`?
