### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by zhakhalov** [Microsoft/vscode-go#474]
Hi
I've installed all required dependencies for extenstion but I cannot run project in _debug_ mode

Having following error:

```
can't load package: package internal: no buildable Go source files in C:\Go\src\internal
exit status 1
```

But I'm able to run application from cmd as `go install ...`

---
## Environment

OS: Windows 10
Runnable: `go1.7.1 windows/amd64`

**Comment by lukehoban** [comment]
That error indicates that you are trying to debug a folder that doesn't have any source code.  It's a Delve error.  You likely need to point at a particular subfolder where you have the sources for a binary?

**Comment by m0n01i7h** [comment]
I have just fire F5 in project directory 

This is my project
![image](https://cloud.githubusercontent.com/assets/4782787/18541551/8c917e18-7b2e-11e6-9d07-b5fc6a837aae.png)

And this is launch.json content
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "remotePath": "",
      "port": 2345,
      "host": "127.0.0.1",
      "program": "${workspaceRoot}",
      "env": {},
      "args": [],
      "showLog": true
    }
  ]
}
```

Also I tried to pass certain file to program field wit same effect :(
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "remotePath": "",
      "port": 2345,
      "host": "127.0.0.1",
      "program": "${workspaceRoot}/main.go",
      "env": {},
      "args": [],
      "showLog": true
    }
  ]
}
```

But if install my package as `d:\development\Go\src\hwapp>go install .` or run app as `d:\development\Go\src\hwapp>go run main.go ` everything goes fine

**Comment by RoboBurned** [comment]
From StackOverflow post [How to fix delve “can't load package: package internal” error](http://stackoverflow.com/questions/39458526/how-to-fix-delve-cant-load-package-package-internal-error)
> Have to fallback to previous version of delve to get it working.

**Comment by m0n01i7h** [comment]
That workaround helped.
Thank you.

Here is solution
```
cd %GOPATH%\src\github.com\derekparker\delve
git checkout e4c7df
cd %GOPATH%\src
go install .\github.com\derekparker\delve\cmd\dlv
```

Please add this workaround to readme.md


But next issue i met is overinformated debug console. 
![image](https://cloud.githubusercontent.com/assets/4782787/18595371/16665ba8-7c4d-11e6-9a1f-934ca5904151.png)
I suppose that debugger generates this output. But could you please reduce info from `debugger.go` or please suggest another workaround for this issue.

**Comment by lukehoban** [comment]
What problem is this issue tracking now?  The Delve issue is a bug in Delve that I beleive is now fixed on head.  The original F5 to run should behave as expected.  The debug output should get fixed (it was fixed, but that broke debugging in some scenarios, so was reverted).  If the last is the only open issue, could you open a separate issue on that and close this one?

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from the OP.
