### ISSUE TITLE
How to set env var before run Go test command

### ISSUE THREAD

**Issue by ysqi** [Microsoft/vscode-go#475]
hi, Need use env var in go test , So  I want  to add Environment Variables just for go test command.
how to do it ?  thanks!
`Go: Run test at cursor`

**Comment by lukehoban** [comment]
I don't think there's any way to do this currently.  Currently the extension just uses the environment that VS Code was launched with.  PRs for a new configuration option to specify additional env vars to pass through to the `go test` invocation welcome.

**Comment by ramya-rao-a** [comment]
Setting env variables via the configuration settings for the tests to use would apply the same env vars to all tests in the project.
Would that be the most common scenario or different tests needing different env vars be more common?
If it is the latter, we can prompt the user for entering the env vars when the test commands are triggered. And whether to prompt or not can be controlled via the configuration settings

**Comment by ysqi** [comment]
thanks @lukehoban @ramya-rao-a  ,I want  to use env variables for all tests in current workspace.
but can't setting env variables via the configuration settings now.
e.g init run mode ,first check Is there a set env var `runMode` . different run mode use different config. `runMode=test` => config= `app.test.config` .

**Comment by ramya-rao-a** [comment]
@ysqi , Just to clarify ..

> e.g init run mode ,first check Is there a set env var runMode . different run mode use different config. runMode=test => config= app.test.config 

What you mean is in your case you would like to set an env var "runMode" and based on its value your tests would use different configs correct?

And **not** that you would like a feature where vscode picks up different config files based on the runMode setting

**Comment by ysqi** [comment]
@ramya-rao-a  the config file is  that  my application's file, not about vscode.

**Comment by ramya-rao-a** [comment]
@ysqi This feature is now available in the latest version of the Go extension : 0.6.44

**Comment by ernsheong** [comment]
I ran into this. Thank you so much!! 🙌 🙌
