### ISSUE TITLE
Syntax errors only on save

### ISSUE THREAD

**Issue by ProTip** [Microsoft/vscode-go#476]
I'm not sure if this is just me, but I *only* get syntax errors on save, and a few other errors such as incorrect package imports. Fixing errors also requires a save to resolve in the editor. Is this usual?  I'm used to these errors being displayed and resolved live without saving..

**Comment by egamma** [comment]
@ProTip if you want to get diagnostics as you type you can enable auto save. This is done using the setting `"files.autoSave": "afterDelay"`.

**Comment by lukehoban** [comment]
Yes - this is expected default behaviour, but configurable per @egamma's comment.
