### ISSUE TITLE
Test for Gometalinter failing as configuration is read-only

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#479]
The test for gometalinter tries to set the user settings for `linttool`. 
```
let config = vscode.workspace.getConfiguration('go');
config['lintTool'] = 'gometalinter';
```

This fails in the latest version of VSCode (1.5 and higher), as you can no longer update config that way.

Interestingly the comment for the above config in vscode.d.ts says it is a readonly dictionary, though it has been writable till the last release

There have been changes to the configuration service in VS Code in August and more to come in September 

I'd say we comment the test case for now until vscode comes up with the right way to set the configs

**Comment by lukehoban** [comment]
Is there any way to continue to test `gometalinter` given the change in VSCode?  It seems a shame to lose the test coverage.  But it makes sense to unblock CI for now and comment this test out.

**Comment by ramya-rao-a** [comment]
@lukehoban updated `check()` method to take in test configuration that will override the workspace configuration. The test for the `gometalinter` can pass in config this way. #480

**Comment by lukehoban** [comment]
I tried out a slightly less invasive fix for this in https://github.com/Microsoft/vscode-go/pull/481 which looks like it works as well - so I'll merge that in as soon as tests pass.
