### ISSUE TITLE
Error: Command failed: go get -u -v github.com/nsf/gocode

### ISSUE THREAD

**Issue by emanuelecesari** [Microsoft/vscode-go#483]
hi I am very new in go i am using visual studio code on linux machine i have installed vscode-go but i dont know why when i try to install all this tools:
 gocode
  goreturns
  gopkgs
  godef
  golint
  go-outline
  go-symbols
  guru
  gorename
I have some errors
![schermata da 2016-09-15 23-05-43](https://cloud.githubusercontent.com/assets/12241058/18567555/f6e6d2a8-7b98-11e6-9f6e-128edcf2c66f.png)

i think the problem is the go global path but i dont know where I made the mistake

**Comment by ramya-rao-a** [comment]
@emanuelecesari If you are new to Go, the docs for [Getting Started](https://golang.org/doc/install) are pretty helpful in setting up your environment.
It walks you through the basic installation, checking if your installation works and setting the GOPATH
