### ISSUE TITLE
I cant install any go tools

### ISSUE THREAD

**Issue by emanuelecesari** [Microsoft/vscode-go#484]
I have installed go on my computer ( windows 10) 
I had also created the enviroment variable but i cant install the go tools for vsc
I hade this error message "Error: Command failed: go get -u -v golang.org/x/tools/cmd/gorename
"go" not reconaised  like internal or external comand!
I have already read the documentation of go but i have still problem is 2 days that i try i am really disperated!!

I hope someone could help me to fix and finally i can start coding!
ps IF i have write go current location i see
Current GOPATH:C:\Projects\Go

**Comment by peterbourgon** [comment]
You haven't installed go properly. I recommend you review the installation instructions.

**Comment by ramya-rao-a** [comment]
@emanuelecesari 
Can you run a simple command `go version` in your command prompt to confirm that you have go installed properly?
In which folder have you installed Go?
Looks like the path to go.exe is not in your $PATH environment variable

**Comment by ramya-rao-a** [comment]
Closing this issue since it has been over 2 weeks since last update. @emanuelecesari  feel free to get back if you still have issues after reading the installation instructions
