### ISSUE TITLE
feature: syntax color for interface type names

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode-go#486]
For me it makes sense to highlight  interface type names differently from other types. For example I would like to highlight `http.Handler`, `http.ResponseWriter` differently then the rest. 
![image](https://cloud.githubusercontent.com/assets/863731/18612203/d3a15a90-7d53-11e6-96bf-cdb62aaa4c04.png)
Suggest a option flag to highlight a interface type name in vsconfig

**Comment by lukehoban** [comment]
It's a good idea, though unfortunately may not be easy to do with good performance.  Knowing these are interfaces requires type-checking the code, which we don't do today for colorization.  Adding this would almost certainly lead to (1) a lot more invocations of the Go compiler (2) scaling issues for larger code bases (3) changes in colorization as the editor waited on the results of compilation.

Issue 1 and 2 might be addressed in theory if there was a resident out-of-proc incremental compiler for Go - but that doesn't appear to exist in the ecosystem and I'm not aware of anyone working on one.  Without that this sort of feature probably won't have a great user experience.

**Comment by gertcuykens** [comment]
What about a "color all interfaces" menu entry and a hot key?

![image](https://cloud.githubusercontent.com/assets/863731/18817779/c0f8acd8-8369-11e6-9f62-b6a4103abf2e.png)

So only one pass will be done on demand

**Comment by ramya-rao-a** [comment]
AFAIK coloring of text is done based on grammar.
Closing this issue as I don't see how we can use type-checking and then dynamically change colors of the text.

If anybody knows how to do that, then we can re-visit this.
