### ISSUE TITLE
Renaming variables doesn't reflect changes immediately (only sometimes)

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-go#488]
When I rename a variable (F2), then even after the change has been done, there is no change reflected in the file, nor is there any message as to if the process was successful or not. I have to close the file and reopen it to see that the variable name was updated. This happens once (I think) when I do this operation the first time, on subsequent edits, I can't reproduce this.

Also, the `undo` functionality is broken after performing a variable rename. I can't seem to be able to go to any previous state, like the history was wiped clean.

**Comment by ramya-rao-a** [comment]
@kumarharsh The undo not working after a rename is being tracked in #13 

I personally have noticed rename operation to be slow on Windows when the rename affects symbols across files.

The slowness is tracked in #297

**Comment by kumarharsh** [comment]
I've noticed that even in the cases when a variable is local (lowercase and in a sub-block scope), vscode apparently scans the whole codebase (because it starts throwing errors in unrelated files) which might contribute to the slowness.
Also, as originally highlighted, sometimes the file doesn't get updated after the rename and it just keeps showing older names until I reopen the file. I've noticed this three times now, but didn't give much heed until the last time it happened. I opened the developer console and there were some errors which unfortunately I didn't take note of at that time.

**Comment by nochso** [comment]
> Also, as originally highlighted, sometimes the file doesn't get updated after the rename and it just keeps showing older names until I reopen the file.

The same thing has happened to me. However sometimes it works as expected, sometimes it doesn't.

**Comment by nochso** [comment]
I use both Windows and Linux so I'll have to test some more. However even on Windows I usually have common unix tools like diff in my PATH.

**Comment by kumarharsh** [comment]
@ramya-rao-a yes, I am on Windows. I do see the progress bar, but I do tend to miss it sometimes (it's so thin), so when the rename operation does succeed, it takes a while for me to realize it. As you said, on windows, this operation takes some time and a success prompt might help.

Like @nochso I also have `diff` and other unix tools (supplied by Git on Windows/mingw64) in my PATH, so diff is accessible by default.

**Comment by ramya-rao-a** [comment]
Closing this issue as there is nothing pending to do here.
