### ISSUE TITLE
Debugger is not running my app, have dlv setup.  How can I found out why?

### ISSUE THREAD

**Issue by jeremywho** [Microsoft/vscode-go#49]
I have everything setup correctly, as far as I can tell.  Dlv is installed correctly, it runs it from the command line.  

I run the app via the debugger and see the tools (run/pause, step, etc), but nothing happens, no breakpoints hit.  

How can I see what's going wrong?

**Comment by rhinoid** [comment]
same here... bottom bar turns orange, nothing happens.

**Comment by lukehoban** [comment]
If you upgrade to `0.6.10` you should now get more diagnostics from the debugger.  Can you do that and report back here if you are still seeing unexpected failures?
