### ISSUE TITLE
Debugging a non-compiling app doesn't automatically end the debug session

### ISSUE THREAD

**Issue by jcdickinson** [Microsoft/vscode-go#492]
## Repro
1. Apply the workaround in #474 on: VSCode 1.5.2, Go 1.7.1, Windows 10 Anniversary.
2. Create a simple hello world `main.go`.
3. Press <kbd>F5</kbd> and accept the defaults for `launch.json`.
4. Press <kbd>F5</kbd> and make sure that debugging works.
5. Add a simple compilation error (e.g. unused variable).
6. Press <kbd>F5</kbd>.
### Outcome

The app fails to compile, the debugger toolbar appears and the stop button must be clicked. The debug log shows `exit status 2`. The debugging session must be manually terminated.

![Debug session is not terminated](https://cloud.githubusercontent.com/assets/522465/18660810/c632c860-7f12-11e6-9b7a-aeaf74da5399.png)
### Expected Outcome

The app fails to compile and no debug session is started, or the debug session is automatically terminated.

**Comment by ramya-rao-a** [comment]
Fixed in the latest update (0.6.54) to the Go extension.
