### ISSUE TITLE
 visual studio code does not see installed packages

### ISSUE THREAD

**Issue by SerjAntiquity** [Microsoft/vscode-go#493]
If i try install go tools using `go get`, vscode not see packages
If i try install go tools via vscode - i get error:

```
Installing 1 tools
  gocode

Installing gocode FAILED

1 tools failed to install.

gocode:
Error: Command failed: go get -u -v github.com/nsf/gocode
/bin/sh: 1: go: not found
/bin/sh: 1: go: not found
```

Default shell - zsh
OS: Linux Mint 17.3

**Comment by ramya-rao-a** [comment]
@SerjAntiquity 

So you are able to install the tools using `go get` outside of vscode, but vscode cannot find them, correct?
This might be because GOPATH is not set.

 Can you run `go env` and share the result?
Can you share a screenshot of your VS Code window?
Is there a status in the status bar saying "GOPATH not set" ?
What do you get when you run the command `Go: Current GOPATH` from your command palette?

**Comment by ramya-rao-a** [comment]
Closing this issue as there as been no response for quite a while

**Comment by goupadhy** [comment]
how to set GOPATH?

**Comment by goupadhy** [comment]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/goupadhy/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gc/d6y6tl513ns4862ygkx1hbcm0000gn/T/go-build118968087=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by SerjAntiquity** [comment]
@goupadhy try to run vs code from terminal.
Or set "go.gopath" in settings.json in  "File"-"Preferences"-"User Settings"

**Comment by SrHuevo** [comment]
I had same problem. It solve add git/bin in var path

**Comment by sancao** [comment]
@SrHuevo: could you please to tell more clearly, how?

**Comment by tamilselvamc** [comment]
set "go.gopath" in settings.json in "Code"-"Preferences"-"User Settings"

**Comment by vishal-uttamchandani** [comment]
@goupadhy I realize this is an old issue. Just to mention, set GOBIN env variable to %GOPATH%\bin and it should install successfully.
