### ISSUE TITLE
Goto Definition, Hover, Signature Help do not work for Dot imported functions 

### ISSUE THREAD

**Issue by Alexendoo** [Microsoft/vscode-go#496]
Using 0.6.43

The function details show correctly

![image](https://cloud.githubusercontent.com/assets/1830331/18731770/00853dba-8056-11e6-8717-c1f06b61ad63.png)

but argument details do not

![image](https://cloud.githubusercontent.com/assets/1830331/18731779/0a47fe3c-8056-11e6-87e4-dddf7081d17e.png)

Becomes an issue in testing when using a different package for the tests or a project such as [goconvery](https://github.com/smartystreets/goconvey)

**Comment by ramya-rao-a** [comment]
The signature help feature uses the `godef` to get package info and then uses `godoc` to get the signature help. The `godef` tool does not support dot imports. See https://github.com/rogpeppe/godef/issues/19

Other features of the Go extension that use the `godef` and so will not work with dot imports are:

- Extra Info on hover
- Goto and Peek definition

**Comment by ramya-rao-a** [comment]
Closing this as won't fix, as the tools we use don't support the dot imported functions

**Comment by ramya-rao-a** [comment]
#622 can fix this, so re-opening

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.50), we now support the use of `gogetdoc` for **Goto/Peek Definition, Hover info and Signature Help** features. Add `"go.docsTool": "gogetdoc"` to your setting to enable the use of `gogetdoc` and that should fix this issue.

**Comment by paulcalcraft** [comment]
Make sure you have gogetdoc installed by running:
`go get github.com/zmb3/gogetdoc`

It's not installed as standard by go or vscode's go extension, and the above setting ("go.docsTool": "gogetdoc") will fail silently if it is not installed.

**Comment by unix2dos** [comment]
in 1.92 mac , do not work?
@ramya-rao-a
