### ISSUE TITLE
Code completions not working

### ISSUE THREAD

**Issue by Krognol** [Microsoft/vscode-go#501]
I've read previous solutions: execute `gocode close` and `go get -u github.com/nsf/gocode`, but this has not solved the problem for me.

Running Windows 10 64bit
Go 1.7.1

**Comment by Krognol** [comment]
After several tries, it now decides to work after doing the steps again.

**Comment by Krognol** [comment]
After a restart, the problem comes back.

**Comment by Krognol** [comment]
Doing `gocode close` and then running an invalid gocode command (ex: `gocode open`) seems to fix it. Strange.

**Comment by lukehoban** [comment]
This is most likely an issue with gocode.  You may need to report an issue there.

If you have a consistent repro (including specific files you are editing, exactly what "restart" means, etc.) that would help investigation either in gocode repo or here.

**Comment by Krognol** [comment]
Will do!

**Comment by Krognol** [comment]
[Solved](https://github.com/nsf/gocode/issues/387#issuecomment-249626743)
