### ISSUE TITLE
formatOnSave not working

### ISSUE THREAD

**Issue by yoke88** [Microsoft/vscode-go#502]
I have some code like this ,when using default `"go.formatOnSave":true` setting ,every time I change the code and save it ,it will delete the import section.

``` go
package main

import 
(
	"fmt"
	"strings"
	"encoding/json"
)

type API struct {
	Message string "json:string"
}

func main() {
	x := new(API)
	fmt.Println(x.Message)
}
```

when save ,the code become
```go
package main

import "fmt"

type API struct {
	Message string "json:string"
}

func main() {
	x := new(API)
	fmt.Println(x.Message)
}

```

**Comment by ramya-rao-a** [comment]
@yoke88 This is as expected. By default, the format tool used by the Go extension is "goreturns".
Both "goreturns" and "goimports" update your Go import lines, adding missing ones and removing unreferenced ones.

In your case, you are adding "strings" and "encoding/json" and saving before using these packages.

Either don't save before using unreferenced packages or change your formatting tool option to "gofmt"
