### ISSUE TITLE
Is it possible to lint only the current package?

### ISSUE THREAD

**Issue by jmunson** [Microsoft/vscode-go#505]
It seems like you have to specify the params in the config with no way to do any kind of placeholders.

Is it possible to make it run gometalinter against the current package name instead of a pre-configured path?

I suppose for what I'm doing right now I could just close vscode and open it inside the specific package I'm working on, but it'd be nice if I did not have to do that to control what I am linting.

**Comment by ramya-rao-a** [comment]
@jmunson 

We already lint only the current package.

Example:
I have all the Go projects as listed in https://github.com/golang/example 
In VS Code, I have opened the example folder which in turn has the below folders

- hello
- stringutil
- outyet


When I am editing a file from the `hello` folder, linting shows errors/warnings from that folder
Same with `stringutil`

Do you see anything that suggests that other packages are being linted ?

**Comment by ramya-rao-a** [comment]
Closing this, as we havent heard back from the OP.
