### ISSUE TITLE
No auto import package

### ISSUE THREAD

**Issue by thanhngvpt** [Microsoft/vscode-go#507]
Hi Author.
I have code `package main

func main() {
	requests := make(chan int, 5)
	for i := 1; i <= 5; i++ {
		requests <- i
	}
	close(requests)

	limiter := time.Tick(time.Milisecond * 200)

	for req := range requests {
		<-limiter
		fmt.Println("request ", req, time.Now())
	}

	burstyLimiter := make(chan time.Time, 3)
}
`

When i press ctrl+s to save file only fmt package  automatic import and time package is not. Please help me how to solve it. 
Many thanks.

**Comment by ramya-rao-a** [comment]
You have a typo. Replace `time.Milisecond` with `time.Millisecond`
