### ISSUE TITLE
debugger navigation seems broken

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#512]
I'm not sure when this happened but it looks like the debugger properly attaches and breaks at my breakpoint but I don't have the navigation feature.

OS: macOS 10.11.6
Go 1.7.1
Delve: Version: 0.11.0-alpha Build: 46803551b888c017e22bef94d6bf223a9eb704a3

![parser_go_-_api](https://cloud.githubusercontent.com/assets/113/19135232/0b1d28ba-8b18-11e6-8016-fae09cbc6e52.png)

I updated Delve to make sure it wasn't an issue with me recently updating Go but I still have the same issue. It seems like a problem with the extension, potentially an API change. From what I can tell, the debugger is properly attached and breaks at the right location (after the print statement). But I can't go inside/step outside the breakpoint.

/cc @lukehoban @derekparker

**Comment by roblourens** [comment]
In this screenshot, it looks like the debugger just isn't paused, I don't see the problem.

**Comment by mattetti** [comment]
@roblourens it is paused (it hangs) but no controls. So maybe it does hang for another reason, but if that's the case, I can't tell why/where it gets stuck.

**Comment by mattetti** [comment]
Next step: I will try to reproduce the issue using a simpler project and confirm that it's indeed broken, even for basic use cases.

**Comment by roblourens** [comment]
It would be very helpful to have a sample repro project, if possible.

**Comment by mattetti** [comment]
@roblourens I was able to repro the issue on a sample project: https://github.com/mattetti/vscode-debugging/tree/master/greetings

`go get github.com/mattetti/vscode-debugging/greetings`
`cd $GOPATH/src/github.com/mattetti/vscode-debugging/greetings`
`code .`
Open `greetings.go`, add a breakpoint to line 10, launch the debugger.

Notice that it does stop and even gives you controls but you aren't stopped at your breakpoint and you don't see any variables.

This might be due to my setup but I could swear it was working less than a month ago (I use the debugger to debug my tests).

VSCode: 1.6.0

Delve Debugger
Version: 0.11.0-alpha
Build: 46803551b888c017e22bef94d6bf223a9eb704a3

macOS: El Capitan 10.11.6 (15G31)

go version go1.7.1 darwin/amd64

**Comment by roblourens** [comment]
Thanks for the repro project, but this actually works for me. I have the same versions of Delve and Go on Sierra.

What does the debug console say? Are you able to debug it on the command line using `dlv test greetings`?

**Comment by roblourens** [comment]
Also we updated the extension yesterday. I don't know if anything relevant to debugging changed, but are you using the latest version?

**Comment by mattetti** [comment]
The debug console says:

```
2016/10/12 13:56:38 server.go:71: Using API v1
2016/10/12 13:56:38 debugger.go:61: launching process with args: [./debug.test]
API server listening at: 127.0.0.1:2345
2016/10/12 13:56:38 debugger.go:238: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x6ec67, File:"/Users/mattetti/Code/golang/src/github.com/mattetti/vscode-debugging/greetings/greetings.go", Line:10, FunctionName:"github.com/mattetti/vscode-debugging/greetings.SayHello", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
```

Yes the following works:

```
$ dlv test github.com/mattetti/vscode-debugging/greetings
```

```
(dlv) b /Users/mattetti/Code/golang/src/github.com/mattetti/vscode-debugging/greetings/greetings.go:10
(dlv) c
(dlv) p name
"matt"
```

I have update VSCode yesterday and I am on the latest version of the Go extension: 0.6.4.4

There is something fishy going on, since it works for you I now wonder if it's not related to some settings. It used to work for me until a couple versions of VSCode ago.

**Comment by roblourens** [comment]
Do you have any `go.` user settings?

**Comment by mattetti** [comment]
Yes I do:

```
  "go.formatOnSave": true,
  "go.buildOnSave": true,
  "go.lintOnSave": true,
  "go.vetOnSave": true,
  "go.buildFlags": [],
  "go.lintTool": "gometalinter",
  "go.lintFlags": ["--disable-all", "--enable=errcheck", "--enable=golint", "--enable=structcheck"],
  "go.vetFlags": [],
  "go.coverOnSave": false,
  "go.useCodeSnippetsOnFunctionSuggest": true,
  "go.goroot": "/Users/mattetti/Code/go",
  "go.gopath": "/Users/mattetti/Code/golang",
  "go.formatTool": "goimports",
  "go.gocodeAutoBuild": true,
  "go.autocompleteUnimportedPackages": true,
```

**Comment by roblourens** [comment]
Ok, none of those look relevant... no errors in the Help > Developer tools? I'm not sure what else to suggest. I hope to add some logging that would let us know what delve is doing and what the adapter is doing in these cases.

**Comment by mattetti** [comment]
The dev tools are showing the error, I should have thought about that!

![greetings_go_-_greetings](https://cloud.githubusercontent.com/assets/113/19329916/12f63afe-9090-11e6-8e56-e6d96cf00224.png)

That gets triggered every single time it breaks.

The root cause seems to be that the threadId is set to 0.

```
this.toDisposeOnSessionEnd.push(this.session.onDidStop(event => {
			this.setStateAndEmit(debug.State.Stopped);
			const threadId = event.body.threadId;

			this.getThreadData().done(() => {
				this.model.rawUpdate({
					threadId,
					stoppedDetails: event.body,
					allThreadsStopped: event.body.allThreadsStopped
				});

				const thread = this.model.getThreads()[threadId];
				thread.getCallStack(this).then(callStack => {
```

![greetings_go_-_greetings](https://cloud.githubusercontent.com/assets/113/19330055/e7dd6256-9090-11e6-9ec6-16ef83e67fe4.png)

**Comment by mattetti** [comment]
![greetings_go_-_greetings](https://cloud.githubusercontent.com/assets/113/19330152/908d2b0c-9091-11e6-82af-cba66ef6c71c.png)

I don't have enough knowledge of the internals to understand what a thread ID is here in this context, we are trying to match on an ID that isn't available in the list of threads on the model.

**Comment by mattetti** [comment]
@roblourens anything else I can do to help?

**Comment by roblourens** [comment]
It looks like the debugger paused and said "i'm paused at thread with id=0" then vscode asked for a list of threads, and it did not return thread 0.

This all comes from Delve, can you debug via delve on the command line?

**Comment by mattetti** [comment]
Delve works from the command line, see https://github.com/Microsoft/vscode-go/issues/512#issuecomment-253350651

Note that in Go, the zero value of an int is `0`, so there might be a race condition in the way the extension layer in fetching the thread id or an un-handled error on the Go side. The weird thing is that it works for you.

**Comment by lukehoban** [comment]
I just tried this myself with the latest Delve from homebrew on OS/X, and I also can't repro exactly what you mention.

I do see that a breakpoint on line 10 in the repro you provided doesn't get hit (and turns grey).  But I see the same thing in Delve when I try to do `b greetings_test.go:10` and get `Command failed: no code at /Users/lhoban/go/src/github.com/mattetti/vscode-debugging/greetings/greetings_test.go:10`.  I believe that is a bug in Delve.  Other than the breakpoint not registering, the behaviour seems right in VS Code.  I do see a breakpoint on line 17 working.

The issues you are seeing in `debugService.ts` may be a red-herring - it's not clear those are necessarily related to any issues here. But it's a bit hard to tell as these call stacks are inside VS Code, not inside the vscode-go debugAdapter implementation itself.

**Comment by mattetti** [comment]
@lukehoban the breakpoint was set on line 10 of `greetings.go` not `greetings_test.go`. If I put the breakpoint on line 10 of the test file, I also have the same issue you reported. That said if I out a breakpoint on line 17 of the test file (in VS Code), I still have the same issue with the scope/variables not set and the JS error in the console. 

What version of OS X do you guys run and what's your `dlv version` output?

**Comment by ramya-rao-a** [comment]
Is this still a problem?

**Comment by mattetti** [comment]
I haven't tried in the latest version you pushed recently but it was last
time I checked

**Comment by roblourens** [comment]
@mattetti I'm curious whether this will repro in 1.7, which you can try with the Insiders build, or it will be released this week. There was a lot of work done on the debugging code to support some new scenarios.

I was playing with a debug adapter trying to get it to produce the same error in vscode, but it seems like it should fail earlier in this scenario...

**Comment by mattetti** [comment]
@roblourens sorry about the delay I was traveling. 1.6.1 was broken, I just updated to 1.7.1 still have issues. The problem seems different now tho. I don't have any errors in the web console but the controls don't do anything.
![decoder_test_go_-_audio_and_debugger_navigation_seems_broken_ _issue__512_ _microsoft_vscode-go_and_release_notes__1_7_1_-_sample_fetcher](https://cloud.githubusercontent.com/assets/113/20506443/1b5f56d8-b009-11e6-9475-71440299b64e.png)

Here is my debugger config:

```
        {
            "name": "mp3 tests",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/mp3",
            "env": {},
            "args": []
        },
```

**Comment by roblourens** [comment]
Does that happen if you don't have any breakpoints set when you launch?

**Comment by mattetti** [comment]
No, if I don't have breakpoints it runs through the tests and ends as expected

**Comment by ramya-rao-a** [comment]
@mattetti 

Is this still a problem? From what I have gathered, the original problem no longer exists i.e the errors in the console logs and the navigation (step in/out/over) buttons being disabled.

What we have now is that breakpoints while in "test" mode are not working. Is that right?

In the last update we have enabled verbose logging for debugging. Can you add `"trace":"verbose"` or `"trace": true` to your launch config and try again?
This will put all the logging to a file (and also to the debug console if you have chosen "verbose") whose path will be printed out to the debug console.
If you share that with us, we can see which step exactly is failing

**Comment by ramya-rao-a** [comment]
Closing this issue as it hasnt seen any recent activity
