### ISSUE TITLE
Breakpoints are ignored

### ISSUE THREAD

**Issue by tapir** [Microsoft/vscode-go#513]
Tested both on VS Code 1.5.3 linux and windows. Delve ignores breakpoints. But otherwise runs okay. If there is a panic, I can see the call stack and the variables etc...

**Comment by ramya-rao-a** [comment]
@tapir I am able to hit breakpoints in Windows with go 1.7 and VS Code 1.5.3

Do you see the issue for all your Go projects? Can you try on a simple project like the Hello project in https://github.com/golang/example ?

Do you see any errors in the debug console?

**Comment by tapir** [comment]
Interestingly this now stopped happening. Let me first test on Linux as well before closing this, because there I'm using a previous version of VSCode.

**Comment by ramya-rao-a** [comment]
Closing this, as we haven't heard back. @tapir, feel free to re-open with more details if you still see the issue
