### ISSUE TITLE
Should have more color with variables, method, and properties

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode-go#514]
In current version. Package token and method and properties have the same color. We should use different color for them to easy recorgize.
In atom.
![atom](http://o8z0dg641.bkt.clouddn.com/QQ20161007-1@2x.png)
But in vscode
![code](http://o8z0dg641.bkt.clouddn.com/QQ20161007-0@2x.png)

**Comment by lukehoban** [comment]
The first screenshot appears to be cut off.  Could you describe what it is you are expecting?

The colorization for `.go` files is actually defined in VS Code itself at https://github.com/Microsoft/vscode/tree/master/extensions/go.  Depending on what change is expected, this may need to move to the VS Code repo.

**Comment by leaxoy** [comment]
All right. Got it. Closing
