### ISSUE TITLE
Go to definition and type info doesn't work with mux.Vars or anything else from gorilla/mux

### ISSUE THREAD

**Issue by DmitriyMV** [Microsoft/vscode-go#515]
I have no idea idea why - maybe because of the build tags? Other packages work fine.

**Comment by ironcladlou** [comment]
What platform and version of Go? I'm using `gorilla/mux` (and other Gorilla packages) and completion works fine for me (OSX 10.11.6 / Go 1.7).

**Comment by DmitriyMV** [comment]
`go version go1.7.1 linux/amd64`
`vs_code_1.6.0-1476123947_amd64`
Auto-complete works (suddenly, for some reason), but try to hover over mux.Vars function for example. In normal case, this should show function info, but it doesn't. Go to definition doesn't work either.

**Comment by ramya-rao-a** [comment]
I can repro this. We use `godef` for Goto definition and the hover features. When I hover over `mux.Router` it  returns an error `godef: no declaration found for mux.Router` 

This is an issue with `godef`. Can you open an issue in the repo for `godef` ?

**Comment by jadrio** [comment]
I have the same issue
OS Ubuntu 16.10
go version go1.7.1 linux/amd64
vscode 1.7.1 02611b40b24c9df2726ad8b33f5ef5f67ac30b44

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.50), we now support the use of `gogetdoc` for **Goto/Peek Definition, Hover info and Signature Help** features. Add `"go.docsTool": "gogetdoc"` to your setting to enable the use of `gogetdoc` and that should fix this issue.
