### ISSUE TITLE
Autocomplete for unimportted package don't work with third_party packages.

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode-go#516]
For the builtin package like `fmt`, `os`, this extension works well.
But for use downloaded packages like `github.com/golang/lint`, this feature broken.

**Comment by ramya-rao-a** [comment]
@leaxoy Are you saying that you are getting autcomplete for builtin packages like `fmt`, `os, `math` without importing them?

**Comment by leaxoy** [comment]
yes. for old version 0.6.43, but not work for third_party package like github.com/golang/golint

**Comment by ramya-rao-a** [comment]
That's interesting, I never got autocomplete to work on `fmt`, `os` etc without importing them.
That was one of the feature requests to get autocomplete working for unimported packages.
This has been implemented in the newest version of the Go extension Go 0.6.44

Are you working on Go 0.6.43 or the latest Go 0.6.44 ?

**Comment by leaxoy** [comment]
In actually, I use version 0.6.43, and auto-import work for builtin package. That's look amazing.
Today, I update to 0.6.44, no change made. Auto-import just work for builtin packages, third_party still dose't work for me. Is there any extra options to set?

**Comment by ramya-rao-a** [comment]
Sorry, I am not able to understand the issue.
Which of the below are you talking about?

- Autocomplete while typing code. Example: You type `fmt.Pr` and autocomplete gives you options for `fmt.Print`, `fmt.Printf`, `fmt.Println` etc.
- Autocomplete while importing packages. Example: You type `import "fm", and autocomplete gives you option for `fmt`
- Auto import when you save/format the document. Example: You type `fmt.Println("hello")`, then save/format the document, and `fmt` gets imported

**Comment by leaxoy** [comment]
1. `fmt` package not imported.
2. type `fmt` then press `.`, will show all method in package `fmt`.
3. Noticed, `fmt` is a builtin package.
4. Have `github.com/golang/lint` installed. Also not imported.
5. type `lint` and then press `.`, there is no hint appears.
6. And `github.com/golang/lint` is a third_party package.

**Comment by leaxoy** [comment]
All right! Version 0.6.44 dose this. Closing! 
Thank for patient answers😀

**Comment by ramya-rao-a** [comment]
@leaxoy Glad you are unblocked, but I am still not sure how you got Step 2 working in 0.6.43

> type fmt then press ., will show all method in package fmt.

That is a real mystery, because auto complete for unimorted packages was only added in 0.6.44 :)

**Comment by leaxoy** [comment]
It really work fine for me. It's so magical. And I am sure with the old version. Any way, third_party auto-import work well with new version(0.6.44).
Thank you!😀

**Comment by ramya-rao-a** [comment]
No problem, happy coding!
