### ISSUE TITLE
Integrate gogetdoc to VS Code Go extension

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode-go#517]
Types as functions as builtin like `println`, `int`, `float32` which belongs to `builtin` package dose not have doc. May be we can add those just like `atom` ext `go-plus` dose.

**Comment by ramya-rao-a** [comment]
Atom's go-plus uses `gogetdoc` for docs. Last I heard, there was some work to integrate `gogetdoc` to the VS Code Go extension.

@zmb3, @abarisain Any updates?

**Comment by abarisain** [comment]
It works pretty well, I'm hoping to submit a pr in the coming weeks. It lacks tests and some rebasing but it can be tested at abarisain/vscode-go on the gogetdoc2 branch

**Comment by ramya-rao-a** [comment]
@abarisain Thats great!

**Comment by leaxoy** [comment]
Thank you! 😀

**Comment by tbroyer** [comment]
Looks like this can be closed, with PR #622 merged and released in 0.6.50.

**Comment by abarisain** [comment]
Yes!

I'm having some issues with the performance of this, but I've yet to take time to open an issue.

**Comment by tbroyer** [comment]
There's a performance issue reported as #667 FWIW

**Comment by leaxoy** [comment]
Closing, please use issue #667 for performance talks!
