### ISSUE TITLE
MacOS is flooded with gocode processes

### ISSUE THREAD

**Issue by DirkWillem** [Microsoft/vscode-go#519]
Visual studio code spawns a lot of `gocode` processes, and after a while it is even impossible to run any other command line processes because there are too many processes running. This also makes my MacBook extremely sluggish

<img width="1070" alt="schermafbeelding 2016-10-09 om 22 22 11" src="https://cloud.githubusercontent.com/assets/3536557/19223409/3755e016-8e6f-11e6-986c-199929b3492f.png">

**My environment**
- MacOS sierra
- Visual studio code 1.5.3
- Go plugin 0.6.43

**Comment by ramya-rao-a** [comment]
Did you recently upgrade to sierra?
See if #503 helps

**Comment by ramya-rao-a** [comment]
@DirkWillem Did that help?

**Comment by ramya-rao-a** [comment]
@DirkWillem Closing this as #503 is tracking the issue with Go 1.7 and Sierra
If #503 does not help, then feel free to re-open this
