### ISSUE TITLE
Debugger pauses/hangs on call to external library (go-sqlite3)

### ISSUE THREAD

**Issue by inputusernamehere** [Microsoft/vscode-go#524]
In trying to use go with sqlite3 I've encounted an issue that I think is related to the vscode-go plugin's debugger.

Here is the smallest possible reproduction I could make:
https://gist.github.com/inputusernamehere/a809e01db846fee39b9cf9621d8f6d23
(I have ommited error checks in the above snippet, they don't make a difference as there is no error.)

When I try to launch this (default launch,json), I get this call stack:
http://i.imgur.com/lPxdL5n.png

As you can see it's supposedly paused at a breakpoint (I didn't set any). No matter how many times I continue nothing happens. If I step over or into, I reach a halted debugger state like in #473 with the same error message if I try to input anything in the debugging console.

Running the program through the command line with "go run main.go" works as expected.

Go: 1.7.1 windows/amd64
VSCode: 1.6.0
VSCode-go: 0.6.43

**Comment by roblourens** [comment]
Thanks for the repro! I see the same. I also see weird stuff when debugging with Delve, which we use. Maybe some issue with debugging that particular library.

![oct-12-2016 15-36-31](https://cloud.githubusercontent.com/assets/323878/19330172/b61cb522-9091-11e6-8ad6-87abbeca97fe.gif)

**Comment by roblourens** [comment]
This actually worked a few times, then I made a change to the program, and it stopped working again.

Better repro if I continue instead of step -
![image](https://cloud.githubusercontent.com/assets/323878/19330627/6f774e90-9094-11e6-917c-46972443d4e7.png)

I don't know what this implies. Is it just breaking on some error?

**Comment by inputusernamehere** [comment]
There's no error in the program itself, this can be seen here:

main.go: https://gist.github.com/inputusernamehere/a764333cd26d0c01681f4391bc88230d
main_test.go: https://gist.github.com/inputusernamehere/35f176a59e4fbb55bc679d1fde7bbdbc

Running this (go run main.go) works fine and outputs the expected result (12345). Running the test also works fine, passes and outputs the expected result without a hitch.

There is only an issue when it's ran/debugged with the default launch.json ("mode": "debug").

**Comment by roblourens** [comment]
Right I also see it run successfully when it isn't being debugged. I'm not sure whether it would be a problem with Delve, or something else that happens differently when the program is being debugged, vs run normally. Still a little new to Go.
