### ISSUE TITLE
languageservice: implementation as a languageservice?

### ISSUE THREAD

**Issue by mbana** [Microsoft/vscode-go#525]
Wondering if there is an example of using something like what's being done on some of the other , say, https://github.com/Microsoft/vscode-css-languageservice languages.

**Comment by ramya-rao-a** [comment]
You mean something like this: https://github.com/sourcegraph/sourcegraph-go/tree/master/langserver ?

**Comment by mbana** [comment]
do you have any plans to integrate this into the extension or the standalone language for that matter?

i've noticed that Monaco already has support for the Typescript via Web Workers etc. so I as wondering if you'll be doing the same any time soon.

The only approach I can think of is to recompile monaco-editor myself to include such support.

**Comment by ramya-rao-a** [comment]
There are plans to explore https://github.com/sourcegraph/sourcegraph-go/tree/master/langserver, but no set date yet.

**Comment by mbana** [comment]
OK, I've started to do some work on this:

- https://github.com/mbana/monaco-go
- https://github.com/mbana/vscode-go-languageservice

I'll keep you posted!

Thanks,

**Comment by ramya-rao-a** [comment]
@mbana We now have a branch that uses the language server by sourcegraph.
See #706

As and when the language server by sourcegraph gets more features, we can update the branch accordingly.

At this moment there is nothing specific to track from the VS Code Go extension's perspective.
Therefore, closing this issue
