### ISSUE TITLE
Add an option for logging

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-go#526]
In the Chrome debugging extension, I've found the 'diagnosticLogging' option really useful. It logs basically everything that happens within the extension to a file, and is easy to upload to github when reporting issues. It might be useful to look at how we can provide better logging to diagnose issues faster.

The non-debug part of the extension can log to a channel in the output pane, like Typescript, eslint, tslint, etc. We could log errors there, with a verbose mode to log everything. The input and output of all the external tools we use would be useful.

**Comment by ramya-rao-a** [comment]
The debug part is done with https://github.com/Microsoft/vscode-go/commit/0ea5206563ee196e187f2243ceae1bdb3d9b688a

**Comment by hyangah** [comment]
It's a great idea and we will follow up in https://github.com/golang/vscode-go/issues/54
