### ISSUE TITLE
Installing gotests FAILED

### ISSUE THREAD

**Issue by wudidong** [Microsoft/vscode-go#528]
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
package golang.org/x/tools/imports: golang.org/x/tools is a custom import path for https://go.googlesource.com/tools, but /Users/goll/gooo/src/golang.org is checked out from https://github.com/zieckey/golang.org

**Comment by ramya-rao-a** [comment]
Referring to https://github.com/golang/go/issues/9540 
You might have to delete `github.com/zieckey/golang.org/x/tools` and try `go get` again

**Comment by ramya-rao-a** [comment]
@wudidong did that help?

**Comment by wudidong** [comment]
thinks!
i am delete golang.org/x/tools is ok

**Comment by gertcuykens** [comment]
I believe there are still problems for mac users installing gotests https://github.com/cweill/gotests/issues/27

**Comment by gertcuykens** [comment]
removing `golang.org/x/tools/` fixed it for me too
