### ISSUE TITLE
Auto-import suggests package twice when file is dirty

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#529]
Type the below in a go file

`import "math"`

Don't save

Type `math`

Observe that autcomplete suggests math twice

**Comment by roblourens** [comment]
Related: 

Type `import "math"`, save.

Delete the import, don't save.

Type `math`, and appear that it's missing from autocomplete.

**Comment by ramya-rao-a** [comment]
The fix for this is out in the latest update (0.6.60)
