### ISSUE TITLE
GOPATH not recognized

### ISSUE THREAD

**Issue by dsbert** [Microsoft/vscode-go#533]
On osx, when launching vs code, I receive an error that GOPATH is not set.

```bash
$ echo $GOPATH
=> /Users/dan/projects/go
$ code .
=> code reports GOPATH is not set
```

**Comment by ramya-rao-a** [comment]
@dsbert Can you share what you get when you echo the $GOPATH from the integrated terminal inside VS Code?

**Comment by dsbert** [comment]
@ramya-rao-a 

Somehow PATH and GOPATH were reset between the time I opened the terminal session and the time I launched vs code. After fixing that, the extension is correctly detecting GOPATH.

**Comment by ramya-rao-a** [comment]
@dsbert glad you are unblocked, happy coding!
