### ISSUE TITLE
Off-by-one characters loss on word wrapping from 'go vet' output

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#538]
I have this piece of go code

```go
		conn, err := net.DialUnix("unix",
			&net.UnixAddr{clientUds, "unix"},
			&net.UnixAddr{mdscon.Config.UdsPath, "unix"})
		if err != nil {
			err = fmt.Errorf("Couldn't open UDS %q: %v", mdscon.Config.UdsPath, err)
		}
```

In the OUTPUT area, I see

```
Finished running tool: /Users/alp/gotools/golint

Finished running tool: /usr/local/bin/go tool vet /Users/alp/workspace/.../logprocessor.go
/Users/alp/workspace/.../logprocessor.go:172: net.Uni
ddr composite literal uses unkeyed fields
/Users/alp/workspace/.../logprocessor.go:173: net.Uni
ddr composite literal uses unkeyed fields
```

pay attention to line wrappings, they should be `net.UnixAddr` but instead, it is `net.Uniddr`.

When I run that `go tool vet` command myself, this doesn't happen.

**Comment by ramya-rao-a** [comment]
This is an issue with VS Code itself. It is fixed in the latest insiders build. You can try the insiders build at http://code.visualstudio.com/insiders or wait for the next stable release which should release early November
