### ISSUE TITLE
can't debug beego

### ISSUE THREAD

**Issue by shuqizhao** [Microsoft/vscode-go#539]
when i write a beego controller,i can't debug it.

**Comment by ramya-rao-a** [comment]
We would need more details...

Can you point to any sample code/repo where we can try to see what the issue is?

**Comment by northtyphoon** [comment]
@shuqizhao I was able to debug beego controller using the launch.json below
https://github.com/Microsoft/vscode-go#optional-debugging

You may want to check if you hit the delve issue in macOS Sierra.
https://github.com/derekparker/delve/issues/645

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from the OP regarding request to more details.
Please drop in a comment, if the issue still persists with more details.
