### ISSUE TITLE
dlv is searched in GOPATH/bin

### ISSUE THREAD

**Issue by ulrichSchreiner** [Microsoft/vscode-go#54]
The debugger is searched in by concat the GOPATH and `bin/dlv`. 

https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L109

As the other tools are now searched in the `PATH` or in the `GOPATH` it would be great to search `dlv` in the same way.

**Comment by ahmetalpbalkan** [comment]
+1

**Comment by lukehoban** [comment]
This should be fixed in the `0.6.11` version of the plugin.

**Comment by ulrichSchreiner** [comment]
Thank you. My version of [visualcode-go in a container](https://github.com/ulrichSchreiner/vsc) now works with debugging. If you have a linux box you can start it without downloading all the parts; you only need docker.

Two questions:

1. is there an option to set autosave to be "true" on startup? 
1. is there a command line client to install a extension? install it with a specific version? in my current version i git clone your extension ...

Thx

**Comment by lukehoban** [comment]
@ulrichSchreiner Awesome! 

/cc @egamma for possible help with these two questions.

1. I don't think there is a command line flag, but you can modify `storage.json` along the lines of [these instructions](https://code.visualstudio.com/Docs/supporting/FAQ) and set the `autoSaveDelay` property to `1000`.
2. I don't think so.  You can perhaps workaround this by `git clone`ing into `~/.vscode/extensions` this repo and then running `npm install` in the cloned folder.

**Comment by ulrichSchreiner** [comment]
1. i'll try it
2. that's what i do :-). but it would be great to have git-tags to clone a specific release
