### ISSUE TITLE
Duplicated import blocks

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#542]
Just encountered regression. I've been seeing this for the past few days, now I have a clear repro. I've seen this happening with other types of blocks like `var ( ... )` and just code lines.

### Repro steps

1. Create a new directory
2. Set GOPATH to that
3. `mkdir -p src/main`
4. Open in vscode
5. Create a file called main.go and open it, start typing `package main`
6. Follow the "Install All" button to install helper tools
7. Quit _without_ saving
8. Relaunch vscode (vscode-go version 0.6.44)
9. Type `package main`
10. Paste the following code (below)
11. Hit Cmd+S
12. Observe multiple imports.

Code:

```go
func tryParseApacheAccessLogMessage(line string) (*logMessage, error) {
	// Example: 00.00.00.000 - - [15/Sep/2016:06:57:21 +0000] "message text"
	splitIndex := strings.Index(line, " - -")
	if splitIndex < 0 {
		return nil, fmt.Errorf("Item delimiter not found in line %q", line)
	}
	if len(line) < splitIndex+32 {
		return nil, fmt.Errorf("Line doesn't contain a date in the required format %q", line)
	}
	dateText := line[splitIndex+6 : splitIndex+32]
	linedate, err := time.Parse(apacheAccessLogDateFormat, dateText)
	if err != nil {
		return nil, fmt.Errorf("Failed to extract date from %q out of line %q %v", dateText, line, err)
	}
	messageDictionary := make(map[string]string)
	messageDictionary[remoteAddressColumnName] = line[:splitIndex]
	return &logMessage{
		linedate,
		line[splitIndex+33:],
		messageDictionary,
		apacheAccessLog,
	}, nil
}

func tryParseJSONFormatMessage(line string) (*logMessage, error) {
	// Example: {"level":"info","msg":"message text","time":"2016-09-15T06:57:21.99545989Z","key":"value","key":"value","key":"value"}
	var decodeBucket interface{}
	if err := json.Unmarshal([]byte(line), &decodeBucket); err != nil {
		return nil, fmt.Errorf("Failed to decode the text to JSON %q", line)
	}
	dateStr := ""
	message := ""
	messageDictionary := make(map[string]string)
	hydratedMap := decodeBucket.(map[string]interface{})
	for k, v := range hydratedMap {
		sval, ok := v.(string)
		if !ok {
			fval, ok := v.(float64)
			if !ok {
				return nil, fmt.Errorf("Failed to convert value '%v' of the %q field into a string %q", v, k, line)
			}
			sval = strconv.FormatFloat(fval, 'f', -1, 64)
		}
		switch k {
		case "msg":
			message = sval
		case "time":
			dateStr = sval
		default:
			messageDictionary[strings.ToLower(k)] = sval
		}
	}
	if message == "" || dateStr == "" {
		return nil, fmt.Errorf("Required fields 'msg' and 'time' weren't found or were empty %q", line)
	}
	if len(dateStr) < 26 {
		return nil, fmt.Errorf("Date %q is not in the expected format %q", dateStr, jsonLogDateFormat)
	}
	date, err := time.Parse(jsonLogDateFormat, dateStr[:26])
	if err != nil {
		return nil, fmt.Errorf("Failed to extract date from %q out of line %q %v", dateStr, line, err)
	}
	return &logMessage{
		date,
		message,
		messageDictionary,
		jsonLog,
	}, nil
}

func tryParseErrorMessage(line string) (*logMessage, error) {
	// Example: 2016/09/27 20:16:48 message text
	if len(line) < 20 {
		return nil, fmt.Errorf("Not enough characters to contain an error message")
	}
	linedate, err := time.Parse(errorLineDateFormat, line[:19])
	if err != nil {
		return nil, fmt.Errorf("Failed to extract date from the line, so this is an unknown format message: %+v", err)
	}
	return &logMessage{
		linedate,
		line[20:],
		nil,
		errorLine,
	}, nil
}
```

Imports section becomes:

```go
import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"
)

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"
)
```

**Comment by ramya-rao-a** [comment]
The imports get added by the formatting tool (goreturns or goimports) which in your case is run on save. Can you confirm this by changing your format tool to gofmt and repeating your steps?

In the recent updates, the only change around formatting that was done was to use the -d flag while running the formatting tool. Can you set go.useDiffForFormatting to false, format tool to goreturns/goimports and try again?

**Comment by ramya-rao-a** [comment]
Note that you need to update the Go extension to 0.6.45 first

**Comment by ahmetalpbalkan** [comment]
I use the latest of everything. I shouldn't be changing any settings because I'm using all the default settings for `go.*` and I can still repro. I suggest you to try reproing this.

**Comment by ramya-rao-a** [comment]
Well, I am on vacation at the moment and only have my phone, so can't try to repro. Have to wait for the weekend for that.

The reason I asked you to try to turn off that particular setting (which was added in the latest update with the -d flag for the formatting tool) was to try to narrow down the root cause and was not offering that as a fix.

I will definitely try to repro once l get my hands on a computer

**Comment by ahmetalpbalkan** [comment]
@ramya-rao-a much appreciated. I wish I had a consistent way of reproing this as well... Yesterday this bug basically ate some of my code lines as well. I had a code block like this:

```
// functionName comment bla bla bla
// more bla bla bla
// even more bla bla bla
func functionName() {
    ...
```

and when I pasted this to a new file and saved, I realized only the line `// even more` and the rest was there because there was an import statement written and it replaced first few lines of my comment block. Just another symptom really, maybe it's the same bug, maybe not.

**Comment by ramya-rao-a** [comment]
@ahmetalpbalkan I tried your steps, but I can't repro it.

Can you ensure you are using the 0.6.45 version of the extension, set `go.useDiffForFormatting` to `false` and try again?

Using diffs from the formatting tool instead of formatted file was the only we change we did recently around formatting. If setting the above to false fixes your problem, then we can narrow down the problem.

**Comment by ramya-rao-a** [comment]
@ahmetalpbalkan ping?

**Comment by ahmetalpbalkan** [comment]
@ramya-rao-a I'm having trouble reproing this lately, sorry. We can close.
