### ISSUE TITLE
Searching for "go test" should lead to running tests as the first option

### ISSUE THREAD

**Issue by prashantv** [Microsoft/vscode-go#543]
See image:
![image](https://cloud.githubusercontent.com/assets/140159/19494026/13f00a92-9532-11e6-8a1d-124d94b814b6.png)

I think a user is much more likely to want to run unit tests when they search for "Go Test" than "Generate unit tests". Is there any way to improve the search matching, or rename the option so running unit tests is preferred over generating unit tests?

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#14727

**Comment by ahmetalpbalkan** [comment]
@ramya-rao-a since I realized it's not just me, perhaps we should have an ability to assign shortcut keys to these tasks?

**Comment by ramya-rao-a** [comment]
actually you can do that today.

You can find the commands here: https://github.com/Microsoft/vscode-go/blob/master/package.json#L79

You can assign keyboard shortcuts to any of the commands above
