### ISSUE TITLE
New test options makes it harder to run tests

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#544]
I used to just 
- Ctrl+Shift+p
- Type "test"
- Pick "Go: Test file"

now I have to hit the cursor 3 more times (because of the new items ranked on the top) to reach the same option...

![image](https://cloud.githubusercontent.com/assets/159209/19499151/bd8e5e16-9549-11e6-9e0a-a970174bcc50.png)

**Comment by ramya-rao-a** [comment]
Duplicate of #543
