### ISSUE TITLE
shift+F12 find all references , does it work for go??

### ISSUE THREAD

**Issue by wy3148** [Microsoft/vscode-go#548]
latest vs code 1.6 and latest vscode-go
this extension is fantastic!
But  it seems   'find all references' not working?

Does any one have any idea? thanks

**Comment by ramya-rao-a** [comment]
"Find all References" works well for me. I tried it in Mac OS X with latest VS Code, the latest Go extension and Go 1.6.3

-  Do you see "No results" or just "Loading.." or any errors?
-  Do you see any errors in the console when you `Developer: Toggle Developer Tools` and then try "Find all References"?
-  Is this a regression? As in was this working for you before and the latest update broke it?

Can you share your OS details and how you set your GOPATH?

**Comment by ramya-rao-a** [comment]
@wy3148 Do you still have issues with Find all references?

**Comment by wy3148** [comment]
@ramya-rao-a 
Thank you , I verified again,
my env is mac os, 10.11.6 , 64 bit, latest vs and go extension,
 it looks like it is about some specific go func I implemented in my project, it shows 'no result', for some functions I 'm able to find references, see attached screenshots. 
So it kinda works, but maybe not always, I'm not sure.

![screen shot 2016-10-27 at 2 24 01 pm](https://cloud.githubusercontent.com/assets/3363899/19753557/5e017b7c-9c51-11e6-8f34-d959b0d33200.png)

![screen shot 2016-10-27 at 2 35 02 pm](https://cloud.githubusercontent.com/assets/3363899/19753700/a903e064-9c52-11e6-9548-1198508560b2.png)

![screen shot 2016-10-27 at 2 29 17 pm](https://cloud.githubusercontent.com/assets/3363899/19753611/db60bff6-9c51-11e6-8605-a551f8055d1e.png)

**Comment by ramya-rao-a** [comment]
Do you get any build errors in the output channel for Go?
Do you see any errors in the console? (Developer: Toggle Developer Tools)

**Comment by wy3148** [comment]
no, I didn't.
I think I can close this issue, I think one of the possible reason I didn't get the reference is some functions are having same name but different input arguments (means actually they are different go funcs), in this case , VS returned "no results' when I tried to search, and the go func i searched was not called in anywhere.
