### ISSUE TITLE
Not able to install package

### ISSUE THREAD

**Issue by mukeshdutt5** [Microsoft/vscode-go#551]
Getting "package golang.org/x/tools/go/buildutil: remote origin not found" message while i'm using
"go get -u github.com/newhook/go-symbols" command.

**Comment by ramya-rao-a** [comment]
@mukeshdutt5 I am able to install `go-symbols` without any problem.
Do you still see this issue?

**Comment by ramya-rao-a** [comment]
Closing this, as we havent heard back from the OP. @mukeshdutt5 feel free to re-open if you still see the same issue

**Comment by mukeshdutt5** [comment]
Now I'm able to download.
Thanks.
