### ISSUE TITLE
keywords missing from completions list

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#558]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

e.g. below, "import" is missing, but everything else is also missing from the completions list. 
![image](https://cloud.githubusercontent.com/assets/762848/19742634/d1839382-9b7a-11e6-9f5a-845237dc8f18.png)

**Comment by ramya-rao-a** [comment]
We use `gocode` for autocomplete + a little extra that we do on our on like

- support for unimported packages
- "package" completion with either "main" or the folder name

https://github.com/nsf/gocode/issues/312 explains why there is no completion for keywords like 

- import
- func
- struct 
etc.

What are you referring to when you say
> but everything else is also missing from the completions list.

**Comment by mousetraps** [comment]
"everything else" == all other keywords :smiley:

Re: the issue linked to (nsf/gocode#312) doesn't seem to provide much of a reasoning as to *why* there are no completions for keywords - just says that there are no completions. May be worth considering contributing upstream because otherwise this behavior is inconsistent w/ the rest of the language services we integrate with

**Comment by ramya-rao-a** [comment]
Now that we have the whitelist of keywords in https://github.com/Microsoft/vscode-go/blob/master/src/util.ts#L16, this is very easy to implement, if anyone wants to take a crack at it.

Hint: Start at `goSuggest.ts`

**Comment by fnouama** [comment]
+1

**Comment by ramya-rao-a** [comment]
The latest update (0.6.56) to the Go extension has this feature.
