### ISSUE TITLE
Poor sorting for completions list

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#559]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

The list is sorted alphabetically, rather than by relevance. 
![image](https://cloud.githubusercontent.com/assets/762848/19742765/688f6738-9b7b-11e6-84fe-a3d9dc5bfa77.png)

**Comment by ramya-rao-a** [comment]
Note from Gitter conversation that also talks about sorting/positioning the items in completion list:

> After last plugin update in autocompletion list I got list of all available packages, it's pretty cool but little annoying because variables with corresponding names appears in the end of a list. It would be nice to sort this list and show variables on top

**Comment by ramya-rao-a** [comment]
This is not repro-able any more. Therefore closing
