### ISSUE TITLE
Generating unit tests should only apply to go files

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#563]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

In this case, no test is actually generated, but a status bar messages appears claiming successful test generation. 
![image](https://cloud.githubusercontent.com/assets/762848/19743811/b066987a-9b7f-11e6-94d2-de8244f19887.png)

**Comment by ramya-rao-a** [comment]
The latest update (0.6.48) has the fix.
