### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#564]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

Not sure if I'm doing something wrong, but I can't seem to get the debugger to launch on a basic hello world app.
![image](https://cloud.githubusercontent.com/assets/762848/19744107/e3a1c74a-9b80-11e6-895e-8b6656c5d49f.png)

**Comment by sinhpham** [comment]
I have the same problem, is there any workaround? Or how can I downgrade to the previous version of the extension?

**Comment by sinhpham** [comment]
This commit looks suspicious https://github.com/Microsoft/vscode-go/commit/49388254f9467e0df71354770d3292d0fb7dd150

**Comment by soechin** [comment]
same problem.

**Comment by jeremywho** [comment]
Same thing for me on OS X.

**Comment by noxyal** [comment]
Same for me on macOS Sierra version 10.12.1

As far as workarounds, you can run the app normally (without the debugger):
1) Open Integrated terminal (ctrl+`) 
2) Run the following command:
> go run yourFileName.go


The recent macOS update seems to have created some issues for delve which might be related to this issue. See: https://github.com/derekparker/delve/issues

**Comment by roblourens** [comment]
The problem is this commit, which pulls in 'window' from the 'vscode' module - https://github.com/Microsoft/vscode-go/commit/c35b419585d403a4cd042856afaf46051ae389cf, which isn't available from the debug adapter. The import was there before, but since it was only pulling in types, typescript didn't output the `require`.

We need a total separation between code that runs in the debug adapter, and code that runs in the extension host (or very careful sharing).

**Comment by roblourens** [comment]
No, I take that back sorry - the problem was https://github.com/Microsoft/vscode-go/commit/49388254f9467e0df71354770d3292d0fb7dd150#diff-16e876ed2a6ddf6a530a935e37dddfdb which pulls in util.ts, which shouldn't be in the debug adapter. I'll make a PR.

**Comment by roblourens** [comment]
Uhh... I can fix the crash but I'm just getting `could not launch process: could not get thread count` from delve right now

**Comment by ramya-rao-a** [comment]
does delve work from the command line?

**Comment by roblourens** [comment]
No

**Comment by ramya-rao-a** [comment]
@sinhpham @soechin @jeremywho A new updates is out (0.6.47) with the fix. Can you confirm that the issue is fixed for you?

The Mac Sierra 10.12.1 still has problems with delve itself which is tracked in https://github.com/derekparker/delve/issues/645

**Comment by soechin** [comment]
0.6.47 fixed, thank you.

**Comment by sinhpham** [comment]
Yep the latest version fixed it for me. Thanks.

**Comment by ramya-rao-a** [comment]
Great, happy coding!
