### ISSUE TITLE
debugger should warn if "program" property doesn't exist

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#565]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

This would help diagnose potential typos/issues in launch.json (esp helpful if files have moved around)

**Comment by ramya-rao-a** [comment]
cc @roblourens thoughts?

Right now, we have a default which points to cwd if the program attribute is not specified

**Comment by roblourens** [comment]
Node debugger checks whether "program" exists, and fails if not.

**Comment by roblourens** [comment]
I don't know what delve is doing though

**Comment by ramya-rao-a** [comment]
@mousetraps When I delete the program property from launch.json and try debugging I get the below error "Failed to continue: "TypeError: Path must be a string. Received undefined"" which I believe is coming from VS Code itself. 

Is that what you were referring to?
