### ISSUE TITLE
Generating unit tests should open or link to generated test file

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#566]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

Right now, the test file is generated, but then the user has to figure out where, exactly, they got dropped. There should either be a button in the infobar that opens the generated test file, or the file should open automatically in the editor.

**Comment by ramya-rao-a** [comment]
Also, the message that is shown at the end of generating tests can be better.
Example:

- Say 2 out of 3 functions in the file `hello.go` already have the tests in `hello_test.go`, then the message should only mention the test for the 3rd function
- Say all functions in the file `hello.go` have the tests in `hello_test.go`, then the message should say that no new tests were created.

etc.
