### ISSUE TITLE
IntelliSense should not appear within multiline strings

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#569]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

![image](https://cloud.githubusercontent.com/assets/762848/19745361/29bcbdca-9b86-11e6-84d1-22b4badc9b70.png)

**Comment by ramya-rao-a** [comment]
Not just multiline, you see this with single line strings as well.
If the string is surrounded with double quotes, you don't see this. 
Labeling as bug

**Comment by ramya-rao-a** [comment]
In the March 2017 release of VS Code, suggestions will not be triggered inside strings. See https://code.visualstudio.com/updates/v1_11#_intellisense-in-comments

**Comment by ramya-rao-a** [comment]
Oh wait, it still shows up pressing `.`

**Comment by Strum355** [comment]
Any ETA on this? PR was submitted, just awaiting review :)

**Comment by ramya-rao-a** [comment]
Hey @Strum355,

I have some concerns on parsing the entire file for every auto-completion attempt.
Also, I am a little held up at work, but I'll get to the PR soon either this week or the next.

Thanks very much for your patience.

**Comment by Strum355** [comment]
Im not sure how else we can reliably tell whether or not in a raw string without scanning the file for how many backticks preceed the current cursor position. 
Naturally we have to not count the backticks that reside in single or multiline comments, hence we have to check for those states as well

**Comment by ramya-rao-a** [comment]
@stamblerre Will `gocode` or the language server know enough about the file contents to not provide completions from insider multi line strings? If yes, then I am inclined to not fix this issue from the extension's side and rely on `gocode` or the future language server to solve it for us.

**Comment by stamblerre** [comment]
@ramya-rao-a: yes, gopls will be able to handle that. Filed [golang.org/issue/30477](https://golang.org/issue/30477).

**Comment by ramya-rao-a** [comment]
Thats good to hear, thanks @stamblerre!

@Strum355 Since we should soon be able to handle this from the language server, I am closing this issue. Parsing the entire file for each completion request can get expensive on large files and affect performance. Thanks for your effort on this and apologies that we cannot take the PR in.
