### ISSUE TITLE
Renaming variable does not put file into a dirty state

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#570]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

Instead, the file gets saved immediately after rename, even though autosave is off.

**Comment by ramya-rao-a** [comment]
In Windows, you need to have the `diff` tool installed for the rename to work with diffs. Else it renames the file on disk.

Can you install the diff tool say from [Diff Utils for Windows](http://gnuwin32.sourceforge.net/packages/diffutils.htm) and try again?

**Comment by mousetraps** [comment]
Thanks, that fixed it! Is that documented somewhere? (other than here?) Also may be worth adding a settings.json option so that it's clearer that it's a dependency.

**Comment by ramya-rao-a** [comment]
I agree that it should be documented. What do you mean by 
>adding a settings.json option so that it's clearer that it's a dependency.

**Comment by mousetraps** [comment]
I was thinking that the path to the diff tool could be an option in settings.json in order to improve discoverability to a user that that's something they may want to install. But it sounds like it's not the vscode-go extension, but rather one of its dependencies (gorename) that flakes out when the diff tool isn't there. So maybe improved docs or auto-detection of some sort?

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode-go/commit/64b3bde341367ac666e5e3878dc83a8d9100842a adds the note about needing the `diff` tool in Windows for undo after rename to work
