### ISSUE TITLE
code completion produces invalid package identifier

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#571]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

![image](https://cloud.githubusercontent.com/assets/762848/19748150/dcad0562-9b94-11e6-9074-1bfe153301b5.png)

**Comment by ramya-rao-a** [comment]
The package line can either be "package main" or "package <the-folder-name>" which is what auto-complete tries to help with here.
In your case why would "hello-go" be an invalid package identifier?

**Comment by mousetraps** [comment]
Ahh, turns out the reason the identifier was invalid was because it included the "go" keyword - I thought it was because of the dash. Closing as this edge case doesn't seem important enough to handle.
