### ISSUE TITLE
code completion list appears too liberally

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#573]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

In the case below, the completions list shouldn't appear after the closing quote, otherwise an unintended result will be committed after the user presses "enter" to begin a new line.
![image](https://cloud.githubusercontent.com/assets/762848/19748301/9dad4ef2-9b95-11e6-83a9-1e1ef00e9b52.png)

**Comment by ramya-rao-a** [comment]
Also, completion list kicks in after an escaped double quote inside a string

<img width="301" alt="screen shot 2016-10-30 at 3 45 49 pm" src="https://cloud.githubusercontent.com/assets/16890566/19840660/4472443e-9eb8-11e6-90f1-e6e6dc3ea017.png">
