### ISSUE TITLE
Not all launch.json "mode" suggestions appear in completions list

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#574]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

"debug" appears, but I also expect to see "test" and "exec"
![image](https://cloud.githubusercontent.com/assets/762848/19748468/aaeaab4a-9b96-11e6-98c0-04bf57dd2785.png)

**Comment by roblourens** [comment]
FYI @ramya-rao-a
