### ISSUE TITLE
Cannot debug after update

### ISSUE THREAD

**Issue by andiyudistira** [Microsoft/vscode-go#575]
I got this error message while trying to debug my go app after update the plugin to version `0.6.46 - 26th October 2016`:
`Debug adapter process has terminated unexpectedly`

I can debug without any issues before I update the plugin.

**Comment by i5on9i** [comment]
Me, either. I've just installed Go plugin, but it doesn't work with the error message like the "andiyudistira " said

**Comment by ramya-rao-a** [comment]
Any errors in the console (Run `Developer: Toggle Developer Tools` and check the console) or in the Go channel in the output window?

In your launch.json, do you have a port configured?

cc @roblourens

**Comment by i5on9i** [comment]
i've posted errors here again,
and, i didnt set the port.
i used the config like the below
```
{
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "run",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
},
```

[![11.png](http://s11.postimg.org/758wogxtv/image.png)](http://postimg.org/image/4b5rb0vnj/)

**Comment by lukehoban** [comment]
See also https://github.com/Microsoft/vscode-go/issues/564 which appears to be the same issue.

**Comment by ramya-rao-a** [comment]
@andiyudistira @i5on9i  A new updates is out (0.6.47) with the fix. Can you confirm that the issue is fixed for you?

**Comment by i5on9i** [comment]
cool~ it works well , thanks @ramya-rao-a

**Comment by andiyudistira** [comment]
Cool, it works fine now thanks @ramya-rao-a 👍

**Comment by ramya-rao-a** [comment]
Glad you are unblocked, happy coding!
