### ISSUE TITLE
completion doesn't show latest version of the file

### ISSUE THREAD

**Issue by didrocks** [Microsoft/vscode-go#579]
Thanks for your great plugin! That was definitively the selling point to me to use VSC :)

However, being up to date on latest plugin version and VCS (1.6.1), I notice I have some issues in completion not being up to date. I'm running Linux (Ubuntu 64 bits 16.04LTS). I'm running latest updated tip (hash 478b96f) gocode with Go 1.7

I reported this bug as well to gocode directly (https://github.com/nsf/gocode/issues/397), but I wonder if the issue isn't in vcs/the go plugin itself.

I did notice some staled cache on my packages, and the new/removed exported structs, variables, or any data fields were not seen by gocode when requesting completion.

On every save, you execute <path_to>/go build -o /tmp/go-code-check -tags "" . and when completion is requested, the static libraries .a files for each package are generated. Gocode seems to use them as a reference.

ls -l $GOPATH/pkg/linux_amd64/<path_to_project>/                                                                                         total 32
-rw-rw-r-- 1 didrocks didrocks  3252 oct.  27 14:29 dirs.a
-rw-rw-r-- 1 didrocks didrocks  8644 oct.  27 14:29 logger.a
-rw-rw-r-- 1 didrocks didrocks 16076 oct.  27 14:29 state.a
I notice that, making a (valid) change to the state package for instance, that gocode doesn't regenerate state.a (still same size and timestamp), and so, doesn't offer the new exposed struct. However, running

gocode close
gocode --debug -s
shows the partially new state file content. For instance:
Adding Abc struct for testing:

```
package state

// State that can be a snap in
type State struct {
    Channel  string
    DevMode  bool
    Revision string
    Version  string
}

// Transition from one state to another one
type Transition struct {
    Action Action
    Next   *State
}

// Action associated to a Transition
type Action int

const (
    // Install or update a snap
    Install = iota
    // Revert a snap
    Revert
    // Remove a snap
    Remove
)

type Abc strin#
2016/10/27 14:44:38 -------------------------------------------------------
2016/10/27 14:44:38 Found "io/ioutil" at "/home/didrocks/tools/go/pkg/linux_amd64/io/ioutil.a"
2016/10/27 14:44:38 Found "path" at "/home/didrocks/tools/go/pkg/linux_amd64/path.a"
2016/10/27 14:44:38 Found "github.com/ubuntu/snaps-manager/dirs" at "/home/didrocks/workspace-go/pkg/linux_amd64/github.com/ubuntu/snaps-manager/dirs.a"
2016/10/27 14:44:38 Found "github.com/ubuntu/snaps-manager/logger" at "/home/didrocks/workspace-go/pkg/linux_amd64/github.com/ubuntu/snaps-manager/logger.a"
2016/10/27 14:44:38 Found "gopkg.in/yaml.v2" at "/home/didrocks/workspace-go/pkg/linux_amd64/gopkg.in/yaml.v2.a"
2016/10/27 14:44:38 Offset: 5
2016/10/27 14:44:38 Number of candidates found: 1
2016/10/27 14:44:38 Candidates are:
2016/10/27 14:44:38   type string built-in
2016/10/27 14:44:38 =======================================================
```

and state.Abc isn't proposed on autocompletion. If you look closely, `Abc string` isn't complete (compared to file on disk). Would that we why state.a isn't regenerated (triggering a failed compilation too early?), but nothing is showing this in gocode logs.

The .a files are unchanged on disk. Removing them and requesting completion again fixes it once they are regenerated.

Could that be an issue with Visual Studio Code go plugin itself, handling this recompile too early?
Any idea or need more debug info? Thanks!

**Comment by ramya-rao-a** [comment]
Correct me if I am getting this wrong.

You have a package called "state" where you have defined the types State, Transition, Action, and Abc
You have another file where you have imported the package "state" and are typing "state.a" expecting autocomplete to suggest "Abc"

Now back in the file that defines the types, you are changing the "Abc" type and you expect the package state.a to get updated before you save the file.

Is this correct?

**Comment by didrocks** [comment]
Not exactly. I have a state packages where I defined State, Transition, Action. I defined there Abc, and save the file.
I do expect then that state.A would propose Abc in another file, which isn't the case. There is a race between Visual Studio Code and gocode, making the .a file not being regenerated, and so, no completion is proposed with the newly defined Abc.

**Comment by ramya-rao-a** [comment]
Do you have the gocodeautobuild setting set to true?

**Comment by didrocks** [comment]
I kept the default, which is set to true, indeed, should I turn it off?

**Comment by ramya-rao-a** [comment]
No, you don't need to turn it off, I'll get back to this thread once I try to repro this again

**Comment by ramya-rao-a** [comment]
@didrocks Sorry for not getting back on this sooner. 

> On every save, you execute <path_to>/go build -o /tmp/go-code-check -tags "" . and when completion is requested, the static libraries .a files for each package are generated. Gocode seems to use them as a reference.

From the past couple of releases, on every save when we run `go build`, the `-i` flag is passed as well. This ensures all the dependent packages of the current package are built and their corresponding .a files are up to date.

Also `gocode` is no longer called with `autoBuild` enabled by default due to a few reasons
- The `-i` passed to `go build` ensures dependent packages are up to date
- The `autoBuild` feature of `gocode` has shown to affect performance in larger projects
- The `gocode` author's lack of confidence in the autoBuild feature

With these changes in, do you still see the issue you originally reported?
