### ISSUE TITLE
Extension process makes Macbook Air fan goes crazy!

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode-go#58]
_From @Totoajax on November 20, 2015 17:9_

Since the new update (0.10.1) my Macbook Airs fan sounds like a jet engine!!! If this isn't a bug, please make an option to disable some of the new things to make it quiet again. I REALY REALY loves Visual Code, so please fix this!

_Copied from original issue: Microsoft/vscode#364_

**Comment by lukehoban** [comment]
_From @Totoajax on November 20, 2015 17:52_

I tracked it down, and found that it's the plugin handler or something. I could close it from activation control. I forgot what it was called. But now it works perfectly (But I guess the plugins won't work)

**Comment by lukehoban** [comment]
_From @Totoajax on November 20, 2015 18:20_

It's called "electron helper" and takes 99% of CPU usage

**Comment by lukehoban** [comment]
_From @bpasero on November 20, 2015 20:51_

@Totoajax what extensions do you have installed?

**Comment by lukehoban** [comment]
_From @Totoajax on November 20, 2015 22:10_

@bpasero Go and bookmarks. I'm gonna try remove them and see if it works

**Comment by lukehoban** [comment]
@Totoajax Did removing these extensions fix the issue?  If so, did you get a chance to identify which extension was causing the issue?

**Comment by lukehoban** [comment]
_From @Totoajax on November 22, 2015 1:20_

@lukehoban I've now worked with vs code for a long time after removing the extensions. And it works perfect! The extension that made the fan go crazy was Go. I installed bookmarks after the first sounds came. BUT I haven't tried to run only with bookmark, so I can't say there's not a problem with bookmarks

**Comment by lukehoban** [comment]
Okay - since this was caused by the Go extension I'll move it over to that repo to investigate further.

**Comment by lukehoban** [comment]
@Totoajax A few follow-up questions in case you have the info:

1. What OS were you on?
2. Were you working with `.go` files, or did you see this even in VS Code sessions when you didn't open any `.go` files?
3. If you were working with `.go` files, is the project you were working on something you can provide a pointer to?

**Comment by Totoajax** [comment]
@lukehoban 
1. OS X 10.11.1
2. No, I never opened a .go file.
3. /\

**Comment by Totoajax** [comment]
@lukehoban I've no idea how. But the spinning fan is back again, and it's because of Electron Helper again at 99% CPU usage. Look's like it's not Gos fault after all

**Comment by lukehoban** [comment]
Closing for now instead of moving back again, but if you find more info to help narrow down what's happening feel free to reopen the original issue in the `vscode` repo.
