### ISSUE TITLE
win10 vscode debugging, can't add/remove breakpoint.

### ISSUE THREAD

**Issue by wildfire810** [Microsoft/vscode-go#580]
1. What version of Delve are you using (`dlv version`)?
   Delve Debugger
   Version: 0.11.0-alpha
   Build:
2. What version of Go are you using? (`go version`)?
   go version go1.7.1 windows/amd64
3. What operating system and processor architecture are you using?
   win10 64bit
4. What did you do?
   At the debugging time, add/remove breakpoint
5. What did you expect to see?
   added breakpoint can pause, and removed breakpoint should pass
6. What did you see instead?
   contrary, until restart debug, all that will be valid

**Comment by jcdickinson** [comment]
1. What version of Delve are you using (dlv version)?
  > Delve Debugger
  > Version: 0.11.0-alpha
  > Build:

2. What version of Go are you using? (go version)?
  > go version go1.7.1 windows/amd64

3. What operating system and processor architecture are you using?
  > win10 64bit home anniversary

**Comment by ramya-rao-a** [comment]
@wildfire810 @jcdickinson Sorry that you are not able to get debugging working properly with VS Code.

Which version of VS Code and the Go extension are you using? Can you update both to the latest?

Also `dlv` has released 0.12.0. Can you update dlv as well `go get -u -v github.com/derekparker/delve/cmd/dlv` and give another try?

Are you able to run `dlv` in the command line and add breakpoints, step in/out etc?

**Comment by wildfire810** [comment]
The bug is report at Oct 2016
Now it works right.
All of the versions are
go version go1.7.5 windows/amd64
vs code 1.8.1
vs code go plugin 0.6.52
delve 0.12.1

In any case, I am a microsoft fans, I love VisualStudio, I love C#, I love Windows.

**Comment by ramya-rao-a** [comment]
Thanks @wildfire810!
Glad to know you are unblocked. Happy Coding!

Closing this issue for now.

@jcdickinson, if you still see the same problem, please drop a comment, I'll reopen the issue and we can investigate.

**Comment by tunggiga** [comment]
I have the same issue, can you help me?

1. What version of Delve are you using (dlv version)?
Delve Debugger
Version: 1.0.0-rc.2
Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c $
2. What version of Go are you using? (go version)?
go version go1.8.3 windows/amd64
3. What operating system and processor architecture are you using?
win10 64bit
4. What did you do?
At the debugging time (when the program is running and not paused), add/remove breakpoint
5. What did you expect to see?
added breakpoint can pause, and removed breakpoint should pass
6. What did you see instead?
contrary, the breakpoint is marked unverified with grey color, until restart debug, all that will be valid

**Comment by aarzilli** [comment]
@tunggiga you'll probably have better luck reporting this to the [vscode plugin](https://github.com/Microsoft/vscode-go)

**Comment by tunggiga** [comment]
@aarzilli I don't get it. Doesn't that link point to this repository?

**Comment by aarzilli** [comment]
@tunggiga yep, my mistake.

**Comment by ramya-rao-a** [comment]
@tunggiga 

> At the debugging time (when the program is running and not paused), add/remove breakpoint

This is not supported at the moment. Delve only allows adding/removing breakpoints when the program is paused
