### ISSUE TITLE
Extract Method feature

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#588]

**Comment by Vinicioslc** [comment]
We need this

**Comment by jijeshmohan** [comment]
How about integrating [godoctor](http://gorefactor.org/index.html) which has the same feature ?

**Comment by ramya-rao-a** [comment]
We did try godoctor back in July, but it had a few limitations. See #370 for the discussions that followed.

**Comment by ramya-rao-a** [comment]
Another way to go about this would be to use the "free variables" feature from guru if anyone wants to give this a try

**Comment by Hades32** [comment]
I just tried the current 0.5 version of GoDoctor and it seems to handle simple cases (including the not so simple multiple return values) just fine and would IMO be an improvement over _nothing_.

Maybe you could re-re-review :)

**Comment by ramya-rao-a** [comment]
Thanks @Hades32! That's good to know 

Anyone willing to give this a try can use #370 as a reference

**Comment by mgood** [comment]
Sorry to be a bit pedantic, but just wanted to note that this should be called "extract function", since "method" refers specifically to [a function with a receiver](https://golang.org/ref/spec#Method_declarations), e.g. `func (p *Point) Length() float64`. Extracting code into a method would also be a nice feature to have, but that could be a special case to add after the initial support for extracting functions.

**Comment by ramya-rao-a** [comment]
@conradwt No one is working on this at the moment as far as I know.

**Comment by blackdahila** [comment]
@ramya-rao-a I'd like to work on that 🙂

**Comment by aswinmprabhu** [comment]
@ramya-rao-a I had a go at this issue [here](https://github.com/aswinmprabhu/vscode-go/commit/61a8230bcccb99f1beace3e310045633cca0452e). I also added "Extract expression to local variable" feature to see if it works [here](https://github.com/aswinmprabhu/vscode-go/commit/1654d62d23287b4e8adc5ce4e960c4133561a730). It seems to work for all the simple examples I tried. I would be happy to make a PR if its good enough.

**Comment by ramya-rao-a** [comment]
> I would be happy to make a PR if its good enough.

@aswinmprabhu Make the PR regardless :) I am sure we can work together to get the feature in.

**Comment by conradwt** [comment]
@aswinmprabhu Good work and I agree with @ramya-rao-a 200% that you should make a PR regardless.

**Comment by aswinmprabhu** [comment]
Thanks @ramya-rao-a and @conradwt.
Check out #404

**Comment by ramya-rao-a** [comment]
The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension has this feature. Please see [Refactoring in VS Code](https://code.visualstudio.com/docs/editor/refactoring) on how you can use the refactor feature.

Thanks @aswinmprabhu!

**Comment by ramya-rao-a** [comment]
This feature is out in the latest release(0.10.0) of the Go extension

We have noticed a few cases where godoctor doesn't as expected. Therefore, the features are available as the below commands, but not as default refactoring as detailed in [Refactoring in VS Code](https://code.visualstudio.com/docs/editor/refactoring)
- `Go: Extract to function`
 - `Go: Extract to variable`
