### ISSUE TITLE
Add setting to lint whole workspace rather than just the current package

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode-go#589]
Example steps:

1. Edit `foo.go` (package `bar`) with some syntax error.
2. Panel correctly shows error.
3. Edit `foo_test.go` (package `bar_test` in same folder) with some syntax error and save.
4. Fix error in `foo_test.go` and save.
5. Error panel is confusingly empty, even though `foo.go` still has syntax errors.
6. Switch to `foo.go`. Panel stays empty.
7. Make a dummy modification and save file.
8. Panel now correctly shows errors for `foo.go`.
9. That's terrible.

In other words, the panel only shows errors for current package, and requires a dummy modification + re-save of a failing file in order to re-display errors if it i's in a different package from the one that previously failed.

More generally, I want VSCode to behave like any IDE: Show errors across my entire project.

For example: Let's say I rename a field in a public struct that's used by other packages. I want to see _all subsequent errors_ from _all packages in my project_ that are using that struct and no longer work. I don't want to build the project to see those errors, and I don't want to randomly save files just to trigger linting.

Surely this must be an extremely common desire.

(Apologies if there's an existing issue for this; I couldn't find it.)

**Comment by ramya-rao-a** [comment]
Funnily enough, there is an issue asking for linting ONLY in current package
#505 

`golint` does have the option of linting a whole directory. Would adding a setting to lint the whole workspace work for you?

**Comment by atombender** [comment]
Yeah, I don't understand that issue.

So I just realized I was using `golint` instead of `gometalinter`. When I enable the latter, I seem to be getting workspace-wide errors. Maybe close this, then.

**Comment by ramya-rao-a** [comment]
That's interesting, I didnt know that.

If `gometalinter` does the job, and you don't mind using it (it runs a bunch of linters including `golint`) then yes, go ahead and close this.

**Comment by atombender** [comment]
Thanks! It would be a good idea to document this behaviour. I find `golint` quite limited, myself.

**Comment by ramya-rao-a** [comment]
@atombender Are you sure you are getting workspace-wide errors even when your workspace has multiple packages?

I tried `gometalinter` on a workspace with multiple packages, and I see linting errors (on save) scoped to just the package to which the current file that is open belongs to

**Comment by atombender** [comment]
I spoke too soon. I'm actually seeing the same behaviour as described originally.

I think what happened was I made some test errors in `somepkg` and `somepkg/nestedpkg`. It looks like `gometalinter` is invoked recursively, so it will return errors for both packages. So that works correctly, but it led me to think the issue was resolved.

It seems there's no way to make it run on the whole workspace (i.e. the root folder of the workspace), other than hard-coding the project name into `go.lintFlags`.

**Comment by ramya-rao-a** [comment]
Both `gometalinter` and `golint` take directory to lint as a parameter. It defaults to `cwd` if none is provided. The Go extension sets `cwd` to the directory to which the current open file belongs to.

We can add a setting to lint the whole workspace while keeping linting current package as the default option.

**Comment by atombender** [comment]
That sounds like a good idea.

**Comment by ramya-rao-a** [comment]
In the latest update (0.6.62):

Set `go.lintOnSave` to `workspace` to lint whole workspace than just the current package.

Same can be done to `go.buildOnSave` and `go.vetOnSave` as well
