### ISSUE TITLE
Install tools does not use go.goroot project setting. 

### ISSUE THREAD

**Issue by tw1nk** [Microsoft/vscode-go#592]
When I setup a go.goroot project setting I expect that the install tools would use the go command installed in that location, and not try to find it from the $PATH environment variable.

I have a setup where I want different tooling and different versions of the go environment for different projects and they should all be self contained. 

Output:

```
Installing 1 tools
  goreturns

Installing goreturns FAILED

1 tools failed to install.

goreturns:
Error: Command failed: go get -u -v sourcegraph.com/sqs/goreturns
/bin/sh: go: command not found
/bin/sh: go: command not found
```

**Comment by ramya-rao-a** [comment]
The latest update (0.6.48) has the fix. 
Happy Coding!

**Comment by NaifAlrashed** [comment]
Hello, it seems that I am having the same issue, and even in the manual installation, which is this
`go get -u -v sourcegraph.com/sqs/goreturns`
the repo for gorutine seems to have moved.
