### ISSUE TITLE
Debugging: support 'launchBrowser' in launch.json

### ISSUE THREAD

**Issue by xinyanmsft** [Microsoft/vscode-go#593]
It appears 'launchBrowser' is not supported. When I was using C# in VSCode, I find 'launchBrowser' is quite useful. It will be great if vscode-go also support this.

**Comment by ramya-rao-a** [comment]
@xinyanmsft What do you expect `launchBrowser` to do? Launch the browser with localhost and configured port?
Can you share which C# extension are you referring to?

**Comment by xinyanmsft** [comment]
here's how you can get the launchBrowser option in launch.json:
  1. create a .net c# project.
  2. open VSCode (you need to have the c# plug-in and debugger installed. ms-vscode.csharp)
  3. enable .Net Core debugging in VSCode.
then you should see the launch.json file contains the following section:
              "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
This is what I was referring to.

**Comment by ramya-rao-a** [comment]
@xinyanmsft I am not aware of the implementation details of the C# plugin. Can you provide more details in the context of Go?

One can have a web app such that when it is running, opening the browser on localhost and given port, the web page is rendered. I am guessing you want to have the opening of the browser done as part of running the web app?
