### ISSUE TITLE
Add a Wiki page for all the features supported by the extension with Gifs

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#596]

**Comment by scriptonist** [comment]
@ramya-rao-a I may be able to help with this.

**Comment by MagnumOpus21** [comment]
Does this issue still need help? If someone can point me what I should do to resolve this I'm happy to help with this issue 😁

**Comment by ramya-rao-a** [comment]
Hey @MagnumOpus21,

Thanks for your interest!

The main reason I logged this issue was to have a place that had details on the features of this extension. Recently, I refactored the README for this extension which now has sufficient details, so I will be closing this issue.

Feel free to checkout any of the other issues with the `help-wanted` label :)
