### ISSUE TITLE
Update gotests to support subtests

### ISSUE THREAD

**Issue by itsjamie** [Microsoft/vscode-go#597]
Hello! 

When I'm able to finish up https://github.com/cweill/gotests/pull/28 and have it land, I'd love for vscode-go to update to support the `nosubtests` flag, perhaps via a user setting?

Thank you for the excellent extension.

**Comment by ramya-rao-a** [comment]
Hi @itsjamie, 

Yes, using a setting to to maintain the flags for `gotests` is the right approach.
PRs are welcome, I'd be happy to point you to the place where to start.

**Comment by itsjamie** [comment]
Yeah, I'd be happy to do a PR. If you can just point me in the right direction of where I might add it that would be appreciated. This will be my first time doing anything with VSCode, is there a central location for documentation about extension development I could peruse?

Regarding the implementation, subtest generation defaults to on when the local machine is running >= Go 1.7, how would you like to handle this? Default to on, and allow users to disable via the flag?

**Comment by ramya-rao-a** [comment]
https://code.visualstudio.com/Docs/extensionAPI/overview would be good point to start with for documentation about extension development for VS Code.

Are you saying that the subtests feature is available only in Go 1.7 and higher?

**Comment by itsjamie** [comment]
That's correct.

The `gotests` binary will handle the case where a user running Go 1.6 will still generate tests that their version of Go can run by not using the new subtests API via `t.Run`. The underlying change to gotests won't have any effect for those users.

The default behaviour for users running Go 1.7 will currently change if `gotests` is updated after the PR lands. I think that is ok because the subtests API is better in every way however, there should be a possible way to turn the feature off. There will be reasons someone may not be able to switch to the new table driven test inspired subtest API.

**Comment by ramya-rao-a** [comment]
Hi @itsjamie,

Any updates on this?

**Comment by itsjamie** [comment]
gotests has merged the subtest support, this admittedly has fallen to the wayside, since I wanted the subtest support and it just ended up working without any changes to vscode-go.

**Comment by ramya-rao-a** [comment]
good to hear, I'll close this issue then
