### ISSUE TITLE
[improvement] Completion mess with import or already set variables

### ISSUE THREAD

**Issue by bennyscetbun** [Microsoft/vscode-go#598]
Hi, there is a new completion stuff that is pretty great.
It can let you choose a package from a list of all available package even if not imported yet.
Pretty good.
But if i have a variable with the name of a package, the completion start with unimported package when i want to use the variable.
Also  if you ve already imported a package with that name some wierd stuff happen and could lead to a file with multiple import of same package but with different path.
Solution:
If a variable/package is already set in the current scope dont show any package that can be imported with the same name and also sort all the result the way that every variables already set in the scope should be first in the completion choice

**Comment by ramya-rao-a** [comment]
Hi @bennyscetbun 

Yes, the issue of variable and an unimported package completion and sorting is a valid one. https://github.com/Microsoft/vscode-go/issues/559#issuecomment-257368248.
Will look into this soon.

Can you elaborate on the below with an example?

>Also if you ve already imported a package with that name some wierd stuff happen and could lead to a file with multiple import of same package but with different path.

**Comment by ramya-rao-a** [comment]
Hi @bennyscetbun 

I was trying to repro the case when a variable and unimported package have the same name

![image](https://cloud.githubusercontent.com/assets/16890566/19988445/55b5b1a4-a1dd-11e6-96ff-b158f35f728c.png)

For me, the variable comes first and then the package. Can you try the code from above and see what you get? And maybe share a case where the package comes before the variable?

Also can you elaborate on the below with an example?

>Also if you ve already imported a package with that name some wierd stuff happen and could lead to a file with multiple import of same package but with different path.

**Comment by bennyscetbun** [comment]
Hi
This is an example where it fails
<img width="529" alt="screen shot 2016-11-05 at 02 56 12" src="https://cloud.githubusercontent.com/assets/5469691/20026839/78f878aa-a303-11e6-865f-e3a59887ca68.png">

and for example if you ve got the same package in a lot of different places and already imported it
<img width="575" alt="screen shot 2016-11-05 at 02 59 15" src="https://cloud.githubusercontent.com/assets/5469691/20026869/1fecac4e-a304-11e6-963e-68d7194b48ca.png">

**Comment by bennyscetbun** [comment]
Btw you should avoid to show path of packages with vendor in it ???

**Comment by ramya-rao-a** [comment]
#603 will group all the packages and show them in the end after the variables/functions/others. You will get that in the next update

About multiple packages having the same name, I can see how in your case it could get annoying. But, wouldn't there be a valid case where you would have 2 packages with same name but offer different things. Why shouldn't auto-complete suggest them then?

About packages with "vendor" in it. If it is a vendor package in the current Go project, then the path will not have "vendor" in it. In the above case, the package is a vendor from another project. Technically, you can still import it and use it....

**Comment by bennyscetbun** [comment]
Tell me if i am wrong but if you import a package in a vendor of an other project you will get an error.
For example i am in `github.com/bennyscetbun/testgo` project and imported a vendored package.
<img width="777" alt="screen shot 2016-11-05 at 11 01 43" src="https://cloud.githubusercontent.com/assets/5469691/20029248/828c9272-a347-11e6-97ae-2cf16f60f423.png">

**Comment by ramya-rao-a** [comment]
That's interesting, I tried something similar and didn't get any build errors (in the output window with buildOnSave set to true), which is why I did not remove the vendored packages from the list of importable packages.

When I build my code independently outside of VS Code, I get a different error
`imports github.com/godoctor/godoctor/vendor/github.com/willf/bitset: must be imported as github.com/willf/bitset`

But you are right. The functions `disallowVendor` and `disallowVendorVisibility` in https://golang.org/src/cmd/go/pkg.go make it clear, the importing a vendor package from another project is not allowed.

Will make that change.

**Comment by bennyscetbun** [comment]
Hi @ramya-rao-a
i have one tiny last thing about:
> About multiple packages having the same name, I can see how in your case it could get annoying. But, wouldn't there be a valid case where you would have 2 packages with same name but offer different things. Why shouldn't auto-complete suggest them then?

You wont be able to build with 2 packages with the same name so importing them in the middle of your code wont be usefull.
The only way to add a package with the same name is to force the name at import  and you ve already done the completion when doing import.
From my PoV not showing other packages that you wont be able to import or that wont override a scope variable is a good idea :)

**Comment by ramya-rao-a** [comment]
I knew about the error on using 2 pkgs with same name. I just expected the user to add an alias to one of them 😊

What can be done in such cases is for the auto complete itself to add an alias. That should be easy.

And thanks for all the feedback! That's how we can together make this a great product 😊

**Comment by ramya-rao-a** [comment]
On second thoughts, I'll go with your suggestion of not showing the importable package if there is an identifier with the same name already in the Go file

**Comment by ramya-rao-a** [comment]
The latest update (0.6.48) has all the fixes discussed here. 
Happy Coding!
