### ISSUE TITLE
godef to net package failed

### ISSUE THREAD

**Issue by tonyjt** [Microsoft/vscode-go#599]
F12 to net package source code failed.

macox

**Comment by zerbitx** [comment]
Just had the same thing happen to me.  It's working for other stdlib symbols, but does nothing for net.   Autocomplete still works for net.

**Comment by ramya-rao-a** [comment]
Do you see any errors in the console in the Developer tools? `Developer: Toggle Developer Tools`

**Comment by ramya-rao-a** [comment]
I can repro this. While debugging, `godef` gives error `godef: no declaration found for net.Dialer` when I tried F12 on `Dialer`.

This is a problem with `godef` and might be related to #515

@tonyjt @zerbitx Can you both chime in on https://github.com/rogpeppe/godef/issues/48 ?

**Comment by ramya-rao-a** [comment]
Closing as duplicate of #442

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.50), we now support the use of `gogetdoc` for **Goto/Peek Definition, Hover info and Signature Help** features. Add `"go.docsTool": "gogetdoc"` to your setting to enable the use of `gogetdoc` and that should fix this issue.
