### ISSUE TITLE
Proposal: intergrate with gotests

### ISSUE THREAD

**Issue by astaxie** [Microsoft/vscode-go#606]
gotests makes writing Go tests easy. It's a Golang commandline tool that generates table driven tests based on its target source files' function and method signatures. Any new dependencies in the test files are automatically imported.

![](https://github.com/cweill/GoTests-Sublime/raw/master/gotests.gif?raw=true)
https://github.com/cweill/gotests

**Comment by ramya-rao-a** [comment]
@astaxie The extension is using `gotests` to generate tests already. Try out the below commands and let us know what is missing.

- Go: Generate unit tests for current file
- Go: Generate unit tests for current function
- Go: Generate unit tests for current package

**Comment by astaxie** [comment]
@ramya-rao-a thanks. I find it. it works well
