### ISSUE TITLE
1.7 formatOnSave Deprecated

### ISSUE THREAD

**Issue by caibirdme** [Microsoft/vscode-go#611]
`go.formatOnSave` deprecated from `vscode 1.7`
set your global config `editor.formatOnSave` to true if you like

---
can't be better to add this to doc or changelog

**Comment by Pitchanon** [comment]
Thank you so much for all you have done for us.

**Comment by helinwang** [comment]
It's `"editor.formatOnSave": true,` in my vs code. (not `edit.formatOnSave`)

**Comment by caibirdme** [comment]
@helinwang Sorry for my careless, u r right

**Comment by tilinna** [comment]
I wouldn't like to enable formatting on all languages. Therefore, I suggest the go.formatOnSave to function like previously until https://github.com/Microsoft/vscode/issues/13547 is fixed.

**Comment by ramya-rao-a** [comment]
@caibirdme A note on deprecating `go.formatOnSave` in favour of `editor.formatOnSave` was added to the Changelog during the release, but I had forgotten to add it to the README which is now updated as well.

@tilinna I'd like to see if more from the community feel the same way. If yes, then I'll circle back to this nexst week.

**Comment by neelance** [comment]
I just tried `editor.formatOnSave` and it completely broke it for me, because I don't want to format our TypeScript and our JSON files, only Go. I found no way to only make it happen for Go. The only way to continue working was to disable `formatOnSave` entirely. I'd say this is a regression and makes this feature unusable. It is especially bad since formatting on save is an expected default in the Go world.

**Comment by ramya-rao-a** [comment]
This change has been reverted due to popular demand in the latest update. Will wait for VS Code to come up with language specific formatOnSave setting.

**Comment by neelance** [comment]
Thanks for fixing this so quickly!

**Comment by ramya-rao-a** [comment]
@neelance No problem
Thanks for reporting issues and pain points. I learn something new each day :)

**Comment by DasJott** [comment]
The `editor.formatOnSave` almost broke one of our releases as we use a selfmade template markup in our js and html and that was "formatted" which destroyed the whole page.
The GO formater always worked great, why not leave it as it is...
