### ISSUE TITLE
When saving a Go file (with either Ctrl-S or from menu) a line near to my cursor position is removed. Does not seem to happen on plain text, just Go, so far.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-go#615]
_From @theescapers on November 13, 2016 23:57_

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.49|

---

Steps to Reproduce:

1.
2.

_Copied from original issue: Microsoft/vscode#15436_

**Comment by ramya-rao-a** [comment]
@theescapers Can you share an example code/ gif where you see this issue?

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back details from the OP

**Comment by safijari** [comment]
I have these import statements 
```
**import (
	"appengine"
	"appengine/urlfetch"
	"encoding/json"
	"gopkg.in/telegram-bot-api.v4"
	"io/ioutil"
	"net/http"
	"fmt"
)
```

If I press Ctrl+s (or just straight up save from the menu), vscode automatically changes these lines to:

```
import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"

	"appengine"
	"appengine/urlfetch"
)
```

I have these extensions installed.

![image](https://cloud.githubusercontent.com/assets/5191844/22859111/89083d18-f086-11e6-925b-4be8e47a627c.png)

I am on Windows 10. Removing the go extension fixed the issue.

**Comment by ramya-rao-a** [comment]
@safijari Is your issue that "gopkg.in/telegram-bot-api.v4" is disappearing from the import list or that the list is re-ordered?

By default, on save, formatting is triggered. (You can disable this by setting `"go.formatOnSave": false`)

By default, the tool used for formatting is `goreturns`. (You can change this by changing the setting "go.formatTool" to either `goimports` or `gofmt`

When the formatting tool used is either `goreturns` or `goimports`, the import list gets re-ordered and any unused imports are removed from the file.

In your case I believe "gopkg.in/telegram-bot-api.v4" was not yet used in your code. Can you confirm?

**Comment by jbrodriguez** [comment]
@ramya-rao-a,

I have the same issue.

The package is "gopkg.in/check.v1" and using either goreturns or goimports deletes the import from the list (I'm using the package).

Is this something you can fix ?
