### ISSUE TITLE
mac can debug code？ mac os 10.12.1 version 

### ISSUE THREAD

**Issue by zuojinmin** [Microsoft/vscode-go#616]
setting
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}/src/hello",
            "env": {},
            "args": []
        }
    ]
}

wrong：-》  could not launch process: could not get thread count

**Comment by roblourens** [comment]
Delve, which we rely on for debug support, is broken on that version of mac os. Issue here - https://github.com/derekparker/delve/issues/645

**Comment by zuojinmin** [comment]
what about this pro reason?

**Comment by roblourens** [comment]
I don't understand what you mean

**Comment by zuojinmin** [comment]
Solving the problem is a problem.？

**Comment by zuojinmin** [comment]
if osx verison is 10.12.1 i can`t use dlv?

**Comment by roblourens** [comment]
Right. We need delve (or MacOS) to fix their issue.

**Comment by zuojinmin** [comment]
thanks ,if you can  Solve  the problem ,plz tell me

**Comment by l2dy** [comment]
@zuojinmin See https://github.com/derekparker/delve/issues/645#issuecomment-260605967
