### ISSUE TITLE
Update the publisher from lukehoban to Microsoft

### ISSUE THREAD

**Issue by y0ssar1an** [Microsoft/vscode-go#617]
If this is the new home for `vscode-go`, then all references to `lukehoban/vscode-go` should be removed. It's confusing. I initially assumed I didn't need a Go extension, because surely `Microsoft/vscode-go` was the default Go package, and it was more up to date than `lukehoban/vscode-go`, which hasn't been updated since May. `lukehoban/vscode-go` also shows up as having been forked from `Microsoft/vscode-go`. What???

![image](https://cloud.githubusercontent.com/assets/1250684/20271665/61439516-aa40-11e6-9261-8f6b69cca55a.png)

`lukehoban/vscode-go` looks like an abandoned fork of `Microsoft/vscode-go`, except that _it is the correct extension_, but it doesn't live at `lukehoban/vscode-go`.

Ideally, `Microsoft/vscode-go` would be installed by default, making an extension unnecessary. If that doesn't happen, it should simply appear as `Microsoft/vscode-go` everywhere.

**Comment by ramya-rao-a** [comment]
`Microsoft/vscode-go` is the repo where the Go extension lives.
`lukehoban/vscode-go` is Luke's personal fork of the extension just like I have mine `ramya-rao-a/vscode-go` 
Personal forked repos are where we choose to develop features before merging to the main Microsoft repo.

> I initially assumed I didn't need a Go extension, because surely `Microsoft/vscode-go was the default Go` package

> Ideally, `Microsoft/vscode-go` would be installed by default, making an extension unnecessary.

This is incorrect. The Go extension is not shipped as part of VS Code and so is not any kind of "default". It is definitely a recommended extension for the Go language by the VS Code team/product.

**Comment by y0ssar1an** [comment]
Can we please make it so that it appears correctly in the Extensions menu?

![image](https://cloud.githubusercontent.com/assets/1250684/20279507/a9796820-aa5d-11e6-8b45-af5ec4f15d88.png)

**Comment by ramya-rao-a** [comment]
Well.... that is the publisher id. @seanmcbreen @lukehoban Some history insights here?

**Comment by mvadu** [comment]
Any update on this @ramya-rao-a ? Why don't we keep this issue open until this is resolved. Its really confused, and even after an year its still shows up as 
![image](https://user-images.githubusercontent.com/8618235/34988738-bc23e1c2-fa8d-11e7-9f67-29e1a8888b62.png), and this repo's home page has "You can also install the extension from the [Marketplace](https://marketplace.visualstudio.com/items?itemName=lukehoban.Go)" which again links to lukehoban.Go. @lukehoban has since moved on and it should be corrected to show new home for the plugin.

**Comment by ramya-rao-a** [comment]
The repo/project related links in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=lukehoban.Go) for this extension points to the correct repo i.e Microsoft/vscode-go. So what is the confusion here?

The word `lukehoban` in the screenshot is the publisher id for this extension. 

Ideally, yes, it would be better for Microsoft to be the publisher id for this extension. 

And that is do-able as well, but is non-trivial. It would break extension packs that have reference, workspace recommendations and links that have reference to "lukehoban.go"

**Comment by mvadu** [comment]
well, the place where I work and several other places where my employer provides services to have strict guidelines what is allowed from FOSS (Free and open-source software) universe. One of the such guideline is publisher. So if I go to VS COde, and search for `Publisher:Microsoft` and don't see this plug in then its not allowed. 

If just updating the publisher name breaks so many things then think of cases when a company who published a plugin gets acquired by another, and wants to rebrand the previous companies assets? What is Microsoft's view on handling such branding changes?

**Comment by ramya-rao-a** [comment]
> well, the place where I work and several other places where my employer provides services to have strict guidelines what is allowed from FOSS (Free and open-source software) universe. One of the such guideline is publisher. So if I go to VS COde, and search for Publisher:Microsoft and don't see this plug in then its not allowed.

Thanks for the clarification @mvadu, that helps and is enough for me to re-open this issue to track the moving of publisher for this extension

> If just updating the publisher name breaks so many things...

The very ability to move an extension from one publisher to another became possible only about 3 months ago. The breaking things I mentioned are an inconvenience, but are not hard reasons not to make the move. I believe we take this case by case.

> What is Microsoft's view on handling such branding changes?

I can't speak for Microsoft as a whole, but @seanmcbreen or @chrisdias can speak for the VS Code team.

**Comment by ramya-rao-a** [comment]
This has now been done.
The Go extension is now published under the official Microsoft VS Code publisher id
