### ISSUE TITLE
Go (golang) Auto Complete (Half) Works

### ISSUE THREAD

**Issue by dc0d** [Microsoft/vscode-go#619]
- VSCode Version: 1.7.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

Can't provide steps to reproduce. It happens spontaneously. Others had this issue too (on gitter).

The default gocode auto built option is not changed: `"go.gocodeAutoBuild": true`.
And I have these personal settings (just FYI; and I do not know if they matter in this matter):
```
// Place your settings in this file to overwrite the default settings
{
    // Is git enabled
    "git.enabled": false

    , // Migrated from previous "File | Auto Save" setting:
    "files.autoSave": "afterDelay",

    // Controls the delay in ms after which a dirty file is saved automatically. Only applies when "files.autoSave" is set to "afterDelay"
    "files.autoSaveDelay": 2000
}
```

And I have this script `rs-gocode`:
```
#!/bin/bash

gocode close
gocode
```
But it does not help (Should I run it inside current directory?).

Sometimes after login/logout or restart, the problem goes away and the problem is mostly with code that is currently being written (it compiles & passes the tests - not broken) - like packages in a directory beside the current directory, and the parent of these is open in VSCode.

**Comment by gngeorgiev** [comment]
Experiencing the same behavior, anyone?

**Comment by dc0d** [comment]
I saw other people with same problem on gitter vscode-go.

**Comment by ramya-rao-a** [comment]
A little on the `auto build` feature of `gocode`
`gocode` works with packages. Packages are built when you `go get` or `go install`
The `auto build`  feature of `gocode` gives you intellisense on code that is not yet built and installed into package.

> A boolean option. If true, gocode will try to automatically build out-of-date packages when their source files are modified, in order to obtain the freshest autocomplete results for them. This feature is experimental. Default: false.

The author claims that the feature is experimental and may or may not work in certain cases.

@dc0d Have you seen issues while using other packages or only when writing code for current package?

**Comment by gngeorgiev** [comment]
@ramya-rao-a I have experienced this within the same project, different packages. Also, `auto build` or not, did not make any difference for me.

**Comment by ramya-rao-a** [comment]
@gngeorgiev 

Say, in your project, you are working on package `mypkg`. You import package `otherPkg` which has a function `Hello()`. You make no changes to `otherPkg` after installing it via `go get`.

Do you see intellisense issues while accessing members of `otherPkg` as well or only while accessing members of your own package?

**Comment by gngeorgiev** [comment]
@ramya-rao-a Here's my case:

I have `.go` files in `<project>/src/services/<someService>/service.go`. I generate some mocks in `<project>/mocks/services/<someService>/service.go`. When I try to use the `mock_service` package in my tests `...service_test.go` I get absolutely no autocomplete, not for the package, not for its methods, not for its returned values.

Interesting fact 1: Even `goimports` does not fire up for the file as far as I can see
Interesting fact 2: IntelliJ idea works good

**Comment by ramya-rao-a** [comment]
Any errors in the console? Run `Developer: Toggle Developer Tools` to see the console.

In the coming update, I'll add more error logging to console. Should help us in cases like these.

**Comment by gngeorgiev** [comment]
@ramya-rao-a nope, none, sorry :disappointed:

**Comment by ramya-rao-a** [comment]
Well, could I ask you to share sample code so that I can try to repro on my end ?

**Comment by dc0d** [comment]
@ramya-rao-a Assuming we have this directory opened in VSCode:

/ctrl
/dashboard
/datastore
notes.md

The first two packages have "acceptable" auto complete. But for some reason it never works for "datastore" package.

The whole app works & is running at production.

**Comment by ramya-rao-a** [comment]
@dc0d Unfortunately, this is one of the cases, where if I can't repro the issue, I cant help :(

Therefore, if you can say create a small example and share it in a git repo, then I can try tan repro

**Comment by ramya-rao-a** [comment]
@dc0d @gngeorgiev Is this still a problem? If yes, then the next time you see it, can you try running `gocode` from the terminal/command line and see what you get? This is to eliminate the case that `gocode` itself has issues.

**Comment by gngeorgiev** [comment]
@ramya-rao-a I no longer use VSCode for Go, I use Gogland instead, VSCode was useless. And I am pretty certain that `gocode` is working fine since `vim` had no autocompletion problems and that's exactly what it's using.

**Comment by dc0d** [comment]
Yes it is.

**Comment by gngeorgiev** [comment]
@ramya-rao-a please excuse me if I am being a bit forward but, I can't hold myself and ask - did you even try to reproduce the issue? I mean I have used VSCode for Go on a few different OSs and PCs and the issue is really really apparent. If you tried it only on a small 2-3 files project, you might experience no issues. But someone of your team has to check this out on a real world project. Simply try to be productive for a few hours. I am pretty sure he won't be able to.

**Comment by dc0d** [comment]
I like VSCode & VSCode-Go and I mainly develop Go in it (though I use LiteIDE which has a code structure tree and Atom from time to time).

And as a free product it works well and I like it.

This issue could be something about inappropriate timing when interacting with `gocode`. It does not provide member of some packages randomly, does not provide info on other packages that you are working on and does not show comments.

I use the `.deb` file to install VSCode on Ubuntu 14.04. Other than this issue, I've no other problem with VSCode-Go. Though I do not use any debugging tool so I can not speak on that.

**Comment by ramya-rao-a** [comment]
@gngeorgiev Yes sir, I sure have tried to reproduce the issue. I have tried it on small as well as big projects. But I sure haven't tried coding for hours. My Go coding is mostly small side projects or I tinker around in some interesting projects out there. Go coding is not part of my (or my team's) main day job.  Which is why I keep hoping (https://github.com/Microsoft/vscode-go/issues/619#issuecomment-261481000,  https://github.com/Microsoft/vscode-go/issues/619#issuecomment-261596567) you(or anyone else) could point me to a repo and a scenario where this consistently happens, then I can clone that repo and try myself.


@mattetti, I know you and your team does a lot of Go coding day in, day out. Could you help out here? Have you or your team seen anything like this?

I would surely like to get to the bottom of this. But without steps that I can use to repro, I am quite helpless at the moment.

**Comment by mattetti** [comment]
@gngeorgiev I'm not sure why you are taking it on Ramya who's doing her best to make this plugin the best she can. 

I've been writing Go for a little while and I switched from vim to vs-code before 1.0 and haven't looked back. Like me, my team uses VS Code, some Go team members like Francesc do too. Is it perfect, no. But it is quite good.

Now, I use VSCode on Mac (Sierra) and Windows (10) using Go 1.8. Can you guys please us a bit more context on what's wrong, what OS you are using, what version of Go you are running. 

I have to admit that I have not used VSCode on Linux and that might be what you guys are experiencing.

**Comment by dc0d** [comment]
I've updated again all tools (`go get ...`s on the front page) & installed 1.9.1. It works now, except sometimes when it's the 1st time you use a specific package in a file.

I can not reproduce it in meaningful way; so I think this should get closed for now.

And for some hours that I'm working with 1.9.1, I did not see it so far (except for what explained above).

**Comment by ramya-rao-a** [comment]
Thanks @dc0d
