### ISSUE TITLE
Formatter adds a line importing the very same current package

### ISSUE THREAD

**Issue by scorphus** [Microsoft/vscode-go#621]
Yeah, as strange as it sounds, the formatter insists on adding an import line of the very same package I'm editing. The obvious error is `import cycle not allowed`.

**Comment by ramya-rao-a** [comment]
@scorphus Can you add a sample code here where you see this issue?

**Comment by scorphus** [comment]
Oh, it's no longer an issue. It might had been a flicker, a momentary glitch. Should it happen again, I'll add a comment with sample code and a screencast. Thank you for replying.
