### ISSUE TITLE
Go plugin doesn't expand  ~ in GoPath

### ISSUE THREAD

**Issue by yizhang82** [Microsoft/vscode-go#623]
- VSCode Version: 1.7.1
- OS Version: Mac OSX Sierra 10.12.1
- Go PlugIn: 0.6.39
Steps to Reproduce:

1. set goPATH=~/gosrc and install plugins there using 'go get' 
2. Open VsCode and add following setting 

"go.gopath": "~/gosrc"

Save and exit.

3. Open VS code - VS code still prompts for missing plugin such as golint, etc
4. If you change ~ to the full path '/users/yizhang/gosrc',  go plugin would properly find the path

**Comment by AlekSi** [comment]
That also breaks formating on save with `goreturns`.

**Comment by ramya-rao-a** [comment]
The fix for this issue is now available in the latest update (0.6.54) to the Go extension.
Please update and let us know if you still see any issues
