### ISSUE TITLE
Repeated save, lint, reformat since latest update

### ISSUE THREAD

**Issue by cristim** [Microsoft/vscode-go#625]
It seems the latest update enters an infinite loop whenever the code being typed is not entirely correct, which can happen a lot while writing it.

**Comment by ramya-rao-a** [comment]
@cristim Can you give an example?

Does this happen on save or just typing?

Can you share your settings?

**Comment by cristim** [comment]
This is happening while typing: it would just repeatedly save, lint, reformat and save again.

Eventually the machine will be overwhelmed by all the lint processes started by the gometalinter which get all CPU cores at 100%.

Here are all my go-related global settings:
```
// Go configuration

    // Run 'go build'/'go test -c' on save.
    "go.buildOnSave": true,

    // Flags to `go build`/`go test` used during build-on-save or running tests. (e.g. ['-ldflags="-s"'])
    "go.buildFlags": [],

    // Run Lint tool on save.
    "go.lintOnSave": true,

    // Specifies Lint tool name.
    "go.lintTool": "golint",

    // Flags to pass to Lint tool (e.g. ['-min_confidenc=.8'])
    "go.lintFlags": [],

    // Run 'go tool vet' on save.
    "go.vetOnSave": true,

    // Flags to pass to `go tool vet` (e.g. ['-all', '-shadow'])
    "go.vetFlags": [],

    // Pick 'gofmt', 'goimports' or 'goreturns' to run on format.
    "go.formatTool": "goreturns",

    // Flags to pass to format tool (e.g. ['-s'])
    "go.formatFlags": [],

    // Run the formatting tools with the -d flag
    "go.useDiffForFormatting": true,

    // Complete functions with their parameter signature
    "go.useCodeSnippetsOnFunctionSuggest": false,

    // Specifies the GOPATH to use when no environment variable is set.
    "go.gopath": null,

    // Specifies the GOROOT to use when no environment variable is set.
    "go.goroot": null,

    // Runs formatting tool on save.
    "go.formatOnSave": true,

    // Run 'go test -coverprofile' on save
    "go.coverOnSave": false,

    // Specifies the timeout for go test in ParseDuration format.
    "go.testTimeout": "30s",

    // Enable gocode's autobuild feature
    "go.gocodeAutoBuild": true,

    // The Go build tags to use for all commands that support a `-tags '...'` argument
    "go.buildTags": "",

    // Environment variables that will passed to the process that runs the Go tests
    "go.testEnvVars": {},

    // Autocomplete members from unimported packages.
    "go.autocompleteUnimportedPackages": true,

```
It appears to be triggered by the `go.lintOnSave` option, it starts happening if I override that in my local settings to `true`, once I set it to `false` it stops happening.

It doesn't matter which lint tool I use, so if I set `go.lintTool` to `golint` it does exactly the same, it's just that I don't get a myriad of linting processes like I get with `gometalinter`.

**Comment by ramya-rao-a** [comment]
What you have shared is the default settings. I was looking for the settings you have overridden.

**Comment by ramya-rao-a** [comment]
Particularly, if you have `files.autoSave` or `editor.formatOnSave` and any other Go setting

**Comment by cristim** [comment]
@ramya-rao-a I mentioned at the end of my previous comment:

> It appears to be triggered by the go.lintOnSave option, it starts happening if I override that in my local settings to true, once I set it to false it stops happening.

**Comment by ramya-rao-a** [comment]
>This is happening while typing: it would just repeatedly save, lint, reformat and save again and again forever, until the machine becomes unusable.

**it would just repeatedly save** : I would expect this to happen only if `files.autosave` is enabled
**reformat** : Formatting, build, linting are run on save. Of all the actions run on save, formatting is the only action that makes changes to the file. Linting does not change the file contents
**and save again** : This would be explained by `files.autosave` being enabled. 

Which is why I am asking for your local settings that would have overridden the default settings.

It is ok, if you don't want to share those.
But, can you please try disabling `files.autoSave` and `editor.formatOnSave` and see if it makes a difference?

Also, see the below note taken from the ReadMe of this extension

>
![image](https://cloud.githubusercontent.com/assets/16890566/20440604/a89f3e3c-ad75-11e6-89e8-8fc4447b2d6c.png)

**Comment by ramya-rao-a** [comment]
There was only one net change in the formatting area in the last few updates.

It was to pass the file contents to the formatting tool via stdin instead of the formatting tool working on the file on disk. This was made to enable formatting to work on unsaved changes.

I have reverted the change in the master branch (it has caused a few other issues).

Since I can't repro your case,  can you try to install the extension from source and see if it fixes the issue for you?

Steps to do that would be:

- Uninstall the Go extension from VS Code. 
- Clone the extension code: `git clone https://github.com/Microsoft/vscode-go`
- `cd vscode-go`
- `npm install`
-  `npm install -g vsce` 
-  `vsce package`
-  `code --install-extension Go-0.6.49.vsix`

You should see a message `Extension 'Go-0.6.49.vsix' was successfully installed!`
Close all instances of VS Code, open a new one and see if you still have the issue.

**Comment by cristim** [comment]
@ramya-rao-a  I have no problem sharing my config:

```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 18,
    "editor.rulers": [80,120],
    "editor.cursorStyle": "block",
    "files.autoSave": "off",
    //"files.autoSaveDelay": 1000,
    "files.trimTrailingWhitespace": false,
    "go.coverOnSave": true,
    //"go.formatOnSave": true,
    "go.formatOnSave": false,
     "go.lintTool": "golint",
    "go.lintOnSave": true,
    "go.gocodeAutoBuild": false ,
    "go.formatTool": "goreturns",
    "ruby.format": "rubocop"
}
```

I traced the problem to `go.formatOnSave`, the problem happens only when that is enabled, regardless which other options I use. I also noticed that when it happens, the code of my program often gets mangled, lines get moved around or duplicated, etc, which is a really bad issue.

When disabling it and formatting on demand everything works as expected. Unfortunately, that's a must-have feature for me so without it I will need to switch to another editor which supports this properly.

**Comment by ramya-rao-a** [comment]
I totally agree that formatOnSave is a very important feature.
As I said in https://github.com/Microsoft/vscode-go/issues/625#issuecomment-261750425 there was only one change that was done in the area of formatting. And I am betting that must have been the reason for what you are seeing. 

I am reverting the said change and will be releasing an update tomorrow.

If you have some time before that, I would very much appreciate it if you side load the extension from source as explained in https://github.com/Microsoft/vscode-go/issues/625#issuecomment-261750425 and confirm that that fixes the issue for you.

**Comment by ramya-rao-a** [comment]
@cristim  I have reverted the change around the formatting logic in the latest update(0.6.50). Can you update and tell me if that fixes the issue for you?

**Comment by cristim** [comment]
@ramya-rao-a with the latest update it no longer formats code at all.

Can I somehow help you reproduce this?

**Comment by ramya-rao-a** [comment]
Yes, #631 is the same.

> it no longer formats code at all.

You mean manual format does not work as well?
Do you see anything in the console? Run `Developer: Toggle Developer Tools` to open the dev tools.

Can you try the below:

- Change `go.formatTool` to `gofmt`
- Change `go.useDiffForFormatting` to false

It is also possible that some other extension is interfering in the format process.
What other extensions do you have?
Can you disable them, just have the Go extension enabled and try?

Usually to reproduce an issue, all we would need is sample code and your user settings.

My last resort would be to help you debug the extension in your environment.

**Comment by ramya-rao-a** [comment]
Can you also try the insiders build of VS Code? http://code.visualstudio.com/insiders

**Comment by ramya-rao-a** [comment]
@cristim Any updates?
Do you still see this issue with other extensions disabled?

**Comment by ramya-rao-a** [comment]
@cristim , The other issue #631 which is similar to yours is confirmed to be caused by an external extension called "whitespace".

Do you have any updates from your side?

**Comment by cristim** [comment]
@ramya-rao-a due to this bug and other issues related to unintentional whitespace mangling in Makefiles and Markdown files, I reduced my use of vscode, so I didn't get the chance to experiment so much with it lately.

I will check and ensure the whitespace external extention is disabled.

**Comment by cristim** [comment]
Okay, that extension was installed and I can't reproduce the issue anymore after disabling it.

I think this issue can be closed.

**Comment by ramya-rao-a** [comment]
Thanks @cristim

**Comment by tugbabodrumlu** [comment]
I have the same problem now, could you please help?

**Comment by ramya-rao-a** [comment]
@tugbabodrumlu Do you have other extensions installed? Can you repro the behavior after disabling other extensions?

**Comment by tugbabodrumlu** [comment]
I had c++ extension and I removed it, but I still have the same problem..

**Comment by ramya-rao-a** [comment]
@tugbabodrumlu Can you share your user settings? Also, can you describe your issue? Is it exactly what @cristim sees?

**Comment by tugbabodrumlu** [comment]
Hi,

I sometimes see godef, golint and goimports processes started many times and CPU cores get at 100%.

Here is my settings:

```json
// Place your settings in this file to overwrite the default settings
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goimports",
    "go.goroot": "/usr/local/go",
    "go.gopath": "/Users/xxxx/Documents/gows",
    //"go.useDiffForFormatting": false,
    "window.zoomLevel": 0
}
```

**Comment by ramya-rao-a** [comment]
There are other issues for the high CPU usage.

Are you in a Mac? Did you recently upgrade to Sierra?

Can you close all but one VS Code window, run `Go: Install Tools` and once that is complete, reload VS Code and try again?

**Comment by tugbabodrumlu** [comment]
Yes I am in a Mac and i recently upgraded to Sierra. I will do so, and will report back.
