### ISSUE TITLE
Message to update go-outline does not go away even after the update in 0.6.49

### ISSUE THREAD

**Issue by Jamesxql** [Microsoft/vscode-go#626]
When I type code in vscode, it always hint "The Go extension is better with the latest version of "go-outline". Use "go get -u -v github.com/lukehoban/go-outline" to update"

but I have already installed it.

<img width="1824" alt="qq20161118-0 2x" src="https://cloud.githubusercontent.com/assets/10518551/20421136/075ddbb4-ad9d-11e6-991a-8c094d9763c3.png">

**Comment by ramya-rao-a** [comment]
@Jamesxql There has been recent updates to the `go-outline` tool. This message is asking you to update your version of `go-outline` tool, so that the Go extension can use the newer features of the `go-outline` tool.

Do you foresee any issues with updating?

**Comment by Jamesxql** [comment]
@ramya-rao-a I have already update it, but vscode always hit me that...

**Comment by Jamesxql** [comment]
platform: MacOS Sierra 10.12.1
vscode: 1.7.1
go: 1.7.3

**Comment by ramya-rao-a** [comment]
Can you run `$GOPATH/bin/go-outline -h` in your terminal and share the result?

**Comment by Jamesxql** [comment]
It shows
`Usage of ./go-outline:
  -f string
    	the path to the file to outline
  -imports-only
    	parse imports only
  -src string
    	source code of the file to outline`

**Comment by ramya-rao-a** [comment]
So here is what is happening behind the scenes. The flag `-imports-only` is the new feature of `go-outline` that the latest update of the Go extension wants to use. The Go extension calls `go-outline` and if it returns error saying `flag provided but not defined: -imports-only`, we show the message you see so that user updates the `go-outline` tool.

The result of `$GOPATH/bin/go-outline -h` that you shared tells me that `go-outline` tool has been updated.

Have you set GOPATH to a different path in your settings?

**Comment by Jamesxql** [comment]
This is my go env shows:
`GOARCH="amd64"`
`GOBIN="/usr/local/Cellar/go/1.7.3/bin"`
`GOEXE=""`
`GOHOSTARCH="amd64"`
`GOHOSTOS="darwin"`
`GOOS="darwin"`
`GOPATH="/Users/xuqiaolun/Desktop/golang:/Users/xuqiaolun/Desktop/gowork"`
`GORACE=""`
`GOROOT="/usr/local/Cellar/go/1.7.3/libexec"`
`GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"`
`CC="clang"`
`GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dj/g9jp23zj37v5632xt060j4900000gn/T/go-build591968537=/tmp/go-build -gno-record-gcc-switches -fno-common"`
`CXX="clang++"`
`CGO_ENABLED="1"`

And This is my $PATH
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/Cellar/go/1.7.3/bin`

Is there any problem?

**Comment by ramya-rao-a** [comment]
And you set `go.gopath` setting in your user settings ?

My theory is that you might have `go-outline` installed in multiple locations.
And that running `go get ...` updated it in one location.
And that the Go extension might be picking up the `go-outline` from the location where it was not updated.

Can you run a search and see if you the `go-outline` file in multiple locations?
(These multiple location correspond to the multiple paths set as GOPATH in your environment : `/Users/xuqiaolun/Desktop/golang` and `/Users/xuqiaolun/Desktop/gowork` and the location you have set `go.gopath` in your user settings.)

**Comment by Jamesxql** [comment]
Yes, that's the problem, there is actually more than one installation locations. I have resolved it already. Thank you very much.

**Comment by ramya-rao-a** [comment]
Great! Happy Coding!
