### ISSUE TITLE
Analysis tool install broken

### ISSUE THREAD

**Issue by newhook** [Microsoft/vscode-go#63]
When I select "install analysis tools" it does nothing. I think the issue is

```
   var p = cp.exec("go get -u -v " + tool, { cwd: process.env['GOPATH'], env: process.env });  
```

In my case GOPATH is multi-path, therefore the cwd is invalid when running go get -u ... In this case, couldn't the cwd be left empty? Or perhaps set to the home dir if empty isn't desirable for some reason?

**Comment by lukehoban** [comment]
Fixed with #65.
