### ISSUE TITLE
Add go.goos to the extension options

### ISSUE THREAD

**Issue by hickeng** [Microsoft/vscode-go#632]
Currently the only way I've found to set GOOS for the Go tools in vscode is to set the environment before launching the editor - this doesn't work well if you have multiple workspaces that may need different GOOS settings.

While I appreciate the prompt to ensure that the code at least compiles on multiple platforms, not all 3rd party packages do so and that causes real issues with guru and the other navigation tools.

**Comment by ramya-rao-a** [comment]
@hickeng On the same line, wouldn't you also need GOARCH?
@mattetti You have any thoughts here?

**Comment by mattetti** [comment]
It is a bit of an edge case but I agree that it would be a useful feature to have. @hickeng can you explain a bit more your edge case, are you trying to check that your code compiles properly against multiple os/arch targets?

**Comment by hickeng** [comment]
@ramya-rao-a For completeness yes, but it's GOOS that's the most awkward currently.

@mattetti The multi-target case is definitely one that I hit, but it's not actually the one I experience on a daily basis.
I'm using Windows for my OS for various reasons but core portions of code I'm developing build only on Linux. It's easy enough to build that portion of the code in a VM or cross-compile but the Go tools are not happy in vscode. For example `godefs` cannot find call targets in the Linux only code. I have tried setting GOOS to linux in the past but never had it propagate to the tools unless I set it at a system level which causes other issues. I realize that I'd have issue navigating the Windows portions of the code if I change GOOS at a workspace level but the portions of the code that are not multi-platform are Linux so that's where the pain primarily presents.

**Comment by ramya-rao-a** [comment]
Thanks @hickeng. This should be easy to do. 

PRs are welcome if anyone wants to take a crack at this.

Hints:
- Add a new configuration property in [package.json](https://github.com/Microsoft/vscode-go/blob/master/package.json#L255)
- Update [updateGoPathGoRootFromConfig](https://github.com/Microsoft/vscode-go/blob/master/src/goInstallTools.ts#L171) which updates GOPATH and GOROOT from settings to include updating the GOOS as well. Probably rename the method as well :)

**Comment by ramya-rao-a** [comment]
This is fixed by https://github.com/Microsoft/vscode-go/pull/932.

The update containing the fix will be out soon

**Comment by ramya-rao-a** [comment]
Fix is out in the latest update (0.6.60)

@hickeng Can you add your env vars in the new setting `go.toolsEnvVars` and confirm if your issue is fixed?

**Comment by jackie-qiu** [comment]
@ramya-rao-a  Thank you, "go.toolsEnvVars": {"GOOS" : "linux"}, that works for me.
