### ISSUE TITLE
Function signature misreported for function ( bigAdd := (*big.Int).Add )

### ISSUE THREAD

**Issue by heliorosa** [Microsoft/vscode-go#634]
for the following program, the signature showed is `bigAdd func(x, y *Int) *Int` and obviously should be `bigAdd func(z, x, y *Int) *Int`.

```go
package main

import (
	"fmt"
	"math/big"
)

func main() {
	bigAdd := (*big.Int).Add
	a := big.NewInt(1)
	b := big.NewInt(2)
	c := bigAdd(new(big.Int), a, b)
	fmt.Println(a)
	fmt.Println(b)
	fmt.Println(c)
}
```

**Comment by ramya-rao-a** [comment]
Setting `go.docsTool` to `gogetdoc` does give the right signature.
The default tool used is `godef` which gives the wrong signature for which I've logged an upstream issue https://github.com/rogpeppe/godef/issues/75
