### ISSUE TITLE
Gometalinter cannot find standard libraries 

### ISSUE THREAD

**Issue by damienstanton** [Microsoft/vscode-go#635]
I am using `vscode 1.7.1`, go `1.7.3`, vscode-go `0.6.50`, macos `10.12.1`

I have tried running `gocode close` and then `go get -u github.com/nsf/gocode`. This does not work.
My editor config as pertains to Go is:
```json
"go.useCodeSnippetsOnFunctionSuggest": true,
"go.formatTool": "goimports",
"go.lintTool": "gometalinter"
```

Screenshots:
![](https://storage.googleapis.com/blinkanalytics-pub.appspot.com/vscode-go-err1.png)
![](https://storage.googleapis.com/blinkanalytics-pub.appspot.com/vscode-go-err2.png)

edit:  I also tried installing from source, same error.

**Comment by ramya-rao-a** [comment]
Can you share the output of `go env` ?

**Comment by damienstanton** [comment]
Certainly:
```sh
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/damien/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tb/r74wwyk17b3fn_frdb0gd0780000gn/T/go-build704047116=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by ramya-rao-a** [comment]
Looks like the linter is not able to find the standard libraries.

In non Windows platforms, Go gets installed to _/usr/local/go_ and all the standard libraries are found in _/usr/local/go/src_ folder. Can you look into your _/usr/local/go/src_ folder and see if the standard libraries (**net, math, database, log**) etc are present ?

Also, can you try running `gometalinter` from the command line ? In the directory of the package you want to lint, run `$GOPATH/bin/gometalinter .`

**Comment by damienstanton** [comment]
I've installed Go with `brew`, so there is no such folder. The path to the Go `src` dir is `/usr/local/Cellar/go/1.7.3/libexec` and the standard libraries are all there.

Running `$GOPATH/bin/gometalinter .` does indeed return the same errors.

**Comment by ramya-rao-a** [comment]
> Running `$GOPATH/bin/gometalinter .` does indeed return the same errors.

Then this must be an issue with `gometalinter`.

Lets run some additional tests.
- Does `go build` build your code successfully?
- Can you change your linting tool to `golint` and give that a try ?

**Comment by damienstanton** [comment]
Yes, builds work. I switched to `golint` and it seems fine now. Thank you!

**Comment by ramya-rao-a** [comment]
Great! Can you please log an issue for `gometalinter` at https://github.com/alecthomas/gometalinter and link it here ?

**Comment by ramya-rao-a** [comment]
Thanks @damienstanton

**Comment by GarethLewin** [comment]
is this resolved by calling `go build -i` before calling `gometalinter`?

**Comment by damienstanton** [comment]
@GarethLewin no, the solution was to run `gometalinter --install`, which repaired the linters causing the path resolution problem.
