### ISSUE TITLE
Suggestion: `go test`

### ISSUE THREAD

**Issue by tejasmanohar** [Microsoft/vscode-go#636]
It would be nice if this plugin integrated with `go test`. Specifically, it's nice to be able to test a package, file, or (most useful) function from the editor.

**Comment by ramya-rao-a** [comment]
We do have commands to run tests using `go test`.
Have you tried the below commands ?

`Go: Test at Cursor`
`Go: Test File`
`Go: Test Package`
`Go: Test Previous`

**Comment by tejasmanohar** [comment]
oops, that's awesome. I was looking under the right click menu haha
