### ISSUE TITLE
when debug run, i marked a new breakpoint,but it is not work?

### ISSUE THREAD

**Issue by helyho** [Microsoft/vscode-go#638]
when debug running and stop on the breakpoint line which i marked it before i press debug button
then i mark a new breakpoint on the line which is after the current stop breakpoint line
now i press F8 ,it not stop on my new breakpoint line.

at last : i like the vscode-go very much ,thanks .

**Comment by helyho** [comment]
i try again today , strange .... it 's workin , i don't know why?
if you can't reappear it, please cloes this issues
sorry to Disturb , thanks & good luck for you

**Comment by roblourens** [comment]
Hm, not sure what to say, I haven't seen that before. Glad it's working now!
