### ISSUE TITLE
Can I use different args when using remote debug

### ISSUE THREAD

**Issue by ahcheqiu** [Microsoft/vscode-go#641]
args pass to debugger have to be set when dlv headless server start.
If I want to debug for different args I have to restart dlv and pass different args.
Is there any workaround for my issue?

here is my command
`bin/dlv debug orzorc/downman-server --headless --log --accept-multiclient --listen=:2345 -- -port=7248`

here is my launch.json
```
{
        "name": "downman-server-remote",
        "type": "go",
        "request": "launch",
        "mode": "remote",
        "program": "${workspaceRoot}/src/orzorc/downman-server",
        "env": {},
        "args": [
            "-open-tls",
            "-crtfile=server.crt",
            "-crtkeyfile=server.key",
            "-port=7248"
        ],
        "showLog": true,
        "port": 2345,
        "host": "orzorc.iask.in",
        "remotePath": "/home/orzorc/gospace/src/orzorc/downman-server"
}
```

**Comment by roblourens** [comment]
I don't understand, you're saying that sometimes you need one set of args, and sometimes you need another? I'd suggest two launch configs, with the two sets of args.

**Comment by ahcheqiu** [comment]
@roblourens sorry. I didn't make myself clear.

#### How I use vscode and dlv:
I run the dlv on a linux pc. And the command I start dlv server is
`bin/dlv debug orzorc/downman-server --headless --log --accept-multiclient --listen=:2345`
I use vscode for coding on a mac. And the launch config is listed above.
I upload the code to the linux pc when I save files.

#### What I am expecting:
The dlv will receive the args I set in launch config and use them.
vscode on mac will receive the output of dlv server and display them.

#### What is reality:
dlv can not get any args I set in launch config.
output is not shown in vscode.

#### After search on internet I found out that:
debugger will not use newest code if I do not restart dlv.
I can only pass args to dlv when I start it, like this command
`bin/dlv debug orzorc/downman-server --headless --log --accept-multiclient --listen=:2345 -- -port=7248`
I will get arg port as 7248 and I can not use other args if I do not restart dlv with new command.

#### What I'm looking for:
Is there a config that I can set in launch config to make it possible to restart dlv server remotely and set args as I wanted?
Or what I am looking for is a daydream and I should stop debug remotely.

**Comment by ramya-rao-a** [comment]
@ahcheqiu 

> Is there a config that I can set in launch config to make it possible to restart dlv server remotely

This is not possible. For remote debugging, the Go extension in VS Code only allows connection to a headless dlv server with the intended args that's already running. It cannot restart the dlv server on the remote machine

I have updated the [wiki](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#remote-debugging) appropriately.

Sorry for the very late response
