### ISSUE TITLE
Too many `-d`'s.

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#642]
So I was looking in the debug console trying to figure out why Go To def wasn't working, I couldn't really figure it out but I noticed this:

```
/home/oneofone/code/go/bin/goreturns -d -d -d -d -d -d -d -d [filename]
# then few errors later we got up to
/home/oneofone/code/go/bin/goreturns -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d -d 
```

**Comment by ramya-rao-a** [comment]
Nice catch. https://github.com/Microsoft/vscode-go/blob/master/src/goFormat.ts#L33 is where we add the `-d`  to `formatFlags` variable. That variable is scoped to the function, I wonder why it persists value from previous runs.

**Comment by OneOfOne** [comment]
@ramya-rao-a it's because `vscode.workspace.getConfiguration('go')['formatFlags'] ` returns a reference and you keep updating it.
