### ISSUE TITLE
Can't use Go To Definition

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#643]
Let me know if I can provide any more information:

```
Version 1.8.0-insider
Commit 731c1b034ed009991c29f9ccaf035c236458e3c6
Date 2016-11-23T07:04:50.401Z
vscode-go 0.6.50
```

Same problem with both `"go.docsTool": "gogetdoc"` and `"go.docsTool": "godoc"`

**Comment by nochso** [comment]
I just updated to the latest release and I had to `go install github.com/zmb3/gogetdoc` to make it work.

Which is a first, I remember vscode hinting at missing executables before.

**Comment by OneOfOne** [comment]
@nochso it didn't prompt me but I did install it manually, also just using godoc should have worked.

**Comment by ramya-rao-a** [comment]
You need to reload/restart VS Code after changing the setting `go.docsTool` for the change to take effect.

If `gogetdoc` is not installed, I do get prompted. I just deleted it from my $GOPATH/bin, tried hovering and Goto definition and got the prompt.

@OneOfOne Yes godoc should have worked. You see any errors in the console?

**Comment by OneOfOne** [comment]
@ramya-rao-a sadly no, there aren't any errors, I'm using Go from git though, so I'll try later with go 1.7 and see if that helps.

code completion works fine.

**Comment by fiam** [comment]
This is also happening to me with Go HEAD on darwin/amd64. However, "Go To Definition" works correctly if I revert to Go 1.7.3. @ramya-rao-a is there an easy way to debug the commands called by the Go extension so I can figure out which one is failing? Thanks!

**Comment by fiam** [comment]
Just figured out the problem. Working on a PR.

**Comment by fiam** [comment]
PR submitted. Please, take a look at it. Thanks! https://github.com/Microsoft/vscode-go/pull/655

**Comment by ramya-rao-a** [comment]
Thanks @fiam. PR is merged. Will release an update in a few days

**Comment by ramya-rao-a** [comment]
The latest update 0.6.51 has this fix. Happy Coding!
