### ISSUE TITLE
There is no Intellisense when coding in the vscode

### ISSUE THREAD

**Issue by Jamesxql** [Microsoft/vscode-go#645]
I install [aws-sdk-go](https://github.com/aws/aws-sdk-go) package on my computer, but when I code in the vscode, there is no Intellisense with this package, however the other package is normal.

Anyone knows why?

**OS:** MacOS Sierra 10.12.1
**VSCode version:** 1.7.2
**VSCode go version:** 0.6.50
**Go version:** 1.7.3

**Comment by ramya-rao-a** [comment]
@Jamesxql I installed [aws-sdk-go](https://github.com/aws/aws-sdk-go) and able to get code completion for packages like `aws`(github.com/aws/aws-sdk-go/aws) , `awserr` (github.com/aws/aws-sdk-go/aws/awserr), `session` (github.com/aws/aws-sdk-go/aws/session) etc.

But not for `aws-sdk-go`(github.com/aws/aws-sdk-go)

Is that what you are seeing as well?

**Comment by Jamesxql** [comment]
My code like this:
```go
package main

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/sqs"
)

var queueURL *string

func init() {
	sess, err := session.NewSession(&aws.Config{
		Region:      aws.String("cn-north-1"),
		Credentials: credentials.NewSharedCredentials("", "default"),
	})
	if err != nil {
		panic(err)
	}

	svc := sqs.New(sess)
	params := &sqs.GetQueueUrlInput{
		QueueName: aws.String(""),
	}

	resp, err := svc.GetQueueUrl(params)
	if err != nil {
		panic(err)
	}

	queueURL = resp.QueueUrl
}

func main() {
	sess, err := session.NewSession(&aws.Config{
		Region:      aws.String("cn-north-1"),
		Credentials: credentials.NewSharedCredentials("", "default"),
	})
	if err != nil {
		panic(err)
	}

	svc := sqs.New(sess)
	params := &sqs.ReceiveMessageInput{
		QueueUrl:            queueURL,
		MaxNumberOfMessages: aws.Int64(1),
	}

	for {
		resp, err := svc.ReceiveMessage(params)
		if err != nil {
			continue
		}
		if resp.Messages == nil || len(resp.Messages) == 0 {
			continue
		}

	}
}
```
and there is no Intellisense  for anything. I use the following command to retrieve the SDK:

    go get -u github.com/aws/aws-sdk-go

is there anything wrong?

**Comment by ramya-rao-a** [comment]
Do you see any errors in the console? Open `Developer: Toggle Developer Tools` to see the console.

I am able to get intellisense for this project.

Is the problem only with auto-complete?
Are you getting other features to work like `Go to Definition`, `Find All References` etc. ?

**Comment by Jamesxql** [comment]
`Find All References` is working well, but `Go to Definition` has some error:

<img width="548" alt="qq20161129-0 2x" src="https://cloud.githubusercontent.com/assets/10518551/20695895/66cb4f56-b62a-11e6-974b-19cb8b035103.png">

and when I type code in the vscode, the same error has shown in the console

**Comment by ramya-rao-a** [comment]
That one is mostly from the hover.
Since you are not seeing any errors from `gocode`, am not sure what the problem is.
Can you try running `gocode` from the command line?

**Comment by Jamesxql** [comment]
running gocode with a debug mode is look like this

<img width="906" alt="qq20161129-0 2x" src="https://cloud.githubusercontent.com/assets/10518551/20698349/68f2b498-b63b-11e6-80e1-45dd82dac892.png">

was not resolved, why?

**Comment by ramya-rao-a** [comment]
That must mean that `gocode` cannot find the packages. Do you have the packages in $GOPATH/pkg/<platform>/github.com/aws/aws-sdk-go ?

**Comment by Jamesxql** [comment]
Absolutely yes, I have this package in the right location

<img width="265" alt="qq20161129-0 2x" src="https://cloud.githubusercontent.com/assets/10518551/20702493/0d921842-b653-11e6-982f-5ae947ae8f1b.png">

**Comment by ramya-rao-a** [comment]
Sorry, do you have the file $GOPATH/pkg/yourplatform/github.com/aws/aws-sdk-go/aws.a ?

**Comment by Jamesxql** [comment]
no, the file name is aws-sdk-go.a, aws.a is not exists.

**Comment by ramya-rao-a** [comment]
Under `$GOPATH/pkg/darwin_amd64/github.com/aws` you should have a folder called `aws-sdk-go`.
If you don't then that means you don't have the complied packages for the `aws` package which explains why auto complete is not working.

**Comment by ramya-rao-a** [comment]
If you don't have the above files, then try running `go build github.com/aws/aws-sdk-go` and `go install github.com/aws/aws-sdk-go`

**Comment by Jamesxql** [comment]
It's weird, I delete the file inside folder $GOPATH/pkg/darwin_amd64/github.com/aws, and running `go build github.com/aws/aws-sdk-go` and `go install github.com/aws/aws-sdk-go`, it still generate aws-sdk-go.a file.

Then I delete the file inside the folder `src` and `pkg`, use `go get -u github.com/aws/aws-sdk-go` to retrieve the sdk, and I'm still seeing the same file in the `pkg` folder

How did you retrieve this SDK? Did you just do like:
`go get -u github.com/aws/aws-sdk-go/aws/...`
`go get -u github.com/aws/aws-sdk-go/service/...`

**Comment by ramya-rao-a** [comment]
I am not saying that `aws-sdk-go.a` file should not be there. I am saying that `$GOPATH/pkg/darwin_amd64/github.com/aws/aws-sdk-go/aws` folder should have the `aws.a` file and other folders I have shown before.

I got the SDK by `go get -u github.com/aws/aws-sdk-go`

**Comment by Jamesxql** [comment]
There is only a aws-sdk-go.a file in the folder, other files about you show to me is not exists at all. 

But when I use 
`go get -u github.com/aws/aws-sdk-go/aws/...
go get -u github.com/aws/aws-sdk-go/service/...`

to retrieve the SDK, everything is fine. 

I don't know why

**Comment by Jamesxql** [comment]
Thank you for taking the time to help me solve this problem, I know it's not the `vscode-go` plugin's  problem. Thanks again. @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Hmm..may be you had vendoring switched off thats why?

**Comment by Jamesxql** [comment]
I use the go v1.7.3, does the vendoring is enabled by default?

How do I check if the vendoring has switched off?

**Comment by ramya-rao-a** [comment]
in go v1.7.3 it will be enabled by default
