### ISSUE TITLE
Support Multiple GOPATH?

### ISSUE THREAD

**Issue by zplzpl** [Microsoft/vscode-go#650]
Support Multiple GOPATH?

"go.gopath" : "path1;path2"

**Comment by ShiYu-Yang** [comment]
"go.gopath" : "path1:path2"

**Comment by zplzpl** [comment]
@ShiYu-Yang sorry,it can't work.

my setting :

{
    "go.gopath":"E:\\goapp:E:\\goproject\\new-app"
}

**Comment by zplzpl** [comment]
{
"go.gopath":"E:\\goapp:E:\\goproject\\new-app"
}

**Comment by ShiYu-Yang** [comment]
Maybe it depends on os? 
It can work on my ubuntu PC.

"go.gopath" : "path1;path2" can work on windows?
Or you can add them to your environment variable

**Comment by zplzpl** [comment]
the system I use is Windows 7;

If I do not set the environment variable, will not come into effect?

**Comment by zplzpl** [comment]
I went to set the environment variable, but unfortunately did not produce results

**Comment by ShiYu-Yang** [comment]
It means that if you set your environment variable,you don't need to set gopath in VSC.
"go.gopath" : ""

**Comment by ramya-rao-a** [comment]
@zplzpl Since you are on Windows, the paths should be separated by `;` and not `:`
So add this to your settings and it should work
`"go.gopath": "E:\goapp;E:\goproject\new-app"`

**Comment by zplzpl** [comment]
Yes, I'm using `;` as a separator, but it doesn't work.

System environment variables and go.gopath are set, whether the go.gopath will not come into effect？

**Comment by ramya-rao-a** [comment]
If you have set environment variables after opening VS Code, then it will not take effect.

When both environment variable GOPATH and the user setting `go.gopath` is set, then `go.gopath` overrides the value in the environment variable in VS Code.

Can you share how you are testing whether the multiple GOPATH work or not?

**Comment by zplzpl** [comment]
windows environment:
GOPATH -> E:\goapp\

launch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/src",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}`

settings.json
{
    "go.gopath":"E:\\goapp;E:\\goproject\\cecs-magento-sync"
}

debug console: [loss gopath E:\\goproject\\cecs-magento-sync]
`app.go:4:2: cannot find package "config" in any of:
	E:\Go1.6.2\src\config (from $GOROOT)
	E:\goapp\src\config (from $GOPATH)
app.go:5:2: cannot find package "models" in any of:
	E:\Go1.6.2\src\models (from $GOROOT)
	E:\goapp\src\models (from $GOPATH)
app.go:8:2: cannot find package "utils" in any of:
	E:\Go1.6.2\src\utils (from $GOROOT)
	E:\goapp\src\utils (from $GOPATH)
exit status 1
`
![debug1](https://cloud.githubusercontent.com/assets/7931755/20780803/f7d5d536-b7b8-11e6-85dd-e85873c99b09.png)

**Comment by ramya-rao-a** [comment]
I was able to repro this by removing GOPATH from my environment, setting GOPATH in `go.gopath` and trying to debug.

Looks like the problem is that the debugging process doesn't read GOPATH from `go.gopath`.

Can you confirm this by checking if reset of the Go extension features work for you?
Like `Go to definition`, `Rename` ?

**Comment by zplzpl** [comment]
About debugging, I also have a problem, I first time according to the F5 key debugging can work normally, when I press the F5 button second times, but did not respond to the debugging

**Comment by zplzpl** [comment]
debugging process doesn't read GOPATH from go.gopath.

I also verified this idea.

**Comment by zplzpl** [comment]
How to solve the problem when debugging GOPATH?

**Comment by ramya-rao-a** [comment]
#356 was logged to track the issue of GOPATH not being read from the settings by the debug process.
There is a workaround mentioned in that issue that you can try.
Will try and get a fix for this in the next update

**Comment by ramya-rao-a** [comment]
@zplzpl As of now, there is no way to pass the settings to the debugger.
Therefore, setting the `env` property in `launch.json` as suggested in #356 is the way to go.
