### ISSUE TITLE
Debug with delve is not working unless `showLogs: true` is on...

### ISSUE THREAD

**Issue by huttarichard** [Microsoft/vscode-go#651]
Guy(s) awesome project love it!

Version is latest published in marketplace.

As soon as I removed showLogs: true in launch.json, extension just hangs when you start debugging..

You need to start dlv with:
`/usr/local/bin/dlv debug --headless=true --listen=127.0.0.1:44316 --log=true --`
--log=true

with this option, debugger will run properly:

```
2016/11/26 11:33:23 debugger.go:55: launching process with args: [./debug]
2016/11/26 11:33:23 server.go:301: method Run has wrong number of ins: 1
2016/11/26 11:33:23 server.go:301: method Stop has wrong number of ins: 2
2016/11/26 11:33:23 debugger.go:177: created breakpoint: &api.Breakpoint{ID:1, Addr:0x5b0db, File:"/Users/richard/Desktop/go-projects/src/github.com/huttarichard/seservice/server/server.go", Line:67, FunctionName:"github.com/huttarichard/seservice/server.Run", Tracepoint:false, Stacktrace:0, Goroutine:false, Variables:[]string(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2016/11/26 11:33:23 debugger.go:239: continuing
```

Maybe it is related to this line?
https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L235

not sure...

Thanks!

**Comment by roblourens** [comment]
What version of delve?

**Comment by roblourens** [comment]
For me, it always prints "API server listening at..." whether or not showLog is set, so that's what kicks it off. Maybe there's a case where this doesn't happen.

**Comment by huttarichard** [comment]
Im using mac el captain 

Delve Debugger
Version: 0.11.0-alpha
Build: v0.11.0

**Comment by trdyer** [comment]
I'm using osx el capitan with Delve 0.11.0-alpha (installed with homebrew) and getting the same issue.

without "showLogs": true I just get the progress bar spinning.

**Comment by ramya-rao-a** [comment]
The `showLog` parameter is used only to pass the set value while starting delve.

@bawr you had initially introduced this paramater in the Go extension. Do you have any idea why setting this to false would result in the behavior mentioned in the previous comments?

**Comment by kjleng** [comment]
I have having the same experience as @trdyer

**Comment by ramya-rao-a** [comment]
Hello all, 
I was able to repro this in my Mac (where I had previously installed delve via brew) and not in Windows.

Updating to the latest delve (v0.12.1) solved this for me.

Here are my steps:
- `brew uninstall delve`
- `brew install go-delve/delve/delve`
- restart VS Code

@kjleng @trdyer @huttarichard : Can you guys update you delve and try as well?

**Comment by huttarichard** [comment]
@ramya-rao-a Awesome!!!

**Comment by ramya-rao-a** [comment]
@huttarichard So I take it that the issue is solved for you?

**Comment by kjleng** [comment]
@ramya-rao-a I took the steps above and the issue is resolved. Thanks.

**Comment by huttarichard** [comment]
@ramya-rao-a resolved

**Comment by huttarichard** [comment]
good job
