### ISSUE TITLE
go get go-symbols timeout

### ISSUE THREAD

**Issue by a57571735** [Microsoft/vscode-go#653]
$ go get -u -v github.com/newhook/go-symbols
github.com/newhook/go-symbols (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

also
  go-symbols
  guru
  gorename
  goreturns
  golint
  gotests

**Comment by a57571735** [comment]
Installing 6 tools
  go-symbols
  guru
  gorename
  goreturns
  golint
  gotests

Installing go-symbols FAILED
Installing guru FAILED
Installing gorename FAILED
Installing goreturns FAILED
Installing golint FAILED
Installing gotests FAILED

6 tools failed to install.

go-symbols:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/newhook/go-symbols
# cd /Users/ahjesus/Git/Bag/src/github.com/newhook/go-symbols; git config remote.origin.url
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
package github.com/newhook/go-symbols: exit status 1
# cd /Users/ahjesus/Git/Bag/src/github.com/newhook/go-symbols; git config remote.origin.url
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
package github.com/newhook/go-symbols: exit status 1

guru:
Error: Command failed: /usr/local/go/bin/go get -u -v golang.org/x/tools/cmd/guru
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/guru: unrecognized import path "golang.org/x/tools/cmd/guru" (https fetch: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/guru: unrecognized import path "golang.org/x/tools/cmd/guru" (https fetch: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

gorename:
Error: Command failed: /usr/local/go/bin/go get -u -v golang.org/x/tools/cmd/gorename
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/gorename: unrecognized import path "golang.org/x/tools/cmd/gorename" (https fetch: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/gorename: unrecognized import path "golang.org/x/tools/cmd/gorename" (https fetch: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

goreturns:
Error: Command failed: /usr/local/go/bin/go get -u -v sourcegraph.com/sqs/goreturns
# cd /Users/ahjesus/Git/Bag/src/sourcegraph.com/sqs/goreturns; git config remote.origin.url
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
package sourcegraph.com/sqs/goreturns: exit status 1
# cd /Users/ahjesus/Git/Bag/src/sourcegraph.com/sqs/goreturns; git config remote.origin.url
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
package sourcegraph.com/sqs/goreturns: exit status 1

golint:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/golang/lint/golint
github.com/golang/lint (download)
# cd .; git clone https://github.com/golang/lint /Users/ahjesus/Git/Bag/src/github.com/golang/lint
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
package github.com/golang/lint/golint: exit status 1
github.com/golang/lint (download)
# cd .; git clone https://github.com/golang/lint /Users/ahjesus/Git/Bag/src/github.com/golang/lint
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
package github.com/golang/lint/golint: exit status 1

gotests:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/cweill/gotests/...
github.com/cweill/gotests (download)
# cd .; git clone https://github.com/cweill/gotests /Users/ahjesus/Git/Bag/src/github.com/cweill/gotests
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
package github.com/cweill/gotests/...: exit status 1
github.com/cweill/gotests (download)
# cd .; git clone https://github.com/cweill/gotests /Users/ahjesus/Git/Bag/src/github.com/cweill/gotests
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
package github.com/cweill/gotests/...: exit status 1

**Comment by a57571735** [comment]
Installing 1 tools
  golint

Installing golint FAILED

1 tools failed to install.

golint:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/golang/lint/golint
github.com/golang/lint (download)
Fetching https://golang.org/x/tools/go/gcimporter15?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcimporter15?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcimporter15": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcimporter15?go-get=1
get "golang.org/x/tools/go/gcimporter15": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
# cd .; git clone https://go.googlesource.com/tools /Users/ahjesus/Git/Bag/src/golang.org/x/tools
Cloning into '/Users/ahjesus/Git/Bag/src/golang.org/x/tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': SSLRead() return error -9806
package golang.org/x/tools/go/gcimporter15: exit status 128
github.com/golang/lint (download)
Fetching https://golang.org/x/tools/go/gcimporter15?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcimporter15?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcimporter15": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcimporter15?go-get=1
get "golang.org/x/tools/go/gcimporter15": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
# cd .; git clone https://go.googlesource.com/tools /Users/ahjesus/Git/Bag/src/golang.org/x/tools
Cloning into '/Users/ahjesus/Git/Bag/src/golang.org/x/tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': SSLRead() return error -9806
package golang.org/x/tools/go/gcimporter15: exit status 128

**Comment by ramya-rao-a** [comment]
Are you getting this error only while getting `go-symbols` or even rest of the tools?
Can you share the output for `go env` and `go version` ?

**Comment by a57571735** [comment]
myMacBook-Pro:~ adrian$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/adrian/Git/Bag:/Users/adrian/Git/CloudNumber"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c_/z3wg1g3j4vb48n6vr8t2sv6c0000gp/T/go-build748633615=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
myMacBook-Pro:~ adrian$ go version
go version go1.7.3 darwin/amd64
myMacBook-Pro:~ adrian$

**Comment by a57571735** [comment]
Installing 6 tools
  go-symbols
  guru
  gorename
  goreturns
  golint
  gotests

Installing go-symbols FAILED
Installing guru FAILED
Installing gorename FAILED
Installing goreturns SUCCEEDED
Installing golint SUCCEEDED
Installing gotests FAILED

4 tools failed to install.

go-symbols:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/newhook/go-symbols
github.com/newhook/go-symbols (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/newhook/go-symbols (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

guru:
Error: Command failed: /usr/local/go/bin/go get -u -v golang.org/x/tools/cmd/guru
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/guru: unrecognized import path "golang.org/x/tools/cmd/guru" (https fetch: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/guru: unrecognized import path "golang.org/x/tools/cmd/guru" (https fetch: Get https://golang.org/x/tools/cmd/guru?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

gorename:
Error: Command failed: /usr/local/go/bin/go get -u -v golang.org/x/tools/cmd/gorename
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/gorename: unrecognized import path "golang.org/x/tools/cmd/gorename" (https fetch: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/tools/cmd/gorename: unrecognized import path "golang.org/x/tools/cmd/gorename" (https fetch: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

gotests:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/cweill/gotests/...
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
# cd /Users/adrian/Git/Bag/src/golang.org/x/tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/tools/imports: exit status 1
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
# cd /Users/adrian/Git/Bag/src/golang.org/x/tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/tools/imports: exit status 1

**Comment by a57571735** [comment]
Installing 1 tools
  gotests

Installing gotests FAILED

1 tools failed to install.

gotests:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/cweill/gotests/...
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
https fetch failed: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
golang.org/x/tools (download)
# cd /Users/adrian/Git/Bag/src/golang.org/x/tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/tools/imports: exit status 1
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
https fetch failed: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
golang.org/x/tools (download)
# cd /Users/adrian/Git/Bag/src/golang.org/x/tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/tools/imports: exit status 1

**Comment by a57571735** [comment]
https://github.com/cweill/gotests/...    404

**Comment by a57571735** [comment]
I can visit https://go.googlesource.com/tools/

**Comment by leaxoy** [comment]
please use proxy for vscode, configuration key is `http.proxy`.
or manual install from command line

**Comment by a57571735** [comment]
I already used pptp vpn, I can visit https://go.googlesource.com/tools/ and github

**Comment by ramya-rao-a** [comment]
@a57571735 Are you able to run `go get` for these tools from the command line?
Example: 
- `go get -u -v github.com/cweill/gotests/...`
- `go get -u -v github.com/newhook/go-symbols`
- `go get -u -v golang.org/x/tools/cmd/gorename`

Like @leaxoy suggested can you set `http.proxy` in your settings and try too?

**Comment by leaxoy** [comment]
Do steps as flows. Because I had the same problem due to live in china.
1. setup an vpn(for me: shadowsocks), then transform `socks5` to `http` protocol.
2. in command line, `export http_proxy=${proxyhost:proxyport} https_proxy=${proxyhost:proxyport}`
3. get tool like `go get -u -v golang.org/x/tools`.
4. install tool with `go build golang.org/x/tools/cmd/guru`

Hopes this help you!!!

**Comment by a57571735** [comment]
I used Cow https://github.com/cyfdecyf/cow to transform socks5 to http protocol, then set vscode configuration key http.proxy, also failed...

**Comment by a57571735** [comment]
@ramya-rao-a @leaxoy @mattetti @buckett @saml  Thanks to help me, but I want to give it up, I try it to the best of my ability, failed!failed!failed!failed!failed!failed!failed!failed!
Go to hell GOLANG

**Comment by a57571735** [comment]
wooooooow,SUCCEEDED! I remember I have seen through the modify hosts to access some websites, I said last try one more time, BINGO! If any one had the same problem, do as flows, open [58hlsg.com](58hlsg.com), click 外网Hosts, you'll see, realy very very simple and easy. GOLANG am coming!

**Comment by jonwinters** [comment]
@a57571735 
同为墙内狗，看了你这个文章 我的go终于安装成功了

**Comment by Go101** [comment]
Looks this issue has nothing related to the network.
I encountered the same problem and just deleted the GOPATH/pkg folder, then re-get and it becomes ok.

**Comment by YouZhengChuan** [comment]
@jonwinters 怎么弄的？设置的代理吗？你有http和https的免费代理可以用吗？

**Comment by a57571735** [comment]
@YouZhengChuan 之前的提供的那个挂了，你现在可以用 58jiasu.com 免费的梯子

**Comment by caryyu** [comment]
参考博客：http://blog.csdn.net/littlebrain4solving/article/details/78871137
