### ISSUE TITLE
Fix "gotests" when generates test for current function

### ISSUE THREAD

**Issue by cedriclam** [Microsoft/vscode-go#656]
Issue: "Generate unit tests for current function" fails with recent vscode-go version. This due to the fact that the GoDocumentSymbolProvider returns now also the receiverType in the name function.

example: 
- before ```DecodeJSON```
- last vscode-go version: ```(*Volume).DecodeJSON``` 

```gotests``` bin is not able to understand this string with the option -only since it is not a valid regular expression.

Fix: check is the function name contains a ".", if yes: returns only the second part of the name that is corresponding to the function name without the receiverType.

**Comment by ramya-rao-a** [comment]
Are you sure this worked before?
`GoDocumentSymbolProvider` and the tool it uses (`go-outline`) hasn't seen any changes recently regarding its output.
So I don't see any reason why this would work before and only the recent Go extension would break it

**Comment by cedriclam** [comment]
So maybe the feature never worked properly from the beginning :(
It was only tested with a global function and not a method of a struct.

**Comment by cedriclam** [comment]
I also opened an Issue to ```gotests``` for a feature request in order to support the type in the regular expression input with the ```-only``` option.

link: https://github.com/cweill/gotests/issues/35
