### ISSUE TITLE
debug console scrollable horizontally, just like code 

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/vscode-go#66]
would make debugging much smoother is the debug console window was scrollable horizontally.
in a code window its nice that i can scroll easily to see long longs.

If there is a way to maybe force the debug console window to flow onto the next line that would be also good.

**Comment by lukehoban** [comment]
Yes - one or both of these does seem necessary to make the debug console usable.

**Comment by lukehoban** [comment]
This issue was moved to Microsoft/vscode#503
