### ISSUE TITLE
Compile errors stop appearing/updating

### ISSUE THREAD

**Issue by ctrlaltdel121** [Microsoft/vscode-go#663]
Occasionally, with vscode-go the build on save stops running. I'll get an error, and then fix the error, but the red squiggly remains. If I introduce a new compile errror, I don't get a squiggly on that.

Autocomplete is still working, but format on save is also broken during this time.

I can recover from this by closing and re-opening the window. On reload, it works for a while until it stops again.

I've looked in my Go output pane and in developer tools and no messages appear in either, so I guess nothing is running. Not sure what is preventing it. Anywhere else I can look for more information?

**Comment by ramya-rao-a** [comment]
Looks like you end up in a state where save does not trigger the usual actions like format, lint and build.

This could mean a problem with the core product or that some other extension is interfering with the save event. Can you disable all the other extensions and see if you still see this? 

When you enter this state, does manual format work ?

**Comment by SimonBuckner** [comment]
I've just had this problem. This was caused by me commenting out one of my files in a package. Once I uncommented the package line and saved the file. Once I did that errors were highlighted properly.

**Comment by ramya-rao-a** [comment]
@SimonBuckner Can you give a sample code?

**Comment by ramya-rao-a** [comment]
Closing this as we havent heard back from OP with answers to the questions asked.

If anyone sees the same issue, please drop in a comment and we can help narrow down the issue and root cause.
