### ISSUE TITLE
No build errors when code fails on import cycle

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode-go#664]
When I get an accidental import cycle, I get zero build errors in VSCode. But manually building, I of course get:

```
$ go build -v github.com/sanity-io/gradient/pkg/search/queryengine
can't load package: import cycle not allowed
[etc.]
```

This is frustrating because when this happens, it appears that compilation/linting has just stopped working.

(Funnily enough, Atom's `go-plus` package has the exact same issue.)

My Go settings:

```
	"go.buildOnSave": true,
	"go.lintOnSave": true,
	"go.vetOnSave": true,
	"go.lintTool": "gometalinter",
	"go.lintFlags": [
		"--disable-all",
		// Linters
		"--enable=deadcode",
		"--enable=vetshadow",
		"--enable=golint",
		//"--enable=errcheck",
		"--enable=ineffassign",
		"--enable=goconst",
		// Exclude stuff
		"--exclude=\\.pb\\.go",
		"--exclude=or be unexported",
		"--exclude=that.stutters",
		"--exclude=don't use underscores",
		"--exclude=\\.nolint\\.go",
		"--vendor",
		"--tests"
	],
	"go.useCodeSnippetsOnFunctionSuggest": false,
	"go.formatOnSave": true,
	"go.formatTool": "goreturns",
```

**Comment by ramya-rao-a** [comment]
This is due to the regex check on build errors happening at https://github.com/Microsoft/vscode-go/blob/master/src/goCheck.ts#L47

**Comment by ramya-rao-a** [comment]
Such errors do not have a filename/linenumber for the editor to use to show the red squiggly lines.

With #732 you can now this see this error in the output pane.

I'll keep looking at a way to get a visual indicator in the file as well. Maybe a red squiggly in the line that defines the "package" ?

**Comment by atombender** [comment]
Yes — errors without a line number can be associated with line 1, in my opinion. Not ideal, but better than no error at all. I use "go to next marker" to find the next error to fix, and obviously the import cycle error doesn't show up that way.

**Comment by atombender** [comment]
Awesome -- thanks, @ramya-rao-a!

**Comment by ramya-rao-a** [comment]
The latest update (0.6.53) has this fix.
Happy Coding!

**Comment by atombender** [comment]
Hooray!
