### ISSUE TITLE
Multi-line string highlighting with backtick

### ISSUE THREAD

**Issue by brandonblock** [Microsoft/vscode-go#666]
When I paste a multiline string as a variable value and surround the string with a backtick, only the first line is highlighted. If I do a new line after the = the highlighting works but gofmt moves the value back to the same line as the assignment.

![screen shot 2016-11-29 at 13 11 14](https://cloud.githubusercontent.com/assets/2208544/20724818/5d49e658-b635-11e6-8e93-1abb15941d2d.png)

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#103
