### ISSUE TITLE
Debugger not working, no feedback on what is wrong.

### ISSUE THREAD

**Issue by coussej** [Microsoft/vscode-go#67]
Using the instructions provided in the readme, I have installed the delve debugger on Mac and create a launch.json as in the example. However, when I start the debugging on a (working) application, nothing happens. The statusbar turns orange, but no breakpoints are hit, no output is generated. I don't get any errors, also not in the console of the developer tools.

I've updated the plugin to the latest version yesterday evening. Any advice on how to find out what exactly my problem is?

(Other than the issue I have above, my experience so far is very positive. Nice work!)

**Comment by lukehoban** [comment]
@coussej Thanks.  

Do you have the latest version of `vscode-go` by chance (`0.6.11`)?  There should have been fixes for a few debugging issues, including displaying more information about what the debugger is doing in the debug console.

If you do, and still have issues, could you add more details along the lines of what is described in https://github.com/Microsoft/vscode-go/issues/51#issuecomment-158703417, and reopen this issue?

**Comment by coussej** [comment]
I do indeed have the latest version. I have a very simple program: 
![screen shot 2015-11-23 at 22 27 01](https://cloud.githubusercontent.com/assets/9944663/11350426/caba0bba-9231-11e5-95be-205ccebbdabc.png)

When I run with the following configuration:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch main.go",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "/Users/jeroen/golang/src/github.com/coussej/hello/main.go",
			"env": {},
			"args": []
		}
	]
}
```

... nothing happens:

![screen shot 2015-11-23 at 22 27 32](https://cloud.githubusercontent.com/assets/9944663/11350432/d0eb2cb2-9231-11e5-84a4-22e6aa9bb9c0.png)

the dlv command is working, I can debug the app using dlv debug in terminal.
