### ISSUE TITLE
duplicated warnings when using gometalinter

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode-go#672]
the output:
>Finished running tool: /usr/local/go-ext-path/bin/gometalinter --disable=gotype --enable=misspell
/root/k8s-branch-fix-glog-message-typo/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:80: cyclomatic complexity 29 of function Run() is high (> 10) (gocyclo)
/root/k8s-branch-fix-glog-message-typo/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:150: TLS InsecureSkipVerify set true.,HIGH,HIGH (gas)
/root/k8s-branch-fix-glog-message-typo/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:150: TLS InsecureSkipVerify set true.,HIGH,HIGH (gas)
/root/k8s-branch-fix-glog-message-typo/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:150: TLS InsecureSkipVerify set true.,HIGH,HIGH (gas)
/root/k8s-branch-fix-glog-message-typo/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:100: declaration of "err" shadows declaration at server.go:96 (vetshadow)
/root/k8s-branch-fix-glog-message-typo/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:121: declaration of "err" shadows declaration at server.go:96 (vetshadow)
/root/k8s-branch-fix-glog-message-typo/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:222: declaration of "err" shadows declaration at server.go:96 (vetshadow)

you can see there are 3 gas warnings from line 150
`proxyTLSClientConfig := &tls.Config{InsecureSkipVerify: true}`

this results in that there are 2 extra warnings in left-bottom corner.

**Comment by ramya-rao-a** [comment]
@bruceauyeung Can you run `gometalinter` in the command line and see if you get the same results?
If yes, then this is an issue with `gometalinter` itself and should be logged in its repo

**Comment by ramya-rao-a** [comment]
This issue was moved to alecthomas/gometalinter#231
