### ISSUE TITLE
No intelligence

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#676]
_From @HopeForToday on December 1, 2016 6:28_

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.51|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1.vsCode cannot list the member or func of fmt, when I typed “fmt.”
2.But in other people's vsCode, it will list...I don't know what to do

_Copied from original issue: Microsoft/vscode#16310_

**Comment by ramya-rao-a** [comment]
_From @chrmarti on December 1, 2016 16:25_

I guess that is with Go? Have you set the GOPATH environment variable?

**Comment by ramya-rao-a** [comment]
@HopeForToday

Are you having auto-complete issues only with `fmt` and standard library or even custom packages?
Does this happen on all of your Go projects?
Do you see any error in the console? Open `Developer: Toggle Developer Tools` to see the console.
Can you share your settings and sample code?

**Comment by qiuhaotc** [comment]
thx when i try this [https://github.com/Microsoft/vscode-go/issues/441](url),problems seemed to be solved.
