### ISSUE TITLE
Goto Definition, Hover, Signature Help stopped working when using gogetdoc

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#679]
From @zgiber in https://github.com/Microsoft/vscode-go/issues/442#issuecomment-264718041:

> I'm using go version go1.7.4 darwin/amd64, not from source, but from archive. The Go plugin is now version 0.6.51. After adding the line: `"go.docsTool": "gogetdoc",` to user settings and restarting VSCode, Goto/Peek definition, Hover info, Signature stopped working. Removing the line restored the usual functionalities, but then the original issue (no tooltip on net package's functions) remains.

**Comment by ramya-rao-a** [comment]
@zgiber Can you check if there are any errors in the console? You can run `Developer: Toggle Developer Tools` to open the console.

Are you able to run `gogetdoc` in the command line?

**Comment by zgiber** [comment]
@ramya-rao-a Yes and I think this will help. I wish I knew about the console earlier.. shame but haven't looked at it yet.
```
[Extension Host] Error: Command failed: /Users/zgiber/dev/go/bin/gogetdoc -u -json -modified -pos /Users/zgiber/dev/go/src/github.com/zgiber/exo/pcontrol/validation.go:#791
flag provided but not defined: -u
Usage of /Users/zgiber/dev/go/bin/gogetdoc
  -cpuprofile string
    	write cpu profile to file
  -json
    	enable extended JSON output
  -linelength int
    	maximum length of a line in the output (in Unicode code points) (default 80)
  -modified
    	read an archive of modified files from standard input
  -pos string
    	Filename and byte offset of item to document, e.g. foo.go:#123

The archive format for the -modified flag consists of the file name, followed
by a newline, the decimal file size, another newline, and the contents of the file.

This allows editors to supply gogetdoc with the contents of their unsaved buffers.

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by ramya-rao-a** [comment]
It says, that the flag `-u` is not supported. Maybe you have an old version of `gogetdoc`. Can you update it?

`go get -u github.com/zmb3/gogetdoc`

**Comment by zgiber** [comment]
@ramya-rao-a Thank you that was it. I thought that Go Install tools did update it to the latest, but apparently it wasn't.

**Comment by ramya-rao-a** [comment]
You mean the command `Go: Install Tools` ? If you had `go.docsTool` set to `gogetdoc` and then run the command, then yes it should have updated it for you.

Anyway, glad you are unblocked now.
Happy coding
