### ISSUE TITLE
code snippet/autocomplete menu is very slow

### ISSUE THREAD

**Issue by chrisolsen** [Microsoft/vscode-go#681]
In the last while getting the snippet/autocomplete menu to be shown now takes about 5 seconds for a medium sized project. However, if I create a new `.go` file outside the project it is back to being fast.

OS: windows 10
vscode: 1.7.2
vscode-go: 0.6.51

**Comment by ramya-rao-a** [comment]
Can you try setting `go.autocompleteUnimportedPackages` to false and see if it is still slow?
This is to see if the extra steps we take to provide auto-completion for unimproved pkgs is the reason for the slowness.

If not, then can you try running `gocode` in the command line and compare the performance?

**Comment by chrisolsen** [comment]
There doesn't seem to be any difference when with `go.autocompleteUnimportedPackages` set to false.
 
For the `gocode` command, is it the `gocode autocomplete` command I should test?

**Comment by chrisolsen** [comment]
Things seem to have sped back up, not sure if running the `gocode status` command would do that...

**Comment by ramya-rao-a** [comment]
Closing for now. If you see more issues, feel free to re-open and we can narrow it down to whether there is an issue with the extension or `gocode` itself

**Comment by chrisolsen** [comment]
Things getting slow has become an issue again.  I am working on a new project and the project has reached a medium size. I am back to having to wait 5 seconds or more before getting any response for autocomplete and go vet. Currently I am using all the default vscode-go settings.

**Comment by ramya-rao-a** [comment]
For autocomplete, I'd suggest you try the following

- `gocode close`
- `go get -u github.com/nsf/gocode`

And see if you still have issues.

For `go vet`, can you try running `go vet` from the command line and compare the speed?

**Comment by chrisolsen** [comment]
After closing and updating gocode, autocomplete is still as slow as it was before. `go vet` runs in about a half a second, but to see updates in the vscode editor it is stil a few seconds.

**Comment by chrisolsen** [comment]
I also noticed that things are also very slow when trying to view the snippet list. Does this make it a vscode issue or can one slow down the other?

**Comment by chrisolsen** [comment]
After setting `"go.gocodeAutoBuild": false` as mentioned [here](https://github.com/Microsoft/vscode-go/issues/696) things are suddenly fast again.

**Comment by ramya-rao-a** [comment]
I really should set up a FAQ/Troubleshooting page, I myself keep forgetting some of these nuances :)

Yes, setting autobuild to `true` for gocode does pose some perf issues

Regarding vet being slow, can you set `go.lintOnSave`, `go.buildOnSave`, `go.vetOnSave`, `go.testOnSave` all to `false`. Then try turning each of them on one by one? The results from all these 4 features are combined and only then surfaced in the editor currently. So it may be the case, that `vet` actuall is done real fast, but one of these other 3 culprits might be slow, thus slowing down the whole party.

If that is the case, then I can look into NOT coupling these.

**Comment by chrisolsen** [comment]
Having all those options turned on still seems to be pretty fast and there is no noticeable difference in time when incrementally turning them on.  The huge slow down was due to the `gocodeAutoBuild` option and having this option turned off seems to make more sense to me anyway.

Thanks for the help.  Hopefully this thread is closed for good.

**Comment by ramya-rao-a** [comment]
great then, Happy Coding!
