### ISSUE TITLE
How can I get gofmt error info ?

### ISSUE THREAD

**Issue by ShiYu-Yang** [Microsoft/vscode-go#682]
I don't know how to see gofmt error info

I think that gofmt is not only a format file tool but a tool helps me check my code whenever I want.

But when I have some error in my code and save it , gofmt doesn't work and show nothing.

I know gofmt will show info like this:
gen_code.go:23:22: expected ')', found '{'
gen_code.go:24:2: expected ';', found 'return'

Can I see it in a front panel?

**Comment by ramya-rao-a** [comment]
Currently, the errors from the formatting tool go to the console. Run `Developer: Toggle Developer Tools` to see the console.

If you have build, vet and lint on save enabled, then wouldnt errors from those actions cover what you would have otherwise gotten from `gofmt` ?

**Comment by ShiYu-Yang** [comment]
I am sorry but I got nothing with go vet or lint too.

There is the easy code
`package main
func Test(     {
}
`

Terminal show
➜ ~$  /home/ysy/go/bin/go tool vet /tmp/test.go                                       
vet: /tmp/test.go: /tmp/test.go:3:16: expected type, found '{' (and 1 more errors)
vet: no files checked

VSCode output just show like this 
Finished running tool: /home/ysy/go/bin/go tool vet /tmp/test.go

**Comment by ShiYu-Yang** [comment]
Wow,now I know that vet tool just is for some static syntax error! 
And I open buildOnSave to check error.
Thank you!

**Comment by ramya-rao-a** [comment]
Use `buildOnSave`, `vetOnSave` and `lintOnSave` and see which works best for you
