### ISSUE TITLE
Command to run short unit tests

### ISSUE THREAD

**Issue by calrsom** [Microsoft/vscode-go#683]
It would be nice to have a palette command to run `go test -short` that I could bind to a keyboard shortcut.  This would be great to quickly run the short test cases while I'm coding to make sure I didn't break anything.

**Comment by ramya-rao-a** [comment]
Would having `go.testFlags` that you can set in the settings help? There was a [PR](#482) to do that. Please do chime in with your thoughts here #401

**Comment by calrsom** [comment]
Yes, I think that would be helpful, although I still think it would be really nice to be able to bind a shortcut for running short tests. I suppose short/package is the combination that would probably be most useful.

**Comment by ramya-rao-a** [comment]
This can be independent of the test flags feature. Having a command `Go: Test Package (Short)` would be a good addition.

This is an easy change. PRs are welcome.

**Comment by ramya-rao-a** [comment]
cc @ironcladlou

**Comment by ironcladlou** [comment]
The VSCode 1.8 release has a [neat new feature](https://code.visualstudio.com/updates#_keyboard-shortcuts) which allows binding shortcuts which pass arguments to commands. Would it make any sense to register a generic `go.test` command which can be invoked with arguments which can amend or override certain things (like the test flags)? For example, the following might be possible:

```
{
  "key": "cmd+shift+t",
  "command": "go.test",
  "args": {
    "mode": "package",   // runs all tests in the current package
    "flags": ["-short"] // adds some flags to the internal default flag list
  }, 
  "when": "editorTextFocus"
}
```

Thinking further, it might even be possible to refactor the "core" test runner command in such a way that one could use it to drive the test runner in any context (e.g. at cursor, in package, in file) in a custom key binding. Ultimately these more specific commands are just setting up different input to a [generic test runner function](https://github.com/Microsoft/vscode-go/blob/master/src/goTest.ts#L139).

Seems like we could come up with something flexible enough to enable users to build out whatever test executions they need. Coming up with a list of use cases would be helpful to figure this out, and probably in a separate issue.

Continuing to add small variants of the test runner options as formal commands for every use case would also work, but would lead to command clutter.

Hope this wasn't overly analytical! Thanks for the cc, @ramya-rao-a, and thanks for opening the discussion @calrsom.

P.S., if there's any interest in the generic command idea, I have free time over the next couple weeks and would be happy to work on it.

**Comment by ramya-rao-a** [comment]
That's a great idea @ironcladlou and seems like the right way to go. Am here to review and test it, so feel free to send a PR.

Note: Since this would need the latest VS Code APIs which in turn needs a more recent typescript dependency, you will need #669 to go in before you get started.

**Comment by ramya-rao-a** [comment]
@ironcladlou 

The Go extension now can use the latest VS Code API (https://github.com/Microsoft/vscode-go/blob/master/package.json#L52), so you should be able to get the new feature.

**Comment by ramya-rao-a** [comment]
@ironcladlou I have updated the PR #482 to reflect your suggestions. Can you take a look?

**Comment by ramya-rao-a** [comment]
The latest update (0.6.53) has the option to add testflags applicable to all tests as well as key bindings to run any of the 3 test commands with any flags.

From the ChangeLog:

   * A new setting `go.testFlags` that can be used to run tests. If null, `go.buildFlags` will be used. [PR 482](https://github.com/Microsoft/vscode-go/pull/482)
    * Customize flags for each of the test command by using different keybindings. [PR 482](https://github.com/Microsoft/vscode-go/pull/482). In the below example, `ctrl+shift+t` is bound to run the tests in current file with `-short` flag. The commands here can be `go.test.package`, `go.test.file` or `go.test.cursor`.
        ```json
        {
            "key": "ctrl+shift+t",
            "command": "go.test.file",
            "args": {
                "flags": ["-short"]
            },
            "when": "editorTextFocus"
        }
        ```
