### ISSUE TITLE
vscode and godef use high cpu (with steps)

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#684]
_From @zakokun on December 6, 2016 4:45_

- VSCode Version: 1.7.2
- OS Version: macOS Sierra
- go version: go1.7.3

extensions: 
 ![extension](http://ww1.sinaimg.cn/large/73c5712dgw1fagy7tsv5gj20bi0dudgh.jpg)

Steps to Reproduce:

1.  open vscode
2.  open a  ` .go` file, use `go def` many times
3.  then vscode use cpu high
 ![extension](http://ww3.sinaimg.cn/large/73c5712dgw1fagyr0o168j20cg06q74o.jpg)
4. use `commad +Q` quit vcode, I see many `godef` process 
 ![extension](http://ww1.sinaimg.cn/large/73c5712dgw1fagyu6a0ykj20bu04y3yl.jpg)

see `ps aux`

 ![extension](http://ww2.sinaimg.cn/large/73c5712dgw1fagywtlmk1j21kw05l43j.jpg)

`/Users/zhanghongwen/golang/src/download/load.go` is the test go file

`/Users/zhanghongwen/golang/` is the `GOPATH`

_Copied from original issue: Microsoft/vscode#16566_

**Comment by ameissnersofi** [comment]
+1 this issue.  All these `godef` processes really eat up my CPU and don't leave me with much anything else.  Please fix this bug!

**Comment by ramya-rao-a** [comment]
@zakokun, @ameissnersofi Did you both recently upgrade to Mac OS X Sierra?

There is a known issue of performance on Mac OS X Sierra. See #503 

Run the command `Go: Install Tools`. That should update all the go tools that the extension depends on which should fix the issue

**Comment by ameissnersofi** [comment]
Yes, I did upgrade.  I can't remember how long ago, but this all seems to be connected because delve debugger is also having trouble on Sierra.  

I'll run this command first thing in the morning and report back.  Thanks for responding so quickly!

**Comment by ameissnersofi** [comment]
@ramya-rao-a, after running `Go: Install Tools`, I get the following error: `command 'go.tools.install' not found`.  What am I missing?

**Comment by zakokun** [comment]
yes! I updated those tools and it fixed!  I can use vscode again. thank you very much~ @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Glad to help. @ameissnersofi Are you unblocked too?

**Comment by ameissnersofi** [comment]
@ramya-rao-a yes!  I'm sorry, I meant to respond sooner.  I've got my team back up and running on vscode again.  Thanks so much!!!

**Comment by ramya-rao-a** [comment]
Great, Happy Coding!
