### ISSUE TITLE
Missing code hinting

### ISSUE THREAD

**Issue by qiuhaotc** [Microsoft/vscode-go#685]
Often missing the code hinting when After the compiler error
![qq 20161210095059](https://cloud.githubusercontent.com/assets/8034473/21070342/77c0766e-bebe-11e6-8257-0c206546a635.png)

**Comment by ramya-rao-a** [comment]
@qiuhaotc Can you provide an example with the compile error?

I get the auto-complete when working on code that doesn't build successfully

**Comment by mattetti** [comment]
I saw this issue many times after updating go and forgetting to restart vscode/gocode. VSCode relies on gocode which is run as a daemon. If Go is updated but gocode not restarted, then things break. Another reason would be that the go tools aren't installed, a warning should appear on your screen tho (look at the bottom right of your screen for another warning).

@ramya-rao-a this issue has been open for 30 days without feedback, could we close it please?

**Comment by qiuhaotc** [comment]
fixed with reinstall

**Comment by mattetti** [comment]
@qiuhaotc awesome, do you mind closing this issue?

**Comment by qiuhaotc** [comment]
@mattetti sure
