### ISSUE TITLE
Ctrl+Shift+I causes "Cannot read property 'substring' of undefined"

### ISSUE THREAD

**Issue by mdmarek** [Microsoft/vscode-go#690]
After updating to version `1.8.0` of VS Code, with vscode-go verison `0.6.51`, trying to format document with CTRL-SHIFT-I causes the error: 

```
Cannot read property 'substring' of undefined
```

Full VS Code version information:

```
Version 1.8.0 
Commit 38746938a4ab94f2f57d9e1309c51fd6fb37553d
Date 2016-12-13T18:03:00.506Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

OS information:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```

**Comment by roblourens** [comment]
It works for me in Ubuntu. Do you have any other extensions installed?

Where are you seeing that error? Is there a stack trace or anything associated with it? Thanks.

**Comment by DashShen** [comment]
I have the same problem after updating to the version `1.8.0` . When I try to format my python code with python extension, it causes the error:
```
Cannot read property 'substring' of undefined
```

**Comment by monty-georgiev** [comment]
I also have the issue after updating to 1.8.0 and only with my python code.
I'm running it in OS 10.12.1

**Comment by dstpierre** [comment]
same here, after updating to 1.8.0 with Go extension 0.6.51 on Arch Linux.

**Comment by openingnow** [comment]
same here with c++ extension. maybe after 1.8.0 update

**Comment by roblourens** [comment]
Where are you seeing this error?

**Comment by mdmarek** [comment]
@roblourens I open a Go source file in my project, any project, and try running CTRL+SHIFT+I, the consequence is that a small header drops down with the warning. See embedded screen shot.

![error-ctrl-shift-i](https://cloud.githubusercontent.com/assets/241294/21274839/04f5da96-c37f-11e6-879e-289039fc568f.png)

**Comment by mdmarek** [comment]
@roblourens: is there a way I could get a stack trace or something useful for you from that warning? If you tell me how I'd be happy to grab the information.

**Comment by roblourens** [comment]
Can you open the developer tools (under the help menu) and show what's in the console there?

**Comment by mdmarek** [comment]
@roblourens Here is the screen shot with the developer tools console:

![ctrl-shift-i-error](https://cloud.githubusercontent.com/assets/241294/21276326/b5570cd8-c385-11e6-90e9-59062783ee52.png)

A couple of notes:

1. 
I had to try CTRL-SHIFT-I maybe a dozen times before the stack trace printed, the warning always appears, but the stack trace for some reason does not.

2.
If you notice in `example.go` you can see that there is no "newline" terminating the file. When trying to get the stack trace in one of the attempts I accidentally added a newline to that `example.go` file, and with the newline the CTRL-SHIFT-I works as expected.

I then tried testing CTRL-SHIFT-I in some other files, indeed, if the file is newline terminated then CTRL-SHIFT-I works, if you remove the newline termination, CTRL-SHIFT-I stops working.

Hope this helps.

**Comment by roblourens** [comment]
Missing a trailing newline is the key. I can repro it too in that case. Thanks! I think the stack is actually unrelated.

**Comment by ramya-rao-a** [comment]
Yes, the stack is actually unrelated.

**Comment by roblourens** [comment]
Looks like an issue in vscode, I filed https://github.com/Microsoft/vscode/issues/17424

**Comment by mdmarek** [comment]
Thank you Rob

**Comment by bipin-nag** [comment]
Also facing the issue. Thanks @roblourens for the solution.

**Comment by ramya-rao-a** [comment]
This has been fixed in the latest VS Code Insiders build.
The next VS Code release in early February will have the fix.

Workaround is to add a trailing newline at the end of the file

**Comment by CfirTsabari** [comment]
@DashShen @monty-georgiev I had the same problem in python code , what solved it for me was to add an empty line to end of the file.
