### ISSUE TITLE
Stepping over wont work .

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode-go#692]
while debugging trying to step over doesn't work and cursor moves randomly backward and forward

**Comment by ramya-rao-a** [comment]
@NikosEfthias Do you have sample code where I can repro this?

I tried it on a simple Go project and stepping over works for me

**Comment by ramya-rao-a** [comment]
@NikosEfthias Can you update your version of dlv, VS Code and the VS Code Go extension, and give this another try?

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from the OP.

@NikosEfthias If you still see issues after updating your dlv version (0.12.1) and the Go extension(0.6.53) and Visual studio Code (1.8 or above), please add `"trace": true` to your launch.config and try again.
This will write a lot of logging to a file (whose path will be printed to your debug console). Share this file with us and we can look into what exactly is the problem.
