### ISSUE TITLE
Comments inside the import block are not highlighted

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#694]
![image](https://cloud.githubusercontent.com/assets/159209/21400087/3439cf6e-c763-11e6-98b8-92ff35b49655.png)

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#105

**Comment by ramya-rao-a** [comment]
The fix is now available in the latest Insiders build and will be available in the next stable build i.e 1.11.0
