### ISSUE TITLE
Empty new lines between imports

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#695]
When I keep writing my code, I almost always end up with empty lines like these in import section. I sometimes copy/paste code from other files too. I wonder if that causes that. I don't have clear steps to repro this but it happens all the time. Just leaving this here in case other people stumble on it too. I'm using latest version of everything.

![image](https://cloud.githubusercontent.com/assets/159209/21406263/798d9408-c77f-11e6-8876-e05baad41adb.png)

**Comment by ramya-rao-a** [comment]
This is done by the formatting tool.

Here is what I have observed.

- If there are multiple empty lines between 2 imports, the formatting tool deletes all but 1 empty line between the 2 imports
- If there are no empty lines between imports, the formatting tool does nothing

It never tries to standardize across multiple imports i.e remove blank lines between ALL imports or add a single blank line between each import.

Also tools like `goreturns` does grouping of imports as well(first core packages, then after blank line 3rd parties).

Closing this issue as it has more to do with the tool we are using for formatting than the Go extension itself.

Please feel free to log an issue with `goreturns`/`goimports` for such inconsistencies
