### ISSUE TITLE
Visual Studio always uses significant energy when doing Go development

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-go#698]
_From @thewhitetulip on December 9, 2016 8:33_

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.5.4|
|swift|Kasik96|0.0.2|
|python|donjayamanne|0.5.2|
|vscode-lua|gccfeli|0.1.2|
|CSSfmt|ilich8086|0.0.3|
|Go|lukehoban|0.6.51|
|HTMLHint|mkaufman|0.0.3|
|prettify-json|mohsen1|0.0.3|

---

Steps to Reproduce:

Open any file and do some changes, open the terminal or write Go code, vscode always consumes too much energy. This is the reason I have to use some light weight editor like Geany or vi. I'd love it if vscode uses less energy than what it does now.

_Copied from original issue: Microsoft/vscode#16963_

**Comment by egamma** [comment]
_From @strrchr on December 9, 2016 14:5_

I encounter the similar problem.
Are there tips or options to reduce cpu usage?

**Comment by egamma** [comment]
_From @thewhitetulip on December 10, 2016 4:55_

I started using `vi`because despite the fact that this is an amazing text editor, it eats up my battery within 2-3hrs of usage. using vi, my battery stays four times upto 8hrs!

**Comment by egamma** [comment]
_From @kieferrm on December 13, 2016 6:0_

//cc @egamma

**Comment by egamma** [comment]
>Open any file and do some changes, open the terminal or write Go code

The Go extension isn't shy to spawn new processes, e.g., on hover, which can result in increased energy consumption.

@thewhitetulip can you confirm that you only saw this problem when disabling the Go extension in the Extensions viewlet.

Assigning to @ramya-rao-a for further investigation in the Go extension. I'll add the `caused by extension` label for now.

**Comment by egamma** [comment]
_From @thewhitetulip on December 23, 2016 4:41_

@egamma Well, I use Code only for Go programming :-) So I can't say for sure. But I will confirm by writing a python project using VScode too

**Comment by egamma** [comment]
_From @thewhitetulip on December 25, 2016 7:15_

@egamma I am sorry for the delay, yes, writing Go code marks VSCode as using high energy, tested thrice writing JS and writing Go, JS has no issues, Go has issues.

Also, thought you might want to know:

Code Helper eats 11% CPU for every single edit of any file (Go or not)
Code itself takes 1.4% CPU and 43MB when it is in background (it is updating to the new version, and has 1 open JS file)

92+28+26+59+23 MB is the system memory Code Helper eats even if it is idle (there are that many instances of the service) contrast that with iTerm, I had 10 tabs and a server running, still iTerm takes .4% CPU 43MB Memory

Do let me know if you need more information.

**Comment by egamma** [comment]
@thewhitetulip thanks for following up, I move the issue to the Go Issue repository for further investigation.

**Comment by ramya-rao-a** [comment]
@thewhitetulip @strrchr Did you recently upgrade to Mac OS X Sierra?

There is a known issue of performance of Go tools on Mac OS X Sierra. See #503 

Run the command `Go: Install Tools`. That should update all the go tools that the extension depends on which should fix the issue

**Comment by thewhitetulip** [comment]
It is about excess Energy being used and not CPU, I am not sure if this is the issue. I am using Sierra and will check after installing new binaries.

**Comment by ramya-rao-a** [comment]
@thewhitetulip @strrchr Any updates?

**Comment by thewhitetulip** [comment]
@ramya-rao-a I am sorry, I was on a vacation, will reply back in 12hrs

**Comment by mattetti** [comment]
@ramya-rao-a on a related note, we are spawning a new process for every hover. One option would be to switch gocode for something else, another would be to implement the gocode RPC client in TS and therefore run the query from within the extension. I have to admit that I don't know the energy cost of starting a new process on Windows and Mac so I can't tell if that would even help.

One thing I know, is that the battery life on my MBP 2016 is a joke and anything that would help me get more unplugged coding hours out of this machine would be welcome.

**Comment by thewhitetulip** [comment]
@mattetti I have a MBP 2012, 8hrs+ battery when I don't use VSCode, I still haven't gotten time to download and test the new binaries, I would love to use VSCode if it took equal or a little bit more energy than vi.

**Comment by mattetti** [comment]
@thewhitetulip VSCodeGo and VimGo use basically the same tools under the hood so the difference might be with electron rendering. In my experience the CPU usage wasn't bad at all so I didn't notice anything specific to VSCode ( I switched from macvim).  CPU is usually the driver or energy consumption. It would be interesting to get more metrics about where "energy" is used when you code with VSCode and if it's related to VSCode or the go extension.

**Comment by thewhitetulip** [comment]
@mattetti Well, when I write Go using VSCode, then after five minutes, it pops up in "apps that use significant energy". I tried with Python, but it seems that Go extension is causing this issue. But even if this isn't the case, surely due to electron rendering vi still rocks.

**Comment by ramya-rao-a** [comment]
@thewhitetulip Now that you see similar energy issues when the Go extension is disabled and the related issue in vscode is tracking the same, is it ok if we close this issue?

The other concern about hover spawning a new shell everytime is being tracked in other issues.

**Comment by thewhitetulip** [comment]
@ramya-rao-a Yes, I feel it is appropriate to close this issue since we have established that energy is being used without this extension. I must say (again), I love how MS is handling this project, fabulous!

**Comment by ramya-rao-a** [comment]
Thanks for the kind words @thewhitetulip! We will keep working on that :)
