### ISSUE TITLE
Format code corrupts imports

### ISSUE THREAD

**Issue by newhook** [Microsoft/vscode-go#70]
I've been working a fair bit with the plugin today and have noticed that the format code command sometimes corrupts my imports. I use "goimports" as my formatter. I've been using this for months with vim-go so I don't think it is the fault directly of goimports.

For example, I got this import

```
import (
   "encoding/jsonfmtio/ioutil"
)
```

which should have been:

```
import (
   "encoding/json"
   "fmt"
   "io/ioutil"
)
```

**Comment by lukehoban** [comment]
Yeah - this is #16.  Pretty sure it's a bug in VS Code per the notes there and in https://github.com/Microsoft/vscode/issues/144.
