### ISSUE TITLE
Ignore vendor in workspace symbol search

### ISSUE THREAD

**Issue by acroca** [Microsoft/vscode-go#700]
Searching symbols in a project with a vendor folder shows all matches in vendor mixed with the project matches.
Is there a way to ignore vendor in the workspace symbol search?

**Comment by ramya-rao-a** [comment]
@acroca The Go extension uses te `go-symbols` tool to get all the workspace symbols.
Currently, we don't provide a way to ignore vendor folder in the symbol search.

Can you open an issue in the repo for `go-symbols` for this feature of ignoring the vendor folder?

**Comment by acroca** [comment]
I figured it out checking the code. Is the `go-symbols` list used anywhere else? like for example going to the implementation of a function...?
Also, re-ordering the list to show project matches first and vendor matches after would work too, not sure if that's doable though.
My main problem, other than speed building the symbols list (~3s) is that the project matches are in the middle of the list..

**Comment by ramya-rao-a** [comment]
The output of `go-symbols` is not used anywhere else other than workspace symbols search.

Lets wait for how https://github.com/newhook/go-symbols/issues/3 gets solved. 
If we don't hear back, then we can circle back to what the Go extension can do.

**Comment by ramya-rao-a** [comment]
It doesn't look like we will be getting a response to https://github.com/newhook/go-symbols/issues/3 anytime soon. There is an issue there from March 2016 that has not been addressed yet.

Feel free to fork `gosymbols` to take a flag to ignore vendor symbols. We can then use that in the Go extension

**Comment by acroca** [comment]
I opened a PR on the main repo, but it'll probably get ignored: https://github.com/newhook/go-symbols/pull/4
My fork has the change: https://github.com/acroca/go-symbols, you can use that one. It supports multiple folders too, maybe other people wants to ignore other things like `test`...

**Comment by ramya-rao-a** [comment]
@acroca Awesome! I'll take a look this week and try to use this in the next update

**Comment by acroca** [comment]
Cool! Thanks @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@acroca I have a PR #795 out for integrating your fork of `go-symbols`.

But at the same time, I don't want to rush into this.

Reason being, we are looking into integration with language server for Go which also implements WorkspaceSymbolProvider, and that might have a different design. 

Also, felt like this is not a Go specific feature ask. Therefore logged https://github.com/Microsoft/vscode/issues/20579 to see what people think about having this feature implemented in the core product itself.

**Comment by acroca** [comment]
@ramya-rao-a Awesome.

**Comment by acroca** [comment]
@ramya-rao-a any updates with this?

**Comment by ramya-rao-a** [comment]
Doesnt look like we will be getting an exclude pattern feature from the core product soon.

I'll try and get the linked PR into the upcoming update which I plan to release in a few days.

Thanks for circling back

**Comment by acroca** [comment]
right, I had a look at the related issues around the language server and doesn't seem to be something happening any time soon.
Thanks!

**Comment by ramya-rao-a** [comment]
PR is merged. Fix will be out in the next update

**Comment by acroca** [comment]
Awesome, Thanks

**Comment by ramya-rao-a** [comment]
This is out in the latest update (0.6.56) to the Go extension
