### ISSUE TITLE
go to declaration not working sometimes (ie f12, editor.action.goToDeclaration)

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode-go#702]
Go to declaration/definition is in _some cases_ not working.  It's not clear to me when it does and does not work.

When it doesn't work, nothing happens when I press f12.  It always seems to happen when I want to jump to a function in another package, but in some cases this does work.  In the cases where it works, it always works, and in the cases where it doesn't, it never seems to work.

This seems to have started happening in the last couple of months.

What debug information is needed to diagnose this?

**Comment by ramya-rao-a** [comment]
In such cases what do you see when you do a `Peek Definition` or when you hover on the function ?
Behind the scenes the extension runs the same code and returns the same data for both Goto and Peek Definition back to VS Code.

If the Peek Definition/Hover just says "Loading" and never shows anything, it might be because the operation to find the definition and docs never completed.

Add `"go.docsTool": "gogetdoc"` in your settings and try again. This will make the Goto/Peek definition and Hover features to use the `gogetdoc` tool instead of `godef` tool.

You can also try running the `godef` tool from the command line and see if it returns anything.

**Comment by josh-tepper** [comment]
Thanks for getting back to me.  In response to your questions:

- When I peek definition or hover, it actually just doesn't do anything.
- Setting "go.docsTool": "gogetdoc" seems to solve the problem, but jump to declaration/peek/etc are much slower (but now work for everything)
- When I run godef for the symbol, it just says "no declaration found".  See below.  First is an example of an expression that does work, followed by one of the problematic expressions:
```
$ godef -f api/main.go environment.SetFromString
<PATH REDACTED>/environment.go:41:6
$ godef -f api/main.go state.Init
godef: no declaration found for state.Init
$
```

**Comment by ramya-rao-a** [comment]
Thanks for the clarification @josh-tepper 
In this case, the right thing to do is to file an issue with godef with sample code.

**Comment by josh-tepper** [comment]
@ramya-rao-a,
I filed a godef issue (linked above), and I pinged it again last week.  I haven't gotten a response.  Do you guys have any godef contacts that you can reach out to about this issue?  I would love to see this fixed -- setting the docsTool to godef gives me a way snappier experience than setting it to gogetdoc.

Thank you in advance!

**Comment by ramya-rao-a** [comment]
@josh-tepper Can you share a sample code?

We did have issues with godef and structs and certain packages.

Do you see this issue for all code? Say a simple `fmt.Println` . Are you able to use go to definition on this one?

Unfortunately, I don't have any godef contact.

But adding sample code in the issue you created in godef should help as well.

Also, do try updating your `godef`. Sometimes, they ship some fixes which might (or might not :) ) help.

**Comment by jwendel** [comment]
@ramya-rao-a I dug into this a little as it was affecting me as well.

It looks like godef has 2 current problems (one has an outstanding pull request).

1) `import "C"` causes godef to break.  See: https://github.com/rogpeppe/godef/pull/44
2) At least on windows `import "golang_org/x/net/route"` from the net package breaks godef. Specifically it seems since all the files within the x/net/route import have a `// +build` header on all the go files for OSes other than Windows, Go complains there are no buildable sources files in the import and causes godef to break.

**Comment by ramya-rao-a** [comment]
@jwendel Your second note on the `net` packages is interesting. Do we know why the `// +build` header is missing for Windows? Is there any documentation or issue for that?

**Comment by jwendel** [comment]
This is the code error:
`C:\go\src\net\interface_bsd.go:12:2: cannot find identifier for package "golang_org/x/net/route": no buildable Go source files in C:\go\src\vendor\golang_org\x\net\route
2017/01/23 21:33:57 } -> <nil>`

Notice it's an import in interface_bsd to the package: https://github.com/golang/net/tree/master/route
And everything in that package is bsd specific implementations. So really, godef probably needs to be changed to not follow imports in files that aren't supported on the current platform. (That's at least my guess)

**Comment by bruparel** [comment]
@ramya-rao-a This is a generic problem with VSCode and not confined to the just the Go lang.  This is happening to me in the Angular 2 Typescript code.  So I would alert the VSCode team of this problem.  Initially upon loading, it works a few times, and then it starts displaying 'Loading.' message.

**Comment by ramya-rao-a** [comment]
@bruparel

Typescript and javascript support comes out of the box in VS Code. Therefore,  please do log an issue in the VS Code repo https://github.com/Microsoft/vscode for the issue you are seeing for the typescript code.

For all other languages, features like Peek definition and Hover are implemented via extensions. The "loading.." is shown when the extension doesnt get back to VS Code in time with data for Hover or Peek Definition feature.

**Comment by ramya-rao-a** [comment]
Closing this issue, as multiple have been logged against `godef`.
Using `gogetdoc` is an alternative.

We are looking at other options for implementing the features that depend on `godef`.
Will update this thread once we have something new to share.

**Comment by kuncevic** [comment]
Same thing here, had to restart vscode to make `f12` working. But it is alway stopping working after some time.

**Comment by ramya-rao-a** [comment]
@kuncevic Can you try using the new language server feature? Set `"go.useLanguageServer": true` in your settings.

**Comment by kuncevic** [comment]
@ramya-rao-a: just did `ctrl+shift+p` => select `user settings` => paste `"go.useLanguageServer": true` => restart
`F12 ` and `intellisense` has stopped after some time.

**Comment by ramya-rao-a** [comment]
@kuncevic What version of the Go extension are you using?

**Comment by josh-tepper** [comment]
I saw the same issue -- that go to def, find refs, etc. stop working after some period time, and this behavior started when I switched go.useLanguageServer to true (unlike kuncevic, I did not experience it beforehand; I was previously using gogetdoc).  Restarting resolves, but this happens consistently and often.

I'm running the 0.6.55 version of the extension on vscode 1.10.2.

Let me know if there is anything else you need.  The lang server was significantly faster than gogetdoc which I used because godef is broken.  Nonetheless, when useLanguageServer is true, the tooling stops working after only 30min so I can't really use this configuration.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @josh-tepper , we will track this in a separate issue #853

**Comment by kuncevic** [comment]
@ramya-rao-a ahhh, and I am not using the go extension, I have same issue with the `typescript` as I did mentioned that in my first comment, sorry if it was not clear enough.
