### ISSUE TITLE
When using gogetdoc, hovering over a local variable shows the current function name, instead of variable type information.

### ISSUE THREAD

**Issue by enitihas** [Microsoft/vscode-go#703]
I recently changed the option "go.docsTool" to gogetdoc. However, now when I hover over a local variable in any function, it shows me the function name instead of type information of the variable. However, hover works correctly for function arguments.
![screenshot from 2017-01-02 09-27-01](https://cloud.githubusercontent.com/assets/4889897/21584432/e00a98d2-d0cd-11e6-90ce-917f91063e7e.png)

**Comment by ramya-rao-a** [comment]
@zmb3 The `decl` property in the json output from `gogetdoc` contains the function declaration instead of the variable declaration in such cases

**Comment by zmb3** [comment]
The current behavior is to ascend the AST until we get to a decl that has [may have] documentation.  In this case, `tests` being a local variable doesn't, and so we keep moving up the AST until we see `Test_checkError()`.

At the time, I thought this behavior made sense.  Recall that `gogetdoc` was originally written for the sole purpose of extracting documentation, not necessarily to provide a tooltip.

I see how this can be confusing, especially now that the tool is being used to provide a tooltip for the item under the cursor.  We should try to be as accurate as possible at describing what is under the cursor.

Please create an issue upstream and link it here, I'll be happy to take a look. Bonus points for a repro with actual/expected output :-)

**Comment by ramya-rao-a** [comment]
Repro: 
![image](https://cloud.githubusercontent.com/assets/16890566/21654787/f4f2cd60-d26b-11e6-9cf8-c39cac6c1aa0.png)

Expected Output: 

![image](https://cloud.githubusercontent.com/assets/16890566/21654796/fe130202-d26b-11e6-8130-2bc4c337e437.png)

**Comment by ramya-rao-a** [comment]
This issue was moved to zmb3/gogetdoc#20

**Comment by ramya-rao-a** [comment]
Thanks @zmb3
