### ISSUE TITLE
Step out, any plan to do this?

### ISSUE THREAD

**Issue by nolanjian** [Microsoft/vscode-go#704]
when I step in a func, I want to step out, but it seems not implement yet.

**Comment by roblourens** [comment]
Right, but we just use Delve for debugging and we'd need them to implement it.

**Comment by ramya-rao-a** [comment]
@roblourens Looks like delve has implemented this in late October 2016 
https://github.com/derekparker/delve/issues/358#issuecomment-255594116.

Re-opening this issue for us to consume the step-out feature

**Comment by nolanjian** [comment]
@ramya-rao-a @roblourens thanks for your reply!

**Comment by ramya-rao-a** [comment]
Done with https://github.com/Microsoft/vscode-go/commit/6d0f4405330efb789c16a01434cf096f0f9fb29c
The next Go extension update will have the "StepOut" feature.

You will need to update dlv though `go get -u github.com/derekparker/delve/cmd/dlv`

**Comment by nolanjian** [comment]
@ramya-rao-a this good, thanks so much! I will get the code to build again, and close this issus.

**Comment by ramya-rao-a** [comment]
The new release of the extension (0.6.52) has this feature now
