### ISSUE TITLE
Code is being deleted on save or run

### ISSUE THREAD

**Issue by abagshaw** [Microsoft/vscode-go#705]
Maybe I am doing something wrong - but I am having this problem where VS Code with the vscode-go modules installed appears to be deleting parts of my go code when I try to run the program.

```
package main

import "fmt"
import "./yolo"

func main() {
	fmt.Printf(vals())
	fmt.Printf("test")
}
```

Every time I hit save or try to run the program the `import "./yolo"` just disappears. Why is this?

**Comment by codmajik** [comment]
I think its because goreturns is run on the code on save. you can disable it by changing

`"go.formatTool": "goreturns",` to `"go.formatTool": "gofmt",` in your workspace config

**Comment by ramya-rao-a** [comment]
@abagshaw The default formatting tool `goreturns` deletes unused imports. Since the `yolo` import is not used in your code it gets deleted by the foramtting tool which is run on save.

You can use workaround  @codmajik has suggested if you don't want to see this behaviour.

**Comment by achekulaev** [comment]
The default behavior is annoying AF. Especially for a novice Go developer. I figured that some linting tool is doing that, but I'd prefer it did not do that and I rather learn Go by fixing errors instead of seeing code disappear and guessing why.
