### ISSUE TITLE
VS tell me my $GOPATH is wrong 

### ISSUE THREAD

**Issue by Wang-Kai** [Microsoft/vscode-go#708]
The vs code show that :

<img width="568" alt="2017-01-05 8 21 14" src="https://cloud.githubusercontent.com/assets/13144386/21664864/2cca73f6-d324-11e6-808a-6db2c5533139.png">

But my $GOPATH is :
➜  ~ echo $GOPATH
/Users/Elegant/go

**Comment by ramya-rao-a** [comment]
Run the command `Go: Current GOPATH` in VS Code. What does that give?
Check your User and Workspace settings. Maybe you have set GOPATH there to a different value.

**Comment by skmlcd** [comment]
I have the same problem. ```Go: Current GOPATH``` outputs "undefined". My GOPATH and GOROOT are set in .bashrc, I'm using Linux.

It only works if I manually add "go.gopath" into the settings.json which is far from ideal.

**Comment by ramya-rao-a** [comment]
@skmlcd Can you try opening VS Code from the command line? `code .`

**Comment by skmlcd** [comment]
Opening from command line works without the problem (GOPATH is correct).

**Comment by skmlcd** [comment]
```
[Desktop Entry]
Name=Visual Studio Code
Comment=Visual Studio Code
GenericName=Text Editor
Exec=code-oss %U
Icon=code-oss
Type=Application
Terminal=false
StartupNotify=true
StartupWMClass=visual-studio-code
Categories=Development;TextEditor;
MimeType=text/plain;
```

This is the desktop file (shortcut) for launching vscode. ```code-oss``` is the same as ```code```, this is only distribution package name.

**Comment by ramya-rao-a** [comment]
@skmlcd In that case, this is as expected.
When opening from command line, the process running the Go extension inherits all the env variables from the shell, and so it can use the GOPATH you have set in .bashrc
When you open from the shortcut, it doesnt have access the env variables from the shell.

@Tyriar Can you confirm the above statement, in case my understanding is wrong?

**Comment by Tyriar** [comment]
Yes this is likely a case of confusion with .bashrc. You probably want to put the environment variable stuff in your `~/.profile` file as you want them to apply globally, not just to bash. Check out http://serverfault.com/a/261807 for more info

**Comment by skmlcd** [comment]
@Tyriar Thanks, putting it in .profile that solved the problem.
