### ISSUE TITLE
support to execute "go get xxx" in context menu when the package can't be found.

### ISSUE THREAD

**Issue by zhaohaidao** [Microsoft/vscode-go#716]
Sometimes packages a project relies on can't be found in GOROOT and GOPATH.
I have to switch to a terminal, execute "go get xxx" to get these packages, then switch back.
Do someone feel inconvenient just like me?

Is there a plan to  support to execute "go get xxx" in context menu when the package can't be found? or maybe we can refer to gogland shown as below. 

![image](https://cloud.githubusercontent.com/assets/6216286/21754475/0767078a-d63c-11e6-8079-9e8c79eca9b6.png)

**Comment by ramya-rao-a** [comment]
It is unlikely that we would have this feature in the context menu. But, it is pretty straightforward to implement this as a command which you can invoke via the command palette or even have a code action show up like a light bulb as you have shown.

PRs are welcome and I can help anyone interested in taking a stab at this.

**Comment by ramya-rao-a** [comment]
The command `Go: Get Package` is now available with the PR https://github.com/Microsoft/vscode-go/pull/1222

You can select the package or place your cursor on it in the import block and run the command `Go: Get Package`.
