### ISSUE TITLE
Tooling stops working after VSCode update

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-go#722]
_From @olliephillips on January 13, 2017 10:15_

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|elm-format|abadi199|0.1.0|
|Go|lukehoban|0.6.51|
|prettify-json|mohsen1|0.0.3|
|elm|sbrink|0.8.3|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Update VSCode
2. Go tooling such as Goimports and Gofmt seem to stop working

I would suggest this can't be reliably reproduced, but I've seen this behaviour on a couple of updates.  Preferences are not changed.  On the last occasion even restarting did not help. 

I should say that the issue seems temporary. In that the tooling does eventually work again without action on my part. I'm wondering if the plugins that provide the tooling mentioned take time to update.

_Copied from original issue: Microsoft/vscode#18508_

**Comment by mattetti** [comment]
that's extremely odd, goimports and gofmt are executables that get called from VSCode at various times. Updating VSCode shouldn't cause any issues with those tools.
@olliephillips can you provide us with a bit more information?

**Comment by olliephillips** [comment]
Thanks @mattetti. At this stage I'm afraid there's nothing else I can offer.  If the issue occurs again I'll update of course, and since my setup is not atypical maybe others will see issue and help corroborate here.

**Comment by ramya-rao-a** [comment]
Closing this issue for now. If anybody can provide more concrete steps, we will open this issue.

@olliephillips Next time you see this, check if there are any errors in your console (`Developer: Toggle Developer Tools`) and share the same. Also share if rest of the extension features (hover, go to definition, file outline, build, linting etc) work as expected in such scenarios.
