### ISSUE TITLE
"Cannot find Delve debugger at dlv" even if go.gopath is set and dlv is in go.gopath/bin

### ISSUE THREAD

**Issue by taketori** [Microsoft/vscode-go#723]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
```
$ go version
go version go1.7.4 windows/amd64 (self-compiled with MinGW64)
$ dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:
```
(I set neither GOPATH, GOROOT nor PATH to go.exe in control panel for some reason.)
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.52|

---

what I experienced:
- vscode showed error message like title of this issue.

what I expected:
- find dlv.exe using go.gopath setting in settings.json.

Steps to Reproduce:
1. just press F5 key.

vscode-go can find another tools in ${go.gopath}/bin directory like godoc, goreturns, gocode, gometalinter etc.
dlv runs if I edit "out/src/debugAdapter/goDebug.js" L.70 like below.

```javascript
            let dlv = goPath_1.getBinPath('d:/src/.go/bin/dlv');
            //let dlv = goPath_1.getBinPath('dlv');
```
it looks like goPath.js are not called from goDebug.js because:
- ${dlv} is "dlv" (no directory name and extension(".exe") is added)
- `console.log("something")` in getBinPath function in goPath.js does not leave any logs at the Developer Tools' console when I press F5.

my settings.json is like below:
```json
    "go.additionalPath": "D:/app/msys64/mingw64/bin",
    "go.gopath": "D:/src/.go",
    "go.docsTool": "godoc",
    "go.formatTool": "goreturns",
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.formatOnSave": true,
    "go.gocodeAutoBuild": false,
    "go.buildFlags": [
        "-pkgdir \"D:\\app\\msys64\\mingw64\\lib\\go\\pkg\\windows_amd64\""
    ],
    "go.gocodeLibPath": "D:/app/msys64/mingw64/lib/go/pkg/windows_amd64",
    "go.lintTool": "gometalinter",
    "go.lintFlags": [
        "--deadline 30s"
    ],
```

**Comment by ramya-rao-a** [comment]
@taketori The debug adapter at the moment cannot read the settings, and so is not aware of the GOPATH you set in the settings.

Either, your PATH has to point to dlv or the GOPATH should be set outside VS Code as an env var.

**Comment by ramya-rao-a** [comment]
If you are not setting GOPATH outside of VS Code, then you need to set it in the `env` property in `launch.json` so that `dlv` gets the right GOPATH to use.

**Comment by taketori** [comment]
Thank you for your quick reply.
I tried after doing as you suggested,  but it did not work .

my launch.json:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"env": {
				"PATH": "D:/app/msys64/mingw64/bin",
				"GOPATH": "d:/src/.go/"
			},
			"name": "Launch",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "${file}",
			"showLog": true,
			"internalConsoleOptions": "openOnSessionStart",
			"args": []
		}
	]
}
```
so I added 2 lines (**) to and comment-outed 7 lines from goDebug.js
```javascript
            Object.assign(process.env, env);  // **
            let dlv = goPath_1.getBinPath('dlv');
            log('Using dlv at: ', dlv);
            if (!fs_1.existsSync(dlv)) {
                return reject(`Cannot find Delve debugger at ${dlv}. Ensure it is in your "GOPATH/bin" or "PATH".`);
            }
            let dlvEnv = null;
            if (env) {
                dlvEnv = {};
                Object.assign(dlvEnv, process.env); //**
                //for (let k in process.env) {
                //    dlvEnv[k] = process.env[k];
                //}
                //for (let k in env) {
                //    dlvEnv[k] = env[k];
                //}
                //return reject(`${dlvEnv["PATH"]}`)
```
This is probably not right way, but works fine for me.

**Comment by ramya-rao-a** [comment]
@taketori 
Is there any reason, you don't want to set GOPATH as an env variable outside of VS Code in Windows?

Adding GOPATH in the `env` property in the launch.json was so that when `dlv` starts running, it knows the GOPATH 

But, `dlv` cannot be run if it is not found in the first place (your original issue `Cannot find Delve debugger...`), for which you need to have the GOPATH set as an env variable outside of VS Code in Windows

Nevertheless, your hack gave me an idea. I have a PR out #725. With that in, the GOPATH you set in launch.json can be used both to find `dlv` and by `dlv` itself, without needing to set GOPATH as env var outside of VS Code

**Comment by taketori** [comment]
I'm sorry for my late reply.

The reason why I don't set GOPATH outside of VS Code is that I have used several "go"es of wsl, cygwin, mingw and  [compiled windows binary](https://storage.googleapis.com/golang/go1.7.4.windows-amd64.zip) and they, VS Code and another development tools are in SD card as I want environment to be portable. so I set variables by a kind of launcher like cygwin.bat, msys2_shell.cmd etc.

anyway, your PR looks nice to me,
I'm looking forward to next update.
I will report if it works well or not and close this if it does.

**Comment by ramya-rao-a** [comment]
With the latest update (0.6.53), the GOPATH passed as env var in the launch.json will also be used to look up the `dlv` binary

**Comment by taketori** [comment]
vscode-go found `dlv.exe`.
thank you.

I am still waiting for another `env` variables like PATH to work fine.
And I wish the `env` in tasks.json also works...
```JSON
	"options": {
		"env": {
			"PATH": "D:/app/msys64/mingw64/bin"
		}
	},
```
