### ISSUE TITLE
Improvement on documentation on how to debug test files

### ISSUE THREAD

**Issue by Zignd** [Microsoft/vscode-go#724]
I'm having a hard time trying to understand how to use the plugin to debug test files. Could you guys make it more descriptive?

Thanks in advance.

**Comment by ramya-rao-a** [comment]
Just add another config in your `launch.json` with `mode` set to `test`. 

There is a drop down in the `Code Debug` viewless that lets you choose which config among the many in `launch.json` you want to use. 

Choose the newly created config and any breakpoints in your test code or the code that is being tested will be hit.

To debug individual tests, pass `-test.run` and the test name as `args` in the config.

All this is in the docs in [Set up configurations]( https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson)

This is also linked from the README for the extension.

Let me know what else we can add to improve the docs.
