### ISSUE TITLE
Feature request: show warnings and errors as light bulbs

### ISSUE THREAD

**Issue by mattetti** [microsoft/vscode-go#727]
https://code.visualstudio.com/docs/editor/editingevolved#_errors-warnings

We support nice linters tools and it would super useful to be able to see their warnings, errors and suggestions side by side the code.

![](https://code.visualstudio.com/images/editingevolved_errorsinline.png)

https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_a-namecodeactionprovideraspan-classcodeitem-id464codeactionproviderspan

We use this API here:

[`src/goCodeAction.ts:13:  public provideCodeActions(document: vscode.TextDocument, range: vscode.Range, context: vscode.CodeActionContext, token: vscode.CancellationToken): Thenable<vscode.Command[]> {`](https://github.com/Microsoft/vscode-go/blob/master/src/goCodeAction.ts#L13)

This code path is rarely triggered since most of us probably have `"go.formatOnSave"` on using `goreturns` or `goimports` to insert the package import. But here is how it looks:

<img width="721" alt="main_go_-_vscodetest" src="https://cloud.githubusercontent.com/assets/113/21974765/9e201e0a-db7d-11e6-97ef-2b6b8e7f0f5f.png">

So ideally we would gather the linter/compiler/tool information and start providing code actions. Take for instance the following code example:

<img width="722" alt="main_go_-_vscodetest_and_midi_clip_go_-_ableton" src="https://cloud.githubusercontent.com/assets/113/21974919/7836316a-db7e-11e6-8c56-9dc110679cb4.png">

The warnings and errors can be checked in the extension output:

```
Finished running tool: /Users/mattetti/Code/golang/bin/golint
/Users/mattetti/tmp/vscodeTest/main.go:7: var Uuid should be UUID
/Users/mattetti/tmp/vscodeTest/main.go:14: exported function FakeFn should have comment or be unexported
/Users/mattetti/tmp/vscodeTest/main.go:14: exported func FakeFn returns unexported type *main.privateType, which can be annoying to use

Finished running tool: /usr/bin/go tool vet /Users/mattetti/tmp/vscodeTest/main.go

Finished running tool: /usr/bin/go build -o /var/folders/4p/sfb8dphs3hgb62k1_6dl09vh0000gn/T/go-code-check -tags "" .
/Users/mattetti/tmp/vscodeTest/main.go:6: leftOvers declared and not used
```

We probably can start by looking at the compiler errors and offer suggestions. In this case, we could offer to delete the declaration. But I would also argue that the linter warnings would be better off in the gutters than on hover since the hover can really quickly get overwhelmed.

<img width="539" alt="main_go_-_vscodetest" src="https://cloud.githubusercontent.com/assets/113/21975108/92910804-db7f-11e6-8435-f2f59a839da9.png">

**Comment by mattetti** [comment]
Note that after reading the guidelines and looking at the API, I realize that the light bulbs should only be used when an actual action can be offered to the user as shown here:

![](https://code.visualstudio.com/images/language-support_quick-fixes.gif)

So we probably should start by listing the kind of actions we would like to offer actions for.

- [ ] Unused variables
- [ ] Missing documentation generation (or offer to unexport)
- [ ] Go vet name suggestion replacement

**Comment by ramya-rao-a** [comment]
The new language server gopls would be the right place to provide code actions to fix common errors and warnings.

Closing this issue as there has been no progress in this area in the past 2 years and because further work in terms of code actions outside the scope of the language server is not planned for the extension.
