### ISSUE TITLE
Feature request: offer unit test generation feature in context menu

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#728]
The Go extension offers ways to generate tests for a function, file or an entire package. However, this feature is "hidden" in the palette menu. I would suggest to have those also available in context menus.

For instance `Generate unit tests for current function` could be available when right clicking the function name, `Generate unit tests for the current package` could be available when right clicking the package name.

<img width="1043" alt="main_go_-_vscodetest_and_gocodeaction_ts_-_vscode-go_and_midi_clip_go_-_ableton" src="https://cloud.githubusercontent.com/assets/113/21975425/6fca0760-db81-11e6-8e78-6a0018a5e5fa.png">

**Comment by tw1nk** [comment]
I did a quick test on implementing this by adding 
```
 "menus": {
      "editor/context": [
        {
          "when": "editorFocus",
          "command": "go.test.generate.function",
          "group": "1_modification",
          "title": "Go: Generate unit test for function"
        }
      ]
    },
``` 
To the contributes section in package.json for vscode-go. 

It sort of works (as well as from the command palette) but as it doesn't seem vscode offers any way to have more control over the "when" property then what's predefined for the keyboard shortcuts and it seems you can't do your own logic on when a menu item should be visible I don't feel confident it would add more than clutter up the context menu.

For instance I would only want the "Generate test for current function" to be visible as long as there aren't any tests defined for the current function.

References: 
* https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus
* https://code.visualstudio.com/docs/customization/keybindings#_when-clause-contexts

**Comment by ramya-rao-a** [comment]
Also, we wouldn't want this option to show up in a test file.

**Comment by ramya-rao-a** [comment]
As a test run, I am planning to ship this in the coming update

![image](https://cloud.githubusercontent.com/assets/16890566/24372205/08f1bd24-12e2-11e7-8c3f-7e22510ef8cc.png)

People who feel this would clutter their menu and are comfortable using the command pallet instead, can change the settings to disable these entries

![image](https://cloud.githubusercontent.com/assets/16890566/24372229/29446630-12e2-11e7-92ef-91dcb1974c38.png)


Sub menus are not supported yet, if they were then we could group these more appropriately.

This can act as a feature discovery tool, which users can prune as per their needs.

Thoughts?

**Comment by mattetti** [comment]
this is great
