### ISSUE TITLE
Convinient way to run projects

### ISSUE THREAD

**Issue by jonnenauha** [Microsoft/vscode-go#73]
I'm coming from LiteIDE and this thing is really promising. I'm not very familiar with vs code but saw that you can make custom tasks. Maybe someone can lighten if this is possible with custom tasks, somehow I understood they need to be node/js based.

In LiteIDE each repo (project) under your `$GOPATH/src` will have a dialog to setup cmd line params for the executable when you hit run or build and run which I always tend to use. I have a lot of server and command line apps that take in various cmd line params that obviously vary a lot per project.

I also really like LiteIDE in that i can hit F7 and it runs the server inline at the bottom in its own "shell". How would this be accomplished here that you would not need to run a normal shell. I know you could use those wrapper type servers that restart it on each code mod etc. Not really a fan of that though, something more integrated that I don't have to leave the IDE would be ideal. I also would prefer it buildings the executable and running it instead of `go run`

My first though was that this plugin could perhaps have some `go.run.project` available if you have a config file in the projects root (repo root), perhaps `.vscodego`

```
{
    args : [ "-config", "~/dev-run.json", "-dev", "-port", 9091 ]

    // I would actually prefer a single string that could 
    // be trimmed and split, maybe support both?
    args : "-config ~/dev-run.json -dev -port 9091",

    // sometimes nice to set custom ENV stuff to emulate
    // production runs where env is utilized more
    env : {
        "MY_SECRET" : "abcd12345"
    }
}
```

Now if I could only set any keybinding to this this would be pretty killer.

P.S. If the above can be accomplished with vs code tasks, can you bind a key to run a particular custom task? How does one specify one task to have different params in each working dir? I suspect it might get a bit complex to get this done with the generic task system?

**Comment by ironcladlou** [comment]
Related to my thoughts in https://github.com/Microsoft/vscode-go/issues/21#issuecomment-159127425

**Comment by jonnenauha** [comment]
I've taken a cursory peak at the `.vscode/*.json` stuff in a JS project. Looks like you can pretty much accomplish this stuff with the tasks.json. Still a bit unclear if you can mixin grunt/gulp + go tasks. Looks like the top level map only has one build runner, maybe you can make an array of them to have multiple tools. But you can give args and seemingly also env variables. I'll test some more later.

If there is some go task runner file and custom logic by this plugin it should be `.vscode/tasks-go.json` or similar.

**Comment by kulshekhar** [comment]
The following entry in tasks.json allows you to execute 'go run' and see the output in a window within vscode itself. You can add multiple files in the `args` array, if required.
```
{
	"version": "0.1.0",
	"command": "go",
	"isShellCommand": true,
	"showOutput": "always",
	"args": ["run", "main.go"]
}
```

**Comment by ramya-rao-a** [comment]
@jonnenauha Have you found what you were looking for?

The current debugging features that we have should suit most of your needs.

![image](https://cloud.githubusercontent.com/assets/16890566/21619571/1eda1b78-d1a5-11e6-9e6a-01090f36b05d.png)

**Comment by jonnenauha** [comment]
Yes, I believe these are doable. You can close this issue.

I still haven't moved from to vs code from LiteIDE for go development. But i will definitely look at it again at some point, so many improvements lately. I did move to it for most JS/HTML stuff.

**Comment by ramya-rao-a** [comment]
Thanks @jonnenauha, I'll close this issue.
I have updated the other issue that references this issue as well.

Do give the Go extension in VS Code a try and feel free to provide us with feedback.

Happy Coding!
