### ISSUE TITLE
expand ${workspaceRoot} in go.testEnvVars and go.toolsEnvVars configuration

### ISSUE THREAD

**Issue by hartshorne** [Microsoft/vscode-go#736]
Just like go.gopath: https://github.com/Microsoft/vscode-go/commit/f83579f568055f8528234f56d32238f308f47ddb (https://github.com/Microsoft/vscode-go/issues/237)

**Comment by ramya-rao-a** [comment]
I was hoping to have this as a feature from the core product.
See https://github.com/Microsoft/vscode/issues/2809

I'll revisit this issue based on how the discussion goes in the linked issue

**Comment by ramya-rao-a** [comment]
Doesn't look like we are going to get upstream support from vs code any time soon.

So, we should do this ourselves in the Go extension.

PRs are welcome, its pretty easy to do this. I can help anyone who wants to get started on this.

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode-go/commit/dd927509a3db3833dc02103e1cf6290074f56a4b

**Comment by ramya-rao-a** [comment]
This is fixed in the latest update to the Go extension
