### ISSUE TITLE
Syntax checking not working in files with build tags

### ISSUE THREAD

**Issue by bedeio** [Microsoft/vscode-go#741]
Steps to reproduce:
1 - Create and save any .go file.- [example](https://play.golang.org/p/v3rrZLwEUC)
2 - Give the file any build tags.- [example](https://play.golang.org/p/URJZN3nzXA)
3 - Write any gibberish outside of a function body and save the file.- [example](https://play.golang.org/p/Bc_G6qKjU5)

Result: Nothing, but building the file with `go build` or in the Go Playground gives  `syntax error: non-declaration statement outside function body`.

Expected: This gibberish is supposed to show up highlighted with a `syntax error: non-declaration statement outside function body` error. If the given build tag is erased and the file re-saved, then everything works as expected.

**Comment by ramya-rao-a** [comment]
@bedeio Sorry for the late reply, but have you updated the `go.buildTags` setting in your User/Workspace settings while trying out the build tag "example" in your example?

**Comment by bedeio** [comment]
Overlooked this setting, it works now. However, shouldn't syntax checking work independent of this?

Running `gofmt -e` on the file containing the "example" build tag gives the same error as shown in the playground.

**Comment by ramya-rao-a** [comment]
This is interesting.. Turns out when you provide filename as args to `go build`, you get the error even without the build tags. But when you provide the directory (which is what the Go extension does) as args, you don't get the error without the build tags

Keeping this issue open to see if anybody else has more ideas about how this works.

cc @mattetti any ideas?

**Comment by mattetti** [comment]
that's definitively an interesting behavior difference. I would file a bug with the Go project (if you have Go 1.8+, you can just type `go bug` in your terminal and it will start a bug report for you). I think the Go team might not be aware that the behavior is different and they should make a decision to what approach is the right one.

**Comment by ramya-rao-a** [comment]
@rakyll Any ideas on why the `go build` behavior is different when provided with file path vs directory?

**Comment by rakyll** [comment]
AFAIK, availability of running `go build` against file paths are not a well-defined behavior but a side effect of the new source importer, see https://github.com/golang/go/commit/e646d07329e7edc56c8cf3284c729937979dae4a.

On the other hand, the other parts of the go tool that works against filenames (e.g. `go run`) doesn't honor build tags. From a consistency point of view, `go build` should ignore the build tags. Is there any reason why you depend on `go build gofiles...` rather than building the package?

**Comment by ramya-rao-a** [comment]
@rakyll We use `go build .` on the directory of the current file. We weren't using filenames in `go build`. The above was just an observation that `go build filename` was able to detect compile errors in the absence of build tags but `go build .` wasn't.

Here is more 

Exhibit A:
- no line between build tag and package clause
- `go build filename`, `go build .`, `go build importpathforpackage` all return the right error "non-declaration statement outside function body
```go
// +build example
package main

import "fmt"

asdfsdf

func main() {
	fmt.Println("Hello, playground")
}
```


Exhibit B:
- a blank line between build tag and package clause
- `go build filename` returns the right error "non-declaration statement outside function body
- `go build .` and `go build importpathforpackage` return error "can't load package:...: no buildable Go source files..."

Also, recently (in master, not released yet), we moved to using the import path for the package.

```go
// +build example

package main

import "fmt"

asdfsdf

func main() {
	fmt.Println("Hello, playground")
}
```

Why does the line between the build tag and the package clause make any difference?

**Comment by rakyll** [comment]
@ramya-rao-a, I don't think it is a bug. The Go tool is expected to work differently against individual files.

`go build filenames...` are expecting you to design a set of files to achieve a build.
Whereas `go build <pkg>` uses the build context (e.g. build tags) to build a package.

I guess `go build <pkg>` vs `go build filename...` require more thinking. For example, users won't be able to compile `// +build android` Go packages on their Mac development machine with the new version of VSCode even though they have the correct Android cross compiler set in their environment. Is this a feature or a bug?

**Comment by ramya-rao-a** [comment]
One thing to keep in mind, is that if you update `go.buildTags` appropriately, there are no issues. The extension will use the tags while running `go build <pkg>`

Therefore in your scenario where one is compiling `// +build android` on a Mac, all will be fines as long as `go.buildTags` is set correctly, which is current behavior.

What I dont understand is why `go build <pkg>` will not throw syntax error on files that use build context if the `-tags` flag is not passed.

**Comment by ramya-rao-a** [comment]
@bedio Closing this as "by-design". Using the build tags, `go build` runs as expected. There is nothing more the Go extension can do here

**Comment by c4milo** [comment]
@ramya-rao-a apologies for commenting on a closed issue. I noticed `go.buildTags` type is a string, I believe it should be an array just like `go.buildFlags`. I'm happy to open a new issue if you agree.

**Comment by c4milo** [comment]
ah, I just looked at my makefiles and multiple tags can be passed separate by space. I forgot about it somehow. Sorry for the noise!
