### ISSUE TITLE
Feature request:  Add command for generating a tasks.json file

### ISSUE THREAD

**Issue by ppey** [Microsoft/vscode-go#743]
I would like to see, that I can generate a task.json just like the launch.json in ordert to trigger "go run" on the current file. This would allow to quickly run the file by pressing Ctrl+ shift + B without running the whole debugger.

**Comment by OneOfOne** [comment]
While that would be a good idea, if you just want to run a specific file maybe try [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner).

Tasks would be more suitable for package building / management.

**Comment by ramya-rao-a** [comment]
We are trying to get the "Run without actually debugging" feature as described in https://github.com/Microsoft/vscode/issues/2780

#299 is tracking this work.

With this, you won't need a task to run the current package.

**Comment by ramya-rao-a** [comment]
In the latest update (0.6.56), you can 
        - Press `Ctrl+F5` or run the command `Debug: Start Without Debugging` to run using the currently selected launch configuration.
        - If you don't have a `launch.json` file, then the current file will be run.
        - Supported only for launch configs with `type` as `debug` and `program` that points to a Go file and not package

**Comment by ppey** [comment]
Great, thank you!
