### ISSUE TITLE
Support configurationSnippets

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-go#744]
In order to be cool as vanila ice chrome debugger should specify `configurationSnippets`
Here's how node is doing it https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L98

This will make the whole setup experience smother. It would be great if we could tackle this in january

**Comment by mattetti** [comment]
here is how it looks for node and mock adapters:

![](https://cloud.githubusercontent.com/assets/1926584/21016889/a526f37e-bd67-11e6-8322-4214dcb00b22.gif)

**Comment by ramya-rao-a** [comment]
We will be releasing a new Go update in a few days. 
The debug related improvements such as this one will be in the update after that.

**Comment by ramya-rao-a** [comment]
@mattetti I can think of "debug", "test", "test single file" being scenarios for having the configuration snippets. As a Go developer you would know more cases if any. What kind of configuration snippets would you/your team be interested in?

Feedback from everyone else is welcome as well

**Comment by mattetti** [comment]
I often setup the launcher to test/debug a specific test using the `-run` feature.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update (0.6.54) to the Go extension.

There are 4 snippets supported as of now: https://github.com/Microsoft/vscode-go/blob/master/package.json#L158

If anyone can think of any other common scenario, then please submit a PR to add a snippet for the same.
