### ISSUE TITLE
Support startSessionCommand

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-go#745]
In order to support debugging in a no folder workspace the debug extension has to support the `startSessionCommand`.
More details can be found [here](https://github.com/Microsoft/vscode/issues/285#issuecomment-271324742)
Node doing it [example](https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L97)
And the code for the command [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension.ts#L252)

We will announce this with greater detail in our release notes.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update (0.6.54) to the Go extension.
