### ISSUE TITLE
gorutine moved their repo?

### ISSUE THREAD

**Issue by NaifAlrashed** [Microsoft/vscode-go#746]
i cant install goreturns. even if i go the website for the repo, i get 404
`go get -u -v sourcegraph.com/sqs/goreturns`
it seems that the repo for gorutine seems to have moved.

**Comment by ramya-rao-a** [comment]
I am able to run `go get -u -v sourcegraph.com/sqs/goreturns` without any errors.

What do you mean by `gorutine` exactly? Do you mean `goroutine` or `goreturns` ?

**Comment by NaifAlrashed** [comment]
sry made a typo. I meant goreturns

so this is what's showing in visual studio code

`Installing 2 tools
  goreturns
  gotests

Installing goreturns FAILED
Installing gotests FAILED

2 tools failed to install.

goreturns:
Error: Command failed: C:\Users\User\go\bin\go.exe get -u -v sourcegraph.com/sqs/goreturns
# cd C:\Users\User\GoCode\src\sourcegraph.com\sqs\goreturns; git config remote.origin.url
package sourcegraph.com/sqs/goreturns: remote origin not found
# cd C:\Users\User\GoCode\src\sourcegraph.com\sqs\goreturns; git config remote.origin.url
package sourcegraph.com/sqs/goreturns: remote origin not found

gotests:
Error: Command failed: C:\Users\User\go\bin\go.exe get -u -v github.com/cweill/gotests/...
# cd C:\Users\User\GoCode\src\github.com\cweill\gotests; git config remote.origin.url
package github.com/cweill/gotests/...: remote origin not found
# cd C:\Users\User\GoCode\src\github.com\cweill\gotests; git config remote.origin.url
package github.com/cweill/gotests/...: remote origin not found`

what i understood from it is that it isnt found. and even when i run it manually, i get this

```
# cd C:\Users\User\GoCode\src\sourcegraph.com\sqs\goreturns; git config remote.origin.url
package sourcegraph.com/sqs/goreturns: remote origin not found
```

so i went manually to the website (sourcegraph.com/sqs/goreturns), and i got a 404 message. this is a screenshot
![image](https://cloud.githubusercontent.com/assets/15128710/22303600/0c27dce8-e345-11e6-9e33-0cdb0090a836.png)

**Comment by ramya-rao-a** [comment]
Did you try running `go get -u -v github.com/cweill/gotests/...` from command line?
Does it still say remote not found?

Are you behind a proxy?

Can you try doing `go get` on one of the other tools? If all of them are giving the same error, then it must be a local env issue

**Comment by NaifAlrashed** [comment]
i am running windows and i ran it on windows PowerShell. also, visual studio code did install most of the other packages. what seems different with this one is that the link for downloading it is not different from the others. all of the other links were either github or golang.org, but this one is different.

**Comment by ramya-rao-a** [comment]
By that logic, `gotests` should have worked, because it is from github. But you see the error "remote origin not found" for that as well.

Do you have $GOPATH/src/sourcegraph/sqs/goreturns folder? If yes, can you delete that and try again?

**Comment by ramya-rao-a** [comment]
No problem, glad you are unblocked. 
Happy Coding!
