### ISSUE TITLE
[BUG] Installing godef & gotests always failing

### ISSUE THREAD

**Issue by WendySanarwanto** [Microsoft/vscode-go#747]
When I install `godef` &  `gotests` by clicking `Install all` button on appeared  notification toaster , at top of screen, the visual studio code unable to install these dependencies. (see this following screenshot)

![image](https://cloud.githubusercontent.com/assets/18456618/22354027/53ee7a2c-e45e-11e6-872a-7689813cb226.png)

Steps to replicate:
-------------------
1. Create a new `go` project in the `go` workspace
2. Ensure that the visual studio code has installed `go` extension from  Extensions panel.
![image](https://cloud.githubusercontent.com/assets/18456618/22354160/196e75e0-e45f-11e6-8f4f-d1eb10b463fd.png)
3.  Add a new `.go` file , write some code and hover the mouse cursor on line which is highlighted with red coloured underline. This will show the notification toaster at the top side. 
![image](https://cloud.githubusercontent.com/assets/18456618/22354226/5c71b6f4-e45f-11e6-9645-450059f7c4c4.png)
4. Click  either `Install All` or `Install`
5. Confirm that the installation is failing
![image](https://cloud.githubusercontent.com/assets/18456618/22354251/77a29b28-e45f-11e6-91e8-cf572d6c29d0.png)

System environment:
-----------------------
- OS Windows 10 version 1607 OS Build: 15014.1000
- Visual Studio Code version 1.8.1
- Go version 1.7.4 windows/amd64

**Comment by ramya-rao-a** [comment]
@WendySanarwanto 
According to the errors, looks like git is having problems finding the remote 

Can you run the below in your command line and share if you are seeing the same errors?
`go get -u -v github.com/rogpeppe/godef`
`go get -u -v github.com/cweill/gotests/...`

If you do see the same errors, then check if you have these folders 
$GOPATH/src/github.com/rogpeppe/godef
$GOPATH/src/github.com/cweill/gotests

If you do have these folders, then delete and try again.

**Comment by ramya-rao-a** [comment]
@WendySanarwanto closing this issue for now as there is nothing to be done from the Go extension's side.
Do let us know if the suggested fix worked for you or not.

**Comment by Antony-redzone** [comment]
I had the same issue, and the above fixed worked. As long as I did it in the VS terminal.
