### ISSUE TITLE
Code disappears on autosave

### ISSUE THREAD

**Issue by prashcr** [Microsoft/vscode-go#748]
I have autosave set to a delay of 1000ms.  
  
I tried to write some Go code, starting with an import:

```
import (
    "encoding/gob"
)
```

And 1 second later, the code gets deleted, presumably because the import is unused. While I agree with autoformatting on save, I think fixing lint errors on save is poor user experience. I'm new to go and I can't figure out which tool in this package is causing this. How do I make it just highlight lint errors and let me decide what I want to do?

**Comment by ramya-rao-a** [comment]
@prashcr By default, the formatting tool used is `goreturns` which removes unused imports.
You can change it to `gofmt` which wouldn't do so.

In your user settings add the following:
`"go.formatTool": "gofmt"`

**Comment by prashcr** [comment]
Thanks!
