### ISSUE TITLE
(Closed)Errors while writing the code

### ISSUE THREAD

**Issue by korovaisdead** [Microsoft/vscode-go#754]
Errors while writing the code. It is totally impossible to write the code while they continuously appearing: 

![Errors](http://image.prntscr.com/image/63831272393f4f6db29eac3591dad440.png "Errors")

Here is the plugins list: 

![Plugins](http://image.prntscr.com/image/b257e7458c3d4668bb3d5c12f6b5c829.png "Plugins")

So I'm not sure that they are the reason..

**Comment by ramya-rao-a** [comment]
@korovaisdead 

This is the repo for the Go extension for VS Code.

You seem to doing some angular work. 

The error most likely might be coming from the angular extension itself.
I'd suggest to disable the angular extension and see if you are still seeing the error.
If you don't see the error with the angular extension disabled, then log the issue in the repo for the angular extension.

Else you can log this in the repo for [VS Code](https://github.com/Microsoft/vscode)
