### ISSUE TITLE
Intellisense (Autocomplete) Not working

### ISSUE THREAD

**Issue by Tsessebe** [Microsoft/vscode-go#756]
This is similar to #441. I have tried all the remedies suggested without success.

![autocomplete](https://cloud.githubusercontent.com/assets/16239917/22461530/482fc6e4-e7b2-11e6-81c9-a69719037eb4.png)

![autocomplete1](https://cloud.githubusercontent.com/assets/16239917/22461544/5822e3f6-e7b2-11e6-9d6d-a8dc35588928.png)

go version go1.7.4 windows/amd64
vscode version 1.8.1

Both new install on clean pc.

Tried:
```
gocode stop
go get -u github.com/nsf/gocode
```
Also tried:

```
gocode stop
go get -u -ldflags -H=windowsgui github.com/nsf/gocode
```

I ran gocode in debug mode and output shows:

![gocode_debug_ouput](https://cloud.githubusercontent.com/assets/16239917/22461560/60f1ba20-e7b2-11e6-8029-57221782ac71.PNG)

Please advise as I've been at this for a few days now.

**Comment by ramya-rao-a** [comment]
Did you try the most recent update on that thread? https://github.com/Microsoft/vscode-go/issues/441#issuecomment-275958002

**Comment by Tsessebe** [comment]
Hi,
Thank you for the feedback.
I did delete the exe in the bin folder; not the settings.
I'll only be able to check that tomorrow as it's on my work pc.

**Comment by Tsessebe** [comment]
Hi,

We got this resolved; 

Thank you

**Comment by producerism** [comment]
`gocode stop` is incorrect, the correct command is `gocode close`
