### ISSUE TITLE
debug - stopOnEntry not working

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-go#763]
When I launch with `"stopOnEntry": true`, the debugger never pauses. Same on Mac and Windows. But I'm surprised that nobody has filed an issue on this. And there are even issues where people mention that they are using stopOnEntry successfully.

**Comment by roblourens** [comment]
Debugging it, I see that we send an initial StoppedEvent, then vscode asks for the list of threads. We call ListGoroutines, Delve returns an empty list that we send back to vscode. Then that's it. It seems like Delve doesn't want to do anything unless we send a Continue command at startup.

**Comment by dibalavs** [comment]
I have the same issue:
vscode: 1.82.2
delve debugger: 1.1.0
go extension: 0.6.93

**Comment by ramya-rao-a** [comment]
Fixed with #2762 
The fix is now available in the latest version of the update (0.11.7)
