### ISSUE TITLE
Lint not showing up

### ISSUE THREAD

**Issue by jtremback** [Microsoft/vscode-go#767]
It looks like this issue has been raised before in many forms, but I have tried all the remedies and they have not worked. The issue right now is that lint marks do not appear under mistakes in the editor, although `golint` correctly produces output in VS Code's built-in terminal.

This issue has come up while doing a fresh install of Go, VS Code and vscode-go on a freshly reformatted Mac.

It might be wise to collect all the various issues and remedies in a central place somewhere because I'm not sure if I've missed something that may work.

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jehan/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b2/fllv55fn17z_pdqxzb4_dnl80000gn/T/go-build079421072=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by jtremback** [comment]
I was able to fix this issue by uninstalling and reinstalling vscode-go and then running it on a "hello world" file with no errors and then introducing an error. I think it might have choked earlier because I was trying it for the first on a file that already had errors and would not build.

**Comment by ramya-rao-a** [comment]
@jtremback Even if there are build errors, linting warnings should still show up.
Linting is triggered on save.

**Comment by jtremback** [comment]
Not sure what the issue was, but those steps worked for me so maybe it will help someone else.
