### ISSUE TITLE
The completion suggest is invalid if some comments contain chinese

### ISSUE THREAD

**Issue by holmeszyx** [Microsoft/vscode-go#77]
I think it may happen when comments contain no only chinese but also other no acsii characters.(like Japanese, no testing)

See Image (A) below. Suggests list for package `fmt` never show when press '.' after 'fmt'.
If I delete `测试` in line 8 like image (B),  everthing be ok now.

(A.)
![invalid](https://raw.githubusercontent.com/holmeszyx/GoExercise/master/tmp/comment1.png)

(B.)
![normal](https://raw.githubusercontent.com/holmeszyx/GoExercise/master/tmp/comment2.png)

Test code.

```go
package main

import (
	"fmt"
)

// Test1 this is for 测试
func Test1(i int)  {
	i = 123
}

func main() {
	fmt.
}
```

**Comment by Reposkeeper** [comment]
not only comments. if unicode in Go Strings, the completion suggest is also invalid.

**Comment by lukehoban** [comment]
@holmeszyx @Reposkeeper Thanks for this.  Pretty sure this was fixed with https://github.com/Microsoft/vscode-go/issues/77.  I just pushed an update to `vscode-go` to `0.6.13` with this fix.  Could you try upgrading, and if you still see this issue, please reactivate.

**Comment by JohnSmithX** [comment]
The `godef` has the same problem.

**Comment by lukehoban** [comment]
Thanks @JohnSmithX.   I've pushed additional fixes for this with some of the other features.  Hover, goto-definition, rename, and find-references apparently all had a similar problem but should now be fixed.

See https://github.com/Microsoft/vscode-go/commit/328ef9ea5223e682dac36653494939d9694f78eb.

**Comment by JohnSmithX** [comment]
@lukehoban Good job!
