### ISSUE TITLE
Trying to start the debugger two times in a row ends in a "endless loop"

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#770]
_From @Gargo83 on November 10, 2016 20:43_

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.48|

There seems to be a problem with the debugger.
Once you try to start it two times it starts and will nerver end.

Note to the "Steps to Reproduce":
I do not do the exact same thing. In reality i try to resolve my bug between steps 2 and 3.
So i change and save one or more files. But the process in "Steps to Reprocuce" is the simplest way to reproduce.

---

Steps to Reproduce:

1. Produce a compile error in your golang project
2. Try to start the debugger. It will output a error in the DEBUG CONSOLE and nothing else happens.
3. Try to start the debugger a second time. The "Debug Toolbar" appears. The Progress blue line above the side bar is "spinning" and clicking on the stop symbol on the debug toolbar doesn't do anything

_Copied from original issue: Microsoft/vscode#15314_

**Comment by ramya-rao-a** [comment]
_From @isidorn on November 14, 2016 9:25_

This seems like an issue with our go extension, thus forwarding to @ramya-rao-a to try to reproduce. Since I do not get this with node debugging

**Comment by ramya-rao-a** [comment]
@Gargo83, in your repro steps, after step 2, do you stop the debug process by clicking on the stop symbol?

**Comment by psollberger** [comment]
@ramya-rao-a in my case the debug toolbar didn't show up in step 2. Only the errors where displayed.
As soon as i get home i can check what happens with the latest version.

**Comment by Gargo83** [comment]
@ramya-rao-a i can confirm that it now behaves like you say

This was not the case at the time i filled this bug.
I think this is now a better situation because Visual Studio Code doesn't need to be restartet anymore.

But now neigther the debug console nor the problems window appear on a failed build/run
So i guess the initial bug was fixed but now this inconvenience appeared

**Comment by ramya-rao-a** [comment]
Thanks @Gargo83 , #492 is tracking what you now observe.

The fix will be out in the next update.

Will close this in favor of #492
