### ISSUE TITLE
Rename fails with missing vendor dependency

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode-go#773]
"Rename symbol" gives me this truncated error message:

<img width="1055" alt="screen shot 2017-02-06 at 17 10 35" src="https://cloud.githubusercontent.com/assets/50314/22668592/3e21da2a-ec8f-11e6-8629-82ccfdc0ba2b.png">

The error is that it's complaining about not finding the package `github.com/olivere/elastic`. That package is in my project's `vendor` folder.

There's nothing in the debug console panel, although when I opened it just now, I got this weird UI artifact at the bottom of the window that eventually goes away (a stuck tooltip perhaps?):

<img width="1440" alt="screen shot 2017-02-06 at 17 11 40" src="https://cloud.githubusercontent.com/assets/50314/22668641/68f80076-ec8f-11e6-9356-06cfc0efaaae.png">

However, I can't copy the text, so I don't have the complete output.

Doing it from the command line works fine:

```
$ gorename -d -from '"github.com/sanity-io/gradient/pkg/search/plans".Constant' -to ConstantValue
```

I set `go.gopath` in my config to the same thing `$GOPATH` is set to, just to be sure.

VSCode 1.9.0, vscode-go 0.6.53.

**Comment by ramya-rao-a** [comment]
Can you try `gorename`  from command line with the `-offset` param (which is used by the extension) instead of the `-from` param?

**Comment by atombender** [comment]
This works fine:

```
$ gorename -offset pkg/search/plans/plans.go:#1691 -to ConstantValue
```

Since I couldn't figure out how to see the command that vscode-go runs, I replaced `gorename` with a shell script that logs to a file. It's running:

```
gorename -offset /Users/alex/.go/src/github.com/sanity-io/gradient/pkg/search/plans/plans.go:#1691 -to ConstantValue -tags ""
```

and it's doing so from `/`. If I do this from the command line, I get tons of errors:

```
/Users/alex/.go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/querysource/scenarios_test.go:11:10: could not import github.com/olivere/elastic (cannot find package "github.com/olivere/elastic" in any of:
	/usr/local/opt/go/libexec/src/github.com/olivere/elastic (from $GOROOT)
	/Users/alex/.go/src/github.com/olivere/elastic (from $GOPATH))
/Users/alex/.go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/querysource/source_test.go:10:2: could not import github.com/olivere/elastic (cannot find package "github.com/olivere/elastic" in any of:
	/usr/local/opt/go/libexec/src/github.com/olivere/elastic (from $GOROOT)
	/Users/alex/.go/src/github.com/olivere/elastic (from $GOPATH))
/Users/alex/.go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/querysource/source_test.go:24:18: undeclared name: elastic
[... etc ...]
```

So it's evidently because the command is run from the root. Bug in `gorename` that causes it to ignore `vendor` if it's not in `$PWD`, maybe?

**Comment by ramya-rao-a** [comment]
That's great finding!

When vscode-go runs `gorename`, it uses the absolute path for the file for the -offset parameter and is run from the workspace root.

So, can you try running your shell script from the workspace root that was open in VS Code?

**Comment by atombender** [comment]
But as I pointed out above, it is actually running `gorename` in `/` (which is not my workspace root!). Running the command from the workspace root works fine.

**Comment by ramya-rao-a** [comment]
There is something else at play here... 
I am testing on the `github.com/godoctor/godoctor` project which has vendor dependencies.
The file I am trying to rename is importing one of the vendor package.

No matter where I run the gorename from, it is always successful

<img width="874" alt="screen shot 2017-02-07 at 11 29 36 am" src="https://cloud.githubusercontent.com/assets/16890566/22707783/c0ba2dea-ed28-11e6-81ef-8acafc9b3a69.png">

Is it possible for you to point me to the code you are using so that I can repro it as well?

**Comment by atombender** [comment]
The code isn't public yet, but I email it to you privately.

**Comment by atombender** [comment]
Turns out my `gorename` was old. Sorry about the noise.
