### ISSUE TITLE
extension does not work

### ISSUE THREAD

**Issue by velomarc** [Microsoft/vscode-go#776]
seems all extensions do not work, and the "build task" also does not work. but it worked well yesterday, I'm so confused

my settings.json
{
    "editor.tabSize": 2,
    "editor.fontSize": 16,
    "editor.fontFamily": "Monaco",
    "files.autoSave": "onFocusChange",
    "go.buildOnSave": false,
    "go.lintOnSave": false,
    "go.vetOnSave": false,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "go.goroot": "/Users/dev/golang/go",
    "go.gopath": "${workspaceRoot}/thirdpartylibs:${workspaceRoot}/progs",
    "go.gocodeAutoBuild": false
}

tasks.json

{
    "version": "0.1.0",
    "command": "go",
    "isShellCommand": true,
    //"args": ["install", "-v", "./..."],
    "args": ["install", "-v", "test/testprog"],
    "showOutput": "always",
    "echoCommand": true
}

**Comment by ramya-rao-a** [comment]
@velomarc Did you do any updates since yesterday?
This sounds like VS Code is stuck in a bad state.
what other extensions are you using?

Sorry for the typical workaround, but have you tried closing and restarting VS Code?

**Comment by velomarc** [comment]
@ramya-rao-a  Thank you for your reply, I'm also thinking of that if it's the problem of Vs Code, 
I tried to remove all extensions and then reinstall vscode-go, it still does not work, I even tried to remove Vs Code, but after I reinstalled Vs Code, the problem still exists, Im not sure how to remove Vs Code completely, even I removed Vs Code from Applications, seems some configuration files still exist in somewhere , do you have any idea about this?

**Comment by velomarc** [comment]
I removed these following folders, then it works again
/Users/dev/Library/Application Support/Code
/Users/dev/Library/Saved Application State/com.microsoft.VSCode.savedState
/Users/dev/Library/.vscode

Thank you

**Comment by ramya-rao-a** [comment]
Sorry you had to go through all that. Now you are unblocked, correct?
Happy Coding!
