### ISSUE TITLE
unable to eval expression when debugging

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode-go#779]
vscode:1.9.0
vscode-go:0.6.52
delve: commit 8c96e275d0e0d943f8d5d4a34900a0e3bbc94810
\# dlv version
Delve Debugger
Version: 0.12.1
Build:

when i step into a function, i can not even evaluate the input parameters

![default](https://cloud.githubusercontent.com/assets/1210201/22722213/71dfa466-edf0-11e6-9e25-d20026c5bb74.PNG)

**Comment by ramya-rao-a** [comment]
I am able to eval the input param and the variable inside the function as well.

<img width="585" alt="screen shot 2017-02-07 at 9 23 36 pm" src="https://cloud.githubusercontent.com/assets/16890566/22724554/d5d40770-ed7b-11e6-9064-989186b1e9f5.png">

I am using the latest delve (0.12.1) and the latest Go extension (0.6.53). How about you?

@roblourens Do you know where the message "unable to find function context" is coming from? Is that a generic message?

**Comment by bruceauyeung** [comment]
@ramya-rao-a i use vscode-go 0.6.52, but vscode does not notify me there is a newer vscode-go version

**Comment by bruceauyeung** [comment]
@ramya-rao-a the problem occurs when golang 1.8rc1 is used, after upgrading to golang 1.8rc3, the problem is gone, thanks!

**Comment by ramya-rao-a** [comment]
@bruceauyeung Can you share a screenshot of your extensions viewless? There should be an update button next to the Go extension there if you are still on 0.6.52

**Comment by ramya-rao-a** [comment]
I haven't tested with go 1.8 rc versions yet. Please do let us know if any of the features of the Go extension do not work as expected with go 1.8

**Comment by bruceauyeung** [comment]
![1](https://cloud.githubusercontent.com/assets/1210201/22764347/1d891090-eea5-11e6-9ba3-b88fd4d75713.png)

i use vscode behind a proxy. you can see my proxy program receives update query requests from vscode
please ignore those Chinese characters which are irrelevant to this subject.

**Comment by ramya-rao-a** [comment]
Were you able to see the Update button/notification previously? What version of VS Code are you using?

@joaomoreno @sandy081 Extension update notification should work behind proxy as well correct?

**Comment by joaomoreno** [comment]
If you can query for extensions in Code, the update notifications should work.

But proxies are a bit of a mess right now. Microsoft/vscode#18103
