### ISSUE TITLE
Follow up of #67: Debugger not working, no feedback on what is wrong.

### ISSUE THREAD

**Issue by coussej** [Microsoft/vscode-go#78]
Follow up on #67, as I cant reopen the issue, additional info provide in [comment](https://github.com/Microsoft/vscode-go/issues/67#issuecomment-159072450), copied here:

I do indeed have the latest version. I have a very simple program: 
![screen shot 2015-11-23 at 22 27 01](https://cloud.githubusercontent.com/assets/9944663/11350426/caba0bba-9231-11e5-95be-205ccebbdabc.png)

When I run with the following configuration:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch main.go",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "/Users/jeroen/golang/src/github.com/coussej/hello/main.go",
			"env": {},
			"args": []
		}
	]
}
```

... nothing happens:

![screen shot 2015-11-23 at 22 27 32](https://cloud.githubusercontent.com/assets/9944663/11350432/d0eb2cb2-9231-11e5-84a4-22e6aa9bb9c0.png)

I also tried other values for the program property, but no result. It's just strange I don't get any error message. The dlv command is working, I can debug the app using dlv debug in terminal.

**Comment by joeblew99** [comment]
i have had good success with this.
Maybe there is some relative pathing issue
From the termianl which is the root of my project, i open ```code . ````
then i edit the launch json, with a  ```./examples/ex01/. ```

might be worth a try

**Comment by coussej** [comment]
@joeblew99 I'll give it a try, but whatever the issue is I believe there should be some kind of message indicating what the problem is. Even some diagnostic messages like 
    
    started debugging main.go in /Users/../hello/

could give a clue on what's happening here.

**Comment by polds** [comment]
What version are you running? I too had this issue but it was resolved in `0.6.10`:

![screen shot 2015-11-24 at 10 54 24 am](https://cloud.githubusercontent.com/assets/2372558/11375691/c7feeda6-9299-11e5-94ee-bf80dcfa19ad.png)

**Comment by lukehoban** [comment]
@coussej Yeah, as @poids mentioned, you should be seeing information coming back to the debug console if you are using the most recent update to the `vscode-go` extension.

If with the latest you still aren't seeing anything, can I ask you to try something a little more complicated to debug this?  

If you follow the instructions [here](https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/Readme.md) you can debug the debugger.  It's a bit of work to set up, but once you do you can step through the code in https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts to see where things are failing.  In particular the code around line 107 is where things would likely be going wrong.

**Comment by coussej** [comment]
I was running 0.6.11. 

I followed your instructions for debugging. The code fails in goPath.ts, line 17:

    var workspaces = process.env["GOPATH"].split(path.delimiter);

with message "Cannot read property 'split' of undefined". This indicates it doesn't find my GOPATH environment variable. Indeed, when looking in globals > process > env, there is no gopath variable. However all instances were started from a terminal which has the GOPATH set:

![screen shot 2015-11-24 at 21 56 52](https://cloud.githubusercontent.com/assets/9944663/11380437/51986f04-92f6-11e5-8c76-e3b45ae8b174.png)

Strange.

**Comment by lukehoban** [comment]
Thanks @coussej - I think that identified at least one issue here - which I've fixed with 315722bdf4eb205b77a350e33ab5aac5f3b61125.

I've published `0.6.14` with that fix - could you try it out and see if it fixes your problem?

I believe there is still an underlying issue where the GOPATH env var is not being passed into the process that is running the debugger.  That may be an underlying Code issue, still trying to track that down.

**Comment by coussej** [comment]
Hi @lukehoban , will try, but I don't have access to my mac until saturday. I'll provide feedback as soon as I get back.

Anyway, thanks already for your quick responses.

**Comment by lukehoban** [comment]
@coussej I'm going to close this out for now - but if you can get any more info I'd love to look into this further.

**Comment by coussej** [comment]
Hi @lukehoban, I've updated the plugin and it works now! thanks! However, I now see something else where in some cases the local variables are not shown when the debugger hits a breakpoint. It is only resolved by restarting code. I'll see if I can make it reproducible and open another issue if I can.

Thanks!

**Comment by lukehoban** [comment]
Thanks @coussej.  If you do get any more info on the issue with locals not showing up, could you report it here: https://github.com/Microsoft/vscode-go/issues/101.
