### ISSUE TITLE
Unhelpful error message when program is not full path in launch.config

### ISSUE THREAD

**Issue by surajbarkale-dolby** [Microsoft/vscode-go#782]
Summery
---------
When using delve in vscode, I got `Failed to continue: "Error: spawn /usr/local/bin/dlv ENOENT"` error. Using command line to launch delve works as expected.

Reproduction
-------------
1. Clone `https://github.com/surajbarkale-dolby/gb-example/tree/vscode`
2. Execute `debug.sh` to launch delve to verify that delve works
3. Launch visual studio code (preferably using `code .`)
4. Try launching debugger by pressing F5

**Comment by ramya-rao-a** [comment]
Can you run `which dlv` in your command line and see if the value is `/usr/local/bin/dlv`?

**Comment by surajbarkale-dolby** [comment]
Yes I installed it using `brew` and it is located at `/usr/local/bin/dlv`. The reported version is 0.12.1 with build version v0.12.1.

**Comment by surajbarkale-dolby** [comment]
The fix is to use full path of executable for "program" key in launch configuration (see [this diff](https://github.com/surajbarkale-dolby/gb-example/commit/3e2cdb0523d7c6fb9ea499454e9a6f2ec6abcdc5)).

Thanks to your instructions about debugging the debugger, I was able to pinpoint root cause of this issue. In `goDebug.ts`, program name is not added to command line (as I did in debug.sh). Instead, vscode-go tries to change directory to the one containing `program` argument. However, the directory is not valid causing ENOENT error.

We should improve the documentation and add a better error message in [goDebug.ts](https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L238) instead of ignoring the error.

I shall try to send a pull request with the change tomorrow.

**Comment by ramya-rao-a** [comment]
Thanks @surajbarkale-dolby !

Yes, the program key needs to be a full path. I just added a line about this in the [wiki](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson)

The debugging part of the extension needs some work, we have been trying to improve it in the last few weeks. 

Looking forward to your PR.

**Comment by ramya-rao-a** [comment]
Fixed in the latest update (0.6.54) to the Go extension.
