### ISSUE TITLE
IntelliSense doesn't understand abbreviated elements when initializing an array/slice of structs

### ISSUE THREAD

**Issue by thrnio** [Microsoft/vscode-go#783]
Consider the following code:

~~~go
package controller

type foo struct {
	bar string
	baz bool
}

var foobar = []foo{
	{bar: "bar", baz: true},
}
~~~

This is valid Go code, since it's optional to specify `foo` before each individual element (i.e., `{bar: "bar", baz: true}`). IntelliSense, however seems to attempt to autocomplete as if it were just `foo{ | }`, not `[]foo{ | }`. Explicitly doing 

~~~go
[]foo{
    foo{bar: "bar", baz: true},
}
~~~

works better.

![golang-array-struct-intellisense-bug](https://cloud.githubusercontent.com/assets/97464/22809008/30560036-eee4-11e6-823b-8c843aaca631.png)

(Ignore the invalid use of `:=`; I was quickly throwing something together enough to get a screenshot and wasn't paying attention. It doesn't change the behavior from the code snippet above.)

**Comment by ramya-rao-a** [comment]
@thrnio We use `gocode` for the completions, where we pass the cursor position and the file contents and show what is returned by `gocode`. Therefore, will move this issue to the repo for `gocode`

**Comment by ramya-rao-a** [comment]
This issue was moved to nsf/gocode#422
