### ISSUE TITLE
Unapprove personal packages

### ISSUE THREAD

**Issue by MarcusMann** [Microsoft/vscode-go#785]
At least in my Visual Code, when I try to import a custom package (my), it simply removes the import because it thinks I'm not using the package.

But in truth I am.

**Comment by ramya-rao-a** [comment]
Can you give an example? A screenshot or a screencast/gif perhaps?

See #705 If you have imported a package and save your file before using the package, formatting will remove it assuming that it is an unused package.

Is there any line of code that is using this custom package of yours before the file gets saved?
