### ISSUE TITLE
Autocomplete issue with function arguments

### ISSUE THREAD

**Issue by ideahitme** [Microsoft/vscode-go#788]
**Some info**: 
Max OS X Sierra 10.12.3
VS Code 1.9.1 f9d0c687ff2ea7aabd85fb9a43129117c0ecf519 
Gocode latest version
vscode-go 0.6.53 

Autocomplete does not popup on function arguments:
![screen shot 2017-02-12 at 23 38 06](https://cloud.githubusercontent.com/assets/23239537/22866819/6b5da626-f17c-11e6-92e1-5667aeca52de.png)

Gocode output:

![screen shot 2017-02-12 at 23 39 51](https://cloud.githubusercontent.com/assets/23239537/22866835/a2de51b8-f17c-11e6-8137-452eed6b8dfa.png)

Works otherwise:
![screen shot 2017-02-12 at 23 38 15](https://cloud.githubusercontent.com/assets/23239537/22866821/74fec200-f17c-11e6-93b6-892a7258bee3.png)

**Comment by ramya-rao-a** [comment]
According to the `gocode` output you have shared, it finds the 5 candidates.
But this output doesn't look like the output that can be consumed by the editor, can you share the command you ran to get that output?

Below is my example for your scenario and auto complete works well for function arguments.
Am I missing something in this example?

<img width="279" alt="screen shot 2017-02-16 at 12 02 29 am" src="https://cloud.githubusercontent.com/assets/16890566/23012471/475872b8-f3db-11e6-8267-d4f1bf64aa4b.png">

**Comment by ideahitme** [comment]
Hi,

I got the output through

1. `gocode close`
2. `gocode -s -debug`
3. Started typing

**Comment by ramya-rao-a** [comment]
Also, can you take a look at the example I shared, and let me know if it is the same case as yours?

**Comment by ideahitme** [comment]
after a bit more investigation, it actually happens only if the parameter is not first argument passed. Your example works, as well as this:

![screen shot 2017-02-16 at 17 37 46](https://cloud.githubusercontent.com/assets/23239537/23030670/b6209d72-f46e-11e6-86ef-0ee4d8e6f2d7.png)

**Comment by ramya-rao-a** [comment]
It still works for the second argument for me

![image](https://cloud.githubusercontent.com/assets/16890566/23478872/8dfe5024-fe77-11e6-9cb5-80d102d41a5c.png)

**Comment by ramya-rao-a** [comment]
@ideahitme I couldn't repro this the last I tried. Closing this issue as 3 months is past and there is no new development.

If it still repros for you, then we can re-open this issue
