### ISSUE TITLE
Unable to Find in Marketplace

### ISSUE THREAD

**Issue by lloy0076** [Microsoft/vscode-go#791]
I simply cannot find this tool in my Visual Studio 15 (Community Edition) marketplace - searching for just "Go" doesn't bring this up.

Is there another way to install this (or download it and point VS at it)?

**Comment by ramya-rao-a** [comment]
@lloy0076 This extension is for Visual Studio Code which is a separate product from Visual Studio.

**Comment by lloy0076** [comment]
Oops, my mistake :)

**Comment by ramya-rao-a** [comment]
No problem, do give Visual Studio Code a try too :)
