### ISSUE TITLE
Possible feature of automatically generation struct tags

### ISSUE THREAD

**Issue by barthr** [Microsoft/vscode-go#792]
Currently in vim-go you can create struct tags with a shortcut. This would be a handy feature and is possible with the new library fatih released:

```https://github.com/fatih/gomodifytags```

Any thoughts?

**Comment by fatih** [comment]
As a side note, I've created a section with some more information on how to integrate it with other editors, check this out: https://github.com/fatih/gomodifytags#editor-integration

**Comment by fatih** [comment]
Seems like this is a duplicate. See #433

**Comment by ramya-rao-a** [comment]
Thanks @fatih!
@barthr Closing this issue as duplicate of #433 
Please do up vote #433 and we'll get to it soon
