### ISSUE TITLE
Missing local variables while debugging

### ISSUE THREAD

**Issue by kopaygorodsky** [Microsoft/vscode-go#793]
sometimes(some magic time), I can't see any local variables, except arguments.  
Here is the screenshot, I implement KMP algorithm and can't see variables. It works sometimes.

![img_2017-02-14 00 42 15](https://cloud.githubusercontent.com/assets/2415637/22906736/92fced90-f24e-11e6-9a62-eb7197ddde11.jpg)
launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {
                "GOPATH": "/Users/kopaygorodsky/Development/www/go"
            },
            "args": [],
            "showLog": true
        }
    ],
    "go.lintTool": "gometalinter"
}
```
Also if I put a breakpoint to an empty line - debugger will skip this line, show result and error at the end: 'failed to get threads', but  I think it should be referenced to delve? right? 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/2415637/22906865/343e773c-f24f-11e6-8564-b420649ed7fc.png)

Versions:
![image](https://cloud.githubusercontent.com/assets/2415637/22906991/be1f688a-f24f-11e6-8774-7714fa2dffa3.png)

I've checked new IDE GOLANG EAP from JetBrains and see the same behavior. Should be referenced to delve, I think. The only difference that I can't put a breakpoint to empty line in GOLANG EAP.

**Comment by ramya-rao-a** [comment]
The next time you don't see the local variables, can you add `"trace": true` to your launch.config and try to repro again? This will add a detailed logging to a text file, the path to the file will be in the debug console. Please share that file with us, so that we try to spot what went wrong.

About your second question, I tried the same with a simple hello world type of code. The breakpoint on an empty line does get skipped but I don't see the "Failed to get threads" message. 
You say that in the other IDE you cannot put the breakpoint, then what do you mean by "I see the same behavior" ?

**Comment by kopaygorodsky** [comment]
@ramya-rao-a 
Ok, will do. 

I mean the same problem with variables. Sorry for the misunderstanding.

**Comment by ramya-rao-a** [comment]
@kopaygorodsky  No problem
@roblourens Do you think we can do anything about not allowing to add breakpoint on a blank line?

**Comment by roblourens** [comment]
Probably not. It's up to the debug adapter to move the breakpoint if it's not in a valid spot. We can see what Delve is doing here and check whether we can do something else to make it not break, or file a bug on Delve.

**Comment by cyc115** [comment]
I can confirm the same behavior 
![screen shot 2017-04-21 at 4 53 52 pm](https://cloud.githubusercontent.com/assets/2107333/25297425/47b970da-26b3-11e7-8e81-c1846fe044f8.png)

**Comment by kopaygorodsky** [comment]
@cyc115  it's not a problem of vscode
https://github.com/derekparker/delve/issues/738

**Comment by kopaygorodsky** [comment]
@ramya-rao-a this issue can be closed, Delve fixed. Update will be available in next release.

**Comment by ramya-rao-a** [comment]
Thanks for looping back @kopaygorodsky
