### ISSUE TITLE
Output panel always popping when coverOnSave=true

### ISSUE THREAD

**Issue by joaodias** [Microsoft/vscode-go#798]
Wouldn't it be nice to add an option so that the output panel would not pop every time something is failing?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/4543850/22927305/6b0fdf9a-f2a8-11e6-88d8-7c4140e66c38.gif)

`getCoverage()` in `goCover.ts` is being called with `true` every time. Can we somehow make this optional?

Does that make sense?

**Comment by ramya-rao-a** [comment]
@joaodias This is fixed with https://github.com/Microsoft/vscode-go/commit/3c4744abb1000accbb8e7bf1058ea1024a362534

The next update will have the fix.

Thanks for reporting!
