### ISSUE TITLE
debug console: the output of the debugger is mixed with the output of the program

### ISSUE THREAD

**Issue by renannprado** [Microsoft/vscode-go#799]
Is there a way to filter the output so that I don't see the output of the debugger?

![image](https://cloud.githubusercontent.com/assets/2359543/22954500/ed4b2adc-f2fd-11e6-9951-c7c4d34d131b.png)

Edit:
Actually instead of filtering, I believe it would be better if we had the output of the program (stdout/stderr) in the *Output* tab.

![image](https://cloud.githubusercontent.com/assets/2359543/22954569/608314ce-f2fe-11e6-88db-a8de602a127d.png)

**Comment by ramya-rao-a** [comment]
Set `showLog` to false in your launch.json to not see the logs from the debugger.

As for sending the program output to output tab, Debug Console is the place where any output during debugging is meant to go. @roblourens You have any insights here?

**Comment by ramya-rao-a** [comment]
Closing as there is a way to get just the program output (set `showLogs` to false)

AFAIK debugger can only print out to the debug console.

If anyone knows otherwise, please chime in.

**Comment by roblourens** [comment]
Right, there is actually no easy way for a debug adapter to write to the Output channel, and I think that what you do currently is the right thing to do.
