### ISSUE TITLE
there should be a way to collapse multi-line comments

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode-go#805]
and it should be enabled by default

**Comment by ramya-rao-a** [comment]
Code folding in VS Code is done based on indentation and spaces. It does not depend on any language or language syntax.

All contiguous lines that have the same number of spaces or tabs in the starting of the lines can be collapsed together

<img width="470" alt="screen shot 2017-02-15 at 11 15 44 pm" src="https://cloud.githubusercontent.com/assets/16890566/23011243/be394d64-f3d4-11e6-98b5-fc681b6080a4.png">

**Comment by bruceauyeung** [comment]
@ramya-rao-a 
https://golang.org/doc/effective_go.html#commentary gives an example of block comment which has no space/tab before the lines.

all of `.go` source files in Kubernetes project have package comments , and all of these package comments have no space / tab before the lines.

gogland EAP version can colapse this kind of comments even when they don't have no space / tab before the lines.
![image 2](https://cloud.githubusercontent.com/assets/1210201/23015723/dcb74daa-f46e-11e6-8eeb-02c04d232dd1.png)

so i sugguest :
even when multi-line comments have no space/tab preceding the lines, vscode / vscode-go should colapse this kind of comments.

ps: should i file a new issue under microsoft/vscode project ?
