### ISSUE TITLE
[feature request]rename symbol should be more intelligent

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode-go#806]
i have a variable `test_name`, when my cursor is between `_` and `n`, if i press `F2`, the rename symbol window is poped up:
1. i think the cursor in the popup window(rename symbol window) should also be exactly in the same place in the source editor window instead of the whole variable name being selected.
2. if i press `arrow left` / `arrow right` key, the cursor should move left / right one character instead of move to the most left / right
3. if i press `home` / `end` key, the cursor should move to the most left / right

but when the whole variable name is double clicked and selected, if i press `F2`, the rename symbol window is poped up:
1. i think the whole variable name in the popup window(rename symbol window) should be selected.
2. if i press `arrow left` / `arrow right` key, the cursor should move left / right one character instead of move to the most left / right
3. if i press `home` / `end` key, the cursor should move to the most left / right

**Comment by ramya-rao-a** [comment]
@bruceauyeung Everything you have described is the VS Code editor behavior and has nothing to do with the Go extension. Therefore please log an issue in the repo for VS Code instead.

Regardless here are my thoughts

When whole variable name is selected and you press `F2`:

> i think the whole variable name in the popup window(rename symbol window) should be selected.

That is exactly what happens, am not sure what you are expecting

> if i press arrow left / arrow right key, the cursor should move left / right one character instead of move to the most left / right

Once you press any key, the selection in the rename symbol window goes away, and every arrow left/right does take you one char left and right. 

> if i press home / end key, the cursor should move to the most left / right

This is also the current behaviour
