### ISSUE TITLE
Error:Error:Illegal value for `line`

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode-go#807]
when i was renaming symbols, this information message poped up. i dont know why .
vscode : 1.9.1
vscode-go : 1.6.52

**Comment by ramya-rao-a** [comment]
Does it happen overtime you try rename? Does it happen only on certain files/projects or all the time?

Is this in Windows? If yes, then can you type `diff` in the terminal and see if you get "not recognized as an external or internal command" ?

If you are not on Windows your machine would have the `diff` cmd available. If you are on Windows and the `diff` cmd does not give that error, then the `diff` cmd is available. 

When `diff` command is not available the the `gorename` tool tries to overwrite the file on disk with the updated file. If `diff` command is available the the diff output from `gorename` is applied to the editor.

I believe the error you are seeing occurs when the file on disk is overwritten and the file enters into a bad state.

**Comment by bruceauyeung** [comment]
@ramya-rao-a 
>Does it happen every time you try rename? 

no , today i renamed over 10 variable names, but only one time this error occurred.

>Does it happen only on certain files/projects or all the time?

not all the time, i have no idea whether its bound to certain files/projects.

>Is this in Windows?

Ubuntu 16.04.1 LTS. sorry about this, i should have mentioned this.

>If you are not on Windows your machine would have the diff cmd available.

on my machine, `diff` command does exist
>\# diff --version
diff (GNU diffutils) 3.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower.

this is my guess :
when i renamed a variable name in one file, and didn't save this file, then if i rename another variable name in this file, is this the reason why the error occurred?

**Comment by ramya-rao-a** [comment]
Can you reproduce the error using the steps you outlined in your guess?

**Comment by bruceauyeung** [comment]
@ramya-rao-a 
>Can you reproduce the error using the steps you outlined in your guess?

no.
there is a message popped up and renaming process terminates :

> these files have been changed in the meantime. /path/to/fileA, /path/to/fileA

**Comment by ramya-rao-a** [comment]
@bruceauyeung Sorry, I never got around to getting a repro for this.

Its been over a year. Both the Go extension and VS Code has undergone a lot of changes, chances are you dont have a repro for this either. If you do, feel free to re-open this issue and we can take another look.

Happy Coding!
