### ISSUE TITLE
Debugging stops at breakpoints but can't step over/into

### ISSUE THREAD

**Issue by idanya** [Microsoft/vscode-go#809]
When I set a breakpoint anywhere in the code the debugger stops, from there if I try to step over or into it all breaks. This is the log stepping over produces:

```
2017/02/21 14:46:21 debugger.go:412: continuing
2017/02/21 14:46:31 debugger.go:432: nexting
unexpected fault address 0x6e520054b00
fatal error: fault
2017/02/21 14:46:34 debugger.go:412: continuing
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6e520054b00 pc=0x125ece9]

```

When paused in a BP I can see the stack, view variables, watch and everything looks good. I can even continue to the next BP using "continue" (F5). Stepping over or into the command is the only thing that breaks the session.

Delve 0.12.1
VSCode 1.9.1
Go Extension 0.6.53

**Comment by ramya-rao-a** [comment]
@idanya Which version of Go are you using and on what platform?

I have been seeing issues with Go 1.8 in Mac, but previous version of Go were fine on my Mac
Go 1.8 is also working fine in Windows

**Comment by idanya** [comment]
@ramya-rao-a  Indeed I am using Go 1.8 on Mac.

**Comment by ramya-rao-a** [comment]
Can you try `dlv` from the command line and see if you can step in/over/out successfully?

**Comment by fasa123** [comment]
Exact same problem here for every go file. Also running the same versions (on Linux). Delve works fine everywhere else (manually and in other editors)

**Comment by nicksnyder** [comment]
Potentially related https://github.com/derekparker/delve/issues/761

**Comment by josiahbgrace** [comment]
Hi, I fixed this by installing the head version of delve.
brew install --HEAD go-delve/delve/delve

**Comment by kalbasit** [comment]
Should this be closed?

**Comment by ramya-rao-a** [comment]
Yes, we should. Thanks @kalbasit 

@idanya Get the latest delve and the issue should be fixed.
