### ISSUE TITLE
gorename: doesn't register as a "save"

### ISSUE THREAD

**Issue by newhook** [Microsoft/vscode-go#81]
This means after a gorename golint isn't re-run leaving potentiailly invalid markup.

**Comment by lukehoban** [comment]
Yes - I think this is the same issue as https://github.com/Microsoft/vscode-go/issues/13, which I have reported as a feature request on `gorename` here: https://github.com/golang/go/issues/13355.  

Anything more you think we can do independent of those two issues?

**Comment by newhook** [comment]
I sort of feel that having the external go tools use the source files on disk as a source of truth is causing multiple issues (including this one). For example, oracle gets out of date, flymake-style builds need multiple temporary files, godef potentially not working for source file changes among others...

**Comment by lukehoban** [comment]
Yes - I agree.  There's two solutions:

1. Basically require AutoSave to be on to get a good experience, and force saves of active buffer before running commands (like `rename` does in the current implementation) to ensure that the source of truth on disk is maintained.

2. Rebuild the Go tooling ecosystem around a model where a language-server can process document change notifications from a tool's in-memory edits, and then operate over this in-memory representation.  For example the TypeScript experience in Code is based off of https://github.com/Microsoft/TypeScript/tree/master/src/server which also powers the [Sublime Text TypeScript support](https://github.com/Microsoft/Typescript-Sublime-plugin).

I've so far focused on (1) as it allows building on the existing Go tools ecosystem.  I fear that (2) means taking on largely rebuilding the ecosystem of Go tools around a new model.  That may be necessary eventually for truly great IDE-like tooling around Go.

**Comment by lukehoban** [comment]
BTW - I just created a gitter chatroom for this repo (link in the README).  This discussion might be a good one to move there since it is cross-cutting.

**Comment by newhook** [comment]
Yes, makes perfect sense. I think that while 2 might be a worthy long term goal 1 is the only realistic solution at present. I guess for gofmt then we'd need to change to feeding in the newly written file and  applying diffs to get a sensible editing experience?

I remember reading that the intellij plugin doesn't use the go tooling, perhaps for the same reason. That said, I wonder what they did to solve this? Did they re-implement everything in java?

**Comment by lukehoban** [comment]
I believe the IntelliJ plugin does indeed reimplement the language analysis itself in Java.  The code is here though I haven't looked closely at their approach: https://github.com/go-lang-plugin-org/go-lang-idea-plugin.

**Comment by lukehoban** [comment]
Closing this for now - I think the work to be done here is tracked in other existing issues.
