### ISSUE TITLE
Autocompletion for the locally imported packages does not work

### ISSUE THREAD

**Issue by zerkms** [Microsoft/vscode-go#811]
Here is a repo with tiny project that reproduces the issue: https://github.com/zerkms/vscode-golang-relative-import

Steps to reproduce:

1. Open `main.go`
2. Create a new line in the `main` function
3. Type `bar.`

Expected: there should be autocompletion with the exported `Hello` function

Actual: no autocomplete shown automatically, and `ctrl+space` just shows all symbols available across the files

**Comment by emicklei** [comment]
a similar problem is when using the (unrecommended) dot import

```
import . "github.com/sample/pkg"
```

Exposed functions defined in this pkg are not found either (using v 0.6.53 of the plugin)

**Comment by caledhwa** [comment]
I am also seeing various issues with autocompletion in regard to generated files (which I don't understand). Possibly it's related to this?

**Comment by caledhwa** [comment]
I can confirm this as well. If I have an `import .` in a file, then most of my autocompletion does not function correctly.

**Comment by ramya-rao-a** [comment]
@zerkms I tried your example and I can see the auto-complete suggestion as expected.
I also see a build error saying `local import "./bar" in a non local package`

@emicklei @caledhwa I get auto complete for dot imported functions as well

I am using Go 1.8 in Mac OS X and the latest Go extension (0.6.55)

**Comment by zerkms** [comment]
That's odd, since I swear it was working for me. Not anymore :-S

Closing since I cannot reproduce it as well.

**Comment by ramya-rao-a** [comment]
We use `gocode` for auto-completion, that must have been stuck in an odd state.

**Comment by zerkms** [comment]
@ramya-rao-a Now I see what's happened: the issue is reproducible when code located outside of `$GOPATH`. Then the behaviour is as I explained: it compiles and runs, but does not autocomplete.

**Comment by ramya-rao-a** [comment]
@zerkms In that case please log the issue in http://github.com/nsf/gocode

**Comment by zerkms** [comment]
@ramya-rao-a done, thanks :-)
