### ISSUE TITLE
Add support for default GOPATH (Go 1.8)

### ISSUE THREAD

**Issue by samherrmann** [Microsoft/vscode-go#813]
Go 1.8 introduced a [default GOPATH](https://beta.golang.org/doc/go1.8#gopath) that is used when users do not set one themselves. That means that `go env` will return a valid GOPATH even when the GOPATH environment variable is not set. As such, the [isGoPathSet](https://github.com/Microsoft/vscode-go/blob/master/src/util.ts#L213) function returns a false negative in that scenario.

**Proposal:**
Instead of checking the GOPATH environment variable, use the output from the `go env GOPATH` command.

**Comment by ramya-rao-a** [comment]
The fix for this issue is now available in the latest update (0.6.54) to the Go extension.
Please update and let us know if you still see any issues
