### ISSUE TITLE
strings.Contains godoc tooltip renders wrong argument name

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode-go#814]
![image](https://cloud.githubusercontent.com/assets/159209/23244854/ff6fcb24-f93c-11e6-922a-d3d239aa1b99.png)

sssubstr should be substr.

**Comment by dmage** [comment]
It's a bug in [vscode](https://github.com/Microsoft/vscode/blob/72a0cfe1ccbc62c2c4b726a5ce8bab13335977bf/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L361), not vscode-go.

**Comment by anxiousmodernman** [comment]
I am also seeing this error.

![vscode_golang_error](https://cloud.githubusercontent.com/assets/396004/23367808/ae674cde-fcd9-11e6-97ee-bf8b8ea91c34.png)


```
Plugin Version 0.5.63
Go version 1.8 linux amd64
VS Code version 1.9.1
```

**Comment by dmage** [comment]
The bug is not in vscode-go, but in vscode. Same issue for TypeScript:
![2017-02-28_02-51-10](https://cloud.githubusercontent.com/assets/443137/23385444/e927b750-fd60-11e6-85c3-e5ff553d04ce.png)
Linked pull request should address the issue.

**Comment by ramya-rao-a** [comment]
Thanks @dmage!
