### ISSUE TITLE
Adding a comma into composite literals

### ISSUE THREAD

**Issue by deltaskelta** [Microsoft/vscode-go#818]
I don't know if this can be fixed from within the vscode extension or not but here is an example...

```
package main

import (
	"fmt"
)

func main() {
	T := []struct {
	    S string
    }{
        {
            "test" // comma needed here, but understandably absent
        } // no comma added here
    } // no comma added here
}
```

If you type this out, then there is no comma added in those two spots which interferes with the compiler so `go fmt` will not catch it either. This is a really common literal pattern in testing and I've gotten really annoyed having to go back and add commas everywhere.

Can this be fixed form within the extension?

**Comment by ramya-rao-a** [comment]
@deltaskelta #738 is tracking something similar, please add your thoughts there.

The conclusion there was that its hard for the extension to do this at present.
But, with the integration of the language server, this can be explored more.

If you have any ideas though, I am open for going through them.

Closing this issue in favor of #738
