### ISSUE TITLE
Pasting immediately into newly created file reverts to empty file

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode-go#819]
**Steps**:

1. Do `cmd+N` to create an empty, untitled file.
2. Hit `cmd+S` to save it as e.g. `foo.go`.
3. _Immediately_ paste something into the file.
4. Watch as VSC deletes the contents.
5. The empty file is now saved and marked as non-dirty.

I assume this is related to the format-on-save behaviour. It only occurs for Go files. I have `go.formatOnSave` enabled. I also have `editor.formatOnSave` enabled, which I think kicks in for JavaScript, but it's not happening with JS.

VSC 1.9.1, vscode-go 0.6.53.

**Comment by atombender** [comment]
Further information: This only happens if `editor.formatSave` is enabled.

**Comment by ramya-rao-a** [comment]
@atombender I can repro this even with `go.formatOnSave` set to `false`. Can you confirm?

**Comment by atombender** [comment]
I wasn't able to, but I will try again. Autosave, no.

**Comment by atombender** [comment]
Oh yeah, it happens even with `go.formatOnSave` set to `false` for me to. That points to a non-Go-extension-related bug, does it now?

**Comment by ramya-rao-a** [comment]
I would say so, but I cant repro it in a non Go file :( Can you?

**Comment by atombender** [comment]
No, I can't. Does it happen with the Go extension disabled?

**Comment by ramya-rao-a** [comment]
No, doesn't happen when the Go extension is disabled. So its definitely us.

`editor.formatOnSave` calls any registered formatter for the language of the given file.
This is the offending line https://github.com/Microsoft/vscode-go/blob/master/src/goFormat.ts#L69 in the Go extension that is causing the issue. Commented this line, and it no longer repros

Am not very sure why we explicitly save, but will look into it

**Comment by ramya-rao-a** [comment]
Since Go 0.6.70 we no longer do the explicit save and have changed the way format on save works which should fix this issue
