### ISSUE TITLE
goimpl support

### ISSUE THREAD

**Issue by itsjamie** [Microsoft/vscode-go#822]
Was looking at implementing [goimpl](https://github.com/sasha-s/goimpl) support into VSCode. It was one aspect from vim-go that I miss.

Any objections to a PR for this?

Any tips for implementation? I was thinking I would use the `gotests` implementation as a guide.

**Comment by ramya-rao-a** [comment]
#259 is tracking the feature request to integrate https://github.com/josharian/impl

I personally am not aware of pros and cons between using https://github.com/josharian/impl and https://github.com/sasha-s/goimpl
If you can make a comparison and present a case here, we have no objections for a subsequent PR and it is very much welcome  :)

**Comment by mattetti** [comment]
agreed, can we continue the conversation in #259 and close this duplicate issue tho?
