### ISSUE TITLE
there is a nag hint bar when edit golang source file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-go#823]
_From @wly65535 on February 27, 2017 15:9_

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.open *.go to edit a golang source file.
2.there is some hint in the top every FIVE SECOND,eg: The "gopkgs" command is not available, Use "go get xxxx" to intall, The "go def" command is not available, Use xxx to install. if I close the hint bar, it will be appear again soon, less than five seconds, I can't find any option as "no longer prompt"

_Copied from original issue: Microsoft/vscode#21503_

**Comment by ramya-rao-a** [comment]
@wly65535 Looks like you have the Go extension installed which needs certain Go tools installed to work.

Either uninstall the Go extension if you dont intend to use it.
Or install the dependent tools as suggested by the pop ups.

Is there any reason you wouldnt want to install the dependent tools?

**Comment by wly65535** [comment]
@ramya-rao-a Thanks, I uninstalled the go tool yesterday, the pop bar appear always, but when I boot my computer today, the pop bar no longer appear, maybe it's need to reboot.
to build a go project only need input "go build xxx", so I like building it from console manual.

**Comment by ramya-rao-a** [comment]
Yes, after uninstalling any extension, you need to reload VS Code window.
