### ISSUE TITLE
gometalinter with relative config path

### ISSUE THREAD

**Issue by giniedp** [Microsoft/vscode-go#825]
Is there a way to setup the gometalinter within vscode with a relative path to the config file?

When i use

```
  "go.lintTool": "gometalinter",
  "go.lintFlags": [
    "--config=golint.json"
  ],
```
then the relative path is not resolved from the project root and the file can not be found. Ofc. it works with an absolute path but i'd like to avoid that.

**Comment by diegobernardes** [comment]
Need this feature too, tryied with $GOPATH, etc... 
Nothing worked :(

**Comment by ramya-rao-a** [comment]
This should be easily do-able.

Will give it a try this weekend

**Comment by ramya-rao-a** [comment]
The fix for this is out in the latest update to the Go extension (0.6.59)

You can now use `${workspaceRoot}` and `~` in the file path for --config
