### ISSUE TITLE
Load envFile in .vscode/launch.json

### ISSUE THREAD

**Issue by bkleef** [Microsoft/vscode-go#829]
It's common to use an `.env` file. We would love to load that file instead of duplicating environment variables.
Looks like it is highly releated to https://github.com/Microsoft/vscode/issues/14523.

Something like this would be awesome!

```
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "envFile": "${workspaceRoot}/.env",
            "args": [],
            "showLog": true
        }
    ]
}
```

**Comment by ramya-rao-a** [comment]
This should be simple enough to do
- Add the new "envFile" property to properties at https://github.com/Microsoft/vscode-go/blob/master/package.json#L226
- Update the `Delve` class at https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L177 to take in the new "envFile" argument and extract the env variables just like it was done for node debug https://github.com/Microsoft/vscode-node-debug/commit/e9ef5be77b66925749797832f15ea44418533d56

PRs are welcome

**Comment by ramya-rao-a** [comment]
PR is merged, this will be out in the next update

**Comment by ramya-rao-a** [comment]
The latest update (0.6.56) to the Go extension has this feature.
