### ISSUE TITLE
Failed to continue: "Cannot find Delve debugger. Ensure it is in your "GOPATH/bin" or "PATH"."

### ISSUE THREAD

**Issue by xdeng** [Microsoft/vscode-go#832]
my go version 1.8 
go env  GOPATH=C:\Users\xdeng\go   and   settings.json  "go.gopath": "C:\\Users\\xdeng\\go"
![20170302205425](https://cloud.githubusercontent.com/assets/2641745/23508009/aa6dc000-ff8a-11e6-8a1a-3446fd1519d4.jpg)

Why the prompt does not exist ???

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#cannot-find-delve-debugger-at--ensure-it-is-in-your-gopathbin-or-path

**Comment by simula67** [comment]
I am facing the same issue. From : 

https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#cannot-find-delve-debugger-at--ensure-it-is-in-your-gopathbin-or-path

Solution: Add the location where dlv is installed to your PATH. You can find this location by running which dlv or where dlv

How do I add dlv to PATH before launching VS Code ?

Cannot find package ".." in any of ...

The debugger is not using the right GOPATH. This shouldnt happen, if it does, log a bug.

Solution: Until the bug you logged is resolved, the work around is to add the GOPATH as an env var in the env property in the launch.json file.

I added this also and I am getting the same exact error


I should probably just use Goland

**Comment by ramya-rao-a** [comment]
> How do I add dlv to PATH before launching VS Code

Updating the PATH environment variable is independent of launching VS Code. Look up how to add environment variables for your specific platform ((Mac/Linux/Window).

> I added this also and I am getting the same exact error

What error do you get? At one point youmention that you are facing the same thing as described in this issue (`Cannot find Delve debugger....`). At another point you are referring to another error `Cannot find package..`. I am not sure which of the 2 issues are you seeing at the moment.

> I should probably just use Goland

You are free to use any tool that makes you productive. If you want to use VS Code, then please describe the exact errors you see and details about your set up

- Platform
- VS Code version and the Go extension version
- Go version
- dlv version
- Is dlv under your GOPATH/bin? Is this GOPATH the same as what you get when you run the command `Go: Current GOPATH`?
- Is the code you are trying to debug under your GOPATH?
- Do you use the setting `go.gopath`? Is this the same as the GOPATH set as environment variable outside of VS Code?
- Do you use the setting `go.inferGopath`?
