### ISSUE TITLE
Add `return` statement into keyboard auto-completion

### ISSUE THREAD

**Issue by fnouama** [Microsoft/vscode-go#835]
vscode: 1.10.1
Go extension: 0.6.54

This is not a bug, but more a request for an improvement.

Since this extension has been, release, I have noticed that the editor never prompt you for the `return` statement in the auto-complete list. It will be handy to have that available. Other editor like JetBrains Gogland already support that.

Thanks.

**Comment by ramya-rao-a** [comment]
Not just `return`, none of the other Go keywords are prompted in the auto-completion.

#558 is tracking this feature request. Please upvote it, I'll  look into getting it into the next update

**Comment by ramya-rao-a** [comment]
The latest update (0.6.56) to the Go extension has this feature.
