### ISSUE TITLE
Comment in import is not highlighted

### ISSUE THREAD

**Issue by vy0b0x** [Microsoft/vscode-go#839]
VSCode version: 1.10.1
vscode-go version: 0.6.55
![1](https://cloud.githubusercontent.com/assets/5011191/23577480/e1a14044-00fa-11e7-98d0-cb03ccf1139e.png)

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#115

**Comment by ramya-rao-a** [comment]
The fix is now available in the latest Insiders build and will be available in the next stable build i.e 1.11.0
