### ISSUE TITLE
Investigate what it would take for the debugger to be aware of GOPATH from settings

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#840]
The debug adapter cannot read the settings. Therefore if go path is set using `go.gopath` or `go.inferGopath` settings then the debug adapter is never aware of the gopath thus set.

It needs user to set the GOPATH again via the debug configurations in the launch.json

**Comment by ramya-rao-a** [comment]
The debug adapter runs in a different process altogether than the extension host and so the usual ways of accessing settings in the extension cannot be used by the debug adapter.

One way to solve the current GOPATH resolving issue when debugging is for the debug adapter to infer the GOPATH based on the path of the file/package it is asked to debug. This is being tracked by the PR #1150

**Comment by ramya-rao-a** [comment]
The GOPATH issue is solved by the debugger figuring out the GOPATH from the path provided in the `program` attribute of the debug configuration. This feature is now out in the latest update to the Go extension 0.6.64

Closing this issue

**Comment by karamana** [comment]
It looks like GOPATH is broken with the latest release (0.6.64). I get the following error message.

go: GOPATH entry is relative; must be absolute path: "undefined".
For more details see: 'go help gopath'
exit status 2
Process exiting with code: 1

Is there a way to use the earlier version of this plugin (0.6.63)?

**Comment by ramya-rao-a** [comment]
For anyone else landing here, @karamana and I are tracking the broken GOPATH issue in https://github.com/Microsoft/vscode-go/issues/1194
