### ISSUE TITLE
When no problems found, `package main` line marked as error which just contains a list of packages

### ISSUE THREAD

**Issue by Southclaws** [Microsoft/vscode-go#841]
- VS Code version: 1.10.0
- Go version: 1.7.5
- VS Code Go extension version: "0.6.55 - 3rd March, 2017"
- OS: Windows 10 64bit

Just updated today and random source files get this when there are no problems found in the project:

![golangbug](https://cloud.githubusercontent.com/assets/1636971/23616523/ea12f71c-0281-11e7-8f57-8792f228edd6.png)

Which, on inspection, is literally just a deep-list of every imported package in my project - output of `go list -f '{{ .Deps }}'` maybe?

- Worked fine earlier this morning, when I was on `v0.6.54`.
- Code compiles fine, this weird error only appears if there are no problems found but instead of `no problems found in workspace` this pops up.
- Tried the `gocode close` mentioned in other issues but this does not work
- Tried deleting, `go get`ing and `go install`ing gocode, still didn't work

Overall, not a huge deal, just a tiny bit irritating not to see that satisfying `no problems found` message :)

**Comment by ramya-rao-a** [comment]
What's in the output pane?

When there is a build error which cannot be mapped to a line in the file, we map it to the first line of the file which in your case happened to be the `package main` line

This change was done a few updates ago.

**Comment by Southclaws** [comment]
The output pane shows the command
```
C:\Go\bin\go.exe build -o C:\Users\Southclaws\AppData\Local\Temp\go-code-check -tags "" -race -v .
```
Which is then followed by the list of files that it has checked, normally when there's an error this output looks like:

```
<go package 1>
<go package 2>
<go package 3>
# <go package 3>
.\my_code.go:23: some error
```

And when there are no problems, it simply looks like:

```
<go package 1>
<go package 2>
<go package 3>
```
With no `#` prefixed lines, seems like the extension is grabbing the entire output and using it as an error message when no `#` prefixed lines are found.

**Comment by ramya-rao-a** [comment]
Ah ha! You have the `-v` flag on which prints the names of the packages as they are compiled.
When `go build` command fails, any output that is of the format `filepath:linenumber: errormessage` gets mapped to the corresponding file and line number

When the output doesnt match this format, it is simply spit out and mapped to the first line of the file.

This was done to show unexpected error messages to the user. See #664

See https://github.com/Microsoft/vscode-go/blob/master/src/goCheck.ts#L79

But this is suppose to happen only when `go build` fails.
Do you see any error message in the output pane at all?

**Comment by Southclaws** [comment]
Ah yes, I do have the `-v` flag and I remember now I did that to debug something else a while ago and assumed it wouldn't affect anything else.

Seems like it's still happening when the build succeeds, checking `$LASTEXITCODE` after running the command in PowerShell returns 0. No errors in the output pane.

**Comment by ramya-rao-a** [comment]
Turns out the verbose output comes in `stderr` which my code deemed as error

Fixed with https://github.com/Microsoft/vscode-go/commit/9b5ea30712c28cf0453207c6755123659cf33d12
