### ISSUE TITLE
dlv not connected properly to vscode interface

### ISSUE THREAD

**Issue by samueletonon** [Microsoft/vscode-go#842]
Hello,
i've been trying to setup dlv on vscode for windows 10 but apparently something is missing as i am not able to launch it by pressing the green arrow and this is the error message i get:

_can't load package: package .: no buildable Go source files in c:\Devel\GO\src
exit status 1
Process exiting with code: 1_

now my GOPATH is c:\GO and my GOROOT=c:\Devel\GO\src 

if i run from the terminal inside vscode:
PS C:\Devel\GO> go install github.com\samueletonon\welcome

i get the binary without problems.

if i launch it from command line i have to do dlv debug github.com\samueletonon\welcome

somehow i suspect the problem is in launch.json

_{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}_

if i change that ${workspaceRoot} in "c:\\Devel\\GO\\src\\${workspaceRoot}"

The program "c:\Devel\GO\src\c:\Devel\GO\src" does not exist: Error: ENOENT: no such file or directory, lstat 'c:\Devel\GO\src\c:\Devel\GO\src'

so i believe that workspaceRoot should be evaluated as the current working directory my source is but somehow it just get GOROOT

is this a bug due to some configuration somewhere? i am using latest vscode (1.10.1) and latest go code (0.6.55) on windows 10.

**Comment by ramya-rao-a** [comment]
`${workspaceRoot}` is getting resolved to `C:\Devel\GO\src` which is the folder you have opened in VS Code.

The `program` attribute in `launch.json` needs to point to the package or file that you want to debug
The default value is `${workspaceRoot}`

Therefore either update the program attribute to `${workspaceRoot}/github.com/samueletonon/welcome` or `C:/Devel/GO/src/github.com/samueletonon/welcome`

OR

open the folder `C:/Devel/GO/src/github.com/samueletonon/welcome` in VS Code and keep the property attribute in launch.json as `${workspaceRoot}`

**Comment by samueletonon** [comment]
> ${workspaceRoot} is getting resolved to C:\Devel\GO\src which is the folder you have opened in VS Code.

and this is the main issue as i may have that folder open to have an overview of the modules i am working on it but at the moment i launch the debug i launch it on a specific file, welcome.go which is in a specific folder while workspaceroot has a different purpose.

I would expect then ${workspaceRoot} being evaluated as the CWD the editor is pointing and looking in the documentation  ( https://code.visualstudio.com/docs/editor/tasks#_variable-substitution )  i found out
${fileDirname} is the one is was looking for

**Comment by ramya-rao-a** [comment]
Yes, that makes sense to have `${fileDirname}` as the default instead of `${workspaceRoot}`.

**Comment by ramya-rao-a** [comment]
The latest update (0.6.56) to the Go extension will use `${fileDirname}` as the default instead of `${workspaceRoot}`.
