### ISSUE TITLE
ability to notify what vscode-go is doing

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode-go#844]
for example, vscode-go has a config `buildOnSave`, when user saves a file, vscode-go starts lint and compile works. I'd like vscode-go tell me :

linting started
linting finished
compiling started
compiling finished

**Comment by ramya-rao-a** [comment]
Where would you like to see these notifications?
Currently they do get printed out to the output window

**Comment by bruceauyeung** [comment]
I know lint and compile events are printed in output view, but sometimes i forget to select `Go` from the select options, maybe we should set `Go` as default when Go project is detected.

**Comment by ramya-rao-a** [comment]
Hmm.. I was very sure that the output pane opens up showing the right channel...
But that doesn't seem to happen anymore.

Will take a look.
