### ISSUE TITLE
make finding all references more user-friendly

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode-go#845]
`Finding all references` will popup a window to show all references, i think it's a little hard to use, i am not blaming vscode-go, maybe it's vscode's limitation because vscode don't provide a view similar with output, problem etc.
1. once user close the popped-up window, referencing results is lost. user have to find all references again if they just closed the window by accident. most other IDEs such as Eclipse, Gogland, they display references in a view , the referencing results will not be lost until user do finding all references again.
2. user may close the window by accident very easily.  currently the window have a close button, a window bar, if user single-click the left part of menu bar or drag the window  on left part of menu bar( mouse pointer becomes to a finger when hovering on it, this indicates user can do something ), window will be closed.

so i suggest:

1, if it's possible, display references in a view similar with problem etc, not in a popup window. if not, 
2, do not close window when left part of menu bar is clicked or dragged, only close window when close button is close or content part of window is double-clicked.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#22261
