### ISSUE TITLE
Open the test file after test cases are generated

### ISSUE THREAD

**Issue by rakyll** [Microsoft/vscode-go#848]
Steps to produce:

1. Cmd+Shift+P
2. Run "Generate unit tests for the current function"

Actual result: gotests generate the tests and a notification is shown in the popup dialog.

Expected result: VS Code opens the test file and skips to the test.

**Comment by ramya-rao-a** [comment]
Which version of the Go extension are you using?
since the version 0.6.48 (https://github.com/Microsoft/vscode-go/wiki/Release-Notes#0648---9th-november-2016) we do open the the test file after the test generation.

If there were no tests generated, then there is no navigation

**Comment by ramya-rao-a** [comment]
@rakyll closing this issue as we havent heard back from you in a while.

The test file does open once test cases are generated.
