### ISSUE TITLE
BoltDB package not parsed

### ISSUE THREAD

**Issue by hinst** [Microsoft/vscode-go#851]
Steps to reproduce:

- Add BoltDB package to project
- Declare local-var or field of type bolt.DB or bolt.Tx
- set text cursor to bolt.T|x, press Go-To (F12)
- VS Code says "**No definition found**". Expected result: source is opened
- mouse over var identifier
- for a short time, "Loading" hint appears
- **empty hint** appears. Expected result: hint with var type appears "bolt.DB"

![no-definition](https://cloud.githubusercontent.com/assets/958706/23749164/f08ab348-04d7-11e7-80b4-4a1c554380b0.png)
---
![no-hint](https://cloud.githubusercontent.com/assets/958706/23749165/f08c38ee-04d7-11e7-95c5-5e724571df94.png)

**Comment by ramya-rao-a** [comment]
@hinst Sorry for the late response, does the `Go to definition` feature work for other packages and the issue is only with this particular package?

Can you share your settings for `go.docsTool` and `go.useLanguageServer` ?

**Comment by hinst** [comment]
Go-to-definition works fine for other packages from my workspace.

Global settings:
```
  "go.docsTool": "godoc",
  "go.useLanguageServer": false,
```

Workspace settings.json:
```
{
    "go.buildOnSave": true,
    "go.lintOnSave": false,
    "go.vetOnSave": true,
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "search.exclude": {
        "**/.hg": true
    },
    "editor.tabSize": 4,
    "editor.detectIndentation": true
}
```

User settings.json:
```
// Place your settings in this file to overwrite the default settings
{
	"editor.fontSize": 13,
	"editor.insertSpaces": false,
	"editor.autoClosingBrackets": false,
	"editor.renderWhitespace": "all",
	"editor.lineNumbers": "off",
	"editor.wordWrap": true,
	"workbench.editor.showIcons": true,
	"window.menuBarVisibility": "toggle",
	"window.zoomLevel": 0,
	"workbench.colorTheme": "Default Light+",
	"workbench.iconTheme": "vs-seti"
}
```

**Comment by ramya-rao-a** [comment]
Can you try changing `go.docsTool` to `gogetdoc`?
There are certain scenarios where the default option does not work because of which we introduced the option to use `gogetdoc`.

If that still does not work, I'll try to get a repro and debug the extension

**Comment by hinst** [comment]
I changed go.docsTool setting to gogetdoc, and now it works

**Comment by ramya-rao-a** [comment]
Great, thanks!
