### ISSUE TITLE
Language Server stops working after a while

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#853]
See https://github.com/Microsoft/vscode-go/issues/702#issuecomment-285549110

The features powered by the language server (go to def, find refs etc.) stop working after some period of time after setting `go.useLanguageServer` to `true`

**Comment by ramya-rao-a** [comment]
@josh-tepper The next time this happens, can you check if there is a process called "go-langserver" running? 

@mattetti @zmb3 @junkblocker I know you have tried the language server as well. Have you seen any issues like this one?

cc @sqs @keegancsmith

**Comment by keegancsmith** [comment]
We haven't seen any issues like this in production. However, the server can occasionally OOM in production (but that is usually when several large repos end up on the same machine).

**Comment by josh-tepper** [comment]
Ok -- this happened again.  This time, it was accompanied by vscode becoming slow as well.
go-langserver was running, but it was spiking the cpu:

$ ps -O %mem,%cpu,rss 32815
  PID %MEM  %CPU    RSS   TT  STAT      TIME COMMAND
32815  5.3 189.0 892168   ??  R     82:25.01 /Users/joshtepper/work/clarifai/go/bin/go-langserver -mode=stdio

Had to restart vscode which became laggy even when typing

**Comment by josh-tepper** [comment]
Since the last comment, I restarted, and now seeing the same thing again -- even larger cpu number:
```
$ ps -O %cpu,%mem 71085
  PID  %CPU %MEM   TT  STAT      TIME COMMAND
71085 326.7 10.2   ??  R     28:57.74 /Users/joshtepper/work/clarifai/go/bin/go-langserver -mode=stdio
```

**Comment by mattetti** [comment]
I am seeing issues too. VSCode gets really slow to recover type information. It looks like I have 2 processes running which might be due to the fact that I have 2 projects open.

<img width="642" alt="activity_monitor__all_processes_" src="https://cloud.githubusercontent.com/assets/113/23828094/40e90480-067b-11e7-9537-957c8d2bfe8a.png">

**Comment by ramya-rao-a** [comment]
@mattetti Yes, as per current design, a new language server gets spawned for each VS Code window that is open

**Comment by keegancsmith** [comment]
I'm used to dealing with servers which I can poke and prod to debug this sort of thing, so hard to know what is going on here. Here is a dump of how to understand what is going on:

* We support logging to a file, these logs are likely a good first step to understand what is taking a long time to run.
* We support sending opentracing spans over the `telemetry/event` to vscode. Not sure if vscode does anything with this.
* We also support running a pprof http endpoint so you can get some mem/cpu/goroutine/etc dumps. It also has prometheus stats which probably won't be that useful in this case.
* I can add a signal handler to dump information to stderr.

@ramya-rao-a how can people run go-langserver with the `-trace` and possible the `-logfile` flag? Also if I make our log handler send `window/logMessage` would this make our life easier?

**Comment by ramya-rao-a** [comment]
@keegancsmith Currently, users cannot run the the language server with the flags you mentioned, but I can add the provision for the same and release an update in a couple of days.

Since you have a repro for the issue now, you can use your local dev environment for the extension.

I am not sure what happens to the `telemetry/event`. Looking into it.

**Comment by keegancsmith** [comment]
Thanks. We believe the root of this issue is our poor use of RAM for editor environments. We have this issue in the go-langserver repo to track https://github.com/sourcegraph/go-langserver/issues/178

**Comment by josh-tepper** [comment]
@keegancsmith -- take a look at the numbers from my process table above.  They are not consistent with the high memory reports in the issue you linked.  On there was very high cpu usage.  This was on a machine with 16GB of memory.  I'll try to get some better statistics about page faults/memory usage/cpu/maybe an strace/etc the next time this happens.

**Comment by josh-tepper** [comment]
Any progress on this?  I just wanted to check that this is not blocked on more reports from me.  If so, I apologize for the confusion!  I'm not currently running the langserver because it wasn't usable, but I can switch back if you need more statistics.  Let me know!

**Comment by ramya-rao-a** [comment]
Thanks for circling back @josh-tepper 

@keegancsmith I'll be enabling the use of `-trace` and `-logfile` flags in the next update. Do you need any more info from the users?

**Comment by ramya-rao-a** [comment]
In the latest update to the Go extension (0.6.56), there will be a new setting `go.languageServerFlags` that will be passed while running the Go language server. 

- Users can set this to `["trace"]` to see the traces from the language server in the output pane under the channel "go-langserver"
- Users can set this to `["trace", "logfile", "path to a text file to log the trace]` to log the traces and errors from the language server to a file.

cc @keegancsmith

**Comment by mattetti** [comment]
Thanks, I turned on trace and see a weird issue:

```
[Error - 8:27:47 PM] Request textDocument/hover failed.
  Message: invalid location: /Users/mattetti/Code/golang/src/<>foo.go:#1508
  Code: 0 
[Error - 8:27:51 PM] Request textDocument/hover failed.
  Message: invalid location: /Users/mattetti/Code/golang/src/<>foo.go:#1530
  Code: 0 
[Error - 8:27:52 PM] Request textDocument/hover failed.
  Message: invalid location: /Users/mattetti/Code/golang/src/<>foo.go:#1531
  Code: 0 
[Error - 8:27:53 PM] Request textDocument/definition failed.
  Message: invalid location: /Users/mattetti/Code/golang/src/<>foo.go:#1531
  Code: 0 
```

The actual path was edited for privacy reason, but the file it's trying to access only has 87 LOC. So something is really going wrong. Is there anything else I can do to help debugging?

**Comment by ramya-rao-a** [comment]
That most probably is the offset not file number

**Comment by josh-tepper** [comment]
Unfortunately, while I saw the high cpu situation again, I'm not seeing any logs from go-langserver.  I basically see a blank golangserver channel when I look at the output in vscode:

![screen shot 2017-03-31 at 3 30 16 pm](https://cloud.githubusercontent.com/assets/20231989/24566459/935a8138-1627-11e7-9301-1dac46191d7b.png)

And the output file that I specified is 0 bytes long.  Looking at the go-langserver command from the process table, I can see that it's not being started with --trace or --logfile (though, note the very high CPU!):
```
$ ps -O %cpu,%mem 48762
  PID  %CPU %MEM   TT  STAT      TIME COMMAND
48762 335.3  7.1   ??  R     19:42.34 /Users/joshtepper/work/clarifai/go/bin/go-langserver -mode=stdio
```
Here are the `go.` settings that I've specified:
```
    "go.docsTool": "gogetdoc",
    "go.formatOnSave": false,
    // because gogetdoc is slow and godoc is broken, use the experimental language server
    // from sourcegraph instead; but this actually causes issues as well
    "go.useLanguageServer": true,
    "go.formatFlags": ["trace", "logfile", "/Users/joshtepper/project/golang_log.txt"],
```
I do specify `go.docsTool`, but the `go.userLangaugeServer` overrides it (it's just there because that's what I revert to; I've commented it out, and still no logs).

**Comment by ramya-rao-a** [comment]
@josh-tepper You have set the trace and logfile flags for `"go.formatFlags"` instead of `"go.languageServerFlags"` :)

**Comment by josh-tepper** [comment]
I apologize for the delay -- I've been away and should have noted that here.

I've grabbed a few examples of the logs from the high cpu situation.  Unfortunately, I didn't realize how much actually code and code structure is included in the logs, and the consensus here is that we're not comfortable sharing it.  This is a closed source project

@keegancsmith -- is there a way that I can do analysis of the process?  Is there another flag that I can pass that will dump less of this code/structure to the logs?

**Comment by keegancsmith** [comment]
@josh-tepper we are aware of a few issues when using the go-langserver on a normal dev machine vs production at sourcegraph.com. We will be prioritising time soon to address them. At this point I don't think you need to gather any data for us. Rather when we have addressed the issues I'd love for you to retry the langserver. Thanks for your patience thus far.

**Comment by cyc115** [comment]
Thanks for the development of the go plugin! 

I also have this problem and is getting very annoying (it would hog the cpu every two minutes or so if I use the "peek / goto definition" feature. 
To solve this I used a script to check process name and cpu usage and kill the process with process name matching `go-langserver` every 2 second if cpu usage exceeds 95%.

**Comment by ramya-rao-a** [comment]
@cyc115 I'd suggest to disable the language server and try again after @keegancsmith and his team have addressed the issues

**Comment by nicpottier** [comment]
Just adding a quick note here that I'm facing the some problems and had to disable the lang-server to make vs-code workable again on a go repo.

**Comment by josh-tepper** [comment]
Just wondering if there's any update on this.  Is there build that we should test?  @keegancsmith

**Comment by ramya-rao-a** [comment]
@keegancsmith is no longer working on this as far as I know.
pinging @slimsag instead

**Comment by sqs** [comment]
Indeed - @slimsag is working on this now (@keegancsmith is on parental leave for a few more weeks 🎊)

**Comment by slimsag** [comment]
I'll have an updated build for people to try soon -- apologies for the delay. :)

In the meantime, if anyone would like to help out, please make sure your binary is updated (run `go get -u github.com/sourcegraph/go-langserver`) and capture a heap/CPU profile per https://github.com/sourcegraph/go-langserver#profiling whenever the issue occurs.

**Comment by slimsag** [comment]
Hi everyone ( /cc @ramya-rao-a ), this issue should be fixed now. 😃 Very significant improvements have been made to both goto definition and hover requests, and they now use a tiny fraction of the memory / CPU usage seen before.

To update, please run:

```
go get -u github.com/sourcegraph/go-langserver
```

And once again set `go.useLanguageServer` to `true` inside your settings to enable the language server.

Please feel free to provide any feedback here, and if all looks good we can close this issue out!

**Comment by josh-tepper** [comment]
This appears to completely solve the problem for me.

**Comment by ramya-rao-a** [comment]
Thanks @slimsag for the amazing work!

@josh-tepper Thanks for confirming
@nicpottier @cyc115 Can you get the latest for the language server `go get -u github.com/sourcegraph/go-langserver`, turn the setting back on and see if it works well for you too?

**Comment by slimsag** [comment]
@ramya-rao-a What do you think of closing this issue now (and folks can open new issues if they run into any problems)? 😄

**Comment by ramya-rao-a** [comment]
Agreed :)
