### ISSUE TITLE
Go to definition don't work when doing "dot" import

### ISSUE THREAD

**Issue by charlires** [Microsoft/vscode-go#856]
When using dot import, go to definition of a function doesn't work

e.i.
```
import "github.com/user/pkg"
pkg.Foo() // Works
```

```
import . "github.com/user/pkg"
Foo() // Fails
```

Hope this is enough explanation, I'll add more if needed.

**Comment by ramya-rao-a** [comment]
Please see #496 which is tracking the exact same issue

**Comment by ramya-rao-a** [comment]
By default, `godef` is used by the Go extension to provide Go to Definition feature which doesn't work with dot imports.

Add to your settings `"go.docsTool": "gogetdoc"` to use `gogetdoc` instead or `"go.useLanguageServer": true`  to use the new experimental language server feature

**Comment by charlires** [comment]
Thank you @ramya-rao-a

**Comment by paulcalcraft** [comment]
Thanks @ramya-rao-a,  "go.docsTool": "gogetdoc" works great after I installed gogetdoc by running:
`go get github.com/zmb3/gogetdoc`

Go to definition was failing silently with this setting before I realised I needed to manually install gogetdoc.

**Comment by ramya-rao-a** [comment]
@paulcalcraft Yes, I noticed the failing silently part recently and fixed with https://github.com/Microsoft/vscode-go/commit/2e56371fb799c6847d774cec8c761f21b8b980c2

Will be releasing an update soon

**Comment by unix2dos** [comment]
@ramya-rao-a   in 1.92 mac ,Go to definition was failing silently. Where did I go wrong? Thanks

**Comment by ramya-rao-a** [comment]
@unix2dos Are you seeing the Go to definition feature failing only for dot imports or for all cases?

**Comment by unix2dos** [comment]
@ramya-rao-a  Go to definition feature failing only for dot imports. other cases are ok.  
my config and install them all
```
    "go.useLanguageServer": true,
    "go.docsTool": "gogetdoc",
```

**Comment by ramya-rao-a** [comment]
@unix2dos You are using the language server which doesnt give the definition for dot imports. I have logged https://github.com/sourcegraph/go-langserver/issues/227
