### ISSUE TITLE
Lint Flags are not working properly

### ISSUE THREAD

**Issue by Oxyrus** [Microsoft/vscode-go#857]
I'm trying to use `gometalinter`, which I do in my settings:

*Settings omitted for brevity*
```json
{
  "go.lintTool": "gometalinter"
}
```

However, when I run the linter I get the following errors:

> Error while running tool: D:\Andres\Go\bin\gometalinter.exe
WARNING: deadline exceeded by linter structcheck on . (try increasing --deadline)
WARNING: deadline exceeded by linter varcheck on . (try increasing --deadline)
WARNING: deadline exceeded by linter vet on . (try increasing --deadline)
WARNING: deadline exceeded by linter unconvert on . (try increasing --deadline)
WARNING: deadline exceeded by linter vetshadow on . (try increasing --deadline)

I'm trying to add the flag like this: `"go.lintFlags": ["--deadline 2s"],` but it doesn't work:

> Error while running tool: D:\Andres\Go\bin\gometalinter.exe --deadline 2s
gometalinter.exe: error: unknown long flag '--deadline 2s', try --help

However, I can run gometalinter with exact same flag `gometalinter.exe --deadline 2s` from the terminal

If I omit the seconds `2s` (`"go.lintFlags": ["--deadline"]`) I get the following:

> Error while running tool: D:\Andres\Go\bin\gometalinter.exe --deadline
gometalinter.exe: error: expected argument for flag '--deadline', try --help

Why is it not using the 2s properly? or how should I configure it then?

**Comment by ramya-rao-a** [comment]
I can repro this. Will look into it.

**Comment by gobijan** [comment]
Just came here to confirm. I have the same bug.
Running in a simple project shows linting. Running in a more complex project (lots of go files etc) it throws:
Error while running tool: /Users/bijan/go/bin/gometalinter
WARNING: deadline exceeded by linter errcheck on . (try increasing --deadline)
WARNING: deadline exceeded by linter structcheck on . (try increasing --deadline)

Runs fine on the terminal so I guess the --deadline flag is too strict in the default settings.

**Comment by ramya-rao-a** [comment]
Found it!

You need to set it as `"go.lintFlags": ["--deadline", "2s"]`

While spawning a new process to run the linting tool, the arguments are passed as an array object
See https://github.com/Microsoft/vscode-go/blob/d8c8cf1d56ea669e4e844e4f09d9211c9d99b43f/src/goCheck.ts#L51
