### ISSUE TITLE
Replace vscode-debug-logger dep with LoggingSession from vscode-debugadapter

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-go#858]
I should do this at some point, as the stuff from vscode-debug-logger has been moved into the official vscode-debugadapter lib.

**Comment by ramya-rao-a** [comment]
@roblourens We moved to using `LoggingDebugSession`. A few questions:

- It provides a lot more details, any way of controlling it?
- The colors are gone :( Anyway to colorize the output?

Before:

![image](https://user-images.githubusercontent.com/16890566/50568220-d9b39a00-0d03-11e9-923a-f6bd2276f902.png)


After:

![image](https://user-images.githubusercontent.com/16890566/50568257-17182780-0d04-11e9-8e06-1633193e508c.png)

**Comment by roblourens** [comment]
It also logs traffic to and from the debug adapter. If you don't want to see it, those messages are "Verbose", so you could use a higher log level for your own messages, then set the log level to exclude Verbose messages.

Errors are red, warnings are yellow, everything else is the default color. If you really want to, you should be able to wrap your log messages in color escape codes (https://www.npmjs.com/package/color) and those should be applied to the console.

**Comment by ramya-rao-a** [comment]
Thanks @roblourens 

Another question:

The `LoggingDebugSession` doesnt seem to be writing the logs to a file.
Note the missing "Verbose logs are written to:" in the after picture above.

**Comment by ramya-rao-a** [comment]
Thanks @roblourens 

Pushed a change to update the `trace` attribute to take one of 3 values
- **verbose**: logs traffic between vscode and the debug adapter + anything logged by the debug adapter itself. Logs to file as well
- **log**: shows only logs by the debug adapter (corresponds to the older "verbose"). Logs to file as well
- **error**: shows only errors (corresponds to the older scenario where `trace` was not set to anything by the user)

The previous option to have verbose logs logged to file but not shown in the debug console is deprecated as we havent seen that being used as much as showing the verbose logs in the debug console + file logging.

@brycekahle, @segevfiner,
Can you try out the newer log levels above and share any feedback you have?

**Comment by ramya-rao-a** [comment]
Turns out the older `vscode-debug-logger` was using the category `console` which logged everything as a yellow warning.

But `vscode-debugadapter` only logs things meant as warning to use the category `console` and so our color went away.

See https://github.com/Microsoft/vscode-go/commit/105de16280ecead758a85415aace03ca9b6ec763#r31811317 (Thanks @segevfiner!)

To get around this, I'll be logging things from the debug adapter using `log.warn` to keep things consistent as before i.e yellow.

This is important to differentiate the logs when in the new "verbose" mode
