### ISSUE TITLE
debug binary not removed after debugging

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#86]
I noticed there's a binary named `debug` where I executed `code .` from, that probably should go to /tmp or $GOPATH/bin, not inside my working source directory. 

Also it's not getting removed. I had to delete it manually.

**Comment by lukehoban** [comment]
This binary is generated by Delve.  But if Delve shuts down cleanly it gets removed on shutdown.  It looks like we aren't correctly shutting down the debug session with Delve.

**Comment by ahmetalpbalkan** [comment]
Yeah I can repro 100%. I'm not shutting down vscode, I am just stopping debugging and `debug` is still there.

**Comment by lukehoban** [comment]
Yep - it's expected that this is currently 100% reproable.  There's a missing call to Delve's `Detach` when the Code debugger detaches/stops debugging.

**Comment by lukehoban** [comment]
Turns out this is an issue in Delve on Windows, being tracked here: https://github.com/derekparker/delve/issues/398.

**Comment by Term1nal** [comment]
Having this issue on Ubuntu.
