### ISSUE TITLE
Rename identifier no longer works

### ISSUE THREAD

**Issue by rogeralsing** [Microsoft/vscode-go#861]
I'm not sure if this is a change in the vscode-go plugin, go-tooling or vscode itself.
But since some week back, I can no longer use "Rename" on identifiers.
Doing so results in the normal scanning of files to find errors etc. but ends in a "file not found" for all files that were supposed to be changed.

**Comment by rogeralsing** [comment]
![renameerror](https://cloud.githubusercontent.com/assets/647031/23832650/56b37afc-0739-11e7-8b35-036f7f0cf73d.png)

**Comment by ramya-rao-a** [comment]
Looks like this is same as #665
