### ISSUE TITLE
Either `testOnSave` or `testFlags` should support method at current cursor

### ISSUE THREAD

**Issue by francoishill** [Microsoft/vscode-go#862]
There is already a "Test at Cursor" action. It would be nice if this was possible to specify to run with `testOnSave`. Or perhaps a `testFlags` variable that could be interpreted as "methodName at cursor" which could be passed in to `go test` as arguments `-run ^TestMyMethod$`.

**Comment by ramya-rao-a** [comment]
That's interesting and a great point. Why run all the tests in the package when you are changing just 1?

I might not get to this in the next week or so, therefore PRs are welcome :)

**Comment by dmage** [comment]
Even if we assume that the user keep the cursor on a changed test, it doesn't mean that nothing else is changed (init function, global variables, other test functions, etc.). So it cannot be the default behavior.

**Comment by ramya-rao-a** [comment]
@dmage Agreed, we can have the `testOnSave` setting accept values like 

`"go.testOnSave": true`
`"go.testOnSave": false`
`"go.testOnSave": { "scope": "cursor" }`
`"go.testOnSave": { "scope": "file" }`
`"go.testOnSave": { "scope": "package" }`

OR

`"go.testOnSave": true`
`"go.testOnSave": false`
`"go.testOnSave": "cursor"`
`"go.testOnSave": "file" `
`"go.testOnSave": "package" `

**Comment by dmage** [comment]
```
"go.testOnSave": {
  "test_function": "cursor" || "file" || "package" || false,
  "test_file": "file" || "package" || false,
  "other_file": "package" || false,
}
```

Someone may want to enable testonsave only if the cursor located in a test function, others may want to have the graceful fallback (if cursor not in function, but in a _test.go file, then test the file; otherwise test the whole package).

"cursor" may be a shorthand for `{"test_function": "cursor", "test_file": "file", "other_file": "package"}`
"package" = `{"test_function": "package", "test_file": "package", "other_file": "package"}`
true = "package"

But it feels a bit complicated.

**Comment by ramya-rao-a** [comment]
@dmage Yes that indeed gets complicated :)

I am not in favor of the fallback. We don't do that today when running the `Go: Test at cursor` command or `Go: Test File`. I'd prefer to keep the behavior in `testOnSave` similar to the options in `Go: Test cursor/file/package` command to keep consistency.

**Comment by ironcladlou** [comment]
I don't have much to add here at the moment. I don't use test-on-save, and make use of the "run last test" (and other commands) to re-execute a specific test scope after changes. So far that workflow feels adequate to me, and I'm not sure additional test-on-save features offer an improvement.

**Comment by ramya-rao-a** [comment]
We now have the `Run tests` and the `Debug Tests` codelens showing up above each test function. 
We have the "Run package tests" and "Run file tests" codelens showing up above the package statement of a Go file.

It is easier than ever to run a single test/ tests in the file/ tests in the package.

I dont see much of an ROI in updating the test on save feature at the moment.
So closing this issue for now.

If any one landing here has any other thoughts, please do share and we can go over them
