### ISSUE TITLE
Go to symbol dont work on test file when using language server

### ISSUE THREAD

**Issue by charlires** [Microsoft/vscode-go#871]
VS Code Version: 1.12.0
Go Extension: 0.6.60

I don't know is this meant to be like this but, goToSymbol don't show anything on golang test files.

**Comment by ramya-rao-a** [comment]
`Ctrl+Shift+o` which opens the File symbols works in the test file for me

![image](https://cloud.githubusercontent.com/assets/16890566/24023253/35a379fc-0a68-11e7-97dd-dd351e1567ee.png)


Are you referring to the same feature or something else?

**Comment by charlires** [comment]
Yes, is not working for me
![image](https://cloud.githubusercontent.com/assets/1058646/24023286/e853a380-0a70-11e7-9746-56dc3848f22c.png)

**Comment by ramya-rao-a** [comment]
Are you trying out the new language server feature? As in do you have `"go.useLanguageServer":true` in your settings?

**Comment by charlires** [comment]
Yes, I have `useLanguageServer` as `true` and Yes, that is causing the goToSymbol to not show the tests.

**Comment by ramya-rao-a** [comment]
cc @keegancsmith

**Comment by keegancsmith** [comment]
Apologies for the radio silence. @charlires can you give an example test file (or link to it if it is OSS).

**Comment by charlires** [comment]
Sorry for the late response, It happens to me with any test file, curious thing is that is works with any no-test file.

<img width="796" alt="screen shot 2017-05-04 at 4 04 08 pm" src="https://cloud.githubusercontent.com/assets/1058646/25724954/6b4aa020-30e3-11e7-9546-f5019b4bd167.png">
<img width="925" alt="screen shot 2017-05-04 at 4 04 23 pm" src="https://cloud.githubusercontent.com/assets/1058646/25724955/6c41b9b4-30e3-11e7-8e5f-55ac525ec169.png">
is

**Comment by charlires** [comment]
Here is my settings.json
`{
    "editor.fontFamily": "Fira Code",
    "editor.fontSize": 14,
    "editor.lineNumbers": "relative",
    "editor.fontLigatures": true,
    "editor.minimap.enabled": true,
    "editor.minimap.renderCharacters": false,
    "extensions.autoUpdate": true,
    "workbench.colorTheme": "Northem Dark",
    "workbench.activityBar.visible": false,
    "workbench.statusBar.visible": true,
    // "go.useLanguageServer": true,
    "go.docsTool": "gogetdoc",
    "search.exclude": {
        // JS
        "**/node_modules": true,
        "**/bower_components": true,
        // Go 
        "**/pkg": true,
        "**/bin": true,
        "**/src/*/vendor": true,
        // Valhala
        "**/docs": true,
        "**/mjolnir_data": true,
        "**/cache": true,
        "**/fixtures": true,
        "**/js": true
    },
    "terminal.integrated.fontSize": 14,
    "workbench.welcome.enabled": true,
    "workbench.colorCustomizations": {
        "statusBar.background": "#222222"
    },
    "window.zoomLevel": -1,
    "terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.external.osxExec": "iTerm.app",
    "editor.folding": true,
    "window.title": "${rootName}${separator}${activeEditorMedium}",
    "vim.autoindent": false,
    "vim.useSystemClipboard": true,
    "vim.leader": ",",
    "editor.formatOnSave": true,
    "[go]": {
        "editor.formatOnSave": false
    },
    "[ruby]": {
        "editor.formatOnSave": false
    },
    "[cpp]": {
        "editor.quickSuggestions": false
    },
    "[c]": {
        "editor.quickSuggestions": false
    }
}`

**Comment by keegancsmith** [comment]
Aah ok thanks. It seems to only happen with xtest packages (ie your package has `_test` suffix). I'll fix it. Thanks for the response.

**Comment by keegancsmith** [comment]
On fixing the bug, I noticed that documentSymbol had a few other corner cases (wouldn't work on main pkg either). It should work much better now.

**Comment by ramya-rao-a** [comment]
@charlires Can you get the latest from the language server (`go get -u github.com/sourcegraph/go-langserver`) and confirm if this is fixed for you?

**Comment by charlires** [comment]
@keegancsmith @ramya-rao-a Sorry for the late response, it's working now.

**Comment by ramya-rao-a** [comment]
Neat. Closing this issue then. Happy Coding!
