### ISSUE TITLE
Does not highlight comments in `import` section

### ISSUE THREAD

**Issue by mprobst** [Microsoft/vscode-go#872]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|tslint|eg2|0.8.1|
|Go|lukehoban|0.6.55|
|debugger-for-chrome|msjsdiag|2.6.0|
|java|redhat|0.0.11|
|clang-format|xaver|1.2.1|
|vscode-proto3|zxh404|0.1.0|;

---

Steps to Reproduce:

1. Add comments to the `import` section of a Go file

        import (
            "foo" // hello world
        )

2. Observe the comment is not highlighted

![vscode-go-comment](https://cloud.githubusercontent.com/assets/7208/24033845/2af466d8-0aef-11e7-80b6-18ce76fa5458.png)

**Comment by ramya-rao-a** [comment]
This was fixed in the atom grammar https://github.com/atom/language-go/issues/102
Will use this current issue to track absorbing the fix into VS Code

**Comment by ramya-rao-a** [comment]
The fix will be available in the VS Code Insiders tomorrow.
And also in the next release of VS Code 1.11.0

**Comment by mprobst** [comment]
Thanks @ramya-rao-a !
