### ISSUE TITLE
Default goroot/gopath ignored by vscode-go

### ISSUE THREAD

**Issue by concatime** [Microsoft/vscode-go#873]
Hi.
<code>Cannot find "go" binary. Update PATH or GOROOT appropriately</code>
<code>Set GOPATH environment variable and restart VS Code or set GOPATH in Workspace settings</code>

It seems that this extension does not search for default `goroot` and `gopath` in Windows. In fact, by default, the `goroot` is set to `c:/go` and `%userprofile%/go` and this extension should search automatically search for go in `c:/go` without adding custom `goroot` or add go to path. Moreover, it should consider that `gopath` is, by default, and if not overridden by local settings or environment variables, equal to `%userprofile%/go` .

<code>C:\go\bin>go env</code>
><code>set GOPATH=C:\Users\USERNAME\go</code>
<code>set GOROOT=c:\go</code>

Thank you.

**Comment by ramya-rao-a** [comment]
Good point. 

Fix will be out in the next update.
Thanks for reporting!

**Comment by concatime** [comment]
Wow! Thank you for this answer! One point, I don't tell you to define GOROOT or GOPATH, but just let them blank if go is located in C:\go.

**Comment by ramya-rao-a** [comment]
well, I do need to set GOPATH and GOROOT somehwere because all the logic to find the binaries depend on it.

See https://github.com/Microsoft/vscode-go/blob/master/src/goPath.ts

Also the command, `Go: Current GOPATH` depends on it.

And since `process.env['GOPATH']` needs to anyway store the overridden GOPATH, we chose to store the defaults in the same place instead of a separate variables

**Comment by ramya-rao-a** [comment]
The previous fix depends on `go env` which cannot be run if the extension doesnt know GOROOT in the first place.

Right fix: https://github.com/Microsoft/vscode-go/commit/0915e50a1ada5c74742d9c4ce7f265b5e273ca31

**Comment by ramya-rao-a** [comment]
The latest update (0.6.56) to the Go extension has the fix to this issue.

**Comment by majimboo** [comment]
I currently have the same issue in Mac.

**Comment by ramya-rao-a** [comment]
@majimboo Please elaborate. Do you have issues with the goroot to gopath?
Share the below details
- Have you set any of these settings: `go.gopath`, `go.goroot` and `go.inferGopath` 
- Run `echo $GOPATH` in the integrated terminal inside VS Code and a separate terminal outside VS Code. Are the results the same?
- Run `go env GOPATH` in the integrated terminal inside VS Code and a separate terminal outside VS Code. Are the results the same? Does this match with the earlier results from `echo $GOPATH`?
- What is the version of Go you are using?

**Comment by waskito** [comment]
Have the same issue in Mac

I didn't set any of `go.gopath`, `go.goroot` and `go.inferGopath`

when I run `go env $GOPATH`, there is no result at all
but when run `go env`, I am getting `GOPATH="/Users/macintosh/go"`

`GOROOT="/usr/local/Cellar/go/1.9.2/libexec"` because I install go using `Homebrew`

**Comment by concatime** [comment]
Actually, it's `go env GOPATH`, there is no `$`.

**Comment by concatime** [comment]
And second, you need to define your GOROOT variable inside your shell, or set the `go.gopath` because your golang directory is not `/usr/local/go`.
> You are a Linux, FreeBSD or OS X user using the the zip or tarball binary downloads from the golang.org website. These binaries have a $GOROOT value of /usr/local/go and recommend you unpack them into that location. If you choose not to do this, then you must set $GOROOT to the location you chose.
[Source](//dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really).
