### ISSUE TITLE
"Go: Install tools" should install delve

### ISSUE THREAD

**Issue by dolmen** [Microsoft/vscode-go#874]
`delve` is needed to use the debugger. But the command "Go: Install tools" does not yet install it.

**Comment by ramya-rao-a** [comment]
That's because in Mac its an easy `go get` to install delve.
See https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md

On the other hand, it is a valid argument that `Go: Install Tools` should install delve in Windows and Linux.

**Comment by dolmen** [comment]
Homebrew does not install the same version as `go get -u`.

**Comment by ramya-rao-a** [comment]
@dolmen can you elaborate your concern?

**Comment by dolmen** [comment]
Well, I'm not an OS X user, so `go get -u` is really fine and I don't know much about Homebrew.
But Go developers on OS X may be interested in having the latest Delve features. Installing Go tools is so easy with `go get` that everyone deserve it!

**Comment by ramya-rao-a** [comment]
Yes, I agree, but that's how the delve needs to be set up in Mac as per instructions from the owner's of delve. So, nothing much can be done from our side.

**Comment by dolmen** [comment]
Oh, [you're right](/derekparker/delve/blob/master/Documentation/installation/osx/install.md): build of Delve on OS X is not as easy as for any other Go app.

**Comment by ramya-rao-a** [comment]
Fix is out in the latest update (0.6.56) to the Go extension
