### ISSUE TITLE
Editing tools should be available even if the build tags don't match

### ISSUE THREAD

**Issue by rakyll** [Microsoft/vscode-go#877]
VSCode Go extension fails to run editing tools (such as gofmt) if the source file has a non-default build context.

Consider the following file:

```
cat main.go
// +build h2demo

package main

func main() {
fmt.Println("hello")
           }
```

VSCode is not going to gofmt and fix the file on save because the file is under the h2demo tag. The same problem exists for the availability of the other editing tools such as golint.

VSCode Go should be able to provide editing tools regardless of the build tags.

**Comment by rakyll** [comment]
Duplicate of https://github.com/Microsoft/vscode-go/issues/741.

**Comment by ramya-rao-a** [comment]
Regarding the formatting, turns out `gofmt` and `goimports` as formatting tool of choice (which you can set in `go.formatTool` setting) works just fine in the above example.

But when using `goreturns`, the formatting tool fails with the error "no buildable Go source files in ..."
