### ISSUE TITLE
Create launch configuration from selected Test function

### ISSUE THREAD

**Issue by dolmen** [Microsoft/vscode-go#879]
In files named `*_test.go` a right click on a function named `Test*` with signature `func (t *testing.T)` would show a menu entry allowing to inject a Launch Configuration or to run it if it already exists.

**Comment by ramya-rao-a** [comment]
Today you can use the configuration snippets in the launch.json file to add a configuration for debugging a test function. Just start typing "Go" and you will get suggestion items for config snippets.

It should be pretty straightforward to add a command that makes use of the config snippet, and plugs in the name of the test function under the cursor.

As far as debugging the test under the cursor, I think we can use the command "go.debug.startSession" and pass in the config

Am a little busy this week and the next week, so might not be able to get to this.
PRs are welcome though, and I am available to help out if anyone wants to take stab at this and needs help

**Comment by ramya-rao-a** [comment]
With the latest update (0.6.60), you can now debug tests via the codelens.

This is for simple cases only.

If you have cases like env vars being set in your launch.json, the codelens will not be using it.
