### ISSUE TITLE
Support running unit test at cursor

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode-go#88]
Add support for for running a unit test at the cursor.

As I'm still learning the VSCode and vscode-go internals, I'm a bit fuzzy on whether this would be implemented as a command or task.

Split off from #21.

**Comment by ironcladlou** [comment]
@lukehoban 

I've got a branch where I'm prototyping this feature as a new command (`go.test.cursor`). Test detection at the primary cursor is working nicely, and I'm on to constructing the `go test` command to execute which leads me to the next design decision: what are the options for integrating the results of `go test` with Code? In this case, we'll have a few different things to present to the user:

1. The message emitted when the test succeeds, like:

```console
ok      github.com/openshift/origin/pkg/deploy/controller/deploymentconfig      0.054s
```

2. The output emitted when the test fails
3. Go source file/line number references related to the failed test (or stack traces emitted by the test code)

I noticed that for vscode-go itself there's a debugger launch configuration which just emits the unit test output to the debug console. We also have access to the diagnostics API, but that seems a little awkward for test results- diagnostics seems to make more sense for compilers/linters/formatters, etc.

Any tips on how to represent unit test output generally in Code from the context of a command?

**Comment by lukehoban** [comment]
Good question - I don't know what the "best" solution is here within Code.  + @egamma in case he has suggestions.

I think the simple initial thing would just be to report the results in the 'Go' output channel.  Like in https://github.com/Microsoft/vscode-go/blob/master/src/goInstallTools.ts#L66-L78.  

You could also/instead use a gutter decoration on the line where the test is defined with hoverText that provides the results?

I agree that diagnostics API is probably not appropriate for test results.

As a starting point, something which renders to the output channel is probably a good starting point and we can improve the UX from there.

**Comment by ironcladlou** [comment]
Great ideas, thanks. I'll experiment along those lines.

Some good news: hindsight and a little more tinkering has led me to believe I can implement "run tests in package" and "run test at cursor" without any need for package discovery of the current file. Just using `go test` in the right working directory in conjunction with `-run regex` seems to be working. Wish I had figured that out sooner for GoTools...

**Comment by lukehoban** [comment]
Great to hear!

**Comment by egamma** [comment]
Regarding representing test results. The wallaby extension is a good example for showing test results
https://marketplace.visualstudio.com/items/WallabyJs.wallaby-vscode:
- status bar shows number of test failures, clicking the status bar opens the output channel
- the output channel show the full test report, the output channel supports link detection
- the gutter is used for coverage information

**Comment by lukehoban** [comment]
The PR that was just merged implements just bullet 2 in @egamma's list.

I think once we add more test commands, like `Go: Run tests in current package` and `Go: Run tests in workspace`, then it will make sense to add the status bar and gutter information as well (since then there will be multiple test results being displayed).
