### ISSUE TITLE
Go to definition in import

### ISSUE THREAD

**Issue by dashaus** [Microsoft/vscode-go#884]
It is planned to implement godef in import like Gogland IDE? It would be a great help!

For example:

```go
import (
	"sample/web/router"
)
```

If I clicked in "sample/web" then go to web package, or if I clicked in "sample/web/router" then go to router package.

**Comment by ramya-rao-a** [comment]
Something like #330?

**Comment by dashaus** [comment]
@ramya-rao-a yes!
