### ISSUE TITLE
go-langserver doesn't work when editing a package outside of the gopath

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#886]
I'm trying to edit a cli tool that lives outside of my gopath and go-langserver is breaking the VSCode experience:

```
langserver-go: reading on stdin, writing on stdout
[Error - 11:41:19 AM] Request textDocument/hover failed.
  Message: import "/Users/mattetti/Code/cr24/cmd/renderercli": cannot import absolute path
  Code: 0 
```

If you look at my import paths, none of them are absolute:

```
package main

import (
	"fmt"
	"log"
	"os"
	"strings"

	"golang.org/x/net/html"
)
```

I'm not sure if that's a vscode go plugin integration or a simple go-langserver issue.

**Comment by ramya-rao-a** [comment]
What is the behavior when you have the language server turned off?

**Comment by mattetti** [comment]
everything works fine with gocode when I turn off the language server feature

**Comment by ramya-rao-a** [comment]
cc @keegancsmith

**Comment by keegancsmith** [comment]
Thanks. I've filed an issue in go-langserver https://github.com/sourcegraph/go-langserver/issues/185

**Comment by ramya-rao-a** [comment]
Closing this issue as we have an upstream issue logged for the same
