### ISSUE TITLE
could not import <library> (can't find import: )

### ISSUE THREAD

**Issue by pierznj** [Microsoft/vscode-go#887]
Since reinstalling vscode on a new machine, all my import statements from the standard go library show green underlines with the above error. Imports of my own packages are fine. Something to do with the go path? But my go path is in the usual place and everything actually works in practice.

**Comment by ramya-rao-a** [comment]
What about 3rd party packages?

If it is just the standard go library, then my bet is on the GOROOT.

**Comment by pierznj** [comment]
OK, I set the `go.goroot` and `go.gopath` settings and that fixed it. Not sure why that was necessary, but hey, it works.
