### ISSUE TITLE
Cannot watch variable on Golang remote debug

### ISSUE THREAD

**Issue by avence12** [Microsoft/vscode-go#888]
- VSCode Version: 1.10.2
- vscode-go Version: 0.6.55
- OS Version: OS X 10.11.6
- Delve Debugger Version: 0.12.1

I can debug my code using mode `test` and `debug` so I assume my Delve works well.
However I cannot watch variable nor call stack when doing remote debug.

Steps to Reproduce:

1. My `launch.json`

```
        {
        "name": "Remote",
        "type": "go",
        "request": "launch",        
        "mode": "exec",
        "port": 12899,
        "host": "127.0.0.1",
        "program": "${workspaceRoot}/bin/server",
        "args": ["-conf", "./conf/dev.conf"]
        }
```
2. My application is a simple Restful API server and I just send a request to `http://127.0.0.1:12899/system/event/`

3. The cursor goes to the breakpoint but I can not watch local variable `sortSpec ` nor const `MGO_SYSTEM_DB `

![image](https://cloud.githubusercontent.com/assets/4282367/24245114/82a38b68-0ffc-11e7-9fa3-3954e7716c28.png)

Reference: 
- https://github.com/Microsoft/vscode/issues/23090

**Comment by ramya-rao-a** [comment]
@avence12 Sorry for not responding sooner. Do you still see this issue?

The `Failed to eval expression` is coming from delve itself. I see that you are using the `exec` mode.
When you run `dlv exec` from the terminal, hit the breakpoint, are you able to evaluate those variables using the `print` command? If no, then this is a limitation of delve itself.
