### ISSUE TITLE
Support running all tests in file

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode-go#89]
Add support for for running all tests defined in the current file.

As I'm still learning the VSCode and vscode-go internals, I'm a bit fuzzy on whether this would be implemented as a command or task.

Split off from #21. Would build upon #88.

**Comment by lukehoban** [comment]
Curious - do you want "all tests in a file" or "all tests in a package" or both?

**Comment by ironcladlou** [comment]
Implemented both in #123.
