### ISSUE TITLE
How does one debug ginkgo tests

### ISSUE THREAD

**Issue by kmudrick** [Microsoft/vscode-go#893]
Ginkgo is a Go testing framework: https://onsi.github.io/ginkgo/

Ginkgo tests need to be run with the ginkgo executable, like:
```
ginkgo -r
```

My problem is that I can create a launch configuration with mode `exec` and my path to ginkgo as the program - but I _cannot_ actually debug with mode `debug`:

> Failed to continue: "The program attribute must be a directory or .go file in debug mode"

Is there any way to do this?  I'd like to be able to step through both the tests and the go code under test.

**Comment by ramya-rao-a** [comment]
The Go extension uses [delve](https://github.com/derekparker/delve) for implementing the debugging features.
I don't think delve supports debugging tests run via a framework as you have described

@derekparker is this doable using delve?

**Comment by zmb3** [comment]
> Ginkgo tests need to be run with the ginkgo executable

This is actually [not the case](https://onsi.github.io/ginkgo/).

> Ginkgo hooks into Go’s existing testing infrastructure. This allows you to run a Ginkgo suite using `go test`.

This means delve test support should work just fine.

**Comment by ramya-rao-a** [comment]
Thanks @zmb3 

In that case, @kmudrick use the `test` mode in your launch config. Details: [Debugging-Go-code-using-VS-Code](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson)

Closing for now, let us know if this doesn't work for you

**Comment by kmudrick** [comment]
@zmb3 @ramya-rao-a thanks so much! Will give this a try today.
