### ISSUE TITLE
Use editor.action.quickFix to implement suggestions

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode-go#896]
If you use the C# plugin you can get actions to carry out when on a certain line/column

With the below I get a green squiggly saying it should be `myJSON`

`myJson, err := json.Marshal(myPerson)`

What would be nice is to invoke `editor.action.quickFix` and for it to change `myJson` to `myJSON`

**Comment by ramya-rao-a** [comment]
You mean you'd like to use the "light bulb" like feature where you click and it auto-corrects the issue?

**Comment by jchannon** [comment]
@ramya-rao-a yup. Exactly that

**Comment by ramya-rao-a** [comment]
Tracked in #727
