### ISSUE TITLE
Error show in "package"

### ISSUE THREAD

**Issue by khoango** [Microsoft/vscode-go#898]
<img width="603" alt="bug1" src="https://cloud.githubusercontent.com/assets/7312077/24535381/e76d1850-15fd-11e7-9b6b-0d541f63500e.png">

Hi, I get this issue when upate to 0.6.57.
How can I fix them.
Thanks

**Comment by ramya-rao-a** [comment]
Hi,

This is being tracked in #894. Closing this issue as duplicate

I do have a fix for this, but since I cannot repro it in my box, can you follow the steps in https://github.com/Microsoft/vscode-go/issues/894#issuecomment-290610756 and confirm if the fix works for you?

**Comment by khoango** [comment]
Thanks

**Comment by ramya-rao-a** [comment]
@khoango I want to understand your scenario better.

Can you share the output you get when you run the command `Go: Current GOPATH` ?

**Comment by ramya-rao-a** [comment]
I just released an update (0.6.59) yesterday which has the fix
