### ISSUE TITLE
Add support for parameter hints

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-go#9]
VS Code has API to provide parameter hints/signature help. It would be great to also have parameter hints for Go.

**Comment by zsxawerdu** [comment]
I am going to do my best to tackle this one, I have a branch I been experimenting on.  
https://github.com/zsxawerdu/vscode-go/tree/exp_gosignature   


It looks like using 'godef' and/or 'go doc -u' to get the relevant information out might be helpful.  I would like to find a way to reverse token from my current position, if I can get the right tokens, I may just be able to use 'go doc -u' to get the calling information.

Thoughts?

**Comment by lukehoban** [comment]
@zsxawerdu Thanks  - just took a look at this - great start.

I like the idea of using `go doc -u`. 

I'm seeing this work okay when typing the `(`, but then the logic to find the function name fails as I type through the arguments to the function call.  Sounds like this is the same issue you were mentioning with having to walk back through the tokens to find the first enclosing function call.  I'm unfortunately not sure how to do that robustly without implementing a bunch of somewhat complicated Go parsing logic.

Also - the rendering of the parameter hints doesn't quite seem as good as the TypeScript rendering yet - seems it doesn't yet know which argument is currently active to highlight it?

Currently seeing from your branch:
![screen shot 2015-11-24 at 11 39 15 am](https://cloud.githubusercontent.com/assets/223467/11378482/430a160a-92a0-11e5-823a-da03f89bf3c3.png)

Seeing in TS files:
![screen shot 2015-11-24 at 11 40 24 am](https://cloud.githubusercontent.com/assets/223467/11378490/4c9fb904-92a0-11e5-9311-749894baf0b5.png)

**Comment by lukehoban** [comment]
Also - since this is trying to show usage not definition, I wonder if it makes sense to drop the leading `func ` from the display?

**Comment by aybabtme** [comment]
I'm trying out vscode today and stumbled on this (parameter hints & completeion-fills-out-parameters). It would be a very nice feature but I notice that development seems to have staled since Nov 25 2015. I don't know any TypeScript personally, so picking up the work would be hard for me. Is there another place where this feature is being worked on?

**Comment by zippoxer** [comment]
Any progress with this?

Without this, I find it hard to believe this extension would fill the void of Gophers migrating to VSCode from Sublime Text, Atom or even IntelliJ IDEA.

So, yeah, that's pretty crucial and I will dive in and help get this done if I choose to stick with VSCode.

**Comment by lukehoban** [comment]
Version 0.6.24 is now published with the Signature Help implementation.

Here's what it currently looks like:
![sighelp](https://cloud.githubusercontent.com/assets/223467/12686967/d8d1e6e4-c681-11e5-8ff4-bc96a2f22eba.gif)

**Comment by aybabtme** [comment]
Wow awesome!!!!
