### ISSUE TITLE
Extension is published with some sources duplicated

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-go#90]
Looking in `C:\Users\Administrator\.vscode\extensions\lukehoban.Go\out`:

I see `goCheck.js` twice:
- once in `C:\Users\Administrator\.vscode\extensions\lukehoban.Go\out\goCheck.js`
- once in `C:\Users\Administrator\.vscode\extensions\lukehoban.Go\out\src\goCheck.js`

**Comment by lukehoban** [comment]
This should be fixed with the `0.6.15` update.
