### ISSUE TITLE
How to run a program?

### ISSUE THREAD

**Issue by martin-flower** [Microsoft/vscode-go#900]
I am new to Go and to Visual Studio Code. I have followed the instructions to run _hello world_ in the debugger. But how do I run the program directly in the IDE without the debugger? I have not found any reference to this in the documentation.

**Comment by ramya-rao-a** [comment]
@martin-flower what nice timing, we just released that feature in the latest update

See https://github.com/Microsoft/vscode-go/wiki/Release-Notes#debugging-improvements

**Comment by martin-flower** [comment]
Thank you @ramya-rao-a. As I now understand it, go programmers run programs from the command line, and use Visual Studio Code for content-assist.

Having selected hello.go in the explorer, then typing Cmd+F5 I find myself in the debugger (and I don't see Hello World output in any console tabs). What I was looking for in this issue is (I think), how to execute go run hello.go by clicking on a button inside Visual Studio Code instead of using the command line, and then seeing 'Hello World' in the output console. This is what I would expect based on my previous experience with IDEs (Eclipse, IntelliJ, and so on).

This will all make more sense to me no doubt when I have learnt more go.

Meanwhile, thanks for your work with this plugin and your help with this issue.

**Comment by ramya-rao-a** [comment]
When you find yourself in the debugger (after Cmd+F5), are the step in/out/over buttons enabled or disabled?

You need to open the file you want to run and then hit Cmd+F5 instead of just selecting it in the explorer. Can you give that a try?

**Comment by martin-flower** [comment]
Hi - my user experience is as follows.

I start Visual Studio Code.
I click on Explorer > SRC > hello > hello.go
hello.go source is visible in the editor
there is some information in the OUTPUT window for golint, tool vet, build
I type Cmd+F5
The debug buttons appear
I can select pause, restart and stop - the others are not selectable
The debug console shows
```
debugger.go:66: launching process with args: [/Users/martin/go/src/hello/debug]
API server listening at: 127.0.0.1:2345
```

**Comment by ramya-rao-a** [comment]
That output means that the debugger(delve) was called instead of just running the program

My bet is that you have a launch configuration with the `program` property pointing to a directory.
Update that to point to `${file}` and then in the editor where your file is open press Cmd+F5

**Comment by martin-flower** [comment]
In launch.json I now have
` "program": "${file}"
`
In the Explorer I select hello.go
The program appears in the editor
I press Cmd+F5
The debug buttons appear for about 1 second, then disappear
In the DEBUG CONSOLE I see the following
```
hello, world
Process exiting with code: 0
```
Is this now the expected behaviour?

**Comment by ramya-rao-a** [comment]
Yes!

**Comment by nibbles-** [comment]
This was a post that was hard to find.
I spent quite a while to find this information.

Would it be possible so that the default config is actually doing what the menubuttons show (i.e if I press cmd/ctrl + f5 in runs without debug regardless of what I have configured in launch.json

**Comment by ramya-rao-a** [comment]
@nibbles The initial reason to use the current selected configuration in launch.json when pressing cmd/ctrl+f5 was to keep parity with VS Code's features of how node programs are run

Also, the advantages being that you could have different configurations for either running the same program with different args or to run different packages under the same parent folder.

**Comment by nibbles** [comment]
*wakes from sleep* huh? what? where?! Someone call me?  :-P
