### ISSUE TITLE
Feature Request: do not ignore a line number in links in the terminal

### ISSUE THREAD

**Issue by TomasB** [Microsoft/vscode-go#901]
Given the output in the integrated terminal window:

```
panic(0xa49c80, 0xc04200a090)
        C:/Go/src/runtime/panic.go:458 +0x251

```
the link in the output is parsed as `C:/Go/src/runtime/panic.go`
Probably should be `C:/Go/src/runtime/panic.go:458` and go to a specific line once clicked on it.

**Comment by ramya-rao-a** [comment]
That is a VS Code specific behavior and not Go related

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#23776
