### ISSUE TITLE
Provide more info when you get "Cannot rename due to errors...."

### ISSUE THREAD

**Issue by freeformz** [Microsoft/vscode-go#902]
Sometimes when I rename I get the following:

![screen shot 2017-03-31 at 10 42 15 am](https://cloud.githubusercontent.com/assets/103/24562598/1cd15284-1600-11e7-88d5-fad25760ffd3.png)

The text I get is : `Cannot rename due to errors: While scanning Go Workspace:`

but there aren't any more details about what those errors are, so it's hard to figure out what those errors are to correct them.

**Comment by ramya-rao-a** [comment]
good catch

We do append the error from the `gorename` tool. See https://github.com/Microsoft/vscode-go/blob/0.6.57/src/goRename.ts#L43

Maybe there is a newline there somewhere that is causing this.

Can you provide a consistent repro step, so that I can debug and see what kind of error causes this?

**Comment by willfaught** [comment]
I see something similar. It happens whenever I try to rename a second time. If I try it again, then it works with no error.

**Comment by ramya-rao-a** [comment]
Ah! My suspicion on the newline was right.

This is where the error comes from: https://github.com/golang/tools/blob/master/refactor/rename/rename.go#L278

You can see there is a new line.

And the vscode information/error box doesnt seem to like newlines.

Just tested with a message of my own

![image](https://cloud.githubusercontent.com/assets/16890566/24624302/3e57f32e-1860-11e7-805a-98b4a81e578b.png)

**Comment by ramya-rao-a** [comment]
@jrieken This is a case when rename operation fails and `provideRenameEdits` returns a rejected promise with the error message which VS Code then displays in the information box.

The information box shows only the first line. The hover shows all lines in the same line.

Shall I move this issue to VS Code or is there any expectation of extensions, that they shouldnt return multi line error messages?

**Comment by jrieken** [comment]
@bpasero might know. The notification story is currently being revisited, today afaik this isn't possible otherwise.

**Comment by bpasero** [comment]
There are already issues logged against the fact that messages cannot show more details. Please check first in our repo.

**Comment by bpasero** [comment]
Yeah, the search @ GH is not very user friendly, I hit this dozen times a day 👎

**Comment by ramya-rao-a** [comment]
Alright, for now, I'll update the error message sent by the Go extension to replace `\n` with space, so that the message surfaces completely.

**Comment by ramya-rao-a** [comment]
@willfaught @freeformz  Just rolled out an update, now you should be able to see the whole error.
