### ISSUE TITLE
Cannot import absolute path

### ISSUE THREAD

**Issue by rogierlommers** [Microsoft/vscode-go#905]
After upgrading to 0.6.57, VSC gives `cannot import absolute path` when I try to edit a .go file which is not in the gopath. This used to work fine. Did something change?

**Comment by yepher** [comment]
I got the update today and now I get this error on every file I open/save. It was working fine yesterday.

![screen shot 2017-04-01 at 7 57 15 am](https://cloud.githubusercontent.com/assets/1359331/24578909/dc7b0e1c-16b0-11e7-81b7-fa7b7b39a549.png)

**Comment by yepher** [comment]
Looks like there maybe a work around here but would like confirmation before trying if possible:

https://github.com/Microsoft/vscode-go/commit/d417fd6725077d1233fb1bcd3aa5d097d02715a9

**Comment by yepher** [comment]
I followed these directions as published by @ramya-rao-a 

## Workaround:

* Uninstall Go extension
* Download the vsix file [Go-0.6.58.vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-0.6.58.vsix)
* Run code --install-extension Go-0.5.58.vsix from the location where you downloaded the file
* I am trying to understand all different scenarios where this occurs (and there are quite a few) and will publish the fix soon


For me on OSX this was my command:

`/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code --install-extension ~/Downloads/Go-0.6.58.vsix `

**Comment by ramya-rao-a** [comment]
@yepher Thanks for linking the workaround!

@jsvensson https://github.com/Microsoft/vscode-go/commit/915ca6331081ed794018bc4e3034a8374b0cb2c1 is actually the fix which is not shipped yet. It is the fix that I have bundled into [Go-0.6.58.vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-0.6.58.vsix) as the workaround.

My assumption was that the `$GOPATH/src` is always prefix in file path. When this is not the case, I used to fall back to to the `cwd` which was absolute path causing the error you are seeing. Changing that to `.`, go is happy to build relative paths.

Now what I am trying to understand is why for certain users the assumption that `$GOPATH/src` is always prefix in file path does not hold true.

Anyone has ideas?

**Comment by yepher** [comment]
I am not exactly clear what you mean by "GOPATH is always prefix in the file path"

GOPATH is an array of paths.  Is the issue possibly related to folks who have multi-paths defined in their GOPATH?

**Comment by rogierlommers** [comment]
Not sure what you mean by "multi-paths". I have a pretty average (out-of-the-box) golang installation. No customisations at all.

**Comment by yepher** [comment]
Sorry @rogierlommers I don't think that is the issue you were seeing. I was responding to @ramya-rao-a's inquiry to continue the discussion above. 

To clarify here is what I meant by multiple paths:

'Since the $GOPATH variable can be a list, the rest of this document will use $GOPATH to mean the first element unless otherwise specified.' See [here](https://github.com/golang/go/wiki/GOPATH)

**Comment by ramya-rao-a** [comment]
@yepher when I say "GOPATH is always prefix in the file path", I meant that atleast one of the paths in the GOPATH env var appended with '/src' is always the prefix in the file path.

Say your GOPATH is "/Users/me/Path1:/Users/me/Path2", then my assumption is that the file path for any of your Go files should either be "/Users/me/Path1/src/....." or "/Users/me/Path2/src/..."

Using this assumption I then try to get the import path.

When this assumption fails, I end up using the file's directory which is what causes the "absolute path" error that you see.

**Comment by yepher** [comment]
@ramya-rao-a I am happy to share details about my env if there is something concrete you would like to see.

**Comment by yepher** [comment]
Re-reading your previous comment I think I may know what is going on (at least with my env).

**Comment by yepher** [comment]
Re-reading your previous comment I think I may know what is going on (at least with my env).

This is my env

```
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cwilson/spWorking/.golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cg/xpwdhpv9635ctpsvh4w5rl900000gn/T/go-build023053584=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

So all my `go get XXX` reside in `/Users/cwilson/spWorking/.golang` but all my project source files are in completely different locations. For instance the project I was working on when I get this error is [SparkPost CLI](https://github.com/SparkPost/sparkpost-cli) and it is located in `/Users/cwilson/spWorking/sparkpost_github/sparkpost-cli`.

I am not sure if this is a standard way of doing development but it is how I've been working. So you will see `/Users/cwilson/spWorking/sparkpost_github/sparkpost-cli` is not in my GOPATH.

**Comment by ramya-rao-a** [comment]
Thanks @yepher!

Yes, your scenario totally explains the error.

I am stumped by some other cases where the project seems to be under GOPATH/src but still see the same error :( That is what I am trying to figure out.

But thanks for explaining your case.

**Comment by rogierlommers** [comment]
Is it known already when the officiel extension will be fixed?

**Comment by ramya-rao-a** [comment]
I just released an update (0.6.59) yesterday which has the fix, sorry didnt get around to updating this thread.

**Comment by yepher** [comment]
I've been using (0.6.59) all day and it is working just fine.

**Comment by rogierlommers** [comment]
Thanks @ramya-rao-a , for all your work! Starting update.......

**Comment by asw** [comment]
Is there perhaps a related bug which causes IntelliSense to break by appearing blank and not disappearing, as below?
![screenshot1](https://cloud.githubusercontent.com/assets/339629/24730464/cc13f00a-1a31-11e7-9a17-e3f28dca9c49.png)

**Comment by ramya-rao-a** [comment]
no there is no such bug, you can log a new one

**Comment by asw** [comment]
@ramya-rao-a Thank you! Logged on https://github.com/Microsoft/vscode-go/issues/918
