### ISSUE TITLE
Enabling useCodeSnippetsOnFunctionSuggest causes autocomplete to stop functioning

### ISSUE THREAD

**Issue by tylerb** [Microsoft/vscode-go#915]
I enabled `useCodeSnippetsOnFunctionSuggest` and, most of the time, it works great. I much prefer having this option on.

However, I noticed that sometimes the autocomplete simply stops working. When I turned this option off, it came right back. I believe it is because there is an exception being thrown quite frequently. At [goSuggest.ts:192](https://github.com/Microsoft/vscode-go/blob/master/src/goSuggest.ts#L192) an exception is thrown as `trim() is not a function`. The exception is caught and rejected at [goSuggest.ts:214](https://github.com/Microsoft/vscode-go/blob/master/src/goSuggest.ts#L214), but seems to be causing the autocomplete functionality to have issues.

**Comment by ramya-rao-a** [comment]
Do you see this exception getting logged anywhere?

**Comment by tylerb** [comment]
No, it doesn't get logged. It's completely ignored from what I can see.

I just managed to get it to happen, so I'm digging into it with the debugger now.

Unfortunately, my javascript skills are quite minimal, but here's what I am seeing as the contents of the variables at the time this issue happens:

```
params
Array[1] ["container"]
length:1
__proto__:Array[0]
0:"container"

i
"apply"
```

Printing the contents of params shows an array containing `"container"`. This seems fine. However, printing the contents of `i`, shows the word `"apply"`, which makes no sense to me.

The line `for (let i in params)` would suggest that `i` should contain `0`. Obviously `params["apply"]` isn't going to work. I don't understand how it got to this state, though.

**Comment by tylerb** [comment]
I added a check to just `continue` if the contents of `i` was bogus. This exception happens frequently, as you can see. I've been coding for about 30 minutes:

```
skipping because i is apply
skipping because i is flatMap
skipping because i is apply
skipping because i is flatMap
skipping because i is apply
skipping because i is flatMap
skipping because i is apply
skipping because i is flatMap
skipping because i is apply
skipping because i is flatMap
skipping because i is apply
skipping because i is flatMap
skipping because i is apply
skipping because i is flatMap
```

**Comment by ramya-rao-a** [comment]
weird, I am not able to repro, `i` is always a number for me.

Can you get a repro on a simple Go file that uses just the standard library?

**Comment by tylerb** [comment]
I saw this same issue when I was working on the live error feature. The file I was testing was the same as the one in the gif I sent. It just imported `fmt` and printed a line.

**Comment by tylerb** [comment]
I can try to reproduce it again in that file.

**Comment by tylerb** [comment]
@ramya-rao-a I now have reproduction steps.

First, create a test Go file containing:

```go
package main

type Test struct{}

func (t *Test) Name() string {
 return "name"
}

func main() {
}
```

Now: 

1. Install the (Rewrap)[https://marketplace.visualstudio.com/items?itemName=stkb.rewrap] extension
2. In your test file, place your cursor on `"name"` and press `alt+q` to trigger rewrap extension.
3. Check your debugger host and you should see `Edits from command rewrap.rewrapComment were not applied.` printed in the debug console.
4. Delete the `Name` method definition and retype it.
5. When you hit the `N` in `Name`, the exception will be thrown and the `i` value in the iterator will first contain `apply`, then `flatMap`.

Stepping through the code, I am seeing that the `for` loop runs 3 times, even though there is only one entry in the array. The first `i` value is `0`, then `apply`, then `flatMap`. Perhaps the rewrite extension is altering the array prototype or something like that? It would seem that only happens after the extension has been loaded and executed.

At this point, the exception will continue to fire until vscode is closed and restarted.

**Comment by tylerb** [comment]
Bingo: https://github.com/stkb/vscode-rewrap/blob/master/src/extensions.ts

**Comment by tylerb** [comment]
@ramya-rao-a given my limited knowledge of javascript, I do not know what an appropriate solution would be here. Is it bad form to alter the prototype of `Array`? Or is that a common occurance, and `vscode-go` should be expecting that might happen?

Basically, who is responsible for fixing this issue? Us or `vscode-rewrap`?

**Comment by ramya-rao-a** [comment]
That's some great investigation @tylerb :clap:

That should definitely be fixed in the extension causing the problem.

From our side, can you try changing `for (let i in params)` to a more basic for loop say `for (let i = 0; i < params.length; i++` and see if that bypasses the issue?

**Comment by tylerb** [comment]
@ramya-rao-a just tried it. The exception goes away and the `i` value always contains a number.

**Comment by ramya-rao-a** [comment]
Great, waiting for your PR to fix this issue :)

**Comment by ramya-rao-a** [comment]
PR is merged, thanks for finding this @tylerb !
