### ISSUE TITLE
Click to goto definition doesn't work for the stdlib

### ISSUE THREAD

**Issue by bcokert** [Microsoft/vscode-go#916]
When I cmd click on an identifier, package, etc, I'd expect it to go to the definition, such as in the stdlib. However everything I try I get "No definition found for 'xxx'". There is no output in the debug console. If I do it on another library (local package or remotely downloaded one) it works fine.

I ran the Go: Install Tools again to make sure, and got no errors:
```
Installing 12 tools
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gomodifytags
  godef
  godoc
  goreturns
  golint
  gotests

Installing gocode SUCCEEDED
Installing gopkgs SUCCEEDED
Installing go-outline SUCCEEDED
Installing go-symbols SUCCEEDED
Installing guru SUCCEEDED
Installing gorename SUCCEEDED
Installing gomodifytags SUCCEEDED
Installing godef SUCCEEDED
Installing godoc SUCCEEDED
Installing goreturns SUCCEEDED
Installing golint SUCCEEDED
Installing gotests SUCCEEDED

All tools successfully installed. You're ready to Go :).
```

I also ran godef manually, as shown in a similar issue:
```
$ echo "$GOPATH"
/Users/brandono/projects/gohome

$ cd ~/projects/gohome/src
$ cat test.go
package main

import "fmt"

func main() {
    _ = fmt.Errorf("hello")
}

$ godef -t -i -f test.go -o 59 < test.go
/usr/local/Cellar/go/1.7.1/libexec/src/fmt/print.go:204:6
Errorf func(format string, a ...interface{}) error
```

Just in case it's different, I also ran godef from within the terminal in vscode, in the project I'm working in:
```
$ godef -t -i -f http/middleware.go -o 33 < http/middleware.go
/usr/local/Cellar/go/1.7.1/libexec/src/net/http
```

Which again seems correct. But then I discovered the debug console, and found the errors - godef is indeed failing:
```
// Paths shorted from absolute paths in the debug log
$ godef -t -i -f http/middleware.go -o 3417 < http/middleware.go
godef: no declaration found for context.WithValues
```
These are failing even when I run locally. I don't know how though, since my gopath is not setup weird as far as I know:
```
$ echo $GOPATH
/Users/brandono/projects/gohome
$ pwd
/Users/brandono/projects/gohome/src/github.company.com/team/enlightning
$ godef -t -i -f http/middleware.go -o 3417 < http/middleware.go
godef: no declaration found for context.WithValues
```

Most other parts of the plugin work. Saving auto fmt's, and code completion works:
```
![screen shot 2017-04-05 at 1 59 38 pm](https://cloud.githubusercontent.com/assets/739964/24726713/2bf5c5b8-1a08-11e7-877d-75e59cc632cd.png)
```

I tried reinstalling godef:
```
$ go get -u github.com/rogpeppe/godef
$ go install github.com/rogpeppe/godef
```
But that didn't fix it either. I also tried setting my GOROOT to /usr/local/opt/go/libexec, which is where brew installed it it looks like.

Other details:
* go version go1.7.1 darwin/amd64
* install via brew

**Comment by bcokert** [comment]
Somewhere in the process of testing this and creating this issue, I broke my gopath. In the process of fixing it, I also seem to have fixed the underlying issue.

The end working result:
```
//.bashrc:
export GOPATH="$HOME/projects/gohome"
export PATH=$PATH:$GOPATH/bin
// GOROOT is not set

$ which go
/usr/local/bin/go
```

**Comment by ramya-rao-a** [comment]
That was some very detailed investigation and reporting, it was a pleasure to read through even though it is a bug report :) You looked into most of the areas that I would have asked follow up questions on.

Since the issue was with stdlib and that other packages was working fine, my bet would be on GOROOT

Am glad it is working now, Happy Coding!
