### ISSUE TITLE
Syntax Highlighting stops midway through .go file

### ISSUE THREAD

**Issue by yepher** [Microsoft/vscode-go#917]
VSC Go Version: 0.6.59

[This](https://github.com/SparkPost/gosparkpost/blob/24ff064d0d36c76152c1ed785348f26b2294de58/del_metrics_test.go) file `del_metrics_test.go` does not render properly in VS Code.

The problem seems to be related to long strings.

Here is a screenshot of what the rendering looks like.

![screen shot 2017-04-05 at 8 13 27 pm](https://cloud.githubusercontent.com/assets/1359331/24733365/e1a134ae-1a3c-11e7-9d64-750ec26ff4cb.png)

**Comment by ramya-rao-a** [comment]
@yepher This is fixed in the latest VS Code after we pulled in the latest grammar for Go from https://github.com/atom/language-go
