### ISSUE TITLE
Can't find delve debuger on Ubuntu

### ISSUE THREAD

**Issue by Kasmetski** [Microsoft/vscode-go#924]
Hello,
I have installed everything. When I open a project in VSCode and type in terminal "dlv debug" the command works but if I push the debug button in VSCode it says
`Failed to continue: "Cannot find Delve debugger. Install from https://github.com/derekparker/delve & ensure it is in your "GOPATH/bin" or "PATH"."`

`dlv` bin file is in `/home/user/go/bin` with the others. but VSCode can't find it. And how I said if I type the command in terminal there is no problem. GOPATH is seth and all other packages are working fine.
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
```
and part of my `.bash_rc` file
```
export GOPATH="/home/user/go"
export PATH=$PATH:"/home/user/go/bin" 
```

**Comment by ramya-rao-a** [comment]
Can you set `"trace": "verbose"` in your launch configuration and try again?
This will print out a more detailed error in the debug console in the form
"Couldnt find dlv at ..... or .."

**Comment by Kasmetski** [comment]
I found the problem with the trace - verbose, thanks!

For others with the same problem:
It looks writing in `~/.bashrc` like that doesnt export correctly. Even the fact everything is working in the console -  `go`, `dlv` & etc. 
```
export GOPATH="/home/user/go"
export PATH=$PATH:"/home/user/go/bin"
```
I searched more and did two things, you can choose the one
Little correction in `.bashrc`
```
export GOPATH="/home/user/go"
export PATH="/home/user/go/bin:$PATH"
```
or add this line in `/etc/profile.d/apps-bin-path.sh`
```
PATH=$PATH:/home/user/go/bin
```

**Comment by ramya-rao-a** [comment]
thanks for sharing the solution @Kasmetski !

**Comment by didenko** [comment]
What probably fixed it is placing the path in the `/etc/profile.d/*` files - which has similar effect at `~/.profile`. See https://github.com/Microsoft/vscode-go/issues/358#issuecomment-323528504 for more details.
