### ISSUE TITLE
Go to Definition is not considering the GOHOSTOS' when the function is defined for multiple GOHOSTOS'

### ISSUE THREAD

**Issue by Zignd** [Microsoft/vscode-go#927]
I was using Windows, I tried to Go to Definition on a call to the `rename` function (internal function in the `os` package), and the function definition for Plan 9 opened in my editor.

The `rename` function has definitions in `GOROOT/src/os/file_plan9.go`, `GOROOT/src/os/file_unix.go`, and in `GOROOT/src/os/file_windows.go`.

I was expecting the extension to open the definition from the `GOROOT/src/os/file_windows.go` file.

**Comment by ramya-rao-a** [comment]
I am on a Mac, and for me the definition in `GOROOT/src/os/file.go` opens.

@rakyll What is the expectation here?

**Comment by Zignd** [comment]
Oh, it's not the `os.Rename` function, it's the `os.rename` function. `os.rename` is called from within `os.Rename` to perform the rename according to a specific operating system. I just tried it on Linux and the same occurs, `GOROOT/src/os/file_plan9.go` opens.

**Comment by ramya-rao-a** [comment]
@Zignd Ah, got it.

I tried on my Mac again, and the definition in `file_unix.go` opened for me.

But on Windows, I can repro what you are seeing i.e `file_plan9.go` opens.
If I update my settings to use the `gogetdoc` tool instead (set `"go.docsTool": "gogetdoc"`), then I get navigated to the right file.

Can you try using `gogetdoc` and see if that helps?

If it does, then this issue should be moved to the repo for `godef`

**Comment by Zignd** [comment]
@ramya-rao-a It works when I set `"go.docsTool": "gogetdoc"`. It seems to be an issue with `godef` as you said. Should I open an issue there?

**Comment by ramya-rao-a** [comment]
This issue was moved to rogpeppe/godef#59

**Comment by ramya-rao-a** [comment]
@Zignd I don't see much activity in the `godef` repo, so I don't expect a fix there soon.

I'd suggest using `gogetdoc` instead

**Comment by Zignd** [comment]
@ramya-rao-a Ok, I will use it instead, thanks for the help.
