### ISSUE TITLE
Variable substitution for go.testFlags

### ISSUE THREAD

**Issue by KevinSjoberg** [Microsoft/vscode-go#928]
It would be nice if `go.testFlags` would allow [variable substation](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution). This could be really useful when passing custom arguments to `go test`.

I'm currently working in a project where we need to pass `-config ${workspaceRoot}/test-config.yml` before running the test suite.

I can see that we already support `~` and `${workspaceRoot}` in `go.gopath` and `go.toolsGopath`. Addressed in https://github.com/Microsoft/vscode-go/pull/768.

Is this something we'd like to implement? If so, I'd be happy to take a stab at it. 😃

**Comment by ramya-rao-a** [comment]
While we could do this in the extension, I would ideally like this support in the form of an API from VS Code.

Give me a few days and I'll see if we can get this support from VS Code. If not, then I'll add a comment here and you can give it a try.

Sound ok?

**Comment by KevinSjoberg** [comment]
@ramya-rao-a sounds good. If it is possible to support this via an API, would we want to update the current implementation for `go.gopath` and `go.toolsGopath` to use that as well?

**Comment by ramya-rao-a** [comment]
yes

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension (0.6.81)

**Comment by fengpf** [comment]
go 1.10 use cache in go test, how to config go.testFlags
