### ISSUE TITLE
gofmt.exe should be default formatter under windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-go#93]
After installing go from 
https://golang.org/doc/install?download=go1.5.1.windows-amd64.msi my `Go\bin` folder contains:
* `go.exe`
* `godoc.exe`
* `gofmt.exe`

The extension could use by default the formatter that comes with the official go installer instead of `goreturns.exe`.

![image](https://cloud.githubusercontent.com/assets/5047891/11402042/261881c0-9396-11e5-83be-caa89c148ffb.png)

**Comment by lukehoban** [comment]
Many of the tools that the extension depends on must be acquired separately from the Go installer, so I'm not sure it helps much to default to a less-rich formatter just to avoid needing to run the tools installs.
