### ISSUE TITLE
Turn off auto-format on file save

### ISSUE THREAD

**Issue by toruk0109** [Microsoft/vscode-go#930]
Hello,

I've one issue. In my VS Code editor.formatOnSave is false (as default), but it still does format my files (paste everywhere spaces like: {} to { } and so on), but I don't need this at all, cause I edit a few lines and have to commit on git too much lines, which wasn't edit by myself. How to solve this?

Thanks.

**Comment by ramya-rao-a** [comment]
Are you working on Go files and have the Go extension installed?
If yes, then you can set `go.formatOnSave` to false
If not, then this is not the repo for the problem you are facing.
