### ISSUE TITLE
Code snippet suggest insert fails on multiple cursors

### ISSUE THREAD

**Issue by tylerb** [Microsoft/vscode-go#931]
If you have multiple cursors in use, then attempt to fill using a snippet, only the first cursor inserts the contents of the snippet. This makes you completely out of sync with the other cursors.

I don't know if this is a vscode-go issue or a vscode issue.

**Comment by ramya-rao-a** [comment]
This is a VS Code issue and is being tracked here: https://github.com/Microsoft/vscode/issues/16037
