### ISSUE TITLE
Syntax highlighting lost in var block multi-line initialize

### ISSUE THREAD

**Issue by LYY** [Microsoft/vscode-go#936]
See below:

![2017-04-20 20 18 01](https://cloud.githubusercontent.com/assets/508941/25230621/3c5110d8-2607-11e7-92d6-fdef5daee0fc.png)

code:

```go
var (
	userService = &services.UserService{}
	userRegister = &routers.Handler{
		Method: "post",
		Path:   "/register",
		Handler: func(c echo.Context) error {
			var user models.User
			if err := c.Bind(&user); err != nil {
				return err
			}

			if err := userService.Register(&user); err != nil {
				return err
			}
			return nil
		},
	}
)
```

In the `Handler` function, lost highlighting with `var`, `if`, `return` and so on.

**Comment by ramya-rao-a** [comment]
@LYY which version of VS Code are you using?

**Comment by LYY** [comment]
@ramya-rao-a For now is 1.12.1, the bug is still there.

**Comment by jimah** [comment]
I am also experiencing this issue in 1.12.2.

Go plugin version 0.6.61.

**Comment by dmke** [comment]
I believe the grammar has a a problem with parentheses in the `var (...)` declaration block. I've notices this while creating a global channel ([Gist with go sources](https://gist.github.com/dmke/a59c76c1d65f5f822c03ff7557288475)):

![screenshot](https://cloud.githubusercontent.com/assets/327411/26319470/6f62c300-3f1f-11e7-9d90-67c87064c80d.png)

Here's another funky example (note the `return` in line 6):

![screenshot](https://cloud.githubusercontent.com/assets/327411/26319729/6bdc531c-3f20-11e7-90d3-2f1c4b9c76a0.png)

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#125

**Comment by ramya-rao-a** [comment]
Thanks everyone for reporting this with the detailed examples, and sorry that I couldn't get to this earlier.

Once the upstream grammar is fixed, the fix will be pulled into VS Code as well

**Comment by ramya-rao-a** [comment]
Thanks to @50Wliu we have the fix!

This will be fixed in the Insiders build of May 23rd, 2017
