### ISSUE TITLE
Readme.md is inaccurate

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-go#94]
![image](https://cloud.githubusercontent.com/assets/5047891/11402148/a8b1e48c-9396-11e5-9b51-c4032687b181.png)

When a tool is missing the extension does not offer to install it for me.

![image](https://cloud.githubusercontent.com/assets/5047891/11402143/9e357c6c-9396-11e5-9eca-2c80e3b97ef3.png)

**Comment by lukehoban** [comment]
The actual "offer" is the green bar in the bottom right that says "Analysis Tools Missing".  Clicking that will pop up an offer to install all the missing tools at once.

**Comment by alexandrudima** [comment]
Oh, cool, sorry I didn't notice it
