### ISSUE TITLE
Make 'green' coverage optional

### ISSUE THREAD

**Issue by kode4food** [Microsoft/vscode-go#942]
Is it possible to not display the green highlight over covered code?  I'd prefer to only see code that's marked red (missing coverage).

**Comment by ramya-rao-a** [comment]
Its definitely do-able.

PRs welcome.

**Comment by kode4food** [comment]
@ramya-rao-a ok, I'll do it, thanks

**Comment by kode4food** [comment]
Please see #945 for the PR

**Comment by kode4food** [comment]
The change has been added as a result of #945 being merged.  Closing the issue.

Thank you

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update (0.6.60)

Thanks @kode4food !
