### ISSUE TITLE
gotype-live is reporting errors based off out-of-date file content

### ISSUE THREAD

**Issue by Taik** [Microsoft/vscode-go#943]
When using live error reporting, gotype-live sometimes returns errors based off out-of-date file content. It's very noticeable when switching between branches where an extra parameter was added to function/method signatures (in my case, I'm extending functions to take in `context.Context`). 

My current setup:
```
VSCode: Version 1.11.2 (1.11.2)
vscode-go: Version 0.6.59 
vim: 0.6.18
```

Live error config: 
```json
"go.liveErrors": { "enabled": true, "delay": 500 }
```

**Comment by ramya-rao-a** [comment]
That's weird. Live errors should really act on the live file :)

One thing to note is that live error reporting kicks in when you start making changes to the file.
Are you seeing this when you switch branches, but haven't edited the file yet?

cc @tylerb

**Comment by Taik** [comment]
I agree :)

Closing and opening the file does not display the errors right away, until I start typing.
The errors are not really related to the line at all, and for the most part points to another part of the code completely (another file). Here's an example:

![screen shot 2017-04-25 at 9 37 44 pm](https://cloud.githubusercontent.com/assets/175499/25414460/8c0435aa-29ff-11e7-9fc1-798f9ae627cc.png)

I opened the file and created a new line (L280), and the error started showing up.

**Comment by tylerb** [comment]
This is most likely related to the PR that was recently merged. This issue should go away once the next release of vscode-go comes out.

**Comment by ramya-rao-a** [comment]
The next release would be early next week which will have the fix for the issue of errors from other files showing up in the current file.

@Taik if you don't mind can you side load the Go extension from master (See https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#sideloading-the-extension) to confirm that the fix in master fixes your issue?

**Comment by Taik** [comment]
I just gave it a try, and it seems like it fixed it. Thanks for the awesome plugin!

**Comment by ramya-rao-a** [comment]
Thanks @Taik 
The credit for the live-error feature goes to @tylerb :)

**Comment by ramya-rao-a** [comment]
Fix is out in the latest update (0.6.60)

**Comment by tylerb** [comment]
Thanks much, @ramya-rao-a!!

**Comment by ramya-rao-a** [comment]
@wangxufire Please share a video/gif of the problem you are seeing. Preferably using a small simple code
