### ISSUE TITLE
Extension seems to force to true files.trimTrailingWhitespace

### ISSUE THREAD

**Issue by kmur911** [Microsoft/vscode-go#944]
Without the extension being installed/enabled I verified that files.trimTrailingWhitespace works as advertised in Visual Studio Code, deleting trailing whitespace on my current line upon file save, but by default not doing so since it defaults to false.  However, after installing this extension (and reloading to let it take effect) the setting seems to lose its control, and acts like files.trimTrailingWhitespace is always set to true, regardless of whether it's set to false by default, by user setting, or workspace setting. This is annoying when combined with auto-save, as it frequently deletes spaces out from under you while typing.

Steps to Reproduce:
1. Without Go extension verify that files.trimTrailingWhitespace setting works as advertised
2. Enable Go extension
3. Type a space at the end of a line of code, ctrl/cmd - s to save
4. See that space is removed, regardless of files.trimTrailingWhitespace setting

Go extension version 0.6.59

**Comment by ramya-rao-a** [comment]
That's the formatting which runs on save 

You can turn formatting off by setting `go.formatOnSave` to `false`.

**Comment by kmur911** [comment]
Thanks!
