### ISSUE TITLE
Call Stack limitied to 20

### ISSUE THREAD

**Issue by BlakeMScurr** [Microsoft/vscode-go#946]
If you run this code

```
package main

func main() {
	d := 30
	recursiveCall(d)
}

func recursiveCall(depth int) {
	if depth <= 0 {
		return
	}
	recursiveCall(depth - 1)
}
```

with a breakpoint on line 10, you can't access the value of d in the main function because it's too far down the stack. How can this be extended?

**Comment by ramya-rao-a** [comment]
Does it work when you run dlv from the command line?

**Comment by BlakeMScurr** [comment]
Yeah, I can print the stack trace at arbitrary depth using the command line with `stack <depth>` during debugging. I might just be missing the interface in vscode that lets you do the same thing.

**Comment by ramya-rao-a** [comment]
cc @roblourens

**Comment by roblourens** [comment]
Looks like we haven't implemented stack trace paging (but probably we should just hardcode a number larger than 20)

**Comment by ramya-rao-a** [comment]
@roblourens Can you add some pointers on how we go about doing that so that someone in the community can pick this up?

**Comment by roblourens** [comment]
VS Code asks for 20 frames at first, and we pass that along to Delve to get 20 frames

https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L574

Then VS Code can ask for the next page of frames 20-40, but it looks like there probably isn't a way to ask for that from Delve. So, someone could change that line to ignore args.levels from VS Code, and simply return 50 frames (or something).

However, someone would need to test it and make sure that it doesn't crash or slow down when exchanging info from 50 frames. Another option would be getting lots of frames from Delve, and implementing paging just between VS Code and the debug adapter.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest version of the Go extension (0.8.0)
