### ISSUE TITLE
Can I disable all warnings?

### ISSUE THREAD

**Issue by DeadNumbers** [Microsoft/vscode-go#948]

**Comment by ramya-rao-a** [comment]
Can you give examples of the warnings you would like to disable?

**Comment by DeadNumbers** [comment]
@ramya-rao-a 
>exported function ReadConfig should have comment or be unexported

>type photoId should be photoID

>don't use underscores in Go names; var LC_Message should be LCMessage

![screen](https://i.imgur.com/zAx57PH.png)

**Comment by ramya-rao-a** [comment]
You can set `go.lintOnSave` and `go.vetOnSave` to `false`
