### ISSUE TITLE
Code highlight Problem

### ISSUE THREAD

**Issue by chenhw2** [Microsoft/vscode-go#950]
```
type EXAMPLE struct {
	SubNet *net.IPNet
}

var e EXAMPLE
_, e.SubNet, _ = net.ParseCIDR("192.168.0.0/16")
```

![sp170428_175917](https://cloud.githubusercontent.com/assets/12322033/25524266/78fdce50-2c3c-11e7-9c20-2f2895b6fe8b.png)

Front ```_``` different from back ```_```

```
Versions
vscode-go: 0.6.59 - 4th April, 2017
vscode: 1.11.2
ubuntu 16.04
```

**Comment by ramya-rao-a** [comment]
The first `_` is getting the scope "source.go" and the second is getting "variable.other.assignment.go"

VSCode is using the Go grammar from https://github.com/atom/language-go/commit/6de3f61

The same can be seen in atom as well

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#121
