### ISSUE TITLE
"if block ends with a return statement..." suggestion when using assignment in IfStmt's SimpleStmt

### ISSUE THREAD

**Issue by skillian** [Microsoft/vscode-go#951]
I've been looking through the issues to see if this is a repost or not, but I haven't found anything; please let me know either if this is a duplicate or the wrong place to put this.

I'm refactoring a function so that it looks like this:
```
func screenRect() (image.Rectangle, error) {
	if hDC, err := getDC(0); err == nil {
		defer releaseDC(0, hDC)
		x := getDeviceCaps(hDC, HORZRES)
		y := getDeviceCaps(hDC, VERTRES)
		return image.Rect(0, 0, x, y), nil
	} else {
		return image.Rectangle{}, err
	}
}
```
And VSCode is telling me that because the if block ends with a return statement, remove the else block and outdent its contents.  The suggestion doesn't seem to recognize that the else's return statement refers to a variable introduced by the SimpleStmt part of the if statement and is invalid when outdented.

**Comment by ramya-rao-a** [comment]
Looks like this is a linting error. Can you confirm? Set `go.lintOnSave` to `false` to ensure that this is a linting error and not vetting error

If yes, then the issue needs to be logged for the linting tool you are using.
