### ISSUE TITLE
go install on save 

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#953]
Hello,

I recently tried moving to [mdempsky/gocode](https://github.com/mdempsky/gocode) due it being faster and also nsf's version being broken on go tip.

However it doesn't have the `autobuild` option, which leads to out of date completion when editing sub-packages.

Is there any way to make `"go.buildOnSave": true,` run `go install` when it's not a main package?

**Comment by OneOfOne** [comment]
This is related to https://github.com/mdempsky/gocode/issues/13

**Comment by OneOfOne** [comment]
Found https://github.com/Microsoft/vscode-go/issues/673

**Comment by ramya-rao-a** [comment]
@OneOfOne I opened an issue https://github.com/nsf/gocode/issues/452 for gocode being broken on go tip.

But since I don't use go tip myself, I don't have details to add.

If you don't mind, can you please update https://github.com/nsf/gocode/issues/452 with any details that you have
