### ISSUE TITLE
Renaming symbols fails due to bad GOROOT

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode-go#955]
When I attempt to rename a symbol, it always fails with the following message:

> Rename failed: /Users/joshtepper/work/go/src/foo/some/file.go:38:2: could not import context (cannot find package "context" in any of: /Users/joshtepper/work/go/src/foo/vendor/context (vendor tree) /usr/local/Cellar/go/1.6.2/libexec/src/context (from $GOROOT) /Users/joshtepper/work/go/src/context (from $GOPATH)) /Users/joshtepper/work/go/src/foo/some/other_file.go:12:2: could not import context (canno...

Note that the package that it is looking for is `context` which wasn't introduced until 1.7.  For some reason, it looks like it is incorrectly looking in `/usr/local/Cellar/go/1.6.2/libexec/src/context`.  The error message says "(from $GOROOT)" but GOROOT is not set (`echo $GOROOT` gives empty string in the shell that started code)!  Brew info on my machine shows that three versions of go are installed and that the one in use is 1.7.4_1:

```
$ brew info go
go: stable 1.8.1 (bottled), HEAD
The Go programming language
https://golang.org
/usr/local/Cellar/go/1.6.2 (5,778 files, 325.3MB)
  Poured from bottle on 2016-07-06 at 20:30:37
/usr/local/Cellar/go/1.7 (6,435 files, 250.6MB)
  Poured from bottle on 2016-08-24 at 19:26:59
/usr/local/Cellar/go/1.7.4_1 (6,438 files, 250.7MB) *
  Poured from bottle on 2017-01-01 at 21:51:38
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb
```

Further, when I delete the older versions entirely, leaving only 1.7.4_1, it fails again, looking again in `/usr/local/Cellar/go/1.6.2/libexec/src/...` (a path which now doesn't exist) and this time failing on the log package -- presumably because no system packages can be found and this is the first one encountered.

I am confident that I do not set GOROOT

Honestly, I'm not sure why I need the source for the built in packages at all.  If I can build without the source (presumably by depending on the object files provided by my installation -- e.g., on my system located here: `/usr/local/Cellar/go/1.7.4_1/libexec/pkg/darwin_amd64/...`), then it seems like the tooling involved in renaming a symbol also shouldn't need the source for these packages either.

**Comment by ramya-rao-a** [comment]
@josh-tepper What happens when you run `gorename` from the shell that started code? Does it work?

What do you get when you run `go env GOROOT GOTOOLDIR` ?

**Comment by josh-tepper** [comment]
```
$ go env GOROOT GOTOOLDIR
/usr/local/Cellar/go/1.7.4_1/libexec
/usr/local/Cellar/go/1.7.4_1/libexec/pkg/tool/darwin_amd64
```

gorename, OTOH, gives the same errors that I saw in vscode:

> could not import ... /usr/local/Cellar/go/1.6.2/libexec/src/log (from $GOROOT) ...

**Comment by ramya-rao-a** [comment]
Since `gorename` is giving the same error in the shell as well, I'd suggest to open an issue in the repo for `gorename`

It might be an environment issue or an issue with gorename itself that it is picking up the wrong Go version

**Comment by josh-tepper** [comment]
It turns out that updating/re-building go-rename solves the issue.

I apologize for raising a spurious issue -- I didn't realize that gorename was the underlying tool, so I didn't previously know what to update.  Closing issue.
