### ISSUE TITLE
Get wrong when debug

### ISSUE THREAD

**Issue by AllenField** [Microsoft/vscode-go#956]
* System: `Mac OS X 10.11.4`
* VS code version: `1.11.2`
* Go version: `go version go1.8.1 darwin/amd64`
* Go extension version: `lukehoban.go 0.6.59`

I got this on debug:

```
2017/05/03 16:10:09 server.go:73: Using API v1
2017/05/03 16:10:09 debugger.go:89: launching process with args: [/Users/fubai/go/src/tour/debug]
could not launch process: exec: "lldb-server": executable file not found in $PATH
Process exiting with code: 1
```
I don't know if this is the right place to ask here? If not, please point me the right place.

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode-go/issues/947#issuecomment-298916693 describes the same exact issue. It got resolved for @zcmack by re-installing the Xcode tools. See https://github.com/Microsoft/vscode-go/issues/947#issuecomment-298950017

Can you try the same?

If that doesn't work, then you can follow #947 

Closing this issue in favor of #947

**Comment by AllenField** [comment]
It worked for me! 

Thank you

**Comment by HanderLo** [comment]
Thanks, Great Answer.
