### ISSUE TITLE
Completion List priority

### ISSUE THREAD

**Issue by hu6360567** [Microsoft/vscode-go#960]
It seems keyword alway has a higher priority than its corresponding snippet.
For example, when I type "func", I cannot expand snippet by "tab".

How can I get snippet before the simple keyword? or select snippet without arrow key?
![image](https://cloud.githubusercontent.com/assets/1241597/25704434/c2c69690-311c-11e7-909e-5febce4a40d6.png)

**Comment by ramya-rao-a** [comment]
The setting `editor.snippetSuggestions` controls whether snippets are shown in suggestion list and where 
 (top, bottom, inline) they should appear. `bottom` is the default value.

Another setting you can try playing with is `editor.tabCompletion`
