### ISSUE TITLE
v0.6.60 availability on VS Marketplace

### ISSUE THREAD

**Issue by calvn** [Microsoft/vscode-go#961]
I noticed that v0.6.60 was released 16 hours ago, but the VS Marketplace still shows v0.6.59 as the latest available version. How long does it take to propagate the package so that it is downloadable?

**Comment by ramya-rao-a** [comment]
0.6.60 was not released yesterday, it was only tagged and I had made a draft for the release.

The actual release was just now in the past hour, you should be able to see the new version int he marketplace.

Thanks!

**Comment by ramya-rao-a** [comment]
But looks like the timestamp says it was released 20 hrs ago.

Hmm... will keep that in mind next time
