### ISSUE TITLE
New Code Lens Feature Trashes CPU On Scroll

### ISSUE THREAD

**Issue by thedillonb** [Microsoft/vscode-go#963]
The new code lens feature, while awesome, is going to town on my CPU when simply scrolling through go files. The GURU process spawns and immediately eats into available CPU:

![screen shot 2017-05-04 at 4 28 49 pm](https://cloud.githubusercontent.com/assets/1644068/25723696/18e89d4c-30e7-11e7-9f7b-cd4b6d13aca6.png)

This results in a choppy scroll experience and only subsides when left alone for a while. My only course of action to mitigate this is to add:

```javascript
"[go]": {
        "editor.codeLens": false
    }
```

I am running on OSX 10.12.1 on the latest VS Code and VSCode-Go releases.

**Comment by ramya-rao-a** [comment]
yes thats crazy, I assumed that VS Code will re-use the data while scrolling if there is no change to the document.

But looks like even a slight scrolling is resulting in vscode asking for references all over again.

I'll look into what options we have.

Thanks for reporting!

Meanwhile you can set `go.referencesCodeLens.enabled` to false to disable this.

**Comment by goenning** [comment]
What about disabling this feature by default and leave as experimental while it's not performing as expected? I guess it's causing more harm than good at the moment.

**Comment by ramya-rao-a** [comment]
The issue was that a new codelens object was being returned after being resolved due to which the cached result was always getting invalidated.

With the commit above, the references will only be recalculated when there is change followed by scroll in the document.

This still may be expensive especially in Windows where guru is known to be slow.

Will consider disabling by default.

**Comment by ramya-rao-a** [comment]
Alright, the perf issue while scrolling without making any change to the document is fixed.
References is disabled by default.
And the setting to use to enable it looks like this:
 ```json
        "go.enableCodeLens": {
            "references": false,
            "runtest": true
        }
  ```

@thedillonb Do give it a try
