### ISSUE TITLE
Configure debug/run links in the editor

### ISSUE THREAD

**Issue by whitlockjc** [Microsoft/vscode-go#964]
The latest update added a ton of new features, thank a lot.  I wanted to cleanup some of the editor cluster and I found `go.referencesCodeLens.enabled` but I don't see any way to turn off the debug/run links for debugging/running tests.  Are there plans to make it configurable to see these in the editor?

**Comment by ramya-rao-a** [comment]
@ironcladlou had the same question :) https://github.com/Microsoft/vscode-go/pull/937#issuecomment-299284015

As concluded in the linked thread, you can turn off all codelens by setting `editor.codeLens` to `false`
You can also turn off all codelens only in Go files, by adding the language scope to the same setting.

Based on the feedback, we can add the setting in the next update

**Comment by goenning** [comment]
You can disable it by setting ’editor.codeLens’ to false.

**Comment by whitlockjc** [comment]
I apologize.  I searched but didn't see anything that seemed related.  I'll close as a duplicate.

**Comment by ramya-rao-a** [comment]
Not at all, that discussion was in a PR. We can still use this one to track whether we want to include settings for each codelens type

**Comment by ramya-rao-a** [comment]
Alright, I didnt want to drag the discussion out too long.

Since my main concern was not having multiple settings, that is now solved by a single setting

 ```json
        "go.enableCodeLens": {
            "references": false,
            "runtest": true
        }
 ```

Problem solved.

Happy Coding everyone!

**Comment by whitlockjc** [comment]
I love that approach.  :)  I like the ability to turn it off completely, as linked in the previous issue, but at some point it might be nice to cherry-pick the ones I _do_ like and your new approach solves this.  Thank you.  :)
