### ISSUE TITLE
Old version of extension not replaced properly during update

### ISSUE THREAD

**Issue by Gaffney** [Microsoft/vscode-go#965]
My VSCode was working fine and was in a happy state.

Now after updating, every time I open a Go file or make a change in a Go file I get the popup:
`vscode "Cannot find "go" binary. Update PATH or GOROOT appropriately"`.

But go is on the path (in `/usr/local/bin`, which contains the symlink: `go -> ../Cellar/go/1.8.1/bin/go`), verified via the built-in terminal in VSCode:
```
gaffney:repo.git gaffney$ which go
/usr/local/bin/go
```
----------
- **Mac OSX**: 10.12
- **VSCode**: 1.12
- **vscode-go**: 0.6.60

**Comment by Gaffney** [comment]
Looks like the old version was not cleaned up.
```
ls ~/.vscode/extensions/
lukehoban.Go-0.6.39/        lukehoban.go-0.6.60/
```
Somehow `0.6.39` was installed as root? (Weird because I never sudo...)

That said, I imagine it should not have "successfully" updated without first deleting the old one.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode#25953
