### ISSUE TITLE
format can not use

### ISSUE THREAD

**Issue by polariseye** [Microsoft/vscode-go#967]
hello,
  i use vs code with version 7.4.0 and go with go 1.8. but i can't use format

**Comment by ramya-rao-a** [comment]
@polariseye 
- What is the version of the Go extension that you are using?
- Can you right-click and choose "Format Document"? Does that format your code?
- If that still doesnt work, can you share a gif to show what you are experiencing?

**Comment by ramya-rao-a** [comment]
Closing as we havent heard back from @polariseye  in a while
