### ISSUE TITLE
Comments in import block not getting the right color

### ISSUE THREAD

**Issue by zoobenthos** [Microsoft/vscode-go#969]
The comments in import block is constant and terribly (as it looks) problem.
It sometimes works right in beginning of the comment line, but is not works right before the module string, etc
Sorry, but it is simply bullshit

**Comment by ramya-rao-a** [comment]
> The comments in import block is constant

What comments?

> It sometimes works right in beginning of the comment line,

What works right in the beginning of the comment line?

Your issue description is not clear.
Can you please elaborate?

**Comment by zoobenthos** [comment]
In previous version this bug was partially fixed but in current version that is appears again.
![example](http://i.imgur.com/TIsDcI9.png)

**Comment by ramya-rao-a** [comment]
Thanks @zoobenthos 
We will look into this.

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#119
