### ISSUE TITLE
Documentation tooltips for variables and instance methods

### ISSUE THREAD

**Issue by wolfgangmeyers** [Microsoft/vscode-go#970]
I noticed that documentation for top-level functions show up when you hover over a reference:
```
// doSomething really does something
func doSomething() { ... }
```
But when the same docs are added to an exported variable or instance method:
```
// MyThing can has a doSomething method!
var MyThing = &MyType{}

// doSomething really does something
func (s *MyType) doSomething() { ... }
```
I do not see the same kind of documentation. Would this be hard to implement?

It might also be nice to have documentation tooltips for non-exported functions and variables when working in the same package.

**Comment by ramya-rao-a** [comment]
That I believe is the limitation of the default tools (godoc) we use for this feature.

Can you try changing your `go.docsTool` setting to `gogetdoc` and try again?

**Comment by wolfgangmeyers** [comment]
That worked like a charm! Thanks!!
