### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined while restarting debugging

### ISSUE THREAD

**Issue by renannprado** [Microsoft/vscode-go#973]
This happens when you to try to restart a debugging session, but your code doesn't compile.

Steps to reproduce:

1 - start debugging
2 - introduce a compilation error in your code
3 - try to restart debugging
4 - `Cannot read property 'toLowerCase' of undefined` is shown

**Comment by ramya-rao-a** [comment]
Thanks! I can repro. Will look into it.

**Comment by renannprado** [comment]
@ramya-rao-a I just tried to do the same thing again and couldn't reproduce it. So I guess it's fixed?

**Comment by ramya-rao-a** [comment]
Well, its been a while and honestly I don't remember :)

Maybe some of the other changes done around the debugging code might have fixed it.

Since you are not able to repro this, can we close this issue?

**Comment by renannprado** [comment]
Yep
