### ISSUE TITLE
when i use dot import in golang edit,can not jump to the dot package(method and constant)

### ISSUE THREAD

**Issue by Anteoy** [Microsoft/vscode-go#975]
When i use dot import in golang edit,can not jump to the dot package,my vscode version is 1.10.2 by ubuntu,go plugin version is 0.6.61 (lukehoban.Go)

**Comment by ramya-rao-a** [comment]
Duplicate of #496
Please follow the instructions in #496 to get the solution for this issue.

**Comment by Anteoy** [comment]
It worked for me!Thank you
