### ISSUE TITLE
auto-import no longer works after v0.6.61

### ISSUE THREAD

**Issue by chrisolsen** [Microsoft/vscode-go#976]
Now I just get the line flagged and when I click on the lightbulb icon the import will be made, but nothing works on save anymore.

Also if I remove a method call of a certain lib, then save it no longer auto removes the import.

**Comment by ramya-rao-a** [comment]
Can you share your settings for `go.formatOnSave` and `go.formatTool` ?

**Comment by chrisolsen** [comment]
formatOnSave: true
formatTool: goreturns

**Comment by ramya-rao-a** [comment]
The auto-import and removal of unused import is done by the formatting tool which is run on save as long as `go.formatOnSave` is set to `true`

Looks like formatting is not being triggered in your case after save.

Other features that run on save are build, lint and vet.

Do you get build errors or linting warnings on save ?

**Comment by chrisolsen** [comment]
I have `lintOnSave` turned off due to a previous issue resulting in a huge slow down, but `vetOnSave` is still enabled.

I don't get any errors. The normal output I get on save is the following, which does show that `goreturns` is not being run

```
Finished running tool: C:\Go\bin\go.exe tool vet c:\Users\Chris\Go\src\quicksort\leaguesmart\src\root_handler.go

Finished running tool: C:\Go\bin\go.exe build -i -o C:\Users\Chris\AppData\Local\Temp\go-code-check -tags "" quicksort\leaguesmart\src
```

Running `goreturns`, `goimports` or `gofmt` from the command line on a file outputs the formatted text to the terminal properly formatted, so as you said, the formatting isn't being triggered on save.

**Comment by ramya-rao-a** [comment]
The formatting tool when run doesn't show anything in the output window.

Does Right-click -> Format Document, format the document?

**Comment by chrisolsen** [comment]
Calling the `Format Document` doesn't work either, but setting `go.useDiffForFormatting` to `false` fixes the problem.

**Comment by ramya-rao-a** [comment]
Cool!

If `go.useDiffForFormatting` is not set to `false` then the Go extension runs the formatting tool with the `-d` flag. The formatting tool returns the diff, and then the extension applies the diff on the editor.

If `go.useDiffForFormatting` is set to `false`, the formatting tool replaces the file on disk.

So my next question would be if you can run `goreturns` from the command line with the `-d` flag and if that returns expected diff.
If yes, then the bug is in the Go extension for not parsing and understanding the diff output properly.

**Comment by chrisolsen** [comment]
Running `goreturns -d filename.go` only returns `diff .\filename.go gofmt/.\filename.go`, where as running `goreturns` without the `-d` does return the formatted output.

**Comment by ramya-rao-a** [comment]
We did see the same before in https://github.com/Microsoft/vscode-go/issues/520#issuecomment-253919509 and logged an issue with goreturns https://github.com/sqs/goreturns/issues/28

Can you try removing the `goreturns` you have and do a fresh `go get -u github.com/sqs/goreturns` ?

Other than that as concluded in https://github.com/Microsoft/vscode-go/issues/520#issuecomment-277493885, there is nothing much we can do from the extension side
