### ISSUE TITLE
Pause command doesn't work

### ISSUE THREAD

**Issue by renannprado** [Microsoft/vscode-go#978]
After starting a debug session, if you hit pause button, nothing happens.
This is important if you want to add breakpoints after running the application.
I was debugging the plugin and saw that `pauseRequest` was never called. So I wonder whether this is a bug in this plugin or in the whole vscode.

**Comment by renannprado** [comment]
@ramya-rao-a is this an issue with the plugin or with vscode? 
if it is a problem with the plugin, maybe I can try to help fix it

**Comment by ramya-rao-a** [comment]
I dont have a proper repro for this. Can you share a sample code with repro steps?

cc @roblourens

**Comment by renannprado** [comment]
So here are the steps to reproduce:

1. start the debugging session with no breakpoints
2. try to put a breakpoint (it won't work, the requests to create the breakpoint get stuck in delve)
2.1. the only way to make the breakpoint to be created in that case would be if we send `Halt` to delve by clicking in pause button
3. click in the pause button nothing happens...

Sample program

```go
package main

import (
	"fmt"
	"sync"
	"time"
)

func main() {
	wg := &sync.WaitGroup{}

	wg.Add(1)

	go func() {
		for {
			fmt.Println("I'll just take a nap for a second... ZZZzz....")
			time.Sleep(time.Second)
		}
	}()

	wg.Wait()
}
```

**Comment by ramya-rao-a** [comment]
Thanks for the steps @renannprado 

cc @roblourens

**Comment by roblourens** [comment]
When debugging starts, vscode sends a ThreadsRequest. goDebug.ts sends a ListGoroutines request to Delve, but Delve never responds. So then when you click Pause, vscode doesn't know which thread to pause, and never sends the pause request over. I suppose we need to figure out whether we're caling ListGoroutines at a bad time, whether it's a Delve bug, or if we should just add a timeout for it.

**Comment by roblourens** [comment]
And as for setting the bp after launch, I don't know whether it should be possible to set a BP when Go is in a loop like that. I can't do it with Delve at least.

**Comment by renannprado** [comment]
@roblourens yes, it is possible (will later update an asciinema session to show)
the only way to set a breakpoint in this case would be to use the command `Halt` (using the pause button in vscode), then everything is paused on the process and you are free to set the breakpoints

**Comment by muravjov** [comment]
Hi, I searched why I cannot set breakpoints as verified in VSCode while the program is running (after continue) and found out that you cannot set breakpoints in delve until you stop/halt debuggee program via delve.

That is, if you try to set a breakpoint in vscode while the debuggee program runs, the request to delve CreateBreakpoint hangs forever (till debugging session' end) and even F6 (Pause) will not work.
**Workaround**: before setting breakpoint you hit F6 (Pause), then set breakpoint, then Continue (F5) and everything is ok.

So I suggest to make start/stop requests to delve for every breakpoint being set if debuggee is running. That is, to call pauseRequest()/continueRequest() in setBreakPointsRequest() , see at

https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L530

I've checked out Goland, https://www.jetbrains.com/go/ , and found out that they do just stop/start in such situations. Here is the log from delve (patched by me) under Goland control, showing that delve was started and stopped only for setting breakpoint: 

```
2018/01/27 23:44:22 server.go:265: rpc command: RPCServer.Command, version 2
2018/01/27 23:44:22 server.go:292: rpc command, is sync: false
2018/01/27 23:44:22 debugger.go:490: Debugger.Command: start
2018/01/27 23:44:22 debugger.go:498: halting
2018/01/27 23:44:23 debugger.go:562: Debugger.Command: stop
2018/01/27 23:44:23 debugger.go:562: Debugger.Command: stop
2018/01/27 23:44:23 server.go:265: rpc command: RPCServer.CreateBreakpoint, version 2
2018/01/27 23:44:23 server.go:292: rpc command, is sync: true
2018/01/27 23:44:23 debugger.go:284: CreateBreakpoint: 1
2018/01/27 23:44:23 debugger.go:303: CreateBreakpoint: 2
2018/01/27 23:44:23 debugger.go:328: CreateBreakpoint: 3
2018/01/27 23:44:23 debugger.go:339: CreateBreakpoint: 4
2018/01/27 23:44:23 debugger.go:348: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x8b8188, File:"/home/ilya/opt/programming/g-core/balancer/src/balancer/master.go", Line:95, FunctionName:"balancer.SendCommandTo", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2018/01/27 23:44:23 server.go:265: rpc command: RPCServer.Command, version 2
2018/01/27 23:44:23 server.go:292: rpc command, is sync: false
2018/01/27 23:44:23 debugger.go:490: Debugger.Command: start
2018/01/27 23:44:23 debugger.go:509: continuing
```

Also, I've checked https://github.com/derekparker/delve sources and found out why one should not request CreateBreakpoint command while debuggee is working: every command except halt (= Pause in vscode) try to lock `processMutex` before performing its action, but if it is already locked (while debuggee runs) so the request hangs forever:

```
// CreateBreakpoint creates a breakpoint.
func (d *Debugger) CreateBreakpoint(requestedBp *api.Breakpoint) (*api.Breakpoint, error) {
	d.processMutex.Lock()
	defer d.processMutex.Unlock()
...
```
See at https://github.com/derekparker/delve/blob/master/service/debugger/debugger.go#L284

**Comment by muravjov** [comment]
I am not so good with TypeScript and those promises so I cannot make PR for my suggestion myself, the right way. Please help with that.

**Comment by ramya-rao-a** [comment]
@muravjov Thanks for the investigation!

> So I suggest to make start/stop requests to delve for every breakpoint being set if debuggee is running. That is, to call pauseRequest()/continueRequest() in setBreakPointsRequest() 

This would work assuming that `pauseRequest()` itself works as expected and halts delve.
As @renannprado and @roblourens has discussed above, that doesnt seem to be happening.
Are you able to pause the program and then set breakpoints?

**Comment by muravjov** [comment]
Yes, I am if I do it in right order: at first pause the program, then set breakpoints.
Other way it hangs forever (till debug session end).
And I understand why - if you set breakpoint while debuggee runs, then you hit deadlock - see d.processMutex.Lock()

**Comment by ramya-rao-a** [comment]
I am not able to pause to begin with. Can you share the program you are using? I was using the `outyet` program from https://github.com/golang/example/tree/master/outyet

**Comment by ramya-rao-a** [comment]
@muravjov 

> The next ThreadsRequest never returns , so no next commands, including Pause, ever has chance to be invoked.

I can see this happening when I try to pause a running program which never had any breakpoints

If I have a breakpoint, it gets hit, I continue, and then after a while try to pause, then I see the `PauseRequest` being made, delve halting, a bunch of thread requests being fired.

> So, workaround is simple now: always set a breakpoint and when control hits it deadlock is over.

How do we determine when the deadlock is hit?

**Comment by muravjov** [comment]
@ramya-rao-a 
> How do we determine when the deadlock is hit?
From the delve's side you are to find out whate all goroutines are doing now = their stacktraces.
If you rebuild delve with a couple of changes mentioned here https://stackoverflow.com/a/19145992 , then you may get all stacktraces with this command:

```
curl http://localhost:9100/debug/pprof/goroutine?debug=2
```

On Linux and MacOs you may kill go program with signal SIGABRT with the same effect, rebuild is not needed.

**Comment by dariopb** [comment]
Is there any workaround for the Pause -> set breakpoint -> Continue issue?  I'm running vsc 1.22.2 with go extension 0.6.78 and still hitting the issue: everything goes fine until I "Pause", then I can set a breakpoint (breakpoint is "verified" it seems) but then "Continue" does nothing and the program doesn't keep running.

**Comment by primalmotion** [comment]
same issue here.  

I have identified the following

1) if I start the debugger without any breakpoint. then hit pause. nothing happens (not even a trace in vscode go). game over

2) if I start the debugger with an initial breakpoint that it hits, then click on continue, then hit pause, I see the halt message sent to delve, and the debugger seems to have halted, I can set breakpoints, but vscode never noticed it is halted, and the pause button never turns to a continue button. game over

3) if I start the debugger with an initial breakpoint that it *doesn't* hit, same as 1

**Comment by ariel-bentu** [comment]
Hi,
I managed to get this working on my macos vscode, by adding pause before setting a breakpoint and continue after it is set:
in line 704, add this line
        this.pauseRequest(null)

in line 728, insert this before:
            this.continueRequest(null)

For me, finally it allows setting new breakpoints while debugee is running.
I hope you find this value-able and add this

**Comment by ramya-rao-a** [comment]
The Pause feature now works in the latest update to the Go extension (0.9.0)
Huge thanks to the amazing @xiphon who made this happen!
