### ISSUE TITLE
"Test Function At Cursor" not work

### ISSUE THREAD

**Issue by silentred** [Microsoft/vscode-go#981]
- VScode version
1.12.1

- plugin version
0.6.61

I updated go-outline tool, and there are "run test | debug test" button above TestFunction. But the original "Test Function At Cursor" command does not work now.
Then I tried to install/update all go tools with a command. Nothing changes.

**Comment by goenning** [comment]
Which OS? I just tried on my Windows with same versions and it worked.

Are you triggering the command by using the command bar? Can you try to bind a keyboard shortcut to this command and run it this way?

**Comment by ramya-rao-a** [comment]
Thanks for reporting @silentred 

This is a regression. While adding the codelens support, there was a missing null/undefinied check.

Pushed https://github.com/Microsoft/vscode-go/commit/2e910389736160166ef721f14d11b95e37197a4f to fix it.

The fix will be out in the next update which will be in a week or 2.

Until then, as a work around you can use the codelens or bind a shortcut for the command

**Comment by ramya-rao-a** [comment]
The fix is now available in the latest update (0.6.62)
