### ISSUE TITLE
Build complete workspace on save

### ISSUE THREAD

**Issue by aeronite** [Microsoft/vscode-go#982]
I'm running the latest golang plugin in vscode on linux mint.
Everything works great as long as I open the editor exactly on the GOPATH however when I reopen the editor on a specific project somewhere inside GOPATH the plugin no longer detects problems on save

**Comment by ramya-rao-a** [comment]
@aeronite Do rest of the features like the below work when you open a specific project?

- Go to Definition
- Formatting (Right-click -> Format Document)
- Find all references 
- Symbol search

Is there any output in the output window (Choose "Go" channel" in the drop down in the output window)

**Comment by aeronite** [comment]
Hi @ramya-rao-a  thanks for the quick reply!

- All of the other features you mentioned still work fine inside a specific proj.
- Running `Go: Current GOPATH` gives me the correct GOPATH

Heres exactly whats happening:
I have a function  called 'Query' in package 'mypackage1', I use this function in 'myPackage2'.
If I change the func name to Query1 I see no indication of an error inside 'myPackage2' If I try to click on the 'Query' there to jump to def it doesn't let me anymore.
When I try actually run my code obviously the compile fails.

The Go output channel doesn't show anything strange during this time:

```
Finished running tool: /home/aharon/go/bin/golint

Finished running tool: /usr/local/go/bin/go tool vet /home/aharon/go/src/github.com/totango/monitoringapi/pipelines/pipeline_api.go

Finished running tool: /usr/local/go/bin/go build -i -o /tmp/go-code-check -tags "" github.com/totango/monitoringapi/pipelines
```

**Comment by ramya-rao-a** [comment]
After renaming the function in `mypackage1`, can you make a small edit and save the file in `myPackage2` which uses the function and then see if the error shows up?

The `go build` that we run on save is run only on the package where the change is being made. In your case this is `myPackage1`. Build is run on `myPackage2` only if there was a change>save in a file belonging to `myPackage2`

**Comment by aeronite** [comment]
Thanks! That was the issue that was confusing me, so everything's fine.
If that's the case though, would you consider an option to build all packages (in project context) on save?
Go's super fast compile times should mean that this won't affect user experience. It will make refactoring much more intuitive.

**Comment by ramya-rao-a** [comment]
#830 attempted to do something similar.

@mattblagden ping ping

**Comment by ramya-rao-a** [comment]
In the latest version of the Go extension (0.6.62) you can now run build/vet/lint on the whole workspace as well
