### ISSUE TITLE
Can't load package error on main package in src/cmd folder

### ISSUE THREAD

**Issue by josephspurrier** [Microsoft/vscode-go#984]
I'm on OSX. This looks like a behavior with go build and not with vscode-go. If there is a main package in the src/cmd folder or a subfolder, it will ignore the GOPATH and will look in libexec.

This is error will show up when go.buildOnSave = true.

This command builds fine:
laptop:~/godev/workspace/src go build cmdd/another

This command throws an error:
laptop:~/godev/workspace/src go build cmd/another
can't load package: package cmd/another: open /usr/local/Cellar/go/1.8.1/libexec/src/cmd/another: no such file or directory

A way to solve this would be to add ./ to the front of the package to let build know it's local. I don't know if this would break any current functionality.

**Comment by ramya-rao-a** [comment]
@josephspurrier You are comparing `laptop:~/godev/workspace/src go build cmdd/another` and `laptop:~/godev/workspace/src go build cmd/another`

I don't see the difference between the two other than an extra `d` in `cmdd` which I think is a typo.

Can you share the two build commands?

**Comment by josephspurrier** [comment]
Sorry, I should have been more clear. I did some more research and the cmd folder in the root of the src directory is a special folder that the Go internal tools see as internal. I added a "d" to the end to demonstrate that anything other than "cmd" works properly.

To reproduce, place a main.go file (any hello world application is fine) in each of the directories:
src/cmdd/another/main.go
src/cmd/another/main.go

These are the build commands if you run them manually:
go build cmdd/another
go build cmd/another

The first build command (go build cmdd/another) will work properly, but the second one will not (go build cmd/another).

**Comment by ramya-rao-a** [comment]
@josephspurrier Thanks for clarifying! i can repro it now.

cc @rakyll @campoy for more input on why import paths beginning with `cmd/` get treated differently 

Based on their and we can then discuss what is the best course of action here.

**Comment by rakyll** [comment]
I don't know/remember why this restriction exists but VS Code shouldn't do anything to change this behavior.

```
$ go help packages

Import paths beginning with "cmd/" only match source code in
the Go repository.
```

I asked relevant people why we are restricted to GOROOT with "cmd/" import paths and will update you once I have an answer.

**Comment by rakyll** [comment]
I learned that this restriction exists for the connivence of the GOROOT developers.

`go install` cmd/compile builds GOROOT/src/cmd/compile and replaces the go binary. It is less tedious than having to run ./make.bash every time. This is going to make my life better :)

So, there is nothing for vscode-go to do here. This a go tool restriction unless the go tool removes the restriction.

**Comment by josephspurrier** [comment]
Ah good to know! We have a corporate application that we built and tried placing all our microservices using the cmd/appname convention. We renamed the folder to app to prevent the conflict. I'm fine with closing this ticket, just good to know the reason! Thanks! Great tool by the way, my team loves it!

**Comment by ramya-rao-a** [comment]
@josephspurrier Thanks! Do let us know if you/your team has any other feedback via the gitter channel or twitter

**Comment by gljubojevic** [comment]
However.. 
If vscode would prepend "./" to path during build it would avoid confusion and avoid errors of this type e.g.
```
Finished running tool: /usr/local/bin/go build -o /var/folders/gg/glq0fl_d2s526bnmcvnsqk9r0000gn/T/go-code-check -tags "" -ldflags=-s cmd/dbi
can't load package: package cmd/dbi: open /usr/local/Cellar/go/1.8.1/libexec/src/cmd/dbi: no such file or directory
```

Build command like this works:
`/usr/local/bin/go build -o /var/folders/gg/glq0fl_d2s526bnmcvnsqk9r0000gn/T/go-code-check -tags "" -ldflags=-s ./cmd/dbi`

Note prepended "./" to build path.

Same works from terminal
`# go build cmd/dbi
`
Fails..
`# go build ./cmd/dbi
`
Works fine

**Comment by ramya-rao-a** [comment]
The reason we don't use relative paths like that is to make the symlinks work. See #846
