### ISSUE TITLE
Fail to connect to debugger

### ISSUE THREAD

**Issue by mpvl** [Microsoft/vscode-go#986]
I've used delve successfully with vscode in the past. But on my recent install on a new laptop, I'm getting the following error:

2017/05/10 15:41:14 server.go:73: Using API v1
2017/05/10 15:41:14 debugger.go:89: launching process with args: [./debug.test -test.run TestCodec]
could not launch process: dial tcp :50889: getsockopt: connection refused
Process exiting with code: 1

VSCode: 1.12.1
Delve: 0.12.2
Go extension: 0.6.61

**Comment by ramya-rao-a** [comment]
How did you install delve? And what platform are you on?

I recently saw this issue when I installed delve on Mac from master using brew.
Didn't see it after I installed the stable version

**Comment by mpvl** [comment]
I've installed it using go get -u and running make install on a Mac.

**Comment by mpvl** [comment]
I get the same when running make install from delve-0.12.2.

**Comment by mpvl** [comment]
Which version is known to work with the given Go extension and VSCode version?

**Comment by cyc115** [comment]
confirm same error on Delve Debugger
Version: 1.0.0-rc.1
Build:

**Comment by ramya-rao-a** [comment]
@mpvl If you are using Mac, then I suggest you install delve using brew as instructed here: https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md#via-homebrew

This way you will get the stable version

**Comment by alexanderGalushka** [comment]
confirm the issue

**Comment by JamesOwenHall** [comment]
I have tried both installation methods, in both cases I'm getting the same `could not launch process: [...] getsockopt: connection refused` message.

**Comment by ramya-rao-a** [comment]
@derekparker Any ideas based on the above error message?

**Comment by cyc115** [comment]
I know this is not a longterm solution but for those that needs it :Try
reverting back to 0.12 , worked for me

**Comment by mpvl** [comment]
I confirm that using 1.0.0 was the issue. Had the wrong path when reverting to 0.12 before.

**Comment by JamesOwenHall** [comment]
Yup, 0.12.2 works.

**Comment by dt** [comment]
Looks like delve has updated their homebrew formula so it is now installing `1.0.0-rc1` rather than 0.0.12, so this now happens even if you install delve using brew as instructed above here and elsewhere in the docs.

**Comment by joneskoo** [comment]
@dt Confirmed 1.0.0-rc1 from homebrew didn't work for me, `brew unlink delve && brew install --HEAD go-delve/delve/delve` seems to work better. No more error from dial.

With the 1.0.0-rc1 I did get the prompt and accepted it, so it's not that in my case. I got the error "could not launch process: dial tcp :50889: getsockopt: connection refused" with the port changing earlier.

**Comment by dt** [comment]
Based on https://github.com/derekparker/delve/issues/836 and https://github.com/derekparker/delve/issues/838, it sounds like the bug is in delve 1.0.0-rc1 but has since been fixed in master.

Upgrading from `1.0.0-rc1` to HEAD via `brew unlink delve && brew install go-delve/delve/delve --HEAD` fixed it for me.

**Comment by natefinch** [comment]
Thanks @dt - building from head w/ homebrew fixed my problem as well!
