### ISSUE TITLE
Test at cursor does not work

### ISSUE THREAD

**Issue by cyc115** [Microsoft/vscode-go#987]
> Go 1.8.1
> Go plugin 0.6.61 
> VS code 1.12.1 

Test function at cursor will not work like before, opening up the chrome dev console shows the following error:
```
[Extension Host] TypeError: Cannot read property 'functionName' of undefined
    at getTestFunctions.then.testFunctions (/Users/xjqw46/.vscode/extensions/lukehoban.go-0.6.61/out/src/goTest.js:42:17)
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
 ```

at ExtensionHost.ts:285

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode-go/issues/981#issuecomment-300341146 for workaround.

The fix has been checked in and will be out in the next update which should be in a week or 2
