### ISSUE TITLE
Inconsistent codeLens vs find references

### ISSUE THREAD

**Issue by IzakMarais** [Microsoft/vscode-go#988]
With the following directory structure, I get inconsistent results between VSCodes CodeLens references and VSCode Find References (or running guru from the command line):

_src/example/main.go_:
```golang
package main

import "example2"

func main() {
	_ = example2.Long.Method()    // external references to Method() missed by codeLens
	k := example2.NewKind("test") // (creates missed reference to Kind?)
	_ = k.Method()
	k2 := example2.Kind{"test2"}
	_ = k2.Method()
}
```
_src/example2/example2.go_:
```golang
package example2

// 0 references <- Wrong
func (k Kind) Method() *string {
	str := "example2"
	return &str
}
// 5 references <- Wrong? (misses k from main.go?)
type Kind struct {
	Param string
}

var (
	Long = Kind{"puttups"}
)

// 1 reference <- Wrong
func NewKind(s string) Kind { return Kind{s} }

```
Screenshots of the inconsistencies. Notice how the codeLens and find references values differ. 
![image](https://cloud.githubusercontent.com/assets/8266640/25934813/3456ad1a-3620-11e7-8b26-66a697f9fcbd.png)

![image](https://cloud.githubusercontent.com/assets/8266640/25934761/f9fa868c-361f-11e7-8082-ce684c992b42.png)

![image](https://cloud.githubusercontent.com/assets/8266640/25935062/70964186-3621-11e7-9e28-c7adf3c21ba6.png)

Finally (this is more a guru question than a VSCode question), is it expected for guru to miss the references to the `Kind` struct created via NewKind()? Or is this not considered a 'referene to Kind'? E.g. is `k` not a reference to type `Kind`?

**Comment by IzakMarais** [comment]
Also, is there an easy way to use VSCode to determine the byte offset of a symbol? It would help to debug issues like this using the command line tools. I'm counting number of characters from the start of the file by hand.

**Comment by IzakMarais** [comment]
This looks like a duplicate of #977 and #962 . Perhaps the minimal example will help reproduce it #977 ? I'm on Windows.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @IzakMarais and sorry for not getting back to you sooner.

I observed similar mismatch early on too. See https://github.com/Microsoft/vscode-go/issues/726#issuecomment-294557826

Somehow references from outside the current workspace are getting included in the codelens.
Is that your case as well?

Funny enough both the codelens and the "Find all References" features use the same `guru` tool. So its weird that they find different counts.

This needs some investigation.

@theSoenke can you take a look at this?

**Comment by IzakMarais** [comment]
> Somehow references from outside the current workspace are getting included in the codelens.
Is that your case as well?

No, as the screenshots demonstrate, codelens shows fewer references than _find all references_, not more.

**Comment by ramya-rao-a** [comment]
Your first case of 0 references is being tracked in #962

In your second case, if you click on the codelens, you will see 5 references. `k2` from main.go is being counted. What is not being counted is the definition of Kind. When you do a "Find all references", the definition is also counted, where as the definition is not counted in the codelens

That is by design.

The third case is same as the second.

As for the byte offset question, I am not aware of any way myself, but yes, that would indeed be very handy.
