### ISSUE TITLE
Go to definition doesn't work on the package in the import statement

### ISSUE THREAD

**Issue by last911** [Microsoft/vscode-go#989]
go1.8.1
vscode 1.21.1
vscode-go 0.6.61
godoc + godef

![wechatimg279](https://cloud.githubusercontent.com/assets/4099143/25988590/2670e20e-372b-11e7-8de4-29df208edc63.jpeg)

**Comment by jackie-qiu** [comment]
Same issue for me

**Comment by xxxtonixxx** [comment]
I have the same problem using vscode 1.13.0-insider and go 1.8.1 linux/amd64

**Comment by ramya-rao-a** [comment]
@last911 What are you settings for `go.docsTool` and `go.useLanguageServer` ?

**Comment by ramya-rao-a** [comment]
From the screenshot, it looks like you are trying to go to definition feature on the import statement.

This is not supported at the moment and has nothing to do with vendor packages.

This feature request is being tracked in #330
