### ISSUE TITLE
Inconsistent syntax highlighting for multiple assignment to fields

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode-go#992]
See the attached image:

<img width="519" alt="screen shot 2017-05-11 at 11 46 04 am" src="https://cloud.githubusercontent.com/assets/63830/25976180/1254e39c-3668-11e7-9845-762829e5809c.png">

The FieldsSplit field is colored differently than the other fields in the assignment.

**Comment by ramya-rao-a** [comment]
In the above case `FieldsSplit` gets the scope `variable.other.assignment.go` and rest of the words before it get `source.go`

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#128

**Comment by ramya-rao-a** [comment]
This is fixed in the latest VS Code Insiders build
