### ISSUE TITLE
Ignore linter output on generated files

### ISSUE THREAD

**Issue by fortytw2** [Microsoft/vscode-go#994]
Per https://github.com/golang/go/issues/13560 it'd be excellent to have the option to ignore all linter output on generated files that match the agreed upon standard here - https://github.com/golang/go/issues/13560#issuecomment-288764366

**Comment by ramya-rao-a** [comment]
I'd prefer to have this option as a flag in the linter tool rather than the editor trying to parse files to find generated files.

Please open this issue in your choice of linting tool, say `golint` or `gometalinter`.
