### ISSUE TITLE
fmt.Scanf("%d", &i) does not debug right

### ISSUE THREAD

**Issue by gideondsouza** [Microsoft/vscode-go#995]
So I'm not entirely sure if this is a problem with vs-code or delve. I've noticed from debugging a few things, like especially a web service the debug console gives me `debugger.go:505: continuing` and just stops.  I know that log output is coming from [this line](https://github.com/derekparker/delve/blob/a843f7944eae7213d256de2a9c14675c1238851a/service/debugger/debugger.go#L505).

No I finally narrowed down a case, this is my code within VS CODE:

```
package main

import (
	"fmt"
)

func main() {
	fmt.Print("Enter NUM: ")
	var i int
	fmt.Scanf("%d", &i)
	fmt.Print(i)
}
```
I hit F5 and I get this in the debug console : 

```
2017/05/14 11:38:20 server.go:73: Using API v1
2017/05/14 11:38:20 debugger.go:97: launching process with args: [/home/gideon/Coding/golang/play/debug]
API server listening at: 127.0.0.1:2345
2017/05/14 11:38:20 debugger.go:505: continuing
Enter NUM: 0
```

Is this a problem with the vs-code extension or delve or both?

I have vscode-go version `0.6.61`  go version go version go1.8 other version info is:
**VS CODE: **
Version 1.12.1
Commit f6868fce3eeb16663840eb82123369dec6077a9b
Date 2017-05-04T21:40:39.245Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

I'm on Fedora 25.

**Comment by ramya-rao-a** [comment]
`fmt.Scanf` reads text from std input. So from what I can understand, unless there is an input the program cannot move forward.

What is your expectation here?

**Comment by gideondsouza** [comment]
> What is your expectation here? 
Being able to put in an input in the debug console somehow.

I played with delve itself and see that this is actually how delve behaves so I'm guessing that some way to interact with a scanf like call would have to be implemented inside delve.

Oh well.
