### ISSUE TITLE
Replace installation pop up for every tool with a better user experience

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#998]
Currently, if user doesn't have the necessary Go tools installed, there is a pop up reminding the user to do the same when the extension performs an action that needs the Go tool.

This is not much of a problem in certain scenarios where user explicitly executes a command like
- Find all references (`guru`)
- Rename (`gorename`)
- Add/delete tags (`gomodifytags`)
- Generate test (`gotests`)
- Find symbol in file (`go-outline`)
- Find symbol in workspace (`gosymbols`)
- Add import (`gopkgs`)

But simple actions like hover, typing, saving a file should not result in intrusive pop-ups.
Example below:

- On hover, pop up for `godef` or `gogetdoc` based on the user preference for `go.toolDocs`
- On save, pop up for `golint` or `gometalinter` based on the user preference for `go.lintTool` when `go.lintOnSave` is `true`
- On save, pop up for `goreturns`, `goimports` or `gofmt` based on the user preference for `go.formatTool` when `go.formatOnSave` is `true`
- On typing, pop up for `gocode`

This issue is to track a better user experience

**Comment by atedja** [comment]
This is very annoying and I have been searching in the settings how to disable these extensions. Maybe a "Disable" button?

**Comment by ramya-rao-a** [comment]
In the latest update (0.6.63) to the Go extension, below are the improvements made

- Prompts will only show up for tools that are used for features that are explicitly executed by the user. Eg: Rename, Generate Unit Tests, Modify tags. And not for features that get triggered behind the scenes like linting, hover or format on save.
- When the prompts do show up, closing them will ensure that they wont show up for the duration of the current session of VS Code.
